### ISSUE TITLE
H2DatabaseTestResource does not work in native mode

### ISSUE THREAD

**Issue by Nunalves** [quarkusio/quarkus#3973] opened 2019-09-11 17:45 UTC
**Describe the bug**
I use the H2DatabaseTestResource like described here:
https://stackoverflow.com/questions/55063778/how-can-use-an-in-memory-h2-database-when-testing-my-quarkus-application

I simply persist some data with a PanacheEntity for the test to retrieve that data.
Here is a simple reproducer project:
[quarkus-h2-test.zip](https://github.com/quarkusio/quarkus/files/3602048/quarkus-h2-test.zip)

But on native tests (@SubstrateTest) this does not work throwing a NullPointerException.

**Expected behavior**
H2DatabaseTestResource working both @QuarkusTest and @SubstrateTest annotated tests.

**Actual behavior**
On native tests it does not work throwing a `java.lang.NullPointerException` without any extra information.

**To Reproduce**
1. download [quarkus-h2-test.zip](https://github.com/quarkusio/quarkus/files/3602048/quarkus-h2-test.zip)
2. unzip and import the maven project on your IDE
3. run
```bash
mvn verify -P native
```

You won't need postgres to reproduce the problem as the tests don't use it, but if you want to run the reproducer application you can use:
```
docker run --name test-postgres -p 9999:5432 -e POSTGRES_DB=test -e POSTGRES_USER=test -e POSTGRES_PASSWORD=test -d postgres
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux MTS-LPT-22P3V 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

 - Output of `java -version`: 
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

 - GraalVM version (if different from Java): 
graalvm-ce-19.0.2
 - Quarkus version or git rev: 
0.21.2

**Additional context**
Zulip discussion:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Integration.20testing.20with.20H2

**Comment by geoand** [comment] 2019-09-11 18:41
Actually I think this is expected, right @gsmet?

**Comment by hantsy** [comment] 2019-09-14 10:35
Same here, tests failed when used native profile.

**Comment by geoand** [comment] 2019-09-14 10:36
I think that is expected, but would like to hear more from others

**Comment by hantsy** [comment] 2019-09-14 12:08
But I can not disable H2 in native test. 
It requires extra DataSource configuration in *src/test/resources/application.properties*. Even I disabled all tests, it still tried to connect to H2 when run tests.

**Comment by gsmet** [comment] 2019-10-01 14:47
Hi Nuno,

I had a look at your issue: the problem is that the native image is built with the `src/main/java/application.properties`, not the test one, thus it tries to connect to the PostgreSQL instance.

The native image is entirely built in `prod` mode, so in your case it will be hard to do what you did.

A possibility would be to set up a PostgreSQL docker container when running the tests.

We had a discussion recently about that on the mailing list: https://groups.google.com/forum/#!topic/quarkus-dev/RJ3dWAOV38o , feel free to weigh in.

-- 
Guillaume

**Comment by Nunalves** [comment] 2019-10-02 08:56
Hi @gsmet,

Thanks for digging into this. That is exactly what i suspected.

We were already using a PostgreSQL docker container as a workaround. I guess the workaround will become the definitive solution.

Thanks :)

**Comment by gsmet** [comment] 2019-11-18 23:11
Closing this as the question about the native image profile is there: https://github.com/quarkusio/quarkus/issues/4371 .

**Closed by gsmet** 2019-11-18 23:11 UTC
Labels: bug
