### ISSUE TITLE
No Converter registered for interface java.util.Map

### ISSUE THREAD

**Issue by ecmrauh** [quarkusio/quarkus#8017] opened 2020-03-20 11:44 UTC
**Describe the bug**
I don't know if it is a bug or a missing feature (or just my fault). I try to use a Map<String, String> as configuration value. I created a custom converter as described [here](https://quarkus.io/guides/config#custom-configuration-converters). The example with the int works, using a Map fails.

**Expected behavior**
It should possible to use a Map as configuration value.

**Actual behavior**
An exception is thrown (java.lang.IllegalArgumentException: No Converter registered for interface java.util.Map).

But the converter is present and it is used with e.g. ints and doubles.

**To Reproduce**
1. Setup a minimal example like [this one](https://quarkus.io/guides/config#custom-configuration-converters) and change int to Map<String, String>.
2. Inject the config and try to use the value.

**Configuration**

My final goal is to use something like:

```properties

config.global.setting = value
config.tenant-map.param1 = xxx
config.tenant-map.param1 = yyy

```

**Environment (please complete the following information):**
 - Output of `uname -a`: 
Linux debian 5.4.0-0.bpo.3-amd64 #1 SMP Debian 5.4.13-1~bpo10+1 (2020-02-07) x86_64 GNU/Linux

 - Output of `java -version`: 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1deb10u1, mixed mode, sharing)

 - Quarkus version: 1.2.1-Final and 1.3.0-Final

 - Build tool (`mvn --version`):
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.6, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-0.bpo.3-amd64", arch: "amd64", family: "unix"

**Additional context**

The example descriped [here](https://github.com/quarkusio/quarkus/issues/4656) works, but changing Double to Map<String, String> fails.

This issue might be similar to #7856.

**Comment by geoand** [comment] 2020-03-20 11:46
I think this is by design, but I am not 100% sure, so let's ask the expert @dmlloyd

**Comment by dmlloyd** [comment] 2020-03-20 12:07
You're essentially hitting two different problems here.  One is that MicroProfile Config does not support generic converter types; Map is a generic type, having two type parameters.  The other is that converters only apply to single string values - they cannot be used to aggregate values from multiple properties without special support from the runtime.

**Comment by geoand** [comment] 2020-03-20 13:21
I'm going to close this as invalid. Feel free to reopen if you feel it's not been adequately covered

**Comment by ecmrauh** [comment] 2020-03-20 13:22
Thanks for your quick response! I wasn't aware of that. After reading issues [like e.g. this one](https://github.com/quarkusio/quarkus/issues/1415), I thought it would be possible somehow. If not, I will have to live with that... :confused:

**Closed by geoand** 2020-03-20 13:21 UTC
Labels: area/config, kind/bug

**Comment by dmlloyd** [comment] 2020-03-20 13:37
We have special support for it within our Quarkus configuration code, which is separate from the standard CDI-based stuff.  Really I think the MP Config spec needs a bit of a rethink in this area though.  My first step in this direction is eclipse/microprofile-config#545.

**Comment by ecmrauh** [comment] 2020-03-20 13:44
Thanks for the clarification and your efforts!!
