### ISSUE TITLE
DataSource properties are not taking priority when using TestContainer

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#8342] opened 2020-04-02 06:46 UTC
**Describe the bug**

DataSource properties are not taking priority when they are returned from TestContainer in form of Map

When using TestContainers with more than one driver in the classpath, and you want to use one specific for the test, driver or dialect properties are ignored.

**Expected behavior**

Properties returned needs to be supported.

**Actual behavior**

An exception

**To Reproduce**

Clone https://github.com/lordofthejars/quarked-test/tree/plain notice that this is a tagged version, and run https://github.com/lordofthejars/quarked-test/blob/plain/src/test/java/org/acme/CheckoutProcessIntegrationTest.java

In my case I have H2 and MariaDB drivers in classpath as I want to run "unit" tests and some integration tests.

The log output is:

```
HH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusH2Dialect
Apr 02, 2020 8:33:21 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.1.Final
Apr 02, 2020 8:33:21 AM org.hibernate.resource.beans.spi.ManagedBeanRegistryInitiator resolveBeanContainer
INFO: HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.
Apr 02, 2020 8:33:21 AM org.hibernate.tuple.entity.EntityMetamodel <init>
INFO: HHH000157: Lazy property fetching available for: org.acme.ShoppingBasket
Apr 02, 2020 8:33:22 AM io.quarkus.agroal.runtime.AgroalEventLoggingListener onWarning
WARN: Datasource '<default>': Driver does not support the provided URL: jdbc:mariadb://localhost:32771/test
```

Notice that URL is updated but not the dialects or driver.

https://github.com/lordofthejars/quarked-test/blob/plain/src/test/java/org/acme/InfrastructureTestResource.java

**Environment (please complete the following information):**

Quarkus 1.3.1

**Comment by geoand** [comment] 2020-04-02 08:33
@lordofthejars I think that in `master` you won't have the same problem.

**Comment by lordofthejars** [comment] 2020-04-02 08:41
No worries, for this evening talk I am just creating a different module, so different classpath.

**Comment by geoand** [comment] 2020-04-02 09:09
Although I absolutely understand what you are trying to do and I can see why you would think it would work, unfortunately it does not for the following reason:

```
quarkus.datasource.driver=org.h2.Driver
```

is a build time property which means that you can't change it by setting it in your `InfrastructureTestResource`.
So essentially what is happening is that the test is being built with  `quarkus.datasource.driver=org.h2.Driver` while the that the running application is using is getting configured from your `InfrastructureTestResource` and of course the two don't match.

So I don't really think this is a bug and I personally think it should be closed. Thoughts @Sanne @gsmet ?

**Comment by lordofthejars** [comment] 2020-04-02 09:12
Well ok not a bug then but still a valid use case. If not we should start promoting to users to create multi test module to avoid having these problems.

**Comment by geoand** [comment] 2020-04-02 09:14
I don't think you need multiple modules for this use case. Just a proper setup of maven filtering or maven profiles.

**Comment by lordofthejars** [comment] 2020-04-02 09:14
Ok so you mean that URL is not a  build config, but driver is? Because the URL can be overriden.

**Comment by geoand** [comment] 2020-04-02 09:16
Yes exactly, `quarkus.datasource.url` is a runtime property.
`quarkus.datasource.driver` is a build time property.

**Comment by gsmet** [comment] 2020-04-02 13:36
Yup, that's how things are. The driver needs to be a build time property.

**Comment by geoand** [comment] 2020-04-02 13:38
I'll close this since it's not a bug.

**Closed by geoand** 2020-04-02 13:38 UTC
Labels: kind/bug
