### ISSUE TITLE
Native build failed due to UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.PanacheEntityBase.count()

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#6396] opened 2020-01-03 17:33 UTC
This is with Quarkus 1.1.

```
[INFO] --- quarkus-maven-plugin:1.1.0.Final:build (default) @ quarkus-qute ---
[WARNING] [io.quarkus.creator.curator.Curator] These dependencies are not recommended:
	- jakarta.xml.bind:jakarta.xml.bind-api should be replaced by org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec
You might end up with two different versions of the same classes or with an artifact you shouldn't have in your classpath.
[INFO] [org.jboss.threads] JBoss Threads version 3.0.0.Final
[INFO] [org.hibernate.jpa.boot.internal.PersistenceXmlParser] HHH000318: Could not find any META-INF/persistence.xml file in the classpath
[INFO] [org.hibernate.Version] HHH000412: Hibernate Core {5.4.10.Final}
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building native image source jar: /Users/gunnar/Development/quarkus/quarkus-qute/target/quarkus-qute-1.0.0-SNAPSHOT-native-image-source-jar/quarkus-qute-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Building native image from /Users/gunnar/Development/quarkus/quarkus-qute/target/quarkus-qute-1.0.0-SNAPSHOT-native-image-source-jar/quarkus-qute-1.0.0-SNAPSHOT-runner.jar
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.2.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/gunnar/Development/quarkus/quarkus-qute/target/quarkus-qute-1.0.0-SNAPSHOT-native-image-source-jar:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.2.1 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -H:ResourceConfigurationFiles=resources-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar quarkus-qute-1.0.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace quarkus-qute-1.0.0-SNAPSHOT-runner
[quarkus-qute-1.0.0-SNAPSHOT-runner:19]    classlist:  45,459.72 ms
[quarkus-qute-1.0.0-SNAPSHOT-runner:19]        (cap):   2,092.14 ms
[quarkus-qute-1.0.0-SNAPSHOT-runner:19]        setup:   5,360.36 ms
17:28:11,883 INFO  [org.hib.Version] HHH000412: Hibernate Core {5.4.10.Final}
17:28:11,998 INFO  [org.hib.ann.com.Version] HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
17:28:12,103 INFO  [org.hib.dia.Dialect] HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusPostgreSQL95Dialect
17:28:14,836 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Final
[quarkus-qute-1.0.0-SNAPSHOT-runner:19]     analysis: 137,334.02 ms
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.PanacheEntityBase.count(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:109)
Call path from entry point to io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(EvalContext):
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:68)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:92)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolve$2(EvaluatorImpl.java:94)
	at io.quarkus.qute.EvaluatorImpl$$Lambda$1141/525500644.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

com.oracle.svm.core.util.UserError$UserException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.PanacheEntityBase.count(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:109)
Call path from entry point to io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(EvalContext):
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:68)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:92)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolve$2(EvaluatorImpl.java:94)
	at io.quarkus.qute.EvaluatorImpl$$Lambda$1141/525500644.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.svm.core.util.UserError.abort(UserError.java:75)
	at com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:223)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:737)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:526)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.PanacheEntityBase.count(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Detailed message:
Trace:
	at parsing io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:109)
Call path from entry point to io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(EvalContext):
	at io.quarkus.hibernate.orm.panache.PanacheEntityBase_ValueResolver.resolve(PanacheEntityBase_ValueResolver.zig:68)
	at io.quarkus.qute.EvaluatorImpl.resolve(EvaluatorImpl.java:92)
	at io.quarkus.qute.EvaluatorImpl.lambda$resolve$2(EvaluatorImpl.java:94)
	at io.quarkus.qute.EvaluatorImpl$$Lambda$1141/525500644.apply(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:966)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:940)
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:456)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:144)
	at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:89)
	at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:143)
	at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:186)
	at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)

	at com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:130)
	at com.oracle.graal.pointsto.BigBang.finish(BigBang.java:565)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:688)
	... 7 more
Caused by: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.PanacheEntityBase.count(). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.reportUnresolvedElement(SharedGraphBuilderPhase.java:238)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedMethod(SharedGraphBuilderPhase.java:228)
	at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.handleUnresolvedInvoke(SharedGraphBuilderPhase.java:182)
	at org.graalvm.compiler.java.BytecodeParser.genInvokeVirtual(BytecodeParser.java:1612)
	at org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5123)
	at org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3267)
	at org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3074)
	at org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:976)
	at org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:870)
	at org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
	at org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:197)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:221)
	at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:340)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.doParse(MethodTypeFlow.java:310)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureParsed(MethodTypeFlow.java:300)
	at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:107)
	at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:191)
	at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:343)
	at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:385)
	at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:510)
	at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:171)
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1402)
	... 4 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  05:27 min
[INFO] Finished at: 2020-01-03T18:30:30+01:00
[INFO] ------------------------------------------------------------------------
```

**Comment by gunnarmorling** [comment] 2020-01-03 17:34
Hey @gsmet, does this ring a bell by any chance?

**Comment by gsmet** [comment] 2020-01-03 17:36
Nope. A reproducer would help. /cc @FroMage

**Comment by gunnarmorling** [comment] 2020-01-03 17:38
A reproducer is here: https://github.com/gunnarmorling/quarkus-qute (not minimal, but not huge either). I got this when running

    ./mvnw package -DskipTests=true -Pnative -Dquarkus.native.container-build=true

**Comment by gunnarmorling** [comment] 2020-01-03 17:43
Note I'm not invoking this method `count()` at all. Only thing vaguely related is that I call `size()` on a result list returned by Panache in one of the templates (todos.html). But I don't quite understand what this error is about.

**Comment by FroMage** [comment] 2020-01-06 15:10
I guess this is due to the `count` method not being registered for reflection by Qute, right @mkouba ?

**Comment by FroMage** [comment] 2020-01-06 15:12
Ah no this isn't reflection. I wonder what the method call looks like in `PanacheEntityBase_ValueResolver.resolve` because this is a static method and it won't work if called directly. Not that this should be able to cause this issue since it's not actually calling it.

**Comment by mkouba** [comment] 2020-01-06 15:34
I'll take a look tomorrow.

**Comment by FroMage** [comment] 2020-01-08 14:28
Famous Last Words™

**Comment by mkouba** [comment] 2020-01-08 16:16
@FroMage progress made: assigned to myself ;-)

**Comment by FroMage** [comment] 2020-01-08 16:31
:tada:

**Comment by mkouba** [comment] 2020-01-16 08:04
Ok. So we generate a value resolver for `PanacheEntityBase` because there is a [param declaration](https://github.com/gunnarmorling/quarkus-qute/blob/master/src/main/resources/templates/todo.html#L1) in `todo.html` which binds `dev.morling.demos.quarkus.Todo` -> value resolver is generated automatically for the class and all subclasses. However, there is a bug in the generator - we don't skip static methods even though it's stated in the docs ;-).

I'll send a PR shortly.

**Closed** 2020-01-20 07:45 UTC
Labels: area/panache, kind/bug
