### ISSUE TITLE
Ctrl+C does not kill the Docker build when running with -Dquarkus.native.container-runtime=docker

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2282] opened 2019-04-29 18:34 UTC
In https://quarkus.io/guides/building-native-image-guide it says that you can build the native image using Docker with `-Dquarkus.native.container-runtime=docker`, however Ctrl +C doesn't kill the docker process.

**Comment by gsmet** [comment] 2019-11-13 21:15
@gastaldi is it still an issue?

**Comment by gastaldi** [comment] 2019-11-14 01:05
@gsmet unfortunately yes. I updated the description to the new option names

**Comment by yrodiere** [comment] 2021-05-18 16:58
Correct me if I'm wrong, but I believe the problem lies in how we're using a `Process` to run `docker` (in `io.quarkus.deployment.pkg.steps.NativeImageBuildRunner#build` and probably others). Basically we spawn a process, but we don't kill it when the JVM forcibly shuts down (i.e. when we receive SIGINT).

I think adding a JVM shutdown hook every time we spawn a new process could do the trick? E.g. `Runtime.getRuntime().addShutdownHook(...)`.

**Comment by geoand** [comment] 2021-07-29 05:39
This was fixed by https://github.com/quarkusio/quarkus/pull/19060 and the issue is actually a duplicate of https://github.com/quarkusio/quarkus/issues/7331

**Closed by geoand** 2021-07-29 05:39 UTC

**Comment by geoand** [comment] 2021-07-29 05:40
> Correct me if I'm wrong, but I believe the problem lies in how we're using a `Process` to run `docker` (in `io.quarkus.deployment.pkg.steps.NativeImageBuildRunner#build` and probably others). Basically we spawn a process, but we don't kill it when the JVM forcibly shuts down (i.e. when we receive SIGINT).
> 
> I think adding a JVM shutdown hook every time we spawn a new process could do the trick? E.g. `Runtime.getRuntime().addShutdownHook(...)`.

Close, but it's a little more complicated. Even if the JVM process dies, the docker build still runs because as a sort of daemon. As the PR that fixes the issue shows, we just needed to execute the proper `docker rm -f ...` command
