### ISSUE TITLE
Bug/OpenTelemetry extension - unexpected exceptions are not recorded on the span

### ISSUE THREAD

**Issue by arik-dig** [quarkusio/quarkus#30462] opened 2023-01-19 07:57 UTC
### Describe the bug

My sample application throws an unexpected exception, and I would expect that the current span would contain an event of `exception` and that attributes of 'exception.message` and/or `exception.stacktrace` would be filled.
see [OTEL Semantic conventions of Exceptions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/exceptions.md#attributes)

### Expected behavior

whenever there's an unexpected exception, the OTEL extension should catch it log event of `exception` and fill span attributes `exception.message` and/or `exception.stacktrace`

### Actual behavior

the span does not contain event of `exception` and attributes `exception.message` and/or `exception.stacktrace` are not being filled

### How to Reproduce?

I used [Quick start of Vertx](https://github.com/quarkusio/quarkus-quickstarts/tree/main/vertx-quickstart) and added to it the following class file

```java
package org.acme;

import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.StatusCode;
import io.smallrye.mutiny.Uni;
import io.vertx.mutiny.core.Vertx;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import java.io.IOException;

@Path("/err")
public class ErrResource {

    private final Vertx vertx;

    ErrResource(Vertx vertx) { // <2>
        this.vertx = vertx;
    }

    @GET
    @Path("/genException01")
    public Uni<String> genExc01() {
        throw new RuntimeException("exception 01");
    }

    @GET
    @Path("/genFailure01")
    public Uni<String> genFail01() {
        return Uni.createFrom().failure(new IOException("fail01"));
    }

    @GET
    @Path("/genRecordException")
    public Uni<String> genInternalRecordException() {
        Span currSpan = Span.current();
        currSpan.recordException(new RuntimeException("Got recorded?"));
        currSpan.setStatus(StatusCode.ERROR);
        return Uni.createFrom().item("exception should been recorded");
    }

}
```

* Repro 1 - accessing /err/genFailure01

see details at https://github.com/quarkusio/quarkus/issues/30462#issuecomment-1396577651

* Repro 2 - accessing /err/genException01

see details at https://github.com/quarkusio/quarkus/issues/30462#issuecomment-1396581548

* Manual recording of exception - accessing /err/genRecordException

see details at https://github.com/quarkusio/quarkus/issues/30462#issuecomment-1396588707

it works as excepted but it means that every user has to do it manually - not ideal.
**I think that should be the case when unexpected exception is catched within the framework.**

### Output of `uname -a` or `ver`

windows 11

### Output of `java -version`

java 17.0.5 2022-10-18 LTS

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by arik-dig** [comment] 2023-01-19 08:01
### Repro - accessing /err/genFailure01

Jaeger shows the following
![image](https://user-images.githubusercontent.com/104715391/213386771-5c710bdd-3961-419f-aa69-2bb859edad35.png)

dump of trace:
[genFailure01-a583545ac5a62bc5ce241c51cf742561.json.txt](https://github.com/quarkusio/quarkus/files/10454664/genFailure01-a583545ac5a62bc5ce241c51cf742561.json.txt)

**Comment by arik-dig** [comment] 2023-01-19 08:04
### Repro 1 - accessing /err/genException01

Jaeger shows the following:

![image](https://user-images.githubusercontent.com/104715391/213387171-0ddc0f65-a095-4b5a-9584-4a7f5f18c16e.png)

dump of trace:
[genException01-be9e6181912e5e2032617236dac04787.json.txt](https://github.com/quarkusio/quarkus/files/10454689/genException01-be9e6181912e5e2032617236dac04787.json.txt)

**Comment by arik-dig** [comment] 2023-01-19 08:11
### Manual recording of exception - accessing /err/genRecordException

when doing a manual record of exception it works as expected, I think that should be the case when unexpected exception is catched within the framework.

Jaeger shows the following:

![image](https://user-images.githubusercontent.com/104715391/213388283-cfa879b1-59a4-4dd2-8c36-572069ef5cfb.png)

dump of trace:
[genRecordException-d36f7fbbcf3c63c6fb0cb4133ca1e1d1.json.txt](https://github.com/quarkusio/quarkus/files/10454746/genRecordException-d36f7fbbcf3c63c6fb0cb4133ca1e1d1.json.txt)

**Comment by brunobat** [comment] 2023-01-19 15:52
Hey @arik-dig ,
Yes, there are some places were is very tricky to get the stack trace. 
I think we have some related issues as well.

**Comment by brunobat** [comment] 2023-01-19 17:00
For now in needs to go to the queue until there's bandwidth for it, sorry

**Comment by arik-dig** [comment] 2023-06-23 09:48
gentle reminder, is there a plan to solve it?

**Comment by brunobat** [comment] 2023-06-25 21:56
Yes, this will be fixed.

**Comment by geoand** [comment] 2023-07-04 09:00
@brunobat I am correct in assuming that currently OpenTelemetry is integrated with pure Vert.x and not RESTEasy Reactive at all?

Asking because it seems to me that none of the exceptions thrown in a JAX-RS method will ever result in the recording of the stacktrace. Correct?

**Comment by geoand** [comment] 2023-07-04 09:04
If so, I think this is a duplicate of #27384 which better captures the problem and therefore this issue should be closed in favor of that one.

**Comment by brunobat** [comment] 2023-07-04 09:26
@geoand there is integration with  [Vert.x](https://github.com/quarkusio/quarkus/blob/f92ac9ac3748efda36fcae2c316f2cd8a222777e/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/vertx/InstrumenterVertxTracer.java#L53) and RESTEasy Reactive, and errors are reported if happen in the scope of the [WithSpanInterceptor](https://github.com/quarkusio/quarkus/commit/e723c0b760cbed5d1be2d65106276f839001734c#diff-14c3d405dab89de77925838eef5dfecb08f079e4797475b6644bbaaed64ad723R75).
The problem is that all the exception throwing points might not be covered. Some because they are not being catch and some because they might happen before a route can be determined.

**Comment by geoand** [comment] 2023-07-04 09:27
> RESTEasy Reactive

Where is this integration? I have not found it (probably not looking in the right location)

**Comment by geoand** [comment] 2023-07-04 09:28
> The problem is that all the exception throwing points might not be covered. Some because they are not being catch and some because they might happen before a route can be determined

Right, that's why I think https://github.com/quarkusio/quarkus/issues/27384 is the proper issue and this one only a subcase of it and should be closed in favor of the former.

**Comment by brunobat** [comment] 2023-07-04 09:41
> > RESTEasy Reactive
> 
> Where is this integration? I have not found it (probably not looking in the right location)

Resteasy reactive tracing is handled by vert.x. See this comment: https://github.com/quarkusio/quarkus/blob/f92ac9ac3748efda36fcae2c316f2cd8a222777e/extensions/opentelemetry/runtime/src/main/java/io/quarkus/opentelemetry/runtime/tracing/intrumentation/restclient/OpenTelemetryClientFilter.java#L37

**Comment by geoand** [comment] 2023-07-04 09:49
`OpenTelemetryClientFilter` is for the JAX-RS Client though...

Did you mean `OpenTelemetryReactiveServerFilter`?

**Comment by brunobat** [comment] 2023-07-04 09:56
> `OpenTelemetryClientFilter` is for the JAX-RS Client though...
> 
> Did you mean `OpenTelemetryReactiveServerFilter`?

That's just setting attributes on resteasy reactive spans.

**Comment by geoand** [comment] 2023-07-04 09:59
Right, that's why I am asking if there is anything else RESTEasy Reactive (Server) specific or is the integration handles at Vert.x level?
Asking, because if it's the latter, there is no way to get the exception that occurred in a JAX-RS method.

**Comment by radcortez** [comment] 2023-07-04 10:07
RESTEasy Reactive Server is handled by the Vert.x Tracer. The `OpenTelemetryReactiveServerFilter` is only used to pass some attributes.

The OTel Context and trace should be active if an exception happens on the JAX-RS side. I guess an ExceptionMapper should be able to record some of the exceptions. The issue is exceptions caught in the extension code that may not have a way to intercept, and we don't want to pollute the code with OTel callbacks.

**Comment by geoand** [comment] 2023-07-04 10:09
I am asking because I likely can make a special integration point that will execute before the exception mapper and set whatever OTel field needs to be set.

I assume that it would be  `LocalRootSpan.current().recordException()` , correct?

**Comment by radcortez** [comment] 2023-07-04 10:34
Hum... it should either be `Span.current()` or if it is not available, retrieve the context first from `QuarkusContextStorage`. I see that `OpenTelemetryReactiveServerFilter` is using `LocalRootSpan`, but I think it shouldn't be using that.

**Comment by radcortez** [comment] 2023-07-04 10:43
There is no way to intercept the exception mapper or just chain our own mapper to users, right? In that case, yes then we need a point that we can call just before the mapper is executed.

**Comment by geoand** [comment] 2023-07-04 10:44
> There is no way to intercept the exception mapper or just chain our own mapper to users, right?

Correct, the spec does not provide for such an integration point

**Comment by radcortez** [comment] 2023-07-04 10:50
Thanks!

**Comment by geoand** [comment] 2023-07-04 10:57
Thank me when it's done 😆

**Comment by geoand** [comment] 2023-07-04 13:31
[Here](https://github.com/quarkusio/quarkus/pull/34521) it is.

**Closed** 2023-07-05 11:45 UTC
Labels: kind/bug, area/tracing

**Comment by arik-dig** [comment] 2023-07-06 06:53
@brunobat , @geoand , @gsmet , @radcortez 
thanks for solving it 🙏

**Comment by geoand** [comment] 2023-07-06 07:11
💪🏼
