### ISSUE TITLE
quarkus.datasource.devservices.port ignored during dockerized @QuarkusIntegrationTest

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#26192] opened 2022-06-16 17:06 UTC
### Describe the bug

When starting a `@QuarkusIntegrationTest` with `quarkus.container-image.build=true` and a dev service datasource, the property `quarkus.datasource.devservices.port` is ignored.

### Expected behavior

When `quarkus.datasource.devservices.port=5432` is set in  application.properties, the db container should map to exposed port 5432.

### Actual behavior

When `quarkus.datasource.devservices.port=5432` is set in application.properties, the db container still maps to a random port

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22000 ******* 3.3.4-341.x86_64 2022-05-09 11:56 UTC x86_64 Msys

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 LTS

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.4.2

**Comment by geoand** [comment] 2022-06-17 08:09
I could not reproduce this, when I tried it the `5432` was used for all tests.

Here is how Quarkus was launching the container:

```
"docker run --name quarkus-integration-test-MUNVY --rm -p 8081:8081 -p 8444:8444 --net=bf860611fd236ff0c26c790745a793b0c4f48bf2e4fefad6d834974462949e70 --env QUARKUS_HTTP_PORT=8081 --env QUARKUS_HTTP_SSL_PORT=8444 --env TEST_URL=http://localhost:8081 --env QUARKUS_DATASOURCE_PASSWORD=quarkus --env QUARKUS_DATASOURCE_DB_KIND=postgresql --env QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://postgres-7eSkV:5432/default?loggerLevel=OFF --env QUARKUS_DATASOURCE_USERNAME=quarkus --env QUARKUS_DATASOURCE_DEVSERVICES_PORT=5432 gandrian/hibernate-orm-quickstart:1.0.0-SNAPSHO
```

Are you sure the port is being ignored?

**Comment by geoand** [comment] 2022-09-01 07:39
Closing this as never got feedback.

**Closed by geoand** 2022-09-01 07:39 UTC
Labels: kind/bug, area/testing, area/devservices
