### ISSUE TITLE
Allow injection of beans created in the `test` suite in `@QuarkusInterationTest`s

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#23529] opened 2022-02-08 21:35 UTC
### Description

 It is quite a handy tool for writing tests to be able to `@Inject` beans established within the `test` source-suite.

It makes sense that internal services, from `main` should not be available to tests running as `@QuarkusIntegrationTest`, but these beans that only use resources created from within the `test` suite should be able to be wired in.

### Implementation ideas

If the utilities that discover beans were flexible enough, we could create a new instance/ set of beans just for the `test` source set, and make that available to `@QuarkusIntegrationTest`s. This is probably wishful thinking though.

Maybe a new set of annotations; `@TestScoped`, `@TestInject`?

**Comment by mkouba** [comment] 2022-02-09 07:58
Hm, the problem is that `src/test/java` becomes part of the tested app. @geoand @aloubyansky correct me if I'm wrong pls.

Anyway, I think that it would be quite error prone and confusing because those _"test-only"_ beans should only inject other _"test-only"_ beans and even if we introduce a new marker annotation e.g. `@TestBean` for such beans, all other beans will be on the classpath.

> It is quite a handy tool for writing tests...

What kind of testing logic would be implemented by those _"test-only"_ beans? I mean isn't it more like "shooting sparrows with cannons"? ;-)

**Comment by geoand** [comment] 2022-02-09 08:10
> Hm, the problem is that `src/test/java` becomes part of the tested app. @geoand @aloubyansky correct me if I'm wrong pls.
> 

Correct

> Anyway, I think that it would be quite error prone and confusing because those _"test-only"_ beans should only inject other _"test-only"_ beans and even if we introduce a new marker annotation e.g. `@TestBean` for such beans, all other beans will be on the classpath.
> 

I completely agree

**Comment by manovotn** [comment] 2022-02-09 13:21
What you describe sounds like a scenario that was commonly solved by adding CDI `@Alternative` beans to the test code which will be used instead of the bean that you have in `main`.

> Anyway, I think that it would be quite error prone and confusing because those "test-only" beans should only inject other "test-only" beans and even if we introduce a new marker annotation e.g. @TestBean for such beans, all other beans will be on the classpath.

I also agree. Quite commonly people need to use most beans from `main` and then mock/override few that should behave differently. Hence the mocking abilities or plain CDI alternatives that exist in Quarkus.

**Comment by mkouba** [comment] 2022-02-09 13:40
> What you describe sounds like a scenario that was commonly solved by adding CDI `@Alternative` beans to the test code which will be used instead of the bean that you have in `main`.

Not really. I think that @GregJohnStewart wants to inject beans defined in the `src/test/java` into a `@QuarkusIntegrationTest` which is currently not possible because the app runs in a separate JVM than the test. We would have to spin up another CDI container for the "test-only" beans which is the confusing part I'm talking about ;-).

**Comment by geoand** [comment] 2022-02-09 13:42
Although I totally understand where this is coming from, however `@QuarkusIntegrationTest` was explicitly designed to do black-box testing of the production application, so this is pretty much antithetical to the original purpose.
For that reason, I'll close this as `Won't fix`.

**Closed by geoand** 2022-02-09 13:42 UTC
Labels: kind/enhancement, area/testing

**Comment by GregJohnStewart** [comment] 2022-02-09 13:52
So the use case for these test-only beans is more to provide some of the utilities to facilitate testing, rather than actually do the testing; the best example I have at the moment is a `TestUserService` that can create new users for the application at will, and provide convenient utilities for persistence and configuration of the new user.

I personally feel that having the convention for these test-only beans could make sense, and having that clear line between main/test beans could end up being helpful. It is already a little handwavey to me to be able to define 'regular' beans in test, and what rammifications if could have. I'm not against having the option to define regular beans, but making the convention to normally set up these test utilities as `@TestScoped` could make it clearer where things should be available, usable, etc.

**Comment by mkouba** [comment] 2022-02-10 07:14
> So the use case for these test-only beans is more to provide some of the utilities to facilitate testing, rather than actually do the testing; the best example I have at the moment is a `TestUserService` that can create new users for the application at will, and provide convenient utilities for persistence and configuration of the new user.

This one would be problematic anyway as it would probably require other services running, i.e. not only CDI but also JPA etc.

**Comment by ayhanap** [comment] 2022-10-06 21:33
To add to possible use cases. I am creating DTOs for test cases then encoding them to json with JsonObject. But because my ObjectMapperCustomizer bean not initialized my json serialization differs with normal tests and ITs. (This was pretty hard to figure out since it was nulls getting serialized causing the validation error and toString not showing json having nulls)
