### ISSUE TITLE
Multithreaded @RestClient injection point fails

### ISSUE THREAD

**Issue by tttomat19** [quarkusio/quarkus#22461] opened 2021-12-21 23:19 UTC
### Describe the bug

Stacktrace is:

    Caused by: java.util.ConcurrentModificationException
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1135)
        at io.quarkus.restclient.config.RestClientsConfig.getClientConfig(RestClientsConfig.java:65)
        at io.quarkus.restclient.runtime.RestClientBase.clientConfigByClassName(RestClientBase.java:331)
        at io.quarkus.restclient.runtime.RestClientBase.configureBaseUrl(RestClientBase.java:286)
        at io.quarkus.restclient.runtime.RestClientBase.create(RestClientBase.java:58)

Code is: 

    @ApplicationScoped
    class MyService {
        @Inject @RestClient MyRestClient myRestClient;

        @Inject
        ManagedExecutor managedExecutor;        

         void callAsync() {
              managedExecutor.runAsync(() -> myRestClient.call());
              managedExecutor.runAsync(() -> myRestClient.call());
         }
    } 

### Expected behavior

No exception is expected.
Actually I'm not sure if it should work. If it should _not_ (as in RFC 2119), can anybody please explain.

### Additional information
The workaround I use is `@Startup` over MyService class for eager bean instantiation.

### Output of `java -version`

openjdk 17, openjdk 11

### Quarkus version or git rev

2.5.2.Final

**Comment by geoand** [comment] 2021-12-22 07:08
This is a duplicate of https://github.com/quarkusio/quarkus/issues/22281 and has already been fixed in https://github.com/quarkusio/quarkus/pull/22286

**Closed by geoand** 2021-12-22 07:08 UTC
Labels: kind/bug, area/arc
