### ISSUE TITLE
More descriptive error message than `java.lang.IllegalArgumentException: Must be a Class or String, got null` when @Produces on a method returning a a non-proxiable bean

### ISSUE THREAD

**Issue by stephenc** [quarkusio/quarkus#2770] opened 2019-06-10 09:53 UTC
**Describe the bug**
I had an application with a dependency on a jar file that had a `@Produces` annotation on a method returning a non-proxiable bean (and nothing was actually consuming this bean)

When the jar file was included in a WAR file using Apache OpenWebBeans, the webapp would start successfully. But when in Quarkus you would get this rather non-specific error message:

```
ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: java.lang.IllegalArgumentException: Must be a Class or String, got null
    at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:137)
    at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:131)
    at io.quarkus.dev.DevModeMain.main(DevModeMain.java:84)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
    [error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: java.lang.IllegalArgumentException: Must be a Class or String, got null
    at io.quarkus.builder.Execution.run(Execution.java:124)
    at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:137)
    at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:108)
    at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:102)
    ... 2 more
Caused by: java.lang.IllegalArgumentException: Must be a Class or String, got null
    at io.quarkus.gizmo.DescriptorUtils.objectToInternalClassName(DescriptorUtils.java:169)
    at io.quarkus.gizmo.MethodDescriptor.ofMethod(MethodDescriptor.java:67)
    at io.quarkus.gizmo.MethodDescriptor.ofConstructor(MethodDescriptor.java:87)
    at io.quarkus.arc.processor.ComponentsProviderGenerator.addBean(ComponentsProviderGenerator.java:239)
    at io.quarkus.arc.processor.ComponentsProviderGenerator.generate(ComponentsProviderGenerator.java:137)
    at io.quarkus.arc.processor.BeanProcessor.process(BeanProcessor.java:217)
    at io.quarkus.arc.deployment.ArcAnnotationProcessor.build(ArcAnnotationProcessor.java:259)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:507)
    at io.quarkus.builder.BuildContext.run(BuildContext.java:414)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
    at java.lang.Thread.run(Thread.java:748)
    at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

Single-stepping the quarkus start-up logic enabled me to identify the root cause and removal of the `@Produces` annotation resulted in the application starting up.

For fun, I added a consumer of the bean to the OpenWebBeans WAR file and it then refused to satisfy the injection because the bean type was non-proxiable.

**Expected behavior**
Either
* `@Produces` annotated methods that are not consumed should be ignored (even if they are for types that cannot be supported by CDI); or
* an error that the method returns a type that cannot be handled using CDI should be reported and that error should identify the offending type and method.

**Actual behavior**
A generic error message is thrown with no identification of the root cause.

**To Reproduce**
1. Add a dependency on https://github.com/jknack/handlebars.java
2. Put `@Produces @ApplicationScope public Handlebars createHandlebars() { return new Handlebars(); }` in your application
3. Boom!

**Configuration**
N/A

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64` 
 - Output of `java -version`: 
    ```
    openjdk version "1.8.0_212"
    OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_212-b03)
    OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.212-b03, mixed mode)
    ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.14.0 and 0.16.0

**Additional context**
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/how.20to.20RCA.20an.20IAE.3A.20Must.20be.20a.20Class.20or.20String.2C.20got.20null

**Comment by stephenc** [comment] 2019-06-10 10:50
Actually turns out that `Handlebars` is proxyable... but still Quarkus doesn't let me instantiate it

**Comment by manovotn** [comment] 2019-06-12 11:04
@mkouba looking into this issue, I think it is fully resolved by your PR here https://github.com/quarkusio/quarkus/pull/2777
The culprit was the method invocation from constructor (usage of delegation thereof), otherwise the object was proxyable and with your PR this now seems to work as intended.
Is there something else you wanted done in this issue?

**Comment by manovotn** [comment] 2019-06-17 09:00
The original problem reported here is now solved via #2777, I'll close this issue.
@stephenc if you find any other problem with this, please reopen the issue.

**Closed by manovotn** 2019-06-17 09:00 UTC
Labels: bug, component:arc

**Comment by jordanglassman** [comment] 2019-09-16 18:07
Still occuring for me using 0.20.0.

As a workaround, I can simply `@Inject` the bean that's produced but not used, and ignore it.

The error message remains unhelpful, but google brought me here.

**Comment by stephenc** [comment] 2019-09-16 18:14
@jordanglassman hit me up on our internal slack tomorrow... 😂

**Comment by mkouba** [comment] 2019-09-16 18:20
> Still occuring for me using 0.20.0.

Feel free to create a new issue.

> As a workaround, I can simply @Inject the bean that's produced but not used, and ignore it.

I'm afraid I don't understand. Could you share a minimal reproducer code?

> The error message remains unhelpful...

What error message do you get?

**Comment by jordanglassman** [comment] 2019-09-16 18:55
Done:  https://github.com/quarkusio/quarkus/issues/4049

**Comment by mkouba** [comment] 2019-09-17 06:14
@jordanglassman Thanks.
