### ISSUE TITLE
Multiple matching properties for name "datasource.url" on 1.1.0.CR1

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6170] opened 2019-12-13 22:36 UTC
**Describe the bug**
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-core</artifactId>
    <version>1.1.0.CR1</version>
</dependency>

**Expected behavior**
no error

**Actual behavior**
on start:
Failed to start Quarkus: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url"

**To Reproduce**
1.
on start:
Failed to start Quarkus: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url"

**Configuration**
```properties
# Add your application.properties here, if applicable.

have only one configuration. for %dev %qa etc - one per env
even if remove all configuration still fails
did not have this error until updated from 1.0.1 final

```

**Additional context**
related:
https://stackoverflow.com/questions/59328770/quarkus-project-once-covered-to-mutli-module-form-got-404-when-hit-the-existing

the comment on bottom.

**Comment by Sergey80** [comment] 2019-12-14 02:16
Reproducer:
https://github.com/Sergey80/quarkus-samples

if you change version to 1.1.0.CR1

on start you would get:

Listening for transport dt_socket at address: 5005
21:06:03,415 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url"
	at io.quarkus.deployment.configuration.matching.PatternMapBuilder.addMember(PatternMapBuilder.java:70)

**Comment by geoand** [comment] 2019-12-14 08:36
I was able to reproduce the problem.

**Comment by geoand** [comment] 2019-12-14 08:55
The problem is that you have both the  `quarkus-agroal` dependency and the `quarkus-reactive-pg-client` dependency. You need to you only one (depending on what your application is actually doing).

Both of these dependencies define the `quarkus.datasource.url` property which is why things fail (Quarkus configuration handling has changes in version 1.1.0 and what you are seeing now is actually more correct than 1.x). 

I am going to close this issue, but if you still feel that there is something Quarkus should be doing differently, feel free to reopen and comment.

**Closed by geoand** 2019-12-14 08:55 UTC
Labels: bug

**Comment by Sergey80** [comment] 2019-12-14 13:03
now:
1. //    implementation 'io.quarkus:quarkus-agroal'  commented out
2. no any databases defined in the application.properries 
result the same:
Listening for transport dt_socket at address: 5005
08:01:16,636 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url"
https://github.com/Sergey80/quarkus-samples/tree/issues_6170

**Comment by geoand** [comment] 2019-12-14 13:14
I tried your Maven examples and at least in those you had the dependencies in multiple places, so I needed to comment out all places

**Comment by Sergey80** [comment] 2019-12-14 13:17
i commented them, it still does not work.
that error is gone gone only when I comment both io.quarkus:quarkus-agroal and quarkus-reactive-pg-client but then I can not use database at all in my app.

**Comment by geoand** [comment] 2019-12-14 13:26
Here is what my diff looks like:

```
diff --git a/my-project-backend/pom.xml b/my-project-backend/pom.xml
index 52fc7e4..3c41f27 100644
--- a/my-project-backend/pom.xml
+++ b/my-project-backend/pom.xml
@@ -69,10 +69,10 @@
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-smallrye-health</artifactId>
         </dependency>
-        <dependency>
-            <groupId>io.quarkus</groupId>
-            <artifactId>quarkus-agroal</artifactId>
-        </dependency>
+<!--        <dependency>-->
+<!--            <groupId>io.quarkus</groupId>-->
+<!--            <artifactId>quarkus-agroal</artifactId>-->
+<!--        </dependency>-->
         <dependency>
             <groupId>io.quarkus</groupId>
             <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
diff --git a/pom.xml b/pom.xml
index 02ea428..9c407e9 100644
--- a/pom.xml
+++ b/pom.xml
@@ -18,7 +18,7 @@
     <maven.compiler.source>1.8</maven.compiler.source>
     <maven.compiler.target>1.8</maven.compiler.target>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
-    <quarkus.version>1.0.1.Final</quarkus.version>
+    <quarkus.version>1.1.0.CR1</quarkus.version>
     <surefire-plugin.version>2.22.1</surefire-plugin.version>
   </properties>
 
@@ -102,10 +102,10 @@
       <groupId>io.quarkus</groupId>
       <artifactId>quarkus-smallrye-health</artifactId>
     </dependency>
-    <dependency>
-      <groupId>io.quarkus</groupId>
-      <artifactId>quarkus-agroal</artifactId>
-    </dependency>
+<!--    <dependency>-->
+<!--      <groupId>io.quarkus</groupId>-->
+<!--      <artifactId>quarkus-agroal</artifactId>-->
+<!--    </dependency>-->
     <dependency>
       <groupId>io.quarkus</groupId>
       <artifactId>quarkus-smallrye-fault-tolerance</artifactId>
```

With that change, when using Maven the error no longer exists

**Comment by Sergey80** [comment] 2019-12-14 13:41
ok. true, thx. now the question remains, how to run it in multi module mode.. but that is differen issue.
rep/target/my-project-service-dev.jar
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:71)

**Comment by geoand** [comment] 2019-12-14 13:42
What you describe is issue #6168 , correct? If so, please update that issue to mention the fact that it's still an issue with `1.1.0.CR1`

**Comment by Sergey80** [comment] 2019-12-14 13:47
ok. let me try

**Comment by Sergey80** [comment] 2019-12-14 13:49
yes. same thing still. updated to <quarkus.version>1.1.0.CR1</quarkus.version>
put a commented on that issue. updated my sample branch.

**Comment by geoand** [comment] 2019-12-14 13:50
Thanks

**Comment by stuartwdouglas** [comment] 2019-12-15 23:08
I think we should print a more obvious error message in this case.

**Comment by geoand** [comment] 2019-12-16 06:52
@stuartwdouglas that would be nice.

@dmlloyd is printing a good error message when multiple config objects use the same property possible?

**Comment by dmlloyd** [comment] 2019-12-16 14:58
It is possible - but maybe instead, for this case at least, it would be better to define the common data source config properties in a common SPI module?  Could you then use both libraries in one project?  It could be annoying if you wanted to mix for whatever reason and you could not just because of an obscure config constraint.

**Comment by dmlloyd** [comment] 2019-12-16 14:59
To clarify more: I think a common module is a good idea regardless.  If both extensions cannot coexist for reasons *other* than config, then let's have a better error message that isn't config related like "Extensions X and Y cannot coexist" (maybe include dependency chain info too if possible).

**Comment by geoand** [comment] 2019-12-16 15:01
I think that that is essentially what @gsmet is proposing on the mailing list.

**Comment by Sergey80** [comment] 2019-12-16 16:47
one more thing:
without quarkus-agroal<

the  /health/ready - will not work for the DB. as it used to work.

probably separate bug?
