### ISSUE TITLE
Non-accessible methods from superclass are not transactional

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#7105] opened 2020-02-09 20:45 UTC
**Describe the bug**
If class A extends class B, and class B has some @Transactional methods that are not accessible from class A (e.g. they a private, or class B is in another package and methods are package-private), methods from class B will not get transaction and they will fail. For example:
```java
    @BeforeEach
    @Transactional()
    /*
    PRIVATE: FAIL
    PACKAGE: FAIL
    protected: OK
    public: OK
     */
      void addPerson() {
        person = new Person();
        person.name = "pero";
        personRepository.persistAndFlush(person);
    }
```

**Expected behavior**
Methods should get transaction or error should be generated.

**Actual behavior**
Build passes, but then it fails in runtime.

**To Reproduce**
1.  Create superclass in package "package.A" with some package-private @Transactional methods.
2. Create subclass in a package "package.B".
3. Call methods from superclass.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Win 10
 - Output of `java -version`: 1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.0.Alpha1

**Additional context**
(Add any other context about the problem here.)
Reproducer is attached: 
[test-superclass.zip](https://github.com/quarkusio/quarkus/files/4177809/test-superclass.zip)

**Comment by stuartwdouglas** [comment] 2020-07-08 03:05
@mkouba I don't think there is any way to actually fix this? As the subclass is in a different package you can't override the package private method. Maybe we should log a warning or fail the deployment in this case?

**Comment by manovotn** [comment] 2020-07-08 07:06
IIUIC we are talking invocation of method(s) declared on B from A, then there is no direct way to achieve that because they are private or pack private. In such case the invocation won't be treated as business method invocation anyway and interception won't happen.

**Comment by mkouba** [comment] 2020-07-08 07:21
@zeljkot How do you call the methods from the superclass? You would have to cast the bean instance of the class from the `package.B` to the superclass from the `package.A` and then call the package-private method from a class from the `package.A`. That looks like a massive corner case ;-).

Hm, a private or package-private `@Transactional` observer method declared on the superclass would problematic as well... but that could be solved with a reflection fallback.

It would be really helpful if you could provide a reproducer app.

**Comment by stuartwdouglas** [comment] 2020-07-08 07:27
I think it is a test, so because the test class is a bean if you have an @Transactional test method on the superclass it won't work. It would be invoked via reflection from the JUnit runner.

**Comment by zeljkot** [comment] 2020-07-08 07:49
You are right, @stuartwdouglas. My original example shows the use case. Generating error during compilation would be one way to solve it.  Because the application cannot be compiled into the desired state, a warning is not strong enough.

**Comment by manovotn** [comment] 2022-10-25 15:12
Looking at the reproducer, it is basically about using interceptor binding on a `@BeforeEach`/`@AfterEach` method of a `@QuarkusTest` class.
I don't think these are meant to be handled as beans since they are invoked via [Quarkus JUnit extension through reflection](https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L790-L799).

We could only generate error if we analyze annotation on a given method which would also require us to look into meta annotations to figure out if they are an interceptor binding. And even then it would probably not include synthetically registered binding. 
CC @mkouba

**Comment by mkouba** [comment] 2022-10-26 09:48
Hm, I don't think that invocation via reflection should matter here and the test classes are meant to be beans. However, in this particular case the generenated interceptor subclass method `addPerson()` does not override the inherited `ParentTest#addPerson()` method because it lives in a different package (and the same applies to `ExampleResourceTest`). Consequently, even if the `QuarkusTestExtension` invokes the `addPerson()` method upon the intercepted subclass the `ParentTest#addPerson()` is called instead.

I'm not really sure there's an easy and realiable way to detect this kind of corner case errors.

**Comment by manovotn** [comment] 2022-10-26 10:05
> Hm, I don't think that invocation via reflection should matter here and the test classes are meant to be beans.

Sorry, I meant to say that I didn't think JUnit lifecycle callbacks were expected to be intercepted. Some are even static by definition which is outside of CDI scope although Quarkus can attempt to bypass that.

> I'm not really sure there's an easy and realiable way to detect this kind of corner case errors.

Agreed. Let's close this for now; if there is further interest, we can reopen the discussion.

**Closed by manovotn** 2022-10-26 10:05 UTC
Labels: kind/bug, area/arc
