### ISSUE TITLE
Optimistic Lock Exception is not working

### ISSUE THREAD

**Issue by gbourant** [quarkusio/quarkus#29601] opened 2022-12-01 07:14 UTC
### Describe the bug

 I have the following two methods:

```java
public String createNewEntity() {
        MyEntity e = new MyEntity();
        e.setName("NewName");
        em.persist(e);
        var message = "MyEntity saved with id " + e.getId() + " and version " + e.getVersion();
        System.out.println("message = " + message);
        return message;
}

public String editEntity() {
        var e = em.find(MyEntity.class, 1L);
        System.out.println("old version " + e.getVersion());
        e.setVersion(-1);
        e.setName("EditedName " + Math.random());
        em.persist(e);
        em.flush();
        var message = "MyEntity updated with id " + e.getId() + " and version " + e.getVersion();
        System.out.println("message = " + message);
        return message;
}
```

When `createNewEntity`  is called, it creates a new entity of type MyEntity with id 1 and version 0. When `editEntity` is called it should throw an `OptimisticLockException` because i set the version to a different number.

Firstly i thought that it was a [panache problem](https://github.com/quarkusio/quarkus/issues/7193) but i tried the same with plain jpa and it didn't work as excepted either. 

I have created a [reproducer](https://github.com/gbourant/quarkus-jpa-version) which is based on plain jpa. It also uses dev-services for the database.

### Output of `uname -a` or `ver`

Linux 6.0.9-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 16 Nov 2022 17:01:17 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.17" 2022-10-18 OpenJDK Runtime Environment (build 11.0.17+1) OpenJDK 64-Bit Server VM (build 11.0.17+1, mixed mode)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 11.0.17, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-11-openjdk Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.0.9-arch1-1", arch: "amd64", family: "unix"

**Comment by Sanne** [comment] 2022-12-01 11:15
See https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#locking-optimistic-version-number :

```
Your application is forbidden from altering the version number set by Hibernate. To artificially increase the version number, see the documentation for properties LockModeType.OPTIMISTIC_FORCE_INCREMENT or LockModeType.PESSIMISTIC_FORCE_INCREMENT
```

Looks like that applies here? (I haven't checked your reproducer yet, let me know if this doesn't explain it)

**Comment by gbourant** [comment] 2022-12-01 12:07
I tried the suggestion but it seems that it's not working.

**Comment by gbourant** [comment] 2023-01-04 18:29
I updated the given reproducer to the 2.15.2 version and the problem still exists.

I found out that there is a way to get the javax.persistence.OptimisticLockException.

step 1:
Create a new entity with the `curl http://localhost:8080/hello`

step 2:
open two terminal and run:

```bash
while true
do
  curl http://localhost:8080/hello/update
done
```

and you get the following error. 

```
ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-2) Request failed: javax.persistence.OptimisticLockException: Batch update returned unexpected row count from update [0]; actual row count: 0; expected: 1; statement executed: update MyEntity set name=?, version=? where id=? and version=?
```

**Comment by yrodiere** [comment] 2023-01-05 08:24
To be clear, setting the version manually is probably not allowed because Hibernate ORM will ignore your changes. So the reproducer you gave doesn't fail because your change to the version number is ignored, and that's expected.

Beyond the fact that setting the version manually is not allowed, if you want to simulate a race condition, neither setting the version manually nor using `LockModeType.OPTIMISTIC_FORCE_INCREMENT` or `LockModeType.PESSIMISTIC_FORCE_INCREMENT` will work.

You really need two concurrent operations to run, both changing the version number (implicitly). Only then will you get the exception, like in your example.

The loop you gave is a good example of how you can get such a situation. And as you said, you do get a `javax.persistence.OptimisticLockException`. So, it works.

Since it works, and since your original reproducer was doing something illegal (setting the version manually)... do you agree we can close this ticket?

**Comment by Sanne** [comment] 2023-01-05 12:25
I agree with Yoann, it seems it's working correctly.

**Closed** 2023-01-05 14:20 UTC
Labels: kind/bug, area/hibernate-orm
