### ISSUE TITLE
Managed Executor context propagation inconsistent

### ISSUE THREAD

**Issue by HelvetiaAppDev** [quarkusio/quarkus#11394] opened 2020-08-14 12:13 UTC
**Describe the bug**
When calling a REST endpoint that starts an async task with the help of ManagedExecutor (org.eclipse.microprofile.context.ManagedExecutor) and this task calls a method that is annotated with `@RolesRequired` it is inconsitent if the role check is successful.

**Expected behavior**
Every time the REST endpoint is called with the appopriate user the call should run without error.

**Actual behavior**
Some calls throw an Exception (io.quarkus.security.UnauthorizedException), especially if the method is called multiple times (overlapping)

**To Reproduce**
1.  Install the Example `security-jdbc-quickstar` (https://quarkus.io/guides/security-jdbc) 
2.  Add dependency for `quarkus-smallrye-context-propagation`
3.  Create class `UserService`
4.  Change class `UserResource` to the example below
5.  Start the local server  
6.  run `curl -i -X GET -u user:user http://localhost:8080/api/users/me` repeatadely and fast.

UserService:
```@ApplicationScoped
public class UserService {
    @RolesAllowed("user")
    void testA()
    {
        try {
            Thread.sleep(20);
        } catch (InterruptedException e) {
        }
        System.out.println("test A done");
    }
    @RolesAllowed("user")
    void testB()
    {
        try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
        }
        System.out.println("test B done");
    }
}
```

UserResource:
```package org.acme.security.jdbc;
import org.eclipse.microprofile.context.ManagedExecutor;
import javax.annotation.security.RolesAllowed;
import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Context;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.SecurityContext;
@Path("/api/users")
public class UserResource {
    @Inject
    UserService userService;
    @Inject
    ManagedExecutor managedExecutor;
    @GET
    @RolesAllowed("user")
    @Path("/me")
    @Produces(MediaType.TEXT_PLAIN)
    public String me(@Context SecurityContext securityContext) {
        userService.testA();
        managedExecutor.runAsync(() -> {try {
            userService.testB();
        }catch (Exception e)
        {
            e.printStackTrace();
        }});
        return securityContext.getUserPrincipal().getName();
    }
}
```

Output in quarkus after 8 fast calls: (the eight "test B done" never happens as suddenly Unauthorized)
```test A done
test B done
test A done
test B done
test A done
test B done
test A done
test B done
test A done
test A done
test B done
test B done
test A done
test A done
io.quarkus.security.UnauthorizedException
        at io.quarkus.security.runtime.interceptor.check.RolesAllowedCheck.apply(RolesAllowedCheck.java:59)
        at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:27)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:23)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(RolesAllowedInterceptor_Bean.zig:386)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.security.jdbc.UserService_Subclass.testB(UserService_Subclass.zig:179)
        at org.acme.security.jdbc.UserService_ClientProxy.testB(UserService_ClientProxy.zig:212)
        at org.acme.security.jdbc.UserResource.lambda$me$0(UserResource.java:30)
        at io.smallrye.context.SmallRyeThreadContext$ContextualRunnable.run(SmallRyeThreadContext.java:56)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1807)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:830)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
test B done
```

**Configuration**
unchanged from the example

**Environment (please complete the following information):**
 - Output of `ver`:  `Microsoft Windows [Version 10.0.19041.450]`
 - Output of `java -version`: 
```java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
``` 
and also tested with
``` java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)
``` 
 - Quarkus version or git rev:  1.7.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: C:\Users\benja\.m2\wrapper\dists\apache-maven-3.6.2-bin\795eh28tki48bv3l67maojf0ra\apache-maven-3.6.2
Java version: 13.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-13.0.2
Default locale: de_AT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by gastaldi** [comment] 2020-08-17 16:54
I'll have a look

**Comment by FroMage** [comment] 2020-08-18 07:54
Yeah, as @Ladicek said, this is because you're propagating the request context, which is terminated after the REST method is done. If you want to keep it alive until your async stuff is done, then you need to make it return an async type that terminates after your async methods. Given that `managedExecutor.runAsync` returns a `CompletableFuture` this is pretty easy to do, just return it from the REST method.

I don't think this is a bug.

**Comment by Ladicek** [comment] 2020-08-18 08:08
I agree it's not a bug, but perhaps it's a feature request. This is the 2nd time since yesterday I hear from someone wanting to "fire and forget" async tasks with context propagation. Do we have a way to say "capture the context, but immediately detach"? It of course brings all kinds of interesting thread safety concerns.

**Comment by FroMage** [comment] 2020-08-18 08:29
Well, context propagation was really meant for reactive programming, where you don't start doing async access to the same context. For many contexts that will just fail, like for JPA which is not thread-safe. Perhaps ArC is thread-safe, but I don't remember. So there's already the limitation that propagating to async threads doesn't mean you can do unsafe stuff with the context.

Now, as to the lifetime of contexts, ArC will defer a call to destroy the request context upon request termination, but I'm not sure what it does, probably call destroy methods for the request-scoped beans? @manovotn would know. For the transaction context it definitely needs to have a termination point, to commit/rollback, plus the limitation that it won't be thread-safe. For the RESTEasy context I'm pretty sure it's a dump `Map` that can be safely propagated forever.

It really depends on the contexts, is what I'm saying.

Now, as to the feature itself, how common is it to start unmonitored run-away async tasks in REST endpoints? It sounds to me like a horrible risk more than something we should advertise.

Note that MP-CP doesn't talk at all about the lifecycle of contexts (when they start or are destroyed), it only talks about propagating them, not keeping them alive until all propagation is done.

IMO, if we want to allow starting async tasks from a request without tying their lifecyle to the request, we should grant them some new context. Perhaps not a request context, perhaps a new sort of CDI context. Perhaps we should make this explicit, with an API like this:

```java
@Path("/api/users")
public class UserResource {
    @Inject
    UserService userService;

    @Inject
    SmallRyeManagedExecutor managedExecutor;

    @GET
    @RolesAllowed("user")
    @Path("/me")
    @Produces(MediaType.TEXT_PLAIN)
    public String me(@Context SecurityContext securityContext) {
        userService.testA();
        managedExecutor.runInAsyncContext(() -> {try {
            userService.testB();
        }catch (Exception e)
        {
            e.printStackTrace();
        }});
        return securityContext.getUserPrincipal().getName();
    }
}
```

Where `SmallRyeManagedExecutor.runInAsyncContext` would:

- Start a new sort of CDI context (ASYNC?) which inherits the current request context?
- Extend the life-cycle of the context until both that async task and the request are done.
- Take over management of that thread so that errors are reported properly

But note that this would either mean that:

- the current request returns to the user without normal end actions being executed yet (DB commit/rollback) and so the request doesn't actually reflect real success/failure
    - we would not take the alternative approach of delaying the request termination upon completion of the async tasks because we can already do that manually and it appears that's not what these users want
- the ASYNC task completion/failure would have no way to be reported back to the user, we could just log it
- it could be tricky to figure out if the failure of the request (after we've started the async tasks) or of one of multiple async task should mean to cancel/terminate the other async tasks of that group (do we have groups?)

So, yeah, it's complex, we can discuss this and try to figure out a reasonable approach, but I'd delay that as much as possible until we're sure this is a use-case we want to support instead of advise against.

@mkouba @manovotn @cescoffier WDYT?

**Comment by manovotn** [comment] 2020-08-18 09:05
> Perhaps ArC is thread-safe, but I don't remember. 

Not really, the way we (intentionally) did ArC propagation was along the lines of reactive programming - it doesn't really presume "parallel" execution which can be the case in this "fire and forget" scenario. It also boils down to user beans having to be thread safe. The storage (map) of beans is actually a concurrent map, but that doesn't ensure you can do anything with it anyway.

> Now, as to the lifetime of contexts, ArC will defer a call to destroy the request context upon request termination, but I'm not sure what it does, probably call destroy methods for the request-scoped beans? @manovotn would know.

Yeah, that's what happens - pre destroy callbacks on beans. Furthermore, the map of bean instances will be cleared on a given thread. This could possibly put those beans in an undefined state based on what you perform in pre destroy callbacks.

**Comment by Ladicek** [comment] 2020-08-18 09:40
Haha, it's much more fun than I could possibly imagine :-) Unfortunately, I don't even see a way how to detect that the user does this (attempts to access short-lived/not-expected-to-contain-thread-safe-objects contexts such as request or transaction from multiple threads in parallel) and produce a warning.

OK, I'll try to narrow it down. I think what both this issue and the other case I saw yesterday (on Zulip) want is: run some task asynchronously, but finish the HTTP response synchronously (or, slightly more generally, finish the HTTP response sooner than all the spawned tasks finish). That is, finish the HTTP response, but not drop the contexts just yet. I can now see how that is dangerous (HTTP response is finished, but transaction is not?). It would probably only make sense for a selected subset of the contexts, and still have thread-safety issues (request-scoped beans are typically not thread safe).

Agree that at this point, we should really advise against this. The only reasonable way [I can see now] to run "fire and forget" tasks from an HTTP endpoint is to explicitly not use context propagation and capture all the necessary state manually, before spawning that task. And all the captured objects should be thread-safe, preferrably immutable. (I think in both usecases, it's about capturing the user's roles, which is a `Set<String>`, so should be fine.)

**Comment by manovotn** [comment] 2020-08-18 10:16
Well, with what ArC does now, you technically can do what you ask for so long as:
* you avoid pre destroy callbacks on your beans
* you make your own beans thread-safe (and be mindful that any beans from other parties might not be thread-safe)

Looking at `ArcContextProvider` (this is what performs CP for CDI), we only `deactivate` the context on the new thread, we do not destroy it. This means that from propagated threads, we won't invoke pre destroy callbacks, this will only happen from the original one (intentionally, so that we don't perform that multiple times).
We also hold the context map in `ThreadLocal` for each thread, so deactivating (or destroying) context in one means we detach that map. Apart from potential pre destroy callback invocation, I don't see an issue if you keep using that context attached to another thread.

**Comment by gastaldi** [comment] 2020-08-18 13:44
I created https://github.com/quarkusio/quarkus/issues/11443 asking for a "fire-and-forget" behavior with Context Propagation.

I'm closing this issue now, thanks!

**Closed by gastaldi** 2020-08-18 13:44 UTC
Labels: kind/bug
