### ISSUE TITLE
Missing field in ConsulConfigProcessor NoSuchFieldError: CONSUL_CONFIG

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#23129] opened 2022-01-24 08:17 UTC
### Describe the bug

consul-config 999-SNAPSHOT throws an error
```
Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.consul.config.ConsulConfigProcessor#feature threw an exception: java.lang.NoSuchFieldError: CONSUL_CONFIG
```
The field is missing in source code

### How to Reproduce?

git clone https://github.com/quarkus-qe/quarkus-test-suite

cd properties
mvn clean verfiy

### Output of `java -version`

OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9

### Quarkus version or git rev

999-SNAPSHOT

**Comment by geoand** [comment] 2022-01-24 09:07
`quarkus-test-suite` is not building for me.

```
Could not resolve dependencies for project io.quarkus.ts.qe:properties:jar:1.0.0-SNAPSHOT: Could not find artifact io.quarkus:quarkus-consul-config:jar:999-SNAPSHOT
```

**Comment by gsmet** [comment] 2022-01-24 09:20
You need to build Quarkus with `-Prelocations` to get it to find this artifact.

**Comment by gsmet** [comment] 2022-01-24 09:23
But my guess is that @kshpak  has an old `io.quarkus:quarkus-consul-config` artifact around in his `.m2` as it was built before and he didn't use `-Prelocations` to build the new one.

**Comment by kshpak** [comment] 2022-01-24 09:27
@gsmet I will try to build it with `-Prelocations`. Is `-Prelocation` is the thing for moved dependencies to Quarkiverse? And should this profile be used then all the time afterward to build 999-SNAPSHOT?

**Comment by geoand** [comment] 2022-01-24 09:29
> You need to build Quarkus with `-Prelocations` to get it to find this artifact.

Ah, thanks!

I am closing this as invalid as I was not able to reproduce it (after building Quarkus with `-Prelocations`) and because the `.m2` explanation makes sense.

> And should this profile be used then all the time afterward to build 999-SNAPSHOT?

It's needed if you are using extensions that have been moved outside of the Quarkus Core to the Quarkiverse (as Consul in this case)

**Closed by geoand** 2022-01-24 09:29 UTC
Labels: kind/bug, triage/needs-triage

**Comment by gsmet** [comment] 2022-01-24 09:34
@kshpak it should be used as a transition but you should point to the new extensions from now on so it shouldn't be necessary in the long run.

See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.6#extensions-moved-to-the-quarkiverse-hub for all the background of this change.
