### ISSUE TITLE
Regression Test: Validation errors on Reactive routes are no longer propagated

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#16430] opened 2021-04-12 07:19 UTC
## Describe the bug
Having these two routes:

```java
@Inject
FruitResource fruitResource;

@Route(methods = HttpMethod.POST, path = "/insert")
void insert(@Body Fruit fruit, RoutingContext context) {
    fruitResource.insertFruit(fruit)
            .onFailure().invoke(context::fail)
            .subscribe().with(id -> context.response().setStatusCode(201).end());
}

@Route(path = "/*", type = Route.HandlerType.FAILURE, produces = "application/json")
void databaseConstraintFailure(PgException e, HttpServerResponse response) {
    response.setStatusCode(400).end();
}
```

The `insert` route will insert a fruit item into the database. The `databaseConstraintFailure` handler will map the database constraints into a 400 Status code.

The above scenario works fine using 1.13.1.Final or later, but not using 999-SNAPSHOT which fails with the next exception:

```
ERROR: HTTP Request to /insert failed, error id: f1aab3c8-a7f2-464d-8c33-bd4a33af5e31-1
io.vertx.core.VertxException: Transaction already completed
	at io.vertx.sqlclient.impl.TransactionImpl.checkPending(TransactionImpl.java:115)
	at io.vertx.sqlclient.impl.TransactionImpl.rollback(TransactionImpl.java:154)
	at io.vertx.sqlclient.impl.TransactionImpl.rollback(TransactionImpl.java:159)
	at io.vertx.mutiny.sqlclient.Transaction.lambda$rollback$2(Transaction.java:112)
	at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:30)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:37)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:37)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:44)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:36)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:140)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:135)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:118)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.vertx.core.Promise.handle(Promise.java:53)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$null$0(TransactionImpl.java:75)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
```

## To Reproduce
1.  git clone `https://github.com/Sgitario/quarkus-examples`
2.  cd quarkus-examples/reproducers/reactive-sql
3. mvn clean verify -Dtest=FruitResourceTest#shouldNotInsertFruitIfValidationError

The test should pass, but it's failing with the above exception

### Quarkus version or git rev
999-SNAPSHOT

**Comment by geoand** [comment] 2021-04-12 07:56
cc @mkouba

**Comment by mkouba** [comment] 2021-04-12 08:34
It does not seem to be a problem in the routing layer. The vertx sql client fails to rollback the transaction but previously the `PgException` was thrown. We will need some eyes from the vertx/pgclient/mutiny team...

@cescoffier Do we have a label for isssues that are probably a consequence of the Vertx 4 the migration?

1.13.1.Final stack trace:
```
2021-04-12 10:23:08,983 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-7) Mutiny had to drop the following exception: io.vertx.pgclient.PgException: null value in column "name" violates not-null constraint
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:29)
	at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
	at io.vertx.pgclient.impl.codec.ExtendedQueryCommandCodec.handleErrorResponse(ExtendedQueryCommandCodec.java:87)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:245)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:131)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:111)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

999-SNAPSHOT:
```
021-04-12 10:30:35,511 ERROR [io.qua.mut.run.MutinyInfrastructure] (vert.x-eventloop-thread-12) Mutiny had to drop the following exception: io.vertx.core.VertxException: Transaction already completed
	at io.vertx.sqlclient.impl.TransactionImpl.checkPending(TransactionImpl.java:115)
	at io.vertx.sqlclient.impl.TransactionImpl.rollback(TransactionImpl.java:154)
	at io.vertx.sqlclient.impl.TransactionImpl.rollback(TransactionImpl.java:159)
	at io.vertx.mutiny.sqlclient.Transaction.lambda$rollback$2(Transaction.java:112)
	at io.smallrye.mutiny.vertx.AsyncResultUni.subscribe(AsyncResultUni.java:30)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:37)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:37)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:99)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.onFailure(UniOnItemOrFailureFlatMap.java:65)
	at io.smallrye.mutiny.operators.uni.UniOperatorProcessor.onFailure(UniOperatorProcessor.java:44)
	at io.smallrye.mutiny.vertx.AsyncResultUni.lambda$subscribe$1(AsyncResultUni.java:36)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:140)
	at io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:135)
	at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:128)
	at io.vertx.core.impl.future.FutureBase.emitFailure(FutureBase.java:79)
	at io.vertx.core.impl.future.FutureImpl.tryFail(FutureImpl.java:198)
	at io.vertx.core.impl.future.PromiseImpl.tryFail(PromiseImpl.java:23)
	at io.vertx.sqlclient.impl.QueryResultBuilder.tryFail(QueryResultBuilder.java:118)
	at io.vertx.core.Promise.fail(Promise.java:89)
	at io.vertx.core.Promise.handle(Promise.java:53)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$null$0(TransactionImpl.java:75)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.sqlclient.impl.TransactionImpl.lambda$txCommand$2(TransactionImpl.java:169)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:83)
	at io.vertx.core.impl.DuplicatedContext.execute(DuplicatedContext.java:199)
	at io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:51)
	at io.vertx.core.impl.future.FutureImpl.tryComplete(FutureImpl.java:179)
	at io.vertx.core.impl.future.PromiseImpl.tryComplete(PromiseImpl.java:23)
	at io.vertx.core.impl.future.PromiseImpl.onSuccess(PromiseImpl.java:49)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:41)
	at io.vertx.core.impl.future.PromiseImpl.handle(PromiseImpl.java:23)
	at io.vertx.pgclient.impl.PgSocketConnection.lambda$doSchedule$2(PgSocketConnection.java:149)
	at io.vertx.sqlclient.impl.command.CommandResponse.fire(CommandResponse.java:46)
	at io.vertx.sqlclient.impl.SocketConnectionBase.handleMessage(SocketConnectionBase.java:258)
	at io.vertx.pgclient.impl.PgSocketConnection.handleMessage(PgSocketConnection.java:94)
	at io.vertx.sqlclient.impl.SocketConnectionBase.lambda$init$0(SocketConnectionBase.java:96)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$new$1(NetSocketImpl.java:97)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.net.impl.NetSocketImpl.lambda$handleMessage$9(NetSocketImpl.java:390)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:52)
	at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:294)
	at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:24)
	at io.vertx.core.net.impl.NetSocketImpl.handleMessage(NetSocketImpl.java:389)
	at io.vertx.core.net.impl.ConnectionBase.read(ConnectionBase.java:153)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:154)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
	at io.vertx.pgclient.impl.codec.PgEncoder.lambda$write$0(PgEncoder.java:88)
	at io.vertx.pgclient.impl.codec.PgCommandCodec.handleReadyForQuery(PgCommandCodec.java:139)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeReadyForQuery(PgDecoder.java:235)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:95)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by pjgg** [comment] 2021-04-12 09:43
Looks like in the previous version, when you were running a DB statement with Mutiny, you didn't need to propagate the failures (that could be handler by a reactive route failure handler), and now in upstream, you need to propagate these failures.

For example:
**Version `1.13.1.Final** `:

```
this.preparedQuery("INSERT INTO " + getDatabaseName() + "." + tableName + " (" + fields + ") VALUES (" + values + ") RETURNING id").execute().onItem().transform(id -> id.iterator().next().getLong("id"));
```

 then you will handler the failure in a reactive route failure handler
```
@ApplicationScoped
public class FailureHandler {

    @Route(path = "/*", type = Route.HandlerType.FAILURE, produces = "application/json")
    void databaseConstraintFailure(PgException e, HttpServerResponse response) {
        response.setStatusCode(400).end(Json.encode(new JsonObject().put("msg", e.getMessage())));
    }

}
```

**Upstream**:

```
this.preparedQuery("INSERT INTO " + getDatabaseName() + "." + tableName + " (" + fields + ") VALUES (" + values + ") RETURNING id").execute().onItem().transform(id -> id.iterator().next().getLong("id")).onFailure().recoverWithUni(failure -> Uni.createFrom().failure(failure));
```
 Note that we have to add a `onFailure`  in order to propagate the failure.

**Comment by cescoffier** [comment] 2021-04-12 09:47
@vietj @tsegismont anything changed around transaction management in Vert.x 4? 

@pjgg 
```.onFailure().recoverWithUni(failure -> Uni.createFrom().failure(failure));```

It should not be required, as it just propagates the failure downstreams.

**Comment by tsegismont** [comment] 2021-04-12 12:24
@cescoffier this may be related to https://github.com/eclipse-vertx/vertx-sql-client/issues/930

**Comment by gsmet** [comment] 2021-04-13 07:54
@tsegismont I don't know how much of a priority it is for Vert.x but I think it's gonna be a very annoying bug for us. Any ETA for a fix?

**Comment by tsegismont** [comment] 2021-04-13 08:14
@gsmet I don't know yet but will tell you as soon as I know

**Comment by vietj** [comment] 2021-04-15 11:48
can a reproducer without quarkus and only mutiny be provided ?

**Comment by tsegismont** [comment] 2021-05-10 16:19
@cescoffier side note: in the Java snippet above, I had to use `.subscribeAsCompletionStage().get()` instead of `await()` otherwise I couldn't see anything in the console.

Are you aware of any issue we `await()` method in `2.4.0`?

**Comment by cescoffier** [comment] 2021-05-10 16:58
No, nothing changed. CC @jponge

**Comment by jponge** [comment] 2021-05-11 05:09
@tsegismont BTW `await` is a group, you need to chain with a method to say how you want to await, like `atMost(duration)`

**Comment by cescoffier** [comment] 2021-05-11 07:43
If you await it's to get a result, `await()`, will get you a `UniAwait`, not the expected result.

**Comment by jponge** [comment] 2021-05-11 15:41
+ https://github.com/smallrye/smallrye-reactive-utils/pull/313

**Comment by tsegismont** [comment] 2021-05-11 20:07
@Sgitario @pjgg can you try to run the test suite with SmallRye Reactive Utils `2.5.1`?

**Comment by jponge** [comment] 2021-05-11 20:09
> @Sgitario @pjgg can you try to run the test suite with SmallRye Reactive Utils `2.5.1`?

...and with https://github.com/quarkusio/quarkus/pull/17113 😉

**Comment by Sgitario** [comment] 2021-05-12 06:36
@jponge Unfortunately, the PR https://github.com/quarkusio/quarkus/pull/17113 made no difference when running the failing test as the smallrye version was sticked at 2.3.0. Actually, we're not using the Smallrye Reactive Utils for nothing.

The good news is that if I update this line: https://github.com/quarkusio/quarkus/pull/17113/files#diff-2b7d71809e1063e0d0411cbe30d606e12b984790680195567e7b8bde0d078e3fR143 to point out to 2.5.1, then the test works.

**Comment by jponge** [comment] 2021-05-12 06:57
The PR does upgrade both Mutiny and Smallrye Reactive Utils.

**Comment by Sgitario** [comment] 2021-05-12 07:14
> The PR does upgrade both Mutiny and Smallrye Reactive Utils.

I meant the `mutiny-vertx.version` version as well.

**Comment by cescoffier** [comment] 2021-05-12 07:27
@Sgitario I think you found another bug:
smallrye-reactive-utils.version and mutiny-vertx.version are intended to be one....

**Comment by Sgitario** [comment] 2021-05-12 07:30
> @Sgitario I think you found another bug:
> smallrye-reactive-utils.version and mutiny-vertx.version are intended to be one....

+1 Actually, if having both was not done on purpose, then I guess the linked PR https://github.com/quarkusio/quarkus/pull/17113 should address it as well.
What do you think @cescoffier @jponge ?

**Comment by jponge** [comment] 2021-05-12 07:30
I'm looking at this, because we shouldn't have redundant properties

**Comment by jponge** [comment] 2021-05-12 07:44
See https://github.com/quarkusio/quarkus/pull/17113/commits/a38ce98b8abccc3f64431e924e240a3e43562558

**Comment by jponge** [comment] 2021-05-12 11:10
Merged!

**Closed** 2021-05-12 11:10 UTC
Labels: area/mutiny, area/reactive, kind/bug, priority/blocker
