### ISSUE TITLE
Encoding errored output in maven on windows

### ISSUE THREAD

**Issue by ginccc** [quarkusio/quarkus#3228] opened 2019-07-15 13:12 UTC
Running ./mvnw compile quarkus:dev on windows produces very hard to read runtime output.

```
...
[INFO] templateengine-definition                                          [jar]
[INFO] templateengine-impl-thymeleaf                                      [jar]
[INFO] propertysetter-definition                                          [jar]
[INFO] propertysetter-impl                                                [jar]
[INFO] httpCallsTask-impl                                                 [jar]
[INFO] backupservice-defintion                                            [jar]
[INFO] backupservice-impl                                                 [jar]
[INFO] apiserver                                                          [jar]
[INFO]
[INFO] ----------------------------< ai.labs:eddi >----------------------------
[INFO] Building eddi 4.7                                                 [1/49]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:0.19.1:dev (default-cli) @ eddi ---
Listening for transport dt_socket at address: 5005
[38;5;145m2019-07-15 13:59:51,640[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.qua.dep.QuarkusAugmentor[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mBeginning quarkus augmentation[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,321[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.authServerUrl[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,321[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.publicClient[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,321[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.user[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,322[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.sslRequired[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,322[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.realmKey[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:52,324[39m[38;5;188m [39m[38;5;137mWARN [39m[38;5;188m [[39m[38;5;69mio.qua.config[39m[38;5;188m] ([39m[38;5;71mbuild-11[39m[38;5;188m) [39m[38;5;151m[39mUnrecognized configuration key "[38;5;188mquarkus.keycloak.admin[39m" provided[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:53,163[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.qua.dep.QuarkusAugmentor[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151mQuarkus augmentation completed in 1523ms[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:54,534[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.quarkus[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mQuarkus [38;5;188m0.19.1[39m started in [38;5;188m3.253[39ms. [38;5;188mListening on: http://[::]:8080[39m[39m[38;5;203m[39m[38;5;227m
[39m[38;5;145m2019-07-15 13:59:54,535[39m[38;5;188m [39m[38;5;107mINFO [39m[38;5;188m [[39m[38;5;69mio.quarkus[39m[38;5;188m] ([39m[38;5;71mmain[39m[38;5;188m) [39m[38;5;151m[39mInstalled features: [[38;5;188mcdi, keycloak, resteasy, security[39m][39m[38;5;203m[39m[38;5;227m
[39m
```

tried it in CMD on windows 10 and Git Bash inside intellij.
Not entirely sure if this is a local encoding issue or a bug... So in case i simple do something wrong here, please let me know.. :-)

**Comment by gwenneg** [comment] 2019-07-15 19:07
Hi @ginccc. I just ran a `mvnw quarkus:dev` in a Windows 10 `cmd` window and got the same result with encoding issues. However, `./mvnw quarkus:dev` in a Git Bash window is not affected by this on my computer.

**Comment by gsmet** [comment] 2019-11-13 22:56
Duplicate of https://github.com/quarkusio/quarkus/issues/2128 .

**Closed by gsmet** 2019-11-13 22:56 UTC
Labels: bug
