### ISSUE TITLE
More control over when hibernate init and finish the connections in the app.

### ISSUE THREAD

**Issue by sirlordt** [quarkusio/quarkus#29846] opened 2022-12-13 22:15 UTC
### Description

Quarkus and another many frameworks assume in wrong way the app need init hibernate/jpa on start/bootstrap of app.

I need develop a app. In start/bootstrap not init hibernate. The app first need connect to remote http/rest api end point every 5 minutes. In the json response get the database connection params, IP from server, Database, User name, Password and window time in minutes. For example 5 minutes or 20 minutes or 30 minutes. When finish the time window i need close the ALL db connection (full hibernate shutdown) and wait for my turn again. Long pooling the rest api end point. And repeat the process.

The point is in quarkus. I no had control when hibernate/jpa init the connections, the hiraky pool. using the data from the remote endpoint. Always try to init hibernate/jpa when the app start. 

The database protocol is always the same. For example MySQL, The models tables are the same too. The database, ip, user, password is very possible changed between turns (Is because i need full shutdown hibernate in middle of the execution).

In the doc not show any way of solution for this requirement.

I known this is possible with vanilla Hibernate. Using the classical connection class Utils.

I need compile this app to native using graalvm/native-image because is a IOT device and had only 128mb of ram.

### Implementation ideas

Expose some kind of DBConnectionManager class when you can bootstrap or shutdown the hibernate in any point of execution of app.

Example:

```java
DataSource dataSource = new DataSource( "JDBC_driver", "IP", "Database", "User", "Password" ); //Here the info of the connection

//Bootstrap in any place in the code.
DBConnectionManager.startConnections( "profile01",  dataSource ); //exception if already connected.

//Full shutdown hibenrate connection
DBConnectionManager.finishConnections( "profile01", true ); //exception if not connected. true = force

```

**Comment by Sanne** [comment] 2022-12-13 23:05
Hi,
Quarkus isn't forcing Hibernate to connect as soon as it's initialized.
There are two things at play:

1. Hibernate by default will validate the schema when it's started; this will trigger a connection to be established - if you don't want this, make sure schema validations on boot are not enabled. See https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.generation .
2. The connection pool has a minimum size, and a separate initial size which can be configured. See [quarkus.datasource.jdbc.initial-size](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.initial-size).

Finally you're also asking to reconfigure the Datasource dynamically; I'm not sure if that's possible - on top of changing the configuration, you'd have to stop the pool and re-start it which is inherently racy but I suppose doable. @barreiro , opinions?

**Comment by sirlordt** [comment] 2022-12-13 23:20
> Hi, Quarkus isn't forcing Hibernate to connect as soon as it's initialized. There are two things at play:
> 
>     1. Hibernate by default will validate the schema when it's started; this will trigger a connection to be established - if you don't want this, make sure schema validations on boot are not enabled. See https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.generation .
> 
>     2. The connection pool has a minimum size, and a separate initial size which can be configured. See [quarkus.datasource.jdbc.initial-size](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc.initial-size).
> 
> 
> Finally you're also asking to reconfigure the Datasource dynamically; I'm not sure if that's possible - on top of changing the configuration, you'd have to stop the pool and re-start it which is inherently racy but I suppose doable. @barreiro , opinions?

I think is connecting to database. With not option to delay the connection.

![image](https://user-images.githubusercontent.com/4441192/207466036-da9b84f6-786e-44be-89fe-b6f7577d96e4.png)

**Comment by Sanne** [comment] 2022-12-14 14:11
@sirlordt Ok, that's not by design. Seems we have a regression.

**Comment by yrodiere** [comment] 2022-12-21 11:03
Created https://github.com/quarkusio/quarkus/issues/30002 to address the regression.

Assuming we fix that regression, can we close this feature request as not planned, @sirlordt? From what I see it wouldn't be necessary anymore.

**Comment by sirlordt** [comment] 2022-12-22 16:52
No. Because is not clear for me, when I can bootstrap or shutdown hibernate. I need full bootstrap hibernate and later full shutdown hibernate in any moment of the execution of the app.

I thinks quarkus not had this feature. At less is not very well documented.

Please read my original comment.

This already possible using vanilla hibernate-orm/mysql-driver/jvm. I mean a plain maven java project with no quarkus. But unfortunally the plain project not compile with native-image.

**Closed** 2022-12-23 17:11 UTC
Labels: kind/enhancement, area/persistence, area/hibernate-orm

**Comment by sirlordt** [comment] 2022-12-23 19:14
@Sanne , @yrodiere  Ok thanks!!. I already did it, using EclipseLink implementarion as provider of jpa. Work like charm. It is a maven plain project with graalvm/native-image, no quarkus. I can bootstrap and full shutdown EntityManager any moment of execution of the app. 

You can look in this repo:

https://github.com/sirlordt/java-eclipse-link-native-image
