### ISSUE TITLE
When using Secrets, config functionality should be auto enabled

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#11258] opened 2020-08-06 14:38 UTC
**Description**
Currently, if an application wants to read configuration from Kubernetes Secrets, but not a ConfigMap, the following properties need to be defined:

```
quarkus.kubernetes-config.enabled=true
quarkus.kubernetes-config.secrets.enabled=true
```

Which for me, was confusing at first as I'd assumed the first enablement was specific to ConfigMaps.

**Implementation ideas**
When `quarkus.kubernetes-config.secrets.enabled` is `true`, but `quarkus.kubernetes-config.enabled` is not present, and thus has the default value, then set it to `true` to simplify the configuration needed.

**Comment by viveksahu26** [comment] 2020-08-08 13:03
sir, i would love to work in this issue.. So, kindly, assign me this issue..

**Comment by viveksahu26** [comment] 2020-08-08 13:34
I am beginner to this issue. Can you please suggest, how to get started..

**Comment by geoand** [comment] 2020-09-02 05:58
Fixed in https://github.com/quarkusio/quarkus/pull/11748

**Closed by geoand** 2020-09-02 05:58 UTC
Labels: area/kubernetes, good first issue, kind/enhancement

**Comment by Ladicek** [comment] 2020-09-08 09:44
This goes directly against my original intent. The `quarkus.kubernetes-config.enabled` config property controls whether config sources are created based on ConfigMaps and Secrets. That's also how all other extensions work.

The `quarkus.kubernetes-config.secrets.enabled` config property is _not_ an alias. It was only meant to enable generating additional Kubernetes resources.

**Comment by geoand** [comment] 2020-09-08 09:45
Let's decide on this one before 1.8 goes out

**Comment by Ladicek** [comment] 2020-09-08 09:52
I don't see a reason to be able to enable/disable only-ConfigMaps or only-Secrets -- you control that by setting the list of ConfigMaps and Secrets to read. You just enable/disable reading config sources from the Kubernetes API server.

So the issue is that I probably should have used a different name for `quarkus.kubernetes-config.secrets.enabled` :-/

**Comment by kenfinnigan** [comment] 2020-09-08 12:39
It's not a one or the other, it's being able to activate secrets without knowing you also must enable the entirety of config for the extension

**Comment by geoand** [comment] 2020-09-08 12:53
Basically I'm leaning towards what Ken mentions here - with the caveat that the user shouldn't have to explicitly set `quarkus.kubernetes-config.enabled=true`.

However, as reported in https://github.com/quarkusio/quarkus/issues/11968, we should probably not fetch the secrets when `quarkus.kubernetes-config.enabled=false` was set explicitly.

WDYT?

**Comment by Ladicek** [comment] 2020-09-08 12:55
There's no such thing as "activate secrets". You just activate Kubernetes config.

The "secrets.enable" thing just makes Quarkus generate additional Kubernetes resources that give the application's service account access to secrets in the Kubernetes API server.

Again, bad name of the property, it seems :-(

**Comment by kenfinnigan** [comment] 2020-09-08 12:58
Irrespective of how it's named, if it needs to be turned on to use secrets, and another config property turned on to make that work, that's a bad experience.

It shouldn't require to configuration properties to be turned on to do one thing

**Comment by Ladicek** [comment] 2020-09-08 12:58
And the reason why we need the property is that we don't know at build time if the user will want to read stuff from secrets. We could generate the resources always, but for some reason I don't recall, we didn't want that.

**Comment by kenfinnigan** [comment] 2020-09-08 13:02
I don't mind if there's a property to generate the secrets, but I don't see why I need to set another property in addition to that one

**Comment by geoand** [comment] 2020-09-08 13:12
I think I can come up with something that fits both of your requirements, checking now

**Comment by Ladicek** [comment] 2020-09-08 13:14
The 2 properties are totally orthogonal, and only appear to not be when you consider Quarkus-generated Kubernetes YAML files to be the only possible way how to obtain Kubernetes YAML files for Quarkus application.

Frankly, we could just always generate the additional Kubernetes resources and let users know that if they don't need them, they can delete them :-) (Or, instead of having a property to generate them, have a property to suppress generating them.)
