### ISSUE TITLE
Opentracing build create instable build

### ISSUE THREAD

**Issue by Dufgui** [quarkusio/quarkus#2316] opened 2019-05-01 18:00 UTC
I see sometime my PR fail due to instability of test in build on opentracing due to small timeout 

[INFO] Running io.quarkus.smallrye.opentracing.deployment.TracingTest
2019-05-01 17:36:48,698 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-05-01 17:36:50,110 INFO  [io.qua.arc.pro.BeanProcessor] (build-13) Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field io.quarkus.smallrye.opentracing.deployment.TestResource#service,
	- @Inject field io.quarkus.smallrye.opentracing.deployment.Service#tracer
2019-05-01 17:36:50,398 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1700ms
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.IIOImageProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventOutputProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultTextPlain is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.client.jaxrs.internal.CompletionStageRxInvokerProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ReactiveStreamProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.CacheControlFeature is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.ServerContentEncodingAnnotationFeature is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.CompletionStageProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.ClientContentEncodingAnnotationFeature is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultNumberWriter is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.SourceProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.interceptors.MessageSanitizerContainerResponseFilter is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.MultiValuedParamConverterProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DocumentProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DefaultBooleanWriter is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ByteArrayProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,555 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StringTextStar is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.StreamingOutputProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.ReaderProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.sse.SseEventSinkInterceptor is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.DataSourceProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.JaxrsFormProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.FileRangeWriter is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,571 WARN  [org.jbo.res.res.i18n] (main) RESTEASY002155: Provider class org.jboss.resteasy.plugins.providers.InputStreamProvider is already registered.  2nd registration is being ignored.
2019-05-01 17:36:50,945 WARN  [io.qua.jae.run.JaegerDeploymentTemplate] (main) Jaeger service name has not been defined, either as 'quarkus.jaeger.service-name' application property or JAEGER_SERVICE_NAME environment variable/system property
2019-05-01 17:36:51,102 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 0.709s. Listening on: http://[::]:8081
2019-05-01 17:36:51,102 INFO  [io.quarkus] (main) Installed features: [cdi, jaeger, resteasy, smallrye-fault-tolerance, smallrye-metrics, smallrye-opentracing, smallrye-rest-client]
2019-05-01 17:36:53,544 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.invocations.total, type: counter]
2019-05-01 17:36:53,559 INFO  [com.net.con.DynamicPropertyFactory] (executor-thread-1) DynamicPropertyFactory is initialized with configuration sources: com.netflix.config.ConcurrentCompositeConfiguration@48d1d116
2019-05-01 17:36:53,903 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.timeout.executionDuration, type: histogram]
2019-05-01 17:36:53,903 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.retry.retries.total, type: counter]
2019-05-01 17:36:53,950 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.fallback.calls.total, type: counter]
2019-05-01 17:36:53,950 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.retry.callsFailed.total, type: counter]
2019-05-01 17:36:53,950 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.invocations.failed.total, type: counter]
2019-05-01 17:36:54,053 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.retry.callsSucceededRetried.total, type: counter]
2019-05-01 17:36:54,053 INFO  [io.sma.met.MetricsRegistryImpl] (executor-thread-1) Register metric [name: ft.io.quarkus.smallrye.opentracing.deployment.Service.faultTolerance.timeout.callsNotTimedOut.total, type: counter]
2019-05-01 17:36:59,175 INFO  [io.sma.fau.HystrixInitializer] (main) ### Reset Hystrix ###
2019-05-01 17:36:59,175 INFO  [io.quarkus] (main) Quarkus stopped in 0.016s
[ERROR] Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 10.65 s <<< FAILURE! - in io.quarkus.smallrye.opentracing.deployment.TracingTest
[ERROR] testContextPropagationInFaultTolerance  Time elapsed: 5.663 s  <<< ERROR!
org.awaitility.core.ConditionTimeoutException: Condition with io.quarkus.smallrye.opentracing.deployment.TracingTest was not fulfilled within 5 seconds.
	at org.awaitility.core.ConditionAwaiter.await(ConditionAwaiter.java:145)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:79)
	at org.awaitility.core.CallableCondition.await(CallableCondition.java:27)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:902)
	at org.awaitility.core.ConditionFactory.until(ConditionFactory.java:860)
	at io.quarkus.smallrye.opentracing.deployment.TracingTest.testContextPropagationInFaultTolerance(TracingTest.java:106)

**Comment by gsmet** [comment] 2019-05-02 13:01
It's a duplicate of this one: https://github.com/quarkusio/quarkus/issues/2187 . Closing.

**Closed by gsmet** 2019-05-02 13:01 UTC
Labels: component:smallrye
