### ISSUE TITLE
[ORM6] Hibernate Search - Class loading issue when starting application

### ISSUE THREAD

**Issue by kaspernielsen** [quarkusio/quarkus#37772] opened 2023-12-15 11:27 UTC
### Describe the bug

I'm trying to upgrade from Quarkus 3.2.2-Final but facing the same issues as in https://github.com/quarkusio/quarkus/issues/31247 even though the problem should have been fixed upstream.

I've tried upgrading to 3.2.3-Final, 3.3.0, 3.5.0, 3.6.6 which all fails with the same exception

Quarkus 3.2.2 was the last version that used hibernate search 6.1.7 before upgrading to 6.2.0.

mvn help:effective-pom | grep -B 1 -A 1  hibernate-search-engine shows (for 3.2.3-Final)

          <groupId>org.hibernate.search</groupId>
          <artifactId>hibernate-search-engine</artifactId>
          <version>6.2.0.Final</version>

(I'm starting the application via mvn quarkus:dev)

### Actual behavior

10:29:00 ERROR traceId=, parentId=, spanId=, sampled= [io.qu.ru.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at org.niord.core.Main.main(Main.java:19)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.RuntimeException: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:78)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:101)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy_2(Unknown Source)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits1868654632.deploy(Unknown Source)
	... 12 more
Caused by: jakarta.persistence.PersistenceException: [PersistenceUnit: <default>] Unable to build Hibernate SessionFactory
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.persistenceException(FastBootEntityManagerFactoryBuilder.java:126)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:86)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
	... 1 more
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH700119: Exception while retrieving the Jandex index for code source location 'quarkus:/': HSEARCH900013: Exception while accessing Jandex index for 'quarkus:/': Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.jandexIndexForCodeSourceLocation(AnnotationMappingConfigurationContextImpl.java:234)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.buildJandexIndex(AnnotationMappingConfigurationContextImpl.java:201)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.lambda$configure$0(AnnotationMappingConfigurationContextImpl.java:127)
	at org.hibernate.search.util.common.jar.spi.JandexBehavior.doWithJandex(JandexBehavior.java:17)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.configure(AnnotationMappingConfigurationContextImpl.java:126)
	at org.hibernate.search.mapper.pojo.mapping.spi.AbstractPojoMappingInitiator.configure(AbstractPojoMappingInitiator.java:134)
	at org.hibernate.search.mapper.orm.mapping.impl.HibernateOrmMappingInitiator.configure(HibernateOrmMappingInitiator.java:163)
	at org.hibernate.search.engine.common.impl.SearchIntegrationBuilder$MappingBuildingState.collect(SearchIntegrationBuilder.java:270)
	at org.hibernate.search.engine.common.impl.SearchIntegrationBuilder.prepareBuild(SearchIntegrationBuilder.java:148)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchPreIntegrationService$NotBooted.doBootFirstPhase(HibernateSearchPreIntegrationService.java:279)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateOrmIntegrationBooterImpl.bootNow(HibernateOrmIntegrationBooterImpl.java:179)
	at java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at org.hibernate.search.mapper.orm.bootstrap.impl.HibernateSearchSessionFactoryObserver.sessionFactoryCreated(HibernateSearchSessionFactoryObserver.java:41)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
	... 6 more
Caused by: org.hibernate.search.util.common.SearchException: HSEARCH900013: Exception while accessing Jandex index for 'quarkus:/': Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.JandexUtils.readOrBuildIndex(JandexUtils.java:113)
	at org.hibernate.search.mapper.pojo.mapping.definition.annotation.impl.AnnotationMappingConfigurationContextImpl.jandexIndexForCodeSourceLocation(AnnotationMappingConfigurationContextImpl.java:227)
	... 23 more
Caused by: java.io.IOException: Could not open 'META-INF/jandex.idx' within 'quarkus:/': HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:122)
	at org.hibernate.search.util.common.jar.impl.JandexUtils.doReadIndex(JandexUtils.java:127)
	at org.hibernate.search.util.common.jar.impl.JandexUtils.readOrBuildIndex(JandexUtils.java:101)
	... 24 more
Caused by: java.io.IOException: HSEARCH900016: Cannot open filesystem for code source at 'quarkus:/': HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.initFileSystem(CodeSource.java:162)
	at org.hibernate.search.util.common.jar.impl.CodeSource.classesPathOrFail(CodeSource.java:128)
	at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:81)
	... 26 more
	Suppressed: java.lang.NullPointerException: Cannot read the array length because "buf" is null
		at java.base/java.io.ByteArrayInputStream.<init>(ByteArrayInputStream.java:108)
		at io.quarkus.bootstrap.classloading.MemoryClassPathElement$MemoryUrlStreamHandler$1.getInputStream(MemoryClassPathElement.java:146)
		at java.base/java.net.URL.openStream(URL.java:1161)
		at org.hibernate.search.util.common.jar.impl.CodeSource.readOrNull(CodeSource.java:112)
		... 26 more
Caused by: java.io.IOException: HSEARCH900017: Cannot interpret 'quarkus:/' as a local directory or JAR.
	at org.hibernate.search.util.common.jar.impl.CodeSource.initFileSystem(CodeSource.java:158)
	... 28 more

### Output of `uname -a` or `ver`

Darwin Kernel Version 22.6.0

### Output of `java -version`

java version "17.0.3.1" 2022-04-22 LTS

### Quarkus version or git rev

3.2.3-Final, 3.3.0, 3.5.0, 3.6.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.5

**Comment by yrodiere** [comment] 2023-12-15 12:38
Hello,

Are you using the `quarkus-hibernate-search-orm-elasticsearch` extension?

I'm asking because that extension [disables the use of Jandex at runtime](https://github.com/quarkusio/quarkus/blob/87704762430e413fb25454e6cb56e11749ce5cc5/extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/mapping/QuarkusHibernateOrmSearchMappingConfigurer.java#L17-L25) (it does it at build time) to avoid exactly this problem, so Hibernate Search shouldn't even try to analyze your JARs on startup, at least if you use the extension.

If you are not using the extension, please do.

If you are using the extension, I'll need a reproducer, please... Maybe something based on this: https://github.com/quarkusio/quarkus-quickstarts/tree/main/hibernate-search-orm-elasticsearch-quickstart

**Comment by yrodiere** [comment] 2023-12-15 13:15
See also the [Hibernate Search guide for Quarkus](https://quarkus.io/guides/hibernate-search-orm-elasticsearch) to know more about this extension I mentioned.

**Comment by kaspernielsen** [comment] 2023-12-15 13:54
I'm not using the Elasticsearch backend but the Lucene one.

<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-mapper-orm-orm6</artifactId>
</dependency>
 <dependency>
    <groupId>io.quarkiverse.lucene</groupId>
    <artifactId>quarkus-lucene</artifactId>
    <version>2.3.0</version>
</dependency>
<dependency>
    <groupId>org.hibernate.search</groupId>
    <artifactId>hibernate-search-backend-lucene</artifactId>
    <version>6.1.7.Final</version>
</dependency>

I've tried both with and without quarkus-lucene

**Comment by yrodiere** [comment] 2023-12-15 14:43
I see.

Using the Lucene backend is something we don't support in Quarkus yet. There is an issue about it here, but unfortunately it didn't make it to the top of my priority list: https://github.com/quarkiverse/quarkus-hibernate-search-extras/issues/179
Maybe someone else could give it a try someday :)

If you use Hibernate Search + Lucene in Quarkus without an extension, I'm afraid your only options are:

1. Disabling Jandex index scanning in Hibernate Search and lose the ability to use `@ProjectionConstructor`; essentially [registering a mapping configurer](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#mapper-orm-mapping-configurer) to do [this](https://github.com/quarkusio/quarkus/blob/87704762430e413fb25454e6cb56e11749ce5cc5/extensions/hibernate-search-orm-elasticsearch/runtime/src/main/java/io/quarkus/hibernate/search/orm/elasticsearch/runtime/mapping/QuarkusHibernateOrmSearchMappingConfigurer.java#L17-L25) but without the last line (which is not useful if you want to just disable the feature).
2. OR providing Jandex indexes to Hibernate Search yourself; i.e. [registering a mapping configurer](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#mapper-orm-mapping-configurer) and using `addJandexIndex` which is briefly mentioned [there](https://docs.jboss.org/hibernate/stable/search/reference/en-US/html_single/#mapping-classpath-scanning-dependencies).

I'll close this issue; feel free to ask here if you have further questions about the recommendation above, or to comment on https://github.com/quarkiverse/quarkus-hibernate-search-extras/issues/179 if you have relevant information for an eventual "Hibernate Search + Lucene" extension.

**Closed by yrodiere** 2023-12-15 14:43 UTC
Labels: kind/bug, area/hibernate-search, triage/needs-feedback

**Comment by kaspernielsen** [comment] 2023-12-15 20:46
Thanks @yrodiere that was a quick fix.
For anyone else having this issue and looking to do option 1 (as outlined previously), add this file to your project

```
import org.hibernate.search.mapper.orm.mapping.HibernateOrmMappingConfigurationContext;
import org.hibernate.search.mapper.orm.mapping.HibernateOrmSearchMappingConfigurer;
import jakarta.enterprise.context.ApplicationScoped;


@ApplicationScoped
public class QuarkusHibernateOrmSearchMappingConfigurer implements HibernateOrmSearchMappingConfigurer {

    @Override
    public void configure(HibernateOrmMappingConfigurationContext context) {
        // Jandex is not available at runtime in Quarkus,
        // so Hibernate Search cannot perform classpath scanning on startup.
        context.annotationMapping()
                .discoverJandexIndexesFromAddedTypes(false)
                .buildMissingDiscoveredJandexIndexes(false);
    }
}

```
And include this line in application.properties
`quarkus.hibernate-orm.unsupported-properties."hibernate.search.mapping.configurer"=class:YOUR_PACKAGE.QuarkusHibernateOrmSearchMappingConfigurer`
