### ISSUE TITLE
Building a native image with minikube docker fails

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#7158] opened 2020-02-12 10:10 UTC
**Describe the bug**
Since I use minikube on my machine, I don't want to switch back and forth with Docker to build my native image which use a lot of resources.

I directly use minikube docker with:
```
$ eval $(minikube docker-env)  
$ mvn package -Pnative -Dquarkus.native.container-build=true
```

and it fails with:
```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] docker run -v /Users/ia3andy/workspace/redhat/talks/game-of-stacks/arrow/target/gos-arrow-0.0.1-native-image-source-jar:/project:z --rm quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java8 -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:ReflectionConfigurationFiles=reflection-config.json --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -H:+JNI -jar gos-arrow-0.0.1-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx7g -H:-AddAllCharsets -H:EnableURLProtocols=http --no-server -H:-UseServiceLoaderFeature -H:+StackTrace gos-arrow-0.0.1-runner
Error: Invalid Path entry gos-arrow-0.0.1-runner.jar
Caused by: java.nio.file.NoSuchFileException: /project/gos-arrow-0.0.1-runner.jar

```

I've checked `gos-arrow-0.0.1-runner.jar` is in the target directory.

**Expected behavior**
Should build the native image

**Actual behavior**
Fail

**To Reproduce**
1. install minikube
2. run:
```
$ eval $(minikube docker-env)  
```
3. build a native image with :
```
$ mvn package -Pnative -Dquarkus.native.container-build=true
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: `1.3.0.Alpha1`

**Comment by ia3andy** [comment] 2020-02-12 10:13
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.0.Alpha1:native-image (default) on project gos-arrow: Failed to generate native image: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:342)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:331)
[ERROR]         ... 12 more
[ERROR] -> [Help 1]

```

**Comment by banshay** [comment] 2020-03-02 00:42
For me, the same thing happens without minikube installed. Just setting up a project and running `mvn package -Pnative -Dquarkus.native.container-build=true` fails with the exception 
`Caused by: java.nio.file.NoSuchFileException: /project/PROJECT_NAME_VERSION.jar`

**Comment by ia3andy** [comment] 2020-03-02 07:27
@geoand any thoughts?

**Comment by geoand** [comment] 2020-03-02 07:29
Building a native image with any docker daemon other than the localhost daemon will fail because the jar is built locally, not on whatever host the daemon is running

**Comment by ia3andy** [comment] 2020-03-02 07:31
Ok then, should we close this as a "wont fix"? (or is this something we should cover)?

**Comment by geoand** [comment] 2020-03-02 07:32
We should probably close since it's a duplicate of https://github.com/quarkusio/quarkus/issues/1610

**Closed** 2020-03-02 07:37 UTC
Labels: kind/bug
