### ISSUE TITLE
ChainBuildException -v 1.3.0.Alpha1 when build native image

### ISSUE THREAD

**Issue by NickyPeetersZinderlabs** [quarkusio/quarkus#7289] opened 2020-02-19 18:36 UTC
**Describe the bug**
When building the native image for Quarkus 1.3.0.Alpha1 with GraalVM 19.3.1-java11 a chainBuildException is raised.

**Expected behavior**
A working native images

**Actual behavior**
ChainBuild Exception is raised:

Failed to execute goal io.quarkus:quarkus-maven-plugin:1.3.0.Alpha1:build (default) on project .... : Failed to build quarkus application: io.quarkus.builder.ChainBuildException: Item class io.quarkus.deployment.builditem.DeploymentClassLoaderBuildItem cannot be produced here (it is an initial resource) (io.quarkus.deployment.steps.DeploymentClassLoaderBuildStep#classloader)

**To Reproduce**
1. Create a base project via code.quarkus.io
2. Change quarks.version to 1.3.0.Alpha1
3. set GraalVM 19.3.1 as VM
3. run command "./mvnw package -Pnative -Dquarkus.native.container-build=true"
OR
run command "mvn package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:19.3.1-java11"

**Configuration**
```properties
N/A

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin MacBook-Pro-van-xxx.local 17.7.0 Darwin Kernel Version 17.7.0: Sun Dec  1 19:19:56 PST 2019; root:xnu-4570.71.63~1/RELEASE_X86_64 x86_64

 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
OpenJDK 64-Bit Server VM GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07, mixed mode, sharing)
 - Quarkus version or git rev: 
1.3.0.Alpha1

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment] 2020-02-19 18:40
So first, try with Alpha2 as we fixed a few issues already.

Then are you sure you also updated the Maven plugin?

**Comment by geoand** [comment] 2020-02-20 13:04
This sounds very much like an issue where the two properties controlling the plugin and platform version have not been updated in lockstep

**Comment by adam-tylr** [comment] 2020-03-03 22:30
I had the same issue and that was the cause. I had to make sure all the versions matched:
`<quarkus.version>1.2.1.Final</quarkus.version>`
`<quarkus-plugin.version>1.2.1.Final</quarkus-plugin.version>`
`<quarkus.platform.version>1.2.1.Final</quarkus.platform.version>`

**Comment by stuartwdouglas** [comment] 2020-07-08 03:51
This sounds like it was a version mismatch. I am closing as we have not seen any other reports of this.

**Closed by stuartwdouglas** 2020-07-08 03:51 UTC
Labels: kind/bug, triage/out-of-date
