### ISSUE TITLE
Rest-assured: quarkus.http.root-path duplicated in request

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#28001] opened 2022-09-16 11:03 UTC
### Describe the bug

We have an application which is configured to use:
quarkus.http.root-path

When we perform a call towards a Rest endpoint with RestAssured we observe that the request is faulty, the quarkus.http.root-path value is duplicated

See provided test which reproduce this

Works fine in previous Quarkus version

### Expected behavior

We expect that the http request from RestAssured is correct and will hit the endpoint

### Actual behavior

We see that the http request url contains two values from quarkus.http.root-path
And it fails with 404

### How to Reproduce?

Run the provided test: MyControllerTest
The test: fails, will produce the fault
[rest-client-reactive-quickstart12.zip](https://github.com/quarkusio/quarkus/files/9583427/rest-client-reactive-quickstart12.zip)

### Output of `uname -a` or `ver`

Linux hty80028.sb1a.sparebank1.no 4.18.0-372.16.1.el8_6.x86_64 #1 SMP Tue Jun 28 03:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### Quarkus version or git rev

2.13.0.CR1

**Comment by gsmet** [comment] 2022-09-16 12:33
@Sgitario could you have a look at that one if @geoand is not already on it?

My guess is that it could get very annoying for users if the issue is general.

**Comment by geoand** [comment] 2022-09-16 12:34
I'll have a look on Monday

**Comment by geoand** [comment] 2022-09-16 12:51
This is actually expected after https://github.com/quarkusio/quarkus/pull/27419 was merged. 

I will add an entry to the migration guide.

**Closed by geoand** 2022-09-16 12:51 UTC
Labels: kind/bug, area/testing

**Comment by lthasle** [comment] 2022-09-19 09:42
@geoand 
Thanks for your feedback!
Hmm, so I now need to remove the duplicated root-path to get my tests to work?
Or am I missing something here?

`
@QuarkusTest
public class MyControllerTest { 
	
	@TestHTTPEndpoint(MyController.class) 
    @TestHTTPResource URL url; 	
	@Test
	void tst() throws Exception { 
		get("ep1");
	}	
	private void get(String operation) {
		RequestSpecification rs = given()
				.log().uri()
				.contentType(MediaType.APPLICATION_JSON);
		rs.get(getPathFix(getPath(operation))).then().statusCode(SC_OK);
	}	
	private String getPath(String operation) {
		return url.getPath() + "/" + operation; 
	}	
	protected String getPathFix(String path) { // then it works!
		return path.replace("/api/", ""); // /api/ is from application.properties: quarkus.http.root-path=/api/
	}	
}

@Path(MyController.DOMAIN)
public class MyController {

	public static final String DOMAIN = "my";
	public static final String EP1 = "/ep1";
	@GET
	@Path(EP1)
	public Response ep1() {
		return Response.ok().build();
	}
}
`

**Comment by geoand** [comment] 2022-09-19 09:52
You are appending the path manually, which you no longer need to do

**Comment by lthasle** [comment] 2022-09-19 10:24
@geoand 
Sorry, but I feel a little stupid her, I can't get your suggestion to work.
Can you please correct my example above, so it works?

**Comment by geoand** [comment] 2022-09-20 05:49
Instead of doing:

```java
private String getPath(String operation) {
		return url.getPath() + "/" + operation; 
	}
```

do:

```java
private String getPath(String operation) {
		return url + "/" + operation;
	}
```

**Comment by lthasle** [comment] 2022-09-20 07:14
@geoand THANKS! It worked fine!

**Comment by geoand** [comment] 2022-09-20 07:15
🎉
