### ISSUE TITLE
Quarkus hot replace does not work for code in constructor

### ISSUE THREAD

**Issue by grumpyrodriguez** [quarkusio/quarkus#15664] opened 2021-03-12 09:37 UTC
**Describe the bug**
Changes to code in the constructor of Java classes are not included in the hot reload, even though Quarkus reports that the class is reloaded.

**Expected behavior**
Changing the code in the constructor of Java classes that are subject to hot reload should be included in the hot reload. 

**Actual behavior**
When code in constructor of a Java class is updated and a new request is made, the changes in the code are not reflected to reloaded class.

**To Reproduce**
Follow the [rest tutorial from Quarkus](https://quarkus.io/guides/rest-json) documentation to create a project. Basically this corresponds to running:

```
mvn io.quarkus:quarkus-maven-plugin:1.12.2.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=rest-json-quickstart \
    -DclassName="org.acme.rest.json.FruitResource" \
    -Dpath="/fruits" \
    -Dextensions="resteasy,resteasy-jackson"
```
Then start Quarkus with:
`./mvnw compile quarkus:dev`

Navigate to http://localhost:8080/resteasy-jackson/quarks using a modern browser
This will display a JSON payload as a result of the GET http request.

Now update the code in `JacksonResource` type's constructor in the generated project code, while Quarkus is still running. Change any of the text values of items added to `quarkus` field, for example, use the following:
`quarks.add(new Quark("Up", "The updated value goes here."));`

Save the changes to file. 

Refresh the browser page. Quarkus will print to terminal that changes are detected to modified Java class and it is reloaded. The changes in the constructor code are not reflected to response from Quarkus. Browser still displays the same json payload.

**Configuration**
As set by the mvn archetype above

**Screenshots**
Not applicable

**Environment (please complete the following information):**
`./mvnw --version` produces:

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/<user-name>/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: GraalVM Community, runtime: /usr/lib/jvm/graalvm-ce-java11-21.0.0.2
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-101-generic", arch: "amd64", family: "unix"
```
This code is run under Ubuntu 18.04.

**Additional context**
N/A

**Comment by mkouba** [comment] 2021-03-19 11:03
> Refresh the browser page. Quarkus will print to terminal that changes are detected to modified Java class and it is reloaded. The changes in the constructor code are not reflected to response from Quarkus. Browser still displays the same json payload.

In fact, the changes are reflected but since the default scope for JAX-RS resources is `@Singleton` and so the constructor is not called for every request - a single resource instance is shared for all requests. Note that CDI contexts are _not destroyed_ when a hot replace is performed via instrumentation. If you annotate the resource class with `@RequestScoped` you'll see the changes because a new resource instance will be created for every request.

**Comment by gsmet** [comment] 2021-03-19 11:17
I don't think we should close this one. For me it's a regression of instrumentation-base hot reload compared to the previous hot reload behavior.

@stuartwdouglas should we collect these things and try to improve?

**Comment by mkouba** [comment] 2021-03-19 11:31
Hm, I don't think we could improve this in a reasonable manner. E.g. we could exclude all `@Singleton` and `@ApplicationScoped` bean classes from instrumentation-based replacement but that would complicate things even more, and possibly also defeat the purpose of instrumentation replacement because a great deal of app components would be probably excluded. But yes, it's a regression when compared to previous behavior.

**Comment by gsmet** [comment] 2021-03-19 11:37
For me the whole promise of Quarkus live reload compared to everything else that existed before was: it will always work.

I think we should try extra hard to keep that promise.

Another idea: should we disable instrumentation when a constructor is changed?

**Comment by mkouba** [comment] 2021-03-19 12:10
> I think we should try extra hard to keep that promise.

My point is that sometimes instrumentation works just better because the contexts are not recreated and so you don't lose the state...

**Comment by mkouba** [comment] 2021-03-19 12:14
> Another idea: should we disable instrumentation when a constructor is changed?

I don't think we're able to detect this kind of modification...

**Comment by grumpyrodriguez** [comment] 2021-03-19 16:31
I created this issue because the behaviour did not match what the documentation and Quarkus console reported, at least as far as my interpretation of these goes. 

It would be absolutely OK if console logs or the documentation mentioned singleton behaviour, but to a developer, reloading a class would mean the whole instance being replaced. 

If you'd consider changing the definition of expected behaviour by changing the documentation, it would be a solution to this issue. Otherwise, others may get confused just like I did.

**Comment by stuartwdouglas** [comment] 2021-03-23 02:34
@mkouba maybe for singleton/application scoped beans we could destroy them and re-created them.

I am beginning to wonder if we should disable instrumentation by default, so those with large projects where it really matters can enable it. We could print an INFO message about enabling it if hot reload is taking a while (e.g. longer than 1s)

**Comment by mkouba** [comment] 2021-03-23 07:57
> @mkouba maybe for singleton/application scoped beans we could destroy them and re-created them.

I'm not quite sure this would help.

> I am beginning to wonder if we should disable instrumentation by default,

Well, from my experience features that are not enabled by default are rarely used.

> so those with large projects where it really matters can enable it. We could print an INFO message about enabling it if hot reload is taking a while (e.g. longer than 1s)

Like I mentioned - I believe that it's not only about the time it takes to reload. With instrumentation enabled you can modify the logic without losing the state. And that can be very useful.

In any case, the current way of disabling instrumentation is quite verbose: `-Dquarkus.live-reload.instrumentation=false`. Maybe something like `-DnoInstrumentation` would work better...

**Comment by grumpyrodriguez** [comment] 2021-03-24 08:59
Even the comments here are helpful in (more or less) understanding what's going on. Based on what I've read so far, please consider @stuartwdouglas 's suggestion and allow users to choose the method to be used for hot reload. 
I can see how keeping state and just hot reloading methods may help, but it would be great if users could choose whether or not they want this and if this was briefly documented. 

@mkouba my understanding is it is possible to disable instrumentation at the moment. Is that correct? Would Quarkus revert to reloading the whole class if I use the JVM parameter you mentioned?

**Comment by mkouba** [comment] 2021-03-24 09:04
> @mkouba my understanding is it is possible to disable instrumentation at the moment. Is that correct? Would Quarkus revert to reloading the whole class if I use the JVM parameter you mentioned?

Yes, `-Dquarkus.live-reload.instrumentation=false` disables the instrumentation. But I don't think it's even mentioned in the docs.

**Comment by gsmet** [comment] 2021-03-24 09:04
@grumpyrodriguez just add `quarkus.live-reload.instrumentation=false` and things will be back to the way it was.

@stuartwdouglas @mkouba while I agree instrumentation has its perks, our previous live reload had a lot of success and one of the reasons was that it always worked and you didn't have weird edge cases.

**Comment by geoand** [comment] 2022-01-26 07:58
I am going to close this as we have reverted to not using instrumentation unless explicitly requested by the user.

**Closed by geoand** 2022-01-26 07:58 UTC
Labels: kind/bug
