### ISSUE TITLE
jdbc-mariadb with JPA entity with drop-and-create Dev service - SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ'

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#36913] opened 2023-11-07 10:05 UTC
### Describe the bug

Just default jdbc-mariadb extension with JPA entity logs an error SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ' on dev mode.

```
2023-11-07 10:57:37,956 WARN  [org.mar.jdb.mes.ser.ErrorPacket] (JPA Startup Thread) Error: 4091-42S02: 2023-11-07 10:57:37,960 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread) GenerationTarget encountered exception accepting command : Error executing DDL "drop sequence Car_SEQ" via JDBC [(conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ']: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop sequence Car_SEQ" via JDBC [(conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ']
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:94)
	at org.hibernate.tool.schema.internal.Helper.applySqlString(Helper.java:233)
	at org.hibernate.tool.schema.internal.Helper.applySqlStrings(Helper.java:217)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropSequences(SchemaDropperImpl.java:337)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropConstraintsTablesSequences(SchemaDropperImpl.java:265)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:215)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:185)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:155)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:115)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:242)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.lambda$process$5(SchemaManagementToolCoordinator.java:143)
	at java.base/java.util.HashMap.forEach(HashMap.java:1337)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:140)
	at io.quarkus.hibernate.orm.runtime.observers.SessionFactoryObserverForSchemaExport.sessionFactoryCreated(SessionFactoryObserverForSchemaExport.java:21)
	at org.hibernate.internal.SessionFactoryObserverChain.sessionFactoryCreated(SessionFactoryObserverChain.java:35)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:293)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:84)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:74)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at jakarta.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:156)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:64)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ'
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:883)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:822)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:741)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:665)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:956)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1082)
	at org.mariadb.jdbc.Statement.execute(Statement.java:474)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:80)
	... 22 more
```

Doesn't block functionality but I don't understand why this is logged since the same with for instance postgres doesn't.

### Expected behavior

No error is logged.

### Actual behavior

`SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.Car_SEQ'` logged when dev mode starts.

### How to Reproduce?

https://github.com/xstefank/quarkus-reproducers/tree/main/mariadb-panache

Just new app with jdbc-mariadb, hibernate-orm-panache and https://github.com/xstefank/quarkus-reproducers/blob/main/mariadb-panache/src/main/java/org/acme/model/Car.java entity.

Just change quarkus-jdbc-mariadb to quarkus-jdbc-postgresql and no error is logged.

### Additional information

Not blocking the functionality but I can't explain this error in the book we're writing :).

**Comment by gsmet** [comment] 2023-11-10 15:30
IIRC, the problem is that we try to drop the sequence without checking if it exists with MariaDB whereas with PostgreSQL, we can only drop it if it exists.

@beikov I see that MariaDB now has a `IF EXISTS` clause for `DROP SEQUENCE` should the dialect be adjusted?

See https://mariadb.com/kb/en/drop-sequence/

In any case, it's not a Quarkus bug, it has more to do with Hibernate ORM, closing.

**Closed by gsmet** 2023-11-10 15:30 UTC
Labels: kind/bug, area/persistence, area/devservices

**Comment by beikov** [comment] 2023-11-10 15:41
Apparently this was added in MariaDB 10.3, but it's hard to keep track with the improvements in all databases. If you care about MariaDB, please provide a PR for this or at least create a [Jira ticket](https://hibernate.atlassian.net/) for this improvement request.
