### ISSUE TITLE
websockets codestart overrides code sample from spring-web when using together

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#18843] opened 2021-07-20 07:37 UTC
### Describe the bug

When generating project with `-Dextensions=spring-di,spring-web,websockets` I receive just code sample for websockets and not code sample for spring-web.

1.13.7.Final based command generates examples with both websockets and spring-web code examples.

### Expected behavior

Both websockets and spring-web code examples are generated.

### Actual behavior

Just code sample for websockets is generated, no code sample for spring-web.

### How to Reproduce?

Reproducer with 2.1.0.CR1:
rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:2.1.0.CR1:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.1.0.CR1 -Dextensions=spring-di,spring-web,websockets

spring-web code sample is generated when running the same command with `websckets` removed:
rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:2.1.0.CR1:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=2.1.0.CR1 -Dextensions=spring-di,spring-web

Running with 1.13.7 (both code examples are generated):
rm -rf app-generated-skeleton && mvn io.quarkus:quarkus-maven-plugin:1.13.7.Final:create -DprojectGroupId=my-groupId -DprojectArtifactId=app-generated-skeleton -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DplatformVersion=1.13.7.Final -Dextensions=spring-di,spring-web,websockets

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.1.0.CR1

**Comment by maxandersen** [comment] 2021-09-19 09:02
duplicate of #20235

**Comment by ia3andy** [comment] 2021-09-20 06:40
Thanks @maxandersen @rsvoboda.

Let's close this one, as the other one is more precise on the fix.

**Closed by ia3andy** 2021-09-20 06:40 UTC
Labels: kind/bug, area/spring, area/codestarts
