### ISSUE TITLE
Update the GraalVM SDK and API dependency to 23.x when they will be java11 compatible

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34299] opened 2023-06-26 06:57 UTC
### Description

Version 23 of the graalVM SDK and API artifacts use Java 17 bytecode. We cannot use these versions in Quarkus as it would break our Java 11 support. 

Fortunately, the GraalVM team agreed to publish these artifacts using Java 11 bytecode. For the time being, we need to lock the version to 22.3 (the last release using Java 11 bytecode).

This issue concerns remembering to update once the new artifacts are released.

The GraalVM team does not commit to keeping these artifacts using Java 11 bytecode forever. At some point, if they need to use a Java feature from 17 / 20 / 21, they will bump the bytecode version.

**Comment by zakkak** [comment] 2023-10-03 10:07
Duplicate of https://github.com/quarkusio/quarkus/issues/35054
Closed by https://github.com/quarkusio/quarkus/pull/35057

**Closed by zakkak** 2023-10-03 10:07 UTC
Labels: area/housekeeping
