### ISSUE TITLE
Resteasy Reactive Transfer-Encoding header is empty

### ISSUE THREAD

**Issue by jaypea** [quarkusio/quarkus#34750] opened 2023-07-14 09:51 UTC
### Describe the bug

We've observed a strange behaviour with a json endpoint and chunked responses in quarks 3.2.0.Final.

the `transfer-encoding` header comes with an empty value when it should be chunked.

clients behave strange and keep waiting in a long-polling state even if all the chunks have already been transferred.

### Expected behavior

going back to quarkus 3.1.3 it looks like this
```
HTTP/1.1 200 OK
transfer-encoding: chunked
Content-Type: application/json;charset=UTF-8
```

### Actual behavior

the response headers looks like this:
```
HTTP/1.1 200 OK
transfer-encoding: 
Content-Type: application/json;charset=UTF-8
```

### How to Reproduce?

this a an example method to reproduce:
```
    @GET
    @Path("status-bug-example")
    fun statusBugExample(): Response {
        val json =  SolverResource::class.java.getResource("/big-example.json")!!.readText()
        return Response.status(200).entity(json).build()
    }
```

if the response length is small enough, the response is not chunked and comes with a valid content-length header.

### Quarkus version or git rev

3.2.0.Final

**Comment by gsmet** [comment] 2023-07-20 16:31
@jaypea this is probably a bug but could you provide a small Maven reproducer that allows us to easily reproduce your issue?

Thanks.

**Comment by greyhairredbear** [comment] 2023-07-23 14:42
@gsmet I've created a reproducer (using gradle though) and shared it on GH: https://github.com/greyhairredbear/quarkus-reproducer-transfer-encoding-header 

Note: The versions from `gradle.properties` are: 
```
#Gradle properties
quarkusPluginId=io.quarkus
quarkusPluginVersion=3.2.2.Final
quarkusPlatformGroupId=io.quarkus.platform
quarkusPlatformArtifactId=quarkus-bom
quarkusPlatformVersion=3.2.2.Final
```

**Comment by geoand** [comment] 2023-07-25 09:07
I took a look at the sample you uploaded and I could not reproduce the problem.

More specifically, there was no `transfer-encoding` encoding as the headers contained `content-length=1026199`

**Comment by greyhairredbear** [comment] 2023-07-26 05:47
Oh, you are of course correct, seems like I didn't take enough time for QA - sorry for that. I did some investigation and it seems like I didn't include all the relevant code... 

I'll go back in the commit history of our project and will try to find out what's missing. Then I'll update the reproducer. 

Sorry again for the inconvenience

**Comment by geoand** [comment] 2023-07-26 06:04
Sounds like a plan!

**Comment by greyhairredbear** [comment] 2023-08-17 22:15
It took me a little while to get back to this, but today I tried to reproduce the issue with an older version of our project, and I couldn't do it on my machine. 

@jaypea Since I saw the bug occurring on your machine, do you still have a commit with the error occurring? Seems like I can't really provide a reproducer :(

**Comment by geoand** [comment] 2023-08-21 07:15
We'll really need a sample if we are to look into this one.

**Comment by geoand** [comment] 2023-08-30 05:09
I am going to close this one for a lack of a reproducer. If one does become available, feel free to comment or reopen

**Closed by geoand** 2023-08-30 05:09 UTC
Labels: kind/bug, area/resteasy-reactive, triage/needs-reproducer
