### ISSUE TITLE
MutinyEmitter fails with an outbound connector configured

### ISSUE THREAD

**Issue by tcerdaITBA** [quarkusio/quarkus#14056] opened 2020-12-26 18:02 UTC
**Describe the bug**
MutinyEmitter fails with `java.lang.IllegalStateException: SRMSG00027: No subscriber found for the channel price-create` when the channel ("price-create") is connected to an outbound connector instead of an in-memory method annotated with `@Incoming`. Changing `MutinyEmitter` to `Emitter` produces the expected behavior of queuing the message.

**Expected behavior**
Message should be sent via configured outbound connector by the application.properties

**Actual behavior**
`java.lang.IllegalStateException` is thrown and no message is sent

**To Reproduce**
Clone repo https://github.com/tcerdaITBA/quarkus-mutiny-emitter-bug

1. `./mvnw compile quarkus:dev`
2. `curl localhost:8080/hello-resteasy`

**Configuration**
```properties
amqp-username=quarkus
amqp-password=quarkus

mp.messaging.outgoing.price-create.connector=smallrye-amqp
mp.messaging.outgoing.price-create.address=prices

mp.messaging.incoming.prices.connector=smallrye-amqp
mp.messaging.incoming.prices.durable=true
```

**Aditional context**

Complete stacktrace:

```
SRMSG00234: Failed to emit a Message to the channel: java.lang.IllegalStateException: SRMSG00027: No subscriber found for the channel price-create
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.verify(AbstractEmitter.java:162)
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.emit(AbstractEmitter.java:144)
	at io.smallrye.reactive.messaging.extension.MutinyEmitterImpl.lambda$send$2(MutinyEmitterImpl.java:26)
	at io.smallrye.mutiny.operators.UniCreateWithEmitter.subscribing(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:30)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.lambda$subscribing$0(ContextPropagationUniInterceptor.java:48)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$1(SmallRyeThreadContext.java:530)
	at io.smallrye.mutiny.context.ContextPropagationUniInterceptor$2.subscribing(ContextPropagationUniInterceptor.java:48)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:54)
	at io.smallrye.mutiny.operators.UniSerializedSubscriber.subscribe(UniSerializedSubscriber.java:49)
	at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
	at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:70)
	at io.smallrye.reactive.messaging.extension.MutinyEmitterImpl.sendAndForget(MutinyEmitterImpl.java:43)
	at org.acme.amqp.PriceEmitter.emitPrice(PriceEmitter.java:22)
	at org.acme.amqp.PriceEmitter_ClientProxy.emitPrice(PriceEmitter_ClientProxy.zig:157)
	at org.acme.PriceResource.hello(PriceResource.java:18)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:136)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:40)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:832)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Comment by cescoffier** [comment] 2021-01-04 09:56
I just ran it with the latest Quarkus which give you a much better message at startup time:


```
...
	Suppressed: io.smallrye.reactive.messaging.wiring.TooManyUpstreamCandidatesException: 'OutgoingConnector{channel:'price-create', attribute:'mp.messaging.outgoing.price-create'}' supports a single upstream producer, but found 2: [Emitter{channel:'price-create'}, Emitter{channel:'price-create'}].
		at io.smallrye.reactive.messaging.wiring.Wiring$OutgoingConnectorComponent.validate(Wiring.java:360)
		at io.smallrye.reactive.messaging.wiring.Graph.<init>(Graph.java:69)
		at io.smallrye.reactive.messaging.wiring.Wiring.resolve(Wiring.java:151)
		at io.smallrye.reactive.messaging.wiring.Wiring_ClientProxy.resolve(Wiring_ClientProxy.zig:166)
		at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:165)
		... 23 more
```

You are using two emitters against the same channel, which would produce an incorrect topology as the connector does allow a single "source". 

The workaround, until we add the "merge" feature in connector is to create have a method like this:

```java
    @Incoming("price-gen")
    @Outgoing("price-create")
    @Merge
    public double merge(double d) {
        return d;
    }
```

So, you end up with:

```java
@ApplicationScoped
public class PriceEmitter {
    @Inject
    @Channel("price-gen")
    Emitter<Double> priceEmitter;

    @Inject
    @Channel("price-gen")
    MutinyEmitter<Double> priceMutinyEmitter;

    public void emitPrice(Double price) {
        priceEmitter.send(price);
        priceMutinyEmitter.sendAndForget(price * 10);
    }

	// Just here to merge both emitters so the connector gets a single source.
    @Incoming("price-gen")
    @Outgoing("price-create")
    @Merge
    public double merge(double d) {
        return d;
    }
}
```

**Comment by cescoffier** [comment] 2021-01-04 09:58
I have created https://github.com/smallrye/smallrye-reactive-messaging/issues/920 to track the _merge_ support on connectors.

**Comment by cescoffier** [comment] 2021-01-04 09:59
Closing as it's now tracked in the upstream project.

**Comment by cescoffier** [comment] 2021-01-04 10:00
(marking it as won't fix as it won't be fixed in quarkus per se :-))

**Closed by cescoffier** 2021-01-04 09:59 UTC
Labels: area/mutiny, area/smallrye, kind/bug

**Comment by tcerdaITBA** [comment] 2021-01-05 13:13
@cescoffier thank you very much for your response. 

I believe the issue with the two emitters on the same channel is a different one from the one I am mentioning. If the `Emitter` is deleted and only the `MutinyEmitter` exists, and therefore only a single emitter exists for the channel, the issue I described occurs. I have updated the code and removed the `Emitter`. Basically now the code is:

```java
@ApplicationScoped
public class PriceEmitter {
    @Inject
    @Channel("price-create")
    MutinyEmitter<Double> priceMutinyEmitter;

    public void emitPrice(Double price) {
        priceMutinyEmitter.sendAndForget(price * 10);
    }
}
```

Could you take another look at it? Maybe there is something I am missing. Thank you very much!

**Comment by cescoffier** [comment] 2021-01-05 14:10
Let me have another look. I believed I tried this.

**Comment by etal2** [comment] 2021-01-05 15:12
I have the same issue with a single emitter. Routing it through a local channel works as a workaround but its not ideal.

**Comment by cescoffier** [comment] 2021-01-05 15:52
I've good and bad news.

The bad news: yes, that's a bug, I was able to reproduce it with the reproducer.
The good news: it's already fixed in _master_.

**Comment by javadevmtl** [comment] 2021-01-21 20:21
I' m not sure if this is the same issue but I cannot seem to share Smallrye messaging destination between 2 producers. Initially I got the same above error and was pointed to this bug here.

I just tried 1.11.0 and I'm getting `javax.enterprise.inject.spi.DeploymentException: Wiring error(s) detected in application.`

This is what I'm trying...

```
@Path("/my-path")
public class MyResource {
    @Inject
    @Channel("my-out") // <--- Can't be shared with the below consumer.
    Emitter<MyRequest> myEmitter;


    @Path("/v1/action/_my")
    @POST
    @Produces(MediaType.TEXT_PLAIN)
    public void my(MyRequest request) {
        LOG.debug("Received my: {}", request);

        Message<MoRequest> kafkaRequest = Message.of(request);
        OutgoingKafkaRecordMetadata<String> metadata = OutgoingKafkaRecordMetadata.<String>builder()
                .withKey(request.getFoo())
                .build();

        myEmitter.send(kafkaRequest.addMetadata(metadata));
    }
}


@ApplicationScoped
public class MyDeadLetterProcessor {
    @SuppressWarnings("unchecked")
    @Incoming("my-dlq")
//    @Outgoing("my-back") <------ This works. The channel is configure to write to the same shared topic.
    @Outgoing("my-out") // <------ This gives wirring error!
    public Uni<Message<MyRequest>> dead(Message<MoRequest> payload) {
        MyRequest rejected = payload.getPayload();
        LOG.debug("Processing dead letter message: {}", rejected);

        MyRequest request = new MyRequest(rejected.getFoo(), rejected.getBar(),
                rejected.getBaz(), "Back from the dead!"
        );


        // Do some extra retry logic type stuff here...

        LOG.debug("Transformed: {}", request);

        return Uni.createFrom().item(Message.of(request)).onItem().delayIt().by(Duration.ofSeconds(20));
    }
}
```

**Comment by cescoffier** [comment] 2021-01-22 06:47
I don't believe it's the same bug, do you have the complete stack trace (including the suppressed exception).

**Comment by javadevmtl** [comment] 2021-01-22 14:38
Here is the error on 1.10.5 and below it is the 1.11.0 error...

Behaviour is a bit different between both versions. This exception gets thrown when I try to write to Kafka using the emitter. While for 1.11.0 the wiring exception gets thrown at startup...
```
2021-01-22 09:27:14,448 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /my-api/v1/action/_my failed, error id: 6f2fc23b-fbe5-4530-8972-4bb717ed89be-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalStateException: SRMSG00027: No subscriber found for the channel mo-out
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:136)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:40)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:97)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.IllegalStateException: SRMSG00027: No subscriber found for the channel mo-out
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.verify(AbstractEmitter.java:162)
	at io.smallrye.reactive.messaging.extension.AbstractEmitter.emit(AbstractEmitter.java:144)
	at io.smallrye.reactive.messaging.extension.EmitterImpl.send(EmitterImpl.java:45)
	at com.xxxxxx.resource.MyResource.mo(MyResource.java:54)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 20 more
```

1.11.0

This throws at startup and Quakus quits.
```
2021-01-22 09:32:52,173 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): javax.enterprise.inject.spi.DeploymentException: Wiring error(s) detected in application.
	at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:168)
	at io.smallrye.reactive.messaging.extension.MediatorManager_ClientProxy.start(MediatorManager_ClientProxy.zig:282)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle.onApplicationStart(SmallRyeReactiveMessagingLifecycle.java:20)
	at io.quarkus.smallrye.reactivemessaging.runtime.SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.notify(SmallRyeReactiveMessagingLifecycle_Observer_onApplicationStart_4e8937813d9e8faff65c3c07f88fa96615b70e70.zig:111)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:69)
	at io.quarkus.arc.runtime.LifecycleEventRunner.fireStartupEvent(LifecycleEventRunner.java:23)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:60)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy_0(LifecycleEventsBuildStep$startupEvent-858218658.zig:81)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent-858218658.deploy(LifecycleEventsBuildStep$startupEvent-858218658.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:904)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
	Suppressed: io.smallrye.reactive.messaging.wiring.TooManyUpstreamCandidatesException: 'OutgoingConnector{channel:'my-out', attribute:'mp.messaging.outgoing.my-out'}' supports a single upstream producer, but found 2: [Emitter{channel:'my-out'}, ProcessingMethod{method:'dead', incoming:'my-dlq', outgoing:'my-out'}].
		at io.smallrye.reactive.messaging.wiring.Wiring$OutgoingConnectorComponent.validate(Wiring.java:360)
		at io.smallrye.reactive.messaging.wiring.Graph.<init>(Graph.java:69)
		at io.smallrye.reactive.messaging.wiring.Wiring.resolve(Wiring.java:151)
		at io.smallrye.reactive.messaging.wiring.Wiring_ClientProxy.resolve(Wiring_ClientProxy.zig:166)
		at io.smallrye.reactive.messaging.extension.MediatorManager.start(MediatorManager.java:165)
		... 22 more

```

**Comment by cescoffier** [comment] 2021-01-22 15:48
Here is the issue:
	Suppressed: io.smallrye.reactive.messaging.wiring.TooManyUpstreamCandidatesException: 'OutgoingConnector{channel:'my-out', attribute:'mp.messaging.outgoing.my-out'}' supports a single upstream producer, but found 2: [Emitter{channel:'my-out'}, ProcessingMethod{method:'dead', incoming:'my-dlq', outgoing:'my-out'}].

There is an open issue to allows _connectors_ (as `my-out` is managed by a connector) to _merge_ multiple upstreams. However, until the next version, you will need to add:

```java
@Incoming("my-out")
@Outgoing("my-out-from-connector")
@Merge
public String justMerge(String s) { return s; }
```

You will need to rename the channel in your configuration to `my-out-from-connector`

**Comment by javadevmtl** [comment] 2021-01-22 16:02
What's the @Merge for? Also to not my @Incoming for me is different then my-out.

**Comment by cescoffier** [comment] 2021-01-22 18:24
@Merge allows consuming messages from multiple producers, in your case the emitter and the method.

**Comment by javadevmtl** [comment] 2021-01-22 19:11
Ah ok, because I'm just using @Outgoing("my-out-from-connector") without @Merge and it seems to work.
