### ISSUE TITLE
Support folded style yaml configuration

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#20508] opened 2021-10-01 15:57 UTC
### Description

Given an `application.yaml` and the following code:

```
    @ConfigProperty(name = "a.b.c.d")
    String prop;
```

I would like to be able to write:
```
a.b:
  c.d: Hello RESTEasy
```

or:
```
a.b.c.d: Hello RESTEasy
```

and not just the full hierarchy:
```
a:
  b:
    c:
      d: Hello RESTEasy
```

it makes it a lot easier to read and maintain.

another example:

```
quarkus:
  security.users.embedded:
    enabled: true
    plain-text: true
    users:
      scott: jb0ss
      stuart: test
      jdoe: p4ssw0rd
      noadmin: n0Adm1n
    roles:
      scott: Admin,admin,Tester,user
      stuart: admin,user
      jdoe: NoRolesUser
      noadmin: user
```

instead of:

```
quarkus:
  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          scott: jb0ss
          stuart: test
          jdoe: p4ssw0rd
          noadmin: n0Adm1n
        roles:
          scott: Admin,admin,Tester,user
          stuart: admin,user
          jdoe: NoRolesUser
          noadmin: user
```

/cc @radcortez

**Comment by radcortez** [comment] 2021-10-01 17:33
Closing this one because I believe it is a duplicate of https://github.com/quarkusio/quarkus/issues/11744. Please contribute there, or if you believe that is something different please reopen it again.

**Closed by radcortez** 2021-10-01 17:33 UTC
Labels: kind/enhancement, area/config
