### ISSUE TITLE
Broken encoding of data retrieved from MS SQL via reactive hibernate

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#19539] opened 2021-08-20 13:02 UTC
### Describe the bug

If data was put into a mssql database via direct sql query(e.g. by using vertx pool or file in quarkus.hibernate-orm.sql-load-script system property) and was retrieved via hibernate reactive session, then all non-ASCII symbols in it will be replaced by either corresponding ASCII symbols("Č"->"C") or with some garbage.

### Expected behavior

Any data should be retrieved the same as it was put in the database

### Actual behavior

Data gets corrupted

### How to Reproduce?

Reproducer: `https://github.com/fedinskiy/quarkus`, branch `reproducer/mssql-encoding`
How to run: `mvn clean verify -pl io.quarkus:quarkus-integration-test-hibernate-reactive-mssql -Dtest-containers -Dstart-containers`

File HibernateReactiveMsSQLTest contains several tests:
vertxQuery — data is put to the database via MSSQLPool.query and retrieved via Mutiny.Session.find. Fails
vertxRetrieval — data is put to and retrieved from the database via  MSSQLPool.query. Fails
persisted —  data is put to the database via Mutiny.Session.persist and retrieved via Mutiny.Session.find. Succeeds
imported —  data is put to the database via `quarkus.hibernate-orm.sql-load-script` Quarkus property and retrieved via Mutiny.Session.find. Fails
jdbc — data is put to the database via `quarkus.hibernate-orm.sql-load-script` Quarkus property and retrieved via jdbc. Succeeds
sanity — send data over the network without accessing the DB

### Output of `uname -a` or `ver`

5.13.8-200.fc34.x86_64

### Output of `java -version`

11.0.11

### Quarkus version or git rev

d67f466512f15901a78f0a63e36560b1830b24ff

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by yrodiere** [comment] 2021-09-01 07:49
@DavideD @gavinking You might be interested in this ^

No sure it's Reactive-specific, though; maybe ORM only supports ASCII for the import script? That would be surprising...

**Comment by DavideD** [comment] 2021-09-01 08:00
Thanks @yrodiere, I will have a look

**Comment by DavideD** [comment] 2021-09-07 15:57
My understanding of this issue is that storing the right encoding in MSSQL Server is a pain: https://stackoverflow.com/questions/12512687/how-to-use-utf-8-collation-in-sql-server-database.

It seems that the encoding used for the column changes based on the type of the column.
Hibernate Reactive uses `varchar` as default, but you can change it using the `@Column` annotation:
```
@Column(name = "name", columnDefinition="nvarchar(40)")
```

I don't know what's the right configuration or schema to make this work with your use case.

Anyway, the issue doesn't seem related to the connection drivers (I've tested it with JDBC and Vert.x).
It seems related to the configuration of the database.

**Comment by DavideD** [comment] 2021-09-07 16:13
> Anyway, the issue doesn't seem related to the connection drivers (I've tested it with JDBC and Vert.x).

What I mean here is that I've replicated the issue but and saw that the returned value changes based on the type of the column.

**Comment by Sanne** [comment] 2022-01-07 11:28
@DavideD could you add a test for this? Then we could close it.

**Comment by DavideD** [comment] 2022-01-07 11:34
What kind of test do you expect here? Something that checks that if the column type is correct the value is returned as expected?

**Comment by Sanne** [comment] 2022-01-07 11:35
yes, showcasing we can store && load accented characters correctly

**Comment by DavideD** [comment] 2022-01-10 14:44
Please, assign this issue to me. Thanks

**Comment by DavideD** [comment] 2022-01-21 19:56
See PR: https://github.com/quarkusio/quarkus/issues/19539

**Closed** 2022-01-24 11:14 UTC
Labels: kind/bug, area/persistence, area/hibernate-reactive

**Comment by gavinking** [comment] 2022-01-24 11:23
I don't see how this problem could possibly be the fault of Hibernate Reactive.

IIRC SQL Server is a NationalizedCharacterSupport.EXPLICIT database, so if you're using the schema export tool you might need to  set the config property that enables use of NVARCHAR.

But I'm not sure because not at my desk right now.

**Comment by DavideD** [comment] 2022-01-24 11:41
Interesting, I didn't know that.
The problem is that setting:
```
configuration.setProperty( AvailableSettings.USE_NATIONALIZED_CHARACTER_DATA, "true" );
```

Causes UnsupportedOperationException in Hibernate Reactive. I will create an issue

**Comment by DavideD** [comment] 2022-01-24 11:42
@gavinking I think that's what you meant? Isn't it?

**Comment by gavinking** [comment] 2022-01-24 11:43
Yes, that's what I meant.

**Comment by gavinking** [comment] 2022-01-24 12:24
> Causes `UnsupportedOperationException` in Hibernate Reactive.

Oh, I see: we didn't implement `setNString()`.

So that setting has two effects:

1. it makes schema export use `NVARCHAR` by default, and
2. it _unnecessarily_, I believe, but _reasonably_, makes Hibernate use `setNString()` instead of `setString()`.

But because we never turned it on before we had no reason to implement `setNString()`.

Anyway, that's really trivial to fix, I suppose.

**Comment by gavinking** [comment] 2022-01-24 12:25
> you can change it using the `@Column` annotation:
> 
> ```
> @Column(name = "name", columnDefinition="nvarchar(40)")
> ```

So this is the right workaround for now, until we fix the bug that @DavideD found.

**Comment by gavinking** [comment] 2022-01-24 14:47
> So this is the right workaround for now

Oh, Steve just reminded me that `@Nationalized` is an even better way to do this

**Comment by gavinking** [comment] 2022-01-25 11:19
And for completeness I should mention that if you set SQL Server to use the `_utf8` collation, you won't run into this issue at all. Now, that's not the default, but I assume without evidence that it's what most sane people do in practice.
