### ISSUE TITLE
Entity is loaded twice and error happens for the 2nd loading

### ISSUE THREAD

**Issue by jw941** [quarkusio/quarkus#12923] opened 2020-10-25 01:36 UTC
Hi,

We have migrated our project from Wildfly to Quarkus. When sometimes a fields is marked as eager loading or in a query with "join fetch", entities may be loaded twice and the exception happens for the 2nd loading. We'll have to make them all lazy loading or remove "fetch" in the query to workaround them. However, it never happened before the migration. And I have tried hard but still couldn't reproduce it in a small project.

The stack trace logs where it shows client[ID=127] were loaded twice and the exception throws at the 2nd time.
Exception shows
org.hibernate.TypeMismatchException: Provided id of the wrong type for class com.britensw.nyx.clients.core.model.Client. Expected: class java.lang.Integer, got class com.britensw.nyx.clients.core.model.Client

This is the detailed log.
 (executor-thread-203) select securityin0_.id as id2_0_0_, portfolio1_.id as id1_229_1_, securityin0_.account_class as account_1_0_0_, securityin0_.portfolio_id as portfol21_0_0_, portfolio1_.client_id as client_11_229_1_, portfolio1_.client_tag as client_t2_229_1_, portfolio1_.default_management_group_subscription as default12_229_1_, portfolio1_.disposal_method as disposal3_229_1_, portfolio1_.end_date as end_date4_229_1_, portfolio1_.locked_year as locked_y5_229_1_, portfolio1_.long_term_yield_requirement as long_ter6_229_1_, portfolio1_.purchase_allowed as purchase7_229_1_, portfolio1_.roa_date as roa_date8_229_1_, portfolio1_.sale_allowed as sale_all9_229_1_, portfolio1_.start_date as start_d10_229_1_ from pluto.account securityin0_ inner join pluto.portfolio portfolio1_ on securityin0_.portfolio_id=portfolio1_.id cross join pluto.client client4_ where securityin0_.account_class=6 and portfolio1_.client_id=client4_.id and securityin0_.account_class=? and (securityin0_.id in (select account2_.income_account from pluto.account account2_ cross join pluto.account account3_ where account2_.account_class in (11, 40, 37, 25, 21, 32, 10, 30, 29, 14, 22, 28, 13, 36, 44, 3, 20, 27, 33, 17, 7, 46, 39, 15, 47, 42, 34, 45, 26, 19, 9, 6, 38, 24, 43, 41, 23, 4, 8, 2, 35, 12) and account2_.income_account=account3_.id and account2_.account_class=? and account2_.security=?)) and securityin0_.portfolio_id=? and (client4_.date_left is null) and client4_.example_client=false
2020-10-19 10:28:43,278 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result set row: 0
2020-10-19 10:28:43,278 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result row: EntityKey[com.britensw.nyx.portfolio.model.accounts.SecurityIncomeAccount#653807], EntityKey[com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,278 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result set row: 1
2020-10-19 10:28:43,278 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result row: EntityKey[com.britensw.nyx.portfolio.model.accounts.SecurityIncomeAccount#652135], EntityKey[com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving attributes for [com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `brokerAccounts` : value = <un-fetched>
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `brokerAccounts`
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `client` : value = 127
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`client`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `clientTag` : value = WHOLE_SALE
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`clientTag`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `defaultManagementGroupSubscription` : value = 90
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`defaultManagementGroupSubscription`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `disposalMethod` : value = MINIMISE_GAIN
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`disposalMethod`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `endDate` : value = null
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`endDate`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `lockedYear` : value = null
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`lockedYear`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `longTermYieldRequirement` : value = null
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`longTermYieldRequirement`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroupSubscriptions` : value = <un-fetched>
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `managementGroupSubscriptions`
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `purchaseAllowed` : value = true
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`purchaseAllowed`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `regularPayments` : value = <un-fetched>
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `regularPayments`
2020-10-19 10:28:43,278 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `roaDate` : value = null
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`roaDate`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `saleAllowed` : value = true
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`saleAllowed`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `startDate` : value = 2005-07-01
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`startDate`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Adding entity to second-level cache: [com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Done materializing entity [com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving attributes for [com.britensw.nyx.portfolio.model.accounts.SecurityIncomeAccount#652135]
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `accountClass` : value = SECURITY_INCOME_ACCOUNT
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`accountClass`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `accountTransactions` : value = <un-fetched>
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `accountTransactions`
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `clientDocuments` : value = <un-fetched>
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `clientDocuments`
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `portfolio` : value = 116
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`portfolio`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `securityAccount` : value = 652135
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`securityAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.loa.Loader] (executor-thread-203) Loading entity: [com.britensw.nyx.portfolio.model.accounts.SecurityAccount#652135]
2020-10-19 10:28:43,279 DEBUG [org.hib.SQL] (executor-thread-203) select securityac0_.id as id2_0_1_, securityac0_.account_class as account_1_0_1_, securityac0_.portfolio_id as portfol21_0_1_, securityac0_.broker_account as broker_33_0_1_, securityac0_.capital_gain_account as capital34_0_1_, securityac0_.drp_account as drp_acc35_0_1_, securityac0_.frozen_till as frozen_16_0_1_, securityac0_.import_allowed as import_17_0_1_, securityac0_.income_account as income_28_0_1_, securityac0_.management_group_subscription as managem24_0_1_, securityac0_.manual_tax_calculation as manual_18_0_1_, securityac0_.security as securit36_0_1_, securityac0_.srn as srn19_0_1_, securityac0_.warrant_liability as warrant37_0_1_, management1_.id as id1_186_0_, management1_.bank_account_id as bank_acc6_186_0_, management1_.default_broker_account as default_7_186_0_, management1_.days_cash_reserve as days_cas2_186_0_, management1_.management_group as manageme8_186_0_, management1_.minimum_trade_size as minimum_3_186_0_, management1_.name as name4_186_0_, management1_.portfolio as portfoli9_186_0_, management1_.reportable as reportab5_186_0_ from pluto.account securityac0_ left outer join pluto.management_group_subscription management1_ on securityac0_.management_group_subscription=management1_.id where securityac0_.income_account=? and securityac0_.account_class=4
2020-10-19 10:28:43,279 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result set row: 0
2020-10-19 10:28:43,279 DEBUG [org.hib.loa.Loader] (executor-thread-203) Result row: EntityKey[com.britensw.nyx.portfolio.model.ManagementGroupSubscription#228], EntityKey[com.britensw.nyx.portfolio.model.accounts.SecurityAccount#652136]
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving attributes for [com.britensw.nyx.portfolio.model.ManagementGroupSubscription#228]
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `bankAccount` : value = null
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`bankAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,279 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `brokerAccount` : value = null
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`brokerAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `brokerAccounts` : value = <un-fetched>
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `brokerAccounts`
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `daysCashReserve` : value = 90
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`daysCashReserve`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroup` : value = 2
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`managementGroup`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroupMasterPortfolios` : value = <un-fetched>
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `managementGroupMasterPortfolios`
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroupSubscriptionAssetClassFreezes` : value = <un-fetched>
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `managementGroupSubscriptionAssetClassFreezes`
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroupSubscriptionSecurityFreezes` : value = <un-fetched>
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `managementGroupSubscriptionSecurityFreezes`
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `minimumTradeSize` : value = null
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`minimumTradeSize`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `name` : value = null
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`name`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `portfolio` : value = 116
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`portfolio`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `reportable` : value = true
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`reportable`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Adding entity to second-level cache: [com.britensw.nyx.portfolio.model.ManagementGroupSubscription#228]
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Done materializing entity [com.britensw.nyx.portfolio.model.ManagementGroupSubscription#228]
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving attributes for [com.britensw.nyx.portfolio.model.accounts.SecurityAccount#652136]
2020-10-19 10:28:43,280 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `accountClass` : value = SECURITY_ACCOUNT
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`accountClass`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `accountTransactions` : value = <un-fetched>
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `accountTransactions`
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `clientDocuments` : value = <un-fetched>
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `clientDocuments`
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `portfolio` : value = 116
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`portfolio`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `brokerAccount` : value = 80
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`brokerAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `capitalGainsAccount` : value = null
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`capitalGainsAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `drpAccount` : value = null
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`drpAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `frozenTill` : value = null
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`frozenTill`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `importAllowed` : value = true
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`importAllowed`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `incomeAccount` : value = 652135
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`incomeAccount`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `managementGroupSubscription` : value = 228
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`managementGroupSubscription`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `manualTaxCalculation` : value = false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`manualTaxCalculation`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `security` : value = 24441
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`security`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `srn` : value = null
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`srn`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `stopLosses` : value = <un-fetched>
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `stopLosses`
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `warrantLiability` : value = null
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`warrantLiability`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Adding entity to second-level cache: [com.britensw.nyx.portfolio.model.accounts.SecurityAccount#652136]
2020-10-19 10:28:43,281 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Done materializing entity [com.britensw.nyx.portfolio.model.accounts.SecurityAccount#652136]
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.jdb.int.JdbcCoordinatorImpl] (executor-thread-203) Skipping aggressive release due to registered resources
2020-10-19 10:28:43,282 DEBUG [org.hib.loa.Loader] (executor-thread-203) Done entity load
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Adding entity to second-level cache: [com.britensw.nyx.portfolio.model.accounts.SecurityIncomeAccount#652135]
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Done materializing entity [com.britensw.nyx.portfolio.model.accounts.SecurityIncomeAccount#652135]
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving attributes for [com.britensw.nyx.portfolio.model.Portfolio#116]
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `brokerAccounts` : value = <un-fetched>
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Resolving <un-fetched> attribute : `brokerAccounts`
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Processing attribute `client` : value = Client [ID: 127]
2020-10-19 10:28:43,282 DEBUG [org.hib.eng.int.TwoPhaseLoad] (executor-thread-203) Attribute (`client`)  - enhanced for lazy-loading? - false
2020-10-19 10:28:43,282 DEBUG [org.hib.res.jdb.int.LogicalConnectionManagedImpl] (executor-thread-203) Initiating JDBC connection release from afterStatement
2020-10-19 10:28:43,283 DEBUG [org.hib.res.jdb.int.LogicalConnectionManagedImpl] (executor-thread-203) Initiating JDBC connection release from afterTransaction
2020-10-19 10:28:43,283 DEBUG [org.hib.eng.tra.int.TransactionImpl] (executor-thread-203) TransactionImpl created on closed Session/EntityManager
2020-10-19 10:28:43,283 DEBUG [org.hib.eng.tra.int.TransactionImpl] (executor-thread-203) On TransactionImpl creation, JpaCompliance#isJpaTransactionComplianceEnabled == false
2020-10-19 10:28:43,290 ERROR [io.und.req.io] (executor-thread-203) Exception handling request 2c0a1f64-46ce-43e2-9367-26c0dcc24f1b-3 to /rest/clients/portfolio/transaction-search/match: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalArgumentException: org.hibernate.TypeMismatchException: Provided id of the wrong type for class com.britensw.nyx.clients.core.model.Client. Expected: class java.lang.Integer, got class com.britensw.nyx.clients.core.model.Client

**Comment by famod** [comment] 2020-10-25 14:25
Thanks for reporting this. I fear it will be hard or even impossible to track this down without a reproducer.

/cc @Sanne

**Comment by jw941** [comment] 2020-12-09 23:33
Hi @Sanne 
I have a reproducer but I am not sure if it is a Quarkus or a Hibernate bug. 

The project is in here:
https://github.com/jw941/hib-bug

Thanks for your help!

**Comment by kekbur** [comment] 2021-01-13 08:33
> I have a reproducer but I am not sure if it is a Quarkus or a Hibernate bug.

It's not a Hibernate bug. I have a minimal reproducing project here: [join-fetch-issue.zip](https://github.com/quarkusio/quarkus/files/5807356/join-fetch-issue.zip). The issue does not appear when the same query is run with the same entities and database contents using Hibernate only. See `PureHibernateBookTest.java` of the attached package.

To reproduce the issue, extract the package and run `./mvnw quarkus:dev` and then request `http://localhost:8080/books/broken`. To see the expected output, request `http://localhost:8080/books/working`.

**Comment by kekbur** [comment] 2021-01-13 20:36
I dug a bit deeper into this issue and found that the problem first appeared in version `1.7.0.CR1`. It was not present in `1.6.1.Final`.

**Comment by stuartwdouglas** [comment] 2021-01-14 05:26
@Sanne sounds like this may be another issue related to the build time proxy generation if it does not happen with regular hibernate?

**Comment by kekbur** [comment] 2021-06-02 12:54
The problem is still present on Quarkus version 2.0.0.CR2. Here is an updated reproducer: 
[join-fetch-issue.zip](https://github.com/quarkusio/quarkus/files/6584652/join-fetch-issue.zip)

**Comment by Sanne** [comment] 2021-06-02 18:54
@kekbur thanks for the reproducer - I just fetched it, and it seems tests are passing. Do I need to make any changes to experience the issue?

**Comment by Sanne** [comment] 2021-06-02 18:56
nevermind :) I hadn not seen your instructions above at https://github.com/quarkusio/quarkus/issues/12923#issuecomment-759292370

yes it fails, I'll have a look tomorrow. Thanks!

**Comment by yrodiere** [comment] 2021-07-13 06:52
@Sanne Are you still looking at this? Should I take over?

**Comment by Sanne** [comment] 2021-07-13 08:45
@yrodiere +1 for you to take it. Thanks!

**Comment by HonoluluHenk** [comment] 2021-07-15 00:47
In case you need another reproducer using Quarkus 2.0.2:

https://github.com/HonoluluHenk/quarkus-hibernate-entity-id-bug

just do a `./mvnw clean test`

**Comment by yrodiere** [comment] 2021-07-16 07:01
Thanks all for the reproducers. This *is* a bug in Hibernate ORM after all; it's just that it happens only with the `PADDED` batch-fetch-style, which is the default in Quarkus (don't ask me why; probably performance), but not in vanilla Hibernate ORM.

I created a bug report in ORM and will submit a fix: https://hibernate.atlassian.net/browse/HHH-14730

**Comment by yrodiere** [comment] 2021-07-16 07:15
Upstream reproducer and fix: https://github.com/hibernate/hibernate-orm/pull/4101

**Comment by yrodiere** [comment] 2021-07-16 08:10
Fix was merged. This will be fixed in Quarkus when we upgrade to ORM 5.5.4.Final (which must first be released).

**Comment by Sanne** [comment] 2021-07-16 09:18
Awesome, thanks @yrodiere !

**Closed** 2021-07-20 07:50 UTC
Labels: area/hibernate-orm, kind/bug
