### ISSUE TITLE
quarkus-swagger-ui logo.png not loaded

### ISSUE THREAD

**Issue by 1-alex98** [quarkusio/quarkus#39523] opened 2024-03-18 12:03 UTC
### Describe the bug

logo.png not loaded by io.quarkus:quarkus-swagger-ui into swagger ui docs

### Expected behavior

In the docs it is stated:

> Logo
To supply your own logo, you need to place a file called logo.png in src/main/resources/META-INF/branding.

See https://quarkus.io/guides/openapi-swaggerui#logo
I did so
![image](https://github.com/quarkusio/quarkus/assets/19996713/328c62a6-eb71-4a93-aedb-9f3962312664)
So I expect that image to be reflected in swagger ui.

### Actual behavior

![image](https://github.com/quarkusio/quarkus/assets/19996713/71e9fa34-126d-4058-9905-edebef978cca)
![image](https://github.com/quarkusio/quarkus/assets/19996713/fb22a408-2ea1-404f-83db-b020fe685cee)
It is not loaded tho

### How to Reproduce?

Using a static open api file 
![image](https://github.com/quarkusio/quarkus/assets/19996713/59d144d3-e011-4a59-8ab8-5a292bc82407)

application.properties content:

quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=docs

mp.openapi.scan.disable=true
quarkus.smallrye-openapi.info-title=Open Api for car insurance api

### Output of `java -version`

21.0.2

### Quarkus version or git rev

quarkusPlatformVersion=3.8.2

### Additional information

Tested that `quarkus.swagger-ui.path` makes no difference.

**Comment by phillip-kruger** [comment] 2024-03-18 12:22
What logo do you want to see ?

**Comment by phillip-kruger** [comment] 2024-03-18 12:26
Ok, there was a bug a version or do back. Did you try with the latest version?

**Comment by 1-alex98** [comment] 2024-03-18 16:55
I am using the latest version of quarkus excluding RC. Should I try the RC? Otherwise I fear the bug is back.

**Comment by phillip-kruger** [comment] 2024-03-18 19:10
Please try with the RC

**Comment by phillip-kruger** [comment] 2024-03-20 00:58
I tested this with the latest version and it's fix. Closing here. Please reopen if it's not fixed for you

**Comment by 1-alex98** [comment] 2024-03-20 22:23
Would like to reopen. I tested 3.8.3. There is does not work for me

**Comment by 1-alex98** [comment] 2024-03-20 22:23
![Screenshot_20240320_232333](https://github.com/quarkusio/quarkus/assets/19996713/c335353f-2e05-4d7f-98bd-c878bbc44fed)

**Comment by phillip-kruger** [comment] 2024-03-20 22:24
Please test with 3.9 (still CR).

**Comment by 1-alex98** [comment] 2024-03-20 22:45
[3.9.0.CR2](https://github.com/quarkusio/quarkus/releases/tag/3.9.0.CR2)

**Comment by 1-alex98** [comment] 2024-03-20 22:47
![Screenshot_20240320_234535](https://github.com/quarkusio/quarkus/assets/19996713/46a01448-e860-4326-8f01-7bccf4777cc1)
well ...

**Comment by phillip-kruger** [comment] 2024-03-20 22:49
Are you sure this is not browser cache ?

**Comment by 1-alex98** [comment] 2024-03-20 22:56
Pretty sure. Also here is the super easy way on how to reproduce:

Need to read upside down sorry
![Screenshot_20240320_235551](https://github.com/quarkusio/quarkus/assets/19996713/f1b48f7f-b4cc-41ac-966b-4417c37b2505)
![Screenshot_20240320_235527](https://github.com/quarkusio/quarkus/assets/19996713/4e100118-e96f-4f1e-a606-7bd8eac69931)
![Screenshot_20240320_235306](https://github.com/quarkusio/quarkus/assets/19996713/9fda7be0-6668-4411-b188-27c15f248ba9)
![Screenshot_20240320_235226](https://github.com/quarkusio/quarkus/assets/19996713/74f75c0e-952f-4144-b0e1-b88876e15319)
![Screenshot_20240320_235141](https://github.com/quarkusio/quarkus/assets/19996713/33dd11dc-3cf2-4c02-afbe-f8a29282234f)
![Screenshot_20240320_235122](https://github.com/quarkusio/quarkus/assets/19996713/854c8719-b01a-4126-9926-61712c310924)

**Comment by phillip-kruger** [comment] 2024-03-20 22:59
Do you run in dev mode or prod ? (java -jar)

**Comment by 1-alex98** [comment] 2024-03-20 23:01
dev
```
2024-03-21 00:00:26,909 INFO  [io.quarkus] (Quarkus Main Thread) logobug 1.0-SNAPSHOT on JVM (powered by Quarkus 3.9.0.CR2) started in 1.580s. Listening on: http://localhost:8080
2024-03-21 00:00:26,912 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2024-03-21 00:00:26,913 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, smallrye-context-propagation, smallrye-openapi, swagger-ui, vertx]
```

**Comment by 1-alex98** [comment] 2024-03-20 23:01
Content of application.properties can also be empty.

**Comment by 1-alex98** [comment] 2024-03-20 23:04
Run with `./gradlew quarkusDev` or with IntelliJ results in the same thing tho

**Comment by phillip-kruger** [comment] 2024-03-20 23:06
Ok, I can not recreate this with a basic mvn app. I can not imagine that this is gradle, but that seems to be the only difference. Can you share a small reproducer ?

**Comment by phillip-kruger** [comment] 2024-03-20 23:07
![image](https://github.com/quarkusio/quarkus/assets/6836179/09e60459-9d1a-420a-94cc-d47161e85ed6)

**Comment by 1-alex98** [comment] 2024-03-20 23:08
https://github.com/1-alex98/logobug

**Comment by phillip-kruger** [comment] 2024-03-20 23:09
Thanks, I'll get back to you

**Comment by 1-alex98** [comment] 2024-03-20 23:09
Thank you so much for all your effort :heart:

**Comment by phillip-kruger** [comment] 2024-03-20 23:57
I can recreate this with your reproducer. The only difference is Gradle (vs maven that I used). I am looking into this, but we might need help from @aloubyansky

**Comment by phillip-kruger** [comment] 2024-03-21 01:07
I have found and fixed this bug, thanks for reporting.

**Comment by snazy** [comment] 2024-03-21 16:18
@1-alex98 your path is wrong - must be `.../META-INF/branding/logo.png`

**Comment by phillip-kruger** [comment] 2024-03-21 22:41
Thanks ! Closing here.

**Closed by phillip-kruger** 2024-03-21 22:41 UTC
Labels: kind/bug, area/swagger-ui
