### ISSUE TITLE
Can't recover from database error with Panache Reactive

### ISSUE THREAD

**Issue by danielbobbert** [quarkusio/quarkus#25630] opened 2022-05-17 19:14 UTC
### Describe the bug

I am trying to develop a method that catches a database failure (specifically a constraint violation) and recover from that by returning some other value.
Uni.onFailure().recoverWithUni() works in principal (if I just return some value), but if I try to access the database again (reading) within my recovery function, that database read will not succeed but return the error from the previous write, just as if the last error was cached somewhere for that request, even though I performed the write in an explicit transaction.

### Expected behavior

Within onFailure().recoverWith() I should be able to read from the database successfully.

### Actual behavior

When trying to access the database during recovery, a previously raised failure is thrown again.

### How to Reproduce?

See attached maven project to reproduce the case.
Note: Sometimes both test cases fail because the app can't connect to the database (dev service too slow to startup?!), but that's another issue...
Normally, the first test case should succeed and the second will fail (even though it should succeed if recovery worked as expected).
This happens with Quarkus 2.9.1 but also with 2.8.x

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.4.0, arm64 (M1 MacBook Pro, Mac OS Monterey)

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.4

### Additional information

[panache-recovery-error.zip](https://github.com/quarkusio/quarkus/files/8710894/panache-recovery-error.zip)

**Comment by danielbobbert** [comment] 2022-05-18 09:12
Just figured out that manually clearing the session before accessing the database in my recovery block resolves the issue:
```Panache.getSession().invoke(Mutiny.Session::clear);```
So it really seems to be something about the internal state of the session. Still `session.clear()` is maybe a bit too much here, and I also think I shouldn't have to do this manually.

**Comment by FroMage** [comment] 2022-07-15 13:48
This sounds like a duplicate of #24499, no?

**Comment by DavideD** [comment] 2022-11-05 09:07
Yes, this is a duplicate.

Note that clearing the session might work in this specific case, but it's not the correct approach (the session should be recreated) and may lead to errors that are hard to debug.

**Comment by danielbobbert** [comment] 2022-11-16 17:53
Has this been fixed? I just tested with Quarkus 2.14.0.Final and the workaround doesn't seem to be necessary any longer.

**Comment by DavideD** [comment] 2022-11-16 18:21
This has not been fixed yet.
It might look like it works for your specific use-case but you shouldn't rely on this.

**Comment by geoand** [comment] 2024-09-20 11:04
@DavideD any idea if this has since been fixed?

**Comment by DavideD** [comment] 2024-09-20 12:56
I think we can close it because, as far as I understand, this is duplicate of #24499

**Comment by geoand** [comment] 2024-09-20 12:57
🙏🏽

**Closed by geoand** 2024-09-20 12:57 UTC
Labels: kind/bug, area/panache, area/hibernate-reactive, triage/needs-feedback
