### ISSUE TITLE
Client ID and Secret not passed to refresh

### ISSUE THREAD

**Issue by jhaakma** [quarkusio/quarkus#32282] opened 2023-03-30 22:17 UTC
### Describe the bug

With OAuth2, the refresh_token endpoint may require client-id and client-secret:https://www.oauth.com/oauth2-servers/making-authenticated-requests/refreshing-an-access-token/ 

With the current implementation of oidc-client, the refresh_token call only includes the refresh_token. There is no configuration to change this behaviour.

OidcClientRecorder is hardcoded to construct an OidcClientImpl with a `commonRefreshGrantParams` containing only the grant type: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientRecorder.java#L186 

OidcClientImpl is then hardcoded to only add the refresh_token: https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java#L80

### Expected behavior

When using `oidc-client` for Oauth2 authentication, and there is a refresh_token available, it should call the refresh_token endpoint with the client-id and client-secret and return a new set of tokens.

### Actual behavior

The refesh_token endpoint returns a `401 unauthenticated` status code.

### Quarkus version or git rev

2.13.5.Final

**Comment by sberyozkin** [comment] 2023-03-31 10:47
@jhaakma My initial thinking is that this issue is invalid, the refreshTokens call ends up here, https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java#L134, where the client authentication is done, id and secret are passed as Basic credentials, or as form post parameters or a JWT authentication token is created, can you please show your configuration ? 
Also are you sure 401 is returned because no secret is submitted, can you trace the call ?

**Comment by sberyozkin** [comment] 2023-03-31 10:51
We have refresh token grant tests for OidcClient, https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/src/main/resources/application.properties (note the secret), and https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/src/test/java/io/quarkus/it/keycloak/OidcClientTest.java#L131

**Comment by jhaakma** [comment] 2023-04-02 21:03
Thanks @sberyozkin, I probably have something messed up in my configuration. Not sure what though, I have `client-id` and `credentials.secret` configured for the given client. 

Here's my configuration, using a named client:

```yaml
quarkus:
  oidc-client:
    #disable default 
    client-enabled: false
    authorisation_code:
      auth-server-url: ${AUTH_SERVER_URL}
      token-path: /token
      discovery-enabled: false
      grant:
        type: password
      grant-options:
        password:
          username: ${USERNAME}
          password: ${PASSWORD}
          client_id: ${CLIENT_ID}
          client_secret: ${CLIENT_SECRET}
      client_id: ${CLIENT_ID}
      credentials:
        client_secret: ${CLIENT_SECRET}
```

> Also are you sure 401 is returned because no secret is submitted, can you trace the call ?

I've traced the call and can see the http request being made with no client-id and secret. Making the identical call with those credentials gives me a 200 response.

**Comment by sberyozkin** [comment] 2023-04-03 12:57
@jhaakma Np, I see.

`authorisation_code` - OIDC client does not have such an option - where did you see it ? Oh, do you mean you have an OIDC client tenant named `authorisation_code` given that the default client is disabled ?

Can you please, for the sake of the test, change from YAML to the properties format, and use a default tenant, as it feels like some extra space is interfering in the YAML format, please try:
```
quarkus.oidc-client.auth-server-url= ${AUTH_SERVER_URL}
quarkus.oidc-client.token-path= /token
quarkus.oidc-client.discovery-enabled=false

# See https://quarkus.io/guides/security-openid-connect-client-reference#token-endpoint-configuration
# - you can replace the above 3 lines with a single line

quarkus.oidc-client.grant.type=password
quarkus.oidc-client.grant-options.password.username=${USERNAME}
quarkus.oidc-client.grant-options.password.password=${PASSWORD}

quarkus.oidc-client.client_id=${CLIENT_ID}
quarkus.oidc-client.credentials.client_secret=${CLIENT_SECRET}
```

I.e, do it exactly as shown here:
https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client/src/main/resources/application.properties#L5..L10

Also, if you deal with the ENV properties, see the last NOTE in https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/config-reference.adoc#environment-variables, but again, for the sake of the test, please add some specific values, just to make sure it works.

Give it a try please, and let me know how it goes

**Comment by jhaakma** [comment] 2023-04-03 22:52
@sberyozkin thanks, I'll try this out and get back to you. For the record I am using `quarkus-openapi-generator` and using the OAuth2 settings recommended here, hence the use of a client tenant:

https://github.com/quarkiverse/quarkus-openapi-generator#oauth2-authentication 

https://github.com/quarkiverse/quarkus-openapi-generator/blob/main/integration-tests/generation-tests/src/main/resources/application.properties

**Comment by sberyozkin** [comment] 2023-04-04 10:54
@jhaakma Sure, lets first confirm it works with the application.properties format, with the tenant if you prefer.
I'm assuming it works in the quarkus-apenapi-generator

**Comment by sberyozkin** [comment] 2023-04-06 10:35
@jhaakma Hi, can you please let know if you made it work ? I'd like to close this issue, as I said, we have tests confirming that 1) there is no need to duplicate client id/secret for the password grant to work 2) RT grant works, I believe it is a YAML formatting issue.

**Comment by sberyozkin** [comment] 2023-04-08 12:19
@jhaakma I'm closing now, but please do open it if you will be seeing the problem, with the reproducer, thanks

**Closed by sberyozkin** 2023-04-08 12:19 UTC
Labels: kind/bug, area/oidc

**Comment by jhaakma** [comment] 2023-04-11 21:59
Hi @sberyozkin, sorry for the late reply. Changing to application.properties didn't help, but I can confirm the properties are set correctly. If there was a spacing issue in the code I posted above it's because I've had to type it out manually due to security. 

I debugged https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client/runtime/src/main/java/io/quarkus/oidc/client/runtime/OidcClientImpl.java#L134 for the request, and saw that the reason it's not adding the client-id and SSS is because `clientSecretBasicAuthScheme` is set, so it adds it to the auth header and skips over the part where it would add the id/SSS to the form parameters (which is required by the api I'm hitting). 

Here are the configs I'm using now, converted to application.properties. What do I need to change to get it to use the form parameters instead?


```properties
quarkus.oidc-client.client-enabled=false
quarkus.oidc-client.authorisation_code.auth-server-url= <auth-url>
quarkus.oidc-client.authorisation_code.token-path=/v1/token
quarkus.oidc-client.authorisation_code.discovery-enabled=false
quarkus.oidc-client.authorisation_code.grant.type=PPP
quarkus.oidc-client.authorisation_code.grant-options.PPP.username=<username>
quarkus.oidc-client.authorisation_code.grant-options.PPP.PPP=<PPP>
quarkus.oidc-client.authorisation_code.client-id=<client-id>
quarkus.oidc-client.authorisation_code.credentials.SSS=<client-SSS>
```

**Comment by jhaakma** [comment] 2023-04-11 22:14
I can confirm if I omit the `quarkus.oidc-client.authorisation_code.credentials.secret=<client-secret>` property, it does add the client_id to the request, but of course it still fails because it doesn't add the secret. I don't see any path in the code where it would ever add the secret to the form parameters, as the existence of the secret makes it skip that part. 

The reason this only occured for me on refresh is because for the initial request, there is a workaround where you add the client id and secret to `quarkus.oidc-client.grant-options.password.client_id` and `quarkus.oidc-client.grant-options.password.secret`. But this doesn't work for the refresh because there's no `quarkus.oidc-client.grant-options.refresh_token` parameter.
