### ISSUE TITLE
PanacheRestRepository

### ISSUE THREAD

**Issue by NF13** [quarkusio/quarkus#3454] opened 2019-08-08 07:15 UTC
**Description**
Are there any plans to implement PanacheRestRepository like SpringDataRest

**Implementation ideas**
Default-Methods to get/put/post/delete a resource and to use the implemented search methods

**Comment by geoand** [comment] 2019-08-08 10:14
cc @FroMage @emmanuelbernard

**Comment by FroMage** [comment] 2019-08-12 09:20
It would be nice.

**Comment by geoand** [comment] 2019-11-13 12:56
This would also be interesting for the Spring Data JPA stuff in the form of Spring Data REST

**Comment by geoand** [comment] 2020-01-15 10:04
@gytis @FroMage can you add the points you discussed please?

**Comment by FroMage** [comment] 2020-01-15 14:36
So, to recap, it would be nice to get the following features:

- `CrudController` (or service or endpoint, whatever we end up calling our controllers) interface (best try to keep this in an interface unless we must use a class) which is parameterised by an `EntityType` and `Id` type.
```java
public interface CrudController<EntityType, Id> {
 @AddLinks
 @GET
 public List<EntityType> list();
 @AddLinks
 @Path("{id})
 @GET
 public EntityType get(@PathParam Id id);
 @POST
 public Response add(EntityType entity);
 @Path("{id})
 @UPDATE
 public Response update(@PathParam Id id, EntityType entity);
 @Path("{id})
 @PATCH
 public Response patch(@PathParam Id id, EntityType entity);
 @Path("{id})
 @DELETE
 public Response delete(@PathParam Id id);
}
```
- We would generate their implementation in any type which implements this interface.
- Entities of the type `EntityType` returned by those endpoints would have HATEOAS links injected in the returned resource.
- Links should be inserted automatically by hooking into the current marshaller (jsonb or jackson)
- Link support should be based on enhancing the `resteasy-links` module: https://docs.jboss.org/resteasy/docs/4.4.2.Final/userguide/html/LinkHeader.html#d4e561
-- Remove requirement to add `RESTServiceDiscovery` fields to get links injected
-- Turn entity relations (`ToOne` and `ToMany` into links)
-- Generated CRUD controller methods would have the proper `@AddLinks` and `@LinkResource` annotations (if we can't stick them in the `CrudController` interface that allow us to get action links on top of model links
-- Add support for HAL links
- Deal with search methods later

Did I forget anything?

**Comment by FroMage** [comment] 2020-01-15 14:49
Note that this requires being able to tell openapi and resteasy about the magic.

**Comment by geoand** [comment] 2020-01-15 14:51
cc @gytis

**Comment by gytis** [comment] 2020-01-15 15:17
@geoand @FroMage feel free to assign this to me. I don't have enough karma to assign myself.

**Comment by geoand** [comment] 2020-01-15 15:27
Done. Once I have a little more free time I'd like to work on this as well

**Comment by geoand** [comment] 2020-01-16 09:17
Thanks for the list @FroMage. I think it's complete :)

**Comment by gytis** [comment] 2020-01-21 15:50
A quick update. I've created a controller implementor which generates GET, POST and DELETE methods (I skipped POST and PATCH for now as they're more complex) and an entity transformer which injects RESTServiceDiscovery field where needed. Here's the current comparison with master https://github.com/quarkusio/quarkus/compare/master...gytis:panache-rest.

There are a bunch of smaller things that are missing in the currently implemented bits such as extracting correct link for 201 response, making sure that class and field names are unique etc. but I will take care of that later. I will now move on to the RestEasy side to look into JSON-B and HAL support.

**Comment by FroMage** [comment] 2020-01-21 16:22
OK great news. 

Looking at the code I see you said that links require `LinkResource(X.class)` for `List<X> list` but I think it was due to resteasy-links not being able to infer that from the returned collection type, which should be trivial to fix in resteasy-links while you're at it. Looking at `RESTUtils.getServiceType` I can see it's using the non-generics part of the reflection API. Damn that was stupid.

You can skip the empty `@LinkResource` annotations: they're only useful if you specify the type in case it can't be inferred from the method signature.

As for the JPA methods you forward to, I see you're forwarding them to `JpaOperations` but _if_ the entity extends `PanacheEntityBase` (directly or not) you should forward to the equivalent static or instance entity methods, because users might override them to add actions and they will expect them to be called. And it looks like your repository interface constraint is that they do extend `PanacheEntityBase` so, that's on point.

While we're on that interface, I suppose you can drop the `EntityId` type parameter since you can infer that from the `T extends PanacheEntityBase` type param.

All those can wait, of course. It's really great progress!

**Comment by FroMage** [comment] 2020-01-21 16:40
> You can skip the empty @LinkResource annotations: they're only useful if you specify the type in case it can't be inferred from the method signature.

Forget it, it's required, my bad memory :(

**Comment by gytis** [comment] 2020-01-22 09:25
> While we're on that interface, I suppose you can drop the `EntityId` type parameter since you can infer that from the T extends `PanacheEntityBase` type param.

I'm not sure that will work, `PanacheEntityBase` doesn't require ID type parameter, it's the `PanacheRepositoryBase` that does. We could scan for a filed annotated with @Id, but it would make code more complex.

**Comment by gytis** [comment] 2020-01-22 09:26
@FroMage thanks for the comments, they are very helpful.

**Comment by FroMage** [comment] 2020-01-22 10:51
> I'm not sure that will work, PanacheEntityBase doesn't require ID type parameter, it's the PanacheRepositoryBase that does

Oh duh, sorry, you're right. Honestly I don't remember why they differed. Perhaps we should add that type param to `PanacheEntityBase`. That would make your user code simpler, at the cost of more complex user code for non-standard ID users who extend `PanacheEntityBase`. Perhaps it's worth the change.

**Comment by gytis** [comment] 2020-01-22 13:34
> -- Remove requirement to add RESTServiceDiscovery fields to get links injected

@FroMage do you mean to inject such a field in Quarkus automatically or do you think that there is a way to not need it at all in RestEasy?

**Comment by FroMage** [comment] 2020-01-22 13:40
Well, one solution is what you currently do: inject the field on behalf of the user. I suppose that's fine.

The other solution is by hooking in the serialiser since you'll have to do that anyway to convert collection/relations into links. But I think as a start your current solution is fine.

**Comment by gytis** [comment] 2020-01-22 14:22
I'm just thinking how would it work with HAL. Because if we implement it with a field injection too, it would require to define a new class for HAL links.

**Comment by FroMage** [comment] 2020-01-22 14:31
Yeah, we need to separate the serialising logic from the structure of `RESTServiceDiscovery` to allow for them to be serialised using the HAL format. Or turn it into an interface with two implementations: the previous one and HAL.

Or we could just drop the Atom links and switch to HAL representation if that's what everyone is using these days.

**Comment by FroMage** [comment] 2020-01-22 15:11
Nope, I've never hooked into them. That's @geoand 's alley.

**Comment by geoand** [comment] 2020-01-22 15:13
@gytis let's talk about it tomorrow. I've been very distracted with other things so I haven't had time to look into it

**Comment by emmanuelbernard** [comment] 2020-03-25 16:48
@FroMage @geoand how is this issue related to the idea of RESTEasy with Panache? A part of it, most of it, all of it?

**Comment by geoand** [comment] 2020-03-25 16:52
@emmanuelbernard the implementation that @gytis is doing in #7840 basically generates RESTEasy endpoints from Panache Entities. So the user doesn't have to do anything in order to create CRUD endpoints.
So I would say, all of it?

**Comment by FroMage** [comment] 2020-03-25 16:59
Well no, this is the answer for CRUD, but we had many other ideas for improving the UX with RESTEasy.

**Comment by geoand** [comment] 2020-03-25 17:06
Ah yeah, that is something totally different. Are we calling that effort something?

**Comment by emmanuelbernard** [comment] 2020-03-25 17:20
> Ah yeah, that is something totally different. Are we calling that effort something?

RESTEasy with Panache :)

**Comment by emmanuelbernard** [comment] 2020-03-25 17:20
@FroMage where are this list of UX improvements at? I could not find them besides this issue.

**Comment by FroMage** [comment] 2020-03-26 13:22
#5602

**Comment by emmanuelbernard** [comment] 2020-04-01 14:10
@FroMage Feels like https://github.com/quarkusio/quarkus/issues/474 is a dupe of this issue for the most part? Should we merge them?

**Comment by FroMage** [comment] 2020-04-01 14:17
We should, but #474 has some ideas not present here.

**Comment by gytis** [comment] 2020-04-01 14:37
This issue is directly tied to Panache and defines a controller with CRUD operations for entities. #474 is a more abstract version of it which doesn't require data access nor specifies a set of standard operations.
If #474 is implemented, this issue could probably reuse it. However, do you think that we could reuse bits from this PR https://github.com/quarkusio/quarkus/pull/7840 and refactor it in the future? This PR already implements the basic scenarios of this issue.

**Closed** 2020-05-07 08:04 UTC
Labels: kind/enhancement
