### ISSUE TITLE
Path on method partly matching path on other class results in 404

### ISSUE THREAD

**Issue by eijckron** [quarkusio/quarkus#41796] opened 2024-07-09 20:12 UTC
### Describe the bug

When a path on a method partly matches the path on another class requesting the endpoint results in a 404.

### Expected behavior

The correct endpoint is executed and a 200 is returned

### Actual behavior

404 is returned

### How to Reproduce?

Class HelloWorldOne
```Java
@ApplicationScoped
@Path("/helloworld")
public class HelloWorldOne {

    @GET
    @Path("/one")
    public String hello() {
        return "Hello World One!";
    }
}
```

Class HelloWorldTwo
```Java
@ApplicationScoped
@Path("/")
public class HelloWorldTwo {

    @GET
    @Path("/helloworld/two")
    public String hello() {
        return "Hello World Two!";
    }
}
```

Test class
```Java
@QuarkusTest
public class HelloWorldTest {

    @Test
    public void testHelloWorldOne() {
        given()
                .when().get("/helloworld/one")
                .then()
                .statusCode(200)
                .body(is("Hello World One!"));
    }

    @Test
    public void testHelloWorldTwo() {
        given()
                .when().get("/helloworld/two")
                .then()
                .statusCode(200)
                .body(is("Hello World Two!"));
    }
}
```

Both tests should succeed but testHelloWorldTwo fails with a 404

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

Java 21

### Quarkus version or git rev

3.2.12.Final and 3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment] 2024-07-10 07:50
Thanks for reporting. 

This is essentially a duplicate of #26496

**Closed by geoand** 2024-07-10 07:50 UTC
Labels: kind/bug, env/windows, triage/needs-triage

**Comment by eijckron** [comment] 2024-07-10 16:27
@geoand 26496 is similar but not the same. In this case there are 2 completely unique endpoints, so one is not an extension of the other. The issue is just the split for class / method that causes issues. If both HelloWorldTwo  is setup with the same path split as HelloWorldOne all works well.

**Comment by geoand** [comment] 2024-07-11 06:08
Indeed, but the root cause is the same :)
