### ISSUE TITLE
Lots of warning with kubernetes + kubernetes-config extension when compiling for native

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#34571] opened 2023-07-06 08:39 UTC
### Describe the bug

If a project uses both kubernetes and kubernetes-config extension and compiling for native, lots of warnings
`Warning: Could not resolve class io.fabric8.{knative,openshift}.someClasses for reflection configuration. Reason: java.lang.ClassNotFoundException: ` are shown.

### Expected behavior

Those warnings should not be shown

### Actual behavior

356 Lines of warnings are shown

### How to Reproduce?

1. Download an app with [the extensions](https://code.quarkus.io/?a=reproduce-warnings&b=GRADLE_KOTLIN_DSL&e=resteasy-reactive&e=resteasy-reactive-jackson&e=kubernetes&e=kubernetes-config) (resteasy+jackson only so a class exists).
2. extract to a directory and go into it
3. run `quarkus build --native --no-tests -Dquarkus.native.container-build=true`
4. observe the 

### Output of `uname -a` or `ver`

Linux SOMEHOST 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          11.0.19 (Ubuntu 11.0.19+7-post-Ubuntu-0ubuntu122.04.1) OS:           Linux 5.19.0-46-generic amd64

**Comment by geoand** [comment] 2023-07-06 08:42
cc @metacosm @manusa

**Comment by Sgitario** [comment] 2023-07-06 08:44
I think this is a duplicate of https://github.com/quarkusio/quarkus/issues/34213 (tho the title should be properly updated)

**Comment by geoand** [comment] 2023-07-06 08:45
@Sgitario in that case, please close this as a duplicate and update the title of the other issue as you see fit.

Thanks

**Comment by Sgitario** [comment] 2023-07-06 08:46
Closing as it's a duplicate of https://github.com/quarkusio/quarkus/issues/34213

**Closed by Sgitario** 2023-07-06 08:46 UTC
Labels: kind/bug, area/kubernetes
