### ISSUE TITLE
`EntityManager` is not injected

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5528] opened 2019-11-16 07:11 UTC
**Describe the bug**
`EntityManager` instance is not injected into @ApplicationScoped object so i'm having the following exception for ``:
```
...
12:02:31,107 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
...
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property entityManager has not been initialized
...
```

**Expected behavior**
`EntityManager` instance is injected and ready -to-use, no exception are thrown

**Actual behavior**
during `./mvnw compile quarkus:dev` i have the following exception
```
...
12:02:31,107 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.ExceptionInInitializerError
...
Caused by: kotlin.UninitializedPropertyAccessException: lateinit property entityManager has not been initialized
...
```
The app is shutdown.

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. cd NotesServerApp
3. git checkout 32c8240dfd6672471cdd73f613e092522fb6528e
4. ./gradlew publishToMavenLocal
5. cd app-quarkus
6. ./mvnw compile quarkus:dev

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:notes
quarkus.datasource.driver = org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
<img width="1445" alt="Снимок экрана 2019-11-16 в 12 07 33" src="https://user-images.githubusercontent.com/846671/68989498-b33e1500-0869-11ea-8691-462b1311389d.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Darwin MBP-Anton.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
* db [entity](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/infra-gateway-jpa/src/main/kotlin/name/antonsmirnov/notes/db/Note.kt#L7) is in [transitive module](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/pom.xml#L39) (having META-INF/beans.xml)
* [rest controllers](https://github.com/4ntoine/NotesServerApp/tree/issue-5-quarkus-maven/infra-rest-jax-rs/src/main/kotlin/name/antonsmirnov/notes/controller/rest) are in [transitive module](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/pom.xml#L44) (having META-INF/beans.xml)
* if commenting AddNoteController and ListNoteController i can run the app and [`Hello1Controller`](https://github.com/4ntoine/NotesServerApp/blob/issue-5-quarkus-maven/app-quarkus/src/main/kotlin/name/antonsmirnov/notes/controller/rest/Hello1Controller.kt) is available

**Comment by geoand** [comment] 2019-11-16 22:29
Is this similar to another issue you had opened @4ntoine ?

**Comment by 4ntoine** [comment] 2019-11-17 04:34
@geoand Hi, I'm still trying to make it working and I've created a couple of similar issue while doing that, but all of them are different from this one:
1. https://github.com/quarkusio/quarkus/issues/5488 - this was with Gradle (and the problem is in Quarkus Gradle plugin classloading) - waiting for it
2. https://github.com/quarkusio/quarkus/issues/5521 (Migrated to Maven. This was my misconfiguration - i had to explicitly mark transitive jar for analysis by Quarkus to find @Entity and configure EntityManager)
3. https://github.com/quarkusio/quarkus/issues/5526 (a bit different, but also related to this. This was also my misconfiguration - i had to explicitly mark transitive jar for analysis by Quarkus and configure REST controllers)

This issue - it's smth else that is still misconfigured/not working, so i wonder what else?

**Comment by 4ntoine** [comment] 2019-11-18 06:24
@geoand anything i can check (if i did it correctly) to save your time?

**Comment by 4ntoine** [comment] 2019-11-18 08:33
@geoand oh, that's strange. I will doublecheck today.

**Comment by geoand** [comment] 2019-11-18 08:46
Thanks

**Comment by 4ntoine** [comment] 2019-11-18 08:49
@geoand I forgot to commit/push the required changes, sorry. The revision should be `32c8240dfd6672471cdd73f613e092522fb6528e`

**Comment by geoand** [comment] 2019-11-18 08:51
Okay, I'll try it out later

**Comment by geoand** [comment] 2019-11-18 09:49
I was able to reproduce the problem. I'll update with more information soon.

**Comment by 4ntoine** [comment] 2019-11-18 09:50
Thank you. Let me know if you need any assistance

пн, 18 нояб. 2019 г., 14:49 Georgios Andrianakis <notifications@github.com>:

**Comment by geoand** [comment] 2019-11-18 10:08
It turns out to be a problem with how CDI is being used in the supplied code:

If you use something like:

```
@ApplicationScoped
open class QuarkusEntityManagerFactory {
    @Inject
    lateinit var entityManager: EntityManager
}

@ApplicationScoped
open class Configuration {

    @Produces
    open fun getJpaGateway(entityManagerFactory: QuarkusEntityManagerFactory): JpaGateway {
        val mapper = MapperImpl()
        return JpaGateway(entityManagerFactory.entityManager, mapper)
    }

    @Produces
    open fun getAddNoteUseCase(gateway: JpaGateway) = AddNoteImpl(gateway)

    @Produces
    open fun getListNotesUseCase(gateway: JpaGateway): ListNotes = ListNotesImpl(gateway)
}
```

everything works as expected.

Note that you can simplify things even more by removing `QuarkusEntityManagerFactory` completely and using something like:

```
    @Produces
    open fun getJpaGateway(entityManager: EntityManager): JpaGateway {
        val mapper = MapperImpl()
        return JpaGateway(entityManager, mapper)
    }
```

So I'm going to go ahead and close this since it's not a Quarkus bug. If you feel that this resolution is not correct, feel free to reopen and add more information.

Thanks

**Closed by geoand** 2019-11-18 10:08 UTC
Labels: bug

**Comment by 4ntoine** [comment] 2019-11-18 10:46
That's an interesting research. It looks like "everything that is involved in CDI should happen in scope of smth annotated with CDI annotations". So CDI framework was unable to understand that EM should be instantiated and injected during `val gateway = JpaGateway(QuarkusEntityManagerFactory().entityManager, mapper)` and it's not in CDI-annotated scope though it is later used in CDI-annotated scope.

**Comment by geoand** [comment] 2019-11-18 10:53
Yes exactly. The fact that you were creating `QuarkusEntityManagerFactory` on your own meant that CDI was never involved in the process for that class.

FWIW, this is not specific to CDI, but would be the same with any dependency injection framework / library (such as Spring or Guice)

**Comment by 4ntoine** [comment] 2019-11-18 14:13
@geoand were you able to access the controllers? I've applied your patch and i don't have Quarkus compile-time errors but the controllers are not registered (and thus unavailable)

**Comment by geoand** [comment] 2019-11-18 14:14
Yup, both `/hello1` and `/hello2` worked correctly

**Comment by 4ntoine** [comment] 2019-11-19 06:36
> Yup, both `/hello1` and `/hello2` worked correctly

Both worked before even without that [CDI-related ]changes (as both does not require EntityManager injected). AddNoteController and ListNotesController do not work. Update: i've made them working with additional changes

**Comment by geoand** [comment] 2019-11-19 06:47
@4ntoine what I meant was that without the changes I mentioned above the application wouldn't start but with them it did and the endpoints worked. 

Glad to hear you got the application working

**Comment by 4ntoine** [comment] 2019-11-19 06:51
@geoand Thanks for the support - it's absolutely awesome!

**Comment by geoand** [comment] 2019-11-19 07:02
You are welcome!
