### ISSUE TITLE
OpenAPI does not support the @BeanParam annotation

### ISSUE THREAD

**Issue by andrejpetras** [quarkusio/quarkus#2819] opened 2019-06-13 07:45 UTC
**Describe the bug**
The openapi does not support @BeanParam.
If the rest service method uses the @BeanParam this attribute is ignored in the generated openapi.yaml file.

**Expected behavior**
The openapi.yaml contains also the information from the @BeanParam parameter object.

**Actual behavior**
The @BeanParam is ignored and not generated in the openapi.yaml

**To Reproduce**
1. Create rest method with a @BeanParam parameter
2. Download openapi http://localhost:8080/openapi

**Comment by gsmet** [comment] 2019-06-13 09:50
@kenfinnigan @EricWittmann I think it's probably a bug in the SmallRye OpenAPI implementation?

**Comment by EricWittmann** [comment] 2019-06-13 11:57
Yes - this issue should be moved over to **smallrye-open-api**.

**Comment by gsmet** [comment] 2019-06-13 13:32
@EricWittmann I created https://github.com/smallrye/smallrye-open-api/issues/135 .

I let this issue open with the `upstream` label so that we think about upgrading SmallRye OpenAPI as soon as the issue is fixed.

Thanks.

**Comment by ia3andy** [comment] 2019-08-05 15:21
@gsmet it seems the referenced issue is fixed, but I still experienced this problem using `@BeanParam` with `@QueryParam` inside.

Openapi: http://editor.swagger.io/?url=https://code.quarkus.io/openapi
Source: https://github.com/fabric8-launcher/launcher-quarkus/blob/master/src/main/kotlin/io/launcher/quarkus/model/QuarkusProject.kt

**Comment by MikeEdgar** [comment] 2019-10-05 10:54
@ia3andy , can you re-post your example? This should be working.

**Comment by MikeEdgar** [comment] 2019-10-30 11:44
This issue is fixed - the parameters from the `@BeanParam` are present in https://editor.swagger.io/?url=https://code.quarkus.io/openapi

* [CodeQuarkusResource.kt](https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/kotlin/io/quarkus/code/CodeQuarkusResource.kt) - uses `@BeanParam`
* [QuarkusProject.kt](https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/kotlin/io/quarkus/code/model/QuarkusProject.kt) - bean with parameters

**Comment by gsmet** [comment] 2019-10-30 11:50
@ia3andy I let you close this one if everything is OK for you?

**Closed** 2019-10-30 13:17 UTC
Labels: bug, component:openapi, upstream
