### ISSUE TITLE
Quarkus 2.13.0: flyway migration fails to complete

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#28329] opened 2022-09-30 20:31 UTC
### Describe the bug

Hi guys!
I believe something is wrong with Flyway in a new Quarkus 2.13.0
In our project, there is a migration where two indices are created in the same script. This migration was working fine up until the Quarkus version is bumped from 2.11.3 to 2.13.0
After that, the migration just fails to complete and tests never end. Tests actually never start; migration somehow just hangs...
I attached the reproducer, please look at V2__add_user_indices.sql file. 
If you change Quarkus version in a reproducer, tests start working.

### Expected behavior

Migration V2__add_user_indices successfully completes in 2.13.0 as in 2.11.3 -> test successfully completes.

### Actual behavior

Test never ends in 2.13.0 version.

### How to Reproduce?

[flyway-fail.zip](https://github.com/quarkusio/quarkus/files/9687431/flyway-fail.zip)

1. Run the only test on 2.13.0 version
2. Run the only test on 2.11.3 version
3. Notice that it hangs on certain migration file V2__add_user_indices.sql

### Quarkus version or git rev

2.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle with Kotlin

**Comment by gsmet** [comment] 2022-09-30 20:41
Could it be related to this note we recently added to the 2.13 migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.13#flyway ?

**Comment by OleKsimov** [comment] 2022-09-30 20:45
It couldn't because we've got this check enabled too in a project. And in reproducer it obviously runs from scratch: it's a clear database in postgres devcontainer.

**Comment by gsmet** [comment] 2022-09-30 20:53
OK, we will have a closer look then. Thanks for the reproducer.

**Comment by gsmet** [comment] 2022-10-03 14:41
@OleKsimov it seems to pass if I remove the `CONCURRENTLY` keyword from the index creations.

And it also passes if I downgrade Flyway to 8.5.13 (I tried 2.13 branch + Flyway 8.5.13). So if I were you, I would report the issue to the Flyway project with a minimal reproducer (that probably shouldn't use Quarkus).

**Comment by gsmet** [comment] 2022-10-03 14:42
Also from what I can see, it's stuck on the query execution in the PostgreSQL driver so nothing specific to Quarkus I would say.

**Comment by gsmet** [comment] 2022-10-03 14:44
For the record, this is where it is stuck:
```
"Test worker" #1 prio=5 os_prio=0 cpu=2298.66ms elapsed=53.88s tid=0x00007f859c02d800 nid=0x6a36d runnable  [0x00007f85a314d000]
   java.lang.Thread.State: RUNNABLE
        at java.net.SocketInputStream.socketRead0(java.base@11.0.11/Native Method)
        at java.net.SocketInputStream.socketRead(java.base@11.0.11/SocketInputStream.java:115)
        at java.net.SocketInputStream.read(java.base@11.0.11/SocketInputStream.java:168)
        at java.net.SocketInputStream.read(java.base@11.0.11/SocketInputStream.java:140)
        at org.postgresql.core.VisibleBufferedInputStream.readMore(VisibleBufferedInputStream.java:161)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:128)
        at org.postgresql.core.VisibleBufferedInputStream.ensureBytes(VisibleBufferedInputStream.java:113)
        at org.postgresql.core.VisibleBufferedInputStream.read(VisibleBufferedInputStream.java:73)
        at org.postgresql.core.PGStream.receiveChar(PGStream.java:453)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2120)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:356)
        - locked <0x00000000f76a0f48> (a org.postgresql.core.v3.QueryExecutorImpl)
        at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:496)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:413)
        - locked <0x00000000f7314fb8> (a org.postgresql.jdbc.PgStatement)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:333)
        at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:319)
        at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:295)
        at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:290)
        at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
        at org.flywaydb.core.internal.jdbc.JdbcTemplate.executeStatement(JdbcTemplate.java:201)
        at org.flywaydb.core.internal.sqlscript.ParsedSqlStatement.execute(ParsedSqlStatement.java:95)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.executeStatement(DefaultSqlScriptExecutor.java:210)
        at org.flywaydb.core.internal.sqlscript.DefaultSqlScriptExecutor.execute(DefaultSqlScriptExecutor.java:126)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.executeOnce(SqlMigrationExecutor.java:68)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.lambda$execute$0(SqlMigrationExecutor.java:57)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor$$Lambda$1120/0x0000000100979040.call(Unknown Source)
        at org.flywaydb.core.internal.database.DefaultExecutionStrategy.execute(DefaultExecutionStrategy.java:27)
        at org.flywaydb.core.internal.resolver.sql.SqlMigrationExecutor.execute(SqlMigrationExecutor.java:56)
        at org.flywaydb.core.internal.command.DbMigrate.doMigrateGroup(DbMigrate.java:376)
        at org.flywaydb.core.internal.command.DbMigrate.applyMigrations(DbMigrate.java:278)
        at org.flywaydb.core.internal.command.DbMigrate.migrateGroup(DbMigrate.java:246)
        at org.flywaydb.core.internal.command.DbMigrate.lambda$migrateAll$0(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate$$Lambda$1117/0x0000000100940c40.call(Unknown Source)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:73)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.lambda$execute$0(PostgreSQLAdvisoryLockTemplate.java:56)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate$$Lambda$1113/0x0000000100941c40.call(Unknown Source)
        at org.flywaydb.core.internal.jdbc.TransactionalExecutionTemplate.execute(TransactionalExecutionTemplate.java:55)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLAdvisoryLockTemplate.execute(PostgreSQLAdvisoryLockTemplate.java:56)
        at org.flywaydb.core.internal.database.postgresql.PostgreSQLConnection.lock(PostgreSQLConnection.java:96)
        at org.flywaydb.core.internal.schemahistory.JdbcTableSchemaHistory.lock(JdbcTableSchemaHistory.java:143)
        at org.flywaydb.core.internal.command.DbMigrate.migrateAll(DbMigrate.java:141)
        at org.flywaydb.core.internal.command.DbMigrate.migrate(DbMigrate.java:98)
```

**Comment by OleKsimov** [comment] 2022-10-03 14:52
Ok, thanks for the investigation! 
CONCURRENTLY keyword is quite common for Postgres databases for index creation. So I would expect some demand from Postgres customers :)

**Comment by gsmet** [comment] 2022-10-03 14:54
Yeah, it should be supported. Not sure what they did that could have broken it.

I will close this issue. If you can't reproduce it with Flyway alone, feel free to reopen. But I really think that's a Flyway issue.

**Closed by gsmet** 2022-10-03 14:54 UTC
Labels: kind/bug, area/kotlin, area/flyway

**Comment by OleKsimov** [comment] 2022-10-04 16:21
@gsmet Just wanted to ask is there a way to set custom Flyway properties in Quarkus? There is one that fixes the mentioned behavior: [postgresqlTransactionalLock](https://flywaydb.org/documentation/configuration/parameters/postgresqlTransactionalLock)
It turned out that the problem is quite common for all Postgres users who don't use PgBouncer, but the Flyway team decided to make this configuration a default. And now it can be [fixed](https://github.com/flyway/flyway/issues/3508) only by turning off transactional locking.
