### ISSUE TITLE
Information endpoint

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#13598] opened 2020-12-01 18:50 UTC
**Description**
Capture information about the Quarkus instance during build/runtime that can be surfaced as an endpoint off of the new non-application endpoint root.

Could display information such as:

- JVM version (not applicable for native)
- Quarkus version
- List of extensions packaged

**Implementation ideas**
One option is to generate a resource file containing some of the information, such as an extension list, that is easier to create at build time and then write a resource file into the archive with the information.

The endpoint can then read the resource to display the stored information, and include JVM version if it's executing within a JVM.

The endpoint could be `/q/info`.

**Comment by famod** [comment] 2020-12-01 20:02
Maybe the version of the actual application could be displayed as well?

**Comment by kenfinnigan** [comment] 2020-12-01 20:11
Don't see why not

**Comment by adriens** [comment] 2022-08-26 07:49
Also some `git` related info would be really nice

**Comment by gastaldi** [comment] 2023-01-13 14:57
Closing as duplicate of #29995 (which also has more information/discussion about it)

**Closed by gastaldi** 2023-01-13 14:57 UTC
Labels: kind/enhancement, area/core, area/vertx
