### ISSUE TITLE
Native image memory leaks?

### ISSUE THREAD

**Issue by dxps** [quarkusio/quarkus#22757] opened 2022-01-09 13:47 UTC
### Describe the bug

Hi Quarkus team & community!

While taking a look again on the recent developments on Quarkus space and started reading a recently published book, initially I played with the native image by just keep pressing F5 (browser reload) on a simple GET /accounts and discovered that the memory was keep increasing.

So, just being genuinely curious about it, I started to do it in a more "standard" way, but simple enough to illustrate the point.
See _How to Reproduce_ section for all the figures.

The app is a bare bone simple service that has an API and returns some data from memory, no disk nor database. The complete example can be found [here](https://github.com/dxps/quarkus_playground/tree/master/knative_quarkus_bank/account_svc).

The "stress test" is done using cURL and it is this [/tests/account_svc_local_stress_1.sh](https://github.com/dxps/quarkus_playground/blob/master/knative_quarkus_bank/tests/account_svc_local_stress_1.sh) file. In all ll the screenshots below you'll see there is no bottleneck anywhere else (script nor system).

Obviously, a native image is not that efficient as a JVM based running app, but still the concerning part is that it keeps increasing the memory usage although there are no real reasons to do it except of some memory leak in the framework internals or the JAX-RS implementation. And most probably the only solution for now would be to recycle the instances from time to time.

### How to Reproduce?

Initially:
```shell
$ ./target/account_svc-1.0.0-SNAPSHOT-runner 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-01-09 15:08:06,648 INFO  [io.quarkus] (main) account_svc 1.0.0-SNAPSHOT native (powered by Quarkus 2.6.1.Final) started in 0.034s. Listening on: http://0.0.0.0:8080
2022-01-09 15:08:06,648 INFO  [io.quarkus] (main) Profile prod activated. 
2022-01-09 15:08:06,648 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]

```

It starts quickly and the memory usage is very low. Of course, it's not that relevant in a grand perspective, but that's the "starting point".

![image](https://user-images.githubusercontent.com/14140226/148683493-6ecf7a11-e367-407a-83c6-e733a2430a9c.png)

After running a first test using `./account_svc_local_stress_1.sh -a http://localhost:8080/accounts` the result is:

![image](https://user-images.githubusercontent.com/14140226/148683556-9a0f61c8-33d6-4ee7-a866-c07073d8fcf1.png)

After running `./account_svc_local_stress_1.sh -r 10000 -a http://localhost:8080/accounts`

![image](https://user-images.githubusercontent.com/14140226/148683629-ad38faca-06ee-4fca-b215-add5b36bae1f.png)

Continue with another test that would take longer by sending 1 million requests using
`./account_svc_local_stress_1.sh -r 1000000 -a http://localhost:8080/accounts`.

During this one, sometimes the CPU usage increases a little bit for short durations (like 3 sec) from ~20 to ~26%, while the memory still increases in a very small steps but kinda consistent.

![image](https://user-images.githubusercontent.com/14140226/148683889-df187918-81da-472e-844f-87676e95bb64.png)

And the result is:

![image](https://user-images.githubusercontent.com/14140226/148684228-7fb9d3dd-55be-4a74-b996-2c32b11d6bc1.png)

Running again the same 1M requests test and the result is:

![image](https://user-images.githubusercontent.com/14140226/148684697-ea4d420e-d25c-409e-846b-be8ace6469fd.png)

### Output of `uname -a` or `ver`

Linux dxps 5.15.8-76051508-generic #202112141040~1639505278~21.10~0ede46a SMP Tue Dec 14 22:38:29 U x86_64 x86_64 x86_64 GNU/Linux

**Comment by geoand** [comment] 2022-01-09 14:12
cc @zakkak @galderz

**Comment by geoand** [comment] 2022-01-10 06:45
Can you share the application you used to obtain this behavior?

**Comment by gsmet** [comment] 2022-01-10 12:06
Maybe it's a stupid question but have you constrained the memory somehow? Maybe try adding `-Xmx100m` to your command line?

**Comment by galderz** [comment] 2022-01-10 12:33
The first thing I'd wonder is: Have you tried the same test with the JVM version and see how the memory metric compares? If the behaviour differs, then it'd be worth exploring further at the native level. Otherwise use the JVM version to inspect things further.

What's the memory value coming from? Is that RSS or some other metric?

@gsmet's suggestion is definitely worth a try. Beyond that you'd want to the tests with some GC flags to see what is going on that level. E.g. add `-XX:+PrintGC -XX:+PrintGCSummary -XX:+PrintGCTimeStamps -XX:+PrintGCTimes -XX:+PrintHeapShape`. A more verbose option can also be added, e.g. `-XX:±VerboseGC`. (Tip: you can run the executable with `-XX:PrintFlags=` to see all flags)

Another aspect to check, is how much of that memory is heap vs native. The GC output should give you some clues.

**Comment by dxps** [comment] 2022-01-10 18:28
Thank you all for the feedback and sorry for the delay.

@geoand The example link is included in the description. [This is it](https://github.com/dxps/quarkus_playground/tree/master/knative_quarkus_bank/account_svc).

@gsmet Those tests where done with the native image, so I don't see the relevance of `-Xmx` JVM argument, but maybe I'm wrong.

@galderz I was thinking about doing it, but I thought how that would help. But sure, I'll do that, why not.
One difference and maybe not helpful would be that the native image is built using Java 11, whereas I could run the JVM mode with a Java 17. So, yes, I should use a locally installed Java 11.

**Comment by geoand** [comment] 2022-01-10 18:31
> so I don't see the relevance of -Xmx JVM argument

This is an incorrect assumption.

The native binary still uses garbage collection and the `-Xmx` argument has the same semantics as for regular JVM mode

**Comment by zakkak** [comment] 2022-01-10 21:17
FWIW this reminds me of https://github.com/oracle/graal/issues/3403, which should be fixed in Graal VM 21.3.0 (haven't verified it though).

**Comment by dxps** [comment] 2022-01-11 11:45
@geoand Your're right. I put the disclaimer _maybe I'm wrong_ as I didn't yet take a look at the docs about that.

@gsmet I'll redo the test using the native image and `-Xmx100`, just to see how it behaves.

### "Running in JVM mode" Scenario

The requests were done using the same cURL based approach (script found in `./tests`):
`./account_svc_local_stress_1.sh -r 1000000 -a http://localhost:8080/accounts`

- Building: `./mvnw package`
- Running: `java -jar target/quarkus-app/quarkus-run.jar`
- Initial "snapshot": RAM usage: `~97.7 MB`
   ![image](https://user-images.githubusercontent.com/14140226/148927857-b15eda44-0e7e-4ea2-845e-86119f3b54ba.png)

- After 1st shot of 1M requests: memory usage got quickly up to ~`188 MB` and stood there for the rest of the test.
   ![image](https://user-images.githubusercontent.com/14140226/148929319-ebddd28d-957d-4e39-b3da-c091a30abe7d.png)
 
- After 2nd shot of 1M requests: memory usage got quickly up to ~`204 MB` and stood there for the rest of the test.
   ![image](https://user-images.githubusercontent.com/14140226/148930521-7d759959-60b2-4116-ac9b-f971a578dbb9.png)

- After 3rd shot of 1M requests: memory usage got quickly up to ~`212 MB` and stood there for the rest of the test.
  Eventually, after the test ended here's the figure.
   ![image](https://user-images.githubusercontent.com/14140226/148931781-113e7cec-29f3-4c64-bf2a-3a060056ba49.png)

- After 4th shot of 1M requests: memory usage got quickly up to ~`216 MB` and stood there for the rest of the test.
  At the end of the test:
  ![image](https://user-images.githubusercontent.com/14140226/148936636-d76b8625-95fc-4ba9-a10e-e685bbf8765d.png)

Now, I could continue like that and expect to increase with a couple of megs at the beginning of each new test and 1 more at the end, according to this behavior. Of course, it doesn't have to be that consistent.

Hope it helps.

**Comment by galderz** [comment] 2022-01-12 08:23
So @dxps, unless I'm mistaken from the data above, JVM mode also shows similar situation? True, the memory numbers are slightly lower but the keep climbing up in similar fashion? Correct me if I'm wrong, it's unclear from your last comment what information you derive from the JVM tests.

If JVM mode shows similar behaviour, then you could try to generate a heap dump when it's reached such high memory and then use Eclipse MAT or similar tools to see what's up. In native, heap memory dumps (in hprof format that Eclipse MAT and others understand) can only be obtained with the GraalVM EE version. So to summarise, if you can replicate the issue with JVM, you have free tools at your disposal to see what's up.

Also, you should be comparing apples with apples. It's not very helpful to use native built with java 11 base but then use java 17 for the jvm mode. If the native to jvm mode behaviour differs, then you should use the same base java 11 version underneath (or as close as possible).

**Comment by alexcheng1982** [comment] 2022-01-13 08:26
With native image, there is only a limited choices of GC: Serial GC (default), Epsilon GC (no-op), and G1 GC (GraalVM EE only). From the setup:

* No GC configured -> Serial GC
* No `-Xmn` config -> Young generation size is `256M`
* No `-Xmx` config -> 80% of the physical memory, very large

> Note that GraalVM releases up to (and including) 21.3 use a different default configuration for the Serial GC with no survivor regions, a young generation that is limited to 256 MB - [GraalVM doc](https://www.graalvm.org/reference-manual/native-image/MemoryManagement/)

Based on the usage pattern, most of the objects are short-lived. The increase of memory size is caused by object allocations in the eden region of the young generation before reaching the limit (256M). After turning on the GC output (`-XX:+PrintGC -XX:+VerboseGC`), I can observe that when the young generation is full, a young collection can collect most of the space. After reaching the limit of young generation, the overall memory size won't increase much.

```
[Heap policy parameters: 
  YoungGenerationSize: 268435456
      MaximumHeapSize: 13743895280
      MinimumHeapSize: 536870912
     AlignedChunkSize: 1048576
  LargeArrayThreshold: 131072]
[[364809794289492 GC: before  epoch: 1  cause: CollectOnAllocation]
[Incremental GC (CollectOnAllocation) 262144K->5120K, 0.0194930 secs]
 [364809813842245 GC: after   epoch: 1  cause: CollectOnAllocation  policy: by space and time  type: incremental
  collection time: 19493077 nanoSeconds]]
[[364871084354828 GC: before  epoch: 2  cause: CollectOnAllocation]
[Incremental GC (CollectOnAllocation) 267264K->6144K, 0.0043234 secs]
 [364871088699094 GC: after   epoch: 2  cause: CollectOnAllocation  policy: by space and time  type: incremental
  collection time: 4323478 nanoSeconds]]
```

When the size of young generation is reduced, like `-Xmn32m`, the overall memory size can also be reduced. So this is unlikely to be a memory leaking issue.

**Comment by dxps** [comment] 2022-01-13 17:25
@galderz Okay, okay, I explicitly mentioned that I used Java 17, instead of java 11. Should I almost feel guilty of pretending to compare apples to apples? :neutral_face:  I'm not here to bash Quarkus, I even promoted internally to my employer and it's being used for around 1.5 years now. Initially, I just wanted to raise a heads up about this issue here, and see if the community has a feedback.
Ofc, I could use Eclipse MAT or something to analyze a heapdump taken during or after a test. I'll try to find and spend some time understanding the why.

@alexcheng1982 Excellent insight! Thanks for sharing it!

---

<br/>

Started another "primitive" testing (previously described) scenario in JVM mode using a Java 11, as the initial native image used during the build. The Java version being used is `11.0.13+8-Ubuntu-0ubuntu1.21.10`.

```shell
❯ /usr/lib/jvm/java-1.11.0-openjdk-amd64/bin/java -jar target/quarkus-app/quarkus-run.jar 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-01-13 17:47:47,422 INFO  [io.quarkus] (main) account_svc 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.6.1.Final) started in 1.088s. Listening on: http://0.0.0.0:8080
2022-01-13 17:47:47,435 INFO  [io.quarkus] (main) Profile prod activated. 
2022-01-13 17:47:47,435 INFO  [io.quarkus] (main) Installed features: [cdi, kubernetes, resteasy, resteasy-jsonb, smallrye-context-propagation, vertx]

```

At fresh startup time (without any request), it looks like this:
![image](https://user-images.githubusercontent.com/14140226/149362733-ac54ede5-78d9-4afb-93a6-6ffb3c9b7c11.png)

- 1st set of 1M requests
  After 4-7 seconds, the memory usage quickly jumps up to `447.7 MB` and it stays there for the rest of the test
  (that normally takes 6m 30s to complete). And the result:
  ![image](https://user-images.githubusercontent.com/14140226/149364257-4e0c5d45-4378-4e38-9803-938f0db8d791.png)

- 2nd set of 1M requests
  After 4-7 seconds, the memory usage jumps up to `461.4 MB` and it kinda stays there for the rest of the test. The result is:
  ![image](https://user-images.githubusercontent.com/14140226/149365575-7f2485db-e0b8-4fdc-a23b-216970bf9998.png)

- 3rd set of 1M requests
  After 4-7 seconds, the memory usage jumps up to `467.6 MB` and it kinda stays there for the rest of the test. The result being:
  ![image](https://user-images.githubusercontent.com/14140226/149367554-facd4791-bcce-4ff7-afae-360666e91bc4.png)


I could continue, but I guess the pattern is predictable.

<br/>

Now just taking another shot with the native image and some `-Xmx`, as rightly suggested by @gsmet and @alexcheng1982.
Used `./target/account_svc-1.0.0-SNAPSHOT-runner -Xmx64m`.

- At startup, it takes `5.1` MB.
- 1st test:
   - During the test, the memory usage was up and down just within 11 - 16 MB range.
   - But the test took 61m 37s, waaay longer (than 6m 30s) to repeat it.

<br/>

Without any other relevant actions, we could consider this issue as closed and get the lessons learned from it.
Thanks again for the valuable feedback! :pray:

**Closed** 2022-01-24 11:21 UTC
Labels: kind/bug, area/native-image
