### ISSUE TITLE
Empty Kotlin files or extensions-only files trigger change detection all the time

### ISSUE THREAD

**Issue by jkopcsek** [quarkusio/quarkus#2616] opened 2019-05-27 22:58 UTC
**Describe the bug**
When having an empty kotlin file or a kotlin file that contains only extensions it will be detected as changed in dev mode all the time. 

**Expected behavior**
It should be detected as changed only when a real change happened.  

**Actual behavior**
It's detected as being changed all the time.

**Example Setup**
https://github.com/jkopcsek/quarkus-kotlin-gradle-demo/tree/bug/quarkus-extensions-auto-reload

**To Reproduce**
1. Create empty or extensions-only kt file
2. Run quarkusDev
3. Observe

**Workaround**
Add a class to the file

**Environment:**
 - Mac, AdoptOpenJDK 8, Quarkus 0.15

**Comment by stuartwdouglas** [comment] 2019-05-29 03:18
This may already be fixed upstream, there will be some changes in this area for the 0.16 release

**Comment by geoand** [comment] 2019-06-03 16:18
I am going to close this since I tested with `0.16.0` which was just released and the problem can no longer reproduce the problem

**Closed by geoand** 2019-06-03 16:18 UTC
Labels: bug, component:kotlin
