### ISSUE TITLE
gradle quarkusDev reloading not working with windows

### ISSUE THREAD

**Issue by NF13** [quarkusio/quarkus#3664] opened 2019-08-23 09:31 UTC
**Describe the bug**
If I change my code with windows and change of the source file detected after reload i get the following error:
```
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/nf13/.gradle/caches/modules-2/files-2.1/io.quarkus/quarkus-resteasy/0.21.1/88e3a2bb147c81196c066295b70914ca80badec9/quarkus-resteasy-0.21.1.jar
	at java.base/sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153)
	at java.base/sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77)
	at java.base/sun.nio.fs.WindowsPath.parse(WindowsPath.java:92)
	at java.base/sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:229)
	at jdk.compiler/com.sun.tools.javac.file.FSInfo.getJarClassPath(FSInfo.java:112)
	at jdk.compiler/com.sun.tools.javac.file.CacheFSInfo.getJarClassPath(CacheFSInfo.java:93)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addJarClassPath(Locations.java:423)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFile(Locations.java:413)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:345)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SearchPath.addFiles(Locations.java:352)
	at jdk.compiler/com.sun.tools.javac.file.Locations$SimpleLocationHandler.setPaths(Locations.java:724)
	at jdk.compiler/com.sun.tools.javac.file.Locations.setLocation(Locations.java:2098)
	at jdk.compiler/com.sun.tools.javac.file.JavacFileManager.setLocation(JavacFileManager.java:927)
	at io.quarkus.dev.JavaCompilationProvider.compile(JavaCompilationProvider.java:48)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:156)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:164)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:103)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:72)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:61)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:376)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**Expected behavior**
Reloaded Resource

**Actual behavior**
Exception

**To Reproduce**
1. Set up quarkus with gradle
2. run gradle quarkusDev
3. Change Source file
4. Reload

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

MSYS_NT-10.0 M060 2.9.0(0.318/5/3) 2018-01-12 23:37 x86_64 Msys

 - Output of `java -version`: 

openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment Corretto-11.0.2.9.3 (build 11.0.2+9-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.2.9.3 (build 11.0.2+9-LTS, mixed mode)

 - Quarkus version or git rev: 

0.21.1

**Comment by gsmet** [comment] 2019-08-23 09:36
This is a duplicate of https://github.com/quarkusio/quarkus/issues/3592 . Thanks for reporting!

**Closed by gsmet** 2019-08-23 09:36 UTC
Labels: bug

**Comment by NF13** [comment] 2019-08-23 09:39
sry not found by searching

**Comment by gsmet** [comment] 2019-08-23 11:03
No worries, it's not always easy to find an already opened issue. Subscribe to the other one, there's a good chance we will have a fix for the next version. Have a nice day!
