### ISSUE TITLE
Occasional org.hibernate.exception.GenericJDBCException when performing REST operations that stream responses 

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#22269] opened 2021-12-15 23:26 UTC
### Describe the bug

We have several REST services that stream the Response to the client via javax.ws.rs.core.StreamingOutput and we occasionally get these errors in the logs.  In this case the call to get the next ResultSet fails because its closed.  

We do not know what is triggering these.

We did upgrade to 2.4.2.Final not too long ago but have no data that suggests that is the cause.

```
2021-12-15 02:28:43,859 ERROR (executor-thread-481) [com.bs.dl.streaming.AppElStreamingOutput_Subclass.write()] Exception streaming data from App: org.hibernate.exception.GenericJDBCException: could not advance using next()
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.internal.ScrollableResultsImpl.convert(ScrollableResultsImpl.java:71)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:106)
	at org.hibernate.query.internal.ScrollableResultsIterator.hasNext(ScrollableResultsIterator.java:33)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:132)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
	at com.bs.dl.streaming.AppStreamingOutput.processResultStream(AppStreamingOutput.java:267)
	at com.bs.dl.streaming.AppStreamingOutput.queryStream(AppStreamingOutput.java:257)
	at com.bs.dl.streaming.AppStreamingOutput.write(AppStreamingOutput.java:245)
	at com.bs.dl.streaming.AppElStreamingOutput_Subclass.write$$superforward1(AppElStreamingOutput_Subclass.zig:106)
	at com.bs.dl.streaming.AppElStreamingOutput_Subclass$$function$$1.apply(AppElStreamingOutput_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:41)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew_Bean.intercept(TransactionalInterceptorRequiresNew_Bean.zig:335)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.bs.dl.streaming.AppElStreamingOutput_Subclass.write(AppElStreamingOutput_Subclass.zig:171)
	at com.bs.dl.streaming.AppElStreamingOutput_ClientProxy.write(AppElStreamingOutput_ClientProxy.zig:680)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:20)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.sql.SQLException: ResultSet is closed
	at io.agroal.pool.wrapper.ResultSetWrapper$1.invoke(ResultSetWrapper.java:52)
	at com.sun.proxy.$Proxy121.next(Unknown Source)
	at io.agroal.pool.wrapper.ResultSetWrapper.next(ResultSetWrapper.java:88)
	at org.hibernate.internal.ScrollableResultsImpl.next(ScrollableResultsImpl.java:101)
	... 54 more
```

### Output of `java -version`

JDK 11 Linux

### Quarkus version or git rev

2.4.2.Final

**Comment by yrodiere** [comment] 2021-12-16 07:59
Most likely the underlying resources have some sort of "reaper" that closes them automatically after a given time in order to avoid leaks, and you're keeping the resources open just long enough for that reaper to come into action. The reaper could be in the JDBC driver, or maybe in Agroal (connection pool) itself.

In any case, I'm afraid there's is little chance we can identify what is going on without a reproducer. Unless you're lucky and @barreiro happens to know the answer.

**Comment by Sanne** [comment] 2021-12-16 12:14
Agreeing with @yrodiere , I also suspect a timeout of the transaction.

**Comment by dhoffer** [comment] 2021-12-16 21:53
I am double-checking our timeout in production but this is what we use as the default.
quarkus:  
  transaction-manager:
    node-name: quarkus
    default-transaction-timeout: 600

So you think that thread happened to work longer than 600 seconds in a TX?

How can I prove what happened?  Is there a way I can capture current thread's time in TX so when we log these exceptions we can add that to the log?

**Comment by dhoffer** [comment] 2021-12-17 17:06
@yrodiere @Sanne @barreiro I have more information on the cause.  Specifically I can see this is due to a TX timeout but specifically this error occurs when the inner streaming TX expires.  Let me elaborate.

All our REST services are @ApplicationScoped & @Transactional(Transactional.TxType.REQUIRED) but for any service endpoint that uses Streaming Response has an inner @Transactional(Transactional.TxType.REQUIRES_NEW) as this can last well longer than the outer TX.

E.g. 
@Override
@Transactional(Transactional.TxType.REQUIRES_NEW)
public void write(OutputStream outputStream) throws WebApplicationException 

This error happens if that inner TX expires.

If the outer one expires we get: org.hibernate.HibernateException: Transaction was rolled back in a different thread!

However for the inner one we get: org.hibernate.exception.GenericJDBCException: could not advance using next()

What we would like is for the inner one to have a better, more clear, exception of what really happened.  Would this be possible to do?

Also are there any standards/best-practices for how to handle responses to the caller when the inner one expires?  They already got the 200 when the stream started to respond but the stream will stop when this happens, how can we let them know they really only got a partial response?  What is the best way to let the user know they didn't get all the records that were valid for their request?

**Comment by brunohpg** [comment] 2022-01-07 00:43
I had this problem once.
I had to change the code to an inefficient way loading the list into memory and then replying.
In my case, I return a Stream<?> and let Quarkus take care of the json conversion.

At first I thought the transaction was closed simply by exiting the last method annotated with @Transaction.
In fact, the Stream is read later (during converting to json) and the transactional methods are gone.

As the Panache documentation says:
> It requires a transaction to work. Without a transaction, the underlying cursor can be closed before the end of the stream.

I don't know a method to do the process that is done after the resource returns inside the resource method. Something like:
```
@Transactional
public Stream<String> myResrouce() {
    return myService.loadStrings();
}
```
to
```
@Transactional
public void myResrouce(SomeResponseObject resp) {
    resp.doResponse(myService.loadStrings());
}
```

If it had a way, it should work. And I'll be happy.

But it could also be transaction timeout. In that case it would fail anyway, so I don't think that's my case.

**Comment by yrodiere** [comment] 2022-10-26 07:59
Hey @dhoffer ,

Sorry, it looks like I missed your answer.

> What we would like is for the inner one to have a better, more clear, exception of what really happened. Would this be possible to do?

That seems reasonable, but can you still provide a reproducer? That will make it much easier to fix the problem.

**Comment by yrodiere** [comment] 2022-12-20 12:45
Hey @dhoffer , did you solve the problem yourself? If not, we'll need a reproducer to help you. Thanks.

**Comment by yrodiere** [comment] 2023-01-11 08:21
I'm going to close this as this is most likely caused by a usage issue, we don't have the reproducer, and making the exception clearer would require changes in Hibernate ORM, not in Quarkus.

If you find time to build a reproducer, even one using Quarkus, please consider submitting a new issue to the Hibernate ORM project with that reproducer: https://hibernate.atlassian.net/browse/HHH.

If you disagree with closing this issue, feel free to ping me.

**Closed by yrodiere** 2023-01-11 08:21 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm, needs-reproducer
