### ISSUE TITLE
GraphQL: JsonWebToken not being detected

### ISSUE THREAD

**Issue by bearbytes** [quarkusio/quarkus#9986] opened 2020-06-13 17:31 UTC
**Describe the bug**
When executing a `@Query` of a `@GraphQLApi`, an injected `org.eclipse.microprofile.jwt.JsonWebToken` is always an instance of `io.smallrye.jwt.auth.cdi.NullJsonWebToken`.
There also doesn't seem to be any other way to check the Authorization Header of the underlying HTTP Request.

**Expected behavior**
It should be possible to inject a `JsonWebToken` into a `@GraphQLApi` bean, in the same way it works for a JAX-RS Resource.

**Comment by sberyozkin** [comment] 2020-06-15 09:41
Looks like a context propagation issue.

**Comment by jmartisk** [comment] 2020-06-22 05:53
I can't reproduce this with current Quarkus master, I think this was fixed as a side effect of https://github.com/quarkusio/quarkus/pull/10004
Can you retry with Quarkus 1.5.2.Final?

**Comment by guardianblue** [comment] 2020-06-26 07:38
Tested with 1.5.2 Final and can confirm that injected `org.eclipse.microprofile.jwt.JsonWebToken` is still being null.

**Comment by jmartisk** [comment] 2020-07-07 08:16
Then I have to ask for a reproducer, because with 1.5.2 it works for me.
My GraphQL api looks like this:

```
@GraphQLApi
public class MyGraphQLApi {

    @Inject
    JsonWebToken token;

    @Query
    public String foo() {
        System.out.println("TOKEN ==== " + token);
        System.out.println("ID = " + token.getTokenID());
        return "bar";
    }
}
```

With 1.5.1, when executing the query, I get
```
TOKEN ==== io.smallrye.jwt.auth.cdi.NullJsonWebToken@a66f6dc
ID = null
```

With 1.5.2, I get
```
TOKEN ==== DefaultJWTCallerPrincipal{id='a-123', name='jdoe@quarkus.io', expiration=1594109631, notBefore=0, issuedAt=1594109331, issuer='https://quarkus.io/using-jwt-rbac', audience=[using-jwt-rbac], subject='jdoe-using-jwt-rbac', type='JWT', issuedFor='null', authTime=1594109331, givenName='null', familyName='null', middleName='null', nickName='null', preferredUsername='jdoe', email='null', emailVerified=null, allowedOrigins=null, updatedAt=0, acr='null', groups=[Echoer,Group2MappedRole,Tester,Subscriber,group2]}
ID = a-123
```

**Comment by guardianblue** [comment] 2020-07-09 01:16
@jmartisk Thanks for looking into this.

After digging deeper into my code, I realized what I am encountering is slightly different from what @bearbytes wrote.

In my case, it is `token` being `null` instead. I suspect I have not configured properly at all. Similar injection _do_ work on REST API endpoint though.

**Comment by guardianblue** [comment] 2020-07-14 05:10
@jmartisk We have refactored our code (moving the package dependencies around), and that the issue is no longer reproducible. While we cannot confirm the original cause of the problem we faced, it is quite likely that we have missing dependencies in some of our pom files.

**Comment by jmartisk** [comment] 2020-07-14 06:05
Great! Let me close the issue then. 
If someone still faces it, we can always reopen.

**Closed by jmartisk** 2020-07-14 06:05 UTC
Labels: area/smallrye, kind/bug

**Comment by MartinSem** [comment] 2022-05-12 14:10
Hi,
i have the same issue using quarkyus 2.8.2, 2.8.3 and 2.9.0. 

my pom
`  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <failsafe.useModulePath>false</failsafe.useModulePath>
    <kotlin.version>1.6.21</kotlin.version>
    <maven.compiler.release>11</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.9.0.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-kotlin</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-jwt</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-graphql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib-jdk8</artifactId>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>kotlin-extensions</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>`


my graphql class
`@GraphQLApi
class Graphtest {
    @Inject
    lateinit var token: JsonWebToken

    @Query("test")
    fun test(): String {
        println("TOKEN : $token");
        return "test";
    }
}
`

i always have the same print: "TOKEN :  io.smallrye.jwt.auth.cdi.NullJsonWebToken@601478c0"

Any help?
