### ISSUE TITLE
Quarkus Maven Plugin create goal fails on Maven 3.9.0

### ISSUE THREAD

**Issue by zforgo** [quarkusio/quarkus#31387] opened 2023-02-23 22:45 UTC
### Describe the bug

When creating a new project e.g. 
```mvn io.quarkus:quarkus-maven-plugin:create -DprojectGroupId=io.github.zforgo -DprojectArtifactId=example```
the execution will fail with error message:
> A required class was missing while executing io.quarkus:quarkus-maven-plugin:3.0.0.Alpha4:create: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory

### Expected behavior

The project skeleton should be generated successfully.

### Actual behavior

When running create goal of Maven plugin using Maven 3.9.0
```mvn io.quarkus:quarkus-maven-plugin:create -DprojectGroupId=io.github.zforgo -DprojectArtifactId=example```
the execution will fail with this output:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus:3.0.0.Alpha4:create (default-cli) @ standalone-pom ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.457 s
[INFO] Finished at: 2023-02-23T22:54:29+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.Alpha4:create (default-cli) on project standalone-pom: Execution default-cli of goal io.quarkus:quarkus-maven-plugin:3.0.0.Alpha4:create failed: A required class was missing while executing io.quarkus:quarkus-maven-plugin:3.0.0.Alpha4:create: org/eclipse/aether/connector/basic/BasicRepositoryConnectorFactory
[ERROR] -----------------------------------------------------

...

[ERROR] Number of foreign imports: 1
[ERROR] import: Entry[import  from realm ClassRealm[maven.api, parent: null]]
[ERROR] 
[ERROR] -----------------------------------------------------
[ERROR] : org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory
[ERROR] -> [Help 1]
[ERROR] 
```

### Quarkus version or git rev

2.16.3.Final, 3.0.0.Alpha4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)

### Additional information

It perfectly works with older version of Maven (e.g 3.8.4 or 3.8.7)
It seems the ```org.apache.maven.resolver:maven-resolver-connector-basic:jar:1.6.3``` did not added to the plugin class realm which cause a ```ClassNotFoundException```

All debug logs available below
[success - 3.8.4.log](https://github.com/quarkusio/quarkus/files/10819126/3.8.4.log)
[failed - 3.9.0.log](https://github.com/quarkusio/quarkus/files/10819127/3.9.0.log)

**Comment by gastaldi** [comment] 2023-02-23 22:52
Duplicate of #31011

**Closed by gastaldi** 2023-02-23 22:52 UTC
Labels: kind/bug, area/maven
