### ISSUE TITLE
No Interceptors invoked on JAX-RS Controllers with Generic Typed Method Arguments

### ISSUE THREAD

**Issue by fxnn** [quarkusio/quarkus#14696] opened 2021-01-29 08:09 UTC
**Describe the bug**
Situation:

1. My JAX-RS Controllers (`Resource` classes, in the reproducer it's [`ExampleResource`](https://github.com/fxnn/reproducer-quarkus-transactional/blob/master/src/main/java/de/fxnn/ExampleResource.java)) derive from an abstract class([`AbstractResource`](https://github.com/fxnn/reproducer-quarkus-transactional/blob/master/src/main/java/de/fxnn/AbstractResource.java)) which contains the general, reusable logic. For example, there's a `create(dto)` method -- the logic is the same for all controllers, only the `POST` request body (`dto` parameter) is different for every controller. Thus, it's a type variable on the abstract controller class.
2. My controllers are annotated `@Transactional`, therefore Quarkus should run the `io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired` interceptor and start a transaction.

That however does not happen. Actually, from a stacktrace one can see that the whole `io.quarkus.arc.impl.InvocationContexts.performAroundInvoke` logic doesn't get invoked. Even the generated `_Subclass` class doesn't appear in the Stacktrace, so the controller's public method is directly invoked instead of the generated `_Subclass` method which should then in turn call `performAroundInvoke`.

**Expected behavior**
A transaction is started when JAX-RS invokes the controller's method.

**Actual behavior**
No transaction is started when JAX-RS invokes the controller's method. The whole Interception logic is skipped.

**To Reproduce**

Reproducer: https://github.com/fxnn/reproducer-quarkus-transactional

It's based on the code.quarkus.io starter with JAX-RS, Jackson, Hibernate and Panache.

1. Checkout the code.
2. Run `mvn verify`
3. The only test case in the project, [`de.fxnn.ExampleResourceTest#create`](https://github.com/fxnn/reproducer-quarkus-transactional/blob/master/src/test/java/de/fxnn/ExampleResourceTest.java), fails with following output.
```
[INFO] Running de.fxnn.ExampleResourceTest
2021-01-29 08:48:26,936 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-7,5,main]=Thread[vert.x-eventloop-thread-7,5,main] has been blocked for 3891 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.netty.channel.AbstractChannel.newId(AbstractChannel.java:101)
	at io.netty.channel.AbstractChannel.<init>(AbstractChannel.java:73)
	at io.netty.channel.nio.AbstractNioChannel.<init>(AbstractNioChannel.java:80)
	at io.netty.channel.nio.AbstractNioMessageChannel.<init>(AbstractNioMessageChannel.java:42)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:89)
	at io.netty.channel.socket.nio.NioServerSocketChannel.<init>(NioServerSocketChannel.java:75)
	at io.vertx.core.net.impl.transport.Transport$$Lambda$813/0x0000000840837040.newChannel(Unknown Source)
	at io.netty.bootstrap.AbstractBootstrap.initAndRegister(AbstractBootstrap.java:310)
	at io.netty.bootstrap.AbstractBootstrap.doBind(AbstractBootstrap.java:272)
	at io.netty.bootstrap.AbstractBootstrap.bind(AbstractBootstrap.java:268)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.lambda$doBind$2(AsyncResolveConnectHelper.java:60)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper$$Lambda$814/0x0000000840837440.handle(Unknown Source)
	at io.vertx.core.impl.AddressResolver.lambda$null$0(AddressResolver.java:88)
	at io.vertx.core.impl.AddressResolver$$Lambda$816/0x0000000840836c40.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$796/0x00000008406f8840.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.7/java.lang.Thread.run(Thread.java:834)
2021-01-29 08:48:27,378 WARN  [io.qua.net.run.NettyRecorder] (Thread-37) Netty DefaultChannelId initialization (with io.netty.machineId system property set to 1f:a9:24:2b:46:ac:4a:77) took more than a second
2021-01-29 08:48:27,411 INFO  [io.quarkus] (main) Quarkus 1.11.1.Final on JVM started in 7.388s. Listening on: http://localhost:8081
2021-01-29 08:48:27,412 INFO  [io.quarkus] (main) Profile test activated. 
2021-01-29 08:48:27,412 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-h2, mutiny, narayana-jta, resteasy, resteasy-jackson, smallrye-context-propagation]
2021-01-29 08:48:29,718 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /create failed, error id: 2e2ee75c-169e-4070-bc1b-851c0e452825-1: org.jboss.resteasy.spi.UnhandledException: javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.persist(TransactionScopedSession.java:140)
	at io.quarkus.hibernate.orm.runtime.session.ForwardingSession.persist(ForwardingSession.java:53)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:99)
	at io.quarkus.hibernate.orm.panache.common.runtime.AbstractJpaOperations.persist(AbstractJpaOperations.java:94)
	at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.persist(PanacheRepositoryBase.java:62)
	at de.fxnn.ExampleRepository_ClientProxy.persist(ExampleRepository_ClientProxy.zig:1216)
	at de.fxnn.AbstractResource.create(AbstractResource.java:14)
	at de.fxnn.ExampleResource.create(ExampleResource.java:5)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 15 more
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 12.37 s <<< FAILURE! - in de.fxnn.ExampleResourceTest
[ERROR] create  Time elapsed: 2.346 s  <<< FAILURE!
java.lang.AssertionError: 
1 expectation failed.
Expected status code <200> but was <500>.
	at de.fxnn.ExampleResourceTest.create(ExampleResourceTest.java:23)
2021-01-29 08:48:29,808 INFO  [io.quarkus] (main) Quarkus stopped in 0.036s
```

The first exception in the output can, however, be ignored from my point of view.

Note how the second Stacktrace doesn't run the `ExampleResource_subclass.create` method:

```
    at de.fxnn.AbstractResource.create(AbstractResource.java:14)
--> at de.fxnn.ExampleResource.create(ExampleResource.java:5)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
    at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
```

For reference, the `ExampleResource_subclass` class can be inspected using the `extract-jar.sh` script, which unpacks all the `-runner.jar` files into the `target/jar` folder. The `create` method starts as follows:

```java
  public String create(Dto var1) {
    Object[] var5 = new Object[]{var1};
    if (this.metadata != null) {
      ExampleResource_Subclass$$function$$1 var4 = new ExampleResource_Subclass$$function$$1(this);
```

Compare with the interface's `ExampleApi#create` method (the interface is implemented by `ExampleResource`):

```java
String create(ExampleDto dto);
```

The parameter type on `ExampleApi` (and thus `ExampleResource`) is more concrete than what's generated in `ExampleResource_subclass`, thus the generated `create` method is not invoked.

You can easily make the test pass by not using the generic type in `AbstractResource`: 

```patch
Index: src/main/java/de/fxnn/AbstractResource.java
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/src/main/java/de/fxnn/AbstractResource.java b/src/main/java/de/fxnn/AbstractResource.java
--- a/src/main/java/de/fxnn/AbstractResource.java	(revision d629ed43e0e1bcc31f612e66af72cb0b58ee3200)
+++ b/src/main/java/de/fxnn/AbstractResource.java	(date 1611907809206)
@@ -10,7 +10,7 @@
     return Long.toString(repository.findAll().count());
   }
 
-  public String create(T dto) {
+  public String create(ExampleDto dto) {
     repository.persist(new ExampleEntity());
     return "ok";
   }
```

**Configuration**
```properties
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:example
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
Should not be of help here.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin carry.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64`
 - Output of `java -version`: 
 ```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - GraalVM version (if different from Java): (see above)
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 14.0.1, vendor: N/A, runtime: /usr/local/Cellar/openjdk/14.0.1/libexec/openjdk.jdk/Contents/Home
Default locale: de_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Additional context**
(Add any other context about the problem here.)

**Comment by famod** [comment] 2021-01-29 09:35
Just an idea: Have you tried adding `@ApplicationScoped` or `@Singleton` to `ExampleResource`?

**Comment by fxnn** [comment] 2021-01-29 10:31
Thanks for your hint! Yeah, did that, unfortunately the behaviour stayed the same. `@Singleton` is already the default scope for `ExampleResource`.  When using `@ApplicationScoped`, the scope changes, but the `_subclass` and thus the interceptors are still not invoked.

**Comment by fxnn** [comment] 2021-01-29 10:32
Another note, the behaviour was correct up until `1.10.2.Final`, it broke since `1.10.3.Final`.

**Comment by famod** [comment] 2021-01-29 10:58
I think it's time to summon @mkouba and @manovotn 😁

**Comment by manovotn** [comment] 2021-01-29 11:45
This is the commit breaking it - https://github.com/quarkusio/quarkus/pull/13657

Looks like the motivation was to avoid duplicit bridge method invocations, but it breaks this scenario. We'll have to fine grain it further. I can take a look at it on Mon.

**Comment by manovotn** [comment] 2021-01-29 12:11
Also, I am not sure the commit actually fixed the original issue, because if you take the [existing test](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/bridge/BridgeMethodInterceptionTest.java) and apply `@Simple` interception binding on a class level instead of method level, you will still be getting multiple interceptor invocations.
FYI @mkouba ^

**Comment by mkouba** [comment] 2021-02-01 09:00
Hm, I think that it's the combination of an abstract generic supertype and annotation inheritance that makes troubles. As @fxnn mentioned the generated subclass intercepts a method with the signature `create(Dto var1)` but it should be `create(de.fxnn.ExampleDto)`.

A simple workaround is to reimplement the method on the resource class:
```java
@Transactional
public class ExampleResource extends AbstractResource<ExampleDto> implements ExampleApi {
    @Override
    public String create(ExampleDto dto) {
        return super.create(dto);
    }   
}
```

**Comment by mkouba** [comment] 2021-02-01 09:13
> Also, I am not sure the commit actually fixed the original issue, because if you take the [existing test](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/interceptors/bridge/BridgeMethodInterceptionTest.java) and apply `@Simple` interception binding on a class level instead of method level, you will still be getting multiple interceptor invocations.
> FYI @mkouba ^

@manovotn You're right. The fix does not work for class-level bindings. I'm not exactly sure what kind of bridge methods-related trickery is in the game. I'll try to find more details today...

**Comment by manovotn** [comment] 2021-02-01 09:16
> what kind of bridge methods-related trickery is in the game

Yeah, it's really weird. I played with it a bit on Fri but didn't find the catch yet. I am also planning to take a look today so feel free to ping me on Zulip if you figure out anything.

**Comment by mkouba** [comment] 2021-02-01 09:24
So I think that the problem is that we also add the intercepted methods candidates from superclasses and there the method (`BridgeMethodInterceptionTest.Base.echo(T)` in the test) is not a bridge method... In other words, we would have to ignore methods that have a bridge method generated on the subtype, which is BTW something we have in `InterceptedSubclassFactory.addMethodsFromClass()` ;-).

**Comment by manovotn** [comment] 2021-02-04 09:39
This issue should now be resolved via https://github.com/quarkusio/quarkus/pull/14767

**Closed by manovotn** 2021-02-04 09:39 UTC
Labels: kind/bug, triage/needs-triage
