### ISSUE TITLE
protected List<E> not working in Quarkus 13.4

### ISSUE THREAD

**Issue by JackyWitt** [quarkusio/quarkus#17602] opened 2021-06-01 13:58 UTC
Currently we updating our services to a newer Quarkus Version. 
One of our Services is using this line of code:
`protected List<E> children;`

We using this Object since previous Quarkus Versions. Since Quarkus 13.4 Final, we have following Exception.
We're using java 11.08

![exception](https://user-images.githubusercontent.com/85175373/120333008-90f6d580-c2ef-11eb-9874-fb17b6e17f09.png)

**Comment by gsmet** [comment] 2021-06-01 14:37
If you can get us a small reproducer (i.e. a simple Maven project reproducing the issue), that would help.

Also maybe try 1.13.6.Final first, just to be sure.

**Comment by stuartwdouglas** [comment] 2021-06-07 08:56
Looks like a ClassLoading issue.

**Comment by geoand** [comment] 2021-09-30 12:15
Is this still a problem with the latest Quarkus versions?

**Comment by Sanne** [comment] 2021-10-01 09:45
I suspect it's still a problem, and agree with Stuart it's most likely due to classloaders.

But it's not high on my priorities since it can easily be worked around by using `public` rather than `protected` - we'll look at it if a reproducer is shared.

**Comment by geoand** [comment] 2022-05-17 09:25
Closing as we never got a reproducer

**Closed by geoand** 2022-05-17 09:25 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm, needs-reproducer
