### ISSUE TITLE
JAX-RS subresources do not work in the native mode

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#4281] opened 2019-09-30 15:02 UTC
**Describe the bug**
JAX-RS subresources are not recognized in the native mode.

**Expected behavior**
They work as expected

**Actual behavior**
An exception like the one below is thrown:
```
019-09-30 13:38:04,247 ERROR [io.qua.resteasy] (vert.x-worker-thread-1) Unhandled Exception: java.lang.IllegalArgumentException: RESTEASY003895: Unable to find a public constructor for class org.acme.jwt.LottoNumbersResource
```
**To Reproduce**

Remove [this override](https://github.com/quarkusio/quarkus-quickstarts/blob/development/security-jwt-quickstart/src/test/java/org/acme/jwt/TokenSecuredResourceIT.java#L13) in the using-jwt-auth guide.
Note a subresource locator is [here](https://github.com/quarkusio/quarkus-quickstarts/blob/development/security-jwt-quickstart/src/main/java/org/acme/jwt/TokenSecuredResource.java#L127), the actual subresource handler is [here](https://github.com/quarkusio/quarkus-quickstarts/blob/development/security-jwt-quickstart/src/main/java/org/acme/jwt/LottoNumbersResource.java) (adding an explicit default constructor does not help)

**Comment by gastaldi** [comment] 2019-11-08 01:34
@sberyozkin it looks like the links in the issue description are broken (probably the quickstarts changed since you opened this issue). Can you update them?

**Comment by sberyozkin** [comment] 2019-11-08 15:53
@gastaldi thanks, 1 sec

**Comment by sberyozkin** [comment] 2019-11-08 15:57
Just noticed #5314, but not sure it is related

**Comment by geoand** [comment] 2021-02-19 10:45
Is this still a problem?

**Comment by tanadeau** [comment] 2021-02-24 17:51
@geoand, I just encountered this issue in Quarkus 1.12.0 so it appears to still be a problem.

**Comment by geoand** [comment] 2021-02-24 17:58
Do you have an example we could use to debug?

**Comment by tanadeau** [comment] 2021-02-24 18:41
Currently what I have is part of larger application that I can't send. I'll see if I can create a small reproducer later this week.

**Comment by geoand** [comment] 2021-02-24 18:58
Thanks

**Comment by geoand** [comment] 2021-08-02 11:14
I am going to close this as I can't reproduce the problem. If someone has a reproducer, feel free to comment and attach it

**Closed** 2021-08-02 11:20 UTC
Labels: kind/bug, triage/out-of-date
