### ISSUE TITLE
import.sql file creation no longer triggers a Quarkus reload and of Hibernate to run the changes

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#13337] opened 2020-11-17 08:36 UTC
Creating an `import.sql` file no longer reload the app and thus the file content is not taken into account

From From https://code.quarkus.io/?g=com.redhat.natwest&a=todo-app&v=1.0.0-SNAPSHOT&b=MAVEN&s=98e.YjV.ARC.XZs.8IG.0D7&cn=code.quarkus.io

Create a resource and an entity and DB settings

```
/**
 * @author Emmanuel Bernard emmanuel@hibernate.org
 */
@RestController
@RequestMapping(value = "/api", consumes="application/json", produces = "application/json")
public class TodoResource {
    @GetMapping
    public List<Todo> getAll() {
        return Todo.listAll(Sort.by("order"));
    }
}

package org.acme.resteasy;

import io.quarkus.hibernate.orm.panache.PanacheEntity;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.validation.constraints.NotBlank;

/**
 * @author Emmanuel Bernard emmanuel@hibernate.org
 */
@Entity
public class Todo extends PanacheEntity {
    @NotBlank @Column(nullable = false)
    public String title;
    public String url;
    public boolean completed;
    @Column(name="ordering")
    public Integer order;
}

# set DB - only mandatory part
quarkus.datasource.db-kind=postgresql
quarkus.datasource.jdbc.url=jdbc:postgresql:quarkus-demo
quarkus.datasource.username=quarkus-demo
quarkus.datasource.password=quarkus-demo

# Hibernate details
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
# don't do this at home !!!!!!
%prod.quarkus.hibernate-orm.database.generation=drop-and-create
%prod.quarkus.hibernate-orm.sql-load-script=import.sql
```

Then refresh browser

Then create `import.sql` and add

```
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Introduction to Quarkus', true, 0, null);
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Hibernate with Panache', false, 1, null);
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Visit Quarkus web site', false, 2, 'https://quarkus.io');
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project', false, 3, 'https://github.com/quarkusio/quarkus/');
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project 2', false, 3, 'https://github.com/quarkusio/quarkus/');
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project 3', false, 3, 'https://github.com/quarkusio/quarkus/');
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project 4', false, 3, 'https://github.com/quarkusio/quarkus/');
INSERT INTO todo(id, title, completed, ordering, url) VALUES (nextval('hibernate_sequence'), 'Star Quarkus project 5', false, 3, 'https://github.com/quarkusio/quarkus/');
```

Then refresh and the  content is not displayed
I get the following logs

```
 ~  Cod  qua  dem  nat  todo-app  mvn compile quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------< com.redhat.natwest:todo-app >---------------------
[INFO] Building todo-app 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.9.2.Final:generate-code (default) @ todo-app ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ todo-app ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 287 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ todo-app ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 3 source files to /Users/emmanuel/Code/quarkus/demos/natwest/todo-app/target/classes
[INFO]
[INFO] --- quarkus-maven-plugin:1.9.2.Final:dev (default-cli) @ todo-app ---
OpenJDK 64-Bit Server VM warning: forcing TieredStopAtLevel to full optimization because JVMCI is enabled
Listening for transport dt_socket at address: 5005
Hibernate:

    drop table if exists Todo cascade
Hibernate:

    drop sequence if exists hibernate_sequence
Hibernate: create sequence hibernate_sequence start 1 increment 1
Hibernate:

    create table Todo (
       id int8 not null,
        completed boolean not null,
        ordering int4,
        title varchar(255) not null,
        url varchar(255),
        primary key (id)
    )
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-11-17 09:24:07,981 INFO  [io.quarkus] (Quarkus Main Thread) todo-app 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.9.2.Final) started in 2.553s. Listening on: http://0.0.0.0:8080
2020-11-17 09:24:07,983 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-11-17 09:24:07,983 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-postgresql, mutiny, narayana-jta, resteasy, resteasy-jackson, resteasy-jsonb, smallrye-context-propagation, smallrye-openapi, spring-di, spring-web, swagger-ui]


2020-11-17 09:24:45,614 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Files changed but restart not needed - notified extensions in: 0.026s
Hibernate:
    select
        todo0_.id as id1_0_,
        todo0_.completed as complete2_0_,
        todo0_.ordering as ordering3_0_,
        todo0_.title as title4_0_,
        todo0_.url as url5_0_
    from
        Todo todo0_
    order by
        todo0_.ordering
```
```

**Comment by gsmet** [comment] 2020-11-17 12:01
Just FYI: we have a similar test case here: `AddNewSqlLoadScriptTestCase` - it's not testing adding the **default** import file though but a configured one.

**Comment by geoand** [comment] 2020-11-17 12:11
Hm...

I can only reproduce this if `%prod.quarkus.hibernate-orm.sql-load-script=import.sql` is used instead  of `quarkus.hibernate-orm.sql-load-script=import.sql`.

If I use `quarkus.hibernate-orm.sql-load-script=import.sql` and there is no `import.sql` file I can a very informative message containing ` Unable to find file referenced in 'quarkus.hibernate-orm.sql-load-script=import.sql'. Remove property or add file to your path.`.
When I do add the `import.sql` file everything works as expected.

Which to me seems reasonable, no?

**Comment by gsmet** [comment] 2020-11-17 12:29
In dev mode, `import.sql` should be taken into account automatically, even without configuration.

See https://github.com/quarkusio/quarkus/blob/master/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmConfigPersistenceUnit.java#L72

**Comment by geoand** [comment] 2020-11-17 12:32
Ah, that's interesting. So the problem is probably pretty simple, that we don't properly handle that case.

**Comment by geoand** [comment] 2020-11-17 13:05
The fix is indeed easy and small.

I'll add a test and open a PR

**Comment by Sanne** [comment] 2020-11-17 13:12
@geoand hey the issue was assigned to me :)  But cool, I have a test but didn't start looking at the fix.  I'll share the test with you

**Comment by Sanne** [comment] 2020-11-17 13:16
@geoand https://github.com/quarkusio/quarkus/commit/801ffbed13e9a6296ff03ff8ee572a0e7b58223c

**Comment by geoand** [comment] 2020-11-17 13:18
@Sanne sorry, it's just that after reproducing the issue, I was curious and only meant to fix it if I could do it real quickly.

Thanks for the test! I'll add it to my PR as a second commit

**Closed** 2020-11-17 16:08 UTC
Labels: area/core, area/hibernate-orm, area/panache, area/spring, area/user experience, kind/bug
