### ISSUE TITLE
Hibernate ORM update issue since 3.13.0

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#42902] opened 2024-08-30 09:40 UTC
### Describe the bug

Since 3.13.0 a panache update statement fails under certain conditions.

When detaching an entity, changing its primary key and persist it as duplicate without flushing , then updating the foreign key in another entity, the update statement fails as the session seems not to know the new id.

Calling an explicit flush after persists seems to workaround the problem.
This is a change of behavior from 3.12.3 to 3.13.0

This issue is related with the history of changes of https://github.com/quarkusio/quarkus/pull/42400

### Expected behavior

No change of behavior. All tests of the reproducer should pass using Quarkus 3.13.x

### How to Reproduce?

https://github.com/HerrDerb/quarkus-issue/tree/panache-entitymanager-session-issue
Run tests with 3.13.x -> one will fail

Run tests with 3.12.3 -> all pass

**Comment by yrodiere** [comment] 2024-08-30 13:23
Seems similar to #42322. I think this is related to https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.13#auto-flush-optimization

Previously Hibernate ORM in Quarkus was flushing indiscriminately before a query, leading to performance issues, especially compared to pretty much every other framework out there, where that sort of aggressive flushing is opt-in. We changed that to align on the rest of the ecosystem -- and on how Hibernate ORM expects to be used.

Your problem would hint at Hibernate ORM not auto-detecting that a flush is needed -- possibly a limitation of auto-flush, which you could try reporting upstream to get improved detection (with a reproducer based on https://github.com/hibernate/hibernate-test-case-templates/blob/main/orm/hibernate-orm-6/src/test/java/org/hibernate/bugs/QuarkusLikeORMUnitTestCase.java, ideally).

**Comment by FroMage** [comment] 2024-08-30 14:17
Thanks a lot @yrodiere :)

**Comment by yrodiere** [comment] 2024-09-03 14:15
Created https://hibernate.atlassian.net/browse/HHH-18559 upstream, let's see how that goes.

**Comment by HerrDerb** [comment] 2024-09-03 14:32
Thanks for you effort 👌😊

**Comment by yrodiere** [comment] 2024-09-04 12:29
So. [HHH-18559](https://hibernate.atlassian.net/browse/HHH-18559) was deemed "not a bug" as it seems in this particular case, auto-flush was not designed to help. Hence, this is unlikely to get fixed in Hibernate ORM 6.6 and Quarkus 3.13/3.14/3.15.

Now, there is still hope, since the Hibernate team is discussing [HHH-18563](https://hibernate.atlassian.net/browse/HHH-18563) and may end up implementing it in a future version of Hibernate ORM, assuming there are no major downsides.

In the meantime, I will close this, as it's not -- technically -- a bug: the previous behavior was unintended.

Reminder of workarounds for anyone ending up here:

1. add an explicit flush before your query
2. OR set the flush mode on your query using `.setHibernateFlushMode(FlushMode.ALWAYS)` / `.setHint(AvailableHints.HINT_FLUSH_MODE, FlushMode.ALWAYS)`  -- or with Panache, `withHint(AvailableHints.HINT_FLUSH_MODE, FlushMode.ALWAYS)`
3. OR set the flush mode on your session using `Session#setHibernateFlushMode`
4. OR revert to the old behavior in Quarkus 3.12 (and accept the performance hit that was present then, throughout your entire application):
```java
    // Put this in an `@ApplicationScoped` bean somewhere.
    void onBeginTransaction(@Observes @Initialized(TransactionScoped.class) Object event, Session session) {
        session.setHibernateFlushMode(FlushMode.ALWAYS);
    }
```

**Closed by yrodiere** 2024-09-04 12:29 UTC
Labels: kind/bug, triage/upstream, area/hibernate-orm

**Comment by cthiebault** [comment] 2024-09-05 07:07
Thanks for the hints @yrodiere !

I also have some issues with the new flush mode, so I tried to revert to the old behavior but I have exatly the same issues, so I imagine it didn't change the way the sessions are flushed.

Here is my code:

```kotlin
@ApplicationScoped
class HibernateFlushModeConfig {

  fun onBeginTransaction(@Observes @Initialized(TransactionScoped::class) event: Any, session: Session) {
    session.hibernateFlushMode = FlushMode.ALWAYS
  }

}
```

**Comment by cthiebault** [comment] 2024-09-06 07:56
Debugging  `io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession#setHibernateFlushMode`, I see that you are right with your 2 approaches @yrodiere:
- your code snippet works... even mine in Kotlin ;-)
- the setting in the `application.properties` also set the flush mode

But even with this, I get some `org.hibernate.FetchNotFoundException` with Quarkus 3.14.2 & `FlushMode.ALWAYS`  and it's working fine with Quarkus 3.12.3.

**Comment by yrodiere** [comment] 2024-09-06 10:14
> But even with this, I get some `org.hibernate.FetchNotFoundException` with Quarkus 3.14.2 & `FlushMode.ALWAYS`  and it's working fine with Quarkus 3.12.3.

Then this is probably a different problem... possibly one in Hibernate ORM... and we'll need a reproducer and report. Ideally directly in Hibernate ORM if you manage to write a reproducer based on https://github.com/hibernate/hibernate-test-case-templates/blob/main/orm/hibernate-orm-6/src/test/java/org/hibernate/bugs/QuarkusLikeORMUnitTestCase.java.

Thanks in advance :)
