### ISSUE TITLE
CompletionStage result doesn't work with @Authenticated

### ISSUE THREAD

**Issue by micheljung** [quarkusio/quarkus#21109] opened 2021-10-31 14:50 UTC
### Describe the bug

This
```
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

@Path("/test")
public class TestResource {

  @GET
  @Produces("application/json")
  public CompletionStage<Response> test() {
    return CompletableFuture.completedFuture(Response.ok("{\"value\": \"Test\"}").build());
  }
}
```
results in:
```
{"value": "Test"}
```

While this:
```
import io.quarkus.security.Authenticated;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.Response;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CompletionStage;

@Path("/test")
@Authenticated
public class TestResource {

  @GET
  @Produces("application/json")
  public CompletionStage<Response> test() {
    return CompletableFuture.completedFuture(Response.ok("{\"value\": \"Test\"}").build());
  }
}
```
results in:
```
{"done":true,"cancelled":false,"completedExceptionally":false,"numberOfDependents":0}
```

### Expected behavior

JSON representation of the object.

### Actual behavior

JSON representation of the completion stage.

### Quarkus version or git rev

2.4.0.Final

**Comment by stuartwdouglas** [comment] 2021-10-31 23:48
This is a duplicate of #20979

**Closed by stuartwdouglas** 2021-10-31 23:48 UTC
Labels: kind/bug, triage/needs-triage
