### ISSUE TITLE
Getting 401 Error: Unauthorized with KeyCloak token Bearer

### ISSUE THREAD

**Issue by EJNunez1311** [quarkusio/quarkus#13738] opened 2020-12-07 17:05 UTC
**Describe the bug**
Hi, I'm using KeyCloak to secure my web application with a bearer token. The first time I did set up my web application was working perfectly with notation @RolesAllowed and still was working fine. But sometimes when I re-run the application and post the request with the Token, the response that gave me is 401 Error: Unauthorized. Don't get why this happens sometimes.

**Expected behavior**
Allows me to get my actual response as authorized.
**Actual behavior**
Inconsistent authorized me, sometimes it won't via bearer token.

**To Reproduce**

**Maven project.**
`<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.proyecto</groupId>
  <artifactId>PruebaPKeycloak</artifactId>
  <version>1.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>1.8.2.Final</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>1.8.2.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-mysql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-oidc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-keycloak-authorization</artifactId>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
              <goal>build</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>`
**Screenshots**
![image](https://user-images.githubusercontent.com/39830766/101381022-9e755a80-388c-11eb-9890-0caad3eb938c.png)

**Additional context**
![image](https://user-images.githubusercontent.com/39830766/101381106-b9e06580-388c-11eb-8446-5842937f5c9a.png)

This is my final project for my degree.

**Configuration**
```properties
#application.properties

`#Datasource Config
quarkus.datasource.db-kind=mysql
quarkus.datasource.driver=com.mysql.cj.jdbc.Driver
quarkus.datasource.username=ej
quarkus.datasource.password=1234
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/employees
quarkus.hibernate-orm.log.sql=true
# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=update
quarkus.smallrye-openapi.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/explorer
mp.openapi.extensions.smallrye.operationIdStrategy=METHOD

# Keycloak with 100 offset
keycloak.url=http://localhost:8180

quarkus.oidc.enabled=true
quarkus.oidc.auth-server-url=${keycloak.url}/auth/realms/quarkus-realm
quarkus.oidc.client-id=quarkus-client
quarkus.oidc.credentials.secret=mysecret
quarkus.http.cors=true
quarkus.oidc.tls.verification=none
grant_type=password
`
**grant_type** is a variable that I use for my code.

**Comment by sberyozkin** [comment] 2020-12-07 17:43
@EJNunez1311 hi, the fact that sometimes one can get 401 is not a bug in itself. Perhaps sometimes the token is expired or there is a small clock skew. Try `quarkus.oidc.token.lifespan-grace=3` (secs).
I'm going to close this issue soon ; please try this property

**Comment by EJNunez1311** [comment] 2020-12-07 18:43
@sberyozkin hi, I follow what you've said, I'm still getting the same getting issue Unauthorized, Token is supposed to expires_in: 300 (5min). Is there anything else that I can try. Please thank you!

**Comment by EJNunez1311** [comment] 2020-12-07 19:14
@sberyozkin  I solved it, after getting to a conclusion with another colleague, probably it has to something to be with memory, cache, I don't know. My colleague tested the app on his computer and did work, so I restarted my computer, also did work. If this can be helpful to anybody, and in the future, if anybody knows more deeply why this happened let us know. Thanks for the help I've been reading other issues posted before. Thanks

**Comment by sberyozkin** [comment] 2020-12-07 22:18
Hi @EJNunez1311 Good news - we have seen such 401 errors before, caused by the tokens either being expired or, surprisingly, issued a few milliseconds in the future compared to the current time - so please keep in mind that property I mentioned as well. This is not so easy to trace though, another issue is opened to enhance Vert.x OAuth logging where it is checked...

**Closed by sberyozkin** 2020-12-07 22:18 UTC
Labels: area/oidc, kind/bug, triage/needs-triage
