### ISSUE TITLE
Using kotlinx.serialization in Kotlin fails after file change

### ISSUE THREAD

**Issue by andreabreu-me** [quarkusio/quarkus#4266] opened 2019-09-29 21:40 UTC
**Describe the bug**
Using `kotlinx.serialization` to serialize an object always fails on compiling Kotlin after editing the file in development mode.

**Expected behavior**
Compilation without errors.

**Actual behavior**
Running `./gradlew quarkusDev` and making some change to `ExampleResource.kt` fails.

```log
java.lang.RuntimeException: Compilation failed        return json.stringify(Person.serializer(), harry)
/Users/andreabreu/Development/andreabreu/quarkus-kotlinx-serialization/src/main/kotlin/me/andreabreu/ExampleResource.kt:24:38
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:47)
	at io.quarkus.dev.ClassLoaderCompiler.compile(ClassLoaderCompiler.java:157)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:164)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:103)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:52)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:44)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**To Reproduce**
1. `$ git clone https://github.com/andreabreu-me/quarkus-kotlinx-serialization`;
2. `$ ./gradlew quarkusDev`;
3. Open `http://0.0.0.0:8080/hello`;
4. Make a change to `ExampleResource.kt` file;
5. Reload the browser;

**Comment by geoand** [comment] 2019-09-30 09:22
This is basically a duplicate of #2811 because `kotlinx-serialization-runtime` is a compiler plugin which does not get applied during dev mode.

**Closed by geoand** 2019-09-30 09:22 UTC
Labels: bug, component:kotlin, duplicate
