### ISSUE TITLE
Metrics extension causes issues with Resteasy in native runtime

### ISSUE THREAD

**Issue by saharshsingh** [quarkusio/quarkus#6898] opened 2020-01-30 19:48 UTC
**Describe the bug**
I followed the [Creating Your First Application](https://quarkus.io/guides/getting-started) guide and created a simple JAX-RS/Resteasy app. I have my code uploaded on [Github](https://github.com/saharsh-samples/sample-quarkus-app). The app runs fine doing a JVM based build. However if I do a native build using the [multi stage Dockerfile](https://quarkus.io/guides/building-native-image#creating-a-container-with-a-multi-stage-docker-build), I start getting MethodNotFoundException errors. After some debugging it looks like the issue is inclusion of the metrics extension. Creating the app as is with the exception of adding the metrics stuff causes the native app to behave just fine.

**Expected behavior**
Runtime of native app behaves the way runtime of the jvm app does.

**Actual behavior**
Any HTTP requests (including readiness health check) results in a MethodNotFoundException in the runtime of the native app.

**To Reproduce**
1. Clone [my repo](https://github.com/saharsh-samples/sample-quarkus-app)
2. Build native executable for the app (e.g. `./mvnw clean package -Pnative -Dquarkus.native.container-runtime=podman`)
3. Run the app (will run on port 8080) - `./target/sample-quarkus-app-1.0-SNAPSHOT-runner &`
4. Consume the app's endpoints:
    - curl localhost:8080/api/values (causes exception - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/resources/ValuesResource.java))
    - curl localhost:8080/health/ready (causes exception - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/health/ReadinessCheck.java))
    - curl curl localhost:8080/health/live (works OK - see [relevant code](https://github.com/saharsh-samples/sample-quarkus-app/blob/master/src/main/java/org/saharsh/samples/quarkus/health/LivenessCheck.java))

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux sahsingh 5.3.16-300.fc31.x86_64 #1 SMP Fri Dec 13 17:59:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11" 2018-09-25
OpenJDK Runtime Environment 18.9 (build 11+28)
OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.2.0.Final`

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment] 2020-01-30 19:50
cc @jmartisk

**Comment by saharshsingh** [comment] 2020-01-30 19:53
Here's an example of the stack trace:

```
java.lang.NoSuchMethodException: org.saharsh.samples.quarkus.service.InMemoryStorageService.<init>
	at io.quarkus.arc.impl.Reflections.findConstructor(Reflections.java:46)
	at org.saharsh.samples.quarkus.service.InMemoryStorageService_Bean.create(InMemoryStorageService_Bean.zig:103)
	at org.saharsh.samples.quarkus.service.InMemoryStorageService_Bean.create(InMemoryStorageService_Bean.zig:191)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at org.saharsh.samples.quarkus.service.InMemoryStorageService_ClientProxy.arc$delegate(InMemoryStorageService_ClientProxy.zig:340)
	at org.saharsh.samples.quarkus.service.InMemoryStorageService_ClientProxy.isReady(InMemoryStorageService_ClientProxy.zig:173)
	at org.saharsh.samples.quarkus.health.ReadinessCheck.call(ReadinessCheck.java:26)
	at org.saharsh.samples.quarkus.health.ReadinessCheck_ClientProxy.call(ReadinessCheck_ClientProxy.zig:175)
	at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:154)
	at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:141)
	at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:129)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:107)
	at io.smallrye.health.SmallRyeHealthReporter.getReadiness(SmallRyeHealthReporter.java:97)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getReadiness(SmallRyeHealthReporter_ClientProxy.zig:101)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:40)
	at io.quarkus.smallrye.health.runtime.SmallRyeReadinessHandler.handle(SmallRyeReadinessHandler.java:32)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:19)
	at io.quarkus.vertx.http.runtime.ResumeHandler.handle(ResumeHandler.java:6)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:460)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
Caused by: java.lang.NoSuchMethodException: org.saharsh.samples.quarkus.service.InMemoryStorageService.<init>
	at java.lang.Class.getConstructor0(DynamicHub.java:3082)
	at java.lang.Class.getDeclaredConstructor(DynamicHub.java:2178)
	at io.quarkus.arc.impl.Reflections.findConstructor(Reflections.java:44)
	... 30 more
```

**Comment by jmartisk** [comment] 2020-01-31 12:44
Hm, it seems that the `NoSuchMethodException` occurs during `InMemoryStorageService` injection, but only if that bean contains a method annotated with `@Gauge`. If I remove the gauge, it works. But right now I have no idea why that happens, especially since it's in native mode only.
At build time, we dynamically attach an interceptor binding (`MetricsBinding`) to beans that contain a Gauge, but that's basically all that happens specifically to such beans at build (we don't actually register/initialize the gauge until the bean is instantiated). Perhaps it has something to do with that.

Anyway if it is necessary to fix quickly, I have a workaround for now: remove the `@Gauge` annotation from the `size()` method and instead register the gauge by including this in `InMemoryStorageService`:

```
@Inject
MetricRegistry metricRegistry;

@PostConstruct
public void sizeGauge() {
	metricRegistry.register(this.getClass().getName() + ".size", (org.eclipse.microprofile.metrics.Gauge<Long>) this::size);
}
```

It should be pretty much equivalent.

**Comment by gsmet** [comment] 2020-01-31 13:30
@jmartisk could it be that when you have a gauge, the bean is instantiated later and thus might need the constructor to be included in the native image?

**Comment by geoand** [comment] 2020-01-31 13:31
Perhaps we just need to register the bean for reflection when `@Gauge` is used?

**Comment by jmartisk** [comment] 2020-01-31 13:48
Including a `@Gauge` does not change when the bean is instantiated I think, it's still a regular `ApplicationScoped` bean, we just attach `@MetricsBinding`, which binds to it an interceptor that intercepts the bean's constructor (via `@AroundConstruct`)

**Comment by geoand** [comment] 2020-01-31 13:51
Sorry, I just saw the full error. Maybe we should just register `InMemoryStorageService` for reflection? Well just it's constructors I guess. That would probably be the easiest way to go, although I highly suspect we can get around that.

I can take a look if you like.

**Comment by jmartisk** [comment] 2020-01-31 14:00
> I can take a look if you like.

Of course, I will be glad. I'm quite busy with getting MP Metrics 2.3 out the door, so I wouldn't be able to spend a lot of time on this the next few days

**Comment by geoand** [comment] 2020-01-31 14:02
I'll try and take a look over the weekend, but I can't give any promises :). I'll post any updates here

**Comment by geoand** [comment] 2020-01-31 14:09
Again I spoke without looking at the details :)

I didn't realize that `InMemoryStorageService` was part of the application itself. Anyway, I'll get back with concrete info when I have it

**Comment by geoand** [comment] 2020-01-31 14:26
OK, actually there is no bug in Quarkus. 

It's just that the pattern used in the application needs a small fix in order to work in native mode.

Due to the use of:

```
	@Produces
	@ConfiguredStorage
	public StorageService createStorage(@Any Instance<StorageService> instance) {
		if (StorageServiceProducer.PERSISTENT.equals(storageType)) {
			return instance.select(PersistentStorageService.class).get();
		}
		return instance.select(InMemoryStorageService.class).get();
	}
```

it's expected that `InMemoryStorageService` and `PersistentStorageService` can be created from the default constructor.

To make that possilble in native mode, these classes need to be annotated with `@RegisterForReflection(fields = false, methods = true)`.

So I am going to close the issue as it's not a bug, however I would like @manovotn or @mkouba to comment on `StorageServiceProducer` which is:

```
public class StorageServiceProducer {

	private static final String INMEM = "inmem";
	private static final String PERSISTENT = "persistent";

	private final String storageType;

	@Inject
	public StorageServiceProducer(
			@ConfigProperty(name = "sample.storage.type", defaultValue = StorageServiceProducer.INMEM) String storageType) {
		this.storageType = storageType;
	}

	@Produces
	@ConfiguredStorage
	public StorageService createStorage(@Any Instance<StorageService> instance) {
		if (StorageServiceProducer.PERSISTENT.equals(storageType)) {
			return instance.select(PersistentStorageService.class).get();
		}
		return instance.select(InMemoryStorageService.class).get();
	}

}
```

I think that there is a way to better do it at build time, but it's late Friday and my brain is fried :P

**Comment by manovotn** [comment] 2020-01-31 20:04
@geoand You could read the config at build time (if that's an option here) and then generate [synthetic bean](https://quarkus.io/guides/cdi-reference#synthetic-beans) or register [additional bean](https://quarkus.io/guides/cdi-reference#additional-beans). Something like that?

**Comment by geoand** [comment] 2020-01-31 20:06
@manovotn I was basically asking what a user could do.
The pattern that is being used in this application seems common but I would really like to make it easier somehow for a user to choose the implementation (I guess based on some config value)

**Comment by manovotn** [comment] 2020-01-31 20:55
Well, in a way it is similar to those Spring-like profiles we were talking recently. On the same principle you could apply this.

**Comment by geoand** [comment] 2020-02-01 05:54
I woke up thinking exactly that 😂. 
I believe it's something we should consider adding

**Comment by saharshsingh** [comment] 2020-02-03 08:07
Awesome. Thanks @geoand ! The `@RegisterForReflection(fields = false, methods = true)` annotation worked like a charm.

**Comment by geoand** [comment] 2020-02-03 08:09
:+1:

**Comment by mkouba** [comment] 2020-02-03 12:05
So I think it is a bug in ArC. It shouldn't be necessary to use `@RegisterForReflection` - ArC should detect this requirement and register the class automatically. For the record - the reflection is used because of the `@Gauge` annotation and the related SmallRye `@AroundConstruct` interceptor.

Reopening...

**Comment by geoand** [comment] 2020-02-03 12:08
OK :)

**Closed** 2020-02-05 20:34 UTC
Labels: area/arc, kind/bug
