### ISSUE TITLE
quarkus-oidc: ID token verification failure: null

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#32967] opened 2023-04-27 17:54 UTC
### Describe the bug

The console shows an error `ERROR [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-3) ID token verification failure: null` when page http://localhost:8080 is called on the second start of the application.

### How to Reproduce?

[reproducer.zip](https://github.com/quarkusio/quarkus/files/11346542/reproducer.zip)

1. `./mvnw quarkus:dev`
2. http://localhost:8080/
3. Login
4. Kill the application
5. `./mvnw quarkus:dev`
6. http://localhost:8080/

=> `ERROR [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-3) ID token verification failure: null`

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by sberyozkin** [comment] 2023-04-27 18:11
@mschorsch Thanks for the reproducer, I'd say the issue is invalid, since when you kill the app, the session cookie persists, and when you restart, Keycloak generates new verification keys and therefore when you go to `localhost:8080` without closing the browser or clearing the cookies, the already available ID token can not be verified.

The error message definitely has to be fixed though, so I'll keep this issue open specifically to address this problem, I know exactly where this `null` message is coming from, forgot to fix earlier

Thanks

**Comment by mschorsch** [comment] 2023-04-27 18:13
@sberyozkin Makes sense. Thanks.

**Closed** 2023-05-08 14:53 UTC
Labels: kind/bug, area/oidc
