### ISSUE TITLE
Fault Tolerant retries and async 

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4774] opened 2019-10-22 21:33 UTC
**Describe the bug**

Using Fault Tolerance with Rest Client spec in async code, makes the request hung.

So I have the next code:

```
@GET
@Path("/beers")
@Produces(MediaType.APPLICATION_JSON)
@ClientHeaderParam(name="user-agent", value="curl/7.54.0")
CompletionStage<List<Beer>> getBeers(@QueryParam("page") int page);
```
And:

```
@GET
@Path("/firstpage")
@Produces(MediaType.APPLICATION_JSON)
public CompletionStage<List<Beer>> getFirstPageBeers() {
     return beerGateway.getBeers(1);
}
```
Then it works as expected but then if I add the fault tolerance:

```
@GET
@Path("/beers")
@Produces(MediaType.APPLICATION_JSON)
@ClientHeaderParam(name="user-agent", value="curl/7.54.0")
@Retry(maxRetries = 3, delay = 2000)
@Fallback(value = EmptyBeers.class)
@Asynchronous
CompletionStage<List<Beer>> getBeers(@QueryParam("page") int page);
```

Then it hangs.

Then if I remove the `@Asynchronous` then it does not hang but the retries are not happening in case of error.

**Expected behavior**

Call should happen in normal calls and do retries in case of failure.

**Actual behavior**

Application either hangs or does not apply automatic retries.

**Environment (please complete the following information):**
 - Quarkus 0.25.0

**Additional context**

Maybe this was the expected behaviour to not working in async code, but then we are missing an important use case.

**Comment by mkouba** [comment] 2019-10-23 08:28
@michalszynkiewicz @Ladicek Any ideas?

**Comment by emmanuelbernard** [comment] 2019-10-30 13:04
Bump up on FT hanging @michalszynkiewicz @Ladicek

**Comment by michalszynkiewicz** [comment] 2019-10-30 13:17
I will be looking at https://github.com/quarkusio/quarkus/issues/4826 soon, can try to tackle this one as well by the way

**Comment by Ladicek** [comment] 2019-10-30 13:28
I can reproduce this with Thorntail. I believe this is an un(der)specified interaction between Fault Tolerance and RestClient, because RestClient can do asynchronous invocations on its own, and when adding FT's `@Asynchronous`, there's 2nd level of async invocations going on.

**Comment by michalszynkiewicz** [comment] 2019-10-30 13:51
the fact that the `@Retry` is not invoked on without `@Asynchronous` is expected because FT treats the completion stage creation as the method under retry in this situation

**Comment by Ladicek** [comment] 2019-10-30 14:55
In case anyone's interested, here's my Thorntail test case: https://github.com/Ladicek/thorntail-test-suite/commit/0a09c24326e08c816be5031843dc3bc4d93f85af

**Comment by Ladicek** [comment] 2019-11-01 12:55
I was wondering if this could perhaps be caused by wrong interceptor order? When I was debugging this (in Thorntail context), the RestClient interceptor was applied before the Fault Tolerance interceptor. Could that possibly be wrong? (Honest question, I don't know.)

**Comment by michalszynkiewicz** [comment] 2019-11-08 13:56
it seems there's some infinite retry loop there for some reason, will continue to debug it.

**Comment by michalszynkiewicz** [comment] 2019-11-13 10:15
In an async FT invocation, the interceptor chain created by the Rest Client is proceeded asynchronously and bringing back the old position value https://github.com/resteasy/Resteasy/blob/05c0caec0af0c2fc889ddf3e018b8e2cdb72467c/resteasy-client-microprofile/src/main/java/org/jboss/resteasy/microprofile/client/InvocationContextImpl.java#L67 causes the FT interceptor to be invoked inifintely.

**Comment by Ladicek** [comment] 2019-11-13 10:31
Wouldn't that be fixed by inverting the interceptor order? That is, first the FT interceptor, and only after that the RestClient interceptor? (I'm not 100% sure what's the correct order...)

**Comment by michalszynkiewicz** [comment] 2019-11-13 10:35
interceptors for Rest Client are done somewhat manually. Maybe one could filter out interceptors with some priority values from the chain constructed there...

**Comment by michalszynkiewicz** [comment] 2019-11-13 12:11
so we need the decrementation to handle re-proceeding after initial failure of an interceptor. I'll implement one context per invocation as is done in Quarkus.

**Comment by michalszynkiewicz** [comment] 2019-11-13 13:20
Fix: https://github.com/resteasy/Resteasy/pull/2216

**Comment by gsmet** [comment] 2019-11-15 14:53
This has been solved by the RESTEasy upgrade.

**Closed by gsmet** 2019-11-15 14:53 UTC
Labels: backport?, bug, component:rest-client, component:smallrye
