### ISSUE TITLE
quarkus-hibernate-validator module ignore custom constraint validators defined in SPI file

### ISSUE THREAD

**Issue by anadollu** [quarkusio/quarkus#2974] opened 2019-06-26 08:41 UTC
**Describe the bug**
quarkus-hibernate-validator module ignores ConstraintValidators defined in 

/META-INF/services/javax.validation.ConstraintValidator file

**Expected behavior**
to be able to register custom constraint validators  for third party annotations in /META-INF/services/javax.validation.ConstraintValidator

**Actual behavior**
Custom constraint validators defined in SPI file not registered and ignored.

**To Reproduce**
1. Create new project with quarkus-hibernate-validator module
2. Create new constraint validator for one of existing constraint (For example create MinCustomValidator for @Min constraint)

```java
public class MinCustomValidator implements ConstraintValidator<Min, Long> {

  @Override
  public boolean isValid(Long value, ConstraintValidatorContext context) {
    return false;
  }
  
}
```

3. put the full class name in to the /META-INF/services/javax.validation.ConstraintValidator SPI file 

` com.acme.MinCustomValidator`

4. Add a simple rest resource with parameter annotated with selected annotation for the custom constraint validator.

```java
@GET
@Path("/{value}")
public Response validate(@Min(1) @PathParam("value") long value) {
}
```

5. Call endpoint with long value greater than 1

You will see that the custom constraint validator not taken into consideration

**Comment by gsmet** [comment] 2019-07-13 15:13
Just to let you know the issue is fixed in HV now: https://github.com/hibernate/hibernate-validator/pull/1041 .

But I can't release it right now as our CI is offline. Hopefully, it will come back soon and I'll update Quarkus to the new version.

**Closed** 2019-07-21 21:01 UTC
Labels: bug, component:hibernate-validator
