### ISSUE TITLE
Error starting application with vertx clustering and TCP stack 

### ISSUE THREAD

**Issue by eddiecarpenter** [quarkusio/quarkus#22880] opened 2022-01-13 21:32 UTC
### Describe the bug

We upgrade our project to Quarkus 2.6.1 and found a runtime error in the Vertx Cluster setup process.
We are specifically setting vertx.jgroups.config=default-configs/default-jgroups-tcp.xml (or default-configs/default-jgroups-kubernetes.xml). If this environment variable is not set error does not happen.

### Expected behavior

The jgroup stack should initialise and the application startup

### Actual behavior

The application terminates with the following stack dump.

2022-01-14 10:11:00,304 ERROR [io.ver.cor.imp.VertxImpl] (vert.x-eventloop-thread-0) Failed to initialize clustered Vert.x: java.lang.NoSuchMethodError: 'org.infinispan.configuration.global.TransportConfigurationBuilder org.infinispan.configuration.global.TransportConfigurationBuilder.addProperty(java.lang.String, java.lang.String)'
	at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$join$6(InfinispanClusterManager.java:257)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-01-14 10:11:00,311 ERROR [io.ver.cor.imp.VertxImpl] (vert.x-eventloop-thread-0) Failed to leave cluster: java.lang.NullPointerException: Cannot invoke "io.vertx.ext.cluster.infinispan.impl.SubsCacheHelper.close()" because "this.subsCacheHelper" is null
	at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$leave$7(InfinispanClusterManager.java:296)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

2022-01-14 10:11:00,338 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NoSuchMethodError: 'org.infinispan.configuration.global.TransportConfigurationBuilder org.infinispan.configuration.global.TransportConfigurationBuilder.addProperty(java.lang.String, java.lang.String)'
	at io.vertx.ext.cluster.infinispan.InfinispanClusterManager.lambda$join$6(InfinispanClusterManager.java:257)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:159)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:157)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:548)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

### How to Reproduce?

The project contains the code to reproduce.

Running the application remember to add "-Dvertx.jgroups.config=default-configs/default-jgroups-tcp.xml" to the environment settings.

[demo.zip](https://github.com/quarkusio/quarkus/files/7866128/demo.zip)

### Output of `uname -a` or `ver`

Darwin Eddies-MacBook-Pro.local 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:28:54 PST 2021; root:xnu-8019.61.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Zulu17.30+15-CA (build 17.0.1+12-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f) Maven home: /usr/local/Cellar/maven/3.8.2/libexec Java version: 17.0.1, vendor: Azul Systems, Inc., runtime: /Users/eddiecarpenter/Library/Java/JavaVirtualMachines/azul-17.0.1/Contents/Home Default locale: en_ZA, platform encoding: UTF-8 OS name: "mac os x", version: "11.1", arch: "x86_64", family: "mac"

**Comment by geoand** [comment] 2022-01-14 06:22
cc @karesti @cescoffier

**Comment by cescoffier** [comment] 2022-01-14 06:45
Vertx clustering has never been supported, as it would require quite some work in native. Did it work before?

Can you provide a reproducer?

Maybe @tsegismont has an idea.

**Comment by eddiecarpenter** [comment] 2022-01-14 07:50
Hi,

 

If you change the Quarkus version to 2.4.2 you will see that it then works.

 

Regards

Eddie

 

From: Clement Escoffier ***@***.***>
Reply to: quarkusio/quarkus ***@***.***>
Date: Friday, 14 January 2022 at 19:45
To: quarkusio/quarkus ***@***.***>
Cc: Eddie Carpenter ***@***.***>, Author ***@***.***>
Subject: Re: [quarkusio/quarkus] Error starting application with vertx clustering and TCP stack (Issue #22880)

 

Vertx clustering has never been supported, as it would require quite some work in native. Did it work before?

Can you provide a reproducer?

Maybe @tsegismont has an idea.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tsegismont** [comment] 2022-01-14 08:52
@eddiecarpenter what @cescoffier said is right, clustering has never been supported, although the vert.x clustering options were available.

I know some users were able to make it work, by changing to a different version of Hazelcast or Kubernetes that Quarkus sets in the BOM. Perhaps you need to do the same here, it seems your project depends on a version of Infinispan that is incompatible with the versions that Vert.x depends on.

**Comment by eddiecarpenter** [comment] 2022-01-14 11:13
Hi Thomas,

 

That is what I thought as well. If you have look at the pom file you will note that I have trimmed it down to the bare minimum. The only dependency on Infinispan comes from vertx-infinispan.

I do think the problem lies version/dependency on a module that Quarkus is using a newer version than vertx-Infinispan.

Regards

Eddie

 

 

From: Thomas Segismont ***@***.***>
Reply to: quarkusio/quarkus ***@***.***>
Date: Friday, 14 January 2022 at 21:52
To: quarkusio/quarkus ***@***.***>
Cc: Eddie Carpenter ***@***.***>, Mention ***@***.***>
Subject: Re: [quarkusio/quarkus] Error starting application with vertx clustering and TCP stack (Issue #22880)

 

@eddiecarpenter what @cescoffier said is right, clustering has never been supported, although the vert.x clustering options were available.

I know some users were able to make it work, by changing to a different version of Hazelcast or Kubernetes that Quarkus sets in the BOM. Perhaps you need to do the same here, it seems your project depends on a version of Infinispan that is incompatible with the versions that Vert.x depends on.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by tsegismont** [comment] 2022-01-14 13:21
If you run `mvn dependency:tree` you will find:

```
[INFO] \- io.vertx:vertx-infinispan:jar:4.2.2:compile
[INFO]    +- io.vertx:vertx-core:jar:4.2.2:compile
[INFO]    |  +- io.netty:netty-handler-proxy:jar:4.1.72.Final:compile
[INFO]    |  |  \- io.netty:netty-codec-socks:jar:4.1.72.Final:compile
[INFO]    |  +- io.netty:netty-resolver-dns:jar:4.1.72.Final:compile
[INFO]    |  |  \- io.netty:netty-codec-dns:jar:4.1.72.Final:compile
[INFO]    |  \- com.fasterxml.jackson.core:jackson-core:jar:2.12.6:compile
[INFO]    +- org.infinispan:infinispan-core:jar:13.0.5.Final:compile
[INFO]    |  +- org.infinispan:infinispan-commons:jar:13.0.5.Final:compile
[INFO]    |  +- org.infinispan.protostream:protostream:jar:4.4.1.Final:compile
[INFO]    |  +- org.infinispan.protostream:protostream-types:jar:4.4.1.Final:compile
[INFO]    |  \- org.jgroups:jgroups:jar:4.2.18.Final:compile
[INFO]    +- org.wildfly.common:wildfly-common:jar:1.5.4.Final-format-001:compile
[INFO]    +- org.infinispan:infinispan-multimap:jar:12.1.7.Final:compile
[INFO]    +- com.github.ben-manes.caffeine:caffeine:jar:2.9.3:compile
[INFO]    +- org.infinispan:infinispan-clustered-lock:jar:12.1.7.Final:compile
[INFO]    +- org.infinispan:infinispan-clustered-counter:jar:12.1.7.Final:compile
[INFO]    +- io.reactivex.rxjava3:rxjava:jar:3.0.13:compile
[INFO]    \- org.reactivestreams:reactive-streams:jar:1.0.3:compile
```

Notice the version mismatch between `infinispan-multimap` (`12.1.7.Final`) and `infinispan-core` (`13.0.5.Final`).

I suspect this is due to the version of Infinispan Core set by the Quarkus BOM that is incompatible with the version that Vert.x depends on.

Please try adding this to your POM file:

```xml
<dependency>
  <groupId>org.infinispan</groupId>
  <artifactId>infinispan-core</artifactId>
  <version>12.1.7.Final</version>
</dependency>
```

**Comment by geoand** [comment] 2022-01-14 13:24
Closing this as it's not a Quarkus issue per-se.

**Closed by geoand** 2022-01-14 13:24 UTC
Labels: kind/bug, area/kubernetes
