### ISSUE TITLE
DI is not working properly on Job instances when scheduling quartz jobs programmatically

### ISSUE THREAD

**Issue by lbroman** [quarkusio/quarkus#14407] opened 2021-01-19 20:53 UTC
**Describe the bug**
When using job classes with programmatic job/triggers in quartz, fields annotated with @Inject gets injected, but with instances that have fields which have not been injected.

I discovered this problem when using a @ConfigProperty field which had different values at different times. After elaborating, this also applies to @Inject ed fields.

**Expected behavior**
Fields on injected beens in Job classes should also have their fields injected.

**Actual behavior**
Fields injected with @Inject and @ConfigProperty are null (or primitive default) when using a bean injected into a Job class.

**To Reproduce**
https://github.com/lbroman/quarkus-config-bug

Run with 

    mvn test

Result will put out some log and you will find 

    2021-01-19 21:40:24,895 INFO  [se.lbr.qua.JobScheduler] (main) Setting is: true
    2021-01-19 21:40:24,915 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Setting is: false

JobScheduler is application scoped and setting is injected with @ConfigProperty. The value of the field is correct during init, but incorrect when accessed from quartz via the Job instance.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MINGW64_NT-10.0-18362 BB904078 3.0.7-338.x86_64 2019-07-03 15:16 UTC x86_64 Msys
 - Output of `java -version`: 
 - openjdk version "15" 2020-09-15 
    OpenJDK Runtime Environment (build 15+36-1562)
    OpenJDK 64-Bit Server VM (build 15+36-1562, mixed mode, sharing)

 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: tried 1.10.5.Final and 1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)

**Comment by machi1990** [comment] 2021-01-19 22:36
By moving the [UpdateJob](https://github.com/lbroman/quarkus-config-bug/blob/152e4d1ece237923e40e322250fce834426dc4fa/src/main/java/se/lbroman/quarkus/JobScheduler.java#L62) class to an upper class (i.e into a file of its own), I've the following output
```
mvn test

2021-01-19 23:27:59,010 INFO  [se.lbr.qua.JobScheduler] (main) Starting
2021-01-19 23:27:59,012 INFO  [se.lbr.qua.JobScheduler] (main) Setting is: true
2021-01-19 23:27:59,013 DEBUG [se.lbr.qua.JobScheduler] (main) Schedule for update 2021-01-19 23:27:59
2021-01-19 23:27:59,016 DEBUG [se.lbr.qua.JobScheduler] (main) Schedule for update 2021-01-19 23:28:00
2021-01-19 23:27:59,017 INFO  [se.lbr.qua.JobScheduler] (main) Setting is: true
2021-01-19 23:27:59,023 DEBUG [se.lbr.qua.UpdateJob] (QuarkusQuartzScheduler_Worker-1) Execute Job
2021-01-19 23:27:59,024 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Updating
2021-01-19 23:27:59,024 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Setting is: true
2021-01-19 23:27:59,024 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Done
2021-01-19 23:27:59,025 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Updating
2021-01-19 23:27:59,025 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Setting is: true
2021-01-19 23:27:59,025 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Done
2021-01-19 23:28:00,019 DEBUG [se.lbr.qua.UpdateJob] (QuarkusQuartzScheduler_Worker-2) Execute Job
2021-01-19 23:28:00,020 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Updating
2021-01-19 23:28:00,020 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Setting is: true
2021-01-19 23:28:00,021 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Done
2021-01-19 23:28:00,021 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Updating
2021-01-19 23:28:00,022 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Setting is: true
2021-01-19 23:28:00,022 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Done
```
@lbroman can you confirm the output is correct with that change? 

However, leaving it as it is indeed indicates the problem as shown by output below. 
```
mvn test
2021-01-19 23:29:05,138 INFO  [se.lbr.qua.JobScheduler] (main) Starting
2021-01-19 23:29:05,140 INFO  [se.lbr.qua.JobScheduler] (main) Setting is: true
2021-01-19 23:29:05,141 DEBUG [se.lbr.qua.JobScheduler] (main) Schedule for update 2021-01-19 23:29:05
2021-01-19 23:29:05,144 DEBUG [se.lbr.qua.JobScheduler] (main) Schedule for update 2021-01-19 23:29:06
2021-01-19 23:29:05,144 INFO  [se.lbr.qua.JobScheduler] (main) Setting is: true
2021-01-19 23:29:05,146 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Execute Job
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Updating
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Setting is: false
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Done
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Updating
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Setting is: false
2021-01-19 23:29:05,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-1) Done
2021-01-19 23:29:06,146 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Execute Job
2021-01-19 23:29:06,147 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Updating
2021-01-19 23:29:06,148 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Setting is: false
2021-01-19 23:29:06,148 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Done
2021-01-19 23:29:06,149 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Updating
2021-01-19 23:29:06,149 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Setting is: false
2021-01-19 23:29:06,149 DEBUG [se.lbr.qua.JobScheduler] (QuarkusQuartzScheduler_Worker-2) Done

````
@mkouba would you have an idea why this is happening?

**Comment by mkouba** [comment] 2021-01-20 07:25
Hello, the problem is that `se.lbroman.quarkus.JobScheduler.doUpdate()` is `private` and so if you [invoke the method upon the injected proxy](https://github.com/lbroman/quarkus-config-bug/blob/152e4d1ece237923e40e322250fce834426dc4fa/src/main/java/se/lbroman/quarkus/JobScheduler.java#L71) then the invocation is not delegated to the target bean instance and the client proxy has no state (`JobScheduler.setting` is false).

Note a client proxy is used for any CDI bean with a normal scope. See also https://quarkus.io/guides/cdi#client_proxies for more information.

> By moving the UpdateJob class to an upper class (i.e into a file of its own), I've the following output

@machi1990 This should definitely help because you would have to change the visibility of the `JobScheduler.doUpdate()` method.

Solutions:
1. Change the visibility of the `JobScheduler.doUpdate()` to public or package-private
2. Change the scope of `JobScheduler` to `javax.inject.Singleton` (no client proxy is used)

**Comment by machi1990** [comment] 2021-01-20 07:49
> Hello, the problem is that `se.lbroman.quarkus.JobScheduler.doUpdate()` is `private` and so if you [invoke the method upon the injected proxy](https://github.com/lbroman/quarkus-config-bug/blob/152e4d1ece237923e40e322250fce834426dc4fa/src/main/java/se/lbroman/quarkus/JobScheduler.java#L71) then the invocation is not delegated to the target bean instance and the client proxy has no state (`JobScheduler.setting` is false).
> 
> Note a client proxy is used for any CDI bean with a normal scope. See also https://quarkus.io/guides/cdi#client_proxies for more information.
> 
> > By moving the UpdateJob class to an upper class (i.e into a file of its own), I've the following output
> 
> @machi1990 This should definitely help because you would have to change the visibility of the `JobScheduler.doUpdate()` method.
> 
> Solutions:
> 
> 1. Change the visibility of the `JobScheduler.doUpdate()` to public or package-private
> 2. Change the scope of `JobScheduler` to `javax.inject.Singleton` (no client proxy is used)

Thanks @mkouba for the explanation.

**Comment by geoand** [comment] 2021-01-20 08:04
I'm going to close this as it is not a problem in Quarkus

**Closed by geoand** 2021-01-20 08:04 UTC
Labels: area/scheduler, kind/bug

**Comment by lbroman** [comment] 2021-01-20 08:11
Sorry for posting what was actually a support question as a bug. I would not have been able to figure this out myself. Thanks so much for the explanation!

**Comment by manovotn** [comment] 2021-01-20 08:24
FTR, as per @mkouba's request I've verified this with Weld (CDI reference implementation) and I can confirm that it behaves equally.
