### ISSUE TITLE
add extensions in gradle

### ISSUE THREAD

**Issue by cniweb** [quarkusio/quarkus#1790] opened 2019-04-01 10:10 UTC
Implement functionality to automatically add extensions to your Gradle project

**Comment by cniweb** [comment] 2019-04-01 10:16
An initial implementation already exists, but unfortunately without function:
https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusAddExtension.java

**Comment by stalep** [comment] 2019-04-01 13:26
Hi, yes it's on our todo :)

**Comment by dhoffi** [comment] 2019-04-08 09:41
well, not being able to addExtension makes the gradle support pretty limited useful ... doesn't it?

**Comment by cniweb** [comment] 2019-04-10 21:37
@dhoffi Yes, you are right, that makes the support of Gradle quite limited useful

**Comment by Dufgui** [comment] 2019-07-27 23:33
duplicate of #3102

**Comment by Dufgui** [comment] 2019-08-09 17:26
@aloubyansky could you assign to me or close it. Please. I have done the based of it in #3415   We just need to call it from the task

**Closed** 2019-08-12 10:13 UTC
Labels: component:gradle
