### ISSUE TITLE
amazon-lambda fails when paired with oidc-client in dev mode

### ISSUE THREAD

**Issue by snowe2010** [quarkusio/quarkus#21523] opened 2021-11-17 18:33 UTC
### Describe the bug

I'm attempting to call an api from an Amazon Lambda. The api is authenticated by OIDC, so with help from @sberyozkin [in zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.E2.9C.94.20OAuth.202.20authorization.20for.20RestClient), I got OIDC working through a regular jaxrs Resource. But when attempting to switch this out for a RequestHandler (or RequestStreamHandler, it didn't matter when I tested with the example repo provided below), it fails with this error message:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.acme:rest-client-lambda-bug >-------------------
[INFO] Building rest-client-lambda-bug 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ rest-client-lambda-bug ---
[INFO] Deleting /Users/tyler/Documents/dev/work/temp/rest-client-lambda-bug/target
[INFO] 
[INFO] --- quarkus-maven-plugin:2.4.2.Final:dev (default-cli) @ rest-client-lambda-bug ---
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.4.2.Final:generate-code) @ rest-client-lambda-bug
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources) @ rest-client-lambda-bug
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Invoking org.jetbrains.kotlin:kotlin-maven-plugin:1.5.31:compile) @ rest-client-lambda-bug
[INFO] Applied plugin: 'all-open'
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile) @ rest-client-lambda-bug
[INFO] Changes detected - recompiling the module!
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources) @ rest-client-lambda-bug
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/tyler/Documents/dev/work/temp/rest-client-lambda-bug/src/test/resources
[INFO] Invoking org.jetbrains.kotlin:kotlin-maven-plugin:1.5.31:test-compile) @ rest-client-lambda-bug
[WARNING] No sources found skipping Kotlin compile
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile) @ rest-client-lambda-bug
[INFO] Changes detected - recompiling the module!
Listening for transport dt_socket at address: 5005
2021-11-17 11:27:52,988 INFO  [io.qua.ama.lam.run.MockEventServer] (build-26) Mock Lambda Event Server Started
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-11-17 11:27:54,059 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Listening on: http://localhost:8080/_lambda_/2018-06-01/runtime/invocation/next

2021-11-17 11:27:54,057 INFO  [io.quarkus] (Quarkus Main Thread) rest-client-lambda-bug 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.4.2.Final) started in 1.939s. Listening on: http://localhost:8080
2021-11-17 11:27:54,061 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2021-11-17 11:27:54,061 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [amazon-lambda, cdi, kotlin, oidc-client, oidc-client-filter, rest-client, rest-client-jackson, smallrye-context-propagation, vertx]
2021-11-17 11:28:22,036 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Error running lambda (DEVELOPMENT): java.net.NoRouteToHostException: Can't assign requested address (Address not available)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:83)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.NoRouteToHostException: Can't assign requested address (Address not available)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:82)
        ... 1 more


2021-11-17 11:28:22,122 ERROR [io.qua.run.StartupContext] (Lambda Thread (DEVELOPMENT)) Running a shutdown task failed: java.lang.IllegalStateException: Unable to unregister all message consumer methods
        at io.quarkus.vertx.runtime.VertxRecorder.unregisterMessageConsumers(VertxRecorder.java:181)
        at io.quarkus.vertx.runtime.VertxRecorder$1.run(VertxRecorder.java:51)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:83)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:72)
        at io.quarkus.runner.ApplicationImpl.doStop(ApplicationImpl.zig:858)
        at io.quarkus.runtime.Application.stop(Application.java:203)
        at io.quarkus.runtime.Application.stop(Application.java:155)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1343)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
        at io.quarkus.vertx.runtime.VertxRecorder.unregisterMessageConsumers(VertxRecorder.java:178)
        ... 8 more


2021-11-17 11:28:22,146 INFO  [io.quarkus] (Lambda Thread (DEVELOPMENT)) rest-client-lambda-bug stopped in 0.044s
2021-11-17 11:28:22,149 INFO  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Lambda polling thread complete (DEVELOPMENT)

--
```

[reproducer repo](https://github.com/snowe2010/quarkus-oidc-lambda-bug)

@patriot1burke, @sberyozkin asked me to tag you.

### Expected behavior

I expect the lambda handler to make the exact same call as the Resource (it should fail with not-found, since the oidc client isn't configured. if the oidc client is configured it should actually make the call and succeed). 

### Actual behavior

Actual behavior is that it throws a very strange error indicating that it can't find some route (what route? I don't know, it fails when the oidc client route is provided as well as when it's not provided)

```

2021-11-17 11:28:22,036 ERROR [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Error running lambda (DEVELOPMENT): java.net.NoRouteToHostException: Can't assign requested address (Address not available)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
        at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:83)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.NoRouteToHostException: Can't assign requested address (Address not available)
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at java.base/java.net.Socket.connect(Socket.java:558)
        at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
        at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
        at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
        at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1253)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1187)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1081)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1015)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1592)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
        at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:82)
        ... 1 more


2021-11-17 11:28:22,122 ERROR [io.qua.run.StartupContext] (Lambda Thread (DEVELOPMENT)) Running a shutdown task failed: java.lang.IllegalStateException: Unable to unregister all message consumer methods
        at io.quarkus.vertx.runtime.VertxRecorder.unregisterMessageConsumers(VertxRecorder.java:181)
        at io.quarkus.vertx.runtime.VertxRecorder$1.run(VertxRecorder.java:51)
        at io.quarkus.runtime.StartupContext.runAllInReverseOrder(StartupContext.java:83)
        at io.quarkus.runtime.StartupContext.close(StartupContext.java:72)
        at io.quarkus.runner.ApplicationImpl.doStop(ApplicationImpl.zig:858)
        at io.quarkus.runtime.Application.stop(Application.java:203)
        at io.quarkus.runtime.Application.stop(Application.java:155)
        at io.quarkus.amazon.lambda.runtime.AbstractLambdaPollLoop$1.run(AbstractLambdaPollLoop.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.InterruptedException
        at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1343)
        at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:232)
        at io.quarkus.vertx.runtime.VertxRecorder.unregisterMessageConsumers(VertxRecorder.java:178)
        ... 8 more
```

### How to Reproduce?

From the readme of the [reproducer repo](https://github.com/snowe2010/quarkus-oidc-lambda-bug):

Demonstrating the bug:

Steps:
* run with `mvn clean quarkus:dev`
* just wait. The error message will show up after a few seconds. You don't need to do anything. 
* comment out the lambda handler, the imports for the lambda handler, and the amazon-lambda dependency in the pom
* uncomment the Resource
* run the command 
```bash
curl --header "Content-Type: application/json" \
        --data '{}' \
        http://localhost:8080/test
```
to see it 'succeed' (won't actually succeed since no oidc details are set up, but demonstrates the issue, no error is thrown on startup)

### Output of `uname -a` or `ver`

Darwin SR-MB-300245 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021; root:xnu-8019.41.5~1/RELEASE_X86_64 x86_64

### Output of `java -version`

graalvm-21.0.0+java11 (see .tool-versions file)

### GraalVM version (if different from Java)

graalvm-21.0.0+java11 (see .tool-versions file)

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.1 (see .tool-versions file)

### Additional information

[reproducer in zip form (in case I ever delete the example repo)](https://github.com/quarkusio/quarkus/files/7556953/rest-client-lambda-bug.zip)

**Comment by sberyozkin** [comment] 2021-11-17 18:53
@snowe2010 The reproducer repo does not show any OIDC configuration

**Comment by snowe2010** [comment] 2021-11-17 21:29
@sberyozkin yes, but it should at least succeed at starting up, which is does with rest-client and it doesn't with amazon-lambda. I don't know what OIDC config I could put in here that would actually work for demonstration purposes. If you have one I can update the reproducer, but as it is, it demonstrates the issue as I see it even with the config missing.

**Comment by sberyozkin** [comment] 2021-11-18 10:21
@snowe2010 The following answer provides a good summary, https://stackoverflow.com/a/38721897/1133928

**Comment by sberyozkin** [comment] 2021-11-19 10:53
@snowe2010 I had a brief look yesterday, the problem I believe is due to the fact `OidcClient` tries to initialize as suggested in Zulip - it is enabled by default - and nothing is configured it fails - the exception which it throws is not shown by the lamda code so it gets confusing.
The problem which you have identified is that you start the app in the dev mode - and here `quarkus-oidc-client` should not interfere if no `quarkus.oidc-client.auth-server-url` is found but it is a dev mode - I'll fix it and resolve this issue.

By the way, the following config optimization would also apply in your case:  #21545

**Comment by sberyozkin** [comment] 2021-11-19 14:18
@snowe2010 My test shows `oidc-client` works fine in the dev mode, without the URL...

**Comment by sberyozkin** [comment] 2021-11-19 14:45
@snowe2010 I can't even reproduce this exception - the only I've been seeing is a port clash (between Quarkus server and likely the lambda wiremock) so I added `-Dquarkus.http.port=8083` and it all just starts fine. I'm going to close this issue as `can't reproduce` - but please reopen with a more specific reproducer if it persists for you even after you add `-Dquarkus.http.port`.
Thank you

**Closed by sberyozkin** 2021-11-19 14:45 UTC
Labels: kind/bug, area/kotlin, area/amazon-lambda, area/oidc
