### ISSUE TITLE
Resteasy Reactive throws java.lang.IllegalArgumentException: stream cannot be null when @Valid is used with @BeanParam

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#14461] opened 2021-01-21 01:30 UTC
**Describe the bug**
Having an endpoint like:
```java
@Path("/hello-resteasy-reactive")
public class ReactiveGreetingResource {

    @POST
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@Valid @BeanParam Coords c) {
        return c.groupId + ":" + c.artifactId;
    }
}
```
When you attempt to build the project, the build fails with the following error:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.11.0.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.BeanArchiveProcessor#build threw an exception: java.lang.IllegalArgumentException: stream cannot be null
[ERROR] 	at org.jboss.jandex.Indexer.index(Indexer.java:1595)
[ERROR] 	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:83)
[ERROR] 	at io.quarkus.arc.deployment.BeanArchiveProcessor.build(BeanArchiveProcessor.java:61)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

 
**Expected behavior**
Build should succeed

**Actual behavior**
Build Fails. Removing `@Valid` works.

**To Reproduce**

Download the following project: [code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5846229/code-with-quarkus.zip)

- Unzip the project above and run `mvn clean package`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Fedora 33
 - Output of `java -version`: JDK 11 
 - GraalVM version (if different from Java): not used
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Comment by gastaldi** [comment] 2021-01-21 01:32
I see this in the logs:
```
[DEBUG] [io.quarkus.deployment.index] Index bean class: @Valid io.quarkus.registry.app.endpoints.ArtifactCoords
```

which looks wrong (the `@Valid` is there)

**Comment by stuartwdouglas** [comment] 2021-01-21 01:59
This is fixed upstream (duplicate of https://github.com/quarkusio/quarkus/issues/14348)

**Closed by stuartwdouglas** 2021-01-21 01:59 UTC
Labels: area/resteasy-reactive, kind/bug

**Comment by gastaldi** [comment] 2021-01-21 02:06
Oops, thanks!
