### ISSUE TITLE
Result of native query cannot be casted to String, when working with MySQL

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#22254] opened 2021-12-15 16:35 UTC
### Describe the bug

If we use method `createNativeQuery` of class `org.hibernate.reactive.mutiny.Mutiny.SessionFactory` to run query against MySQL or MariaDB database and return the query's result as String, we receive an error `com.sun.proxy.$Proxy33 cannot be cast to class java.lang.String`.

### Expected behavior

We should be able to receive a result of a native query.

### Actual behavior

The method throws an exception.

### How to Reproduce?

Reproducer: https://github.com/fedinskiy/quarkus-test-suite/tree/reproducer/hibernate-mysql-string

Steps to reproduce:
1) Run `mvn clean verify -pl io.quarkus.ts.qe:hibernate-reactive -Dit.test=MySQLDatabaseIT#reproducer*`
OR
2) Run `mvn clean verify -pl io.quarkus.ts.qe:hibernate-reactive -Dit.test=MariaDbDatabaseIT#reproducer*`

Method `reproducerTitle`, which accesses data like this: `session.createNativeQuery("SELECT title FROM books WHERE id = " + id, String.class)` fails.
Method `reproducerBook`, which accesses data like this: `session.createNativeQuery(""SELECT * FROM books WHERE id = " + id, Book.class)` succeeds.

For comparison, if we replace `MySQLDatabaseIT` in the first step to `Postgresql13DatabaseIT`, `MsSQLDatabaseIT` or `DB2DatabaseIT`, which use exactly the same code, but connect to other databases( with corresponding drivers), both methods succeed.

Since there is no MariaDB-specific driver in Reactive Hibernate, both MySQLDatabaseIT and MariaDbDatabaseIT use the same parameters and drivers, but connect to different DBMS.

### Output of `uname -a` or `ver`

OS name: "linux", version: "5.15.6-100.fc34.x86_64"

### Output of `java -version`

11.0.13, vendor: Eclipse Adoptium

### Quarkus version or git rev

4b4d655db69d527df39c3c00aff3281a36248760

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by fedinskiy** [comment] 2021-12-15 16:36
Proper label is probably this one: https://github.com/quarkusio/quarkus/labels/area%2Fhibernate-reactive

**Comment by DavideD** [comment] 2021-12-16 09:14
I will check

**Comment by DavideD** [comment] 2021-12-16 13:51
I cannot run this testsuite. I have this error:
```
RROR] [ERROR] Some problems were encountered while processing the POMs:
[WARNING] 'build.plugins.plugin.version' for io.quarkus:quarkus-maven-plugin is missing. @ line 23, column 21
[ERROR] 'dependencies.dependency.version' for org.flywaydb:flyway-sqlserver:jar is missing. @ line 54, column 21
 @ 
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project io.quarkus.ts.qe:vertx-sql:1.0.0-SNAPSHOT (/home/ddalto/workspace/quarkus-test-suite/sql-db/vertx-sql/pom.xml) has 1 error
[ERROR]     'dependencies.dependency.version' for org.flywaydb:flyway-sqlserver:jar is missing. @ line 54, column 21
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:

```

**Comment by DavideD** [comment] 2021-12-16 15:47
@fedinskiy I've  applied some changes to this branch: https://github.com/DavideD/quarkus-test-suite/tree/reproducer/hibernate-mysql-string

**Comment by fedinskiy** [comment] 2022-01-04 08:38
@DavideD I ran the checks on commit c16115ec1b1092bbedeb5f14dc39848383e068d4 and this is the result:

```
MySQLDatabaseIT>AbstractReactiveDatabaseIT.reproducerTitle:258 expected: <Thinking fast and slow> but was: <{"code":500,"error":"class com.sun.proxy.$Proxy36 cannot be cast to class java.lang.String (com.sun.proxy.$Proxy36 is in unnamed module of loader io.quarkus.bootstrap.runner.RunnerClassLoader @3cbbc1e0; java.lang.String is in module java.base of loader 'bootstrap')"}>

```

**Comment by fedinskiy** [comment] 2022-01-04 08:46
I also removed source of fails in the reproducer, it should now work properly.

**Comment by DavideD** [comment] 2022-01-10 14:31
Can somebody assign this to me, please?

**Comment by DavideD** [comment] 2022-01-21 17:18
The propery `title` is mapped on a column of type `text` in the database. This means that the value returned by a native query is going to be a `java.sql.Blob`.

The error happens because `session.createNativeQuery("SELECT title FROM books WHERE id = " + id, String.class)` is trying to cast a `Blob` into a `String`.

I can see three possible solutions:

* Convert the blob value into a String:
    ```
            return session.createNativeQuery("SELECT title FROM books WHERE id = " + id, Blob.class)
                    .getSingleResult()
                    .chain(blob -> {
						try {
							String str = new String( blob.getBytes( 1l, (int) blob.length() ) );
							return Uni.createFrom().item( Response.ok( blob ).build() );
						}
						catch (Throwable t) {
							return Uni.createFrom().failure( t );
						}
					});
    ```
* Use a HQL query:
  ```
              return session.createQuery("SELECT title FROM Book WHERE id = " + id, String.class)
                    .getSingleResult()
                    .map(title -> Response.ok(title).build());
  ```
* Change the column type to varchar
  ```
  title varchar(255) NOT NULL,
  ```

Not sure what you are trying to test but any of these three fixes the issue.

**Comment by DavideD** [comment] 2022-01-21 17:20
@Sanne I don't think this is a bug and we can close this issue

**Closed** 2022-01-24 11:23 UTC
Labels: kind/bug, area/hibernate-reactive

**Comment by fedinskiy** [comment] 2022-09-27 11:27
@DavideD I run the tests and you're right and if text replaced with varchar, the tests work as expected.

But it is not very clear, why `text` type is mapped to Blob and not String. First, this is unexpected _per se_, since it is not `BLOB` type, and with size of 65,535 bytes[1] it should fit into java's String. Second, for PostgreSQL `text` fields are mapped to String and work as expected, so this discrepancy is surprising.

And sorry for resurrecting this thread :)

[1] https://www.w3schools.com/mysql/mysql_datatypes.asp

**Comment by DavideD** [comment] 2022-09-27 12:40
I don't think this is a Hibernate Reactive nor Quarkus issue.

I'm not sure if this is a bug, but the issue is in the [Vert.x SQL client](https://github.com/eclipse-vertx/vertx-sql-client/).
Hibernate Reactive just returns the value from the SQL client.

If I have to guess (and assuming this is not a bug), I would say that returning a potentially long string as a `Blob` has some performance benefits than returning it as a `String`. But I haven't look too much into it.

The Vert.x team should be able to give you a better answer or fix it.

**Comment by fedinskiy** [comment] 2022-09-27 13:33
Well, I would argue, that since Quarkus provides this as a `io.quarkus`module, than this issue is a bug of Quarkus, too. 
I can create an issue for Vert.X, but I need to know, how do we use their functionality under the hood?

I took a look into code for Postgress[1] and MySQL[2] and it looks like the `text` case is not handled properly in the latter.

[1] https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-pg-client/src/main/java/io/vertx/pgclient/impl/codec/DataType.java
[2] https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-mysql-client/src/main/java/io/vertx/mysqlclient/impl/datatype/DataType.java

**Comment by DavideD** [comment] 2022-09-27 14:00
My point is that you would have this issue even if you create an app that only uses Vert.x without Quarkus or Hibernate Reactive.

In your original example, there is not much happening between the result returned by the Vert.x client and the result returned by `createNativeQuery`. 

I'm starting to think that this is a bug, but you have  a better chance to see it solved if you open an issue on the Vert.x client. Or at least, they should be able to justify those choices.

If they fix it, I don't think there is additional work to do on the Quarkus or Hibernate Reactive side, aside updating the dependency.

**Comment by DavideD** [comment] 2022-09-27 14:07
> I took a look into code for Postgress[1] and MySQL[2] and it looks like the text case is not handled properly in the latter.

Why don't you send a PR with your proposed fixed (maybe as preview if you are not sure about it)? It's the fastest way to see this issue solved.

**Comment by DavideD** [comment] 2022-09-27 14:16
I will create the issue on the Vert.x side

**Comment by DavideD** [comment] 2022-09-27 14:18
Done: https://github.com/eclipse-vertx/vertx-sql-client/issues/1239
