### ISSUE TITLE
JaxbFileRootBuildItem config

### ISSUE THREAD

**Issue by dufoli** [quarkusio/quarkus#19861] opened 2021-09-02 08:47 UTC
### Description

add possibility to add JaxbFileRootBuildItem from config.

### Implementation ideas

add a config
quarkus.jaxb.jaxb-index-path=/path1,/path2
config generate JaxbFileRootBuildItem in jaxbProcessor.
modify the test jaxb test to add an application.properties with the config to point to jaxb.index.

**Comment by dufoli** [comment] 2021-09-02 08:48
it is a good first issue I guess.

**Comment by netodevel** [comment] 2021-09-10 17:44
@dufoli,

Oops, I have a question.
This snippet of code 
```
class JaxbProcessor

for (JaxbFileRootBuildItem i : fileRoots) {
      try (Stream<Path> stream = iterateResources(applicationArchivesBuildItem, i.getFileRoot())) {
          stream.filter(p -> p.getFileName().toString().equals("jaxb.index"))
                  .forEach(p1 -> handleJaxbFile(p1, resource, reflectiveClass));
      }
  }
```
I understand that it to scan directories into resources and register the resource to a native image and read all lines from jaxb.index and register for reflection.
The question is it looks like the extension already read the automatic jaxb.index, right?
if I declare a property `quarkus.jaxb.jaxb-index-path=path1,path2`, will this property overwrite the auto scanner?

**Comment by netodevel** [comment] 2021-09-13 21:27
@gsmet @dufoli,
any feedback on the above question?

**Comment by dufoli** [comment] 2021-09-14 07:39
@netodevel processor read the jaxb.index but only on ressource within the path.
the property will generate a new JaxbFileRootBuildItem  so it will be added to path to process.

**Comment by netodevel** [comment] 2021-09-15 23:16
Hi @dufoli, 

I opened the pull request for this issue. https://github.com/quarkusio/quarkus/pull/20188
but I need help to finish.

1. Am I following the correct path for the specified problem?

2. I'm trying to run the `integration-tests/jaxb` project but this error always happens:
Exception in thread "main" java.lang.RuntimeException: java.util.ServiceConfigurationError: io.quarkus.dev.spi.HotReplacementSetup: Provider io.quarkus.vertx.core.runtime.VertxHotReplacementSetup not found
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:151)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: java.util.ServiceConfigurationError: io.quarkus.dev.spi.HotReplacementSetup: Provider io.quarkus.vertx.core.runtime.VertxHotReplacementSetup not found
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.nextProviderClass(ServiceLoader.java:1211)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1220)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.setupRuntimeCompilation(IsolatedDevModeMain.java:253)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:403)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:58)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:89)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        ... 1 more

**Comment by gsmet** [comment] 2022-01-12 16:46
We were unable to determine the usage of this and there's no explanation in the issue so closing. If you end up having a usage for this, please open a new issue explaining how it would be useful to you.

See https://github.com/quarkusio/quarkus/issues/19861 for a possible implementation.

**Closed by gsmet** 2022-01-12 16:46 UTC
Labels: kind/enhancement, good first issue, area/jaxb
