### ISSUE TITLE
Continuous testing fails to pick up if there is initially no test

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#18888] opened 2021-07-21 10:34 UTC
### Describe the bug

Start writing Quarkus code, but have no test yet.
Run `mvn quarkus:dev`. The continuous test options line is shown

Now add a test and type 'r'un in the console, the test is not picked up.
One has to stop Quarkus and re-run `mvn quarkus:dev`. 
From there on, tests (at least in the exiting test class) are picked up correctly

### Quarkus version or git rev

2.1.0.CR1

**Comment by stuartwdouglas** [comment] 2021-07-22 00:47
I think this is a duplicate of https://github.com/quarkusio/quarkus/issues/18795

Basically if src/test was not present when the process was started it was not monitored.

**Closed by stuartwdouglas** 2021-07-22 00:47 UTC
Labels: area/continuous-testing, kind/bug
