### ISSUE TITLE
Two beans with @Scheduled causes jaeger metrics error

### ISSUE THREAD

**Issue by mejlholm** [quarkusio/quarkus#2267] opened 2019-04-29 09:18 UTC
There seems to be an issue with the combination of two (or more) beans using @Scheduled with @Traced at the same time. 

Quarkus 0.14
Mvn 3.6.1
Java 11
GraalVM not relevant

Trigger using code sample in this repository:
https://github.com/mejlholm/quarkus-scheduled-error

Though it seems to be an issue with @Traced and @Scheduled in two @ApplicationScoped beans at the same time. 

Triggers this error on startup with: mvn clean compile quarkus:dev

2019-04-29 11:07:17,088 ERROR [org.qua.cor.ErrorLogger] (DefaultQuartzScheduler_Worker-1) Job (io.quarkus.scheduler.Scheduler.1_org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:76)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:32)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:28)
        at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:221)
        at io.jaegertracing.Configuration.getTracer(Configuration.java:245)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.lambda$tracer$0(QuarkusJaegerTracer.java:45)
        at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:41)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.buildSpan(QuarkusJaegerTracer.java:51)
        at io.opentracing.util.GlobalTracer.buildSpan(GlobalTracer.java:133)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:44)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at io.quarkus.arc.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:38)
        at io.quarkus.arc.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at org.acme.quickstart.Scheduler1_Subclass.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ClientProxy.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invoke(Unknown Source)
        at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: java.lang.IllegalArgumentException: A metric with name jaeger_tracer_reporter_queue_length already exists
        at io.smallrye.metrics.MetricsRegistryImphttps://github.com/quarkusio/quarkus/issues/new

l.register(MetricsRegistryImpl.java:113)
        at io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.createGauge(QuarkusJaegerMetricsFactory.java:64)
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:66)
        ... 25 more

**Comment by mkouba** [comment] 2019-04-29 09:51
Hi @pavolloffay, could you pls take look at this one?

**Comment by pavolloffay** [comment] 2019-05-02 13:48
I was able to reproduce with `0.14.0` but not with `999-SNAPSHOT`. It might have been fixed in https://github.com/quarkusio/quarkus/pull/2156

```
777d19e98d20799c6b72c29b26289f3f771250 threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.]
	at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.
	at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:76)
	at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:32)
	at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:28)
	at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:221)
	at io.jaegertracing.Configuration.getTracer(Configuration.java:245)
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.lambda$tracer$0(QuarkusJaegerTracer.java:45)
	at java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:179)
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:41)
	at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.buildSpan(QuarkusJaegerTracer.java:51)
	at io.opentracing.util.GlobalTracer.buildSpan(GlobalTracer.java:133)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:44)
	at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
	at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
	at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
	at io.quarkus.arc.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:38)
	at io.quarkus.arc.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
	at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
	at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
	at org.acme.opentracing.CounterBean_Subclass.increment(Unknown Source)
	at org.acme.opentracing.CounterBean_ClientProxy.increment(Unknown Source)
	at org.acme.opentracing.CounterBean_ScheduledInvoker_increment_1c777d19e98d20799c6b72c29b26289f3f771250.invoke(Unknown Source)
	at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	... 1 more
Caused by: java.lang.IllegalArgumentException: A metric with name jaeger_tracer_reporter_queue_length already exists
	at io.smallrye.metrics.MetricsRegistryImpl.register(MetricsRegistryImpl.java:113)
	at io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.createGauge(QuarkusJaegerMetricsFactory.java:64)
	at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:66)
	... 25 more

```

**Comment by gsmet** [comment] 2019-05-02 13:58
@mejlholm any chance you could test with a freshly built Quarkus?

Just clone master and run `mvn clean install -DskipTests -DskipITs` then use 999-SNAPSHOT as the version.

Thanks!

**Comment by mejlholm** [comment] 2019-05-03 19:01
I've tried with a locally build version of quarkus from master and it started the first time. After that it has been failing on me at least 5-6 times in a row. Is this some kind of race condition issue?

**Comment by mkouba** [comment] 2019-05-06 07:11
@pavolloffay ^ ?

**Comment by pavolloffay** [comment] 2019-05-06 07:26
@mejlholm would you be able to share your reproducer/app?

**Comment by mejlholm** [comment] 2019-05-06 12:13
@pavolloffay it is still the reproducer in github that is causing the issue. Here is a full log from the reproducer:

λ mvn clean compile quarkus:dev
Java HotSpot(TM) 64-Bit Server VM warning: Ignoring option PermSize; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ getting-started ---
[INFO] Deleting C:\dev\sandbox\quarkus-scheduled-error\target
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ getting-started ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to C:\dev\sandbox\quarkus-scheduled-error\target\classes
[INFO]
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:dev (default-cli) @ getting-started ---
Listening for transport dt_socket at address: 5005
2019-05-06 14:12:45,626 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-05-06 14:12:46,545 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 919ms
2019-05-06 14:12:47,018 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.515s. Listening on: http://[::]:8080
2019-05-06 14:12:47,023 INFO  [io.quarkus] (main) Installed features: [cdi, jaeger, resteasy, scheduler, smallrye-metrics, smallrye-opentracing]
2019-05-06 14:12:47,044 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_traces, type: counter]
2019-05-06 14:12:47,044 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_traces, type: counter]
2019-05-06 14:12:47,047 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_started_spans, type: counter]
2019-05-06 14:12:47,049 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_started_spans, type: counter]
2019-05-06 14:12:47,051 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_finished_spans, type: counter] 2019-05-06 14:12:47,053 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_finished_spans, type: counter] 2019-05-06 14:12:47,054 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_span_context_decoding_errors, type: counter]
2019-05-06 14:12:47,057 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_span_context_decoding_errors, type: counter]
2019-05-06 14:12:47,059 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_reporter_spans, type: counter] 2019-05-06 14:12:47,062 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_reporter_spans, type: counter] 2019-05-06 14:12:47,064 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_sampler_queries, type: counter]

2019-05-06 14:12:47,067 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_sampler_updates, type: counter]

2019-05-06 14:12:47,067 ERROR [org.qua.cor.JobRunShell] (DefaultQuartzScheduler_Worker-1) Job io.quarkus.scheduler.Scheduler.1_org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de threw an unhandled Exception: : java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:76)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:32)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:28)
        at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:221)
        at io.jaegertracing.Configuration.getTracer(Configuration.java:245)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.lambda$tracer$0(QuarkusJaegerTracer.java:45)
        at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:41)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.buildSpan(QuarkusJaegerTracer.java:51)
        at io.opentracing.util.GlobalTracer.buildSpan(GlobalTracer.java:133)
        at io.quarkus.smallrye.opentracing.runtime.TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.buildSpan(Unknown Source)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:44)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at io.quarkus.arc.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:38)
        at io.quarkus.arc.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at org.acme.quickstart.Scheduler1_Subclass.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ClientProxy.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invoke(Unknown Source)
        at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.IllegalArgumentException: A metric with name jaeger_tracer_reporter_queue_length already exists
        at io.smallrye.metrics.MetricsRegistryImpl.register(MetricsRegistryImpl.java:113)
        at io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.createGauge(QuarkusJaegerMetricsFactory.java:64)
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:66)
        ... 26 more

2019-05-06 14:12:47,071 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_updates, type: counter]

2019-05-06 14:12:47,074 ERROR [org.qua.cor.ErrorLogger] (DefaultQuartzScheduler_Worker-1) Job (io.quarkus.scheduler.Scheduler.1_org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de threw an exception.: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.]
        at org.quartz.core.JobRunShell.run(JobRunShell.java:213)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: java.lang.RuntimeException: No reflection exceptions should be thrown unless there is a fundamental error in your code set up.
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:76)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:32)
        at io.jaegertracing.internal.metrics.Metrics.<init>(Metrics.java:28)
        at io.jaegertracing.Configuration.getTracerBuilder(Configuration.java:221)
        at io.jaegertracing.Configuration.getTracer(Configuration.java:245)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.lambda$tracer$0(QuarkusJaegerTracer.java:45)
        at java.base/java.util.concurrent.atomic.AtomicReference.updateAndGet(AtomicReference.java:209)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.tracer(QuarkusJaegerTracer.java:41)
        at io.quarkus.jaeger.runtime.QuarkusJaegerTracer.buildSpan(QuarkusJaegerTracer.java:51)
        at io.opentracing.util.GlobalTracer.buildSpan(GlobalTracer.java:133)
        at io.quarkus.smallrye.opentracing.runtime.TracerProducer_ProducerMethod_tracer_96dadb3d6afa0cccadfe742c3e06ad433737c844_ClientProxy.buildSpan(Unknown Source)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor.wrap(OpenTracingInterceptor.java:44)
        at io.opentracing.contrib.interceptors.OpenTracingInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at io.quarkus.arc.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:38)
        at io.quarkus.arc.ActivateRequestContextInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:270)
        at io.quarkus.arc.InvocationContextImpl.invokeNext(InvocationContextImpl.java:149)
        at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:173)
        at org.acme.quickstart.Scheduler1_Subclass.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ClientProxy.run(Unknown Source)
        at org.acme.quickstart.Scheduler1_ScheduledInvoker_run_72e66771a77415a7284d3ae42331659c186071de.invoke(Unknown Source)
        at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        ... 1 more
Caused by: java.lang.IllegalArgumentException: A metric with name jaeger_tracer_reporter_queue_length already exists
        at io.smallrye.metrics.MetricsRegistryImpl.register(MetricsRegistryImpl.java:113)
        at io.quarkus.jaeger.runtime.QuarkusJaegerMetricsFactory.createGauge(QuarkusJaegerMetricsFactory.java:64)
        at io.jaegertracing.internal.metrics.Metrics.createMetrics(Metrics.java:66)
        ... 26 more

2019-05-06 14:12:47,076 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_truncations, type: counter]
2019-05-06 14:12:47,089 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_restrictions_updates, type: counter]
2019-05-06 14:12:47,139 INFO  [io.jae.Configuration] (DefaultQuartzScheduler_Worker-2) Initialized tracer=JaegerTracer(version=Java-0.34.0, serviceName=getting-started, reporter=RemoteReporter(sender=UdpSender(), closeEnqueueTimeout=1000), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=SNBWS0027, jaeger.version=Java-0.34.0, ip=10.0.75.1}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)

**Comment by pavolloffay** [comment] 2019-05-06 13:48
@mejlholm I have cloned your repository and changed quarkus version to `999-SNAPSHOT`, and run `./mvnw compile quarkus:dev` but I wasn't able to reproduce your issue

```
diff --git a/pom.xml b/pom.xml
index 49e79dc..b962875 100644
--- a/pom.xml
+++ b/pom.xml
@@ -8,7 +8,7 @@
   <version>1.0-SNAPSHOT</version>
   <properties>
     <surefire-plugin.version>2.22.0</surefire-plugin.version>
-    <quarkus.version>0.14.0</quarkus.version>
+    <quarkus.version>999-SNAPSHOT</quarkus.version>
     <maven.compiler.source>11</maven.compiler.source>
     <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
     <maven.compiler.target>11</maven.compiler.target>
```

```
JAVA_HOME=/usr/lib/jvm/java-11-openjdk-11.0.2.7-6.fc28.x86_64 ./mvnw compile quarkus:dev                                                                                          3:48 
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ getting-started ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ getting-started ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:999-SNAPSHOT:dev (default-cli) @ getting-started ---
Listening for transport dt_socket at address: 5005
2019-05-06 15:48:15,177 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-05-06 15:48:15,938 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 761ms
2019-05-06 15:48:16,175 INFO  [io.quarkus] (main) Quarkus 999-SNAPSHOT started in 1.097s. Listening on: http://[::]:8080
2019-05-06 15:48:16,177 INFO  [io.quarkus] (main) Installed features: [cdi, jaeger, resteasy, scheduler, smallrye-metrics, smallrye-opentracing]
2019-05-06 15:48:16,189 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_traces, type: counter]
2019-05-06 15:48:16,189 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_traces, type: counter]
2019-05-06 15:48:16,191 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_started_spans, type: counter]
2019-05-06 15:48:16,191 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_started_spans, type: counter]
2019-05-06 15:48:16,192 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_finished_spans, type: counter]
2019-05-06 15:48:16,192 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_finished_spans, type: counter]
2019-05-06 15:48:16,193 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_span_context_decoding_errors, type: counter]
2019-05-06 15:48:16,193 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_span_context_decoding_errors, type: counter]
2019-05-06 15:48:16,194 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_reporter_spans, type: counter]
2019-05-06 15:48:16,195 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_reporter_spans, type: counter]
2019-05-06 15:48:16,196 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_sampler_queries, type: counter]
2019-05-06 15:48:16,196 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_sampler_queries, type: counter]
2019-05-06 15:48:16,196 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_sampler_updates, type: counter]
2019-05-06 15:48:16,196 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_sampler_updates, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_baggage_updates, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_updates, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_baggage_truncations, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_truncations, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-1) Register metric [name: jaeger_tracer_baggage_restrictions_updates, type: counter]
2019-05-06 15:48:16,197 INFO  [io.sma.met.MetricsRegistryImpl] (DefaultQuartzScheduler_Worker-2) Register metric [name: jaeger_tracer_baggage_restrictions_updates, type: counter]
2019-05-06 15:48:16,250 INFO  [io.jae.Configuration] (DefaultQuartzScheduler_Worker-1) Initialized tracer=JaegerTracer(version=Java-0.34.0, serviceName=getting-started, reporter=RemoteReporter(sender=UdpSender(), closeEnqueueTimeout=1000), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=dhcp-144-223.gva.redhat.com, jaeger.version=Java-0.34.0, ip=10.33.144.223}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)
2019-05-06 15:48:16,250 INFO  [io.jae.Configuration] (DefaultQuartzScheduler_Worker-2) Initialized tracer=JaegerTracer(version=Java-0.34.0, serviceName=getting-started, reporter=RemoteReporter(sender=UdpSender(), closeEnqueueTimeout=1000), sampler=ConstSampler(decision=true, tags={sampler.type=const, sampler.param=true}), tags={hostname=dhcp-144-223.gva.redhat.com, jaeger.version=Java-0.34.0, ip=10.33.144.223}, zipkinSharedRpcSpan=false, expandExceptionLogs=false, useTraceId128Bit=false)

```

**Comment by mejlholm** [comment] 2019-05-07 15:59
I dont really know how to progress this any further. I tried pulling from master and building again with the same result. 

Only conclusion I can come to is that this must be mvn/os specific. 

The app I found the issue in has evolved to a single schedule class, which solves the issue and some other things as well, so perhaps we should close the issue for now?

**Comment by pavolloffay** [comment] 2019-05-07 16:06
You could provide us your env info and commit SHA of quarkus master you have built.

**Comment by mejlholm** [comment] 2019-05-08 17:50
Tried this on the same machine, but on a linux OS instead. Same issue, but interestingly it worked the first time I started mvn clean compile quarkus:dev. If I close down and start again, it starts throwing the error. Both on 0.14.0 and 999-SNAPSHOT.

mejlholm@usb:~/sandbox/quarkus-scheduled-error$ mvn -version
Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)
Maven home: /home/mejlholm/apache-maven-3.6.1
Java version: 11.0.3, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-13-generic", arch: "amd64", family: "unix"

Cloned quarkus and built it on linux for the first time with git commit:
a540c385a1b2de4c14af0324b4b69a2e4d8886cc

What happens if you run it multiple times?

**Comment by gsmet** [comment] 2019-05-14 14:23
@pavolloffay any chance you could take another look? Apparently, it's triggered if you run it multiple times.

**Comment by pavolloffay** [comment] 2019-05-14 14:40
I have run it multiple times and I could not reproduce, I can give it another try this week.

**Comment by pavolloffay** [comment] 2019-05-15 11:08
I was able to reproduce it. There is a race condition in https://github.com/quarkusio/quarkus/blob/991e5a31b1d4e87739c807df89accaa66f17b994/extensions/jaeger/runtime/src/main/java/io/quarkus/jaeger/runtime/QuarkusJaegerTracer.java#L41

```java
    Tracer tracer() {
        return REF.updateAndGet((orig) -> {
            if (orig != null) {
                return orig;
            }
            return Configuration.fromEnv().withMetricsFactory(new QuarkusJaegerMetricsFactory()).getTracer();
        });
    }
```
The func supplied to `updateAndGet` can be executed multiple times and the function should be "side-effect-free" which is not in this case because it creates the same metrics which is illegal hence `Caused by: java.lang.IllegalArgumentException: A metric with name jaeger_tracer_reporter_queue_length already exists` https://stackoverflow.com/a/33267333/4158442

> Atomically updates the current value with the results of applying the given function, returning the updated value. The function should be side-effect-free, since it may be re-applied when attempted updates fail due to contention among threads.

**Closed** 2019-05-15 13:57 UTC
Labels: bug, component:scheduler, component:smallrye

**Comment by mejlholm** [comment] 2019-05-15 19:53
Just for the sake of good order - I've also check this with current master as of this writing. Issue is fixed. 
Nice work!

**Comment by pavolloffay** [comment] 2019-05-16 08:47
:+1: Thanks for reporting @mejlholm!
