### ISSUE TITLE
JsonbDeserializer deserializes JSON array into class java.lang.String with Quarkus 3.x.x

### ISSUE THREAD

**Issue by dziobiak-203872** [quarkusio/quarkus#34989] opened 2023-07-25 07:37 UTC
### Describe the bug

Hello,

After migrating project from Quarkus 2.16.4.Final to 3.2.0.Final there is strange behaviour while using JsonbDeserializer.

In my model class I have declared field of type String:
```
public class ExampleRequest {

  private String test;
}
```

During the POST request I am passing array of string values:
Postman request body:
```
{
  “test”: [
         “data1”,
         "data2”,
         "data3”,
         “data4”
   ]
}
```

Before upgrade such request failed with the following exception:
`javax.json.bind.JsonbException: Unable to deserialize property 'issuerPanReference' because of: Can't deserialize JSON array into: class java.lang.String
`

Now during the deserialisation last value from that array is taken (data4) - no exception is thrown.

I’ve checked other Quarkus 3.x.x versions but this behaviour is seen from the beginning 3.0.0.Aplha3 

I guess we shouldn't deserialize json arrays into string by taking last value and ignoring the rest of the values.

### Output of `java -version`

Java version: 17.0.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by gsmet** [comment] 2023-07-25 07:52
My guess is that it's not a Quarkus issue but a change of behavior in the new version of the JSON-B implementation we are using (https://github.com/eclipse-ee4j/yasson).

If I were you, I would try to reproduce it with a simple Yasson test and report it there.

I will close this issue for now, but please reopen if it turns out it is not a Yasson issue.

**Closed by gsmet** 2023-07-25 07:52 UTC
Labels: kind/bug, triage/needs-triage
