### ISSUE TITLE
gradle quarkusUpdate (3.6.1) is broken running in a git repository

### ISSUE THREAD

**Issue by quotidian-ennui** [quarkusio/quarkus#37715] opened 2023-12-13 13:17 UTC
### Describe the bug

`./gradlew quarkusUpdate` in a project that contains git history breaks gradle.properties by replacing gradle.properties with a file that contains a a single entry `quarkusPluginVersion`

### Expected behavior

gradle.properties should contain the required properties `quarkusPluginId` etc.

### Actual behavior

gradle.properties is overwritten such that it only contains
```
bsh ❯ cat gradle.properties
quarkusPluginVersion=3.6.3
```

### How to Reproduce?

1. Create an app. `quarkus create app org.acme:micrometer --extension='resteasy-reactive,micrometer-registry-prometheus' --no-code --gradle`
2. Modify gradle.properties to downgrade the versions to a previous version `3.6.3->3.6.1`
3. ./gradlew quarkusUpdate
4. gradle.properties has been updated _correctly_
5. Repeat step 2; i.e. downgrade the version numbers again
6. git init
7. `git add * && git commit -m"Initial Checkin"`
8. ./gradlew quarkusUpdate
9. gradle.properties only contains `quarksPluginVersion`

### Output of `uname -a` or `ver`

Linux phooey 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 OpenJDK Runtime Environment GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19) OpenJDK 64-Bit Server VM GraalVM CE 21.0.1+12.1 (build 21.0.1+12-jvmci-23.1-b19, mixed mode, sharing)

### Quarkus version or git rev

Quarkus CLI 3.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.5

### Additional information

The key thing here is the logging extract that you can see then you see 

- __NOT WORKING EXTRACT__ (my gut says here it's tried to modify gradle.properties twice).

```
All sources parsed, running active recipes: io.quarkus.openrewrite.Quarkus
Generated new file gradle.properties by:
    io.quarkus.openrewrite.Quarkus
        org.openrewrite.gradle.AddProperty: {key=quarkusPlatformVersion, value=3.6.3, overwrite=true}
Generated new file gradle.properties by:
    io.quarkus.openrewrite.Quarkus
        org.openrewrite.gradle.AddProperty: {key=quarkusPluginVersion, value=3.6.3, overwrite=true}
Please review and commit the results.
```

- __WORKING__
```
All sources parsed, running active recipes: io.quarkus.openrewrite.Quarkus
Changes have been made to gradle.properties by:
    io.quarkus.openrewrite.Quarkus
        org.openrewrite.gradle.AddProperty: {key=quarkusPlatformVersion, value=3.6.3, overwrite=true}
        org.openrewrite.gradle.AddProperty: {key=quarkusPluginVersion, value=3.6.3, overwrite=true}
Please review and commit the results.
```

**Comment by gastaldi** [comment] 2023-12-13 13:28
I tried to reproduce using your steps but it works for me. 
Can you share a reproducer (maybe in a GitHub repository) so I can run `./gradlew quarkusUpdate` locally?

**Comment by quotidian-ennui** [comment] 2023-12-13 13:42
https://github.com/quotidian-ennui/quarkus-update-repro

Running on WSL2 a fresh checkout is 'broken'. If I do this afterwards

```
$ git restore gradle.properties
$ rm -rf .git
$ ./gradlew quarkusUpdate 
### it works
```

Same behaviour with 21.0.1-graalce & 21.0.1-zulu installed via sdkman

**Comment by gastaldi** [comment] 2023-12-13 13:45
@quotidian-ennui Nope, even with your reproducer I still can't reproduce it locally. Do you have any IDE opened by chance while running it?

**Comment by quotidian-ennui** [comment] 2023-12-13 13:53
No IDEs I'm using the fresh checkout just like you now. I agree with you that it's very very strange. I spun up a completely fresh Ubuntu machine and tried it and it's working fine. It's definitely something to do with my environment / WSL2; it is happening every single time.

```
$ curl -s "https://get.sdkman.io" | bash
$ source "/home/lchan/.sdkman/bin/sdkman-init.sh"
$ sdk install java 21.0.1-zulu
$ java -version
openjdk version "21.0.1" 2023-10-17 LTS
OpenJDK Runtime Environment Zulu21.30+15-CA (build 21.0.1+12-LTS)
OpenJDK 64-Bit Server VM Zulu21.30+15-CA (build 21.0.1+12-LTS, mixed mode, sharing)
$ git clone https://github.com/quotidian-ennui/quarkus-update-repro
$ cd quarkus-update-repro/
$ ./gradlew quarkusUpdate
...

> Task :rewriteRun
Validating active recipes
Scanning sources in project :
Using active styles []
All sources parsed, running active recipes: io.quarkus.openrewrite.Quarkus
Changes have been made to gradle.properties by:
    io.quarkus.openrewrite.Quarkus
        org.openrewrite.gradle.AddProperty: {key=quarkusPlatformVersion, value=3.6.3, overwrite=true}
        org.openrewrite.gradle.AddProperty: {key=quarkusPluginVersion, value=3.6.3, overwrite=true}
Please review and commit the results.

```

**Comment by quotidian-ennui** [comment] 2023-12-13 14:10
@gastaldi

Looks like we hate windows users as well... Since if I switch to 'powershell' + the batch files...

```
psh ❯ .\gradlew quarkusUpdate
...
> Task :quarkusUpdate
quarkusUpdate is experimental, its options and output might change in future versions
Detected project Java version: 21
Detected project Java version: 21
Instructions to update this project from '3.6.2' to '3.6.3':
Recommended Quarkus platform BOM updates:
Update: io.quarkus.platform:quarkus-bom:pom:3.6.2 -> 3.6.3
...

Resolved io.quarkus:quarkus-updates-recipes:1.0.11 with 0 recipe(s) to update from 3.6.2 to 3.6.3 (initially made for OpenRewrite GRADLE plugin version: 6.5.10)
OpenRewrite recipe generated: C:\TEMP\quarkus-project-recipe-18062489789386963700.yaml
...
Executing:
D:\storage\workdir\quarkus-update-repro\gradlew.bat --console plain --stacktrace --init-script C:\TEMP\openrewrite-init15405549798719511192gradle rewriteRun

```

Which then hangs forever... If you try to run the precise commandline again in powershell:

```
psh ❯ ./gradlew.bat --console plain --stacktrace --init-script C:\TEMP\openrewrite-init15405549798719511192gradle rewriteRun
...
FAILURE: Build failed with an exception.

* Where:
Initialization script 'C:\TEMP\openrewrite-init15405549798719511192gradle' line: 27

* What went wrong:
Could not compile initialization script 'C:\TEMP\openrewrite-init15405549798719511192gradle'.
> startup failed:
  initialization script 'C:\TEMP\openrewrite-init15405549798719511192gradle': 27: Unexpected character: '"' @ line 27, column 50.
     project.getRootProject().file("C:\TEMP\q
                                   ^

  1 error
```

**Comment by quotidian-ennui** [comment] 2023-12-13 15:14
@gastaldi I did a bit more digging and I found the problem; it's not quarkus necessarily, but possibly worth documenting 

> I tend to mark gradle.properties as a global gitignore and then _explicitly `git add -f` it in to projects that want it_; this is for safety reasons. This is the root cause of the issue.

## Reproducer

You can still use https://github.com/quotidian-ennui/quarkus-update-repro

```
# There is no .gitignore file 
$ echo gradle.properties >> .gitignore
$ ./gradlew --console plain --stacktrace --init-script openrewrite.gradle rewriteDryRun
### the patch is broken
$ cat ./build/reports/rewrite/rewrite.patch
$ git restore .gitignore (or rm .gitignore)
$ ./gradlew --console plain --stacktrace --init-script openrewrite.gradle rewriteDryRun
### the patch is correct
$ cat ./build/reports/rewrite/rewrite.patch
```

If `gradle.properties` is in your gitignore then the patch file looks something like this.

```
psh ❯ cat .\build\reports\rewrite\rewrite.patch
diff --git a/gradle.properties b/gradle.properties
new file mode 100644
index 0000000..8043af8
--- /dev/null
+++ b/gradle.properties
@@ -0,0 +1 @@ org.openrewrite.config.CompositeRecipe
+quarkusPlatformVersion=3.6.3
\ No newline at end of file

diff --git a/gradle.properties b/gradle.properties
new file mode 100644
index 0000000..93e0142
--- /dev/null
+++ b/gradle.properties
@@ -0,0 +1 @@ org.openrewrite.config.CompositeRecipe
+quarkusPluginVersion=3.6.3
\ No newline at end of file
```

- The comment above (vis-a-vis `C:\TEMP`) may deserve its own bug report if you can confirm it locally.
- This particular issue related to .git can be explained by this comment, and could be closed.

**Comment by gastaldi** [comment] 2023-12-13 16:45
I created https://github.com/quarkusio/quarkus/issues/37721 about the issue you found, I'm going to close this one for now

**Closed by gastaldi** 2023-12-13 16:45 UTC
Labels: kind/bug, area/gradle
