### ISSUE TITLE
can't inject @RequestScoped bean in ResteasyReactiveClientResponseFilter - javax.enterprise.context.ContextNotActiveException

### ISSUE THREAD

**Issue by npoirey** [quarkusio/quarkus#27354] opened 2022-08-18 09:09 UTC
### Describe the bug

On Quarkus resteasy reactive with a reactive rest client to make an external HTTP call.

It seems that the requestContext is not active when using a ResteasyReactiveClientResponseFilter 

I made a simple project to reproduce this issue :  
https://github.com/npoirey/quarkus_bugreport_reactiveclientfilter

Injecting a RequestScopedBeam works on a ResteasyReactiveClientRequestFilter but fails on a ResteasyReactiveClientResponseFilter 

A similar bug was reported and fixed for the non reactive quarkus http client : https://github.com/quarkusio/quarkus/issues/8538
but this doesn't work on the reactive version

### Expected behavior

my 2 filters should work and print in console 
```
MyRequestFilter
1
MyResponseFilter
1
```

### Actual behavior

injecting the bean works in the request filter but fail with stacktrace on the response filter:

```
MyRequestFilter
1
MyResponseFilter
2022-08-18 10:58:51,006 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: b683fec2-0839-4c3b-92dc-bbfb8c314c87-1: javax.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of CLASS bean [class=org.acme.MyRequestScopedBean, id=4c0d454954d7fcba5081c8479a45d86d4c28035e]
	- you can activate the request context for a specific method using the @ActivateRequestContext interceptor binding
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:53)
	at org.acme.MyRequestScopedBean_ClientProxy.arc$delegate(Unknown Source)
	at org.acme.MyRequestScopedBean_ClientProxy.getCounter(Unknown Source)
	at org.acme.MyResponseFilter.filter(MyResponseFilter.java:18)
	at org.acme.MyResponseFilter_Subclass.filter$$superforward1(Unknown Source)
	at org.acme.MyResponseFilter_Subclass$$function$$4.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.MyResponseFilter_Subclass.filter(Unknown Source)
	at org.jboss.resteasy.reactive.client.spi.ResteasyReactiveClientResponseFilter.filter(ResteasyReactiveClientResponseFilter.java:10)
	at org.acme.MyResponseFilter_Subclass.filter$$superforward1(Unknown Source)
	at org.acme.MyResponseFilter_Subclass$$function$$3.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:53)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:51)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.MyResponseFilter_Subclass.filter(Unknown Source)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:20)
	at org.jboss.resteasy.reactive.client.handlers.ClientResponseFilterRestHandler.handle(ClientResponseFilterRestHandler.java:9)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.invokeHandler(AbstractResteasyReactiveContext.java:218)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.lambda$execute$0(RestClientRequestContext.java:276)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

start the example project at https://github.com/npoirey/quarkus_bugreport_reactiveclientfilter

navigate to localhost:8080/hello

### Quarkus version or git rev

2.11.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\npoirey\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6   Java version: 11.0.15, vendor: Eclipse Adoptium, runtime: C:\sources\products\OpenJDK11U_11.0.15_10 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment] 2022-08-22 08:08
@michalszynkiewicz have you encountered this before?

**Comment by michalszynkiewicz** [comment] 2022-08-22 08:37
No, haven't seen this one

**Comment by geoand** [comment] 2022-08-22 08:45
It seems like this happening because the execution of the response filter is being done on an event loop thread instead of the executor thread where the server request (and request filter) are being executed on

**Comment by geoand** [comment] 2022-08-22 08:51
Essentially, [this](https://github.com/quarkusio/quarkus/blob/2.11.2.Final/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/handlers/ClientSendRequestHandler.java#L87-L109) seems wrong to me @cescoffier @michalszynkiewicz because it does not take into account the executor on which `ClientSendRequestHandler#handle` is being run

**Comment by geoand** [comment] 2022-08-22 09:09
> This code supposes that the handle method is called from an event loop (or at least from a thread having a Context. @geoand, you are saying that it may not be the case?

Yes, exactly. Here is the stacktrace for this example:

```posh
	at org.acme.MyRestClient$$QuarkusRestClientInterface.getById(Unknown Source:-1)
	at org.acme.MyRestClient$$CDIWrapper.getById(Unknown Source:-1)
	at org.acme.MyResource.hello(MyResource.java:23)
	at org.acme.MyResource$quarkusrestinvoker$hello_e747664148511e1e5212d3e0f4b40d45c56ab8a1.invoke(Unknown Source:-1)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:829)
```

**Comment by cescoffier** [comment] 2022-08-22 09:23
If we do not do that switch, the callback will be called on a random event loop. 
Won't we have the same problem when the response is received? Because I would have to make the switch to the context at that time.

**Comment by geoand** [comment] 2022-08-22 09:25
I am thinking that we probably need some integration with the server to be able to dispatch back to the executor used to serve the request...

**Comment by cescoffier** [comment] 2022-08-22 09:28
it's not the executor, it's the thread. If I submit a task on the same executor, I've no guarantee that it will be on the same thread (I suppose it does not use a single thread executor). 

This is what is done with "runOnContext" in the Vert.x world.

However, isn't the original code blocking, which basically means the thread in question is stuck waiting? In that case, we should be fine as soon as I have a way to "unblock" the thread.

**Comment by cescoffier** [comment] 2022-08-22 09:34
Hum... no, in the reproducer the request and response filter are different, so, yes, if we cannot switch back to the same thread or at least same request context, we will have a problem. 

If there a way to "resume" the request context even if we are not on the same thread?

**Comment by cescoffier** [comment] 2022-08-22 09:36
The code seems to resume the`requestContext`. Does this re-attach that context to the current thread?

**Comment by geoand** [comment] 2022-08-22 09:37
> it's not the executor, it's the thread. If I submit a task on the same executor, I've no guarantee that it will be on the same thread (I suppose it does not use a single thread executor).

Yeah... I thought of that too...

**Comment by geoand** [comment] 2022-08-22 09:38
> If there a way to "resume" the request context even if we are not on the same thread?

Calling `resume` on the server request context should work no matter what thread is making the call.

**Comment by cescoffier** [comment] 2022-08-22 10:01
@geoand can you remind me of the relation between the RESTEasy Reactive RequestContext (which has a link to the Vert.x context) and the CDI Request Scope?

In the reproducer, I see the first one suspended and resumed correctly.

**Comment by geoand** [comment] 2022-08-22 10:03
The CDI request scope is activated very early in the lifecycle of `RESTEasy Reactive RequestContext`. It's deactivated when the procesing is suspended and reactivated when processing resumes.
The request scope is finally terminated when the RESTEasy Reactive RequestContext concludes

**Comment by cescoffier** [comment] 2022-08-22 11:41
I'm not sure about "reactivated when processing resumes.". 
Activation is only done in `org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext#requireCDIRequestScope`, which is not called when we resume the request. `org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext#run` (which is call on `resume()` does not seem to re-active the request scope.

**Comment by geoand** [comment] 2022-08-22 11:50
I think you actually might be correct... It doesn't look like we automatically reactivate it... That's very weird, I'll have another look tomorrow.

**Comment by geoand** [comment] 2022-08-23 07:51
So indeed we don't automatically reactivate it, but that is generally not a problem because almost all handlers explicitly request it.

**Comment by geoand** [comment] 2022-10-18 15:09
This should be addressed in Quarkus 2.13 so I'll close it. If it's still an issue, feel free to comment / reopen

**Closed by geoand** 2022-10-18 15:09 UTC
Labels: kind/bug, area/rest-client, area/resteasy-reactive

**Comment by AMShareef** [comment] 2023-06-02 11:23
i have same problem in quarkus 3.1.0

**Comment by geoand** [comment] 2023-06-02 11:24
Do you have a sample application we can use to debug?

**Comment by AMShareef** [comment] 2023-06-02 11:29
I have Communication class between twins microservices 

@Path("/mypath")
@RegisterRestClient(configKey = "configKey")
@RegisterClientHeaders(InternalRequestHeaderFactory.class)
@RequestScoped
public interface JwtTokenCommunication {

    @POST
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    Response find(String myString);
}

**Comment by geoand** [comment] 2023-06-02 11:32
Please attach a full project that exhibits the problematic behavior
