### ISSUE TITLE
OpenTelemetry extension does not print trace/span ids to the console

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#26301] opened 2022-06-22 18:10 UTC
### Describe the bug

I'm following the [Quarkus OpenTelemetry guide](https://quarkus.io/guides/opentelemetry), but the console logs aren't showing the trace information. The traces do get exported to Jaeger though.

### Expected behavior

When I issue the `curl http://localhost:8080/hello` command, the guide says I should expect to see

```
10:49:02 INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (main) Installed features: [cdi, opentelemetry, opentelemetry-otlp-exporter, rest-client, resteasy, smallrye-context-propagation, vertx]
10:49:03 INFO  traceId=17ceb8429b9f25b0b879fa1503259456, parentId=3125c8bee75b7ad6, spanId=58ce77c86dd23457, sampled=true [or.ac.op.TracedResource] (executor-thread-1) hello
10:49:03 INFO  traceId=ad23acd6d9a4ed3d1de07866a52fa2df, parentId=, spanId=df13f5b45cf4d1e2, sampled=true [or.ac.op.TracedResource] (executor-thread-0) hello
```

### Actual behavior

When I issue the `curl http://localhost:8080/hello` command, I actually see

```
14:08:00 INFO  traceId=, parentId=, spanId=, sampled= [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, opentelemetry, opentelemetry-otlp-exporter, resteasy-reactive, smallrye-context-propagation, vertx]
14:08:51 INFO  traceId=, parentId=, spanId=, sampled= [or.ac.op.TracedResource] (executor-thread-0) hello
```

### How to Reproduce?

Following the [Quarkus OpenTelemetry guide](https://quarkus.io/guides/opentelemetry)

### Output of `uname -a` or `ver`

Darwin edeandrea-m1pro 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/17.0.3-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"
```

**Comment by luneo7** [comment] 2022-06-23 20:08
https://github.com/quarkusio/quarkus/issues/26258 was brought before, same thing =]

**Comment by luneo7** [comment] 2022-06-23 20:09
Fat jar, native mode works, but fast-jar doesn't...

**Comment by geoand** [comment] 2022-06-27 08:11
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/26258.

I have mentioned in https://github.com/quarkusio/quarkus/issues/26258#issuecomment-1162712626 what likely has to be done to address the problem.
I'll try and take a look tomorrow.

**Comment by geoand** [comment] 2022-06-27 08:11
> Fat jar, native mode works, but fast-jar doesn't...

As explained in https://github.com/quarkusio/quarkus/issues/26258#issuecomment-1162712626, this is because `fast-jar` does not use a flat classpath, while the uber-jar and the native mode do.

**Closed by geoand** 2022-06-27 08:11 UTC
Labels: kind/bug, area/smallrye, area/tracing
