### ISSUE TITLE
OpenAPI bug with RESTEasy `@PathParam` and `@Consumes`

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#2856] opened 2019-06-17 13:16 UTC
We made the `quarkus-smallrye-openapi` extension understand the RESTEasy `@PathParam` annotation, but if there is a `@Consumes` annotation on the same endpoint, it will require a body, when this is not the case with the JAX-RS `@PathParam` annotation. This is a bug, we should see if this is a bug in our extension or in SmallRye-OpenAPI.

**Comment by gsmet** [comment] 2019-06-17 13:50
Could you be a bit more clear about what the problem is?

What does not work and what would be expected where?

**Comment by FroMage** [comment] 2019-06-17 13:55
In swagger UI, the behaviour changes for this test:

```java
package org.acme.quickstart;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
//import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.jboss.resteasy.annotations.jaxrs.PathParam;

@Path("/hello/{path}")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
//    @Consumes(MediaType.TEXT_PLAIN)
    public String hello(@PathParam("path") String path) {
        return "hello "+path;
    }
}
```

As I said, with JAX-RS's `@PathParam`, the behaviour is the same with or without the `@Consume`, but if you use RESTEasy's `@PathParam`, Swagger UI requires a body if you add the `@Consume`

**Comment by sberyozkin** [comment] 2019-06-17 16:27
Perhaps instead Quarkus should fail the deployment if the user combines @Consumes with @GET ?

**Comment by FroMage** [comment] 2019-06-18 09:18
Well it really depends on what the JAX-RS spec says about that. I suspect the problem here is that OpenAPI thinks RESTEasy's `PathParam` annotation is a body type to deserialise.

**Comment by sberyozkin** [comment] 2019-06-18 09:48
Oh, it is the RestEasy specific annotation, I see. Not sure though why would one use it instead of the JAX-RS `PathParam`. I believe the reason the RestEasy specific one changes the OpenApi output is that the RestEasy specific one is simply not recognized and as such OpenApi thinks it is a body (without checking if it is `Get' or not) - but the same would be the case if one would just add some `A` annotation. So I'd say Quarkus failing such deployments would be fine :-) but if it is seen as too harsh then indeed OpenApi should be tweaked, thanks

**Comment by FroMage** [comment] 2019-06-18 10:03
> Not sure though why would one use it instead of the JAX-RS PathParam

Because it's better and what we recommend since it does not require the value.

>  I believe the reason the RestEasy specific one changes the OpenApi output is that the RestEasy specific one is simply not recognized

It should be, I wrote an extension for them. It's probably missing some part, though.

> Quarkus failing such deployments would be fine

Absolutely not, this is really the recommended way to write REST apps. I will check our extension points and propose a patch.

**Comment by sberyozkin** [comment] 2019-06-18 11:35
What is the recommended way, allow combining `Consumes` and `Get` ? And I'm honestly not following what is it that the RestEasy annotation brings compared to the equivalent `PathParam` (based on your example above) but I think I'm simply missing the point of it all so I'll keep quiet

**Comment by sberyozkin** [comment] 2019-06-18 11:48
I've looked at the source, right, RestEasy one, as you said, does not require a `PathParam` value, which can be handy, you are right (I guess one has to be careful about the conventions when multiple path parameters are involved, but anyway, I understand).
But as I mentioned before, I thought it was not really about the RestEasy annotation. If someone has `Consumes` and any other annotation (not even related to JAX-RS) then OpenApi will likely expect the body should be available...

**Comment by FroMage** [comment] 2019-06-18 12:21
Well, no, when there's no body parameter, the `@Consumes` annotation is ignored, which is right: it allows people to put global consumes/produces on the class and only consume a body when they want to.

With my PR to smallrye-openapi I can resolve this bug and have the same behaviour with jax-rs and RESTEasy `@PathParam` annotations. If someone has a `@Consumes` and any other annotation they will be able to use the extension point if they want to mark their annotation as not being a body, but I think only jax-rs extensions will do that honestly.

**Comment by sberyozkin** [comment] 2019-06-18 12:44
FYI, I was only referring to the case of an explicit `Consumes` on the `GET` method (which is incorrect and which is what I proposing to target but indeed it can be ignored).
Your explanation about the OpenApi enhancement makes sense, thanks :-)

**Comment by emmanuelbernard** [comment] 2019-06-21 09:57
@sberyozkin Let's not focus on the consumes and get because this code equally fails. That's the original code that failed it if I recall.

```
package org.acme.quickstart;

import javax.ws.rs.Consumes;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
//import javax.ws.rs.PathParam;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import org.jboss.resteasy.annotations.jaxrs.PathParam;

@Path("/hello/{path}")
@Produces(MediaType.TEXT_PLAIN)
@Consumes(MediaType.TEXT_PLAIN)
public class GreetingResource {

    @GET
    public String hello(@PathParam("path") String path) {
        return "hello "+path;
    }

    // future code to use    @POST
}
```

**Comment by MikeEdgar** [comment] 2019-10-05 10:53
I believe this issue can be closed now that SmallRye supports the RESTEasy types directly.

Side note - you may wish to remove the following method overrides from `io.quarkus.smallrye.openapi.deployment.RESTEasyExtension` as they are now `@Deprecated` in SmallRye OpenAPI. They were only in the interface to support RESTEasy types and are no longer necessary.

```java
public JaxRsParameterInfo getMethodParameterJaxRsInfo(MethodInfo method, int idx)
public In parameterIn(MethodParameterInfo paramInfo)
```

**Comment by kenfinnigan** [comment] 2019-11-01 18:25
Closing as it should be fixed

**Closed by kenfinnigan** 2019-11-01 18:25 UTC
Labels: bug, component:openapi
