### ISSUE TITLE
JAX RS kind of overlapping paths not reachable

### ISSUE THREAD

**Issue by yvespp** [quarkusio/quarkus#34967] opened 2023-07-24 18:14 UTC
### Describe the bug

Not sure if this is a according to the spec or a bug.

If `@Path` on a class (TestSubApi) overlaps the combination of `@Path` on class and `@Path` on a method of another class (TestApi), the method of the second class (TestApi) isn't reachable.

Paths: on class + on method
* TestApi: /test + /{name} -> not reachable (404)
* TestSubApi: /test/{name}/ + config -> works

### Expected behavior

As the path don't overlap all methods/paths should be reachable.

### How to Reproduce?

Run this service:
```
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;
import jakarta.ws.rs.core.Response;

@ApplicationScoped
@Path("/test")
public class TestApi {
    @Path("/{name}")
    @GET
    public Response getName(String name) {
        return Response.ok().entity(name).build();
    }
}

@ApplicationScoped
@Path("/test/{name}")
class TestSubApi {
    @Path("/config")
    @GET
    public Response getConfig(String name) {
        return Response.ok().entity("Config of " + name).build();
    }
}
```
`/test/{name}` can't be called and returns a 404. `/test/{name}/config` works

### Quarkus version or git rev

3.2.0.Final

### Additional information

If all the code is in one class with a common `@Path` everything works.
If both classes use `@Path("/")` and the full path on the methods it works as well.

As the code in my project that is broken is generated, it's a bit laborious to change the paths.

**Comment by geoand** [comment] 2023-07-25 06:41
This is essentially a duplicate of https://github.com/quarkusio/quarkus/issues/26496

**Closed by geoand** 2023-07-25 06:41 UTC
Labels: kind/bug, triage/needs-triage
