### ISSUE TITLE
Infinispan - can't load configuration from file in quarkus dev

### ISSUE THREAD

**Issue by Sirz3chs** [quarkusio/quarkus#29572] opened 2022-11-30 10:57 UTC
### Describe the bug

I'm creating an infinispan cache and tried to create my cache from configuration file like the [documentation](https://quarkus.io/guides/infinispan-client#creating-caches-from-the-client) said. When starting in dev mode, quarkus raise an exception.

Creating my config file in `src/main/resources` or `src/main/resources/META-INF/resources` like i've read in some issues, has the same behavior.

### Expected behavior

Being able to load configuration from `quarkus.infinispan-client.cache.books.configuration-uri` even in dev mode.

### Actual behavior

Quarkus won't start

```
2022-11-30 11:58:12,911 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.NullPointerException: Cannot invoke "java.net.URL.toURI()" because "configFile" is null
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.builderFromProperties(InfinispanClientProducer.java:239)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.initialize(InfinispanClientProducer.java:66)
        at io.quarkus.infinispan.client.runtime.InfinispanClientProducer.remoteCacheManager(InfinispanClientProducer.java:367)
        ...
```

### How to Reproduce?

I've made a project wheere the issue can be reproduced https://github.com/Sirz3chs/quarkus-infinispan-client-issue

### Output of `uname -a` or `ver`

Linux 5.4.0-132-generic https://github.com/quarkusio/quarkus/pull/148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment] 2022-12-01 08:49
I am going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/29592.

If it's not, feel free to reopen

**Closed by geoand** 2022-12-01 08:49 UTC
Labels: kind/bug, area/infinispan

**Comment by Sirz3chs** [comment] 2022-12-01 10:48
Ah my bad, i didn't see the issues already exist. Thanks

**Comment by karesti** [comment] 2022-12-02 13:46
@Sirz3chs no problem! thanks for the issue and for using the feature!
