### ISSUE TITLE
 Runtime exception and returns "500" for malformed charset in "x-www-form-urlencoded" Content-Type

### ISSUE THREAD

**Issue by pedro-hos** [quarkusio/quarkus#36870] opened 2023-11-04 14:48 UTC
### Describe the bug

We were working on [Keycloak throws runtime exception and returns 500 for malformed charset in x-www-form-urlencoded Content-Type #17513](https://github.com/keycloak/keycloak/issues/17513). However due to the fix [Update the server to use RESTEasy Reactive #10713](https://github.com/keycloak/keycloak/issues/10713)  We start to see the following exception in the quarkus internals:

```{bash}
2023-09-19 11:26:56,353 ERROR [org.keycloak.services.error.KeycloakErrorHandler] (executor-thread-1) Uncaught server error: java.nio.charset.IllegalCharsetNameException: 'utf-8'
	at java.base/java.nio.charset.Charset.checkName(Charset.java:305)
	at java.base/java.nio.charset.Charset.lookup2(Charset.java:481)
	at java.base/java.nio.charset.Charset.lookup(Charset.java:461)
	at java.base/java.nio.charset.Charset.forName(Charset.java:525)
	at org.jboss.resteasy.reactive.server.core.multipart.FormEncodedDataDefinition$FormEncodedDataParser.decodeParameterValue(FormEncodedDataDefinition.java:208)
	at org.jboss.resteasy.reactive.server.core.multipart.FormEncodedDataDefinition$FormEncodedDataParser.inputDone(FormEncodedDataDefinition.java:264)
	at org.jboss.resteasy.reactive.server.core.multipart.FormEncodedDataDefinition$FormEncodedDataParser.parseBlocking(FormEncodedDataDefinition.java:239)
	at org.jboss.resteasy.reactive.server.handlers.FormBodyHandler.handle(FormBodyHandler.java:94)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:150)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
It looks like there is no space for a check because the parameters are not decoded yet on . So perhaps we should to fix it on Quarkus side (`QuarkusHttpRequest`), since the same [fix](https://github.com/keycloak/keycloak/pull/23221) works for  undertow.

### Expected behavior

Return the 400 status code and don't throw an exception.

### Actual behavior

Currently we see the:

~~~
curl -vX POST -H "Content-Type: application/x-www-form-urlencoded;charset='utf-8'" --data-raw 'lala=ññññ' "http://localhost:8080/realms/master/protocol/openid-connect/token"
...
< HTTP/1.1 500 Internal Server Error
...
{"error":"unknown_error"}
~~~

### How to Reproduce?

Send a request with `"Content-Type: application/x-www-form-urlencoded;charset='utf-8'` as content type

**Comment by geoand** [comment] 2023-11-06 12:57
Thanks for reporting. 

To be honest, I doubt that the command mentioned to reproduce the issue aligns with the exception being shown.
The reason I am saying this is because the stacktrace indicates a multipart request while that `curl` command shows a url encoded form being used.

Nonetheless, I agree that an incorrect charset should result in an HTTP 400 instead of an HTTP 500.

**Comment by pedro-hos** [comment] 2023-11-06 14:44
Thank you @geoand I will try to reproduce it on a simple Resteasy caller instead of using keycloak. :-D

**Comment by geoand** [comment] 2024-10-22 13:39
Closing for the lack of a reproducer

**Closed by geoand** 2024-10-22 13:39 UTC
Labels: kind/bug, area/rest, triage/needs-reproducer
