### ISSUE TITLE
Configuration validation fails when setting property using environment variable

### ISSUE THREAD

**Issue by rudiger3d** [quarkusio/quarkus#26022] opened 2022-06-09 08:44 UTC
### Describe the bug

I experience a weird problem/bug when setting configuration properties using environment variables. I originally experienced the problem in an OpenShift environment using extraEnv in a values.yaml file, but I can replicate it locally using an .env file.

The problem appears to be a function of the number of properties and also the specific key of the property. See below for more details.

Having

```java
package org.acme.config;

import io.smallrye.config.ConfigMapping;
import io.smallrye.config.WithDefault;
import io.smallrye.config.WithParentName;

import java.util.Map;
import java.util.Optional;

@ConfigMapping(prefix = "clients", namingStrategy = ConfigMapping.NamingStrategy.VERBATIM)
public interface ClientsConfiguration {
    enum ClientId { ROEDTKORT, SOS_DAH  }

    @WithParentName
    Map<ClientId, ClientConfiguration> clients();

    interface ClientConfiguration {
//        @WithDefault("NA")
//        String organization();
//        OrderProperties order();
        EnabledProperties callback();
        EnabledProperties task();
        Optional<CiscoProperties> cisco();
        CreatedByProperties web();
//        CreatedByProperties app();
        MediumProperties medium();
        Features feature();
    }

    interface OrderProperties {
        @WithDefault("swan")
        String caseSystem();
        @WithDefault("false")
        boolean sendServiceOrderDamageTypeInDescription();
    }

    interface EnabledProperties {
        @WithDefault("false")
        boolean enabled();
    }

    interface CiscoProperties {
        String feed();
        String customerId();
        @WithDefault("RoadRunner")
        String taskCustomerId();
        @WithDefault("AAR01")
        String taskCallcenter();
    }

    interface CreatedByProperties {
        @WithDefault("RoadrunnerWeb")
        String createdByApplication();
    }

    interface MediumProperties {
        boolean web();
        @WithDefault("false")
        boolean app();
        @WithDefault("false")
        boolean inapp();
        @WithDefault("false")
        boolean ivr();
    }

    interface Features {
        boolean followTruck();
        boolean orderRsa();
        @WithDefault("false")
        boolean truckConsent();
        @WithDefault("false")
        boolean orderRsaMemberId();
        @WithDefault("false")
        boolean orderRsaState();
        @WithDefault("false")
        boolean orderRsaDiagnose();
        @WithDefault("false")
        boolean orderRsaReviewCase();
    }

}
```

and resources/application.properties

```
clients.SOS_DAH.callback.enabled=false
clients.SOS_DAH.task.enabled=true
clients.SOS_DAH.cisco.feed=100101
clients.SOS_DAH.cisco.customerId=36936471
clients.SOS_DAH.cisco.taskCustomerId=DAH
clients.SOS_DAH.cisco.taskCallcenter=AAR01
#clients.SOS_DAH.customerProductId=21522258
#clients.SOS_DAH.organization=DAH
#clients.SOS_DAH.order.caseSystem=swan
clients.SOS_DAH.web.createdByApplication=RoadrunnerWeb
#clients.SOS_DAH.app.createdByApplication=Roadrunner
clients.SOS_DAH.feature.followTruck=true
clients.SOS_DAH.feature.orderRsa=true
clients.SOS_DAH.feature.orderRsaMemberId=false
clients.SOS_DAH.feature.orderRsaDiagnose=true
clients.SOS_DAH.feature.orderRsaState=true
clients.SOS_DAH.feature.orderRsaReviewCase=true
clients.SOS_DAH.feature.truckConsent=false
clients.SOS_DAH.medium.web=true
clients.SOS_DAH.medium.app=true

clients.ROEDTKORT.callback.enabled=true
clients.ROEDTKORT.task.enabled=false
clients.ROEDTKORT.cisco.feed=100103
clients.ROEDTKORT.cisco.customerId=36936471
clients.ROEDTKORT.cisco.taskCustomerId=ROEDTKORT
clients.ROEDTKORT.cisco.taskCallcenter=AAR01
#clients.ROEDTKORT.customerProductId=21641375
#clients.ROEDTKORT.organization=DAH
#clients.ROEDTKORT.order.caseSystem=swan
clients.ROEDTKORT.web.createdByApplication=RoadrunnerWebRoedtkort
clients.ROEDTKORT.feature.followTruck=false
clients.ROEDTKORT.feature.orderRsa=true
clients.ROEDTKORT.feature.orderRsaMemberId=false
clients.ROEDTKORT.feature.orderRsaDiagnose=true
clients.ROEDTKORT.feature.orderRsaState=false
clients.ROEDTKORT.feature.truckConsent=false
clients.ROEDTKORT.medium.web=true
clients.ROEDTKORT.medium.inapp=true
clients.ROEDTKORT.medium.ivr=true
```

A resource
```java
package org.acme.config;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import static org.acme.config.ClientsConfiguration.ClientId.ROEDTKORT;

@Path("/greeting")
public class GreetingResource {
    @Inject
    ClientsConfiguration clientsConfiguration;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "feed " + clientsConfiguration.clients().get(ROEDTKORT).cisco().get().feed();
    }
}
```

and .env file in the root of a project

```
clients.ROEDTKORT.cisco.feed=100104
```

The app fails when starting with `./mwn quarkus:dev`
```
2022-06-09 09:25:24,567 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): io.smallrye.config.ConfigValidationException: Configuration validation failed:
        java.util.NoSuchElementException: SRCFG00014: The config property clients.roedtkort.cisco.feed is required but it could not be found in any config source
        java.util.NoSuchElementException: SRCFG00014: The config property clients.roedtkort.cisco.customerId is required but it could not be found in any config source
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:838)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:450)
        at io.quarkus.runtime.generated.Config.readConfig(Unknown Source)
        at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:103)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

If I try to substitute the contents of .env with
```
clients.SOS_DAH.cisco.feed=100104
```

The problem does not appear. 

One further discovery:

I tried setting a breakpoint in SmallRyeConfig.java line 760. The problem only appears when the total number of properties in the properties `Set` is above 151 the third and fourth time one hits the breakpoint (I hit 153 and 154 respectively). Dropping below that number and there is no problem. 

E.g. on my machine if I out-comment `MediumProperties medium();` or `Features feature();` in the `ClientConfiguration` interface and in application.properties the problem does not appear.

That also means that it depends on the number of environment variables in your shell/environment if one will experience the problem with this specific example.

### Expected behavior

Setting of configuration properties with environment variables should work when using allowed keys and not depending on the number of properties.

### Actual behavior

Setting of configuration properties with environment variables fails depending on the particular key and depending on the number of properties.

### How to Reproduce?

git clone https://github.com/quarkusio/quarkus-quickstarts/tree/main/config-quickstart
cd config-quickstart

Add the ClientsConfiguration.java to the org.acme.config package and the properties from the "Describe the error" section to application.properties. Add the .env file with the above contents the root of the project.
`./mvnw quarkus:dev`

or

git clone https://github.com/rudiger3d/quarkus-quickstarts.git and `cd config-quickstart` and run `./mwnw quarkus:dev`

### Output of `java -version`

openjdk 11.0.15 2022-04-19

### Quarkus version or git rev

2.9.2.Final

**Comment by radcortez** [comment] 2022-06-15 15:52
How are you setting the environment variable name? Are you setting it exactly as `clients.ROEDTKORT.cisco.feed`?

The problem here is that this name does not follow the expected conventions of a environment variable name (we may have to change that). For environment variable sources, SmallRye Config generates a dotted, lower case version to simplify lookups. So in pratice what you have is:

`clients.ROEDTKORT.cisco.feed` converts to `clients.roedtkort.cisco.feed`. 

When looking up `clients.roedtkort.cisco.feed` in Env sources we look for the exact match, or by converting back to `CLIENTS_ROEDTKORT_CISCO_FEED`. If you change this in your reproduced `.env` file, it works as expected.

**Comment by radcortez** [comment] 2022-06-20 17:20
> So even though this error only appears because I'm breaking some assumptions, it is quite peculiar that it only manifest itself, when the number of properties extends a certain threshold 🤔

It is not because of the numbers of properties directly, but how they are ordered and the types that are being mapped. For instance, in the case of `Optional` we don't retrieve the keys directly, because we don't know if the values exist, so we have to rely on the list of keys, iterate on that and populate the objects with the keys that we find.

In this case, when `clients.ROEDTKORT.cisco.feed` is found first in the `EnvSource` it is converted to `clients.roedtkort.cisco.feed` and now we expect to find all mandatory configs in the `clients.roedtkort.cisco.*` namespace. 

When `clients.ROEDTKORT.cisco.feed` is found first in the `properties` source it is mapped as expected and all duplicates are removed, so it doesn't get to the one generated by the `EnvSource` and you don't get an error. That also explains why you don't see the value overridden.

**Comment by radcortez** [comment] 2022-06-20 17:30
I'm unsure if we want to allow mixing different name formats in the `.env` file. I think it may become confusing because in an actual terminal these names are not acceptable.

I'm closing this issue for now. Please reopen if you disagree and let me know your ideas :)

**Closed by radcortez** 2022-06-20 17:30 UTC
Labels: kind/bug, triage/invalid, area/config

**Comment by rudiger3d** [comment] 2022-06-22 06:58
Thanks for looking into it and explanation. I don't have any ideas regarding the code right now - might look at a later point in time.
