### ISSUE TITLE
Ping-Pong quarkus 

### ISSUE THREAD

**Issue by adityakrk** [quarkusio/quarkus#41227] opened 2024-06-15 17:03 UTC
### Description

Hi ,
I have implemented ping-pong functionality for jakarta.websocket using quarkus . so i wrote some TestClient to check the functionality .
Firstly i have connected to the server using TestClient once the connection is established onOpen method initiate the heartbeat to sendPing to the client for every 30sec. But client is not receiving the PongMessage instead of that server receiving the PongMessage .

```
@OnMessage
   public void onPongMessage(Session session, PongMessage pongMessage) {
}
```
But i want client should receive the pongmessage if server sends ping .It is not happening in my case . Please find the details of the version i have used and suggest me the version which work as excepted .
Quarkus Version : 3.4.1
io.quarkus:quarkus-websockets :3.4.1

**Comment by codespearhead** [comment] 2024-06-17 13:42
@adityakrk Duplicate of #41228 .

Can you [close it](https://docs.github.com/en/enterprise-cloud@latest/issues/tracking-your-work-with-issues/closing-an-issue)?

**Closed** 2024-06-18 04:35 UTC
Labels: kind/enhancement, area/websockets
