### ISSUE TITLE
@CacheResult for RestClient methods

### ISSUE THREAD

**Issue by rinaldodev** [quarkusio/quarkus#8221] opened 2020-03-27 15:15 UTC
**Description**
Make `io.quarkus.cache.CacheResult` work on RestClient's methods.
Right now, if you annotate a Rest Client method with `@CacheResult`, it will just ignore it silently and not cache anything.

**Implementation ideas**
[Discussed here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/.40CacheResult.20.2B.20RestClient).
[Working Example Reproducer here.](https://github.com/rinaldodev/quarkus-issue-cacheresult-restclient)

Seeing RestClient's implementations as CDI beans, I would expect the `@CacheResult` annotation to work OOTB with it's methods.

**Comment by gwenneg** [comment] 2020-03-27 23:42
Thanks for reporting this @rinaldodev! I will take a look at it.

**Comment by gwenneg** [comment] 2020-03-29 23:20
The `@AroundInvoke`-annotated method of [CacheResultInterceptor](https://github.com/quarkusio/quarkus/blob/master/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java) is not invoked when the `@CacheResult`-annotated method of the `RestClient` is invoked.

@mkouba: Does it look like an ArC limitation or could there be something missing in the `quarkus-rest-client` extension?

**Comment by mkouba** [comment] 2020-03-30 08:06
@gwenneg That's very likely because the `@CacheResult` is not an interceptor binding. Note that RestClient impl does not care about the Quarkus annotation transformers. In fact, RestClient interception is a bit special use case in a way that the RestClient impl must take care of the interception itself because CDI does not support anything like interception of synthetic beans or interfaces.

Anyway, what was the reason to use `CacheResultInterceptorBinding` and friends?

**Comment by gwenneg** [comment] 2020-03-30 09:19
> Anyway, what was the reason to use `CacheResultInterceptorBinding` and friends?

The cache interceptor bindings contain things that I didn't want to expose in the extension API. For example, `CacheResultInterceptorBinding` contains a `cacheKeyParameterPositions` parameter that is valued at build time by `CacheProcessor`.

**Comment by mkouba** [comment] 2020-03-30 09:27
Fair enough. Ideally, the RestClient impl should expose some SPI that can be implemented by Quarkus to handle interception in this special case.

**Comment by gwenneg** [comment] 2020-11-29 19:58
I have a fix for this issue based on Quarkus changes only, but #13332 has to be addressed first.

**Comment by gwenneg** [comment] 2020-12-10 16:06
I'm reopening this since #13545 was only the first part of the fix.

**Closed** 2021-01-04 16:50 UTC
Labels: area/cache, area/smallrye, kind/enhancement

**Comment by knutwannheden** [comment] 2021-01-11 10:25
Very nice! I just tried adding an `@CacheResult` annotation to a method of an MP REST client interface and also a corresponing `@CacheInvalidateAll` annotated method. The latter doesn't work (see stacktrace below). If you think this would be a valid use case I can report a feature request for this.

```
java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public abstract void ch.mobi.gluon.onprem.security.internal.bps.BpsUserInfosAdapter.clearCache()

	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:74)
	at com.sun.proxy.$Proxy87.clearCache(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:62)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:91)
	at io.quarkus.cache.runtime.CacheInvalidateAllInterceptor.intercept(CacheInvalidateAllInterceptor.java:36)
	at io.quarkus.cache.runtime.CacheInvalidateAllInterceptor_Bean.intercept(CacheInvalidateAllInterceptor_Bean.zig:329)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:154)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.invokeNext(InvocationContextImpl.java:53)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:89)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:144)
	at com.sun.proxy.$Proxy91.clearCache(Unknown Source)
```

**Comment by gwenneg** [comment] 2021-01-11 14:51
Hi @knutwannheden.

We have an integration test for @CacheInvalidateAll (see [this](https://github.com/quarkusio/quarkus/blob/master/integration-tests/cache/src/test/java/io/quarkus/it/cache/RestClientTestCase.java) and [that](https://github.com/quarkusio/quarkus/blob/master/integration-tests/cache/src/main/java/io/quarkus/it/cache/SunriseRestClient.java)), is there any significant difference between your code and the test?

The exception was thrown when the interceptors implementation (which is not part of Quarkus) tried to proceed to the next interceptor in the chain. It's not an exception from the cache extension itself but I'd still be interested in investigating this further. Could you please provide a minimal reproducer?

**Comment by knutwannheden** [comment] 2021-01-11 15:09
I think the difference is that in my case the `@CacheInvalidateAll` annotated method has no JAX-RS annotations. Since the caching is performed client-side there is also no need for a corresponding server-side REST endpoint. I tried declaring this as a default method, but that didn't help.

I suppose the use case is a bit weird and as a workaround I can of course move the caching to a decorator object.

**Comment by gwenneg** [comment] 2021-01-11 17:09
Sounds like a convincing explanation. If that's the cause, then the same failure should probably happen with any kind of interceptor 
placed on a method without any JAX-RS annotation from a registered REST Client.

**Comment by knutwannheden** [comment] 2021-01-12 11:04
@gwenneg Do you think it would make sense to support the use case with methods which don't comprise the REST API in an MP REST client interface (like an `@CacheInvalidateAll` annotated method)? Otherwise I think the support for `@CacheResult` annotations in MP REST clients is rather limited: The annotation must currently be declared on another type. This asymmetry is a bit awkward.

**Comment by gwenneg** [comment] 2021-01-12 15:05
I don't like this asymmetry either :)

I confirmed yesterday that the same exception is thrown with any kind of interceptor binding when `InvocationContext#proceed` is called during the execution of the interceptor's `@AroundInvoke`-annotated method.

This probably needs to be fixed either upstream or in the quarkus-rest-client extension code.
