### ISSUE TITLE
More trace when run mvn test and binding port fail

### ISSUE THREAD

**Issue by rbelfils** [quarkusio/quarkus#4788] opened 2019-10-23 09:07 UTC
**Description**
Manque d'informations dans la stacktrace lors du lancement des tests Quarkus.
Si le port par défaut (8081) est utilisé, il n'affiche pas le port qui pose souci.

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

**Comment by gsmet** [comment] 2019-11-18 23:32
Closing as duplicate of https://github.com/quarkusio/quarkus/issues/4890 .

**Closed by gsmet** 2019-11-18 23:32 UTC
Labels: enhancement
