### ISSUE TITLE
Open API produces invalid document

### ISSUE THREAD

**Issue by bwand** [quarkusio/quarkus#14814] opened 2021-02-04 10:01 UTC
**Describe the bug**
The generated openapi document misses several schema elements eg. /components/schemas/MapStringBoolean

**Expected behavior**
Openapi document should be consistent without any errors.

**Actual behavior**
Swagger UI shows errors stating that schema references are missing:

```
Resolver error at paths./admin/api/users.get.responses.200.content.application/json.schema.items.properties.access.$ref
Could not resolve reference: Could not resolve pointer: /components/schemas/MapStringBoolean does not exist in document
```
Generated File:
[openapi_inconsistent.txt](https://github.com/quarkusio/quarkus/files/5924762/openapi_inconsistent.txt)

**To Reproduce**
I do not know exactly which stuff will be missing and why. I am using keycloak API classes and there the error occured.
Document has been ok with Quarkus Version 1.10

**Screenshots**
![image](https://user-images.githubusercontent.com/4275361/106876395-ef140300-66d7-11eb-8fdd-aaedf0784c75.png)

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.2" 2019-01-15
 - Quarkus version or git rev: 1.11.FINAL

**Comment by MikeEdgar** [comment] 2021-02-04 12:04
This looks a lot like https://github.com/quarkusio/quarkus/issues/14670. @bwand, can you share the Java classes that result in the incorrect document?

**Comment by bwand** [comment] 2021-02-04 12:33
Yes, sure. The admin.zip contains the classes and the other ZIPs are from Keylcoak. One is with classes (JAR) and the other one contains the sources.

[admin.zip](https://github.com/quarkusio/quarkus/files/5925651/admin.zip)
[keycloak-core-11.0.3.zip](https://github.com/quarkusio/quarkus/files/5925655/keycloak-core-11.0.3.zip)
[keycloak-core-11.0.3-sources.zip](https://github.com/quarkusio/quarkus/files/5925671/keycloak-core-11.0.3-sources.zip)

**Comment by bwand** [comment] 2021-02-10 10:33
Hey @MikeEdgar any news on that? Do you need additional information/stuff?

**Comment by MikeEdgar** [comment] 2021-02-10 12:55
Hi @bwand - I haven't yet been able to look at this in detail, but the a fix for the other issue I mentioned earlier has been released. Can you confirm if you still have this issue with Quarkus 1.11.2 ?

**Comment by bwand** [comment] 2021-02-10 13:06
Hi @MikeEdgar, yes the errors still occur with latest release 1.11.2-FINAL
![image](https://user-images.githubusercontent.com/4275361/107513876-29cedd00-6ba9-11eb-9f12-d1c9fc828464.png)

**Comment by MikeEdgar** [comment] 2021-02-10 13:08
Darn... Ok, I'll look into this later today or tomorrow, most likely. Thanks for checking.

**Comment by phillip-kruger** [comment] 2021-02-10 13:21
#14670 is not included in 1.11.2.Final, but will be in 1.12.0.Final. So if you can, you can try against master.

**Comment by MikeEdgar** [comment] 2021-02-10 13:29
Thanks for clarifying @phillip-kruger ! I assumed it made it in the release, but it was just close timing.

**Comment by phillip-kruger** [comment] 2021-02-10 13:34
1.12.0.CR1 should be out soon, then we can check there.

**Comment by phillip-kruger** [comment] 2021-02-11 08:56
@bwand 1.12.0.CR1 is out, can you perhaps check against that ?

**Comment by bwand** [comment] 2021-02-11 14:45
@phillip-kruger Checked it against 1.12.0.CR1 but no success. Getting the same errors as before:
![image](https://user-images.githubusercontent.com/4275361/107651795-35410780-6c80-11eb-97f6-5b3e487fd5b2.png)

**Comment by phillip-kruger** [comment] 2021-02-11 14:48
mmm , ok thanks. @MikeEdgar that means that fix did not fix this scenario ....

**Comment by Legion2** [comment] 2021-02-13 17:30
I have the same problem, and it seems that all schemas for generic types with more than one generic type parameter are missing. All my Map<T1, T2> types have no schema generated for them. I'm using kotlin and `1.12.0.CR1` did not fix it.

**Comment by JPM84** [comment] 2021-02-16 11:36
Same issue here. After upgrading from 1.10.5.Final to 1.11.3.Final. Downgrading for now...

**Comment by phillip-kruger** [comment] 2021-02-16 12:21
@gsmet  - @MikeEdgar have a fix for this, should we try and get it into 1.12.0.Final ?

**Closed** 2021-02-16 17:40 UTC
Labels: area/openapi, kind/bug, triage/upstream

**Comment by felipewind** [comment] 2021-04-14 17:34
I had a similar problem, but I believe is not a bug.

I have one rest endpoint which uses one class as the openapi schema:

```java
import javax.ws.rs.Path;
import org.eclipse.microprofile.openapi.annotations.media.Schema;
import org.eclipse.microprofile.openapi.annotations.responses.APIResponse;

@Path("/orders")
@RequestScoped
public class OrdersRest {
        @APIResponse(responseCode = "200", description = "Create a new order", content = {
                        @Content(mediaType = "application/json", schema = @Schema(implementation = OrderDto.class)) })
        public Response create(OrderDto request) throws SessionNotFound {
```

The OrderDto class has one attribute that refers to another class, that exists on my project:
```java
public class SessionDto {
    private SessionSettingsProperties[] sessionSettingsProperties;
```

When I access the swagger-ui, I am receiving the error:
```
Errors
 
Resolver error at paths./session.get.responses.200.content.application/json.schema.properties.sessionSettingsProperties.items.$ref

Could not resolve reference: Could not resolve pointer: /components/schemas/SessionSettingsProperties does not exist in document
```

![image](https://user-images.githubusercontent.com/47837222/114753755-364cee80-9d2e-11eb-999d-bdf9b8efc339.png)

I'm using the Quarkus 1.13.1.Final version.

I was able to fix my problem including one `org.eclipse.microprofile.openapi.annotations.media.Schema` annotation in my field of the SessionDto class like this:
```
import org.eclipse.microprofile.openapi.annotations.media.Schema;

public class SessionDto {

    @Schema(implementation = SessionSettingsProperties.class)
    private SessionSettingsProperties[] sessionSettingsProperties;
```

**Comment by MikeEdgar** [comment] 2021-04-14 18:21
Seems like another scenario not handled properly... @felipewind - would you mind opening an issue in [smallrye-open-api](https://github.com/smallrye/smallrye-open-api)?
