### ISSUE TITLE
Context propagation and dev mode - RejectedExecutionException thrown during app shutdown

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#2699] opened 2019-06-03 12:36 UTC
Steps to reproduce:

1.  clone https://github.com/mkouba/pulls
2.  run `mvn compile quarkus:dev`
3. CTRL + C

This issue is a follow-up of #2696.

**Comment by mkouba** [comment] 2019-06-03 12:41
```
at org.jboss.threads.RejectingExecutor.execute(RejectingExecutor.java:38)
	at org.jboss.threads.EnhancedQueueExecutor.rejectShutdown(EnhancedQueueExecutor.java:2055)
	at org.jboss.threads.EnhancedQueueExecutor.execute(EnhancedQueueExecutor.java:765)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at io.quarkus.runtime.CleanableExecutor.submit(CleanableExecutor.java:122)
	at io.quarkus.runtime.CleanableExecutor.clean(CleanableExecutor.java:67)
	at io.quarkus.runtime.ExecutorTemplate$1.run(ExecutorTemplate.java:63)
	at io.quarkus.runtime.StartupContext.close(StartupContext.java:59)
	at io.quarkus.runner.ApplicationImpl1.doStop(Unknown Source)
	at io.quarkus.runtime.Application.stop(Application.java:167)
	at io.quarkus.runner.RuntimeRunner$1.close(RuntimeRunner.java:138)
	at io.quarkus.runner.RuntimeRunner.close(RuntimeRunner.java:84)
	at io.quarkus.dev.DevModeMain$1.run(DevModeMain.java:113)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by FroMage** [comment] 2019-06-05 14:09
Duplicate of #2728. Closing this one just because the other one has more comments, even though this one was first.

**Closed by FroMage** 2019-06-05 14:09 UTC
Labels: bug, component:dev-mode, component:smallrye
