### ISSUE TITLE
quarkus:update suggests latest released version even if I'm using 999-SNAPSHOT

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24496] opened 2022-03-23 10:15 UTC
### Describe the bug

quarkus:update suggests latest released version even if I'm using 999-SNAPSHOT

```
[INFO] Recommended Quarkus platform BOM updates:
[INFO] Add:    io.quarkus.platform:quarkus-bom:pom:2.7.5.Final
[INFO] Add:    io.quarkus.platform:quarkus-amazon-services-bom:pom:2.7.5.Final
[INFO] Remove: io.quarkus:quarkus-bom:pom:999-SNAPSHOT
```

From the end user perspective it feels correct to propose latest released version. But for 999-SNAPSHOT it feels a bit odd.

Maybe the update proposals can be printed but there should be notification about the fact that the project in using Quarkus main dependencies and for production the latest released version should be used

### Expected behavior

Print message that Quarkus main dependencies are used and provide info the suggested released versions to use are A.B.C.Final.

### Actual behavior

quarkus:update suggests latest released version even if I'm using 999-SNAPSHOT

### How to Reproduce?

 - clone https://github.com/quarkus-qe/beefy-scenarios
 - run `mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:update -f 002-quarkus-all-extensions/`

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.5.Final

**Comment by aloubyansky** [comment] 2022-03-23 11:44
For the current state of things, what's reported is the expected and intended behavior. It's all driven by the registry(ies). Registries are meant to push current recommendations. It pretty much will stay this way. What we could enhance is the notion of the current (platform) stream (the project is based on) and currently recommended stream. And then suggest recommendations for a particular stream provided by the registry(ies).

**Comment by gastaldi** [comment] 2024-08-27 21:02
Closing as this is the expected behavior

**Closed by gastaldi** 2024-08-27 21:02 UTC
Labels: kind/bug, area/devtools
