### ISSUE TITLE
All JARS: Empty MANIFEST.MF starting with 3.1.0.Final

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#33874] opened 2023-06-07 12:21 UTC
### Describe the bug

Before 3.1.0.Final this code was working to get the Quarkus Version.

```java
"Quarkus: " + 
StringUtils.defaultIfEmpty(
            io.quarkus.bootstrap.runner.QuarkusEntryPoint.class.getPackage().getImplementationVersion(), "???");
```

Now however `getImplementationVersion` is returning NULL because it looks like Quarkus JARS have an almost empty MANIFEST.MF.

**3.0.3.Final MANIFEST.MF**

```
Manifest-Version: 1.0
Created-By: Maven Archiver 3.4.0
Build-Jdk-Spec: 11
Specification-Title: ArC - Runtime
Specification-Version: 3.0
Specification-Vendor: JBoss by Red Hat
Implementation-Title: ArC - Runtime
Implementation-Version: 3.0.3.Final
Implementation-Vendor: JBoss by Red Hat
Implementation-URL: https://github.com/quarkusio/quarkus
Java-Vendor: Eclipse Adoptium
Java-Version: 11.0.17
Os-Arch: amd64
Os-Name: Linux
Os-Version: 5.15.12-200.fc35.x86_64
Scm-Connection: scm:git:git@github.com:quarkusio/quarkus.git
Scm-Revision: 37b8b79e07ef615b5ba8b25505c8054834cc05a4
Scm-Url: https://github.com/quarkusio/quarkus
```

**3.1.0.Final MANIFEST.MF**

```
Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 11
```

### How to Reproduce?

Just look inside any JAR from Quarkus

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by geoand** [comment] 2023-06-07 13:07
@gsmet didn't you fix something similar?

**Comment by geoand** [comment] 2023-06-07 13:08
Found it: https://github.com/quarkusio/quarkus/pull/33614

**Comment by geoand** [comment] 2023-06-07 13:08
So this is a duplicate of https://github.com/quarkusio/quarkus/issues/33613

**Comment by geoand** [comment] 2023-06-07 13:09
🙏🏼

**Closed by geoand** 2023-06-07 13:08 UTC
Labels: kind/bug
