### ISSUE TITLE
ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) invalid version format: HTML content

### ISSUE THREAD

**Issue by akil-rails** [quarkusio/quarkus#34498] opened 2023-07-03 18:05 UTC
### Discussed in https://github.com/quarkusio/quarkus/discussions/33509

<div type='discussions-op-text'>

<sup>Originally posted by **akil-rails** May 21, 2023</sup>
Hi

How can I figure out the source/reason for the error `ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) invalid version format: <!DOCTYPE`. I see this in the log, but the requests work fine. The application is a quarkus 3.0.3 final app using quarkus-resteasy-reactive-jackson and quarkus-rest-client-reactive-jackson. 

The full trace is as follows
```
2023-05-21 23:26:36,031 WARN  [io.qua.ope.run.exp.otl.LateBoundBatchSpanProcessor] (Quarkus Main Thread) No BatchSpanProcessor delegate specified, no action taken.
2023-05-21 23:26:36,057 INFO  [io.quarkus] (Quarkus Main Thread) statement-service 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.0.3.Final) started in 0.656s. Listening on: http://localhost:8080
2023-05-21 23:26:36,057 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-05-21 23:26:36,058 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cache, cdi, hibernate-validator, opentelemetry, redis-client, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, smallrye-health, smallrye-openapi, swagger-ui, vertx]
2023-05-21 23:26:36,060 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Live reload total time: 1.182s 
2023-05-21 23:26:37,883 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Request: POST https://eiscuat2.camsonline.com/REST/WhiteOak/statement/instantMailback Headers[Authorization=xx clientId=xx Content-Type=application/json User-Agent=Resteasy Reactive Client x-do-encrypt=true content-length=331], Body:
{"data":"SKuUp8NB8c5hapGPbtPwfWbtn64CyN/+isXQfJCz3IQNCzezqTa4uWkjf+VpRAUnxzvq8He/F/zvwfeD5xN/fzMICC8MOFZxnLW7wc3grLcoO3GdTOCjbhAkDTV/HodBizfV+sM4N05IgbyIyGxq6PqY1jMcHeu/xOtPkGGIjChyB8l5dN+H4RMaWnHHAWVHHpruclByvwWgGBjRKXwECEiVg3BldDG6/2XdwJ5RfYhF1tXXCcjUS+CpqVqmkouOHB8H54jPONfEMbMPS8XreWmFoM2wr9Sfx26Ptg0aAr1PZUOWqYx3DE/bCPCPqxne"}

2023-05-21 23:27:01,599 DEBUG [org.jbo.res.rea.cli.log.DefaultClientLogger] (vert.x-eventloop-thread-0) Response: POST https://eiscuat2.camsonline.com/REST/WhiteOak/statement/instantMailback, Status[200 OK], Headers[Cache-Control=no-cache Pragma=no-cache Content-Length=274 Content-Type=application/json; charset=utf-8 Expires=-1 Server=XXXXXXXXXXXXXXXX X-AspNet-Version=XXXXXXXXXXXX!! x-frame-options=DENY X-Powered-By=XXXXXXXXXXXX!! Date=Sun, 21 May 2023 17:57:01 GMT Set-Cookie=cookiesession1=678B287CC9B5B4C0D0F3A6BEB5A70FCA;Expires=Mon, 20 May 2024 17:57:01 GMT;Path=/;HttpOnly], Body:
{
  "data": "xl0pbs/8+eMl+Dfx/LDgJmmVTs+oeokIBwMjVZ75UA2FFeL3TVNrvuRyD6bdaPaKe14+etbcuu+T5cWCi8g09jOxQani6pqFSbMmGpBo8gHfyfu09K21AXqAH/GLm/YdVBj1zwuRaem1XqT1CP/ZXhiXwII/FN5yQDhNTXyjqa+iKFOj98+hDWUIT2ScKS6+BdJ9xPYfhanhN6l9OyJIWJx5GLTKIFBP0XAWlpiC+yCtAIcJZwUd5MzbVR7RW5Zm"
}

2023-05-21 23:27:01,602 INFO  [com.api.mf.inf.sec.MessageCipherFilter] (vert.x-eventloop-thread-0) Body (decrypted) {"Information":{"returnCode":"0","returnMsg":"Record inserted successfully","Instant_MailBack":{"status":"Notifications selected by you will be sent to your registered e-mail address"}}}
2023-05-21 23:27:01,614 ERROR [io.ver.cor.net.imp.ConnectionBase] (vert.x-eventloop-thread-0) invalid version format: <!DOCTYPE
```

One of the API requests fails more frequently with the following error:
```
 [Error Occurred After Shutdown]: java.lang.IllegalArgumentException: invalid version format: <!DOCTYPE
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:123)
	at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:85)
	at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:155)
	at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:277)
	at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1382)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1245)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1294)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)

```

I see a similar issue discussed at [StackOverflow](https://stackoverflow.com/questions/41634675/netty-3-10-0-final-says-invalid-version-format-doctype) , but the fix suggested doesn't work in Quarkus - as trying to set the SSLContext fails with the following stack
```
Caused by: java.lang.UnsupportedOperationException: Specifying SSLContext is not supported at the moment
	at org.jboss.resteasy.reactive.client.impl.ClientBuilderImpl.sslContext(ClientBuilderImpl.java:91)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.sslContext(RestClientBuilderImpl.java:91)
	at io.quarkus.rest.client.reactive.runtime.RestClientBuilderImpl.sslContext(RestClientBuilderImpl.java:46)
```

Could someone help with this? Where do I need to look ?

**Comment by geoand** [comment] 2023-07-04 06:17
Please attach a sample project that exhibits the problematic behavior

**Comment by akil-rails** [comment] 2023-07-04 12:23
I can share the code - but to reproduce; I'll also need to share the VPN credentials (since the issue comes only with the private server that we connect to via a VPN).

Current status (with the same code - and changing application.properties - quarkus.rest-client.rta-cams.url) is as follows:
1. http://localhost:8090/ - always works
2. aws (https) - https://ilc6zne5l3.execute-api.ap-south-1.amazonaws.com/mock - always works 
3. private end-point https://eiscuat2.camsonline.com/ - always gives an error

**Comment by geoand** [comment] 2023-07-04 13:46
We really need a sample application that we can run freely - it doesn't need to be the actual application where you see the problem, just something that behaves in the same way.

**Comment by geoand** [comment] 2023-07-04 13:47
@franz1981 or @cescoffier however might be able to make a guess by looking at the stacktrace

**Comment by akil-rails** [comment] 2023-07-04 18:08
Update: When I put a NGINX [reverse proxy](https://kirillplatonov.com/posts/simple-reverse-proxy-on-mac-with-nginx/)  between the quarkus app and eisuat2.camsonline.com, the problem goes away - so it is confirmed that the error comes only when the quarkus app (rather netty) connects to eiscuat2.camsonline.com directly.

Unfortunately, the server is a third party, and will remain behing static IP addresses, i can still share the code & my VPN creds on a one-on-one basis if that helps .

I had seen a discussion regarding such an error on [StackOverflow](https://stackoverflow.com/questions/41634675/netty-3-10-0-final-says-invalid-version-format-doctype) which was solved by setting the TLS version in the SSLContext, but that's not possible today right?

**Comment by akil-rails** [comment] 2023-07-05 05:55
Update : I used [burp](https://portswigger.net/burp/releases/professional-community-2023-6-2) to intercept the response from the eiscuat2.camsonline.com -- it's apparent that the server is misbehaving and is send a HTTP response more than the content-length that is specified in the headers. This is making vertex read the subsequent bytes and subsequently failing. 
Given that nodejs, nginx are able to ignore the bytes after the content-length, isn't this something that should also be handled in vertx/netty ?

See the trace below - content-length is 4478 (which is the json), but there is data <!DOCTYPE HTML>...</HTML> even post that , which vertx / netty is not discarding, and is instead trying to read - isn't this a bug ?

Is this a good enough hint to figure out the fix at the client side?

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Length: 4478
Content-Type: application/json; charset=utf-8
Expires: -1
Server:XXXXXXXXXXXXXXXX
X-AspNet-Version:XXXXXXXXXXXX!!
x-frame-options: DENY
X-Powered-By:XXXXXXXXXXXX!!
Date: Wed, 05 Jul 2023 05:38:13 GMT
Connection: close
Set-Cookie: cookiesession1=678B287C22359FCB61A8801E1F2CC863;Expires=Thu, 04 Jul 2024 05:38:13 GMT;Path=/;HttpOnly

{
  "data": "xl0pbs/8+eMl+Dfx/LDgJmmVTs+oeokIBwMjVZ75UA2FFeL3TVNrvuRyD6bdaPaKsgtDNAQdze8TR4fv3Rvv2+svqrdywFnKF1mjO66s9lMKvqh/Akcu+Dmm9/Ow8Hed206ZITqzCCb/Ii+zkMyaH3jUWFTZ6kPFWe7Au5ec6FJDLTHYmv/LSEiKwlPoG3J7+0w1FdHYWzpGtjun3DUp4SBn+GxvcF9WmAiCFQc6BbCapR/OG6VKrVj1qTGYWi6NxiQyuQ9bSIweOhtqT91pGmj0eMtdx7Zl++Qba+XwVMpsfvSTktRpv+pmEYHOGgTY3VFnoYUPnCRY3MkfHkWj7t/yUuzaNFb9FfxTo3aRRIGMI3y71d00vVdSheegvadjfkO1Ri2LFyClJcnvnXndPezjRUWEA17m0H+UN0v0NOn/6aTvTmekdqbl0MXSSMuVplG/1aSzz3sqCjAydTubD1YJ7uxLGACTb4s1pNvXlDuvstNwbKJQ/Yje/ucbMwcCepAqE2ahXhlOI79fTe9C+CfMcaS70f18cp1huUnezyoAKu2xQcLxl3+PNHtTo+eegA+ZjO/4+/KnsMn1cCB6g6362Vc+SQkq2cZcTxtxq+V86oWokpbDxbrQosECn7srZrLk7pFNxn4uroTjiVxDh+LAMomi4nH3qMKg53YqIXms03lHl1Oh5Ynocs7pM/T2Hly7ApBV0naa7wW6FI/9cPn5tC//QBQoUx2542eF3D4KASibggKPX/swBKSHkMEATSH50fJSfOsR37C0sRNT02jL5zhpZs5xqywc6RAXXvrRQepX2yhTGPR3GEkZKqUoy7ldvtlor1dyGS3w7pBdNcY+owKO0JzDRAQBLDlyCmd5bYM3HZeBwn7XC63qm2ukZsunqnCH2FOqpvEuRklzpFy+oK2HSxVDg8mDvdQGZ3GHR9ifQr/5hXMNMbJYHqM23FZCzYiErdh+NBh+anZ/cNSk+3DpoWXz3ezxz19d+bRxZZpOLNlt1U8FrDlw5CcHQB2dMIGUwJMXVCG5AYebwnL3LOTEdNiXFT6rt+2NtV6RUmy3fI5Lo1PDWjK7rG1GHdUP1BNlkGabbUBzsgwpCvCyDpX/rJsOjONJa6c2iC9Gw/sLGB1x6WbvSadXr1pIz9QLUPYg+jhRiJ8AC62bwbXDYM4TL9c3qQPoMNm9B7VqrE6vG1AuzM8wpfgBj932FKaEtw0meoSR1yGYujcleYKEUU/hghtVwUsXS+wQ3UucZJ0F7Mgyv/l35+1N5Pu5gX4+wpSBoudhc3AOlCWyIRBvatCeMfDVbpoIGqIsO46QB4BkH+P00JZCMeFvnAG/eoeqzjlqMcfnZJE5jqlLa42dV/3U7Dw2oNRzipFFrttvHIrRpiJnwgdXWAdL2KFzuM8A22llI/UZCSRXI5TMaq4DKBm7cZCKVKhrR0akBrwIlT5CsrY3CHmrnBzkmh5JOtxdyVbTwR1Iyu3EcXuE8yKdI+RV271sZBHohaFEqzUx7BJM4/E7teyayyXtRM6gSWD8xXho3TjR6w/WYIkCVRgQPjnpn4Ej+iWslDAucVyrufZr5dMXIg4GoxWvzhEru5SK2wQnr0EUoY3hbCTUyKW11+WzkDHGRh/ANTGJ769fpObu5HilN1N12u172nR69Zr8Ad0+PobBFXiTzr+sI1fWSYNgapogFMnfSKCRb48ei39Bc4xSoCQxNLVJLl/iNwGUbEQLiHBZ67JUpprndGV0XRTAx/p+PRFCk7zWaugP8v28vsfZqk0EAAKraxkedsZdydYsltPGkB0xGGmY7OPgQgC+MI0bN44/xVC3Wk5M6TgJF8ebXfuIAf+mOEQOON6mYpurR7LWygb61tiCVxfwSmVfUYIEMm01adTM6lyvF1/NuyiEi23QN6TKnetn+bWAgBDAJp5suY8TrS7ugOmqlkAyW+9wVwOmMIt3KSww4LxUElgleRpQ4ZkimZhYbO8FCQuBs7eUcgyB/GgS0yLpozEZEj1EihAKWYkpQ7f21yTGRIQSjA7K/Z13BS8whWaUm1lYKdpDB5BK+WsJzz7dcEewjsOosYUR2rjKV1OiBstE+4RFxvprvmp+Fs7xA8IbGIofhD/VWVBZd6iQnsBsv1LCq7FyGk4uUYC/t7ih/CN3naHthoZHdvX6Wff+jFAPj6k9MkyYlo7ByJLdAwM7oB45k/pbdW12A7q77ceyinEQgoxDlwvC/P5FM/2ej1UK5zP++92ry8LdQo7u0XX30SZMs++gEFMEE93QNpw1dcsKWbkULHi7yKrWGtVJazVwBFAkxZGXv56wni3e0yQ8NPVmf+Z8ZJDHtVcS8rh+RNg8kyvIIDDytKUkK7EDJSHb/Sw3C2uPipDYQ89hb+I8u+JaqU5lljpNw/Fcs4H27vcB/irTpvxyyQScrh3Ew+d1XdrSHORsg+JA37gBYP8Alrza3Q0GjWHUcmVM596wjUezcntJf5fx3rnecervv2xbZrqUwAaO4Qm2Lk4JQ8VAfIz3EIcXC7sm9tJVHfjou7iz7n9sBYbbQT/CQkOcAs7l6UHcCFzuTV7Yhu7IRk/2PsvlFscx00JJvitII89iwa6buS3twRTrS4BRhjaEX0NMlSkgEZ56GoIN7pBctJIwGs5V8mlNmDNeLAk3cV4aGEWy7FfwunfHAZpVL8xSc7r8e9nXXyIjyrbXjpSss/LNInDYdmTPNVGI1JlPDPTMrJgGwqEc8yDWteo8I+ToTEq2WWgh7XYhOe/bxwZOHN6/+ZG2eW22oQYlcCqisNNyR4BWvoBDRA6Q16OYHbXz/7FxIAKbz61rWMHhMgcpPR7O+1e2qGZEMWEd/LdfFDOcMfvdg8hHEA54ANnlz0er9bsTh7Qo8qJvQAOsKGyrL1+gUjlg2setc7b0h5dkoS6V/pIRWm+oYa4f7sbOxwmvWtKS8buXEJmLor996jLLa8qWh29C3nMCnbt8fhsNtaCJmH0m4oixNrfqqmxaMv/+xhDsQ5WA9NSI994OXw1vX5cH9BEJy0sylWcoVhSXmb8W+O6RFv6tXq/ZPtUHXRLcVQEItcWtsBN2WOIFL6l58/HXE8Kij2XFLXgEVo5/iEgZgQU+WKvA320uEMgOV5Zn0lqlR72VpWKGDYoYc43Vwvxq3yYC4WO48RBO0IYyty0tzWJZersdda+KCqejgaZGDXKtAEKRLRv2EXFmELhYaIXKW/kysM4W7y2O1zgTDBNKblWrhPh0+U0f4cYXoJu6jTv6J3QeuCf3ICFzmlWD/DWJBHodLJf8SRY33VuF/1R75mJif4SKxDlqVAfshEu0SP6bKQTfW6AVgXXNBYRXik+bg169aRxzyf893s4zAIG4Jj3K9lMKRHede3p/n/DNlkYz5ZT+vFTmvjMkobpLYiaMxNkx3T572FW2krN9SUa6FpiSpvDIUnkCaylfuootBXuczRHGR1Y1ggzuwiNPeBQM8xp95HQvW83ptPj3u+zNLmjqYiBoVMDwGd7P92gqONVH+pybqkT1gcS4MfylO+Nqzla5QIfbpxTv53N1j4WkFNYavBc4J62XoHJZuewm+M6/Z0mj2xvrzdw6JruA2FMPMTUrvVcj+n7Zuk2e7lDWSfPeV1RmEJFOvF74L/Fe3I0KQCv0+dm6vLbxGYcmSb4U34Z5vsjopne+z4JPjP5iLa12z1EvSgWhyPmr2TTLHrdnOTYeiZZLdabGQv8+fA/oEnmVjLf4NyUDVB5Sj5qXoIaeROWW+1+kw1kVWxyJnCINoGfNzoB9hfWyW32GVlrOC/xobmsznKf8SrL16DAKuSRp9WX4M3LA89DVUzr48hCayxG4LJLuEWh2EX6pER1EJvyyPQ/23G1l9IDNkQxeMtLcxIRtGvnocqzxA0bkJrgAg+/ZFc7TyqoMhiv7sE4loz/ljBHv72r5MN306/EpcRSPe45CBmhDRbCN7tSmrk6A+r8xVTtRWLmdlkRlx7tpvDtPcJ48Kb9syAMhyZi/0HP385iG5HEUU5P7zSWT+y4va4DWHLcbhf+JbtI0SaVatS2Cqsp2kD/O9YQz674sY3cupid8ymhKDHVRbF6GwcWtkBwNWp38YxeDlBFiyRYI2jZbgkU9yXrzwlO4k1tbsaq3P/UBx4tFdHm0HAPTYtnQzu4PlPdIgrTGTF7FKEjzyzmVqK1a+UTCKTNn2N8oDtWblaV2mVmWfPi2PX/utaV29HHCDjf6ZtVv3khsaEqXnxW8DdUcj8WvnUkCDoEKSXjb0Ts5WQGk/hySU8fwSULhi7YmAtXs9eswt4e4fRaaObWmTyvhXlbAR1kBzqFd7RilG+ePlNFySjWFD628/x3jNz3vVkyt74hTgvPtOUmp+n1BUgU8Ec7J6sVLC2xG8a0YMpDdZtuEVoga+RtfICv7KZAvXtEUxauV0I2hf+PkOFjH1oewlbc+kJyv5dk="
}<!DOCTYPE html>
<html>
    <head>
        <title>Runtime Error</title>
        <meta name="viewport" content="width=device-width" />
        <style>
         body {font-family:"Verdana";font-weight:normal;font-size: .7em;color:black;} 
         p {font-family:"Verdana";font-weight:normal;color:black;margin-top: -5px}
         b {font-family:"Verdana";font-weight:bold;color:black;margin-top: -5px}
         H1 { font-family:"Verdana";font-weight:normal;font-size:18pt;color:red }
         H2 { font-family:"Verdana";font-weight:normal;font-size:14pt;color:maroon }
         pre {font-family:"Consolas","Lucida Console",Monospace;font-size:11pt;margin:0;padding:0.5em;line-height:14pt}
         .marker {font-weight: bold; color: black;text-decoration: none;}
         .version {color: gray;}
         .error {margin-bottom: 10px;}
         .expandable { text-decoration:underline; font-weight:bold; color:navy; cursor:pointer; }
         @media screen and (max-width: 639px) {
          pre { width: 440px; overflow: auto; white-space: pre-wrap; word-wrap: break-word; }
         }
         @media screen and (max-width: 479px) {
          pre { width: 280px; }
         }
        </style>
    </head>

    <body bgcolor="white">

            <span><H1>Server Error in '/REST' Application.<hr width=100% size=1 color=silver></H1>

            <h2> <i>Runtime Error</i> </h2></span>

            <font face="Arial, Helvetica, Geneva, SunSans-Regular, sans-serif ">

            <b> Description: </b>An application error occurred on the server. The current custom error settings for this application prevent the details of the application error from being viewed remotely (for security reasons). It could, however, be viewed by browsers running on the local server machine.
            <br><br>

            <b>Details:</b> To enable the details of this specific error message to be viewable on remote machines, please create a &lt;customErrors&gt; tag within a &quot;web.config&quot; configuration file located in the root directory of the current web application. This &lt;customErrors&gt; tag should then have its &quot;mode&quot; attribute set to &quot;Off&quot;.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;Off&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            <b>Notes:</b> The current error page you are seeing can be replaced by a custom error page by modifying the &quot;defaultRedirect&quot; attribute of the application&#39;s &lt;customErrors&gt; configuration tag to point to a custom error page URL.<br><br>

            <table width=100% bgcolor="#ffffcc">
               <tr>
                  <td>
                      <code><pre>

&lt;!-- Web.Config Configuration File --&gt;

&lt;configuration&gt;
    &lt;system.web&gt;
        &lt;customErrors mode=&quot;RemoteOnly&quot; defaultRedirect=&quot;mycustompage.htm&quot;/&gt;
    &lt;/system.web&gt;
&lt;/configuration&gt;</pre>                      </code>

                  </td>
               </tr>
            </table>

            <br>

            </font>

    </body>
</html>
```

**Comment by cescoffier** [comment] 2023-07-05 06:56
This is a good question. I vaguely remember having discussed that a long time ago with the Vert.x team, and it was considered problematic in some cases (@vietj can you remember?).

**Comment by geoand** [comment] 2023-07-06 07:18
Is there perhaps some Vert.x or Netty flag that can be set to ignore such cases?

**Comment by cescoffier** [comment] 2023-07-11 05:33
We would need more detail, especially to understand if the response is provided as expected (and if this is just noise) or if it breaks the application.

Indeed, it's tricky. Netty parses the framer as they come and build the HTTP messages on the fly. So, it gets the header, gets the first body, builds the message, and sends it downstream (that's your response). Because the connection is still used and still receives data, it parses it, but it's incorrect, so fails - but we believe it's just discarded. This behavior is expected, and that's actually what allows pipelining. 

On the server side, we have an invalid frame handler. We do not have the same on the client side as the occurrence of such kind of behavior is low.

**Comment by cescoffier** [comment] 2023-07-11 05:33
@geoand we cannot stop reading - that would break pipelining.

**Comment by geoand** [comment] 2023-07-11 06:01
Gotcha, thanks

**Comment by akil-rails** [comment] 2023-07-11 06:12
The server is sending a malformed response, and we are getting that server fixed. But, I wanted to bring to your attention the following:
1. We are currently able to still work with the malformed server, when we use an NGINX proxy between quarkus and the misbehaving server - NGINX seems to be able to handle this - I am not sure if NGINX handled pipelining like what you said.
2. We are able to work with the malformed server when we call it using the node-fetch api , again not sure if nodejs-fetch supports pipelining.

To your question on whether the quarkus application is able to recover from the malformed response, at times it does, and at times it fails (with the exception that I've shared earlier).

**Comment by cescoffier** [comment] 2023-07-11 07:38
I think it should not fail as the message should just be discarded, but I see why it can fail: netty reports the exception and we close the connection.

**Comment by vietj** [comment] 2023-07-11 12:58
I think there can be an issue if back pressure is involved, perhaps the connection instead of being abruptly close should be reset which would not interfere with current current request in progress and would close the connection in a more graceful manner

**Comment by akil-rails** [comment] 2023-07-11 15:52
Failures occur more frequently when running multiple tests that make HTTP calls to the server, and when I comment out all the tests except one, the test passes (the error is still logged) - so probably it is because of back pressure.

**Comment by cescoffier** [comment] 2023-11-20 07:11
I would need a standalone reproducer to look into that problem. 
Unfortunately, without it's pretty hard to understand what's going on.

**Comment by geoand** [comment] 2023-12-12 08:03
Closing for lack of a reproducer.

If one does become available, we can reopen the issue

**Closed by geoand** 2023-12-12 08:03 UTC
Labels: area/vertx, triage/needs-reproducer
