### ISSUE TITLE
Quarkus Native with OpenTelemetry-jdbc Unable to find a driver that accepts url: jdbc:oracle:thin@

### ISSUE THREAD

**Issue by brianmolinaspring** [quarkusio/quarkus#29110] opened 2022-11-07 22:04 UTC
### Describe the bug

hello guys, I need your support, I'm getting this error when trying to run my ms with quarkus native but it tells me that it can't find a driver, it should be noted that in jvm mode it works without problems:

   at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.ja        va:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)

Caused by: java.lang.IllegalStateException: Unable to find a driver that accepts url: jdbc:oracle:thin:@(
 at io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver.findDriver(OpenTelemetryDriver.java:113)
        at io.opentelemetry.instrumentation.jdbc.OpenTelemetryDriver.connect(OpenTelemetryDriver.java:161)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)
        at java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        ... 3 more

**Comment by geoand** [comment] 2022-11-08 10:53
This looks like a duplicate of https://github.com/quarkusio/quarkus/issues/28915. Can you confirm @brunobat ?

**Comment by brunobat** [comment] 2022-11-08 11:23
@geoand @brianmolinaspring I think this is a duplicate for this one: https://github.com/quarkusio/quarkus/pull/28921
@brianmolinaspring can you please review that PR and see if your issue is solved by it?

**Comment by brianmolinaspring** [comment] 2022-11-08 12:49
@brunobat check and I'll tell you

**Comment by michalvavrik** [comment] 2022-11-16 23:07
We discussed this with @brianmolinaspring in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7028 sufficiently, and this is definitely a duplicate of #28915, hence we should close the issue.

**Closed by michalvavrik** 2022-11-16 23:07 UTC
Labels: kind/bug, area/tracing
