### ISSUE TITLE
JsonParsingException for Quarkus GraphQL Integration

### ISSUE THREAD

**Issue by eichstaedtk** [quarkusio/quarkus#16716] opened 2021-04-22 09:13 UTC
## Describe the bug
I wrote the following GraphQL Quarkus Integration using Resteasy: 

 given()
        .when().contentType("application/json")
        .body("{\"query\": \"query {findACorporateBodyWithID(id:\"123\") {preferredName}}\"}")
        .post("/rest/graphql")
        .then()
        .statusCode(200)
        .body("data.findACorporateBodyWithID.preferredName", is("Staatsbibliothek zu Berlin"))
        .log().all();

But the Server response was: 

2021-04-22 11:01:34,824 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-8) HTTP Request to /rest/graphql failed, error id: 6a5af92d-3290-4a1c-aa81-451a5e33d262-1: javax.json.stream.JsonParsingException: Invalid token=NUMBER at (line no=1, column no=50, offset=49). Expected tokens are: [COMMA]
	at org.glassfish.json.JsonParserImpl.parsingException(JsonParserImpl.java:426)
	at org.glassfish.json.JsonParserImpl.access$1100(JsonParserImpl.java:55)
	at org.glassfish.json.JsonParserImpl$ObjectContext.getNextEvent(JsonParserImpl.java:480)
	at org.glassfish.json.JsonParserImpl.next(JsonParserImpl.java:352)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:311)
	at org.glassfish.json.JsonParserImpl.getObject(JsonParserImpl.java:149)
	at org.glassfish.json.JsonReaderImpl.readObject(JsonReaderImpl.java:88)
	at io.quarkus.smallrye.graphql.runtime.SmallRyeGraphQLExecutionHandler.doRequest(SmallRyeGraphQLExecutionHandler.java:168)

## To Reproduce

Write an @QuarkusTest using RestEasy 

Can you advice me how I can test the HTTP Rest graphql Endpoint properly or is this an bug? 

Using Java 11 and Quarkus 1.13.2

**Comment by phillip-kruger** [comment] 2021-04-22 09:17
Hi @eichstaedtk Can you share a small application that reproduce this ? Thanks

**Comment by eichstaedtk** [comment] 2021-04-22 10:23
@phillip-kruger No Sorry that is an internal project. But what I found meanwhile is that if I remove the double quotes around und using the following JSON Body the server is responding with 

given()
        .when().contentType("application/json; charset=UTF-8")
        .body("{ \"query\": \"{" +
            "  **findACorporateBodyWithID(id: 123)** {" +
            "    preferredName" +
            "  }" +
            "}\"" +
            "}")
        .post("/rest/graphql")

2021-04-22 12:18:20,125 WARN  [not.gra.GraphQL] (vert.x-worker-thread-0) Query failed to validate : '{  findACorporateBodyWithID(id: 123) {    preferredName  }}'

The problem seems to be the line findACorporateBodyWithID(id: 123) but I can't solve this so that I getting an proper response. Have you any example using an query with parameter?

**Comment by phillip-kruger** [comment] 2021-04-22 10:26
You can test out the query using the graphql-ui and once you have it working use that in the test case

**Comment by eichstaedtk** [comment] 2021-04-22 10:31
@phillip-kruger The query is ok using the graphql-ui but won't be accepted during test. I found that the query without the parameter id and using an DefaultValue on Server Side the test is running through. 
 This is the resteasy command with which the test is running

given()
        .when().contentType("application/json; charset=UTF-8")
        .body("{ \"query\": \"{" +
            "  findACorporateBodyWithID {" +
            "    preferredName" +
            "  }" +
            "}\"" +
            "}")
        .post("/rest/graphql")
        .then()
        .statusCode(200)
        .body("data.findACorporateBodyWithID.preferredName", is("Staatsbibliothek zu Berlin"))
        .log().all();

But why is the test not accepting a query parameter for findACorporateBodyWithID ?

**Comment by phillip-kruger** [comment] 2021-04-22 11:00
Should the quotes in query not be escaped ?

**Comment by eichstaedtk** [comment] 2021-04-22 11:22
Yes but that makes no difference. The test failed with and without quotation. The only difference ist the error message.

**Comment by phillip-kruger** [comment] 2021-04-22 11:33
Ok, if you can create a small example app that reproduce this I can have a look. Thanks

**Comment by phillip-kruger** [comment] 2021-05-26 12:31
@eichstaedtk - did you manage to create a reproducer ?

**Comment by phillip-kruger** [comment] 2021-07-01 13:46
@jmartisk I think this is now fixed ? Or is this unrelated to the fix you done recently ?

**Comment by jmartisk** [comment] 2021-07-02 08:01
I think you're just not properly escaping the quotes.

The test needs to look like this:
```
given()
        .when().contentType("application/json")
        .body("{\"query\": \"query {findACorporateBodyWithID(id:\\\"123\\\")} {preferredName}\"}")
        .post("/graphql")
        .then()
        .statusCode(200)
        .body("data.findACorporateBodyWithID.preferredName", is("Staatsbibliothek zu Berlin"))
        .log().all();
```

Then it should work.
With this escaping, the actual request body is:
```
{"query": "query {findACorporateBodyWithID(id:\"123\")}"}
```

You need to 
- escape the quotes with `\` because you're inside Java code
- and also prepend them with `\\`, which in the end turns into `\`, because you're inside a JSON string


May I also suggest to consider switching to using a GraphQL client library, for example with the dynamic client, you could change the test to something like:

```
  @TestHTTPResource("graphql")
  URL url;

  @Test
  public void testClient() throws ExecutionException, InterruptedException {
    DynamicGraphQLClient client = DynamicGraphQLClientBuilder
        .newBuilder()
        .url(url.toString())
        .build();
    Document query = document(
        operation(
            field("findACorporateBodyWithID",
                args(arg("id", "123")),
		field("preferredName"))
        ));
    Response response = client.executeSync(query);
    Assertions.assertEquals("Staatsbibliothek zu Berlin",
        response.getData().getJsonObject("findACorporateBodyWithID").get("preferredName"));
  }
```

**Comment by jmartisk** [comment] 2021-07-02 08:54
I'll close this because I think this is not a bug. If you have more questions, feel free to ask.

**Closed by jmartisk** 2021-07-02 08:54 UTC
Labels: area/graphql, area/smallrye, kind/bug
