### ISSUE TITLE
Support AWT Image IO in native image

### ISSUE THREAD

**Issue by galderz** [quarkusio/quarkus#13567] opened 2020-11-30 16:48 UTC
An extension, new or existing, should add the following to support AWT Image IO in native image. See attached JSON files containing write and read registration registrations.

[imageio-read-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617323/imageio-read-native-image-config.zip)
[imageio-write-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617328/imageio-write-native-image-config.zip)

**Comment by galderz** [comment] 2020-11-30 16:51
Credit to @jerboaa who came up with the the [instructions](https://github.com/graalvm/mandrel/issues/180#issuecomment-734873511) to get all of this working 👏. Note that as @jerboaa mentions in that issue, jpg is not yet fully working. More details in https://github.com/oracle/graal/issues/3031.

**Comment by gsmet** [comment] 2020-11-30 17:21
Just a note that we already have some ImageIO related tweaks in https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/ImageIOProcessor.java .

**Comment by jerboaa** [comment] 2020-11-30 17:24
> An extension, new or existing, should add the following to support AWT Image IO in native image. See attached JSON files containing write and read registration registrations.
> 
> [imageio-read-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617323/imageio-read-native-image-config.zip)
> [imageio-write-native-image-config.zip](https://github.com/quarkusio/quarkus/files/5617328/imageio-write-native-image-config.zip)

Thanks @galderz 

Note that the config is highly dependent on the JDK code in use. JDK 11.0.8+11 might need slightly different config to JDK 11.0.10.

Consider perhaps to drive the app from java first (with the `native-image-agent` running). That would generate the config on-the-fly. As a second step, produce the native image with the config in `META-INF/native-image` that got produced in step 1. See this for an example: https://github.com/graalvm/mandrel/issues/180#issuecomment-734873511

**Comment by galderz** [comment] 2020-12-02 11:59
@gsmet But according to the description of the issue in https://github.com/graalvm/mandrel/issues/180, the tweaks available are not enough, otherwise you'd not get the `NoSuchMethodError`. Converting @jerboaa's example into a test would be desirable too, if no similar tests exist? 

Also, could this be a good first native issue for the community?

**Comment by gsmet** [comment] 2020-12-03 09:32
@galderz I wasn't saying no additional work was needed, just that we had preliminary work there.

BTW, this is blocking the GraalVM 20.3 upgrade, things that used to work don't work anymore:

https://github.com/quarkusio/quarkus/pull/13644#issuecomment-737779519

**Comment by zakkak** [comment] 2020-12-04 14:48
> BTW, this is blocking the GraalVM 20.3 upgrade, things that used to work don't work anymore

I tested the code examples from https://github.com/graalvm/mandrel/issues/180#issuecomment-734873511 with GraalVM 20.2 as well and they don't work there either. So I think that this specific issue is not related to the 20.3 upgrade and doesn't need to be resolved for Quarkus to move to upgrade to 20.3.

**Comment by jerboaa** [comment] 2020-12-04 15:21
> > BTW, this is blocking the GraalVM 20.3 upgrade, things that used to work don't work anymore
> 
> I tested the code examples from [graalvm/mandrel#180 (comment)](https://github.com/graalvm/mandrel/issues/180#issuecomment-734873511) with GraalVM 20.2 as well and they don't work there either. So I think that this specific issue is not related to the 20.3 upgrade and doesn't need to be resolved for Quarkus to move to upgrade to 20.3.

Thanks for testing it, @zakkak. I would have been surprised if it was any other way.

**Comment by rsvoboda** [comment] 2021-01-08 07:28
Quarkus 1.11 CR1 is released, it comes with GraalVM 20.3 support. Is this going to get fixed before .Final?

**Comment by zakkak** [comment] 2021-01-08 09:11
@rsvoboda I think it won't.

Note that this issue is about a feature and not a bug.
The AWT related issues (resulting in the imageIO test failing) discussed in https://github.com/quarkusio/quarkus/issues/13954 should be fixed before .Final though.

**Closed** 2021-12-07 10:24 UTC
Labels: kind/enhancement, triage/needs-triage
