### ISSUE TITLE
devservices doesn't run initscript / initfunction

### ISSUE THREAD

**Issue by geniusit** [quarkusio/quarkus#16738] opened 2021-04-22 18:34 UTC
Hi,

According to the quarkus documentation, the confiugration
```properties
quarkus.datasource.devservices.properties
```
accepts a ```java Map<String,String>``` for additional properties

But i suspect it doesn't work as excpected.

### Expected behavior
An init script / init function should be called after container creation.

### Actual behavior
Noting happens

## To Reproduce
Create a sample quarkus project with this dependency :

```xml
<dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-reactive-pg-client</artifactId>
    </dependency>
```

Add this class to the classpath : 

```java
public class TestContainerScript {

    public static void sampleInitFunction(Connection connection) throws SQLException {
        // e.g. run schema setup or Flyway/liquibase/etc DB migrations here...
        System.out.println("Never called ... why ?");
    }
}
```

### Configuration
```properties
quarkus.datasource.devservices.properties.TC_INITFUNCTION=io.quarkus.TestContainerScript::sampleInitFunction
```

More details [here](https://www.testcontainers.org/modules/databases/jdbc)

Thank you

Quarkus 1.13
Maven

**Comment by geniusit** [comment] 2021-05-03 11:28
@stuartwdouglas

**Comment by glefloch** [comment] 2021-05-03 11:45
@geniusit I'm having a look at this one. Actually those parameters (`TC_INITFUNCTION` and `TC_INITSCRIPT`) are handled by the testcontainer driver which is not used by `devservices` (https://github.com/testcontainers/testcontainers-java/blob/9183f8f940e12045e8790c6eb6693cf8c62bd779/modules/jdbc/src/main/java/org/testcontainers/jdbc/ContainerDatabaseDriver.java#L132)

I think we would need to handle them right after container start, WDYT @stuartwdouglas ?

**Comment by glefloch** [comment] 2021-05-03 11:46
BTW, I think this is a duplicate of #16125

**Comment by geniusit** [comment] 2021-05-03 11:48
Yes it is, sorry I haven't seen it before

**Comment by stuartwdouglas** [comment] 2021-05-03 23:50
Yea, we would need to manually implement it. Really though how many different ways do we want to setup a DB schema? At the moment we have Hibernate, Liquibase and Flyway support, although these don't really work for reactive databases. Maybe we should start a discussion about this on the dev list, as I don't know if just adding another DevServices specific one is what we are after.

**Comment by glefloch** [comment] 2021-05-04 05:08
Yes I agree with you and furthermore it's only working for database dev service that rely on test container and the JDBC container which is not always the case (H2, derby). 
I will update the documentation to specify that those test containers specific parameters are not supported for the moment.

**Closed** 2021-05-04 20:59 UTC
Labels: kind/enhancement, triage/needs-triage
