### ISSUE TITLE
2.2.0.Final Can no longer read config mapping

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#19763] opened 2021-08-30 05:21 UTC
### Describe the bug

When migrating from `2.1.4.Final` to `2.2.0.Final`, configurations for a `@ConfigMapping` interface can no longer be found on system startup.

### Expected behavior

Service starts up successfully.

### Actual behavior

```
Exception in thread "main" java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
Caused by: java.lang.ExceptionInInitializerError
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:60)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.base/java.lang.reflect.Constructor.newInstance(Unknown Source)
	at java.base/java.lang.Class.newInstance(Unknown Source)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:65)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	... 6 more
Caused by: java.lang.IllegalStateException: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.my-config.name is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.my-config.num is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.their-config.name is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.their-config.num is required but it could not be found in any config source
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:406)
	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:399)
	... 16 more
Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.my-config.name is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.my-config.num is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.their-config.name is required but it could not be found in any config source
	java.util.NoSuchElementException: SRCFG00014: The config property app.config.their-config.num is required but it could not be found in any config source
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:838)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:403)
	... 17 more
```

### How to Reproduce?

Reproducer: `service3` in https://github.com/mweber03/quarkus-test

1. `./gradlew service3:quarkusBuild`
2. `docker build -t service3 -f modules/service4/Dockerfile .`
3. `docker run -it -p 8080:8080 service3`

### Output of `uname -a` or `ver`

Ubuntu 20.04

### Output of `java -version`

OpenJDK 11.0.11

### Quarkus version or git rev

2.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by mweber03** [comment] 2021-08-30 05:21
@radcortez

**Comment by aloubyansky** [comment] 2021-08-30 08:36
Thanks for the report and the reproducer @mweber03 
@radcortez, fyi, reverting https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef#diff-97590934dcf5a67bd5024cc9d8765c75ea29b98b5272d2f04a03b3065138d65e fixes the issue.

**Comment by geoand** [comment] 2021-08-30 09:07
I am pretty sure that the same cause @aloubyansky pointed to is also responsible for https://github.com/quarkusio/quarkus/issues/19448

**Comment by aloubyansky** [comment] 2021-08-30 14:33
@mweber03
````
[aloubyansky@localhost quarkus-test]$ git diff
diff --git a/modules/service3/build.gradle b/modules/service3/build.gradle
index ad4bf8c..f4d9417 100644
--- a/modules/service3/build.gradle
+++ b/modules/service3/build.gradle
@@ -12,5 +12,5 @@ dependencies {
     implementation 'io.quarkus:quarkus-arc'
     implementation 'io.quarkus:quarkus-resteasy'
     implementation 'io.smallrye.config:smallrye-config'
-    runtimeOnly 'io.quarkus:quarkus-config-yaml'
+    implementation 'io.quarkus:quarkus-config-yaml'
 }
````
fixes your issue. What was the reason for `runtimeOnly`? `runtimeOnly` for a Quarkus extension is clearly a wrong configuration, so I am closing this issue.

**Closed by aloubyansky** 2021-08-30 14:33 UTC
Labels: kind/bug, area/config

**Comment by mweber03** [comment] 2021-08-30 15:44
@aloubyansky why is it clearly wrong? I was trying to limit the scope of what is visible to developers. What I had worked in 1.13.7, 2.0.3, and 2.1.4.

**Comment by aloubyansky** [comment] 2021-08-30 15:58
Because extensions are build time dependencies. With runtimeOnly none of the "build items" this extension is expected to produce are actually produced. Perhaps there was a change in the Gradle plugin that affected your config but the current behavior is definitely not a bug.

**Comment by aloubyansky** [comment] 2021-08-30 15:59
Actually it's probably not a change in the gradle plugin but the one I referenced previously.

**Comment by gsmet** [comment] 2021-08-30 16:32
My guess is that it was just accidentally working before. But all extensions needs to be `implementation`.
