### ISSUE TITLE
Project containing AWS Java SDK v2 and Hibernate ORM won't compile to native

### ISSUE THREAD

**Issue by bgoggin** [quarkusio/quarkus#17361] opened 2021-05-19 14:28 UTC
## Describe the bug
If you want to use AWS Secrets Manager, for example, and if you therefore create a project that uses both Hibernate ORM and leverages the AWS Java SDK v2 and try to do a native compile, the compilation fails with the exception:
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.4.Final:build (default) on project demo: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:209)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:350)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:181)
[ERROR] 	... 10 more
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.4.Final:build (default) on project demo: Failed to build quarkus application

### Expected behavior
I would expect the project to compile to a native executable. It does if you comment out the includes for the AWS SDK for Java v2 in the pom.xml.

### Actual behavior
Compilation fails with a series of exceptions beginning with:
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.4.Final:build (default) on project demo: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:209)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:350)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:181)
[ERROR] 	... 10 more
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.4.Final:build (default) on project demo: Failed to build quarkus application

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.
https://github.com/bgoggin/demo
[demo-master.zip](https://github.com/quarkusio/quarkus/files/6509484/demo-master.zip)

1. Create project dependencies for Hibernate ORM and AWS SDK for Java v2, not just a AWS extension.
2. Try to build a native executable: '❯ mvn -X -e clean install -Dnative -Dquarkus.native.container-build=true -DskipTests=true'
3. The build will fail, sample attached

### Configuration
```properties
# Add your application.properties here, if applicable.
Does not seem to be applicable.
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin BillMacBookPro.local 20.4.0 Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
### Quarkus version or git rev
1.13.4.Final
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.11, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.3", arch: "x86_64", family: "mac"
## Additional context
(Add any other context about the problem here.)

**Comment by Sanne** [comment] 2021-05-19 15:03
I managed to reproduce this on `1.13.4` as reported, but it works fine on `main`.
Also it's not clear which component is causing it, I suspect it's not the Hibernate extension

**Comment by bgoggin** [comment] 2021-05-19 15:05
I used the AWS SDK for Java v2 in another project without the error and Hibernate ORM was the biggest difference I was aware of between the 2 projects.

**Comment by Sanne** [comment] 2021-05-19 15:13
I've found this is caused by https://github.com/aws/aws-sdk-java-v2/pull/2368 - Quarkus main is unaffected as the AWS SDK has been fixed with that PR and upgraded in https://github.com/quarkusio/quarkus/pull/16277

@gsmet I've flagged #16277 to be considered for backport

**Comment by Sanne** [comment] 2021-05-19 15:14
@bgoggin a workaround is to override the awsskdk version in your project:

```
 <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>software.amazon.awssdk</groupId>
        <artifactId>sdk-core</artifactId>
        <version>2.16.36</version>
      </dependency>
     < ... and all other sdk components? .. >
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
```

**Comment by Sanne** [comment] 2021-05-19 15:16
@gsmet so this issue was already fixed in main.. I don't remember how we flag this, should I close it?

**Comment by bgoggin** [comment] 2021-05-19 20:36
@Sanne Hi, am I understanding correctly that just just rolling back to version of 2.16.36 of AWS SDK for Java v2 should work? I get the same error with 2.16.36.

**Comment by Sanne** [comment] 2021-05-19 21:03
Are you sure? It worked for me, using your reproducer.

I'll try again tomorrow - it's too late for me now :)

**Comment by bgoggin** [comment] 2021-05-19 21:11
@Sanne I see, it's a different, additional dependency. Please ignore my comment above. It compiles with this added dependency.

**Comment by bgoggin** [comment] 2021-05-20 12:56
@Sanne Yes, might as well close it, thanks.

**Closed** 2021-05-20 12:56 UTC
Labels: area/hibernate-orm, area/persistence, kind/bug
