### ISSUE TITLE
Qute: Not able to access data variables in object

### ISSUE THREAD

**Issue by ncioj10** [quarkusio/quarkus#13719] opened 2020-12-05 03:05 UTC
**Describe the bug**
I have a data class that needs to insert its own data into a template. 
It seems that it is not possible to Inject Templates or access data variables within the same class that is passed as data context. 
Only Reflection loading seems to work.

**Expected behavior**
Template gets injected by name and object values can be accessed.

**Actual behavior**
Attributes of the data object are "NOT_FOUND". 

**To Reproduce**

I've added a small reproducer to the current qute template project. 
It contains the Item class which demonstrate said behaviour once loaded.

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5646403/code-with-quarkus.zip)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Ubuntu 18.04
 - Output of `java -version`: 
```
java version "14.0.1" 2020-04-14
Java(TM) SE Runtime Environment (build 14.0.1+7)
Java HotSpot(TM) 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
```

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvnw
```
Java version: 14.0.1, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-14-oracle
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.128-microsoft-standard", arch: "amd64", family: "unix"

```

**Comment by mkouba** [comment] 2020-12-05 09:44
This is not a bug. You create a new `Engine` instance in the `org.acme.qute.Item.testString()` method and this engine has no value resolver registered. You should use the `Engine` provided by quarkus (i.e. `@Inject Engine`).

Furhtermore, injection does not work if you instantiate an object yourself, e.g. the `new Item()` in your code. Injection only works for instances managed by the container. See the [Introduction to CDI](https://quarkus.io/guides/cdi).

Could you try to describe what exactly are you trying to achieve? Maybe we can find a solution ;-).

**Comment by ncioj10** [comment] 2020-12-05 12:36
Hi,
thank you for your quick reply! 
We currently have a Spring Boot Service (we can't port it to quarkus just yet) which receives input via GRPC, the Input is then converted to Java POJO Objects and mapped to database via Hibernate (so the POJO objects are not CDI managed).
On the POJO we want to have a `createText()` method, that uses the variables of the object itself and injects them as context to a POJO-specific template. 

In the quarkus toy example I have now tried to `@Inject Engine` in QuteResource and pass it to the method call e.g. `createText(Engine engine)`, but the injected Engine is null. 
Also for us it would be helpful to have it running standalone, as we are not using the full quarkus stack and with the current "Hello World" Tutorial it does not explain how to create an Engine with the correct value resolver manually.
It would be really cool, if you had an idea on that as the qute approach seems really interesting.

**Comment by mkouba** [comment] 2020-12-07 07:50
> Hi,
> thank you for your quick reply!
> We currently have a Spring Boot Service (we can't port it to quarkus just yet) which receives input via GRPC, the Input is then converted to Java POJO Objects and mapped to database via Hibernate (so the POJO objects are not CDI managed).
> On the POJO we want to have a `createText()` method, that uses the variables of the object itself and injects them as context to a per POJO-specific template. This method then returns a completed string.
> 
> Also for us it would be helpful to have it running standalone, as we are not using the full quarkus stack and with the current "Hello World" Tutorial it does not explain how to create an Engine with the correct value resolver manually.

`Engine.builder().addDefaults().addValueResolver(new ReflectionValueResolver()).build()`. Note that the `ReflectionValueResolver` is considered a fallback and something that is not recommended for idiomatic qute apps. 

The problem with manually created `Engine` is that most of the quarkus-specific stuff will not work (e.g. template validation). 

> It would be really cool, if you had an idea on that as the qute approach seems really interesting.
> 
> In the quarkus toy example I have now tried to `@Inject Engine` in `QuteResource` and pass it to the method call e.g. `createText(Engine engine)`, which seems to work. Can I use this approach in my application like that as well?

Yes, that would work. However, keep in mind that if you parse the template manually then again some features will not be available.

**Comment by ncioj10** [comment] 2020-12-07 15:56
> Yes, that would work. However, keep in mind that if you parse the template manually then again some features will not be available.

Ok but is there a reason why these features are only available in the CDI managed versions of them? 
For our use case and I can imagine a lot of others have similar use cases we don't have CDI managed objects getting the templates. 
The template checking is really the major features why we would want to use the qute engine.

**Comment by mkouba** [comment] 2020-12-08 07:53
> > Yes, that would work. However, keep in mind that if you parse the template manually then again some features will not be available.
> 
> Ok but is there a reason why these features are only available in the CDI managed versions of them?

Yes, there is a reason. Part of the configuration is done at build time (incl. generated value resolvers) and we need a way to pass this configuration to the engine instance. Therefore, we create a preconfigured `Engine`.

> For our use case and I can imagine a lot of others have similar use cases we don't have CDI managed objects getting the templates.

 Anyway, the managed `Engine` instance can be also obtained via static methods: `CDI.current().select(Engine.class).get()` and `Arc.container().instance(Engine.class).get()`.

> The template checking is really the major features why we would want to use the qute engine.

Right. But we cannot validate templates that are parsed "on the fly" at runtime. Currently, only templates located in `src/main/resources/templates` are validated.

**Comment by ncioj10** [comment] 2020-12-08 17:19
> Yes, there is a reason. Part of the configuration is done at build time (incl. generated value resolvers) and we need a way to pass this configuration to the engine instance. Therefore, we create a preconfigured `Engine`.

Ok thank you for the help, so if I didn't overlook something most Qute features only work in combination with a Quarkus service and can not be used as a stand alone library with Spring Boot for example?
We will then see how Quarkus evolves and might port in the future. It would be really cool to have Qute as a more abstracted library useable also with other backend services, as this would make evaluations a little easier.

**Comment by mkouba** [comment] 2020-12-09 08:16
> Ok thank you for the help, so if I didn't overlook something most Qute features only work in combination with a Quarkus service and can not be used as a stand alone library with Spring Boot for example?

I wouldn't say _"most Qute features"_ but _"all features that require build time processing and further integration"_ ;-). That said, it's possible to integrate Qute in other build time oriented java stacks.

**Comment by mkouba** [comment] 2020-12-09 08:17
I'm going to close this issue. Feel free to reopen it if you think there's something that requires further discussion.

**Closed by mkouba** 2020-12-09 08:17 UTC
Labels: area/qute
