### ISSUE TITLE
Vertx-http access log rotate on file size

### ISSUE THREAD

**Issue by agreedSkiing** [quarkusio/quarkus#24670] opened 2022-03-31 13:47 UTC
### Description

Whilst doing some load testing on a clone of our production environment we noticed that our quarkus pod in our kubernetes cluster got evicted quite a lot since the access log rotates daily instead on file size. Our enviroment has a 200MiB file storage for each pod to keep log files in.

Is it possible to add an option to rotate the file on file size also?

**Comment by cescoffier** [comment] 2022-05-08 15:23
The access log is written using a regular logger. So, if you configure the logger to do file rotation, it should work.

**Comment by agreedSkiing** [comment] 2022-05-17 06:35
@cescoffier thanks for the tip we got it working in our application.properties but when we try to add as configuration we can't escape the character correctly for quarkus.log.category."io.quarkus.http.access-log".level, got any tips on how we should escape it? 
One of our developers has tried the combinations below in our yaml configuration
```
QUARKUS_LOG_CATEGORY__IO_QUARKUS_HTTP_ACCESS_LOG__LEVEL
QUARKUS_LOG_CATEGORY__IO_QUARKUS_HTTP_ACCESSLOG__LEVEL
QUARKUS_LOG_CATEGORY__IO__QUARKUS__HTTP__ACCESSLOG__LEVEL
QUARKUS_LOG_CATEGORY__IO__QUARKUS__HTTP__ACCESS-LOG__LEVEL
QUARKUS_LOG_CATEGORY__IO__QUARKUS__HTTP__ACCESS_LOG__LEVEL
QUARKUS_LOG_CATEGORY__IO__QUARKUS__HTTP__ACCESS__LOG__LEVEL
QUARKUS_LOG_CATEGORY__IO__QUARKUS__HTTP__ACCESS_-LOG__LEVEL
```

**Comment by cescoffier** [comment] 2022-06-27 14:38
Sorry, I missed your comment. @radcortez any idea?

**Comment by radcortez** [comment] 2022-06-28 12:25
@agreedSkiing are you only setting the environment variable and removing the property in `application.properties`?

The right way to set it up is with `QUARKUS_LOG_CATEGORY__IO_QUARKUS_HTTP_ACCESS_LOG__LEVEL` (your first option). The issue is when this is only set up as an environment variable, we have no way to know the dynamic part of the key name (the category name) if it should be split by dashes or dots, so we use the standard rules to convert everything to dots and the property becomes `quarkus.log.category."io.quarkus.http.access.log".level`.

If you set a `quarkus.log.category."io.quarkus.http.access-log".level` in `application.properties`, it will allows us to do a double mapping and match `QUARKUS_LOG_CATEGORY__IO_QUARKUS_HTTP_ACCESS_LOG__LEVEL` to the correct property name.

I hope this makes sense. I'll try to document this.

**Comment by radcortez** [comment] 2022-06-28 18:00
> @radcortez would it make sense to have come kind of conversion form in the Dev UI showing what the environment variable for configuration in `application.properties` would be?

We could. Just to clarify that in this case, the issue was not in the env name, but since it was not working than people start to try out different combinations.

The problem is when you have a dynamic piece of the key name, that needs to be mapped via `getPropertiesNames`, we need to convert that back to dotted format, and when that name only exists in the env, what is the real name? For instance  `QUARKUS_LOG_CATEGORY__IO_QUARKUS_HTTP_ACCESS_LOG__LEVEL` is a valid representation for:

- quarkus.log.category."io.quarkus.http.access.log".level
- quarkus.log.category."io-quarkus.http.access.log".level
- quarkus.log.category."io.quarkus-http.access.log".level
- quarkus.log.category."io.quarkus.http-access.log".level
- quarkus.log.category."io.quarkus.http.access-log".level
- ... all the other combinations of dash in `IO_QUARKUS_HTTP_ACCESS_LOG`

Only when we have the dotted key in one of the other sources we can match the correct one, because now we can do the env to dotted conversion and the dotted to env conversion and find the match.

Even adding a warning won't help, because you may be defining a perfectly valid env variable.

I have no good idea of how to solve this (other than what is currently implemented). Well, I guess we could generate all combinations of dotted and dashed keys and brute force it, but we don't know the implications in business code logic.

**Comment by radcortez** [comment] 2022-06-29 13:34
Added clarifications to https://smallrye.io/smallrye-config/latest/config/environment-variables/.

The Quarkus Configuration reference already has a link to this: https://github.com/quarkusio/quarkus/blob/81cef8d84bca559cb68a6afae1969ffbbbb7732b/docs/src/main/asciidoc/config-reference.adoc#L65

There is also a PR to add the Env format to the docs: https://github.com/quarkusio/quarkus/pull/26408

I believe we can close this.

**Closed by radcortez** 2022-06-29 13:34 UTC
Labels: kind/enhancement, area/vertx
