### ISSUE TITLE
Connecting to PostgreSQL DB is failing with native-image

### ISSUE THREAD

**Issue by majoferenc** [quarkusio/quarkus#30701] opened 2023-01-30 10:29 UTC
### **Describe the bug**

When app deployed into k8s cluster, the application is not able to connect to PostgreSQL DB due to error Driver does not support the provided URL: jdbc:postgresql://config-db-postgresql-db:5432/my_database                               

### **Expected behavior**

Driver should support correct jdbc URLs

### **Actual behavior**

Driver will return error:
```
│ 2023-01-30 09:02:48,864 WARN  [io.agr.pool] (main) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://config-db-postgresql-db:5432/my_database                                  
│ 2023-01-30 09:02:48,889 WARN  [io.agr.pool] (agroal-11) Datasource '<default>': Driver does not support the provided URL: jdbc:postgresql://config-db-postgresql-db:5432/my_database                             
│ 2023-01-30 09:02:48,890 WARN  [org.hib.eng.jdb.env.int.JdbcEnvironmentInitiator] (JPA Startup Thread) HHH000342: Could not obtain connection to query metadata: java.sql.SQLException: Driver does not support the provided URL: jdbc:postgresql://config-db-postgresql-db:5432/my_database                                                                                                                                      
│     at io.agroal.pool.ConnectionFactory.connectionSetup(ConnectionFactory.java:242)                                                                                                                              
│     at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)                                                                                                                             
│     at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:535)                                                                                                                          
│     at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:516)                                                                                                                          
│ 2023-01-30 09:02:48,925 INFO  [io.quarkus] (main) Installed features: [agroal, cache, cdi, config-yaml, hibernate-orm, hibernate-orm-panache, jaeger, jdbc-db2, jdbc-h2, jdbc-postgresql, keycloak-authorization, micrometer, narayana-jta, oidc, resteasy-reactive, resteasy-reactive-jackson, security, servlet, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-opentracing, spring-data-jpa, spring-di, spring-security, spring-web, swagger-ui, vertx]
```
The same app when running locally in dev mode can connect to postgresql database without issues.

### Steps to reproduce:

create a web app with jdbc connection
build application as native binary
deploy into container engine
try to configure jdbc connection to database system like postgresql

### Output of java -version

No response

### GraalVM version (if different from Java)

No response

### Quarkus version or git rev

2.15.3.FINAL

### Build tool (ie. output of mvnw --version or gradlew --version)

No response

### Additional information

Dependencies:

``` 
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-agroal'
```

Our configuration in YAML:

```
quarkus:
  datasource:
    db-kind: ${CONFDB_DATABASE_KIND:postgresql}
    username: ${CONFDB_DATASOURCE_USERNAME:usernam}
    password: ${CONFDB_DATASOURCE_PASSWORD:password}
    jdbc:
      url: ${CONFDB_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/my_database}
      max-size: ${CONFDB_CONNECTION_POOL_MAX_SIZE:2}
      min-size: ${CONFDB_CONNECTION_POOL_MIN_SIZE:2}
 ```

Environment variables in the container:
```
bash-4.4$ env | grep CONFDB
CONFDB_DATASOURCE_JDBC_URL=jdbc:postgresql://localhost/test
CONFDB_CONNECTION_POOL_MAX_SIZE=2
CONFDB_DATASOURCE_USERNAME=username
CONFDB_CONNECTION_POOL_MIN_SIZE=2
CONFDB_DATASOURCE_PASSWORD=password
CONFDB_DATABASE_KIND=postgresql

**Comment by gastaldi** [comment] 2023-01-30 15:35
My bet is that the default value needs to be escaped. What happens if you replace:
```
      url: ${CONFDB_DATASOURCE_JDBC_URL:jdbc:postgresql://localhost:5432/my_database}
```

with 

```
      url: ${CONFDB_DATASOURCE_JDBC_URL}
```
?

**Comment by gastaldi** [comment] 2023-01-31 14:08
Can you remove the `jdbc-db2` and the `jdbc-h2` extensions from your project? It looks like a different driver is being used to connect to it

**Comment by gastaldi** [comment] 2023-01-31 14:16
Also if you could provide a sample reproducer project that would help a lot. I couldn't reproduce the issue following the steps above

**Comment by majoferenc** [comment] 2023-01-31 16:50
@gastaldi yes of course, here is a sample project: 
[https://drive.google.com/file/d/1PlWbtgpRQGkM6ffOCo_LD7tbW_KTWUTk/view?usp=share_link](url)

**Comment by majoferenc** [comment] 2023-01-31 17:08
@gastaldi You were right, after remove jdbc-db2 and jdbc-h2 dependencies, we are getting following build issue, which is also present on the sample project:

```
> io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[1512](https://gitlab.ngncc.de/cocomat/oss-pfs/pfsipclusterquarkus/-/jobs/416257#L1512)  	[error]: Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find a JDBC driver corresponding to the database kind 'postgres' for the default datasource. Either provide a suitable JDBC driver extension, define the driver manually, or disable the JDBC datasource by adding 'quarkus.datasource.jdbc=false' to your configuration if you don't need it.
```

**Comment by majoferenc** [comment] 2023-01-31 17:26
Correct, now it works, thanks! 
Looks like the issue is present only when `multiple jdbc libraries` are present in the project.
However, I believe this is legitimate use case, for example on our testing environment we are using `PostgreSQL` database, but on customer side `DB2` is used, therefore this feature is necessary for us.

**Comment by gastaldi** [comment] 2023-01-31 17:50
There is a discussion about this in: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Support.20multiple.20RDBMS.20with.20the.20same.20build.20.2F.20image.3F

**Comment by geoand** [comment] 2023-07-21 11:00
@gastaldi is there still something that needs to be done here or can we close the issue?

**Comment by gastaldi** [comment] 2023-07-21 11:01
@geoand nope, let's close it

**Closed by gastaldi** 2023-07-21 11:01 UTC
Labels: area/persistence, area/native-image

**Comment by geoand** [comment] 2023-07-21 11:08
👍🏼
