### ISSUE TITLE
Quarkus test with @ParameterizedTest and @MethodSource using Lists.reverse does not work

### ISSUE THREAD

**Issue by jakubbrzeski** [quarkusio/quarkus#28678] opened 2022-10-19 08:41 UTC
### Describe the bug

Similar to [#28677](https://github.com/quarkusio/quarkus/issues/28677) and other issues linked there. Occurs in `@ParemeterizedTest` while providing arguments via `@MethodSource` and using `com.google.common.collect.Lists.reverse`. The error:

```
No converter available
---- Debugging information ----
message             : No converter available
type                : com.google.common.collect.Lists$RandomAccessReverseList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @76a3e297
-------------------------------
com.thoughtworks.xstream.converters.ConversionException: No converter available
---- Debugging information ----
message             : No converter available
type                : com.google.common.collect.Lists$RandomAccessReverseList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field protected transient int java.util.AbstractList.modCount accessible: module java.base does not "opens java.util" to unnamed module @76a3e297
```

### How to Reproduce?

```
@QuarkusTest
public class ExampleTest {

    @ParameterizedTest
    @MethodSource("params")
    void testLists(List<String> strings) {
        assertTrue(true);
    }

    private static Stream<Arguments> params() {
        return Stream.of(
            Arguments.of(
                Lists.reverse(List.of(1, 2, 3))
            )
        );
    }
}
```

### Output of `java -version`

openjdk 17.0.3 (Temurin-17.0.3+7)

### Quarkus version or git rev

2.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 7.5.1

**Comment by geoand** [comment] 2022-10-19 08:50
I'll close this in favor of https://github.com/quarkusio/quarkus/issues/28677 which has the same root cause

**Closed by geoand** 2022-10-19 08:50 UTC
Labels: kind/bug, area/testing
