### ISSUE TITLE
quarkus:dev  error on re compiling  windows 

### ISSUE THREAD

**Issue by halkhalil** [quarkusio/quarkus#4380] opened 2019-10-04 15:53 UTC
openjdk 11.0.4 2019-07-16
Apache Maven 3.6.2 
OS name: "windows 10"

in quarkus:dev  when a source file is changed terminal shows
(vert.x-worker-thread-1) Changed source files detected, recompiling....
and getting stuck here, while in browser the following errors are displayed. |
Error restarting Quarkus
java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/Users/.m2/repository/org/jboss/spec/javax/ws/rs/jboss-jaxrs-api_2.1_spec/1.0.2.Final/jboss-jaxrs-api_2.1_spec-1.0.2.Final.jar

**Comment by geoand** [comment] 2019-10-04 16:36
I am going to close this as a duplicate of #3592. Please follow that issue for updates.

Thanks

**Closed by geoand** 2019-10-04 16:36 UTC
Labels: bug, duplicate
