### ISSUE TITLE
PATCH with merge-patch+json not working properly with RESTEasy Reactive

### ISSUE THREAD

**Issue by errXprintln** [quarkusio/quarkus#37980] opened 2024-01-02 15:16 UTC
### Describe the bug

Dear Quarkus dev team,

while building my app using quarkus 3.2.2.Final I experienced that merge-patch+json seems not to be working properly with the quarkus-resteasy-reactive-jackson extension.

Some background:
Before experiencing this issue I was using quarkus-resteasy-jackson as dependency, where my PATCH would work like a charm.
However I switched to quarkus-resteasy-reactive-jackson due to a change of requirements within the project. 

That's when I experienced, that calling those PATCH routes result in a HTTP 500 Internal Server Error due to org.hibernate.PropertyValueException.
After a bit of digging it looks like the respective GET route is not called upon PATCH.

As per documentations regarding quarkus-resteasy-jackson the `resteasy.patchfilter.legacy` switch is set to true.

My respective resource with both GET and PATCH mappings:
```
@GET
  @Path("/{id}")
  public Foo getFoo(@PathParam("id") long id) {
    return fooService.getFoo(id);
  }

  @PATCH
  @Path("/{id}")
  @Consumes("application/merge-patch+json")
  @Produces(MediaType.APPLICATION_JSON)
  public Foo patchFoo(@PathParam("id") long id, Foo foo) {
    @SuppressWarnings("unchecked")
    Set<String> patchedFields = (Set<String>) request.getProperty("patchedFields");
    return fooService.update(id, foo, patchedFields);
  }
```

My implementation within fooService:
getFoo:
```
public Foo getFoo(long id) {
    return fooRepository.findByIdOptional(id).orElseThrow(EntityNotFoundException::new);
  }
```

update:
```
@Transactional
  public Foo update(long fooId, Foo foo, Set<String> patchedFields) throws EntityNotFoundException {
    Foo existingFoo = fooRepository.findByIdOptional(fooId)
        .orElseThrow(EntityNotFoundException::new);

    if (patchedFields.size() > 0) {
      changeService.recordEntityChanges(existingFoo, foo, existingFoo, 1, patchedFields);
    }

    foo = fooRepository.getEntityManager().merge(foo);
    fooRepository.persist(foo);
    return foo;
  }
```

Any help would be highly appreciated.

### Expected behavior

Upon calling the PATCH route with application/merge-patch+json the respective GET resource should be called upfront.

### Actual behavior

Upon calling the PATCH route with application/merge-patch+json the respective GET resource does not seem to be called upfront, since Exceptions like `not-null property references a null or transient value` are thrown, while the values on the PATCHED object are certainly not null.

### Output of `java -version`

17.0.7

### Quarkus version or git rev

3.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.8

**Comment by geoand** [comment] 2024-01-03 07:16
This is a duplicate of #24632, right?

**Comment by errXprintln** [comment] 2024-01-03 15:44
> This is a duplicate of #24632, right?

Yes, didn't find this. Sorry for that.
I can see that @FroMage wanted to know more about the usage of that, since it feels "hackish".
What kind of information do you need before you can make a decision about whether or not adding it to resteasy-reactive?

While I do not have a small reproducer at hand right now (I guess the reproducer mentioned in #24632 should be sufficient for my case), I can already give you the additional information, that I'm working along the repository pattern (`public class FooRepository implements PanacheRepository<Foo>`). Shouldn't make a difference but the more info the better.
Generally I think the handling in resteasy adds 5 points to convenience since the GET is executed automagically beforehand.

**Comment by geoand** [comment] 2024-01-03 15:47
> Yes, didn't find this. Sorry for that

No problem

**Closed** 2024-01-03 15:47 UTC
Labels: kind/bug, area/resteasy-reactive, triage/needs-feedback

**Comment by FroMage** [comment] 2024-01-04 14:49
Can you please add a comment on #24632 to explain your use-case? What's the client in this case (JavaScript, Java…)? Why are you using this merge-patch+json?
Thanks.
