### ISSUE TITLE
Internal server error when selecting certain extensions

### ISSUE THREAD

**Issue by xorye** [quarkusio/quarkus#5817] opened 2019-11-27 20:58 UTC
**Describe the bug**
I have discovered this error in two cases:
Case 1: Select Kotlin and Quarkus Extension for Spring Web API, then click "Generate your application"
Case 2: Select Scala and Quarkus Extension for Spring Web API, then click "Generate your application"

![image](https://user-images.githubusercontent.com/20326645/69758762-63dfca80-112e-11ea-8c6b-1b35fec6f275.png)
 
**Expected behavior**
Project should download. Or maybe its not meant for these two extensions to be used in the same project? Although, I am able to add these two extensions in the same project using the command line just fine.

**Actual behavior**
Internal server error

![image](https://user-images.githubusercontent.com/20326645/69758818-92f63c00-112e-11ea-94e6-93750d2c4185.png)

**Comment by gsmet** [comment] 2019-11-27 21:03
This is due to the fact that we don't have the appropriate templates:
```
java.io.IOException: Failed to locate templates/basic-rest/kotlin/spring-controller-template.ftl on the classpath
	at io.quarkus.platform.descriptor.loader.json.ClassPathResourceLoader.loadResource(ClassPathResourceLoader.java:24)
	at io.quarkus.platform.descriptor.loader.json.impl.QuarkusJsonPlatformDescriptor.getTemplate(QuarkusJsonPlatformDescriptor.java:108)
	at io.quarkus.generators.rest.BasicRestProjectGenerator$BasicRestProject.generate(BasicRestProjectGenerator.java:126)
	at io.quarkus.generators.rest.BasicRestProjectGenerator$BasicRestProject.createClasses(BasicRestProjectGenerator.java:213)
	at io.quarkus.generators.rest.BasicRestProjectGenerator$BasicRestProject.access$300(BasicRestProjectGenerator.java:46)
	at io.quarkus.generators.rest.BasicRestProjectGenerator.generate(BasicRestProjectGenerator.java:36)
	at io.quarkus.cli.commands.CreateProject.doCreateProject(CreateProject.java:134)
	at io.quarkus.code.services.QuarkusProjectCreator.create(QuarkusProjectCreator.kt:49)
```

I think this should be fixed somehow.

**Comment by uaihebert** [comment] 2019-11-30 23:07
hello, I was able to reproduce this problem locally.
```
Caused by: java.io.IOException: Failed to locate templates/basic-rest/scala/spring-controller-template.ftl on the classpath
	at io.quarkus.platform.descriptor.loader.json.ClassPathResourceLoader.loadResource(ClassPathResourceLoader.java:24)
	at io.quarkus.platform.descriptor.loader.json.impl.QuarkusJsonPlatformDescriptor.getTemplate(QuarkusJsonPlatformDescriptor.java:108)
	... 92 more
```
what should be the expected behavior? to return a 422 error saying that selected framework X is not supported by langague Y? Or to create the template?

**Comment by gsmet** [comment] 2019-12-06 12:05
@uaihebert sorry, I missed your comment somehow. The best solution would be to create the templates. I think they would be useful, at least for Kotlin (not totally sure about Scala as I'm not sure Spring Web + Scala is a common combination).

@geoand WDYT?

**Comment by geoand** [comment] 2019-12-06 12:07
Ouch... Yeah, we need to fix this one

**Comment by geoand** [comment] 2019-12-06 12:11
I'm on it, I'll have a PR momentarily

**Comment by geoand** [comment] 2019-12-06 12:22
PR is: https://github.com/quarkusio/quarkus/pull/5983.

I tested it locally and everything works

**Closed** 2019-12-06 17:11 UTC
Labels: component:kotlin, component:scala, component:spring, good first issue
