### ISSUE TITLE
Removing javax.decorator.Decorator annoation on class in AnnotationsTransformerBuildItem has no effect

### ISSUE THREAD

**Issue by mkomadel** [quarkusio/quarkus#30846] opened 2023-02-03 11:39 UTC
### Describe the bug

Removing `javax.decorator.Decorator` in extension with AnnotationsTransformerBuildItem has no effect as `io.quarkus.arc.processor.BeanDeployment` uses only `beanArchiveImmutableIndex `and doesn't check against AnnotationStore (which actually applies annotation transformations) if decorator annotation was removed within some `AnnotationsTransformerBuildItem ` build step. 

See here:
https://github.com/quarkusio/quarkus/blob/6faf038f8964c9685a2028d2fa56d3b13205e2b2/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L1287

### How to Reproduce?

Write quarkus extension with following deployment processor

```java
import io.quarkus.arc.deployment.AnnotationsTransformerBuildItem;
import io.quarkus.arc.processor.AnnotationsTransformer;
import io.quarkus.arc.processor.DotNames;
import io.quarkus.deployment.annotations.BuildStep;
import io.quarkus.deployment.builditem.FeatureBuildItem;

public class MyDeploymentProcessor {

    public static final String FEATURE_NAME = "mytest";

    @BuildStep
    FeatureBuildItem feature() {
        return new FeatureBuildItem(FEATURE_NAME);
    }

    @BuildStep
    public AnnotationsTransformerBuildItem removeDecorators() {
        return new AnnotationsTransformerBuildItem(new AnnotationsTransformer() {

            @Override
            public boolean appliesTo(org.jboss.jandex.AnnotationTarget.Kind kind) {
                return true;
            }

            @Override
            public void transform(TransformationContext context) {
                context.transform()
                        .remove(ann -> DotNames.DECORATOR.equals(ann.name()))
                        .done();
            }

        });
    }
}
```
And implement decorators
e.g.:

```java
 
import static org.junit.jupiter.api.Assertions.assertEquals;

import javax.annotation.Priority;
import javax.decorator.Decorator;
import javax.decorator.Delegate;
import javax.enterprise.context.Dependent;
import javax.inject.Inject;

import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.asset.EmptyAsset;
import org.jboss.shrinkwrap.api.spec.JavaArchive;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.RegisterExtension;

import io.quarkus.test.QuarkusUnitTest;

public class DecoratorTest {

    @RegisterExtension
    static final QuarkusUnitTest unitTest = new QuarkusUnitTest()
            .setArchiveProducer(() -> ShrinkWrap.create(JavaArchive.class)
                    .addAsManifestResource(EmptyAsset.INSTANCE, "beans.xml"));

    public interface TestInterface {
        String getValue();
    }

    @Dependent
    public static class DefaultBean implements TestInterface {

        @Override
        public String getValue() {
            return "Default";
        }

    }

    @Priority(1)
    @Decorator
    public static class MyDecorator implements TestInterface {

        @Inject
        @Delegate
        TestInterface delegate;

        @Override
        public String getValue() {
            return "Decorator " + delegate.getValue();
        }

    }

    @Inject
    TestInterface bean;

    @Test
    public void decorator_is_ignored() {
        //fails with DecoratorTest.decorator_is_ignored:60 expected: <Default> but was: <Decorator Default>
        assertEquals("Default", bean.getValue());
    }

}

```

**Comment by geoand** [comment] 2023-02-06 07:58
@mkouba is this the expected behavior or a bug?

**Comment by mkouba** [comment] 2023-02-06 08:41
Well, it's not supported at the moment because we didn't have a use case so far. 

@mkomadel do you need to "disable" an existing decorator? If so you can also try to produce an `ExcludedTypeBuildItem` in your extension.

**Comment by mkomadel** [comment] 2023-02-08 08:15
@mkouba it relates to this other bug from me #30811. In our company, we use 2 java stacks (quarkus and open liberty) and need to use our own internal framework, that was made primarily with open liberty in mind. In this case cdi decorator that implements the needed functionality is implementing interface extending other generic interface, which also doesn't work in quarkus (#30811). I was trying to work my way around this problem with making it a standard bean and implementing kind of service registry that would reuse existing code (in current decorators). This would work, as the use of decorator in our framework is (imho) wrong abstraction for the problem at hand, but changing the framework is, well, let say impossible. 

Currently I fell back to copy pasting of framework code into our extension.

**Comment by mkouba** [comment] 2023-02-08 16:26
I see. So you need to reuse the logic from the decorator.  I don't think that using a decorator as a regular bean is a good idea anyway. Ideally, you should extract the logic in a seperate bean/util method and use it in both the decorator and your extension.

**Comment by mkouba** [comment] 2023-02-08 16:28
I think that we can close this issue - the `ExcludedTypeBuildItem` can be used to ignore the decorator class completely and we don't want to support the use case where a decorator is used as a regular bean.

@manovotn @Ladicek WDYT?

**Comment by Ladicek** [comment] 2023-02-08 16:51
While I can't really say anything about the idea of using a decorator as a regular bean, I do believe we should normally look for annotations in the `AnnotationStore` and only use Jandex as an exception. So I'd personally be in favor of fixing the original issue: inability to remove the annotation through a transformer. I can take a look at that if you wish.

**Comment by Ladicek** [comment] 2023-02-08 16:57
Ah there's a catch, of course! The operation `Index.getAnnotations(DotName)` can't really be implemented using the annotation overlay. And it's super convenient on a bunch of places. Well, there it is :shrug:

**Comment by manovotn** [comment] 2023-02-08 19:06
I agree that using decorator as a bean is non-standard.
Leveraging `AnnotationStore` whenever possible should be a go-to option but I haven't checked the code to see if it's an option in this case. Can take a closer look tomorrow.
Last but not least, the other issue mentioned here (generic decorators) is something we should look into. Eventually. Because it's generic decorators, so nobody's to keen to take it I suppose :-D

**Comment by mkouba** [comment] 2023-02-08 20:14
> While I can't really say anything about the idea of using a decorator as a regular bean, I do believe we should normally look for annotations in the `AnnotationStore` and only use Jandex as an exception. So I'd personally be in favor of fixing the original issue: inability to remove the annotation through a transformer. I can take a look at that if you wish.

One of the drawbacks is that the delegate injection point will not be handled correctly. So it's not so easy...

**Comment by mkouba** [comment] 2023-02-09 08:25
> > While I can't really say anything about the idea of using a decorator as a regular bean, I do believe we should normally look for annotations in the `AnnotationStore` and only use Jandex as an exception. So I'd personally be in favor of fixing the original issue: inability to remove the annotation through a transformer. I can take a look at that if you wish.
> 
> One of the drawbacks is that the delegate injection point will not be handled correctly. So it's not so easy...

Which means that removing the `@Decorator` annotation would not be enough to make it work in most cases anyway...

> Ah there's a catch, of course! The operation `Index.getAnnotations(DotName)` can't really be implemented using the annotation overlay. And it's super convenient on a bunch of places. Well, there it is shrug

Yes, for this you would need to iterate over all known classes and then query the `AnnotationStore` which is possible but suboptimal (OTOH we already do this in several places).

**Comment by manovotn** [comment] 2023-06-26 08:47
@mkouba do you think it's worth looking into using `AnnotationStore` in this particular case or should we close the issue?

**Comment by mkouba** [comment] 2023-06-26 09:00
> @mkouba do you think it's worth looking into using `AnnotationStore` in this particular case or should we close the issue?

+0

I think that it's a very low priority...

**Comment by Ladicek** [comment] 2023-06-26 09:14
We recently fixed the original underlying issue (#30811), so perhaps we could just leave this as is?

Originally, I probably thought that removing the `@Decorator` annotation via a transformation would be enough to make the class work as a normal bean, but I'm now fairly sure it wouldn't. You'd also have to remove the `@Delegate` annotation from the delegate injection point, otherwise you would (or at least should; not sure if we validate it) get an error because delegate injection points are invalid outside of decorators, but doing that would most likely lead to resolution error or something generally weird.

I now think this proposal doesn't make too much sense.

**Comment by mkouba** [comment] 2023-06-26 09:21
> Originally, I probably thought that removing the `@Decorator` annotation via a transformation would be enough to make the class work as a normal bean, but I'm now fairly sure it wouldn't. You'd also have to remove the `@Delegate` annotation from the delegate injection point, otherwise you would (or at least should; not sure if we validate it) get an error because delegate injection points are invalid outside of decorators, but doing that would most likely lead to resolution error or something generally weird.

That's exactly what I was trying to explain above ;-)

**Comment by manovotn** [comment] 2023-06-26 10:39
> We recently fixed the original underlying issue (https://github.com/quarkusio/quarkus/issues/30811), so perhaps we could just leave this as is?

Yeah, that's pretty much why I bumped this issue :)

> Originally, I probably thought that removing the @Decorator annotation via a transformation would be enough to make the class work as a normal bean, but I'm now fairly sure it wouldn't. You'd also have to remove the @Delegate annotation from the delegate injection point, otherwise you would (or at least should; not sure if we validate it) get an error because delegate injection points are invalid outside of decorators, but doing that would most likely lead to resolution error or something generally weird.

> That's exactly what I was trying to explain above ;-)

Yes, the use cases are very limited.
I'll close this issue for now, the original problem was solved anyway and we can always revisit using `AnnotationStore` for decorators independently of this issue. Feel free to re-open if you disagree.

**Closed by manovotn** 2023-06-26 10:39 UTC
Labels: kind/bug, area/arc
