### ISSUE TITLE
Transform `-D` arguments to system properties

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#2885] opened 2019-06-19 07:21 UTC
Transform `-D` arguments to system properties so that users can just append properties to the command and don't need to jump back and forth.

Currently users have to pass properties prior to`-jar` - e.g. `java -Dfoo=bar -Dgoo=baz -jar myApplication-runner.jar`

it would be helpful to support also following style `java -jar myApplication-runner.jar -Dfoo=bar -Dgoo=baz -D...`

This works for Thorntail and some other projects, we should have similar usability experience

**Comment by gsmet** [comment] 2019-11-13 22:27
This is a duplicate of https://github.com/quarkusio/quarkus/issues/372 .

**Closed by gsmet** 2019-11-13 22:27 UTC
Labels: enhancement
