### ISSUE TITLE
Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest

### ISSUE THREAD

**Issue by aguilardias** [quarkusio/quarkus#9284] opened 2020-05-13 22:31 UTC
i've developed a rest service, i would like to log all request calls, with theirs parameters,

i started with this
https://github.com/quarkusio/quarkus-quickstarts/blob/master/rest-json-quickstart/src/main/java/org/acme/rest/json/LoggingFilter.java

im having problems acessing formAttributes of a multipart/form request

for example, the rest service is like this
```
@Path("/multipart-test")
@POST
@Consumes(MULTIPART_FORM_DATA)
@Produces(TEXT_PLAIN)
public String multiPartTest(@MultipartForm MyForm form
```
the filter
```
@Context
HttpServerRequest request;

@Override
public void filter(ContainerRequestContext requestContext) throws IOException {

    request.setExpectMultipart(true);
    request.endHandler(v -> {
        try {
            MultiMap formAttributes = request.formAttributes();
            System.out.println("formAttributes: " + formAttributes.entries().size());
        } catch (Exception e) {
            e.printStackTrace();
        }
    });
}
```
The exception is throwed
`Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest`

**Comment by geoand** [comment] 2020-05-14 11:08
Can you please provide a reproducer for this?

**Comment by aguilardias** [comment] 2020-05-14 13:11
Reproduce

1. `git clone https://github.com/aguilardias/quarkus-form-attributes.git`

2. start application
```
cd quarkus-form-attributes
mvn quarkus:dev
```

3. Open a new terminal and execute the following curl command (update file path):  
`curl -X POST "http://localhost:8080/hello" -H "accept: text/plain" -H "Content-Type: multipart/form-data" -F "name=user name" -F "photo=@/path/to/file"`

4. Watch error
```
endHandler
org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:124)
        at com.sun.proxy.$Proxy41.formAttributes(Unknown Source)
        at org.acme.AuditFilter.lambda$filter$1(AuditFilter.java:25)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:118)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by aguilardias** [comment] 2020-05-14 13:11
> Can you please provide a reproducer for this?

Reproducer

1. `git clone https://github.com/aguilardias/quarkus-form-attributes.git`

2. start application
```
cd quarkus-form-attributes
mvn quarkus:dev
```

3. Open a new terminal and execute the following curl command (update file path):  
`curl -X POST "http://localhost:8080/hello" -H "accept: text/plain" -H "Content-Type: multipart/form-data" -F "name=user name" -F "photo=@/path/to/file"`

4. Watch error
```
endHandler
org.jboss.resteasy.spi.LoggableFailure: RESTEASY003880: Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest
        at org.jboss.resteasy.core.ContextParameterInjector$GenericDelegatingProxy.invoke(ContextParameterInjector.java:124)
        at com.sun.proxy.$Proxy41.formAttributes(Unknown Source)
        at org.acme.AuditFilter.lambda$filter$1(AuditFilter.java:25)
        at io.vertx.core.http.impl.HttpServerRequestImpl.onEnd(HttpServerRequestImpl.java:530)
        at io.vertx.core.http.impl.HttpServerRequestImpl.lambda$pendingQueue$1(HttpServerRequestImpl.java:118)
        at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:237)
        at io.vertx.core.streams.impl.InboundBuffer.drain(InboundBuffer.java:224)
        at io.vertx.core.streams.impl.InboundBuffer.lambda$fetch$0(InboundBuffer.java:277)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by Meemaw** [comment] 2020-05-31 16:44
I've faced the same issue, but I found a workaround. This error happens when you are trying to access properties of HttpServerRequest inside async lambda.

e.g. following code will crash:
```java
  public CompletionStage<Response> logout(String sessionId) {
    return ssoService
        .logout(sessionId)
        .thenApply(
            deleted -> {
              String cookieDomain = RequestUtils.parseCookieDomain(request.absoluteURI());
              return Response.ok().cookie(SsoSession.clearCookie(cookieDomain)).build();
            });
  }
```

but this will work:

```java
  public CompletionStage<Response> logout(String sessionId) {
    String cookieDomain = RequestUtils.parseCookieDomain(request.absoluteURI());
    return ssoService
        .logout(sessionId)
        .thenApply(deleted -> Response.ok().cookie(SsoSession.clearCookie(cookieDomain)).build());
  }
```

**Comment by brundipub** [comment] 2020-09-14 09:15
Hi, in my case I was getting data from the request repetitively in a loop, like:

```
for (String host : hostsList) {
  if (host.equals(request.remoteAddress().host())) {
      (...)
   }
}

```
Only first passing worked, the second threw the exception "Unable to find contextual data of type: io.vertx.core.http.HttpServerRequest".

Solution: Put the value to a local variable and use it in the loop.

```
String requestHost = request.remoteAddress().host();
for (String host : hostsList) {
  if (host.equals(requestHost)) {
      (...)
   }
}




```

**Comment by geoand** [comment] 2021-08-03 10:30
I am going to close this as such issues have been addressed in a much better way in RESTEasy Reactive. See [this](https://quarkus.io/guides/resteasy-reactive#request-or-response-filters) part of the documentation

**Closed by geoand** 2021-08-03 10:30 UTC
Labels: kind/bug

**Comment by guoxunbo** [comment] 2022-04-02 06:17
@geoand  hello. I had saw this.But I don;t konw how to get multipart/form-data info in filter?

**Comment by guoxunbo** [comment] 2022-04-02 06:18
@aguilardias do to get multipart/form-data info in filter? Can you tell me how to get these info?

**Comment by geoand** [comment] 2022-04-02 16:37
What info do you need?

**Comment by guoxunbo** [comment] 2022-04-06 01:54
@geoand such as this. I want to get the `MultipartBody` info like `request` property in web filter.
```java
public class MultipartBody implements Serializable {

    @FormParam("file")
    @PartType(MediaType.APPLICATION_OCTET_STREAM)
    public InputStream file;

    @FormParam("fileName")
    @PartType(MediaType.TEXT_PLAIN)
    public String fileName;

    @FormParam("request")
    @PartType(MediaType.TEXT_PLAIN)
    public String request;

}
```

**Comment by geoand** [comment] 2022-04-06 06:47
That information is only available in an actual endpoint, not a filter

**Comment by guoxunbo** [comment] 2022-04-06 07:40
Yes.I konw. Is there have any thing to gei this info? but a model.such as a map. Let me to get the `request` info.
such as spring `MultipartResolver ` and `StandMultipartResolver `

**Comment by geoand** [comment] 2022-04-06 07:46
Not really, because this information is part of the body which may not have been read yet
