### ISSUE TITLE
Docker or Podman required for tests since 3.0.0.Alpha6

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#31893] opened 2023-03-16 09:16 UTC
### Describe the bug

Since 3.0.0.Alpha6 it's not possible to run tests that do not require testcontainers without having docker or podman installed. Instead you get:

```
SomeTest > initializationError FAILED
	    java.lang.NoClassDefFoundError at BasicLoggingEnabler.java:109
	        Caused by: java.lang.ExceptionInInitializerError at ContainerRuntimeUtil.java:86
 ```

### Expected behavior

You should only need podman/docker if testcontainer needs to be startet

### Actual behavior

You need podman/docker even if you only have unit tests without any interaction with services

### How to Reproduce?

1. Have a computer without docker or podman installed (or simply not in Path)
2. Init a simple quarkus app with 3.0.0.Alpha6 without and extensions
3. Try to run the tests

### Output of `uname -a` or `ver`

5.19.0-35-generic

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS
OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### Quarkus version or git rev

3.0.0.Alpha6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------
Gradle 8.0.2
------------------------------------------------------------

Build time:   2023-03-03 16:41:37 UTC
Revision:     7d6581558e226a580d91d399f7dfb9e3095c2b1d

Kotlin:       1.8.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.18 (Ubuntu 11.0.18+10-post-Ubuntu-0ubuntu122.04)
OS:           Linux 5.19.0-35-generic amd64

### Additional information

Noticed it on the build server first, then tried uninstalling docker + podman locally and that let me reproduce it.

**Comment by geoand** [comment] 2023-03-16 09:31
cc @Karm

**Comment by gsmet** [comment] 2023-03-16 09:59
@bulldog98 could you paste the whole stacktrace, please?

**Comment by gsmet** [comment] 2023-03-16 10:05
Let's make this a priority because we need this usability regression to get fixed by the final.

**Comment by Karm** [comment] 2023-03-16 10:31
This is fixed by #31857, i.e. the scenario where neither docker nor podman is available.

**Comment by bulldog98** [comment] 2023-03-16 10:42
```
build	16-Mar-2023 09:25:58	> Task :project:test
build	16-Mar-2023 09:25:58	
build	16-Mar-2023 09:25:58	Test2 > initializationError FAILED
build	16-Mar-2023 09:25:58	    java.lang.NoClassDefFoundError at BasicLoggingEnabler.java:109
build	16-Mar-2023 09:25:58	        Caused by: java.lang.ExceptionInInitializerError at ContainerRuntimeUtil.java:86
build	16-Mar-2023 09:25:58	
build	16-Mar-2023 09:25:58	Test1 > initializationError FAILED
build	16-Mar-2023 09:25:58	    java.lang.NoClassDefFoundError at BasicLoggingEnabler.java:109
build	16-Mar-2023 09:25:58	        Caused by: java.lang.ExceptionInInitializerError at ContainerRuntimeUtil.java:86
error	16-Mar-2023 09:25:58	
error	16-Mar-2023 09:25:58	31 tests completed, 31 failed
build	16-Mar-2023 09:25:59	
build	16-Mar-2023 09:25:59	> Task :project:test FAILED
```
Was all I got on the ci, with 29 more tests, that all had the exact same error message @gsmet 

On my computer I got the stacktrace

```
Could not initialize class io.quarkus.test.junit.IntegrationTestUtil
java.lang.NoClassDefFoundError: Could not initialize class io.quarkus.test.junit.IntegrationTestUtil
	at io.quarkus.test.junit.BasicLoggingEnabler.beforeAll(BasicLoggingEnabler.java:109)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:110)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:90)
	at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:85)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at jdk.proxy2/jdk.proxy2.$Proxy5.stop(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker$3.run(TestWorker.java:193)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:129)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:100)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:60)
	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)
	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
	at worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
```

**Comment by jefrog1844** [comment] 2023-03-17 03:27
[com.mfmea.dfmea.authentication.AuthenticationResourceTest.txt](https://github.com/quarkusio/quarkus/files/10997544/com.mfmea.dfmea.authentication.AuthenticationResourceTest.txt)

**Comment by Karm** [comment] 2023-03-17 06:01
@jefrog1844 That is before the #31857 fix, right?

**Closed** 2023-03-17 08:44 UTC
Labels: kind/bug, priority/blocker, triage/quarkus-3

**Comment by jefrog1844** [comment] 2023-03-17 23:31
Thanks for the quick response
