### ISSUE TITLE
Hibernate Reactive does not work with Flyway Migration

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#15499] opened 2021-03-05 16:14 UTC
**Describe the bug**
We try to use hibernate reactive for database access and flyway for migrations in a project. Since flyway seems to require a standard (non-reactive) datasource, we defined two datasources with different tenant names. 

Unfortunately, as soon as we add the flyway dependency, Quarkus cannot start any more and complains that our reactive datasource (called `xreactive`) would need to have the property `quarkus.datasource.xreactive.jdbc.url` specified. 

However, when we specify this property additionally to the reactive properties, hibernate reactive complains the reactive datasource would not be a reactive one. The exception is:
```
2021-03-05 17:10:15,435 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalStateException: Booting an Hibernate Reactive serviceregistry on a non-reactive RecordedState!
	at io.quarkus.hibernate.reactive.runtime.boot.registry.PreconfiguredReactiveServiceRegistryBuilder.checkIsReactive(PreconfiguredReactiveServiceRegistryBuilder.java:76)
	at io.quarkus.hibernate.reactive.runtime.boot.registry.PreconfiguredReactiveServiceRegistryBuilder.<init>(PreconfiguredReactiveServiceRegistryBuilder.java:66)
	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.rewireMetadataAndExtractServiceRegistry(FastBootHibernateReactivePersistenceProvider.java:177)
	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.getEntityManagerFactoryBuilderOrNull(FastBootHibernateReactivePersistenceProvider.java:156)
	at io.quarkus.hibernate.reactive.runtime.FastBootHibernateReactivePersistenceProvider.createEntityManagerFactory(FastBootHibernateReactivePersistenceProvider.java:82)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:117)
	at io.quarkus.hibernate.orm.runtime.JPAConfig.startAll(JPAConfig.java:41)
	at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.startAllPersistenceUnits(HibernateOrmRecorder.java:88)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits951856026.deploy_0(HibernateOrmProcessor$startPersistenceUnits951856026.zig:74)
	at io.quarkus.deployment.steps.HibernateOrmProcessor$startPersistenceUnits951856026.deploy(HibernateOrmProcessor$startPersistenceUnits951856026.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:784)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

How can we use Flyway in conjunction with reactive hibernate?

**Expected behavior**
Flyway should use the specified datasource and not require the jdbc url on the reactive datasource.

**Actual behavior**
It crashes.

**To Reproduce**

1. Download reproducer project and unzip
[2021-03-05-flyway-reactive.zip](https://github.com/quarkusio/quarkus/files/6091727/2021-03-05-flyway-reactive.zip)
2. Run docker-compose to startup postgres database
3. Run `./gradlew quarkusDev` to start the application. This crashes with
```
Listening for transport dt_socket at address: 5005
quarkus.datasource.xreactive.jdbc.url has not been defined
Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-03-05 17:14:14,004 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start hot replacement endpoint to recover from previous Quarkus startup failure
```

**Configuration**
See reproducer

**Environment (please complete the following information):**
 - Windows, MacOS
 - Quarkus 1.12.1.Final
 - Java 11

**Comment by geoand** [comment] 2021-03-05 16:22
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/10716

**Closed** 2021-03-05 16:22 UTC
Labels: area/flyway, area/hibernate-reactive, area/persistence, env/windows, kind/bug
