### ISSUE TITLE
Application yaml configuration arrays (http.cors) not working

### ISSUE THREAD

**Issue by Michael-AT-Corporation** [quarkusio/quarkus#44875] opened 2024-12-02 12:54 UTC
### Describe the bug

When I upgraded from Quarkus 3.16.3 to 3.17.0 the cors configuration stopped working. Maybe the problem is a general one and not just related to the cors configuration.  (Also not working with 3.17.2)
Apparently the configuration can't read arrays in a yaml with the following format:
```
quarkus:
  http:
    cors:
      ~: true
      origins:
        - http://localhost:8000
```
But when using the other format like:
```
quarkus:
  http:
    cors:
      ~: true
      origins: http://localhost:8000
```
it works as expected. The same behaviour occurs for http.cors.headers or methods.

### Expected behavior

The configuration is read correctly.

### Actual behavior

The configuration for origings is empty.

### How to Reproduce?

Reproducer:
[reproducerConfigYamlArray.zip](https://github.com/user-attachments/files/17978067/reproducerConfigYamlArray.zip)

Run `mvn clean test`. The test should fail with 403 Error.
Then comment out line 6 and 7 of the application.yaml and uncomment line 5. Then run `mvn clean test` again and the test should finish succesfully.
When setting a breakpoint in the CorsFilter function `public void handle(RoutingContext event)` you can see that the origings of the cors config are empty or set when using the line 5 in the config.

### Quarkus version or git rev

3.17.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment] 2024-12-02 14:17
@radcortez I assume the root cause is the same (the since fixed) https://github.com/quarkusio/quarkus/issues/44811?

**Comment by Michael-AT-Corporation** [comment] 2024-12-02 15:06
@radcortez Yes, the downgrade `io.smallrye.config:smallrye-config-source-yaml` to `3.9.1` works with 3.17.2

**Comment by geoand** [comment] 2024-12-02 15:18
Thanks for checking @Michael-AT-Corporation.

Closing this as `out-of-date` then as the fix has already been merged in `main`.

**Closed by geoand** 2024-12-02 15:18 UTC
Labels: kind/bug, area/config
