### ISSUE TITLE
[Vert.x 4] Incorrect HTTP metric reporting

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15593] opened 2021-03-10 07:12 UTC
**Describe the bug**

An assertion from `io.quarkus.it.micrometer.prometheus.PrometheusMetricsRegistryTest` does not pass with Vert.x 4.

With an endpoint like:
```
@GET
@Path("item/{id}")
public String item(@PathParam("id") String id) {
    return "return message with id " + id;
}
```

The reported metrics uses the actual path instead of the parameterized path:

```
http_server_requests_seconds_count{env="test",method="GET",outcome="SUCCESS",registry="prometheus",status="200",uri="/message/item/123",} 1.0
http_server_requests_seconds_sum{env="test",method="GET",outcome="SUCCESS",registry="prometheus",status="200",uri="/message/item/123",} 0.002675179
```

This will lead to OOM as for each unique id, a metric will be captured. 

**Expected behavior**

It should report:
```
http_server_requests_seconds_count{env="test",method="GET",outcome="SUCCESS",registry="prometheus",status="200",uri="/message/item/{id}",} 1.0
http_server_requests_seconds_sum{env="test",method="GET",outcome="SUCCESS",registry="prometheus",status="200",uri="/message/item/{id}",} 0.002675179
```

**To Reproduce**

In the `vertx-snapshot` branch:

* Open io.quarkus.it.micrometer.prometheus.PrometheusMetricsRegistryTest
* Uncomment line 137 
* Run -> boom

Note: The assertion has been commented to avoid being stuck. However, this issue should be considered critical.

**Comment by cescoffier** [comment] 2021-03-10 12:42
I was able to workaround the issue by specifying an explicit match pattern (/message/item/\\[0-9]+=/message/item/{id}).

**Comment by ebullient** [comment] 2021-03-10 13:00
This should be related to #15047 , but could also require micrometer to change how it is storing state against Vertx context.

**Comment by cescoffier** [comment] 2021-03-22 08:51
@ebullient I've seen work around that. Are we good?

**Comment by ebullient** [comment] 2021-03-22 13:05
Not quite. I put a lid on it (no OOM), if you want to try that and call that an answer to this issue..

Better recognition of patterns for client / server / etc. is still in flight.

**Comment by cescoffier** [comment] 2021-04-12 07:22
@ebullient should this one be closed?

**Comment by ebullient** [comment] 2021-04-12 12:46
Close as duplicate of #15231

**Closed by ebullient** 2021-04-12 12:46 UTC
Labels: area/metrics, area/vertx, kind/bug
