### ISSUE TITLE
integrate mapstruct with dev mode

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#17745] opened 2021-06-07 21:50 UTC
ATM, `quarkus:dev` restart is needed when mapstruct interface gets changed.
It would be great if we could have it working without needing the restart.

It could probably be made by creating a mapstruct extension and using the code gen provider but would require some changes.

**Comment by famod** [comment] 2021-06-08 21:37
Related: #1502 & #5956 (maybe more)

**Comment by michalszynkiewicz** [comment] 2021-06-09 10:13
Thanks @famod !

Maybe we could have a single CodeGenProvider invoking all the annotation processors...

**Comment by geoand** [comment] 2021-08-03 16:22
Closing this as it's a duplicate of the aforementioned issues

**Closed by geoand** 2021-08-03 16:22 UTC
Labels: area/devmode, kind/enhancement
