### ISSUE TITLE
kubernetes init container value wrong in yaml

### ISSUE THREAD

**Issue by csscriptplus** [quarkusio/quarkus#27934] opened 2022-09-14 13:31 UTC
### Describe the bug

**My maven build has following parameters:**

- -Dquarkus.kubernetes.init-containers."init-containers".image=curlimages/curl:latest
- -Dquarkus.kubernetes.init-containers."init-containers".command=["sh","-c"]
- -Dquarkus.kubernetes.init-containers."init-containers".arguments=["while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done"]

**That is wrote in the Kubernetes.yml:**
```
  - args:
        - "[while [ 200 -ne 200 ]; do sleep 2; done]"
    command:
        - "[sh"
        - "-c]"
    image: curlimages/curl:latest
```

**I would like that:**
```
   - command: ["sh", "-c"]
     args: ["while [ $(curl -ksw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done"]
     image: curlimages/curl
```

### GraalVM version (if different from Java)

22.2

### Quarkus version or git rev

2.11.2

**Comment by csscriptplus** [comment] 2022-09-14 20:02
@geoand it doesn't work.
```
command:
        - "[\"sh\""
        - "\"-c\"]"
```

**Comment by Sgitario** [comment] 2022-09-15 05:14
I think the problem is that you're wrapping the values with `[...]` in the `command` and `arguments` properties. These properties are a comma-separated list. Instead, I tried with:

```
quarkus.kubernetes.init-containers."init-containers".command=sh -c
quarkus.kubernetes.init-containers."init-containers".arguments=while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done
```

And the output looks better:

```yaml
initContainers:
      - args:
          - "while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null)\
            \ -ne 200 ]; do sleep 2; done"
        command:
          - sh -c
```

Note the stripping of the `args` value (it's in two lines because it's too long). I think this is automatically done by the yaml serializer (Jackson) and I'm not sure if it interferes with the execution, please let me know if so, as I think it would need some fixing on the Dekorate side.

**Comment by csscriptplus** [comment] 2022-09-15 09:59
@Sgitario  This is the result of my tests:
Application.properties | Kubernetes.yml
-- | --
Command: [sh, -c] | command:   <br>- "[sh"  <br> - " -c]”
Command: sh, -c | command:   <br>- sh  <br>- ‘ -c’
Command: “sh, -c” | command:   <br>- '"sh'   <br>- ' -c"'
Command: “sh”, “-c” | command:   <br>- '"sh"'  <br> - '"-c"'
Command: sh -c | command:  - sh -c

**All results are wrong.**

Possible results are:
`command: [sh, -c]`
```
command:
  - sh
  - -c
```

**Comment by Sgitario** [comment] 2022-09-15 10:07
> @Sgitario This is the result of my tests:
> 
> Application.properties	Kubernetes.yml
> Command: [sh, -c]	command:  
> - "[sh"  
> - " -c]”
> Command: sh, -c	command:  
> - sh  
> - ‘ -c’
> Command: “sh, -c”	command:  
> - '"sh'  
> - ' -c"'
> Command: “sh”, “-c”	command:  
> - '"sh"'  
> - '"-c"'
> Command: sh -c	command:  - sh -c
> **All results are wrong.**
> 
> Possible results are: `command: [sh, -c]`
> 
> ```
> command:
>   - sh
>   - -c
> ```

Why is wrong: `quarkus.kubernetes.init-containers."init-containers".command=sh -c`? The output seems correct, or is Kubernetes failing to start the container? 

Alternatively, have you tried to move the `-c` flag to the arguments? To be precise:

```
quarkus.kubernetes.init-containers."init-containers".command=sh
quarkus.kubernetes.init-containers."init-containers".arguments=-c,while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done
```

**Comment by csscriptplus** [comment] 2022-09-15 10:27
> Why is wrong: quarkus.kubernetes.init-containers."init-containers".command=sh -c? The output seems correct, or is Kubernetes failing to start the container?
```
command:
  - sh -c
```
This is in a kubernetes yaml file not correct. The container is not starting.

**Comment by csscriptplus** [comment] 2022-09-15 10:28
```
quarkus.kubernetes.init-containers."init-containers".command=sh
quarkus.kubernetes.init-containers."init-containers".arguments=-c,while [ $(curl -sw '%{http_code}' http://nexus.xxx.local -o /dev/null) -ne 200 ]; do sleep 2; done
```

This works and the container is starting.

**Comment by Sgitario** [comment] 2022-09-19 05:04
I'm glad it worked. I'm closing the issue then.

**Closed by Sgitario** 2022-09-19 05:04 UTC
Labels: kind/bug, area/kubernetes
