### ISSUE TITLE
Resteasy Reactive fails with beanparam nested in beanparams

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#27501] opened 2022-08-25 12:02 UTC
### Describe the bug

In case BeanParams are used on a subresource like this:

Subresource:
``` 
  @Path("/datasource")
  public DatasourceResource getDatasource() {
    return new DatasourceResource();
  }
```

BeanParam:
```
  @GET
  @Path("/reactive")
  public String showResteasyReactive(@BeanParam BeanParamExample beanParamExample) {
```

then the endpoint registration fails, test returns 405 Method not allowed. 

### Expected behavior

Resteasy reactive should work the same way as classic. 

### Actual behavior

405 Method not allowed returned.

### How to Reproduce?

Please compile the following project:

[resteasy-reactive-problem-project.tar.gz](https://github.com/quarkusio/quarkus/files/9424413/resteasy-reactive-problem-project.tar.gz)

Changing the resteasy implementation makes it pass the test.

### Quarkus version or git rev

2.11.3

**Comment by Sgitario** [comment] 2022-08-26 07:43
Looking at the reproducer, the problem is that the `DatasourceResource.java` is explicitly producing a JSON media type plus adding an extra "/" to the path:

```java
@Path("/")
@Produces("application/json")
@IfBuildProfile("")
public class DatasourceResource {
// ...
}
```

Removing the annotations `@Path` and `@Produces` will fix your issue and your tests will pass. 
@geoand I think we can close this issue, unless you think that adding extra path "/" should work (I think the actual behaviour is correct).

**Comment by geoand** [comment] 2022-08-26 08:38
Thanks for looking into @Sgitario.

Yeah, I think we can close it

**Comment by smil2k** [comment] 2022-08-26 12:50
Hi,

Thank you the reproducer now working fine, but it turned out that it was simpler than our scenario. Please find attached the extended variant:
[resteasy-reactive-problem-project.tar.gz](https://github.com/quarkusio/quarkus/files/9433268/resteasy-reactive-problem-project.tar.gz)

The problem is caused by an embedded bean param in a bean param. Again, for classic it was fine.

**Comment by smil2k** [comment] 2022-08-29 07:38
@Sgitario @geoand Can you look at the new reproducer, or shall I open a new ticket?

**Comment by geoand** [comment] 2022-08-29 07:39
I'll let @Sgitario decide

**Comment by Sgitario** [comment] 2022-08-30 05:31
Indeed, this is not working in Resteasy Reactive, where it was working fine for Resteasy Classic. 
Let's reopen this issue.

**Closed** 2022-08-30 14:04 UTC
Labels: kind/bug, area/resteasy-reactive
