### ISSUE TITLE
Kotlin reactive messaging 

### ISSUE THREAD

**Issue by jogueber** [quarkusio/quarkus#22945] opened 2022-01-17 16:41 UTC
### Describe the bug

When I write the following code with the `quarkus-smallrye-reactive-messaging-rabbitmq` : 
```
    @Incoming("interface-exc")
    @Outgoing("outgoind")
    suspend fun handleActualMsg(msg: Message<JsonObject>): Message<JsonObject>? {
        val converted = msg.payload.mapTo()
        val queueName = determineQueueName(converted)
        val outgoing = copyHeaders(metadata, queueName)
        return Message.of(
            msg.payload, Metadata.of(outgoing)
        )
    }
```
I get the following exception:
```
2022-01-17 17:32:01,447 ERROR [io.sma.rea.mes.provider] (pool-1-thread-1) SRMSG00201: Error caught while processing a message: java.lang.IllegalStateException: No Vertx context found
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:16)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:11)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:91)
	at io.smallrye.reactive.messaging.providers.SubscriberMediator.lambda$processMethodReturningACompletionStage$18(SubscriberMediator.java:218)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:63)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:591)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:24)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:161)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:191)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:597)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:82)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:46)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)

```

### Expected behavior

The handler should process the message in seperate coroutine!

### How to Reproduce?

Create an applicaiton with kotlin+reactive-messaging-rabbit mq
(version 2.6.2)

1. define input and output
2. annotate a method with  `@Incoming` and `@Outgoing`
test the app with an embedded rabbit 

### Output of `java -version`

openjdk 11.0.2 2019-01-15

### Additional information

according to https://github.com/quarkusio/quarkus/issues/21423 it is supposed to be fixed I can't confirm and reproduce this!

**Comment by cescoffier** [comment] 2022-01-17 16:43
I believe it's a duplicate of #21423.

**Comment by cescoffier** [comment] 2022-01-17 16:44
My guess is that the client does not go back on the Vert.x context.

**Comment by jogueber** [comment] 2022-01-17 16:45
okay is there some way to work around the issue or rather not?

**Comment by cescoffier** [comment] 2022-01-17 20:03
It should be possible with Vertx DB clients or Hibernate Reactive.

**Comment by kdubb** [comment] 2022-01-18 05:25
@jogueber Does a simple incoming, like the following, work for you?

```
@Incoming("interface-exc")
suspend fun handleActualMsg(msg: Message<JsonObject>) {
}
```

I know we were discussing this in the Kafka issue. The above works for me in 2.6.2.Final

**Comment by jogueber** [comment] 2022-01-24 23:00
Not a 100% but I think the above solution didn't work either @kdubb 
I will verify it though!

**Comment by geoand** [comment] 2022-02-07 08:38
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/21423.

**Closed by geoand** 2022-02-07 08:38 UTC
Labels: kind/bug, area/smallrye, area/kotlin, area/reactive-messaging
