### ISSUE TITLE
Scheduler delay not always considered in native executable

### ISSUE THREAD

**Issue by belu** [quarkusio/quarkus#19967] opened 2021-09-07 13:58 UTC
### Describe the bug

The initial delay of a `@Scheduled` method is not always considered in a native executable.

### Expected behavior

The initial delay is always considered on every start of the application.

### Actual behavior

The initial delay is sometimes not considered on the start of the application.

### How to Reproduce?

Reproducer:

https://github.com/belu/quarkus-bootcamp

The scheduled method is defined here:
https://github.com/belu/quarkus-bootcamp/blob/v1.0/src/main/java/ch/open/messaging/NewFactProducer.java
with the following settings:
`@Scheduled(every = "5s", delay = 3, delayUnit = TimeUnit.SECONDS)`

Therefore it is expected to be triggered after 3 seconds for the first time.

There is a release for Linux and Mac. Tested with the Linux version.
For setup of env use provided `docker-compose.yml`.

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.6.3

**Comment by mkouba** [comment] 2021-09-08 07:10
So I don't think it's a problem in the scheduler, i.e. the `NewFactProducer.produceNewFact()` seems to be executed corretly. I tried to add some logging in this method and I was never able to reproduce the problem, i.e. the method was always called after the delay. However, I saw that the method `NewFactConsumer.consume()` can be called immediately when the app starts which could be caused by the fact that a message can be produced by `NewFactProducer.produceNewFact()` but not consumed e.g. because the app is stopped. And so when the app starts the kafka log is read and `NewFactConsumer.consume()` is called.

```
2021-09-08 08:46:15,387 INFO  [io.quarkus] (main) quarkus-bootcamp 1.0.0-SNAPSHOT native (powered by Quarkus 2.2.1.Final) started in 0.058s. Listening on: http://0.0.0.0:8080
2021-09-08 08:46:15,387 INFO  [io.quarkus] (main) Profile prod activated. 
2021-09-08 08:46:15,387 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, kafka-client, micrometer, narayana-jta, resteasy, resteasy-jackson, scheduler, smallrye-context-propagation, smallrye-health, smallrye-openapi, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, swagger-ui, vertx]
2021-09-08 08:46:15,389 INFO  [org.apa.kaf.cli.Metadata] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Cluster ID: 7RttLD3lQ2m9gqAnLR-Bhg
2021-09-08 08:46:15,389 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Discovered group coordinator localhost:9092 (id: 2147483647 rack: null)
2021-09-08 08:46:15,390 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] (Re-)joining group
2021-09-08 08:46:15,392 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] (Re-)joining group
2021-09-08 08:46:15,394 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Successfully joined group with generation Generation{generationId=17, memberId='kafka-consumer-facts-in-0a5813d7-90fd-46ec-8285-4ad20e95e70d', protocol='range'}
2021-09-08 08:46:15,394 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Finished assignment for group at generation 17: {kafka-consumer-facts-in-0a5813d7-90fd-46ec-8285-4ad20e95e70d=Assignment(partitions=[facts-0])}
2021-09-08 08:46:15,395 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Successfully synced group in generation Generation{generationId=17, memberId='kafka-consumer-facts-in-0a5813d7-90fd-46ec-8285-4ad20e95e70d', protocol='range'}
2021-09-08 08:46:15,395 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Notifying assignor about the new Assignment(partitions=[facts-0])
2021-09-08 08:46:15,395 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Adding newly assigned partitions: facts-0
2021-09-08 08:46:15,396 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-facts-in, groupId=quarkus-bootcamp] Setting offset for partition facts-0 to the committed offset FetchPosition{offset=14, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[localhost:9092 (id: 0 rack: null)], epoch=0}}
Incoming Kafka message: NewFact{statement='The tongue is the only muscle in one's body that is attached from one end.'}
2021-09-08 08:46:18,999 INFO  [ch.ope.messaging] (executor-thread-0) New fact PRODUCED: NewFact{statement='The Roman - Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD.'}
Incoming Kafka message: NewFact{statement='The Roman - Persian wars are the longest in history, lasting over 680 years. They began in 54 BC and ended in 628 AD.'}
```
CC @Ladicek

**Comment by Ladicek** [comment] 2021-09-08 08:35
I didn't try to run the reproducer, but what @mkouba writes seems to be true. The issue description lacks information -- specifically how do you observe the problem? If you see an `Incoming Kafka message` sooner than 3 seconds after startup, that _doesn't_ mean that the scheduler method fired sooner. It may very well mean that there's an unconsumed message in Kafka -- be it from previous run of the app, or otherwise.

**Comment by mkouba** [comment] 2021-09-08 13:53
Ok, I'm going to close this one. @belu feel free to reopen if needed.

**Closed by mkouba** 2021-09-08 13:53 UTC
Labels: kind/bug, area/scheduler
