### ISSUE TITLE
[CI] - Kogito extension + Quarkus LTS

### ISSUE THREAD

**Issue by radtriste** [quarkusio/quarkus#14791] opened 2021-02-03 11:53 UTC
This issue will be open and closed dependent on the state of https://github.com/kiegroup/kogito-runtimes building against Quarkus LTS branch.

If you have interest in being notified of this subscribe to the issue.

**Comment by radtriste** [comment] 2021-02-04 08:24
@geoand looks like there was an issue with the test ...
https://github.com/kiegroup/kogito-runtimes/runs/1828215473?check_suite_focus=true

It checks out `master` branch => `Your branch is up to date with 'origin/master'.`
but `context.yaml` seems fine ...
For the jbang issue at the end, I suspect the comment after the issue number to be the root cause ...

**Comment by radtriste** [comment] 2021-02-04 08:26
just noticed that it seems it does the other way around ...
https://github.com/kiegroup/kogito-runtimes/runs/1828215492?check_suite_focus=true
on this one it should checkout Quarkus `master` but seems to checkout a branch

**Comment by geoand** [comment] 2021-02-04 08:59
Thanks for reporting.

It should be fixed now. Furthermore I suggest you update https://github.com/kiegroup/kogito-runtimes/blob/master/.github/workflows/quarkus-snapshot.yaml#L80 on your side to better reflect what the step actually does

**Comment by radtriste** [comment] 2021-02-04 09:02
oh right gonna update that ! thx

**Comment by radtriste** [comment] 2021-02-05 10:18
@geoand Last thing
Build succeeded but the job is marked as FAILED due to:

```
[jbang] Building jar...
2021-02-05T06:36:42.5972270Z The CI build had status success.
2021-02-05T06:36:43.6468167Z Report issue found: [CI] - Kogito extension + Quarkus LTS - https://github.com/quarkusio/quarkus/issues/14791
2021-02-05T06:36:43.6473017Z The issue is currently OPEN
2021-02-05T06:36:44.0903245Z WARNING: An illegal reflective access operation has occurred
2021-02-05T06:36:44.0905856Z WARNING: Illegal reflective access by org.kohsuke.github.Requester (file:/home/runner/.m2/repository/org/kohsuke/github-api/1.101/github-api-1.101.jar) to field java.net.HttpURLConnection.method
2021-02-05T06:36:44.0908169Z WARNING: Please consider reporting this to the maintainers of org.kohsuke.github.Requester
2021-02-05T06:36:44.0909716Z WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
2021-02-05T06:36:44.0910798Z WARNING: All illegal access operations will be denied in a future release
2021-02-05T06:36:44.2098902Z java.io.UncheckedIOException: org.kohsuke.github.HttpException: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#update-an-issue"}
2021-02-05T06:36:44.2101692Z 	at Report.run(quarkus-ecosystem-issue.java:83)
2021-02-05T06:36:44.2103062Z 	at picocli.CommandLine.executeUserObject(CommandLine.java:1769)
2021-02-05T06:36:44.2104415Z 	at picocli.CommandLine.access$900(CommandLine.java:145)
2021-02-05T06:36:44.2106368Z 	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
2021-02-05T06:36:44.2108293Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
2021-02-05T06:36:44.2109388Z 	at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
2021-02-05T06:36:44.2110768Z 	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
2021-02-05T06:36:44.2112196Z 	at picocli.CommandLine.execute(CommandLine.java:1904)
2021-02-05T06:36:44.2113481Z 	at Report.main(quarkus-ecosystem-issue.java:92)
2021-02-05T06:36:44.2115529Z Caused by: org.kohsuke.github.HttpException: {"message":"Must have admin rights to Repository.","documentation_url":"https://docs.github.com/rest/reference/issues#update-an-issue"}
2021-02-05T06:36:44.2118341Z 	at org.kohsuke.github.Requester.handleApiError(Requester.java:903)
2021-02-05T06:36:44.2119836Z 	at org.kohsuke.github.Requester._to(Requester.java:415)
2021-02-05T06:36:44.2121008Z 	at org.kohsuke.github.Requester.to(Requester.java:336)
2021-02-05T06:36:44.2122182Z 	at org.kohsuke.github.GHIssue.edit(GHIssue.java:239)
2021-02-05T06:36:44.2123329Z 	at org.kohsuke.github.GHIssue.close(GHIssue.java:253)
2021-02-05T06:36:44.2124670Z 	at Report.run(quarkus-ecosystem-issue.java:66)
2021-02-05T06:36:44.2125423Z 	... 8 more
2021-02-05T06:36:44.2127097Z Caused by: org.kohsuke.github.HttpException: Server returned HTTP response code: 403, message: 'Forbidden' for URL: https://api.github.com/repos/quarkusio/quarkus/issues/14791
2021-02-05T06:36:44.2129312Z 	at org.kohsuke.github.Requester.parse(Requester.java:840)
2021-02-05T06:36:44.2130823Z 	at org.kohsuke.github.Requester.parse(Requester.java:782)
2021-02-05T06:36:44.2132147Z 	at org.kohsuke.github.Requester._to(Requester.java:393)
2021-02-05T06:36:44.2132981Z 	... 12 more
2021-02-05T06:36:44.2134171Z Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/quarkusio/quarkus/issues/14791
2021-02-05T06:36:44.2136961Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-02-05T06:36:44.2142258Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-02-05T06:36:44.2146140Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-02-05T06:36:44.2148794Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2021-02-05T06:36:44.2150482Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
2021-02-05T06:36:44.2152328Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
2021-02-05T06:36:44.2153814Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-02-05T06:36:44.2155756Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
2021-02-05T06:36:44.2158162Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
2021-02-05T06:36:44.2160597Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
2021-02-05T06:36:44.2163430Z 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:250)
2021-02-05T06:36:44.2165565Z 	at org.kohsuke.github.Requester.parse(Requester.java:818)
2021-02-05T06:36:44.2166330Z 	... 14 more
2021-02-05T06:36:44.2167288Z Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://api.github.com/repos/quarkusio/quarkus/issues/14791
2021-02-05T06:36:44.2169389Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
2021-02-05T06:36:44.2171981Z 	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
2021-02-05T06:36:44.2174185Z 	at java.base/java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:527)
2021-02-05T06:36:44.2176761Z 	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:334)
2021-02-05T06:36:44.2178940Z 	at org.kohsuke.github.Requester.parse(Requester.java:790)
2021-02-05T06:36:44.2179707Z 	... 14 more
2021-02-05T06:36:44.2552797Z ##[error]Process completed with exit code 1.
```
can you have a look ?

**Comment by geoand** [comment] 2021-02-05 10:28
I saw that but I think the problem is on your side.
See https://github.com/quarkusio/quarkus-ecosystem-ci#what-do-i-need-to-do-as-a-quarkus-platform-participant point `1`.

Basically you should close this issue, create a new one with user `kie-ci` (as has been done for #12486) and then update `info.yaml` in ecosystem-ci with the new ticket number

**Comment by radtriste** [comment] 2021-02-05 10:32
oh I see. gonna check that.
Thx !

**Comment by geoand** [comment] 2021-02-05 10:36
np!

**Comment by radtriste** [comment] 2021-02-05 17:08
Created new issue https://github.com/quarkusio/quarkus/issues/14860 and PR https://github.com/quarkusio/quarkus-ecosystem-ci/pull/41

**Closed** 2021-02-05 17:08 UTC
Labels: area/infra, triage/ci-participant, triage/ci-platform
