### ISSUE TITLE
Exception in blocking graphql query is wrapped

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#39059] opened 2024-02-28 14:57 UTC
### Describe the bug

With a blocking graphql query throwing an exception, the exception gets wrapped in an additional exception. Graphql specfic features do not work with this wrapped exception. For example, the error code is wrong and changed to `execution`.

The exception is thrown here, and we probably need to get the real exception somewhere around here.

https://github.com/quarkusio/quarkus/blob/9f7a2cd79658cc0f303f27d2e431d5a8d108ef7c/extensions/smallrye-graphql/runtime/src/main/java/io/quarkus/smallrye/graphql/runtime/spi/datafetcher/QuarkusUniDataFetcher.java#L57

### Expected behavior

Non wrapped exception and correct error code in graphql response.

### Actual behavior

Exception from application gets wrapped in other exception, disabling graphql specific features like error code.

### Additional information

```
{
  "timestamp":"2024-02-28T14:36:37.817379492Z",
  "sequence":68739,
  "loggerClassName":"io.smallrye.graphql.SmallRyeGraphQLServerLogging_$logger",
  "loggerName":"io.smallrye.graphql",
  "level":"ERROR",
  "message":"SRGQL012000: Data Fetching Error",
  "threadName":"vert.x-eventloop-thread-4",
  "threadId":48,
  "mdc":{ },
  "ndc":"",
  "hostName":"product-service-8544bdc687-dqhgt",
  "processName":"quarkus-run.jar",
  "processId":1,
  "exception":{
    "refId":1,
    "exceptionType":"java.util.concurrent.ExecutionException",
    "message":"de.mobilexag.serviceplatform.permission.PermissionException: Permissions not sufficient",
    "frames":[
      {
        "class":"java.util.concurrent.CompletableFuture",
        "method":"reportGet",
        "line":396
      },
      {
        "class":"java.util.concurrent.CompletableFuture",
        "method":"get",
        "line":2073
      },
      {
        "class":"io.smallrye.context.CompletableFutureWrapper",
        "method":"get",
        "line":148
      },
      {
        "class":"io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusUniDataFetcher",
        "method":"lambda$handleUserMethodCallBlocking$0",
        "line":57
      },
      {
        "class":"io.smallrye.context.impl.wrappers.SlowContextualCallable",
        "method":"call",
        "line":21
      },
      {
        "class":"io.vertx.core.impl.ContextImpl",
        "method":"lambda$executeBlocking$0",
        "line":177
      },
      {
        "class":"io.vertx.core.impl.ContextInternal",
        "method":"dispatch",
        "line":276
      },
      {
        "class":"io.vertx.core.impl.ContextImpl",
        "method":"lambda$internalExecuteBlocking$2",
        "line":209
      },
      {
        "class":"io.vertx.core.impl.TaskQueue",
        "method":"run",
        "line":76
      },
      {
        "class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14",
        "method":"runWith",
        "line":582
      },
      {
        "class":"org.jboss.threads.EnhancedQueueExecutor$Task",
        "method":"run",
        "line":2513
      },
      {
        "class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody",
        "method":"run",
        "line":1538
      },
      {
        "class":"org.jboss.threads.DelegatingRunnable",
        "method":"run",
        "line":29
      },
      {
        "class":"org.jboss.threads.ThreadLocalResettingRunnable",
        "method":"run",
        "line":29
      },
      {
        "class":"io.netty.util.concurrent.FastThreadLocalRunnable",
        "method":"run",
        "line":30
      },
      {
        "class":"java.lang.Thread",
        "method":"run",
        "line":1583
      }
    ],
    "causedBy":{
      "exception":{
        "refId":2,
        "exceptionType":"de.mobilexag.serviceplatform.permission.PermissionException",
        "message":"Permissions not sufficient",
      ...
```

**Comment by geoand** [comment] 2024-02-28 15:35
I assume all we have to do is get the cause of `ExecutionException` in `AbstractAsyncDataFetcher#invokeAndTransform` and use that, but I'll leave it to @jmartisk and @phillip-kruger

**Comment by phillip-kruger** [comment] 2024-02-28 23:26
@jmartisk this feels like the same issue in json-rpc that you fixed recently ?

**Comment by jmartisk** [comment] 2024-02-29 06:38
I don't understand what the problem is supposed to be.
Given two queries, one blocking and one async

```
    @Query
    public Uni<List<String>> testAsync() {
        throw new RuntimeException("This is a test exception");
    }
    @Query
    public List<String> test() {
        throw new RuntimeException("This is a test exception");
    }
```

And configuration:
```
quarkus.smallrye-graphql.show-runtime-exception-message=java.lang.RuntimeException
quarkus.smallrye-graphql.error-extension-fields=exception,classification,code,description,validationErrorType,queryPath
```

When I execute both using:

```
query {
  test 
  testAsync
}

```
I get the same exact result for them:

```
{
  "errors": [
    {
      "message": "This is a test exception",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "test"
      ],
      "extensions": {
        "classification": "DataFetchingException",
        "code": "runtime",
        "exception": "java.lang.RuntimeException"
      }
    },
    {
      "message": "This is a test exception",
      "locations": [
        {
          "line": 3,
          "column": 3
        }
      ],
      "path": [
        "testAsync"
      ],
      "extensions": {
        "classification": "DataFetchingException",
        "code": "runtime",
        "exception": "java.lang.RuntimeException"
      }
    }
  ],
  "data": {
    "test": null,
    "testAsync": null
  }
}
```

Can you provide some more info on how to reproduce it?

**Comment by robp94** [comment] 2024-02-29 07:25
This query
```
    @Query
    @Description("Say hello")
    @Blocking
    public Uni<String> sayHello() {
        return Uni.createFrom().failure(new RuntimeException());
    }
```
results in this error.
```
{
  "errors": [
    {
      "message": "java.lang.RuntimeException",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "sayHello"
      ],
      "extensions": {
        "classification": "DataFetchingException",
        "code": "execution",
        "exception": "java.util.concurrent.ExecutionException"
      }
    }
  ],
  "data": {
    "sayHello": null
  }
}
```

**Comment by jmartisk** [comment] 2024-02-29 07:56
I see, so this happens with queries that return `Uni` but are marked as blocking. That should be fixable, I'll look into it.

**Comment by phillip-kruger** [comment] 2024-03-01 04:48
@robp94 - out of interest, why add a `@Blocking` on a `Uni` ?

**Closed** 2024-03-01 08:38 UTC
Labels: kind/bug, area/smallrye, area/graphql

**Comment by robp94** [comment] 2024-03-01 11:30
@phillip-kruger if I remember correctly, in some validators we use blocking calls since ConstraintValidator does not support a non-blocking api.
