### ISSUE TITLE
QuarkusRestClientBuilder should fallback to read base URI from @RegisterRestClient annotation

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#18392] opened 2021-07-05 06:18 UTC
## Describe the bug
When using the `RestClientBuilder` API to programmatically construct a REST client, the implementation requires either of `RestClientBuilder#baseUrl()` or `RestClientBuilder#baseUri()` to be called, otherwise the `build()` method will fail with an `IllegalStateException`: https://github.com/quarkusio/quarkus/blob/987c9b466534e6d09782c3ca200e76b5e074e353/extensions/resteasy-classic/rest-client/runtime/src/main/java/io/quarkus/restclient/runtime/QuarkusRestClientBuilder.java#L232-L234

### Expected behavior
While this part isn't entirely clear from the spec (at least not to me), I think it would make sense if the implementation would also support the `baseUri` which can be registered on the `@RegisterRestClient` annotation as a fallback. And if that isn't given, then try to get the base URI (or base URL) from the respective config property (respecting the `configKey` if specified). This would also be in line with how other properties and the `@RegisterProvider` annotations are supported by the builder.

### Actual behavior
If `RestClientBuilder#baseUrl()` or `RestClientBuilder#baseUri()` isn't invoked the `build()` method will fail with an `IllegalStateException`.

### Quarkus version or git rev
Quarkus 2.0.0.Final

**Comment by geoand** [comment] 2021-07-05 07:05
cc @michalszynkiewicz

**Comment by michalszynkiewicz** [comment] 2021-07-23 10:11
Firstly, it's definitely not a bug. 

`@RegisterRestClient` - the annotation that has the `baseUri` attribute - is a marker to make the client generated for the interface available as a CDI bean.
As such, in my opinion, it should not be taken into consideration when create the client programmaticaly (with ClientBuilder).

@geoand what's your opinion?

**Comment by geoand** [comment] 2021-07-23 10:17
I agree with @michalszynkiewicz on this one. The way I see it, `@RegisterRestClient` is specific used for auto-registration of the interface and therefore anything specificied in it should be ignored when doing programmatic registration.

I propose we close this as `won't-fix`

**Closed** 2021-07-23 11:58 UTC
Labels: area/rest-client, kind/enhancement
