### ISSUE TITLE
integration-tests/jackson fails in native mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#5993] opened 2019-12-06 15:48 UTC
integration-tests/jackson fails in native mode, I see it on latest macOS with latest GraalVM, I see it on RHEL 7 with latest GraalVM too

```
mvn -version
Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T17:06:16+02:00)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 1.8.0_232, vendor: Oracle Corporation, runtime: /Users/rsvoboda/.sdkman/candidates/java/19.3.0.r8-grl/jre
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.1", arch: "x86_64", family: "mac"
```

Interesting part is https://github.com/quarkusio/quarkus/blob/master/ci-templates/stages.yml#L328 which means CI is passing (probably).

```
cd integration-tests/jackson
mvn clean verify -Dnative
...
[INFO] Running io.quarkus.reproducer.ModelWithBuilderResourceIT
Executing [/Users/rsvoboda/git/quarkus/integration-tests/jackson/service/target/quarkus-integration-test-jackson-service-999-SNAPSHOT-runner, -Dquarkus.http.port=8081, -Dtest.url=http://localhost:8081, -Dquarkus.log.file.path=target/quarkus.log]
2019-12-06 16:42:49,003 INFO  [io.quarkus] (main) quarkus-integration-test-jackson-service 999-SNAPSHOT (running on Quarkus 999-SNAPSHOT) started in 0.015s. Listening on: http://0.0.0.0:8081
2019-12-06 16:42:49,003 INFO  [io.quarkus] (main) Profile prod activated.
2019-12-06 16:42:49,003 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.868 s <<< FAILURE! - in io.quarkus.reproducer.ModelWithBuilderResourceIT
[ERROR] testModelWithBuilder  Time elapsed: 0.216 s  <<< ERROR!
java.lang.NullPointerException

[INFO] Running io.quarkus.reproducer.RegisteredPojoModelResourceIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0 s <<< FAILURE! - in io.quarkus.reproducer.RegisteredPojoModelResourceIT
[ERROR] testSimplePojoModel  Time elapsed: 0 s  <<< ERROR!
java.lang.NullPointerException

[INFO] Running io.quarkus.reproducer.ModelWithSerializerAndDeserializerOnFieldResourceIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.465 s - in io.quarkus.reproducer.ModelWithSerializerAndDeserializerOnFieldResourceIT
[INFO] Running io.quarkus.reproducer.InheritedModelWithBuilderResourceIT
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.003 s <<< FAILURE! - in io.quarkus.reproducer.InheritedModelWithBuilderResourceIT
[ERROR] testModelWithBuilder  Time elapsed: 0.003 s  <<< ERROR!
java.lang.NullPointerException
```

**Comment by rsvoboda** [comment] 2019-12-06 16:39
Ok, there is problem with CI, it's not executing sub-modules for jackson
https://github.com/quarkusio/quarkus/tree/master/integration-tests/jackson

https://dev.azure.com/quarkus-ci/quarkus/_build/results?buildId=13173&view=logs&jobId=c27ee6a9-ba10-582a-72b6-8a770e76588d

```
[INFO] ---------< io.quarkus:quarkus-integration-test-jackson-parent >---------
[INFO] Building Quarkus - Integration Tests - Jackson 999-SNAPSHOT        [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce) @ quarkus-integration-test-jackson-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ quarkus-integration-test-jackson-parent ---
[INFO] 
[INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-maven-version) @ quarkus-integration-test-jackson-parent ---
[INFO] 
[INFO] --- buildnumber-maven-plugin:1.4:create (get-scm-revision) @ quarkus-integration-test-jackson-parent ---
[INFO] Executing: /bin/sh -c cd '/home/vsts/work/1/s/integration-tests/jackson' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/vsts/work/1/s/integration-tests/jackson
[INFO] Storing buildNumber: 92fecad7316a2a744f1b816c0ddec2ff70b9620c at timestamp: 1575439519523
[WARNING] Cannot get the branch information from the git repository: 
Detecting the current branch failed: fatal: ref HEAD is not a symbolic ref

[INFO] Executing: /bin/sh -c cd '/home/vsts/work/1/s/integration-tests/jackson' && 'git' 'rev-parse' '--verify' 'HEAD'
[INFO] Working directory: /home/vsts/work/1/s/integration-tests/jackson
[INFO] Storing buildScmBranch: UNKNOWN
[INFO] 
[INFO] --- formatter-maven-plugin:2.8.1:validate (default) @ quarkus-integration-test-jackson-parent ---
[INFO] Using 'UTF-8' encoding to format source files.
[INFO] Number of files to be formatted: 0
[INFO] 
[INFO] --- impsort-maven-plugin:1.2.0:check (check-imports) @ quarkus-integration-test-jackson-parent ---
[INFO]  Total Files Processed: 0 in 00:00.015
[INFO]         Already Sorted: 0
[INFO]         Needed Sorting: 0
[INFO] 
[INFO] --- maven-source-plugin:3.0.1:jar-no-fork (attach-sources) @ quarkus-integration-test-jackson-parent ---
[INFO] 
[INFO] --- maven-install-plugin:2.5.2:install (default-install) @ quarkus-integration-test-jackson-parent ---
[INFO] Installing /home/vsts/work/1/s/integration-tests/jackson/pom.xml to /home/vsts/work/1/.m2/repository/io/quarkus/quarkus-integration-test-jackson-parent/999-SNAPSHOT/quarkus-integration-test-jackson-parent-999-SNAPSHOT.pom
[INFO] 
[INFO] -------------< io.quarkus:quarkus-integration-test-jsonb >--------------
[INFO] Building Quarkus - Integration Tests - JSON-B 999-SNAPSHOT         [2/3]
```

**Comment by rsvoboda** [comment] 2019-12-06 16:41
@misl / @geoand / @machi1990 can you take a look ?

**Comment by geoand** [comment] 2019-12-06 17:05
I'll take a look soon

**Comment by gsmet** [comment] 2019-12-06 17:31
if I follow @rsvoboda instructions, I have a NPE even in JVM mode.

**Comment by geoand** [comment] 2019-12-06 19:33
I've identified the issue and I'll have a PR shortly

**Comment by geoand** [comment] 2019-12-06 19:39
#5997 should take care of it

**Comment by misl** [comment] 2019-12-06 20:59
@geoand can you explain what you identified?

I see a lot of changes which look like refactoring to me, but I can not clearly see what actual root cause got solved. Was it CI or was it the testcases itself?

**Comment by geoand** [comment] 2019-12-06 21:03
The basic problem was a change I had introduced regarding retrieval of the ObjectMapper.

CI was also sort of misconfigured due to the fact that the project was a multi module project

**Comment by misl** [comment] 2019-12-06 21:04
BTW, multi module was actually by design. Initially I ran into issues with stuff missing when building native. Back then I created a reproducer which I later modified into these test cases. So I wonder if changing it into single module will actually reproduce the original case.

**Comment by geoand** [comment] 2019-12-06 21:09
I understand, but I am pretty sure that cases are being addressed now.
Furthermore I wanted this integration test to be similar to the others we have to keep things consistent.

**Comment by misl** [comment] 2019-12-06 21:28
It is good that you are confident, but I have my doubts. That tests still run fine is no guarantee that the actual code flow is exactly the same in case of single module. If I understood correctly in single module the Jackson annotated model classes will be indexed. In the multi module scenario they were not. So I wonder if the test scenario is still the same.

See #3652 for the original issue.

**Comment by geoand** [comment] 2019-12-06 21:35
One could argue that we should take the same approach for modules we have, but we haven't so far :).

If an issue arises that requires that we specifically use a multi-module test, we can always reconsider.

**Comment by gsmet** [comment] 2019-12-06 21:46
My understanding of the original issue is that multi module was not the issue. So I think we will be fine.

**Comment by misl** [comment] 2019-12-06 22:07
Indeed multi module was not the issue itself, but quote from #3562 `Both the model and builder are in a separate (reusable) jar library`. How to reproduce this separate jar library in a test case without using multi module?

Sorry for being persistent, but I am just worried that future changes might break things unnoticed.

Also it is a pity to see README gone for which I got a 100  ([see here](https://github.com/quarkusio/quarkus/pull/3688#discussion_r319566660))

**Comment by geoand** [comment] 2019-12-06 22:20
We can't of course guarantee that nothing will break, but we are pretty confident that the extension and the test cases are good.
Moreover from a maintenance perspective, having integration tests that are consistent across all extensions is a huge plus. The past month or so every time I looked at this integration test I was getting the feeling that it was a little odd due to module split. That coupled with the fact that the modules themselves didn't provide any apparent testing benefit (on the contrary they broke the scripts used to test all modules) led to me refactoring it.

**Closed** 2019-12-07 01:14 UTC
Labels: bug
