### ISSUE TITLE
Non-existing template variable not reported by Qute

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#14534] opened 2021-01-22 19:30 UTC
**Describe the bug**

I have a template declared like so:

```
    @CheckedTemplate
    public static class Templates {
        public static native TemplateInstance todos(List<Todo> todos, List<Integer> priorities, String filter, boolean filtered);
    }
```

In the template itself, I reference an undeclared variable:

```
{#for todo in todos123}
...
{/for}
```

The build succeeds despite this error; at runtime, this exception is raised:

```
Caused by: io.quarkus.qute.TemplateException: Loop section error in template TodoResource/todos.html on line 34: [todos123] resolved to [io.quarkus.qute.Results$Result] which is not iterable
	at io.quarkus.qute.LoopSectionHelper.extractIterator(LoopSectionHelper.java:86)
	at io.quarkus.qute.LoopSectionHelper.lambda$resolve$1(LoopSectionHelper.java:41)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1183)
```

**Expected behavior**

Build fails due to the undeclared variable todos123

**Actual behavior**

Build passes.

**To Reproduce**

Build https://github.com/gunnarmorling/quarkus-qute, modify _src/main/resources/templates/TodoResource/todos.html_ so it contains the invalid variable name, build, run and invoke localhost:8080/todos

**Environment (please complete the following information):**

Quarkus 1.11.0.Final

**Comment by mkouba** [comment] 2021-01-25 14:31
This works as designed, i.e. only those expressions that are referenced by [type-safe templates](https://quarkus.io/guides/qute-reference#typesafe_templates) or matched with a [parameter declaration](https://quarkus.io/guides/qute-reference#typesafe_expressions) are validated against the existing Java types. You can always pass additional data to a template instance.

We could probably add something like a "strict mode" that would disallow the usage of expressions that cannot be validated.

**Comment by mkouba** [comment] 2021-04-13 10:19
https://github.com/quarkusio/quarkus/pull/16466 should fix this issue, although it's not checking the undeclared variables. It merely validates that a template only contains expressions that can be validated at build time, i.e. the following template definition would not fail because `todos123` is bound to a parameter declaration:
```
{@org.acme.Todos todos123}
{#for todo in todos123}
...
{/for}
```

**Comment by mkouba** [comment] 2021-04-30 12:03
This should be resolved by https://github.com/quarkusio/quarkus/pull/16466.

**Closed by mkouba** 2021-04-30 12:03 UTC
Labels: area/qute, kind/enhancement
