### ISSUE TITLE
Jberet is missing in Quarkus bootstrap list

### ISSUE THREAD

**Issue by Rahamathulla** [quarkusio/quarkus#6804] opened 2020-01-16 10:15 UTC
**Description**
Jberet is missing in Quarkus bootstrap list. are they plans to add it here? is there any alternative given ?

**Comment by jmartisk** [comment] 2020-01-27 13:01
There is a feature request for it here: https://github.com/quarkusio/quarkus/issues/1505
I'm kinda working on it in my free time, haven't had too much progress yet though.

**Comment by gastaldi** [comment] 2020-01-27 13:11
Duplicate of #1505, please vote it in there if you're interested in it. Thanks!

**Closed by gastaldi** 2020-01-27 13:11 UTC
Labels: kind/extension-proposal
