### ISSUE TITLE
Ignore hidden OpenAPI schema properties for methods since v1.7.1

### ISSUE THREAD

**Issue by florianRieb** [quarkusio/quarkus#11712] opened 2020-08-28 12:52 UTC
In my TO's I have some methods to convert the object into entities. I don't want a field to be created for them in the api-yaml, so I use the@Schema annotation with hidden = true.
```java
  @JsonIgnore
  @Schema(hidden = true)
  public Incident getAsEntity() {  ... }
```

Today we have updated the version of quarkus to 1.7.1-Final and now there are fields for the methods in the yaml.
```yaml
        asEntity:
          $ref: '#/components/schemas/Incident'
```

**Expected behavior**

The expectation was that only fields was crated for @Schema annotated attributes and the fields with @Schema(hidden = true) also not present on the api-yaml

**Actual behavior**
Create fields on the api-yaml which annotated with @Schema(hidden = true)

**To Reproduce**
1. Create TO with some fields and methods annotate a method with @Schema(hidden = true)
2. Start the dev mode and open the open-api.yaml

**Configuration**
```properties

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   Linux fri-VBox 5.4.0-39-generic #43-Ubuntu SMP Fri Jun 19 10:28:31 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
   openjdk version "11.0.7" 2020-04-14
   OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
   OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)

 - Quarkus version or git rev: 1.7.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  Apache Maven 3.6.3
   Maven home: /usr/share/maven
   Java version: 11.0.7, vendor: GraalVM Community, runtime: /home/fri/.sdkman/candidates/java/20.1.0.r11-grl
   Default locale: en_US, platform encoding: UTF-8
   OS name: "linux", version: "5.4.0-39-generic", arch: "amd64", family: "unix"

**Comment by gsmet** [comment] 2020-09-01 15:41
@phillip-kruger @EricWittmann @radcortez if it's a regression in 1.7.1, we probably want to address this very soon (before September 8th).

**Comment by phillip-kruger** [comment] 2020-09-01 16:11
@florianRieb - from what version of Quarkus are you updating ? 1.7.0 or lower ?

**Comment by florianRieb** [comment] 2020-09-01 19:57
Yes from 1.7.0-Final

Phillip Krüger <notifications@github.com> schrieb am Di., 1. Sep. 2020,
18:12:

**Comment by phillip-kruger** [comment] 2020-09-02 07:00
Ok, This is the PR that broke (or fixed) this: 
https://github.com/smallrye/smallrye-open-api/pull/439

The reason (I think) that this is now showing up, it because the ignore is only on the get method. Try adding it to the field or also to the set method. 

Not adding it to the setter indicate that the field is still writeable (so it still needs to be in the schema). 

Let me know. If you believe the logic is wrong, please open an issue on https://github.com/smallrye/smallrye-open-api/issues
and we can discuss there.https://github.com/smallrye/smallrye-open-api/issues

Closing this as this is the current correct behaviour.

**Closed by phillip-kruger** 2020-09-02 07:00 UTC
Labels: kind/bug

**Comment by MikeEdgar** [comment] 2020-09-03 15:05
@phillip-kruger , i agree. Moving the hidden property to the field should fix it. If no setter exists that would be a change in smallrye to account for that. It is also misleading that the field in the schema is not identified as writeOnly. Adjusting for that would also be a good smallrye enhancement/fix.
