### ISSUE TITLE
quarkus-maven-plugin:create fails on Windows with IOException: Stream Closed

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#23093] opened 2022-01-21 13:28 UTC
### Describe the bug

Going through the new Camel Quarkus Workshop by @aldettinger on Windows.

### How to Reproduce?

1. Have a Windows machine
2. `git clone git@github.com:aldettinger/camel-quarkus-workshop.git` - not sure this is actually needed. I am just listing what I did
3. 'cd camel-quarkus-workshop' 
4.
```
C:\orgs\cq\camel-quarkus-workshop>mvn io.quarkus:quarkus-maven-plugin:2.6.1.Final:create
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] part-2-jvm-mode                                                    [jar]
[INFO] part-3-native-mode                                                 [jar]
[INFO] part-4-routes                                                      [jar]
[INFO] part-5-extensions                                                  [jar]
[INFO] part-6-eips                                                        [jar]
[INFO] prerequisites                                                      [pom]
[INFO]
[INFO] -----------------------< org.acme:prerequisites >-----------------------
[INFO] Building prerequisites 1.0.0-SNAPSHOT                              [1/6]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.6.1.Final:create (default-cli) @ prerequisites ---
Set the project groupId:
Set the project artifactId: part-1-dev-mode
Set the project version:
What extensions do you wish to add (comma separated list): platform-http
Would you like some code to start (yes), or just an empty Quarkus project (no): no
Exception in thread "main" java.io.IOError: java.io.IOException: Stream Closed
        at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:544)
        at org.apache.maven.shared.utils.logging.MessageUtils.doSystemUninstall(MessageUtils.java:101)
        at org.apache.maven.shared.utils.logging.MessageUtils.systemUninstall(MessageUtils.java:80)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.IOException: Stream Closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at org.fusesource.jansi.io.FastBufferedOutputStream.flushBuffer(FastBufferedOutputStream.java:58)
        at org.fusesource.jansi.io.FastBufferedOutputStream.flush(FastBufferedOutputStream.java:65)
        at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
        at org.fusesource.jansi.io.AnsiOutputStream.uninstall(AnsiOutputStream.java:338)
        at org.fusesource.jansi.AnsiPrintStream.uninstall(AnsiPrintStream.java:82)
        at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:541)
        ... 11 more

```

The above happens with both `cmd.exe` and PowerShell

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment 18.9 (build 11.0.13+8) OpenJDK 64-Bit Server VM 18.9 (build 11.0.13+8, mixed mode)

### Quarkus version or git rev

2.6.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 Maven 3.8.4

**Comment by ppalaga** [comment] 2022-01-21 13:38
Hm.. on the console, it looks like it just fails, but in reality, it actually created the project as expected.
BTW, the same issue with quarkus 2.6.3

**Comment by MrBattary** [comment] 2022-04-25 10:17
Same with the create-extension. 
And the same behavior: in the console script crashes, but in fact it works as expected.

```
~\Projects\project\application [BRANCHNAME +1 ~0 -0 !]> mvn io.quarkus:quarkus-maven-plugin:create-extension -DwithoutTests
OpenJDK 64-Bit Server VM warning: Ignoring option MaxPermSize; support was removed in 8.0
[INFO] Scanning for projects...
[INFO]
[INFO] ---------< my.project:application >---------
[INFO] Building application 2022.1.2.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:2.4.0.Final:create-extension (default-cli) @ portal-application ---
Set the extension my.project.extension
Set the extension id: filter-extension
Exception in thread "main" java.io.IOError: java.io.IOException: Stream Closed
        at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:544)
        at org.apache.maven.shared.utils.logging.MessageUtils.doSystemUninstall(MessageUtils.java:101)
        at org.apache.maven.shared.utils.logging.MessageUtils.systemUninstall(MessageUtils.java:80)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
Caused by: java.io.IOException: Stream Closed
        at java.base/java.io.FileOutputStream.writeBytes(Native Method)
        at java.base/java.io.FileOutputStream.write(FileOutputStream.java:354)
        at org.fusesource.jansi.io.FastBufferedOutputStream.flushBuffer(FastBufferedOutputStream.java:58)
        at org.fusesource.jansi.io.FastBufferedOutputStream.flush(FastBufferedOutputStream.java:65)
        at java.base/java.io.FilterOutputStream.flush(FilterOutputStream.java:153)
        at org.fusesource.jansi.io.AnsiOutputStream.uninstall(AnsiOutputStream.java:338)
        at org.fusesource.jansi.AnsiPrintStream.uninstall(AnsiPrintStream.java:82)
        at org.fusesource.jansi.AnsiConsole.systemUninstall(AnsiConsole.java:541)
        ... 11 more
```

**Comment by pissardl** [comment] 2022-06-08 06:43
Same issue with io.quarkus:quarkus-maven-plugin:2.9.2.Final , openjdk 11.0.2 , maven 3.8.5

**Comment by danilolopesabreu** [comment] 2022-07-02 14:30
same issue with mvn io.quarkus:quarkus-maven-plugin:2.10.1.Final:create, Apache Maven 3.8.4

**Comment by Schuppel1** [comment] 2022-11-21 17:13
Apache Maven 3.8.6
java version "11.0.17" 2022-10-18 LTS
graalvm-ce-java11-22.3.0

command
mvn -U io.quarkus:quarkus-maven-plugin:create

Still crashes same error

**Comment by gastaldi** [comment] 2024-08-28 00:07
Cannot reproduce with 3.14.0 and JDK 21 on Windows 11, closing

**Closed by gastaldi** 2024-08-28 00:07 UTC
Labels: kind/bug, area/maven, env/windows
