### ISSUE TITLE
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types:

### ISSUE THREAD

**Issue by arsen-papoyan** [quarkusio/quarkus#22647] opened 2022-01-05 12:35 UTC
### Describe the bug

Added bytebuddy dependency:

```xml
             <groupId>net.bytebuddy</groupId>
             <artifactId>byte-buddy</artifactId>
             <version>1.12.3</version>
```

Used this after initializing:
```java
    WebDriver driver = new Augmenter().augment(getWebDriver());
    DevTools devTools = ((HasDevTools) driver).getDevTools();
```

Step is:
```java
    public void clearBrowserCache() {
        devTools.createSession();
        devTools.send(Network.clearBrowserCache());
    }
```

### Actual behavior

If running on a local environment, everything is fine, but when running on a remote environment, in the case of clearBrowserCache step, the test is being failed and get this error:

```
 java.lang.ExceptionInInitializerError
 Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class com.sun.proxy.$Proxy12
 	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:486)
 	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:459)
 	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:356)
 	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:179)
```

### Output of `uname -a` or `ver`

Remote environment: Selenium Grid (standalone v4.1.0)

**Comment by geoand** [comment] 2022-01-05 13:29
Hi,

First of all thanks for reporting. However as you can certainly understand, there is almost no way anyone working on Quarkus can make an inch of progress with this issue due to severe lack of information. 
Specifically, there is almost no code provided, no context of how to reproduce the problem, no Quarkus version and certainly no example to try.

This might seem awkward, but put yourself in a maintainers shoes: If you were working on the project and across this GitHub issue (with obviously zero a-priori knowledge of the exact problem the reporter is reporting)  how would you fix it? The simple answer is you can't.

Presumably when you open an issue, you would like it to be fixed so you can go about your business and not have Quarkus get in your way. However in order to do that, when you report an issue you need to put in some effort to make it very easy for maintainers to understand the context, easily be able to reproduce the problem and test potential fixes.

Furthermore, when reporting an issue you must take into consideration that maintainers look at multiple issues per day (and have zero knowledge of the exact problem each issue describes), so there is very little time to try spend trying to decipher each one. The less time maintainers need to spend on deciphering the exact meaning of an issue, the more issues can be addressed and the better the Quarkus community as a whole is served.

**Comment by arsen-papoyan** [comment] 2022-01-05 14:04
@geoand Thank you for the reply.
I got you. 
But I ran many issues reported where there is even less information. 
After all, I can't post my whole project and describe the problem.
Also, I don't know if this problem is exactly related to the Quarkus or not, I just asked about it in another conversation and suggested me to open an issue. 
And in fact, I guess the problem is not needed a huge description.
I am using the DevTools protocol in my project which is built based on Selenium 4 (Java), and when I run my test on a remote environment (Selenium Grid v4), then when my test step reaches to the devtools action, the test fails and get an error.
That's it.

**Comment by arsen-papoyan** [comment] 2022-01-07 10:15
@geoand 
I found exactly where the problem comes from.
I'll try to explain in detail.
Is it okay to post the code in the comment section?

**Comment by geoand** [comment] 2022-01-07 10:41
Of course

**Comment by arsen-papoyan** [comment] 2022-01-07 11:07
**Project**: Maven
**Runner**: TestNG
**Remote**: Selenium Grid (selenium server 4.1.0)
**JavaSE 14**: version 16.0.1
**src/main/java folder**:

`public class Driver {
    public static void initDriver() {
        assertionMode = AssertionMode.SOFT;
        baseUrl = "https://www.google.com/";
        pageLoadStrategy = "eager";
        browser = "Chrome";
        pollingInterval = 500;
        holdBrowserOpen = false;
        savePageSource = false;
        fastSetValue = true;
        screenshots = false;
        remote = "remoteMachineUrl";
        driverManagerEnabled = true;
        headless = false;
        timeout = 10000;
        WebDriverRunner.addListener(new WebDriverEvent());
        open();
    }


public final class Util {
    public static WebDriver driver = new Augmenter().augment(getWebDriver());
    public static DevTools devTools = ((HasDevTools) driver).getDevTools();
}


public class WebDriverEvent implements WebDriverListener {
    @Override
    public void beforeClick(WebElement element) {
        WebDriverListener.super.beforeClick(element);
        System.out.println("Before Click");
    }
}
`

**src/testjava folder**:

`public class DevToolsTest {
    @Test
    public void devToolTest(){
        Driver.initDriver();
        open(baseUrl);
        Util.devTools.createSession();
        Util.devTools.send(Network.clearBrowserCache());
    }
}`

**pom xml**:

`<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>Draft</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.testng</groupId>
            <artifactId>testng</artifactId>
            <version>7.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.codeborne</groupId>
            <artifactId>selenide</artifactId>
            <version>6.1.2</version>
        </dependency>
        <dependency>
            <groupId>org.selenide</groupId>
            <artifactId>selenide-testng</artifactId>
            <version>1.0.0</version>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>net.bytebuddy</groupId>
            <artifactId>byte-buddy</artifactId>
            <version>1.12.6</version>
        </dependency>
    </dependencies>
</project>`

After running I get this error:

> java.lang.ExceptionInInitializerError
	at DevToolsTest.devToolTest(DevToolsTest.java:13)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
	at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
	at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
	at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
	at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
	at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.testng.TestRunner.privateRun(TestRunner.java:794)
	at org.testng.TestRunner.run(TestRunner.java:596)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
	at org.testng.SuiteRunner.run(SuiteRunner.java:276)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
	at org.testng.TestNG.runSuites(TestNG.java:1063)
	at org.testng.TestNG.run(TestNG.java:1031)
	at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
	at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
Caused by: java.lang.IllegalArgumentException: Cannot subclass primitive, array or final types: class jdk.proxy2.$Proxy10
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:490)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:463)
	at net.bytebuddy.ByteBuddy.subclass(ByteBuddy.java:360)
	at org.openqa.selenium.remote.Augmenter.augment(Augmenter.java:179)
	at Util.<clinit>(Util.java:10)

The problem is connected with the WebDriverEvent class, when I remove this class everything is okay.
But the problem is only arising in the case of running the test on the remote machine, when I run the test with the WebDriverEvent class in the local machine, everything is okay.

**Comment by geoand** [comment] 2022-01-07 18:51
Thanks for the investigation.

Quarkus does not support TestNG, so I am going to close this.

**Closed by geoand** 2022-01-07 18:52 UTC
Labels: kind/bug, needs-reproducer
