### ISSUE TITLE
HTTP Request to /metrics failed 

### ISSUE THREAD

**Issue by miladjafary** [quarkusio/quarkus#33323] opened 2023-05-12 08:21 UTC
### Describe the bug

Hi
I have used the dd-trace-java agent to trace my service which is developed on top of Quarkus framework.
However when DataDog agent try to create a trace a vertx request, the following exception is thrown. 
```
13:55:33 ERROR traceId=, spanId= [io.quarkus.vertx.http.runtime.QuarkusErrorHandler] (vert.x-eventloop-thread-7) HTTP Request to /metrics failed, error id: 6952b93b-71b0-447c-8e01-a0d9a637b874-1: java.lang.NullPointerException: Cannot invoke "datadog.trace.bootstrap.instrumentation.api.AgentSpan.setTag(String, java.lang.CharSequence)" because "span" is null
	at datadog.trace.bootstrap.instrumentation.decorator.http.HttpResourceDecorator.withRoute(HttpResourceDecorator.java:45)
	at datadog.trace.instrumentation.vertx_4_0.server.EndHandlerWrapper.handle(EndHandlerWrapper.java:33)
	at datadog.trace.instrumentation.vertx_4_0.server.EndHandlerWrapper.handle(EndHandlerWrapper.java:13)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:441)
	at io.vertx.core.http.impl.Http1xServerResponse.end(Http1xServerResponse.java:409)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.doHandle(PrometheusHandler.java:63)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.handle(PrometheusHandler.java:43)
	at io.quarkus.micrometer.runtime.export.handlers.PrometheusHandler.handle(PrometheusHandler.java:18)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

- I did not create any custom trace, I just use the DataDog agent along with open-tracing dependency. 
- I use the latest version of trace which I download it from https://dtdg.co/latest-java-tracer

### Expected behavior

Be able to trace the vertex library in DD. 

### Actual behavior

Throw an exception

### How to Reproduce?

1. Create a quarkus project with Kotlin  
2. Add the `quarkus-smallrye-opentracing`,`quarkus-micrometer-registry-prometheus` extension
3. Run the quarkus-app by using the `-javaagent:/dd-java-agent.jar` 
4. Hit the `http://localhost:8080/q/metric` 
5. The exception will be throws

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by geoand** [comment] 2023-05-12 08:22
cc @brunobat @radcortez

**Comment by brunobat** [comment] 2023-05-12 11:27
@miladjafary can you please provide a reproducer project?

**Comment by ebullient** [comment] 2023-05-12 11:51
Is the datadog tracing agent only for tracing? 
Is it expecting opentracing (retired) or opentelemetry?

It looks like the datadog agent is instrumenting vertx directly, which means it may have supplanted the vertx tracing handler (to my knowledge, there can be only one). Either that, or it is manipulating byte code to inject more than one, and things are happening out of order.

Why are you using the datadog agent for tracing? Can we switch to the Otel extension to get traces to datadog instead?

**Comment by miladjafary** [comment] 2023-05-12 14:33
@ebullient 

> Is the datadog tracing agent only for tracing?

Yes, datadog agent is used for tracing.

>Is it expecting opentracing (retired) or opentelemetry?

OpenTracnig  

> It looks like the datadog agent is instrumenting vertx directly, which means it may have supplanted the vertx tracing handler (to my knowledge, there can be only one). Either that, or it is manipulating byte code to inject more than one, and things are happening out of order.

Indeed, the datadog agent has integration with vertx. A full list could be found [here](https://docs.datadoghq.com/tracing/trace_collection/compatibility/java/#integrations). But, honestly I don't know how does it work. 

> Why are you using the datadog agent for tracing? Can we switch to the Otel extension to get traces to datadog instead?

Regarding the company policy I'm not allowed to use OTEL

**Comment by miladjafary** [comment] 2023-05-12 14:33
@brunobat I try to create a sample project for it

**Comment by geoand** [comment] 2023-05-29 10:38
@miladjafary were you able to come up with a sample project?

**Comment by geoand** [comment] 2023-06-02 09:39
Closing as we never got a reproducer

**Closed by geoand** 2023-06-02 09:39 UTC
Labels: kind/bug, area/smallrye, area/kotlin, area/metrics, triage/needs-reproducer
