### ISSUE TITLE
Uberjar JVM Mode - Override datasource properties

### ISSUE THREAD

**Issue by sniew** [quarkusio/quarkus#31027] opened 2023-02-09 08:41 UTC
### Description

Hi everyone.
For some customers i use quarkus in jvm mode, packaged in uber jar and deployed in production like desktop app and launched with command mode.
I have one uberjar and i could specialize database informations in config/application.yaml.
With quarkus 2.9 it is possible to override at runtime datasource properties but its not possible anymore in later version (2.12 for example)

Why is this not possible anymore ?
Is it possible to add a new config parameter to allow this for uber-jar and deployment in jvm mode ?
Is there another solution (i saw reaugmentation but its not possible with uber jar) ?
Is it possible to transform a mutable jar to uberjar with command mode ?

Configuration Example 

- jar embedded application.yaml :
 > datasource:
 >&nbsp; &nbsp;  persistence-unit:
 >&nbsp; &nbsp;&nbsp; &nbsp; db-kind: mssql
 >&nbsp; &nbsp;&nbsp; &nbsp;    jdbc:
 >&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;      ~: false
 > &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;     url: jdbc:sqlserver://localhost;databaseName=dummy

 - extern config file conf/application.yaml
 > datasource:
 >&nbsp; &nbsp;  persistence-unit:
 >&nbsp; &nbsp;&nbsp; &nbsp;    jdbc:
 >&nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;      ~: true
 > &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; &nbsp;     url: jdbc:sqlserver://host;databaseName=db

**Comment by geoand** [comment] 2023-02-13 08:05
cc @gsmet @yrodiere @Sanne

**Comment by yrodiere** [comment] 2023-02-13 08:48
Runtime properties should be overrideable when starting your application. If they are not, it's a bug.

To clarify, does this only happen with the uberjar packaging, and not in others?

Can you please provide a small reproducer?

**Comment by yrodiere** [comment] 2023-02-13 08:52
That being said, [quarkus.datasource.jdbc](https://quarkus.io/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc) is clearly a build-time property, and has been as far back as [Quarkus 2.7](https://quarkus.io/version/2.7/guides/datasource#quarkus-agroal_quarkus.datasource.jdbc) (probably more). Why are you trying to override that property? Is *that* the problematic property?

**Comment by sniew** [comment] 2023-02-13 10:07
The problematic property is quarkus.datasource.jdbc
At built-time quarkus.datasource.jdbc is false and i runtime through external config/application.yaml i override it to true.
My problem is that i don't know at build time how many datasources i will need so i configure in resources application.yaml X datasources which are disabled.
At runtime i configure many datasources and i enable only those datasources to avoid connections errors.

In jvm mode and uber jar i expect override this property quarkus.datasource.jdbc like i did before in quarkus 2.9


Here my default embedded application.yaml : [resources/application.yaml](https://github.com/quarkusio/quarkus/files/10721026/resources_application.txt)

Here my external production for runtime application.yaml in config directory : [config/application.yaml](https://github.com/quarkusio/quarkus/files/10721059/config_application.txt)

**Comment by Sanne** [comment] 2023-02-13 21:25
@sniew a build time property needs to be defined at build time.

It sounds like you have an highly dynamic application; I would suggest processing the build after the configuration is defined.
If you really can't do that (but I'd suggest thinking about that), and you need multiple combinations to be available after the build, you should build multiple different flavours of your application so you can choose which one to start at runtime. Alternatively enable all datasources and ensure only the ones you actually need get activated: you can have many datasources and have a little bit of custom logic to select the right datasources based on your own configuration.

I'll close this as it's not a bug; if you need more clarifications please start a conversation on the [chat](https://quarkusio.zulipchat.com/).

**Closed by Sanne** 2023-02-13 21:25 UTC
Labels: kind/bug, area/persistence, area/core, triage/needs-reproducer
