### ISSUE TITLE
CDI beans generated by kapt and gradle are not picked up in tests and cause `javax.enterprise.inject.UnsatisfiedResolutionException`

### ISSUE THREAD

**Issue by omarsahl** [quarkusio/quarkus#14555] opened 2021-01-24 13:47 UTC
**Describe the bug**
I'm using [MapStruct](https://mapstruct.org/) with gradle and kapt to genererate `Mappers` as injectable CDI beans.
The problem appears when I try to inject those mappers and run any test as it causes `javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type <Mapper> and qualifiers [@Default]` .
Running in dev mode (e.g. by running `quarkusDev`) works normally though. 

**Expected behavior**
I should be able to inject the mappers and run the tests without any errors.

**Actual behavior**
Tests fails with the exception: `javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type <Mapper> and qualifiers [@Default]`.

**To Reproduce**
Reproducer project: [map-struct-test-error.zip](https://github.com/quarkusio/quarkus/files/5862352/map-struct-test-error.zip)

1. Run the test inside of the `GreetingResourceTest` file in the attached reproducer project.

**Environment:**
 - Output of `ver`:
```
Microsoft Windows [Version 10.0.19042.746]
```
 - Output of `java -version`: 
```
java version "1.8.0_261"
Java(TM) SE Runtime Environment (build 1.8.0_261-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.261-b12, mixed mode)
```
 - Quarkus version or git rev: 
```
1.9.2.Final
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
------------------------------------------------------------
Gradle 6.5.1
------------------------------------------------------------

Build time:   2020-06-30 06:32:47 UTC
Revision:     66bc713f7169626a7f0134bf452abde51550ea0a

Kotlin:       1.3.72
Groovy:       2.5.11
Ant:          Apache Ant(TM) version 1.10.7 compiled on September 1 2019
JVM:          11.0.8 (Oracle Corporation 11.0.8+10-LTS)
OS:           Windows 10 10.0 amd64
```

**Comment by glefloch** [comment] 2021-01-24 19:27
@omarsahl, thanks for reporting this. 
I updated your reproducer to 1.10.5.Final and the test is ok. can you try with it?

**Comment by manovotn** [comment] 2021-01-25 05:33
Yea, had the same thought because I thought I saw this issue somewhere and I tried the reproducer with latest version(1.11.0.Final) - works fine.

**Comment by omarsahl** [comment] 2021-01-25 11:20
@glefloch, @manovotn Thanks for your help, I tried it with version `1.11.0.Final` and it works fine now.

**Comment by glefloch** [comment] 2021-01-25 12:34
Great. I close this issue then

**Closed by glefloch** 2021-01-25 12:34 UTC
Labels: area/arc, area/gradle, area/kotlin, env/windows, kind/bug
