### ISSUE TITLE
Native support fo java printing

### ISSUE THREAD

**Issue by dloiacono** [quarkusio/quarkus#13018] opened 2020-10-29 17:09 UTC
**Describe the bug**
I'm using the JAVA printer APIs.

The PrinterJob.lookupPrintServices() works fine with the JRE but doesn't work with native. 
Basically it doesn't return any printer.

I created an extension with a @Recorder to let the initialisation to work at application runtime and not a build time:

public void connectToServer(BeanContainer beanContainer) {
    PrintInteraction interaction = beanContainer.instance(PrintInteraction.class);
    interaction.init();
}
But it doesn't worked for me.

This is the init method:

public void init() {
    this.printers.putAll(Arrays.stream(PrinterJob.lookupPrintServices())
        .peek(printer -> log.info(String.format("Found printer: %s", printer.getName())))
        .collect(Collectors.toMap(PrintService::getName, Function.identity())));
}

**Expected behavior**
All the printers in the system are discovered.

**Actual behavior**
No printers are discovered when native application runs.

**To Reproduce**
Use this code:
public void init() {
    this.printers.putAll(Arrays.stream(PrinterJob.lookupPrintServices())
        .peek(printer -> log.info(String.format("Found printer: %s", printer.getName())))
        .collect(Collectors.toMap(PrintService::getName, Function.identity())));
}

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin NMOL538577.local 19.6.0 Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  openjdk version "15" 2020-09-15
OpenJDK Runtime Environment AdoptOpenJDK (build 15+36)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15+36, mixed mode, sharing)
 - GraalVM version (if different from Java): openjdk version "11.0.8" 2020-07-14
OpenJDK Runtime Environment GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03)
OpenJDK 64-Bit Server VM GraalVM CE 20.2.0 (build 11.0.8+10-jvmci-20.2-b03, mixed mode, sharing)
 - Quarkus version or git rev: 1.9.1-Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/user/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 15, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-15.jdk/Contents/Home
Default locale: en_IT, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

**Additional context**
(Add any other context about the problem here.)

**Comment by gastaldi** [comment] 2020-10-29 17:23
Duplicate of #13017. Closing

**Closed by gastaldi** 2020-10-29 17:23 UTC
Labels: kind/bug, triage/duplicate
