### ISSUE TITLE
Kotlin module works wrong in Intellij IDEA

### ISSUE THREAD

**Issue by max-grigoriev** [quarkusio/quarkus#15359] opened 2021-02-27 21:32 UTC
**Describe the bug**

```
"".trim()
```
such code is red in IDEA but the build is OK.
IDEA shows such error: `Unresolved reference: trim`
And the same behavior with all string functions.

if I comment `implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))` in `build.gradle.kts` then `String` functions are returned.

**Expected behavior**
String functions should be known.

**Actual behavior**
 
IDEA doesn't know about `String` functions.

**To Reproduce**

1.  Generate Kotlin and Gradle (Kotlin dsl) project using Quarkus initializer.
2. Open in IDEA
3. Try to call any string function.

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin Maksyms-MacBook-Pro.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
 - Quarkus version or git rev: 1.12.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.8
 - IDEA: IntelliJ IDEA 2020.3.2 (Ultimate Edition)

**Comment by glefloch** [comment] 2021-02-28 09:26
Hi @max-grigoriev, I just tested it and I'm not able to reproduce it. I generate a project from `code.quarkus.io` and selected `gradle kotlin DSL` and `kotlin` as extension. Did you do something else?

**Comment by max-grigoriev** [comment] 2021-02-28 11:40
@glefloch No, I did just these simple steps. Here's [this repository](https://github.com/max-grigoriev/code-with-quarkus)
I use the latest IDEA and Kotlin plugin (203-1.4.31-release-IJ7148.5)
<img width="806" alt="kotlin-plugin" src="https://user-images.githubusercontent.com/691931/109417032-819f7d80-79ca-11eb-970a-b3f9ffa0ee13.png">
<img width="1305" alt="no-trim" src="https://user-images.githubusercontent.com/691931/109417034-8401d780-79ca-11eb-8a43-61ab7805c194.png">

**Comment by belu** [comment] 2021-02-28 12:25
@max-grigoriev 
I am not able to reproduce this issue. Not with your repository and not with a sample project from code.quarkus.io directly (Gradle Kotlin DSL + Kotlin extension).

**Comment by max-grigoriev** [comment] 2021-02-28 15:49
I tried with the latest IDEA EAP and it works OK.

**Comment by glefloch** [comment] 2021-02-28 16:55
If everything is ok I close the issue then.

**Closed by glefloch** 2021-02-28 16:55 UTC
Labels: area/kotlin, kind/bug
