### ISSUE TITLE
Kotlin: Make installMockForType work for @RegisterRestClient Beans

### ISSUE THREAD

**Issue by alkuit** [quarkusio/quarkus#14515] opened 2021-01-22 12:23 UTC
**Describe the bug**
When using Kotlin, JUnit and MockK (and not mockito), `@RegisterRestClient` Beans cannot be mocked with `installMockForType`.

```
@QuarkusTest
class CountryServiceIntTest {

    companion object {
        @RestClient
        val countryAccessor: CountryAccessor = mockk()
        @BeforeAll
        @JvmStatic
        fun setupMocks() {
            QuarkusMock.installMockForType(countryAccessor, CountryAccessor::class.java)
        }
    }

    @Inject
    @field: Default
    lateinit var countryService: CountryService

    @Test
    fun `should mock the accessor`() {
        every { countryAccessor.getByName("greece") } returns setOf(Country())
        countryService.getCountryByName("greece")
    }
}
```

**Expected behavior**
Mocking should work for `@RegisterRestClient` Beans with `installMockForType`.

**Actual behavior**
Mocking does not work, fails with exception:
```
No bean found for required type [interface org.acme.CountryAccessor] and qualifiers [[]]
javax.enterprise.inject.UnsatisfiedResolutionException: No bean found for required type [interface org.acme.CountryAccessor] and qualifiers [[]]
```
	
**To Reproduce**
Link to sample: https://github.com/alkuit/quarkus-mockk

1. Clone the repository
2. Execute `CountryServiceIntTest.kt`

**Environment (please complete the following information):**
 - Output of `java -version`: openjdk version "11.0.8" 2020-07-14
 - Quarkus version: 1.11.0.Final

**Comment by glefloch** [comment] 2021-01-29 13:01
Thanks for reporting this @alkuit. I can reproduce the error. 

@geoand, is this a limitation of `QuarkusMock` ? Looking at the documentation, it works with `quarkus-test-junit5-mockito`  and `@InjectMock` (https://quarkus.io/blog/mocking/#using-injectmock), and this module doing more stuff than `QuarkusMock` ?

**Comment by geoand** [comment] 2021-01-29 14:33
Does  https://quarkus.io/blog/mocking/#using-injectmock-with-restclient help?

**Comment by glefloch** [comment] 2021-01-29 15:04
yes, I tried moving from `mockk` to `mockito` with `quarkus-junit5-mockito` and it works.

**Comment by geoand** [comment] 2021-01-29 15:27
👍🏼 

So this ticket essentially becomes as request to support `mockk`, right?

**Comment by glefloch** [comment] 2021-01-29 15:43
Well yes, I was planning to create a module outside of quarkus (in quarkiverse) to add this support. But as mention in the doc, `QuarkusMock` is not tied to mockito. So I was wondering if it was a bug, or if needed to be supported which seems to be the case.

**Comment by geoand** [comment] 2021-01-29 15:51
I guess you are right, I didn't really look at the code in the example.

**Comment by csh0711** [comment] 2021-02-08 19:46
**Side note or just to let you know:** 
We (@alkuit is a colleague of mine) created a blog post about testing Quarkus with Kotlin/MockK in general: https://www.novatec-gmbh.de/en/blog/testing-quarkus-with-kotlin-junit-and-mockk/

As the most "official" examples are mainly Java-based this could be helpful for Kotlin developers starting with Quarkus.

**Comment by glefloch** [comment] 2021-02-20 14:20
@csh0711, @alkuit, nice article! 
FTR I started working a quarkus extension for MockK. This allows you to write: 

````

@QuarkusTest
class CountryServiceIntTest {
    @InjectMock    
    @RestClient
    lateinit var countryAccessor: CountryAccessor
 
    @Inject
    @field: Default
    lateinit var countryService: CountryService

    @Test
    fun `should mock the accessor`() {
        every { countryAccessor.getByName("greece") } returns setOf(Country())
        countryService.getCountryByName("greece")
    }
}
````

You can find more information  here: https://github.com/quarkiverse/quarkus-mockk

If this is ok for you, I think we can clsose this issue?

**Comment by csh0711** [comment] 2021-02-22 21:48
@glefloch Thanks for your reply!
Your extension looks really promising to me. My trivial test with the example from the Blog Post works nicely.

I think as soon as @alkuit confirms that his issue with the RestClient works as well we are fine.

Just curious: As this extension is still in v0.2.0 - will it be developed and maintained in the future?

Btw. I created a small pull request in your GitHub repo. :-)

**Comment by alkuit** [comment] 2021-02-23 06:10
Just tested it, works like a charm. Thank you!

**Comment by geoand** [comment] 2021-02-23 06:22
Thanks folks!

I'll close this issue as fixed

**Closed by geoand** 2021-02-23 06:22 UTC
Labels: area/kotlin, area/testing, kind/enhancement
