### ISSUE TITLE
QuarkusTest throws exceptions when having parameters in test function

### ISSUE THREAD

**Issue by AlexLi-Monster** [quarkusio/quarkus#8703] opened 2020-04-20 14:37 UTC
**Describe the bug**
When having a test function with parameters injected, QuarkusTest throws `java.lang.IllegalArgumentException: argument type mismatch` exception

**Expected behavior**
Maybe it should work with parameters injected.

**Actual behavior**
```argument type mismatch
java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:433)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:334)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
```

**To Reproduce**
Steps to reproduce the behavior, simple reproduce test below:
In order to use [`VertxExtension`](https://vertx.io/docs/vertx-junit5/java/), I need to inject `VertxTestContext` in my test function:
```
@ExtendWith(VertxExtension::class)
@QuarkusTest
class simpleTest {
    @Test
    fun myTest(vertxTestContext: VertxTestContext) {
           testContext.verify { }
     }
}
```
I can create a new instance of `VertxTestContext` in the test, but will lost the benefit of its context and need to do some workaround to verify the test etc.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Darwin Kernel Version 19.4.0`
 - Output of `java -version`: `openjdk version "11.0.6" 2020-01-14`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `io.quarkus:quarkus-bom:1.3.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  `6.0.1`
 - Vertx-junit5 version: `3.8.5`

**Comment by geoand** [comment] 2020-04-20 14:47
This is essentially a duplicate of #8251

**Closed** 2020-05-18 08:05 UTC
Labels: kind/bug
