### ISSUE TITLE
quarkus-keycloak-admin-client-reactive does not getAuthorizationSettings

### ISSUE THREAD

**Issue by bigglesandginger** [quarkusio/quarkus#31086] opened 2023-02-10 18:30 UTC
### Describe the bug

When using a Keycloak client configured with Authorization (there are two Resources, two Scopes, and two Permissions configured, viewable in the Keycloak UI, and work with the `@Authenticated` annotation), the admin-client fails to extract the AuthorizationSettings, simply returning NULL.

```
        List<ClientRepresentation> clients = keycloak.realm("realmname").clients().findByClientId("clientname");
        ClientRepresentation appClient = clients.get(0);
        if (appClient.getAuthorizationServicesEnabled()) {
            ResourceServerRepresentation authz = appClient.getAuthorizationSettings();
            List<ResourceRepresentation> resources = authz.getResources();  // <--- Fails with NPE
            return resources;
        }
```

### Expected behavior

I am expecting that `ClientRepresentation.getAuthorizationSettings()` returns a usable `ResourceServerRepresentation` object.

### Actual behavior

```
java.lang.NullPointerException: Cannot invoke "org.keycloak.representations.idm.authorization.ResourceServerRepresentation.getResources()" because "authz" is null
	at software.uncharted.RolesResource.getPermissions(RolesResource.java:40)
	at software.uncharted.RolesResource$quarkusrestinvoker$getPermissions_63cdc876fbca54bedb90a9e84f307b6ccb49314b.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:114)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

To reproduce I am using the example found here: https://quarkus.io/guides/security-keycloak-admin-client and simply changing the getRoles function to a getPermissions function with the code above.  However, one needs a Keycloak with Authorization permissions set up.

Here is a `testrealm.json` with two permissions: https://gist.github.com/bigglesandginger/78500e9de2ee4298c8640a61dcba6bf1

### Output of `uname -a` or `ver`

Darwin Typhoon.local 22.2.0 Darwin Kernel Version 22.2.0: Fri Nov 11 02:03:51 PST 2022; root:xnu-8792.61.2~4/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "18.0.2.1" 2022-08-18

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by sberyozkin** [comment] 2023-02-10 18:53
@bigglesandginger I see you work with `2.12.3.Final`. Can you try the latest `2.16.1.Final` - what might be happening here is that ClientRepresentation is a subresource and I believe something was fixed about it earlier. If it does not help - please upload a realm to your reproducer with the configured permissions so that it can be tested quicly

**Comment by bigglesandginger** [comment] 2023-02-10 20:00
I update Quarkus to 2.16.2.Final, but that did not work, so I added a realm file to the Reproduce section (replicated here for clarity: https://gist.github.com/bigglesandginger/78500e9de2ee4298c8640a61dcba6bf1)

**Comment by sberyozkin** [comment] 2023-02-11 11:53
@bigglesandginger Thanks, I'll try to test sometime next week, if you could experiment a bit more since you already have everything set up then it would be great. Specifically, can you try to capture the traffic between the admin client and Keycloak leading to this NPE. Example, if the Keycloak port is 8180, then update the Quarkus code to use for 8280 and have a trace utility routing to 8180. 
That will let verify if the request URI have been structured correctly, if Keycloak has been configured correctly and the expected data are returned

**Comment by sberyozkin** [comment] 2023-02-11 11:57
@geoand Hey, I recall awhile back you did some work on the HTTP tracing support natively in Quarkus, not sure it would be possible to enable it for RestEasy Reactive client ?

**Comment by geoand** [comment] 2023-02-13 07:18
Hi, that stuff did not end up getting merged, however we do have https://quarkus.io/guides/rest-client-reactive#logging-traffic

**Comment by sberyozkin** [comment] 2023-02-13 11:24
Cool, that is very easy as well

**Comment by geoand** [comment] 2023-02-13 11:29
💪🏼

**Comment by bigglesandginger** [comment] 2023-02-13 12:43
I ran the process again with Wireshark sniffing the traffic and the response from the Keycloak server (I assume from the call `clients.get(0)` is https://gist.github.com/bigglesandginger/912592a7643601b73198bf9af3518813

In which one can see that `"authorizationServicesEnabled": true,` (which I think is the setting to use to enable the whole Permission aspect of Keycloak).

**Comment by bigglesandginger** [comment] 2023-02-13 12:46
> 

WIth regards to the rest-client logging, I found the documented `quarkus.rest-client.logging.body-limit` setting is hard-coded to 100 - the example of 50 and any other value I chose (500, 5000) did not produce a different number of characters).

**Comment by sberyozkin** [comment] 2023-02-13 13:38
@bigglesandginger Thanks, I don't see anything in that JSON that would satisfy 

`ResourceServerRepresentation authz = appClient.getAuthorizationSettings();`, `ClientRepresentation` is a bean, `appClient.getAuthorizationSettings()` returns whatever related was returned in `ClientRepresentation`. So Keycloak does not return this info

**Comment by bigglesandginger** [comment] 2023-02-13 14:12
So then the question is, what populates that?  I don't know where to find the code to read, as the JavaDocs do not seem to describe this, though would be wonderful if there were examples in the JavaDocs.

**Comment by sberyozkin** [comment] 2023-02-13 14:28
@bigglesandginger It has to be resolved at the Keycloak level, Quarkus can not affect it. Please open a Keycloak discussion https://github.com/keycloak/keycloak/discussions, please let the team know how you configured the realm, and show the response captured by Wireshark confirming no authorization settings are returned, please CC me there.
Let me close this issue now
Thanks

**Comment by bigglesandginger** [comment] 2023-02-13 14:45
@sberyozkin I posted the question over on Keycloak: https://github.com/keycloak/keycloak/issues/17042 - I am not certain if I included you correctly.

**Comment by sberyozkin** [comment] 2023-02-13 15:01
@bigglesandginger Thanks, added my comment in https://github.com/keycloak/keycloak/issues/17042, lets continue there

**Closed by sberyozkin** 2023-02-13 15:01 UTC
Labels: kind/bug, area/keycloak

**Comment by sberyozkin** [comment] 2023-02-14 11:41
Just adding a link to Pedro's answer, https://github.com/keycloak/keycloak/issues/17042#issuecomment-1428432930
