### ISSUE TITLE
[Regression] UnresolvedElementException: Discovered unresolved field during parsing

### ISSUE THREAD

**Issue by wiradikusuma** [quarkusio/quarkus#18293] opened 2021-07-01 05:09 UTC
## Describe the bug
I have a hierarchy of model classes:

```
@MappedSuperclass
@JsonFilter("sanitize-secret")
public class WithCode extends PanacheEntity {
	@Column(unique = true, nullable = false, length = 100)
	public String code;
}

@MappedSuperclass
public class WithCodeAndName extends WithCode {
	public String name;
}

@Entity
public class Foo extends WithCodeAndName {
	public String address;
}

// Normal class, not Entity
public class ExtendedFoo extends Foo {
	@Transient
	public int age;
}
```

It compiles perfectly to native with version `1.12.1.Final`. Ugrading to `2.0.0.Final` breaks native compilation:

```
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved field during parsing: com.app.api.model.ExtendedFoo.code. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing field is then reported at run time when it is accessed the first time.
Trace: 
        at parsing com.app.model.Foo.lambda$postLoad$2(Foo.java:102)
Call path from entry point to com.app.model.Foo.lambda$postLoad$2(FooAnotherClass): 
        at com.app.model.Foo.lambda$postLoad$2(Foo.java:99)
        at com.app.model.Foo$$Lambda$2045/0x00000007c2636040.apply(Unknown Source)
        at sun.security.ec.XECParameters$1.get(XECParameters.java:183)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:211)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:164)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:293)
 ```

### Expected behavior
Compiling to native code using `2.0.0.Final`should work.

### Actual behavior
Upgrading to `2.0.0.Final` breaks native compilation.

### Output of `uname -a` or `ver`
Darwin twmbp.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`
OpenJDK Runtime Environment GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev
2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/wiradikusuma/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/wiradikusuma/.sdkman/candidates/java/21.0.0.r11-grl
Default locale: en_ID, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by geoand** [comment] 2021-07-01 08:49
Hi,

can you please attach a reproducer project?

**Comment by Adelrisk** [comment] 2021-07-23 09:30
I also experienced this. My workaround: refactor the public fields into private fields with getters/setters.

The decisive combination seems to be:
- public field `parentField` in a class with `@MappedSuperclass` (extending `PanacheEntity` is not required)
- child class `ChildEntity` with `@Entity`
- given an instance of the child, access the public fields declared in the parent class.

This access will break during the native compilation with the above exception `[...] Discovered unresolved field during parsing: ChildEntity.parentField [...]`

**Comment by FroMage** [comment] 2021-07-26 10:02
Which version of Quarkus and native-image are you using? Can you share a reproducer? It works for me with GraalVM 20.3.1 and Quarkus 2.0.3.Final with this code:

```java
@MappedSuperclass
public class ParentEntity extends PanacheEntity {
//    @GeneratedValue
//    @Id
//    public Long id;
    public String name;
}

@Entity
public class ChildEntity extends ParentEntity {
    public String other;
}

@Path("/hello")
public class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        ChildEntity entity = new ChildEntity();
        System.err.println(entity.id);
        System.err.println(entity.name);
        System.err.println(entity.other);
        ParentEntity p = entity;
        System.err.println(p.id);
        System.err.println(p.name);
        return "Hello RESTEasy Reactive";
    }
}
```

Both with and without `extends PanacheEntity`.

**Comment by geoand** [comment] 2021-09-30 06:59
Is this still an issue with the latest Quarkus versions?

**Comment by geoand** [comment] 2021-11-09 08:50
Closing as we have no received any updates.

Feel free to comment or reopen if it's still an issue.

**Closed by geoand** 2021-11-09 08:50 UTC
Labels: kind/bug, area/panache, needs-reproducer
