### ISSUE TITLE
Resource are not filtered when they are replaced in quarkusDev with gradle

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#18448] opened 2021-07-06 12:04 UTC
## Describe the bug
I have the following task in my build.gradle:
```
processResources {
  filter(ReplaceTokens, tokens: [
    "token1": project.property("token1"),
    "token2": project.property("token2"),
  ])
}
```
It is working fine, however when I modify my application.yml lwhile the dev mode is running, I face the following exception:
```
Failed to start quarkus: java.lang.RuntimeException: while scanning for the next token
found character '@' that cannot start any token. (Do not use @ for indentation)
 in 'reader', line 15, column 13:
        secret: @token1@
```
### Expected behavior

application.yml is filtered during hot reload

### Actual behavior

application.yml is replaced without filtering

### Output of `java -version`
15.0.1

### Quarkus version or git rev

2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1

## Additional context
(Add any other context about the problem here.)

**Comment by glefloch** [comment] 2021-07-07 11:41
Thanks for reporting this @rmanibus. 

When changes are detected by quarkus in dev mode, it does not rely on the build tool to process resources and compile classes. It copy/paste resources and compile manually classes.  

I don't think this would be possible. WDYT @aloubyansky ?

**Comment by aloubyansky** [comment] 2021-07-07 11:51
Right, it's not a bug. It was a design decision. We don't have the necessary integration with the underlying build tools (Maven/Gradle) for that to happen at the moment. Currently we are not looking to do anything about that, unfortunately.

**Comment by rmanibus** [comment] 2021-07-07 12:09
Ok, I understand, what solution do you advise to provide credentials to the application in dev mode ? I used to provide them to the application.properties with maven or gradle filtering, I would like to avoid having to set them as environment variable ! I would love to have something like dot env in javascript !

**Comment by rmanibus** [comment] 2021-07-07 12:12
now that I say it, I could implement a [java dotenv](https://github.com/cdimascio/dotenv-java) [credentials-provider](https://quarkus.io/guides/credentials-provider)

**Comment by aloubyansky** [comment] 2021-07-07 12:20
Simply adding `.env` to your app's module dir should work.

**Comment by rmanibus** [comment] 2021-07-07 12:22
Thank's I missed that one !

**Comment by aloubyansky** [comment] 2021-07-07 12:25
Yes, let's close this one for now.

**Closed by aloubyansky** 2021-07-07 12:25 UTC
Labels: area/gradle, kind/bug
