### ISSUE TITLE
Hibernate cannot track changes of primitive boolean value

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#3261] opened 2019-07-17 15:56 UTC
**Describe the bug**
Given an entity with a single boolean attribute and a key (an EmbeddedId in my test-case), the changes are tracked only if you change from false to true, instead changing from true to false is not persisted.

As a workaround I shifted to Boolean and it works.

I investigated and the generated method is done this way:
```java
    public void $$_hibernate_write_abilitata(boolean var1) {
        if (var1 - this.abilitata != 0) {
            this.$$_hibernate_trackChange("abilitata");
        }

        if (this.$$_hibernate_getInterceptor() != null) {
            this.abilitata = this.$$_hibernate_getInterceptor().writeBoolean(this, "abilitata", this.abilitata, (boolean)var1);
        } else {
            this.abilitata = (boolean)var1;
        }
    }

```
and I don't know how the JVM works with the bytecode that is decompiled that way (boolean cannot be subtracted), with the values in the stack and the OpCode.ISUB. 

**Expected behavior**
The JPA Provider should update in both case

**Actual behavior**
Only changes to true are persisted

**To Reproduce**
1. mvn install the attached test-case
2. see the two test, one with false, one with true
3. the one that starts with true fails

**Configuration**
```properties
# H2 Database in memory
quarkus.datasource.url: jdbc:h2:mem:testdb
quarkus.datasource.driver: org.h2.Driver
quarkus.datasource.username: sa
quarkus.datasource.password:

quarkus.hibernate-orm.database.generation=drop-and-create

quarkus.hibernate-orm.log.sql: true
```

**Environment (please complete the following information):**
 - Darwin WMICTLM1P.local 18.6.0 Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.0.2 (build 25.212-b03-jvmci-19-b04, mixed mode)
 - Quarkus version or git rev: 0.19.1

[test-case.zip](https://github.com/quarkusio/quarkus/files/3402721/test-case.zip)

**Comment by jaikiran** [comment] 2019-10-18 07:46
This most likely looks like a core Hibernate issue, than Quarkus. Perhaps @Sanne would know?

**Comment by dreab8** [comment] 2019-10-19 06:44
I may be wrong but it seems that the marshalling/unmarshalling process interferes in some way with the hibernate inline dirty tracking mechanism.

**Comment by dreab8** [comment] 2019-10-19 07:36
probably this issue is related to https://github.com/quarkusio/quarkus/issues/2815

**Comment by dreab8** [comment] 2019-10-21 12:00
It seems we have this issue every time we change a property to its type default value, when the entity is unmarshalled the value of `$$_hibernate_tracker` is null and the inline dirty track mechanism fails to detect the change.

**Comment by hpopov** [comment] 2022-05-21 09:56
The same happened to me with Hibernate, outside of Quarkus. Used `org.hibernate:hibernate-core:jar:5.4.21.Final` over Spring Boot version `2.3.4.RELEASE`. Whenever an entity changes single primitive attribute from `false` to `true`, it gets persisted (update query is issued), but not the vise versa (with primitive boolean attribute changed from `true` to `false`)

**Comment by gsmet** [comment] 2022-05-21 10:00
@Sanne do you know if this one was fixed in recent ORM releases?

**Comment by hpopov** [comment] 2022-05-21 10:49
> The same happened to me with Hibernate, outside of Quarkus. Used `org.hibernate:hibernate-core:jar:5.4.21.Final` over Spring Boot version `2.3.4.RELEASE`. Whenever an entity changes single primitive attribute from `false` to `true`, it gets persisted (update query is issued), but not the vise versa (with primitive boolean attribute changed from `true` to `false`)

Sorry, guys, I deceived you accidentally. That was not the case: my Booleaans were all wrappers, not primitives, the mistake was rather on my side.

**Comment by Sanne** [comment] 2022-05-23 08:40
> @Sanne do you know if this one was fixed in recent ORM releases?

I don't know for sure but I suspect it's still an issue - when we looked at it, this was mostly caused by a Jackson integration flaw and would only manifest such a problem when exposing directly entities to endpoints and lettting Jackson serialize them and transparently re-merge them within long spanning transactions: a pattern we don't encourrage nor support.

We discussed possible solutions with the team and came to the conclusion that we can workaround it in theory but it requires extensive re-thinking of the bytecode enhancement code, something I'd prefer not doing on ORM version 5.x.  In the meantime I suggest avoiding Jackson / ORM patterns like this.

**Comment by geoand** [comment] 2023-04-11 10:26
@Sanne any chance this has been fixed in ORM 6?

**Comment by geoand** [comment] 2024-09-20 06:30
@yrodiere should we close this as `won't fix`?

**Comment by yrodiere** [comment] 2024-09-24 10:41
Upgrading the test case to 3.14 solves the issue. New test case: 
[test-case-3-14.zip](https://github.com/user-attachments/files/17113220/test-case-3-14.zip)


Before:

```
[ERROR] Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.974 s <<< FAILURE! - in org.acme.quickstart.TestCaseTest
[ERROR] testKo  Time elapsed: 0.944 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <false> but was: <true>
        at org.acme.quickstart.TestCaseTest.testWithValue(TestCaseTest.java:39)
        at org.acme.quickstart.TestCaseTest.testKo(TestCaseTest.java:24)
```

After:

```
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 5.224 s -- in org.acme.quickstart.TestCaseTest
2024-09-24 12:38:32,143 INFO  [io.quarkus] (main) quarkus stopped in 0.017s
```

I do not know when this was fixed, but considering the original test case used Quarkus 0.9, I say let's close this as obsolete.

**Closed by yrodiere** 2024-09-24 10:41 UTC
Labels: kind/bug, area/persistence, triage/upstream, area/hibernate-orm, pinned
