### ISSUE TITLE
[Solved in 1.3.0] Quarkus Scheduler doesn't log RuntimeExceptions

### ISSUE THREAD

**Issue by canidae** [quarkusio/quarkus#6759] opened 2020-01-24 09:32 UTC
**Describe the bug**
Quarkus Scheduler doesn't log RuntimeExceptions.

**Expected behavior**
RuntimeException logged.

**Actual behavior**
RuntimeException is not logged.

**To Reproduce**
1. Create Quarkus project with extension "quarkus-scheduler".
2. Create a task that throws a RuntimeException, for example:
```
    @Scheduled(every = "1m")
    public void name() {
        System.out.println("Scheduled task started");
        if (true) throw new UnsupportedOperationException("This exception is not logged");
        System.out.println("This is never printed");
    }
```
3. mvn quarkus:dev
4. Observe that exception is not logged.

**Environment**
 - Linux chihiro 5.4.13-arch1-1 #1 SMP PREEMPT Fri, 17 Jan 2020 23:09:54 +0000 x86_64 GNU/Linux
 - openjdk version "11.0.6" 2020-01-14
   OpenJDK Runtime Environment (build 11.0.6+10)
   OpenJDK 64-Bit Server VM (build 11.0.6+10, mixed mode)
 - Quarkus 1.1.1.Final

**Comment by jaikiran** [comment] 2020-02-07 14:25
Hello @canidae, can you try this with `1.3.0-Alpha1` of Quarkus. It logs this exception when I tried it on that version:

```
Scheduled task started
2020-02-07 19:54:20,006 ERROR [io.qua.sch.run.SimpleScheduler] (executor-thread-1) Error occured while executing task for trigger IntervalTrigger [id=0_org.acme.ExampleResource_ScheduledInvoker_greet_c65e98765c20bed77f6d2a561466783b7679975a, interval=60000]: java.lang.UnsupportedOperationException: This exception is not logged
	at org.acme.ExampleResource.greet(ExampleResource.java:20)
	at org.acme.ExampleResource_ScheduledInvoker_greet_c65e98765c20bed77f6d2a561466783b7679975a.invokeBean(ExampleResource_ScheduledInvoker_greet_c65e98765c20bed77f6d2a561466783b7679975a.zig:45)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.scheduler.runtime.SimpleScheduler$2.run(SimpleScheduler.java:123)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:224)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```
If you can still reproduce it on that version, please add relevant details or share an application (preferably as a github repo) to reproduce the issue.

**Comment by canidae** [comment] 2020-02-11 09:26
1.3.0.Alpha1, and presumably 1.3.0.Final once released fixes this issue.
This issue is not listed in the [release log](https://github.com/quarkusio/quarkus/releases), sa of such I'm leaving the issue open. Feel free to close this issue whether you want it to be listed in the release log or not.

**Comment by machi1990** [comment] 2020-02-18 11:35
@canidae 1.3.0.Alpha2 has been released. Can you test it and see if the issue is also fixed there? Also, closing now, this can been re-opened if it is not the case.

**Closed by machi1990** 2020-02-18 11:35 UTC
Labels: area/scheduler, kind/bug
