### ISSUE TITLE
Openshift extension fails to deploy when on RHEL

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#34276] opened 2023-06-23 12:21 UTC
### Describe the bug

I have an application(resteasy, two endpoints) which I wan to deploy to Openshift via quarkus-openshift extension. After an update to 3.2.0.CR2, the deployment process succeeds on Fedora and fails on RHEL 8 with "Connection was closed" error. This happens robustly.

### Expected behavior

Successful deployment as for 3.1.0.Final and on Fedora

### Actual behavior

```
[ERROR] 	[error]: Build step io.quarkus.container.image.openshift.deployment.OpenshiftProcessor#openshiftBuildFromJar threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: Connection was closed
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:520)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:535)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleGet(OperationSupport.java:478)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleGet(BaseOperation.java:741)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.requireFromServer(BaseOperation.java:185)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:141)
[ERROR] 	at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.get(BaseOperation.java:92)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuild(OpenshiftProcessor.java:462)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.lambda$openshiftBuild$10(OpenshiftProcessor.java:429)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[ERROR] 	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR] 	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR] 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR] 	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuild(OpenshiftProcessor.java:429)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.createContainerImage(OpenshiftProcessor.java:388)
[ERROR] 	at io.quarkus.container.image.openshift.deployment.OpenshiftProcessor.openshiftBuildFromJar(OpenshiftProcessor.java:285)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: io.vertx.core.http.HttpClosedException: Connection was closed
```

### How to Reproduce?

1. `git clone https://github.com/fedinskiy/reproducer -b opeshift-extension-rhel-disconnect`
2. `oc new-project rhel-disconnect && cd reproducer`
3. `mvn package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.expose=true -Dquarkus.openshift.route.expose=true -Dquarkus.application.name=app -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.kubernetes.deployment-target=openshift` fails
4. `mvn package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.expose=true -Dquarkus.openshift.route.expose=true -Dquarkus.application.name=app -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.kubernetes.deployment-target=openshift  -Dquarkus.platform.version=3.1.0.Final` succeeds (in another project)

### Output of `uname -a` or `ver`

4.18.0-477.13.1.el8_8.x86_64

### Output of `java -version`

 11.0.13, vendor: Red Hat, Inc

### Quarkus version or git rev

3.2.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

oc version(same on both Fedora and RHEL):
```
Client Version: 4.13.0-202305312300.p0.g05d83ef.assembly.stream-05d83ef
Kustomize Version: v4.5.7
Kubernetes Version: v1.26.5+7a891f0
```

**Comment by rsvoboda** [comment] 2023-06-26 07:51
@iocanel any idea what it could be connected with? We don't see this with Quarkus 3.1 and older.

**Comment by fedinskiy** [comment] 2023-06-26 08:15
Update: 3.1.2.Final is not affected by this bug, so whatever is the root cause it was not backported.

RHEL9[1] is not affected

[1]
```

```

**Comment by rsvoboda** [comment] 2023-06-26 09:43
@fedinskiy, so the problem is with 3.2.0.CR1 / Quarkus main and RHEL 8?

**Comment by fedinskiy** [comment] 2023-06-26 09:51
@rsvoboda yes,  Quarkus 3.2.0.CR1/main and RHEL 8.

**Comment by rsvoboda** [comment] 2023-06-27 10:21
@iocanel @Sgitario this is blocking issue for RHBQ as product needs to be tested on RHEL8

**Comment by Sgitario** [comment] 2023-06-27 13:29
@rsvoboda I'm trying to reproduce the issue in an RHEL8 environment (please, contact me if you have any virtual machine to use).
In the meantime, I think this might be related to https://github.com/quarkusio/quarkus/pull/34068. Could you test in Quarkus main by reverting this change? @fedinskiy @rsvoboda 

@manusa does it ring any bell to you?
@fedinskiy when the timeout happens? after 1 min or after more time? Can you share the build logs as well?

**Comment by cmoulliard** [comment] 2023-06-27 13:36
Is it possible to get the log of the pod doing the s2i build on ocp as error is taking place there ?

**Comment by rsvoboda** [comment] 2023-06-27 14:04
> In the meantime, I think this might be related to https://github.com/quarkusio/quarkus/pull/34068. Could you test in Quarkus main by reverting this change? @fedinskiy @rsvoboda

Fedor is working on it.

**Comment by fedinskiy** [comment] 2023-06-27 14:09
@Sgitario 
There is no timeout per se.
It takes the build around 10 seconds to reach line 31 of the log(see below), then there is ~ 30 seconds wait period and then for 30 seconds there is a log output and almost immediate failure after the line 357 is shown.
RHEL8 machine details are in your Slack DMs

I will test with this change reverted and reach back to you.

@cmoulliard  full test logs:
https://gist.github.com/fedinskiy/df9a586ad7a1a8995fc904e14c7ffb4a

**Comment by cmoulliard** [comment] 2023-06-27 14:53
> full test logs:

Many thanks but I was talking about the log of the s2i pod created by openshift and doing the job. This is where the problem was taking place. As the build process failed (= timeout) then the java f8 client will get a timeout and will close theconnection but to know the root cause, it is needed to get the log of the pod @fedinskiy

**Comment by fedinskiy** [comment] 2023-06-27 15:05
Build with reverted #34068 didn't work _even on a fresh machine_:

1. `git clone https://github.com/quarkusio/quarkus`
2. `git revert 0c52b6f72f78b07541c00269a9184263a6567dda`
3. ` mvn clean install -Dquickly -Dmp-test-modules -Prelocations -Dinsecure.repositories=WARN`
4. (After steps 1&2 of the original reproducer): `mvn package -Dquarkus.kubernetes.deploy=true -Dquarkus.openshift.expose=true -Dquarkus.openshift.route.expose=true -Dquarkus.application.name=app -Dquarkus.kubernetes-client.trust-certs=true -Dquarkus.kubernetes.deployment-target=openshift  -Dquarkus.platform.version=999-SNAPSHOT`

**Comment by fedinskiy** [comment] 2023-06-27 15:18
@Sgitario since this behavior is not caused by https://github.com/quarkusio/quarkus/pull/34068, maybe it is  https://github.com/quarkusio/quarkus/pull/33767 to blame?

**Comment by cmoulliard** [comment] 2023-06-27 15:40
> s2i logs

Many thanks. Your are right ;-)

According to the build [initiated](https://gist.github.com/fedinskiy/df9a586ad7a1a8995fc904e14c7ffb4a#file-build-log-L14-L24)
```
Generating dockerfile with builder image registry.access.redhat.com/ubi8/openjdk-11@sha256:60b88d0608b870dea560d34e916446dacb9e2120ca90b853612eab4c7be9c38f
Adding transient rw bind mount for /run/secrets/rhsm
STEP 1/9: FROM registry.access.redhat.com/ubi8/openjdk-11@sha256:60b88d0608b870dea560d34e916446dacb9e2120ca90b853612eab4c7be9c38f
STEP 2/9: LABEL "io.openshift.build.source-location"="/tmp/build/inputs"       "io.openshift.s2i.destination"="/tmp"       "io.openshift.build.image"="registry.access.redhat.com/ubi8/openjdk-11@sha256:60b88d0608b870dea560d34e916446dacb9e2120ca90b853612eab4c7be9c38f"
STEP 3/9: ENV OPENSHIFT_BUILD_NAME="app-1"     OPENSHIFT_BUILD_NAMESPACE="rhel-fresh"
STEP 4/9: USER root
STEP 5/9: COPY upload/src /tmp/src
STEP 6/9: RUN chown -R 185:0 /tmp/src
STEP 7/9: USER 185
STEP 8/9: RUN /usr/local/s2i/assemble
INFO S2I source build with plain binaries detected
INFO Copying binaries from /tmp/src to /deployments ...
```
the error occurs here within the code during the execution of the method `public void openshiftBuildFromJar(OpenshiftConfig openshiftConfig,`: https://github.com/quarkusio/quarkus/blob/3.2.0.CR1/extensions/container-image/container-image-openshift/deployment/src/main/java/io/quarkus/container/image/openshift/deployment/OpenshiftProcessor.java#L238

**Comment by Sgitario** [comment] 2023-06-28 04:53
> @Sgitario since this behavior is not caused by #34068, maybe it is #33767 to blame?

Yes, please let us know if without #34068 and #33767, the issue is gone.

**Comment by fedinskiy** [comment] 2023-06-28 08:44
It is not #33767, since running tests with Quarkus fea1aeeaa69e67be4ee8e6b0cb0d9fd7048d1055[1] works

[1]https://github.com/quarkusio/quarkus/pull/33767/commits/fea1aeeaa69e67be4ee8e6b0cb0d9fd7048d1055

**Comment by fedinskiy** [comment] 2023-06-28 10:42
It looks like 69682b3d9ed3a3029319884481680fd970e92c72 is not affected, so whatever update brought this change it was after the seventh of June

**Comment by fedinskiy** [comment] 2023-06-28 11:00
At the same time, 0fcfc8b517f72f49c780ea96ec8ff6350bda5062 is affected, so the change was brought somewhere from 8 to 14  of June

**Comment by Sgitario** [comment] 2023-06-28 12:06
This is definitely a timeout issue that I think it's more related to the OpenShift instance in use that the RHEL system.

What's happening is that the OpenShift instance is closing a connection after a timeout and the Fabric8 Kubernetes Client connection is gone. However, this does not mean that the build failed and we should recover from it. I will submit a pull request for fixing once I do a few more tests. 

Note that I still think the bump of Kubernetes Client by https://github.com/quarkusio/quarkus/pull/34068 and https://github.com/quarkusio/quarkus/pull/33767 is the root cause of the issue: @manusa

**Comment by fedinskiy** [comment] 2023-06-28 13:02
@Sgitario it seems to be helping, thank you!

**Closed** 2023-06-29 07:02 UTC
Labels: kind/bug, area/kubernetes
