### ISSUE TITLE
Quarkus Native Azure Build Pipeline Issue with Signing and Injected Libraries

### ISSUE THREAD

**Issue by colsonGM** [quarkusio/quarkus#19181] opened 2021-08-02 19:33 UTC
### Describe the bug

We are having a problem in our build pipelines which is preventing us from using DI from a library.  We are seeing a fatal error in the build pipeline when doing build step CI – Native Build, Maven Quarkus Build.  It occurs when we inject beans from a common library. It presents like a signing issue (`java.lang.SecurityException: class "com.[package].AClass_Bean"'s signer information does not match signer information of other classes in the same package`); however, we are certain that the package (and our app injecting the bean, for that matter) only contains one class - we created this one-class library and app in order to attempt to isolate the issue.

**Common library class (again, this is the only class in this package):**

```java
@Dependent
public class CountryCode1 {
    public static String SWITZERLAND = "CH";

    public String getCountryCode() {

        return SWITZERLAND;

    }
}
```

**App injecting bean from class:**

```java
import com.[package].CountryCode1;

@JBossLog
@ApplicationScoped
public class anApp {

    @Inject
    CountryCode1 cc1;
    @Scheduled(every = "24h", delayed = "5s")
    public void testApi(){

        String z = cc1.getCountryCode();
        log.info("Country code: " + z);

    }//testApi


}
```

### Expected behavior

We expect the Quarkus Native build to succeed

### Actual behavior

The build fails with the following error:

```
Caused by: java.lang.SecurityException: class "com.[package].CountryCode1_Bean"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:589)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans1(Default_ComponentsProvider.zig:138)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Default_ComponentsProvider.zig:38)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:115)
	at io.quarkus.arc.Arc.initialize(Arc.java:20)
	... 21 more
Error: Image build request failed with exit status 1
```

### How to Reproduce?

Steps to reproduce:

1. Create a library with an injectable bean
2. Create a signed version of this library and publish it to Artifactory or similar
3. Add the library as a dependency in some app
4. Inject a class from the library into a class in your app
5. Try to perform a Quarkus Native build on the app

### Output of `java -version`

java version "11.0.10" 2021-01-19 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

### Quarkus version or git rev

1.11.3.Final

### Additional information

Linux build agent version: 2.170.1

**Comment by zakkak** [comment] 2024-08-28 08:56
@colsonGM is this still an issue? If so, could you please provide a minimal reproducer (e.g. a repository we could clone and build to reproduce the issue)?

**Comment by zakkak** [comment] 2024-08-28 09:30
Closing as duplicate of https://github.com/quarkusio/quarkus/issues/35906

**Closed by zakkak** 2024-08-28 09:30 UTC
Labels: kind/bug, area/native-image, triage/needs-reproducer
