### ISSUE TITLE
Java Record Support for @ConfigProperties

### ISSUE THREAD

**Issue by SelimHorri** [quarkusio/quarkus#32746] opened 2023-04-19 02:15 UTC
### Description

Hi Community,

I would like to draw your attention to support **Java 17 records** for **_@ConfigProperties_** OR **_@ConfigMapping_** in order to leverage a smooth immutability without a _work-around_ solution.
It would be nice also to provide a constructor-binding mechanism for non-record types.

Kindest,
Selim

**Comment by geoand** [comment] 2023-04-19 05:33
Hi,

`@ConfigMapping` only works on interfaces (by design) and I don't think we are going to change that.
In any case, this is for @radcortez to decide.

**Comment by radcortez** [comment] 2023-04-20 00:13
Regarding `@ConfigProperties`, we believe that using a `class` to represent a configuration with fields is / was a mistake. For that reason, we introduced `@ConfigMapping`. Quarkus also had a `@ConfigProperties`, which was deprecated and removed. Unfortunately, MP Config added it to the specification and had the exact same pitfalls we encountered with our own version. Here is a summary with some of the reasons: https://github.com/jakartaee/config/discussions/122. In Jakarta Config, the group reached the same conclusion, and a `class` to represent a config will not be supported.

Since both Jakarta and MP are language level 11 only, there is no way to support Records at the spec level. Implementations can still support them on their own.

Regarding `@ConfigMapping`, I feel that adding Record support at this point would be a huge effort for little gain, but if someone is willing to put the work forward, I'm happy to help guide it and review it.

If I may, what aren't you able to achieve with an `interface` `@ConfigMapping`, that you would achieve with a Record? 

A mapping, while not strictly immutable, would require knowledge of the generated implementation class and a bunch of reflection to be able to change its state. There is nothing at the API level that allows you to change their values, and we even have multiple requests to make them reload the configuration (which we don't support). In practice, I think they are immutable :) Which work-around solution are you referring to make mappings immutable?

As for constructors, you can create a new anonymous class (or even your own class) to have your own instance. Granted, it requires more code than a Record would, but they are also easier to mock, and from my experience, config representations tend to grow big, which in my opinion is less readable with all the parameters in the constructors (plus annotations and docs), then a single method with its own context.

**Comment by geoand** [comment] 2023-04-20 04:08
Closing as per the comments above

**Closed by geoand** 2023-04-20 04:09 UTC
Labels: kind/enhancement, area/config

**Comment by SelimHorri** [comment] 2023-04-22 08:14
Hi @radcortez 
Your answer is pretty convincing and straight-forward. u made it clear..
Thank you..

**Comment by climategadgets** [comment] 2023-06-25 06:32
> If I may, what aren't you able to achieve with an `interface` `@ConfigMapping`, that you would achieve with a Record?

Interoperability with existing code (both Spring[Boot] based, and framework independent).
I may be mistaken here (WIP), but it seems like if the goal, say, to read an existing YAML configuration into data structures, it can't be done in a way that will work everywhere without a mapper (implying code bloat). SpringBoot reads records, and can work with interfaces. However, making records implement interfaces that Quarkus understands will not help, best guess so far is because JavaBeans specs are not honored by records.

On the other hand, your argument about being language level 11 makes perfect sense, regrettably :)

**Comment by radcortez** [comment] 2023-06-26 12:38
At least currently, you don't read a YAML directly into a Properties / Mapping, because the API has no knowledge of such structure and it uses a Map like API to retrieve the configuration. For instance, to be able to support YAML we had to write a source that is able to convert a YAML structure into a Map of keys and values.
