### ISSUE TITLE
Creating a ConfigItem in an unsupported way should fail explicitly 

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#16899] opened 2021-04-29 09:14 UTC
## Describe the bug
Creating a config as follows:
```java
@ConfigRoot
public class FooConfiguration {

    /**
     * The bar
     */
    @ConfigItem
    public String bar;

    /**
     * The baz
     */
    @ConfigItem
    public Optional<BazConfiguration> baz;

}
```
builds just fine without any warning. However, at runtime, `baz` is always initialized to `Optional.empty`, thus making it seem like the properties/configuration is not properly detected. This should fail explicitly if this set up is not supported instead of failing silently at runtime.

### Expected behavior
It shouldn't be possible to build an extension with an invalid configuration set up or, at the very least, a warning should be output.

### Actual behavior
The extension builds fine, resulting in unexpected behavior at runtime, making it seem like the configuration couldn't be initialized when it should have failed at build time.

**Comment by geoand** [comment] 2021-07-29 09:08
This is essentially a duplicate of https://github.com/quarkusio/quarkus/issues/7862

**Closed by geoand** 2021-07-29 09:08 UTC
Labels: area/config, kind/bug
