### ISSUE TITLE
Issue with Camel FHIR extension when upgrading to 1.13.0.Final

### ISSUE THREAD

**Issue by jjdestef3** [quarkusio/quarkus#16319] opened 2021-04-07 12:10 UTC
## Describe the bug
I an using the Camel FHIR extension in a project which is working fine for Quarkus version 1.12.2.Final. When upgrading to 1.13.0.Final and running the application in dev mode it fails to start and throws a ChainBuilder Exception.

### Expected behavior
The application starts without exceptions.

### Actual behavior
The application does not start and throws the following exception:

java.lang.RuntimeException: io.quarkus.builder.ChainBuildException: Cycle detected:
                   io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.BeanContainerBuildItem
                to org.apache.camel.quarkus.component.fhir.deployment.r5.FhirR5Processor#recordContext produced class io.quarkus.arc.deployment.SyntheticBeanBuildItem
                to io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem$BeanConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#registerSyntheticObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem
                to io.quarkus.arc.deployment.StartupBuildSteps#registerStartupObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem$ObserverConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
                to io.quarkus.arc.deployment.ObserverValidationProcessor#validateApplicationObserver produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem$ValidationErrorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#generateResources
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:396)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:269)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:79)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:378)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:56)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:127)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:144)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.ChainBuildException: Cycle detected:
                   io.quarkus.arc.deployment.ArcProcessor#generateResources produced class io.quarkus.arc.deployment.BeanContainerBuildItem
                to org.apache.camel.quarkus.component.fhir.deployment.r5.FhirR5Processor#recordContext produced class io.quarkus.arc.deployment.SyntheticBeanBuildItem
                to io.quarkus.arc.deployment.SyntheticBeansProcessor#initRuntime produced class io.quarkus.arc.deployment.BeanRegistrationPhaseBuildItem$BeanConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#registerSyntheticObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem
                to io.quarkus.arc.deployment.StartupBuildSteps#registerStartupObservers produced class io.quarkus.arc.deployment.ObserverRegistrationPhaseBuildItem$ObserverConfiguratorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#validate produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem
                to io.quarkus.arc.deployment.ObserverValidationProcessor#validateApplicationObserver produced class io.quarkus.arc.deployment.ValidationPhaseBuildItem$ValidationErrorBuildItem
                to io.quarkus.arc.deployment.ArcProcessor#generateResources
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:362)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheckProduce(BuildChainBuilder.java:335)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:366)
        at io.quarkus.builder.BuildChainBuilder.cycleCheck(BuildChainBuilder.java:326)
        at io.quarkus.builder.BuildChainBuilder.build(BuildChainBuilder.java:236)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:137)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:394)
        ... 9 more

## To Reproduce

Include the Camel Quarkus FHIR extension in the build.

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Start a project with the Camel Quarkus FHIR extension included in the pom
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin Johns-MBP-3 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)

### Quarkus version or git rev
1.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/johndestefano/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: GraalVM Community, runtime: /Users/johndestefano/.sdkman/candidates/java/21.0.0.2.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

## Additional context
(Add any other context about the problem here.)

**Comment by ppalaga** [comment] 2021-04-08 20:37
Duplicate of https://github.com/apache/camel-quarkus/issues/2441

**Closed by ppalaga** 2021-04-08 20:37 UTC
Labels: kind/bug, triage/needs-triage
