### ISSUE TITLE
Native build failures after Quarkus 3 migration

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#31105] opened 2023-02-12 23:53 UTC
### Describe the bug

After migration to Quarkus 3, native build of some of our modules fails. I can't reproduce the issue with a code start containing same dependencies (e.g. https://code.quarkus.io/d?e=resteasy&e=resteasy-jsonb&e=resteasy-jaxb&e=micrometer&S=io.quarkus.platform%3A3.0&cn=code.quarkus.io), therefore I realize there is a good chance that issue is on my side. I'd appreciate any hint.

### Expected behavior

Builds as before.

### Actual behavior

Build fails with exception (depends of module).

Modules `http/rest-client`, `http/rest-client-reactive`:
```bash
2 fatal errors detected:
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$11.parse(java.lang.CharSequence) 
Parsing context:
   at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$11.parse(RuntimeBuiltinLeafInfoImpl.java:467)
   at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$11.parse(RuntimeBuiltinLeafInfoImpl.java:464)
...
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$12.parse(java.lang.CharSequence) 
Parsing context:
   at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$12.parse(RuntimeBuiltinLeafInfoImpl.java:486)
   at org.glassfish.jaxb.runtime.v2.model.impl.RuntimeBuiltinLeafInfoImpl$12.parse(RuntimeBuiltinLeafInfoImpl.java:482)
```
Modules `security/keycloak-oidc-client-extended`:
```bash
Error: Class initialization of sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher failed. Use the option --initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher to explicitly request delayed initialization of this class.
Detailed message:

com.oracle.svm.core.util.UserError$UserException: Class initialization of sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher failed. Use the option --initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher to explicitly request delayed initialization of this class.
Detailed message:

	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FallbackFeature.reportAsFallback(FallbackFeature.java:248)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:776)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:578)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
Caused by: com.oracle.graal.pointsto.constraints.UnsupportedFeatureException: Class initialization of sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher failed. Use the option --initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher to explicitly request delayed initialization of this class.
Detailed message:

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.constraints.UnsupportedFeatures.report(UnsupportedFeatures.java:126)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:771)
	... 5 more
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1155)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.ensureClassInitialized(ClassInitializationSupport.java:172)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.computeInitKindAndMaybeInitializeClass(ProvenSafeClassInitializationSupport.java:344)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ProvenSafeClassInitializationSupport.computeInitKindAndMaybeInitializeClass(ProvenSafeClassInitializationSupport.java:75)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.classinitialization.ClassInitializationSupport.maybeInitializeHosted(ClassInitializationSupport.java:163)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.SVMHost.initializeType(SVMHost.java:267)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.initializeType(AnalysisUniverse.java:682)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.lambda$new$0(AnalysisType.java:293)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisFuture.ensureDone(AnalysisFuture.java:63)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.ensureInitialized(AnalysisType.java:670)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.onReachable(AnalysisType.java:567)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AtomicUtils.atomicMarkAndRun(AtomicUtils.java:52)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.lambda$registerAsReachable$7(AnalysisType.java:539)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:650)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:636)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.forAllSuperTypes(AnalysisType.java:632)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.registerAsReachable(AnalysisType.java:539)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.makeAnalysisTypeReachable(ReflectionDataBuilder.java:683)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.registerTypesForReachableMethod(ReflectionDataBuilder.java:523)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.processMethodMetadata(ReflectionDataBuilder.java:321)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionDataBuilder.duringAnalysis(ReflectionDataBuilder.java:197)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.reflect.ReflectionFeature.duringAnalysis(ReflectionFeature.java:254)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$10(NativeImageGenerator.java:748)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:85)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$11(NativeImageGenerator.java:748)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.AbstractAnalysisEngine.runAnalysis(AbstractAnalysisEngine.java:162)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:745)
	... 5 more
Caused by: java.lang.NullPointerException: Cannot invoke "sun.awt.datatransfer.DataTransferer.getToolkitThreadBlockedHandler()" because the return value of "sun.awt.datatransfer.DataTransferer.getInstance()" is null
	at java.desktop/sun.awt.dnd.SunDropTargetContextPeer$EventDispatcher.<clinit>(SunDropTargetContextPeer.java:756)
```

### How to Reproduce?

Reproducer:

1. `git clone git@github.com:michalvavrik/quarkus-test-suite.git`
2. `cd quarkus-test-suite`
3. `git checkout reproducer/jakarta-failing-native`
4. `cd security/keycloak-oidc-client-extended`
5. `mvn clean verify -Dnative -DskipITs -DskipTests`

### Output of `uname -a` or `ver`

Linux

### Output of `java -version`

openjdk 17.0.4 2022-07-19

### GraalVM version (if different from Java)

GraalVM 22.3.1.0-Final Java 17 Mandrel Distribution

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by zakkak** [comment] 2023-02-13 09:55
Hi @michalvavrik , 

As an immediate workaround I was able to build it with passing `-Dquarkus.native.additional-build-args=--initialize-at-run-time=sun.awt.dnd.SunDropTargetContextPeer\$EventDispatcher`. But this should be handled by the `quarkus-awt` extension instead.

The issue is that adding `quarkus-awt` to the dependencies I get:

```
Fatal error: com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing sun.awt.X11.XToolkit.createCanvas(java.awt.Canvas) 
Parsing context:
   at sun.awt.X11.XToolkit.createCanvas(XToolkit.java:1063)
   at java.awt.Canvas.addNotify(Canvas.java:109)
   at java.awt.Container.addImpl(Container.java:1150)
   at java.awt.Container.add(Container.java:440)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java:38)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)
   at com.sun.activation.viewers.TextViewer.<init>(TextViewer.java)

	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:153)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:104)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureFlowsGraphCreated(MethodTypeFlow.java:83)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.getOrCreateMethodFlowsGraph(MethodTypeFlow.java:65)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.typestate.DefaultVirtualInvokeTypeFlow.onObservedUpdate(DefaultVirtualInvokeTypeFlow.java:109)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:562)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.PointsToAnalysis$1.run(PointsToAnalysis.java:488)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.executeCommand(CompletionExecutor.java:193)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.util.CompletionExecutor.lambda$executeService$0(CompletionExecutor.java:177)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type sun.awt.X11.XBaseWindow is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at parsing sun.awt.X11.XToolkit.createCanvas(XToolkit.java:1063)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2518)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase$SharedBytecodeParser.throwParserError(SharedGraphBuilderPhase.java:110)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3393)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.handleBytecodeBlock(BytecodeParser.java:3345)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3190)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1138)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1030)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:97)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:84)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:446)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
	at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:135)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:685)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:171)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:349)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.flow.MethodTypeFlow.createFlowsGraph(MethodTypeFlow.java:93)
	... 13 more
Caused by: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported type sun.awt.X11.XBaseWindow is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.lookup(AnnotationSubstitutionProcessor.java:140)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:210)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:190)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:237)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisType.<init>(PointsToAnalysisType.java:56)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createType(PointsToAnalysisFactory.java:45)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:274)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:213)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:190)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:237)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisType.<init>(PointsToAnalysisType.java:56)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createType(PointsToAnalysisFactory.java:45)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:274)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:213)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:190)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:237)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisType.<init>(PointsToAnalysisType.java:56)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createType(PointsToAnalysisFactory.java:45)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:274)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:213)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:190)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisType.<init>(AnalysisType.java:237)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisType.<init>(PointsToAnalysisType.java:56)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.PointsToAnalysisFactory.createType(PointsToAnalysisFactory.java:45)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.createType(AnalysisUniverse.java:274)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:213)
	at org.graalvm.nativeimage.pointsto/com.oracle.graal.pointsto.infrastructure.WrappedConstantPool.lookupType(WrappedConstantPool.java:244)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupType(BytecodeParser.java:4199)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genNewInstance(BytecodeParser.java:4493)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5291)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3385)
	... 28 more
```

@Karm do you have any idea why `quarkus-awt` doesn't do the trick?

@michalvavrik do you have any idea which part of your code might depend on awt?

**Comment by michalvavrik** [comment] 2023-02-13 10:21
thank you for workaround and quick response @zakkak ; I can't see any code that depends on `quarkus-awt` except of extension combinations that we run, but that's minor case, many other modules fails.

**Comment by Karm** [comment] 2023-02-13 12:43
I wonder whether is isn't another case of some XML (or other) serializer/deserializer depending on AWT because of a deeply buried capability to serialize/deserialize thumbnail images.  Gonna take a look.

**Comment by galderz** [comment] 2023-02-14 05:57
One thing to note is that this is caused by the Quarkus 3 upgrade, so it could due to difference libraries and/or interdependencies changing the universe structure. Just added a tag to signal this is Quarkus 3. @geoand @gsmet any thoughts of ideas of what Quarkus 3 changes could be having an impact here?

**Comment by geoand** [comment] 2023-02-14 07:19
I personally have absolutely no idea what could have caused this

**Comment by gsmet** [comment] 2023-02-14 08:20
For the first error, it could be the JAXB major upgrade causing this. But I'm not sure if we have the complete stacktrace.

As for the second one, we probably need to trace how AWT comes into play.

**Comment by gsmet** [comment] 2023-02-14 08:24
What I find a bit surprising is errors mentioning `com.sun.activation`. We are using Angus Activation now so I wonder if there's something off with the dependencies. I will have a look.

**Comment by gsmet** [comment] 2023-02-15 13:01
The second issue is fixed with this diff:

```
diff --git a/security/keycloak-oidc-client-extended/pom.xml b/security/keycloak-oidc-client-extended/pom.xml
index c2a2dd16..0d726a36 100644
--- a/security/keycloak-oidc-client-extended/pom.xml
+++ b/security/keycloak-oidc-client-extended/pom.xml
@@ -42,6 +42,12 @@
         <dependency>
             <groupId>org.keycloak</groupId>
             <artifactId>keycloak-authz-client</artifactId>
+            <exclusions>
+                <exclusion>
+                    <groupId>com.sun.activation</groupId>
+                    <artifactId>jakarta.activation</artifactId>
+                </exclusion>
+            </exclusions>
         </dependency>
         <dependency>
             <groupId>io.quarkus.qe</groupId>
```

I integrated the change in our upgrade scripts.

**Comment by gsmet** [comment] 2023-02-15 13:34
I also created this PR: https://github.com/quarkusio/quarkus/pull/31188 to force Quarkus to ignore these dependencies even if in the classpath.

**Comment by gsmet** [comment] 2023-02-15 14:17
And for the first problem, the issue is that the Camel Quarkus BOM you are enforcing forces an old version of istack-commons-runtime (3.0.10) which is not compatible with the new version of JAXB which uses 4.x.

So I think we can close this issue.

**Comment by Karm** [comment] 2023-02-15 14:52
I tested it some minutes ago and I can confirm that using gsmet:banned-dependencies + camel 3.0.0-SNAPSHOT (8b8ee68cc8) makes the build pass [just fine](https://karms.biz/pastebin/quarkus-issue-31105-camel-jaxb-hell.txt), while it used to fail for me with camel  2.16.0.

**Closed by Karm** 2023-02-15 14:52 UTC
Labels: kind/bug, area/mandrel, area/graphics, area/jakarta
