### ISSUE TITLE
mvnw clean package fails when Entity extend PanacheBaseEntity and multi-class catch in ExampleResource

### ISSUE THREAD

**Issue by willr3** [quarkusio/quarkus#6092] opened 2019-12-11 03:29 UTC
**Describe the bug**
`./mvnw clean package` fails when trying to run `ExampleResourceTest.testHelloEndpoint` from the project boilerplate if you add an `@Entity` that extends PanacheBaseEntity and use multi-class catch blocks `catch(IOException | NullPointerException e)` in the ExampleResource. Changing to separate catch blocks or not extending PanacheBaseEntity fixes the problem.

**Expected behavior**
BUILD SUCCESS

**Actual behavior**
```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 3.884 s <<< FAILURE! - in org.acme.ExampleResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.019 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.ExampleResourceTest]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: Failed to initialize Arc
Caused by: java.lang.VerifyError: 
Bad type on operand stack
Exception Details:
  Location:
    org/acme/ExampleResource.hello()Ljava/lang/String; @37: invokevirtual
  Reason:
    Type 'java/lang/Object' (current frame, stack[0]) is not assignable to 'java/lang/Exception'
  Current Frame:
    bci: @37
    flags: { }
    locals: { 'org/acme/ExampleResource', 'java/lang/Object' }
    stack: { 'java/lang/Object' }
  Bytecode:
    0000000: bb00 0259 bb00 0359 2ab6 0004 b600 0512
    0000010: 06b6 0007 b700 08b7 0009 4c2b b600 0a57
    0000020: a700 0d4c 2bb6 000d 2bb6 000e b012 0fb0
    0000030:                                        
  Exception Handler Table:
    bci [0, 32] => handler: 35
    bci [0, 32] => handler: 35
  Stackmap Table:
    same_locals_1_stack_item_frame(@35,Object[#17])
    append_frame(@45,Object[#2])
```

**To Reproduce**
```java
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;

@Path("/hello")
public class ExampleResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        try /* (  BufferedReader reader = new BufferedReader(new InputStreamReader(getClass().getClassLoader().getResourceAsStream("jsonpath.js")))  ) */ {
            BufferedReader reader = new BufferedReader(new InputStreamReader(getClass().getClassLoader().getResourceAsStream("jsonpath.js")));
            reader.readLine();
         }catch (IOException | NullPointerException e) {
            e.printStackTrace();
            return e.getMessage();
        }
        return "ok";
    }
}
```
```java
package org.acme;

import io.quarkus.hibernate.orm.panache.PanacheEntityBase;
import io.quarkus.runtime.annotations.RegisterForReflection;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.validation.constraints.NotNull;

@Entity
@RegisterForReflection
public class Example extends PanacheEntityBase {

   @Id
   @SequenceGenerator(
      name = "cellSequence",
      sequenceName = "cell_id_seq",
      allocationSize = 1,
      initialValue = 10)
   @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "cellSequence")
   public Integer id;

   @NotNull
   public String type;

   @NotNull
   public String content;

}
```
`./mvnw clean package`

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.datasource.url = jdbc:postgresql://localhost:5432/repo
quarkus.datasource.driver = org.postgresql.Driver
```

**Screenshots**

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
`Linux laptop 5.0.6-200.fc29.x86_64 #1 SMP Wed Apr 3 15:09:51 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```
 - GraalVM version (if different from Java): `19.2.0.1`
 - Quarkus version or git rev: `1.0.1.Final`

**Additional context**
(Add any other context about the problem here.)

**Comment by jaikiran** [comment] 2019-12-12 06:40
A similar issue was recently fixed in `master` branch https://github.com/quarkusio/quarkus/issues/5878. That fix has made it to `1.1.0.CR1` of Quarkus which was released recently. Is there any chance you can test against that?

**Comment by aguibert** [comment] 2019-12-16 17:48
Tested this with 1.0.1.Final and reproduced the issue, then I re-tested it on the latest master and confirmed the issue is now resolved.

@gsmet please close out this issue

**Comment by willr3** [comment] 2019-12-17 15:29
Changing to `<quarkus.version>1.1.0.CR1</quarkus.version>` prevents the VerifyError and now I get `Property quarkus.index-dependency.yaup.classifier not found`. Does `1.1.0.CR1` require the classifier? The documentation still claims it is optional: https://quarkus.io/guides/cdi-reference

**Closed** 2020-02-03 17:11 UTC
Labels: kind/bug
