### ISSUE TITLE
Some paths do not match even if the should

### ISSUE THREAD

**Issue by codemaker219** [quarkusio/quarkus#34362] opened 2023-06-28 08:31 UTC
### Describe the bug

Check is two Controller:

`A.java`
```
@Path("/")
public class A {

    @Path("/a/a")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "A called";
    }
}
```
`B.java`
```
@Path("/a")
public class B {

    @Path("/b")
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "B called";
    }
}
```
This two controller provide two endpoints `GET /a/a` and `GET /a/b` They are shown in swagger and also under `/q/dev-v1/io.quarkus.quarkus-resteasy-reactive/endpoints`.

But you cant call `/a/a`. But you can call `/a/b`

### Expected behavior

You Should be able to call `GET /a/a` and `GET /a/b` .

### Actual behavior

You can call `GET /a/b` .
You can **not** call  `GET /a/a` -> 404 Resource not found.

### Output of `uname -a` or `ver`

Linux xxx 5.15.0-75-generic #82-Ubuntu SMP Tue Jun 6 23:10:23 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux 

### Output of `java -version`

openjdk version "19.0.2" 2023-01-17 OpenJDK Runtime Environment (build 19.0.2+7-44) OpenJDK 64-Bit Server VM (build 19.0.2+7-44, mixed mode, sharing)

### Quarkus version or git rev

3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.3

**Comment by geoand** [comment] 2023-06-28 08:46
This is essentially a duplicate of https://github.com/quarkusio/quarkus/issues/26496

**Closed by geoand** 2023-06-28 08:46 UTC
Labels: kind/bug
