### ISSUE TITLE
Reactive Messaging (RabbitMQ) - can't ack messages manually with consumer ack

### ISSUE THREAD

**Issue by samodadela** [quarkusio/quarkus#28350] opened 2022-10-03 09:32 UTC
### Describe the bug

It seems that whatever I do messages get always acknowledged automatically. How can I ack a message manually?

Code:
```
    @Incoming("prices")
    @Acknowledgment(Acknowledgment.Strategy.MANUAL)
    public CompletionStage<Void> process(Message<String> message) {
        String priceInUsdString = message.getPayload();
        Integer priceInUsd = Integer.parseInt(priceInUsdString);
        LOGGER.infof("process priceInUsd=%d", priceInUsd);
        return message.ack();
    }
```

```
    @Inject
    @Channel("generated-price")
    Emitter<Integer> emitter;

    public Integer generateInteger() {
        Integer i = random.nextInt(100);
        LOGGER.infof("generateInteger i=%d send", i);
        emitter.send(
                Message.of(i, () -> {
                            // Called when the message is acknowledged.
                            LOGGER.infof("generateInteger i=%d ack", i);
                            return CompletableFuture.completedFuture(null);
                        },
                        reason -> {
                            // Called when the message is acknowledged negatively.
                            LOGGER.infof("generateInteger i=%d nack", i);
                            return CompletableFuture.completedFuture(null);
                        }));
        return i;
    }
```
Calling:
```
curl http://localhost:8080/prices/generate
```

Produces the output:
```
2022-10-03 11:25:31,810 INFO  [org.acm.amq.PriceGenerator] (executor-thread-0) generateInteger i=26 send
2022-10-03 11:25:31,816 INFO  [org.acm.amq.PriceGenerator] (vert.x-eventloop-thread-1) generateInteger i=26 ack
2022-10-03 11:25:31,817 INFO  [org.acm.amq.PriceConverter] (vert.x-eventloop-thread-2) process priceInUsd=26
2022-10-03 11:25:31,818 INFO  [io.sma.rea.mes.rabbitmq] (vert.x-eventloop-thread-2) SRMSG17033: A message sent to channel `prices` has been ack'd
```

        

### Expected behavior

I'd expect the following output (the ack message only after the message has been acked):

```
2022-10-03 11:25:31,810 INFO  [org.acm.amq.PriceGenerator] (executor-thread-0) generateInteger i=26 send

2022-10-03 11:25:31,817 INFO  [org.acm.amq.PriceConverter] (vert.x-eventloop-thread-2) process priceInUsd=26
2022-10-03 11:25:31,818 INFO  [io.sma.rea.mes.rabbitmq] (vert.x-eventloop-thread-2) SRMSG17033: A message sent to channel `prices` has been ack'd
2022-10-03 11:25:31,816 INFO  [org.acm.amq.PriceGenerator] (vert.x-eventloop-thread-1) generateInteger i=26 ack
```

### Actual behavior

The 'message is acknowledged' block gets called before the message is acked.

### How to Reproduce?

1. Run the attached reproducer. 
2. Run: `curl http://localhost:8080/prices/generate`
3. Check output

[ack-test.zip](https://github.com/quarkusio/quarkus/files/9696293/ack-test.zip)

Requirements: an rabbitmq instance

### Output of `uname -a` or `ver`

Linux a 5.15.65-1-MANJARO #1 SMP PREEMPT Mon Sep 5 10:15:47 UTC 2022 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19 OpenJDK Runtime Environment (build 18.0.2+0) OpenJDK 64-Bit Server VM (build 18.0.2+0, mixed mode)

### Quarkus version or git rev

Quarkus 2.13.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /opt/apache-maven-3.8.6
Java version: 11.0.14.1, vendor: Eclipse Adoptium, runtime: /opt/jdk-11.0.14.1+1
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.65-1-manjaro", arch: "amd64", family: "unix"

**Comment by samodadela** [comment] 2022-10-03 09:37
Will do.

**Comment by samodadela** [comment] 2022-10-03 09:42
@cescoffier [RabbitMQ Reactive Messaging, can't ack messages manually #1925 ](https://github.com/smallrye/smallrye-reactive-messaging/issues/1925)

**Comment by ozangunalp** [comment] 2022-10-03 10:06
Wait, this seems to be normal behaviour. The emitter is pushing generating to the `generated-price` channel, which appears to be a channel connected to RabbitMQ. The custom outgoing message ack is run when the message is sent to the broker successfully. 

Then your `prices` channel consumes that message, I presume, and logs "process" then incoming message ack.

**Comment by samodadela** [comment] 2022-10-03 11:14
So ack() can not be used to be notified that processing is done? You are saying that the broker does the ack as soon as it gets the message, so the consumer can not do it? The consumer can neither ack() nor nack()?

**Comment by cescoffier** [comment] 2022-10-03 11:23
Ah yes, @ozangunalp is right, the emitter gets the ack when the message is acked by the broker, not when the processing succeeded.

**Comment by samodadela** [comment] 2022-10-03 11:28
Is this a limitation of RabbitMQ? 

There are settings like ` @Acknowledgment(Acknowledgment.Strategy.MANUAL)` and also `auto-acknowledgement` in application.properties... so those do nothing?

Would it make sense to log an error or warning so that the user knows it was acknowledged by the broker?

Is there a way to achieve what I intended? That is get ack after processing?

**Comment by samodadela** [comment] 2022-10-03 11:49
I guess this applies when using connectors, https://smallrye.io/smallrye-reactive-messaging/3.20.0/concepts/acknowledgement/#chain-of-acknowledgment. 

```
When using connectors to receive and consume messages, the outbound connector acknowledges the messages when they are dispatched successfully to the broker. The acknowledgment chain would, as a result, acknowledges the inbound connector, which would be able to send an acknowledgment to the broker.
```
(I don't quite understand the second part, though)

So what I wanted to do would work only with in-memory channels?

Please shine some light.

**Comment by samodadela** [comment] 2022-10-03 12:32
OK, thanks. I guess I'd have to use a separate channel to send my 'ack' back to the producer.

In my opinion this behavior of is quite different from what RabbitMQ supports so that it could be documented under its own title/chapter.

Looking at https://www.rabbitmq.com/confirms.html#basics, it seems that RM does not support consumer acknowledgements but does support publisher confirmations (the ack in this case).

**Comment by ozangunalp** [comment] 2022-10-03 14:18
I've not confirmed but I believe we use the `RabbitMQPublisher` feature (from https://vertx.io/docs/vertx-rabbitmq-client/java/#_reliable_message_publishing) of the underlying vertx client, which does publisher confirmations.

**Comment by samodadela** [comment] 2022-10-04 07:57
Also from the documentation:
_By default, the Reactive Messaging Message is acknowledged when the broker acknowledges the message._

... might be misleading since the default can not be changed (the broker will always ack the message)

**Comment by kdubb** [comment] 2022-10-07 04:26
@samodadela Are you trying to ack/nack at the destination and have that travel back through the broker to the sending client?

**Comment by samodadela** [comment] 2022-10-07 06:41
That was the idea, yes.
I guess that in general this might be complicated depending on the broker, number of hops. I though that using rabbitmq and having just one hop would work.

Since currently brokers "cut" the acknowledgment chain, I would propose to make this more clear in the documentation. I've spent quite some time trying different options to get the ack through.

I guess I can simulate the ack using a 'reply' channel.

**Comment by kdubb** [comment] 2022-10-07 06:46
Yeah as you've surmised this is not possible; at least with RabbitMQ.

Reply channels are not currently supported by the RabbitMQ connector. There is already an issue in the SRRM repository related to supporting reply channels. I would suggest these tickets be closed and add your use case to the existing issues regarding reply channels.

**Comment by cescoffier** [comment] 2022-10-17 07:23
Closed as proposed in the last comment.

**Closed** 2022-11-02 07:10 UTC
Labels: kind/bug, triage/wontfix, area/smallrye, area/reactive-messaging
