### ISSUE TITLE
Add ability to add an additional run time configuration file

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1218] opened 2019-03-05 13:40 UTC
This could be by way of generic command line argument parsing.  The additional config source would have a higher priority than the run-time defaults inherited from the build config, but lower than system property/environment variables.

**Comment by geoand** [comment] 2019-03-27 14:12
If this can be implemented like I think it can be (I was thinking that adding some bytecode to `io.quarkus.runtime.generated.RunTimeConfig#getRunTimeConfiguration` that would check a specific system property and/or an environment variable and if found add a new `ApplicationPropertiesConfigSource`), then I can take this up as part of an after hours activity :)

**Comment by dmlloyd** [comment] 2019-03-27 14:16
First we need command-line argument parsing to be done (I have a WIP branch now).  Then it can be done as you say, except it'd be the command line argument values being checked first.

**Comment by geoand** [comment] 2019-03-27 14:19
Got it! If you want me to take this after the command-line arguments work is in, feel free to assign it to me.

**Comment by emmanuelbernard** [comment] 2019-05-13 13:56
OK so it seems to exist in some form https://github.com/geoand/quarkus/blob/46dc078de494b331d83d39df8dddcc97e516bf85/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSource.java#L70

But it's not in the Guide https://quarkus.io/guides/application-configuration-guide so on the Schrodinger scale, this feature is more dead than alive. Is `config/application.properties` our recommended way? If yes can we simply document it.

**Comment by lordofthejars** [comment] 2019-05-13 14:08
Yes also, I'll update the Quarkus cheat sheet accordantly

**Comment by dmlloyd** [comment] 2019-05-13 18:24
It is the recommended way, but this issue includes setting an alternative location IMO; also there was a user report that there may be circumstances where the filesystem file is not used under native image for some reason.  Once all the cases have been chased down, I'll resolve the issue.

**Comment by emmanuelbernard** [comment] 2019-05-14 08:18
@dmlloyd let's document it as it stand (mark it WIP if you want). Because right now, while a common question, there is nowhere  to point users to.

**Comment by manoelcampos** [comment] 2019-06-27 18:24
Has anyone been able to use an external config file?
I have a uber jar and created the `config/application.properties` inside the jar dir. Then I run the app using 

```bash
export QUARKUS_PROFILE=prod; java -jar rest-app-quarkus-server-jpa-runner.jar
```

But I get the following warning:

```bash
ARJUNA048002: Could not find configuration file, URL was: null
```

**Comment by manoelcampos** [comment] 2019-06-28 14:21
Hello guys,

After analyzing the [ApplicationPropertiesConfigSource.java](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSource.java), I realized that when running the app from a jar, it ignores the config dir.

Shouldn't it prioritize an existing `config/application.properties` file instead of loading the file from the jar? I can make that change and provide a PR.

**Comment by geoand** [comment] 2019-06-28 14:40
Hi,

It should prioritize the file system properties due to the priority being higher here: https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSource.java#L72 

Maybe perhaps you are trying to override a property that is build time only?

**Comment by manoelcampos** [comment] 2019-06-28 14:52
I'm just trying to use a different JDBC connection string and other DB-related parameters in the production env. My `src/main/resources/application.properties` has the `dev.quarkus.datasource.url` and `prod.quarkus.datasource.url` variables.

Despite I define the profile to be used by typing `export QUARKUS_PROFILE=prod; java -jar rest-app-quarkus-server-jpa-runner.jar`, it seems to ignore when running from my uber jar, even if I have the `config/application.properties` at the jar dir.

If I define a system property, it works fine:

```bash
java -Dquarkus.datasource.url=jdbc:mariadb://abc.amazonaws.com:3306/mydb -jar rest-app-quarkus-server-jpa-runner.jar
```

**Comment by manoelcampos** [comment] 2019-06-28 14:56
@geoand, for what I understood, the method you pointed is from the `InFileSystem` class, which I suppose will be used only when the app is running outside a jar. 

When running from a jar file, I suppose the [InJar](https://github.com/quarkusio/quarkus/blob/master/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSource.java#L52) class will be used instead. That class ignores the `config/application.properties` file.

**Comment by geoand** [comment] 2019-06-28 14:59
@manoelcampos I think you have sort of confused things. The `InFileSystem` and `InJar` refers to the location of the properties file, not how the application is launched :).

As per your problem, could you supply a reproucer (perhaps with a reproducer containing a README with steps) that I can check over the weekend?

**Comment by manoelcampos** [comment] 2019-06-28 15:02
For sure and thanks for the support.

**Comment by geoand** [comment] 2019-06-28 15:08
No problem :)

**Comment by manoelcampos** [comment] 2019-06-28 20:35
Hello @geoand 
In fact, the issue is not what I thought. 
I could reproduce it in a sample project available at https://github.com/manoelcampos/quarkus-profiles-issue

There is a README explaining the issue and how to reproduce it.
Thanks.

**Comment by geoand** [comment] 2019-06-29 10:30
@manoelcampos nice, I'll take a look today or tomorrow most likely

**Comment by geoand** [comment] 2019-06-30 07:52
@manoelcampos I see a few problems with the configuration. First of all the system property is `-Dquarkus-profile` not `-DQUARKUS_PROFILE`.
Moreover when using profiles in `application.properties` you need to prefix them with `%`, like `%dev.quarkus.datasource.url`

**Comment by manoelcampos** [comment] 2019-06-30 11:56
Oh God. I missed out this %.
Sorry and thanks.

**Comment by geoand** [comment] 2019-06-30 12:36
No problem 😊

**Comment by jordanglassman** [comment] 2019-08-15 19:33
FYI, for running on the command line with maven, the `config` directory needs to live in `target/classes`.  

Consider clarifying this in the cheat sheet too, as "current working directory" was not obvious to me.

+1 for allowing this file to live somewhere that doesn't get wiped by `mvn clean`.

**Comment by geoand** [comment] 2019-11-13 12:57
I assume that this is covered by your latest config work @dmlloyd ?

**Comment by dmlloyd** [comment] 2019-11-13 13:01
No, not yet.  The groundwork is there but we really need to get command mode sorted out first, since setting the config file location probably warrants a command line option.  We do of course support a config file in a fixed location on the file system for now.

**Comment by geoand** [comment] 2019-11-13 13:01
Thanks for the update

**Comment by raffaelespazzoli** [comment] 2020-12-06 12:24
I also think that this feature would be very useful. Not just passing an argument at command line, but also via environment variable (which are easier to manage in containers).
I tried to pass the `APPLICATION_PROPERTIES` environment variable as suggested by the code, but it does not seem to have any effects.

**Comment by radcortez** [comment] 2021-01-05 15:13
I believe this is now covered by SR Config 1.10.0: https://smallrye.io/docs/smallrye-config/config/config.html#locations. We don't have support for command line yet, but that can be added separately.

**Closed by radcortez** 2021-01-05 15:13 UTC
Labels: area/config, pinned

**Comment by thomas-mc-work** [comment] 2021-01-05 16:01
For me it wouldn't be covered by that feature. It's limited to a static definition in the config. But the thing is that the software developer doesn't know the config file location at the time of development. It also limits the choices of the administrator to place the file somewhere else.

**Comment by radcortez** [comment] 2021-01-05 16:40
How so? The `smallrye.config.locations` configuration works like any other configuration property, so you can use it as an environment variable or use it as an argument in the `jar`.

**Comment by thomas-mc-work** [comment] 2021-01-05 21:38
Thank you, @radcortez !

So it's possible like this?:

    QUARKUS_SMALLRYE_CONFIG_LOCATION=/etc/my_app.properties /opt/my_app_launcher

Also, this would be very useful in the documentation.

**Comment by radcortez** [comment] 2021-01-05 21:44
Yes, but with the environment variable `SMALLRYE_CONFIG_LOCATIONS`. I guess that we need to improve the support on the Quarkus side to have a property that does the same in the Quarkus namespace.

**Comment by radcortez** [comment] 2021-01-05 21:45
Ah, and multiple locations need to be separated with a comma `,`.

**Comment by thomas-mc-work** [comment] 2021-03-09 19:08
Can it be that this env var is only being used when runnig the jar or native image, but not via `mvn quarkus:dev`?

**Comment by thomas-mc-work** [comment] 2021-03-09 20:52
Same for the CLI switch?

**Comment by radcortez** [comment] 2021-03-12 01:11
I've tried with a personal project and it is working. Which path are you using? For dev mode the working directory is `{projectRoot}/target`. So if you are using a relative path, you need to reference it from the `target` folder.

**Comment by thomas-mc-work** [comment] 2021-03-15 21:31
Well, configuration seems to be a hard road for me. I just found out that the order of the CLI options is important:

working: `java -Dsmallrye.config.locations=… -jar ….jar`
not working: `java -jar ….jar -Dsmallrye.config.locations=…`

**Comment by thomas-mc-work** [comment] 2021-03-15 21:33
But another question arose: I wasn't able to override values of the internal configuration file (`src/main/resources/application.properties`) from the out configuration. Is that intended? Wouldn't it make more sense make that possible?

Thanks for your patience!

**Comment by famod** [comment] 2021-03-15 21:34
@thomas-mc-work I think we all fell into that trap at some point. I surely did!

**Comment by radcortez** [comment] 2021-03-16 11:07
> Well, configuration seems to be a hard road for me. I just found out that the order of the CLI options is important:
> 
> working: `java -Dsmallrye.config.locations=… -jar ….jar`
> not working: `java -jar ….jar -Dsmallrye.config.locations=…`

Well, this is how `java` accepts system properties :)

> But another question arose: I wasn't able to override values of the internal configuration file (`src/main/resources/application.properties`) from the out configuration. Is that intended? Wouldn't it make more sense make that possible?
> 

Not necessarily. Everything loaded in the additional locations loads sources with the default ordinal `100`. Quarkus `application.properties` loads with `250`, so it gets higher. 

The issue is that we don't know if the user has anything higher, so if we would set to something higher, it may still not be enough to override user sources. The recommendation is to use `config_ordinal={value}`  where `value` is something higher than `250` (`275` for instance).

We may need to revise this behaviour, since it seems most users expect for configs present in the additional locations to override `application.properties`. Or at least clarify it in the documentation. I'm already planning to improve the documentation.

**Comment by thomas-mc-work** [comment] 2021-03-16 13:20
> We may need to revise this behaviour, since it seems most users expect for configs present in the additional locations to override application.properties

I second that! Here is what I'd expect from my command line experience:

1. The base is everything that comes included with the application (`src/main/resources/application.properties`)
2. These values can be overridden by values defined via the CLI switch (`-Dsmallrye.config.locations=…`). This is the level of the system administrator who is operating in a different environment as the developer.
3. This again can be overridden by values defined via the env variable definition (`SMALLRYE_CONFIG_LOCATIONS`). It has the highest priority because it is often the last way to intercept a process that might be buried in a shell script.

> Or at least clarify it in the documentation. I'm already planning to improve the documentation.

Wonderful! :+1: :slightly_smiling_face:
