### ISSUE TITLE
Invalid WARNING: Closing open connection prior to commit

### ISSUE THREAD

**Issue by bcluap** [quarkusio/quarkus#6770] opened 2020-01-24 14:19 UTC
**Describe the bug**
Logs are showing an invalid error when doing user local transaction management and committing a transaction. Does not happen in 1.2.0.CR1 but does on 999-SNAPSHOT
2020-01-24 16:09:46,216 WARN  [io.agr.pool] (executor-thread-27) Datasource '<default>': Closing open connection prior to commit

**Expected behavior**
This should not be logged

**Actual behavior**
Logs show:
2020-01-24 16:09:46,216 WARN  [io.agr.pool] (executor-thread-27) Datasource '<default>': Closing open connection prior to commit

**To Reproduce**

1) Run an app that uses resource local transactions. E.g.

@Path("/hello1")
@RequestScoped
public class GreetingResource1 {

    @Inject
    EntityManagerFactory myEmf;
    
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        
        EntityManager em = myEmf.createEntityManager();
        em.getTransaction().begin();
        em.createNativeQuery("SELECT 1").getResultList();
        em.getTransaction().commit();
        em.close();
        
        return "hello1";
    }
}
2) Call the rest endpoint and the logs will show the warnng when the line "em.getTransaction().commit();" is called

**Configuration**
```properties
# Add your application.properties here, if applicable.
Just standard props file to connect to a DB

**Screenshots**
NA

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux PCBLaptop 4.15.0-74-generic #84-Ubuntu SMP Thu Dec 19 08:06:28 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "11.0.5" 2019-10-15
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 999-SNAPSHOT

**Additional context**
I only noticed this today. Yesterday it was fine

**Comment by bcluap** [comment] 2020-01-24 14:47
I guess this is due to https://github.com/quarkusio/quarkus/pull/6702

**Comment by gsmet** [comment] 2020-01-24 17:51
#6702 has been merged in master recently, it's not in 1.2.0.

**Comment by AmsterdamFilho** [comment] 2020-01-28 13:43
I just built quarkus using the master version, but still getting the error. I am using the transaction annotation, though.

**Comment by gsmet** [comment] 2020-01-28 14:56
@AmsterdamFilho can you come up with a small reproducer with the `@Transactional` annotation?

**Comment by AmsterdamFilho** [comment] 2020-01-28 15:47
@gsmet Sure. It is available at https://github.com/AmsterdamFilho/quarkus-poc

**Comment by gsmet** [comment] 2020-01-29 11:28
@AmsterdamFilho I have a test failure with your POC but no warnings.

```
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 7.81 s <<< FAILURE! - in br.com.quarkus.poc.AnimalResourceTest
[ERROR] testPut  Time elapsed: 1.413 s  <<< ERROR!
java.lang.RuntimeException: org.opentest4j.AssertionFailedError: expected: <dog> but was: <dawg>
	at br.com.quarkus.poc.AnimalResourceTest.testPut(AnimalResourceTest.java:36)
```

**Comment by AmsterdamFilho** [comment] 2020-01-29 11:43
The test is related to issue #6832 mentioned in the README. 
To see the warning just run the Application in any mode and execute the post endpoint. The entity is persisted and the undesired warning appears in the log.

**Comment by Sanne** [comment] 2020-01-30 12:39
In a nutshell this issue is about using resource-local EntityManager instances.

While Quarkus is automatically configuring Hibernate ORM to use JTA; I wonder if we should make it possible to use resource-local automatically when detecting the use of `getTransaction().begin();`, or if we should rather throw an exception.

Clearly not having that API at all would be even better, but since it's defined by JPA that's a bit more complicated.

**Comment by Sanne** [comment] 2020-01-30 13:27
Please forget my previous commit, I was completely off-track: now that I'm debugging I see this is actually unrelated to Hibernate ./

**Comment by Sanne** [comment] 2020-01-30 13:52
@barreiro , I'll need your help again :)

The warning logged by Agroal seems to be unnecessarily noisy, but I'm not confident enough with the intent of the `ConnectionWrapper` to be totally sure of this.

At an high level, this is what's happening in the application:

1. a JTA transaction is started
2. a connection is acquired from the pool, so it needs to be enlisted in the existing TX
3. connection is being used by the application (Hibernate ORM in this case)
4. TX is committed

Looking into Agroal's `ConnectionHandler`, this translated into invoking these methods, in this order:

1. `void transactionStart()`
2. `ConnectionWrapper newConnectionWrapper()` (while enlisted=true so the wrapper is added to the `enlistedOpenWrappers`)
3. `void transactionCommit()` --> fires the warning as the `enlistedOpenWrappers` isn't empty.
4. transactionEnd()

This seems like by design. I guess this specific sequence of events wasn't expected ?

**Comment by jesperpedersen** [comment] 2020-02-03 13:46
@Sanne 

There are two cases here.

1) Active JTA transaction

`begin()`, `commit() and `rollback()` throws IllegalStateException(). `isActive()` returns `true`, and the rest of the `EntityTransaction` methods are hookup to `TransactionSynchronizationRegistry`.

2) No active transaction

The code looks ok, as I can't see a `close()` method. Hence Hibernate is leaking a connection within the

```java
em.createNativeQuery("SELECT 1").getResultList();
```

code path.


The WARN is in place to detect leaked connections at a transaction boundary. Calling `close()` on the connection will fix this issue.

**Comment by bcluap** [comment] 2020-02-03 13:56
@jesperpedersen Where should the close() be called? IMHO, the only call to close() should be done at an application level as per the example I posted at the top of this issue - and then cascaded down to agroal which allocates it back into the pool. Application code should be free to get an entitymanager with resource local TX mgt and start and commit transactions as it pleases over a prolonged time period if it so chooses. There should be no expectation that a connection will be given back upon commit;

**Comment by jesperpedersen** [comment] 2020-02-03 14:05
@bcluap Inside Hibernate. A connection is associated with a transaction through a `XAResource` instance, and hence a wrapper is returned. See the JCA, Transaction and XA specifications for more information.

**Comment by Sanne** [comment] 2020-02-03 14:06
@jesperpedersen bear in mind this isn't WildFly, in Quarkus we configure Hibernate ORM to only close connections on closing of the EntityManager, as that's proven to be the most efficient configuration.
 - https://github.com/hibernate/hibernate-orm/blob/3a813dcbb4b5cf5b13571c63ff0c66b94a83b53c/hibernate-core/src/main/java/org/hibernate/ConnectionReleaseMode.java#L37-L41

In WildFly it needs to close resources right away as EJB interceptors otherwise think it's leaking a connection, but we're not.

**Comment by jesperpedersen** [comment] 2020-02-03 14:23
@Sanne You will see this WARN is the physical connection is enlisted, and if there are unclosed wrappers. Calling `.close()` doesn't close the physical connection as it will be released back to the pool on the transaction boundary. There is only one physical connection associated to a transaction, as the XAResource methods are called with the Xid of the connection. Does the `EntityManager` keep these references across transactions ? If so, how are they enlisted through `enlistResource()` in the second transaction ?

**Comment by Sanne** [comment] 2020-02-03 14:25
@jesperpedersen we're not closing yet, the WARN is logged when we're attempting to invoke `void transactionCommit()`.  A close is followed immediately after, but the warning is already logged.

**Comment by jesperpedersen** [comment] 2020-02-03 14:27
@Sanne Sounds like the statements should be swapped.

**Comment by Sanne** [comment] 2020-02-03 14:40
@jesperpedersen right, I suppose this particular sequence was simply not used before

Please see my notes from debugging, I'll repeat them for your convenience:

Looking into Agroal's `ConnectionHandler`, this translated into invoking these methods, in this order:

1. `void transactionStart()`
2. `ConnectionWrapper newConnectionWrapper()` (while enlisted=true so the wrapper is added to the `enlistedOpenWrappers`)
3. `void transactionCommit()` --> fires the warning as the `enlistedOpenWrappers` isn't empty.
4. transactionEnd()

**Comment by jesperpedersen** [comment] 2020-02-03 14:45
@Sanne You need 2b. `ConnectionHandler.onConnectionWrapperClose()` which is called from `ConnectionWrapper.close()`.

**Comment by Sanne** [comment] 2020-02-07 17:24
hi @jesperpedersen , sorry I don't understand what you mean? Are you suggesting a code change in Agroal?

**Comment by jesperpedersen** [comment] 2020-02-10 15:35
@Sanne We need to look at the code that calls `DataSource.getConnection()` and find a code path to stick the `c.close()` in. Where is the code for `em.getTransaction()` and the `ON_CLOSE` functionality ? We are basically in a bean managed transaction scenario - should this be allowed if Narayana is deployed ? - so we need go through those code paths.

**Comment by AmsterdamFilho** [comment] 2020-02-15 21:45
Is there a workaround for this? This issue is really polluting the logs of my application.

**Comment by Sanne** [comment] 2020-02-17 13:29
> Is there a workaround for this? This issue is really polluting the logs of my application.

Right, sorry it's taking me long to understand the best way forward.

A good workaround would be to add `hibernate.connection.handling_mode=DELAYED_ACQUISITION_AND_RELEASE_AFTER_STATEMENT` , but there is no way to set this in the `application.properties` : you will need to have a persitence.xml to override it.

I think I'll need to switch back to that default for now, and consider this more of a longer term optimisation: Agroal and Hibernate seem to overlap on responsibilities such as resource tracking and lifecycle checks, I suspect we'll need an ad-hoc SPI.

**Closed** 2020-02-17 20:46 UTC
Labels: area/persistence, kind/bug

**Comment by Sanne** [comment] 2020-02-17 22:20
Followed up by ##7242
