### ISSUE TITLE
Redis Sentinel not working with Quarkus 1.11.2

### ISSUE THREAD

**Issue by akoufa** [quarkusio/quarkus#14532] opened 2021-01-22 17:57 UTC
**Describe the bug**
Hello. Quarkus is not being able to connect with Redis Sentinel. The standalone option works as expected. The issue is reproducible with both Quarkus 1.10.5 and 1.11.0

**To Reproduce**

You can use the following project to reproduce the issue: https://github.com/akoufa/quarkus_sentinel_issue. In this project I am configuring two Redis clients one with sentinel and one standalone.

1. Run `docker-compose up -d` and then start Quarkus Server
2. Visit http://localhost:8080/hello/standalone works as expected
3. Visit http://localhost:8080/hello/sentinel throws error

**Configuration**
```
quarkus.redis.client-type=sentinel
quarkus.redis.hosts=redis://localhost:26379

quarkus.redis.standalone.client-type=standalone
quarkus.redis.standalone.hosts=redis://localhost:6379

```

**Comment by machi1990** [comment] 2021-01-22 18:09
@akoufa thank you for opening the issue. 

I've tried the reproducer for both of the endpoints I am getting back `it works`.

**Comment by akoufa** [comment] 2021-01-22 19:03
Hello @machi1990 . I am getting the following exception: `io.smallrye.mutiny.TimeoutException` . In the production system we have a similar setup where I am getting the following exception: `:io.vertx.core.impl.NoStackTraceThrowable: No more endpoints in chain.` . Both when using the sentinel setup.

**Comment by eldimious** [comment] 2021-01-22 19:19
Hey @akoufa @machi1990 . I have the same error with @akoufa . When I run the second endpoint [http://localhost:8080/hello/sentinel](http://localhost:8080/hello/sentinel) I am receiving error. I attached below the error sceenshot:
<img width="1219" alt="Screenshot 2021-01-22 at 9 18 40 PM" src="https://user-images.githubusercontent.com/5548457/105535313-6bc9d900-5cf7-11eb-93d8-42ccafc4dcd3.png">

**Comment by machi1990** [comment] 2021-01-22 20:20
> Hello @machi1990 . I am getting the following exception: `io.smallrye.mutiny.TimeoutException` . 

Thanks @akoufa @eldimious , does changing (increasing) the timeout https://quarkus.io/guides/redis#quarkus-redis-client_quarkus.redis.timeout produce any effect? The default is 10s, should be enough but try changing it to some higher value to see if connection timing out is an issue here.

**Comment by oursy** [comment] 2021-01-23 07:05
vertx-redis-client  Obtaining the address of the current master command
```
127.0.0.1:26379> sentinel GET-MASTER-ADDR-BY-NAME mymaster
1) "172.19.0.2"
2) "6379"
```
So just change `REDIS_MASTER_HOST=localhost` in https://github.com/akoufa/quarkus_sentinel_issue/blob/master/docker-compose.yml#L10

**Comment by akoufa** [comment] 2021-01-23 10:28
Thank you @oursy . Indeed the reproducer setups was wrong. I tweaked a little bit the connection pool values in our production system. I managed to connect to redis but I am getting following errors now: `executor-thread-1) READONLY You can't write against a read only replica.` . Though I have https://quarkus.io/guides/redis#quarkus-redis-client_quarkus.redis.role as master as it is the default value anyways.

**Comment by baodingfengyun** [comment] 2021-01-27 03:33
**quarkus.redis.max-pool-size** is 6 (default), there will be timeout when times > 6 :
io.smallrye.mutiny.TimeoutException
	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:57)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.quarkus.redis.client.runtime.RedisClientImpl.await(RedisClientImpl.java:1026)
	at io.quarkus.redis.client.runtime.RedisClientImpl.incr(RedisClientImpl.java:337)

**Comment by akoufa** [comment] 2021-02-05 19:54
I was checking again and I found that setting the config value `quarkus.redis.pool-cleaner-interval` fixed the issue I am getting after some `executor-thread-1) READONLY You can't write against a read only replica.` the following `[io.ver.red.cli.imp.ConnectionManager] (vert.x-eventloop-thread-1) Unhandled Error: SWITCH-MASTER Received +switch-master message from Redis Sentinel.` and then redis works as expected and the redis client connects to the new master.

**Comment by akoufa** [comment] 2021-02-10 11:28
@machi1990 Unfortunately I experienced the issue again. I have updated the reproducer https://github.com/akoufa/quarkus_sentinel_issue found here upgrading to Quarkus 1.11.2 and fixing the docker-compose issue according to the suggestion from @oursy . After calling the endpoint multiple times one after another with `curl --location --request GET 'localhost:8080/hello/sentinel'` the following exception is being thrown:

```Caused by: io.smallrye.mutiny.TimeoutException

	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:57)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.quarkus.redis.client.runtime.RedisClientImpl.await(RedisClientImpl.java:1026)
	at io.quarkus.redis.client.runtime.RedisClientImpl.get(RedisClientImpl.java:237)
	at io.quarkus.redis.client.RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.get(RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.zig:1467)
	at org.acme.GreetingResource.hello(GreetingResource.kt:23)```

**Comment by machi1990** [comment] 2021-02-10 11:51
> @machi1990 Unfortunately I experienced the issue again. I have updated the reproducer https://github.com/akoufa/quarkus_sentinel_issue found here upgrading to Quarkus 1.11.2 and fixing the docker-compose issue according to the suggestion from @oursy . After calling the endpoint multiple times one after another with `curl --location --request GET 'localhost:8080/hello/sentinel'` the following exception is being thrown:
> 
> ```
> 
> 	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:57)
> 	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
> 	at io.quarkus.redis.client.runtime.RedisClientImpl.await(RedisClientImpl.java:1026)
> 	at io.quarkus.redis.client.runtime.RedisClientImpl.get(RedisClientImpl.java:237)
> 	at io.quarkus.redis.client.RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.get(RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.zig:1467)
> 	at org.acme.GreetingResource.hello(GreetingResource.kt:23)```
> ```

I'll check in again, just to confirm:

Are you seeing this issue all the time or it is an intermittent issue? 

From this line https://github.com/akoufa/quarkus_sentinel_issue/blob/master/src/main/kotlin/org/acme/GreetingResource.kt#L16, it seems that you are setting a value in redis. Just to confirm by "not working", when you connect to redis, do you see the value that was set? 

> the following exception is being thrown:

```
	at io.smallrye.mutiny.operators.UniBlockingAwait.await(UniBlockingAwait.java:57)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:61)
	at io.quarkus.redis.client.runtime.RedisClientImpl.await(RedisClientImpl.java:1026)
	at io.quarkus.redis.client.runtime.RedisClientImpl.get(RedisClientImpl.java:237)
	at io.quarkus.redis.client.RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.get(RedisClient_761b9a6e5f634178e3291b09c1921f229025da0c_Synthetic_ClientProxy.zig:1467)
	at org.acme.GreetingResource.hello(GreetingResource.kt:23)
```

is the stacktrace the same as the previous one?

Does changing to using the `ReactiveRedisClient` show the same behaviour? You can see https://quarkus.io/guides/redis#creating-the-increment-service on how to use it.

**Comment by akoufa** [comment] 2021-02-10 12:32
> Are you seeing this issue all the time or it is an intermittent issue?
Yes in the beginning the first X < 20 requests it works as expected and I see the value that is set. Also the issue is not if the value is returned or not. As I can just remove the code the puts the value then I will get the fallback value I have set. The issue is that somehow the connection to redis seems to be lost and then it blocks in the Redis `GET` cmd until this TimeoutException is thrown from Mutiny so that it does no block forever.

> is the stacktrace the same as the previous one?
Yes the stacktrace is the same as the previous one.

> Does changing to using the ReactiveRedisClient show the same behaviour?
Same issue also by using the ReactiveRedisClient

> see

**Comment by machi1990** [comment] 2021-02-10 13:00
> > Are you seeing this issue all the time or it is an intermittent issue?
> 
> Yes in the beginning, for the first X < 20 requests it works as expected and I see the value that is set.
> But the issue is not if the value is returned or not. I can just remove the code that puts the value and then for the first X < 20 requests I will get the fallback value. The issue is that somehow the connection to redis seems to be lost and then it blocks in the Redis `GET` cmd until this TimeoutException is thrown from Mutiny so that it does no block forever.
> 
> > is the stacktrace the same as the previous one?
> 
> Yes the stacktrace is the same as the previous one.
> 
> > Does changing to using the ReactiveRedisClient show the same behaviour?
> 
> Same issue also by using the ReactiveRedisClient
> 
> @machi1990
> I have identified that if I set the value `quarkus.redis.max-pool-size` to **X** then after the **X** request every requests experiences the above exceptions. So it has to do something with the connection pool, after having used all the connections specified there. But I am not doing the requests concurrently. It should always use 1 connection and put it back to the pool. But I 
think that does not seem to be the case

The default value for `quarkus.redis.max-pool-size` is 6.  Normally, the connection should be recycled, the default is recycle after 15 seconds.  Have you tried setting the [Pool Recycle Timeout](https://quarkus.io/guides/redis#quarkus-redis-client_quarkus.redis.pool-recycle-timeout) and [Pool Cleaner Interval](https://quarkus.io/guides/redis#quarkus-redis-client_quarkus.redis.-additional-redis-clients-.pool-cleaner-interval) configurations? 

/cc @pmlopes

**Comment by akoufa** [comment] 2021-02-10 13:11
> The default value for quarkus.redis.max-pool-size is 6. Normally, the connection should be recycled, the default is recycle after 15 seconds. Have you tried setting the Pool Recycle Timeout and Pool Cleaner Interval configurations?

Yes I tried configuring it with these properties but unfortunately the issue continues to persist.

**Comment by machi1990** [comment] 2021-02-10 14:32
> > The default value for quarkus.redis.max-pool-size is 6. Normally, the connection should be recycled, the default is recycle after 15 seconds. Have you tried setting the Pool Recycle Timeout and Pool Cleaner Interval configurations?
> 
> Yes I tried configuring it with these properties but unfortunately the issue continues to persist. @machi1990 Are you able to reproduce it with the reproducer project I have shared ?

Yes, I was able to reproduce it. It looks like connection pool are not recycled and the parameters I mentioned above do not have any effect. @pmlopes would you have an idea why this is only happening in sentinel mode but works fine for standalone?

**Comment by pmlopes** [comment] 2021-02-11 15:59
@machi1990 can you share the reproducer? Also now that work started on vertx 4, can you give it a shot with the new client?

**Comment by machi1990** [comment] 2021-02-11 21:40
> @machi1990 can you share the reproducer? 

@akoufa prepared a reproducer here https://github.com/akoufa/quarkus_sentinel_issue

> Also now that work started on vertx 4, can you give it a shot with the new client?

Has this issue been fixed in vertx 4?

**Comment by cescoffier** [comment] 2021-02-12 07:29
Anyway, we need a vert.x 3.x fix if that's a bug. Vert.x 4 integration is still months away (4-5 months)

**Comment by akoufa** [comment] 2021-02-18 13:08
@cescoffier @machi1990 @pmlopes Thanks for taking care of this. Can we maybe change the label of the issue back to **bug** ?

**Comment by michaz** [comment] 2021-03-07 14:48
Greeting! I also ran into this issue.

I *could* reproduce it with plain vert.x 3.9.6
I *could not* reproduce it with plan vert.x 4.0.2

**Comment by pmlopes** [comment] 2021-03-09 08:54
This is great news, it tells us that once quarkus upgrades to 4.x we can guarantee that sentinel, clustering and TLS support work as expected!

**Comment by machi1990** [comment] 2021-04-07 19:37
> This is great news, it tells us that once quarkus upgrades to 4.x we can guarantee that sentinel, clustering and TLS support work as expected!

There is an ongoing PR https://github.com/quarkusio/quarkus/pull/16333 to do the upgrade work.

**Closed** 2021-04-08 06:45 UTC
Labels: area/redis, kind/bug
