### ISSUE TITLE
File download not working when upgrade to 2.5.0.Final

### ISSUE THREAD

**Issue by leonardochen30** [quarkusio/quarkus#21825] opened 2021-11-30 17:36 UTC
### Describe the bug

When return a File type on response the file is not send to the browser, on 2.4.2.Final works ok.

### Expected behavior

File send successfully.

### Actual behavior

the browser don't get any response.

### How to Reproduce?

1. Create a resource
2. return any file:

public Response getFile() {
   File file = new File("/path/tp/file");
    return Response.ok(new FileInputStream(file)).build();
}

### Output of `uname -a` or `ver`

Windows

### Output of `java -version`

11

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\Users\leonardo\.m2\wrapper\dists\apache-maven-3.8.1-bin\2l5mhf2pq2clrde7f7qp1rdt5m\apache-maven-3.8.1 Java version: 11.0.12, vendor: Eclipse Foundation, runtime: C:\Java\jdk-11.0.12.7 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment] 2021-12-01 09:05
This is a duplicate of https://github.com/quarkusio/quarkus/issues/21602. 

The problem has been fixed in `main` and the fix will be available in `2.5.1.Final` (which should be out very soon)

**Closed by geoand** 2021-12-01 09:05 UTC
Labels: kind/bug, env/windows, triage/needs-triage
