### ISSUE TITLE
Table of map substition with environement variable not working in yaml properties files

### ISSUE THREAD

**Issue by DariusMR** [quarkusio/quarkus#12831] opened 2020-10-20 15:49 UTC
**Describe the bug**

Substitution of env variable which is a table of map produce this error at launch with an application.yml file :
```
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-10-20 15:35:20,341 ERROR [io.qua.application] (main) Failed to start application (with profile prod): Can't construct a java object for tag:yaml.org,2002:****; exception=No suitable constructor with 1 arguments found for class *****
 in 'string', line 1, column 1:
    [{type: test, host: localhos ...
    ^

        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:335)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObjectNoCheck(BaseConstructor.java:229)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructObject(BaseConstructor.java:219)
        at org.yaml.snakeyaml.constructor.BaseConstructor.constructDocument(BaseConstructor.java:173)
        at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470)
        at ****.convert(****.java:11)
        at ****.convert(****.java:7)
        at io.smallrye.config.Converters$OptionalConverter.convert(Converters.java:746)
        at io.smallrye.config.Converters$OptionalConverter.convert(Converters.java:727)
        at io.smallrye.config.SmallRyeConfig.getValue(SmallRyeConfig.java:161)
        at io.smallrye.config.SmallRyeConfig.getOptionalValue(SmallRyeConfig.java:206)
        at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:37)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy_0(ConfigBuildStep$validateConfigProperties1249763973.zig:260)
        at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties1249763973.deploy(ConfigBuildStep$validateConfigProperties1249763973.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:598)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: org.yaml.snakeyaml.error.YAMLException: No suitable constructor with 1 arguments found for class ****
        at org.yaml.snakeyaml.constructor.Constructor$ConstructSequence.construct(Constructor.java:604)
        at org.yaml.snakeyaml.constructor.Constructor$ConstructYamlObject.construct(Constructor.java:331)
        ... 22 more
```

**Expected behavior**

launching app with this env variable should work :

```
my_env_var='[{type: test, host: localhost, port: 443, scheme: https}]'
```

**Actual behavior**

when I put directly 
```[{type: test, host: localhost, port: 443, scheme: https}]```
 in the conf file i'ts working, but when I want to build a seemless jar with ```$my_env_var```, it's not working for table of map configuration variable (but it's working for classic simple string)

**To Reproduce**

create a application.yml : 

```
block:
  sinks: ${block_sink}
```
1. build your quarkus app
2. launch it with an env variable 
```block_sink='[{type: test, host: localhost, port: 443, scheme: https}]'``` in a docker compose file for instance
3. observe the crash

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

=> not applicable it's a application.yml

**Screenshots**

no screenshot

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux c9fda8f5f0ef 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 Linux

 - Output of `java -version`: openjdk version "1.8.0_212"
OpenJDK Runtime Environment (IcedTea 3.12.0) (Alpine 8.212.04-r0)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: tested with 1.8.1.FINAL and 1.9.0.CR1
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /usr/local/lib/apache-maven-3.5.2
Java version: 11.0.7, vendor: Oracle Corporation
Java home: /usr/lib/jvm/jdk-11.0.7
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-12-amd64", arch: "amd64", family: "unix"

**Additional context**
(Add any other context about the problem here.)

**Comment by radcortez** [comment] 2020-10-21 11:25
Hum, it seems you are trying to use a custom converter to convert the substitution yaml.

I suspect that the issue is in the model used to convert the yaml. Can you try using only `{type: test, host: localhost, port: 443, scheme: https}` (without the square brackets)?

**Comment by DariusMR** [comment] 2020-10-21 12:17
Yes but as I said, I need a table of map in input

I tried ```[{type: test, host: localhost, port: 443, scheme: https}] ``` directly in the conf file 
(or 

```yaml
    streams:
      -
        type: test
        host: localhost
        port: 443
        scheme: https
```

)

so directly written in the application.yaml file and it's working (I need this table of map in input)

without the bracket it's not working because it's not how we design our input

For instance we can have one stream or many and we don't know the number in advance, that's why we want to env_var this file with this table of map

**Comment by radcortez** [comment] 2020-10-21 12:51
I understand.

In that case, it seems you may need to adjust the mapping model. At least by looking into this portion of the stacktrace:

```
 at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:157)
        at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:490)
        at org.yaml.snakeyaml.Yaml.loadAs(Yaml.java:470)
        at ****.convert(****.java:11)
        at ****.convert(****.java:7)
        at io.smallrye.config.Converters$OptionalConverter.convert(Converters.java:746)
```

Do you have your own custom converter to pick up the expression result and convert it to some sort of model? Can you try running `ConfigProvider.getConfig().getValue("block.sink", String.class); and check you get the right expression back as a String?

**Comment by DariusMR** [comment] 2020-10-21 13:17
Yes, I've done this with the tool envsubst and after that I've controlled the number of spaces by pipe and sed the file 

after that I had exact same application.yml (which is working without using env var) so it's quite strange

I obtained the exact same conf file with the exact same number of spaces

**Comment by radcortez** [comment] 2020-10-21 14:50
I was not able to reproduce it, in the sense that I get the error both with the expression and the inline value: https://github.com/radcortez/smallrye-config/commit/0cf26bbe03f5ca9b7f6102524e0057b916e4faba

Is this a fair reproducer?

**Comment by acastele** [comment] 2020-10-21 16:35
Hello @radcortez , thanks for the reproducer. Here is a modification that represents more accurately the issue we are facing: https://github.com/acastele/smallrye-config/commit/812cdeace80dcf8839ae87d35063cc5a0346c678

**Comment by radcortez** [comment] 2020-10-22 15:04
Hi @acastele. Thank you!

I can see the issue now. Yes, the problem here is the difference on how an inline or a replaced property is interpreted by the YAML parser.

When the value is inline, it is put in the context of the `servers` and the YAML parser know it is an array and stores at such. When using the replaced value, the context is not there anymore, so the YAML parser doesn't know anything about it and treat this as a plain String. Once replaced, there is no array context, so you get the error.

If you help the YAML parser to rebuild the context, it would work. You can just use `servers: [{type: test, host: localhost, port: 443, scheme: https}]` instead (adding the `servers`) context. 

Let me know if that works for you.

**Comment by acastele** [comment] 2020-10-23 10:22
Thanks, your solution is working here : https://github.com/radcortez/smallrye-config/commit/6fe66de879942ac4f4c2a031cbcd4a7f69055b4d This is a weird behaviour since we cannot access the values the same way when using a environment variable or an inline value.

**Comment by radcortez** [comment] 2020-10-23 10:48
I wouldn't say it is a weird behaviour. Is just that the YAML Parser does not have enough context to know that the variable is an array. 

Expression replacement happens only when you retrieve the configuration value, not when the YAML file is read. If replacement would happen before the file being parsed, then it would work as you expect. Unfortunately, we cannot change that behaviour. MP Config allows dynamic sources and configurations,  so the replacement needs to happen on value retrieval, since the value may have changed. 

I guess that until now, this was never an issue, because most sources do not change their contextual values depending on how the values are set up.

**Comment by radcortez** [comment] 2020-10-27 15:43
@DariusMR @acastele Since you were able to have this working, I'll be closing down this issue. If you feel that something if not addressed, please feel free to reopen. Thanks!

**Closed by radcortez** 2020-10-27 15:43 UTC
Labels: area/config, area/smallrye, kind/bug
