### ISSUE TITLE
Kafka messages on multiple consumers for the same channel with Hibernate Reactive dont work on Quarkus 2.13

### ISSUE THREAD

**Issue by summit-pgoncalves** [quarkusio/quarkus#29019] opened 2022-11-02 22:09 UTC
### Describe the bug

Since **2.13.0** version of Quarkus, using the **session.withTransaction** then closing it as per the documentation is not working anymore when using multiple consumers for the same channel. Throwing multiple exceptions:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
...
Caused by: java.lang.IllegalStateException: Session/EntityManager is closed
```

The migration guide indicates:

_Prior to Quarkus 2.13, the Reactive Messaging consuming methods were called with an active CDI request context, inadvertently propagated, and were never terminated. Quarkus corrects this behaviour and makes sure the request context is not activated unnecessarily on message consuming methods. Code relying on the presence of the RequestScoped beans might need to start a request scope explicitly; for example, using @ActivateRequestContext annotation on the message consuming method._

Adding @ActivateRequestContext does not seem to fix the issue.

### Expected behavior

Injecting and using Mutiny.Session as per the documentation (https://quarkus.io/guides/kafka#persisting-kafka-messages-with-hibernate-reactive) should work: 

```
session.withTransaction(t -> {  
            // Database work here
        }).onTermination().call(() -> session.close()); 
```

### Actual behavior

Multiple exceptions are thrown:

```
java.util.concurrent.CompletionException: java.lang.IllegalStateException: HR000061: Session is currently connecting to database
...
Caused by: java.lang.IllegalStateException: Session/EntityManager is closed
```

### How to Reproduce?

Configure a bean for incoming kafka messages having at least two consumers on the same channel, then try to save an entity to a database.

### Output of `uname -a` or `ver`

Linux summit127 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.4" 2022-07-19

### Quarkus version or git rev

2.13.3

### Additional information

This was working prior to 2.13

**Comment by ozangunalp** [comment] 2022-11-07 10:29
Hi, I cannot reproduce this straightforwardly. @summit-pgoncalves would you be able to create a simple reproducer using the [kafka-panache-reactive-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-panache-reactive-quickstart) ? (with or without panache)

**Comment by summit-pgoncalves** [comment] 2022-11-07 14:57
Hi @ozangunalp ,

I will. The only difference I see with our code is that the incoming message class is using a bean that we inject and that is responsible for dealing with the database.

**Comment by summit-pgoncalves** [comment] 2022-11-07 15:40
Hi @ozangunalp,

I was able to reproduce the issue using [kafka-panache-reactive-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/kafka-panache-reactive-quickstart) as a base.
The issue is only reproducible when you have more than one incoming processor classes. To reproduce it:
- Create a copy of the class `PriceStorage.java` in the same folder
- Add `mp.messaging.incoming.prices.broadcast=true` to **src/main/resources**

Then on the first message received you will see the exceptions.

**Comment by ozangunalp** [comment] 2022-11-07 18:08
Thanks for looking into this. 
I think you really need to use the `@Inject Mutiny.SessionFactory` in that case. Otherwise, the created session is bound to the message context, which is the same for both calls on broadcasted channels.

**Comment by summit-pgoncalves** [comment] 2022-11-07 20:02
Thanks @ozangunalp

**Comment by cescoffier** [comment] 2022-11-13 15:16
@ozangunalp should we close this one?

**Comment by ozangunalp** [comment] 2022-11-14 11:34
No, I'll close this one after the Kafka guide update.

**Comment by ozangunalp** [comment] 2022-11-21 08:51
Documentation changed by #29176

**Closed by ozangunalp** 2022-11-21 08:51 UTC
Labels: kind/bug, area/persistence, area/kafka, area/hibernate-reactive, needs-reproducer
