### ISSUE TITLE
Quarkus updates quarkus-openapi-generator, not able to build

### ISSUE THREAD

**Issue by vkn** [quarkusio/quarkus#44689] opened 2024-11-25 15:36 UTC
### Describe the bug

[getting-started-camel.tar.gz](https://github.com/user-attachments/files/17905176/getting-started-camel.tar.gz)

After updating the project from version _3.14.2_ with `quarkus update --stream=3.15` command, the build is not working.
To reproduce run ./mvnw verify in the attached project

Temp fix is to downgrade quarkus-openapi-generator back to 2.4.7

**Comment by ricardozanini** [comment] 2024-11-25 16:17
@gastaldi duplicate of https://github.com/quarkiverse/quarkus-openapi-generator/issues/824

**Comment by ricardozanini** [comment] 2024-11-25 16:18
Original discussion link https://quarkusio.zulipchat.com/#narrow/channel/187030-users/topic/Quarkus.20updates.20quarkus-openapi-generator.2C.20not.20able.20to.20build

**Comment by gsmet** [comment] 2024-11-25 16:25
OK, let's close it then, it will be handled in https://github.com/quarkiverse/quarkus-openapi-generator/issues/824 .

@vkn please subscribe to this issue ^ for updates.

**Closed by gsmet** 2024-11-25 16:25 UTC
Labels: kind/bug, area/smallrye, area/openapi
