### ISSUE TITLE
OIDC: TenantResolver enhancement

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22197] opened 2021-12-14 14:59 UTC
### Description

ATM I have to use `TenantResolver` to be able to support multiple OIDC providers (github, google) and also a manual JWT option, where I handle my own auth via a JWT token.

Config looks like this:

```
# Default=Google
quarkus.oidc.auth-server-url=https://accounts.google.com
...

# Github
quarkus.oidc.github.auth-server-url=https://github.com/login/oauth
...

# MS
quarkus.oidc.microsoft.auth-server-url=https://login.microsoftonline.com/common/v2.0
...

# Facebook
quarkus.oidc.facebook.auth-server-url=https://www.facebook.com
...

# Apple
quarkus.oidc.apple.auth-server-url=https://appleid.apple.com/
...

# Manual context
quarkus.oidc.manual.tenant-enabled=false

mp.jwt.verify.issuer=https://example.com/issuer
mp.jwt.token.header=Cookie
mp.jwt.token.cookie=QuarkusUser
```

So in order to support this, I have to declare one endpoint that triggers OIDC auth for every provider:

```java
    @Path("/login-{provider}")
    @Authenticated
    public void loginNow(@RestPath String provider) {
        // never actually called, but better be safe
        redirect(Application.class).index();
    }
```

While my manual auth is handled by this endpoint:

```java
    @POST
    public Response manualLogin(@NotBlank @RestForm String userName, 
            @NotBlank @RestForm String password) {
        if(validationFailed()) {
            login();
        }
        User user = User.findRegisteredByUserName(userName);
        if(user == null
                || !BcryptUtil.matches(password, user.password)) {
            validation.addError("userName", "Invalid username/pasword");
            prepareForErrorRedirect();
            login();
        }
        NewCookie cookie = Register.makeUserCookie(user);
        return Response.seeOther(Router.getURI(Application::index)).cookie(cookie).build();
    }
```

And I need a `TenantResolver` to tell OIDC which tenant to use:

```java
@ApplicationScoped
public class OidcTenantResolver implements TenantResolver {
    
    @Inject
    OidcConfig oidcConfig;

    @Override
    public String resolve(RoutingContext context) {
        // Named tenants
        for (Entry<String, OidcTenantConfig> tenantEntry : oidcConfig.namedTenants.entrySet()) {
            if(!tenantEntry.getValue().tenantEnabled)
                continue;
            String tenant = tenantEntry.getKey();
            // First case: login
            // Note that Router.getURI only works in JAX-RS endpoints
            if(context.request().path().equals("/login-"+tenant)) {
                return tenant;
            }

            // Second case: auth callback from the auth server
            Cookie cookie = context.request().getCookie("q_auth_"+tenant);
            if(cookie != null) {
                return tenant;
            }

            // Third case: already logged in
            cookie = context.request().getCookie("q_session_"+tenant);
            if(cookie != null) {
                return tenant;
            }
        }
        
        // manual JWT session
        Cookie cookie = context.request().getCookie("QuarkusUser");
        if(cookie != null) {
            return "manual";
        }

        // Not logged in or default tenant
        return null;
    }
}
```

Now, it seems to me that most of these things could be handled by Quarkus itself, because the existance of a `q_session*` or `q_auth*` should always indicate its related tenant, no?
I guess sorta similarly, if I have the cookie defined in `mp.jwt.token.cookie` it also means that I'm doing JWT and not OIDC, so I shouldn't even need that `quarkus.oidc.manual.tenant-enabled=false` hack, no?

**Comment by sberyozkin** [comment] 2021-12-14 15:12
@FroMage Let me close it as a duplicate of the `OidcSession` issue, #21928 - which has been opened specifically for the users to avoid dealing with cookies in the resolver, I'll copy your comment there

**Comment by sberyozkin** [comment] 2021-12-14 15:14
I don't think `quarkus-oidc` will start checking the `mp.jwt` cookies, IMHO we'd need to make both `smallrye-jwt` and `oidc` align better

**Comment by sberyozkin** [comment] 2021-12-14 18:28
@FroMage Let me close this one, I honestly hope the Oidc Session PR will simplify things a lot and I've also opened an issue to make sure `smallrye-jwt` and `quarkus-oidc web-app` align; I'll ask you to review, thanks

**Comment by sberyozkin** [comment] 2021-12-14 19:45
@FroMage Sorry, `OidcSession` can't help in this case. I've looked closer at your code - I don't see how it can be generalized. The problem is, before `CodeAuthenticationMechanism` can decide what to do it needs to resolve the config - and there could be many session or state cookies and it is impossible to guess the tenant id without the tenant resolver doing it using an application specific knowledge (such as the `/login-{tenantId}` convention, while in other cases it can be some header specific content).

**Comment by sberyozkin** [comment] 2021-12-14 22:28
@FroMage Just ignore me on this one please, somehow I did not get there are obviously either `q_session-*` or `q_auth_*` cookies in the current request context if it is a completion of the code flow or the session already exists, so the tenant id can be calculated before the config resolution, I'll tweak the OidcSession PR

**Closed** 2021-12-20 10:07 UTC
Labels: kind/enhancement, area/oidc

**Comment by FroMage** [comment] 2021-12-21 11:29
OK verified, thanks.
