### ISSUE TITLE
MicroProfile RestClient Encoding Failing for Emojis

### ISSUE THREAD

**Issue by haseemisaac** [quarkusio/quarkus#10134] opened 2020-06-20 13:06 UTC
**Describe the bug**
Unable to encode emoji's in a @QueryParam for their GET request for their MicroProfile RestClient. It keeps failing for me; any emoji I try it automatically converts to ??.

I even tried to do:
String pre = "Sending emoji: 😉";
```System.out.println(URLEncoder.encode(pre, "UTF-8"));```

```@Encoded``` on the parameter and URLEncoder to encode the text with emoji before passing to the RestClient method.

I would be grateful if someone else can replicate the same issue; it would be amazing! because I think I am crazy 😂 

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
I expect the emoji to be decoded properly and converted into the correct URL encoding. 

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
String pre = "Sending emoji: 😉"; <- this is what I put in my java code

On my console it looks like this:
Sending emoji: 😉

But the encoding done, makes it look like this:
 https://api.telegram.org/..../sendMessage?chat_id=00000&text=Sending+emoji%3A+%3F%3F

When I decode the above it is:
 https://api.telegram.org/..../sendMessage?chat_id=00000&text=Sending emoji: ??

When decoded the telegram sees it like so:
Sending emoji: ??

**To Reproduce**
1. Extension required MicroProfile RestClient
2. Make a interface class with your RestClient requests
3. Try sending a emoji was part of a @QueryParam in a GET request

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by jaikiran** [comment] 2020-06-24 14:01
Hello @haseemisaac, is there an application that you can share as a github repo, which reproduces this issue? That will make it easier for some of us to quickly look into it and see what's going wrong.

**Comment by haseemisaac** [comment] 2020-06-24 16:29
I've put my code into this repo:
https://github.com/haseemisaac/test-quar
Look for the file: TelegramWebhookService

The app needs the TELEGRAM_BOT_KEY environment variable in order for it to
work. This app is for a telegram chat bot

Best,
Haseem

**Comment by gsmet** [comment] 2020-06-24 16:40
@haseemisaac just to narrow down the issue a bit, are you using a non-UTF-8 locale?

Could you try an `export LANG=en_US.UTF-8` on the linux box before launching the app if so?

Thanks!

**Comment by haseemisaac** [comment] 2020-06-24 19:40
> @haseemisaac just to narrow down the issue a bit, are you using a non-UTF-8 locale?
> 
> Could you try an `export LANG=en_US.UTF-8` on the linux box before launching the app if so?
> 
> Thanks!

I have, I still get the same issue
![image](https://user-images.githubusercontent.com/27515169/85619892-de3be300-b65a-11ea-9283-f061e9193ad8.png)

![image](https://user-images.githubusercontent.com/27515169/85619903-e4ca5a80-b65a-11ea-89d3-226c24a26778.png)

**Comment by jaikiran** [comment] 2020-06-25 13:59
Stuart has narrowed this down to a specific bug in RestEasy. It's being tracked in https://github.com/quarkusio/quarkus/issues/10245. Closing this issue in favour of that other one.

**Comment by gsmet** [comment] 2020-06-25 14:50
I prefer we keep it open so that we are aware of it.

**Comment by alexbrigido** [comment] 2021-11-03 14:28
How to send an URI query param decoded? I would like to send "GET /server/api/v1/mail=person@gmail.com" instead of sending "GET /server/api/v1/mail=person%40gmail.com"

I'm using rest client to consumes external API.

Quarkus: 1.13.7.Final

**Comment by gsmet** [comment] 2023-07-13 14:49
Apparently yes. If not working for you, please provide a simple reproducer that doesn’t rely on an external service. Thanks.

**Comment by floka94** [comment] 2023-07-13 17:36
So just add @Encoded on the Param?
For example:
````java
@Encoded @QueryParam(„text“) String text
```
Or on the entire Method?

**Comment by floka94** [comment] 2023-07-17 10:15
@gsmet here is a simple reproducer for this bug: https://github.com/floka94/react-client-emoji

This is what i get if i send this request `curl -X POST [http://localhost:5300/telegram?chatId=123-abc\&text=🔴-emoji](http://localhost:5300/telegram?chatId=123-abc%5C&text=%F0%9F%94%B4-emoji)`
```cli
123-abc
??-emoji
```

**Comment by gastaldi** [comment] 2023-07-18 00:49
This seems to be a RestEasy Reactive bug, as it works if you use RestEasy Classic (using the below dependencies instead):

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>
```

**Comment by gastaldi** [comment] 2023-07-18 01:37
This is the fix: https://github.com/resteasy/resteasy/commit/a02582028726bc4ce89d61b8ccb5c3ccafbe9444#diff-9694003787363ace42f1c4a03cb2363a20dc1fce1eccd6797484c8653e436f74L430

I'll submit a PR with a test to confirm it works

**Closed** 2023-07-18 06:10 UTC
Labels: kind/bug, area/resteasy-reactive

**Comment by floka94** [comment] 2023-07-18 06:19
@gastaldi thank you! With RestEasy Classic its working, but i don´t want to use it :-)
