### ISSUE TITLE
Openshift/k8s /metrics should be /q/metrics

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#15121] opened 2021-02-16 17:14 UTC
## Description
As nowadays we are doing with /health, that on k8s/Openshift is pointing to /q/health 

For example:
```
livenessProbe:
  failureThreshold: 3
  httpGet:
    path: "/q/health/live"
    port: 8080
    scheme: "HTTP"
```
We should do the same with /metrics in order to avoid a client redirection to /q/metrics that could be `inconvenience` in terms of performance and also could give some troubles with security. 

### Expected behavior
Currently, we are generating the following Openshift.yaml:
```
metadata:
  annotations:
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "8080"
```
Proposal:
```
metadata:
  annotations:
    prometheus.io/scheme: "http"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/q/metrics"
    prometheus.io/port: "8080"

**Comment by geoand** [comment] 2021-02-16 17:16
This is a duplicate of https://github.com/quarkusio/quarkus/issues/15118

**Closed by geoand** 2021-02-16 17:16 UTC
Labels: area/kubernetes, area/metrics, area/smallrye, kind/enhancement
