### ISSUE TITLE
Hibernate Inheritance not persisting to database table

### ISSUE THREAD

**Issue by shohruh-genius** [quarkusio/quarkus#42081] opened 2024-07-23 12:14 UTC
### Describe the bug

```
@Entity
@Table(name = "test_parent")
@Inheritance(strategy = InheritanceType.JOINED)
class Parent(var name: String) : PanacheEntity()
```

```
@Entity
class Child(name: String) : Parent(name)
```

```
@GraphQLApi
@Name("test_inheritance")
class TestInheritanceGraphQLResource {
    @Mutation
    fun create(name: String) = withTransaction {
        Child(name).persist<Child>().awaitSuspending()
    }
}
```

database is postgresql 16

### Expected behavior

It should save the data to the table when endpoint is called.

### Actual behavior

It is not working on aws ecs which runs on ubuntu-latest

(p.s. it works on local devices which run on macos 15 and windows 11)

### Output of `java -version`

21

### Quarkus version or git rev

3.12.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by yrodiere** [comment] 2024-07-23 13:01
Hey,

Thanks for reporting.

To clarify, you're using Hibernate Reactive, right? Hard to say without the imports, but I guess `awaitSuspending()` gives us a clue.

As you can guess, other users -- and our own test suite -- are dealing with inheritance fine, so the issue must involve some specifics of your setup.

Please provide a reproducer (a simple Quarkus project demonstrating the issue). Preferably in Java since Kotlin is not my _forte_.

**Comment by shohruh-genius** [comment] 2024-07-24 13:19
found the issue
when I added following property
`quarkus.hibernate-orm.jdbc.statement-batch-size=20`
Hibernate @Inheritance didn't work, it didn't persist the data

**Comment by yrodiere** [comment] 2024-07-24 13:24
Thanks, but this is not normal behavior. The JDBC statement batch size shouldn't even interact with `@Inheritance` in any way.

Please provide a reproducer?

**Comment by geoand** [comment] 2024-09-05 14:31
Closing for a lack of a reproducer.

If one becomes available, please add it and we can reopen the issue.

**Closed by geoand** 2024-09-05 14:31 UTC
Labels: kind/bug, env/windows, area/hibernate-reactive, triage/needs-reproducer
