### ISSUE TITLE
Consume grpc stream with quarkus-grpc

### ISSUE THREAD

**Issue by misho9933** [quarkusio/quarkus#27380] opened 2022-08-19 11:43 UTC
### Describe the bug

I am trying to consume SalesForce pub/sub API with quarkus-grpc. I am invoking successfully getTopic and getSchema methods but am having troubles when trying to invoke the subscribe method which accepts and returns grpc streams. Here's a link to the SalesForce proto file https://github.com/developerforce/pub-sub-api/blob/main/pubsub_api.proto

For the quarkus app I am following this article https://quarkus.io/guides/grpc-service-consumption

But I am getting the following exception when trying to invoke the "subscribe" method which uses grpc streams:

`17:51:07 ERROR traceId=, spanId=, trId= [or.jb.re.re.co.co.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-3) Request failed: io.grpc.StatusRuntimeException: INTERNAL: Received unexpected EOS on empty DATA frame from server
        at io.grpc.Status.asRuntimeException(Status.java:535)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:479)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.quarkus.grpc.runtime.supports.IOThreadClientInterceptor$1$1.lambda$onClose$3(IOThreadClientInterceptor.java:70)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
        at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)`

And Here's my code:

`package com.salesforce.quarkus.grpc.example.controller;

import com.salesforce.quarkus.grpc.example.service.AuthenticationService;
import com.salesforce.eventbus.protobuf.*;
import io.quarkus.grpc.GrpcClient;
import io.quarkus.grpc.GrpcClientUtils;
import io.smallrye.mutiny.Multi;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import javax.inject.Inject;
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/streaming")
@Produces(MediaType.APPLICATION_JSON)
public class Streaming {

    @Inject
    AuthenticationService authenticationService;

    private final Logger log = LoggerFactory.getLogger(getClass());

    @GrpcClient("pubsub")
    MutinyPubSubGrpc.MutinyPubSubStub pubsub;

    @GET
    public Multi<String> invokeSource() throws InterruptedException {
        log.info("Endpoint invoked");

        var metadata = authenticationService.connect();
        var alteredClient = GrpcClientUtils.attachHeaders(pubsub, metadata);
        log.info("Headers attached to grpc client");

        Multi<FetchRequest> fetchRequestMulti = Multi.createFrom().item(
                FetchRequest.newBuilder()
                        .setNumRequested(1)
                        .setTopicName("/data/AccountChangeEvent")
                        .build());

        return alteredClient.subscribe(fetchRequestMulti)
                .onSubscription().invoke(() -> log.info("⬇️ Subscribed"))
                .onFailure().invoke(f -> log.info("⬇️ Failed with " + f))
                .onCompletion().invoke(() -> log.info("⬇️ Completed"))
                .onRequest().invoke(l -> log.info("⬆️ Requested: " + l))
                .onItem().transform(fetchResponse -> {
                    log.info(fetchResponse.getRpcId());
                    return fetchResponse.getRpcId();
                });
    }
}`

**Comment by cescoffier** [comment] 2022-08-29 08:13
(weird, I was pretty sure to have posted a comment - sorry about the delay).

The issue seems to be on the server side.
Can you provide a minimal reproducer and show how you implemented the server-side?

**Comment by cescoffier** [comment] 2022-09-05 06:02
We would need a complete reproducer to understand the issue.

**Comment by misho9933** [comment] 2022-09-09 11:23
Hi,
The server is SalesForce and I don't have the code myself.

I managed to connect to the same server by using the io.grpc.stub.StreamObserver and pure java.
Unfortunatelly I cannot use the same approach with quarkus because i need to create some threads manually and my understanding is the only way is quarkus-grpc which is not working for me

**Comment by cescoffier** [comment] 2022-09-09 11:42
The deadline can be configured with: `[quarkus.grpc.clients."client-name".deadline](https://quarkus.io/guides/grpc-service-consumption#quarkus-grpc-config-group-config-grpc-client-configuration_quarkus.grpc.clients.-client-name-.deadline)`

Note that you can use the regular stubs if you do not want to use the Mutiny one. Unfortunately, without a proper reproducer, it's hard for us to investigate (I don't have access to a SalesForce server). 

Note that the issue seems related to an empty frame with the end-of-stream flag. These frames indicate the client to switch to the half-open mode (the server won't send anything anymore), but it's unexpected; maybe the client is already on this mode, or closing completely. Our clients are purely the ones from grpc-java. So, it's pretty weird it does work with gRPC java but not with Quarkus.

It would be very helpful to have something mocking the server side of your call.

**Comment by geoand** [comment] 2023-07-21 11:41
Can we close this?

**Comment by geoand** [comment] 2023-08-30 05:07
Closing

**Closed by geoand** 2023-08-30 05:07 UTC
Labels: kind/bug, area/grpc, triage/needs-reproducer
