### ISSUE TITLE
java.util.NoSuchElementException: SRCFG00011: Could not expand value IFS+x in property BASH_FUNC__module_raw%%

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#15269] opened 2021-02-23 13:55 UTC
I was working with my Quarkus application and at some point (maybe som OS update? I am on Fedora), I started to get this error:

```shell
2021-02-23 14:49:49,523 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.NoSuchElementException: SRCFG00011: Could not expand value IFS+x in property BASH_FUNC__module_raw%%
	at io.smallrye.config.ExpressionConfigSourceInterceptor.lambda$getValue$0(ExpressionConfigSourceInterceptor.java:44)
	at io.smallrye.common.expression.ExpressionNode.emit(ExpressionNode.java:22)
	at io.smallrye.common.expression.CompositeNode.emit(CompositeNode.java:22)
	at io.smallrye.common.expression.Expression.evaluateException(Expression.java:56)
	at io.smallrye.common.expression.Expression.evaluate(Expression.java:70)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:37)
	at io.smallrye.config.ExpressionConfigSourceInterceptor.getValue(ExpressionConfigSourceInterceptor.java:18)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:192)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsSupplier.get(ConfigDescriptionsSupplier.java:44)
	at io.quarkus.vertx.http.runtime.devmode.ConfigDescriptionsSupplier.get(ConfigDescriptionsSupplier.java:13)
	at io.quarkus.vertx.http.runtime.devmode.DevConsoleRecorder.addInfo(DevConsoleRecorder.java:37)
	at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates-308161071.deploy_18(DevConsoleProcessor$runtimeTemplates-308161071.zig:41142)
	at io.quarkus.deployment.steps.DevConsoleProcessor$runtimeTemplates-308161071.deploy(DevConsoleProcessor$runtimeTemplates-308161071.zig:130)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:653)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:97)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at org.bf2.operator.Main.main(Main.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by maxandersen** [comment] 2021-02-23 14:14
looks related to this fix https://github.com/quarkusio/quarkus/issues/15269

is it blocking you or is it just when you go to i.e. /q/dev config ?

**Comment by ppatierno** [comment] 2021-02-23 14:30
my application doesn't start actually. Upgrading to 0.12.0.Final doesn't help.

**Comment by maxandersen** [comment] 2021-02-23 14:58
to reproduce:

```
bash
_func() { if [ -n "${IFS+x}" ]; then \n unset _mlshdbg; fi;}
export -f _func
```

this gives me the error when using 1.11.3, but not on 1.11.0

**Comment by ppatierno** [comment] 2021-02-23 16:56
So I downgrade to 1.11.2 and it seems to work.

**Comment by radcortez** [comment] 2021-02-23 19:03
1.12.0 was just released and contains the fix for this if you want to upgrade.

**Comment by radcortez** [comment] 2021-02-23 19:04
@ppatierno if you are ok, I'll be closing this issue, since we already have a released version with the fix. If you disagree, feel free to reopen. Thanks!

**Closed by radcortez** 2021-02-23 19:04 UTC
Labels: triage/needs-triage

**Comment by radcortez** [comment] 2021-02-23 19:07
Duplicate of https://github.com/quarkusio/quarkus/issues/15032

**Comment by rossbrigoli** [comment] 2021-06-25 01:44
This seems to be happening in version 1.13.7 but only when running `mvn package`. It works when running` mvn quarkus:dev` but I couldn't package application.
