### ISSUE TITLE
It's not possible to disable openapi 

### ISSUE THREAD

**Issue by AlexandreGuidin** [quarkusio/quarkus#13806] opened 2020-12-10 14:09 UTC
**Describe the bug**
The `enabled` config of dependency `quarkus-smallrye-openap` it's not working.

**Expected behavior**
After adding the following config in `application.yml`, it should disable the generation or endpoint or download of the openapi schema file

```
quarkus:
  smallrye-openapi:
    enable: false
```
It's described here: https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_configuration
And here: https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-openapi/runtime/src/main/java/io/quarkus/smallrye/openapi/runtime/OpenApiRuntimeConfig.java

**Actual behavior**
Even after adding aditional configuration, it not make any difference. I'm still able to download and see the file
```
quarkus:
  smallrye-openapi:
    enable: false

smallrye-openapi:
  enable: false
```

**To Reproduce**
1. Add dependenct `quarkus-smallrye-openapi`
2. Add configuration properties
3. Open swagger-ui page or try to download openapi-file

**Comment by phillip-kruger** [comment] 2020-12-10 14:15
Hi @AlexandreGuidin - what version of Quarkus are you using ?

**Comment by gastaldi** [comment] 2020-12-10 14:17
I can't reproduce this in 1.10.3.Final or in the latest master

**Comment by gastaldi** [comment] 2020-12-10 14:19
It doesn't work in 1.9.2.Final though, closing this issue

**Comment by AlexandreGuidin** [comment] 2020-12-10 14:20
i'm using Quarkus 1.9.2.Final, thanks for feedback!

**Closed** 2020-12-10 14:19 UTC
Labels: area/openapi, area/smallrye, kind/bug, triage/out-of-date

**Comment by AlexandreGuidin** [comment] 2020-12-10 17:30
I've tested again in 1.10.30.Final and it works!

Some other bugs related with swagger-ui are resolved as well. Thanks again guys, nice work!  @phillip-kruger @gastaldi
