### ISSUE TITLE
Live reload failing with Zip archives generated by code.quarkus.io due to time zone issues

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4064] opened 2019-09-17 14:14 UTC
on 0.22

1. Start new project with `code.quarkus.io` with resteasy,resteasy-jsonb,panache,postgresql,openapi,validator
2. go in live reload
3. add TodoResource

```
@Path("/api")
@Consumes(MediaType.APPLICATION_JSON)
@Produces(MediaType.APPLICATION_JSON)
public class TodoResource {
    @GET
    public List<Todo> getAll() {
        return Todo.listAll();
    }
}
```

4. add Todo

```
@Entity
public class Todo extends PanacheEntity {
    public String title;
}
```

5. refresh http://localhost:8080/api
6. see Hibernate not configured error
7. add in application.properties

```
# set DB
quarkus.datasource.url=jdbc:postgresql:quarkus-demo
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus-demo
quarkus.datasource.password=quarkus-demo

# Hibernate details
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
```

8. refresh http://localhost:8080/api
9. You still see the error where it should not and the logs show that the hot reload detects the wrong file change (I did not update `ExampleResource.java` but `application.properties`

```
2019-09-17 07:07:00,034 INFO  [io.qua.dev] (executor-thread-1) Changed source files detected, recompiling [/Users/emmanuel/Code/quarkus/demos/CodeOne/hibernate-app/src/main/java/io/quarkus/hibernate/ExampleResource.java]
2019-09-17 07:07:00,247 INFO  [io.qua.dep.QuarkusAugmentor] (executor-thread-1) Beginning quarkus augmentation
```

I would love for this exact scenario to be tested in unit tests because it has broken numnerous times in the past.

**Comment by ia3andy** [comment] 2019-09-17 14:25
@emmanuelbernard you can share the link to the generate [app](https://code.quarkus.io/api/download?g=org.acme&a=regression-live-reload&v=1.0.0-SNAPSHOT&c=org.acme.ExampleResource&e=io.quarkus%3Aquarkus-resteasy&e=io.quarkus%3Aquarkus-resteasy-jsonb&e=io.quarkus%3Aquarkus-hibernate-orm-panache&e=io.quarkus%3Aquarkus-jdbc-postgresql&e=io.quarkus%3Aquarkus-smallrye-openapi&e=io.quarkus%3Aquarkus-hibernate-validator).
I think a tiny url feature would be great 😅

**Comment by emmanuelbernard** [comment] 2019-09-17 14:32
I confirm that doing the same app with 

```
mvn io.quarkus:quarkus-maven-plugin:0.21.2:create
mvn quarkus:add-extension -Dextensions=jdbc-postgresql,hibernate-orm-panache,hibernate-validator,resteasy-jsonb,openapi
```

Work as expected so it's either a bug from the code.quarkus.io generator or Quarkus 0.22 or a combination of both.

BTW I don't understand why code. generates ExampleResource while the mvn pluging generates HelloResource,

**Comment by emmanuelbernard** [comment] 2019-09-17 14:32
@ia3andy No time, I'm trying to salvage my demos for CodeOne

**Comment by emmanuelbernard** [comment] 2019-09-17 14:47
As @gsmet guessed my files have a modified date in the future which must be screwing up things

**Comment by emmanuelbernard** [comment] 2019-09-17 14:48
So I'm on macOS and use the code.quarkus.io in SFO. if that helps on the date problem and use the macOS native archive opener

**Comment by gsmet** [comment] 2019-09-17 14:53
FWIW, the date issue is reproducible on a plain Fedora 30 so I think it's a general issue.

**Comment by ia3andy** [comment] 2019-09-17 15:06
This issue has been reproduced and seems to be due to the zip creation in Code Quarkus. I filed an issue there: https://github.com/quarkusio/code.quarkus.io/issues/152

Let's keep that issue open until we actually have a fix.

**Comment by ia3andy** [comment] 2019-09-17 16:13
It's now fixed on code.quarkus.io

I think as @maxandersen suggested, maybe it would be better to check the (risky?) files dates at build/runtime?

**Comment by emmanuelbernard** [comment] 2019-09-18 01:12
Is it really fixed in the macOS archiver case in the end?

**Comment by ia3andy** [comment] 2019-09-18 07:04
> Is it really fixed in the macOS archiver case in the end?

@emmanuelbernard no it still bug, I'll create a new fix with a fixed date in the past (probably build date UTC - 12h).

As discusses with @dmlloyd and @stuartwdouglas, in parallel, a fix in the quarkus dev watch algo seems important too. They suggested using date offset from the file dates.

**Comment by dmlloyd** [comment] 2019-09-19 13:36
> As discusses with @dmlloyd and @stuartwdouglas, in parallel, a fix in the quarkus dev watch algo seems important too. They suggested using date offset from the file dates.

Not date offset: rather, record the dates for each file and compare to see if they've changed (in any way).  Don't do arithmetic of any kind on filesystem dates/timestamps *or* dates/timestamps returned by the JVM - such operations are inherently unreliable in the face of DST, NTP, human error, etc.  Just see if it's different or not different than it was before.

**Closed** 2019-09-24 11:47 UTC
Labels: bug, component:dev-mode, good first issue
