### ISSUE TITLE
Maven quarkus:dev does not recognise dependencies added through activated profile

### ISSUE THREAD

**Issue by nikospara** [quarkusio/quarkus#4147] opened 2019-09-22 21:26 UTC
**Describe the bug**
When running quarkus:dev from Maven and some dependency is in an activated profile, this dependency is not picked up. On the contrary, when running the packaged `-runner.jar`, this dependency is indeed activated.

**Expected behavior**
Dependencies should be picked up, however they get activated.

**Actual behavior**
Dependencies defined in an activated Maven profile are not picked up.

**To Reproduce**

1. Create a sample project e.g. through https://code.quarkus.io/ - I included Arc. RESTEasy-JAX-RS, Hibernate ORM and JDBC Driver H2, ....
2. Move one dependency from the top-level `<dependencies>` in a profile; I removed the `quarkus-jdbc-h2` and added the following profile:

        <profile>
          <id>xxx</id>
          <dependencies>
            <dependency>
              <groupId>io.quarkus</groupId>
              <artifactId>quarkus-jdbc-h2</artifactId>
            </dependency>
          </dependencies>
        </profile>
3. Try the following:
    - Start quarkus:dev, activating the profile:

            mvn compile quarkus:dev -Pxxx

        Quarkus reports:

            INFO  [io.quarkus] (main) Installed features:
              [agroal, cdi, hibernate-orm, narayana-jta, resteasy]

        **Observe that `jdbc-h2` is not activated!**

    - Now package and run the runner:

            mvn package -Pxxx
            java -jar target/code-with-quarkus-1.0.0-SNAPSHOT-runner.jar

        Quarkus reports:

            INFO  [io.quarkus] (main) Installed features:
              [agroal, cdi, hibernate-orm, jdbc-h2, narayana-jta, resteasy]

**Configuration**
None - using the pristine source as downloaded from code.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: *Linux wanderer 4.15.0-64-generic <span>#</span>73-Ubuntu SMP Thu Sep 12 13:16:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux*
 - Output of `java -version`:

            openjdk version "11.0.6" 2020-01-14
            OpenJDK Runtime Environment (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1)
            OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Ubuntu-1ubuntu118.04.1, mixed mode, sharing)
 - GraalVM version (if different from Java): *-N/A-*
 - Quarkus version or git rev: *1.2.0.Final*

**Additional context**
N/A

**Comment by geoand** [comment] 2019-09-23 05:55
@aloubyansky perhaps this is something you can take a look at?

**Comment by aloubyansky** [comment] 2019-09-23 07:30
Yes, this issue has been reported before. Please watch the status of #3702. I am going to close this one as a duplicate. Thanks for reporting.

**Comment by nikospara** [comment] 2019-09-23 11:01
Thank you @aloubyansky , I wasn't sure it was due to the same reason!

**Comment by nikospara** [comment] 2019-12-28 13:19
Hi @aloubyansky ,

I can see that #3702 is closed, but this is not solved; tried with 1.1.0.Final - apparently the solution for 3702 was incorporated in 1.1.0.CR1.

I have updated the description, shall we reopen this?

Thank you!

**Comment by aloubyansky** [comment] 2019-12-28 14:20
Hi @nikospara,
sorry, reviewing this issue I see that my first assessment of it was not entirely accurate. It's not a duplicate of #3702. They do look identical but their nature is different. This issue should in fact be fixed now but not in 1.1.0. Please see #5464.

**Comment by nikospara** [comment] 2019-12-28 16:29
Thank you, @aloubyansky , will keep an eye on it.

**Comment by nikospara** [comment] 2020-02-07 21:35
Still happening with 1.2.0, which has 5464 merged.

**Comment by geoand** [comment] 2020-02-08 06:41
Is it an issue with 1.3.0.Alpha1 as well?

**Comment by nikospara** [comment] 2020-02-09 19:38
Hi @geoand, sorry for the delayed response. YES, I get the same behavior with 1.3.0.Alpha1 (compiled locally).

**Comment by geoand** [comment] 2020-02-09 19:51
Okay thanks for checking.

@aloubyansky is this something you want to check?

**Comment by aloubyansky** [comment] 2020-02-09 19:53
Sure, I was going to.

**Comment by geoand** [comment] 2020-02-09 20:29
Thanks!

**Comment by aloubyansky** [comment] 2020-02-09 22:17
I can reproduce it.

**Closed** 2020-02-12 07:42 UTC
Labels: area/dev-mode, area/maven, kind/bug

**Comment by aloubyansky** [comment] 2020-02-12 07:47
@nikospara I believe https://github.com/quarkusio/quarkus/pull/7154 fixes your issue. The PR also includes a test for it. And it's now merged in master. If there is a chance you can try it, please, do and let us know how it worked for you. Thanks.

**Comment by nikospara** [comment] 2020-02-13 22:51
Hi @aloubyansky, again sorry for the late reaction. Will check ASAP (tomorrow probably) and let you know. Thank you!

**Comment by nikospara** [comment] 2020-02-16 20:57
Hello again @aloubyansky. Yes, I confirm it is working with the latest master.

**Comment by aloubyansky** [comment] 2020-02-16 21:21
Excellent, thanks @nikospara
