### ISSUE TITLE
SRMSG18245: There are still 140 unprocessed messages after the closing timeout

### ISSUE THREAD

**Issue by Inithron** [quarkusio/quarkus#42583] opened 2024-08-16 07:43 UTC
### Describe the bug

Our application uses the Kafka extension and is running in EKS with a "Horizontal Pod Autoscaler". When the pods are scaling down, following warnings are logged (we us logging in JSON format):
```
{
	"timestamp": "2024-08-15T21:48:52.372650631Z",
	"sequence": 908,
	"loggerClassName": "io.smallrye.reactive.messaging.kafka.i18n.KafkaLogging_$logger",
	"loggerName": "io.smallrye.reactive.messaging.kafka",
	"level": "WARN",
	"message": "SRMSG18245: There are still 140 unprocessed messages after the closing timeout",
	"threadName": "Shutdown thread",
	"threadId": 14,
	"mdc": {},
	"ndc": "",
	"hostName": "tccm-kas-bmp-7c8c5468c5-h8xmc",
	"processName": "quarkus-run.jar",
	"processId": 1
}
```

### Expected behavior

The applications shutting down / pods are scaling down without any warnings.

### How to Reproduce?

This bug occurs each time when during a shutdown the re-balancing is executed and the record stores are initialized:
```
SRMSG18224: Executing consumer revoked re-balance listener for group 'group-id'
SRMSG18256: Initialize record store for topic-partition 'topic-partition' at position 184616.
SRMSG18245: There are still 140 unprocessed messages after the closing timeout
```

### Output of `java -version`

17

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle version 8.9

**Comment by cescoffier** [comment] 2024-08-19 15:19
First, make sure that `graceful-shtdown` is enabled for that channel (it's true by default). 

The connector tries to wait a grace period to let the processing complete. However, the grace period expires in your case, and there are still unprocessed messages. It can be due to:

1. A poison pill message avoiding anything to be committed after that offset
2. A processing to slow (in this case, you would need to increase the grace period (it's 2* the poll period, so increase the poll period))

**Comment by Inithron** [comment] 2024-08-20 12:59
@cescoffier thanks for your answer. I have tried out many config parameter but non of them solved the problem.

I have not find a property with the name "poll period" but a similar one: I have set the following property: `mp.messaging.incoming.inbound-channel-toll-declaration.poll-timeout=20000`. With this property the initial issue does no more occur. But now a new warning is logged:

```
{
	"timestamp": "2024-08-20T12:23:53.309016799Z",
	"sequence": 463,
	"loggerClassName": "org.apache.kafka.common.utils.LogContext$LocationAwareKafkaLogger",
	"loggerName": "org.apache.kafka.clients.consumer.internals.ConsumerCoordinator",
	"level": "WARN",
	"message": "[Consumer clientId=kafka-consumer-inbound-channel-toll-declaration, groupId=bmp] Close timed out with 2 pending requests to coordinator, terminating client connections",
	"threadName": "smallrye-kafka-consumer-thread-1",
	"threadId": 27,
	"mdc": {},
	"ndc": "",
	"hostName": "tccm-kas-lpt-bmp-79cf859877-xshp8",
	"processName": "/usr/lib/jvm/java-17-openjdk-17.0.12.0.7-2.el9.x86_64/bin/java",
	"processId": 1
}
```
Do you also know how I can solve this warning?

**Comment by cescoffier** [comment] 2024-08-20 13:02
Not totally sure about this new warning. @ozangunalp is at expected when you increase the poll timeout? (BTW, that sounds rather high)

**Comment by Inithron** [comment] 2024-08-20 16:12
Our application process records concurrently. We have 150 partitions per topic.

I still do not understand the new issue. The poll-timeout is 20 seconds so the grace time should be 40 seconds but this is still less than the default value for the `default.api.timeout.ms` which is 1 minute.

Or is the application first waiting for the poll-timeout and than for the grace time?

**Comment by cescoffier** [comment] 2024-09-05 05:44
As Ozan said, we are only waiting for poll timeout *2 but then wait for a commit interval. That might explain your behavior.

Closing as this is not an issue anymore.

**Closed by cescoffier** 2024-09-05 05:44 UTC
Labels: kind/bug, area/reactive-messaging

**Comment by cescoffier** [comment] 2024-09-09 12:41
It seems more like a plain Kafka configuration issue than a Quarkus issue.
Refer to Ozan's comment and to my last comment that explain how the graceful shutdown configures itself.

If you believe it's wrong and can provide a reproducer, please re-open the issue with that reproducer attached.

**Comment by Inithron** [comment] 2024-10-14 10:26
I tried out a lot with different timeouts for several properties. But I did not achieve a graceful shutdown. Unfortunately I am even not able to reproduce the issue on my local PC. I am only able to reproduce it in our AWS EKS environment by scaling the pods up and down while they are processing messages. @cescoffier do you have any idea how I can implement a reproducer?
