### ISSUE TITLE
Error processing Health Checks: java.lang.NullPointerException in native mode.

### ISSUE THREAD

**Issue by yanxuehe** [quarkusio/quarkus#9768] opened 2020-06-04 03:46 UTC
**Describe the bug**
Error processing Health Checks: java.lang.NullPointerException in native mode.

the healthcheck code
```java
@Liveness
@ApplicationScoped
@Slf4j
public class JIRAHealthCheck implements HealthCheck {

  @Inject
  JIRAConfiguration jiraConfiguration;

  @Inject
  @RestClient
  JIRAHealthCheckService jiraHealthCheckService;

  @Inject
  @RestClient
  JIRARestClient jiraRestClient;

  @Override
  public HealthCheckResponse call() {
    HealthCheckResponseBuilder responseBuilder = HealthCheckResponse.named("JIRA connections and configurations health check");

    Response resp = jiraHealthCheckService.status();

    Map map = resp.readEntity(Map.class);
    responseBuilder.withData("state", map.get("state").toString());
    responseBuilder.state(resp.getStatus() == 200);

    try {
      jiraRestClient.getProject(jiraConfiguration.project());
    } catch (WebApplicationException e) {
      Response r1 = e.getResponse();
      switch (r1.getStatus()) {
        case 401:
          responseBuilder.withData("message", "the credentials '" + jiraConfiguration.username() + "/******'" + " configured is invalid.");
          break;
        case 404:
          responseBuilder.withData("message", "the project key '" + jiraConfiguration.project() + "' configured is invalid.");
          break;
        default:
          break;
      }
      responseBuilder.state(resp.getStatus() == 200 && r1.getStatus() != 401 && r1.getStatus() != 404);
    }

    return responseBuilder.build();
  }
}
```

the log
```log
2020-06-04 02:58:23,228 ERROR [io.sma.hea.SmallRyeHealthReporter] (vert.x-worker-thread-0) Error processing Health Checks: java.lang.NullPointerException
	at java.lang.reflect.Method.invoke(Method.java:559)
	at org.jboss.resteasy.microprofile.client.header.ComputedHeaderValueFiller.generateValues(ComputedHeaderValueFiller.java:121)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderValueGenerator.fillHeaders(ClientHeaderValueGenerator.java:59)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProvider.lambda$addHeaders$3(ClientHeaderProvider.java:68)
	at java.util.HashMap$Values.forEach(HashMap.java:976)
	at org.jboss.resteasy.microprofile.client.header.ClientHeaderProvider.addHeaders(ClientHeaderProvider.java:68)
	at org.jboss.resteasy.microprofile.client.header.ClientHeadersRequestFilter.lambda$filter$0(ClientHeadersRequestFilter.java:40)
	at java.util.Optional.ifPresent(Optional.java:183)
	at org.jboss.resteasy.microprofile.client.header.ClientHeadersRequestFilter.filter(ClientHeadersRequestFilter.java:40)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.filterRequest(ClientInvocation.java:679)
	at org.jboss.resteasy.microprofile.client.impl.MpClientInvocation.filterRequest(MpClientInvocation.java:45)
	at org.jboss.resteasy.client.jaxrs.internal.ClientInvocation.invoke(ClientInvocation.java:485)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invokeSync(ClientInvoker.java:149)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientInvoker.invoke(ClientInvoker.java:112)
	at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:76)
	at com.sun.proxy.$Proxy347.getProject(Unknown Source)
	at java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:149)
	at com.sun.proxy.$Proxy348.getProject(Unknown Source)
	at com.ibm.jira.JIRAHealthCheck.call(JIRAHealthCheck.java:46)
	at com.ibm.jira.JIRAHealthCheck_ClientProxy.call(JIRAHealthCheck_ClientProxy.zig:183)
	at io.smallrye.health.SmallRyeHealthReporter.jsonObject(SmallRyeHealthReporter.java:187)
	at io.smallrye.health.SmallRyeHealthReporter.fillCheck(SmallRyeHealthReporter.java:174)
	at io.smallrye.health.SmallRyeHealthReporter.processChecks(SmallRyeHealthReporter.java:162)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:140)
	at io.smallrye.health.SmallRyeHealthReporter.getHealth(SmallRyeHealthReporter.java:99)
	at io.smallrye.health.SmallRyeHealthReporter_ClientProxy.getHealth(SmallRyeHealthReporter_ClientProxy.zig:428)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:26)
	at io.quarkus.smallrye.health.runtime.SmallRyeHealthHandler.handle(SmallRyeHealthHandler.java:18)
	at io.vertx.ext.web.impl.BlockingHandlerDecorator.lambda$handle$0(BlockingHandlerDecorator.java:48)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:527)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

**Expected behavior**
the same code works perfect in jvm mode
the health check can work as the jvm mode. 

**Actual behavior**
Error processing Health Checks: java.lang.NullPointerException

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
I am using ```quay.io/quarkus/centos-quarkus-maven:20.0.0-java11``` for building
```registry.access.redhat.com/ubi8/ubi-minimal:8.1``` for running

Quarkus version: 1.4.2.Final
Installed features: [agroal, cdi, hibernate-orm, hibernate-orm-panache, hibernate-validator, jdbc-mysql, narayana-jta, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, swagger-ui]

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment] 2020-06-04 05:31
Hi,

Since it's not clear from the stacktrace, does this happen when `jiraHealthCheckService` is called, or when `jiraRestClient` is called?

Moreover, do these calls work outside of the health check in native mode?

Finally, it would be a tremendous help if you could provide a small project that reproduces this behavior. That way we can test any potential fix we come up with. Otherwise we are sort of blind.

Thanks

**Comment by yanxuehe** [comment] 2020-06-04 07:25
the error happened when jiraRestClient called.

tried to create a reproducer with only the healthcheck, it works.

**Comment by geoand** [comment] 2020-06-04 07:30
It would be great if you uploaded your a reproducer so we can use it to fix the issue.

**Comment by yanxuehe** [comment] 2020-06-04 07:32
is it possible to debug the native code on my side?

**Comment by geoand** [comment] 2020-06-04 07:39
You can check out: https://www.youtube.com/watch?v=JqV-NFWupLA

**Comment by geoand** [comment] 2020-06-04 09:48
Can you paste what `JIRARestClient` looks like?

**Comment by yanxuehe** [comment] 2020-06-12 04:16
sorry for the late response

```java

import org.eclipse.microprofile.config.Config;
import org.eclipse.microprofile.config.ConfigProvider;
import org.eclipse.microprofile.rest.client.annotation.ClientHeaderParam;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

import javax.ws.rs.*;
import javax.ws.rs.core.Response;
import java.util.Base64;
import java.util.Map;

@RegisterRestClient(configKey = "jira-api")
@Path("/api/latest")
@ClientHeaderParam(name = "Authorization", value = "{lookupAuth}")
public interface JIRARestClient {

  default String lookupAuth() {
    final Config config = ConfigProvider.getConfig();
    final String username = config.getValue("jira.username", String.class);
    final String password = config.getValue("jira.password", String.class);
    return "Basic " + Base64.getEncoder().encodeToString((username + ":" + password).getBytes());
  }

  /**
   * Get Project By Project Key
   *
   * @param key the project key
   * @return
   */
  @GET
  @Path("/project/{key}")
  Response getProject(@PathParam("key") String key);

  /**
   * Get all the Issue Types in Project
   *
   * @param projKey the project key
   * @return
   */
  @GET
  @Path("/issue/createmeta/{projKey}/issuetypes")
  Object getIssuetypesByProjKey(@PathParam("projKey") String projKey, @QueryParam("maxResults") int maxResults);

  /**
   * Get Issue Type By Project Key and Issue Type Id
   *
   * @param projKey     the project key
   * @param issuetypeId the Issue Type Id
   * @return
   */
  @GET
  @Path("/issue/createmeta/{projKey}/issuetypes/{issuetypeId}")
  Object getIssuetypeByProjKeyAndIssuetypeId(@PathParam("projKey") String projKey, @PathParam("issuetypeId") String issuetypeId, @QueryParam("maxResults") int maxResults);

  /**
   * Create new Issue
   *
   * @param body the given issue
   * @return
   */
  @POST
  @Path("/issue")
  Map<String, Object> createIssue(Map<String, Object> body);
}

```

**Comment by geoand** [comment] 2020-06-15 05:19
Oh right, this happens because `default` methods do really work in native mode (the reason being that MethodHandles don't work).

cc @michalszynkiewicz @kenfinnigan - I think taking another look at not relying on method handles at all for the rest client would be great :)

**Comment by geoand** [comment] 2020-07-27 12:13
I'll close this in favor of #10249 (as @michalszynkiewicz has already assigned himself to that one).

Please monitor the progress on that issue in order to see when the problem will be addressed.

**Closed by geoand** 2020-07-27 12:13 UTC
Labels: kind/bug
