### ISSUE TITLE
Live reload with multi-module workspace containing SNAPSHOT dependencies

### ISSUE THREAD

**Issue by rokkolesa** [quarkusio/quarkus#33725] opened 2023-05-31 10:58 UTC
### Describe the bug

When developing a multi-module `Quarkus` application with `SNAPSHOT` modules, the live-reload functionality does not register any modules which are deployed to a maven repository (e.g. Sonatype Nexus).
These modules can be used in other applications and therefore have to be deployed to a maven repository (we use a self-hosted instance of Sonatype Nexus).

### Expected behavior

The live reload functionality should work in a multi-module project regardless if it is deployed to a maven repository or not.

### Actual behavior

Live reload of `SNAPSHOT`-versioned modules which were uploaded to a maven repository does not work.
It actually works, if you `mvn install` these modules.

### How to Reproduce?

Reproducer with detailed instructions and information: https://github.com/rokkolesa/quarkus-live-reload-problem.

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Homebrew (build 17.0.7+0) OpenJDK 64-Bit Server VM Homebrew (build 17.0.7+0, mixed mode, sharing)

### Quarkus version or git rev

3.0.4.Final, 3.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Running `/Users/rokkolesa/Medius/workspaces/workspace-sandbox/demo-live-reload-parent/mvnw`... Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39) Maven home: /Users/rokkolesa/.m2/wrapper/dists/apache-maven-3.8.8-bin/67c30f74/apache-maven-3.8.8 Java version: 17.0.7, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk@17/17.0.7/libexec/openjdk.jdk/Contents/Home Default locale: en_SI, platform encoding: UTF-8 OS name: "mac os x", version: "13.3.1", arch: "aarch64", family: "mac"

**Comment by rokkolesa** [comment] 2023-06-21 09:21
@geoand any progress on this? This is a very annoying limitation and hinders our development quite a bit.

**Comment by geoand** [comment] 2023-06-21 09:31
No progress AFAIK, maybe @aloubyansky knows more

**Comment by aloubyansky** [comment] 2023-06-21 09:49
I haven't tried the reproducer yet but I suspect the problem is `4. mvn clean`. I guess by that you mean you are removing all the `target` dirs from all the modules? It won't work. `quarkus:dev` handles compilation automatically only in the app module itself but not the lib. Now that you removed the classes from the lib module, the lib can't be resolved from the workspace - it simply does not exist, so the resolver is looking for it in local and then remote repos.

**Comment by aloubyansky** [comment] 2023-06-21 10:24
As a workaround in such cases, you could add the quarkus-maven-plugin link n the pluginManagement in the parent pom (possibly without the goals) and then run `compile quarkus:dev` from the root project dir. As long as you have a single quarkus app in the multi module project it should work.

**Comment by rokkolesa** [comment] 2023-06-21 10:56
Thanks for the quick responses! 🙂 

I see what you mean, but even if i compile the modules beforehand, the same thing happens.
If I change a file in `..-lib`, it doesn't get picked up.
I just included the `4. mvn clean` to start with a clean project.
It should have been `4. mvn clean compile`, of course 🙂

Your second workaround however, works for this reproducer.
But I'm afraid we have some multi-module projects containing multiple quarkus apps 😕
We even have some libraries we want to develop and use in a quarkus app, which are in a separate git repo and are not in the multi-module tree.
We would like to develop these apps with the live-reload functionality.

To illustrate:
```
rootDir
|
|- quarkus-multimodule-project
|---- quarkus-app1
|---- quarkus-app2
|---- common-lib
|- common-lib-external1
|- common-lib-external2
```

Ideally, we would like to develop and use all these common libraries with live reload functionality.
What do you suggest we do in these cases?
We used to create an aggregator `pom.xml` to act as a parent of all these maven projects to simulate one big multi-module project.

I also found the `maven.multiModuleProjectDirectory` system property and `maven.top-level-basedir`.
According to the docs:
> This property may be useful to help the Maven resolver identify the top-level Maven project in the workspace. By default, the Maven resolver will be discovering a project’s workspace by navigating the parent-module POM relationship. However, there could be project layouts that are using an aggregator module which isn’t appearing as the parent for its modules. In this case, this property will help the Quarkus Maven resolver to properly discover the workspace.

These do not seem to have an effect here.. shouldn't this property tell quarkus to take the directory as the maven root and resolve these libraries?
I mean.. it does to some degree by our tests, but it fails when comparing the versions from `.m2/repository` and local versions - `SNAPSHOT` vs timestamp as it exists on `SonarQube Nexus` (see the images in reproducer project).

**Comment by MatejPucihar** [comment] 2023-06-21 12:04
I wanted to open a discussion, linking to this issue, for some time now... I won't do that, since the issue became alive now :)

1. I also experience the bug described in the issue.  
2. I really love the hot reload functionality, it is an extremely useful piece of art! (if you don't go mad reading code as complicated as this :) ) 
3. I believe there are some documentation issues (or something is missing) regarding workspace resolution. Maybe, also IDE run configs are not implemented correctly. 

Let me try to explain, since I invested quite some time researching...

Traditionally, when you open a project in IDE (IntelliJ in my case), you import maven modules. That 'tells' your IDE what it must compile/build before you run any program (depending on run configuration ofc.). 
When the java program is started, its class path is modified using some plexus magic.
And then there is quarkus. I do not fully understand how it works, but I know that the tests from continuous testing are not run with the same modified classpath as the original program was run. (testing runs an additional JVM, on which tests are performed, talking about QuarkusTest). So the only option for tests to work correctly is: quarkus must compile them. It doesn't matter, if your IDE compiles, imports modules... Quarkus MUST compile them. Otherwise, you get a user as dumb as me, who looks at quarkus app that uses different classes than IntelliJ compiled ones. 
(Please note, I'm not part of quarkus team, so correct me if I'm wrong)
Quarkus compiles the **'app' module, and also all the modules from the same maven workspace.** e.g. the whole maven multimodule project. (as described in bug report above, only if there are no downloaded *snapshot dependencies in your .m2 dir. )

And another missing part of the jigsaw:
If you have a monorepo (workspace with multiple maven modules, without common parent. These modules can be versioned independently of each other) and you want to work with it...
It is extremely useful to know the concept of aggregator pom.

e.g.
- monorepoDirectory
  - quarkus-app : 1.0.0
  - lib : 2.0.0

In this case, if you want to develop `quarkus-app` simultaneously with `lib` you must link them with an aggregator pom, something like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

    <packaging>pom</packaging>
    <groupId>si.puci</groupId>
    <version>0.0.1-DOESNTMATTER</version>
    <artifactId>aggregator-pom</artifactId>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>quarkus-app</module>
        <module>lib</module>
    </modules>
</project>
```
And then, everything works like a charm! (if there are no downloaded snapshot dependencies in your .m2 ofc. :) )

**Comment by aloubyansky** [comment] 2023-06-21 12:53
Thanks for all the feedback.

* SNAPSHOTs in remote repos - I'll look into that;
* `maven.multiModuleProjectDirectory` where is it documented actually? It looks like an internal property and there is  https://issues.apache.org/jira/browse/MNG-7038 introduce an official one;
* aggregated POMs should work for projects in different coderepos, we could probably introduce an alternative quarkus-specific approach to add more projects into the "live reloadable workspace";
* feel free to create specific issues for the rest, they won't be fixed altogether.

**Comment by rokkolesa** [comment] 2023-06-21 13:31
Thank you for looking into all of this 🙂 

The `maven.multiModuleProjectDirectory` is mentioned here; https://quarkus.io/guides/maven-tooling#top-level-vs-multi-module-project-directory.. it does say "use at your own risk" though..

Aggregator approach is fine by me, but if you find a quarkus-specific approach to this - that is the dream 🙂

I agree on raising separate issues for documentation and devui enhancements.
They would be very useful to understand what is happening with live reload though!
Right now, it just works or it doesn't - you don't know why.

**Comment by aloubyansky** [comment] 2023-06-23 16:02
PR opened to fix the snapshots.

As to the `maven.multiModuleProjectDirectory` it's not something you would set yourself and it's not recommended.  However, `maven.top-level-basedir` property will work in case you need to point to the root `pom.xml` dir.

**Closed** 2023-06-27 09:19 UTC
Labels: kind/bug, area/devmode

**Comment by MatejPucihar** [comment] 2023-10-05 17:52
@maxandersen discussed on devoxx
