### ISSUE TITLE
Graal CE 19.0 fails to build native images

### ISSUE THREAD

**Issue by michael-simons** [quarkusio/quarkus#2410] opened 2019-05-11 15:59 UTC
In several integration tests, i.e. Vertx and my upcoming Neo4j extension, native images cannot be build with Graal CE 19.0:

```
com.oracle.svm.core.util.UserError$UserException: Already registered: java.lang.reflect.Method.getDefaultValue()
	at com.oracle.svm.core.util.UserError.abort(UserError.java:65)
	at com.oracle.svm.core.util.UserError.guarantee(UserError.java:86)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.register(AnnotationSubstitutionProcessor.java:710)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:334)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:298)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:274)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:864)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:819)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:521)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:441)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
```

Environment:

Java:
> java -version 
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190420112649.buildslave.jdk8u-src-tar--b03)
OpenJDK GraalVM CE 19.0.0 (build 25.212-b03-jvmci-19-b01, mixed mode)

Native Image
> $GRAALVM_HOME/bin/native-image --version
GraalVM Version 19.0.0 CE

**Comment by michael-simons** [comment] 2019-05-11 16:50
You'll see those errors when trying to build the vertx example / integration test "by hand" and adding ` -H:+ReportExceptionStackTraces`

I created this option to have this in the Maven and Gradle plugins.

https://github.com/quarkusio/quarkus/pull/2411

**Comment by evacchi** [comment] 2019-05-13 10:00
#2412 is duplicate @Sanne

**Comment by dmlloyd** [comment] 2019-05-17 20:45
Duplicate of #2412.

**Closed by dmlloyd** 2019-05-17 20:45 UTC
Labels: duplicate
