### ISSUE TITLE
When generating Kubernetes files (minikube,openshift,kubernetes) add "common.yml" 

### ISSUE THREAD

**Issue by jonathanvila** [quarkusio/quarkus#23188] opened 2022-01-25 16:31 UTC
### Description

Now when generating the yaml files for Kubernetes , we need to put the fragments to be added on the final generated file ( target/kubernetes/{deployment-target}.yml) 

This leads to have duplicated fragments in 3 files.

### Implementation ideas

Consider a 4th file : common.yml that contains fragments that will be added in every target-deployment yaml.

kubernetes.yml = common.yml + kubernetes.yml + generated files
openshift.yml = common.yml + openshift.yml + generated files
minikube.yml = common.yml + minikube.yml + generated files

**Comment by geoand** [comment] 2022-01-25 18:40
I like the idea!

**Comment by geoand** [comment] 2022-01-26 07:54
This would need a change in Decorate, right @iocanel ?

**Comment by geoand** [comment] 2022-04-12 09:09
cc @Sgitario

**Comment by Sgitario** [comment] 2022-04-12 10:41
I think this is already working as intended. If you place your `common`manifests at `src/main/kubernetes`, the framework will use it as a base to generate the others. 
Wdyt @iocanel ?

**Comment by Sgitario** [comment] 2022-10-19 06:23
Closing this issues because it's duplicated by https://github.com/quarkusio/quarkus/issues/22290

**Closed by Sgitario** 2022-10-19 06:23 UTC
Labels: kind/enhancement, area/kubernetes
