### ISSUE TITLE
Solution for serving files that does not involve storing them in the native image 

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#3018] opened 2019-06-28 09:33 UTC
**Description**
Solution for serving files that does not involve storing them in the native image.
This requirement originates from discussion in https://github.com/quarkusio/quarkus/issues/2917

**Implementation ideas**
Serving via an external directory is obvious way - filesystem path could be configurable via property, same could be done for the endpoint which exposes the content

Expose just files in the root directory vs. all content and directories recursively

Possibility to expose multiple directories under multiple endpoints (mapping 1:1)

Possibility to expose multiple directories under one endpoint, mapping n:1, challenge with duplicate file names and same sub-directories structure

**Comment by gsmet** [comment] 2019-11-13 22:20
I think this is a duplicate of https://github.com/quarkusio/quarkus/issues/3886 for which we have an in-progress PR.

**Closed by gsmet** 2019-11-13 22:20 UTC
Labels: enhancement

**Comment by rsvoboda** [comment] 2019-11-14 11:55
@gsmet this issue originates from https://github.com/quarkusio/quarkus/issues/2917 where @stuartwdouglas said "We do need some solution for serving files that does not involve storing them in the native image (e.g. an external directory)."

It seems https://github.com/quarkusio/quarkus/issues/3886 is also covering this topic

**Comment by gsmet** [comment] 2019-11-14 12:04
@rsvoboda yup, that's why I marked it as a duplicate of #3886 , especially since we have an ongoing PR targeting #3886 .
