### ISSUE TITLE
Make it easier to retry REST client processing exceptions

### ISSUE THREAD

**Issue by kenkania** [quarkusio/quarkus#29594] opened 2022-11-30 19:42 UTC
### Description

One cannot easily use the fault tolerance `@Retry` annotation (which allows specifying exception classes to retry) with the various internal JAX-RS processing exceptions that may be thrown during REST client operations.

This is because:
* they are often wrapped in ProcessingException (alleviated in Quarkus 2.8+ which examines the entire causal chain according to [smallrye's non-compatible mode](https://smallrye.io/docs/smallrye-fault-tolerance/6.1.0/usage/extra.html#_inspecting_exception_cause_chains))
* they are undocumented and subject to change
* they do not share a common ancestry that would make it easier to target similar exceptions

Quarkus, as of 2.14.2, with the resteasy reactive client, throws the following exceptions:

* When hitting REST client connect-timeout:
	javax.ws.rs.ProcessingException caused by io.netty.channel.ConnectTimeoutException
* When hitting REST client read-timeout:
	javax.ws.rs.ProcessingException caused by io.vertx.core.http.impl.NoStackTraceTimeoutException
* When REST client connection refused:
	javax.ws.rs.ProcessingException caused by io.netty.channel.AbstractChannel$AnnotatedConnectException caused by java.net.ConnectException
* When HTTP connection closed:
	io.vertx.core.http.HttpClosedException; in earlier Quarkus versions this is just a VertxException; note this is not wrapped in a ProcessingException; note this has no cause, no stack trace, and no meaningful details of the request that was aborted
* When various SSL issues: (didn't reproduce these)
* Many other cases that I'm not aware of and may want to retry or handle

**Comment by geoand** [comment] 2022-12-01 08:43
I am wondering if we should define some specific exceptions and document them...

**Comment by kostacasa** [comment] 2022-12-01 13:52
I'd love to see an opinionated hierarchy of exceptions for various network conditions.

For example, a connect timeout or SSL exception indicate that the connection with a server was never established with the server. Therefore, those could extend from a RetryableException (in situations where the client is making a POST request). On the other hand, connection resets and read timeouts indicate that the result is ambiguous and the server might have fulfilled the request. So they could extend a different exception class.

Normalizing exceptions in this manner would allow fault tolerance libraries to be used out of the box without writing all the messy exception mapping boilerplate for the REST clients. Considering most Quarkus applications will probably have some kind of a REST client, this would be an incredibly useful quality of life improvement for developers.

**Comment by geoand** [comment] 2022-12-01 13:54
I like the idea. @Ladicek @cescoffier WDYT?

**Comment by Ladicek** [comment] 2022-12-01 14:40
Makes sense to me.

**Comment by kenkania** [comment] 2022-12-01 15:19
Minor correction to initial report: since Quarkus 2.8, the Retry's retryOn applies to exception causes as well as the immediate exception (following smallrye's non-compatible mode). This alleviates the problem of ProcessingException wrapping, although the other difficulties still apply.

**Comment by geoand** [comment] 2023-03-02 15:02
I am actually going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/29594

**Closed by geoand** 2023-03-02 15:02 UTC
Labels: kind/enhancement, area/rest-client, area/fault-tolerance

**Comment by Ladicek** [comment] 2023-03-02 15:29
Surely this is not a duplicate of itself? :-)

**Comment by geoand** [comment] 2023-03-02 15:42
Damn it... Now I forgot what the issue was... Let me go digging...

**Comment by geoand** [comment] 2023-03-02 15:42
Found it: https://github.com/quarkusio/quarkus/issues/24185

**Comment by geoand** [comment] 2023-03-02 15:55
Thanks for keeping me honest :)
