### ISSUE TITLE
After upgrade to 2.7.x from 2.6.3.Final Jackson cannot marshall "Java 8 date/time LocalDateTime"

### ISSUE THREAD

**Issue by guhilling** [quarkusio/quarkus#24371] opened 2022-03-17 11:46 UTC
### Describe the bug

We upgraded our Quarkus project from 2.6.3.Final to 2.7.0.Final. We're using JAX-RS with Jackson (default) and also use "Java 8" DateTime types.
After the upgrade we get the following exception:
```
Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: de.sgservice.awx.inventory.inventory.model.dto.ImmutableUpdateInfoDto["openEncashmentStartDate"])
```
As documented this module should be added automatically and - apart from that - adding it additionally doesn't fix the issue for us.
Dependencies are as follows:
```
    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-orm-panache</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-hibernate-validator</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-liquibase</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-narayana-jta</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-scheduler</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-quartz</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-config-yaml</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-security-jpa</artifactId>
        </dependency>
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>value</artifactId>
            <version>${immutables.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.immutables</groupId>
            <artifactId>serial</artifactId>
            <version>${immutables.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>com.google.code.findbugs</groupId>
            <artifactId>jsr305</artifactId>
            <version>${jsr305.version}</version>
            <scope>provided</scope>
        </dependency>
        <dependency>
            <groupId>org.freemarker</groupId>
            <artifactId>freemarker</artifactId>
            <version>${freemarker.version}</version>
        </dependency>
        <dependency>
            <groupId>org.hibernate</groupId>
            <artifactId>hibernate-jpamodelgen</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jboss.slf4j</groupId>
            <artifactId>slf4j-jboss-logmanager</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-container-image-docker</artifactId>
        </dependency>
```
Quarkus-plugin config:
```
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

### Expected behavior

This should work after the upgrade. No breaking changes were announced.
Apart from that: configuration looks correct to me...

### Actual behavior

The following exception is thrown:
```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Java 8 date/time type `java.time.LocalDateTime` not supported by default: add Module "com.fasterxml.jackson.datatype:jackson-datatype-jsr310" to enable handling (through reference chain: de.sgservice.awx.inventory.inventory.model.dto.ImmutableUpdateInfoDto["openEncashmentStartDate"])
		at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
		at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
		at com.fasterxml.jackson.databind.ser.impl.UnsupportedTypeSerializer.serialize(UnsupportedTypeSerializer.java:35)
		at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
		at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
		at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
		at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
		at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
		at com.fasterxml.jackson.databind.ObjectWriter$Prefetch.serialize(ObjectWriter.java:1518)
		at com.fasterxml.jackson.databind.ObjectWriter.writeValue(ObjectWriter.java:1007)
		at org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider.writeTo(ResteasyJackson2Provider.java:345)
		at org.jboss.resteasy.core.messagebody.AsyncBufferedMessageBodyWriter.asyncWriteTo(AsyncBufferedMessageBodyWriter.java:24)
		at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:87)
		at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.asyncProceed(AbstractWriterInterceptorContext.java:203)
		at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:166)
		at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
		at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
		at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
		at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
		at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
		at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
		at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
		at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
		at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
		at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
		at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
		at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
		at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
		at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
		at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
		at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
		at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
		at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
		at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
		at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
```

### How to Reproduce?

Hard to tell as this is probably not an issue that affects too many users...
For us:
- Worked with 2.6.3.Final
- Doesn't work with any 2.7.x version

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18362.1256]

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12-39) OpenJDK 64-Bit Server VM (build 17.0.1+12-39, mixed mode, sharing)

### Quarkus version or git rev

2.7.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

A similar bug/feature request for automatic adding of `jackson-datatype-jsr310` was addressed some years ago IIRC

**Comment by gsmet** [comment] 2022-03-17 11:49
Please upgrade to 2.7.5.Final, not 2.7.0.Final. If you can still reproduce the issue with 2.7.5.Final, please provide a reproducer.

IIRC, they changed how the modules are handled and we adjusted to it. If you are using a specific ObjectMapper, you might have to adjust your code.

**Comment by guhilling** [comment] 2022-03-17 11:51
The problem also occurs in 2.7.4 and 2.7.5. I just provided the "initial failed version" because that probably could "ring a bell" due to the changes introduced with 2.7.x
We'll try to create a reproducer in the next few days ...

**Comment by geoand** [comment] 2022-03-17 12:22
A reproducer would be great, thanks

**Comment by gsmet** [comment] 2022-03-17 12:30
Yeah, we are definitely still registering them here: https://github.com/quarkusio/quarkus/blob/125879f3023c9c49c575612ccaf145863f90cc21/extensions/jackson/deployment/src/main/java/io/quarkus/jackson/deployment/JacksonProcessor.java#L226 .

So my guess is that there's something fishy somewhere in your specific application, especially since we would have had a lot of complaints if it was broken in the general case.
Can you check that `jackson-datatype-jsr310` is in your classpath? It should come with the `quarkus-jackson` extension.
Also check that Quarkus and Jackson versions are consistent in your classpath. And also the version of the `quarkus-maven-plugin`.

**Comment by guhilling** [comment] 2022-03-17 13:05
Will do!

**Comment by Paul6552** [comment] 2022-03-17 20:30
> So my guess is that there's something fishy somewhere in your specific application, especially since we would have had a lot of complaints if it was broken in the general case. 

Not sure, because of the "modulation" I stopped at 2.6.3 as well and I think many developer stay a few versions below the latest one as well. So let's see :)

I am using LocalDateTime as well in my code. In the next days I will upgrade for testing purposes to the latest version.

**Comment by trfulcher** [comment] 2022-03-17 22:02
This is an interesting thread since I seem to be banging my head on the same issue using 2.7.4-FINAL with quarkus-amazon-lambda-rest and resteasy dependencies. That said I _just_ got it working by declaring quarkus-resteasy-jackson over quarkus-resteasy-jaxb. I'd earlier proved the 3 extra modules were registered by dumping out all registered ones on startup

**Comment by geoand** [comment] 2022-03-23 05:51
Closing this as we don't have a reproducer yet. Feel free to comment with a reproducer so we can have another look and perhaps reopen the issue.

**Closed by geoand** 2022-03-23 05:51 UTC
Labels: kind/bug, env/windows, needs-reproducer, area/jackson

**Comment by mh03r932** [comment] 2022-04-05 20:50
After upgrading to Quarkus 2.7 we also had this problem. The Code that worked on 2.6 suddenly generated 
"java.time.LocalDateTime not supported" errors.

I got to work to reproduce the error from scratch in a clean Quarkus 2.7 jackson quick-start environment. 
After some fiddling I managed to reproduce the problem!

In our case the auto-registration seems to be disabled if we add a custom jackson module containing a constructor that uses 
the com.fasterxml.jackson.core.Version from com.fasterxml.jackson.datatype.jsr310.PackageVersion.Version

```
import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.module.SimpleModule;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.fasterxml.jackson.datatype.jsr310.PackageVersion;
import org.checkerframework.checker.nullness.qual.Nullable;


public class StringNormalizerModule extends SimpleModule {
	private static final long serialVersionUID = 2854608270842290484L;

	public StringNormalizerModule() {
		super(PackageVersion.VERSION); // this is the Problem
		addDeserializer(String.class, new Deserializer());
		addSerializer(String.class, new Serializer());
	}

....
}
```

If I call super() without the Version reference everything works as expected. 
Now granted it seems wrong of us to use this PackageVersion. However the same code worked in 2.6. I suspect the problem might be triggered because Quarkus 2.7 updated jackson.

So  if anyone else has similar problems I would suggest to check their ObjectMapperCustomizer.

For reference here is a reproducer that demonstrates the problem on the master branch and a fixes it on the branch reproducer_fixed:

[reproducer on github](https://github.com/mh03r932/jackson-module-autoregistration-problem-reproducer.git)

**Comment by geoand** [comment] 2022-04-06 06:35
> Now granted it seems wrong of us to use this PackageVersion

Well not exactly, but you have used in the wrong way since you are using `com.fasterxml.jackson.datatype.jsr310.PackageVersion` which is the same one that `JavaTimeModule` uses.
