### ISSUE TITLE
Maven Multi-Module Project And Class Cast Errors

### ISSUE THREAD

**Issue by InfoSec812** [quarkusio/quarkus#5970] opened 2019-12-05 16:48 UTC
**Describe the bug**
I have a multi-module Maven project (https://github.com/InfoSec812/quarkus-openapi-todo-demo) which has the following structure:

todo:
  - jsclient
  - javaclient
  - server
  - frontend
  - implementation

The `server`, `jsclient`, and `javaclient` are all generated using OpenAPI Generator and custom templates to make them "Quarkified".

I have added Jandex indexing to the `server` and I then implement the Service interface in the `implementation` project.

When I compile to a runnable JAR, everything is now working (with the addition of Jandex Maven Plugin), but the `quarkus:dev` mode fails with Class Cast errors like the following:

```
java.lang.ClassCastException: com.redhat.quarkus.demo.todo.TodosApiServiceImpl_ClientProxy cannot be cast to com.redhat.demos.quarkus.openapi.todo.api.TodosApiService
	at com.redhat.demos.quarkus.openapi.todo.api.TodosApi_Bean.create(TodosApi_Bean.zig:134)
	at com.redhat.demos.quarkus.openapi.todo.api.TodosApi_Bean.create(TodosApi_Bean.zig:209)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:80)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at com.redhat.demos.quarkus.openapi.todo.api.TodosApi_Bean.get(TodosApi_Bean.zig:241)
	at com.redhat.demos.quarkus.openapi.todo.api.TodosApi_Bean.get(TodosApi_Bean.zig:170)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:355)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:367)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:222)
	at io.quarkus.arc.impl.ArcContainerImpl$1.get(ArcContainerImpl.java:219)
	at io.quarkus.arc.runtime.ArcRecorder$2$1.create(ArcRecorder.java:79)
	at io.quarkus.resteasy.common.runtime.QuarkusConstructorInjector.construct(QuarkusConstructorInjector.java:56)
	at org.jboss.resteasy.plugins.server.resourcefactory.POJOResourceFactory.createResource(POJOResourceFactory.java:69)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:363)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:118)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:74)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Resulted in: java.lang.RuntimeException: Error injecting com.redhat.demos.quarkus.openapi.todo.api.TodosApiService com.redhat.demos.quarkus.openapi.todo.api.TodosApi.service
	at com.redhat.demos.quarkus.openapi.todo.api.TodosApi_Bean.create(TodosApi_Bean.zig:147)
	... 30 more
Resulted in: org.jboss.resteasy.spi.UnhandledException: java.lang.RuntimeException: Error injecting com.redhat.demos.quarkus.openapi.todo.api.TodosApiService com.redhat.demos.quarkus.openapi.todo.api.TodosApi.service
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:381)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:503)
	... 13 more
```

**Expected behavior**
Dev Mode should work the same as the runnable JAR.

**Actual behavior**
ClassCastException as detailed above

**To Reproduce**
The instructions are in the project linked above.

**Configuration**
```properties
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.url=jdbc:h2:mem:todo
quarkus.datasource.username=sa
quarkus.datasource.password=password

quarkus.hibernate-orm.database.generation = drop-and-create

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.path=/swagger
mp.openapi.scan.disable=true

quarkus.http.cors=true
```

**Screenshots**
![image](https://user-images.githubusercontent.com/99691/70255468-d9622100-1754-11ea-88aa-8bd84ce5fad2.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
   - `Linux Deven-X1E 5.3.0-23-generic #25-Ubuntu SMP Tue Nov 12 09:22:33 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
   - ```
     openjdk version "1.8.0_232-ea"
     OpenJDK Runtime Environment (build 1.8.0_232-ea-8u232-b09-0ubuntu1-b09)
     OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)
     ```
 - GraalVM version (if different from Java): 
   ```
   ${GRAALVM_HOME}/bin/java -version
   openjdk version "1.8.0_232"
   OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
   OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
   ```
 - Quarkus version or git rev: 1.0.1.Final

**Additional context**

**Comment by gsmet** [comment] 2019-12-05 17:49
@mkouba could you have a look and check if it's an issue with ArC or something else?

**Comment by mkouba** [comment] 2019-12-06 07:59
@InfoSec812 I've just tried to build the project with `mvn clean install` and I get:
```
[INFO] --- openapi-generator-maven-plugin:4.2.1:generate (resteasy-api) @ todo-server ---
[WARNING] Exception while reading:
java.lang.RuntimeException: Could not find /opt/source/protean/bugs/issue-5970/quarkus-openapi-todo-demo/server/../openapi.yml on the classpath
    at io.swagger.v3.parser.util.ClasspathHelper.loadFileFromClasspath (ClasspathHelper.java:31)
    at io.swagger.v3.parser.OpenAPIV3Parser.readWithInfo (OpenAPIV3Parser.java:149)
    at io.swagger.v3.parser.OpenAPIV3Parser.readLocation (OpenAPIV3Parser.java:58)
    at io.swagger.parser.OpenAPIParser.readLocation (OpenAPIParser.java:16)
```
And I get the same error when running the `1-build-js-client.sh ` script. Is there any further configuration required? 

Should I use the master or the `switch-to-maven-multimodule` branch?

**Comment by mkouba** [comment] 2019-12-09 09:12
@InfoSec812 I still have problems to run the app 

```
```

https://github.com/quarkusio/quarkus/issues/5992

**Comment by mkouba** [comment] 2019-12-09 09:21
Hm, actually I'm not so sure I will be able to send a PR so soon. It seems that the problem is a bit more complicated.

**Comment by mkouba** [comment] 2019-12-09 10:48
@InfoSec812 after some debugging I found out that the dev mode fails because you're using properties in the dependency definition for the `todo-server` module in the `implementation/pom.xml`: https://github.com/InfoSec812/quarkus-openapi-todo-demo/blob/master/implementation/pom.xml#L58-L62

I've tried to hard-code the `groupId` and `version` and it works fine.

I'm not sure whether it's legal to use properties to specify `groupId` but apparently it's not supported ATM.

CC @aloubyansky who is our expert in this area and knows much more about this topic!

**Comment by aloubyansky** [comment] 2019-12-09 11:02
At this point, our bootstrap LocalWorkspace impl does not support `parent.project.XXX` props. Changing them to `project.XXX` (which is ok in the given example) can be a workaround.

**Comment by geoand** [comment] 2019-12-09 11:28
Can we maybe provide a better error message?

**Comment by geoand** [comment] 2023-08-30 10:52
I am going to close this as it seems pretty out of date

**Closed by geoand** 2023-08-30 10:52 UTC
Labels: kind/bug
