### ISSUE TITLE
Querydsl integration to Panache

### ISSUE THREAD

**Issue by kivan-mih** [quarkusio/quarkus#5896] opened 2019-12-01 09:49 UTC
In Spring Data JPA I used Spring Data Querydsl(http://www.querydsl.com) plugin to allow typesafe compile-time queries and out of the box IDE autocompletion. Panache is ok, but it's not type-safe, so extending it with something like Querydsl predicates could be a good idea.

**Comment by loicmathieu** [comment] 2019-12-02 10:03
There is already an issue for this: #4016
You can vote for it (+1 on the issue description).

There is also a discussion about optional predicate inside of Panache (#2303) and query by specification (#3965) / example (#4015) you can vote for the one you prefere :)

I close this issue as duplicate of #4016

**Closed by loicmathieu** 2019-12-02 10:03 UTC
Labels: component:panache, duplicate, enhancement
