### ISSUE TITLE
Gradle - @QuarkusIntegrationTest don't see @QuarkusTestResource from parent class/interface

### ISSUE THREAD

**Issue by bitxon** [quarkusio/quarkus#27511] opened 2022-08-25 14:10 UTC
### GitHub repo with Example
https://github.com/bitxon/quarkus-gradle-failed-native-test
https://github.com/bitxon/quarkus-gradle-failed-native-test/actions

### Description
In case of **Gradle**  QuarkusTest and QuarkusIntegrationTest are being stored in different folders
`src/native-test` - `@QuarkusIntegrationTest`
`src/test` - `@QuarkusTest`
In case of **Maven** QuarkusTest and QuarkusIntegrationTest are being stored in same folder
Looks like this is the reason why it works in Maven

Hierarchy:
```java
// src/test
@QuarkusTestResource(PostgresTestResource.class)
public abstract class AbstractQuarkusTest {}
// src/test
@QuarkusTest
public class GreetingResourceTest extends AbstractQuarkusTest {
    @Test void someTest() {...}
}
// src/native-test
@QuarkusIntegrationTest
public class GreetingResourceIT extends GreetingResourceTest {}
``` 
### Issue
Execution of`./gradlew testNative` - will failed 

### Unexpected trick that helps to solve problem 
If we will add any class annotated with `@QuarkusTestResource(PostgresTestResource.class)` near the GreetingResourceIT, GreetingResourceIT will start working
```java
// src/native-test
@QuarkusTestResource(PostgresTestResource.class)
public class SomeOtherClass {}
// src/native-test
@QuarkusIntegrationTest
public class GreetingResourceIT extends GreetingResourceTest {}
``` 

### How to Reproduce?

1. Clone example: https://github.com/bitxon/quarkus-gradle-failed-native-test
2. Navigate to folder `gradle-project`
3. Run `./gradlew testNative`

### Output of `uname -a` or `ver`

MacAir Darwin Kernel Version 21.6.0 (arm64)

### Output of `java -version`

openjdk version "17.0.2"

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.11.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by glefloch** [comment] 2022-08-25 14:32
Thanks for reporting this issue @bitxon. 
In order to run `@QuarkusIntegrationTets` you can use the `quarkusIntTest` task with your test class under `src/integrationTest/java`. 
The `testNative` task will force a native packaging of your application.

**Comment by glefloch** [comment] 2022-08-25 15:33
Yes I have seen this too. 
It looks like devservices don't start for integration tests. Is it expected @geoand ?

**Comment by geoand** [comment] 2022-08-25 16:02
It is not expected - dev services should work for integration tests too

**Comment by glefloch** [comment] 2022-08-25 18:50
Ok I will investigate it then.

**Comment by glefloch** [comment] 2022-09-05 13:44
Actually, I don't understand why this is working on maven. Dev services starts when configuration is missing. 

However, in your `application.properties` file, you have configured an URL / username / password (https://github.com/bitxon/quarkus-gradle-failed-native-test/blob/main/gradle-project/src/main/resources/application.properties#L6-L8).

 If you remove those configuration, then dev service starts correctly.

@geoand, is it expected that we ignore datasource properties and always start dev services for integration tests ?

**Comment by geoand** [comment] 2022-09-05 13:50
@glefloch  no, dev services should only kick in when no URL is provided

**Comment by bitxon** [comment] 2022-09-05 15:20
@glefloch If we remove `quarkus.datasource.jdbc.url` -> nativeTest is working fine

**Comment by geoand** [comment] 2022-09-05 15:23
That is the expected behavior

**Comment by glefloch** [comment] 2022-09-06 07:26
Ok, I will close this one then.

**Closed by glefloch** 2022-09-06 07:26 UTC
Labels: kind/bug, area/gradle, area/testing
