### ISSUE TITLE
Enlisted connection used without active transaction after Migration to Quarkus 2.0.0

### ISSUE THREAD

**Issue by KaiSuchomel** [quarkusio/quarkus#18450] opened 2021-07-06 13:04 UTC
## Describe the bug
After migrated to the newest Version(2.0.0) we see a lot of the following exceptions in our logs:
```
2021-07-06 14:48:02,148 WARN  [com.arj.ats.jta] (QuarkusQuartzScheduler_Worker-3) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:b391:60e45102:0, node_name=quarkus, branch_uid=0:ffff7f000101:b391:60e45102:3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@1fae3ec5) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:97)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.commit$$superforward1(CDIDelegatingTransactionManager_Subclass.zig:386)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass$$function$$6.apply(CDIDelegatingTransactionManager_Subclass$$function$$6.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)

```
```
2021-07-06 14:48:02,157 INFO  [org.qua.cor.JobRunShell] (QuarkusQuartzScheduler_Worker-3) Job io.quarkus.scheduler.Scheduler.1_io.gec.test.control.GiftController_ScheduledInvoker_schedule_c3705fc8cd7ee35acd13c98d8d089325355c7af1 threw a JobExecutionException: : org.quartz.JobExecutionException: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method [See nested exception: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method]
	at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:409)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at io.gec.test.control.GiftController_Subclass.doTransactionalStuff(GiftController_Subclass.zig:299)
	at io.gec.test.control.GiftController.schedule(GiftController.java:32)
	at io.gec.test.control.GiftController_Subclass.schedule$$superforward1(GiftController_Subclass.zig:214)
	at io.gec.test.control.GiftController_Subclass$$function$$2.apply(GiftController_Subclass$$function$$2.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.gec.test.control.GiftController_Subclass.schedule(GiftController_Subclass.zig:369)
	at io.gec.test.control.GiftController_ClientProxy.schedule(GiftController_ClientProxy.zig:188)
	at io.gec.test.control.GiftController_ScheduledInvoker_schedule_c3705fc8cd7ee35acd13c98d8d089325355c7af1.invokeBean(GiftController_ScheduledInvoker_schedule_c3705fc8cd7ee35acd13c98d8d089325355c7af1.zig:48)
	at io.quarkus.arc.runtime.BeanInvoker.invoke(BeanInvoker.java:20)
	at io.quarkus.quartz.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:407)
	... 2 more
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1307)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:97)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.commit$$superforward1(CDIDelegatingTransactionManager_Subclass.zig:386)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass$$function$$6.apply(CDIDelegatingTransactionManager_Subclass$$function$$6.zig:24)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:62)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
	at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Subclass.commit(CDIDelegatingTransactionManager_Subclass.zig:983)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:313)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:164)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.gec.test.control.GiftController_Subclass.doTransactionalStuff(GiftController_Subclass.zig:278)
	... 17 more
	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
		... 40 more
	Caused by: java.sql.SQLException: Enlisted connection used without active transaction
		at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:352)
		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:321)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
		... 46 more
```

### Expected behavior
No Exception should occur on the Console Log

### Actual behavior
With Version 1.13.7 of Quarkus no Exception is thrown on the Console Log
With Version 2.0.0 of Quarkus the above mentioned Exceptions are thrown on the Console Log

## To Reproduce
Clone Project: https://github.com/KaiSuchomel/quarkus-without-active-transaction-issue

1. Start Database:
`docker run -d -e POSTGRES_USER=hibernate -e POSTGRES_PASSWORD=hibernate -e POSTGRES_DB=hibernate_db -e POSTGRES_PORT=5432 --name mydb -p 5432:5432 postgres`
2. Start Kafka
`docker-compose up`
3. start quarkus
`mvn clean quarkus:dev`

Switch Quarkus Version via pom.xml (current the 2.0.0 Version ist set)
```
        <quarkus.platform.version>2.0.0.Final</quarkus.platform.version>
        <!--<quarkus.platform.version>1.13.7.Final</quarkus.platform.version>-->
```
or
```
mvn -Dquarkus.platform.version=1.13.6.Final clean quarkus:dev
```
### Configuration
see application.properties at linked project

### Output of `uname -a` or `ver`
Linux 5.4.0-77-generic #86-Ubuntu SMP Thu Jun 17 02:35:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### Output of `java -version`
openjdk version "14.0.1" 2020-04-14
OpenJDK Runtime Environment (build 14.0.1+7)
OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)
### Quarkus version or git rev
1.13.7 vs 2.0.0
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
mvn

**Comment by KaiSuchomel** [comment] 2021-07-06 13:07
@cescoffier FYI

**Comment by cescoffier** [comment] 2021-07-06 13:27
Thanks,

To be honest,  I don't understand. `emitter.send()` enqueue the message into a queue read from another thread.

It seems to work if you use `emitter.send(aProducedGift.toString()).toCompletableFuture().join();`, which basically wait until the message is written into Kafka. I'm thinking it's actually safer as it would roll back the insertion in this case.

**Comment by KaiSuchomel** [comment] 2021-07-06 14:10
@cescoffier  Hey Clement, thanks for your quick Response.
The UseCase that we are archieving with the code is, after we have for example saved an entity the entity is send via Kafka to another microservice. I have changed the Sources so far that we need to send an Message with a KafkaKey instead of a simple String. Can you have a look at the implementation, perhaps you have also hint for this situation.
Thanks

**Comment by cescoffier** [comment] 2021-07-06 15:53
Do you mean doing something like:

```
emitter.send(Record.of("my-key", myGift)).toCompletableFuture().join();
```

**Comment by ChMThiel** [comment] 2021-07-07 05:53
Why won't it work with Microprofile's Message-Interface?
```
Message<T> message = Message.of(aMessage, Metadata.of(metadata));
aEmitter.send(message);
message.getAck().get().toCompletableFuture().join();
```
To switch to smallrye's Record-Class would cause a lot of refactoring...

**Comment by cescoffier** [comment] 2021-07-07 06:12
That would work too.

**Comment by ChMThiel** [comment] 2021-07-07 06:19
no it won't ;(
```
    @Transactional
    public void doTransactionalStuff(Gift aProducedGift) {
        System.err.println("GiftController.doTransactionalStuff: " + aProducedGift);
        em.persist(aProducedGift);
        OutgoingKafkaRecordMetadata<String> metadata = OutgoingKafkaRecordMetadata.<String>builder()
                .withKey("my-key")
                .build();
        Message<String> message = Message.of(aProducedGift.toString(), Metadata.of(metadata));
        emitter.send(message);
        message.getAck().get().toCompletableFuture().join();
    }
```
throws 
```
2021-07-07 08:17:13,012 WARN  [com.arj.ats.arjuna] (QuarkusQuartzScheduler_Worker-3) ARJUNA012094: Commit of action id 0:ffff7f000101:8f57:60e546d0:96 invoked while multiple threads active within it.
2021-07-07 08:17:13,012 WARN  [com.arj.ats.arjuna] (QuarkusQuartzScheduler_Worker-3) ARJUNA012107: CheckedAction::check - atomic action 0:ffff7f000101:8f57:60e546d0:96 commiting with 2 threads active!
2021-07-07 08:17:13,013 WARN  [com.arj.ats.jta] (QuarkusQuartzScheduler_Worker-3) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff7f000101:8f57:60e546d0:96, node_name=quarkus, branch_uid=0:ffff7f000101:8f57:60e546d0:99, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@1f7f2659) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
...
```

**Comment by cescoffier** [comment] 2021-07-07 06:47
Ah yes, you can't retrieve the ack like that. You will. We'd to pass your own ack function. Let me craft an example.

**Comment by cescoffier** [comment] 2021-07-07 06:49
Try with:
```
 @Transactional
    public void doTransactionalStuff(Gift aProducedGift) {
        System.err.println("GiftController.doTransactionalStuff: " + aProducedGift);
        CompletableFuture<Void> future = new CompletableFuture();
        em.persist(aProducedGift);
        OutgoingKafkaRecordMetadata<String> metadata = OutgoingKafkaRecordMetadata.<String>builder()
                .withKey("my-key")
                .build();
        Message<String> message = Message.of(aProducedGift.toString(), Metadata.of(metadata), () ->  future);
        emitter.send(message);
        future.join();
    }
```

**Comment by ChMThiel** [comment] 2021-07-07 08:13
Hello Clement,

Thank your for your example and your prompt help.
But it seems, the ack never comes... the 'future.join()' waits for ever. So the transaction is not closed (because the method never ends)....Then the next timer triggers a new 'doTransactionalStuff' with a new Transaction, until eventually there are no more open connections and Exceptions are thrown....
I tried 'future.get(500L, TimeUnit.MILLISECONDS);' instead of 'join'....then always a TimeoutException occurs.

any ideas?

**Comment by ChMThiel** [comment] 2021-07-07 08:22
```
        Record<String, String> r = Record.of("my-key", aProducedGift.toString());
        emitter.send(r).toCompletableFuture().get(500L, TimeUnit.MILLISECONDS);
```
Works as a charm...the completableFuture finishes in time, the method is finished, transaction is closed.

**Comment by cescoffier** [comment] 2021-07-07 19:47
Ah, yes, m'y ack function is incorrect.

 @Transactional
    public void doTransactionalStuff(Gift aProducedGift) {
        System.err.println("GiftController.doTransactionalStuff: " + aProducedGift);
        CompletableFuture<Void> future = new CompletableFuture();
        em.persist(aProducedGift);
        OutgoingKafkaRecordMetadata<String> metadata = OutgoingKafkaRecordMetadata.<String>builder()
                .withKey("my-key")
                .build();
        Message<String> message = Message.of(aProducedGift.toString(), Metadata.of(metadata), () ->  { future.complete(null); return new CompletableFuture()});
        emitter.send(message);
        future.join();
    }

**Comment by ChMThiel** [comment] 2021-07-08 08:29
Hello Clement,
using your last code, we cannot reproduce the bug in our test-project.
Nevertheless in our real project every once in a while the exception occurs in our logs:
```
2021-07-07 08:17:13,012 WARN  [com.arj.ats.arjuna] (QuarkusQuartzScheduler_Worker-3) ARJUNA012094: Commit of action id 0:ffff7f000101:8f57:60e546d0:96 invoked while multiple threads active within it.
2021-07-07 08:17:13,012 WARN  [com.arj.ats.arjuna] (QuarkusQuartzScheduler_Worker-3) ARJUNA012107: CheckedAction::check - atomic action 0:ffff7f000101:8f57:60e546d0:96 commiting with 2 threads active!

```
Maybe there is some internal race-condition?
Also I'm not quite sure, what's the difference of using `Record` or `Message` (with the Metadata- and Future-parameters posted in your last comment). How can this affect the Transaction-handling?

**Comment by cescoffier** [comment] 2021-07-11 16:35
I'm not totally sure. A Record is a payload, so it's wrapped into a message (automatically). So, in theory: no differences.

**Comment by OleKsimov** [comment] 2021-08-10 17:45
What works for me is to move emitter usage to another public method and use separate transaction for this method (@Transactional(TxType.REQUIRES_NEW)). Despite there is no database interaction in such a method, the main flow somehow handles this part separately and allows the main transaction to be committed.

**Comment by cescoffier** [comment] 2021-08-17 12:23
I looked into it a bit more. The reproducer sends a message that is processed asynchronously. Messages sent using an emitter are always handled asynchronously - see https://quarkus.io/blog/reactive-messaging-emitter/. However, the transaction ends at the end of the method so, **before** the message being processed. This is not correct and the error message is telling that the object is touched outside of a transaction.  It may have been working before because the transaction was still "active" (delay, or timing being slightly different), but it was wrong.

The solution is to make the @Transactional method returns a CompletionStage<Void> so the transaction is committed when the message is acknowledged. 

So, it works if you update the code to:

```
@Transactional
    public CompletionStage<Void> doTransactionalStuff(Gift aProducedGift) {
        System.err.println("GiftController.doTransactionalStuff: " + aProducedGift);
        CompletableFuture<Void> acked = new CompletableFuture<>();
        Message<String> m = Message.of(aProducedGift.toString(), Metadata.of(OutgoingKafkaRecordMetadata.<String>builder()
                    .withKey(UUID.randomUUID().toString()).build()), () -> {
                        acked.complete(null); return CompletableFuture.completedStage(null);
                    }, t -> {
                        acked.completeExceptionally(t);
                        return CompletableFuture.completedFuture(null);
                    });
        em.persist(aProducedGift);
        emitter.send(m);
        return acked;
    }
```

I would recommend using records instead of a Message so it would simplify that code:

```java
@Channel("giftsOut")
@OnOverflow(OnOverflow.Strategy.BUFFER)
@Broadcast
Emitter<Record<String, String>> emitter;

@Transactional
public CompletionStage<Void> doTransactionalStuff(Gift aProducedGift) {
    Record<String, String> record = Record.of(UUID.randomUUID().toString(), aProducedGift.toString());    
    em.persist(aProducedGift);
    return emitter.send(record);
}
```

**Closed by cescoffier** 2021-08-17 12:23 UTC
Labels: kind/bug, triage/needs-triage

**Comment by wicksim** [comment] 2021-09-15 05:07
What if we are not returning a reactive CompletionStage from our transactional method and don't want to change that at the moment? Just modified your example:

```
@Channel("giftsOut")
@OnOverflow(OnOverflow.Strategy.BUFFER)
@Broadcast
Emitter<Record<String, String>> emitter;

@Transactional
public Gift doTransactionalStuff(Gift aProducedGift) {
    Record<String, String> record = Record.of(UUID.randomUUID().toString(), aProducedGift.toString());    
    em.persist(aProducedGift);
    emitter.send(record);
    return aProducedGift;
}
```

Just doing `emitter.send(record).toCompletableFuture().join();` didn't resolve the problem. Is there any other way?

We now implemented `@Transactional(TxType.REQUIRES_NEW)`-workaround and moved emitting to an other bean, but are not sure if this is the cleanest way...

**Comment by cescoffier** [comment] 2021-09-15 18:15
What is calling the doTransactionalStuff method?

**Comment by cescoffier** [comment] 2021-09-15 18:16
Not that at the moment, even if the emission fails it won't affect your transaction. So even if your message can't be sent to Kafka (or whatever broker), your transaction will not be rolled back.

**Comment by wicksim** [comment] 2021-09-16 10:25
It is called from a REST-Resource. So i guess changing to reactive-based Resources would save that problem?
