### ISSUE TITLE
support azure app config similar to other config stores 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#10400] opened 2020-07-01 10:57 UTC
**Description**
support azure config similar to spring cloud config and other config stores

https://docs.microsoft.com/en-us/azure/azure-app-configuration/overview

**Comment by geoand** [comment] 2020-07-22 13:52
@maxandersen did you get any information on this? Is this something we want soon?

**Comment by maxandersen** [comment] 2020-07-22 13:56
No, no additional info besides what you saw that it would be nice to have in.

**Comment by geoand** [comment] 2020-07-22 14:00
The question then becomes, what sort of priority are we thinking about this one? Because uf we want it in 1.7, then I'd probably have to bump this to the top in order to get it in time due to various time constraints.

**Comment by RHodzelmans** [comment] 2020-07-30 13:31
So one of my customers is talking about that all Azure docs are pointing to Spring Boot. If we want to offer a developer low friction onramp to run Quarkus on Azure, they need doc examples that are feature comparable with the documentation about Spring Boot. So that if they want to adopt Quarkus, they get friction, if they want to deploy Spring Boot examples galore. E.g. https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/deploy-spring-boot-java-app-on-kubernetes

**Comment by geoand** [comment] 2020-07-30 13:35
cc @jclingan

**Comment by edco29** [comment] 2021-01-21 20:57
Hi there , is there  any documentation with Quarkus  instead SpringBoot ?

**Comment by geoand** [comment] 2021-01-22 06:24
The issue is still open as https://github.com/quarkusio/quarkus/pull/11106 was never completed

**Comment by radcortez** [comment] 2022-01-07 22:58
Closing in favor of https://github.com/quarkiverse/quarkus-config-extensions/issues/45

**Closed by radcortez** 2022-01-07 22:58 UTC
Labels: kind/enhancement, area/config
