### ISSUE TITLE
Parsing empty parameter to non String type should become null instead of 404 

### ISSUE THREAD

**Issue by blazmrak** [quarkusio/quarkus#42414] opened 2024-08-08 14:40 UTC
### Description

Right now, parsing of non String types throws 404 if parameter is empty (e.g. `?param=` and `@RestQuery LocalDate param`), but works when `param` is omitted or when `param` is the correct value. 

This is technically correct and kind of expected, but it clashes with default browser behavior, which sends empty params in the request. In my opinion it would be better if empty value would be treated as null for non String types.

### Implementation ideas

One way of doing this that would not break Jakarta spec and be backwards compatible is to add a configuration option/annotation and update the converters.

It is probably important to make this configuration option work for a subset of the default known types, that fail when parsing empty String, not for all non String types, as this might cause issues for custom types.

**Comment by geoand** [comment] 2024-08-09 05:47
@FroMage WDYT?

**Comment by FroMage** [comment] 2024-08-09 08:41
Dupe of https://github.com/quarkusio/quarkus/issues/40833?

**Comment by FroMage** [comment] 2024-08-09 08:43
Oh, the other is for form params, and this one for query params. But it's the same issue, really.

**Comment by geoand** [comment] 2024-08-09 08:43
Ah, good point!

**Closed** 2024-08-09 08:44 UTC
Labels: triage/duplicate, kind/enhancement, area/resteasy-reactive
