### ISSUE TITLE
Quarkus Scheduled at wrong interval

### ISSUE THREAD

**Issue by DemiusAcademius** [quarkusio/quarkus#9112] opened 2020-05-06 08:41 UTC
Wrong scheduling interval

With annotation @Scheduled(cron="{cloudprint.schedule}")
and application.yaml config:

```
cloudprint:
    schedule: "*/5 * * * * ?"
```

**Expected behavior**
must run  every 5 seconds

**Actual behavior**
scheduled task runs every 10 seconds

 - version:  1.4.2
 - gradlew: 6.3 
 - quarkusDev

**Comment by gsmet** [comment] 2020-05-06 09:15
@DemiusAcademius could you prepare a small reproducer and attach it to the issue?

/cc @mkouba

**Comment by mkouba** [comment] 2020-05-06 09:58
@DemiusAcademius Have you tried the `0/5 * * * * ?` syntax? We use quartz CRON syntax by default and it could be that it does not support `*/5` (note that slash `/` itself is a non-standard character).

Anyway, a reproducer would be really helpful.

**Comment by DemiusAcademius** [comment] 2020-05-06 10:15
I create a reproduces with empty job method and identical application.yaml. It works every 5 secs!
```
2020-05-06 13:09:10,004 INFO  [com.sia.wor.Job] (executor-thread-1) job started
2020-05-06 13:09:15,004 INFO  [com.sia.wor.Job] (executor-thread-1) job started
2020-05-06 13:09:20,001 INFO  [com.sia.wor.Job] (executor-thread-1) job started
```

**Comment by DemiusAcademius** [comment] 2020-05-06 10:16
But for real job log another:

```
2020-05-06 13:14:50,003 INFO  [com.sia.wor.Job] (executor-thread-1) job started
Receive token
2020-05-06 13:14:52,255 INFO  [com.sia.wor.Job] (executor-thread-1) tremol-fp-15-apacanal-1 : PrinterState(fmReadOnly=false, powerDownInOpenedFiscalReceipt=false, printerNotReadyOrOverheated=false)
2020-05-06 13:14:52,619 INFO  [com.sia.wor.Job] (executor-thread-1) job ended
2020-05-06 13:15:00,002 INFO  [com.sia.wor.Job] (executor-thread-1) job started
2020-05-06 13:15:00,611 INFO  [com.sia.wor.Job] (executor-thread-1) tremol-fp-15-apacanal-1 : PrinterState(fmReadOnly=false, powerDownInOpenedFiscalReceipt=false, printerNotReadyOrOverheated=false)
2020-05-06 13:15:00,627 INFO  [com.sia.wor.Job] (executor-thread-1) job ended
```

**Comment by DemiusAcademius** [comment] 2020-05-06 10:17
```
2020-05-06 13:15:10,001 INFO  [com.sia.wor.Job] (executor-thread-1) job started
2020-05-06 13:15:10,606 INFO  [com.sia.wor.Job] (executor-thread-1) tremol-fp-15-apacanal-1 : PrinterState(fmReadOnly=false, powerDownInOpenedFiscalReceipt=false, printerNotReadyOrOverheated=false)
2020-05-06 13:15:10,630 INFO  [com.sia.wor.Job] (executor-thread-1) job ended
```

Execution of job takes ~ 2-3 seconds

**Comment by DemiusAcademius** [comment] 2020-05-06 10:17
and I try 0/5 * * * * ? syntax

**Comment by mkouba** [comment] 2020-05-06 10:21
> But for real job log another:

Hm, I can smell a bug in our scheduling logic...

**Comment by DemiusAcademius** [comment] 2020-05-06 10:26
I added code:
```
try {
            Thread.sleep(2000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
```
to reproduces. All work OK

**Comment by DemiusAcademius** [comment] 2020-05-06 10:27
Real code of cronjob class:
java```
package com.sia.work;

import com.sia.beans.*;
import com.sia.domain.FPJob;
import com.sia.domain.FPJobDetail;
import com.sia.domain.FPPrinterStatus;
import com.sia.repos.FiscalPrinterRepo;
import com.sia.restclient.api.model.state.PrinterState;
import com.sia.restclient.api.requests.FiscalData;
import com.sia.restclient.api.requests.PaymentItem;
import io.quarkus.scheduler.Scheduled;
import lombok.extern.slf4j.Slf4j;

import javax.enterprise.context.ApplicationScoped;
import javax.inject.Inject;
import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.*;
import java.util.stream.Collectors;

@Slf4j
@ApplicationScoped
public class Job {

    @Inject
    CloudprintService printService;

    @Inject
    FiscalPrinterRepo fiscalPrinterRepo;

    @Scheduled(cron="{cloudprint.schedule}")
    void runSync() {
        LOG.info("job started");
        var readyPrinters = prepareReadyPrinters();
        if (readyPrinters.size() == 0) return;

        var jobs = fiscalPrinterRepo.loadAllPendingJobs();
        for (var job : jobs) {
            var printerId = job.getPrinterId();
            LOG.info("job " + job.getJob() + " for printer " + printerId);
            if (readyPrinters.containsKey(printerId)) {
                LOG.info("  printer is ready");
                var fpStatus = readyPrinters.get(printerId);
                readyPrinters.remove(printerId);

                prepareJob(fpStatus, job);
                processJob(job);
                finalizeJob(fpStatus, job);
            }
        }
        LOG.info("job ended");
    }

    private Map<String, FPPrinterStatus> prepareReadyPrinters() {
        try {
            var printers = printService.listPrinters();

            var readyPrinters = new HashMap<String, FPPrinterStatus>();

            for (var info : printers) {
                try {
                    var state = printService.getPrinterState(info.getId());

                    LOG.info(info.getId() + " : " + state.toString());
                    var fpStatus = fiscalPrinterRepo.updatePrinterStatus(info.getId(), state, 200, null);

                    var isReady = !fpStatus.isProcessing() &&
                            !state.isFmReadOnly() &&
                            !state.isPowerDownInOpenedFiscalReceipt() &&
                            !state.isPrinterNotReadyOrOverheated();
                    if (isReady) readyPrinters.put(info.getId(), fpStatus);

                } catch (CloudprintException e) {
                    LOG.error(e.errorResponse.getResponse());
                    fiscalPrinterRepo.updatePrinterStatus(info.getId(), PrinterState.EMPTY, e.status, e.errorResponse.getData().getException());
                }
            }
            fiscalPrinterRepo.updateServiceStatus(200, null);
            return readyPrinters;
        } catch (CloudprintException e) {
            LOG.error(e.errorResponse.getResponse());
            fiscalPrinterRepo.updateServiceStatus(e.status, e.errorResponse.getData().getException());
        }
        return Collections.emptyMap();
    }

    private void prepareJob(FPPrinterStatus status, FPJob job) {
        status.setProcessing(true);
        job.setSysdateRegistered(new Timestamp(System.currentTimeMillis()));
        fiscalPrinterRepo.saveJobStatus(status, job);
    }

    private void finalizeJob(FPPrinterStatus status, FPJob job) {
        status.setProcessing(false);
        job.setSysdateProcessed(new Timestamp(System.currentTimeMillis()));
        fiscalPrinterRepo.saveJobStatus(status, job);
    }

    private void processJob(FPJob job) {
        var printerId = job.getPrinterId();
        var operatorId = job.getOperatorId();
        job.setStatus(999);

        try {
            switch (job.getJob()) {
                case "XREP" -> printService.printDailyReport(printerId, DailyReportType.X);
                case "ZREP" -> printService.printDailyReport(printerId, DailyReportType.Z);
                case "FREC" -> {
                    var paymentType = job.getPaymentType();
                    if (checkPaymentType(paymentType)) {
                        job.setErrorMessage("Not recognized PAYMENT TYPE: " + job.getPaymentType());
                        return;
                    }

                    var details = generateJobDetails(job);

                    var items =
                            job.getPaymentItems()
                                    .stream()
                                    .map(item -> {
                                        var tax = Map.of("taxRate", item.getTaxRate());
                                        return new PaymentItem(
                                                item.getName(),
                                                item.getUnitPrice(),
                                                item.getQuantity(),
                                                "noCorrection", BigDecimal.ZERO,
                                                tax);
                                    })
                                    .collect(Collectors.toList());

                    printService.fiscalReceipt(printerId, operatorId, "0000", job.isExactPayment(), paymentType, items, details);
                }
                case "NREC" -> {
                    var paymentType = job.getPaymentType();
                    if (checkPaymentType(paymentType)) {
                        job.setErrorMessage("Not recognized PAYMENT TYPE: " + job.getPaymentType());
                        return;
                    }

                    var amount = job.getAmountPaid();
                    if (amount == null || amount.equals(BigDecimal.ZERO)) {
                        job.setErrorMessage("AMOUNT PAID for non-fiscal receipt is NULL or ZERO");
                        return;
                    }

                    var details = generateJobDetails(job);

                    printService.nonFiscalReceipt(printerId, operatorId, "0000", paymentType, amount, details);
                }
                default -> {
                    job.setErrorMessage("Not recognized JOB TYPE: " + job.getJob());
                    return;
                }
            }

            job.setStatus(200);
        } catch (CloudprintException e) {
            LOG.error(e.errorResponse.getResponse());
            job.setStatus(e.status);
            job.setErrorMessage(e.errorResponse.getData().getException());
        }
    }

    private Map<String, String> generateJobDetails(FPJob job) {
        var jobDetails = job.getJobDetails();
        return jobDetails.size() == 0 ?
                Collections.emptyMap() :
                jobDetails.stream().collect(Collectors.toMap(FPJobDetail::getName, FPJobDetail::getText));
    }

    private final static Set<String> validPaymentTypes = Set.of("CASH", "CARD", "COUPON", "CHEQUE", "CREDIT");
    private boolean checkPaymentType(String paymentType) {
        return validPaymentTypes.contains(paymentType);
    }

}
```

**Comment by DemiusAcademius** [comment] 2020-05-06 10:28
This logic call Hibernate (Oracle) and RestClient

**Comment by mkouba** [comment] 2020-05-06 10:31
Do you use simple scheduler (or the quartz extension) for both the reproducer and the prod app?

**Comment by DemiusAcademius** [comment] 2020-05-06 10:34
In gradle:
```
implementation 'io.quarkus:quarkus-scheduler'
```

**Comment by mkouba** [comment] 2020-05-06 10:40
So it's the simple scheduler impl.

**Comment by DemiusAcademius** [comment] 2020-05-06 10:56
May be I try another scheduler?
By the way, For quarkus.io SSL_ERROR_BAD_CERT_DOMAIN

**Comment by DemiusAcademius** [comment] 2020-05-06 11:19
With quartz extension same picture. application.yaml with changed passwords:
```yaml

quarkus:
  resteasy:
    gzip:
      enabled: true
      max-input: 10M

  datasource:
    url: jdbc:oracle:thin:@10.10.112.1:1521:ACC
    driver: oracle.jdbc.OracleDriver
    username: USERNAME
    password: PASSWORD
    min-size: 1
    max-size: 3

  hibernate-orm:
    dialect: org.hibernate.dialect.Oracle12cDialect
    database:
      generation: none

  log:
    category:
      "io.quarkus.category":
        level: TRACE

com:
  sia:
    restclient:
      auth:
        CloudprintAuthService/mp-rest/url: https://api-int.bytemill.io/auth/realms/apa-canal
        CloudprintAuthService/mp-rest/scope: javax.inject.Singleton
      api:
        CloudprintApiService/mp-rest/url: https://api-int.bytemill.io/api/event
        CloudprintApiService/mp-rest/scope: javax.inject.Singleton

cloudprint:
    config:
        location-id: apacanal
        apikey: 5435253453425
        client-id: SUPER-app
        client-secret: 32432DSFSAFRE
        scope: openid api
        username: api-user
        password: password
    schedule: "0/5 * * * * ?"
```

**Comment by mkouba** [comment] 2020-05-06 11:40
I'm afraid there's not much we can do until we have a reproducer.

Isn't the config property overriden at runtime? E.g. using a system property or an ENV variable?

**Comment by DemiusAcademius** [comment] 2020-05-06 12:22
Not. Config properties not overriden. I can send zipped source to email?

**Comment by mkouba** [comment] 2020-05-06 12:25
Pls join the https://quarkusio.zulipchat.com/login/ channel and ping me.

**Comment by DemiusAcademius** [comment] 2020-05-07 05:45
The problem was solved after I exit from IntelliJ, kill all Java processed and delete build directory (I use gradle). May be quarkus save old version of application.yaml and don't see new version?

**Comment by mkouba** [comment] 2020-05-07 06:43
Ok. So I think that we can close this issue as it looks like some IDE/build tool caching problem.

**Closed by mkouba** 2020-05-07 06:43 UTC
Labels: area/scheduler, kind/bug
