### ISSUE TITLE
Remote-dev with mutable jar throws connection errors

### ISSUE THREAD

**Issue by sdaschner** [quarkusio/quarkus#12497] opened 2020-10-03 08:21 UTC
**Describe the bug**
Since the change in how the `remote-dev` feature works (was that around `1.6`, `1.7`?), the remote dev doesn't quite work for me anymore.

Before, I've used this approach: https://blog.sebastian-daschner.com/entries/quarkus-remote-dev-in-containers

Now, I've tried the following, with `mutable-jar` and `QUARKUS_LAUNCH_DEVMODE=true` on the production side, which *basically* works, but results in many connection errors, and also reacts much slower than usual, since it involves some restarts (?).

**To Reproduce**
- The following branch: https://github.com/sdaschner/quarkus-playground/tree/remote-dev
- `mvn clean package`
- `export QUARKUS_LAUNCH_DEVMODE=true`
- `java -jar target/quarkus-app/quarkus-run.jar`
- In another terminal: `mvn quarkus:remote-dev -Dquarkus.live-reload.url=http://localhost:8080`
- In another terminal: `curl localhost:8080/coffee`

When I change some Java code and make another HTTP request, it produces the following errors:

In `mvn`:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] -------------< com.sebastian-daschner:quarkus-playground >--------------
[INFO] Building quarkus-playground 1.0
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.8.1.Final:remote-dev (default-cli) @ quarkus-playground ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 10 source files to /home/sebastian/workspaces/sdaschner/quarkus-playground/target/classes
Listening for transport dt_socket at address: 5005
2020-10-03 10:14:17,646 INFO  [org.jbo.threads] (main) JBoss Threads version 3.1.1.Final
2020-10-03 10:14:19,901 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 2997ms
2020-10-03 10:14:20,396 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connected to remote server
2020-10-03 10:14:20,590 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:859)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1618)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:188)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:14:22,593 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1256)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1370)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1345)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:186)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:14:24,735 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connected to remote server
2020-10-03 10:16:42,361 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Remote dev client thread) Changed source files detected, recompiling [/home/sebastian/workspaces/sdaschner/quarkus-playground/src/main/java/com/sebastian_daschner/coffee/CoffeeShop.java]
2020-10-03 10:16:44,755 INFO  [io.qua.dep.QuarkusAugmentor] (Remote dev client thread) Quarkus augmentation completed in 801ms
2020-10-03 10:16:44,768 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Remote dev client thread) Hot replace total time: 2.409s 
2020-10-03 10:16:44,848 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending app/quarkus-playground.jar
2020-10-03 10:16:44,852 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending dev/app/com/sebastian_daschner/coffee/CoffeeShop.class
2020-10-03 10:16:44,855 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending quarkus-run.jar
2020-10-03 10:16:44,859 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending lib/deployment/build-system.properties
2020-10-03 10:16:45,297 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.NioSocketImpl.implRead(NioSocketImpl.java:323)
	at java.base/sun.nio.ch.NioSocketImpl.read(NioSocketImpl.java:350)
	at java.base/sun.nio.ch.NioSocketImpl$1.read(NioSocketImpl.java:803)
	at java.base/java.net.Socket$SocketInputStream.read(Socket.java:982)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:244)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:343)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:754)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:863)
	at java.base/sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:689)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1618)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1523)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:188)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:16:47,299 ERROR [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Remote dev request failed: java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:503)
	at java.base/sun.nio.ch.Net.connect(Net.java:492)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588)
	at java.base/java.net.Socket.connect(Socket.java:648)
	at java.base/java.net.Socket.connect(Socket.java:597)
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:182)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:474)
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:569)
	at java.base/sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:341)
	at java.base/sun.net.www.http.HttpClient.New(HttpClient.java:362)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1256)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1194)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1082)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:1016)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1370)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1345)
	at io.quarkus.vertx.http.deployment.devmode.HttpRemoteDevClient$Session.run(HttpRemoteDevClient.java:186)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:16:49,449 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending app/quarkus-playground.jar
2020-10-03 10:16:49,452 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending dev/app/com/sebastian_daschner/coffee/CoffeeShop.class
2020-10-03 10:16:49,454 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending quarkus-run.jar
2020-10-03 10:16:49,456 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Sending lib/deployment/build-system.properties
2020-10-03 10:16:49,458 INFO  [io.qua.ver.htt.dep.dev.HttpRemoteDevClient] (Remote dev client thread) Connected to remote server
```

In `java -jar`:

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-03 10:13:18,360 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2020-10-03 10:13:18,445 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground 1.0 on JVM (powered by Quarkus 1.8.1.Final) started in 2.234s. Listening on: http://0.0.0.0:8080
2020-10-03 10:13:18,446 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-10-03 10:13:18,447 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-jsonb, scheduler, smallrye-health]
2020-10-03 10:14:20,559 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground stopped in 0.085s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-03 10:14:23,140 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2020-10-03 10:14:23,203 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground 1.0 on JVM (powered by Quarkus 1.8.1.Final) started in 2.148s. Listening on: http://0.0.0.0:8080
2020-10-03 10:14:23,203 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-10-03 10:14:23,203 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-jsonb, scheduler, smallrye-health]
2020-10-03 10:14:24,663 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-2) Invalid session
2020-10-03 10:16:44,916 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground stopped in 0.051s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-03 10:16:45,667 ERROR [io.qua.run.boo.ForkJoinClassLoading] (vert.x-worker-thread-1) Failed to set fork join ClassLoader: java.lang.InterruptedException
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.tryAcquireSharedNanos(AbstractQueuedSynchronizer.java:1080)
	at java.base/java.util.concurrent.CountDownLatch.await(CountDownLatch.java:278)
	at io.quarkus.runner.bootstrap.ForkJoinClassLoading.setForkJoinClassLoader(ForkJoinClassLoading.java:40)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:117)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:176)
	at io.quarkus.deployment.dev.IsolatedDevModeMain$$Lambda$118/0000000000000000.accept(Unknown Source)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:183)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:61)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:51)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.ContextImpl$$Lambda$729/0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:16:45,813 ERROR [io.qua.application] (Quarkus Main Thread) Failed to start application (with profile dev): java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$675/0000000000000000@49d13145 rejected from java.util.concurrent.ThreadPoolExecutor@5c3e938f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:334)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:283)
	at io.vertx.core.impl.EventLoopContext.executeBlocking(EventLoopContext.java:23)
	at io.vertx.core.impl.VertxImpl.executeBlocking(VertxImpl.java:748)
	at io.vertx.core.impl.VertxImpl.executeBlocking(VertxImpl.java:754)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.tryCleanTccl(VertxCoreRecorder.java:115)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.configureVertx(VertxCoreRecorder.java:77)
	at io.quarkus.deployment.steps.VertxCoreProcessor$build-956362597.deploy_0(VertxCoreProcessor$build-956362597.zig:117)
	at io.quarkus.deployment.steps.VertxCoreProcessor$build-956362597.deploy(VertxCoreProcessor$build-956362597.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:468)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:835)

2020-10-03 10:16:45,816 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:176)
	at io.quarkus.deployment.dev.IsolatedDevModeMain$$Lambda$118/0000000000000000.accept(Unknown Source)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:183)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:61)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:51)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at io.vertx.core.impl.ContextImpl$$Lambda$729/0000000000000000.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:835)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:717)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	... 1 more
Caused by: java.util.concurrent.RejectedExecutionException: Task io.vertx.core.impl.TaskQueue$$Lambda$675/0000000000000000@49d13145 rejected from java.util.concurrent.ThreadPoolExecutor@5c3e938f[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2057)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:827)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
	at io.vertx.core.impl.TaskQueue.execute(TaskQueue.java:93)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:334)
	at io.vertx.core.impl.ContextImpl.executeBlocking(ContextImpl.java:283)
	at io.vertx.core.impl.EventLoopContext.executeBlocking(EventLoopContext.java:23)
	at io.vertx.core.impl.VertxImpl.executeBlocking(VertxImpl.java:748)
	at io.vertx.core.impl.VertxImpl.executeBlocking(VertxImpl.java:754)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.tryCleanTccl(VertxCoreRecorder.java:115)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder.configureVertx(VertxCoreRecorder.java:77)
	at io.quarkus.deployment.steps.VertxCoreProcessor$build-956362597.deploy_0(VertxCoreProcessor$build-956362597.zig:117)
	at io.quarkus.deployment.steps.VertxCoreProcessor$build-956362597.deploy(VertxCoreProcessor$build-956362597.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:468)
	... 12 more

2020-10-03 10:16:45,833 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-1) Hot replace total time: 3.482s 
2020-10-03 10:16:46,377 INFO  [org.jbo.threads] (Classpath Change Timer) JBoss Threads version 3.1.1.Final
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-03 10:16:48,280 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2020-10-03 10:16:48,355 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground 1.0 on JVM (powered by Quarkus 1.8.1.Final) started in 3.423s. Listening on: http://0.0.0.0:8080
2020-10-03 10:16:48,355 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-10-03 10:16:48,355 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-jsonb, scheduler, smallrye-health]
2020-10-03 10:16:49,377 ERROR [io.qua.ver.htt.run.dev.RemoteSyncHandler] (vert.x-eventloop-thread-2) Invalid session
2020-10-03 10:16:51,925 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground stopped in 0.025s
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-10-03 10:16:52,439 INFO  [io.qua.sch.run.SimpleScheduler] (Quarkus Main Thread) No scheduled business methods found - Simple scheduler will not be started
2020-10-03 10:16:52,440 INFO  [io.quarkus] (Quarkus Main Thread) quarkus-playground 1.0 on JVM (powered by Quarkus 1.8.1.Final) started in 0.511s. Listening on: http://0.0.0.0:8080
2020-10-03 10:16:52,440 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2020-10-03 10:16:52,440 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, resteasy-jsonb, scheduler, smallrye-health]
2020-10-03 10:16:52,441 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (vert.x-worker-thread-0) Hot replace total time: 0.552s
```

I've used:

- Quarkus: `1.8.1.Final`
- Java: `Eclipse OpenJ9 VM AdoptOpenJDK (build openj9-0.19.0, JRE 14 Linux amd64-64-Bit Compressed References 20200318_6 (JIT enabled, AOT enabled)`

With that experience, I'm blocked to update to the latest version. What is the correct way to run this new remote-dev mode?

**Comment by stuartwdouglas** [comment] 2020-10-14 00:25
Looking at your workflow this is not actually remote, you are running both the remote agent and the mvn quarkus:remote-dev agent in the same directory. 

You need to either:

- copy the target somewhere else and run it from there
- put it in a container

previously the agent would just handle sending files, while now it handles local compilation as well.

**Comment by sdaschner** [comment] 2020-10-26 14:23
Sorry for responding late.

Actually, this was just the reproducer which resulted in the same condition like in the container. In my tests, it also didn't work inside a Docker container. Could you please re-open? From my PoV it's still open.

**Comment by stuartwdouglas** [comment] 2020-10-27 01:36
I could only reproduce problems with  pom.xml changes, that I think should be fixed at https://github.com/quarkusio/quarkus/pull/12969

I could not reproduce any problems with normal java files changes.

Can you test out the PR and let me know if it helps?

**Closed** 2020-10-30 11:42 UTC
Labels: area/devmode, kind/bug
