### ISSUE TITLE
JOIN used with nullable referenced entity prevents some entity loading

### ISSUE THREAD

**Issue by mrizzi** [quarkusio/quarkus#15088] opened 2021-02-15 18:46 UTC
**Describe the bug**
I have 2 entities with a `@ManyToOne` relationship.
```java
@Entity
public class Person extends PanacheEntity {
    public String name;
    public LocalDate birth;
    @ManyToOne
    public Country country;
}

@Entity
public class Country extends PanacheEntity {
    public String name;
    public Long population;
}
```
Executing `findAll(Sort sort)` method with different sorting parameter produces result sets with different number of items
```java
@QuarkusTest
public class PersonTest {

    @BeforeAll
    @Transactional
    public static void setup() {
        Country foo = new Country();
        foo.name = "Foo";
        foo.persist();

        Person alice = new Person();
        alice.name = "Alice";
        alice.birth = LocalDate.of(1910, Month.FEBRUARY, 1);
        alice.country = foo;
        alice.persist();

        Person bob = new Person();
        bob.name = "Bob";
        bob.birth = LocalDate.of(1920, Month.MARCH, 1);
        bob.persist();
    }

    @Test
    public void findAllSortByNameTest() {
        List<Person> allPersons = Person.listAll(Sort.by("name"));
        assertEquals(2, allPersons.size());
    }

    @Test
    public void findAllSortByCountryNameTest() {
        List<Person> allPersons = Person.listAll(Sort.by("country.name"));
        assertEquals(2, allPersons.size());
    }
}
```

**Expected behavior**
`listAll(Sort.by("name"))` method should always return the same number of items (i.e. `2` from the above `findAllSortByNameTest` tests)

**Actual behavior**
`listAll(Sort.by("country.name"))` method returns different number of items (i.e. `1` from the above `findAllSortByCountryNameTest` test)
The `allPersons` list in `findAllSortByCountryNameTest` test is missing the `Bob` entry because the generate SQL query is:
```SQL
Hibernate: 
    select
        person0_.id as id1_2_,
        person0_.birth as birth2_2_,
        person0_.country_id as country_4_2_,
        person0_.name as name3_2_ 
    from
        Person person0_ cross 
    join
        Country country1_ 
    where
        person0_.country_id=country1_.id 
    order by
        country1_.name
```
and having the `cross join` condition instead of a `left join` prevents the `Person` entity without `Country` to be loaded.

**To Reproduce**

Execute the [`PersonTest`](https://github.com/mrizzi/quarkus-quickstarts/blob/sort-by-referenced-field/hibernate-orm-panache-quickstart/src/test/java/org/acme/hibernate/orm/panache/PersonTest.java) in my [`sort-by-referenced-field`](https://github.com/mrizzi/quarkus-quickstarts/tree/sort-by-referenced-field/hibernate-orm-panache-quickstart) branch based on the `hibernat-orm-panache` quickstart.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 `Linux fedora-p1 5.10.13-200.fc33.x86_64 #1 SMP Thu Feb 4 14:54:51 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: 
   ```
   openjdk version "11.0.10" 2021-01-19
   OpenJDK Runtime Environment 18.9 (build 11.0.10+9)
   OpenJDK 64-Bit Server VM 18.9 (build 11.0.10+9, mixed mode, sharing)
   ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
 `development` branch in quickstart
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**

**Comment by gsmet** [comment] 2021-02-16 15:46
/cc @Sanne @dreab8 any chance one person from the ORM team could have a look, at least to confirm if there's a bug? There is a reproducer above.

Thanks!

**Comment by dreab8** [comment] 2021-02-16 16:40
Hi @gsmet I'm going to look at it

**Comment by yrodiere** [comment] 2021-02-22 14:50
@dreab8 I'm assigning this ticket to you then, but it's just to have better visibility on what I can work on and what I cannot. Feel free to un-assign yourself if you won't work on this after all.

**Comment by gsmet** [comment] 2021-02-22 15:27
Sorry, we had a discussion with Andrea last week and I needed to post the outcome: when the join is implicit (here the join is added because of a sort), the join is not a left join so it’s normal you don’t have all the rows. 

So given the query that Panache generates, this is the expected behavior. 

If you want a left join, you need to make it explicit in your query.

**Closed by gsmet** 2021-02-22 15:27 UTC
Labels: area/hibernate-orm, area/panache, kind/bug, triage/needs-triage

**Comment by mrizzi** [comment] 2021-02-22 19:07
Sorry for asking more about this but I feel like the answer confused me and it may be worth clarifying for whoever will read this issue.
Considering the `@ManyToOne` relationship that has default fetch `EAGER`, shouldn't the SQL generated join be always a `left outer join` due to the eager loading?
It's not clear to me why the "fetch contract" should not be observed in this case.
