### ISSUE TITLE
Quarkus 2.1.0.CR1 complains about split-package

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#18819] opened 2021-07-19 14:54 UTC
### Describe the bug

I have this in my pom:

```
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-arc</artifactId>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-resteasy</artifactId>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-funqy-knative-events</artifactId>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-jdbc-postgresql</artifactId>
      </dependency>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-hibernate-orm-panache</artifactId>
      </dependency>

```

When running (tests) Quarkus complains

```
2021-07-19 16:49:59,853 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-34) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.quarkus.hibernate.orm.panache" found in [io.quarkus:quarkus-hibernate-orm-panache, io.quarkus:quarkus-hibernate-orm-panache-common]

```

and also later:

```
[INFO] --- quarkus-maven-plugin:2.1.0.CR1:build (default) @ log-funq ---
[INFO] [org.jboss.threads] JBoss Threads version 3.4.0.Final
[WARNING] [io.quarkus.arc.deployment.SplitPackageProcessor] Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.quarkus.hibernate.orm.panache" found in [io.quarkus:quarkus-hibernate-orm-panache, io.quarkus:quarkus-hibernate-orm-panache-common]
[INFO] [org.hibernate.Version] HHH000412: Hibernate ORM core version 5.5.3.Final
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 1566ms
```

### Expected behavior

This warning should not be printed, as the user can not do anything against it.

**Comment by geoand** [comment] 2021-07-19 14:55
@loicmathieu IIRC, you have a PR for this, right?

**Comment by geoand** [comment] 2021-07-19 14:59
I'll close this as a duplicate of https://github.com/quarkusio/quarkus/issues/18732

**Closed by geoand** 2021-07-19 14:59 UTC
Labels: area/panache, kind/bug

**Comment by loicmathieu** [comment] 2021-07-19 15:05
Yes, this one has already been fixed by a PR by @gsmet.

**Comment by geoand** [comment] 2021-07-19 15:09
Cool, thanks
