### ISSUE TITLE
@QuarkusTest @Inject NPE with Spock + Kotlin

### ISSUE THREAD

**Issue by mvniekerk** [quarkusio/quarkus#4797] opened 2019-10-23 13:01 UTC
**Describe the bug**
Adding Spock and annotating a specification class with @QuarkusTest, doing an @Inject with some bean always result in a NPE

**Expected behavior**
Have the beans injected into the specification

**Actual behavior**
NPE when trying to accessing the (should have been) injected beans

**To Reproduce**
1. Checkout https://github.com/mvniekerk/quarkus-test-spock-kotlin/
2. ./gradlew test

**Configuration**
```properties
# NA, fails regardless
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Darwin Michaels-MacBook-Pro.local 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (Zulu 8.40.0.25-CA-macosx) (build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (Zulu 8.40.0.25-CA-macosx) (build 25.222-b10, mixed mode)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
0.26.1

**Additional context**
Trying to get Spock BDD tests up and running with Quarkus

**Comment by geoand** [comment] 2019-10-23 16:02
Thanks for reporting.

There is no `Spock` integration currently in Quarkus which is why you are seeing the error.

**Comment by mvniekerk** [comment] 2019-10-23 19:20
There doesn't seem to be integration on anything but Java src + Java tests.

As a POC I've written an interface in Kotlin, implementation in Kotlin and wrote a test in Java and injecting the interface. Fails at ARC level.

**Comment by geoand** [comment] 2019-10-23 19:25
I didn't dig into details but I wouldn't expect it to work OOTB

**Comment by loicmathieu** [comment] 2021-04-21 09:20
Can you try with Spock version 2.0-M5 that has support for JUnit5 ?

**Comment by NetoDevel** [comment] 2021-04-28 17:15
@loicmathieu,
Even with this version of the spock, quarkus is still unable to synchronize with the lifecycle of the spock .. ending up not raising the context of the application before running the tests.

**Comment by geoand** [comment] 2021-07-29 06:04
I am going to close this as essentially a duplicate of https://github.com/quarkusio/quarkus/issues/6506

**Closed by geoand** 2021-07-29 06:04 UTC
Labels: kind/bug
