### ISSUE TITLE
Hibernate validator and annotated static method on enum

### ISSUE THREAD

**Issue by pehunka** [quarkusio/quarkus#3284] opened 2019-07-19 06:36 UTC
**Describe the bug**
Application fails to start when an enum type has annotated static method with bean validation constraint.

**Expected behavior**
I will expect that quarkus app will compile and ignore the validation constraint as not supported by the bean validation specification.

**Actual behavior**
Application crashes with following stack trace

```
[io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError ..
Caused by: java.lang.ArrayIndexOutOfBoundsException: 1
at io.quarkus.hibernate.validator.runtime.HibernateValidatorRecorder
```

**To Reproduce**
```
mvn io.quarkus:quarkus-maven-plugin:0.19.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
```

Add enum with static factory method annotated with a bean validation constraint:

```java
public enum Gender {
    MALE,
    FEMALE;

    public static Gender fromCode(@NotNull String code) {
        return Gender.valueOf(code);
    }
}
```

Add dependency on hibernate validator to your pom:

```xml
 <dependency>
     <groupId>io.quarkus</groupId>
     <artifactId>quarkus-hibernate-validator</artifactId>
 </dependency>
```

```
mvn compile quarkus:dev
```

**Environment (please complete the following information):**
```terminal
 Java version: 1.8.0_212, vendor: Amazon.com Inc., runtime: /Library/Java/JavaVirtualMachines/amazon-corretto-8.jdk/Contents/Home/jre
Default locale: en_CZ, platform encoding: UTF-8
OS name: "mac os x", version: "10.14.5", arch: "x86_64", family: "mac"
```

**Additional context**
I've tried POJO instead of Enum and it works.

**Comment by gsmet** [comment] 2019-07-20 15:40
Usually these issues are related to synthetic parameters being added in enum methods.

I'll have a look.

**Comment by gsmet** [comment] 2019-10-07 13:42
There is a tentative PR here: https://github.com/hibernate/hibernate-validator/pull/1049 .

While I suppose the PR fixes the issue mentioned here, it looks like there is something weird going on so we need to fully understand the issue before merging.

**Comment by yrodiere** [comment] 2019-10-22 12:09
@gsmet Setting the same milestone as https://github.com/quarkusio/quarkus/issues/2556, since both problems have the same root cause and will be fixed by a new release of HV and an upgrade to that new release in Quarkus.

**Comment by yrodiere** [comment] 2019-10-22 12:09
See also  #4439

**Closed** 2019-10-29 12:48 UTC
Labels: bug, component:hibernate-validator
