### ISSUE TITLE
Quarkus Swagger UI behind an Ingress Controller

### ISSUE THREAD

**Issue by limadelrey** [quarkusio/quarkus#4200] opened 2019-09-25 12:08 UTC
Hey,

I'm using quarkus-smallrye-openapi maven dependency to take advantage of automatic OpenApi specifications and Swagger UI. In order to do that I've coded the following configurations on application.properties file:

```
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.path=/open-api
```

Although both work on my local environment, when I try to deploy them on a Kubernetes cluster behind an Ingress controller my /swagger-ui endpoint doesn't work. I'm using the following Ingress configuration:

```
{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "test-service",
    "namespace": "development",
    "selfLink": "/apis/extensions/v1beta1/namespaces/development/ingresses/test-service",
    "uid": "c8e4b62e-df8a-11e9-92ba-026e3f42042e",
    "resourceVersion": "24998716",
    "generation": 1,
    "creationTimestamp": "2019-09-25T11:51:18Z",
    "annotations": {
      "certmanager.k8s.io/acme-challenge-type": "http01",
      "certmanager.k8s.io/issuer": "letsencrypt-prod",
      "kubernetes.io/ingress.class": "nginx",
      "nginx.ingress.kubernetes.io/rewrite-target": "/$2"
    }
  },
  "spec": {
    "tls": [
      {
        "hosts": [
          "xxxxx"
        ],
        "secretName": "xxxxx"
      }
    ],
    "rules": [
      {
        "host": "xxxxx",
        "http": {
          "paths": [
            {
              "path": "/test-service(/|$)(.*)",
              "backend": {
                "serviceName": "test-service",
                "servicePort": 8080
              }
            }
          ]
        }
      }
    ]
  },
  "status": {
    "loadBalancer": {
      "ingress": [
        {
          "ip": "xxxxx"
        }
      ]
    }
  }
}
```

As you can see I'm using a rewrite strategy which works perfectly for /open-api endpoint, but also for my /health endpoints, /metrics endpoints and my REST API endpoints. It rewrites any request with the prefix "/test-service" to the deployed service. However, for some reason /swagger-ui endpoint isn't working. It seems to me that the files which Swagger UI uses behind the curtains are having some issues with Ingress path.

Can anyone help me solving this?

Thank you in advance.

**Comment by gsmet** [comment] 2019-09-25 12:21
When you say:

> my /swagger-ui endpoint doesn't work

what do you mean exactly?

**Comment by limadelrey** [comment] 2019-09-25 13:05
Ingress is redirecting to an error page probably because it doesn't recognise some path inside Swagger UI static files.

**Comment by gsmet** [comment] 2019-09-25 13:16
The first thing that comes to mind is that you need to point Swagger UI to `/test-service/open-api` not `/open-api`. as your browser will be the one making the request.

The issue is that this is build time config so you can't override it with a profile or a runtime override.

**Comment by limadelrey** [comment] 2019-09-25 14:00
First of all, thank you for trying to help @gsmet.

In one of my previous tests I've already changed Swagger UI to `/test-service/swagger-ui` and OpenAPI to `/test-service/open-api`. The result was that Swagger UI was available and communicating with OpenAPI specification, but the "Try Out" buttons were communicating to `/api` instead of `/test-service/api` endpoints. So there's still this issue when pointing out to `/test-service/swagger-ui` instead of `/swagger-ui`.

Also, these changes were made by using a previously known value. I tried using environment variables in order to achieve the same dynamically, but at this moment it isn't possible (https://github.com/quarkusio/quarkus/issues/4172). I'm just referring it so you can have a bigger picture of this use case, no need to bring that issue up here since it's already being looked on.

**Comment by gsmet** [comment] 2019-09-25 14:11
Have you checked `quarkus.servlet.context-path`?

Because AFAICS you need everything to be moved to this `test-service` path.

**Comment by limadelrey** [comment] 2019-09-25 14:36
To be honest I hadn't used it before. I've applied the following properties:

```
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
quarkus.smallrye-openapi.path=/open-api
quarkus.servlet.context-path = /test-service
```

Although I haven't tried yet to deploy it on Kubernetes, I can't get it to work locally:
<img width="1568" alt="Screenshot 2019-09-25 at 15 34 24" src="https://user-images.githubusercontent.com/14318789/65610998-19b16000-dfaa-11e9-8460-3e21c80482fd.png">

**Comment by gintsgints** [comment] 2019-09-28 09:18
Can you open test-service/open-api ?

Also why not try with default paths.
Use only one config:
```
quarkus.swagger-ui.always-include=true
```
Check /swagger-ui/ then.

**Comment by limadelrey** [comment] 2019-09-30 13:26
Hi @gintsgints,

I've tried to use default paths just like you suggested by only setting up the following properties:

```
quarkus.servlet.context-path = /test-service
quarkus.swagger-ui.always-include=true
```

Now I can access both endpoints:
`/test-service/openapi`
`/test-service/swagger-ui`

However, I keep getting the same error as before:
<img width="1491" alt="Screenshot 2019-09-30 at 14 25 55" src="https://user-images.githubusercontent.com/14318789/65883099-3ffe4380-e38e-11e9-933a-be512fe09fd2.png">

Any thoughts?

**Comment by gsmet** [comment] 2019-09-30 13:39
Unfortunately, this is a bug in the Swagger UI extension: it doesn't
properly take into account the context path.

If you change the "/openapi" in the field at the top to
"/test-service/openapi", I'm pretty sure it will be OK.

Now, the thing is that with our new Vert.x based layer, I'm not sure how
this is handled now.

-- 
Guillaume

**Comment by gsmet** [comment] 2019-09-30 13:41
@stuartwdouglas @cescoffier do we have an equivalent to the `contextPath` in the new HTTP layer?

**Comment by stuartwdouglas** [comment] 2019-10-01 05:54
We will once https://github.com/quarkusio/quarkus/pull/4286 is merged, and it should handle all this correctly.

**Comment by limadelrey** [comment] 2019-10-01 09:41
Perfect! Thank you @gsmet, @stuartwdouglas and @gintsgints.

**Comment by gsmet** [comment] 2019-11-18 11:26
This one should have been fixed by https://github.com/quarkusio/quarkus/pull/4286 .

**Closed by gsmet** 2019-11-18 11:26 UTC
Labels: question

**Comment by sirAlexanderT** [comment] 2020-07-03 19:20
> This one should have been fixed by #4286 .

@gsmet i'm still facing this issue with `1.6.0.CR1`

**Comment by stuartwdouglas** [comment] 2020-07-06 02:14
Is it just the defaults that don't work? i.e. if you manually change the path in the UI to  /test-service/openapi does it work as expected?

**Comment by sirAlexanderT** [comment] 2020-07-08 12:24
> Is it just the defaults that don't work? i.e. if you manually change the path in the UI to /test-service/openapi does it work as expected?

@stuartwdouglas manually changing the path in the ui and clicking explore brings up the swagger api, but running execute on any of the end points doesn't  work because the open api doc created does not have `/test-service/`  as part of the generated path.

so the path for example is `/users` instead of `/test-service/users`

**Comment by stuartwdouglas** [comment] 2020-07-08 23:45
Would setting the http root path and removing the rewrite be an option? Just set quarkus.http.root-path=/test-service, so openapi will end up being mounted at the correct location.

**Comment by sirAlexanderT** [comment] 2020-07-09 07:17
@stuartwdouglas Thanks for the suggestion, that worked. Now fingers crossed the infrastructure "gatekeeper" will be happy with the change
