### ISSUE TITLE
Quarkus has a NPE in CDI logic trying to provide a TransactionManager

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#17237] opened 2021-05-14 16:33 UTC
In testing with 1.13.2.Final I found that Quarkus has a NPE in its CDI logic trying to provide a TransactionManager.

```
2021-05-14 16:14:00,380 ERROR (pool-17-thread-1) [com.app.util.AodrUtils.foregroundHistoryTask()] Cursor error by Bulk Data Request:: java.lang.RuntimeException: Error injecting javax.transaction.TransactionManager io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.transactionManager
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.create(TransactionalInterceptorRequired_Bean.zig:173)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.get(TransactionalInterceptorRequired_Bean.zig:211)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.get(TransactionalInterceptorRequired_Bean.zig:246)
        at com.app.util.MongoHelper_Subclass.<init>(MongoHelper_Subclass.zig:32)
        at com.app.util.MongoHelper_Bean.create(MongoHelper_Bean.zig:188)
        at com.app.util.MongoHelper_Bean.create(MongoHelper_Bean.zig:378)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.ClientProxies.getApplicationScopedDelegate(ClientProxies.java:17)
        at com.app.util.MongoHelper_ClientProxy.arc$delegate(MongoHelper_ClientProxy.zig:67)
        at com.app.util.MongoHelper_ClientProxy.findAllCursor(MongoHelper_ClientProxy.zig:547)
        at com.app.util.AodrUtils.process(AodrUtils.java:126)
        at com.app.util.AodrUtils.foregroundHistoryTask(AodrUtils.java:85)
        at com.app.util.AodrProcessor.submit(AodrProcessor.java:76)
        at com.app.util.BaseAodrProcessor.process(BaseAodrProcessor.java:69)
        at com.app.AppLifecycle.lambda$afterStartup$10(AppLifecycle.java:325)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.NullPointerException
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Bean.get(CDIDelegatingTransactionManager_Bean.zig:533)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager_Bean.get(CDIDelegatingTransactionManager_Bean.zig:556)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.create(TransactionalInterceptorRequired_Bean.zig:155)
        ... 26 more
```

**Comment by gastaldi** [comment] 2021-05-14 16:39
Please attach a reproducer project if possible

**Comment by dhoffer** [comment] 2021-05-14 18:33
I have just learned that this error occurred during an app shutdown.  Quarkus might still want to prevent the NPE but since the app is going down anyway its not critical for us to resolve as I first thought.

**Comment by dhoffer** [comment] 2021-05-14 19:30
Unfortunately I don't have that.  I don't know how to recreate this in a
small simple app.  I have only seen this once in a large app.  Hopefully
the stack trace will show what was null.

**Comment by stuartwdouglas** [comment] 2021-05-16 23:41
There is not much we can do about this, if you shut down a node while work is going on you can eventually get all kinds of errors, as the framework is being torn down around your running work. It would be better if this particular error was 'container is shutting down' rather than NPE, but the end result will be the same.

**Comment by stuartwdouglas** [comment] 2021-05-16 23:46
So I had a look, and this seems to require a very specific race, where basically we have code that looks like:
```
requireRunning() //throws an error if the container is shutdown
return singletonScope;
```
If the container is shut down after the requireRunning() call, but before the scope is returned this method may return null.

In this case we could fix it by doing the read before the check, but you will pretty much also have the potential to get these issues if you shutdown while things are running.

**Comment by stuartwdouglas** [comment] 2021-05-16 23:48
@mkouba I don't think there is much we can do about this, what do you think?

**Comment by dhoffer** [comment] 2021-05-17 01:55
Yeah I agree that a container is being shut down error is preferred as it's
obvious what is going on then.  In this case I did not know that at first.

But this raised another question.  Should we be doing something to manage
an orderly shutdown?  Does the container have a hook we should be using
when we shut down the app?

Dave

**Comment by stuartwdouglas** [comment] 2021-05-17 02:05
If you set `quarkus.shutdown.timeout` Quarkus will wait for current requests to be done before initiating shutdown (up till the timeout). 

At the moment this is only implemented for HTTP requests, so it won't work for message based systems. We can definitely improve this, but so far we just have not had anyone ask for it.

**Comment by mkouba** [comment] 2021-05-17 07:52
So the exception that bubbles to the user is `java.lang.RuntimeException: Error injecting javax.transaction.TransactionManager io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.transactionManager` and the NPE is just the cause, right?

> In this case we could fix it by doing the read before the check, but you will pretty much also have the potential to get these issues if you shutdown while things are running.

Exactly, I don't think it would help much because we'll likely hit the same problem a bit later...

@dhoffer I can see the `java.util.concurrent.ScheduledThreadPoolExecutor` in the stack trace. Do you define a custom `ScheduledExecutorService` in your app? If so you can try to shutdown the executor service before the container is shut down, i.e. observe the `ShutdownEvent`:  https://quarkus.io/guides/lifecycle#listening-for-startup-and-shutdown-events

**Comment by gsmet** [comment] 2021-05-17 10:00
Not saying it's easy to fix it but from a user point of view, I think it's really bad to not have a clean shutdown.

**Comment by dhoffer** [comment] 2021-05-17 16:25
@mkouba Yes we already do use several ExecutorService and already have this to shut these down.  Is this not correct?

void beforeShutdown(@Observes ShutdownEvent ev) {
      
        sendingExecutorServices.forEach(executorService -> executorService.shutdown());
        sendingExecutorServices.clear();

        receivingExecutorServices.forEach(executorService -> executorService.shutdown());
        receivingExecutorServices.clear();

        otherExecutorServices.forEach(executorService -> executorService.shutdown());
        otherExecutorServices.clear();
    }

**Comment by stuartwdouglas** [comment] 2021-05-18 01:41
@gsmet it is pretty much impossible to guarantee a clean shutdown if user code is still running, graceful shutdown is the only answer for this.

Because shutdown can occur at literally any point in any runtime code path to guarantee this you would need to audit every single code path of every single library almost line by line and make sure that if a shutdown happens on a given line you end up throwing a meaningful exception rather than NPE (or whatever).

**Comment by mkouba** [comment] 2021-05-19 15:51
> Yes we already do use several ExecutorService and already have this to shut these down. Is this not correct?

@dhoffer You can try to use `ExecutorService.shutdownNow()` or even `ExecutorService.awaitTermination(long, TimeUnit)` (this method blocks until all tasks have completed or the timeout occurs) instead. `ExecutorService.shutdown()` does not attempt to stop all executing tasks. And the executed task would need to test whether the current thread has been interrupted...

**Comment by geoand** [comment] 2022-08-02 06:30
I think we can close this.

If the issue persists (and is not happening during shutdown), feel free to  comment or reopen

**Closed by geoand** 2022-08-02 06:30 UTC
Labels: area/arc, needs-reproducer
