### ISSUE TITLE
Allow adding attributes to to the Manifest Main Attributes

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#17568] opened 2021-05-31 19:14 UTC
## Description

Currently, Quarkus allows adding attributes to custom sections (see https://github.com/quarkusio/quarkus/blob/9245ad39e42234e929bf24034821c619d76ee23a/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/JarResultBuildStep.java#L1292-L1299), but does not provide any way to add to the Manifest main attributes (getEntries does not allow modifying main attributes).

There are some use-cases where it is required to add to the Manifest main attributes (example: creating a java agent for instrumentation of another jar https://www.baeldung.com/java-instrumentation ).

Some attributes should not be overriden (ex: Class-Path, Main-Class, etc.), but new one should be able to be added. 

## Implementation ideas

- new `Map` property `quarkus.package.manifest.main-section` (ex: `quarkus.package.manifest.main-section.Premain-Class=org.acme.PremainClass`)
- Make the "empty" section refer to the main section in `quarkus.package.manifest.manifest-sections` (ex: `quarkus.package.manifest.manifest-sections.Premain-Class=org.acme.PremainClass`)
- Make the "main" section refer to the main section in `quarkus.package.manifest.manifest-sections` (ex: `quarkus.package.manifest.manifest-sections.main.Premain-Class=org.acme.PremainClass`)

**Comment by geoand** [comment] 2021-11-09 09:32
If you are willing to provide a Pull Request, I'd be willing to include it.

**Comment by geoand** [comment] 2022-01-25 10:58
This is actually a duplicate of https://github.com/quarkusio/quarkus/issues/12889 which will be handled by https://github.com/quarkusio/quarkus/pull/23147

**Closed by geoand** 2022-01-25 10:58 UTC
Labels: kind/enhancement, triage/needs-triage
