### ISSUE TITLE
System.out.println in @Observers StartupEvent shows up before banner

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#9681] opened 2020-05-29 13:01 UTC
In my live demo, I added an `@Observers StartupEvent`  to add testdata, but that test data didn't show up in the UI (due to a bug in another class related to REST). However, I added System.out in that startup event method, but **it appeared as it didn't show up.** In reality, it probably did, before the Quarkus banner.

See that go awfully wrong here: https://youtu.be/JqtF2PLYTvI?t=1938

**However, in another project, the System.out does show up after the quickstart banner.**

Project 1 "timetabling" (= reproducer):

```
[INFO] Compiling 6 source files to /home/ge0ffrey/tmp/demo/timetabling/target/classes
Listening for transport dt_socket at address: 5005
THE STARTUP EVENT HAPPENED <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-29 12:44:21,837 INFO  [io.quarkus] (Quarkus Main Thread) timetabling 1.0.0-SNAPSHOT (powered by Quarkus 1.4.2.Final) started in 2.936s. Listening on: http://0.0.0.0:8080
```

Project 2 "timetaling2" (=working project that is pretty much the same code and pom, has same JDK and is also using java 8 source/target):

```
[INFO] --- quarkus-maven-plugin:1.4.2.Final:dev (default-cli) @ timetabling ---
[INFO] Nothing to compile - all classes are up to date
Listening for transport dt_socket at address: 5005
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2020-05-29 12:42:06,514 WARN  [io.qua.dep.ste.ReflectiveHierarchyStep] (build-31) Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - io.quarkus.deployment.recording.BytecodeRecorderImpl$$ClassProxy42
        - org.optaplanner.core.api.score.buildin.hardsoft.HardSoftScore
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
2020-05-29 12:42:06,661 INFO  [io.qua.arc.pro.BeanProcessor] (build-42) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field org.acme.rest.TimeTableResource#solverManager
THE STARTUP EVENT HAPPENED <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
2020-05-29 12:42:07,892 INFO  [io.quarkus] (Quarkus Main Thread) timetabling 1.0.0-SNAPSHOT (powered by Quarkus 1.4.2.Final
```

**Reproducer:** https://github.com/ge0ffrey/reproducer-quarkus-startupevent-ignored
Run "mvn quarkus:dev" on that and watch the console.

**Comment by mkouba** [comment] 2020-05-29 13:37
So I believe that the "ordering issue" is caused by the fact that the banner is not logged as a message but it's the return value of `java.util.logging.Formatter.getHead(Handler)`. And the head is probably used once the first log record is published. 

CC @RotBolt 

See also the related zulip discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/StartupEvent.20not.20triggered

**Comment by RotBolt** [comment] 2020-05-29 13:49
I remember I implemented it as return value 
of `formatter.getHead()` 
So this return value and sysout gets into race condition. 🤔

**Comment by mkouba** [comment] 2020-05-29 13:55
I don't think it's a race condition. It's more like the head is used lazily when the first log record is published or something like that...

> so add banner message as log ?

Yes, we can try this. Would you care to send a PR?

**Comment by RotBolt** [comment] 2020-05-30 14:48
Sure. Will work on it.

**Comment by geoand** [comment] 2024-09-13 11:01
Is this still an issue?

**Comment by mkouba** [comment] 2024-09-13 11:11
> Is this still an issue?

I believe that it still applies because the PR was never sent ;-). @RotBolt?

**Comment by geoand** [comment] 2024-09-13 11:12
Yeah, I'm wondering whether some other change inadvertently fixes this as well.

**Comment by geoand** [comment] 2024-09-30 10:49
Closing for now

**Closed by geoand** 2024-09-30 10:49 UTC
Labels: kind/bug, triage/needs-feedback
