### ISSUE TITLE
quarkus-vertx provides non-covergent io.smallrye.reactive:smallrye-mutiny-vertx-core versions

### ISSUE THREAD

**Issue by pierDipi** [quarkusio/quarkus#28512] opened 2022-10-11 15:54 UTC
### Describe the bug

I've imported quarkus-vertx and I'm getting a dependency convergence error:

```
Dependency convergence error for io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.25.0:compile paths to dependency are:
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.quarkus:quarkus-vertx:jar:2.12.2.Final:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.25.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-web-common:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-uri-template:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile

```

### Expected behavior

quarkus-vertx provides the same dependency version and the [maven-enforcer-plugin](https://maven.apache.org/enforcer/maven-enforcer-plugin/) doesn't fail when importing quarkus-vertx.

### Actual behavior

```
Dependency convergence error for io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.25.0:compile paths to dependency are:
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.quarkus:quarkus-vertx:jar:2.12.2.Final:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.25.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-auth-common:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-web-common:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile
and
+-dev.knative.eventing.kafka.broker:core:jar:1.0-SNAPSHOT
  +-io.smallrye.reactive:smallrye-mutiny-vertx-web-client:jar:2.26.0:compile
    +-io.smallrye.reactive:smallrye-mutiny-vertx-uri-template:jar:2.26.0:compile
      +-io.smallrye.reactive:smallrye-mutiny-vertx-core:jar:2.26.0:compile

```

### How to Reproduce?

1. Import quarkus-vertx
2. Run maven-enforcer-plugin

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739) Maven home: /home/pierdipi/.m2/wrapper/dists/apache-maven-3.8.3-bin/5a6n1u8or3307vo2u2jgmkhm0t/apache-maven-3.8.3 Java version: 18.0.2, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-18-openjdk-18.0.2.0.9-1.rolling.fc36.x86_64 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.19.4-200.fc36.x86_64", arch: "amd64", family: "unix"

### Additional information

Similar to https://github.com/quarkusio/quarkus/issues/28511

**Comment by cescoffier** [comment] 2022-10-11 16:13
Well, I believe the problem is on the other project.

**Comment by gsmet** [comment] 2022-10-11 16:13
That's why we provide a BOM. Please use the BOM to align everything.

**Comment by geoand** [comment] 2022-10-11 16:15
Oh, this isn't using our BOM?

Then we should close this and all the other similar issues

**Comment by pierDipi** [comment] 2022-10-11 16:20
I was following this guide which is not using the BOM: https://quarkus.io/guides/vertx, I will try with the BOM, maybe that guide should be updated? or perhaps clarified that importing dependencies directly without the BOM is not supported?

**Closed** 2022-10-11 16:24 UTC
Labels: kind/bug, area/smallrye, area/kubernetes, area/mutiny

**Comment by gsmet** [comment] 2022-10-11 16:25
Are you sure you followed all the steps? Because the project generated by code.quarkus.io should enforce the BOM. If not we have a big issue.

**Comment by pierDipi** [comment] 2022-10-11 16:26
I didn't generate it with code.quarkus.io
