### ISSUE TITLE
RestClient potential memory leak depending on the CDI scope

### ISSUE THREAD

**Issue by lvargas0584** [quarkusio/quarkus#16894] opened 2021-04-29 02:51 UTC
## Describe the bug
When I call my API a lot of times(+600) , This stops responding.
I checking the memory use ,  using jvisualvm.
Memory goes up until the service stops responding.
I'm using RestClient, to call others api's.
I noticed, that when I use the @RequestScope notation on my restClient class, the memory goes up but goes back down automatically

### Expected behavior
I hope the service does not stop responding when I use it many times in a row

### Actual behavior
Memory goes up until the service stops responding.

![image](https://user-images.githubusercontent.com/11546734/116496926-cb420280-a86b-11eb-9cc5-18df8476c876.png)

**Comment by gsmet** [comment] 2021-04-29 08:37
Sure looks like a memory leak somewhere.

I think the best way to pursue this would be to get a memory dump (hprof file) and have a look at what's there.

**Comment by geoand** [comment] 2021-04-29 11:42
cc @mkouba

**Comment by manovotn** [comment] 2021-04-29 12:08
I suppose the memory leak occurs when you use `@Dependent` scope? Since if an instance of dependent scope is created somewhere "manually" you also need to dispose of it properly. Having a reproducer or at least the heap dump would be neat; otherwise it is really hard to tell what is going on.

**Comment by mkouba** [comment] 2021-04-29 14:40
> I suppose the memory leak occurs when you use `@Dependent` scope? Since if an instance of dependent scope is created somewhere "manually" you also need to dispose of it properly. Having a reproducer or at least the heap dump would be neat; otherwise it is really hard to tell what is going on.

+1

We're also interested in the code that injects the rest client. For instance, if there was an `@Inject Instance<BusinessCommandClient>` and you would do `instance.get().doSomething()` then a new client instance will be created  for every invocation and it's retained in the memory until the bean that injects `Instance<BusinessCommandClient>` is destroyed.

**Comment by lvargas0584** [comment] 2021-04-29 15:34
I share with you my code
https://github.com/lvargas0584/quarkus-ms

**Comment by mkouba** [comment] 2021-04-29 15:40
Could you also try to create a heap dump, e.g. via [visualvm](https://visualvm.github.io/)?

**Comment by manovotn** [comment] 2021-05-03 10:08
The code you shared is not even buildable; there are snapshot dependencies on `com.lamark.architecture:core-ms` and `com.lamark.dto:shared-dto` which are not part of the project and classes from them are apparently used throughout the code. That means we cannot reproduce the behavior to get to the memory leak.
We'll need either buildable reproducer or a heap dump that we can analyze.

**Comment by geoand** [comment] 2022-03-09 13:17
Closing as we never got adequate information to be able to perform a proper investigation.

Feel free to comment with more up to date and detailed information if this is still an issue

**Closed by geoand** 2022-03-09 13:17 UTC
Labels: kind/bug, area/rest-client

**Comment by gaetancollaud** [comment] 2024-01-04 14:51
I got the same problem and `@RequestScope` on my Resteasy client class fixed the issue. I have saved heapdumps from before the fix, I can send them but they are quite heavy (530mb). Is someone still interested ? If yes where can I upload them ?

**Comment by sujalmandal** [comment] 2024-04-07 05:25
> > I suppose the memory leak occurs when you use `@Dependent` scope? Since if an instance of dependent scope is created somewhere "manually" you also need to dispose of it properly. Having a reproducer or at least the heap dump would be neat; otherwise it is really hard to tell what is going on.
> 
> +1
> 
> We're also interested in the code that injects the rest client. For instance, if there was an `@Inject Instance<BusinessCommandClient>` and you would do `instance.get().doSomething()` then a new client instance will be created for every invocation and it's retained in the memory until the bean that injects `Instance<BusinessCommandClient>` is destroyed.

I did something for a project where an authentication filter needed to call an external api to perform some auth operations. I injected an instance of the authClient and inadvertently created an memory leak. One has to be careful with the above aproach. The one with the bug looks like this.


```java

@Secured
@Provider
@NoArgsConstructor
@Priority(Priorities.AUTHENTICATION)
public class AuthenticationFilter implements ContainerRequestFilter{

    @Context
    UriInfo info;

    private Instance<AuthServiceClient> authServiceClientInstance;

    @Inject
    public AuthenticationFilter(@RestClient Instance<AuthServiceClient> authServiceClient) {
        this.authServiceClientInstance = authServiceClient;
    }

    @Override
    public void filter(ContainerRequestContext context) {
        try {
            var verifyResponse = authServiceClient.get().verify(..); // <-- creates one instance each for every request

            if (verifyResponse == null) {
                log.error("Authentication failed.");
                context.abortWith(Response.status(Response.Status.UNAUTHORIZED).build());
                return;
            }

        } catch (Exception ex) {
            log.error("unable to verify token with auth client");
            context.abortWith(Response.status(Response.Status.UNAUTHORIZED).build());
        }
}
}
```

The fix was to include a finally block in which the instance would be released.

```java
var authServiceClient = authServiceClientInstance.get(); 
        try {
            var verifyResponse = authServiceClient.verifyAccessToken(..);
           ...
        } catch (Exception ex) {
           ...
        } finally {
            // destroy the instance to prevent a memory leak
            authServiceClientInstance.destroy(authServiceClient);
        }
```
