### ISSUE TITLE
microprofile client library can't be called directly from the service project.

### ISSUE THREAD

**Issue by queencge** [quarkusio/quarkus#15133] opened 2021-02-17 00:55 UTC
**Describe the bug**
I generated client library separate with openapi-generator with microprofile
Add this client library in main service project with mvn dependency.
but that  client API doesn't call properly.

First Issue.
So I need to create api client again in service project although client dependency library has it.
Although generated client class is in the client library which was generated, I need to make the same class in service project.

Second issue,
I used like this instead of creating the same class under service project. 
that was working fine with non-native-image.

@ApplicationScoped
@RegisterRestClient(configKey = "email-api")
public interface EmailClient extends EmailApi {

But in the native-image, not working. So, I need to create the same RegisterRestClient class in the service project

**Expected behavior**
Just adding library

**Actual behavior**
2021-02-16 22:54:37 ERROR (vert.x-eventloop-thread-2) [nz.co.vodafone.dx.core.identity.resource.ExceptionMappers] handleRuntimeException: runtimeException: java.lang.RuntimeException: RESTEASY004530: Could not find a method for: public abstract nz.co.vodafone.dx.email.model.EmailResponse nz.co.vodafone.dx.email.client.EmailApi.sendResetPassword(nz.co.vodafone.dx.email.model.ResetPasswordModel) throws nz.co.vodafone.dx.email.client.ApiException,javax.ws.rs.ProcessingException
    at org.jboss.resteasy.client.jaxrs.internal.proxy.ClientProxy.invoke(ClientProxy.java:74)
    at com.sun.proxy.$Proxy409.sendResetPassword(Unknown Source)
    at java.lang.reflect.Method.invoke(Method.java:566)
    at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:147)
    at com.sun.proxy.$Proxy410.sendResetPassword(Unknown Source)
    at nz.co.vodafone.dx.core.identity.config.EmailClient_1d1b8a582092d0ebdd2689e213c6e3419e43c95c_Synthetic_ClientProxy.sendResetPassword(EmailClient_1d1b8a582092d0ebdd2689e213c6e3419e43c95c_Synthetic_ClientProxy.zig:152)
    at nz.co.vodafone.dx.core.identity.service.EmailService.sendResetPassword(EmailService.java:66)
    at nz.co.vodafone.dx.core.identity.service.EmailService_ClientProxy.sendResetPassword(EmailService_ClientProxy.zig:194)
    at nz.co.vodafone.dx.core.identity.service.IdentityServiceImpl.sendResetPassword(IdentityServiceImpl.java:69)
    at nz.co.vodafone.dx.core.identity.service.IdentityServiceImpl_ClientProxy.sendResetPassword(IdentityServiceImpl_ClientProxy.zig:296)
    at nz.co.vodafone.dx.core.identity.IdentityResource.sendResetPassword(IdentityResource.java:81)
    at nz.co.vodafone.dx.core.identity.IdentityResource_Subclass.sendResetPassword$$superaccessor6(IdentityResource_Subclass.zig:976)
    at nz.co.vodafone.dx.core.identity.IdentityResource_Subclass$$function$$6.apply(IdentityResource_Subclass$$function$$6.zig:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
    at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:69)
    at io.quarkus.hibernate.validator.runtime.jaxrs.QuarkusRestEndPointValidationInterceptor.validateMethodInvocation(QuarkusRestEndPointValidationInterceptor.java:19)
    at io.quarkus.hibernate.validator.runtime.jaxrs.QuarkusRestEndPointValidationInterceptor_Bean.intercept(QuarkusRestEndPointValidationInterceptor_Bean.zig:341)
    at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
    at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
    at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
    at nz.co.vodafone.dx.core.identity.IdentityResource_Subclass.sendResetPassword(IdentityResource_Subclass.zig:931)
    at nz.co.vodafone.dx.core.identity.IdentityResource_ClientProxy.sendResetPassword(IdentityResource_ClientProxy.zig:296)
    at nz.co.vodafone.dx.core.identity.IdentityResource$quarkusrestinvoker$sendResetPassword_238d516cd15d3880980515fa896b2ce03a352085.invoke(IdentityResource$quarkusrestinvoker$sendResetPassword_238d516cd15d3880980515fa896b2ce03a352085.zig:45)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
    at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
    at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:117)
    at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:497)
 

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>

use below command to make native-image
mvn clean install -Pnative -Dquarkus.native.native-image-xmx=4g -DskipTests

Environment (please complete the following information):
Java Version
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

qurkus version : 1.11.3, main rest is resteasy-reactive
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>

use below command to make native-image
mvn clean install -Pnative -Dquarkus.native.native-image-xmx=4g -DskipTests

**Comment by geoand** [comment] 2021-02-17 10:52
Thanks for reporting.

Do you have a specific reproducer project you could share?

**Comment by queencge** [comment] 2021-02-17 11:10
with attached jar

Add depenency

```
    <!-- client -->
    <dependency>
      <groupId>nz.co.xxx.dx.client</groupId>
      <artifactId>microprofile-external-book</artifactId>
      <version>1.0.0-SNAPSHOT</version>
    </dependency>
```

In main service project, to call this client.
1. BookApi which is from library -> not working, JVM and native-image both
2. Create a interface
@RegisterRestClient(configKey = "microprofile-external-book-api")
@RegisterProvider(ApiExceptionMapper.class)
public interface BookClient extends BookApi
-> JVM working but native-image not working

3. need to create BookApi  in service project, BookApi  in client module(library) can't use it


[microprofile-external-book-1.0.0-SNAPSHOT.jar.zip](https://github.com/quarkusio/quarkus/files/5995134/microprofile-external-book-1.0.0-SNAPSHOT.jar.zip)

**Comment by geoand** [comment] 2021-02-17 11:13
Thanks for the reproducer, but it looks like it missing the source code.

**Comment by queencge** [comment] 2021-02-17 11:28
[client.tar.gz](https://github.com/quarkusio/quarkus/files/5995262/client.tar.gz)
I attached client library source.. but.. that is just auto-generated one which is from openapi-cli.

And.. I just import this with dependency to connect external service.

**Comment by geoand** [comment] 2021-02-17 11:29
@michalszynkiewicz mind taking a look at this?

**Comment by michalszynkiewicz** [comment] 2021-02-17 11:33
Does the library with the client interfaces provide a jandex index? You can find instructions for adding it [here](https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module)

**Comment by leonidr** [comment] 2021-07-22 10:51
@queencge  - I am having the same RESTEASY004530 with JAX-RS interface based proxy client in native image. Have you been able to overcome it?

**Comment by michalszynkiewicz** [comment] 2021-07-22 10:59
@leonidr does your library with client provide a jandex index?

If yes, can you please attach a whole reproducer, client library sources  + the sources of the project that uses it?

**Comment by michalszynkiewicz** [comment] 2021-07-23 09:58
I'm quite certain this is the problem with non-indexed client interfaces. 
Therefore I'm closing the issue.

If the linked instructions of adding dependencies to the index don't solve the problem, please reopen it with a full reproducer (or create a new one).

**Closed by michalszynkiewicz** 2021-07-23 09:58 UTC
Labels: kind/bug, triage/needs-triage

**Comment by cghislai** [comment] 2022-06-15 12:01
Just for reference, the lack of jandex index in my library was indeed the cause of the error I got. I was using the quarkus client reactive extension, and the error message was misleading: 'No jax-rs @Path annotation found on class X, or no method annotation found', or something similar. 

The linked stackoverflow answer above works. For my case (external library), i needed:
- to provide the quarkus.index-dependency config values for my lib in the build-time application.properties
- to add the index plugin in the pom
