### ISSUE TITLE
RESTEASY003210: Could not find resource for full path after updating to 1.4.2.Final

### ISSUE THREAD

**Issue by serrodcal** [quarkusio/quarkus#9401] opened 2020-05-18 09:44 UTC
**Describe the bug**
After updating my application from 1.3.2.Final to 1.4.2.Final I always get `RESTEASY003210: Could not find resource for full path: http://localhost:8080/swagger-ui` error trying to access to `http://localhost:8080/swagger-ui` resource.

**Expected behavior**
The browser should get the Swagger UI page.

**Actual behavior**
The output in DEBUG is the following:
```
2020-05-18 11:37:38,411 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-10) -Dio.netty.recycler.maxCapacityPerThread: 4096
2020-05-18 11:37:38,412 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-10) -Dio.netty.recycler.maxSharedCapacityFactor: 2
2020-05-18 11:37:38,412 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-10) -Dio.netty.recycler.linkCapacity: 16
2020-05-18 11:37:38,412 DEBUG [io.net.uti.Recycler] (vert.x-eventloop-thread-10) -Dio.netty.recycler.ratio: 8
2020-05-18 11:37:38,418 DEBUG [io.net.buf.AbstractByteBuf] (vert.x-eventloop-thread-10) -Dio.netty.buffer.checkAccessible: true
2020-05-18 11:37:38,418 DEBUG [io.net.buf.AbstractByteBuf] (vert.x-eventloop-thread-10) -Dio.netty.buffer.checkBounds: true
2020-05-18 11:37:38,419 DEBUG [io.net.uti.ResourceLeakDetectorFactory] (vert.x-eventloop-thread-10) Loaded default ResourceLeakDetector: io.netty.util.ResourceLeakDetector@4d411bf1
2020-05-18 11:37:38,474 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-10) -Dio.netty.noJdkZlibDecoder: false
2020-05-18 11:37:38,474 DEBUG [io.net.han.cod.com.ZlibCodecFactory] (vert.x-eventloop-thread-10) -Dio.netty.noJdkZlibEncoder: false
2020-05-18 11:37:38,514 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002315: PathInfo: /swagger-ui
2020-05-18 11:37:38,525 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002305: Failed executing GET /swagger-ui: javax.ws.rs.NotFoundException: RESTEASY003210: Could not find resource for full path: http://localhost:8080/swagger-ui
	at org.jboss.resteasy.core.registry.ClassNode.match(ClassNode.java:70)
	at org.jboss.resteasy.core.registry.RootClassNode.match(RootClassNode.java:47)
	at org.jboss.resteasy.core.ResourceMethodRegistry.getResourceInvoker(ResourceMethodRegistry.java:481)
	at org.jboss.resteasy.core.SynchronousDispatcher.getInvoker(SynchronousDispatcher.java:330)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:251)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

2020-05-18 11:37:38,534 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2020-05-18 11:37:38,534 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.StringTextStar
2020-05-18 11:37:38,534 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.StringTextStar
2020-05-18 11:37:38,537 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2020-05-18 11:37:38,537 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) Interceptor Context: org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext,  Method : proceed
2020-05-18 11:37:38,537 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.core.providerfactory.SortedKey
2020-05-18 11:37:38,537 DEBUG [org.jbo.res.res.i18n] (executor-thread-1) MessageBodyWriter: org.jboss.resteasy.plugins.providers.StringTextStar
```

**To Reproduce**
1. Add the dependency to the project:
    ```xml
     <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-smallrye-openapi</artifactId>
    </dependency>
    ```
2. Add the following class to specify the API documentation:
    ```java
    @OpenAPIDefinition(
        info = @Info(
                title="Fruit API",
                version = "1.0.0",
                contact = @Contact(
                        name = "Example API Support",
                        url = "http://exampleurl.com/contact",
                        email = "techsupport@example.com"),
                license = @License(
                        name = "Apache 2.0",
                        url = "http://www.apache.org/licenses/LICENSE-2.0.html"))
    )
    public class FruitApiApplication extends Application { }
    ```

**Configuration**
N/D

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin **** 18.7.0 Darwin Kernel Version 18.7.0: Mon Feb 10 21:08:45 PST 2020; root:xnu-4903.278.28~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
    ```
    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02)
    OpenJDK 64-Bit Server VM GraalVM CE 20.0.0 (build 11.0.6+9-jvmci-20.0-b02, mixed mode, sharing)
    ```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
    ```
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: ~/.m2/wrapper/dists/apache-maven-3.6.3- 
    bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
    Java version: 11.0.6, vendor: Oracle Corporation, runtime: 
    /Library/Java/JavaVirtualMachines/graalvm-ce-java11-20.0.0/Contents/Home
    Default locale: en_ES, platform encoding: UTF-8
    OS name: "mac os x", version: "10.14.6", arch: "x86_64", family: "mac"
    ```

**Comment by gastaldi** [comment] 2020-05-19 03:33
I can confirm this is reproducible with the steps above. Also It works with `mvn quarkus:dev`

**Comment by gastaldi** [comment] 2020-05-19 03:40
That happens because by default the swagger-ui is only included when the application is running in dev mode. 

To include it everytime, you need to add the following to your `application.properties`:
```properties
quarkus.swagger-ui.always-include=true
```

**Comment by gastaldi** [comment] 2020-05-19 03:41
This is documented here: https://quarkus.io/guides/openapi-swaggerui#use-swagger-ui-for-development

Closing as this is not a bug.

**Closed by gastaldi** 2020-05-19 03:41 UTC
Labels: kind/bug
