### ISSUE TITLE
JUnit-Extension with ParameterResolver leads to "RuntimeException: Could not find method XY on test class" with 1.3.0.Alpha1

### ISSUE THREAD

**Issue by vonatzigenc** [quarkusio/quarkus#7140] opened 2020-02-11 13:46 UTC
This bug affects only 1.3.0.Alpha1 and not earlier releases.

**Describe the bug**
JUnit test methods with a parameter provided by a ParameterResolver from a JUnit extension will throw a runtime exception originating from _io.quarkus.test.junit.quarkusTestExtension#runExtensionMethod_.

The probable cause is that the class is loaded with the ContextClassLoader, but the parameter types are not. Therefore _java.lang.Class#getDeclaredMethod_ throws a MethodNotFoundException.

**Expected behavior**
Testmethods using parameters should be executed, with instances of classes loaded by the correct classloaders.

**Actual behavior**
A runtime exception is thrown. It doesn't matter if the test is run through Maven or the IDE.

**To Reproduce**
1. Creating JUnit5-ParameterResolver, 
2. Add ParameterResolver to testclass with `@ExtendWith(ExampleJUnitExtension.class)`
3. Add parameter to JUnit-Test
4. Run test

**_ParamterResolver_**
```
public class ExampleJUnitExtension implements ParameterResolver {

    @Override
    public boolean supportsParameter(ParameterContext parameterContext, ExtensionContext extensionContext)
            throws ParameterResolutionException {
        return SomeDtoProvidedByParameterResolver.class.equals(parameterContext.getParameter().getType());
    }

    @Override
    public Object resolveParameter(ParameterContext parameterContext, ExtensionContext extensionContext)
            throws ParameterResolutionException {
        return new SomeDtoProvidedByParameterResolver();
    }

}
```

_**Test**_
```
@QuarkusTest
@ExtendWith(ExampleJUnitExtension.class) //JUnit-Extension added
public class ExampleResourceTest {

    @Test
    public void testHelloEndpoint(SomeDtoProvidedByParameterResolver parameter) { //Parameter added
        given()
                .when().get("/hello")
                .then()
                .statusCode(200)
                .body(is("hello"));
    }
}
```

**Configuration**
No config present

**Stacktrace**
Extract from stacktrace: ([complete_stacktrace_intellij-runner.txt](https://github.com/quarkusio/quarkus/files/4185907/complete_stacktrace_intellij-runner.txt))
```
java.lang.RuntimeException: Could not find method public void ch.vonatzigenc.ExampleResourceTest.testHelloEndpoint(ch.vonatzigenc.junitextension.SomeDtoProvidedByParameterResolver) on test class
    at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:357)
    at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:302)
    at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
    at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
    at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17134.1246]
 - Output of `java -version`: openjdk version "1.8.0_232"
 - GraalVM version (if different from Java): None
 - Quarkus version or git rev: 1.3.0.Alpha1

**Additional context**
(Add any other context about the problem here.)

**Comment by rquinio** [comment] 2020-02-18 16:42
Also reproduced with 1.3.0.Alpha2.
Seems to be a regression of "The big ClassLoader change".
My reproducer: https://github.com/rquinio/quarkus-reproducer-7140

**Comment by rquinio** [comment] 2020-03-09 08:30
cc @gsmet - any chance of this regression being looked at for 1.3.0 ?

**Comment by kaisernick** [comment] 2020-03-20 14:49
@rquinio @gsmet, I've been seeing this issue too. I created a JUnit to verify some Pacts (https://docs.pact.io/). I have a `@BeforeEach` method that accepts a `PactVerificationContext` parameter. I did some digging through `QuarkusTestExtension`. 

1) When `interceptBeforeEach(...)` calls `runExtensionMethod(invocationContext, extensionContext)` it uses the current thread’s class loader (`QuarkusClassLoader`) to create an instance of `Class`. 
2) Then it uses `invocationContext.getExecutable().getName()` and `invocationContext.getExecutable().getParameterTypes()` to find the extension method to run in the `Class` object. 
3) Name matches, but parameter types do not match. 

This does not work because there are two instances of parameter types, one in the `QuarkusClassLoader` and the other in the system class loader. We are trying to use the instance in the system class loader (`invocationContext.getExecutable().getParameterTypes()`) to find the instance in the `QuarkusClassLoader`, they are not the same, so will never match. This is what causes the NoSuchMethodError which gets ignored and causes the RuntimeException. I hope this helps.

**Comment by davidhervas** [comment] 2020-03-26 13:31
Hi everyone,

I wanted to upgrade my Quarkus application from version 1.0.1.Final to 1.3.0.Final but I can't because this bug cause my Pact tests to fail. I will upgrade to 1.2.0.Final.

Is a correction can be added in 1.3.1 ?

Thanks by advance.

**Comment by sean-scott-lr** [comment] 2020-03-31 15:52
@stuartwdouglas Can you provide some guidance on this?  Maybe a suggested workaround?  We are have this issue with our Pact testing as well.

**Comment by ppurdy** [comment] 2020-03-31 18:16
1.3.1 Final has changed this bug slightly.  Now the method is found, but the method cannot be invoked and produces an IllegalArgumentException.

In runExtensionMethod:

            List<Object> originalArguments = invocationContext.getArguments();  // These arguments come from the System Class Loader
            List<Object> argumentsFromTccl = new ArrayList<>();
            for (Object arg : originalArguments) {
                if (arg != null && arg.getClass().isEnum()) {
                    argumentsFromTccl.add(Enum.valueOf((Class<Enum>) Class.forName(arg.getClass().getName(), false,
                            Thread.currentThread().getContextClassLoader()), arg.toString()));
                } else {
                    // we can't do anything but hope for the best...
                    argumentsFromTccl.add(arg);
                }
            }

 
// actualTestInstance is in the Quarkus Class Loader and the method is being invoked with and instance of an object loaded in the System Class Loader
            return newMethod.invoke(actualTestInstance, argumentsFromTccl.toArray(new Object[0]));

**Comment by aloubyansky** [comment] 2020-06-23 12:25
The issue described in the original description appears to be fixed in 1.5.0.Final. Please, give 1.5.2.Final a try and if it still fails for some of you, please, open a new issue with a reproducer and/or detailed instructions to reproduce the issue. Thanks everyone!

**Closed by aloubyansky** 2020-06-23 12:25 UTC
Labels: kind/bug

**Comment by tioback** [comment] 2021-07-06 14:19
@aloubyansky - this issue seems to have resurfaced in 2.0.0.Final.

    ./mvnw test -f integration-tests/hibernate-validator -Dtest=HibernateValidatorFunctionalityTest

Running the above line breaks on master.

**Comment by tioback** [comment] 2021-07-06 14:52
In a sense, you're right.

It works if you go only through `mvnw`:

```console
./mvnw -Dquickly
./mvnw test -f integration-tests/hibernate-validator -Dtest=HibernateValidatorFunctionalityTest
```

However, if you try to run and test through IntelliJ, or build it through IntelliJ and run it through `mvnw`, then it breaks.

I'm guessing they haven't added the proper support for 2.0.0.Final to it, yet.
