### ISSUE TITLE
@QuarkusTest (Jacoco) ignores lombok.config & pitests fail with timeout

### ISSUE THREAD

**Issue by Manfred73** [quarkusio/quarkus#29160] opened 2022-11-09 21:11 UTC
### Describe the bug

I have annotated all my tests with @QuarkusTest and added the quarkus-jacoco as a test dependency to my pom. No further jacoco plugin configuration as I understand this is not needed when adding this dependency. Is this the best way to write unittests for Quarkus without any further configuration to your pom?

I'm using lombok in my project and have added a lombok.config in the root of my project:
```
config.stopBubbling = true
lombok.addLombokGeneratedAnnotation = true 
```
Version of lombok 1.18.24.

However, when the project and sonar coverage is run on the buildserver, I get some major issue on my data classes which have been annotated with lombok annotations that private fields should be removed.
It seems the lombok.config is being ignored.

This configuration is working fine for another project where I use Spring Boot, but for that I also have configured the jacoco plugin in my pom (version 0.8.8). 

Besides coverage with jacoco/sonar, I also run pitests using the (version 1.9.9 of pitest-maven and 1.1.0 of pitest-junit5-plugin) and every mutation test fails with Timout error. And if I increase the timeout, some run into failure and others still into a timeout. The same configuration for unittests in a Spring Boot application work fine.

Could these issues be related to the @QuarkusTest and should I remove this from my tests and instead configure the jacoco plugin? 

### Expected behavior

Lombok generated code should be ignored.
Expect pittest to run correctly.

### Actual behavior

Lombok generated code is not ignored. Sonar reports major issues on data classes with generated lombok code.
Pittests should not all run into a timeout.

**Comment by geoand** [comment] 2022-11-10 06:48
What configuration of the jacoco-plugin do you make in your non-Quarkus projects that results in lombok config being used properly?

**Comment by Manfred73** [comment] 2022-11-10 07:30
I have the following config in a parent pom for jacoco in my Spring Boot projects:

```
<plugin>
	<groupId>org.jacoco</groupId>
	<artifactId>jacoco-maven-plugin</artifactId>
	<version>0.8.8</version>
	<executions>
		<execution>
			<id>pre-unit-test</id>
			<goals>
				<goal>prepare-agent</goal>
			</goals>
			<configuration>
				<!-- Sets the path to the file which contains the execution data. -->
				<destFile>${sonar.jacoco.reportPath}</destFile>
				<propertyName>surefireArgLine</propertyName>
			</configuration>
		</execution>
		<!-- Ensures that the code coverage report for unit tests is created after unit tests have been run. -->
		<execution>
			<id>post-unit-test</id>
			<phase>test</phase>
			<goals>
				<goal>report</goal>
			</goals>
			<configuration>
				<!-- Sets the path to the file which contains the execution data. -->
				<dataFile>${sonar.jacoco.reportPath}</dataFile>
				<!-- Sets the output directory for the code coverage report. -->
				<outputDirectory>${jacoco.path}</outputDirectory>
			</configuration>
		</execution>
	</executions>
</plugin>
```

With my Quarkus application I don't have this config, but only included:
```
<!-- Plugin in Intellij fails with errors: IllegalClassFormatException: Error while instrumenting.....
	 See: https://stackoverflow.com/questions/69906908/jacoco-java-lang-instrument-illegalclassformatexception-error-while-instrumenti
	 See: https://github.com/quarkusio/quarkus/issues/16358
	 Not everything is showing 100% coverage in Intellij, although the generated reports in target folder look OK.
-->
<dependency>
	<groupId>io.quarkus</groupId>
	<artifactId>quarkus-jacoco</artifactId>
	<scope>test</scope>
</dependency>
```

**Comment by geoand** [comment] 2022-11-10 07:34
Thanks

**Comment by geoand** [comment] 2022-11-10 07:36
Any chance you can share a sample project that we can use for debugging?

**Comment by Manfred73** [comment] 2022-11-10 08:14
I can't post my current project here, but I will see if I can create one somewhere this week or next week.

**Comment by geoand** [comment] 2022-11-10 08:15
Great, thanks

**Comment by Manfred73** [comment] 2022-11-11 15:25
Sample project added: https://github.com/Manfred73/file-repository-rest-service

**Comment by famod** [comment] 2022-11-11 15:33
FWIW, in one of my projects I have lombok and quarkus-jacoco and lombok.config is used just fine (Quarkus 2.13.3 and 2.14.0).

**Comment by Manfred73** [comment] 2022-11-11 16:26
> FWIW, in one of my projects I have lombok and quarkus-jacoco and lombok.config is used just fine (Quarkus 2.13.3 and 2.14.0).

Do you have lombok.config in the roof of your project or under the src folder? And your sonar is not complaining about unused private fields in your data/dto classes where you use Lombok?

**Comment by famod** [comment] 2022-11-11 16:48
> Do you have lombok.config in the root of your project or under the src folder?

Root of the project.

> And your sonar is not complaining about unused private fields in your data/dto classes where you use Lombok?

I'm not using sonar, we are using a Jenkins plugin instead.
It seems others have had your issue before: https://stackoverflow.com/questions/58319017/sonarqube-remove-this-unused-private-field-code-smell-using-lombok-data

To me it seems it's more of a sonar-specific issue.

> Are you also using pitest by any chance?

No.

**Comment by Manfred73** [comment] 2022-11-11 20:39
> To me it seems it's more of a sonar-specific issue.

Maybe, but i still don't understand why it works for a spring boot configuration where I don't get these issues reported in sonar. The difference is that I have configured the jacoco plugin which is not the case in my quarkus project where I only use the quarkus-jacoco dependency, which leads me to believe this is somehow working differently.

**Comment by geoand** [comment] 2022-11-14 07:39
I tried your reproducer and everything worked as expected.

**Comment by Manfred73** [comment] 2022-11-14 07:55
When I look in Sonar, I see these major issues.
![image](https://user-images.githubusercontent.com/13829887/201604900-daa8fe4b-523b-4ee6-8732-e4232b2cb1ff.png)

What about the pitests when you run with ```mvn verify -Pit``` ?

**Comment by geoand** [comment] 2022-11-14 08:00
> What about the pitests when you run with mvn verify -Pit ?

I just ran that and it worked

**Comment by Manfred73** [comment] 2022-11-14 08:18
Sorry, I meant: ```mvn verify -Ppit```.   The previous only runs the integration test, this one runs pit tests.

**Comment by geoand** [comment] 2022-11-14 08:28
I haven no idea what pitest, does, so I can't really debug that

**Comment by Manfred73** [comment] 2022-11-14 08:30
We use pitest maven-plugin for our mutation testing: https://pitest.org/

**Comment by geoand** [comment] 2022-11-14 08:32
Yeah, I understand that, my point is that because I don't know how it works, I can't really dig into what's going on in your application

**Comment by Manfred73** [comment] 2022-11-22 21:29
OK, https://github.com/hcoles/pitest/issues/1072 might have a solution for that, so hopefully this will be solved by a newer version of the pitest maven plugin.
With regards to the sonar issue: we use ```sonar-scanner``` in our pipeline task, so we may have to try running ```mvn sonar:sonar``` instead as described in the posting https://stackoverflow.com/questions/58319017/sonarqube-remove-this-unused-private-field-code-smell-using-lombok-data

**Comment by geoand** [comment] 2022-11-23 05:21
Thanks for the update.

I am going to close this as it's not a Quarkus issue

**Closed by geoand** 2022-11-23 05:21 UTC
Labels: kind/bug, area/testing

**Comment by Manfred73** [comment] 2022-12-15 17:55
In case anybody else was having issues with QuarkusTest and pittest: the RUN_ERRORS were solved in newer version of pittest. With a bit of tweaking the configuration settings (mainly the timeout), pittests are now running fine against QuarkusTest as well. See: https://github.com/hcoles/pitest/issues/1072.

**Comment by Manfred73** [comment] 2023-01-06 12:14
Another update:

I can confirm that PITest is running much better after having rewritten tests to be pure unittests (removing @QuarkusTest using constructor injection).
The only tests I still annotate with @QuarkusTest are the Resource/Controller classes which I test using RestAssured.
I do notice however, when PIT mutates these classes, it complains about coverage (which is 0%), so I've excluded these classes annotated with @QuarkusTest from PIT.
