### ISSUE TITLE
MongoHealthCheck doesn't work

### ISSUE THREAD

**Issue by stefanwendelmann** [quarkusio/quarkus#23405] opened 2022-02-03 10:24 UTC
### Describe the bug

MongoDB connection health check always UP

Quarkus Version: `2.6.3.Final`

### Expected behavior

`"status": "DOWN"` when MongoDB is not reachable

### Actual behavior

`"status": "UP"` when MongoDB is not reachable

## Sources

pom.xml
```xml
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jsonb</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mongodb-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-health</artifactId>
    </dependency>
  </dependencies>
```

`src/main/java/com/acme/MyLivenessCheck.java`

```java
@Liveness
public class MyLivenessCheck implements HealthCheck {

    @Override
    public HealthCheckResponse call() {
        return HealthCheckResponse.up("alive");
    }

}
```

## Build

Native Build
```shell
./mvnw package -Pnative

```

And run in a Docker Environment using the `src/main/docker/Dockerfile.native`

```dockerfile
FROM quay.io/quarkus/quarkus-micro-image:1.0
WORKDIR /work/
RUN chown 1001 /work \
    && chmod "g+rwX" /work \
    && chown 1001:root /work
COPY --chown=1001:root target/*-runner /work/application

EXPOSE 8080
USER 1001

CMD ["./application", "-Dquarkus.http.host=0.0.0.0"]
```

## Test it

```shell
curl -sk http://localhost:8080/q/health |  jq
```

Returns but Mongo DB is shut down

```json 
{
  "status": "UP",
  "checks": [
    {
      "name": "alive",
      "status": "UP"
    },
    {
      "name": "MongoDB connection health check",
      "status": "UP"
    }
  ]
}
```

### Output of `uname -a` or `ver`

quay.io/quarkus/quarkus-micro-image:1.0

### Output of `java -version`

quay.io/quarkus/ubi-quarkus-native-image:21.3.0-java11

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.3.0-java11

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

quay.io/quarkus/ubi-quarkus-native-image:21.3.0-java11

**Comment by loicmathieu** [comment] 2022-02-03 16:18
Yes, if no request has been done, by design the MongoDB client will not be created (it is created lazily) so the health check will be OK.
If it's the case here, it's a duplicate of #22934

**Comment by geoand** [comment] 2022-02-03 16:21
Thanks

**Closed** 2022-02-03 16:21 UTC
Labels: kind/bug, area/smallrye, area/mongodb, area/health
