### ISSUE TITLE
Constructor injection in JAX-RS Resource which extends the class causes a RuntimeException

### ISSUE THREAD

**Issue by Denistr** [quarkusio/quarkus#27081] opened 2022-08-02 09:57 UTC
### Describe the bug

Constructor injection in an RX-Resource class, which extends another class raise an RuntimeException.

```
Caused by: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class: org.test.openapi.NewRestApi
        at org.jboss.resteasy.spi.metadata.ResourceBuilder.getConstructor(ResourceBuilder.java:852)

```
If I put @ApplicationScoped at my resource, then application starts successfully. This issue is not reproduced on 2.7.4.Final

### Expected behavior

Quarkus' applications is started successfully

### Actual behavior

On startup:
Caused by: java.lang.RuntimeException: RESTEASY003190: Could not find constructor for class

### How to Reproduce?

checkout this repo https://github.com/Denistr/quarkus-openapi-test

and then
`mvn compile quarkus:dev`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19044.1826]

### Output of `java -version`

openjdk version "11" 2018-09-25 OpenJDK Runtime Environment 18.9 (build 11+28) OpenJDK 64-Bit Server VM 18.9 (build 11+28, mixed mode)

### Quarkus version or git rev

2.10.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

ava version: 11, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-11 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment] 2022-08-02 10:46
CC @geoand

**Comment by geoand** [comment] 2022-08-02 10:51
Isn't this a duplicate of https://github.com/quarkusio/quarkus/issues/27022?

**Comment by Denistr** [comment] 2022-08-02 11:04
No, it is separate issue which occurred at runtime. 
I used the same git repo for this issue, but different resources

I will test it using RESTEasy Reactive very soon

**Comment by Denistr** [comment] 2022-08-02 14:02
I have tested with RESTEasy Reactive. The issue is resolved
But what if I don't need reactive feature and I would like to use normal quarkus-resteasy lib?

**Comment by geoand** [comment] 2022-08-02 14:11
RESTEasy Reactive is not only about reactive, you can do normal blocking code as well (see the various blog posts we have on the issue).

It's also the REST stack we are focusing moving forward.

**Comment by fercomunello** [comment] 2022-08-16 23:54
> It's also the REST stack we are focusing moving forward.

@geoand Quarkus integrates very well with Vert.x and even more for applications using reactive JAX-RS or Reactive Routes, but this not means that applications that are using RESTEasy Classic will become deprecated in the near future, right?

**Comment by geoand** [comment] 2022-08-17 04:51
They won't become deprecated.

My point is that we will focus our efforts on RESTEasy Reactive going forward

**Comment by geoand** [comment] 2022-09-02 11:59
I am going to close this as it would probably take some work to get this working and TBH I'd rather focus on other things, especially considering that 2 alternatives exist:

* Use field injection
* Use RESTEasy Reactive

**Closed by geoand** 2022-09-02 11:59 UTC
Labels: kind/bug, area/resteasy
