### ISSUE TITLE
Quarkus Test fails with 'This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?'

### ISSUE THREAD

**Issue by lukedipa** [quarkusio/quarkus#6696] opened 2020-01-21 16:42 UTC
**Describe the bug**
Quarkus tests fail with 'This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?' if I add in the same test class a method which returns an entity used in the test method.

Here are my entity and test classes:

```@Entity
public class Message extends PanacheEntity {
    public String content;
    public String status;
}
```

and my test class:

```@QuarkusTest
public class EntitiesTest {
    @Test
    @Transactional
    void deleteAllMessages() {
        Message.deleteAll();
        List<Message> messages=Message.listAll();
        assertNotNull(messages);
        assertEquals(0, messages.size());
    }

    private static Message createMsg() {
        return null;
    }

    @Test
    @Transactional
    void findAllUsers() {
        List<UserAccount> users=UserAccount.listAll();
        assertNotNull(users);
    }
}
```
As long as the createMsg method (which actually is meant to create a new instance of Message) remains there (even unused!), the test deleteAllMessages() will fail when executing Message.deleteAll() as written above, whereas findAllUsers() still works properly. This makes usage of helper methods impossible.

**Comment by geoand** [comment] 2020-01-21 21:43
This is a duplicate of #1724

**Closed by geoand** 2020-01-21 21:43 UTC
Labels: kind/bug

**Comment by lukedipa** [comment] 2020-01-22 07:37
Ok, thank you!
