### ISSUE TITLE
Thread blocked when starting multiple instances of gRPC server with SSL

### ISSUE THREAD

**Issue by fberthelon** [quarkusio/quarkus#29349] opened 2022-11-18 11:31 UTC
### Describe the bug

After upgrading from Quarkus 2.10.4 to 2.13.3, our gRPC server was throwing thread blocked exception indefinitely. After investigation, we found that the issue started with Quarkus 2.13.1 and still occurs in 2.14.1.

We are able to reproduce the issue with a minimal application (code sample generated from Quarkus.io) including gRPC with SSL and multiple instances.

This issue does not happen in dev mode.

### Expected behavior

Application starting multiple SSL instances of the gRPC server

### Actual behavior

Application never start because of thread blocked indefinitely

### Exception:

```
2022-11-18 12:02:59,044 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-7,5,main] has been blocked for 3951 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
        at java.base@18.0.1.1/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1726)
        at io.vertx.grpc.VertxServer.start(VertxServer.java:177)
        at io.quarkus.grpc.runtime.GrpcServerRecorder$GrpcServerVerticle.start(GrpcServerRecorder.java:484)
        at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
        at io.vertx.core.impl.DeploymentManager$$Lambda$982/0x00000008010a0f78.handle(Unknown Source)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
        at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
        at io.vertx.core.impl.EventLoopContext$$Lambda$983/0x00000008010a1188.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@18.0.1.1/java.lang.Thread.run(Thread.java:833)
```

### Steps to reproduce the behavior:

1. Create quarkus application with gRPC extension (https://code.quarkus.io/d?e=grpc&cn=code.quarkus.io)
2. Configure SSL certificate for gRPC server (quarkus.grpc.server.ssl.key  and quarkus.grpc.server.ssl.certificate)
3. Configure more than one instance (quarkus.grpc.server.instances)
4. run tests (mvn test)
6. After few seconds the following exception is displayed:
Thread Thread[vert.x-eventloop-thread-5,5,main] has been blocked for 3937 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked

Another option to reproduce it, is to package the application in native mode and start it with the same configuration.

### pom.xml

```
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>code-with-quarkus</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.release>17</maven.compiler.release>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.14.1.Final</quarkus.platform.version>
    <skipITs>true</skipITs>
    <surefire-plugin.version>3.0.0-M7</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-grpc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <compilerArgs>
            <arg>-parameters</arg>
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-failsafe-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <executions>
          <execution>
            <goals>
              <goal>integration-test</goal>
              <goal>verify</goal>
            </goals>
            <configuration>
              <systemPropertyVariables>
                <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                <maven.home>${maven.home}</maven.home>
              </systemPropertyVariables>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <properties>
        <skipITs>false</skipITs>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```

### application.properties

```
quarkus.grpc.server.instances=10
quarkus.grpc.server.ssl.key=<PEM KEY PATH>
quarkus.grpc.server.ssl.certificate=<PEM CERTIFICATE PATH>
```

### Output of `java -version`

openjdk version "18.0.1.1" 2022-04-22 OpenJDK Runtime Environment (build 18.0.1.1+2-6) OpenJDK 64-Bit Server VM (build 18.0.1.1+2-6, mixed mode, sharing)

### GraalVM version (if different from Java)

mandrel-java17-22.3.0.1-Final

### Quarkus version or git rev

2.14.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 18.0.1.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-18.0.1.1 Default locale: en_IE, platform encoding: UTF-8 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

Thanks for your support and amazing tools you build

**Comment by cescoffier** [comment] 2022-11-18 12:44
The question is whether the same happen with the new gRPC server.

**Comment by Karm** [comment] 2022-11-18 13:36
Hello, @fberthelon, you included Mandrel version, does it mean this issue is native-image specific? If so, building Java classes with JDK 18 and compiling to native with JDK 17 based Mandrel is ill advised.

Please, clarify if this is a native-image specific bug report.

Cheers

**Comment by fberthelon** [comment] 2022-11-18 13:39
Hello @Karm,
I was able to reproduce the issue in both cases native image and running test locally (JVM).
The only case where this issue cannot be reproduced is starting the application in dev mode.

**Comment by Karm** [comment] 2022-11-18 13:41
@fberthelon Ack. I will remove the native image label then.

**Comment by cescoffier** [comment] 2023-07-31 07:06
Can you provide a reproducer? I was not able to reproduce it locally.

**Comment by geoand** [comment] 2023-08-30 05:07
Closing for a lack of a reproducer

**Closed by geoand** 2023-08-30 05:07 UTC
Labels: kind/bug, env/windows, area/grpc, triage/needs-reproducer
