### ISSUE TITLE
Quarkus Mailer fails to run in native mode

### ISSUE THREAD

**Issue by madduci** [quarkusio/quarkus#13996] opened 2020-12-21 04:52 UTC
I've written a service which is responsible of sending emails to a recipient and follows [this guide](https://quarkus.io/guides/mailer). The same code, if run on JVM as it is, works perfectly, with both Mailer and ReactiveMailer. If it is compiled native with GraalVM, it throws an UnknownHostException on the SMTP Server, which is correct (e.g. smtp.office365.com).

The Mailer should send emails in native code without error.

An UnknownHostException is thrown when contacting the SMTP server.

**To Reproduce**

1. Create a demo like in the official Guide: https://quarkus.io/guides/mailer
2. Compile it native
3. Run

**Configuration**
```properties
quarkus.mailer.auth-methods=DIGEST-MD5 CRAM-SHA256 CRAM-SHA1 CRAM-MD5 PLAIN LOGIN
quarkus.mailer.from=${EMAIL_USERNAME}
quarkus.mailer.host=smtp.office365.com
quarkus.mailer.port=587
quarkus.mailer.start-tls=REQUIRED
quarkus.mailer.username=${EMAIL_USERNAME}
quarkus.mailer.password=${EMAIL_PASSWORD}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Linux 5.9.11-3-MANJARO #1 SMP PREEMPT Sat Nov 28 09:08:57 UTC 2020 x86_64 GNU/Linux
 - Output of `java -version`:  15.0.1
 - GraalVM version (if different from Java):  20.03
 - Quarkus version or git rev:  1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.3

**Comment by geoand** [comment] 2020-12-21 07:32
cc @cescoffier

**Comment by gsmet** [comment] 2020-12-21 09:35
Any chance we could have the full stracktrace? Thanks.

**Comment by madduci** [comment] 2020-12-21 14:16
I'm trying to reproduce again a full stacktrace, at the moment the quarkus Docker image seems to trigger errors like missing libraries (both `quay.io/quarkus/ubi-quarkus-native-image:20.3.0-java11` and `quay.io/quarkus/ubi-quarkus-native-image:20.2.0-java11`)

**Comment by madduci** [comment] 2020-12-29 11:09
I've managed to produce the full stacktrace again:

`
2020-12-29 11:06:56,672 INFO  [io.quarkus] (main) mycalisthenicsapp 1.0.0-SNAPSHOT native (powered by Quarkus 1.10.3.Final) started in 0.029s. Listening on: http://0.0.0.0:8080
2020-12-29 11:06:56,673 INFO  [io.quarkus] (main) Profile prod activated. 
2020-12-29 11:06:56,673 INFO  [io.quarkus] (main) Installed features: [cdi, hibernate-validator, mailer, mutiny, qute, resteasy, resteasy-jsonb, smallrye-context-propagation, smallrye-health, smallrye-metrics, vertx]
2020-12-29 11:07:04,453 INFO  [io.qua.htt.access-log] (vert.x-eventloop-thread-0) 172.17.0.1 - - 29/Dec/2020:11:07:04 +0000 "GET / HTTP/1.1" 304 -
2020-12-29 11:07:42,795 ERROR [io.ver.ext.mai.imp.SMTPConnection] (vert.x-eventloop-thread-3) exception on connect: java.net.UnknownHostException: smtp.office365.com: System error
	at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_net_UnknownHostException_2_0002e_0003cinit_0003e_00028Ljava_lang_String_2_00029V(JNIJavaCallWrappers.java:0)
	at java.net.Inet4AddressImpl.lookupAllHostAddr(Inet4AddressImpl.java)
	at java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:929)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1515)
	at java.net.InetAddress$NameServiceAddresses.get(InetAddress.java:848)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1505)
	at java.net.InetAddress.getAllByName(InetAddress.java:1364)
	at java.net.InetAddress.getAllByName(InetAddress.java:1298)
	at java.net.InetAddress.getByName(InetAddress.java:1248)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
	at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
	at java.security.AccessController.doPrivileged(AccessController.java:119)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
	at io.netty.bootstrap.Bootstrap.doResolveAndConnect(Bootstrap.java:162)
	at io.netty.bootstrap.Bootstrap.connect(Bootstrap.java:139)
	at io.vertx.core.net.impl.ChannelProvider.handleConnect(ChannelProvider.java:140)
	at io.vertx.core.net.impl.ChannelProvider.connect(ChannelProvider.java:93)
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:211)
	at io.vertx.core.net.impl.NetClientImpl.doConnect(NetClientImpl.java:168)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:116)
	at io.vertx.core.net.impl.NetClientImpl.connect(NetClientImpl.java:110)
	at io.vertx.ext.mail.impl.SMTPConnection.openConnection(SMTPConnection.java:176)
	at io.vertx.ext.mail.impl.SMTPStarter.start(SMTPStarter.java:52)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.createConnection(SMTPConnectionPool.java:247)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.createNewConnection(SMTPConnectionPool.java:231)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection0(SMTPConnectionPool.java:155)
	at io.vertx.ext.mail.impl.SMTPConnectionPool.getConnection(SMTPConnectionPool.java:81)
	at io.vertx.ext.mail.impl.MailClientImpl.getConnection(MailClientImpl.java:101)
	at io.vertx.ext.mail.impl.MailClientImpl.lambda$sendMail$1(MailClientImpl.java:85)
	at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:327)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:834)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)

2020-12-29 11:07:42,795 INFO  [app.web.myc.res.PersonResource] (executor-thread-1) java.net.UnknownHostException: smtp.office365.com: System error
2020-12-29 11:07:42,797 INFO  [io.qua.htt.access-log] (executor-thread-1) 172.17.0.1 - - 29/Dec/2020:11:07:42 +0000 "POST /profile HTTP/1.1" 200 56
`

**Comment by cescoffier** [comment] 2021-01-04 09:00
I just tried with gmail (I don't have an office 365 account) and it works in native. 

The error seems related to DNS. Does it happen every time?

**Comment by cescoffier** [comment] 2021-01-04 09:36
@madduci I've created a new quickstart (using gmail): https://github.com/quarkusio/quarkus-quickstarts/pull/739. That's how I tested it in both JVM and native.

**Comment by madduci** [comment] 2021-01-04 10:13
@cescoffier thanks for the answer. Yes, it does happen everytime with office365, but only in native mode. In JVM it works just fine.

**Comment by cescoffier** [comment] 2021-01-04 16:15
@madduci Can you try with GraalVM CE 20.3.0.
I just tried (I don't have an account, but DNS lookup happen before authentication), and I got:

```
2021-01-04 17:12:45,181 ERROR [org.jbo.res.res.i18n] (vert.x-eventloop-thread-2) RESTEASY002020: Unhandled asynchronous exception, sending back 500: io.vertx.core.impl.NoStackTraceThrowable: AUTH LOGIN failed 535 5.7.3 Authentication unsuccessful [MR2P264CA0034.FRAP264.PROD.OUTLOOK.COM]
```

which is expected...

**Comment by madduci** [comment] 2021-01-05 10:57
I've tested with the newer image to build the native executable (quay.io/quarkus/centos-quarkus-maven:20.3-java11) and now the process crashes (apparently a segmentation fault) without any output.

**Comment by cescoffier** [comment] 2021-01-05 15:53
Can you try with the quickstart I did, just changing it to use office365?

**Comment by madduci** [comment] 2021-01-06 13:30
The quickstart works fine as I've tested it with different Quarkus versions, but I've seen there's no active usage of the ReactiveMailer, but it's just injected, which is somehow different from what in the website is shown as example.

**Comment by cescoffier** [comment] 2021-01-09 09:26
Under the hood the template uses the mailer.

**Comment by madduci** [comment] 2021-01-14 08:32
Thanks for the clarification, perhaps the trick lies in the "native" keyword being used while invoking the Template method?

**Comment by cescoffier** [comment] 2021-01-14 11:40
I just tried without template and it worked.

**Comment by madduci** [comment] 2021-01-20 05:38
I don't know what to say, but stripping down my application to the base minimum and using the Mailer (not the reactive variant), I still get the stacktrace error with the UnknownHostException

**Comment by cescoffier** [comment] 2021-01-20 06:35
The non-reactive mailer runs on top of the reactive one. But here the problem is DNS, it's not the mailer. Which version of GraalVM do you use?

**Comment by madduci** [comment] 2021-01-20 10:28
I'm using the Graal 20.3 VM. What I don't understand is, the quickstarter project works fine, but in my implementation I've encapsulated the Mailer in an @ApplicationScoped service and using this service in my REST endpoint, thus generating the JNI error.

**Comment by madduci** [comment] 2021-01-20 12:07
It's definitively not a DNS problem, since I'm experiencing two different behaviors:

if I run my built application under a ubuntu:20.04 container, it crashes as soon as it calls the Mailer, without producing even a stacktrace.

If I run it under a gcr.io/distroless/base:latest, it generates the stacktrace error that I've posted at the beginning of this discussion.

Any extra hint to the DNS server and the extra host:IP mapping don't help.

For instance, my build process is this one:

```
# Stage that builds the application, a prerequisite for the running stage
FROM quay.io/quarkus/centos-quarkus-maven:20.3-java11 as backend

WORKDIR /usr/src/app/

USER root

# Copy pom.xml and prefetch dependencies so a repeated build can continue from the next step with existing dependencies
ADD backend /usr/src/app/
RUN mvn dependency:go-offline 

# Build Project
RUN mvn clean package -DskipTests -Pnative

# Running stage: the part that is used for running the application
FROM gcr.io/distroless/base:latest
LABEL maintainer="Michele Adduci <adduci@tutanota.com>"
COPY --from=backend /usr/src/app/target/*-runner /usr/app/app
ENTRYPOINT [ "/usr/app/app" ]
```

and I run the application like this:

`docker run --dns 8.8.8.8 --rm -it --name myapp -p 8080:8080 -e EMAIL_USERNAME=ACCOUNT@outlook.com -e EMAIL_PASSWORD=PASSWORD myapp:latest-native`

**Comment by cescoffier** [comment] 2023-01-09 07:18
Closing - it's been fixed a long time ago. Please open a new issue with a reproducer is the problem reappears.

**Closed by cescoffier** 2023-01-09 07:18 UTC
Labels: kind/bug
