### ISSUE TITLE
MP Fault Tolerance - default method fallback doesn't work in native mode

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#14394] opened 2021-01-19 12:25 UTC
**Summary**
I have a microprofile HttpClient on Native mode, and also a fallback action configured, then I got the following exception:

```
2021-01-18 10:36:17,661 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.RuntimeException: Not implemented in native mode
```

**Expected behavior**
Same as JVM mode (if HTTP request fail, then move on to fallback)

**Actual behavior**
```
2021-01-18 10:36:17,661 ERROR [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.RuntimeException: Not implemented in native mode
```

**To Reproduce**

Setup an HttpClient pointing to a not found URL

```
@RegisterRestClient(baseUri = "http://microprofile-test:8080/")
public interface HelloClient {
    
    @GET
    @Path("/hello/notFound")
    @Produces(MediaType.TEXT_PLAIN)
    @Asynchronous
    @Fallback(fallbackMethod = "fallback")
    CompletionStage<String> getWithFallback();

    default CompletionStage<String> fallback() {
        return completedFuture("Fallback");
    }
}
```

And then make a query: 
```
@Inject
@RestClient
HelloClient hello;

hello.getWithFallback().thenApply(result -> "Client got: " + result);
```

[Jira ref](https://issues.redhat.com/browse/QUARKUS-697)

**Comment by mkouba** [comment] 2021-01-19 13:05
CC @Ladicek 

SmallRye has a workaround for default fallback methods: `io.smallrye.faulttolerance.DefaultMethodFallbackProvider.getFallback(Method, ExecutionContextWithInvocationContext)`. However, this may not work in native mode and therefore the method is substituted in `io.quarkus.smallrye.faulttolerance.runtime.graal.Target_io_smallrye_faulttolerance_DefaultMethodFallbackProvider.getFallback()`.

**Comment by Ladicek** [comment] 2021-01-19 13:16
Yea I've noticed that, and chose to forget about it because supporting it will probably require non-trivial changes in SRye FT :-) Assigning to myself, but it will take a bit of time.

**Comment by geoand** [comment] 2021-02-17 14:15
I think in GraalVM 21 support method handles better now so maybe this can be re-examined?

**Comment by rsvoboda** [comment] 2021-03-16 08:02
@Ladicek can you look into this regression again? Quarkus is on GraalVM 21 now.

**Comment by Ladicek** [comment] 2021-03-16 09:04
I'll try (remove the substitution and verify), but no promises if it doesn't work out :-)

**Comment by Ladicek** [comment] 2021-03-16 11:58
Confirm that with GraalVM 21 and the substitution removed, it works. I'll take a look where to add a test and submit a PR.

**Comment by Ladicek** [comment] 2021-03-16 20:25
Submitted #15788.

**Comment by Ladicek** [comment] 2021-03-16 20:52
Also, let's make one thing clear: this is not a regression. This has never worked :-)

**Closed** 2021-03-17 09:35 UTC
Labels: area/smallrye, kind/bug, triage/needs-triage
