### ISSUE TITLE
CDI Instance memory leak

### ISSUE THREAD

**Issue by blsouthr** [quarkusio/quarkus#5209] opened 2019-11-05 10:28 UTC
Instance<SomeBean> is not destroying dependent beans. The array  "dependentInstances" of creationalContext is constantly growing, which eventually results in OOM.

Thorntail is working fine in that scenario. In Weld "dependentInstances" array has size 0.

1. Execute mvn test of attached project
2. The output shows that total free memory is decreasing
3. Alternatively, start the project and execute http://localhost:8080/hello/ok multiple times to observe the behavior in debugger. Screenshot attached/
4. To reproduce OOM quickly, increase array size in SomeBean and execute mvn test

[instance_memory_leak.zip](https://github.com/quarkusio/quarkus/files/3808431/instance_memory_leak.zip)
![DebugInstanceOutput](https://user-images.githubusercontent.com/56728828/68199649-b9590980-ffbe-11e9-834e-8ac949ec9f12.PNG)

**Comment by mkouba** [comment] 2019-11-05 11:32
Hello, I've checked the attached project and I can confirm that this is not a bug. Every invocation of `Instance<SomeBean>.get()` creates a new instance of `SomeBean` because it's `@Dependent` and _"An instance of a bean with scope @Dependent obtained by direct invocation of an Instance is a dependent object of the instance of Instance."_ (see the [6.4.1. Dependent objects](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#dependent_objects) in the spec. In other words, it's the responsibility of the client to destroy `@Dependent` instances manually through `Instance.destroy()`. See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#dynamic_lookup. 

It's probably not a problem in Thorntail because JAX-RS resources are `@RequestScoped` there (ie. a resource instance is created to service a single request only and then it's destroyed). In Quarkus however, a JAX-RS resource is `@Singleton` by default.

WORKAROUND:
1. Destroy an instance of `SomeBean` manually once not needed
2. Annotated the resource with `@RequestScoped`

**Comment by blsouthr** [comment] 2019-11-05 11:48
JAX-RS in my Thorntail app is annotated with @ApplicationScoped. Does Thorntail ignore it and applies @RequestScoped instead?

Wouldn't it make sense if Quarkus would also make JAX-RS @RequestScoped by default then?

**Comment by mkouba** [comment] 2019-11-05 12:08
> JAX-RS in my Thorntail app is annotated with @ApplicationScoped..

It shouldn't but I'm not 100% sure. @Ladicek WDYT?

> Wouldn't it make sense if Quarkus would also make JAX-RS @RequestScoped by default then?

Well, it's configurable - you can switch the default behavior via `quarkus.resteasy.singleton-resources=false`. More details on motivation can be found here: https://github.com/quarkusio/quarkus/issues/312

**Comment by Ladicek** [comment] 2019-11-05 12:21
I'm pretty sure Thorntail doesn't do anything to override Weld's and RESTEasy's behavior. If you annotate your JAX-RS resource `@ApplicationScoped`, then it's application scoped. I'm not sure if the default is `@RequestScoped`, but if @mkouba says it is, then it probably is :-)

**Comment by blsouthr** [comment] 2019-11-05 14:15
BTW, why this test has so bad performance? I changed the loop in test to run 1000 times and it takes ca 4 minutes with high cpu and memory usage:
![visualvm](https://user-images.githubusercontent.com/56728828/68215143-064cd800-ffdf-11e9-8f3e-e082d9cf1970.PNG)

**Comment by mkouba** [comment] 2019-11-05 15:40
@blsouthr Well, you allocate/fill an array of size 52 428 800 per each request (because a new `SomeBean` is created for each request). So even if you destroy the bean correctly the JVM has to do a lot of garbage collection (`Total time: 01:40 min` for 1000 requests on my laptop). Of course, if you don't destroy the bean you'll get `OutOfMemoryError` very soon.

**Comment by mkouba** [comment] 2019-11-05 15:46
Closing. Feel free to reopen if needed.

**Closed by mkouba** 2019-11-05 15:46 UTC
Labels: bug, invalid

**Comment by blsouthr** [comment] 2019-11-07 12:06
@mkouba Apparently, Weld did the optimization to solve the leak problem if 
there is no @PreDestroy callback so its not needed keeping the references 
https://issues.jboss.org/browse/WELD-1076
source: https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/contexts/unbound/DependentContextImpl.java#L88

Would it make sense to do the same enhancement in quarkus?

**Comment by mkouba** [comment] 2019-11-07 12:31
@blsouthr Good catch! Yes, I think that we could try to implement a similar optimization in quarkus. I've created https://github.com/quarkusio/quarkus/issues/5281.

**Comment by geoand** [comment] 2019-11-22 14:36
@tpenakov you mentioned that you saw similar behavior using the  Spring DI layer?

**Comment by tpenakov** [comment] 2019-11-22 14:53
Yes - Yesterday I've migrated one of my microservices to 1.0.0.CR1. I have a few Spring ConfigurableBeanFactory.SCOPE_PROTOTYPE beans there. 
Then the microservice become very unstable. Now I am trying to destroy the Instances as @mkouba suggested, but to be honest I am not happy at all, that I have to manage the memory of the JVM application manually. 
This is unexpected and unintuitive behavior and is totally different than the Spring framework

**Comment by geoand** [comment] 2019-11-22 15:26
@mkouba if you would like to add some more details to ##5281 I'd be glad to take a look at it

**Comment by mkouba** [comment] 2019-11-22 16:17
Ok, the idea behind this optimization is that if a `@Dependent` bean requires no "cleanup" (`@PreDestroy` callback/disposal method) and does not inject any other `@Dependent` bean that requires cleanup we don't have to store the instance in the `CreationalContext` (`CC.release()` is invoked when a bean is destroyed and ensures all `@Dependent` bean instances are destroyed correctly). I'm not really sure how difficult it could be to implement this elegantly in ArC. Feel free to look at it! ;-)

**Comment by geoand** [comment] 2019-11-22 18:17
Thanks @mkouba. I'll try and have a look soon
