### ISSUE TITLE
Fail to build Quarkus in master because of minikube dependency

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#7460] opened 2020-02-27 15:52 UTC
`./mvnw clean install`

```
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource io.quarkus.test.kubernetes.client.KubernetesMockServerTestResource@3676ac27
        at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:47)
        at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:179)
        at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:208)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$7(ClassBasedTestDescriptor.java:359)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:359)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:189)
        at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:132)
        ... 31 more
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:64)
        at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:199)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClientForMockServer(HttpClientUtils.java:69)
        at io.fabric8.kubernetes.client.server.mock.KubernetesMockServer.createClient(KubernetesMockServer.java:86)
        at io.quarkus.test.kubernetes.client.KubernetesMockServerTestResource.start(KubernetesMockServerTestResource.java:22)
        at io.quarkus.test.common.TestResourceManager.start(TestResourceManager.java:45)
        ... 39 more
Caused by: java.nio.file.NoSuchFileException: /Users/emmanuel/.minikube/client.crt
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:370)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:421)
        at java.base/java.nio.file.Files.readAllBytes(Files.java:3205)
        at io.fabric8.kubernetes.client.internal.CertUtils.getInputStreamFromDataOrFile(CertUtils.java:72)
        at io.fabric8.kubernetes.client.internal.CertUtils.createKeyStore(CertUtils.java:242)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:128)
        at io.fabric8.kubernetes.client.internal.SSLUtils.keyManagers(SSLUtils.java:122)
        at io.fabric8.kubernetes.client.utils.HttpClientUtils.createHttpClient(HttpClientUtils.java:85)
        ... 43 more
```

We need to list it as a required dependency and point to it.

**Comment by emmanuelbernard** [comment] 2020-02-27 15:52
@maxandersen @iocanel @geoand

**Comment by geoand** [comment] 2020-02-27 16:10
Minikube definitely isn't a dependency to running the tests, so there is something else funny going on here.

@emmanuelbernard can you please check `/Users/emmanuel/.kube/config` and see if there is any reference to minikube? 

@iocanel what would be the way to have https://github.com/quarkusio/quarkus/blob/master/test-framework/kubernetes-client/src/main/java/io/quarkus/test/kubernetes/client/KubernetesMockServerTestResource.java#L18 completely ignore the user's `.kube/config` file?

**Comment by iocanel** [comment] 2020-02-27 18:34
There is a property which allows to to disable it.
Will pay more details when I get back home.

**Comment by iocanel** [comment] 2020-02-27 18:36
The property is 'kubernetes.auth.tryKubeConfig' and can be passed as system property or it's corresponding environment variable.

**Comment by geoand** [comment] 2020-02-27 19:35
> The property is 'kubernetes.auth.tryKubeConfig' and can be passed as system property or it's corresponding environment variable.

If you open a PR, I'll approve it ASAP :)

**Comment by iocanel** [comment] 2020-02-27 21:53
PR incoming.

**Comment by geoand** [comment] 2020-02-28 06:21
@iocanel 's PR has been merged, can you give it another try sometime @emmanuelbernard ?

**Closed** 2020-02-28 06:21 UTC
Labels: area/kubernetes, kind/bug

**Comment by maxandersen** [comment] 2020-02-28 08:33
wait - tryKubeConfig is there to read the normal kubeconfig settings, right ? 
we should definitely read those - in this case i assume the issue is that emmanuel has a file that point to settings/files that does not exist ?

**Comment by maxandersen** [comment] 2020-02-28 08:34
ah PR is just for preventing this to happen during testing...never mind ;)

**Comment by geoand** [comment] 2020-02-28 08:34
@maxandersen In this case you want the client to only contact the mock server. So I don't think that reading the settings does any good.

**Comment by emmanuelbernard** [comment] 2020-02-28 11:09
Ok so indeed I had a .kube/config with minikube refs but I had removed minikube a long time ago.

**Comment by maxandersen** [comment] 2020-02-28 12:01
PEBCAK's are the best :) but good find as the tests shouldn't be affected byit.

**Comment by geoand** [comment] 2020-02-28 12:26
Good find indeed 👍
