### ISSUE TITLE
package org.springframework.data.jpa.domain.support does not exist

### ISSUE THREAD

**Issue by ajaykushwaha1** [quarkusio/quarkus#22020] opened 2021-12-08 11:17 UTC
### Discussed in https://github.com/quarkusio/quarkus/discussions/22019

<div type='discussions-op-text'>

<sup>Originally posted by **ajaykushwaha1** December  8, 2021</sup>
Hi, 

I am migrating my project from spring-boot to quarkus and using the below dependency for spring-data-jpa.

**groupId: io.quarkus
    artifactId: quarkus-spring-data-jpa
     version: 2.5.0.Final**

I have to use AuditingEntityListener for auditing purpose. But I am getting compilation error :  **package org.springframework.data.jpa.domain.support does not exist.** Can any one help on this?

I am using below import for AuditingEntityListener,

 **org.springframework.data.jpa.domain.support.AuditingEntityListener**

![image](https://user-images.githubusercontent.com/36269701/145198895-ec4c153c-d758-4ec7-8604-6909ae1ca8bf.png)
</div>

**Comment by geoand** [comment] 2021-12-08 11:22
cc @aureamunoz @Sgitario

**Comment by Sgitario** [comment] 2021-12-08 17:29
@geoand I will work on this!

**Comment by geoand** [comment] 2021-12-08 18:19
Great! You will have to coordinate with @aureamunoz on this

**Comment by aureamunoz** [comment] 2021-12-10 12:06
I have taken a look on that and the problem is that it requires spring aspects also to be processed so I'm not sure that it can work even if we add the classes to our custom jar.
cc @geoand @Sgitario

**Comment by geoand** [comment] 2021-12-10 12:14
Which aspects does it require?

**Comment by aureamunoz** [comment] 2021-12-10 12:55
org.springframework.beans.factory.aspectj.ConfigurableObject

> Which aspects does it require?

`org.springframework.beans.factory.aspectj.ConfigurableObject`

**Comment by geoand** [comment] 2021-12-10 13:00
Oh... Yeah, that will definitely not work

**Comment by geoand** [comment] 2021-12-10 13:00
So let's close this as `won't fix`

**Closed by geoand** 2021-12-10 13:00 UTC
Labels: area/spring
