### ISSUE TITLE
graphql-ui issue show Â on each line and near the cursor 

### ISSUE THREAD

**Issue by MartinSem** [quarkusio/quarkus#23914] opened 2022-02-23 14:00 UTC
**Describe the issue**
After the upgrade to Quarkus 2.7.0 and maven 3.8.3, graphql-ui show a Â on each line and near the cursor.
It happens only on window local environment, there is no issue  when we deploy it into a kubernetes container.

![image](https://user-images.githubusercontent.com/38289371/155333825-c52509f5-759f-4365-ac14-6b06360e5f3b.png)

**Environment info**
`$ mvn -v
Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)
Java version: 11.0.7, vendor: Oracle Corporation, runtime: ***
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
`

Is there anyway to handle this?

**Comment by phillip-kruger** [comment] 2022-02-23 23:13
I think it's due to platform encoding: Cp1252. I'll see if I can fix that, but if you can change to UTF8 that might solve it

**Comment by jmartisk** [comment] 2022-02-24 08:31
I'm trying to reproduce this on my Windows machine that also uses CP1252, but I'm not successful. 
I tried compiling  and running the application there, 
I also tried compiling and running it on the linux/UTF8 machine but accessing it from the Windows machine, 
but no luck. We might need some more info, like your pom.xml, or built jar files,....

**Comment by gsmet** [comment] 2022-02-28 19:04
@MartinSem care to share some information?

@phillip-kruger @jmartisk I wonder if it could be that we are not sending proper encoding headers anymore for these resources. That could explain that you have different behaviors depending on the default encoding of the browser.

**Comment by gsmet** [comment] 2022-03-01 10:47
Probably fixed by https://github.com/quarkusio/quarkus/pull/24025 .

**Closed** 2022-03-02 10:40 UTC
Labels: area/smallrye, area/kubernetes, env/windows, area/graphql
