### ISSUE TITLE
Error: Main entry point class 'io.quarkus.runner.GeneratedMain' neither found on  classpath

### ISSUE THREAD

**Issue by facundobringas** [quarkusio/quarkus#37372] opened 2023-11-29 03:05 UTC
### Describe the bug

This is happening while following getting started steps from Quarkus documentation and easily reproduced as described.

### Expected behavior

 Class _io.quarkus.runner.GeneratedMain_ should be found in classpath and build should complete without errors.

### Actual behavior

Sample output:
```
(... irrelevant build output)
[1/8] Initializing...                                                                                    (0.0s @ 0.04GB)
Error: Main entry point class 'io.quarkus.runner.GeneratedMain' neither found on 
classpath: '/project:/project/lib/io.quarkus.quarkus-resteasy-reactive-jackson-3.5.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-jackson-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-jackson-3.5.3.jar:/project/lib/com.fasterxml.jackson.core.jackson-databind-2.15.3.jar:/project/lib/com.fasterxml.jackson.core.jackson-annotations-2.15.3.jar:/project/lib/io.quarkus.quarkus-jackson-3.5.3.jar:/project/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.15.3.jar:/project/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.15.3.jar:/project/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.15.3.jar:/project/lib/io.quarkus.quarkus-arc-3.5.3.jar:/project/lib/io.quarkus.arc.arc-3.5.3.jar:/project/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-4.0.1.jar:/project/lib/jakarta.enterprise.jakarta.enterprise.lang-model-4.0.1.jar:/project/lib/jakarta.el.jakarta.el-api-5.0.1.jar:/project/lib/jakarta.interceptor.jakarta.interceptor-api-2.1.0.jar:/project/lib/jakarta.annotation.jakarta.annotation-api-2.1.1.jar:/project/lib/jakarta.transaction.jakarta.transaction-api-2.0.1.jar:/project/lib/io.smallrye.reactive.mutiny-2.5.1.jar:/project/lib/io.smallrye.common.smallrye-common-annotation-2.1.2.jar:/project/lib/org.jboss.logging.jboss-logging-3.5.3.Final.jar:/project/lib/io.quarkus.quarkus-core-3.5.3.jar:/project/lib/jakarta.inject.jakarta.inject-api-2.0.1.jar:/project/lib/io.smallrye.common.smallrye-common-os-2.1.2.jar:/project/lib/io.quarkus.quarkus-development-mode-spi-3.5.3.jar:/project/lib/io.smallrye.config.smallrye-config-3.4.4.jar:/project/lib/io.smallrye.config.smallrye-config-core-3.4.4.jar:/project/lib/org.eclipse.microprofile.config.microprofile-config-api-3.0.3.jar:/project/lib/io.smallrye.common.smallrye-common-classloader-2.1.2.jar:/project/lib/io.smallrye.config.smallrye-config-common-3.4.4.jar:/project/lib/org.jboss.logmanager.jboss-logmanager-3.0.2.Final.jar:/project/lib/io.smallrye.common.smallrye-common-constraint-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-cpu-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-expression-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-function-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-net-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-ref-2.1.2.jar:/project/lib/jakarta.json.jakarta.json-api-2.1.2.jar:/project/lib/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar:/project/lib/org.jboss.threads.jboss-threads-3.5.0.Final.jar:/project/lib/org.slf4j.slf4j-api-2.0.6.jar:/project/lib/org.jboss.slf4j.slf4j-jboss-logmanager-2.0.0.Final.jar:/project/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/project/lib/io.quarkus.quarkus-bootstrap-runner-3.5.3.jar:/project/lib/io.smallrye.common.smallrye-common-io-2.1.2.jar:/project/lib/io.quarkus.quarkus-fs-util-0.0.9.jar:/project/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-3.5.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-common-types-3.5.3.jar:/project/lib/org.reactivestreams.reactive-streams-1.0.4.jar:/project/lib/io.smallrye.reactive.mutiny-zero-flow-adapters-1.0.0.jar:/project/lib/io.quarkus.quarkus-mutiny-3.5.3.jar:/project/lib/io.quarkus.quarkus-smallrye-context-propagation-3.5.3.jar:/project/lib/modified-io.smallrye.smallrye-context-propagation-2.1.0.jar:/project/lib/io.smallrye.smallrye-context-propagation-api-2.1.0.jar:/project/lib/io.smallrye.smallrye-context-propagation-storage-2.1.0.jar:/project/lib/io.smallrye.reactive.mutiny-smallrye-context-propagation-2.5.1.jar:/project/lib/io.quarkus.quarkus-vertx-3.5.3.jar:/project/lib/io.quarkus.quarkus-netty-3.5.3.jar:/project/lib/io.netty.netty-codec-4.1.100.Final.jar:/project/lib/com.aayushatharva.brotli4j.brotli4j-1.12.0.jar:/project/lib/com.aayushatharva.brotli4j.service-1.12.0.jar:/project/lib/com.aayushatharva.brotli4j.native-osx-aarch64-1.12.0.jar:/project/lib/io.netty.netty-codec-haproxy-4.1.100.Final.jar:/project/lib/io.quarkus.quarkus-vertx-latebound-mdc-provider-3.5.3.jar:/project/lib/io.smallrye.smallrye-fault-tolerance-vertx-6.2.6.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-vertx-3.5.3.jar:/project/lib/io.vertx.vertx-web-4.4.6.jar:/project/lib/io.vertx.vertx-web-common-4.4.6.jar:/project/lib/io.vertx.vertx-auth-common-4.4.6.jar:/project/lib/io.vertx.vertx-bridge-common-4.4.6.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-core-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-3.7.2.jar:/project/lib/io.smallrye.reactive.vertx-mutiny-generator-3.7.2.jar:/project/lib/io.vertx.vertx-codegen-4.4.6.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-3.5.3.jar:/project/lib/jakarta.ws.rs.jakarta.ws.rs-api-3.1.0.jar:/project/lib/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:/project/lib/jakarta.xml.bind.jakarta.xml.bind-api-4.0.1.jar:/project/lib/jakarta.activation.jakarta.activation-api-2.1.2.jar:/project/lib/io.quarkus.quarkus-vertx-http-3.5.3.jar:/project/lib/io.quarkus.quarkus-security-runtime-spi-3.5.3.jar:/project/lib/io.quarkus.quarkus-credentials-3.5.3.jar:/project/lib/io.smallrye.common.smallrye-common-vertx-context-2.1.2.jar:/project/lib/io.quarkus.security.quarkus-security-2.0.2.Final.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-auth-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-bridge-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-uri-template-3.7.2.jar:/project/lib/io.vertx.vertx-uri-template-4.4.6.jar:/project/lib/io.github.crac.org-crac-0.1.3.jar:/project/lib/io.quarkus.quarkus-jsonp-3.5.3.jar:/project/lib/org.eclipse.parsson.parsson-1.1.5.jar:/project/lib/io.quarkus.quarkus-virtual-threads-3.5.3.jar:/project/lib/modified-io.vertx.vertx-core-4.4.6.jar:/project/lib/io.netty.netty-common-4.1.100.Final.jar:/project/lib/io.netty.netty-buffer-4.1.100.Final.jar:/project/lib/io.netty.netty-transport-4.1.100.Final.jar:/project/lib/io.netty.netty-handler-4.1.100.Final.jar:/project/lib/io.netty.netty-transport-native-unix-common-4.1.100.Final.jar:/project/lib/io.netty.netty-handler-proxy-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-socks-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-http-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-http2-4.1.100.Final.jar:/project/lib/io.netty.netty-resolver-4.1.100.Final.jar:/project/lib/io.netty.netty-resolver-dns-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-dns-4.1.100.Final.jar:/project/lib/com.fasterxml.jackson.core.jackson-core-2.15.3.jar:/project/rest-quickstart-1.0.0-SNAPSHOT-runner.jar' nor
modulepath: '/opt/mandrel/lib/svm/library-support.jar'.
com.oracle.svm.core.util.UserError$UserException: Main entry point class 'io.quarkus.runner.GeneratedMain' neither found on 
classpath: '/project:/project/lib/io.quarkus.quarkus-resteasy-reactive-jackson-3.5.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-jackson-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-jackson-3.5.3.jar:/project/lib/com.fasterxml.jackson.core.jackson-databind-2.15.3.jar:/project/lib/com.fasterxml.jackson.core.jackson-annotations-2.15.3.jar:/project/lib/io.quarkus.quarkus-jackson-3.5.3.jar:/project/lib/com.fasterxml.jackson.datatype.jackson-datatype-jsr310-2.15.3.jar:/project/lib/com.fasterxml.jackson.datatype.jackson-datatype-jdk8-2.15.3.jar:/project/lib/com.fasterxml.jackson.module.jackson-module-parameter-names-2.15.3.jar:/project/lib/io.quarkus.quarkus-arc-3.5.3.jar:/project/lib/io.quarkus.arc.arc-3.5.3.jar:/project/lib/jakarta.enterprise.jakarta.enterprise.cdi-api-4.0.1.jar:/project/lib/jakarta.enterprise.jakarta.enterprise.lang-model-4.0.1.jar:/project/lib/jakarta.el.jakarta.el-api-5.0.1.jar:/project/lib/jakarta.interceptor.jakarta.interceptor-api-2.1.0.jar:/project/lib/jakarta.annotation.jakarta.annotation-api-2.1.1.jar:/project/lib/jakarta.transaction.jakarta.transaction-api-2.0.1.jar:/project/lib/io.smallrye.reactive.mutiny-2.5.1.jar:/project/lib/io.smallrye.common.smallrye-common-annotation-2.1.2.jar:/project/lib/org.jboss.logging.jboss-logging-3.5.3.Final.jar:/project/lib/io.quarkus.quarkus-core-3.5.3.jar:/project/lib/jakarta.inject.jakarta.inject-api-2.0.1.jar:/project/lib/io.smallrye.common.smallrye-common-os-2.1.2.jar:/project/lib/io.quarkus.quarkus-development-mode-spi-3.5.3.jar:/project/lib/io.smallrye.config.smallrye-config-3.4.4.jar:/project/lib/io.smallrye.config.smallrye-config-core-3.4.4.jar:/project/lib/org.eclipse.microprofile.config.microprofile-config-api-3.0.3.jar:/project/lib/io.smallrye.common.smallrye-common-classloader-2.1.2.jar:/project/lib/io.smallrye.config.smallrye-config-common-3.4.4.jar:/project/lib/org.jboss.logmanager.jboss-logmanager-3.0.2.Final.jar:/project/lib/io.smallrye.common.smallrye-common-constraint-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-cpu-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-expression-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-function-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-net-2.1.2.jar:/project/lib/io.smallrye.common.smallrye-common-ref-2.1.2.jar:/project/lib/jakarta.json.jakarta.json-api-2.1.2.jar:/project/lib/org.jboss.logging.jboss-logging-annotations-2.2.1.Final.jar:/project/lib/org.jboss.threads.jboss-threads-3.5.0.Final.jar:/project/lib/org.slf4j.slf4j-api-2.0.6.jar:/project/lib/org.jboss.slf4j.slf4j-jboss-logmanager-2.0.0.Final.jar:/project/lib/org.wildfly.common.wildfly-common-1.5.4.Final-format-001.jar:/project/lib/io.quarkus.quarkus-bootstrap-runner-3.5.3.jar:/project/lib/io.smallrye.common.smallrye-common-io-2.1.2.jar:/project/lib/io.quarkus.quarkus-fs-util-0.0.9.jar:/project/lib/org.eclipse.microprofile.context-propagation.microprofile-context-propagation-api-1.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-3.5.3.jar:/project/lib/io.quarkus.quarkus-resteasy-reactive-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-common-3.5.3.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-common-types-3.5.3.jar:/project/lib/org.reactivestreams.reactive-streams-1.0.4.jar:/project/lib/io.smallrye.reactive.mutiny-zero-flow-adapters-1.0.0.jar:/project/lib/io.quarkus.quarkus-mutiny-3.5.3.jar:/project/lib/io.quarkus.quarkus-smallrye-context-propagation-3.5.3.jar:/project/lib/modified-io.smallrye.smallrye-context-propagation-2.1.0.jar:/project/lib/io.smallrye.smallrye-context-propagation-api-2.1.0.jar:/project/lib/io.smallrye.smallrye-context-propagation-storage-2.1.0.jar:/project/lib/io.smallrye.reactive.mutiny-smallrye-context-propagation-2.5.1.jar:/project/lib/io.quarkus.quarkus-vertx-3.5.3.jar:/project/lib/io.quarkus.quarkus-netty-3.5.3.jar:/project/lib/io.netty.netty-codec-4.1.100.Final.jar:/project/lib/com.aayushatharva.brotli4j.brotli4j-1.12.0.jar:/project/lib/com.aayushatharva.brotli4j.service-1.12.0.jar:/project/lib/com.aayushatharva.brotli4j.native-osx-aarch64-1.12.0.jar:/project/lib/io.netty.netty-codec-haproxy-4.1.100.Final.jar:/project/lib/io.quarkus.quarkus-vertx-latebound-mdc-provider-3.5.3.jar:/project/lib/io.smallrye.smallrye-fault-tolerance-vertx-6.2.6.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-vertx-3.5.3.jar:/project/lib/io.vertx.vertx-web-4.4.6.jar:/project/lib/io.vertx.vertx-web-common-4.4.6.jar:/project/lib/io.vertx.vertx-auth-common-4.4.6.jar:/project/lib/io.vertx.vertx-bridge-common-4.4.6.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-core-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-runtime-3.7.2.jar:/project/lib/io.smallrye.reactive.vertx-mutiny-generator-3.7.2.jar:/project/lib/io.vertx.vertx-codegen-4.4.6.jar:/project/lib/io.quarkus.resteasy.reactive.resteasy-reactive-3.5.3.jar:/project/lib/jakarta.ws.rs.jakarta.ws.rs-api-3.1.0.jar:/project/lib/org.jboss.logging.commons-logging-jboss-logging-1.0.0.Final.jar:/project/lib/jakarta.xml.bind.jakarta.xml.bind-api-4.0.1.jar:/project/lib/jakarta.activation.jakarta.activation-api-2.1.2.jar:/project/lib/io.quarkus.quarkus-vertx-http-3.5.3.jar:/project/lib/io.quarkus.quarkus-security-runtime-spi-3.5.3.jar:/project/lib/io.quarkus.quarkus-credentials-3.5.3.jar:/project/lib/io.smallrye.common.smallrye-common-vertx-context-2.1.2.jar:/project/lib/io.quarkus.security.quarkus-security-2.0.2.Final.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-web-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-auth-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-bridge-common-3.7.2.jar:/project/lib/io.smallrye.reactive.smallrye-mutiny-vertx-uri-template-3.7.2.jar:/project/lib/io.vertx.vertx-uri-template-4.4.6.jar:/project/lib/io.github.crac.org-crac-0.1.3.jar:/project/lib/io.quarkus.quarkus-jsonp-3.5.3.jar:/project/lib/org.eclipse.parsson.parsson-1.1.5.jar:/project/lib/io.quarkus.quarkus-virtual-threads-3.5.3.jar:/project/lib/modified-io.vertx.vertx-core-4.4.6.jar:/project/lib/io.netty.netty-common-4.1.100.Final.jar:/project/lib/io.netty.netty-buffer-4.1.100.Final.jar:/project/lib/io.netty.netty-transport-4.1.100.Final.jar:/project/lib/io.netty.netty-handler-4.1.100.Final.jar:/project/lib/io.netty.netty-transport-native-unix-common-4.1.100.Final.jar:/project/lib/io.netty.netty-handler-proxy-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-socks-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-http-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-http2-4.1.100.Final.jar:/project/lib/io.netty.netty-resolver-4.1.100.Final.jar:/project/lib/io.netty.netty-resolver-dns-4.1.100.Final.jar:/project/lib/io.netty.netty-codec-dns-4.1.100.Final.jar:/project/lib/com.fasterxml.jackson.core.jackson-core-2.15.3.jar:/project/rest-quickstart-1.0.0-SNAPSHOT-runner.jar' nor
modulepath: '/opt/mandrel/lib/svm/library-support.jar'.
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:73)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:439)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:720)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.start(NativeImageGeneratorRunner.java:142)
	at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:97)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.564 s
[INFO] Finished at: 2023-11-28T23:44:22-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.5.3:build (default) on project rest-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:474)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:264)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:840)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

This is easily reproducible running the following commands:
```
> quarkus create app org.acme:rest-quickstart --extension='resteasy-reactive-jackson'
> cd rest-quickstart  
> ./mvnw install -Dnative -DskipTests -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=podman
```

### Output of `uname -a` or `ver`

Darwin <local.hostanme> 23.1.0 Darwin Kernel Version 23.1.0: Mon Oct  9 21:28:31 PDT 2023; root:xnu-10002.41.9~6/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

Java 17.0.9

### Mandrel or GraalVM version (if different from Java)

ubi-quarkus-mandrel-builder-image:jdk-21

### Quarkus version or git rev

Quarkus 3.5.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.9.5

### Additional information

I am also using: 
 - MacBook Air M2 (Aarch64) 
 - **podman version 4.7.2** 
 
I have tried with other environment variables. It also happens using:
1. **kotlin**:
 > quarkus create app org.acme:rest-quickstart --extension='kotlin, resteasy-reactive-jackson'
 
2. **gradle**
>  quarkus create app org.acme:rest-quickstart --extension='resteasy-reactive-jackson' --gradle

3. GraalVM image 
> ./mvnw install -Dnative -Dquarkus.native.container-build=true  -Dquarkus.native.container-runtime=podman -Dquarkus.native.builder-image=graalvm

**Comment by galderz** [comment] 2023-12-04 16:11
What podman version are you running? All looks good to me on M1 with Quarkus 3.6.0 and the very latest podman install with brew, see [output](https://gist.github.com/galderz/ab45a76314208779e9128abd02122716).

After installing podman I ran:
```bash
$ podman machine init -m 8092 --cpus 4
Extracting compressed file: podman-machine-default_fedora-coreos-39.20231119.2.0-qemu.aarch64.qcow2: done
Image resized.
Machine init complete
To start your machine run:

	podman machine start

$ podman machine start
Starting machine "podman-machine-default"
Waiting for VM ...
Mounting volume... /Users:/Users
Mounting volume... /private:/private
Mounting volume... /var/folders:/var/folders

This machine is currently configured in rootless mode. If your containers
require root permissions (e.g. ports < 1024), or if you run into compatibility
issues with non-podman clients, you can switch using the following command:

        podman machine set --rootful

API forwarding listening on: /Users/galder/.local/share/containers/podman/machine/qemu/podman.sock

The system helper service is not installed; the default Docker API socket
address can't be used by podman. If you would like to install it, run the following commands:

        sudo /opt/homebrew/Cellar/podman/4.8.0/bin/podman-mac-helper install
        podman machine stop; podman machine start

                You can still connect Docker API clients by setting DOCKER_HOST using the
following command in your terminal session:

        export DOCKER_HOST='unix:///Users/galder/.local/share/containers/podman/machine/qemu/podman.sock'

Machine "podman-machine-default" started successfully
```

**Comment by facundobringas** [comment] 2023-12-04 17:30
@galderz, thanks on your input. I am using podman version 4.7.2. I also include it in the bug description.

**Comment by facundobringas** [comment] 2023-12-04 17:59
@galderz this is my podman machine info output:
```
podman machine info
Host:
  Arch: arm64
  CurrentMachine: podman-machine-default
  DefaultMachine: podman-machine-default
  EventsDir: /var/folders/wz/q9j66fx96433z_zfgdw9rftm0000gn/T/podman-run--1/podman
  MachineConfigDir: /Users/facundolarrosa/.config/containers/podman/machine/qemu
  MachineImageDir: /Users/facundolarrosa/.local/share/containers/podman/machine/qemu
  MachineState: Stopped
  NumberOfMachines: 1
  OS: darwin
  VMType: qemu
Version:
  APIVersion: 4.7.2
  Built: 1698753557
  BuiltTime: Tue Oct 31 08:59:17 2023
  GitCommit: 750b4c3a7c31f6573350f0b3f1b787f26e0fe1e3
  GoVersion: go1.21.3
  Os: darwin
  OsArch: darwin/arm64
  Version: 4.7.2

```

**Comment by galderz** [comment] 2023-12-07 09:05
I was running `4.8.0` vs your `4.7.2`. You could try updating to `4.8.0` and see if that works.

The other thing you could do is re-creating the machine instance in case something has gone wrong with it, e.g. `podman machine rm` and then create it again. Make sure the new machine has enough cpu and memory to do the native compilation.

**Comment by zakkak** [comment] 2024-08-28 10:34
@facundobringas is this still an issue? 

Please note that `resteasy-reactive-jackson` has been renamed to `quarkus-rest-jackson`.
See https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9#resteasy-reactive-extensions-renamed-to-quarkus-rest-gear-white_check_mark

I tried reproducing on a MacBook Air M3 with the following software versions:

* Quarkus 3.13.3
* Podman Desktop 1.12.0
* Podman v5.2.0

with no luck.

**Comment by facundobringas** [comment] 2024-08-29 21:56
@zakkak I updated quarkus cli and to now use `quarkus-rest-jackson`  and ran again. I did not get the same error. 
I did get the process hung while Copying Blobs  in two cases, and in a third run got the following error.  But ok, this can be the case for another thread.
```

[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.14.1:build (default) on project rest-quickstart: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code was 137 which indicates an out of memory error. The most likely cause is Docker not being given enough memory. Also consider increasing the Xmx value for native image generation by setting the "quarkus.native.native-image-xmx" property
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:464)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:262)
[ERROR] 	at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(MethodHandle.java:733)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:854)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:483)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by zakkak** [comment] 2024-08-30 08:03
These all look like `container` issues on your setup. 

The copying blobs issue could be due to unstable network or low disk space?

The other issue could be due to not giving containers enough memory to run.

My podman machine is configured to use 8 CPUs and 16GB of memory, but half of that should be fine as well. 4GB of memory though might be an issue.

Closing this, please feel free to open a new issue for the rest. Thank you.

**Closed by zakkak** 2024-08-30 08:03 UTC
Labels: kind/bug, area/native-image, triage/needs-feedback, env/podman
