### ISSUE TITLE
compact props names in yaml

### ISSUE THREAD

**Issue by jeschu** [quarkusio/quarkus#13032] opened 2020-10-30 13:36 UTC
yaml config should be possible in this 2 ways:
```
foo:
  bar:
    val: foobar
```
or
```
foo.bar:
  val: foobar
```

The second one does not work.

See: https://groups.google.com/g/quarkus-dev/c/SP8t6e7tiNQ

**Comment by radcortez** [comment] 2020-10-30 15:05
Duplicate of https://github.com/quarkusio/quarkus/issues/11744.

**Closed by radcortez** 2020-10-30 15:05 UTC
Labels: area/config, kind/bug
