### ISSUE TITLE
Exception while asking for JSON metric

### ISSUE THREAD

**Issue by nuhlngda** [quarkusio/quarkus#33082] opened 2023-05-03 07:59 UTC
### Describe the bug

Hi!
When I try to get the metrics from a web service (Quarkus project) in JSON format, I get always a HTTP 500 with such content:

`{
    "details": "Error id 4b11145a-d4a5-4f31-a834-1680c536f063-8",
    "stack": ""
}`

**With errors:**
.../metrics
.../metrics/application

**No errors:**
.../metrics/base
.../metrics/vendor

The calling metrics in **normal text format is ok** and delivers the correct content.

### Expected behavior

Expected is an **application** entry like this...

**...
 "application": {
        "com.xxxx.yyyy.main.controller.AController.CountGetHighProducts": 0,      
        "com.xxxx.yyyy.main.controller.AController.CountGetProdData": 0,        
        "com.xxxx.yyyy.main.controller.ADController.MeteredGetRProducts": {        
            "fiveMinRate": 0.0,            
            "fifteenMinRate": 0.0,            
            "meanRate": 0.0,            
            "count": 0,            
            "oneMinRate": 0.0            
        },        
        "com.xxxx.yyyy.main.controller.AController.TimeGetProdData": {        
            "p99": 0.0,            
            "min": 0.0,            
            "max": 0.0,            
            "mean": 0.0,            
            "p50": 0.0,            
            "p999": 0.0,            
            "stddev": 0.0,            
...**

... within the JSON output.

### Actual behavior

**But instead of this, I get the 500 error with this message:**

{"timestamp":"2023-05-02T14:12:59.977Z","sequence":1045,"loggerClassName":"org.jboss.logging.Logger","loggerName":"io.quarkus.vertx.http.runtime.QuarkusErrorHandler","level":"**ERROR**","message":"HTTP Request to **.../metrics/application failed**, error id: 4b11145a-d4a5-4f31-a834-1680c536f063-8","threadName":"vert.x-eventloop-thread-3","threadId":12,"mdc":{},"ndc":"","hostName":"xxxxxxx","processName":"NativeImageGeneratorRunner$JDK9Plus","processId":26,"exception":{"refId":1,"exceptionType":"**java.lang.NumberFormatException**","message":"**Character N is neither a decimal digit number, decimal point, nor \"e\" notation exponential mark.**","frames":[{"class":"java.math.BigDecimal","method":"<init>","line":518},{"class":"java.math.BigDecimal","method":"<init>","line":401},{"class":"java.math.BigDecimal","method":"<init>","line":834},{"class":"java.math.BigDecimal","method":"valueOf","line":1304},{"class":"org.glassfish.json.JsonNumberImpl","method":"getJsonNumber","line":46},{"class":"org.glassfish.json.JsonProviderImpl","method":"createValue","line":244},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"snapshotValues","line":317},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"exportTimer","line":276},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"lambda$exportMetricsByName$5","line":176},{"class":"java.util.HashMap","method":"forEach","line":1337},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"exportMetricsByName","line":174},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"lambda$exportMetricsForMap$9","line":215},{"class":"java.util.stream.ReferencePipeline$3$1","method":"accept","line":195},{"class":"java.util.HashMap$EntrySpliterator","method":"forEachRemaining","line":1764},{"class":"java.util.stream.AbstractPipeline","method":"copyInto","line":484},{"class":"java.util.stream.AbstractPipeline","method":"wrapAndCopyInto","line":474},{"class":"java.util.stream.ForEachOps$ForEachOp","method":"evaluateSequential","line":150},{"class":"java.util.stream.ForEachOps$ForEachOp$OfRef","method":"evaluateSequential","line":173},{"class":"java.util.stream.AbstractPipeline","method":"evaluate","line":234},{"class":"java.util.stream.ReferencePipeline","method":"forEach","line":497},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"exportMetricsForMap","line":216},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"exportOneRegistry","line":200},{"class":"io.smallrye.metrics.exporters.JsonExporter","method":"exportOneScope","line":72},{"class":"io.smallrye.metrics.MetricsRequestHandler","method":"handleRequest","line":160},{"class":"io.smallrye.metrics.MetricsRequestHandler_ClientProxy","method":"handleRequest"},{"class":"io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler","method":"handle","line":38},{"class":"io.quarkus.smallrye.metrics.runtime.SmallRyeMetricsHandler","method":"handle","line":18},{"class":"io.vertx.ext.web.impl.BlockingHandlerDecorator","method":"lambda$handle$0","line":48},{"class":"io.vertx.core.impl.ContextImpl","method":"lambda$null$0","line":159},{"class":"io.vertx.core.impl.AbstractContext","method":"dispatch","line":100},{"class":"io.vertx.core.impl.ContextImpl","method":"lambda$executeBlocking$1","line":157},{"class":"io.quarkus.vertx.core.runtime.VertxCoreRecorder$14","method":"runWith","line":550},{"class":"org.jboss.threads.EnhancedQueueExecutor$Task","method":"run","line":2449},{"class":"org.jboss.threads.EnhancedQueueExecutor$ThreadBody","method":"run","line":1478},{"class":"org.jboss.threads.DelegatingRunnable","method":"run","line":29},{"class":"org.jboss.threads.ThreadLocalResettingRunnable","method":"run","line":29},{"class":"io.netty.util.concurrent.FastThreadLocalRunnable","method":"run","line":30},{"class":"java.lang.Thread","method":"run","line":829},{"class":"com.oracle.svm.core.thread.JavaThreads","method":"threadStartRoutine","line":597},{"class":"com.oracle.svm.core.posix.thread.PosixJavaThreads","method":"pthreadStartRoutine","line":194}]}}

:-(

### Additional information

**What to do now?**

Thanks in advance for any help.

Regards

**Comment by nuhlngda** [comment] 2023-05-03 08:45
Hi @gsmet :-)

No, unfortunately I dont have any chance to reproduce this error with a small application because this error happens only in a native image.

On my local development PC while running my app in JVM mode, no error occurs. Only in the native image mode. But I dont have access to build a native example image in order to deploy this on the servers. I see only the error entries in the log file while calling the application metrics.

Best regards

**Comment by nuhlngda** [comment] 2023-05-03 09:29
When I call the metrics in order to see it with normal text output (not JSON), I can found entries (text rows) like these:

**# TYPE application_com_xxxx_yyyy_main_controller_AController_TimeGetHighProducts_mean_seconds gauge
application_com_xxxx_yyyy_main_controller_AController_TimeGetHighProducts_mean_seconds NaN**

As you can see above in the description, there is a problem with character 'N' while trying to format the number.

Perhaps this "N" (from 'NaN') causes the error?!

Regards

**Comment by gsmet** [comment] 2023-05-03 09:32
Yes, that's what I suspected.
@jmartisk does it ring a bell? Apparently, it only fails in native.

**Comment by jmartisk** [comment] 2023-05-03 11:20
No idea why the mean would become `NaN` in native mode, and I don't know how to reproduce it (it works for me). 
But I assume we could add a guard that maps `NaN` to 0 in case that a `NaN` appears for whatever reason?!

**Comment by jmartisk** [comment] 2023-05-04 09:35
@nuhlngda I've submitted https://github.com/smallrye/smallrye-metrics/pull/628 but I'm not completely sure it will fix it, because I can't reproduce it. Any chance you could test it yourself? You'd have to build a custom snapshot of smallrye-metrics, and a build of Quarkus where you set the dependency on your smallrye-metrics snapshot

**Comment by miladjafary** [comment] 2023-05-10 12:42
I have the same issue on JVM mode. In local and also in the k8s pod when you request on http://0.0.0.0:9000/metrics it gives the `HTTP Request to /metrics failed, error id: a6a17324-debf-46b6-be32-214513c85113-118` error. 
FYI: I've set the root path to `/`

**Comment by gsmet** [comment] 2024-08-24 12:44
I'm closing the issue here. If there is interest in continuing the discussion, please do it in the tentative PR upstream: https://github.com/smallrye/smallrye-metrics/pull/628 .

**Closed by gsmet** 2024-08-24 12:44 UTC
Labels: kind/bug, area/metrics
