### ISSUE TITLE
Hibernate-orm not batch inserting entities

### ISSUE THREAD

**Issue by danielreis3195** [quarkusio/quarkus#30305] opened 2023-01-11 12:02 UTC
### Description
When trying to insert several entities in the Database using hibernate-orm, I can't make the insertion to be in batch.

From the documentation [Using Hibernate ORM and JPA](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.jdbc.statement-batch-size) I see the option for batch insert is available at runtime (**quarkus.hibernate-orm.jdbc.statement-batch-size**). 

However, I don't see it working (or at least how I think it should work).

Below, you can see the code and properties I used as well as the database logs

### Dependencies
- implementation("io.quarkus:quarkus-hibernate-orm-panache:2.15.2.Final")
- implementation("io.quarkus:quarkus-jdbc-postgresql:2.15.2.Final")

### Entity
```
package database.entities;


import javax.persistence.*;
import java.util.List;
import java.util.UUID;

@Entity
public class School {

    @Id
    private UUID id = UUID.randomUUID();

    private String name;

    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```
### Repository

```
package database.repositories;

import database.entities.School;
import io.quarkus.hibernate.orm.panache.PanacheRepository;

import javax.enterprise.context.ApplicationScoped;


@ApplicationScoped
public class SchoolRepository implements PanacheRepository<School> {}
```

### Test

```
package com.database;

import database.entities.School;
import database.repositories.SchoolRepository;
import io.quarkus.test.junit.QuarkusTest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import javax.inject.Inject;
import javax.transaction.*;

import java.util.ArrayList;
import java.util.List;

import static helper.TestObjectHelper.createSchool;


@QuarkusTest
public class Tests {

    @Inject
    SchoolRepository schoolRepository;

    @Transactional
    @Test
    public void whenNotConfigured_ThenSendsInsertsSeparately() {
        List<School> schools = new ArrayList<>();
        for (int i = 0; i < 50; i++) {
            schools.add(createSchool(i));
        }
        schoolRepository.persist(schools);
        schoolRepository.flush();
    }

}
```

### application.properties
```


# Configuring datasource
quarkus.datasource.db-kind = postgresql
quarkus.datasource.username = core-db
quarkus.datasource.password = masterpassword
quarkus.datasource.jdbc.url = jdbc:postgresql://localhost:5432/core-db
quarkus.datasource.jdbc.max-size=15


# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation = drop-and-create

quarkus.hibernate-orm.jdbc.statement-batch-size=5

quarkus.hibernate-orm.log.jdbc-warnings=true
# quarkus.hibernate-orm.log.sql=true
#quarkus.hibernate-orm.log.bind-parameters=false
```

### Expected behavior

As in the properties above I put "batch-size=5", I expected there to be multiple inserts with multiple values:

```
"batch":true, "querySize":1, "batchSize":5, "query":["insert into school (name, id) values (?, ?)"], 
  "params":[["School1","1"],["School2","2"],["School3","3"],["School4","4"],["School5","5"]]
"batch":true, "querySize":1, "batchSize":5, "query":["insert into school (name, id) values (?, ?)"], 
  "params":[["School6","6"],["School7","7"],["School8","8"],["School9","9"],["School10","10"]]
```

### Actual Behavior

From the logs below, the insert is being done on a single transaction with **multiple individual inserts**.

### Logs

```
2023-01-11 11:23:38.120 UTC [149] DETAIL:  parameters: $1 = '"$user", public'
2023-01-11 11:23:38.121 UTC [149] LOG:  execute S_1: COMMIT
2023-01-11 11:23:38.259 UTC [149] LOG:  execute S_3: BEGIN
2023-01-11 11:23:38.266 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.266 UTC [149] DETAIL:  parameters: $1 = 'School1', $2 = '65baf811-7366-4267-b866-66375d467479'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School2', $2 = '20fb8361-f219-4f0a-a0ba-4b5d093396db'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School3', $2 = 'bcb63bbb-fc42-4772-9cef-36f0f0e35c79'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School4', $2 = '2466d7be-11ee-4ea7-9702-945db301c89c'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School5', $2 = 'ca9b7732-ac26-4477-a081-5d310e10b5cd'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School6', $2 = '6b420d1f-3b32-44bc-84f8-5fe6fca9a3de'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School7', $2 = '4c47427f-024c-4803-8dfc-8f52993d6df6'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School8', $2 = '7ce3dddb-f344-43a7-b76e-31a47d0adb44'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School9', $2 = '70645a87-c7d5-49ec-9391-528e206d6661'
2023-01-11 11:23:38.283 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.283 UTC [149] DETAIL:  parameters: $1 = 'School10', $2 = 'c512506e-c86d-4845-be95-517e0b0be5f6'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School11', $2 = 'dba4cf15-8167-40a0-be45-b3ecf971a766'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School12', $2 = '351a4f05-512c-4434-b7df-c352f91cbe27'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School13', $2 = '1be8db42-0c48-4711-961d-c55d01a1ee1f'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School14', $2 = 'b49b778d-c4cc-4af3-bfd8-ca3c1e899ab9'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School15', $2 = '01d1002c-fda8-40f8-afaa-bfdcb3a8b5d4'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School16', $2 = '239782f9-de83-4cab-b5fe-19042449c1c6'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School17', $2 = 'aa2e0509-7030-473f-ae69-be952b589b66'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School18', $2 = '41b5f5c6-d6af-41bf-bd35-d2861c186b11'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School19', $2 = '2f0f8ef6-a9ba-4433-8eee-c19320547fb4'
2023-01-11 11:23:38.287 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.287 UTC [149] DETAIL:  parameters: $1 = 'School20', $2 = 'f2da3d63-4bed-4316-8ab9-21eb3e82cb01'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School21', $2 = '77d8c544-d53c-46ed-b286-595ad7768f82'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School22', $2 = 'fb6bf550-3674-4785-a814-9092a9e77cbb'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School23', $2 = '14535602-4046-4e23-926a-223376295542'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School24', $2 = '93dc6692-4688-4061-8343-dbb4efdba8cb'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School25', $2 = 'c493b329-9811-40a7-93e0-87d17ae98223'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School26', $2 = '52b14795-b1ea-43e1-b15e-39f94aa01887'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School27', $2 = 'b8ed7cce-8093-4125-8da7-5f34521d3750'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School28', $2 = '16c154c4-3422-49c6-bbc0-3f56c62dcdf1'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School29', $2 = '04b79c54-c8ec-4c3a-aeda-49907db22297'
2023-01-11 11:23:38.290 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.290 UTC [149] DETAIL:  parameters: $1 = 'School30', $2 = 'd0e4b2e5-c80a-4502-b582-e12dfa8e2486'
2023-01-11 11:23:38.295 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.295 UTC [149] DETAIL:  parameters: $1 = 'School31', $2 = 'ec782062-4d07-485d-9bc7-f920b7958de1'
2023-01-11 11:23:38.295 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.295 UTC [149] DETAIL:  parameters: $1 = 'School32', $2 = '46eb0b30-ac20-4e08-a2d9-bcd5d47f44d3'
2023-01-11 11:23:38.295 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.295 UTC [149] DETAIL:  parameters: $1 = 'School33', $2 = '88d9176c-07f9-4a2e-b1d4-f7e890dd4166'
2023-01-11 11:23:38.295 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.295 UTC [149] DETAIL:  parameters: $1 = 'School34', $2 = '9c566e70-c242-4da9-ab0e-4bad9191bace'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School35', $2 = 'b9ef5cc3-16ec-4dcd-8acc-5a183a6478b8'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School36', $2 = 'ce38f893-ddf4-478e-b272-949dcfd2d45e'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School37', $2 = '22134a01-109f-457c-8c0f-f12fcb5ce06e'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School38', $2 = 'e066b430-5c6d-4ba4-8d3a-405d783bdbcf'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School39', $2 = '9398ced2-97b7-4fa7-802e-1e3094544c65'
2023-01-11 11:23:38.296 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.296 UTC [149] DETAIL:  parameters: $1 = 'School40', $2 = 'ef152096-d533-45ed-817e-1aadbac63302'
2023-01-11 11:23:38.297 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.297 UTC [149] DETAIL:  parameters: $1 = 'School41', $2 = '09b547fb-faf2-47bc-b4c6-e3f05bea59dc'
2023-01-11 11:23:38.297 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.297 UTC [149] DETAIL:  parameters: $1 = 'School42', $2 = '101fd478-40bb-46a0-85d7-8daeac131a91'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School43', $2 = 'd6bc82c7-f20f-4364-82ca-f73992dcb759'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School44', $2 = '9187a86e-e9fc-48f4-b4fa-1a48f5e9d222'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School45', $2 = '70a721f4-edee-4ddf-8e4b-539493ece7b0'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School46', $2 = '44e28ffd-32c0-47a3-b408-bf27f52228cf'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School47', $2 = 'f0b36ace-4274-4200-bd0c-a772631fb5d5'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School48', $2 = '4ff6b91b-a224-4228-b046-f91941555c04'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School49', $2 = 'dce2b886-818f-4e45-a1a1-1eda09756833'
2023-01-11 11:23:38.298 UTC [149] LOG:  execute S_4: insert into school (name, id) values ($1, $2)
2023-01-11 11:23:38.298 UTC [149] DETAIL:  parameters: $1 = 'School50', $2 = '3f21ab8a-23dc-433a-838d-c2f8889ae1b1'
2023-01-11 11:23:38.313 UTC [149] LOG:  execute S_1: COMMIT

```

### Output of `uname -a` or `ver`

Darwin MBP.Home 21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk-17 (17.0.1)

### Quarkus version or git rev

2.15.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by yrodiere** [comment] 2023-01-11 12:24
Hello,

Here is the documentation of `quarkus.hibernate-orm.jdbc.statement-batch-size`:

> The number of updates (inserts, updates and deletes) that are sent by the JDBC driver at one time for execution.

So this is strictly about JDBC, not about SQL. This is about sending multiple `INSERT` statements to the JDBC driver in one batch, i.e. sending multiple statements in one batch over the network. This is **not** about merging multiple `INSERT` statements into one.

See also `java.sql.PreparedStatement#executeBatch()`.

I am not aware of any way of telling Hibernate ORM to merge multiple `INSERT` statements into one.

I'll close this issue since things work as expected, but feel free to create a feature request if you find a way of telling Hibernate ORM to merge multiple `INSERT` statements into one.

If you want that feature to be added to Hibernate ORM itself, the right place to ask for that would be the [Hibernate ORM JIRA instance](https://hibernate.atlassian.net/browse/HHH). I'm not sure whether this would bring anything, though. @beikov might have an opinion on that.

**Closed by yrodiere** 2023-01-11 12:24 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm

**Comment by danielreis3195** [comment] 2023-01-11 13:07
Thank you for the reply @yrodiere ! Will give it a look

**Comment by beikov** [comment] 2023-01-11 13:09
Are you sure that the logs aren't just trying to show you in a consistent way what is happening logically? Also, what logs are you showing there?
Hibernate will use the JDBC Batch API and then it's up to the driver to decide how to send that to the DB. Usually, the result is as efficient or most of the time even better than using a single insert statement with multiple tuples in the values clause, but the implementation is the responsibility of the driver. Maybe you have to configure something special through JDBC for your driver?

**Comment by Sanne** [comment] 2023-01-11 13:14
N.B. when Hibernate uses the batch capabilities, the logged statements still "look like" individual insert statements.

**Comment by danielreis3195** [comment] 2023-01-11 16:33
@Sanne

I was expecting the inserts to be faster.. the only evidence I got was through the debugger where if **quarkus.hibernate-orm.jdbc.statement-batch-size** is set, org.hibernate.engine.jdbc.batch.interna. BatchingBatch#performExecution() is invoked (if not set, it doesn't go through here).

> Batching is enabled by default: I'd guess that's why it doesn't make any difference?

Can you confirm me this one? Was looking though the documentation, but couldn't find anything

**Comment by Sanne** [comment] 2023-01-11 16:52
> Can you confirm me this one? Was looking though the documentation, but couldn't find anything

Well I know that the code is intended to enabled this by default, I wouldn't have told you otherwise.
But you are claiming that it's not working... bugs happen occasionally so it's possible that you're correct, but it's up to you to provide some more details or a reproducer: last time I tested this, this was working fine.

**Comment by danielreis3195** [comment] 2023-01-11 17:05
@Sanne 
I've been doing isolated tests now (empty project and reduced dependencies) and everything seems to be working as it should. It looks like a problem from my project

Thanks for the answers and attention! Sorry for wasting your time

**Comment by Sanne** [comment] 2023-01-11 17:32
no problem! hope you sort it, and feel free to comment again if you make any progress.

**Comment by beikov** [comment] 2023-01-11 17:58
>My expectation with the use of the flag quarkus.hibernate-orm.jdbc.statement-batch-size, would be multiple inserts with several values in order to improve insertion capability. However, with or without it, the insert time is the same.

Usually, batching will only improve things if you have a somewhat high network latency to the database. Without batching, the app does the following logical network/protocol requests:

```
exec query=123,values=[1,abc]
exec query=123,values=[2,def]
exec query=123,values=[3,ghi]
```

and with batching it does

```
exec query=123,values=[1,abc],[2,def],[3,ghi]
```

but the database still writes all the values to the WAL at transaction commit time, so the batching doesn't help with reducing the overall work, it just avoids some network ping-pongs.

**Comment by gabrielburceanu** [comment] 2024-08-03 17:56
I know it's an old thread, but I ended up here looking for the same thing and I later found out it was a PostgreSQL-specific feature called **reWriteBatchedInserts** that did that, not related to Hibernate. 

All you need to do to enable it is to change the jdbc url: jdbc:postgresql://localhost:5432/core-db?reWriteBatchedInserts=true

You can learn more here: https://jdbc.postgresql.org/documentation/use/
> **reWriteBatchedInserts** (boolean) Default false
> This will change batch inserts from insert into foo (col1, col2, col3) values (1, 2, 3) into insert into foo (col1, col2, col3) values (1, 2, 3), (4, 5, 6) this provides 2-3x performance improvement

**Comment by Sanne** [comment] 2024-08-03 19:21
@gabrielburceanu I know that feature, and I wouldn't recommend it when there are alternatives.

There are two problems with it:

1.  JDBC driver needs to do quite some work on the client side to rewrite the SQL statements.
2. The SQL statements are going to be different, negating query parsing cache and statement reuse opportunities.

It's of course going to be more efficient when you have no better choice, but since Hibernate ORM supports native batching, that's a better choice as you would get the same effect of reducing the network roundtrips but w/o the above mentioned drawbacks.

**Comment by gabrielburceanu** [comment] 2024-08-03 19:51
Makes sense. Using the reWriteBatchedInserts flag together with Hibernate batching actually seemed to be 10-15% faster than using Hibernate batching alone for my use case. 

Probably not worth the trouble, I only got to this Postgres flag because it wasn't clear to me at that time that Hibernate was actually batching inserts since they were not in a single insert query. 

Thank you!

**Comment by Sanne** [comment] 2024-08-03 19:56
> it wasn't clear to me at that time that Hibernate was actually batching inserts since they were not in a single insert query.

Right, that has confused myself as well in the past. I have it on our wishlist to figure out how to make this clearer.

**Comment by The-Funk** [comment] 2024-08-21 23:30
@Sanne Sorry to once again bring this old thread back from the grave but are there any docs around JDBC batching? I wound up here because I can't tell if batching is working or not on my system, so I feel like I'm in the same boat as the original poster. I need to find a way to profile and determine if the batching is working or not.

I'm running into deadlock issues with my Azure SQL instance and so my thought is to reduce as much work for the instance as possible. One way I intend to reduce work is by enabling batch inserts/updates if they're not already enabled by default. I understand that this could offer some significant performance improvement due to fewer network roundtrips and fewer transaction commits.

For whatever reason when I put ` quarkus.hibernate-orm.jdbc.statement-batch-size=20` in the application.properties file my IDE says it is not a recognized config property. I checked the code here in the 3.8 branch (I'm on the LTS) and the default persistence unit in the config should have a jdbc field that has this property, so I'm not sure why it's not being recognized by my IDE when all the other hibernate-orm properties are being recognized. I'm using Hibernate ORM w/ Panache.
