### ISSUE TITLE
quarkus:dev not working well for kotlin projects

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#4414] opened 2019-10-07 13:43 UTC
Anytime I change project, I need to restart my `./mvnw clean compile quarkus:dev` command. 

Otherwise, I get errors such as: 

```
Error restarting Quarkus
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:841)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:114)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:780)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:345)
	at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:893)
	at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:294)
	at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:110)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:250)
	... 12 more

	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:149)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:195)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:116)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:52)
	at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$1.handle(VertxHotReplacementSetup.java:44)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#generateResources threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:841)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:114)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:780)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:345)
	at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:893)
	at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:294)
	at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:110)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:250)
	... 12 more

	at io.quarkus.builder.Execution.run(Execution.java:108)
	at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
	at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:115)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:110)
	... 10 more
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:841)
	at io.quarkus.arc.processor.BeanProcessor.processValidationErrors(BeanProcessor.java:114)
	at io.quarkus.arc.deployment.ArcProcessor.generateResources(ArcProcessor.java:275)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:780)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.spi.DefinitionException: Normal scoped bean must not be final: CLASS bean [types=[java.lang.Object, rs.dodalovic.ordinacija.patients.PatientsService], qualifiers=[@Default, @Any], target=rs.dodalovic.ordinacija.patients.PatientsService]
	at io.quarkus.arc.processor.BeanInfo.validate(BeanInfo.java:345)
	at io.quarkus.arc.processor.BeanDeployment.validateBeans(BeanDeployment.java:893)
	at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:294)
	at io.quarkus.arc.processor.BeanProcessor.validate(BeanProcessor.java:110)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:250)
	... 12 more
```

By just restarting the runner, the things work well again.

**Comment by geoand** [comment] 2019-10-07 13:47
Most likely related to: https://github.com/quarkusio/quarkus/pull/4397#issuecomment-538770929

**Comment by Arcnor** [comment] 2019-11-13 12:04
I don't think this issue should be closed, as it's still affecting users (like me).

I'm also having other situations where the compiler seems to do strange things when using Kotlin in dev mode (like `Compilation failed Tuple.newInstance(io.vertx.sqlclient.Tuple.of(myVar1, *myOtherTuple.toTypedArray()))`) but I'm not sure if it's still related to #4397 like @geoand mentioned.

**Comment by jaikiran** [comment] 2019-11-20 06:51
Hello @Arcnor, can you share an application and steps which reproduces this? Perhaps as a github repository?

**Comment by stuartwdouglas** [comment] 2020-03-12 05:37
@mkouba is there any reason we can't just remove the final flag automatically with a bytecode transformer? It would likely make life a lot easier for kotlin developers.

**Comment by mkouba** [comment] 2020-03-12 10:07
I don't remember any specific reason. Myabe we just wanted to avoid too many transformations because in kotlin classes are final by default? I wonder if we could break anything when removing the final flag automatically for any bean class... probably not?

**Comment by stuartwdouglas** [comment] 2020-03-12 10:09
Nope, because we are doing a closed world assumption we know that this is safe, nothing can accidentally extend it later except our code.

**Comment by mkouba** [comment] 2020-03-12 10:12
I was thinking about some runtime checks/expectations...

**Comment by mkouba** [comment] 2020-03-12 10:14
I can try to prepare a pull later today.

**Comment by mkouba** [comment] 2020-03-12 13:29
@stuartwdouglas the only problem is that every framework might need to skip the validation for such transformed classes because we usually validate the info from jandex. For now I'll send a PR for ArC.

**Comment by stuartwdouglas** [comment] 2020-03-12 21:09
I think we should just remove that validation as well, as we don't really need it if we always transform.

**Comment by mkouba** [comment] 2020-03-13 08:37
> I think we should just remove that validation as well, as we don't really need it if we always transform.

I don't think we should remove the validation completely, at least in ArC, because of spec compatibility. So I'm going to send a PR where we make the transformation configurable, i.e.  deprecate existing `quarkus.arc.remove-final-for-proxyable-methods` and introduce new unifying `quarkus.arc.transfrorm-unproxyable-classes`. @stuartwdouglas I'll add you for review.

**Comment by mkouba** [comment] 2020-03-13 10:13
FYI https://github.com/quarkusio/quarkus/pull/7837

**Comment by stuartwdouglas** [comment] 2020-03-19 02:05
I think we can call this one fixed now.

**Closed by stuartwdouglas** 2020-03-19 02:05 UTC
Labels: kind/bug, pinned
