### ISSUE TITLE
Upgrade from 3.0.4 to 3.1.0 throws build exception Injected @Intercepted Bean<?> has to use unbound wildcard as its type parameter

### ISSUE THREAD

**Issue by itatdcer** [quarkusio/quarkus#33765] opened 2023-06-01 09:36 UTC
### Describe the bug

I have a multi module maven project that is working with quarkus 3.0.4.Final. It has been started with 2.x and upgraded through every 3.0.x versions.

Trying to upgrade to 3.1.0.Final, the project does not compile anymore and throws the error:
```posh
Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.1.0.Final:build (default) on project my-project: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#registerBeans threw an exception: jakarta.enterprise.inject.spi.DefinitionException: Injected @Intercepted Bean<?> has to use unbound wildcard as its type parameter. Problematic injection point: xxx.yyy.MyInterceptor#bean
	at io.quarkus.arc.processor.Injection.validateInjections(Injection.java:120)
	at io.quarkus.arc.processor.Injection.validateInjections(Injection.java:151)
	at io.quarkus.arc.processor.Injection.forBean(Injection.java:215)
	at io.quarkus.arc.processor.Interceptors.createInterceptor(Interceptors.java:79)
	at io.quarkus.arc.processor.BeanDeployment.findInterceptors(BeanDeployment.java:1425)
	at io.quarkus.arc.processor.BeanDeployment.registerBeans(BeanDeployment.java:272)
	at io.quarkus.arc.processor.BeanProcessor.registerBeans(BeanProcessor.java:142)
	at io.quarkus.arc.deployment.ArcProcessor.registerBeans(ArcProcessor.java:443)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

There should be no error compiling the same project after upgraded from 3.0.4 to 3.1.0.

### How to Reproduce?

I don't have a reproducer since I can't quite understand the cause of this error.

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.4 Java 17.0.7

**Comment by itatdcer** [comment] 2023-06-01 09:45
If I change the intercepted bean injection from:
```
@Inject
@Intercepted
protected Bean<MyInterceptedClass> bean;
```
to
```
@Inject
@Intercepted
protected Bean<?> bean;
```

It compiles the project.

Is there any reason why I can't restrict the type as before?

**Comment by manovotn** [comment] 2023-06-01 10:26
This is per CDI specification, we just didn't have proper validation implemented in previous versions 

See https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_metadata

> If the injection point is a field, an initializer method parameter or a bean constructor of an interceptor, with qualifier @Intercepted, then the type parameter of the injected Bean must be an unbounded wildcard

**Comment by manovotn** [comment] 2023-06-01 11:33
I am going to close this issue as it is not a bug - you should be able to safely switch the type in your injection point to what you said above:

```
@Inject
@Intercepted
protected Bean<?> bean;
```
If it's not the case, feel free to reopen/keep the discussion going.

FTR, the reason for this validation is that the interceptor has no knowledge of the bean type is it being applied to and therefore, for the sake of type safety, you cannot/should not rely on `Bean<MyInterceptedClass>` and instead go with the wildcard. You can always query the `Bean` metadata for the bean class and go from there.

**Closed by manovotn** 2023-06-01 11:33 UTC
Labels: kind/bug, area/arc
