### ISSUE TITLE
Rest client reactive class not found

### ISSUE THREAD

**Issue by fabry00** [quarkusio/quarkus#17611] opened 2021-06-01 17:17 UTC
## Describe the bug
The native application throws some WARNS messages at runtime using the combination of quarkus-resteasy-reactive and quarkus-rest-client  

### Expected behavior
Not warn messages should be thrown

### Actual behavior
As soon as I perform a rest request the native application deployed in a docker container throws the following warnings:

2021-06-01 17:07:10,176 WARN  [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.IIOImageProvider from resource:META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.IIOImageProvider`

2021-06-01 17:07:10,177 WARN  [org.jbo.res.res.i18n] (executor-thread-1) RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.sse.SseEventProvider from resource:META-INF/services/javax.ws.rs.ext.Providers: java.lang.ClassNotFoundException: org.jboss.resteasy.plugins.providers.sse.SseEventProvider

.....
....

## To Reproduce

https://github.com/fabry00/quarkus-rest-client-warn

## Edit

I've added the logs for each script:

- buildDocker.sh: https://github.com/fabry00/quarkus-rest-client-warn/blob/master/buildDocker.log
- runDocker.sh: https://github.com/fabry00/quarkus-rest-client-warn/blob/master/runDocker.log
- test.sh: https://github.com/fabry00/quarkus-rest-client-warn/blob/master/test.log

**Comment by derkoe** [comment] 2021-06-08 06:47
This seems to be the same as #15665

**Comment by fabry00** [comment] 2021-06-08 16:15
> I did not see this WARNING when running:
> 
> ```
> mvn clean package -DskipTests -Dnative -Dquarkus.native.container-build=true
> ```
> 
> on the supplied reproducer

You'll  see the WARNS after running the container with ./runDocker.sh and performing a rest call: ./test.sh

**Comment by geoand** [comment] 2021-06-11 07:53
I could not reproduce the problem with the provided scripts either

**Comment by fabry00** [comment] 2021-06-15 06:40
> I could not reproduce the problem with the provided scripts either

I've added the logs of the scripts in the issue description.

**Comment by geoand** [comment] 2021-06-15 06:54
@zakkak perhaps you can reproduce it?

**Comment by zakkak** [comment] 2021-06-15 09:16
> @zakkak perhaps you can reproduce it?

@geoand I was able to reproduce it with:
```
git clone https://github.com/fabry00/quarkus-rest-client-warn.git
./target/rest-client-quickstart-1.0.0-SNAPSHOT-runner
```
and in a different terminal
```
curl http://0.0.0.0:8080/country/name/italy
```

It's reproducible on 1.13.7.Final as well.

**Comment by geoand** [comment] 2021-06-15 09:49
OK, I was able to reproduce this.

@michalszynkiewicz want to take a look?

**Comment by michalszynkiewicz** [comment] 2021-06-16 16:27
@geoand did you use the code from https://github.com/fabry00/quarkus-rest-client-warn/blob/master/pom.xml ?
Contrary to the title of this issue, it uses the good old `quarkus-rest-client`, and not `quarkus-rest-client-reactive`, and mixes it with `quarkus-resteasy-reactive`

**Comment by geoand** [comment] 2021-06-16 16:28
I just did what @zakkak mentioned above.

If things are being mixed, is the issue invalid then?

**Comment by michalszynkiewicz** [comment] 2021-06-17 05:25
TBH, I'm not sure. It's still weird that RestEasy Rest Client would try to load classes that are not available with this combination...

**Comment by michalszynkiewicz** [comment] 2021-06-17 05:27
Anyway @fabry00 can you try one of:

- switch the server implementation to `quarkus-resteasy`
- change the client you are using to `quarkus-rest-client-reactive-jackson` - you should remove `quarkus-rest-client-mutiny`, `quarkus-rest-client-jackson` and `quarkus-rest-client` then

**Comment by fabry00** [comment] 2021-06-17 09:22
@michalszynkiewicz 

**POINT 1**

I switched the dependencies `quarkus-resteasy-reactive` and `quarkus-resteasy-jackson` with `quarkus-resteasy` and `quarkus-resteasy-jackson` and now I do not see any WARNs. You can check the modifications in this branch: https://github.com/fabry00/quarkus-rest-client-warn/tree/try1

However I have a question, Is my API still reactive even if I removed the *reactive dependencies? if yes can you provide an expansive explanation?

**POINT 2**

I tried to remove `quarkus-rest-client-mutiny, quarkus-rest-client-jackson` and `quarkus-rest-client`  and add `quarkus-rest-client-reactive-jackson` but there were some compilation errors: 

```
#13 8.489 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project rest-client-quickstart: Compilation failure: Compilation failure:
#13 8.494 [ERROR] /usr/src/app/src/main/java/org/acme/rest/client/CountriesResource.java:[13,44] package org.jboss.resteasy.annotations.jaxrs does not exist
#13 8.494 [ERROR] /usr/src/app/src/main/java/org/acme/rest/client/CountriesService.java:[11,44] package org.jboss.resteasy.annotations.jaxrs does not exist
```

Just adding back  `quarkus-rest-client`  the build succeeded but then I had other type of runtime errors while hitting the API
More info here: https://github.com/fabry00/quarkus-rest-client-warn/tree/try2

Thanks

**Comment by michalszynkiewicz** [comment] 2021-06-17 10:56
> @michalszynkiewicz
> 
> > Anyway @fabry00 can you try one of:
> > 
> > * switch the server implementation to `quarkus-resteasy`
> > * change the client you are using to `quarkus-rest-client-reactive-jackson` - you should remove `quarkus-rest-client-mutiny`, `quarkus-rest-client-jackson` and `quarkus-rest-client` then
> 
> **POINT 1**
> 
> I switched the dependencies `quarkus-resteasy-reactive` and `quarkus-resteasy-jackson` with `quarkus-resteasy` and `quarkus-resteasy-jackson` and now I do not see any WARNs. You can check the modifications in this branch: https://github.com/fabry00/quarkus-rest-client-warn/tree/try1
> 
> However I have a question, Is my API still reactive even if I removed the *reactive dependencies? if yes can you provide an expansive explanation?

If you use `quarkus-resteasy` and/or `quarkus-rest-client`, even if you use the reactive types (`Multi`, `Uni`, `CompletionStage`), the code you are running will still do blocking things.
`quarkus-resteasy-reactive` and `quarkus-rest-client-reactive` have a reactive core and are non-blocking all the way.

> 
> **POINT 2**
> 
> I tried to remove `quarkus-rest-client-mutiny, quarkus-rest-client-jackson` and `quarkus-rest-client` and add `quarkus-rest-client-reactive-jackson` but there were some compilation errors:
> 
> ```
> #13 8.489 [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project rest-client-quickstart: Compilation failure: Compilation failure:
> #13 8.494 [ERROR] /usr/src/app/src/main/java/org/acme/rest/client/CountriesResource.java:[13,44] package org.jboss.resteasy.annotations.jaxrs does not exist
> #13 8.494 [ERROR] /usr/src/app/src/main/java/org/acme/rest/client/CountriesService.java:[11,44] package org.jboss.resteasy.annotations.jaxrs does not exist
> ```
> 

That's because you use `org.jboss.resteasy.annotations.jaxrs.PathParam;` which is specific to `quarkus-rest-client` (and classic RestEasy). 
The counterpart that works with `quarkus-rest-client-reactive`, and RestEasy Reactive, is `org.jboss.resteasy.reactive.RestPath`. You can just replace the former with the latter and all should work.

> Just adding back `quarkus-rest-client` the build succeeded but then I had other type of runtime errors while hitting the API
> More info here: https://github.com/fabry00/quarkus-rest-client-warn/tree/try2
> 
> Thanks

**Comment by fabry00** [comment] 2021-06-18 07:42
@michalszynkiewicz

I've moved the modification in my real project but now I have another issue.
Basically I've just removed `quarkus-rest-client`, `quarkus-rest-client-munity-jakson` and `quarkus-rest-client-munity` and added  `quarkus-rest-client-reactive-jacson`

Now the following code is throwing an exception (it was working fine before modifying the POM)

`
@ApplicationScoped
public class MyService {

   public Uni<Result> calculate(Request request) {
      
       return myRestClientService.getId().    // This return Uni<String> and perform a rest call using an injected instance of @RegisterRestClient interface
                  .flatMap(id -> anotherService.calculate(id, request) // This is doing another rest call and return Uni<Calculation>
                  .onItem().invoke(calculation -> oracleService.store(calculation) // This is throwing the exception (quarkus-jdbc-oracle)
                  .runSubscriptionOn(Infrastructure.getDefaultWorkedPool())
   }
}
`

The previous code was working fine. As specified in the docs we added `runSubscriptionOn` in order to move the blocking operation `oracleService.store` in the worker thread. It seems that, after modifying the POM the `runSubscriptionOn` is not working anymore. The exception shown is:

`IllegalStateException You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread` 

We saw this before and the solution was just to add `.runSubscriptionOn(Infrastructure.getDefaultWorkedPool())` and it has been working for a month. After this changes you mentioned above now it not working.

Can you please advice? how the modification with the POM clients libraries are related to this error?

Thanks

**Comment by michalszynkiewicz** [comment] 2021-06-18 08:20
I think it should rather be something like below:
```java
@ApplicationScoped   
public class MyService {
      public Uni<Result> calculate(Request request) {
          return myRestClientService.getId()    // This return Uni<String> and perform a rest call using an injected instance of @RegisterRestClient interface
                .flatMap(id -> anotherService.calculate(id, request) // This is doing another rest call and return Uni<Calculation>
                .emitOn(Infrastructure.getDefaultWorkedPool())
                .onItem().invoke(calculation -> oracleService.store(calculation) // This is throwing the exception (it uses quarkus-jdbc-oracle and orm-panache);
      }
 }
```

**Comment by fabry00** [comment] 2021-06-18 14:06
@michalszynkiewicz  thanks it worked.... I panicked for a while :)

**Comment by michalszynkiewicz** [comment] 2021-06-20 18:06
I'll close this issue then.

**Closed by michalszynkiewicz** 2021-06-20 18:06 UTC
Labels: area/native-image, area/rest-client, kind/bug
