### ISSUE TITLE
Provide capability to generate java-artifacts needed for native-image generation, without triggering native-image generation itself

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#14007] opened 2020-12-21 13:16 UTC
**Description**
The [Guide on building a native executable](https://quarkus.io/guides/building-native-image#using-a-multi-stage-docker-build) outlines the possibility of using multistage-dockerfiles to build a native executable through a container. The approach outlined has two major disadvantages:

- The whole application has to be rebuilt. in particular, all dependencies have to be downloaded. Through clever layering, we can cache some layers in which dependencies seldom change, but this approach will not cache all dependencies.
- In a multi-module setup, we would have to generate an assembly of the root project and then copy this assembly to the container.

A more straight forward approach would be to build the java artifacts on the host-side and only perform native compilation within a container by copying the java-artifacts to the container and calling `native-image` directly.

**Implementation ideas**
A possibility would be to add either a property or a separate packaging type that executes the existing build-process for local `native-image` compilation, but skips the call to `native-image ...`

FTR: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Can.20we.20compile.20an.20uber-jar.20to.20native.20executable.3F

**Comment by geoand** [comment] 2021-07-09 13:39
Actually this is a duplicate of https://github.com/quarkusio/quarkus/issues/15208 for which a fix was added in https://github.com/quarkusio/quarkus/pull/15233

**Closed by geoand** 2021-07-09 13:39 UTC
Labels: kind/enhancement, triage/needs-triage
