### ISSUE TITLE
Offer a way to centrally handle / log all unhandled exceptions outside of RestEasy

### ISSUE THREAD

**Issue by MarcusBiel** [quarkusio/quarkus#19224] opened 2021-08-04 12:21 UTC
### Description

For exceptions happening in RestEasy, we can create a class like:

```java
@Provider
public final class ApplicationExceptionHandler implements ExceptionMapper<RuntimeException> {

}
```

Which will then centrally handle all Exeptions and return a Response to the client. 
---
We need something similar for code unrelated to RestEasy, for example async Code running by @Scheduled or Quartz Jobs. 

I know you can create a LoggingInterceptor, but this will only work when you manually annotate each class with your newly created annotation. We need something that will make sure ALL Exceptions are ALWAYS caught and handled / logged, no matter if it was caught with a catch(MyException e) or an Interceptor, or not.

**Comment by famod** [comment] 2021-12-16 20:30
FWIW, just a "workaround", but a custom interceptor + ArchUnit tests work rather well for us.
E.g. we have a test that ensures that each `@Scheduled` is annotated with `@CatchAll` (our fault barrier interceptor).

**Comment by geoand** [comment] 2023-01-27 10:16
I am going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/19413

**Closed by geoand** 2023-01-27 10:16 UTC
Labels: kind/enhancement, area/core
