### ISSUE TITLE
Route conflict if Swagger and OpenAPI have a common path prefix

### ISSUE THREAD

**Issue by tcampili** [quarkusio/quarkus#4613] opened 2019-10-16 14:26 UTC
After upgrading quarkus version to 0.24.0 (even 0.25.0) swagger-ui interface is not displayed.
Swagger file is downloaded instead.

**To Reproduce**
1. Pick a working swagger-ui configuration with quarkus version 0.23.2
2. Upgrade quarkus to version 0.24.0 or 0.25.0
3. Access page http://localhost:8080/swagger-ui/
4. Swagger file is downloaded instead of showing swagger-ui interface

**Configuration**
```properties
# OPENAPI - SWAGGER
quarkus.smallrye-openapi.path=/swagger
quarkus.swagger-ui.always-include=true
```

**Additional Information**
Startup log does not show expected log
00:00:00,000 INFO  [io.qua.swa.run.SwaggerUiServletExtension] Swagger UI available at /swagger-ui

quarkus dependency included in project:
- quarkus-resteasy-jackson
- quarkus-smallrye-openapi
- quarkus-hibernate-orm-panache
- quarkus-jdbc-h2

Same problem appear even adding dependency on quarkus-undertow

**Comment by gsmet** [comment] 2019-10-16 14:36
From what I can see, you don't have the issue if you define `quarkus.smallrye-openapi.path` to `foo`. So I would bet that `/swagger` somehow catches everything starting with `/swagger`, `/swagger-ui` included.

**Comment by jaikiran** [comment] 2019-10-17 04:18
Unrelated to the issue at hand, I find it strange that log message's timestamp is `00:00:00,000`. I find it a bit hard to believe that the message was really logged at exactly 12 AM. It looks like this `SwaggerUiServletExtension` (which seems to be generating that log message) is a generated class. So perhaps there's something interesting going on in there in terms of logging.

**Comment by cescoffier** [comment] 2019-10-18 08:33
This is going to be fixed with the update to Vertx 3.8.3

**Comment by cescoffier** [comment] 2019-10-18 08:33
(so hopefully very soon)

**Comment by cescoffier** [comment] 2019-10-18 08:34
BTW, I've added a test reproducing the issue.

**Comment by cescoffier** [comment] 2019-10-27 16:20
Was fixed with the update to Vert.x 3.8.2

**Closed by cescoffier** 2019-10-27 16:20 UTC
Labels: bug
