### ISSUE TITLE
quarkus-hibernate-reactive-panache: hibernate validate doesn't work

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#15785] opened 2021-03-16 18:51 UTC
## Describe the bug
When using the `quarkus-hibernate-reactive-panache` extension and setting `quarkus.hibernate-orm.database.generation=validate`, the application fails to start with this exception:

```
2021-03-16 10:47:01,740 INFO  [org.hib.rea.pro.imp.ReactiveIntegrator] (Quarkus Main Thread) HRX000001: Hibernate Reactive Preview
2021-03-16 10:47:01,844 WARN  [org.hib.eng.jdb.spi.SqlExceptionHelper] (Quarkus Main Thread) SQL Error: 0, SQLState: null
2021-03-16 10:47:01,844 ERROR [org.hib.eng.jdb.spi.SqlExceptionHelper] (Quarkus Main Thread) Not using JDBC
2021-03-16 10:47:02,425 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.sql.SQLException: Not using JDBC
        at org.hibernate.reactive.provider.service.NoJdbcConnectionProvider.getConnection(NoJdbcConnectionProvider.java:25)
        at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection(JdbcEnvironmentInitiator.java:180)
        at org.hibernate.resource.transaction.backend.jdbc.internal.DdlTransactionIsolatorNonJtaImpl.getIsolatedConnection(DdlTransactionIsolatorNonJtaImpl.java:43)
```

If I change `quarkus.hibernate-orm.database.generation=drop-and-create` then everything works as expected.

**Comment by gavinking** [comment] 2021-03-16 18:53
Hi, this is a limitation listed in the README. We're working on it.

**Comment by edeandrea** [comment] 2021-03-16 18:54
Which README? For the extension? I also noticed there isn't a guide available for the `quarkus-hibernate-reactive-panache` extension.

**Comment by DavideD** [comment] 2021-03-16 18:56
The Hibernate Reactive [README.md](https://github.com/hibernate/hibernate-reactive/#limitations)

**Comment by DavideD** [comment] 2021-03-16 18:58
> I also noticed there isn't a guide available for the `quarkus-hibernate-reactive-panache` extension.

It's still an experimental feature but you can find some examples in the quickstart: https://github.com/quarkusio/quarkus-quickstarts/tree/development/hibernate-reactive-quickstart

**Comment by DavideD** [comment] 2021-03-16 19:05
Sorry, it was the wrong quickstart. This is the one for `quarkus-hibernate-reactive-panache`: https://github.com/quarkusio/quarkus-quickstarts/tree/development/hibernate-reactive-panache-quickstart

**Comment by gavinking** [comment] 2021-03-22 11:31
This issue is a dupe of #10665. Can we just close it?

**Comment by edeandrea** [comment] 2021-03-22 11:39
#10665 seems related to this one but not the same use case, although from an implementation standpoint it might be more related?

Essentially what's missing is the ability to validate the schema matches what the application "thinks" the schema should be.

**Comment by gavinking** [comment] 2021-03-22 12:53
> though from an implementation standpoint it might be more related?

From an implementation standpoint I have no idea how I could make schema validation work without also making schema update work by side-effect :-)

All we need to do is make a "mock" JDBC metadata API based on the reactive driver.

**Comment by edeandrea** [comment] 2021-03-22 12:54
That works for me.

**Closed** 2021-04-01 09:36 UTC
Labels: area/hibernate-reactive, area/panache, area/persistence, kind/bug
