### ISSUE TITLE
Native application throws CCE on SIGINT

### ISSUE THREAD

**Issue by johnaohara** [quarkusio/quarkus#2215] opened 2019-04-25 09:48 UTC
I terminated a native running application with Ctrl+C, and the following exception was thrown;

```
2019-04-25 10:42:58,373 ERROR [org.jbo.exe.uncaught] (executor-thread-2) Thread Thread[executor-thread-2,5,executor] threw an uncaught exception: java.lang.ClassCastException: org.jboss.threads.JBossThread cannot be cast to java.lang.Thread
	at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:47)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
```

This application was built with graalvm-ee-1.0.0-rc16-linux-amd64 and quarkus 999-SNAPSHOT (5d27cf8b738b2ad0e9ce2c505e206dbda48745a2)

**Comment by ppalaga** [comment] 2019-04-26 08:13
Looks like a duplicate of https://github.com/quarkusio/quarkus/issues/2218

**Closed** 2019-04-26 10:06 UTC
Labels: bug, component:core, duplicate
