### ISSUE TITLE
Reactive Messaging Kafka: cannot connect to DLQ when using SASL protocol since 3.7

### ISSUE THREAD

**Issue by jacopo-cavallarin** [quarkusio/quarkus#38700] opened 2024-02-09 08:29 UTC
### Describe the bug

After upgrading from Quarkus 3.6 to 3.7, our Kafka consumers can no longer connect to the DLQ while processing a nack.

This makes the nack fail after a timeout of 60 seconds, making the application unhealthy and causing continuous restarts of our k8s pods.

This seems to happen only when using a security protocol different from PLAINTEXT. We use SASL_SSL in our microservices in order to connect to our Confluent Cloud cluster; we also managed to reproduced the problem locally by creating a broker that uses the SASL_PLAINTEXT protocol (see the reproducer).

### Expected behavior

When a message is nacked in an `@Incoming` channel consumer, the message should be sent to the DLQ without errors.

### Actual behavior

The application keeps logging this warning every couple of seconds as soon as it starts:
`WARN  [org.apa.kaf.cli.NetworkClient] (kafka-producer-network-thread | kafka-dead-letter-topic-producer-kafka-consumer-test-consumer) [Producer clientId=kafka-dead-letter-topic-producer-kafka-consumer-test-consumer] Bootstrap broker <bootstrap server> (id: -1 rack: null) disconnected`

When a message is nacked in an `@Incoming` channel consumer, no message is sent to the DLQ. After about 60 seconds, this error is logged:
`Topic <dlq topic name> not present in metadata after 60000 ms.`
and the application is reported as unhealty.

### How to Reproduce?

Reproducer: https://github.com/jacopo-cavallarin/dlq-bug-reproducer

Clone the linked repo and follow the README to reproduce the problem.

### Output of `uname -a` or `ver`

Darwin Host-009.homenet.telecomitalia.it 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:55:06 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17 LTS OpenJDK Runtime Environment Temurin-21.0.1+12 (build 21.0.1+12-LTS) OpenJDK 64-Bit Server VM Temurin-21.0.1+12 (build 21.0.1+12-LTS, mixed mode)

### Quarkus version or git rev

3.7.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /Users/jacopocavallarin/.sdkman/candidates/maven/current Java version: 21.0.1, vendor: Eclipse Adoptium, runtime: /Users/jacopocavallarin/.sdkman/candidates/java/21.0.1-tem Default locale: en_IT, platform encoding: UTF-8 OS name: "mac os x", version: "14.2.1", arch: "aarch64", family: "mac"

**Comment by ozangunalp** [comment] 2024-02-09 08:33
Looks like an issue on reactive messaging. Thanks for the reproducer. I'll check ASAP

**Comment by pcasaes** [comment] 2024-02-13 00:09
We had a similar issue for the schema registry configuration `.schema.registry.url`.

4.16.2 fixed that as well.

**Comment by cescoffier** [comment] 2024-02-13 07:07
@ozangunalp should we close this one?

**Comment by ozangunalp** [comment] 2024-02-13 09:34
Indeed, it is fixed with #38712

**Closed by ozangunalp** 2024-02-13 09:34 UTC
Labels: kind/bug, area/smallrye, area/reactive-messaging, area/kafka
