### ISSUE TITLE
swagger ui resource(js, css, ico, png) sometimes not found in quarkus:dev mode

### ISSUE THREAD

**Issue by angelo-chan** [quarkusio/quarkus#14879] opened 2021-02-07 03:23 UTC
**Describe the bug**
when start the application using quarkus:dev and request the swagger ui, sometimes, the swagger UI resource missing

**Expected behavior**
Swagger UI always can request successfully

**Actual behavior**
Sometimes request swagger UI resource missing

**Screenshots**

![image](https://user-images.githubusercontent.com/8653839/107135483-12d48480-6936-11eb-8897-5aa476eea9c0.png)

and the generated resource on my pc like below(successful situation):

![image](https://user-images.githubusercontent.com/8653839/107135610-1ae0f400-6937-11eb-95c0-539e6cd5ff4e.png)

while request failed, there's only an index.html in the folder. After I delete the whole folder, and restart the application, everything is ok.

**Environment (please complete the following information):**
 - Darwin AngeloChen-MBP 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - java version "1.8.0_191"
 - Quarkus 1.10.5.Final, 1.11.1.Final

**Additional context**

**Comment by phillip-kruger** [comment] 2021-02-07 04:01
Hi, this is "fixed" in 1.12.

See https://github.com/quarkusio/quarkus/pull/14499

**Comment by gsmet** [comment] 2021-02-08 17:16
Hmmm, this PR has been backported to 1.11.1.Final so if the OP has the issue with 1.11.1.Final too, it's a different issue.

@angelo-chan when you have only the index.html, it's the file you would expect or it's something else entirely?

**Comment by phillip-kruger** [comment] 2021-02-08 17:21
Hi @gsmet - we decided not to backport. But saying that, reading the issue again, this sounds like something else.
@angelo-chan - can you provide more details ? Ie. the flow of commands to get to this state. (so what is the sometimes)

**Comment by gsmet** [comment] 2021-02-08 17:34
In the end, I backported it (IIRC it conflicted with other things I wanted fix or I thought it was safe enough in the end). I checked and it's in the 1.11 branch and the fix version is correct.

**Comment by phillip-kruger** [comment] 2021-02-08 20:14
@gsmet -  Ok awesome. Waiting for @angelo-chan to provide more details, so that I can see if I can recreate this issue.

**Comment by angelo-chan** [comment] 2021-02-09 07:34
Actually I can't reproduce the issue always, most of time it happens at accident. 

It's happens while I issue `./mvnw clean compile quarkus:dev`, then request the swagger-ui, the resource not found. If this situation happens, I enter the folder `/var/folders/f3/b3g92vt537n0mct3m86938_h0000gn/T/quarkus/net.yuntu/era/io.smallrye/smallrye-open-api-ui/2.0.19`, there's only one file index.html exists, no other resource files.

**Comment by phillip-kruger** [comment] 2021-02-09 07:37
How often does it happen ? And does it go away if you try again ?

**Comment by phillip-kruger** [comment] 2021-02-09 07:42
@angelo-chan - I can not seem to recreate this, so I am not sure how to proceed. This works every time for me. Any more details you can provide ? What change did you make that made you restart dev mode ?

**Comment by angelo-chan** [comment] 2021-02-09 07:42
More frequent than a developer can ignore it. To manually delete the folder `/var/folders/f3/b3g92vt537n0mct3m86938_h0000gn/T/quarkus/net.yuntu/era/io.smallrye/smallrye-open-api-ui/2.0.19` and issue `./mvnw compile quarkus:dev` again, everything back to normal.

**Comment by phillip-kruger** [comment] 2021-02-09 07:45
And nothing in the log ? Maybe it's specific to your application. Can you share a small app where it happens for you ?

**Comment by phillip-kruger** [comment] 2021-02-09 07:47
> More frequent than a developer can ignore it. 
I am trying to find out how many times I need to start and stop to see if I can recreate it. So I am going to need a more tangable answer  :) 1 out of 10? 5? 2?

**Comment by angelo-chan** [comment] 2021-02-09 08:22
there's no accurate happen ratio, most of time it works perfectly. It just happens sometimes, maybe 1 out of 100. Once happen, I have to delete that folder. No special log.

**Comment by phillip-kruger** [comment] 2021-02-09 08:30
OK, I am going to need more details before I can spend time on this. What change did you make that made you restart dev mode ?
Can you share a small application that you know that it happens with?

**Comment by angelo-chan** [comment] 2021-02-09 09:14
I just tried to reproduce it but failed. I share a project [here](https://github.com/angelo-chan/quarkus-sample)

**Comment by phillip-kruger** [comment] 2021-02-09 09:29
Thanks :) I still can not recreate this. If you figure out more details, please share.

**Comment by angelo-chan** [comment] 2021-02-09 10:17
> Thanks :) I still can not recreate this. If you figure out more details, please share.

sure

**Comment by gsmet** [comment] 2022-02-28 21:15
We changed the way the resources are initialized so this might have been fixed in the way. Closing cause we were unable to reproduce it.

**Closed by gsmet** 2022-02-28 21:15 UTC
Labels: kind/bug, area/devmode, area/swagger-ui
