### ISSUE TITLE
Quarkus RESTEasy default dependency

### ISSUE THREAD

**Issue by sumitpaulde** [quarkusio/quarkus#7942] opened 2020-03-18 17:50 UTC
**Problem Description**
I am trying to develop one microservice which will upload file to the Amazon S3 cloud. As Quarkus uses RESTEasy as default so I am unable to use MultipartFile provided by the org.springboot.web.multipart.MultipartFile. Then I have decided to use RESTEasy but after going through this `https://stackoverflow.com/questions/26333298/multipartform-how-to-get-the-original-file-name` no hope left. Is there really no option to get the name and extension of the uploaded file without parsing an HTML file? If not how can I exclude the RESTEasy dependency, so that MultipartFile of the spring-boot can work? Without original file name and extension uploading files in Amazon S3 makes no sense.

**Implementation ideas**
Exclude the RESTEasy default dependency so that any user can use the MultipartFile from org.springframework.web.multipart.MultipartFile.

**Comment by gsmet** [comment] 2020-03-20 18:22
@asoldano I think the root of the issue is that manipulating files with JAX-RS is too complicated, even with the RESTEasy additions.

I also found myself in the same situation a few months ago.

Could we try to improve this situation? Especially compared to what Spring does?

**Comment by asoldano** [comment] 2020-03-23 09:57
@gsmet  @sumitpaulde , I haven't looked in details at this and don't know about the implementation of springboot, but sure if you have a proposal for enhancing RESTEasy, feel free to create a JIRA or even send a proposal in a PR. AFAIR, the expectations is that the user goes and scan the input parts' headers; isn't going iterating through them and looking for Content/Disposition with filename in it doable? Perhaps we could provide a convenient utility method that does this?

**Comment by gsmet** [comment] 2020-03-23 10:45
Yes, having to go through the headers is exactly what we want to avoid. It would be nice to be able to inject a properly populated object containing all the relevant information.

You can see what Spring does here with `MultipartFile`: https://spring.io/guides/gs/uploading-files/ .

**Comment by geoand** [comment] 2021-02-26 11:31
I think we can close this as both RESTEasy Classic and RESTEasy Reactive we have support for Multipart file upload (see https://quarkus.io/guides/resteasy-reactive#handling-multipart-form-data).

If there are more idea for improvement, I'd love to hear them.

**Closed by geoand** 2021-02-26 11:31 UTC
Labels: kind/enhancement
