### ISSUE TITLE
List of compatible Java versions & default Java version should be stream dependent

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#28754] opened 2022-10-21 15:03 UTC
### Description

Currently the Java version list is fixed which is ok in the current state.

In the future we might need to add new compatible version only for new streams.

cc @quarkusio/devtools

**Comment by gastaldi** [comment] 2022-10-21 15:08
Duplicate of https://github.com/quarkusio/quarkus/issues/28497?

**Comment by gastaldi** [comment] 2022-10-28 12:29
Duplicate of 28497

**Closed by gastaldi** 2022-10-28 12:29 UTC
Labels: kind/enhancement, area/platform, area/devtools, area/registry
