### ISSUE TITLE
NoSuchMethod during unit test

### ISSUE THREAD

**Issue by agiertli** [quarkusio/quarkus#2949] opened 2019-06-24 14:17 UTC
Please see following test case:

https://github.com/agiertli/quarkus-nosuchmethod-error

This may be related to:
https://github.com/quarkusio/quarkus/issues/1724
(I am not sure)

**Comment by agiertli** [comment] 2019-06-24 14:17
Closing as it's a duplicate of:
https://github.com/quarkusio/quarkus/issues/1724

**Comment by agiertli** [comment] 2019-06-25 06:07
Can somebody from eng please double check whether this is the same manifestation of the issue reported here #1724?

**Comment by FroMage** [comment] 2019-06-25 10:17
Thanks, I will check this.

**Comment by FroMage** [comment] 2019-06-26 14:55
Huh, this is weird, I can't reproduce this. Running `mvn clean test` from your repo passes for me. Which JDK are you using?

**Comment by agiertli** [comment] 2019-06-27 09:59
Hi,

I have tried with jdk 8 and jdk 11. Error occurs with both.

$ java -version
openjdk version "11.0.2" 2019-01-15
$ java -version
java version "1.8.0_181"
$ mvn -v
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T20:33:14+02:00)

**Comment by agiertli** [comment] 2019-06-27 10:05
I've also asked a friend test this.
He is using Fedora 30 and OpenJDK 1.8
The output is here:
```
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.RepositoryTest
[INFO] H2 database started in TCP server mode
2019-06-27 12:02:10,234 INFO  [io.qua.dep.QuarkusAugmentor] (main) Beginning quarkus augmentation
2019-06-27 12:02:11,610 INFO  [io.qua.dep.QuarkusAugmentor] (main) Quarkus augmentation completed in 1376ms
2019-06-27 12:02:12,280 INFO  [io.qua.swa.run.SwaggerUiServletExtension] (main) Swagger UI available at /swagger-ui
2019-06-27 12:02:13,167 INFO  [io.quarkus] (main) Quarkus 0.17.0 started in 1.338s. Listening on: http://[::]:8081
2019-06-27 12:02:13,167 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, hibernate-orm, jdbc-postgresql, narayana-jta, resteasy, resteasy-jsonb, smallrye-openapi, swagger-ui]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 13.448 s - in org.RepositoryTest
[INFO] Running org.NoSuchMethodTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in org.NoSuchMethodTest
[ERROR] testNoSuchMethodError  Time elapsed: 0.001 s  <<< ERROR!
java.lang.NoSuchMethodError: org.redhat.Invoice.setAccountId(Ljava/lang/String;)V
        at org.NoSuchMethodTest.testNoSuchMethodError(NoSuchMethodTest.java:38)
 
[INFO] H2 database was shut down
2019-06-27 12:02:13,213 INFO  [io.quarkus] (main) Quarkus stopped in 0.012s
[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   NoSuchMethodTest.testNoSuchMethodError:38 » NoSuchMethod org.redhat.Invoice.se...
[INFO]
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:31 min
[INFO] Finished at: 2019-06-27T12:02:13+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project no-such-method-error: There are test failures.
[ERROR]
[ERROR] Please refer to /tmp/quarkus-nosuchmethod-error/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

**Comment by geoand** [comment] 2019-07-05 14:04
I could reproduce this every time on my clean with a simple `mvn clean test`.
The funny (but sort of expected) thing is that moving `TestUtils` from `src/test` to `src/main` eliminates the problem.

**Comment by anderson-marques** [comment] 2019-07-18 22:12
Same happens to me. I'm running inside the docker image `maven:3.6-jdk-8` and running simply `mvn test`.

```
2019-07-18 22:08:37,859 ERROR [io.und.req.io] (executor-thread-1) Exception handling request d3ea51de-e68a-48ac-ab0b-7b77fbc1f83f-3 to /accounts: java.lang.NoSuchMethodError: i.p.a.c.CreateAccountServiceImpl: method <init>()V not found
```

**Comment by anderson-marques** [comment] 2019-07-18 22:43
> Same happens to me. I'm running inside the docker image `maven:3.6-jdk-8` and running simply `mvn test`.
> 
> ```
> 2019-07-18 22:08:37,859 ERROR [io.und.req.io] (executor-thread-1) Exception handling request d3ea51de-e68a-48ac-ab0b-7b77fbc1f83f-3 to /accounts: java.lang.NoSuchMethodError: i.p.a.c.CreateAccountServiceImpl: method <init>()V not found
> ```
> 
> **Maven home: /usr/share/maven Java version: 1.8.0_212, vendor: Oracle Corporation, runtime: /usr/local/openjdk-8/jre Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "4.9.125-linuxkit", arch: "amd64", family: "unix"**

My bean was using `@Inject` in the constructor. I replaced this for `@Inject` for each dependency member and everything works perfectly now.

```java
// From this

@RequestScoped
class X implements Z {

   @Inject
   public X(A a, B b, C c) {
       //...
   }
}

// To this

@RequestScoped
class X implements Z {
   @Inject A a;
   @Inject B b;
   @Inject C c;
}

**Comment by gsmet** [comment] 2019-11-13 14:28
@anderson-marques could you check if it's still an issue with latest master?

**Comment by gsmet** [comment] 2019-11-18 21:42
Closing, please reopen a new one if you encounter this issue. It might have different causes.

**Closed by gsmet** 2019-11-18 21:42 UTC
Labels: bug, component:panache
