### ISSUE TITLE
class cast exception

### ISSUE THREAD

**Issue by jigneshmpatel** [quarkusio/quarkus#32973] opened 2023-04-27 22:20 UTC
### Describe the bug

@ApplicationScoped
public class CustomerRepository implements PanacheRepositoryBase<Customer,Integer> {

    private static final Logger logger = Logger.getLogger(CustomerRepository.class);
    /**
     * Find Customer data base on customerId
     * @param customerId
     */
    @Transactional(REQUIRED)
    public Customer findByCustomerId(String customerId) {
        logger.info("customerId: "+customerId);
        return find("customerId",customerId).firstResult();
    }
}
The system gives following error
 Caused by: [CIRCULAR REFERENCE: java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')]

### Expected behavior

The system should execute the flow.

### Actual behavior

throws classcast exception
Caused by: java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')

### Output of `java -version`

17

### Quarkus version or git rev

3.0.0.CR2

**Comment by jigneshmpatel** [comment] 2023-04-27 22:22
The serilizers and deserailzers are looks as follows:
mp.messaging.outgoing.data.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.incoming.requests.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer

**Comment by mschorsch** [comment] 2023-04-28 06:29
Try Quarkus 3.0.1.Final instead of Quarkus 3.0.0.CR2

**Comment by jigneshmpatel** [comment] 2023-04-28 12:07
Tried same issue.
Is it because I am using lombok?
I posted the code at the following place.
https://github.com/quarkusio/quarkus/issues/32835

**Comment by jigneshmpatel** [comment] 2023-04-28 22:48
Sample code updated,
https://github.com/jigneshmpatel/consumer/settings/access
after removing other code now, it is giving different error:
RMSG00103: Exception thrown when calling the method
com.acme.consumer.processor.Consumer#processEvent
at
io.smallrye.reactive.messaging.providers.ProcessorMediator.handlePostInvocation(ProcessorMediator.java:369)
at
io.smallrye.reactive.messaging.providers.ProcessorMediator.lambda$processMethodReturningACompletionStageOfPayloadAndConsumingIndividualItem$51(ProcessorMediator.java:423)
at
io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
at
io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
... 39 more
Caused by: org.hibernate.type.descriptor.java.CoercionException: Error
coercing value
at
org.hibernate.type.descriptor.java.CoercionHelper.coerceWrappingError(CoercionHelper.java:396)
at
org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:182)
at
org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:24)
at
org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:176)
at
org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:160)
at
org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:107)
at
org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:160)
at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2401)
at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2367)
at
io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.find(TransactionScopedSession.java:175)
at
org.hibernate.engine.spi.SessionLazyDelegator.find(SessionLazyDelegator.java:784)
at
org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.find(Unknown
Source)
at
com.acme.consumer.repository.CustomerRepository.findByCustomerId(CustomerRepository.java:27)
at
com.acme.consumer.repository.CustomerRepository_Subclass.findByCustomerId$$superforward(Unknown
Source)
at
com.acme.consumer.repository.CustomerRepository_Subclass$$function$$1.apply(Unknown
Source)
at
io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
at
io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
at
io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown
Source)
at
io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
at
io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
at
io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
at
com.acme.consumer.repository.CustomerRepository_Subclass.findByCustomerId(Unknown
Source)
at
com.acme.consumer.repository.CustomerRepository_ClientProxy.findByCustomerId(Unknown
Source)
at
com.acme.consumer.service.CustomerService.findByCustomerId(CustomerService.java:23)
at
com.acme.consumer.service.CustomerService_ClientProxy.findByCustomerId(Unknown
Source)
at com.acme.consumer.service.BService.process(BService.java:41)
at com.acme.consumer.service.BService_ClientProxy.process(Unknown Source)
at
com.acme.consumer.processor.Consumer.lambda$processEvent$0(Consumer.java:32)
at
java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
... 6 more
Caused by: java.lang.NumberFormatException: For input string:
"2020110000107"
at
java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
at java.base/java.lang.Integer.parseInt(Integer.java:668)
at java.base/java.lang.Integer.parseInt(Integer.java:786)
at
org.hibernate.type.descriptor.java.IntegerJavaType.lambda$coerce$0(IntegerJavaType.java:183)
at
org.hibernate.type.descriptor.java.CoercionHelper.coerceWrappingError(CoercionHelper.java:393)
... 39 more
[CIRCULAR REFERENCE:org.hibernate.type.descriptor.java.CoercionException:
Error coercing value]

**Comment by yrodiere** [comment] 2023-05-01 07:22
> after removing other code now

Do you mean the previous error you were getting was caused by a problem in your own code? This is important for us, so we know whether there's something to investigate or not.

> it is giving different error

@jigneshmpatel "2020110000107" cannot be parsed into an integer, it's higher than `Integer.MAX_VALUE`. From what I can see in your stack trace, you asked the session to find the entity with ID `"2020110000107"`, passing a String, and Hibernate ORM tried to convert that to the actual entity ID type (`Integer`), which failed because it's not possible. So this is basically an input error.

Does that help?

**Comment by yrodiere** [comment] 2023-05-02 11:52
I'm going to close this as invalid; feel free to comment again if my answer above does not explain your problems completely, and we'll reopen as necessary.

**Closed by yrodiere** 2023-05-02 11:52 UTC
Labels: kind/bug, triage/invalid, area/hibernate-orm
