### ISSUE TITLE
How to use multiple OIDC clients with a single realm in Quarkus (IDP: Keycloak). Multi-tenancy support with Token instead of RoutingContext's path

### ISSUE THREAD

**Issue by aksth** [quarkusio/quarkus#11021] opened 2020-07-28 08:44 UTC
I have two questions regarding the use of OIDC with Keycloak in Quarkus:

1.  I need to use multiple clients with a single realm (tenant). How to?
2. Right now, multi-tenancy is based on `RoutingContext`'s path parameter. What if I want to use the same API URL path for multiple tenants/realms? In that case, I will have to use JWT Token's "issuer" parameter to distinguish the realm. Is there a way to get the JWT Token in the `TenantResolver`? I can't see the Authorization header in the header properties of the 'RoutingContext'.

Here, if the second issue is solved, then the first one can also be resolved by implementing `TenantResolver`, and using the token's "authorized party" parameter.

In my app, I have a single realm with multiple clients. The API URL paths are pretty complex and some have common paths associated with. If I go by separating the realm, I can't distinguish the realm using the API URL path. If there is a way to get the token in the `TenantResolver`, then I could either use "one realm, multiple clients" or "multiple realms, single/multiple clients" configuration. But I don't prefer to separate the realm. So how can I deal with this situation?. I really need to use multiple clients with the same single realm.

**Comment by aksth** [comment] 2020-07-28 09:03
@pedroigor @sberyozkin Can you help me out?

**Comment by pedroigor** [comment] 2020-07-28 11:50
@aksth If your application is a `web-app` type you should be able to obtain tokens via CDI. The token should only be available from your request headers if your application is a `service` type and protected with bearer authorization.

Could you confirm what is the type of application you are using?

**Comment by aksth** [comment] 2020-07-28 18:03
It is a `service` type. The clients send requests which include a Bearer token in the 'Authorization' header. Even if its a `service` type application, I tried to inject the `JsonWebToken` (IdToken) as well as `SecurityContext` but like you said it wasn't loaded when context resolver was executing.

**Comment by pedroigor** [comment] 2020-07-28 18:34
@aksth For that type of client you should be able to obtain the bearer token from header context.request().headers().get("Authorization"). The problem is that you would need to decode and parse the value to then access the content of the JWT (for opaque tokens, it won't work).

I would say we need to revied multi-tenancy code in order to allow custom resolvers to have access to the "unverified" token so that you can perform any logic based on its claims. That should not work for opaque tokens though.

**Comment by aksth** [comment] 2020-07-29 03:30
Thanks, @pedroigor. `context.request().headers().get("Authorization")` does the work. Is this a suitable way to do it? or will it have some side effects in the future?

**Comment by pedroigor** [comment] 2020-07-29 12:42
No side effect if you are using JWT. But you would need to parse the token by yourself. We could potentially make this use case a bit easier to implement.

**Comment by sberyozkin** [comment] 2020-08-17 12:34
Hi @aksth @pedroigor Just back from PTO. 
Since we can't inject, the only way to simplify is to offer some utility code to parse the token but I'm not sure if we we can generalize beyond that. 
@aksth, how do you parse the token right now ?

**Comment by sberyozkin** [comment] 2020-08-20 15:49
@aksth Hi, we have a simple utility code which decodes the content into `JsonObject`: https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcUtils.java#L44

It is quite effective and please use it, if you;d like. I think we can close this issue now
CC @pedroigor

**Closed** 2020-08-20 16:38 UTC
Labels: area/oidc
