### ISSUE TITLE
Dev Services for Kafka combined with continuous testing not working right.

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#19180] opened 2021-08-02 19:26 UTC
### Describe the bug

I'm trying to combine Dev Services for Kafka with Continuous testing and the experience isn't that great. In all the scenarios I mention below I am creating an application from scratch using the SmallRye Reactive messaging & RESTEasy reactive extensions.

In all scenarios mentioned below the continuous testing hangs and the entire `quarkus:dev` needs to be `CTRL-C`'ed and restarted.

The `PriceResourceTests` class mentioned in all scenarios looks like this:
```java
@QuarkusTest
class PriceResourceTests {
    @TestHTTPEndpoint(PriceResource.class)
    @TestHTTPResource("/stream")
    URI uri;

    @Test
    public void sseStream() {
        Client client = ClientBuilder.newClient();
        WebTarget target = client.target(this.uri);

        List<Double> received = new CopyOnWriteArrayList<>();

        try (SseEventSource source = SseEventSource.target(target).build()) {
            source.register(inboundSseEvent -> received.add(Double.valueOf(inboundSseEvent.readData())));
            source.open();

            await()
                .atMost(Duration.ofSeconds(15))
                .until(() -> received.size() == 2);
        }

        assertThat(received)
            .hasSize(2)
            .allMatch(value -> (value >= 0) && (value < 100));
    }
}
```

When completed, the `PriceGenerator` class looks like this:
```java
@ApplicationScoped
public class PriceGenerator {
    private final Random random = new Random();

    @Outgoing("generated-price")
    public Multi<Integer> generate() {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(5))
                .onOverflow().drop()
                .map(tick -> this.random.nextInt(100));
    }
}
```

When completed, the `PriceConverter` class looks like this:
```java
@ApplicationScoped
public class PriceConverter {
    private static final double CONVERSION_RATE = 0.88;

    @Incoming("prices")
    @Outgoing("processed-prices")
    @Broadcast
    public double process(int priceInUsd) {
        return priceInUsd * CONVERSION_RATE;
    }
}
```

When completed, the `PriceResource` class looks like this:
```java
@Path("/prices")
public class PriceResource {
    private final Publisher<Double> processedPrices;

    public PriceResource(@Channel("processed-prices") Publisher<Double> processedPrices) {
        this.processedPrices = processedPrices;
    }

    @GET
    @Path("/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public Publisher<Double> ssePrices() {
        return this.processedPrices;
    }
}
```

When completed, the `application.properties` file looks like this:
```properties
# Configure the Kafka sink (we write to it)
mp.messaging.outgoing.generated-price.connector=smallrye-kafka
mp.messaging.outgoing.generated-price.topic=prices
mp.messaging.outgoing.generated-price.value.serializer=org.apache.kafka.common.serialization.IntegerSerializer

# Configure the Kafka source (we read from it)
mp.messaging.incoming.prices.connector=smallrye-kafka
mp.messaging.incoming.prices.health-readiness-enabled=false
mp.messaging.incoming.prices.topic=prices
mp.messaging.incoming.prices.value.deserializer=org.apache.kafka.common.serialization.IntegerDeserializer
```

### How to Reproduce?

# Scenario 1
1. Generate project
2. Add these dependencies to `pom.xml`
   ```xml
   <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
   ```
3. Add an empty `PriceGenerator`, `PriceConverter`, and `PriceResource` classes in `src/main/java/com/example`
4. Add a completed `PriceResourceTests` class in `src/test/java/com/example`
5. Run `quarkus:dev`
6. Turn on testing
7. Complete `PriceResource` class
8. Complete `PriceGenerator` class
9. Complete `PriceConverter` class
10. Complete `application.properties`

At this step the console output indicates the test is running but it never completes, even though the test itself has a 15 second timeout. Furthermore, it seems the application itself never even restarts itself unless, from another terminal, issue an http request to `/prices/stream`. Still, the continuous testing is hung and I have to CTRL-C.

# Scenario 2
1. Generate project
2. Add these dependencies to `pom.xml`
   ```xml
   <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
   ```
3. Add an empty `PriceGenerator`, `PriceConverter`, and `PriceResource` classes in `src/main/java/com/example`
4. Add a completed `PriceResourceTests` class in `src/test/java/com/example`
5. Complete `application.properties`
6. Run `quarkus:dev`
7. Turn on testing
8. Complete `PriceResource` class
9. Complete `PriceGenerator` class
10. Complete `PriceConverter` class

Same result as scenario 1

# Scenario 3
1. Generate project
2. Add these dependencies to `pom.xml`
   ```xml
   <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
   ```
3. Add an empty `PriceGenerator`, `PriceConverter`, and `PriceResource` classes in `src/main/java/com/example`
4. Add a completed `PriceResourceTests` class in `src/test/java/com/example`
5. Complete `application.properties`
6. Run `quarkus:dev`
7. Complete `PriceResource` class
8. Complete `PriceGenerator` class
9. Complete `PriceConverter` class
10. Turn on testing

Same result as scenario 1

# Scenario 4
1. Generate project
2. Add these dependencies to `pom.xml`
   ```xml
   <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-client</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.awaitility</groupId>
      <artifactId>awaitility</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.assertj</groupId>
      <artifactId>assertj-core</artifactId>
      <scope>test</scope>
    </dependency>
   ```
3. Add a completed `PriceGenerator` and `PriceResource` classes in `src/main/java/com/example`
4. Add a completed `PriceResourceTests` class in `src/test/java/com/example`
5. Complete `application.properties`
6. Run `quarkus:dev`
7. Turn on testing
10. Complete `PriceConverter` class

Same result as scenario 1

### Output of `uname -a` or `ver`

`Darwin edeandre-mac 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

### GraalVM version (if different from Java)
```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
```

### Quarkus version or git rev

`2.1.0.Final`

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Users/edeandre/.sdkman/candidates/java/11.0.2-open
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by edeandrea** [comment] 2021-08-02 19:28
FYI I also did [post on Zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/DevServices.20for.20Kafka.20not.20restarting/near/247940900) about this

**Comment by edeandrea** [comment] 2021-08-02 20:25
I've been playing around a bit and not sure if this is relevant, but when its "hung" I can see multiple kafka brokers trying to be run, both trying to be exposed on port `9092` on my localhost.

```shell
edeandre@edeandre-mac:quarkus-kafka$ docker ps
CONTAINER ID   IMAGE                         COMMAND                  CREATED              STATUS              PORTS                                                                                      NAMES
c1548293f5f0   vectorized/redpanda:v21.5.5   "sh -c 'while [ ! -f…"   38 seconds ago       Up 37 seconds       0.0.0.0:55076->9092/tcp, :::55076->9092/tcp, 0.0.0.0:55075->9644/tcp, :::55075->9644/tcp   quirky_brattain
a93a5e5194a9   testcontainers/ryuk:0.3.1     "/app"                   About a minute ago   Up About a minute   0.0.0.0:55072->8080/tcp, :::55072->8080/tcp                                                testcontainers-ryuk-7dc07c45-b9aa-421d-836e-4b950468a41b
e85a973edce9   vectorized/redpanda:v21.5.5   "sh -c 'while [ ! -f…"   About a minute ago   Up About a minute   0.0.0.0:55071->9092/tcp, :::55071->9092/tcp, 0.0.0.0:55070->9644/tcp, :::55070->9644/tcp   infallible_zhukovsky
0d4e9c15f8ea   testcontainers/ryuk:0.3.1     "/app"                   About a minute ago   Up About a minute   0.0.0.0:55069->8080/tcp, :::55069->8080/tcp                                                testcontainers-ryuk-be11a142-f947-48ea-8200-2262ed126206

```

**Comment by stuartwdouglas** [comment] 2021-08-03 07:12
I think this may be fixed upstream, can you try with the main branch?

**Comment by Ladicek** [comment] 2021-08-03 09:19
I'm trying scenario 4 (seems easiest :-) ) on current `main` and it seems to work just fine. The test does fail after 15 seconds, and when I complete `PriceConverter`, the test automatically runs again and passes (after a little more than 10 seconds, as expected).

**Comment by ozangunalp** [comment] 2021-08-03 10:29
I tested a bunch of scenarios and never had multiple test containers for the same application with `quarkus:dev`. (Working on Mac for reference.)

However, I am having issues at app startup with reactive messaging Kafka extension. 
1. When the `application.properties` contains the connector options but no associated code, it won't start up.
2. When adding code and associated configuration options together, I've the `value.deserializer` must be set error because I am guessing the serde autodetection hasn't re-run.

Not sure how it can be resolved.

**Comment by Ladicek** [comment] 2021-08-03 10:48
Multiple containers, 2 containers to be precise, are totally expected -- 1 is for dev mode, 1 for test.

**Comment by Ladicek** [comment] 2021-08-03 10:49
Oh and @ozangunalp is right, I have also seen serde autodetection not re-running, but I have _no idea_ why is that :-)

**Comment by edeandrea** [comment] 2021-08-03 11:31
> I think this may be fixed upstream, can you try with the main branch?

I'd be happy to try if you can explain to me (or point me to documentation) how to compile `main` and link a project to it.

**Comment by edeandrea** [comment] 2021-08-03 20:49
I understand there should be multiple containers running (one for dev one for test) but should they both be exposed to the host on the same port(s) (i.e. 9092 and 9644)?

**Comment by Ladicek** [comment] 2021-08-04 07:28
I got a notification for comment "I understand there should be multiple containers running (one for dev one for test) but should they both be exposed to the host on the same port(s) (i.e. 9092 and 9644)?", which seems to be gone now -- and I think for good reason :-)

So just for future reference: in `docker ps` output (such as `0.0.0.0:55076->9092/tcp, :::55076->9092/tcp, 0.0.0.0:55075->9644/tcp, :::55075->9644/tcp` in this case), the thing _before_ `->` is host port, and in-container port is _after_ `->`. So the dev services containers are exposed on randomly assigned ports on the host, there's no collision.

**Comment by Ladicek** [comment] 2021-08-04 07:29
@edeandrea Here's how to test against the `main` branch: https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#checking-an-issue-is-fixed-in-main

**Comment by edeandrea** [comment] 2021-08-04 11:31
> I got a notification for comment "I understand there should be multiple containers running (one for dev one for test) but should they both be exposed to the host on the same port(s) (i.e. 9092 and 9644)?", which seems to be gone now -- and I think for good reason :-)

Yeah I realized just after posting that I was mis-reading it, so I deleted the comment :)

**Comment by edeandrea** [comment] 2021-08-09 14:33
@stuartwdouglas / @Ladicek 

I made a few changes to the application. I realized I was using RESTEasy Reactive but my tests were using the blocking client and not the reactive one.

### Additions to `pom.xml` (replacing what was mentioned above in initial summary)
```xml
<dependency>
  <groupId>org.assertj</groupId>
  <artifactId>assertj-core</artifactId>
  <scope>test</scope>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jaxrs-client-reactive</artifactId>
  <scope>test</scope>
</dependency>
```

### Completed `PriceResourceTests.java` (replacing what was mentioned above in initial summary)
```java
@QuarkusTest
class PriceResourceTest {
  @TestHTTPEndpoint(PriceResource.class)
  @TestHTTPResource("/stream")
  URI uri;

  @Test
  public void sseEventStream() {
    List<Double> received = ClientBuilder.newClient()
      .target(this.uri)
      .request(MediaType.SERVER_SENT_EVENTS)
      .rx(MultiInvoker.class)
      .get(Double.class)
      .select().first(3)
      .subscribe().withSubscriber(AssertSubscriber.create(3))
      .assertSubscribed()
      .awaitItems(3, Duration.ofSeconds(20))
      .assertCompleted()
      .getItems();

  assertThat(received)
    .hasSize(3)
    .allMatch(value -> (value >= 0) && (value < 100));
  }
}
```

I verified all the scenarios still do not work with Quarkus `2.1.1.Final`. I then tried the [Using Snapshots](https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#using-snapshots) to use the latest Quarkus snapshot.

After re-testing, all the scenarios pass! Does this mean that this will be fixed in Quarkus `2.2`? Or will it be rolled into a Quarkus `2.1.x` maintenance release? It does not work in Quarkus `2.1.1.Final`.

**Comment by Ladicek** [comment] 2021-08-09 15:19
If it's fixed in `main`, it will be fixed in 2.2 for sure. I don't know which PR fixed this, so no idea if it's marked for backport to 2.1. (If there ever is another 2.1 release.)

**Comment by edeandrea** [comment] 2021-08-09 15:23
Sounds good @Ladicek - let me leave this open then until 2.2 is out and I'll re-test and make sure. If everything is good I'll close it then. Sound ok?

**Comment by gsmet** [comment] 2021-08-09 15:44
There will be another 2.1. For now, I have planned to include these fixes: https://github.com/quarkusio/quarkus/pull/19306 . Could you check how it goes with my backport branch?

**Comment by edeandrea** [comment] 2021-08-09 15:48
@gsmet If you can tell me how I test locally with that branch then sure I can test with it. I assume it would be similar to https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#building-main? That section though, after building Quarkus doesn't mention how I configure my project to use those artifacts that I just built. Does it install the artifacts in my local maven repo under the `999-SNAPSHOT` version?

**Comment by gsmet** [comment] 2021-08-09 15:53
@edeandrea yes exactly!

**Comment by edeandrea** [comment] 2021-08-09 15:54
Is that branch (`gsmet:2.1.2-backports-1`) ready now to test? Or do you want to let me know when you'd like me to test?

**Comment by gsmet** [comment] 2021-08-09 15:58
Yes please have a look at it now. Since we have no idea what fixed your issue, starting with the things I will backport sounds like a good idea.

**Comment by edeandrea** [comment] 2021-08-09 16:03
Running the Quarkus build now. I have to step out for a bit but will report back by the end of the day.

**Comment by edeandrea** [comment] 2021-08-09 17:09
One thing I noticed when I start dev mode is

```shell
WARN  [io.qua.con.build] (main) Using @ConfigProperty for Quarkus configuration items is deprecated (use @ConfigItem instead) at io.quarkus.smallrye.reactivemessaging.kafka.ReactiveMessagingKafkaConfig#enableGracefulShutdownInDevAndTestMode
```

Testing with building from @gsmet 's backport branch: Scenario 3 works fine but Scenarios 1, 2, & 4 are still broken.

**Comment by stuartwdouglas** [comment] 2021-08-10 04:36
It is likely due to https://github.com/quarkusio/quarkus/pull/19075

This is a relatively large PR so I did not mark it for backport, but it might be worth it if it fixes this issue.

**Comment by edeandrea** [comment] 2021-08-10 11:50
@stuartwdouglas / @gsmet I can retest with that PR branch today if you'd like.

**Comment by stuartwdouglas** [comment] 2021-08-11 00:06
That would be helpful.

**Comment by edeandrea** [comment] 2021-08-11 20:04
@stuartwdouglas I'm not able to build that PR branch. I've tried twice now and it keeps failing:

```
[INFO] Quarkus - Integration Tests - Redis DevService ..... SUCCESS [  0.940 s]
[INFO] Quarkus - Integration Tests - gRPC - TLS ........... SUCCESS [  4.754 s]
[INFO] Quarkus - Integration Tests - gRPC - Plain Text with gzip compression SUCCESS [  5.384 s]
[INFO] Quarkus - Integration Tests - gRPC - Plain Text with Mutiny SUCCESS [  4.340 s]
[INFO] Quarkus - Integration Tests - gRPC - TLS with mutual auth SUCCESS [  3.549 s]
[INFO] Quarkus - Integration Tests - gRPC - Streaming ..... FAILURE [  2.533 s]
[INFO] Quarkus - Integration Tests - gRPC - Interceptors .. SKIPPED
[INFO] Quarkus - Integration Tests - gRPC - Proto v2 ...... SKIPPED
[INFO] Quarkus - Integration Tests - gRPC - Health ........ SKIPPED
[INFO] Quarkus - Integration Tests - gRPC - Hibernate ..... SKIPPED
[INFO] Quarkus - Integration Tests - gRPC - Hibernate Reactive SKIPPED
[INFO] Quarkus - Integration Tests - Google Cloud Functions HTTP SKIPPED
[INFO] Quarkus - Integration Tests - Google Cloud Function  SKIPPED
[INFO] Quarkus - Documentation ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  27:03 min
[INFO] Finished at: 2021-08-11T16:03:22-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:generate-code (default) on project quarkus-integration-test-grpc-streaming: Quarkus code generation phase has failed: InvocationTargetException: Failed to generate Java classes from proto files: [/Users/edeandre/workspaces/quarkus/quarkus/integration-tests/grpc-streaming/src/main/proto/streaming.proto] to /Users/edeandre/workspaces/quarkus/quarkus/integration-tests/grpc-streaming/target/generated-sources/grpc -> [Help 1]
```

**Comment by edeandrea** [comment] 2021-08-11 22:48
I'd say then let's keep this open until 2.2 is out. Once it's out I'll re-test and then close it if everything is good.

**Comment by stuartwdouglas** [comment] 2021-08-11 23:09
If you have already confirmed it worked with main then we should be able to close it now, we generally close when the fix is in not at release time.

**Comment by stuartwdouglas** [comment] 2021-08-11 23:10
I guess we should add a test for this, then we can call it closed.

**Comment by stuartwdouglas** [comment] 2021-08-12 00:56
The linked PR contains tests for scenarios 1-3. I don't think it is worth worrying about 4, it's conceptually the same as 3.

**Closed** 2021-08-12 08:02 UTC
Labels: kind/bug, area/kafka, area/devservices, area/continuous-testing
