### ISSUE TITLE
SmallRye Reactive Messaging - readiness check fails intermittently with Event hubs

### ISSUE THREAD

**Issue by ManishJain-TomTom** [quarkusio/quarkus#25650] opened 2022-05-18 09:59 UTC
### Describe the bug

In our application, we have 2 methods that write to the same topic. Initially we tried to use the same channel for both these methods, but then realised that the same channel can't be used with @Outgoing and Emitter. To fix the issue, we have created 2 channels, one that is used with @Outgoing, and another one which is used with Emitter. Both of these have same topics configured.

First connector:
`mp.messaging.outgoing.outbound.connector=smallrye-kafka

mp.messaging.outgoing.outbound.topic=topic
`

Second connector:
`
mp.messaging.outgoing.outbound2.connector=smallrye-kafka

mp.messaging.outgoing.outbound2.topic=topic
`
This setup has been running fine with when we use it with Kafka. However, when we use the same setup with Azure Event hubs, we keep getting readiness check errors intermittently. The service will start fine, and work for a day or two, and then we will start seeing service down messages. 

Error Message:
`Reporting health down status: {"status":"DOWN","checks":[{"name":"SmallRye Reactive Messaging - readiness check","status":"DOWN","data":{"inbound":"[OK]","outbound":"[KO]","outbound2":"[OK]"}}]}`

Since both the connectors and essentially connecting to same topic, either both outbound and outbound2 should be down, or both should work fine. But as can be seen in the message, only one of the connector fails, and the other one works fine.

### Expected behavior

If Event Hub is down, then all 3 connectors should fail. inbound, outbound and outbound2.

If topic for outbound is down, both outbound and outbounds2 connectors should fail.

If nothing is down, all 3 connectors should work fine.

### Actual behavior

Intermittently, we get error that outbound or outbound2 connector is down, and the remaining connectors are up.

### How to Reproduce?

Reproducer:

Since it's an intermittent issue, it will require an application to be deployed for couple of days for replication.

1. Create an Event Hub Namespace in Azure.
2. Create one Event hub in the namespace.
3. Configure quarkus app to use this event hub (topic) in 2 connectors.
4. Use @Outgoing with one connector and emitter with second connector.
5. Keep the application running for a few days.

### Quarkus version or git rev

1.10.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by ozangunalp** [comment] 2022-05-18 11:16
The default readiness check for an outgoing Kafka channel looks if the connection-count metric of the underlying Kafka producer is at least 1. So that would mean for some reason the connection is intermittently cut. Can you correlate that to the active connections metric from the Azure event hubs ?

**Comment by ManishJain-TomTom** [comment] 2022-05-18 11:24
![image](https://user-images.githubusercontent.com/100848347/169027716-f23ed5a6-e66d-453e-ab67-4804b0276c45.png)

Active connections look fine to me. This is the last 7 days chart. I can see similar chart for 48 hrs and 30 days.

**Comment by ozangunalp** [comment] 2022-05-18 14:35
The sawtooth pattern suggests that some connections keep dropping and coming back up.
You can try looking at `connections.max.idle.ms` and `metadata.max.age.ms` on producer channels. 
I remember that Event Hubs close inbound connections that are idle for a certain amount of time.

BTW instead of the active connections metric you can use the topic verification method for readiness checks, or disable readiness: https://smallrye.io/smallrye-reactive-messaging/3.16.0/kafka/health/

**Comment by ozangunalp** [comment] 2022-05-18 14:36
Here maybe this will help for adjusting kafka client configurations : https://docs.microsoft.com/en-us/azure/event-hubs/apache-kafka-configurations

**Comment by ManishJain-TomTom** [comment] 2022-05-19 06:16
Hi @ozangunalp , 

Thanks for sharing these details. After checking the configuration of the application, I found that **connections.max.idle.ms** was set to **540000**, which was beyond the allowed value for azure event hubs (<240000 permitted value). I've set it to **180000** now and will check if that fixes the issue.

I also found that metadata.max.age.ms was not set, so have set it to **180000**.

Let's say that the channel is idle for a certain time and hence the connection is closed. What happens if a message comes after the connection has been closed? Should a new connection not be created to send the relevant message? Is there a way I can configure that so that this doesn't happen?

The problem is not just with the health metrics, the problem is that once these logs start coming, no messages are sent to the event hub. And from our upstream system, we can see that thousands of messages are coming per minute. Hence were expecting that even if the connection drops for a while, then it should be recovered and even if we miss a few messages, other messages should go through and be processed.

**Comment by ManishJain-TomTom** [comment] 2022-06-10 08:42
Hi @ozangunalp ,

Tried with these settings, the app works fine for 5-6 days and then again start giving System down error. When app is restarted, connection gets established. Which means the EH is working fine. But not sure why the problem with the app is happening.

**Comment by cescoffier** [comment] 2023-02-06 13:26
Any update?

**Comment by cescoffier** [comment] 2024-08-21 13:49
Closing - no feedback. 

Unfortunately, we couldn't reproduce it. Please re-open with a reproducer we can use.

**Closed by cescoffier** 2024-08-21 13:49 UTC
Labels: kind/bug, area/smallrye, area/reactive-messaging
