### ISSUE TITLE
Error when starting the default Oracle container for development

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#23846] opened 2022-02-21 19:42 UTC
If the configuration doesn't specify the URL:
```
quarkus:
  datasource:
    jdbc: false
    db-kind: oracle
    username:
    password:
    reactive:
      url:

  hibernate-orm:
    database:
      generation: drop-and-create
    log:
      sql: true
```

when starting quarkus, the following error occurs:
```
Caused by: java.lang.IllegalArgumentException: Cannot parse invalid connection URI: oracle:thin:@localhost:49494/quarkusdb
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:54)
	at io.vertx.oracleclient.impl.OracleConnectionUriParser.parse(OracleConnectionUriParser.java:40)
	at io.vertx.oracleclient.OracleConnectOptions.fromUri(OracleConnectOptions.java:54)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.toOracleConnectOptions(OraclePoolRecorder.java:93)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.initialize(OraclePoolRecorder.java:56)
	at io.quarkus.reactive.oracle.client.runtime.OraclePoolRecorder.configureOraclePool(OraclePoolRecorder.java:38)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ReactiveOracleClientProcessor$build2113975005.deploy(Unknown Source)
	... 74 more
```

The reason is that the url should be:
```
oracle:thin:@localhost:49494:quarkusdb
```

I have a reproducer here: https://github.com/DavideD/hibernate-reproducer/tree/oracle-issue

The exception will happen with:
```
./gradlew quarkusDev
```

**Comment by LazaroR94** [comment] 2022-02-21 19:52
Good catch as this is exactly what happened to me when I sent you the reproducer (hence why I didn't add much to the **application.yml**).

**Comment by gsmet** [comment] 2022-02-22 20:15
My understanding is that it's a bug in the reactive Oracle client.
The URL formats for Oracle can be:
- `jdbc:oracle:thin:@<hostName>:<portNumber>:<sid>`  (if you have sid)
- `jdbc:oracle:thin:@//<hostName>:<portNumber>/serviceName` (if you have oracle service name)

according to https://stackoverflow.com/questions/1054105/url-string-format-for-connecting-to-oracle-database-with-jdbc .

And only `:sid` is handled in the reactive Oracle client here: https://github.com/eclipse-vertx/vertx-sql-client/blob/master/vertx-oracle-client/src/main/java/io/vertx/oracleclient/impl/OracleConnectionUriParser.java#L28 

We might be able to work around it as apparently we use `:` if we have a shared network but I'm not sure how it would work for JDBC and Testcontainers use the `/` variant if it doesn't use the SID - which has the fixed value of `xe` so I really think a `/` is the way to go in our case.

I would rather fix the reactive Oracle client and use a `/` consistently for the URL in the `OracleDevServicesProcessor`.

/cc @tsegismont WDYT?

**Comment by tsegismont** [comment] 2022-02-28 10:30
@gsmet indeed, we need to update the reactive Oracle client to support more connection url formats. I will work on it.

**Comment by tsegismont** [comment] 2022-03-03 18:16
@gsmet there is a fix in Vert.x 4.2 branch https://github.com/eclipse-vertx/vertx-sql-client/commit/a7edd75d3161d745ff8bdfce129816782b9aa01d

After Quarkus has upgraded to Vert.x 4.2.6, we can test again and, if it goes well, close this issue.

**Comment by tsegismont** [comment] 2022-03-24 14:51
@cescoffier is the upgrade to `4.2.6` planned?

**Comment by cescoffier** [comment] 2022-03-24 14:55
Yes, but not soon soon. Not in 2.8 typically. 2.9 definitely.

**Comment by tsegismont** [comment] 2022-03-25 14:06
Thanks, @cescoffier

**Comment by tsegismont** [comment] 2022-03-25 14:08
@DavideD can you confirm the issue is resolved in `main` branch? It should be fixed now: https://github.com/quarkusio/quarkus/commit/0dbc247b7c010ebc2f729abf263bd00b7fb2c057

**Comment by DavideD** [comment] 2022-03-25 16:21
I'm checking

**Closed** 2022-03-25 19:55 UTC
Labels: kind/bug, triage/needs-triage
