### ISSUE TITLE
Using square brackets in url causes URISyntaxException

### ISSUE THREAD

**Issue by imzahahs** [quarkusio/quarkus#10177] opened 2020-06-23 02:52 UTC
**Describe the bug**
Sending square brackets `[` or `]` for any url results in Internal Server Error page. Other symbols seem to work fine. Problem happens on deployed container as well, an error page is shown and `ExceptionMapper<Throwable>` is not honored. :/

**Expected behavior**
Should be handled as 404 instead

**Actual behavior**
HTTP 500 received with the following stacktrace.

```
Internal Server Error
Error handling efe66235-e299-4cbf-9a06-45a0f6c6c21d-5, java.lang.NullPointerException:
Click Here to see the stacktrace in reversed order (root-cause first)

java.lang.NullPointerException
	at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:116)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```

**To Reproduce**
1.  Use square brackets in url [ ], e.g: `http://localhost:8080/v1/c/schemas/asmlco]nfig2`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Microsoft Windows [Version 10.0.18362.900]`
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
```
 - Quarkus version or git rev: `1.5.1.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Users\someguy233\.m2\wrapper\dists\apache-maven-3.6.3-bin\1iopthnavndlasol9gbrbg6bf2\apache-maven-3.6.3
Java version: 11.0.7, vendor: GraalVM Community, runtime: E:\proj04_base\graalvm\graalvm-ce-java11-20.1.0
Default locale: en_MY, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by stuartwdouglas** [comment] 2020-06-23 03:37
I could not reproduce this locally. Are you using proxy address forwarding by any chance?

**Comment by imzahahs** [comment] 2020-06-23 06:17
Hmm not that I'm aware of, I was able to reproduce it with a fresh Quarkus project from https://code.quarkus.io/. No additional changes, just run it and go to `http://localhost:8080/he[llo`

Here's an additional stacktrace from console:

```
2020-06-23 14:00:57,141 SEVERE [io.ver.cor.htt.imp.HttpServerRequestImpl] (executor-thread-1) Failed to create abs uri: java.net.URISyntaxException: Illegal character in path at index 3: /he[llo
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3084)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3166)
	at java.base/java.net.URI$Parser.parse(URI.java:3125)
	at java.base/java.net.URI.<init>(URI.java:600)
	at io.vertx.core.http.impl.HttpUtils.absoluteURI(HttpUtils.java:366)
	at io.vertx.core.http.impl.HttpServerRequestImpl.absoluteURI(HttpServerRequestImpl.java:370)
	at io.quarkus.vertx.http.runtime.AbstractRequestWrapper.absoluteURI(AbstractRequestWrapper.java:156)
	at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:210)
	at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:31)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:116)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:37)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:94)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
```
I tried using Oracle JDK 11, GraalVM Java 11 and Adopt OpenJDK 11. Same results.

**Comment by famod** [comment] 2020-06-28 22:02
I can reproduce this with https://github.com/quarkusio/quarkus-quickstarts/tree/master/getting-started

Since the root cause (`URISyntaxException`) is thrown by the JDK, I am asking myself whether brackets are actually "valid".
Might be interesting in this context:
- https://stackoverflow.com/a/13500078/9529981
- https://stackoverflow.com/questions/11038967/brackets-in-a-request-url-are-legal-but-not-in-a-uri-java#comment31519183_11040308

**Comment by jaikiran** [comment] 2020-07-04 14:11
This is actually a bug in vertx. I have created https://github.com/vert-x3/vertx-web/issues/1654

**Comment by geoand** [comment] 2023-04-11 11:17
This seems to have been fixed in Vert.x, so I'll close this

**Closed by geoand** 2023-04-11 11:17 UTC
Labels: kind/bug
