### ISSUE TITLE
Quarkus shows warning messages for properties that are actually used but not part of config classes

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5980] opened 2019-12-06 10:32 UTC
**Describe the bug**
It seems like the big config PR removed he list of false positives keys that wouldn't trigger a warning when set.

**Expected behavior**
Setting `-Dquarkus.profile` (as is mentioned for example [here](https://quarkus.io/guides/config#configuration-profiles)) should not trigger the logging of any warning.

**Actual behavior**
Setting `-Dquarkus.profile` yields:

```
2019-12-06 11:48:32,749 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.profile" was provided; it will be ignored
```

**To Reproduce**
1. Use any of the Quarkus quickstarts (from the `development` branch).
2. Build
3. Run with `-Dquarkus.profile` set

**Comment by geoand** [comment] 2019-12-06 10:33
cc @dmlloyd

**Comment by gastaldi** [comment] 2019-12-06 10:59
Duplicate of https://github.com/quarkusio/quarkus/issues/5855?

**Comment by geoand** [comment] 2019-12-06 11:00
Yes it is. Although I'm pretty certain that it's not a `Good first issue` :), that is unless I missed something

**Comment by gastaldi** [comment] 2019-12-06 11:05
According to @stuartwdouglas, the fix is to create a Config object for the missing properties, that's why I marked as a good first issue :)

**Comment by geoand** [comment] 2019-12-06 11:06
That works for sure. But there are plenty of properties that need to be ignored: https://github.com/quarkusio/quarkus/blob/1.0.1.Final/core/deployment/src/main/java/io/quarkus/deployment/configuration/ConfigDefinition.java#L70

so I'm not sure if adding all those Config objects is the right way to go.

**Comment by gsmet** [comment] 2019-12-06 11:30
I think it's OK to create a proper config for these. @gastaldi did you plan to work on it? I think we need it for CR so basically today.

If nobody's working on it, I'll do it.

**Comment by gastaldi** [comment] 2019-12-06 11:31
> did you plan to work on it?

Nope, I'll leave the fun for you this time ;)

**Comment by geoand** [comment] 2019-12-06 11:31
Having Config objects still won't solve the problem for `quarkus.profile` and `quarkus.version`

**Comment by gsmet** [comment] 2019-12-06 11:33
@geoand why?

**Comment by geoand** [comment] 2019-12-06 11:36
What Config object would you use to capture `quarkus.profile`? I guess there is some fundamental piece I am missing :)

**Comment by gsmet** [comment] 2019-12-06 11:47
Hum. That's a good question.

Maybe a config root called `profile` and then a config item with a `ConfigItem#PARENT` name would work.

@dmlloyd is there a cleaner trick we could use? If at some point we want to add a `quarkus.locales` thing, it might be nice to have a proper config root with all these root properties.

**Comment by geoand** [comment] 2019-12-06 12:07
The old exclude list also had `quarkus.version`

**Comment by machi1990** [comment] 2019-12-06 12:44
The good thing with having a config root handling these false unknowns is that they'll be properly documented with the generated documentation.

**Comment by dmlloyd** [comment] 2019-12-06 13:55
For root properties, either create a group and use the parent name like suggested above, or else we could enhance the config parser to support empty root names.  Either way isn't too hard.

**Comment by geoand** [comment] 2019-12-06 13:59
The second solution seems more intuitive to me.

**Comment by dmlloyd** [comment] 2019-12-06 14:01
I'll have a patch ready in moments ;)

**Comment by geoand** [comment] 2019-12-06 14:02
:100:

**Comment by geoand** [comment] 2019-12-06 15:10
Who wants to take this after #5989 is in? If no one wants to, I can do it

**Closed** 2019-12-07 23:07 UTC
Labels: bug, component:config
