### ISSUE TITLE
Cannot exclude Application class in dev mode

### ISSUE THREAD

**Issue by mweber03** [quarkusio/quarkus#18205] opened 2021-06-28 14:14 UTC
## Describe the bug
I have a service that with `quarkusDev` dependencies on other service projects for the purpose of dev mode only. I knew there would be collisions on the `Application` classes, so I added the `Application` class fro mthe dependency to `quarkus.arc.exclude-types`. But it does not seem to be excluded because I get an error saying there is more than one `Application` class.

### Expected behavior
Quarkus dev mode to work.

### Actual behavior
`RuntimeException: More than one Application class: [my.project.service1.Service1Application,my.project.service1.Service1Application,my.project.service3.Service3Application]`

## To Reproduce

`service3` in https://github.com/mweber03/quarkus-test

1.  `./gradlew build service3:quarkusDev`

### Configuration
build.gradle
```groovy
dependencies {
    quarkusDev project('service1')
}
```

application.properties
```properties
quarkus.arc.exclude-types=my.project.service1.Service1Application
```

### Output of `uname -a` or `ver`
Ubuntu 20.04

### Output of `java -version`
OpenJDK 11.0.11

### Quarkus version or git rev
Quarkus 1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.8.3

**Comment by mkouba** [comment] 2021-06-30 06:36
@mweber03 I suppose that you're talking about `javax.ws.rs.core.Application`, right? If so, then `quarkus.arc.exclude-types` would not help here because this property only affects the bean discovery and not processing of JAX-RS components. In other words, the application class is excluded from the bean discovery but the resteasy extension registers the class as a regular POJO. @geoand I'm not sure whether `resteasy-reactive` handles this use case differently?

**Comment by stuartwdouglas** [comment] 2021-07-01 02:05
We could probably add a config property to select the application class.

**Comment by mweber03** [comment] 2021-07-06 16:11
@stuartwdouglas I think that's a great idea.

**Comment by stuartwdouglas** [comment] 2021-07-15 06:58
There is something that should work for you that is now merged: https://github.com/stuartwdouglas/quarkus/commit/54af257ec4b1a101669554744b6452fcfa3f4540

It's not JAX-RS specific, but can be used to remove resources from dependencies. An example is shown below:

```
quarkus.class-loading.removed-resources."io.quarkus\:quarkus-integration-test-shared-library"=io/quarkus/it/shared/RemovedResource.class
```

If you replace the `io.quarkus\:quarkus-integration-test-shared-library` with your group:artifact and the class file name with the application class you should be able to ignore it.

**Comment by geoand** [comment] 2022-01-25 09:51
Closing as we already have a solution for this and this is also sort of a duplicate of https://github.com/quarkusio/quarkus/issues/18725

**Closed by geoand** 2022-01-25 09:51 UTC
Labels: kind/bug, area/devmode, area/resteasy, area/resteasy-reactive
