### ISSUE TITLE
JavaFX extension

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#9313] opened 2020-05-14 22:02 UTC
**Describe the extension**
As discussed on [Quarkus Insights](https://youtu.be/5UhM_W6zukg?list=PLsM3ZE5tGAVatO65JIxgskQh-OKoqM4F2&t=1041) with command mode we now can work with swing/javafx but we should have an extension to enable CDI injection in the UI eventqueues.

This one is for JavaFX and in this world [Gluon Ignite](https://gluonhq.com/labs/ignite/) seem to be the popular option.

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Comment by geoand** [comment] 2020-05-19 12:40
Seems that JavaFX does work in native mode: https://gluonhq.com/native-windows-applications-using-gluon-substrate-javafx-and-graalvm/

**Comment by maxandersen** [comment] 2020-05-19 19:21
Yes. This issue is about having cdi injection between javafx models / controllers.

**Comment by geoand** [comment] 2020-05-19 19:27
👍

I would love to look into it, but I dont know when I'll be able to...

**Comment by geoand** [comment] 2020-05-19 19:32
Although it might be really easy, won't really know until / unless I look into it

**Comment by geoand** [comment] 2020-05-26 12:40
I removed the `good first issue` because of the following:

1) We need to be able to have JavaFX controllers be CDI beans, otherwise the experience would be bad
2) We should provide an easy way for a user to create a JavaFX application, perhaps an annotation like `@QuarkusJavaFXApplication` or a `QuarkusJavaFXApplication` interface. This would allow Quarkus to hide all the boilerplate code needed to make JavaFX and Quarkus play nicely together

**Comment by starksm64** [comment] 2020-05-26 13:26
Another issue is the use of FXML and how the FXMLLoader uses reflection on the generated CDI controller proxies if the controller is not using Dependent scoping. Ideally a CDI aware FXMLLoader would be produced that does not use reflection, but it did not look possible to do with a simple subclass of FXMLLoader given the current architecture.

**Comment by johanvos** [comment] 2020-06-11 13:54
FXML strongly depends on reflection, but I am very open to discuss how we can avoid this (without breaking the top-level API). I agree CDI would be interesting here.

**Comment by jmartisk** [comment] 2020-09-22 10:42
I've been investigating this a little bit..
IIUC we'd also need to somehow integrate Gluon Substrate into our Maven plugin that builds native images, without it I suppose we won't be able to build native images.
And one more problem will be with dev mode, where the application potentially gets booted multiple times in the same JVM, which is something that JavaFX protects itself against

**Comment by Christopher-Chianelli** [comment] 2020-11-25 04:08
For FXML, I think we could generate a custom implementation of FXMLLoader. We would need to generate custom classes for all fxml files, and the FXMLLoader simple construct instances of the generated class for the corresponding FXML files. There is the issue that FXMLLoader can load via an InputStream, so we would need to keep the entire fxml file in memory so we can map the input stream to an instance.

**Comment by pedrolopix** [comment] 2021-01-30 01:57
I created a simple demo with minimal implementation, see https://github.com/pedrolopix/quarkus-javafx-example

**Comment by maxandersen** [comment] 2021-01-30 05:58
Nice @pedrolopix !

**Comment by maxandersen** [comment] 2021-01-30 08:02
Haven't been at laptop where I can run it but from reading code I assume this is only jvm mode and injection is not happening in the jfx application side - correct ?

**Comment by pedrolopix** [comment] 2021-01-30 11:55
Yes it's correct, it's only jvm mode and no injection in jfx side. It's only a simple example, better than nothing :)

**Comment by maxandersen** [comment] 2021-01-30 14:21
Definitely! Very appreciated.

**Comment by nham-xuan-thanh** [comment] 2021-02-06 10:29
Nice @pedrolopix ! But I can't debug, when click button it throw null pointer!
Any solution for debug, thanks!

**Comment by pedrolopix** [comment] 2021-02-06 12:46
Just open the pom.xml in intellij as a project, then start CDIApplication.main as a debug, it should work.

**Comment by nham-xuan-thanh** [comment] 2021-02-06 15:22
Perfect @pedrolopix ! Many thanks !!!

**Comment by pedrolopix** [comment] 2021-09-25 16:24
Just bumped the demo project to latest versions and work fine

**Comment by ennishol** [comment] 2021-09-27 08:40
@pedrolopix  I pulled your changes and get the same error when pressing 'Click' button with `mvn quarkus:dev`:
```
Exception in thread "JavaFX Application Thread" 
                                               java.lang.InternalError: bouncer cannot be found
...
Caused by: java.lang.NullPointerException: Cannot invoke "java.lang.Class.getDeclaredMethod(String, java.lang.Class[])" because "<local1>" is null
	at com.sun.javafx.reflect.MethodUtil$1.run(MethodUtil.java:306)
	at com.sun.javafx.reflect.MethodUtil$1.run(MethodUtil.java:300)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:569)
	at com.sun.javafx.reflect.MethodUtil.getTrampoline(MethodUtil.java:299)
	... 49 more

```

**Comment by jdbranham** [comment] 2023-01-14 16:23
I used a similar approach but required a vm option for the maven javafx plugin.  
I don't know if it's the same root cause as @ennishol issue, but it might help.  

https://github.com/pedrolopix/quarkus-javafx-example/pull/3

**Comment by moamenhredeen** [comment] 2023-10-23 19:58
any update here ? 
i tried to do something similar using micronaut.
the problem is (as you all already said) the FXMLLoader. 
the FXMLLoader relay heavly on reflection. 
i would love to help with writing quarkus extension for javafx.

**Comment by maxandersen** [comment] 2023-10-24 05:37
@moamenhredeen I haven't had time to look deeper. If you want to help go try and make JavaFX based example and see how far you get. As mentioned above running JavaFX in quarkus app is all doable as it is "just java" - what needs solving is how we get Arc dependency injection happening in a JavaFX app.

**Comment by MarceloRuiz** [comment] 2023-11-01 14:59
I would be great to have Quarkus able to run JavaFX applications.
I don't know if this could be relevant, but the following project got it working based on CDI version 2. It might help to give an idea of how the solution could be implemented:

[https://github.com/cgiesche/javafx-cdi-bootstrap](javafx-cdi-bootstrap)

**Comment by maxandersen** [comment] 2023-11-27 16:34
Very cool. Will give it a try!

**Comment by CodeSimcoe** [comment] 2024-01-22 20:35
> Very cool. Will give it a try!

Have you managed to give it a try ?
Any feedback ?

**Comment by maxandersen** [comment] 2024-01-24 22:00
completely fell through the cracks - taking a look now!

**Comment by maxandersen** [comment] 2024-01-24 22:21
I took a look:

1) the project did not build unless I fixed parent version, submitted PR at https://github.com/CodeSimcoe/quarkus-fx-extension/pull/1

2) my javafx skills are rusty so didn't manage to make app work with it. do you have example app that is setup and working (with working pom.xml) ?

3) does it actually work with injection in larger javafx constructs? 

4) the license is currently GPL 3.0 - that isn't a license that we can accept for quarkus/quarkiverse extensions. if you want to contribute it there I encourage you to update/change it to ASL as everything else.

**Comment by CodeSimcoe** [comment] 2024-01-25 00:20
Hello, and thanks.
1. Thanks for this, PR merged
2. You can check https://github.com/CodeSimcoe/quarkus-using-fx-extension
3. Do you have any specific use cases in mind ? I don't why it could not... but let's figure it out.
4. Updated to Apache 2.0

**Comment by hallvard** [comment] 2024-01-26 08:48
I tried the extension and it works well. I'm working on a chatbot langChain4j and coded a simple gui for browsing the internal data. I can use DI as expected to get hold of all chatbot-related objects. There's two general things I miss:
- a custom scope that corresponds to a container/pane, e.g. imagine a tabbed application where each tab is a separate scope
- an annotation to simplify rigging the application, now you need both a quarkus application class and the class that observes the PrimaryStage event. I would be nice if I only needed the latter, with an annotation that provides the former.

**Comment by hallvard** [comment] 2024-01-26 08:49
BTW, I also tried it with jbang, here's a selv contained jbang class that worked for me:

```
//usr/bin/env jbang "$0" "$@" ; exit $?

//DEPS io.quarkus.platform:quarkus-bom:3.6.6@pom
//DEPS org.openjfx:javafx-controls:21.0.1
//DEPS org.openjfx:javafx-fxml:21.0.1
//DEPS com.codesimcoe:quarkus-fx-extension:1.0.0-SNAPSHOT

//JAVAC_OPTIONS -parameters
//JAVA_OPTIONS -Djava.util.logging.manager=org.jboss.logmanager.LogManager

import java.io.ByteArrayInputStream;
import java.util.HashMap;
import java.util.Collection;
import java.util.List;
import java.util.Map;

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.QuarkusApplication;

import jakarta.enterprise.context.Dependent;
import jakarta.enterprise.event.Observes;
import jakarta.inject.Inject;

import javafx.application.Application;
import javafx.application.Platform;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.control.ComboBox;
import javafx.scene.control.ListView;
import javafx.scene.layout.Pane;
import javafx.scene.Scene;
import javafx.stage.Stage;

import com.codesimcoe.quarkus.fx.extension.runtime.FxApplication;
import com.codesimcoe.quarkus.fx.extension.runtime.PrimaryStage;

public class fxgui {

    // run with jbang

    public static void main(String[] args) throws Exception {
        Quarkus.run(runner.class, args);
    }

    public static class runner implements QuarkusApplication {

        @Override
        public int run(String... args) throws Exception {
            Application.launch(FxApplication.class, args);
            return 0;
        }
    }

    public static class FxApplicationDelegate {

        private static String fxml = """
        <?xml version="1.0" encoding="UTF-8"?>

        <?import javafx.scene.control.ComboBox?>
        <?import javafx.scene.control.ListView?>
        <?import javafx.scene.layout.VBox?>
        <?import javafx.scene.layout.HBox?>

        <VBox prefHeight="800" prefWidth="1000" xmlns:fx="http://javafx.com/fxml" fx:controller="%s">
            <ComboBox fx:id="keySelector" onAction="#handleKeySelected"/>
            <ListView fx:id="valuesList"/>
        </VBox>
        """.formatted(FxController.class.getName());

        @Inject
        FXMLLoader fxmlLoader;
    
        public void start(@Observes @PrimaryStage Stage stage) throws java.io.IOException {
            Pane fxmlParent = this.fxmlLoader.load(new ByteArrayInputStream(fxml.getBytes()));

            Scene scene = new Scene(fxmlParent);
            stage.setScene(scene);
            stage.show();
        }
    }

    @Dependent
    public static class FxController {

        @FXML
        ComboBox<String> keySelector;

        @FXML
        ListView<String> valuesList;

        Map<String, Collection<String>> map = Map.of("Norway", List.of("NTNU", "UiO"), "Sweden", List.of("KTH", "Uppsala"));

        @FXML
        void initialize() {
            keySelector.getItems().addAll(map.keySet());
            Platform.runLater(() -> keySelector.setValue("Norway"));
        }

        @FXML
        void handleKeySelected() {
            valuesList.getItems().clear();
            valuesList.getItems().addAll(map.get(keySelector.getSelectionModel().getSelectedItem()));
        }
    }
}
```

**Comment by hallvard** [comment] 2024-01-26 08:51
P.S. It would be super cool to have an FXML string template processor that simplified loading embedded FXML snippets like the one above.

**Comment by CodeSimcoe** [comment] 2024-01-26 19:33
In branch https://github.com/CodeSimcoe/quarkus-fx-extension/tree/fx_startup, the application is automatically started (no more need to redefine the Quarkus main method and call the JavaFx Application::launch.

**Comment by maxandersen** [comment] 2024-01-26 20:33
If You are interested @CodeSimcoe - I Think it would be worth we create a quarkiverse repo to iterate on it. 

Is Quarkus-fx the best name ?


/cc @gastaldi

**Comment by CodeSimcoe** [comment] 2024-01-26 21:00
Let's do this

**Comment by gastaldi** [comment] 2024-01-26 21:12
> Is Quarkus-fx the best name ?

I'd prefer `quarkus-openjfx` or `quarkus-javafx`, as it enables using the `org.openjfx:javafx-fxml` dependency in Quarkus.

Thoughts?

**Comment by CodeSimcoe** [comment] 2024-01-26 21:28
All sound good to me

**Comment by maxandersen** [comment] 2024-01-26 23:23
taking a look at https://github.com/mhrimaz/AwesomeJavaFX I'll say its majority <name>FX so io.quarkiverse.quarkus-fx works - and yeah it will use openjfx:javafx-* dependencies

**Comment by gastaldi** [comment] 2024-01-27 01:33
Repository https://github.com/quarkiverse/quarkus-fx created, welcome aboard @CodeSimcoe!

**Closed** 2024-01-27 01:32 UTC
Labels: kind/extension-proposal

**Comment by CodeSimcoe** [comment] 2024-01-27 08:24
As a start, I've pushed code from my repo, with package update.

**Comment by maxandersen** [comment] 2024-01-28 17:07
Is a property really needed ? Wouldn't a @quarkusmain be sufficient similar how done for command mode/picocli?

**Comment by CodeSimcoe** [comment] 2024-01-28 17:27
> Is a property really needed ? Wouldn't a @quarkusmain be sufficient similar how done for command mode/picocli?

Would be simpler.
Can this have side effects with other extensions ?

**Comment by CodeSimcoe** [comment] 2024-01-29 19:28
> Is a property really needed ? Wouldn't a @quarkusmain be sufficient similar how done for command mode/picocli?

Can you give me some more details on what you could expect ?
I'll be glad to improve

**Comment by CodeSimcoe** [comment] 2024-01-30 10:12
> Is a property really needed ? Wouldn't a @quarkusmain be sufficient similar how done for command mode/picocli?

Just had a look into quarkus-picocli.
I'll make a code proposition soon.

Thanks for the tip.

**Comment by maxandersen** [comment] 2024-01-30 11:14
Excellent :)

**Comment by CodeSimcoe** [comment] 2024-01-30 16:38
> Excellent :)

@maxandersen
https://github.com/quarkiverse/quarkus-fx/pull/5

**Comment by maxandersen** [comment] 2024-01-31 09:14
@CodeSimcoe good - lets open issues on the quarkus-fx repo for future updates.
