### ISSUE TITLE
Env variable "QUARKUS_RESTEASY_PATH" doesn't work, but parameter "-Dquarkus.resteasy.path=" works 

### ISSUE THREAD

**Issue by isikemre** [quarkusio/quarkus#2842] opened 2019-06-14 12:00 UTC
**Describe the bug**
If you want to add a base-path to your JAX-RS Rest Service then it works only with this steps:

- Write `quarkus.resteasy.path=/some-path` into your `application.properties` file. [here on stackoverflow](https://stackoverflow.com/questions/55104574/how-can-i-set-the-base-path-for-my-resteasy-resources-in-quarkus)
- ~~Pass as a java property `-D` parameter like `java -jar application.jar -Dquarkus.resteasy.path=/some-path`~~ **UPDATE: don't work**
- Same as java property with maven. like `mvn clean compile quarkus:dev -Dquarkus.resteasy.path=/some-path`

This 3 options works like a charm.  
**But** if you use Environment variables, like `QUARKUS_RESTEASY_PATH="/some-path" mvn clean compile quarkus:dev`, **it doesn't work**.  
Exporting the env-variable before executing maven `export QUARKUS_RESTEASY_PATH="/some-path"` **it doesn't work**, too.  
If I pass the `QUARKUS_RESTEASY_PATH` environment variable to my quarkus docker container **it doesn't work**, too.

**Expected behavior**
It should (like the quarkus docs, says) take the environment variable into the `application.properties`. Like `QUARKUS_HTTP_PORT` or other properties as env variable.

**Actual behavior**
It doesn't take it.

**To Reproduce**
1. Executing `QUARKUS_RESTEASY_PATH="/file"  mvn clean compile quarkus:dev`
2. 
3. 

**Configuration**
```properties
quarkus.http.port=8090
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Darwin Marss-iMac.local 18.5.0 Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64 x86_64`
 - Output of `java -version`:  `java version "1.8.0_192"
Java(TM) SE Runtime Environment (build 1.8.0_192-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.192-b12, mixed mode)`

 - Quarkus version or git rev: `0.16.1`

**Comment by geoand** [comment] 2019-06-15 12:33
Just curious, does `QUARKUS_RESTEASY_PATH="/some-path" java -jar application.jar` work or is the behavior the same as with the `mvn quarkus:dev`?

**Comment by isikemre** [comment] 2019-06-19 10:47
Sorry for the late response. Yeah, `QUARKUS_RESTEASY_PATH="/some-path" java -jar application.jar` does not work too.

I just found out, that this **don't work**, too:  
`java -Dquarkus.resteasy.path="/some-path" -jar someJar.jar` or `java -jar someJar.jar -Dquarkus.resteasy.path="/some-path"`

Currently only `mvn quarkus:dev` works fine with `-Dquarkus.resteasy.path="/some-path"`

**Comment by geoand** [comment] 2019-06-19 10:55
OK, I see what the issue is, the `ResteasyConfig` by using `@ConfigRoot` implicitly uses `phase() default BUILD_TIME`. That mean that the RESTEasy configuration is build time only and cannot be overriden at runtime. @gsmet is this done on purpose?

**Comment by geoand** [comment] 2019-06-19 13:03
Well it looks like we do generate some build items that depend on it, so I assume this works as expected. Should we close this then?

**Comment by gsmet** [comment] 2019-06-19 13:06
Maybe we could make explicit that the config is build time config? I know it's the default value but explicit won't hurt.

**Comment by geoand** [comment] 2019-06-19 13:08
Yeah, that makes sense

**Comment by isikemre** [comment] 2019-06-19 13:18
So it's working like expected and it is not a bug?

**Comment by gsmet** [comment] 2019-06-19 13:25
Yes, this is a build time config that you can't override at runtime.

It is used during the build.

**Comment by geoand** [comment] 2019-06-19 13:25
It is working as expected. In Quarkus some configuration is build time only, and RESTEasy config is part of it

**Comment by isikemre** [comment] 2019-06-19 13:33
Alright thank you for the awesome help/work. I am gonna close this now!

**Closed** 2019-06-19 13:35 UTC
Labels: bug, component:config
