### ISSUE TITLE
Propagation of contexts

### ISSUE THREAD

**Issue by kenfinnigan** [quarkusio/quarkus#5338] opened 2019-11-08 16:05 UTC
We need to define how, and who propagates any contexts between threads. Contexts could include RESTEasy, CDI, Transaction, Servlet, or anything else.

This is the cause of #4404, and possibly others, but we want to ensure we're propagating in a consistent manner.

**Comment by FroMage** [comment] 2019-11-08 16:16
For Quarkus I vote that it should be automatic, and use MP-CP whenever anything is responsible for creating new threads on which user (or lib) code can run, especially if that code expects contexts to be available.

**Comment by kenfinnigan** [comment] 2019-11-08 16:18
+1, we don't want users needing to remember to propagate things

**Comment by FroMage** [comment] 2019-11-08 16:18
Note that in Quarkus we already have an `ExecutorService` (typed `ManagedExecutor`) provided via CDI, that uses the Quarkus worker pool, but has context propagation turned on. So if you have lib code that spawns threads that require context, they should probably use that service rather than the naked Quarkus worker pool.

**Comment by kenfinnigan** [comment] 2019-11-08 16:19
So maybe we just need hooks in RESTEasy to set that?

**Comment by FroMage** [comment] 2019-11-08 16:23
Maybe, but the fact that `AsyncInvocationInterceptor.prepareContext` exists at all leads me to think that perhaps SR-rest-client is supposed to handle context propagation itself. And the fact that resteasy-client-microprofile has facility to run things async also leads me to think it should _at the very least_ be self-sufficient and propagate at least its own context. We need to discuss those issues.

**Comment by michalszynkiewicz** [comment] 2019-11-08 20:46
I still don't know much about how MP CP works but I agree that it should be possible to create an `AsyncInvocationInterceptor` to pass the context.

(SR-rest-client is now archived and all the development is done in resteasy-client-microprofile now)

**Comment by FroMage** [comment] 2019-12-03 11:02
So, it turns out that this was not really the cause of #4404, and it causes some questions as to which context should be propagated, because we have both a RE client and server context. 

I've added code to fix https://issues.jboss.org/browse/RESTEASY-2401 so that the server context never leaks to the clients.

I'd rather we wait a bit more for user feedback to know if we should propagate the client or request contexts when doing async client calls on a rest end point. Frankly, it's not trivial to judge at this point. My guess is that the server context is the most useful one, though.

ATM users can get CP manually which is probably good enough. I'd rather give this more time to think.

**Comment by stuartwdouglas** [comment] 2020-07-08 01:44
I am closing this, as I think this is now well understood.

**Closed by stuartwdouglas** 2020-07-08 01:44 UTC
Labels: kind/bug
