### ISSUE TITLE
"QUARKUS - GETTING STARTED WITH REACTIVE" creating the project yields wrong project

### ISSUE THREAD

**Issue by morhei** [quarkusio/quarkus#14298] opened 2021-01-14 11:48 UTC
Hi,

I'm currently going through your guide and noticed that when I use the mvn command to create the project I get an unexpected outcome:

`mvn io.quarkus:quarkus-maven-plugin:1.10.5.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started-reactive \
    -DclassName="org.acme.quickstart.ReactiveGreetingResource" \
    -Dpath="/hello" \
    -Dextensions="resteasy-mutiny, resteasy-jackson"`

yields to a project with the following structure:
![image](https://user-images.githubusercontent.com/53338754/104587056-a59b3f80-5666-11eb-9f25-4ef45a8f2331.png)

However, it's expected to have a class named ReactiveGreetingResource in the package org.acme.quickstart

**Comment by ia3andy** [comment] 2021-01-14 12:25
I guess this is a duplicate of this one: https://github.com/quarkusio/quarkus/issues/13917

**Comment by morhei** [comment] 2021-01-14 12:29
Thanks, Indeed that is the exact same behavior I've observed. When omitting resteasy-jackson the outcome was as expected.

**Comment by ia3andy** [comment] 2021-01-14 12:39
Closing as duplicate #13917

**Closed by ia3andy** 2021-01-14 12:39 UTC
Labels: triage/needs-triage
