### ISSUE TITLE
quarkus-jdbc-mssql not working with ActiveDirectoryPassword - MSAL4J Java library Error

### ISSUE THREAD

**Issue by chvsnraju** [quarkusio/quarkus#36142] opened 2023-09-25 15:06 UTC
### Describe the bug

Trying to use Microsoft SQL Server ActiveDirectoryPassword authentication with quarkus-jdbc-mssql  dependency but getting below error

 [com.mic.sql.jdb.int.SQLServerException] (agroal-11) *** SQLException: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryPassword authentication. Failed to load MSAL4J Java library for performing ActiveDirectoryPassword authentication.

I have below dependencies

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>msal4j</artifactId>
      <version>1.13.10</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-mssql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>

When I run a standalone java program, it works fine, the issue is only when I start the Quarkus server and try to call DAO from service. 

When I replace quarkus-jdbc-mssql dependency with the below one, it works fine. Seems when we use quarkus-jdbc-mssql, it is not able to load right MSAL4J, Is anybody aware of this or any help on this?

    <dependency>
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>mssql-jdbc</artifactId>
      <version>12.4.1.jre11</version>
    </dependency>

**Comment by chvsnraju** [comment] 2023-09-25 15:07
Tried with old 2.x version as well as latest 3.4.1, getting the same error

**Comment by geoand** [comment] 2023-09-26 06:10
@yrodiere didn't you recently look into this?

**Comment by yrodiere** [comment] 2023-09-26 06:47
@geoand Looks a bit like #34580 , though the error is clearer here.

@chvsnraju can you please provide the full stacktrace?

**Comment by yrodiere** [comment] 2023-09-26 06:53
And ideally a reproducer :) That way we can try adding an integration test into Quarkus and document this MSSQL + AD stuff once for all.

**Comment by chvsnraju** [comment] 2023-09-26 13:01
@yrodiere  - Here is the full stacktrace, please let me know if need anything else, I am glad to provide any additional details to reproduce this issue

 (executor-thread-1) 37399: com.microsoft.sqlserver.jdbc.SQLServerException: Failed to load MSAL4J Java library for performing ActiveDirectoryPassword authentication.
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.getFedAuthToken(SQLServerConnection.java:5739)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.onFedAuthInfo(SQLServerConnection.java:5715)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.processFedAuthInfo(SQLServerConnection.java:5549)
        at com.microsoft.sqlserver.jdbc.TDSTokenHandler.onFedAuthInfo(tdsparser.java:310)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:130)
        at com.microsoft.sqlserver.jdbc.TDSParser.parse(tdsparser.java:42)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.sendLogon(SQLServerConnection.java:6612)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.logon(SQLServerConnection.java:5154)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection$LogonCommand.doExecute(SQLServerConnection.java:5087)
        at com.microsoft.sqlserver.jdbc.TDSCommand.execute(IOBuffer.java:7675)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.executeCommand(SQLServerConnection.java:4137)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectHelper(SQLServerConnection.java:3583)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.login(SQLServerConnection.java:3172)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connectInternal(SQLServerConnection.java:3014)
        at com.microsoft.sqlserver.jdbc.SQLServerConnection.connect(SQLServerConnection.java:1836)
        at com.microsoft.sqlserver.jdbc.SQLServerDriver.connect(SQLServerDriver.java:1246)
        at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:226)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:536)
        at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:517)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yrodiere** [comment] 2023-09-26 13:08
Ok, so this seems to be the condition that fails unexpectedly:

```
    private boolean msalContextExists() {

        try {
            Class.forName("com.microsoft.aad.msal4j.PublicClientApplication");
        } catch (ClassNotFoundException e) {
            return false;
        }

        return true;
    }
```

I'm guessing that swallowed exception would have more information for us, but, well... it's lost in the process.

> I am glad to provide any additional details to reproduce this issue

@chvsnraju a simple zip or GitHub repo containing a Quarkus project that exhibits this issue would be of great help. Could you please provide that?

**Comment by chvsnraju** [comment] 2023-09-26 13:57
@yrodiere   - This is sample DAO code which is throwing that exception, same error when I inject the datasource as well

import com.microsoft.sqlserver.jdbc.SQLServerDataSource;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import org.jboss.logging.Logger;

import java.sql.Connection;
import java.sql.SQLException;

@ApplicationScoped
public class ActiveDirectoryDBConnect {

    @Inject
    Logger LOG;


    public void testConnect()  {


        SQLServerDataSource ds = new SQLServerDataSource();
        ds.setServerName("xxxxxxxx.database.windows.net");
        ds.setDatabaseName("DB_NAME");
        ds.setUser("USERMAME.onmicrosoft.com");
        ds.setPassword("PASSWORD");
        ds.setAuthentication("ActiveDirectoryPassword");
         try (Connection connection = ds.getConnection();) {

        } catch (SQLException e) {
            LOG.error(  e);
        }

    }
}



These are related pom.xml dependencies, I tested in the latest 3.4.1 and a few other previous versions as well.

    <dependency>
      <groupId>com.microsoft.azure</groupId>
      <artifactId>msal4j</artifactId>
      <version>1.13.10</version>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-mssql</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-agroal</artifactId>
    </dependency>

**Comment by yrodiere** [comment] 2023-09-26 14:11
Thanks. Do you happen to know how to make this test pass once the classpath problem gets solved? I.e. how to set up Active Directory for automated tests (preferably with Docker), how to configure SQL Server to connect to AD, ... ?

**Comment by chvsnraju** [comment] 2023-09-26 15:12
@yrodiere  - Thanks for checking this issue quickly. We are connecting to an externally hosted Microsoft SQL Sever ad AD connection, this server is not part of our application hosting, honestly, I don't know how to configure it. 

However, I can gladly verify from my local for any possible fix.

**Comment by yrodiere** [comment] 2023-09-26 15:23
Ok, that's too bad. The thing is, we'd need a reliable non-regression test, otherwise the fix might break in the next micro and we wouldn't know about it.

I'll have to look for ways to set up AD for integration testing. Hopefully ways that work on Linux...

**Comment by geoand** [comment] 2024-07-03 14:49
Closing as we don't have a reproducer. If one becomes available, we can reexamine the issue.

**Closed by geoand** 2024-07-03 14:49 UTC
Labels: kind/bug, triage/needs-reproducer
