### ISSUE TITLE
Flyway does not work without default datasource 3.3

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#35655] opened 2023-08-31 09:24 UTC
### Describe the bug

We do not have a default data source, since we add them programmatically at runtime. We trigger flyway on our own. Since 3.3 quarkus fails to start with: 

`Error creating synthetic bean [803bdbdea0e23416b5b2639797778edfee1ac6aa]: jakarta.enterprise.inject.UnsatisfiedResolutionException: No datasource present`

I found this issue, maybe the proposed change would although help for this issue, not sure.

https://github.com/quarkusio/quarkus/issues/35528

**Comment by geoand** [comment] 2023-08-31 10:38
It don't think it's the same thing but likely similar. 
Let's wait for the fix @gsmet has cooking for https://github.com/quarkusio/quarkus/issues/35528 before tackling this in order avoid potential conflictss.

**Comment by gsmet** [comment] 2023-09-05 10:50
It would help if we could have the full stacktrace because it's hard to know what the exact issue is.

**Comment by gsmet** [comment] 2023-09-05 10:54
Also, if you could paste your Quarkus config (with the private information redacted), that would be useful.

**Comment by gsmet** [comment] 2023-09-05 10:55
I created https://github.com/quarkusio/quarkus/pull/35732 but I suspect it won't fix this particular issue.

**Comment by robp94** [comment] 2023-09-05 11:10
Stacktrace:
```
2023-09-04 15:07:30.787	
__  ____  __  _____   ___  __ ____  ______ 
2023-09-04 15:07:30.787	
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
2023-09-04 15:07:30.787	
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
2023-09-04 15:07:30.787	
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-09-04 15:07:30.787	
2023-09-04 13:07:30,754 ERROR [io.qua.run.Application] (main) Failed to start application (with profile [prod]): java.lang.RuntimeException: Failed to start quarkus
2023-09-04 15:07:30.787	
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.runtime.Application.start(Application.java:101)
2023-09-04 15:07:30.787	
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:111)
2023-09-04 15:07:30.787	
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
2023-09-04 15:07:30.787	
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
2023-09-04 15:07:30.787	
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
2023-09-04 15:07:30.787	
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
2023-09-04 15:07:30.787	
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-04 15:07:30.787	
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-09-04 15:07:30.787	
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-04 15:07:30.787	
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-09-04 15:07:30.787	
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
2023-09-04 15:07:30.787	
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
2023-09-04 15:07:30.787	
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [803bdbdea0e23416b5b2639797778edfee1ac6aa]: jakarta.enterprise.inject.UnsatisfiedResolutionException: No datasource present
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.doCreate(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.create(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.create(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.get(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.get(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.Instances$3.get(Instances.java:132)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.LazyInstanceHandle.instanceInternal(LazyInstanceHandle.java:32)
2023-09-04 15:07:30.787	
	at io.quarkus.arc.impl.AbstractInstanceHandle.get(AbstractInstanceHandle.java:46)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:96)
2023-09-04 15:07:30.787	
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2035800939.deploy_0(Unknown Source)
2023-09-04 15:07:30.787	
	at io.quarkus.deployment.steps.FlywayProcessor$startActions2035800939.deploy(Unknown Source)
2023-09-04 15:07:30.787	
	... 13 more
2023-09-04 15:07:30.787	
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: No datasource present
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayRecorder$1.apply(FlywayRecorder.java:62)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayRecorder$1.apply(FlywayRecorder.java:57)
2023-09-04 15:07:30.787	
	at io.quarkus.flyway.runtime.FlywayContainer_803bdbdea0e23416b5b2639797778edfee1ac6aa_Synthetic_Bean.createSynthetic(Unknown Source)
2023-09-04 15:07:30.787	
	... 31 more
```

Workaround:
```
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
```

We do not have any config for flyway or data sources in the config, they are created and configured on runtime. Flyway is although triggered on demand and not on startup.

**Comment by gsmet** [comment] 2023-09-05 11:17
That's very odd. Without a datasource, you shouldn't have any Flyway bean around. I'll dig a bit more.

**Comment by gsmet** [comment] 2023-09-05 11:20
Ah wait, I think the dev services will probably be triggered even if you don't have any config.

When you have the problem in dev mode, does Quarkus start a PostgreSQL Docker container? (You have the dev services enabled, right?)

Another question: you do need the workaround in prod mode too? If it's the problem I mentioned above, you shouldn't.

**Comment by robp94** [comment] 2023-09-05 11:50
Actually, I only need it in production and yes, for dev mode we use dev services which fires up a postgres docker container.

**Comment by gsmet** [comment] 2023-09-05 12:59
@robp94 could you assemble a small app reproducing the issue? My time is very limited this week so it would be very helpful if I can reproduce it easily (it might be easy to reproduce but sometimes it takes several back and forth to get things right).

Thanks!

**Comment by gsmet** [comment] 2023-09-05 13:06
Just to log my current line of thinking: I don't understand what triggers the Flyway bean in prod mode as no datasource should be present there and Flyway bean initialization is based on present datasources.
So I need to understand where this datasource is coming from.

**Comment by robp94** [comment] 2023-09-05 13:29
@gsmet sure here is a reproducer.
https://github.com/robp94/quarkus-flyway-statup-failure

**Comment by gsmet** [comment] 2023-09-05 16:05
Thanks for the reproducer, I was able to reproduce the issue and pushed an additional commit to https://github.com/quarkusio/quarkus/pull/35732 .

**Closed** 2023-09-19 11:10 UTC
Labels: kind/bug, area/flyway
