### ISSUE TITLE
ConfigSourceProvider not working with uber-jar in 1.4.1.Final

### ISSUE THREAD

**Issue by crissi98** [quarkusio/quarkus#8906] opened 2020-04-28 08:09 UTC
**Describe the bug**
The Quarkus Build (mvn package) fails when the project is using a ConfigSourceProvider. This only happens when quarkus.package.uber-jar is set to true.

**Expected behavior**
The build should be successful, as in 1.3.2.Final or older

**Actual behavior**
This build fails with the following error message:
```
 Failed to build quarkus application: java.nio.file.FileSystemException: path\to\project\config-service\target\config-service-1.0-SNAPSHOT.jar -> path\to\project\config-service\target\config-service-1.0-SNAPSHOT.jar.original: The process cannot access the file because it is being used by another process.
```

**To Reproduce**
1. Create a Quarkus-Project with version 1.4.1.Final
2. Add another properties-File to src/main/resources (in this example called more.properties)
3. Add the following CustomConfigSourceProvider to the project
```java
import io.smallrye.config.PropertiesConfigSource;
import org.eclipse.microprofile.config.spi.ConfigSource;
import org.eclipse.microprofile.config.spi.ConfigSourceProvider;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

public class CustomConfigSourceProvider implements ConfigSourceProvider {

    @Override
    public Iterable<ConfigSource> getConfigSources(ClassLoader classLoader) {
        List<ConfigSource> configs = new ArrayList<>();
        try {
            configs.add(new PropertiesConfigSource(classLoader.getResource("more.properties")));
        } catch (IOException e) {
            e.printStackTrace();
        }
        return configs;
    }
}
```
4. Add a file called org.eclipse.microprofile.config.spi.ConfigSourceProvider into META-INF\services and put the fully qualified name of the CustomConfigSourceProvider in it
5. Set quarkus.package.uber-jar=true
6. mvn package

**Configuration**
```properties
quarkus.package.uber-jar=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Microsoft Windows [Version 10.0.17763.1098]
 - Output of `java -version`: 
openjdk version "11.0.3-ojdkbuild" 2019-04-16 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.3-ojdkbuild+7-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.3-ojdkbuild+7-LTS, mixed mode)
 - Quarkus version or git rev: 
1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: path\to\maven\apache-maven-3.6.3\bin\..
Java version: 11.0.3-ojdkbuild, vendor: Oracle Corporation, runtime: C:\Program Files\JavaSoft\OpenJDK\11.0.3.7
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
I could recreate the same error with a ConfigSource by using Java 8. An update to Java 11 solved the problem with the ConfigSource, but for the ConfigSourceProvider it is still as described.

**Comment by gsmet** [comment] 2020-04-28 08:25
@jaikiran any chance you could have a look at that one?

**Comment by gsmet** [comment] 2020-04-28 09:50
@crissi98 could you create a simple Maven project reproducing the issue and either attach the zip on GH or point to a GH repository? Thanks!

**Comment by crissi98** [comment] 2020-04-28 10:40
@gsmet No Problem
[config-service.zip](https://github.com/quarkusio/quarkus/files/4545097/config-service.zip)

**Comment by geoand** [comment] 2020-04-28 10:44
I was not able to reproduce this on Linux

**Comment by crissi98** [comment] 2020-04-28 10:53
I also tried it on Mac again and did not get the same error, so it seems to be a Windows specific problem

**Comment by crissi98** [comment] 2020-04-30 07:57
I did some research and I was able to solve the issue.

In #8284 you moved the Jar renaming logic from the JarResultBuildStep to the BuildMojo. I was able to fix the issue by moving it back to the JarResultBuildStep. Here are the changes I made: https://github.com/crissi98/quarkus/tree/windows-uber-jar-lock

Could you have a look at this? I don`t know if you want to use this fix since the intention of this change was to avoid that Jar locking problem on Windows.

**Comment by geoand** [comment] 2020-04-30 11:15
cc @aloubyansky

**Comment by aloubyansky** [comment] 2020-04-30 22:49
Yes, your changes will lead to JAR locking on Windows. I've verified it again on our TS. I am not yet sure why you didn't see it actually. I'll have a look into your reproducer.

**Comment by jaikiran** [comment] 2020-05-01 02:37
Hello @aloubyansky, I'm just curious - from the linked commit:
> I know there is an expectation to have a single JAR in the output dir by some tools, I think it has to be somehow fixed there.

Do you know which tools those are and does that concern still hold? Maybe we can just get rid of this whole renaming of jar files during the build process, if those concerns can be ignored?

**Comment by geoand** [comment] 2020-05-01 04:50
The renaming is done in order to make Openshift s2i work OOTB

**Comment by arielcarrera** [comment] 2020-08-05 18:44
+1 Same problem, in Windows fails and Linux works.

**Comment by unexist** [comment] 2020-08-07 08:15
So apparently, this issue isn't fixed in 1.6.2 and I can confirm it works in 1.3.2, but is broken afterwards.

**Comment by arielcarrera** [comment] 2020-11-07 01:08
This still happens with Windows in version v1.9.2.

**Comment by aloubyansky** [comment] 2020-11-08 16:39
I looked into this again and was able to reproduce it with the reproducer from @crissi98 https://github.com/quarkusio/quarkus/issues/8906#issuecomment-620527339
However, the suggested change https://github.com/quarkusio/quarkus/issues/8906#issuecomment-620527339 that is supposed to fix it, isn't actually fixing it.

The issue is that SmallRye Config is using `java.util.ServiceLoader` which calls `URL.openConnection()` on the JAR and then `URLConnection.getInputStream()` (although it's properly closed) that locks the file until the JVM process terminates.

As a workaround, I would suggest moving service providers to a separate JAR and make the main app module depend on them.

**Comment by hamburml** [comment] 2020-12-09 08:22
Still happens in v1.10.2.

**Comment by radcortez** [comment] 2020-12-10 17:58
This should fix this issue: https://github.com/smallrye/smallrye-config/commit/0391e243e3b07c227a0c33326e0ed48598301aa0.

But, I haven't really tested it against this reproducer, so I'll have a look.

**Comment by hamburml** [comment] 2020-12-10 18:03
If there is a snapshot version I can try it out!

**Comment by radcortez** [comment] 2020-12-10 18:16
This was added to Quarkus yesterday: https://github.com/quarkusio/quarkus/pull/13745. You could try out the Quarkus snapshot, or just override SR Config version with 1.10.0. It should work on latest Quarkus Final.

**Comment by hamburml** [comment] 2020-12-13 14:27
I tried the quarkus snapshot and sadly it's not working on Windows with JDK 8. I've added another example which uses ClassPathUtils from smallrye config.

[config-service.zip](https://github.com/quarkusio/quarkus/files/5684718/config-service.zip)

**Comment by radcortez** [comment] 2020-12-14 17:38
Yes, I can confirm the issue is caused by a `ServiceLoader` lock to the file in JDK 8 / Windows. There is even an issue reported in OpenJDK (with no fix for 8): https://bugs.openjdk.java.net/browse/JDK-6587593, but works from 9 forward.

In SR Config, we cannot get rid of `ServiceLoader`, since it is part of the spec. There were other Windows issues in SR Config that were probably preventing to run fine in JDK 11, but those should be fixed with latest Quarkus master.

Like @aloubyansky mentioned, the `ServiceLoader` causes the lock and then the BuildMojo fails here:
https://github.com/quarkusio/quarkus/blob/1.4/devtools/maven/src/main/java/io/quarkus/maven/BuildMojo.java#L192-L198 (this was added in 1.4).

A possible workaround is to add a separate jar with the `ConfigSourceProvider`. Since the locking on the file will be different, it should be fine.

**Comment by hamburml** [comment] 2020-12-15 13:28
Hi!

I tried the possible workaround but got the same error message. GH repo is found here https://github.com/hamburml/CustomConfigSourceProvider

Just build the project with JDK 8 on Windows located under "config-service". Inside the "customconfigsourceprovider" you will find the CustomConfigSourceProvider.java. The jar is already build and copied inside "config-service" folder.

Thanks!

**Comment by radcortez** [comment] 2021-01-05 14:17
I believe this is out of scope of our resolution, due to the issues with the `ServiceLoader`, JDK 8 and Windows. The recommended approach would be to use a separate module or jar that provides the custom `Provider` or `Source`.

**Closed by radcortez** 2021-01-05 14:17 UTC
Labels: area/config, kind/bug, triage/backport?

**Comment by hamburml** [comment] 2021-01-05 17:06
I don't agree with you.

Yes, there are workarounds - but simply saying "this is out of scope" is in my opinion an easy way of shifting responsibility away. The issue appeared after a change in the BuildMojo.java file. You even linked it in this issue. This also mean that version v1.4 and newer are not compatibel with JDK 8 on Windows anymore when building an uber-jar.

The fact that it worked in past version does without any doubt tell that it's an issue during the quarkus build process.

Nevertheless, I hope we can switch to a newer JDK version which fixes this or adjust our build pipeline to add another dependency which sadly only contains one Provider and one service file. I personally don't like the workaround because the service file is hidden in a dependency. Which means that it's getting intransparent. But that's only my opinion.

**Comment by radcortez** [comment] 2021-01-05 19:01
Ok, let see if you can move forward with it from your side. If not, I may have another trick that we can try :)
