### ISSUE TITLE
Agroal: default datasource health check is up, without any url configured

### ISSUE THREAD

**Issue by turing85** [quarkusio/quarkus#41152] opened 2024-06-12 08:50 UTC
### Describe the bug

The health check for the default datasource shows an `UP` status, without any url being configured.

### Expected behavior

The application should fail to start, since the datasource is not configured correctly

### Actual behavior

The health check for the default datasource shows an `UP` status

### How to Reproduce?

Reproducer:
- clone https://github.com/turing85/quarkus-camel-local-transactions
  ```bash
  git clone https://github.com/turing85/quarkus-camel-local-transactions.git
  cd quarkus-camel-local-transactions
  ```
- look at the [`application.properties`](https://github.com/turing85/quarkus-camel-local-transactions/blob/main/src/main/resources/application.properties) and verify that no database url is configured
- build the application:
  ```bash
  ./mvnw --define skipTests clean package
  ```
- run the application:
  ```bash
  QUARKUS_ARTEMIS_URL=tcp://localhost:5432 java -jar target/quarkus-app/quarkus-run.jar
  ```
- access http://localhost:8080/q/health
- notice that the health check for the database is up:
  ```json
  {
    ...
    "checks": [
      ...
      {
        "name": "Database connections health check",
        "status": "UP",
        "data": {
          "<default>": "UP"
        }
      },
      ...
    ]
  }
  ```

### Output of `uname -a` or `ver`
```
Linux xxx 5.15.0-52-generic #58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
```

### Output of `java -version`
```
openjdk 21.0.2 2024-01-16 LTS
OpenJDK Runtime Environment Temurin-21.0.2+13 (build 21.0.2+13-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.2+13 (build 21.0.2+13-LTS, mixed mode, sharing)
```
### Quarkus version or git rev
```
3.11.1
```

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: /home/marco/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6
Java version: 21.0.2, vendor: Eclipse Adoptium, runtime: /opt/java/mandrel/23.1.2.0-java21
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-52-generic", arch: "amd64", family: "unix"
```
### Additional information

If we downgrade the quarkus version from `3.11.1` to `3.8.5`, we get a slightly different result; the `default` datasource is then missing from the health check:
```json
{
  ...
  "checks": [
    ...
    {
      "name": "Database connections health check",
      "status": "UP"
    },
    ...
  ]
}
```

**Comment by turing85** [comment] 2024-06-12 08:52
cc @yrodiere

**Comment by yrodiere** [comment] 2024-06-12 12:51
Alright, sorry, I misremembered.

If you were using Hibernate ORM, the application wouldn't start, because there are additional checks there.

If you use JDBC directly, or through another extension that doesn't perform additional checks on startup, then the behavior you're seeing is unfortunately expected.
See #36666 and in particular future plans to address the problem [here](https://github.com/quarkusio/quarkus/issues/36666#issuecomment-2162923149).

I'll close this issue as duplicate of #36666; feel free to ping me if you disagree.

**Closed by yrodiere** 2024-06-12 12:51 UTC
Labels: kind/bug, area/persistence, area/health
