### ISSUE TITLE
Do not produce Infinispan `RemoteCacheManager` if no Infinispan configuration is present

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#18232] opened 2021-06-29 10:07 UTC
We depend on quarkus-infinispan-client in camel-quarkus-infinispan. Camel offers some alternative ways to configure Infinispan client, e.g. users can pass the list of hosts through the Camel route definition - see https://github.com/apache/camel-quarkus/issues/2344#issue-834501872 . If the user does not provide any `quarkus.infinispan.*` config in application.properties, starting the application fails, because quarkus-infinispan-client still produces an improperly configured `RemoteCacheManager`. Thus we'd appreciate if the producer methods in `InfinispanClientProducer` could please return `null` if no `quarkus.infinispan.*` config was provided by the end user.

cc @jamesnetherton

**Comment by karesti** [comment] 2021-06-29 13:06
we are working now on the extension, I will create a JIRA to address this issue

**Comment by karesti** [comment] 2021-06-29 13:09
https://issues.redhat.com/browse/ISPN-13137

**Comment by karesti** [comment] 2021-07-02 12:32
@ppalaga would this make the trick?  I also upgraded to 12.1.5.Final but it has not landed in central yet 
https://github.com/karesti/quarkus/commit/3a65b186f104ff489c8c5f33919bca74f041d399

**Comment by jamesnetherton** [comment] 2021-07-02 13:32
Peter is on PTO, but it looks ok to me.

I can try to test it with camel-quarkus when 12.1.5.Final shows up in central.

**Comment by jamesnetherton** [comment] 2021-07-05 08:39
I tested and it didn't quite work. The problem is in `InfinispanClientProducer.initialize()`. It seems `properties` is not null and contains some values that I assume the extension set at build time?

* `infinispan.client.hotrod.protofile.org/infinispan/protostream/message-wrapping.proto`
* `infinispan.client.hotrod.marshaller`
* `infinispan.client.hotrod.protofile.org/infinispan/query/remote/client/query.proto`

Maybe because the camel component has [this](https://github.com/apache/camel/blob/main/components/camel-infinispan/camel-infinispan/pom.xml#L50-L54) dependency.

**Closed** 2021-07-08 08:49 UTC
Labels: area/infinispan, kind/enhancement

**Comment by karesti** [comment] 2021-07-08 16:01
@jamesnetherton sorry I missed this comment before.
