### ISSUE TITLE
ManagedExecutor - runAsync - Request context is not consistent

### ISSUE THREAD

**Issue by ZetalyAlexandre** [quarkusio/quarkus#44451] opened 2024-11-12 17:07 UTC
### Describe the bug

We run “long” processes in the background using the `ManagedExecutor `class. The behavior of the `RequestContext `is inconsistent from one run to the next. Sometimes the request context is active, sometimes not. This seems to depend on the executor thread used.
In addition, we sometimes put processing on hold via `Thread.sleep()`. This sometimes changes the context state.

### Expected behavior

- The request context should be consistent and should not depend on executor thread. 
- After a `Thread.sleep()`, the context should be preserved.

### Actual behavior

- The `RequestContext `depends on ExecutorThread.
- The context state change after a `Thread.sleep`

### How to Reproduce?

Sample projet: [request-context.zip](https://github.com/user-attachments/files/17720162/request-context.zip)
It create a thread with a loop displaying the context state every second.

Call the url: `/thread/1`
Check the log. Sometimes it stick to the same thread with a activated context. Sometimes it stick with the same thread without a context. Sometimes it stick to the same thread but the context is deactiated.

Example with active context:
`2024-11-12 17:42:17,680 INFO  [org.acm.GreetingResource] (executor-thread-3) Start mainLoop
2024-11-12 17:42:17,682 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:18,688 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:19,694 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:20,702 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:21,708 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:22,714 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:23,721 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:24,730 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:25,737 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:26,741 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 17:42:27,747 INFO  [org.acm.GreetingResource] (executor-thread-3) mainLoop ended`

Example with inactive context:
`2024-11-12 17:42:39,369 INFO  [org.acm.GreetingResource] (executor-thread-2) Start mainLoop
2024-11-12 17:42:39,371 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:40,373 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:41,381 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:42,385 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:43,391 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:44,397 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:45,405 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:46,414 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:47,421 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:48,428 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 17:42:49,436 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop ended`

Example with a deactivated context:
`2024-11-12 18:01:43,457 INFO  [org.acm.GreetingResource] (executor-thread-2) Start mainLoop
2024-11-12 18:01:43,459 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: true, Normal: true.
2024-11-12 18:01:44,467 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:45,472 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:46,478 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:47,496 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:48,502 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:49,508 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:50,524 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:51,529 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:52,537 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop - Container state. Active: false, Normal: true.
2024-11-12 18:01:53,545 INFO  [org.acm.GreetingResource] (executor-thread-2) mainLoop ended`

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16

### Quarkus version or git rev

3.8.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\Alexandre\.m2\wrapper\dists\apache-maven-3.9.9-bin\33b4b2b4\apache-maven-3.9.9 Java version: 17.0.12, vendor: Eclipse Adoptium, runtime: C:\Program Files\Eclipse Adoptium\jdk-17.0.12.7-hotspot Default locale: fr_FR, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by manovotn** [comment] 2024-11-18 15:27
Hm, I think this scenario is a misuse of the propagation. In your reproducer, you are basically trying to prolong the lifespan of CDI req. context beyond the initial HTTP request because your `hello()` endpoint invocation will end long before the `mainLoop()` method.
What `ManagedExecutor` does (for req. context) is that it gives the new thread for async task a link to the same underlying storage that the req. context uses to store beans and activates the context. However, req. context as such will be terminated from the original thread once HTTP request is over and the storage that you passed over will be invalidated. Therefore, based on the race condition between the original thread and the new one, you will either:
* lose req. context during `mainLoop` execution if the `mainLoop` method printed out container state before the HTTP req. ended
* have no req. context whatsoever when the async thread was created but context state was invalidated before `mainLoop` first printed out container state
* always have req. context - here I am not 100% sure why but my bet is that the async thread starts a fresh req. context because before the `ManagedExecutor` manages to capture the context, it is already invalidated

Now, I said that I think this scenario is a misuse because you need to differentiate two things:

1. The need to have the **exact same** CDI request context active during the `mainLoop` execution - i.e. access to the same existing req. scoped beans with their current states. This is IMO wrong here.
2. The need to have **any** CDI request context active, just so that you can freely use req. scoped beans but you do not care for their previous state. This is OK and can be done if you tweak your example a little[1].

Which of the above two are you trying to achieve @ZetalyAlexandre?

Side note - your reproducer also logs result of `Arc.container().requestContext().isNormal()`. This has nothing to do with context being active or propagated, it is merely a CDI API to determine whether a context is normal-scoped (which req. context always is) or otherwise.

_________________________________________________________________
[1] Here's how:

```java
    @Inject
    @ManagedExecutorConfig(cleared = ThreadContext.CDI) // prevents propagating CDI req. context from original thread
    private ManagedExecutor managedExecutor;

    @ActivateRequestContext // Activates a fresh CDI req. context is none is active when entering this method
    protected void mainLoop() {
        ...
    }
```

**Comment by ZetalyAlexandre** [comment] 2024-11-18 16:17
First of all, thank you for your reply.

We are trying to achieve the second case: "The need to have any CDI request context active, just so that you can freely use req. scoped beans but you do not care for their previous state. This is OK and can be done if you tweak your example a little".

We had previously tried to just add `@ActivateRequestContext` but we had the same behavior. It seems that adding `@ManagedExecutorConfig` is enough and a fresh request context is created without the need of `@ActivateRequestContext` .

If my understanding is correct, at the end of http request, every request scoped created by the executor are invalidated, that's why adding only `@ActivateRequestContext` was not enough ?

**Comment by manovotn** [comment] 2024-11-18 17:09
> We had previously tried to just add `@ActivateRequestContext` but we had the same behavior. It seems that adding `@ManagedExecutorConfig` is enough and a fresh request context is created without the need of `@ActivateRequestContext` .
> 
> If my understanding is correct, at the end of http request, every request scoped created by the executor are invalidated, that's why adding only `@ActivateRequestContext` was not enough ?

@ZetalyAlexandre not exactly, the issue there is that `@ActivateRequestContext` will attempt to active the context once before entering the method and only if it wasn't already active. That's the culprit here - by the time it attempts to active it, it can happen that it sees the context still active and does nothing.

BTW, in my previous fix I didn't realize that you don't even need `@ActivateRequestContext` if you use `@ManagedExecutorConfig`.
So you should be able to do just this:

```java
    @Inject
    @ManagedExecutorConfig(cleared = ThreadContext.CDI) // prevents propagating CDI req. context from original thread
    private ManagedExecutor managedExecutor;

    // no need for activation, having a context on manager executor as "cleared" means it will always spawn a new one for you
    protected void mainLoop() {
        ...
    }
```

However, since you don't need to actually propagate anything, the `ManagedExecutor` presents an overhead (not massive in this case, but it's there) and I'd suggest you do it differently. Give a go to the following code:

```java
    // following executor service provides no context propagation
    @Inject
    ScheduledExecutorService scheduledExecutorService;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/1")
    public String hello() {
        // fires off a job immediately; you pass in the annotated method as Runnable
        scheduledExecutorService.schedule(() -> mainLoop(), 0, TimeUnit.MILLISECONDS);
        return "Thread started...";
    }

    // activates fresh req. context
    @ActivateRequestContext
    protected void mainLoop() {
        Log.info("Start mainLoop");
        for (int i = 0; i < 10; i++) {
            displayContainerInfo("mainLoop");
            try {
                Thread.sleep(1000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        }
        Log.info("mainLoop ended");
    }
```

**Comment by manovotn** [comment] 2024-11-19 09:01
Closing this as resolved.
If you think further action is needed, or if you have further questions, feel free to ask/re-open.

**Closed by manovotn** 2024-11-19 09:01 UTC
Labels: kind/question, env/windows, area/context-propagation
