### ISSUE TITLE
@TestTransaction does not work for @Nested tests

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#29142] opened 2022-11-09 07:38 UTC
### Describe the bug

When you have lots of tests you might want to group them e.g. by method using a `@Nested` inner class.

```
@TestTransaction
@QuarkusTest
class MyServiceTest {

    @Nested
    class Method1 {
  
        @Test
        void myTest(){
            // test implementation
        }
    }
}
```
This seems to break the functionality of `@TestTransaction`. All the nested test will run without a transaction, resulting in `Transaction is not active, consider adding @Transactional to your method to automatically activate one.`

It doesn't matter if the `@TestTransaction` is on the top test class `MyServiceTest `, on the nested class `Method1 ` or on the specific nested test `myTest`.

Currently, the fallback is to use `QuarkusTransaction` to manually create and rollback transactions.

### Expected behavior

When using `@TestTransaction` on the top class, nested test should run within a test transaction.

### Actual behavior

No transaction is open when a nested test is executed.

**Comment by famod** [comment] 2022-11-13 22:57
Pretty much a duplicate of #20034, no?

**Comment by geoand** [comment] 2022-11-14 06:53
It does indeed look like that but let's let @Sgitario confirm

**Comment by Sgitario** [comment] 2022-11-14 07:19
I had a look into this issue and when running the reproducer, the transaction was not active at all when running the nested tests (not only when rolling it back). But the root cause is the same, so yes, it's a duplicated issue.

**Comment by geoand** [comment] 2022-11-14 07:21
Thanks for checking @Sgitario

**Closed by geoand** 2022-11-14 07:21 UTC
Labels: kind/bug, area/testing
