### ISSUE TITLE
Check RESTEasy typos at build time and avoid the @PathPAram annotation

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2144] opened 2019-04-18 10:11 UTC
```
@Path("/api")
public class TodoResources {

    @GET
    @Path("{naaaame}")
    public String getOne(@PathParam("name") String name) {
    ...
    }
}
```

Should fail and mention that naaame is not present as a path param.

And to go beyond we should use parameter names form the method as default path param value. Like this

```
@Path("/api")
public class TodoResources {

    @GET
    @Path("{name}")
    public String getOne(String name) { //@PathParam not needed
    ...
    }
}
```

Maybe the latter already works.

CC @asoldano for input
CC @FroMage for info

**Comment by kenfinnigan** [comment] 2019-04-18 13:08
Is the information for the former case easily accessible from Jandex?

**Comment by FroMage** [comment] 2019-04-23 07:22
We do have a `@PathParam` annotation that does not need a value (in a resteasy package), but requires your compiler to add method parameters to reflection.

**Comment by emmanuelbernard** [comment] 2019-04-23 16:02
@kenfinnigan if it's not, we can add it to jandex yes (cc @n1hility )

**Comment by sberyozkin** [comment] 2019-04-25 14:07
As far as I recall one can have a PathParam in a subresource, with the actual template var specified in the root resource Path, example
```
@Path("root")
class Root {
   @Path("{id}")
   public Response get() {
      return new SubRoot();
   } 
}

class SubRoot {
   @GET
   public Response get(@PathParam("id") Long id) {
      return Response.ok().build();
   } 
}

```

**Comment by n1hility** [comment] 2019-04-25 14:08
@kenfinnigan @emmanuelbernard so the issue is javac requires a special parameter for jandex to be able to read it. Else it's omitted from the class file (the API improvements to access them was a contribution from @FroMage). That said we could put this setting in the archetype. We could also default to arg0, arg1, etc in the absence of no param (jandex might do that already, need to check the source). We can additionally force the param in dev mode.

**Comment by emmanuelbernard** [comment] 2019-04-25 16:05
So we can disable validation if we see arg0 etc. Or stop and ask people to enable the session. I say the former is ok.

But if you can enable it in dev mode without the user having to do it that would be cool. Not sure how as you still don't control compilation.

**Comment by sberyozkin** [comment] 2019-04-26 10:08
@emmanuelbernard, in the example I typed above, one can't deduce that the 'body' requires an implicit @PathParam. It is a relatively rare case though. Sorry if I've missed your earlier point

**Comment by geoand** [comment] 2021-07-29 05:28
I am going to close this as we have implemented this stuff in RESTEasy Reactive

**Closed by geoand** 2021-07-29 05:28 UTC
Labels: area/resteasy, kind/enhancement
