### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#14068] opened 2020-12-29 10:36 UTC
**Describe the bug**

Java: 11
Quarkus: 1.10.5.Final
Vertx: 3.9.5
Vertx-redis-client: 3.9.5

Deploy on cloud server, OutOfMemoryError will occur about every two days.
The picture is a screenshot of jvm dump.

Java command line: `nohup java -Xms2048m -Xmx2048m -XX:+HeapDumpOnOutOfMemoryError --add-opens java.base/jdk.internal.misc=ALL-UNNAMED -Dio.netty.tryReflectionSetAccessible=true -jar provider-web-jl-1.0-SNAPSHOT-runner.jar &`

**Configuration**
```properties

quarkus.http.so-reuse-port=true
quarkus.http.tcp-quick-ack=true
quarkus.http.tcp-cork=true
quarkus.http.tcp-fast-open=true
quarkus.vertx.prefer-native-transport=true

quarkus.redis.hosts=redis://:xxx@127.0.0.1:26379/0
quarkus.redis.client-type=standalone
quarkus.redis.max-pool-size=16
quarkus.redis.max-pool-waiting=128

```

**Screenshots**
![image](https://user-images.githubusercontent.com/70388114/103277201-70a2b200-4a03-11eb-95e0-18e4ccb607cc.png)

**Environment (please complete the following information):**

`uname -a`:
```shell
Linux ca6bc6ac552834168972275782b04da63-node6 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
`java -version`
```shell
openjdk version "11.0.7" 2020-04-14 LTS
OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)
```

**Comment by geoand** [comment] 2021-01-04 11:11
Hi,

Do you have a sample of the application that exhibits this behavior? 
I am afraid without a simple it will be very tough to locate the memory leak

**Comment by gsmet** [comment] 2021-01-04 19:04
@cescoffier do you know who's working on the Redis client on the Vert.x side?

**Comment by cescoffier** [comment] 2021-01-04 20:05
@gsmet @pmlopes is the maintainer of the vertx redis client.

**Comment by pmlopes** [comment] 2021-01-04 20:26
Just by looking at the screenshot it's hard to tell the root cause. The trace seems normal because it shows where the buffers arrive from redis and are parsed `RESPParser` and thanks to `ReadableBuffer` which "glues" byte chunks together to allow the protocol parsing.

Now these chunks may remain active outside the parser as they are then given to the user, so the leak can be anywhere.

Further research (with a demo project) would be appreciated!

**Comment by cescoffier** [comment] 2021-05-03 09:28
@aomsweet any news about that issue?

**Comment by geoand** [comment] 2021-08-03 11:31
Closing as we haven't got any new information. Feel free to reopen if there is new information

**Closed by geoand** 2021-08-03 11:31 UTC
Labels: kind/bug, triage/needs-triage
