### ISSUE TITLE
Same prefix path in two classes leads to 404 not found

### ISSUE THREAD

**Issue by antssilva96** [quarkusio/quarkus#27659] opened 2022-09-01 09:32 UTC
### Describe the bug

This bug seems to be similar to https://github.com/quarkusio/quarkus/issues/18542 but is happening in regular `quarkus-resteasy`.

I have a resourceA with 

```
@Path("test")
public class ResourceA {
    @GET
    @Path("{testId}")
    public String getString(@PathParam("testId") final long testId) {
        return "hello this is test from resource A";
    }
}
```

and a resourceB with

```
@Path("test/{testId}")
public class ResourceB {
    // no GET endpoint here
}
```

and this leads to 404 NOT Found  when I perform a GET /test/1234, even though it should be able to find the method in ResourceA.

If I remove the `/{testId}` from ResourceB's path it works as expected.

### Expected behavior

All classes should be scanned for matching endpoints and it should be able to find the request when it exists in another resource class.

### Actual behavior

Getting 404 not found if the method is not present in the resource with the most specific path that matches the request.

### Output of `uname -a` or `ver`

Linux laptop-XXXX 5.15.0-46-generic #49~20.04.1-Ubuntu SMP Thu Aug 4 19:15:44 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### Quarkus version or git rev

<quarkus.platform.version>2.11.3.Final</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by geoand** [comment] 2022-09-01 10:34
I am going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/25462

**Closed by geoand** 2022-09-01 10:34 UTC
Labels: kind/bug, triage/needs-triage

**Comment by antssilva96** [comment] 2022-09-01 11:31
Thanks! Should we add a not that it doesn't happen only_ for reactive resteasy ?

**Comment by geoand** [comment] 2022-09-01 11:37
A note where?
