### ISSUE TITLE
Quarkus Build Fails if using Scala case class with JAX-RS

### ISSUE THREAD

**Issue by ungerts** [quarkusio/quarkus#14017] opened 2020-12-21 22:31 UTC
**Describe the bug**
If using a Scala case class as return type in JAX-RS build fails.

**Expected behavior**
Build should be successful.

**Actual behavior**
Build throws NullPointerException

**To Reproduce**
Example Repository:
https://github.com/ungerts/scala-rest-quarkus

1. mvnw package -X

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: mac os x
 - Output of `java -version`: OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.8+10)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.5.Final:build (default) on project scala-rest: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.ReflectiveHierarchyStep#build threw an exception: java.lang.NullPointerException
[ERROR] 	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
[ERROR] 	at java.base/java.util.Optional.<init>(Optional.java:107)
[ERROR] 	at java.base/java.util.Optional.of(Optional.java:120)
[ERROR] 	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.computeAdditional(BeanArchives.java:242)
[ERROR] 	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
[ERROR] 	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:111)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:176)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:213)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
[ERROR] 	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.build(ReflectiveHierarchyStep.java:63)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:834)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.5.Final:build (default) on project scala-rest: Failed to build quarkus application
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to build quarkus application
    at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:111)
    at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:85)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ReflectiveHierarchyStep#build threw an exception: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.computeAdditional(BeanArchives.java:242)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:111)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:176)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:213)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.build(ReflectiveHierarchyStep.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

    at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment (AugmentActionImpl.java:254)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication (AugmentActionImpl.java:94)
    at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:84)
    at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:85)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.deployment.steps.ReflectiveHierarchyStep#build threw an exception: java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.Optional.<init>(Optional.java:107)
	at java.base/java.util.Optional.of(Optional.java:120)
	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.computeAdditional(BeanArchives.java:242)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName(BeanArchives.java:111)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:176)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:213)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:201)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:148)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy(ReflectiveHierarchyStep.java:226)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy(ReflectiveHierarchyStep.java:126)
	at io.quarkus.deployment.steps.ReflectiveHierarchyStep.build(ReflectiveHierarchyStep.java:63)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:972)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)

    at io.quarkus.builder.Execution.run (Execution.java:116)
    at io.quarkus.builder.BuildExecutionBuilder.execute (BuildExecutionBuilder.java:79)
    at io.quarkus.deployment.QuarkusAugmentor.run (QuarkusAugmentor.java:148)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment (AugmentActionImpl.java:252)
    at io.quarkus.runner.bootstrap.AugmentActionImpl.createProductionApplication (AugmentActionImpl.java:94)
    at io.quarkus.maven.BuildMojo.doExecute (BuildMojo.java:84)
    at io.quarkus.maven.QuarkusBootstrapMojo.execute (QuarkusBootstrapMojo.java:85)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
Caused by: java.lang.NullPointerException
    at java.util.Objects.requireNonNull (Objects.java:221)
    at java.util.Optional.<init> (Optional.java:107)
    at java.util.Optional.of (Optional.java:120)
    at io.quarkus.arc.processor.BeanArchives$IndexWrapper.computeAdditional (BeanArchives.java:242)
    at java.util.concurrent.ConcurrentHashMap.computeIfAbsent (ConcurrentHashMap.java:1705)
    at io.quarkus.arc.processor.BeanArchives$IndexWrapper.getClassByName (BeanArchives.java:111)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:176)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:213)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:126)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:201)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:201)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:201)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:148)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addClassTypeHierarchy (ReflectiveHierarchyStep.java:226)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.addReflectiveHierarchy (ReflectiveHierarchyStep.java:126)
    at io.quarkus.deployment.steps.ReflectiveHierarchyStep.build (ReflectiveHierarchyStep.java:63)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:566)
    at io.quarkus.deployment.ExtensionLoader$2.execute (ExtensionLoader.java:972)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:277)
    at org.jboss.threads.ContextClassLoaderSavingRunnable.run (ContextClassLoaderSavingRunnable.java:35)
    at org.jboss.threads.EnhancedQueueExecutor.safeRun (EnhancedQueueExecutor.java:2046)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask (EnhancedQueueExecutor.java:1578)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1452)
    at java.lang.Thread.run (Thread.java:834)
    at org.jboss.threads.JBossThread.run (JBossThread.java:479)
```

**Comment by gsmet** [comment] 2020-12-22 10:36
I think your issue is a duplicate of https://github.com/quarkusio/quarkus/issues/12985 . We haven't fixed it yet though.

**Closed by gsmet** 2020-12-22 10:36 UTC
Labels: kind/bug, triage/needs-triage
