### ISSUE TITLE
Property `quarkus.openshift.arguments` fails in native mode

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#25196] opened 2022-04-27 10:37 UTC
### Describe the bug

When application which has `quarkus.openshift.arguments` as a property is started in native mode on OpenShift, it fails with error.

### Expected behavior

quarkus.openshift.arguments should work the same way in native and in JVM mode.

### Actual behavior

Deploy fails with multiple errors like this:
```
10:01:40,388 INFO  oc: 4m46s       Warning   Failed              pod/app-1-rs4vz               Error: container create failed: time="2022-04-27T07:56:54Z" level=error msg="runc create failed: unable to start container process: exec: \"ARG1\": executable file not found in $PATH"
```

### How to Reproduce?

1. `git clone git@github.com:quarkus-qe/quarkus-test-suite.git` I can reproduce it on commit `c70188cd6fceaf083e3c6449421ef56bee4f209e`
2. `cd quarkus-test-suite/lifecycle-application`
3. Run tests on OpenShift in Native mode:
```
VERSION=2.5.7.Final
mvn clean verify  -Dnative -Dts.openshift.ephemeral.namespaces.enabled=true \
	-Dquarkus.native.container-runtime=docker \
	-Dquarkus.native.builder-image=registry-proxy.engineering.redhat.com/rh-osbs/quarkus-mandrel-21-rhel8:21.3 \
	-Dquarkus.platform.version=${VERSION} \
	-Dquarkus-plugin.version=${VERSION} \
	-Dts.global.version-number=${VERSION} \
	-Dquarkus.platform.artifact-id=quarkus-bom \
	-Dopenshift -Dall-modules -Dinclude.operator-scenarios -Dinclude.serverless \
	-Dts.global.build-number=5 \
	-Dts.global.service-name=rhbq-2.7-rhel8-jdk11-openshift-ts-native-ocp-4-stable # last two options can hold any values
```

### Output of `uname -a` or `ver`
5.16.20-200.fc35.x86_64

### Output of `java -version`
11.0.12, vendor: GraalVM Community

### Quarkus version or git rev
2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

oc v3.11.420
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server — OCP 4.10
kubernetes v1.23.5+9ce5071

**Comment by geoand** [comment] 2022-04-27 10:38
@iocanel @Sgitario weren't you already handling something similar?

**Comment by fedinskiy** [comment] 2022-04-27 10:39
@geoand there is a similar change made in https://github.com/quarkusio/quarkus/pull/17889

**Comment by Sgitario** [comment] 2022-04-27 11:00
This is a duplicate of https://github.com/quarkusio/quarkus/issues/24885

**Closed** 2022-04-27 11:01 UTC
Labels: kind/bug, area/kubernetes, area/mandrel
