### ISSUE TITLE
java.lang.ClassCastException when upgrading from 2.16.0.Final to 2.16.1.Final

### ISSUE THREAD

**Issue by spolti** [quarkusio/quarkus#30850] opened 2023-02-03 13:01 UTC
### Describe the bug

After upgrading to Quarkus 2.16.1 this issue started to happen:

```

 Caused by: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
 	[error]: Build step io.quarkus.kubernetes.deployment.KubernetesProcessor#build threw an exception: java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.lang.String (java.util.HashMap and java.lang.String are in module java.base of loader 'bootstrap')
 	at io.dekorate.docker.adapter.DockerBuildConfigAdapter.newBuilder(DockerBuildConfigAdapter.java:58)
 	at io.dekorate.docker.config.DockerBuildConfigGenerator.addPropertyConfiguration(DockerBuildConfigGenerator.java:48)
 	at io.dekorate.Session.lambda$addPropertyConfiguration$1(Session.java:167)
 	at io.dekorate.Session.addConfiguration(Session.java:183)
 	at io.dekorate.Session.addPropertyConfiguration(Session.java:167)
 	at io.quarkus.kubernetes.deployment.KubernetesProcessor.lambda$build$2(KubernetesProcessor.java:164)
	at java.base/java.util.Optional.ifPresent(Optional.java:183)
	at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:141)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
 	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
 	at java.base/java.lang.Thread.run(Thread.java:829)
 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

No issues when upgrading from 2.16.0.Final to 2.16.1.Final

### Actual behavior

This seems to be a breaking change that we would not expect to see in a minor release.

**Comment by radtriste** [comment] 2023-02-03 13:02
See also https://github.com/kiegroup/kogito-runtimes/pull/2783

**Comment by Sgitario** [comment] 2023-02-03 13:03
Can you share the configuration you're using?

**Comment by radtriste** [comment] 2023-02-03 13:06
@Sgitario https://github.com/kiegroup/kogito-examples/tree/stable/kogito-quarkus-examples/onboarding-example/onboarding-quarkus

**Comment by radtriste** [comment] 2023-02-03 13:07
that would be:
```
quarkus.http.port=8080
quarkus.infinispan-client.hosts=localhost:11222
quarkus.infinispan-client.use-auth=false

# Kubernetes related properties
%minikube.quarkus.kubernetes.deployment-target=minikube
%kubernetes.quarkus.kubernetes.deployment-target=kubernetes
quarkus.container-image.group=kogito
quarkus.container-image.name=onboarding-service
quarkus.container-image.tag=latest
quarkus.kubernetes.labels.onboarding=process

%knative.quarkus.kubernetes.deployment-target=kubernetes
%knative.quarkus.knative.labels.onboarding=process
```

**Comment by geoand** [comment] 2023-02-03 13:09
Looks like a dekotate issue

**Comment by Sgitario** [comment] 2023-02-03 13:32
We already have tests to cover this scenario.
I could not reproduce this issue when building the Kogito example locally and using Quarkus 2.16.1.Final (I simply tried `mvn clean install`). Let me know if I need to use something else to reproduce it. 

Also, are you adding some properties when running Maven? I could not find any in the Jenkins logs though :/
Quarkus Kubernetes is automatically mapping some properties into Dekorate properties and maybe here is the issue, but I can't be 100% sure.

**Comment by geoand** [comment] 2023-02-03 13:35
We certainly have tests, but something is obviously wrong in this case.
It would be nice to add a test once we know that the actual problem is

**Comment by Sgitario** [comment] 2023-02-03 13:37
> We certainly have tests, but something is obviously wrong in this case. It would be nice to add a test once we know that the actual problem is

Indeed

**Comment by radtriste** [comment] 2023-02-03 13:38
command line:
```
mvn clean install  -s /home/jenkins/workspace/KIE/kogito/main/pullrequest/kogito-runtimes.tests.downstream.kogito-quarkus-examples@tmp/config1980440886206568513tmp -Dmaven.wagon.http.ssl.insecure=true -Dmaven.test.failure.ignore=true -nsu -ntp -fae -e -Dhttp.keepAlive=false -Dmaven.wagon.http.pool=false -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 -Dmaven.wagon.http.retryHandler.count=3   dependency:tree  -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -B
```
nothing quarkus specific here

Trying to get quick reproducer

**Comment by Sgitario** [comment] 2023-02-03 14:07
Thanks

To give more information, the dekorate version is the same for 2.16.0.Final and 2.16.1.Final. 
In Quarkus, as far I see, the only difference in the Kubernetes extension between these releases is https://github.com/quarkusio/quarkus/pull/30591, which seems related. Though, I don't see how these changes could break your example.

**Comment by radtriste** [comment] 2023-02-03 14:14
ok. cannot reproduce as well ...
so seems an issue on CI ...

**Comment by spolti** [comment] 2023-02-06 13:38
@radtriste can this be closed?

**Comment by radtriste** [comment] 2023-02-06 13:40
still having an issue here ... but cannot reproduce ... 
GHA is green though ...

**Comment by radtriste** [comment] 2023-02-06 13:45
Could it be a Filesystem issue on Jenkins ?

**Comment by radtriste** [comment] 2023-02-06 13:45
I mean reading the properties ?

**Comment by radtriste** [comment] 2023-02-06 13:46
The issue is happening really on 3 apps and not the other. But the container configuration is on almost all examples

**Comment by spolti** [comment] 2023-02-06 13:51
is there a chance of something be pulling and older version of Quarkus and, maybe the dekorate dep?

**Comment by radtriste** [comment] 2023-02-06 15:04
dekorate-core and docker-annotations are both in version 3.2.0

**Comment by radtriste** [comment] 2023-02-06 21:44
So far I tried different hypothesis on why it fails on Jenkins:

1) Hierarchy of the repositories in the filesystem
2) Environment variables already available on Jenkins node
3) Application properties set (but why would it work on GHA ?)

If you want to help, here are some links (Red Hat internal):
- A failure example, just for one example, can be found [here](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-examples-test/13/execution/node/138/log/)
- The environment can be found [here](https://eng-jenkins-csb-business-automation.apps.ocp-c1.prod.psi.redhat.com/job/custom/job/tradisso/job/kogito-examples-test/13/artifact/env_props/*view*/)

**Comment by Sgitario** [comment] 2023-02-08 07:39
FYI: This issue is going to be fixed by https://github.com/quarkusio/quarkus/pull/30977. but this pull request cannot be backported to 2.16 because it has breaking changes. 

Therefore, let me know if you managed to address the issue by either moving the `quarkus-kubernetes` extension to another profile or removing the `docker.` properties. Otherwise, I can provide a quick fix only for 2.16 (though, there are no plans to release 2.16.2, right @gsmet ?)

**Comment by gsmet** [comment] 2023-02-08 09:05
@Sgitario I'm releasing 2.16.2.Final as we speak and there will be more 2.16 micros for sure. So please fix it in 2.16 too if you can.

**Comment by Sgitario** [comment] 2023-02-08 09:35
Here you have: https://github.com/quarkusio/quarkus/pull/30992
I've manually verified that now the Docker dekorate builder is not triggered when adding any `docker.XX=YY` property. So, this should address this issue.

**Comment by radtriste** [comment] 2023-02-08 11:12
Let me know when it is released or at least merged.
the update of Kogito will be done directly  to 2.16.2 (skipping 2.16.1)

**Comment by radtriste** [comment] 2023-02-08 11:14
in fact, @Sgitario I am running directly with your branch to check this was the fix :)

**Comment by Sgitario** [comment] 2023-02-08 11:38
> in fact, @Sgitario I am running directly with your branch to check this was the fix :)

Great! Let me know if it was ok!

**Comment by radtriste** [comment] 2023-02-08 20:18
@Sgitario @gsmet all greem with change from Jose.
Will wait for the next bug fix release :)

**Comment by radtriste** [comment] 2023-02-08 20:22
Should be fixed in https://github.com/quarkusio/quarkus/pull/30992

**Comment by scrocquesel** [comment] 2023-02-24 23:18
Maybe of interest, I have CI env var named `DOCKER_REGISTRY_USER` and `DOCKER_REGISTRY_PASSWORD` which seems to be converted to a map for the key `docker.registry` but docker-annotation expects a string. Removing them fix the build meanwhile.

I don't use docker-annotation in the project and it's indeed a good idea to get rid of it from the ground up, but I wonder what would be the long term fix. I guess the generated adapter in dekorate should also not assume the type of the value is what it expects especially with so common variable name.

**Comment by gsmet** [comment] 2023-03-03 14:49
@Sgitario not sure if you have seen this one ^. I think we could close the issue but maybe there is more to it?

**Comment by Sgitario** [comment] 2023-03-03 14:54
I think we can close it as it's already fixed in the main branch and in 2.16.

**Closed by Sgitario** 2023-03-03 14:54 UTC
Labels: kind/bug, area/kubernetes

**Comment by spolti** [comment] 2023-03-03 14:59
Many thanks all!!

**Comment by radtriste** [comment] 2023-03-06 09:03
@gsmet @Sgitario Can we expect https://github.com/quarkusio/quarkus/commit/7afcad6640b82e9eae765081e28516e22b75f10f to be in a Quarkus 2.16 release ?

**Comment by radtriste** [comment] 2023-03-06 09:04
or is it part of 2.16.4 ? (could not get the information)
