### ISSUE TITLE
Failed to load a directory from a classpath when build as a fast-jar

### ISSUE THREAD

**Issue by ynojima** [quarkusio/quarkus#23744] opened 2022-02-16 04:56 UTC
### Describe the bug

Failed to load a directory from a classpath root when build as a fast-jar with Quarkus 2.7.1.Final.
~~~
Thread.currentThread().getContextClassLoader().getResource("<a directory that exists in classpath root>");
~~~
It worked with Quarkus 1.11.7.Final-redhat-00009.

### Expected behavior

~~~
Thread.currentThread().getContextClassLoader().getResource("<a directory that exists in classpath root>");
~~~
should return `URL` instance

### Actual behavior

~~~
Thread.currentThread().getContextClassLoader().getResource("<a directory that exists in classpath root>");
~~~
returns `null`

### How to Reproduce?

I made a reproducer:
https://github.com/ynojima/quarkus-issue-reproducer

## fast-jar(default), Quarkus 2.7
build it as a `fast-jar` (./mvnw package) with Quarkus 2.7, 
~~~
$cd quarkus-playground-2.7
$./mvnw package -Dquarkus.package.type=uber-jar 
$java -jar target/quarkus-app/quarkus-run.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-16 12:01:13,992 INFO  [io.quarkus] (main) quarkus-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.1.Final) started in 0.544s.
2022-02-16 12:01:14,012 INFO  [io.quarkus] (main) Profile prod activated.
2022-02-16 12:01:14,012 INFO  [io.quarkus] (main) Installed features: [cdi]
sample directory is NOT found.
2022-02-16 12:01:14,054 INFO  [io.quarkus] (main) quarkus-playground stopped in 0.029s
~~~
The directory is NOT found.

## uber-jar, Quarkus 2.2
But when I build it as `uber-jar`, 
~~~
$./mvnw package -Dquarkus.package.type=uber-jar 
$java -jar target/quarkus-playground-1.0.0-SNAPSHOT-runner.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-16 12:03:30,754 INFO  [io.quarkus] (main) quarkus-playground 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.1.Final) started in 0.517s.
2022-02-16 12:03:30,773 INFO  [io.quarkus] (main) Profile prod activated.
2022-02-16 12:03:30,774 INFO  [io.quarkus] (main) Installed features: [cdi]
sample directory is found.
2022-02-16 12:03:30,817 INFO  [io.quarkus] (main) quarkus-playground stopped in 0.029s
~~~
The directory is found.

## fast-jar(default), Quarkus 1.11
When I buid it with Quarkus 1.11, It also find the directory succcessfully.
~~~
$cd quarkus-playground-1.11
$./mvnw package
$ java -jar target/quarkus-playground-1.11-1.0.0-SNAPSHOT-runner.jar
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-02-16 12:09:59,087 INFO  [io.quarkus] (main) quarkus-playground-1.11 1.0.0-SNAPSHOT on JVM (powered by Quarkus 1.11.7.Final-redhat-00009) started in 0.467s.
2022-02-16 12:09:59,105 INFO  [io.quarkus] (main) Profile prod activated.
2022-02-16 12:09:59,106 INFO  [io.quarkus] (main) Installed features: [cdi]
sample directory is found.
2022-02-16 12:09:59,119 INFO  [io.quarkus] (main) quarkus-playground-1.11 stopped in 0.007s
~~~

### Output of `uname -a` or `ver`

Linux redcap 5.10.16.3-microsoft-standard-WSL2 #1 SMP Fri Apr 2 22:23:49 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment] 2022-02-16 05:14
This is a duplicate of https://github.com/quarkusio/quarkus/issues/23582 and has already been fixed in main

**Closed by geoand** 2022-02-16 05:14 UTC
Labels: kind/bug, triage/needs-triage
