### ISSUE TITLE
Root cause of exception "Failed to initialize Arc" not getting reported.

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7124] opened 2020-02-10 19:47 UTC
All types of exceptions thrown during testing using quarkus are not getting
reported, (e.g. ClassNotFound, ServiceConfigurationError, RuntimeExceptions,
java.net.ConnectException). 
Almost all errors bubble up through io.quarkus.arc.Arc.initialize(Arc.java:26)
and are caught in  org.jboss.arquillian.core.impl.ObserverImpl  line 89,
however at no time in the call stack is the exception information being
printed to the console.  All the user sees is a test result of
   [INFO] Tests run: 0, Failures: 0, Errors: 0, Skipped: 0

In addition the true cause is hidden in layers of wrapping exceptions.  See
attached image (![quarkus-cause-image](https://user-images.githubusercontent.com/506867/74184092-214d6a80-4c14-11ea-8c38-740fd5f49b06.jpg)) of a typical cause stack.  This image was generated by  
setting a breakpoint at ObserverImpl line 90 and commenting out exclude statement
in pom.xml at line 599 for test org/jboss/resteasy/test/client/InputStreamTest.java.
Test run with cmd 
    mvn test -Dmaven.surefire.debug

See project to reproduce  https://github.com/rsearls/qurakus-test-exception-reporting.git
Follow the directions in the README to run test

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 1.3.0.Alpha1

**Comment by mkouba** [comment] 2020-04-02 08:55
@rsearls Unfortunately, your reproducer requires some SNAPSHOTs, e.g. `org.jboss.resteasy:resteasy-wadl:jar:4.5.0-SNAPSHOT`.

Anyway, I've tried to modify the `io.quarkus.arquillian.test.SimpleTest` to throw an exception from an `@Observes @Initialized(ApplicationScoped.class)` observer:
```java
void observe(@Observes @Initialized(ApplicationScoped.class) Object event) {
   throw new IllegalStateException("Mook!");
}
```

And I can see the following error:
```
org.jboss.arquillian.container.spi.client.container.DeploymentException: Unable to start the runtime runner
	at io.quarkus.arquillian.QuarkusDeployableContainer.deploy(QuarkusDeployableContainer.java:232)
	<<REMOVED>>
Caused by: java.lang.ExceptionInInitializerError
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:84)
	at io.quarkus.arquillian.QuarkusDeployableContainer.deploy(QuarkusDeployableContainer.java:190)
	... 99 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:246)
	... 103 more
Caused by: java.lang.RuntimeException: Failed to initialize Arc
	at io.quarkus.arc.Arc.initialize(Arc.java:26)
	at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:35)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources10.deploy_0(ArcProcessor$generateResources10.zig:72)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources10.deploy(ArcProcessor$generateResources10.zig:36)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:232)
	... 103 more
Caused by: java.lang.IllegalStateException: Mook!
	at io.quarkus.arquillian.test.SimpleTest$SimpleClass.observe(SimpleTest.java:73)
	at io.quarkus.arquillian.test.SimpleTest_SimpleClass_Observer_observe_e59a6f556572ff5acee13086fbd6a12e1fcef17d.notify(SimpleTest_SimpleClass_Observer_observe_e59a6f556572ff5acee13086fbd6a12e1fcef17d.zig:153)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:282)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:267)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:217)
	at io.quarkus.arc.impl.ArcContainerImpl.init(ArcContainerImpl.java:159)
	at io.quarkus.arc.Arc.initialize(Arc.java:22)
	... 107 more

**Comment by rsearls** [comment] 2020-04-06 15:48
Yes some of the "cause by"  classes I see as well.  This issue is still the root cause never gets printer to the terminal or any log file I can find.
I have updated the project to use quarkus 1.3.1.Final and resteasy 4.5.2.Final.
This should allow you to build the project.
Here is the stacktrace I get upon setting a breakpoint on
io.quarkus.arc.Arc.initialize(Arc.java:28).  The true cause of the failure remains as 
listed in the initial report above.
Again its the reporting of the issue I need not a resolution to the error itself.

"main@1" prio=5 tid=0x1 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	  at io.quarkus.arc.Arc.initialize(Arc.java:25)
	  at io.quarkus.arc.runtime.ArcRecorder.getContainer(ArcRecorder.java:35)
	  at io.quarkus.deployment.steps.ArcProcessor$generateResources20.deploy_0(ArcProcessor$generateResources20.zig:72)
	  at io.quarkus.deployment.steps.ArcProcessor$generateResources20.deploy(ArcProcessor$generateResources20.zig:36)
	  at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:338)
	  at java.lang.Class.forName0(Class.java:-1)
	  at java.lang.Class.forName(Class.java:398)
	  at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:83)
	  at io.quarkus.arquillian.QuarkusDeployableContainer.deploy(QuarkusDeployableContainer.java:190)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:151)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$3.call(ContainerDeployController.java:118)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.executeOperation(ContainerDeployController.java:239)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deploy(ContainerDeployController.java:118)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	  at org.jboss.arquillian.container.impl.client.container.DeploymentExceptionHandler.verifyExpectedExceptionDuringDeploy(DeploymentExceptionHandler.java:47)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	  at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createDeploymentContext(ContainerDeploymentContextHandler.java:71)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	  at org.jboss.arquillian.container.impl.client.ContainerDeploymentContextHandler.createContainerContext(ContainerDeploymentContextHandler.java:54)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	  at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:92)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController$1.perform(ContainerDeployController.java:77)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachDeployment(ContainerDeployController.java:232)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.forEachManagedDeployment(ContainerDeployController.java:212)
	  at org.jboss.arquillian.container.impl.client.container.ContainerDeployController.deployManaged(ContainerDeployController.java:77)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	  at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
	  at org.jboss.arquillian.container.test.impl.client.ContainerEventController.execute(ContainerEventController.java:96)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
	  at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	  at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java:-1)
	  at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	  at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	  at java.lang.reflect.Method.invoke(Method.java:566)
	  at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
	  at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
	  at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
	  at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.beforeClass(EventTestRunnerAdaptor.java:89)
	  at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:163)
	  at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:350)
	  at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
	  at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:177)
	  at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	  at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:115)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	  at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	  at org.testng.junit.JUnit4TestRunner.start(JUnit4TestRunner.java:81)
	  at org.testng.junit.JUnit4TestRunner.run(JUnit4TestRunner.java:69)
	  at org.testng.TestRunner$1.run(TestRunner.java:689)
	  at org.testng.TestRunner.runWorkers(TestRunner.java:1014)
	  at org.testng.TestRunner.privateRunJUnit(TestRunner.java:720)
	  at org.testng.TestRunner.run(TestRunner.java:621)
	  at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	  at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	  at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	  at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	  at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	  at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	  at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	  at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	  at org.testng.TestNG.run(TestNG.java:1048)
	  at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:135)
	  at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeMulti(TestNGDirectoryTestSuite.java:198)
	  at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:94)
	  at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	  at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
	  at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
	  at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
	  at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)

**Comment by mkouba** [comment] 2020-04-07 06:16
> Could not resolve dependencies for project org.jboss.resteasy:qurakus-test-exception-reporting:jar:1.0-SNAPSHOT: Could not find artifact org.jboss.resteasy:utils-arquillian-utils:jar:4.5.0-SNAPSHOT

@rsearls ^

**Comment by rsearls** [comment] 2020-04-07 12:01
Please read the directions in the projects README.md file.
It provides directions for installing this needed archive locally.

**Comment by mkouba** [comment] 2020-04-07 12:05
@rsearls I'm sorry but where should I download this artifact? The readme says `-Dfile=FIX_THIS/lib/utils-arquillian-utils-4.5.0-SNAPSHOT.jar `...

**Comment by rsearls** [comment] 2020-04-07 12:07
The file is in the project's lib directory.

**Comment by mkouba** [comment] 2020-04-07 12:12
Ok. Thanks :man_facepalming:.

**Comment by mkouba** [comment] 2020-04-07 13:15
Your tests are using JUnit annotations but the pom.xml declares the dependency on `org.jboss.arquillian.testng:arquillian-testng-container`. When I replace this dependency with `org.jboss.arquillian.junit:arquillian-junit-container` (and remove the testng completely) I get the following error:
```
org.jboss.arquillian.container.spi.client.container.DeploymentException: Unable to start the runtime runner
	at org.jboss.resteasy.test.client.InputStreamTest.<clinit>(InputStreamTest.java:47)
```

Now in order to display the full stacktrace you'll need to set the `trimStackTrace` property to `false`. See http://maven.apache.org/surefire/maven-surefire-plugin/test-mojo.html#trimStackTrace for more information. I could see the stack because all quarkus modules have the `jboss-parent` where the property is already set to `false`. And then you should see something like:

```
Caused by: java.util.ServiceConfigurationError: org.apache.logging.log4j.spi.Provider: org.apache.logging.log4j.core.impl.Log4jProvider not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
```

**Comment by rsearls** [comment] 2020-04-07 13:49
I've made the changes and see  .. DeploymentException ..
I do not see .. ServiceConfigurationError ...
Where should that be appearing?

**Comment by mkouba** [comment] 2020-04-07 14:12
You should see the full stack. Pls update your repo so that I can verify the config.

**Comment by rsearls** [comment] 2020-04-07 14:46
Update complete.

**Comment by gastaldi** [comment] 2020-10-29 17:44
This seems to have been resolved. Closing now

**Closed by gastaldi** 2020-10-29 17:44 UTC
Labels: area/testing, kind/bug
