### ISSUE TITLE
quarkus code reload doesn't work if there is generated avro specific class

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#19276] opened 2021-08-06 16:53 UTC
### Describe the bug

When use confluent schema registry to consume Kafka topic, I put corresponding avsc file in src/main/avro/,  avro-maven-plugin will generated classes.  If I change **any Java** source file in the project, "quarkus dev" automatically regenerate the avro specific classes and load them,  but this will fail with exception **on consuming new message**:

```
2021-08-07 00:34:49,166 ERROR [io.sma.rea.mes.provider] (pool-1-thread-1) SRMSG00201: Error caught while processing a message: java.lang.ClassCastException: class mysql.my_db.my_table.Envelope cannot be cast to class mysql.my_db.my_table.Envelope (mysql.my_db.my_table.Envelope is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @abff8b7; mysql.my_db.my_table.Envelope is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1d08c389)
        at com.xxx.yyy.user.mapping.sync.XxxUserSyncer_SmallRyeMessagingInvoker_consume_11740f37c23f2cf653c1801df3fb82cf9411aec1.invoke(XxxUserSyncer_SmallRyeMessagingInvoker_consume_11740f37c23f2cf653c1801df3fb82cf9411aec1.zig:46)
        at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:94)
        at io.smallrye.reactive.messaging.SubscriberMediator.lambda$null$15(SubscriberMediator.java:249)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:68)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenCompleteStage(CompletableFuture.java:883)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:2251)
        at java.base/java.util.concurrent.CompletableFuture.whenComplete(CompletableFuture.java:143)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forward(UniCreateFromCompletionStage.java:51)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:35)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.groups.UniSubscribe.withSubscriber(UniSubscribe.java:50)
        at io.smallrye.mutiny.groups.UniSubscribe.with(UniSubscribe.java:90)
        at io.smallrye.mutiny.operators.uni.UniSubscribeToCompletionStage.subscribe(UniSubscribeToCompletionStage.java:29)
        at io.smallrye.mutiny.groups.UniSubscribe.asCompletionStage(UniSubscribe.java:123)
        at io.smallrye.mutiny.Uni.subscribeAsCompletionStage(Uni.java:136)
        at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningAUni$16(SubscriberMediator.java:255)
        at io.smallrye.mutiny.streams.stages.FlatMapCompletionStageFactory$FlatMapCompletionStage.lambda$apply$0(FlatMapCompletionStageFactory.java:46)
        at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply(SlowContextualFunction.java:21)
        at io.smallrye.mutiny.groups.MultiOnItem.lambda$transformToUni$6(MultiOnItem.java:256)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:176)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.streams.utils.ConnectableProcessor.onNext(ConnectableProcessor.java:122)
        at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
        at org.eclipse.microprofile.reactive.streams.operators.CompletionSubscriber$1DefaultCompletionSubscriber.onNext(CompletionSubscriber.java:85)
        at io.smallrye.reactive.messaging.SubscriberMediator$1.onNext(SubscriberMediator.java:118)
        at io.smallrye.reactive.messaging.SubscriberMediator$1.onNext(SubscriberMediator.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
        at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
        at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
        at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:595)
        at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
        at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:77)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
        at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
        at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:43)
        at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
        at io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:169)
        at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
        at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
        at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
        at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor.lambda$intercept$0(DevModeSupportConnectorFactoryInterceptor.java:42)
        at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
        at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
        at io.quarkus.smallrye.reactivemessaging.runtime.devmode.ReactiveMessagingHotRetSetup$OnMessage$1.run(ReactiveMessagingHotReplacementSetup.java:44)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

pom.xml:
```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xxx.yyy</groupId>
    <artifactId>user-mapping</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>2.1.1.Final</quarkus.platform.version>
        <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
        <avro.version>1.10.2</avro.version>
    </properties>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-mysql-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
        </dependency>
        <!-- required by io.confluent:kafka-avro-serializer -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-avro-serializer</artifactId>
            <version>6.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.ws.rs</groupId>
                    <artifactId>jakarta.ws.rs-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <parameters>${maven.compiler.parameters}</parameters>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.avro</groupId>
                <artifactId>avro-maven-plugin</artifactId>
                <version>${avro.version}</version>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>schema</goal>
                        </goals>
                        <configuration>
                            <enableDecimalLogicalType>true</enableDecimalLogicalType>
                            <stringType>String</stringType>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                        <maven.home>${maven.home}</maven.home>
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>
</project>
```

* Quarkus 2.1.1.Final
* OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Expected behavior

quarkus should correctly reload and there is no error on consuming new message.

### Actual behavior

quarkus throws exception.

### How to Reproduce?

change any code to make `quarkus dev` reload,  publish message to kafka to make quarkus consume.

### Output of `uname -a` or `ver`
```
Darwin aaa-mbp.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64
```
### Output of `java -version`

```
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)
```

### Quarkus version or git rev

Client Version 2.1.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
$ ./mvnw --version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /Users/aaa/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home 
Default locale: en_CN, platform encoding: UTF-8
OS name: "mac os x", version: "11.2", arch: "x86_64", family: "mac"
```

**Comment by geoand** [comment] 2021-08-06 16:57
cc @Ladicek @ozangunalp

**Comment by Dieken** [comment] 2021-08-06 16:59
@quarkus-bot  I don't think this is related to Kubernetes.

**Comment by ozangunalp** [comment] 2021-08-06 17:05
This seems like a duplicate of https://github.com/quarkusio/quarkus/issues/18776. Should have been fixed by https://github.com/quarkusio/quarkus/pull/19043 in 2.1.1.Final

**Comment by Dieken** [comment] 2021-08-06 17:18
@ozangunalp  Thanks, very happy to know it has been fixed.  Unluckily it's actually not merged into 2.1.1.Final.

And I doubt that fix may not work for confluent schema registry,  I find quarkus won't automatically compile avsc files when I **don't** use Apicurio registry,  see pom.xml above, I have to explicitly add avro-maven-plugin.

**Comment by ozangunalp** [comment] 2021-08-06 17:25
I think the fix was backported to 2.1.1.Final but as you are saying wouldn't help for classes generated with avro-maven-plugin.
 Did you try adding `quarkus-avro` extension to your project instead of using the `avro-maven-plugin` ?

**Comment by Dieken** [comment] 2021-08-06 17:41
My bad, I found https://github.com/quarkusio/quarkus/pull/19043/commits/e5ac1e25a255b6ef2de2fed27645eff010379883 didn't mention tag 2.1.1.Final in the commit message,  I thought it wasn't backported by mistake.

Just add `quarkus-avro` extension,  it does work.  The example https://github.com/quarkusio/quarkus-quickstarts/blob/main/kafka-avro-schema-quickstart/pom.xml#L49 doesn't explicitly introduce it, I thought Quarkus have automatically include quarkus-avro.

Thank you very much for your quick support,  it's amazing to find Quarkus Just Works™️.

**Closed** 2021-08-06 17:41 UTC
Labels: kind/bug, area/devmode

**Comment by Ladicek** [comment] 2021-08-09 07:11
`quarkus-apicurio-registry-avro` _does_ automatically bring in `quarkus-avro`: https://github.com/quarkusio/quarkus/blob/2.1.1.Final/extensions/apicurio-registry-avro/runtime/pom.xml#L26-L29, so that should be enough?

**Comment by Dieken** [comment] 2021-08-10 14:51
@Ladicek   I use Confluent Schema Registry server,  according to the Quarkus guide, I mustn't use quarkus-apicurio-registry-avro, I guess this client side jar supports only Apicurio server although the Apicurio server supports Confluent Schema Registry server.

I would like Quarkus to support Confluent Schema Registry with an easy to use extension and corresponding dev service, I created a feature request for the dev service part: https://github.com/quarkusio/quarkus/issues/19277

**Comment by Ladicek** [comment] 2021-08-10 14:55
I'd love to have an extension for Confluent Schema Registry, but they don't publish artifacts to Maven Central, so it isn't really possible :-(

**Comment by Ladicek** [comment] 2021-08-10 14:59
That said, our documentation should say that `quarkus-avro` should be present. I'll submit a PR.

**Comment by Dieken** [comment] 2021-08-10 15:01
The code is open source: https://github.com/confluentinc/schema-registry

Maybe you can publish artifiacts to Redhat own public maven server if it exists😄

About the dev services,  a slim docker image is enough, no need to publish to maven centra. Anyway other dev services already depend on Docker although schema registry seems to be in pure Java.

**Comment by Dieken** [comment] 2021-08-10 15:03
> That said, our documentation should say that `quarkus-avro` should be present. I'll submit a PR.

That's very helpful, thanks!

Please also clarify those "avro.codegen.*" properties must be put in `pom.xml`, not in `application.properties`,  I spent about two days to realize that😭

@Ladicek

**Comment by Ladicek** [comment] 2021-08-10 15:08
I'm pretty sure we don't want to (and shouldn't) rebuild Confluent artifacts. That would just fragment the ecosystem.

Regarding `avro.codegen.*` properties, do you refer to https://quarkus.io/guides/kafka-schema-registry-avro#avro-code-generation-details? If so, I think they _should_ be in `application.properties`, no idea why they should be in `pom.xml` (though that would also work).

**Comment by Dieken** [comment] 2021-08-10 16:32
my pom.xml for your information:

```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.xxx.yyy</groupId>
    <artifactId>zzz</artifactId>
    <version>1.0.0-SNAPSHOT</version>

    <properties>
        <compiler-plugin.version>3.8.1</compiler-plugin.version>
        <maven.compiler.parameters>true</maven.compiler.parameters>
        <maven.compiler.source>11</maven.compiler.source>
        <maven.compiler.target>11</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
        <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
        <quarkus.platform.version>2.1.1.Final</quarkus.platform.version>
        <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
        <avro.codegen.enableDecimalLogicalType>true</avro.codegen.enableDecimalLogicalType>
    </properties>

    <repositories>
        <repository>
            <id>confluent</id>
            <url>https://packages.confluent.io/maven/</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>${quarkus.platform.artifact-id}</artifactId>
                <version>${quarkus.platform.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-reactive-mysql-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kubernetes</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-health</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-openapi</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-flyway</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mysql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-micrometer-registry-prometheus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-avro</artifactId>
        </dependency>
        <!-- required by io.confluent:kafka-avro-serializer -->
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-rest-client-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.confluent</groupId>
            <artifactId>kafka-avro-serializer</artifactId>
            <version>6.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>jakarta.ws.rs</groupId>
                    <artifactId>jakarta.ws.rs-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>${quarkus.platform.group-id}</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.platform.version}</version>
                <extensions>true</extensions>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                            <goal>generate-code</goal>
                            <goal>generate-code-tests</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <parameters>${maven.compiler.parameters}</parameters>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemPropertyVariables>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        <maven.home>${maven.home}</maven.home>
                    </systemPropertyVariables>
                </configuration>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                                        <maven.home>${maven.home}</maven.home>
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
            <properties>
                <quarkus.package.type>native</quarkus.package.type>
            </properties>
        </profile>
    </profiles>
</project>
```

**Comment by Dieken** [comment] 2021-08-10 17:12
This can be easily recurred:

```sh
quarkus create -P io.quarkus.platform:quarkus-bom:2.1.1.Final
...add io.quarkus:quarkus-avro to pom.xml "<dependencies>" section...
echo "avro.codegen.enableDecimalLogicalType=true" >>  src/main/resources/application.properties
```

$ cat src/main/avro/movie.avsc 
```json
{
  "namespace": "org.acme.kafka.quarkus",
  "type": "record",
  "name": "Movie",
  "fields": [
    {
      "name": "title",
      "type": "string"
    },
    {
      "name": "year",
      "type": "int"
    },
    {
      "default" : null,
      "name" : "nav",
      "type" : [
        "null",
        {
          "connect.name" : "org.apache.kafka.connect.data.Decimal",
          "connect.parameters" : {
            "connect.decimal.precision" : "7",
            "scale" : "4"
          },
          "connect.version" : 1,
          "logicalType" : "decimal",
          "precision" : 7,
          "scale" : 4,
          "type" : "bytes"
        }
      ]
    }
  ]
}
```

```sh
quarkus build
grep getNav target/generated-sources/avsc/org/acme/kafka/quarkus/Movie.java
  public java.nio.ByteBuffer getNav() {
    public java.nio.ByteBuffer getNav() {
```

After `<avro.codegen.enableDecimalLogicalType>true</avro.codegen.enableDecimalLogicalType>` is added to pom.xml "properties" section:
```sh
rm target
quarkus build
grep getNav target/generated-sources/avsc/org/acme/kafka/quarkus/Movie.java
  public java.math.BigDecimal getNav() {
    public java.math.BigDecimal getNav() {
```

**Comment by Ladicek** [comment] 2021-08-11 07:41
OK, that sounds weird. Maybe the config support in codegen is broken? I'm unfortunately not well versed in that area; I guess this will have to wait for @michalszynkiewicz (when he's back from vacation :-) ).

**Comment by Ladicek** [comment] 2021-08-11 12:01
Ah and for the record, the PR to improve documentation slightly is here: https://github.com/quarkusio/quarkus/pull/19320

**Comment by Dieken** [comment] 2021-08-11 14:00
> Ah and for the record, the PR to improve documentation slightly is here: #19320

Thanks, could you also document how to configure SSL for Kafka? or even more properties documented at https://kafka.apache.org/documentation/#consumerconfigs and https://kafka.apache.org/documentation/#producerconfigs?

I guess they are `mp.messaging.[incoming|outgoing].<CHANNEL>.<KAFKA_CONFIG>`,  for example:

```
mp.messaging.incoming.my_topic.security.protocol=SSL
mp.messaging.incoming.my_topic.ssl.truststore.location=my-ca.p12
mp.messaging.incoming.my_topic.ssl.truststore.type=PKCS12
mp.messaging.incoming.my_topic.ssl.truststore.password=xxx
mp.messaging.incoming.my_topic.ssl.keystore.location=my-keystore.p12
mp.messaging.incoming.my_topic.ssl.keystore.type=PKCS12
mp.messaging.incoming.my_topic.ssl.keystore.password=xx
mp.messaging.incoming.my_topic.ssl.key.password=xxx
```

Both documentation of Quarkus and Smallrye messaging don't mention those configuration.

**Comment by Ladicek** [comment] 2021-08-11 14:22
That is correct, this is exactly how config properties are passed down to the Kafka client. I'll submit a PR to SmallRye Reactive Messaging docs, as it still wrongly says that the Vert.x Kafka client is used underneath. Thanks!

**Comment by Ladicek** [comment] 2021-08-11 14:50
Added here: https://github.com/smallrye/smallrye-reactive-messaging/pull/1347

I didn't include specific examples for SSL, because I have no experience using it. If you feel like submitting a PR, that would be very much appreciated! (I think I would just copy the approach we use for documenting Kerberos auth.)

**Comment by Dieken** [comment] 2021-08-12 15:41
> OK, that sounds weird. Maybe the config support in codegen is broken? I'm unfortunately not well versed in that area; I guess this will have to wait for @michalszynkiewicz (when he's back from vacation :-) ).

https://github.com/quarkusio/quarkus/blob/main/devtools/maven/src/main/java/io/quarkus/maven/GenerateCodeMojo.java#L73

```java
            initAndRun.invoke(null, deploymentClassLoader,
                    PathsCollection.of(sourcesDir),
                    generatedSourcesDir(test),
                    buildDir().toPath(),
                    sourceRegistrar,
                    curatedApplication.getAppModel(),
                    mavenProject().getProperties());               // <----  only properties in pom.xml
```

This is why `quarkus-avro` extension can't use configuration in `application.properties`. According to code in `quarkus/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment`,  maybe the `quarkus-avro` extension should use `@ConfigItem` to obtain configuration.

@michalszynkiewicz  @Ladicek

**Comment by Ladicek** [comment] 2021-08-16 07:05
Thanks @mbrembilla for filing #19389, let's move the conversation there.

**Comment by ayushdgupta** [comment] 2023-04-12 15:13
How to change the path of the generated java files from the avro schema in build.gradle?
