### ISSUE TITLE
quarkus.hibernate-orm.database.generation=update not working

### ISSUE THREAD

**Issue by serviceability** [quarkusio/quarkus#31088] opened 2023-02-10 19:32 UTC
### Describe the bug

The setting

**quarkus.hibernate-orm.database.generation=drop-and-create**

works by creating the database schema, however, the config

**quarkus.hibernate-orm.database.generation=update**

which in previous versions also created the scheme stopped creating (using as database postgress 13.3 )

### Expected behavior

Still create the database schema

### Actual behavior

Does not create the schema causing issues during the dev

### How to Reproduce?

Just set the config
quarkus.hibernate-orm.database.generation=update
 in a database without the schema defined in 
 quarkus.hibernate-orm.database.default-schema=altair_user

### Output of `uname -a` or `ver`

Linux fedora 6.1.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Feb  6 23:56:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

2.16.2_final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------
Gradle 7.3
------------------------------------------------------------

Build time:   2021-11-09 20:40:36 UTC
Revision:     96754b8c44399658178a768ac764d727c2addb37

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Red Hat, Inc. 17.0.6+10)
OS:           Linux 6.1.10-200.fc37.x86_64 amd64

**Comment by yrodiere** [comment] 2023-02-13 08:55
Hey,

Thanks for reporting, but I believe this is a duplicate of #30086, so I'll close this ticket.

If not, feel free to comment here and explain why it's different. Thanks.

**Closed by yrodiere** 2023-02-13 08:55 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm

**Comment by yrodiere** [comment] 2023-02-13 08:57
Alternatively this could be a duplicate of #25244 .
