### ISSUE TITLE
Swagger-ui dont format correctly java.lang.LocalTime

### ISSUE THREAD

**Issue by zakhdar** [quarkusio/quarkus#6065] opened 2019-12-09 19:49 UTC
**Describe the bug**

swagger-ui dont take care of jackson objectMapper/@jsonformat , 
let's consider with have a REST endpoint that consume a POJO with LocalTime as attribute with correct @JsonFormat
We have configured ObjectMapper, but in swagger-ui java.time.LocalTime  is not represented by a String but has an entity 

Exemple of swagger-ui output 
```json
{
      "heureDebutActivite": {
        "hour": "string",
        "minute": "string",
        "nano": 0,
        "second": "string"
      },
      "heureFinActivite": {
        "hour": "string",
        "minute": "string",
        "nano": 0,
        "second": "string"
      }
    }
```

POJO 
```java
public class Site {

	...

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm:ss")
	public LocalTime heureDebutActivite;

	@JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "HH:mm:ss")
	public LocalTime heureFinActivite;

	public Site() {
		// TODO Auto-generated constructor stub
	}
	
	...
}
```
Object Mapper configuration

```java
import javax.inject.Singleton;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.SerializationFeature;
import com.fasterxml.jackson.datatype.jdk8.Jdk8Module;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import com.fasterxml.jackson.module.paramnames.ParameterNamesModule;

import io.quarkus.jackson.ObjectMapperCustomizer;

@Singleton
public class RegisterCustomModuleCustomizer implements ObjectMapperCustomizer {

    public void customize(ObjectMapper mapper) {
        mapper.registerModule(new ParameterNamesModule())
        .registerModule(new Jdk8Module())
        .registerModule(new JavaTimeModule())
        .disable(SerializationFeature.WRITE_DATES_AS_TIMESTAMPS)
        .configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false)
        .setSerializationInclusion(JsonInclude.Include.ALWAYS);
    }
}
```

pom.xml

```xml
...
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-mongodb-panache</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-validator</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jdk8</artifactId>
		</dependency>
		<dependency>
			<groupId>com.fasterxml.jackson.datatype</groupId>
			<artifactId>jackson-datatype-jsr310</artifactId>
		</dependency>
...
```

**Expected behavior**
LocalTime can be represented by ISO string  (and  pattern specififed in @JsonFormat)  in swagger ui 

**Actual behavior**
LocalTime not correctly formatted in swagger ui 

**To Reproduce**
1. create a quarkus project (quarkus version 1.0.1.Final)  
2. Create a POJO with LocalTime as attribute
2. Create a simple endpoitn that consume this pojo
3. Configure Jackson objectMapper with JavaTimeModule  
3. Test your endpoint with swagger ui 

**Environment (please complete the following information):**
windows 10
Quarkus version 1.0.1.Final
jdk:8

**Comment by gsmet** [comment] 2019-12-10 10:27
/cc @EricWittmann 

Not sure OpenAPI supports Jackson specific stuff, though.

**Comment by zakhdar** [comment] 2019-12-10 11:27
I think it's  openAPi generator config  [https://stackoverflow.com/questions/40525468/java-8-localdate-displaying-in-swagger](url) , the question is now,  it's possible to configure openapi generator in Quarkus ?

**Comment by EricWittmann** [comment] 2019-12-11 09:32
The Microprofile OpenAPI spec doesn't really have much to say about how to handle specific java types and annotations.  But the SmallRye OpenAPI implementation does try to do sensible things whenever possible - in general as well as specifically in regard to data types.  There are, of course, a lot of data types and not all of them are currently handled ideally.  This is a good example.  

If @MikeEdgar wants to provide additional insight, as he is closer to that code than I am, that'd be great.  But for types that aren't already being handled ideally, we have (or will soon have) the ability to provide custom mappings.  So in this case you'd be able to map the `LocalTime` to a string with an ISO pattern.

It might be also useful to update SmallRye OpenAPI to do that by default for certain java.time classes.

**Comment by MikeEdgar** [comment] 2019-12-11 14:48
SmallRye OpenAPI currently supports `date` and `date-time`, but not `time` for the `java.time` classes, likely because they are not mentioned in the OpenAPI spec itself. As @EricWittmann suggested, it would probably be good to support time, following along with the formats outlined by [RFC3339](https://xml2rfc.ietf.org/public/rfc/html/rfc3339.html#anchor14) for `partial-time` and/or `full-time`.

In the short term @zakhdar,  you should be able to get your expected output by applying a `@Schema` attribute to each of your `LocalTime` fields with `implementation` of `String.class` and your desired `format`. Please also open an issue in [smallrye-open-api](https://github.com/smallrye/smallrye-open-api) to look at adding out-of-box support for `LocalTime`.

**Comment by zakhdar** [comment] 2019-12-11 17:55
Thank you @EricWittmann  and @MikeEdgar  for your information , i will use @Schema as workaround and  open an issue in smallrye-open-api for adding out-ofbox support for LocalTime. thk you for your support

**Comment by loicmathieu** [comment] 2020-05-01 14:45
@zakhdar I saw that the PR on smallrye-openapi to fix that has been merged.
Can we close this one ?

**Comment by csfercoci** [comment] 2020-05-29 18:54
The same issue for JODATIME, still not fixed

**Comment by MikeEdgar** [comment] 2020-05-29 19:47
@csfercoci - are you saying the issue is still occurring for `LocalTime` or that it is also happening for Joda types? If it is happening for Joda types, there has been no change in the scanner to support them.

P.S. do you have control over the code using Joda-Time types? The recommendation is that code using Joda-Time on JDK 8 or later migrate to `java.time`.

**Comment by loicmathieu** [comment] 2020-07-31 11:55
Closing this one as it has been fixed on Smallrye OpenAPI side.

**Closed by loicmathieu** 2020-07-31 11:55 UTC
Labels: kind/bug
