### ISSUE TITLE
Crash during mvn io.quarkus-maven-plugin:2.1.2.Final:create

### ISSUE THREAD

**Issue by wmeints** [quarkusio/quarkus#19491] opened 2021-08-19 06:19 UTC
### Describe the bug

The maven plugin crashes in Windows Powershell when I try to create a new project. 

### Actual behavior

The maven process crashes with the following exception:

```
com.google.inject.ProvisionException: Unable to provision, see the following errors:

1) Error injecting constructor, java.lang.NoSuchMethodError: 'java.io.OutputStream org.fusesource.jansi.AnsiConsole.wrapOutputStream(java.io.OutputStream)'
  at io.quarkus.maven.components.Prompter.<init>(Unknown Source)
  while locating io.quarkus.maven.components.Prompter
  while locating io.quarkus.maven.CreateProjectMojo

...
```

### How to Reproduce?

Open up a Powershell instance.
Then execute the following command:

```
mvn io.quarkus:quarkus-maven-plugin:2.1.2.Final:create `
-DprojectGroupId="com.infosupport.pitstop.customermanagement" `
-DprojectArtifactId="customer-management" `
-DclassName="com.infosupport.pitstop.customermanagement.CustomersResource" `
-Dpath="customer-management"clear
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1110]

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-16.0.1+9 (build 16.0.1+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-16.0.1+9 (build 16.0.1+9, mixed mode, sharing)

### Quarkus version or git rev

2.1.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)

### Additional information

Powershell version: 5.1.19041.1023

**Comment by gsmet** [comment] 2021-08-19 09:05
I can't reproduce it on Linux so it might be Windows specific. @jaikiran do you still have your Windows box around?

**Comment by jaikiran** [comment] 2021-08-19 10:40
Hello @gsmet, I had a quick look and this indeed is reproducible on Windows (at least with powershell, I didn't try the usual command prompt way).

What's happening here is that, the Maven tool is trying to instantiate and inject into `io.quarkus.maven.CreateProjectMojo`. One of the injections into it is the `io.quarkus.maven.components.Prompter`[1]. So the Maven framework code goes and tries to instantiate this `io.quarkus.maven.components.Prompter` class. The constructor of this class leads to the instantiation of `jline.console.ConsoleReader` class which comes from the `jline` library/jar. That library internally leads to a call to `jline.AnsiWindowsTerminal.detectAnsiSupport()` method which ultimately class a `wrapOutputStream` method on the `org.fusesource.jansi.AnsiConsole` class. 

The problem here is that, the version of `org.fusesource.jansi.AnsiConsole` class being picked up from Maven installation (I'm not talking about the Maven repository but Maven installation itself) doesn't have this method. The version being shipped internally in Maven of this jansi jar is 2.3.4:
```
[0.311s][info][class,load] org.fusesource.jansi.AnsiConsole source: file:/C:/apache-maven-3.8.2/lib/jansi-2.3.4.jar
```
and this version doesn't have this method. 
What's interesting is that the jline library "shades" the jansi classes as can be seen here[2]. So it appears that the classloader is picking up the jansi classes from Maven installation instead of picking it up from within this shaded jar. It's possible and in fact looking at the classloading logs that I gathered, the jansi classes get loaded from that Maven installation jar very early in the bootstrapping of Maven which causes it to ignore the shaded version of jansi classes from jline jar. In short, the jline jar version 2.14.6 that gets used isn't compatible with the jansi version 2.3.4 that's shipped in Maven installation.

I haven't yet checked anything about jline docs or versions that might be compatible with the jansi version shipped in Maven. Nor have I thought of any classloading workarounds for now.


[1] https://github.com/quarkusio/quarkus/blob/2.1.2.Final/devtools/maven/src/main/java/io/quarkus/maven/CreateProjectMojo.java#L166
[2] https://repo1.maven.org/maven2/jline/jline/2.14.6/jline-2.14.6.pom

**Comment by jaikiran** [comment] 2021-08-19 10:41
For the sake of reference for others, here's the actual stacktrace it generates:

```
Caused by: java.lang.NoSuchMethodError: 'java.io.OutputStream org.fusesource.jansi.AnsiConsole.wrapOutputStream(java.io.OutputStream)'
    at jline.AnsiWindowsTerminal.detectAnsiSupport (AnsiWindowsTerminal.java:57)
    at jline.AnsiWindowsTerminal.<init> (AnsiWindowsTerminal.java:27)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstanceWithCaller (Constructor.java:499)
    at java.lang.reflect.ReflectAccess.newInstance (ReflectAccess.java:128)
    at jdk.internal.reflect.ReflectionFactory.newInstance (ReflectionFactory.java:350)
    at java.lang.Class.newInstance (Class.java:642)
    at jline.TerminalFactory.getFlavor (TerminalFactory.java:205)
    at jline.TerminalFactory.create (TerminalFactory.java:96)
    at jline.TerminalFactory.get (TerminalFactory.java:180)
    at jline.TerminalFactory.get (TerminalFactory.java:186)
    at jline.console.ConsoleReader.<init> (ConsoleReader.java:244)
    at jline.console.ConsoleReader.<init> (ConsoleReader.java:236)
    at jline.console.ConsoleReader.<init> (ConsoleReader.java:224)
    at io.quarkus.devtools.utils.Prompter.<init> (Prompter.java:20)
    at io.quarkus.maven.components.Prompter.<init> (Prompter.java:17)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0 (Native Method)
    at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance (NativeConstructorAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance (DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstanceWithCaller (Constructor.java:499)
    at java.lang.reflect.Constructor.newInstance (Constructor.java:480)
    at com.google.inject.internal.DefaultConstructionProxyFactory$ReflectiveProxy.newInstance (DefaultConstructionProxyFactory.java:126)
    at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:114)
    at com.google.inject.internal.ConstructorInjector.access$000 (ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call (ConstructorInjector.java:98)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:93)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.eclipse.sisu.plexus.PlexusRequirements$RequirementProvider.get (PlexusRequirements.java:250)
    at org.eclipse.sisu.plexus.ProvidedPropertyBinding.injectProperty (ProvidedPropertyBinding.java:48)
    at org.eclipse.sisu.bean.BeanInjector.injectMembers (BeanInjector.java:52)
    at com.google.inject.internal.MembersInjectorImpl.injectMembers (MembersInjectorImpl.java:160)
    at com.google.inject.internal.ConstructorInjector.provision (ConstructorInjector.java:124)
    at com.google.inject.internal.ConstructorInjector.access$000 (ConstructorInjector.java:32)
    at com.google.inject.internal.ConstructorInjector$1.call (ConstructorInjector.java:98)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ConstructorInjector.construct (ConstructorInjector.java:93)
    at com.google.inject.internal.ConstructorBindingImpl$Factory.get (ConstructorBindingImpl.java:306)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at com.google.inject.internal.InjectorImpl.getInstance (InjectorImpl.java:1086)
    at org.eclipse.sisu.space.AbstractDeferredClass.get (AbstractDeferredClass.java:48)
    at com.google.inject.internal.ProviderInternalFactory.provision (ProviderInternalFactory.java:85)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision (InternalFactoryToInitializableAdapter.java:57)
    at com.google.inject.internal.ProviderInternalFactory$1.call (ProviderInternalFactory.java:66)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:112)
    at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision (ProvisionListenerStackCallback.java:127)
    at com.google.inject.internal.ProvisionListenerStackCallback.provision (ProvisionListenerStackCallback.java:66)
    at com.google.inject.internal.ProviderInternalFactory.circularGet (ProviderInternalFactory.java:61)
    at com.google.inject.internal.InternalFactoryToInitializableAdapter.get (InternalFactoryToInitializableAdapter.java:47)
    at com.google.inject.internal.InjectorImpl$1.get (InjectorImpl.java:1050)
    at org.eclipse.sisu.inject.Guice4$1.get (Guice4.java:162)
    at org.eclipse.sisu.inject.LazyBeanEntry.getValue (LazyBeanEntry.java:81)
    at org.eclipse.sisu.plexus.LazyPlexusBean.getValue (LazyPlexusBean.java:51)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:263)
    at org.codehaus.plexus.DefaultPlexusContainer.lookup (DefaultPlexusContainer.java:255)
    at org.apache.maven.plugin.internal.DefaultMavenPluginManager.getConfiguredMojo (DefaultMavenPluginManager.java:520)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:124)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:972)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:78)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:567)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
```

**Comment by jaikiran** [comment] 2021-08-19 10:44
The reason why it might not be reproducible on Linux is probably because of classloading order, where on Windows, for whatever reason the jansi jar from Maven installation gets loaded very early during some other code path, unlike Linux.

**Comment by jaikiran** [comment] 2021-08-19 13:41
@gsmet, I don't think there's a easy way out here. I see that https://github.com/quarkusio/quarkus/blob/main/independent-projects/tools/devtools-common/src/main/java/io/quarkus/devtools/utils/Prompter.java uses JLine 2.x which has been EOLed long back. Moving to JLine 3.x should solve this issue since JLine 3.x uses a very closer version of Jansi to what Maven ships with. I am not too familiar with this `Prompter` class, but from the looks of it, moving this code to newer 3.x shouldn't be that hard.

**Comment by gastaldi** [comment] 2021-08-19 13:52
It looks like the groupId changed in JLine 3.x: https://mvnrepository.com/artifact/org.jline/jline/3.20.0

**Comment by loetscher** [comment] 2021-08-19 13:54
A downgrade of the used maven version worked for me.
This setup is working:

_Apache Maven **3.6.3** (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\develop\tools\apache-maven\bin\..
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"_

With this setup I got the already mentioned stacktrace :

_Apache Maven **3.8.2** (ea98e05a04480131370aa0c110b8c54cf726c06f)
Maven home: C:\develop\tools\apache-maven
Java version: 11.0.8, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.8.10-hotspot
Default locale: de_CH, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"_

It took me some time to find this workaround, as I thought I should update to maven 3.8.2 to be able to generate the bootstrapping project as https://quarkus.io/guides/getting-started#prerequisites mentions explicitly to to use maven 3.8.1+ ...

**Comment by jaikiran** [comment] 2021-08-19 13:58
>A downgrade of the used maven version worked for me.
>This setup is working:

>Apache Maven 3.6.3

I had a quick look, that version of Maven ships with Jansi 1.x (specifically 1.17.1) which is the version that JLine 2.14.6 works fine with.

> It took me some time to find this workaround, as I thought I should update to maven 3.8.2

For a project like Quarkus which heavily relies on Maven for some of its core stuff, I wouldn't recommend downgrading the Maven version.  It might have solved this specific issue but it's highly likely you might run into various other issues in the application later on.

**Comment by loetscher** [comment] 2021-08-19 14:06
> For a project like Quarkus which heavily relies on Maven for some of its core stuff, I wouldn't recommend downgrading the Maven version. It might have solved this specific issue but it's highly likely you might run into various other issues in the application later on.

I absolutely agree. The downgrade was only made for "Bootstrapping the project" so I could continue with the Getting Started tutorial.

**Comment by gsmet** [comment] 2021-08-19 14:19
I'd say let's try to move to JLine 3 and see how it goes.

**Comment by gastaldi** [comment] 2021-08-19 14:22
TBH I am not sure JLine is necessary at all in `Prompter`. @jaikiran are you looking into this already? Otherwise I can have a look

**Comment by jaikiran** [comment] 2021-08-19 14:24
> TBH I am not sure JLine is necessary at all in `Prompter`. @jaikiran are you looking into this already? Otherwise I can have a look

I'll open a PR shortly and we can decide how to go about it.

**Comment by jaikiran** [comment] 2021-08-19 14:32
@gastaldi FYI - https://github.com/quarkusio/quarkus/pull/19510

**Comment by jaikiran** [comment] 2021-08-19 14:56
@wmeints @loetscher, till we sort out this issue properly, a more reliable workaround/fix is to use Maven 3.8.1. This is the version that Quarkus CI uses to test/build the project and we haven't seen issue in this version. It looks like it's only the latest released Maven 3.8.2 which is impacted. See my comment here for details https://github.com/quarkusio/quarkus/pull/19510#issuecomment-901982879

If either of you do use this 3.8.1 version of Maven to test your use case, please do let us know if it works fine in context of this issue.

**Comment by gastaldi** [comment] 2021-08-19 15:00
I can confirm that this does not occur with 3.8.1. This only occurs when Maven 3.8.2 is used

**Comment by jaikiran** [comment] 2021-08-19 15:06
Thank you both for testing.

**Comment by wmeints** [comment] 2021-08-19 16:38
Thanks for testing this, I'm going to revert to maven 3.8.1

**Comment by wmeints** [comment] 2021-08-20 06:08
I've found another workaround for people who run into this issue: If you have WSL2 on Windows 10, you can create your project in WSL2 on the Windows filesystem. As a bonus, if you're using the latest version of IntelliJ you can create it on the Linux filesystem and edit it too.

**Closed** 2021-08-21 12:35 UTC
Labels: kind/bug, area/maven, env/windows
