### ISSUE TITLE
Quarkus Mongo Client - MongoClientCustomizer

### ISSUE THREAD

**Issue by lucini** [quarkusio/quarkus#44241] opened 2024-10-31 21:21 UTC
### Describe the bug

    /**
     * Configures the MongoDB server addressed (one if single mode).
     * The addresses are passed as {@code host:port}.
     */
    @ConfigItem(defaultValue = "127.0.0.1:27017")
    public List<String> hosts;

Quarkus pre configure hosts of mongoclient with defaultValue **127.0.0.1:27017**, when i dont set my connectionstring on properties and create a custom mongoclient config implementing the interface MongoClientCustomizer and setting the connectionstring with SRV host, the driver throw an exception because it thinks that the mongoclient is configured with two types of connectionstring.

### Expected behavior

Permit creating my customized connection without setting application.properties with the host.

### Actual behavior

I need to set the mongodb host on application.properties with no use in my application.

### How to Reproduce?

1. Create a class that implements MongoCustomizer:
```java
@Override
    public MongoClientSettings.Builder customize(MongoClientSettings.Builder builder) {

            builder.applyConnectionString(
                    new com.mongodb.ConnectionString(
                            "mongodb+srv://hosttt"
                    )
            );
 

        return builder;
    }
```
2. dont set mongoclient configuration on application.properties.

**Comment by geoand** [comment] 2024-11-01 08:59
Thanks for reporting, but I could not reproduce this problem - no exception  like the one mentioned was thrown.

**Comment by hemanth-web-dev** [comment] 2024-11-04 09:02
It appears that Quarkus pre-configures MongoDB with a default host (`127.0.0.1:27017`) which causes a conflict when using a custom `MongoClientCustomizer` that specifies an SRV connection string. This conflict occurs because the Mongo client ends up with two types of connection strings. To address this, set `quarkus.mongodb.connection-string` in `application.properties` to an empty value (`quarkus.mongodb.connection-string=`), which should prevent Quarkus from applying the default host configuration, allowing your custom SRV connection string to work without issues. This approach allows you to fully customize the client without interference from the default host setting.

**Comment by geoand** [comment] 2024-11-04 09:04
As I said, I could not reproduce that problem

**Comment by geoand** [comment] 2024-11-25 13:25
Closing for a lack of a reproducer. If one becomes available, please attach it and we can reopen and reexamine the issue.

**Closed by geoand** 2024-11-25 13:25 UTC
Labels: kind/bug, area/mongodb, triage/needs-feedback
