### ISSUE TITLE
get NPE when force restarting with kubernets dev service running

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33006] opened 2023-04-28 23:17 UTC
### Describe the bug

startup with kubernets-cliet devservice. 

Then press 's' for forced restart and I get this error:

```
2023-04-29 01:15:23,961 ERROR [io.qua.kub.cli.dep.DevServicesKubernetesProcessor] (build-5) Failed to stop the Kubernetes cluster [Error Occurred After Shutdown]: java.lang.NullPointerException: Cannot invoke "java.io.Closeable.close()" because "this.closeable" is null
        at io.quarkus.deployment.builditem.DevServicesResultBuildItem$RunningDevService.close(DevServicesResultBuildItem.java:90)
        at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.shutdownCluster(DevServicesKubernetesProcessor.java:153)
        at io.quarkus.kubernetes.client.deployment.DevServicesKubernetesProcessor.setupKubernetesDevService(DevServicesKubernetesProcessor.java:101)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by Sgitario** [comment] 2023-05-02 10:53
I could not reproduce the error, but looking at the code, I see that the problematic logic is in [here](https://github.com/quarkusio/quarkus/blob/8dd43a487db045d7ad3b0bd9edb33385eb95f24b/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/DevServicesKubernetesProcessor.java#L151), because before closing, it should check whether it's the owner (the closeable instance is not null). 

Note that the null closeable instance might happen when the Kubernetes Client Dev Service has detected a running dev service: see [this line](https://github.com/quarkusio/quarkus/blob/8dd43a487db045d7ad3b0bd9edb33385eb95f24b/extensions/kubernetes-client/deployment/src/main/java/io/quarkus/kubernetes/client/deployment/DevServicesKubernetesProcessor.java#L239).

However, I would like to be sure that this is indeed the problem. @maxandersen can you provide the steps you did to reproduce the issue?

**Comment by maxandersen** [comment] 2023-05-10 08:35
It was building https://github.com/aureamunoz/instaquarm and then go into https://github.com/aureamunoz/instaquarm/blob/main/upload-service/ and run `quarkus dev`

you might need some secrets to have it working ...I got them from @cescoffier but not sure if they matter or not.

**Comment by Sgitario** [comment] 2023-05-10 08:55
> It was building https://github.com/aureamunoz/instaquarm and then go into https://github.com/aureamunoz/instaquarm/blob/main/upload-service/ and run `quarkus dev`
> 
> you might need some secrets to have it working ...I got them from @cescoffier but not sure if they matter or not.

I see. https://github.com/quarkusio/quarkus/pull/33252 should take care of it.

**Closed** 2023-05-15 09:57 UTC
Labels: kind/bug, area/kubernetes
