### ISSUE TITLE
Bcrypt method to check password

### ISSUE THREAD

**Issue by marcuspaulo** [quarkusio/quarkus#10855] opened 2020-07-20 13:22 UTC
Hi mates,

CC: @FroMage 

I’ve a doubt, what’s the best way to check password encrypted with Bcrypt (Quarkus)? (**I’m not using annotation: @UserDefinition**)

When I need to save in database:

```java
BcryptUtil.bcryptHash(password);
```

But doesn’t have, e.g. 
```java
Bcrypt.checkPassword(password, hashedPassword);.
```

https://quarkus.io/guides/security-jpa#password-storage-and-hashing

**Implementation ideas**
Create a method to compare password in database with password from Request.
Suggestion: Class: io.quarkus.elytron.security.common.BcryptUtil

E.g usage:
```java
   Bcrypt.checkPassword(password, hashedPassword);.
```

---
Conversation thread - https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/quarkus-dev/g0yAkjB7zDU/eqEww7FICgAJ

Kind regards

**Comment by FroMage** [comment] 2020-07-20 14:14
So we can either add the method to the util class, or move everything into CDI. @geoand and @sberyozkin  were in favour of using CDI. I prefer static methods.

**Comment by geoand** [comment] 2020-07-20 14:16
I prefer CDI, but I honestly don't mind

**Comment by marcuspaulo** [comment] 2020-11-26 14:19
Hi folks, 
I have a question, how I recover Salt and Iterations with a saved password?

**Comment by FroMage** [comment] 2020-11-26 16:47
It's encoded in there: https://en.wikipedia.org/wiki/Bcrypt

```
$2b$[cost]$[22 character salt][31 character hash]
```

**Comment by marcuspaulo** [comment] 2020-11-26 19:02
Thank you @FroMage

**Comment by sberyozkin** [comment] 2020-12-01 10:11
Here is a proposed code from @jefrog1844  at #13576 (which I've closed as a duplicate of this issue)

```
public void testPasswordHash() throws Exception {
            
            // get the password the user sent in the post
            String testPassword = "myPassword";

            // get the MCF formatted string to store in the database
            String encryptedPwd = BcryptUtil.bcryptHash(testPassword);

            // verify posted password against the encrypted password from the database
            boolean matches = verifyPassword(testPassword, encryptedPwd);

            Assertions.assertTrue(matches, "passwords match!");
    }

    private boolean verifyPassword(String originalPwd, String encryptedPwd) throws Exception {
            // convert encrypted password string to a password key
            Password rawPassword = ModularCrypt.decode(encryptedPwd);

            // create the password factory based on the bcrypt algorithm
            PasswordFactory factory = PasswordFactory.getInstance(BCryptPassword.ALGORITHM_BCRYPT);

            // create encrypted password based on stored string
            BCryptPassword restored = (BCryptPassword) factory.translate(rawPassword);

            // verify restored password against original
            return factory.verify(restored, originalPwd.toCharArray());
    }
```

CC @FroMage

**Comment by MartinX3** [comment] 2021-11-06 17:00
I don't know if this issue can get closed, but `BcryptUtil.matches(String plainText, String passwordHash)` exist now.

**Closed** 2022-03-03 14:16 UTC
Labels: kind/enhancement

**Comment by marcuspaulo** [comment] 2022-03-03 14:18
Thank you very much.
@FroMage @MartinX3, @geoand and @sberyozkin, and Quarkus contributed team.

**Comment by jefrog1844** [comment] 2022-03-04 00:57
Yes, thank you very much.
