### ISSUE TITLE
io.quarkus.qute.i18n.MessageBundle annotated class not found for multi-module gradle project in dev mode

### ISSUE THREAD

**Issue by nikosk686** [quarkusio/quarkus#20063] opened 2021-09-10 15:12 UTC
### Describe the bug

Seems to be related to [this](https://github.com/quarkusio/quarkus/issues/11188)  but it affects all quarkus v1 releases.

We have a custom multi-module setup in our services.
When we use a `@MessageBundle` annotated class 
```java
@MessageBundle(value = "alert")
public interface AlertMessages {

    @Message("")
    String withoutParams();

    @Message("")
    String withParams(String name);
}
```
with several localized implementations generated from the provided `messages/alert_xx.properties` files
we get the following error when trying to run the app in dev mode

>  ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.ClassNotFoundException: org.acme.AlertMessages

This error does not affect single module projects.

### Expected behavior

The application should be able to start in dev mode in as it happens in a single module project.

### Actual behavior

The application fails to start

>  ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.ClassNotFoundException: org.acme.AlertMessages

### How to Reproduce?

clone the following repo https://github.com/nikosk686/quarkus-message-bundle-poc
checkout the `1.13.7-multi-module-dev-mode-error` branch
and try to run in dev mode.

You can also check the `1.13.7-working-single-module` which is a single module application and it starts without error.

### Output of `uname -a` or `ver`

Linux dell-desktop 5.10.0-1045-oem #47-Ubuntu SMP Wed Aug 18 10:41:03 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 LTS OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS) OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)

### Quarkus version or git rev

1.13.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

### Additional information

The problem is not present in quarkus v2 (check the `2.2.0-multi-module-integration-tests-error` branch of the above repo)

**Comment by mkouba** [comment] 2021-09-17 11:06
@nikosk686 isn't this a duplicate of https://github.com/quarkusio/quarkus/issues/20064?

**Comment by nikosk686** [comment] 2021-09-18 16:59
@mkouba 
Could be but not quite sure.
They are similar for sure but this one is about Quarkus v1.x.x while #20064 is for v2.
The problem here is that the multi-module application cannot start in dev mode (the other issue is about test mode)
due to a similar CNFE.
Didn't try the work around with the `quarkus.class-loading.reloadable-artifacts=org.org.acme:api` tbh, I ll let you know when I do.
Also I didn't check if the actual fix (#20204) has been back ported into v1.

**Comment by mkouba** [comment] 2021-09-20 05:43
I don't think that https://github.com/quarkusio/quarkus/pull/20204 will not be backported in 1.x.

**Comment by nikosk686** [comment] 2021-10-01 13:22
@mkouba if I am not wrong property does not exist in v1
So I cannot try this workaround.
Anyway, I have updated my service in the latest v2 version and use this property 
for now until the actual fix of https://github.com/quarkusio/quarkus/issues/20064
comes with the next release.
So from my side, I don't mind if you close this issue for now.

**Closed** 2021-10-02 12:16 UTC
Labels: kind/bug, area/gradle, area/devmode, area/qute
