### ISSUE TITLE
@MaperSupperClass Object extend PanacheEntityBase. How to write a new static method in it.

### ISSUE THREAD

**Issue by guoxunbo** [quarkusio/quarkus#24619] opened 2022-03-30 01:58 UTC
### Describe the bug

> Hello. I want to write a static method in class with @MapperdSupperclass. such as findByName. so the child object can use method to query itself. But I got error. It will query BaseUpdatableEntity not the childObject.The code like this.

```java
@MappedSuperclass
@Slf4j
@ToString
public abstract class BaseUpdatableEntity extends BaseEntity {

    @Getter
    protected LocalDateTime created;

    @Getter
    protected LocalDateTime updated;

    @Getter
    protected String createdBy;

    @Getter
    protected String updatedBy;

    @Version
    @Setter
    @Getter
    protected Long lockVersion = 1L;

    @Override
    protected void prePersist() {
        super.prePersist();
        created = LocalDateTime.now();
        createdBy = MDCScope.getUsername();
    }

    @PreUpdate
    protected void preUpdate() {
        updated = LocalDateTime.now();
        updatedBy = MDCScope.getUsername();
    }

    @Override
    public Object clone() throws CloneNotSupportedException {
        BaseUpdatableEntity updatableEntity = (BaseUpdatableEntity) super.clone();
        updatableEntity.setLockVersion(1L);
        return updatableEntity;
    }

    public BaseUpdatableEntity getByName(String name) {
        return find("name", name).<BaseUpdatableEntity>singleResultOptional().orElse(null);
    }
}
```

> so I read the PanacheEntityBase code. I find the static method with @GenerateBridge But I don't konw how to archive it with myself?

### Quarkus version or git rev

2.7.2.Final

**Comment by loicmathieu** [comment] 2022-03-30 10:20
In Java, static methods are bound to the declaring class, so even if you call it via a child class, it is still called on your `BaseUpdatableEntity` abstract class and not the child class. This is the way static methods works in java.

Unfortunatly, for this to work you'll need to define `getByName` in your child class (it can delegate to a static method on you abstract class if you want).

**Comment by guoxunbo** [comment] 2022-03-30 10:35
@loicmathieu 
Yes.Understand. But why the `PanacheEntityBase`Can do this? such as findById, list or find.
```
it can delegate to a static method on you abstract class if you want
```
I don't undestand this?

**Comment by loicmathieu** [comment] 2022-03-30 10:40
> But why the PanacheEntityBaseCan do this? such as findById, list or find.

It cannot, there is bytecode enhancement going on under the cover. 

The issue is that the method is bound to the wrong type `BaseUpdatableEntity` instead of the child type. Hibernate need to know the entity type to map the resultset to the right Java type, and your method declare `BaseUpdatableEntity` as the return type so it try to map to this type instead of the type of the entity.

**Comment by guoxunbo** [comment] 2022-03-30 10:48
@loicmathieu 
ok. Understand it. Thank's a lot. 
Is there have any example to know how to use bytecode enhancement to cover it? I want to study it in my free time.

**Comment by loicmathieu** [comment] 2022-03-30 12:54
Well, it's not very easy to follow.

At build time, Quarkus will generates Java bytecode via the ASM library to override the methods comming from the PanacheBaseEntity that are annotated by the annotation `@GenerateBridgeMethod`. So the methods that are not implemented (implemented by throwing an exception) would in fact be implemented on the child entity class at build time.

For example, this class will generate the bytecode for any repository: https://github.com/quarkusio/quarkus/blob/main/extensions/panache/panache-common/deployment/src/main/java/io/quarkus/panache/common/deployment/visitors/PanacheRepositoryClassOperationGenerationVisitor.java

**Comment by guoxunbo** [comment] 2022-03-31 01:38
ok.thanks. I had write some asm extention in my project. let me have a look this.
Thank's a lot.Love[抱拳]

**Comment by loicmathieu** [comment] 2022-03-31 07:22
As it's not a bug and the question was answer, I'll close this issue.
Please reopen it or ask qestion on Zulip or Github Discussion if you have more question

**Closed by loicmathieu** 2022-03-31 07:22 UTC
Labels: kind/bug, area/panache

**Comment by guoxunbo** [comment] 2022-04-02 06:32
@loicmathieu ok. Thanks.how to join your zulip or Github Discussion? I have some question want to ask you for some advice.

**Comment by loicmathieu** [comment] 2022-04-11 09:19
Github discussions Q&A: https://github.com/quarkusio/quarkus/discussions/categories/q-a
Zulip user stream: https://quarkusio.zulipchat.com/#narrow/stream/187030-users
