### ISSUE TITLE
Liquibase is not able to parse resource location

### ISSUE THREAD

**Issue by Greg-Zss** [quarkusio/quarkus#30568] opened 2023-01-24 10:36 UTC
### Describe the bug

I'm using Quarkus with Liquibase in a docker container. Starting with Quarkus version 2.15.x and above Liquibase fails loading resources when starting the container. In DEV mode and under tests everything works fine. I'm using the includeAll feature and the scripts are located in resources.

I got following error message when I try to start the container:
`Cannot parse resource location: 'jar:file:/home/jboss/app/xxx-backend-0.1.0-SNAPSHOT.jar!/db/changelogs/v0.1'`

It seems that the dependency of liquibase in Quarkus has changed between 2.14.x and 2.15.0:
In Quarkus 2.15.x: org.liquibase:liquibase-core:jar:4.17.2:compile
in Quarkus 2.14.x: org.liquibase:liquibase-core:jar:4.16.1:compile

In the Liquibase documentation I found this "maybe" breaking change:
`The liquibase.resource.ResourceAccessor APIs were updated to take advantage of the new liquibase.resource.Resource abstraction that was introduced. Code that USES the existing ResourceAccessor methods will continue to work as before with no changes, but if you have written custom implementations of ResourceAccessor there are new and changed methods to implement`
[Liquibase changes](https://github.com/liquibase/liquibase/releases/tag/v4.17.0)

I don't know if Quarkus uses a custom implementation. In the pull request of this [change](https://github.com/liquibase/liquibase/pull/3064) additional information can be found.

### Expected behavior

Liquibase works in the same way than in Quarkus 2.14.x and is able to load the database sql scripts.

### Actual behavior

Startup of application is interrupted. You can see the stacktrace in additional information

### Output of `java -version`

OpenJDK 11

### Quarkus version or git rev

2.15.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 

### Additional information

`[li.changelog] (main) includeAll for db/changelogs/v0.1/`
`[li.changelog] (main) Using file opener for includeAll: ClassLoaderResourceAccessor{}`
`[li.servicelocator] (main) Loaded liquibase.resource.PathHandler instance liquibase.resource.DirectoryPathHandler`
`[li.servicelocator] (main) Loaded liquibase.resource.PathHandler instance liquibase.resource.ZipPathHandler`
...
```
ERROR [io.qu.ru.Application] (main) Failed to start application (with profile prod): java.io.IOException: Cannot parse resource location: 'jar:file:/home/jboss/app/xxx-backend-0.1.0-SNAPSHOT.jar!/db/changelogs/v0.1'
 at liquibase.resource.PathHandlerFactory.getResourceAccessor(PathHandlerFactory.java:36)
 at liquibase.resource.ClassLoaderResourceAccessor.search(ClassLoaderResourceAccessor.java:124)
 at liquibase.changelog.DatabaseChangeLog.includeAll(DatabaseChangeLog.java:618)
 at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:462)
 at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:364)
 at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
 at liquibase.changelog.DatabaseChangeLog.include(DatabaseChangeLog.java:717)
 at liquibase.changelog.DatabaseChangeLog.handleChildNode(DatabaseChangeLog.java:411)
 at liquibase.changelog.DatabaseChangeLog.load(DatabaseChangeLog.java:364)
 at liquibase.parser.core.xml.AbstractChangeLogParser.parse(AbstractChangeLogParser.java:23)
 at liquibase.Liquibase.getDatabaseChangeLog(Liquibase.java:408)
 at liquibase.Liquibase.validate(Liquibase.java:2323)
 at io.quarkus.liquibase.runtime.LiquibaseRecorder.doStartActions(LiquibaseRecorder.java:67)
 at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy_0(Unknown Source)
 at io.quarkus.deployment.steps.LiquibaseProcessor$startLiquibase763757012.deploy(Unknown Source)
 at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
 at io.quarkus.runtime.Application.start(Application.java:101)
 at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:109)
 at io.quarkus.runtime.Quarkus.run(Quarkus.java:71)
 at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
 at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
 at io.quarkus.runner.GeneratedMain.main(Unknown Source)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
 at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.base/java.lang.reflect.Method.invoke(Unknown Source)
 at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:61)
 at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:32)
```

**Comment by geoand** [comment] 2023-01-24 12:49
Is there any chance you supply us a sample application that works with `2.14` and not with `2.15`?

**Comment by Greg-Zss** [comment] 2023-01-24 16:01
I tried to generate a sample application. You just have to add your registry and maybe your repository. Then you can create the docker image and start it. 
In the archive is version 2.15.3 that is not running. I verified with version 2.14.3 and here it is running.
It is working when you start the application in DEV mode.

You can find a docker compose file in the root folder. 
[issue-30568.zip](https://github.com/quarkusio/quarkus/files/10491745/issue-30568.zip)

![image](https://user-images.githubusercontent.com/123459127/214343915-5cca908a-d62d-4b37-b70e-285e52fc06c3.png)

**Comment by famod** [comment] 2023-01-24 20:22
I wouldn't be surprised if this is related to https://github.com/liquibase/liquibase/issues/3524

My app is on Quarkus 2.16.0.Final, but I had to override/downgrade Liquibase because of that issue.
Luckily I'm not using native, otherwise the downgrade wouldn't be compatible I suppose.

**Comment by Greg-Zss** [comment] 2023-01-25 07:27
Indeed, this is working. When I downgrade the version of liquibase, then the reporoducer works with 2.15.3. 
I used this version:

```
    <dependency>
      <groupId>org.liquibase</groupId>
      <artifactId>liquibase-core</artifactId>
      <version>4.16.1</version>
    </dependency>
```
Thanks @famod for the information

**Comment by geoand** [comment] 2023-01-25 07:30
Thanks for the information folks.

I am going to close this as an upstream issue.

**Closed by geoand** 2023-01-25 07:30 UTC
Labels: kind/bug, area/liquibase

**Comment by famod** [comment] 2023-03-12 21:57
FWIW, I found a workaround: https://github.com/liquibase/liquibase/issues/3524#issuecomment-1465282155

I hope the underlying root cause can now be fixed after my deep dive.
