### ISSUE TITLE
Test with beforeEach for entity data update fails with strange message.

### ISSUE THREAD

**Issue by gintsgints** [quarkusio/quarkus#5523] opened 2019-11-15 20:28 UTC
**Describe the bug**
I have project jpa, Panache with apropriate test - https://github.com/gintsgints/quarkus-ws
Test try to recreate data in tables with before each procedure.

**Expected behavior**
Tests fail with endpoint error or execute without error.

**To Reproduce**
1. Clone repository 
2. Start database with docker docker-compose up -d db
3. Start project, so it creates basic structure in database
4. Execute test
5. You get error - java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?

**Configuration**
Check project for configs.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Windows 
 - Output of `java -version`: 1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 0.28.1

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment] 2019-11-18 23:46
Can you try with 1.0.0.CR1? I know we fixed a related issue recently.

**Comment by gintsgints** [comment] 2019-11-19 07:22
Same with 1.0.0.CR1. (repo updated)

**Comment by famartinrh** [comment] 2019-11-27 15:44
Same error here, I have been investigating this and I'm unable to determine what is going on, to me it looks like CDI works different in tests.
The log error looks like this 
```
java.lang.IllegalStateException: This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?
	at io.quarkus.hibernate.orm.panache.runtime.JpaOperations.implementationInjectionMissing(JpaOperations.java:367)
	at io.quarkus.hibernate.orm.panache.PanacheRepositoryBase.listAll(PanacheRepositoryBase.java:356)
	at org.acme.hibernate.orm.panache.FruitRepository_ClientProxy.listAll(FruitRepository_ClientProxy.zig:602)
	at org.acme.hibernate.orm.panache.FruitsPanacheTest.testEntity(FruitsPanacheTest.java:30)
	at org.acme.hibernate.orm.panache.FruitsPanacheTest_Subclass.testEntity$$superaccessor4(FruitsPanacheTest_Subclass.zig:248)
	at org.acme.hibernate.orm.panache.FruitsPanacheTest_Subclass$$function$$4.apply(FruitsPanacheTest_Subclass$$function$$4.zig:29)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:119)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:92)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:168)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.hibernate.orm.panache.FruitsPanacheTest_Subclass.testEntity(FruitsPanacheTest_Subclass.zig:72)
```

```FruitsPanacheTest.java
@QuarkusTest
public class FruitsPanacheTest {

    @Inject
    FruitRepository repository;

    @Test
    @Transactional
    public void testEntity() {
        try {
            repository.listAll();
        } catch(Exception e){
            e.printStackTrace();
            throw e;
        }
    }
}
```

```FruitRepository.java
@ApplicationScoped
public class FruitRepository implements PanacheRepository<Fruit>{
    
}
```

**Comment by gintsgints** [comment] 2019-12-14 10:39
Also what I found, EntityManager if injected and used in BeforeEach, is null.

**Comment by loicmathieu** [comment] 2020-05-01 14:59
@gintsgints can you try with a recent version of Quarkus, like 1.4.1.Final ?
This seems like #6374 that has been fixed

**Comment by gintsgints** [comment] 2020-05-02 07:15
Problem solved with latest Quarkus.

**Comment by gintsgints** [comment] 2020-05-02 07:37
Sorry, it is solved partly.

When I debug test, I see panache object there and it has ID (seems like it is persisted).
Bet when I try to access ID of the object I get null value.

**Comment by dcdh** [comment] 2020-05-02 19:23
You can see ID value maybe because it has been processed from the debug panel when variable is watched.
I figure a look like issue: In beforeEach I truncate a table created in an injected service in a PostConstruct callback.
In major times, when I launch the test using maven in bash it fails because the PostConstruct has not been called before the BeforeEach.

**Comment by loicmathieu** [comment] 2020-05-04 07:14
@gintsgints this is not the same issue.
Can you please open a new issue with a description and possibly a reproducer.
Can you also ping @dcdh when the issue is open so he can add his feedback on it.

As the issue with `This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?` in test case is fixed I close this one.

**Closed by loicmathieu** 2020-05-04 07:14 UTC
Labels: kind/bug

**Comment by dcdh** [comment] 2020-05-06 13:29
Not an issue. I fixed it by adding `@Singleton`  on `AgroalDataSourceSecretStore`. Like this the `@PostConstruct` is called before the `@BeforeEach`.
Sorry for the inconvenience.
