### ISSUE TITLE
Create a Maven archetype for new Extensions

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2160] opened 2019-04-19 01:34 UTC
It would be nice if an archetype based on https://quarkus.io/guides/extension-authors-guide#maven-setup existed

**Comment by cescoffier** [comment] 2019-04-19 06:19
I believe @danielpetisme wanted to work on this.

**Comment by cescoffier** [comment] 2019-04-19 06:34
Actually, this is a duplicate of #2113.

**Closed** 2019-04-19 06:34 UTC
Labels: duplicate
