### ISSUE TITLE
quarkus-resteasy NPE with special character in request uri

### ISSUE THREAD

**Issue by antonwiens** [quarkusio/quarkus#5584] opened 2019-11-19 13:17 UTC
**Describe the bug**
When making a HTTP GET Request with an "{" (special character) in the request line and the quarkus-resteasy extension is used in the application, the server returns a NPE with statuscode 500.
Used quarkus version is 1.0.0.CR1.

The following stacktraces show that calculation of the absoluteURI for the resteasy extension fails:

>2019-11-19 14:09:58,701 SEVERE [io.ver.cor.htt.imp.HttpServerRequestImpl] (vert.x-worker-thread-3) Failed to create abs uri: java.net.URISyntaxException: Illegal character in path at index 1: /{param}
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3105)
        at java.net.URI$Parser.parse(URI.java:3063)
        at java.net.URI.<init>(URI.java:588)
        at io.vertx.core.http.impl.HttpUtils.absoluteURI(HttpUtils.java:365)
        at io.vertx.core.http.impl.HttpServerRequestImpl.absoluteURI(HttpServerRequestImpl.java:373)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:204)
        at io.vertx.ext.web.impl.HttpServerRequestWrapper.absoluteURI(HttpServerRequestWrapper.java:204)
        at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:31)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:94)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

>2019-11-19 14:09:58,704 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-worker-thread-3) HTTP Request to /{param} failed, error id: 158d1602-d89c-4dc9-a9a1-9cbda08f22ff-1: java.lang.NullPointerException
        at io.quarkus.resteasy.runtime.standalone.VertxUtil.extractUriInfo(VertxUtil.java:37)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:94)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatchRequestContext(VertxRequestHandler.java:84)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.lambda$handle$0(VertxRequestHandler.java:71)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:316)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

**Expected behavior**
The server should return status code 4xx.

**Actual behavior**
The server returns status code 500.

**To Reproduce**
1. Create a simple project with quarkus-resteasy extension, a simple jaxrs endpoint and start the server.
2. Make a http request to a path containing the special character "{" without escaping, e.g. with curl:
> curl "localhost:8080/\{param\}" --verbose
3. The server returns status code 500

**Comment by gsmet** [comment] 2019-11-20 15:56
@asoldano not sure about that one? Is this the expected behavior or not?

**Comment by gsmet** [comment] 2019-11-20 15:57
(I saw it's in the Vert.x implementation but I'm mostly wondering what the behavior should be)

**Comment by asoldano** [comment] 2019-11-26 10:53
@gsmet HTTP 500 does not look right, I agree. I would generally expect HTTP 400 too. Actually, in some cases, the special char could even be fine, for example, if used in a part of the path that corresponds to a @PathParam parameter of the resource.

**Comment by asoldano** [comment] 2019-11-26 10:54
@gsmet having said this, this is likely not a resteasy thing

**Comment by gsmet** [comment] 2019-11-26 11:28
@asoldano yes, I agree, I just wanted your feedback.

@cescoffier looks like this is more of a Vert.x issue. Could you push that one to the right person? Maybe @asoldano will be able to point out how things are done in RESTEasy.

**Comment by vc-void** [comment] 2019-11-28 16:19
This is also happening with the "\" character.

**Comment by gorshkov-leonid** [comment] 2020-12-31 07:54
Hello, what is the result of this discussion?
My case is the usage of a valid URL. According to JAX-RS URL "https://bla-bla/my-api/project%2Ffolder%2F42.txt" is enough valid and should be decoded on the server. But decoding is done prematurely before authorization, is not it?
The expected URL that is sending to Keycloak seems to be encoded again or it should not be decoded before authorization.

**Comment by geoand** [comment] 2022-01-11 11:01
This has since been fixed in https://github.com/quarkusio/quarkus/pull/21921

**Closed by geoand** 2022-01-11 11:01 UTC
Labels: kind/bug, area/resteasy
