### ISSUE TITLE
OIDC: 401 when keys need to be refreshed

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#15004] opened 2021-02-11 15:06 UTC
**Describe the bug**
We're using OIDC-Extension. Everything works fine until our OIDC-Server starts rotating keys. In this case, the first call ends in a 401-unauthorized answer from Quarkus. All subsequent calls then work fine again.

**Expected behavior**
Rotated OIDC-keys should have no negative impact on any call.

**Actual behavior**
First call after key-rotation ends up in an 401 answer, despite the valid token provided.

**To Reproduce**
Unfortunately it is not possible for me to provide a reproducer, because the problem only happens when keys of the OIDC-system rotate and I have no idea how to simulate this in a reproducer.

**Configuration**
```properties
quarkus.oidc.auth-server-url=https://oidc-server.com
quarkus.oidc.client-id=MY_CLIENT
quarkus.oidc.authentication.user-info-required=true
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.1697]
 - Output of `java -version`: OpenJDK Runtime Environment Corretto-11.0.6.10.1 (build 11.0.6+10-LTS)
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 1.11.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**

> 2021-02-11 14:19:52,397 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RouterImpl] (vert.x-eventloop-thread-1) Router: 1547641481 accepting request GET http://my-server.com/my-endpoint
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Route matches: RouteState{path='null', order=-2147483648, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[AccessLogHandler{formatString='%r %s
%{ALL_REQUEST_HEADERS}'}], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=false}
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Calling the  handler
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Route matches: RouteState{path='null', order=-2147483647, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.micrometer.runtime.binder.vertx.VertxMeterFilter@5c328f41], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=false}
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Calling the  handler
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Route matches: RouteState{path='null', order=-200, enabled=true, methods=null, consumes=null, emptyBodyPermittedWithConsumes=false, produces=null, contextHandlers=[io.quarkus.vertx.http.runtime.security.HttpSecurityRecorder$2@cf260af7], failureHandlers=null, added=true, pattern=null, groups=null, useNormalisedPath=true, namedGroupsInRegex=null, virtualHostPattern=null, pathEndsWithSlash=false, exclusive=false, exactPath=false}
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.web.imp.RoutingContextImplBase] (vert.x-eventloop-thread-1) Calling the  handler
2021-02-11 14:19:52,398 FINEST traceId=, parentId=, spanId= [io.ver.ext.aut.oau.imp.OAuth2API] (executor-thread-54) Fetching URL: https://oidc-server.com/me
2021-02-11 14:19:52,412 DEBUG traceId=, parentId=, spanId= [io.net.han.ssl.SslHandler] (vert.x-eventloop-thread-1) [id: 0x5435b32b, L:/XXX.XXX.XXX.XXX:37684 - R:oidc-server.com/XXX.XXX.XXX.XXX:443] HANDSHAKEN: protocol:TLSv1.2 cipher suite:TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
2021-02-11 14:19:52,436 FINEST traceId=, parentId=, spanId= [io.ver.ext.aut.oau.imp.OAuth2ResponseImpl] (vert.x-eventloop-thread-1) New response: statusCode: 200
2021-02-11 14:19:52,436 DEBUG traceId=, parentId=, spanId= [io.qua.oid.run.JwkSetRefreshHandler] (vert.x-eventloop-thread-1) No JWK with RS256#341455926609357730 key id is available, trying to refresh the JWK set
2021-02-11 14:19:52,436 FINEST traceId=, parentId=, spanId= [io.ver.ext.aut.oau.imp.OAuth2API] (vert.x-eventloop-thread-1) Fetching URL: https://oidc-server.com/keys
2021-02-11 14:19:52,438 DEBUG traceId=, parentId=, spanId= [io.qua.mic.run.bin.ver.VertxHttpServerMetrics] (vert.x-eventloop-thread-1) responseEnd: io.quarkus.micrometer.runtime.binder.HttpRequestMetric@f17474a7, io.vertx.core.http.impl.HttpServerResponseImpl@149aff41
2021-02-11 14:19:52,438 INFO  traceId=, parentId=, spanId= [io.qua.htt.access-log] (vert.x-eventloop-thread-1) GET /my-endpoint HTTP/1.1 401

**Comment by sberyozkin** [comment] 2021-02-11 15:45
@wicksim Hi, thanks for opening this issue, it is a duplicate of #12984.
 Let me close this one and please watch #12984 - at the moment there is nothing that can be done about it. It will be resolved with #14492. thanks

**Comment by sberyozkin** [comment] 2021-02-12 16:47
It is better to keep this issue open as the other issue I linked to is overloaded and primarily about the optional blocking of the introspection

**Comment by wicksim** [comment] 2021-02-13 11:53
@sberyozkin Thank you for your answer. I read the other ticket and as far as I understood, this problem should not appear if there is an introspection-endpoint configured? There is an introspection-endpoint in the .well-known-page of our IDP. As you can see in the bug report, I configured `quarkus.oidc.auth-server-url`, which should also automatically configure the introspection-path. So in my opinion, it should work in my case? Or do I need to configure anything else?

**Closed** 2021-03-03 10:02 UTC
Labels: area/oidc, env/windows, kind/bug
