### ISSUE TITLE
NPE in ConfigMapping on Native when using -H:ResourceConfigurationFiles or quarkus.native.resources.includes property

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#17653] opened 2021-06-03 06:04 UTC
## Describe the bug
Using an application that needs a resource, when registering this external resource for Native via:

- Or `pom.xml`:
```xml
<profiles>
        <profile>
            <id>native</id>
            <properties>
                <quarkus.native.additional-build-args>-H:ResourceConfigurationFiles=resources-config.json</quarkus.native.additional-build-args>
            </properties>
        </profile>
    </profiles>
```

And:
```json
{
  "resources": [
    {
      "pattern": "configsource.properties"
    }
  ]
}
```

- Or via Quarkus property:
```
quarkus.native.resources.includes=configsource.properties
```

It builds ok, but when running the Native tests or running the Native app with the next Null pointer exception:

```
2021-06-03 08:01:05,613 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): java.lang.NullPointerException
        at io.smallrye.config.ConfigMappingContext.getConverter(ConfigMappingContext.java:97)
        at io.smallrye.config.ConfigMappingContext.lambda$getValueConverter$4(ConfigMappingContext.java:92)
        at java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.smallrye.config.ConfigMappingContext.getValueConverter(ConfigMappingContext.java:89)
        at io.quarkus.qe.config.interfaces.ProtagonistConfigurable1275545271Impl.<init>(Unknown Source)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at io.smallrye.config.ConfigMappingLoader.configMappingObject(ConfigMappingLoader.java:55)
        at io.smallrye.config.ConfigMappingContext.constructGroup(ConfigMappingContext.java:80)
        at io.smallrye.config.ConfigMappingContext.constructRoot(ConfigMappingContext.java:76)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:794)
        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:777)
        at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
        at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
        at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:50)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:292)
        at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:513)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
```

## To Reproduce

1. `git clone https://github.com/Sgitario/beefy-scenarios`
2. cd beefy-scenarios
3. git checkout reproducer_17653
4. cd 022-quarkus-properties-config-all
5. mvn clean verify -Dnative

It fails when running the tests with the above exception.

### GraalVM version (if different from Java)
GraalVM 21.0.0.2
GraalVM 21.1.0

### Quarkus version or git rev
999-SNAPSHOT

**Comment by Sgitario** [comment] 2021-06-03 06:07
cc @radcortez maybe this is related to the new `@ConfigMapping` annotation changes?

**Comment by radcortez** [comment] 2021-06-03 09:57
Not sure. I'll need to check. Did it work without adding the argument?

**Comment by radcortez** [comment] 2021-06-07 13:35
Ok, the issue is related with the `IBiography` hierarchy. We are not automatically registering for reflection the config mapping hierarchy (if any). I'll make a fix for this.

For now, you can workaround this by adding a `@RegisterForReflection` in any hierarchy classes.

**Closed** 2021-06-08 13:04 UTC
Labels: area/config, kind/bug
