### ISSUE TITLE
Mongo health check connection auto close

### ISSUE THREAD

**Issue by Dosexe** [quarkusio/quarkus#25606] opened 2022-05-16 15:07 UTC
### Describe the bug

When the connection pool is setup for MongoDb, and there is `max-connection-idle-time` also present, the connection pool itself working as expected, but the `MaintenanceTimer-thread` which is called to clear the idle connection,  closing the connections that are used for health check by itself, so it creates a problem that even if the connection pool is setup a lot of connections are opened and closed because of the maintenance.

### Expected behavior

If the `quarkus.mongodb.min-pool-size` is setup the connections should be reused, not closed and opened frequently.
Or health check connection should have it own pool.

### Actual behavior

Connections are closed and opened frequently.
```
2022-05-16 20:47:33,115 DEBUG [org.mon.dri.connection] (MaintenanceTimer-1-thread-1) Pruning pooled connections to localhost:27017
2022-05-16 20:47:33,115 DEBUG [org.mon.dri.connection] (MaintenanceTimer-1-thread-1) Closed connection [connectionId{localValue:36, serverValue:322}] to localhost:27017 because it is past its maximum allowed idle time.
2022-05-16 20:47:33,115 DEBUG [org.mon.dri.connection] (MaintenanceTimer-1-thread-1) Closing connection connectionId{localValue:36, serverValue:322}
2022-05-16 20:47:33,115 DEBUG [org.mon.dri.connection] (MaintenanceTimer-1-thread-1) Ensuring minimum pooled connections to localhost:27017
2022-05-16 20:47:33,179 INFO  [org.mon.dri.connection] (MaintenanceTimer-1-thread-1) Opened connection [connectionId{localValue:37, serverValue:323}] to localhost:27017
2022-05-16 20:47:35,510 DEBUG [org.mon.dri.pro.command] (cluster-rtt-ClusterId{value='6282557c9965e50b69eaf771', description='null'}-localhost:27017) Sending command '{"hello": 1, "$db": "admin"}' with request id 470 to database admin on connection [connectionId{localValue:3, serverValue:289}] to server localhost:27017
```

### How to Reproduce?

Create quarkus app with mongo dependency. Mongo  - image: "mongo:5.0.6"

Gradle

```kotlin
    api("io.quarkus:quarkus-rest-client-reactive-jackson")
    api("io.quarkus:quarkus-micrometer-registry-prometheus")
    api("io.quarkus:quarkus-kotlin")
    api("io.quarkus:quarkus-smallrye-health")
    api("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    api("io.quarkus:quarkus-mongodb-panache-kotlin")
```

MongoDb props:

```yaml
quarkus:
  mongodb:
    min-pool-size: ${MONGO_POOL_MIN_SIZE:2}
    max-pool-size: ${MONGO_POOL_MAX_SIZE:20}
    max-connection-idle-time: ${MONGO_CONNECTION_IDLE_TIME:60s}
```

### Output of `uname -a` or `ver`

21.1.0 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:23 PDT 2021

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment Homebrew (build 11.0.12+0) OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

7.4.1

**Comment by loicmathieu** [comment] 2022-07-21 13:54
@Dosexe maybe I don't understand correctly what is the issue here but it is the way the MongoDB driver handle connection pooling, we cannot do anything on our side.

**Comment by Dosexe** [comment] 2022-07-21 20:16
@loicmathieu Is health checks are also fully controlled by mongo driver?

**Comment by loicmathieu** [comment] 2022-07-22 07:01
@Dosexe If you talk about readiness health check as in https://quarkus.io/guides/mongodb#connection-health-check this is provided by the MongoDB extension in conjonction with the Smallrye Health extension (https://quarkus.io/guides/smallrye-health). But the periodicity of these check depends of how you call them (for eg the periodSecond of a k8s probe).

If you talk about MongoDB client connection pool health check, this is up to the MongoDB client and you can configure it, see https://quarkus.io/guides/mongodb#configuration-reference

**Comment by loicmathieu** [comment] 2022-08-24 10:47
@Dosexe I'm closing it works as intended and information to configure the health check has been provided. Feel free to re-open it if needed.

**Closed by loicmathieu** 2022-08-24 10:47 UTC
Labels: kind/bug, area/smallrye, area/kotlin, area/mongodb, area/health
