### ISSUE TITLE
oracle error ORA-01461 when persisting entity with special characters in absurdly specific circumstances

### ISSUE THREAD

**Issue by Felk** [quarkusio/quarkus#35070] opened 2023-07-27 19:05 UTC
### Describe the bug

In some absurdly specific circumstances, trying to persist an entity containing the string `Nêin` will cause the following error when connected to an oracle database:  
> ORA-01461: can bind a LONG value only for insert into a LONG column

This looks more like a hibernate bug than a quarkus bug, but creating a reproducer with quarkus is way easier, because it requires an actual oracle database, which is trivially availabe using dev services.

Let's say we have this entity:
```java
@Entity
@Data
@NoArgsConstructor(access = AccessLevel.PROTECTED) // for JPA
public class MyEntity {
    @Id
    @GeneratedValue
    private Long id;

    @Column
    Boolean someBool;

    @Column
    String someString;

    public MyEntity(Boolean someBool, String someString) {
        this.someBool = someBool;
        this.someString = someString;
    }
}
```

and a JDBC batch size of at least 2 (e.g. setting `quarkus.hibernate-orm.jdbc.statement-batch-size` to 2). Then, running this code will result in the aforementioned error:

```java
MyEntity entityOk = new MyEntity(null, null);
MyEntity entityBorked = new MyEntity(true, "Nêin");

entityManager.persist(entityOk);
entityManager.persist(entityBorked);
entityManager.flush(); // ERROR! ORA-01461
```

The absurd thing isn't even that the error looks completely unrelated, but that these little changes all fix the problem:

- Using other special characters, e.g. stuff like "äöüßÄÖÜẞ💩"</li>
- Slightly changing the string's size, e.g. "Nêi" and "Nêin_" both work</li>
- Using the decomposite unicode normalization "Nêin" (e + 0x0302 "COMBINING CIRCUMFLEX ACCENT")
  instead of the composite form "Nêin" (0x00EA "LATIN SMALL LETTER E WITH CIRCUMFLEX")</li>
- Not having a JDBC batch size > 1, or flushing in-between the two inserts</li>
- Changing the order in which the two entities are persisted</li>
- Removing the random additional nullable boolean field</li>
- Not having the Boolean be null for one and not-null for the other entity,
  e.g. true->false or false->true makes the test pass</li>
- not having the first entity's string be null</li>

I have attached a reproducer project: [quarkus-nein-reproducer.zip](https://github.com/quarkusio/quarkus/files/12187389/quarkus-nein-reproducer.zip)

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

3.2.2.Final (broken starting with 3.1.0, fine with 3.0.4)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.2

**Comment by marko-bekhta** [comment] 2023-07-28 15:41
hey @Felk 
Thanks for reporting the issue. It looks though that the problem goes beyond Quarkus or even Hibernate ORM 😄. See this test I've created here https://github.com/marko-bekhta/hibernate-test-case-templates/commit/663bf6c55a6bbad855c3361d2f1f504965f3108d.

The error happens if you try to do this with a simple prepared statement. It is only reproducible with a combination of `com.oracle.database.jdbc:ojdbc11:23.2.0.0` driver and `gvenzl/oracle-free:23` Oracle DB. If a previous version of a driver is used (`21.10.0.0`) it works fine with `gvenzl/oracle-free:23` too. Or if the DB image is changed to `gvenzl/oracle-xe` it works fine with both drivers.

> 3.2.2.Final (broken starting with 3.1.0, fine with 3.0.4)

Quarkus 3.1.0 upgraded the driver to `com.oracle.database.jdbc:ojdbc11:23.2.0.0` from `com.oracle.database.jdbc:ojdbc11:21.5.0.0` so that explains why it started to fail.

As a workaround, you could downgrade the oracle driver.

**Comment by Felk** [comment] 2023-07-31 10:14
Thanks for narrowing the problem down further! Downgrading the driver back to 21 worked.

I couldn't find an official place to report jdbc driver bugs to Oracle, so if it's okay with you I'll try posting on [their forums](https://forums.oracle.com/ords/apexds/domain/dev-community/category/oracle-database-free) with a link to this issue and your reproducer, and close this one as it's not Quarkus' fault. Does that sound good?

**Comment by yrodiere** [comment] 2023-07-31 10:20
Hey @Felk , LGTM, thanks!

Please remember to post a link to your post here, so that others facing the same problem can follow progress on the Oracle side of things :)

Closing as this is not strictly caused by Quarkus, and I expect a fix in the Oracle JDBC driver will take some time.

**Closed by yrodiere** 2023-07-31 10:20 UTC
Labels: kind/bug, area/persistence, triage/upstream

**Comment by Felk** [comment] 2023-07-31 10:29
I've posted on their forum: https://forums.oracle.com/ords/apexds/post/oracle-error-ora-01461-when-persisting-entity-with-special-2651

**Comment by Felk** [comment] 2024-07-23 08:45
This is properly fixed now in Quarkus due to https://github.com/quarkusio/quarkus/pull/41998 which updated the Oracle JDBC driver to 23.4
