### ISSUE TITLE
Bamboo agent does not build the native image after upgrading from 3.9.1 to 3.9.2

### ISSUE THREAD

**Issue by DisterDE** [quarkusio/quarkus#39879] opened 2024-04-04 11:59 UTC
### Describe the bug

Hello.

The renovate bot updated the application dependency versions from 3.9.1 to 3.9.2, and the native build no longer builds.
Building two Kotlin projects (aws lambda & default web app) using Gradle 8.7 and Bamboo agents.

Build command: 
```
./gradlew build
        -Dquarkus.package.type=native
        -Dquarkus.native.remote-container-build=true
        -Dquarkus.native.builder-image=quarkus/ubi-quarkus-mandrel-builder-image:jdk-17
        -Dnative-image.xmx=6g
        --info 
        --stacktrace
```
[log.txt](https://github.com/quarkusio/quarkus/files/14865951/log.txt)

Thanks.

### Output of `java -version`

openjdk 17.0.10 2024-01-16 LTS

### Mandrel or GraalVM version (if different from Java)

MANDREL 23.0.3.0 JDK 17.0.10+7

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.7

**Comment by geoand** [comment] 2024-04-04 12:10
@zakkak @maxandersen @jponge @cescoffier another instance of GraalVM 17 :)

**Comment by jponge** [comment] 2024-04-04 12:30
@DisterDE Is there any possibility you could also check with a custom build of Quarkus on the `main` branch?

`./mvnw -Dquickly` then bump your dependencies to `999-SNAPSHOT`

**Comment by zakkak** [comment] 2024-04-04 12:35
Looks like a duplicate of https://github.com/quarkusio/quarkus/issues/39819

The issue should indeed be fixed on `main` (and is expected to be backported to 3.9).

**Closed** 2024-04-04 12:36 UTC
Labels: kind/bug, area/kotlin, area/native-image

**Comment by zakkak** [comment] 2024-04-04 12:46
> but essentially the fact that it worked previously could be considered an accident.

I think we should use different wording here. It didn't really work by accident as we are actually testing Quarkus with Mandrel 23.0 on a weekly base (which indeed caught the issue).

The thing is that supporting Mandrel 23.0 is not a high priority, so such failures might not get immediate attention (as it happened and 3.9.2 got out with the issue). Moving forward when using an older Mandrel version users will get a warning that will hopefully break the assumption that these versions get the same attention as the latest version, see https://github.com/quarkusio/quarkus/pull/39866. 

HTH

**Comment by geoand** [comment] 2024-04-04 12:47
Fair enough :)
