### ISSUE TITLE
Quartz - scheduling jobs programmatically fails when running from IDE

### ISSUE THREAD

**Issue by bobanbg** [quarkusio/quarkus#11017] opened 2020-07-28 07:28 UTC
**Describe the bug**
Execution of "SCHEDULING PERIODIC TASKS WITH QUARTZ" Guide fails when MyJob is fired after job creation is done correctly.  

**Expected behavior**
Trigger calls MyJob method "performTask()" and persist a new Task.

**Actual behavior**
When it comes to fire MyJob execution, it throws IllegalStateException:  Job class must implement the Job interface.

**To Reproduce**
Code to reproduce (as  [Quarz Guide](https://quarkus.io/guides/quartz) )
```
import io.quarkus.arc.Arc;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.StartupEvent;
import io.quarkus.runtime.annotations.QuarkusMain;
import org.quartz.*;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.transaction.Transactional;
import java.time.Instant;

@QuarkusMain
public class Main {

    public static void main(String[] args) {
        Quarkus.run(args);
    }


    @Entity
    @Table(name = "TASKS")
    static class Task extends PanacheEntity {
        public Instant createdAt;

        public Task() {
            createdAt = Instant.now();
        }

        public Task(Instant time) {
            this.createdAt = time;
        }
    }

    @ApplicationScoped
     static class TaskBean {

        @Inject
        private Scheduler quartz;

        void onStart(@Observes StartupEvent event) throws SchedulerException {
            JobDetail job = JobBuilder.newJob(MyJob.class)
                    .withIdentity("myJob", "myGroup")
                    .build();
            Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity("myTrigger", "myGroup")
                    .startNow()
                    .withSchedule(
                            SimpleScheduleBuilder.simpleSchedule()
                                    .withIntervalInSeconds(10)
                                    .repeatForever())
                    .build();
            quartz.scheduleJob(job, trigger);
        }

        @Transactional
        void performTask() {
            Task task = new Task();
            task.persist();
        }

        // A new instance of MyJob is created by Quartz for every job execution
        static class MyJob implements Job {

            public void execute(JobExecutionContext context) throws JobExecutionException {
                Arc.container().instance(TaskBean.class).get(). performTask();
            }

        }
    }
}

````

SQL database generation: [link](https://github.com/quarkusio/quarkus-quickstarts/blob/master/quartz-quickstart/src/main/resources/db/migration/V2.0.0__QuarkusQuartzTasks.sql)

**Configuration**
```
quarkus.quartz.store-type=jdbc-cmt
quarkus.quartz.clustered=true
quarkus.quartz.force-start=true

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=password
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost/db

quarkus.hibernate-orm.database.generation=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

quarkus.flyway.connect-retries=10
quarkus.flyway.table=flyway_quarkus_history
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.flyway.baseline-version=1.0
quarkus.flyway.baseline-description=Quartz
```

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/5721868/88631611-b5bc6400-d0b2-11ea-98cc-4c4afe62d8b1.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Microsoft Windows [Versione 10.0.18363.959]

 - Output of `java -version`: 
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)

 - Quarkus version or git rev: 
Quarkus 1.6.1.FINAL

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\Program Files\apache-maven\bin\..
Java version: 1.8.0_201, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk1.8.0_201\jre
Default locale: it_IT, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Additional context**
Runned with:
```
docker run --name some-postgres -e POSTGRES_PASSWORD=password -e POSTGRES_USER=postgres -e POSTGRES_DB=db -d  -p 5432:5432 postgres:alpine
```

**Comment by mkouba** [comment] 2020-07-30 13:05
I've tried to modify our [quartz-quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/master/quartz-quickstart) to schedule the job programmatically (with `quarkus.quartz.force-start=true`) and I didn't run into any problem. We also have a [InjectQuartzSchedulerTest](https://github.com/quarkusio/quarkus/blob/master/extensions/quartz/deployment/src/test/java/io/quarkus/quartz/test/InjectQuartzSchedulerTest.java) for this use case. 

@bobanbg In which mode (dev/test/prod) does the problem occur?

Ideally, pls provide a minimal reproducer app shared on github.

**Comment by bobanbg** [comment] 2020-07-30 13:37
Sure! Here's the repo whith code:  https://github.com/bobanbg/quarz-example

I launched it with Intellij shortcut (green arrow) next to psvm

**Comment by mkouba** [comment] 2020-07-30 13:58
Hm, your example works fine from the command line. So it seems like a class loading problem connected to `@QuarkusMain` started from the IDE. @stuartwdouglas Do you have an idea?

BTW `MyJob` should be public (the docs are already fixed in the master branch).

**Comment by bobanbg** [comment] 2020-07-30 14:19
Yep sorry, I used IDE for debugger and I didn't tried with command line... I confirm code works with command line and NOT work with QuarkusMain from IDE.

PS: I refactored code in the repo and made public MyJob as suggested

**Comment by stuartwdouglas** [comment] 2020-07-30 23:52
The reason why this works in the console but not the ide is that the default Quartz CL model looks like:
        loadHelpers = new LinkedList<ClassLoadHelper>();

        loadHelpers.add(new LoadingLoaderClassLoadHelper());
        loadHelpers.add(new SimpleClassLoadHelper());
        loadHelpers.add(new ThreadContextClassLoadHelper());
        loadHelpers.add(new InitThreadContextClassLoadHelper());

In the IDE all the job classes are on the Class Path, so ThreadContextClassLoadHelper loads the non-quarkus versions of the class, before the correct ones can be loaded from InitThreadContextClassLoadHelper.

**Closed** 2020-07-31 08:18 UTC
Labels: area/scheduler, kind/bug
