### ISSUE TITLE
Fault Tolerance @Fallback with @Timeout not working Properly with Panache ORM

### ISSUE THREAD

**Issue by jclingan** [quarkusio/quarkus#1537] opened 2019-03-17 02:41 UTC
While executing a method using Panache ORM (MyEntity.findById()) that is annotated with `@Fallback` and `@Timeout`, the fallback is always called. The issue may be either with Panache or with SmallRye Fault Tolerance.

If `@Timeout` is is replaced with` @Retry`, the method executes properly. If Panache ORM is not used at all, the method executes properly with either `@Retry` or `@Timeout`.

As a result, the problem seems to be with either Panache ORM or Fault Tolerance `@Timeout`. I have not tried with with vanilla JPA.

I have created a reproducible example here:
https://github.com/jclingan/FallbackBug

~~The example requires Postgres, which can be run - assuming docker is running - with:
`docker run --name postgres -e POSTGRES_USER=admin -e POSTGRES_PASSWORD=admin -e POSTGRES_DB=quarkus -p 5432:5432 postgres`~~ **(Switched to embedded h2 database)**

To test the issue, run:
```
$ mvn compile quarkus:dev
$ curl localhost:8080/timeout
```

**Comment by michalszynkiewicz** [comment] 2019-03-19 12:26
So the problem is that, probably due to a method with `@Timeout` being invoked in a separate thread, `javax.enterprise.context.ContextNotActiveException` is thrown on `MeEntity.findById`.
I will see if I see anything that we could do in this case.

**Comment by michalszynkiewicz** [comment] 2019-03-19 12:45
And comments in `TransactionScopedEntityManager` suggest that we don't want to spawn another `EntityManager` for such cases.
I don't think there is anything sensible we could do with this.
Do you have any suggestions @stuartwdouglas ?

**Comment by kenfinnigan** [comment] 2019-03-22 13:30
Wondering if this is something that can be resolved with SmallRye Context Propagation? @manovotn @FroMage

**Comment by manovotn** [comment] 2019-03-25 08:11
@kenfinnigan @michalszynkiewicz  yea,I think you could make this work with MP context propagation.
Basically it's request scope not being active in another thread if I get it correctly (which is standard behaviour). So having CDI context propagated would make it work.

Alternatively, if you just need the scope to be active but don't care about preserving state from previous thread, you could [manually activate the scope via CDI API](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#activating_request_context).

**Comment by FroMage** [comment] 2019-04-03 08:33
Why don't you get similar errors for all things that require scopes? Like ArC, RESTEasy and others? Surely if all contexts are lost with those annotations you would have noticed the problem sooner, no?

**Comment by enbohm** [comment] 2019-05-03 08:55
I have the same issue with vanilla JPA. A simple class such as
```java
@ApplicationScoped
@Transactional
public class SomeService {

  @PersistenceContext
  EntityManager em;

  @Timeout
  //@Bulkhead // un-comment to make this work  
  public MyEntity find(Long id) {
    return em.find(MyEntity.class, id);
  }
}
```
generates the below stacktrace when  ```SomeService#find(id)``` is called.

What is a bit interesting is that if I add the ```@Bulkhead``` annotation is seem to be working (i.e. no exception is thrown and I get a valid result back).

```
org.jboss.resteasy.spi.UnhandledException: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:234)
	at io.quarkus.resteasy.runtime.ResteasyFilter$ResteasyResponseWrapper.sendError(ResteasyFilter.java:72)
	at io.undertow.servlet.handlers.DefaultServlet.doGet(DefaultServlet.java:175)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:686)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.quarkus.resteasy.runtime.ResteasyFilter.doFilter(ResteasyFilter.java:43)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.opentracing.contrib.jaxrs2.server.SpanFinishingFilter.doFilter(SpanFinishingFilter.java:52)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:91)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$7$1$1.call(UndertowDeploymentTemplate.java:437)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1382)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.context.ContextNotActiveException: interface javax.enterprise.context.RequestScoped
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.delegate(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.RequestScopedEntityManagerHolder_ClientProxy.getOrCreateEntityManager(Unknown Source)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.getEntityManager(TransactionScopedEntityManager.java:91)
	at io.quarkus.hibernate.orm.runtime.entitymanager.TransactionScopedEntityManager.find(TransactionScopedEntityManager.java:135)
	at io.quarkus.hibernate.orm.runtime.entitymanager.ForwardingEntityManager.find(ForwardingEntityManager.java:58)
	at se.acme.quarkus.DefaultGreetingService.find(DefaultGreetingService.java:20)
	at se.acme.quarkus.DefaultGreetingService_Subclass.find$$superaccessor3(Unknown Source)
	at se.acme.quarkus.DefaultGreetingService_Subclass$$function$$15.apply(Unknown Source)
	at io.quarkus.arc.InvocationContextImpl.interceptorChainCompleted(InvocationContextImpl.java:157)
	at io.quarkus.arc.InvocationContextImpl.proceed(InvocationContextImpl.java:177)
	at io.smallrye.faulttolerance.ExecutionContextWithInvocationContext.proceed(ExecutionContextWithInvocationContext.java:59)
	at io.smallrye.faulttolerance.SimpleCommand.run(SimpleCommand.java:89)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:302)
	at com.netflix.hystrix.HystrixCommand$2.call(HystrixCommand.java:298)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:46)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:51)
	at rx.internal.operators.OnSubscribeDefer.call(OnSubscribeDefer.java:35)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
	at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
	at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
	at rx.Observable.unsafeSubscribe(Observable.java:10151)
	at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:56)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction$1.call(HystrixContexSchedulerAction.java:47)
	at io.smallrye.faulttolerance.tracing.TracingConcurrencyStrategy$OpenTracingHystrixCallable.call(TracingConcurrencyStrategy.java:60)
	at com.netflix.hystrix.strategy.concurrency.HystrixContexSchedulerAction.call(HystrixContexSchedulerAction.java:69)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by FroMage** [comment] 2019-05-24 13:25
Now that SR-CP has been merged, perhaps @michalszynkiewicz you can fix this using context propagation? Surely that's the right thing to do, since you're using rxjava underneath so this will break anything that requires ArC, Transactions or RESTEasy unless you use SR-CP.

**Comment by michalszynkiewicz** [comment] 2019-05-24 13:27
Yes, I think it should be doable. Right @manovotn?

**Comment by FroMage** [comment] 2019-05-24 13:38
Note that if you're using rxjava, you get automatic context propagation by importing the `smallrye-context-propagation-propagators-rxjava2` module ;)

So, _in theory_ (Famous Last Words™) that's all it should take for it to to Just Work©

**Comment by michalszynkiewicz** [comment] 2019-05-24 21:35
Sorry, I forgot you are working on the project :)
I will try it on Monday.

**Comment by michalszynkiewicz** [comment] 2019-05-27 10:16
It seems that with `...-rxjava1` and one tiny little fix to the context propagation extension it works ! 

I'll create a PR soon.

**Closed** 2019-05-27 14:40 UTC
Labels: component:persistence, component:smallrye
