### ISSUE TITLE
Gelf logging not working with Graylog 3.2.2

### ISSUE THREAD

**Issue by MrTyre2** [quarkusio/quarkus#7612] opened 2020-03-05 16:01 UTC
Hi everyone

**Describe the bug**
(Describe the problem clearly and concisely.)
I tried the quarkus-logging-gelf extension on my company app and it worked well with Graylog central management in version 2.1.2. The Graylog version was updated to 3.2.2 earlier this week, but now I don't see my application logs being uploaded to Graylog. I tried udp and tcp protocols, but the messages seems to be compressed as you can see in the image below : 
![image](https://user-images.githubusercontent.com/10597884/75998513-3ced1d80-5f01-11ea-9a72-e85e7bf6f714.png)
When uncompressed manually, I can see the fields and the log messages in a JSON format.
If the log is sent directly to a graylog interface, it seems to be working. Problem is that we have a supplementary layer where the log pass through to Graylog, but as the log is compressed, it is processed as broken and is not sent to Graylog.

Also, it seems to be a Quarkus problem as I retrieve some log before quarkus is launched (from the mongo, for instance), but nothing as soon as the app is started.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
The logs from quarkus should not be compressed so that I can see them in the Graylog 3.2.2 interface.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
Logs are compressed and filtered as broken, and not sent from my company log layer to Graylog.

**To Reproduce**
Difficult because there is a third internal layer in my context..
1. Have Graylog 3.2.2 and launch it as an external service.
2. Configure logging-gelf extension to point to this Graylog.
3. Logs are compressed

**Configuration**
```properties
# Add your application.properties here, if applicable.
#
# configuration
#
quarkus.mongodb.connection-string=mongodb://localhost:27017
quarkus.http.port=8082
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=graylog.mycompany.net
quarkus.log.handler.gelf.port=12201
quarkus.log.handler.gelf.include-full-mdc=true
```

**Environment (please complete the following information):**
 - Output of `java -version`: Java 8
 - Plateform: Windows 10  
 - Quarkus version or git rev: 1.2.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.2

I was thinking maybe it can be good to have another option to sent the uncompressed log if needed, like quarkus.log.handler.gelf.zip=false or something. Maybe I totally misunderstood the problem, so thanks for any help :)

**Comment by loicmathieu** [comment] 2020-03-06 10:22
@MrTyre2 GELF UDP is compressed via GZIP (it's no clearly documented in the site of the library we usehttps://logging.paluch.biz/) and it's supported by Graylog.

GELF TCP is not compressed.

You can turn off the compression using `?compression=false` on the URL of your Graylog server.

I assume the issue here is because you have something between your application and Graylog, as it's not very common and the library we used dismiss the addition of the compress option as a configuration parameter because nobody really needs it (https://github.com/mp911de/logstash-gelf/issues/85) I suggest we do the same on Quarkus, don't provide this configuration option as it should not be touched on standard use cases.

**Comment by MrTyre2** [comment] 2020-03-06 16:25
Hey @loicmathieu, indeed the issue seems to come from the additional layer, I heard the TCP protocol is not yet activated but we'll work on it to make it work. Got your explanations right though, thanks for that !

**Comment by MrTyre2** [comment] 2020-03-11 08:29
Hello @loicmathieu, I did another test : I tried to reach directly the graylog server with Gelf UDP, but the logs were still not supported by Graylog.. Do you think it is a Graylog issue or a Quarkus log issue ? 
Is there a way to go around the quarkus-logging-gelf extensions to be able to log without interfering with Quarkus inner log management ? Thanks

**Comment by loicmathieu** [comment] 2020-03-12 14:32
@MrTyre2 I test our integration test with 3.2.2 and it works: https://github.com/quarkusio/quarkus/tree/master/integration-tests/logging-gelf

> Is there a way to go around the quarkus-logging-gelf extensions to be able to log without interfering with Quarkus inner log management ? Thanks

The purpose of the extension is to use the Quarkus log support to send logs to Graylog. If you don't want to use it you can directly use https://logging.paluch.biz/ it works fine with Quarkus ...

**Comment by loicmathieu** [comment] 2020-04-02 09:08
I'll close this one as it works fine with Graylog 3.2.2.
If you still think there is an issue, please reopen it and provides a reproducer.

**Closed by loicmathieu** 2020-04-02 09:08 UTC
Labels: area/logging, kind/question
