### ISSUE TITLE
@Blocking annotation not working in dev mode (gRPC Service)

### ISSUE THREAD

**Issue by atilli** [quarkusio/quarkus#17307] opened 2021-05-18 05:54 UTC
Method is marked as blocking (uses Panache later) . It works when running jar with java command.

# Code
`
@Override
    @Blocking
    public Uni<RouteReply> routeTest(RouteTestRequest request) {
`

# Result in dev mode: 

in dev mode however:

{
  "error": "2 UNKNOWN: java.lang.IllegalStateException - You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread."
}

Did not not find in documentation, that this would be a feature. Annotation is from
`
import io.smallrye.common.annotation.Blocking;
`
Quarkus Version
`
 <quarkus.platform.version>1.13.4.Final</quarkus.platform.version>
`

**Comment by geoand** [comment] 2021-05-18 06:51
Can you attach an example application please? I was not able to try reproduce this in a simple test

**Comment by michalszynkiewicz** [comment] 2021-05-18 07:25
This should be fixed with https://github.com/quarkusio/quarkus/pull/16830

Could you try with Quarkus 2.0.0.Alpha2?

**Comment by michalszynkiewicz** [comment] 2021-05-18 07:25
@geoand the problem was that after reload the interceptors were lost

**Comment by geoand** [comment] 2021-05-18 07:38
Okay, I was testing main so that's why I didn't see it

**Comment by cescoffier** [comment] 2021-05-18 11:29
So can we close it?

**Closed** 2021-05-19 06:56 UTC
Labels: area/devmode, area/grpc

**Comment by gaetancollaud** [comment] 2021-05-25 14:24
My findings:
* 1.12.2 => no bug
* 1.13.x => bug
* 2.0.0.Alpha2 => no bug

So either roll back to 1.12.2 or use the alpha version.
