### ISSUE TITLE
ContainerResponseFilter does not filter OIDC redirects

### ISSUE THREAD

**Issue by peter-lejon-v** [quarkusio/quarkus#40547] opened 2024-05-10 08:50 UTC
### Describe the bug

ContainerResponseFilter and ServerRequestFilter do not filter OIDC redirects for unauthorized requests

### Expected behavior

ContainerResponseFilter and ServerRequestFilter filters all http responses

### Actual behavior

OIDC redirects are not filtered

### How to Reproduce?

using 

```xml
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-oidc</artifactId>
</dependency>
```

And adding a ContainerResponseFilter 

```java
import jakarta.ws.rs.container.ContainerRequestContext;
import jakarta.ws.rs.container.ContainerResponseContext;
import jakarta.ws.rs.container.ContainerResponseFilter;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.ext.Provider;
import java.io.IOException;

@Provider
public class ResponseInterceptor implements ContainerResponseFilter {

  @Override
  public void filter(
      ContainerRequestContext requestContext, ContainerResponseContext responseContext)
      throws IOException {

    if (responseContext.getStatus() == Response.Status.FOUND.getStatusCode()
        && Boolean.parseBoolean(requestContext.getHeaderString("HX-Request"))) {
      String location = responseContext.getHeaderString("Location");
      if (location != null) {
        responseContext.getHeaders().add("HX-Redirect", location);
        responseContext.setStatus(Response.Status.OK.getStatusCode());
      }
    }
  }
}
```

### Output of `uname -a` or `ver`

5.4.204-113.362.amzn2.x86_64 #1 SMP Wed Jul 13 21:34:30 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 21.0.3 2024-04-16 LTS OpenJDK Runtime Environment (Red_Hat-21.0.3.0.9-1) (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM (Red_Hat-21.0.3.0.9-1) (build 21.0.3+9-LTS, mixed mode, sharing)

### Quarkus version or git rev

<quarkus.platform.version>3.10.0</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6

**Comment by johanhugg** [comment] 2024-05-10 08:53
I think this only applies when using the keycloak extension

**Comment by sberyozkin** [comment] 2024-05-10 09:27
@peter-lejon-v It looks like an invalid issue, `quarkus-oidc` does not operate as part of the JAX-RS chain and must also work for reactive routes, static resources accessible outside of the JAX-RS chain. 

But, it initiates redirects by throwing `AuthenticationRedirectException` - which is the only possible link to JAX-RS, you can use a JAX-RS ExceptionMapper to capture it . I'm not sure though what should happen in the exception mapper - you should either make sure a mapped Response contains the Location from `AuthenticationRedirectException` or rethrow the exception after adding extra custom headers. 

I'm going to close this issue shorty as an invalid issue, but I'd appreciate if you could test the exception mapper suggestion, and open another bug issue if the exception mapping does not help

Thanks

**Comment by johanhugg** [comment] 2024-05-10 09:34
> @peter-lejon-v It looks like an invalid issue, `quarkus-oidc` does not operate as part of the JAX-RS chain and must also work for reactive routes, static resources accessible outside of the JAX-RS chain.
> 
> But, it initiates redirects by throwing `AuthenticationRedirectException` - which is the only possible link to JAX-RS, you can use a JAX-RS ExceptionMapper to capture it . I'm not sure though what should happen in the exception mapper - you should either make sure a mapped Response contains the Location from `AuthenticationRedirectException` or rethrow the exception after adding extra custom headers. CC @michalvavrik
> 
> I'm going to close this issue shorty as an invalid issue, but I'd appreciate if you could test the exception mapper suggestion, and open another bug issue if the exception mapping does not help
> 
> Thanks

Using something like this

```java
@Provider
public class AuthenticationRedirectExceptionMapper implements ExceptionMapper<AuthenticationRedirectException> {
  @Override
  public Response toResponse(AuthenticationRedirectException exception) {
    return Response.accepted().build();
  }
}
```
Is not being invoked, am I missing something?

**Comment by peter-lejon-v** [comment] 2024-05-10 09:41
> quarkus-oidc does not operate as part of the JAX-RS

This is what I was thinking, albeit hoping that it wasn't so.

I did se that there is a request filter `io.quarkus.oidc.common.OidcRequestFilter;` but no responsefilter? Is that correct

**Comment by sberyozkin** [comment] 2024-05-10 10:00
@peter-lejon-v 

>I did se that there is a request filter io.quarkus.oidc.common.OidcRequestFilter; but no responsefilter? Is that correct

This filtering is about intercepting direct requests between Quarkus OIDC and the OIDC provider, they are not used to manage the communication between the client and the Quarkus endpoint.

As far as the redirects are concerned, you should be able to use Vert.x filter which is where this is managed.

However, AuthenticationRedirectException mapper should work, so I'll open a dedicated bug issue to handle it

**Comment by sberyozkin** [comment] 2024-05-10 10:03
@michalvavrik So do we close this issue then, right ? And ask @peter-lejon-v to open another one once the reproducer is available ?

**Comment by johanhugg** [comment] 2024-05-10 10:28
I'll try my best. Let me know if I should add anything more.

Following the example in the [link](https://quarkus.io/version/main/guides/security-proactive-authentication#customize-auth-exception-responses)

```java
@Provider
@Priority(Priorities.AUTHENTICATION)
public class AuthenticationFailedExceptionMapper implements ExceptionMapper<AuthenticationFailedException> {

  @Context
  UriInfo uriInfo;

  @Override
  public Response toResponse(AuthenticationFailedException exception) {
    return Response.status(401).header("WWW-Authenticate", "Basic realm=\"Quarkus\"").build();
  }
}
```

![image](https://github.com/quarkusio/quarkus/assets/1291530/8fa05069-f8c4-4e60-abe2-fed6c6d4744d)
The frontend correctly tries to follow the new URL provided by the backend, but since it's a request invoked from Javascript the redirect breaks the flow.

![image](https://github.com/quarkusio/quarkus/assets/1291530/c1e42c66-a0f6-4c70-8100-f6515c9cefb1)
The header set in the example is subsequently not returned in the response (302 found)

With debugging enabled, I can see that the exception mapper is not called (and also as mentioned the header is not present).

Changing it to just "Exception" instead of a specific exception makes no difference.

I can also just make a repository with complete code example if that helps.

**Comment by johanhugg** [comment] 2024-05-10 10:36
> > I can also just make a repository with complete code example if that helps.
> 
> 
> 
> that would be fantastic; especially in case if that is a bug, I would have a lot of guessing and that's time consuming.

I'll get right on it. Thank you for the quick replies!

**Comment by sberyozkin** [comment] 2024-05-10 10:57
@johanhugg, as far as the problem you are trying to solve, there should be an easier way:

https://quarkus.io/version/main/guides/security-oidc-code-flow-authentication#single-page-applications 

Have a look please

**Comment by sberyozkin** [comment] 2024-05-10 19:09
@johanhugg @peter-lejon-v Let me close it, please open an issue with a reproducer if mapping `AuthenticationRedirectException` does not work, though if you can make things work by configuring Quarkus to avoid redirects as explained in the linked OIDC doc, then it would be simpler.

See also #40562

**Closed by sberyozkin** 2024-05-10 19:09 UTC
Labels: kind/bug, area/oidc, triage/needs-reproducer

**Comment by sberyozkin** [comment] 2024-05-13 10:45
@johanhugg @peter-lejon-v FYI, the reason you could not catch `AuthenticationRedirectException` was that it is actually not thrown during the challenge, but only in a few other cases, apologies for the confusion. In any case, please check my previous comment for the suggestions, thanks

**Comment by peter-lejon-v** [comment] 2024-05-13 12:54
Sorry for the late reply. I understand that this is not a bug (so lets leave it closed), and that the feature is a bit HTMX specific.
see this [this](https://github.com/bigskysoftware/htmx/issues/2052) HTMX issue for a bit more context.

I solved it by adding an interceptor to the vert.x router using the guide [here](https://quarkus.io/version/main/guides/security-proactive-authentication#customize-auth-exception-responses)


```java
package org.acme;

import io.vertx.ext.web.Router;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.enterprise.event.Observes;

@ApplicationScoped
public class VertxHandler {

  public void init(@Observes Router router) {
    router.route().handler(new VertXMiddeware());
  }
}
```

and 

```java
package org.acme;

import io.vertx.core.Handler;
import io.vertx.ext.web.RoutingContext;
import jakarta.ws.rs.core.Response;

public class VertXMiddeware implements Handler<RoutingContext> {

  @Override
  public void handle(RoutingContext ctx) {

    ctx.addHeadersEndHandler(
        v -> {
          if (ctx.response().getStatusCode() == Response.Status.FOUND.getStatusCode()
              && Boolean.parseBoolean(ctx.request().headers().get("HX-Request"))) {
            String location = ctx.response().headers().get("Location");
            if (location != null) {
              ctx.response()
                  .setStatusCode(Response.Status.OK.getStatusCode())
                  .putHeader("HX-Redirect", location);
            }
          }
        });
    ctx.next();
  }
}
```

**Comment by peter-lejon-v** [comment] 2024-05-13 13:59
It can be worth noting, that this only works with 

```java
@Authenticated
```

and not

```yaml
quarkus:
  http:
    auth:
      permission:
        authenticated:
          paths: /*
          policy: authenticated
```
