### ISSUE TITLE
Rest Client guide should show how to test the client

### ISSUE THREAD

**Issue by adamu** [quarkusio/quarkus#9698] opened 2020-05-31 10:25 UTC
I'm looking at the [rest client guide](https://quarkus.io/guides/rest-client).

It demonstrates how to set up a rest client using dependency injection. However, it doesn't demonstrate how to test the client.

It does include tests, but the tests are testing a Rest server endpoint that wraps the use of the rest client. It would be helpful to provide an example of testing the client directly, rather than via a level of indirection via a local server resource.

**Comment by tobad357** [comment] 2020-05-31 13:45
Adding on to this
We run tests in parallel and test with MockServer, the problem is there doesn't seem to be an easy way to change the URL/port the clients point to.

We need a way to start a MockServer with a random port and then point the client to that random port. Basically override the config in the test

**Comment by geoand** [comment] 2020-06-01 05:32
@adamu can you elaborate a little more on what you would like to see?

@tobad357 you can manually start Wiremock and make the rest-client point to it, see [this](https://github.com/geoand/quarkus-test-demo/blob/master/src/test/java/org/acme/getting/started/country/WiremockCountries.java) for example

**Comment by adamu** [comment] 2020-06-01 05:53
A test that calls `countriesService.getByName(name)` and `countriesService.getByNameAsync(name)` directly from the test, and shows how to assert the results would be useful.

I think that the test tools are likely to be different. The current example is using `RestAssured`, but for testing the client I think it's more likely that the tester will want to call the client method directly and then perform assertions on the response object (at least, that's how I'm currently approaching it).

**Comment by geoand** [comment] 2020-06-01 06:59
@adamu would you like to contribute a documentation Pull Request?

**Comment by adamu** [comment] 2020-06-01 07:31
I'm currently working out how to do it nicely on the project I'm working on. Let me finish that (could be a few days), and then post what I'm doing here. If you think it's sensible, I can look at updating the guide.

**Comment by geoand** [comment] 2020-06-01 07:33
Sounds like a plan

**Comment by geoand** [comment] 2024-02-27 09:59
The documentation now does show how to test the client, so I am going to close this

**Closed by geoand** 2024-02-27 09:59 UTC
Labels: area/documentation, area/housekeeping
