### ISSUE TITLE
test-resource-h2 does not work

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#38273] opened 2024-01-18 07:32 UTC
### Describe the bug

Upgrade to Quarkus 3.7.0.CR1, the test-resource-h2 does not work as expected.

The example project: https://github.com/hantsy/quarkus-sandbox/tree/master/resteasy-classic
The test used H2 test resource, https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/src/test/java/com/example/PostRepositoryTest.java

### Expected behavior

The test should be got passed.

### Actual behavior

The original test failed with the following exception.

```bash 
Build step io.quarkus.agroal.deployment.AgroalProcessor#build threw an exception: 
io.quarkus.runtime.configuration.ConfigurationException: 
Unable to find a JDBC driver corresponding to the database kind 'h2' for the datasource 'jdbc' (available: 'postgresql'). 
Check if it's a typo, otherwise provide a suitable JDBC driver extension, 
define the driver manually, or disable the JDBC datasource by 
adding 'quarkus.datasource."jdbc".jdbc=false' to your configuration 
if you don't need it.
```

### Output of `uname -a` or `ver`

Windows

### Output of `java -version`

21

### Quarkus version or git rev

3.7.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by geoand** [comment] 2024-01-18 08:24
You have configured:

```
quarkus.datasource.db-kind=postgresql
```

[here](https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/src/main/resources/application.properties#L7).

Try removing it

**Comment by hantsy** [comment] 2024-01-18 11:51
@geoand I used a `H2Profile` to pick up the application-h2.properties and H2TestResource.

Check the content of application-h2.properties, https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/src/test/resources/application-h2.properties

**Comment by geoand** [comment] 2024-01-18 11:53
Missed that, sorry.

**Comment by geoand** [comment] 2024-01-18 11:54
This might be a config issue, do you mind changing 

```properties
quarkus.datasource.db-kind=postgresql
```

to

```properties
%prod.quarkus.datasource.db-kind=postgresql
```

and seeing if thar works?

**Comment by hantsy** [comment] 2024-01-18 12:00
The same result https://github.com/hantsy/quarkus-sandbox/actions/runs/7569583589/job/20613206204

**Comment by yrodiere** [comment] 2024-01-18 12:01
`db-kind` is a build-time property... I'm not sure how this used to work, but I'd be surprised if test extensions supported rebuilding the app... ?

You might want to define two separate datasources/PUs instead, but that's been introduced only recently (probably not included in any relase ATM): https://quarkus.io/version/main/guides/hibernate-orm#persistence-unit-active

**Comment by geoand** [comment] 2024-01-18 12:01
Gotcha.

@yrodiere @gsmet this one sounds up your alley

**Comment by yrodiere** [comment] 2024-01-18 12:02
@geoand see above :)

**Comment by hantsy** [comment] 2024-01-18 12:02
when using a profile, the profile based properties should override the default value at build time.

**Comment by yrodiere** [comment] 2024-01-18 12:05
> when using a profile, the profile based properties should override the default value at build time.

I mean I agree it'd be nice, I'm just not sure it's how it's been designed. And evidently that's not working.

Now if @geoand confirmed it's supposed to work that way, maybe there's something broken in the Agroal extension, some build step not being re-executed upon switching profiles.

**Comment by hantsy** [comment] 2024-01-18 12:07
Check the historical version, https://github.com/hantsy/quarkus-sandbox/tree/64ba5f1b966e0b355af34686b61cff6a2498ac9d/resteasy-classic, which used Quarkus 3.6.4, the build was working well.

**Comment by geoand** [comment] 2024-01-18 12:10
When using `@TestProfile`, Quarkus does re-augment the application and therefore the profile specific properties should be applied. 

Admitedly here we have the complication that a profile specific file is being used, so there could be something wrong. 
Maybe @radcortez can take a look

**Comment by yrodiere** [comment] 2024-01-18 12:14
Alright then.

I'd personally bet on a bug in classloading and/or extension loading, since the error seems to indicate the H2 JDBC extension was ignored (Quarkus doesn't know about the driver), and the H2 JDBC extension here is a test-only dependency: https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/pom.xml#L88-L92

I doubt we have many tests checking that kind of setup...

**Comment by yrodiere** [comment] 2024-01-18 12:16
@hantsy if my assumption is right, a workaround would be to change the scope of the dependency. Not that it's an acceptable solution, of course, but it might help pin down the problem.

**Comment by yrodiere** [comment] 2024-01-18 12:17
Hey, wait a minute. It's worse than that: the Quarkus H2 JDBC extension driver is not present in your dependencies... Try adding that, first with the `test` scope and if it doesn't work, with the default scope?

**Comment by yrodiere** [comment] 2024-01-18 12:23
> Check the historical version, https://github.com/hantsy/quarkus-sandbox/tree/64ba5f1b966e0b355af34686b61cff6a2498ac9d/resteasy-classic, which used Quarkus 3.6.4, the build was working well.

BTW this part of the build logs is interesting:

> 2024-01-04 01:23:56,878 INFO  [io.qua.dev.com.ContainerShutdownCloseable] (main) Dev Services for PostgreSQL shut down.
> [INFO] H2 database started in TCP server mode; server status: TCP server running at tcp://10.1.0.61:9092 (only local connections)
> 2024-01-04 01:23:59,271 WARN  [io.qua.config] (main) Unrecognized configuration key "quarkus.datasource.jdbc.db-kind" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo

Wasn't your build simply running against PostgreSQL before?

**Comment by hantsy** [comment] 2024-01-19 01:23
> Hey, wait a minute. It's worse than that: the Quarkus H2 JDBC extension is not present in your dependencies... Try adding that, first with the `test` scope and if it doesn't work, with the default scope?

I only want to use h2 in test scope for db related repository test, and not want to be packaged in the final app.

**Comment by yrodiere** [comment] 2024-01-19 06:53
> > Hey, wait a minute. It's worse than that: the Quarkus H2 JDBC extension is not present in your dependencies... Try adding that, first with the `test` scope and if it doesn't work, with the default scope?
> 
> I only want to use h2 in test scope for db related repository test, and not want to be packaged in the final app.

You're going to have to try to help us help you, here.

If you want to use H2 in tests, you at least need to use the H2 jdbc extension _in tests_. At least try that before saying you don't want it in the packaged application?

**Comment by hantsy** [comment] 2024-01-19 10:53
@yrodiere Ok, remove the scope, got the same result, https://github.com/hantsy/quarkus-sandbox/actions/runs/7582734244/job/20652898716#step:5:183

**Comment by hantsy** [comment] 2024-01-19 10:54
I am afraid if all test resources have this issue now. Some changes in 3.7 about this feature?

**Comment by yrodiere** [comment] 2024-01-19 13:06
> @yrodiere Ok, remove the scope, got the same result, https://github.com/hantsy/quarkus-sandbox/actions/runs/7582734244/job/20652898716#step:5:183

You don't need to remove the zcope, you need to add a dependency to quarkus-jdbc-h2 with the test scope.

> Hey, wait a minute. It's worse than that: the Quarkus H2 JDBC extension is not present in your dependencies... Try adding that, first with the test scope and if it doesn't work, with the default scope?

**Comment by hantsy** [comment] 2024-01-21 01:32
> You don't need to remove the scope, you need to add a dependency to quarkus-jdbc-h2 with the test scope.

Got new exception after adding `quarkus-jdbc-h2` to `test` scope.

```bash 
java.lang.RuntimeException: 
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: ]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#configurationDescriptorBuilding threw an exception: io.quarkus.runtime.configuration.ConfigurationException: Unable to find datasource '<default>' for persistence unit '<default>': Datasource '<default>' is not configured. To solve this, configure datasource '<default>'. Refer to https://quarkus.io/guides/datasource for guidance.
```

Github action build result: https://github.com/hantsy/quarkus-sandbox/actions/runs/7598121081/job/20693747471

**Comment by yrodiere** [comment] 2024-01-22 10:16
Your config is invalid. I guess you didn't notice it before because Quarkus was ignoring it and just running tests against PostgreSQL.

This config:

```
quarkus.datasource.jdbc.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
```

Should be:

```
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
```

Or even, since the driver is inferred by Quarkus:

```
quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
```

**Comment by hantsy** [comment] 2024-01-23 01:30
Mentioned above, I need to use Postgres at runtime. 

But I used a [`H2Profile`](https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/src/test/java/com/example/H2Profile.java) for [this test](https://github.com/hantsy/quarkus-sandbox/blob/master/resteasy-classic/src/test/java/com/example/PostRepositoryTest.java#L17), check the profile based properties file application-h2.properties.

```properties
quarkus.datasource.jdbc.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:tcp://localhost/mem:test
quarkus.datasource.jdbc.driver=org.h2.Driver
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false
```

And the testing codes worked well in the previous 3.6.4. 
@yrodiere Any update of profile/test-resource overriding in the 3.7?

**Comment by yrodiere** [comment] 2024-01-23 08:33
> And the testing codes worked well in the previous 3.6.4.

Mentioned above, your previous builds were using Postgres for testing too.
Your configuration was being ignored, most likely due to a bug that was fixed since then. And now we're discovering that your configuration is simply invalid.

Anyway, if you're going to continuously assume bugs without even trying to understand suggestions, this is going to take forever. Here's a fix: https://github.com/hantsy/quarkus-sandbox/pull/1917
With that, I'm getting:

```shell script
$ cd resteasy-classic
$ mvn clean verify
...
[INFO] Results:
[INFO] 
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0
...
```

You're welcome.

This was not a bug; closing.

**Closed by yrodiere** 2024-01-23 08:33 UTC
Labels: kind/bug, area/persistence, area/testing, env/windows

**Comment by yrodiere** [comment] 2024-01-23 11:39
> So the `db-kind` is moved out of jdbc(shared with reactive settings) in Quarkus 3.7?

No. It's never been there. Even in 2.7: https://quarkus.io/version/2.7/guides/datasource#jdbc-datasource

Again, your configuration was simply being ignored, and it turns out it was invalid.
