### ISSUE TITLE
Arquillian adapter - @Before and @After callbacks are not invoked

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#3528] opened 2019-08-15 07:10 UTC
It seems that Arquillian's `ClientBeforeAfterLifecycleEventExecuter` invokes the callbacks only if `org.jboss.arquillian.container.test.impl.client.protocol.local.LocalProtocol` is used. Which is not the case for Quarkus.

See
https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/execution/ClientBeforeAfterLifecycleEventExecuter.java#L65
and
https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/RunModeUtils.java#L112

In theory, we should be able to invoke the callbacks ourselves. 

There is one problem though. The callbacks are invoked on the original test class whereas the test methods are invoked upon a "enhanced" test class loaded by the app class loader (`RuntimeClassLoader`). In other words, we could invoke the callbacks but it would be useless (e.g. it would not be possible to assert the static members set in the callbacks).

**Comment by mkouba** [comment] 2019-08-15 07:39
An ugly solution would be to invoke the callbacks manually, i.e. find all callbacks and invoked them via reflection.

**Comment by kenfinnigan** [comment] 2019-08-15 12:48
I'd modified the QuarkusExtension to register an observer for https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/execution/BeforeLifecycleEventExecuter.java which works, but they're operating on different instances of the test class.

**Comment by kenfinnigan** [comment] 2019-08-15 12:50
Can we extend https://github.com/arquillian/arquillian-core/blob/master/container/test-impl-base/src/main/java/org/jboss/arquillian/container/test/impl/client/protocol/local/LocalProtocol.java for Quarkus to then have our own execute method creation?

**Comment by kenfinnigan** [comment] 2019-08-15 13:16
So I just tried extending it, but I get errors complaining about two Local Protocols being registered

**Comment by manovotn** [comment] 2019-08-15 13:23
Or we would need a way to fully provide the test instance to Arquillian so that it operates on the enhanced version right away, that should solve it too.
But for that we would need to update Arquillian (from what I know you cannot do that now) and then I am not sure it would work correctly with various TCKs which are presumably relying on older versions...

**Comment by kenfinnigan** [comment] 2019-08-15 13:26
Ok, so I've now got `LocalProtocol` working and the `@Before` and `@After` are triggered, but the test instance being used for Before/After is different from the one used in the test execution.

Having looked at `Arquillian`, I'm not sure there's a way to override it creating an instance directly.

**Comment by manovotn** [comment] 2019-08-15 13:33
Hmm, looks like (MP) TCKs are already running on older version (1.1.13 BOM) then what Quarkus hopes to have (1.4.1 BOM). So maybe it would be possible to make a change in Arq and dep. on newer version?

**Comment by kenfinnigan** [comment] 2019-08-15 18:07
Bit of an update before going on PTO.

Switching the Arquillian container to use the `LocalProtocol` means that the `@Before` methods are executed. However, test class instances are still different.

I tried creating a `TestEnricher` to see if we could replace the test class instance with the one Quarkus creates, but that results in the `@Before` methods executing with a different instance, as the instance from inside `Arquillian` appears to be used instead. Can't win!

A most recent attempt was using a `BeforeTestLifecycleEvent` observer to set the values of the fields from the Arc instance into the instance used by Arquillian. However, I hit an issue with it not being able to set the value of a Bean instance causing `Caused by: java.lang.IllegalArgumentException: Can not set io.astefanutti.metrics.cdi.se.CounterFieldTagBean field io.astefanutti.metrics.cdi.se.CounterFieldTagBeanTest.bean to io.astefanutti.metrics.cdi.se.CounterFieldTagBean`.

A `MetricRegistry` instance could be set ok, but not the Bean.

That's as far as I can dig before PTO, hopefully one of you has more success in finding a solution

**Comment by mkouba** [comment] 2019-08-16 06:09
> Switching the Arquillian container to use the LocalProtocol means that the @Before methods are executed. However, test class instances are still different.

Yeah, this was the first thing I was trying to use but unfortunately we can't use the local protocol because the test class must be loaded by the `RuntimeClassLoader`.

> I tried creating a TestEnricher ...

AFAIK `TestEnricher` cannot be used to replace the test instance.

> That's as far as I can dig before PTO, hopefully one of you has more success in finding a solution...

A quick and dirty solution would be to [invoke the callbacks via reflection](https://github.com/quarkusio/quarkus/issues/3528#issuecomment-521547637). Maybe we could use this as a short-term solution and explore other possibilities later.

**Comment by mkouba** [comment] 2019-08-16 09:02
I've created a branch with the JUnit-specific short-term workaround: https://github.com/mkouba/quarkus/tree/issue-3528. @kenfinnigan it would we great if you could verify whether this helps with the MP Metrics TCK. 

@manovotn is going to try to find a "correct" solution, i.e. to make it possible to slip the test class instance on the Arquillian side.

**Comment by manovotn** [comment] 2019-08-16 12:29
> @manovotn is going to try to find a "correct" solution, i.e. to make it possible to slip the test class instance on the Arquillian side.

So I spent half a day poking around Arq and how it works with junit. I tried to create an extension point in Arq where we could supply the test instance through simple service loader mechanism.
However, I ran into bunch of problems, biggest of which is the fact that Arq. junit operates with pre-created `org.junit.runners.model.FrameworkMethod` from junit. That class still has wires to the "wrong" `Method` (loaded from a `Class` that came from different CL). This in practice means that most attempts to forge the test class end in `java.lang.IllegalArgumentException: object is not an instance of declaring class` because the `Method` instance doesn't belong to the provided test instance.

Now, `FrameworkMethod` is created when `Arquillian` impl of `BlockJUnit4ClassRunner` is created, therefore we would need to be able to pass in our `Class` instance at that point. But that is too soon for Quarkus isn't started yet. At least that's my understanding of things.

Maybe we should ask some Arq. gurus on how to properly supply our own test instance or whether it's even possible - @MatousJobanek @bartoszmajsak

Personally, I think we are better off with Martin's solution and leaving Arq. untouched, but being no Arq. expert, I can easily be missing something ;)

**Comment by mkouba** [comment] 2019-08-16 13:01
For the record - #206 describes some of the problems I encountered when trying to leverage the existing Arq protocols.

> Personally, I think we are better off with Martin's solution and leaving Arq. untouched...

Note that the Arquillian adapter is still considered an internal tool required for MP TCKs. In other words, I'm fine with adding a hack just to make the TCK pass ;-).

**Comment by jmartisk** [comment] 2019-08-20 07:53
Ken is now on PTO, so for now I tried the temporary solution and it seems it works. Will use it to dig deeper into the TCKs and find more issues :)

**Comment by manovotn** [comment] 2019-08-26 14:23
@kenfinnigan just as an FYI, these were the things that @jmartisk found blocking it and I tried fixing in the meantime:
* https://github.com/quarkusio/quarkus/pull/3614
* https://github.com/quarkusio/quarkus/issues/3594
* https://github.com/quarkusio/quarkus/issues/3619

Last of these is still open as my previous solution was flawed but it now has a PR (by Martin) that fully solves it.

A little off topic: I also consulted Matous who formerly worked on Arq. and he gave me the same conclusion I came to before - that with junit 4 you cannot replace test instance with your own without changes to junit core. So we should be sticking to the workaround Martin devised for Before/After methods.

That's all I know, maybe @jmartisk did some more digging that I am unaware of :-)

**Comment by jmartisk** [comment] 2019-08-27 06:08
@kenfinnigan Welcome back! I've been digging into the TCK quite heavily for a week and I think I'm getting close to sending an initial PR. Some tests will still be excluded because of unimplemented things, some will be excluded because of things that can't work in Quarkus by design. 
Unfortunately we will require some changes in the TCK as well, which is a bit weird, but.. See the [list of Quarkus related TCK issues](https://github.com/eclipse/microprofile-metrics/issues?utf8=%E2%9C%93&q=is%3Aissue+label%3Aquarkus-tck-issue+). So I will also take care of releasing 2.0.2 of the TCK and upgrading it in Quarkus. If you want to help, there will be the excluded tests - I'd like to get an initial version merged quite soon even if not everything is resolved.

**Comment by jmartisk** [comment] 2019-08-28 13:20
List of remaining tasks:
- Merge a permanent fix for this Arquillian issue with Before/After methods
- Merge https://github.com/eclipse/microprofile-metrics/pull/432 and https://github.com/eclipse/microprofile-metrics/pull/429 into MP Metrics and release 2.0.2 of the spec 
- Either merge PR https://github.com/quarkusio/quarkus/pull/3731 or include the workaround in TCK: https://github.com/eclipse/microprofile-metrics/pull/433
- Resolve issue https://github.com/quarkusio/quarkus/issues/3673 (optional, I have a workaround for this in my branch)
- Update to Metrics spec 2.0.2 in my branch

And then I can send a PR with the MP Metrics TCK for Quarkus.
The main problem and the only I can't really resolve all by myself right now is the first one :)

**Comment by jmartisk** [comment] 2019-08-28 13:28
If https://github.com/jmartisk/quarkus/commit/c91b8310541217a87f7006bb113393cab7a4a00f can be considered a permanent solution I can simply add that into my PR and get everything ready probably tomorrow

**Comment by jmartisk** [comment] 2019-08-28 13:36
Also not sure about the status of https://github.com/quarkusio/quarkus/pull/3731, I see there are some unresolved issues with it. I can include a workaround in the TCK but as I said, we don't want to pollute it too much

**Comment by mkouba** [comment] 2019-08-28 13:58
> If jmartisk@c91b831 can be considered a permanent solution I can simply add that into my PR and get everything ready probably tomorrow

+1

> Also not sure about the status of #3731

This PR should be ready - the last failures were most probably unrelated. I'm waiting for the next CI run ;-).

**Comment by mkouba** [comment] 2019-08-28 14:41
@jmartisk FYI I've just merged https://github.com/quarkusio/quarkus/pull/3731.

**Closed** 2019-08-30 19:10 UTC
Labels: bug, component:testing
