### ISSUE TITLE
Native Image with Custom Config and OpenTracing

### ISSUE THREAD

**Issue by radcortez** [quarkusio/quarkus#9086] opened 2020-05-05 11:36 UTC
**Describe the bug**
There seems to be a weird combination between custom MP Config Source and Opentracing in Quarkus that fails to run the project in native mode.

**Expected behavior**
Native image should run as normal.

**Actual behavior**
Native image runs fails with:

```
ERROR: Failed to start application
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.jboss.resteasy.microprofile.config.ServletConfigSource could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:175)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:32805)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:38)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:94)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:26)
	at org.jboss.resteasy.microprofile.config.ServletConfigSource.<init>(ServletConfigSource.java:21)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 14 more
Caused by: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:796)
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:23)
	... 17 more

May 05, 2020 12:06:49 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Error running Quarkus application
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:307)
	at io.quarkus.runtime.Application.start(Application.java:89)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSource: Provider org.jboss.resteasy.microprofile.config.ServletConfigSource could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:581)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:803)
	at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:721)
	at java.util.ServiceLoader$3.next(ServiceLoader.java:1394)
	at java.lang.Iterable.forEach(Iterable.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.discoverSources(SmallRyeConfigBuilder.java:74)
	at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:175)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:32805)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:38)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:94)
	... 6 more
Caused by: java.lang.RuntimeException: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:26)
	at org.jboss.resteasy.microprofile.config.ServletConfigSource.<init>(ServletConfigSource.java:21)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.util.ServiceLoader$ProviderImpl.newInstance(ServiceLoader.java:779)
	... 14 more
Caused by: java.lang.InstantiationException: Type `org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
	at java.lang.Class.newInstance(DynamicHub.java:796)
	at org.jboss.resteasy.microprofile.config.BaseServletConfigSource.<init>(BaseServletConfigSource.java:23)
	... 17 more
```
**To Reproduce**
Sample project here:
https://github.com/radcortez/microprofile-samples

1. Build project with `mvn verify`
2. Move to the folder `services\number-api`.
3. Run mvn verify -Pnative
4. Run ./target/number-api-runner

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.http.port=8081

# Logging
quarkus.log.console.enable=true
quarkus.log.console.format=%d{yyyy-MM-dd HH:mm:ss} %-5p [%c{3.}]] (%t) %s%e%n
quarkus.log.console.level=DEBUG
quarkus.log.console.color=true

# Tracking
quarkus.jaeger.service-name=number-api
quarkus.jaeger.sampler-type=const
quarkus.jaeger.sampler-param=1
quarkus.jaeger.propagation=b3

quarkus.swagger-ui.always-include=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64
 - Output of `java -version`: openjdk version "11.0.7" 2020-04-14
 - GraalVM version (if different from Java): GraalVM CE 19.3.1 (build 11.0.6+9-jvmci-19.3-b07)
 - Quarkus version or git rev: 1.4.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
If we remove the dependency for `quarkus-smallrye-opentracing`, project runs fine in native. If we remove the registration of the custom Config Source in `org.eclipse.microprofile.config.spi.ConfigSource` it also works. Both together fail with the exception detailed above.

**Comment by artkonr** [comment] 2020-05-26 09:24
Hi, @radcortez, have you tried specifying reflection config for Graal? I had just the same issue and it worked for me. Basically, it takes a .json file which contains metadata on all classes that utilize reflection (and ServletConfigEtc certainly does) in your project. This .json is then fed to the GraalVM so that it could instantiate classes on build-time with reflective access preserved.

It is documented on Quarkus page [here](https://quarkus.io/guides/writing-native-applications-tips). To assemble such a file you can use built-in GVM tool called 'native-agent', which is available from your GMV distribution (see [here](https://github.com/oracle/graal/blob/master/substratevm/RESOURCES.md) and [also here](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) for more information on how to configure it. The agent will produce this file for you, but it takes some use-case coverage, because GraalVM agent will only pick metadata that were accessed in runtime.

As a result you will get a relatively big .json (~60kbs for my project), which you can definetely sift through, since Graal is oblivious on which classes are already configured for reflection on the Quarkus side. Takes some time to do it though :) Hope it helps.

BTW, @geoand I'm not sure who to address this point to (I just saw you in discussion frequently :) ), but I think it would make sense to add reference to [this](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) to the Quarkus page too.

**Comment by geoand** [comment] 2020-05-26 09:36
> BTW, @geoand I'm not sure who to address this point to (I just saw you in discussion frequently :) ), but I think it would make sense to add reference to [this](https://github.com/oracle/graal/blob/master/substratevm/CONFIGURE.md) to the Quarkus page too.

That process should rarely be needed, unless your **application** code does a ton of reflection on its own.
Perhaps we can add a reference to it somewhere in https://github.com/quarkusio/quarkus/blob/d5e643d5bfabde67ce1cfd143e5bd2f5861d198d/docs/src/main/asciidoc/writing-native-applications-tips.adoc

**Comment by artkonr** [comment] 2020-05-26 10:07
@geoand, actually, my problem was pretty close to what is described in this issue: Graal threw this
```
Error: Classes that should be initialized at run time got initialized during image building:
org.jboss.resteasy.microprofile.config.ServletConfigSourceImpl
```
, which is quite nasty, because it originated from what Quarkus delivered. It may have caused some odd error case with my project, but the failure description was very confusing. I guess in no-idea-what-to-do-next cases native agent might be quite useful.

**Comment by radcortez** [comment] 2020-05-26 10:09
Yes, the case here is that adding your own reflection metadata shouldn't be needed.

**Comment by geoand** [comment] 2020-07-08 11:23
This issue can easily be fixed in isolation but I am looking into whether there is a more general issue with the opentracing extension

**Comment by radcortez** [comment] 2020-07-08 11:27
What did you find?

**Comment by geoand** [comment] 2020-07-08 11:32
This problem is caused by `org.jboss.resteasy.microprofile.config.ServletConfigSource` being on the classpath but not being registered for reflection.

That is easy enough to solve, but I think that the opentracing extension has a more serious issue, see https://quarkusio.zulipchat.com/#narrow/stream/187038-dev

**Comment by geoand** [comment] 2020-07-08 13:46
Since it looks from the discussion that Opentracing is doing what it's supposed to, here the PR that just fixes this issue: https://github.com/quarkusio/quarkus/pull/10573

**Closed** 2020-07-13 10:33 UTC
Labels: kind/bug
