### ISSUE TITLE
Fail to start a container image build using buildpacks on MacOS ARM

### ISSUE THREAD

**Issue by cmoulliard** [quarkusio/quarkus#36030] opened 2023-09-20 09:49 UTC
## Issue

When we launch on MacOS ARM an image build using the following parameters:
```
./mvnw install -Dquarkus.container-image.build=true \
   -Dquarkus.buildpack.jvm-builder-image=paketobuildpacks/builder-jammy-tiny:0.0.176 \
   -Dquarkus.container-image.image="quay.io/ch007m/quarkus-hello:1.0" \
   -Dquarkus.buildpack.builder-env.BP_NATIVE_IMAGE="false" \
   -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \
   -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar"
```
then we got this error 
```
docker run -it --rm -p 8080:8080 quay.io/ch007m/quarkus-hello:1.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
ERROR: failed to launch: path lookup: exec: "java": executable file not found in $PATH
```

### Expected behavior

The quarkus java app should be started

### Actual behavior

Quarkus app is not started

### How to Reproduce?

```
## TODO on macos ARM machine ;-)

cd ~/temp; rm -rf quarkus-hello

mvn io.quarkus.platform:quarkus-maven-plugin:3.3.2:create \
-DprojectGroupId=me.snowdrop \
-DprojectArtifactId=quarkus-hello \
-DprojectVersion=1.0 \
-Dextensions='resteasy-reactive,kubernetes,buildpack'

cd quarkus-hello

./mvnw install -Dquarkus.container-image.build=true \
   -Dquarkus.buildpack.jvm-builder-image=paketobuildpacks/builder-jammy-tiny:0.0.176 \
   -Dquarkus.container-image.image="quay.io/ch007m/quarkus-hello:1.0" \
   -Dquarkus.buildpack.builder-env.BP_NATIVE_IMAGE="false" \
   -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \
   -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar"
   
docker run -it --rm -p 8080:8080 quay.io/ch007m/quarkus-hello:1.0
```
   

### Output of `uname -a` or `ver`

Darwin cmoullias-MacBook-Pro.local 22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.8" 2023-07-18 OpenJDK Runtime Environment Temurin-17.0.8+7 (build 17.0.8+7) OpenJDK 64-Bit Server VM Temurin-17.0.8+7 (build 17.0.8+7, mixed mode)

### Quarkus version or git rev

3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven: 3.9.4

**Comment by geoand** [comment] 2023-09-20 09:52
cc @BarDweller

**Comment by gsmet** [comment] 2024-11-21 15:26
@cmoulliard is it still an issue? I remember having seen quite a lot of work related to mac Mx architecture lately. I would be good if you could try with latest release and confirm or close the issue.

**Comment by cmoulliard** [comment] 2024-11-21 15:52
If I try to reproduce the issue on macos using podman 5.2.5, then we got another new error which should be fixed in a new Quarkus PR created recently by @BarDweller. 
```
❯ podman version
Client:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.23.2
Git Commit:   10c5aa720d59480bc7edad347c1f5d5b75d4424f
Built:        Wed Oct 23 19:49:37 2024
OS/Arch:      darwin/arm64

Server:       Podman Engine
Version:      5.2.5
API Version:  5.2.5
Go Version:   go1.22.7
Built:        Fri Oct 18 02:00:00 2024
OS/Arch:      linux/arm64

~/temp/quarkus-hello
❯ podman info | grep sock

    path: /run/user/501/podman/podman.sock

❯ set -x DOCKER_HOST "unix:///run/user/501/podman/podman.sock"
❯ ./mvnw install -Dquarkus.container-image.build=true \
               -Dquarkus.buildpack.jvm-builder-image=paketobuildpacks/builder-jammy-tiny:0.0.176 \
               -Dquarkus.container-image.image="quay.io/ch007m/quarkus-hello:1.0" \
               -Dquarkus.buildpack.builder-env.BP_NATIVE_IMAGE="false" \
               -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILT_ARTIFACT="target/quarkus-app/lib/ target/quarkus-app/*.jar target/quarkus-app/app/ target/quarkus-app/quarkus/" \
               -Dquarkus.buildpack.builder-env.BP_MAVEN_BUILD_ARGUMENTS="package -DskipTests=true -Dmaven.javadoc.skip=true -Dquarkus.package.type=fast-jar"
...
===> ANALYZING
ERROR: failed to initialize analyzer: getting previous image: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Get "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/info": dial unix /var/run/docker.sock: connect: permission denied
[INFO] Buildpack build complete, with exit code 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.585 s
[INFO] Finished at: 2024-11-21T16:48:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.8.6:build (default) on project quarkus-hello: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.container.image.buildpack.deployment.BuildpackProcessor#buildFromJar threw an exception: java.lang.IllegalStateException: Buildpack build failed
[ERROR] 	at io.quarkus.container.image.buildpack.deployment.BuildpackProcessor.runBuildpackBuild(BuildpackProcessor.java:213)
[ERROR] 	at io.quarkus.container.image.buildpack.deployment.BuildpackProcessor.buildFromJar(BuildpackProcessor.java:91)
[ERROR] 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:1583)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionExceptio
```

**Comment by gsmet** [comment] 2024-11-21 16:00
OK so let's try to revisit when 3.17.1 is released, it will include this fix.

**Comment by BarDweller** [comment] 2024-11-21 16:08
Multiple issues here all being conflated together.. 

 - macos arm buildpack build created an amd64 image. 
   Not a bug, the paketo ubi builder doesn't do multi-arch yet.. it's coming.. paketo is still rolling out multi-arch to the non ubi stacks, and once done we'll integrate across to the ubi one. Looks like your docker run is expecting an arm image, which paketo builder will never create today. 
  (although it's a tad unclear how you ran an amd64 builder image to create an amd64 application image, when your docker will only seemingly run arm images.. something isn't being said here re how this contradiction was possible in the first place). 

 - quarkus was unable to set a custom dockerhost for buildpack builds. (the cause of the 'new' error above)
   an error in the snowdrop lib dsl handler meant that the way quarkus set the custom dockerhost into the config wasn't being respected.
   this is fixed in https://github.com/quarkusio/quarkus/pull/44543 (merged)

 - podman builds are broken (even if you can now set a custom dockerhost)
    even with 44543, it appears podman builds no longer function due to unexpected changes in ownership of mountpoints during the build, this was an issue with podman previously that was addressed in may, that potentially has returned, we are still investigating this.

**Comment by gsmet** [comment] 2024-11-21 16:35
OK, my understanding here is that issues are not related to Quarkus at all.

So I will just close it, thanks for the summary!

**Closed by gsmet** 2024-11-21 16:35 UTC
Labels: kind/bug, area/kubernetes, env/m1, triage/needs-feedback
