### ISSUE TITLE
Camel Quarkus 2.12.0 incompatible with current main

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#28007] opened 2022-09-16 13:03 UTC
### Describe the bug

When running current `main` together with Camel 2.12.0, we get:
```
Error:  Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (build) on project kamelet: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
Error: [ERROR] 	[error]: Build step org.apache.camel.quarkus.core.deployment.InjectionPointsProcessor#injectedComponents threw an exception: java.lang.ClassCastException: class org.jboss.jandex.MethodParameterInfo cannot be cast to class org.jboss.jandex.Type (org.jboss.jandex.MethodParameterInfo and org.jboss.jandex.Type are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2448d7d3)
Error:  	at org.apache.camel.quarkus.core.deployment.InjectionPointsProcessor.injectedComponents(InjectionPointsProcessor.java:130)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Error:  	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
Error:  	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Error:  	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
Error:  	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
Error:  	at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
Error:  	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
Error:  	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
Error:  	at java.base/java.lang.Thread.run(Thread.java:829)
Error:  	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```
Last Quarkus snapshot, that does not throw this error, was made of revision https://github.com/quarkusio/quarkus/commit/06944a5269aebe5a5b4900456356f15d41242895.

### How to Reproduce?

1. Build Quarkus `main`.
2. Run [quarkus-test-suite](https://github.com/quarkus-qe/quarkus-test-suite)
```
git clone git@github.com:quarkus-qe/quarkus-test-suite.git && cd quarkus-test-suite
mvn clean verify -pl kamelet
```

**Comment by gsmet** [comment] 2022-09-16 13:43
Yes, this is due to the Jandex upgrade. @Ladicek is there a way to support both for a while?

**Comment by Ladicek** [comment] 2022-09-16 13:52
The `MethodInfo.parameters()` method is the one most problematic, because I couldn't add a synthetic bridge method for binary compatibility :-/

In any case, if Camel Quarkus uses recent Quarkus and therefore Jandex 2.4.3, the recommendation would be to avoid calling the deprecated methods (`MethodInfo.parameters()` -> `MethodInfo.parameterTypes()`, `ClassInfo.annotations()` -> `ClassInfo.annotationsMap()`). Assuming there are no calls to `Indexer`, this should be enough to let Camel Quarkus compile against Jandex 2.4.3 yet run against both Jandex 2.4.3 and Jandex 3.0.

**Comment by rsvoboda** [comment] 2022-09-19 06:05
CC @ppalaga / @lburgazzoli

**Comment by aloubyansky** [comment] 2022-09-27 06:41
This was caught in the quarkus-platform CI too. In general, we don't guarantee compatibility of specific platform member versions (e.g. CEQ 2.12.0) with core versions other than those they were released with as a platform. This is already fixed in 2.13.0, which will be included in quarkus-platform 2.13.0.Final. See https://github.com/quarkusio/quarkus-platform/pull/628

**Closed by aloubyansky** 2022-09-27 06:41 UTC
Labels: kind/bug, area/camel, area/core

**Comment by fedinskiy** [comment] 2022-10-14 08:57
@aloubyansky I can confirm, that this works for 2.13.z, but at the same time the reproducer fails when running with current 999-SNAPSHOT(db531a327054fe7b69592c3192e023d30dd4157f at the time of writing)

**Comment by aloubyansky** [comment] 2022-10-14 09:18
How does it fail this time?

**Comment by fedinskiy** [comment] 2022-10-14 09:29
@aloubyansky the same error: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/3248450288/jobs/5330018583

**Comment by aloubyansky** [comment] 2022-10-14 09:37
Let's clarify the versions than.
The Quarkus main branch is currently targeting 2.14 but there hasn't been a release yet.
There this Quarkus 2.13 branch from which we release 2.13 versions.
Equivalent branches exist in the quarkus-platform project.

Which version of CEQ is being tested? If it's 2.13.X then in 2.14.X CEQ will need an adjustment to work with Quarkus 2.14.

**Comment by fedinskiy** [comment] 2022-10-14 09:57
I presume, that "CEQ" is Camel Quarkus, ie maven libraries, with "org.apache.camel.quarkus" group.
I also presume, that CEQ version is defined by version of imported  `org.apache.camel.quarkus:camel-quarkus-bom`

Quarkus 2.13.0.Final and 2.13.2.Final works as expected with CEQ 2.13.0
Quarkus 999-SNAPSHOT(main branch, commit https://github.com/quarkusio/quarkus/commit/db531a327054fe7b69592c3192e023d30dd4157f) fails when working with CEQ 2.13.0

I can not Quarkus 999-SNAPSHOT with CEQ 2.14 since it is not available (which is not surprising :)

**Comment by aloubyansky** [comment] 2022-10-14 10:08
Correct, CEQ stands for Camel extensions for Quarkus.

Quarkus 2.14 isn't available neither. You could try building the CEQ main branch, similar to what is being done for Quarkus here.

**Comment by fedinskiy** [comment] 2022-10-14 11:02
So, it looks like we either need to reopen this issue, or create a new one for quarkus-platform.

Also, does all thus mean, that the same thing will happen with Quarkus 2.15 and CEQ 2.14?

**Comment by aloubyansky** [comment] 2022-10-14 12:06
> So, it looks like we either need to reopen this issue, or create a new one for quarkus-platform.

It's already open https://github.com/quarkusio/quarkus/issues/8593

> Also, does all thus mean, that the same thing will happen with Quarkus 2.15 and CEQ 2.14?

Yes, as mentioned previously, it's not guaranteed to work.

**Comment by aloubyansky** [comment] 2022-10-14 12:09
See a comment from James https://github.com/quarkusio/quarkus/issues/8593#issuecomment-1257584575
