### ISSUE TITLE
Tooling should display a message saying the extension to add has not been found

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#16353] opened 2021-04-08 09:31 UTC
## Describe the bug

Quarkus CLI "qs add not-found" is not showing any output (even when a valid extension is in the list)
```
~/D/code-with-quarkus> qs add not-found                                                                        
~/D/code-with-quarkus>     
~/D/code-with-quarkus> qs add not-found resteasy-jackson                                                     
~/D/code-with-quarkus> qs add resteasy-jackson                                                                
[SUCCESS] ✅ Extension io.quarkus:quarkus-resteasy-jackson has been installed
```

### Expected behavior
It should tell the user something like "No extension have been found matching 'not-found'"

I guess it should add the other extensions if they are found.

**Comment by ia3andy** [comment] 2021-04-08 09:32
I think the maven command has a similar problem:
```
~/D/code-with-quarkus> mvn quarkus:add-extension -Dextensions=not-found       
executing mvnw instead of mvn
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 50710  100 50710    0     0   287k      0 --:--:-- --:--:-- --:--:--  286k
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.13.1.Final:add-extension (default-cli) @ code-with-quarkus ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.206 s
[INFO] Finished at: 2021-04-08T11:31:27+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.13.1.Final:add-extension (default-cli) on project code-with-quarkus: Unable to update the pom.xml file: Unable to add extensions -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
```

**Comment by maxandersen** [comment] 2021-04-08 12:13
I believe this is a duplicate of https://github.com/quarkusio/quarkus/issues/16044

**Comment by ia3andy** [comment] 2021-04-08 12:21
@maxandersen it's close, but the case is a bit different here, so both cases need to be handled and tested.

**Comment by maxandersen** [comment] 2021-04-08 15:34
what is the different case ? the issue I see is that when there is an extension not found the cli fails siliently.

**Closed** 2021-05-11 05:32 UTC
Labels: area/cli, kind/bug, triage/duplicate
