### ISSUE TITLE
EntityManager in not injected when using devmode with gradle

### ISSUE THREAD

**Issue by 4ntoine** [quarkusio/quarkus#5488] opened 2019-11-14 19:10 UTC
**Describe the bug**
I'm using JPA + Hibernate without Panache. application.properties seems to be configured correctly. Beans injecting annotations are set. However `EntityManager` instance is not injected.

**Expected behavior**
`EntityManager` instance is instantiated by Quarkus (Arc) and injected.

**Actual behavior**
`EntityManager` instance is `null`.

**To Reproduce**
1. git clone git@github.com:4ntoine/NotesServerApp.git
2. git checkout issue-5-quarkus
3. ./gradlew :app-quarkus:quarkusDev
4. navigate to "localhost:8080/hello" and make sure you can see stacktrace NPE''

**Configuration**
```properties
quarkus.datasource.url = jdbc:h2:mem:notes
quarkus.datasource.driver = org.h2.Driver

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
<img width="1414" alt="Снимок экрана 2019-11-15 в 0 05 26" src="https://user-images.githubusercontent.com/846671/68887904-afac7000-073b-11ea-8b7b-34bdad16f71b.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
> Darwin MBP-Anton.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
```
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: `1.0.0CR1`

**Additional context**
CDI configuration:
```
package name.antonsmirnov.notes

import name.antonsmirnov.notes.gateway.JpaGateway
import name.antonsmirnov.notes.gateway.mapper.MapperImpl
import name.antonsmirnov.notes.usecase.*
import javax.enterprise.inject.Produces
import javax.inject.Inject
import javax.persistence.EntityManager

class QuarkusEntityManagerFactory {
    @Inject
    lateinit var entityManager: EntityManager // will be injected by Quarkus (but is not!)
}

class Configuration {
    val mapper = MapperImpl()
    val gateway = JpaGateway(QuarkusEntityManagerFactory().entityManager, mapper)
    val addNote: AddNote = AddNoteImpl(gateway)
    val listNotes: ListNotes = ListNotesImpl(gateway)

    @Produces
    fun getAddNoteUseCase(): AddNote = addNote

    @Produces
    fun getListNotesUseCase(): ListNotes = listNotes
}
```

dependencies configuration (Gradle + Kotlin DSL):
```
...
dependencies {
    implementation(project(":app-impl"))
    implementation(project(":infra-gateway-jpa"))
    implementation(project(":infra-rest-jax-rs")) {
        // provided by Quarkus or it's transitive dependencies
        exclude("javax.ws.rs:javax.ws.rs-api:2.0")
        exclude("javax.enterprise:cdi-api:2.0.SP1")
    }

    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-resteasy-jsonb")
    implementation("io.quarkus:quarkus-jdbc-h2")
    implementation("io.quarkus:quarkus-hibernate-orm")
    implementation(enforcedPlatform("io.quarkus:quarkus-bom:1.0.0.CR1"))
    implementation("io.quarkus:quarkus-resteasy")
}
...
```

Does it look like correct CDI configuration? Should `entityManager` be injected by Quarkus before it's `entityManager` accessed?

**Comment by geoand** [comment] 2019-11-15 07:12
Hi, 

The CDI configuration is indeed not correct - you need to add `@ApplicationScoped` to `QuarkusEntityManagerFactory` and `Configuration`.

However even after doing that, there seems to be a bug which is most likely another manifestation of https://github.com/quarkusio/quarkus/pull/4905#issuecomment-546851800

**Comment by 4ntoine** [comment] 2019-11-15 08:04
@geoand Thanks for the reply, any [known] workaround for Gradle bug that you are aware of? BTW is it Gradle or gradle quarkus plugin?

**Comment by geoand** [comment] 2019-11-15 08:38
It's a gradle quarkus plugin issue, not gradle itself.

We are working on having great gradle support, but currently it's incubating :). Stay tuned however, we should have more updates soon.

@maxandersen FYI

**Comment by maxandersen** [comment] 2019-11-15 08:57
thanks for the headsup @geoand ! 

I've updated the title to reflect the specific issue as I see it and yeah; this is the kind of issue we need to go fix proper in the context of maturing gradle work at #5101

**Comment by 4ntoine** [comment] 2019-11-15 17:42
I've jut tried it with maven and also failed to make it working: https://github.com/quarkusio/quarkus/issues/5521

**Comment by KaenDagger** [comment] 2020-02-12 03:49
I am taking up this issue. If its fine

**Comment by SR-Lut3t1um** [comment] 2020-02-15 15:50
How can I work arround this bug?

**Comment by KaenDagger** [comment] 2020-02-18 05:52
@SR-Lut3t1um currently it is not injected. We are working on improving gradle support on quarkus

**Comment by KaenDagger** [comment] 2020-02-24 05:55
@4ntoine ,have you deleted your quarkus branch ?

**Comment by SR-Lut3t1um** [comment] 2020-03-10 09:29
@KaenDagger How far are you? Is there any way I can help? What are you working on right now?

Kind regards

**Comment by aloubyansky** [comment] 2020-03-13 13:07
@4ntoine have you deleted the branch with the reproducer?

**Comment by KaenDagger** [comment] 2020-03-13 17:58
@SR-Lut3t1um was away for exams. Was not able to go ahead. just resumed work

**Comment by KaenDagger** [comment] 2020-03-13 17:58
@aloubyansky  yes branch is deleted

**Comment by aloubyansky** [comment] 2020-03-13 18:05
@KaenDagger do you by chance have a reproducer?

**Comment by KaenDagger** [comment] 2020-03-13 18:10
On the way, first test with hibernate-orm + kotlin +gradle. I suppose injection should fail there only as per issue description. 
Normal injection works in Kotlin+gradle project

**Comment by aloubyansky** [comment] 2020-03-13 20:43
Once you have a reproducer, please add it to this issue. Thanks a lot.

**Comment by SR-Lut3t1um** [comment] 2020-03-14 06:38
@aloubyansky I have a reproducer. It's a repo of a project I'm working on right now, so it does include more that what's nessisary to reproduce the bug. If you want to I can share it here.

**Comment by aloubyansky** [comment] 2020-03-14 06:53
@SR-Lut3t1um sure, that might not be the easiest to work with but still a reproducer. Thanks!

**Comment by aloubyansky** [comment] 2020-03-14 06:54
Have you tried 1.3.0.Final, btw?

**Comment by SR-Lut3t1um** [comment] 2020-03-14 06:58
> Have you tried 1.3.0.Final, btw?

Not yet, last version I tried was 1.3.0.CR2

**Comment by SR-Lut3t1um** [comment] 2020-03-14 07:03
> @SR-Lut3t1um sure, that might not be the easiest to work with but still a reproducer. Thanks!

Here it is, I hope it's good enough to work with.: 
https://gitlab.informatik.uni-bremen.de/tobias5/aut0m4t0n

**Comment by SR-Lut3t1um** [comment] 2020-03-14 07:05
It's configured to use H2. To reproduce the issue got to: http://127.0.0.1:8080/automaton/test

**Comment by SR-Lut3t1um** [comment] 2020-06-01 15:54
Is there any new information on this topic?

**Comment by aloubyansky** [comment] 2020-06-02 16:11
@SR-Lut3t1um I think you are getting NPE because you are creating AutomatonManager using the constructor instead of injecting it https://gitlab.informatik.uni-bremen.de/tobias5/aut0m4t0n/-/blob/master/src/main/java/org/un1qu3/endpoints/AutomatonSocket.java#L46

**Comment by aloubyansky** [comment] 2020-06-02 16:18
About the issue described in the original report, I think the CDI spec expects you to use a getter instead of accessing the field directly here 
````
val gateway = JpaGateway(QuarkusEntityManagerFactory().entityManager, mapper)
````
Correct, @mkouba ? (see the original description of the issue)

**Comment by aloubyansky** [comment] 2020-06-03 06:31
Actually, I also missed the fact that `QuarkusEntityManagerFactory` is created using constructor too instead of relying on DI to provide a properly initialized instance.
````
val gateway = JpaGateway(QuarkusEntityManagerFactory().entityManager, mapper)
````
I am closing this issue since what's described is not expected to work and is not a bug. Thanks everyone.

**Closed by aloubyansky** 2020-06-03 06:31 UTC
Labels: area/gradle, kind/bug
