### ISSUE TITLE
Failed to start quarkus in 2.16.0.Final: `Ambiguous dependencies for type java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> and qualifiers [@Default]`

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#30616] opened 2023-01-25 17:58 UTC
### Describe the bug

It  looks like a conflict between:
- `io.smallrye.config.inject.ConfigProducer`
- `io.quarkus.micrometer.runtime.export.OpentelemetryExemplarSamplerProvider`

Dependencies are:
```kt
implementation(platform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))
implementation("io.quarkus:quarkus-agroal")
implementation("io.quarkus:quarkus-arc")
implementation("io.quarkus:quarkus-cache")
implementation("io.quarkus:quarkus-kotlin")
implementation("io.quarkus:quarkus-micrometer-registry-prometheus")
implementation("io.quarkus:quarkus-resteasy-reactive")
implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
implementation("com.fasterxml.jackson.module:jackson-module-kotlin:${GlobalVersions.jackson}")
implementation("io.quarkus:quarkus-smallrye-fault-tolerance")
implementation("io.quarkus:quarkus-smallrye-openapi")
implementation("io.quarkus:quarkus-vertx")
implementation("io.quarkus:quarkus-reactive-routes")

implementation("io.quarkus:quarkus-opentelemetry")
implementation("io.opentelemetry:opentelemetry-extension-kotlin")
implementation("io.opentelemetry.instrumentation:opentelemetry-jdbc")
```

Error is:
```java
2023-01-25 12:56:09,282 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> and qualifiers [@Default]
        - java member: io.quarkus.micrometer.runtime.export.PrometheusMeterRegistryProducer#registry():exemplarSampler
        - declared on PRODUCER METHOD bean [types=[io.micrometer.core.instrument.MeterRegistry, java.lang.Object, io.micrometer.prometheus.PrometheusMeterRegistry], qualifiers
=[@Default, @Any], target=io.micrometer.prometheus.PrometheusMeterRegistry registry(io.micrometer.prometheus.PrometheusConfig config, io.prometheus.client.CollectorRegistry co
llectorRegistry, java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> exemplarSampler, io.micrometer.core.instrument.Clock clock), declaringBean=io.quarkus.micrometer.runtime.export.PrometheusMeterRegistryProducer]
        - available beans:
                - PRODUCER METHOD bean [types=[java.util.Optional<T>, java.lang.Object], qualifiers=[@Default, @Any], target=java.util.Optional<T> produceOptionalConfigProperty(javax.enterprise.inject.spi.InjectionPoint ip), declaringBean=io.smallrye.config.inject.ConfigProducer]
                - PRODUCER METHOD bean [types=[java.lang.Object, java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler>], qualifiers=[@Default, @Any], target=java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> exemplarSampler(), declaringBean=io.quarkus.micrometer.runtime.export.OpentelemetryExemplarSamplerProvider]      
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:288)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:148)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:281)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.AmbiguousResolutionException: Ambiguous dependencies for type java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> and qualifiers [@Default]
        - java member: io.quarkus.micrometer.runtime.export.PrometheusMeterRegistryProducer#registry():exemplarSampler
        - declared on PRODUCER METHOD bean [types=[io.micrometer.core.instrument.MeterRegistry, java.lang.Object, io.micrometer.prometheus.PrometheusMeterRegistry], qualifiers
=[@Default, @Any], target=io.micrometer.prometheus.PrometheusMeterRegistry registry(io.micrometer.prometheus.PrometheusConfig config, io.prometheus.client.CollectorRegistry co
llectorRegistry, java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> exemplarSampler, io.micrometer.core.instrument.Clock clock), declaringBean=io.quarkus.micrometer.runtime.export.PrometheusMeterRegistryProducer]
        - available beans:
                - PRODUCER METHOD bean [types=[java.util.Optional<T>, java.lang.Object], qualifiers=[@Default, @Any], target=java.util.Optional<T> produceOptionalConfigProperty(javax.enterprise.inject.spi.InjectionPoint ip), declaringBean=io.smallrye.config.inject.ConfigProducer]
                - PRODUCER METHOD bean [types=[java.lang.Object, java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler>], qualifiers=[@Default, @Any], target=java.util.Optional<io.prometheus.client.exemplars.ExemplarSampler> exemplarSampler(), declaringBean=io.quarkus.micrometer.runtime.export.OpentelemetryExemplarSamplerProvider]      
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:449)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:539)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:276)
        ... 13 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:335)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:252)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:86)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:447)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:59)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:149)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:104)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
```

**Comment by GavinRay97** [comment] 2023-01-25 18:28
Workaround for anyone else that runs into this:

```kt
class CustomOpenTelemetryExemplarSamplerProvider {

    @Produces
    @Alternative
    @io.quarkus.arc.Priority(100000)
    fun getSampler(): Optional<io.prometheus.client.exemplars.ExemplarSampler> {
        return io.quarkus.micrometer.runtime.export.OpentelemetryExemplarSamplerProvider().exemplarSampler()
    }

}
```

**Comment by geoand** [comment] 2023-01-25 18:42
cc @mkouba @manovotn

**Comment by mkouba** [comment] 2023-01-25 19:30
Hm, the `io.smallrye.config.inject.ConfigProducer.produceOptionalConfigProperty()` producer method should not have `qualifiers=[@Default, @Any]` but `qualifiers=[@ConfigProperty, @Any]`.

@GavinRay97 what does you app setup look like? Would you care to prepare a simple reproducer app?

**Comment by GavinRay97** [comment] 2023-01-25 20:30
@mkouba By app setup, you mean the `build.gradle.kts` and whatnot?

If so yeah I can definitely put one of those together`

**Comment by GavinRay97** [comment] 2023-01-25 20:50
Okay, here is the minimized reproduction, got it to work:

[quarkus-repro.zip](https://github.com/quarkusio/quarkus/files/10503559/quarkus-repro.zip)

Let me know if there is any issue with that, it should run with just `./gradlew quarkusDev` and then fail at startup with the same message 👍

**Comment by mkouba** [comment] 2023-01-26 07:49
I've tried to add the `io.quarkus:quarkus-opentelemetry` and `io.quarkus:quarkus-micrometer-registry-prometheus` dependencies in the [config quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/config-quickstart) and no `AmbiguousResolutionException` occurs, i.e. the qualifiers of `ConfigProducer.produceOptionalConfigProperty()` are `[@ConfigProperty, @Any]`.

I think that it's a gradle/build-related problem.

**Comment by geoand** [comment] 2023-01-26 10:09
cc @aloubyansky @glefloch

**Comment by vladimirfx** [comment] 2023-02-02 19:20
I hit by this without any telemetry dependency.

**Comment by mkouba** [comment] 2023-02-03 06:11
> I hit by this without any telemetry dependency.

Then it has to be a different error message...

**Comment by aloubyansky** [comment] 2023-02-03 11:32
@mkouba is this supposed to resolve properly?
`io.smallrye.config.injectConfigProducer`
```
    @Dependent
    @Produces
    @ConfigProperty
    protected <T> Optional<T> produceOptionalConfigProperty(InjectionPoint ip) {
        return ConfigProducerUtil.getValue(ip, getConfig());
    }
```
and
`io.quarkus.micrometer.runtime.export.OpentelemetryExemplarSamplerProvider`
```
    @Produces
    public Optional<ExemplarSampler> exemplarSampler() {
...
```

**Comment by mkouba** [comment] 2023-02-03 12:19
> is this supposed to resolve properly?

It depends on the required qualifier. I.e. `@Inject Optional<ExemplarSampler>` (which corresponds to `@Inject @Default Optional<ExemplarSampler>` ) is ok and is satisfied by the `exemplarSampler()` but `@Inject @Any Optional<ExemplarSampler>` would result in an `AmbiguousResolutionException` because both `exemplarSampler()` and `produceOptionalConfigProperty()` are eligible.

As I mentioned in https://github.com/quarkusio/quarkus/issues/30616#issuecomment-1404653857 from the error message it looks like if the qualifiers of `produceOptionalConfigProperty()` are `[@Default, @Any]` instead of `[@ConfigProperty, @Any]`. Maybe for some reason the `@ConfigProperty` is not registered as a qualifier...

**Comment by aloubyansky** [comment] 2023-02-03 15:26
Haven't yet dug to the cause but I see in `Beans.createProducerMethod` for
```
java.util.Optional<T> produceOptionalConfigProperty(javax.enterprise.inject.spi.InjectionPoint ip) CLASS bean [types=[io.smallrye.config.inject.ConfigProducer, java.lang.Object], qualifiers=[@Default, @Any], target=io.smallrye.config.inject.ConfigProducer]
```
we get 0 qualifiers although we do iterate over the three annotations including `org.eclipse.microprofile.config.inject.ConfigProperty`.

**Comment by mkouba** [comment] 2023-02-06 08:56
Then we failed to identify the `@ConfigProperty` as a qualifier. Normally, it should be identified because we [register the `ConfigProducer` as an additional bean](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java#L101) and all the [additioanl bean classes are indexed](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/BeanArchiveProcessor.java#L63-L66) (including used annotations) and become part of the immutable bean archive index that is queried to [find all qualifiers](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L683-L693).

**Comment by aloubyansky** [comment] 2023-02-06 13:38
In `BeanDeployment.findQualifiers` I can find the config property bean with `beanArchiveImmutableIndex.getClassByName(DotNames.create("org.eclipse.microprofile.config.inject.ConfigProperty"))` and list its annotations that include
```
    @Target([METHOD,FIELD,PARAMETER,TYPE])
    @Requirements([@Requirement(effective = "active",name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension"),@Requirement(name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension",resolution = OPTIONAL)])
    @Qualifier
    @Nonbinding
    @Nonbinding
    @Retention(RUNTIME)
```
However, listing `beanArchiveImmutableIndex.getAnnotations(DotNames.QUALIFIER)` does not include the `ConfigProperty`:
```
io.smallrye.context.api.NamedInstance
io.quarkus.cache.CacheName
io.smallrye.common.annotation.Identifier
javax.enterprise.context.BeforeDestroyed
io.quarkus.netty.BossEventLoopGroup
io.quarkus.netty.MainEventLoopGroup
javax.inject.Named
io.quarkus.runtime.annotations.CommandLineArguments
io.quarkus.arc.log.LoggerName
io.quarkus.agroal.runtime.JdbcDriver
io.quarkus.micrometer.runtime.MeterFilterConstraint
io.quarkus.arc.All
javax.enterprise.inject.Any
javax.enterprise.inject.Intercepted
javax.enterprise.inject.Default
javax.enterprise.inject.Any
javax.inject.Named
javax.enterprise.context.Initialized
javax.enterprise.context.BeforeDestroyed
javax.enterprise.context.Destroyed
javax.enterprise.inject.Intercepted
io.quarkus.arc.All
io.quarkus.arc.impl.Identified
```

**Comment by mkouba** [comment] 2023-02-06 13:51
> However, listing `beanArchiveImmutableIndex.getAnnotations(DotNames.QUALIFIER)` does not include the `ConfigProperty`:

That should not be a problem. We extract the qualifiers of a producer method via `BeanDeployment.extractQualifiers()`  and this method leverages the result of `BeanDeployment.findQualifiers()`.

**Comment by aloubyansky** [comment] 2023-02-06 13:54
Isn't it strange though that the `ConfigProperty` isn't listed when querying for the `Qualifier`?

**Comment by aloubyansky** [comment] 2023-02-06 14:00
That's exactly the problem, afaics. If it's not collected in `BeanDeployment.findQualifiers` it's going to appear later in `extractQualifiers`

**Comment by mkouba** [comment] 2023-02-06 14:01
> Isn't it strange though that the `ConfigProperty` isn't listed when querying for the `Qualifier`?

@Ladicek when we call `Indexer#indexWithSummary()` and the indexed class is an annotation, does `ClassSummary.annotations()` return meta-annotations as well?

**Comment by mkouba** [comment] 2023-02-06 14:23
@aloubyansky I've just tried to build the app with the main branch and the error is gone (?).

**Comment by aloubyansky** [comment] 2023-02-06 14:27
Yes, I know. I'd like to understand the cause though. I don't see how it is specific to Gradle so far and want to make sure we fixed the cause properly.

**Comment by aloubyansky** [comment] 2023-02-06 14:41
Oh, I see. For some reason in both 2.16 and main I get the following list of annotations for `org.eclipse.microprofile.config.inject.ConfigProperty`:
```
    @Target([METHOD,FIELD,PARAMETER,TYPE]) java.lang.annotation.Target
    @Requirements([@Requirement(effective = "active",name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension"),@Requirement(name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension",resolution = OPTIONAL)]) org.osgi.annotation.bundle.Requirements
    @Qualifier jakarta.inject.Qualifier
    @Nonbinding jakarta.enterprise.util.Nonbinding
    @Nonbinding jakarta.enterprise.util.Nonbinding
    @Retention(RUNTIME) java.lang.annotation.Retention
```
Notice, it's the `jakarta` version. While in 2.16 we are looking for `javax.inject.Qualifier`.

**Comment by mkouba** [comment] 2023-02-06 14:43
> Oh, I see. For some reason in both 2.16 and main I get the following list of annotations for `org.eclipse.microprofile.config.inject.ConfigProperty`:
> 
> ```
>     @Target([METHOD,FIELD,PARAMETER,TYPE]) java.lang.annotation.Target
>     @Requirements([@Requirement(effective = "active",name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension"),@Requirement(name = "org.eclipse.microprofile.config",namespace = "osgi.cdi.extension",resolution = OPTIONAL)]) org.osgi.annotation.bundle.Requirements
>     @Qualifier jakarta.inject.Qualifier
>     @Nonbinding jakarta.enterprise.util.Nonbinding
>     @Nonbinding jakarta.enterprise.util.Nonbinding
>     @Retention(RUNTIME) java.lang.annotation.Retention
> ```
> 
> Notice, it's the `jakarta` version. While in 2.16 we are looking for `javax.inject.Qualifier`.

Hm, I don't see how this could be `jakarta.inject.Qualifier` in the 2.16 branch... :thinking:

**Comment by aloubyansky** [comment] 2023-02-06 14:43
I'll tell you in a bit.

**Comment by mkouba** [comment] 2023-02-06 14:44
Isn't there a specific MP Config API version used?

**Comment by Ladicek** [comment] 2023-02-06 14:44
Maybe the Gradle dependency resolves to a "too new" MP Config API?

> when we call `Indexer#indexWithSummary()` and the indexed class is an annotation, does `ClassSummary.annotations()` return meta-annotations as well?

I believe so, yes.

**Comment by aloubyansky** [comment] 2023-02-06 14:45
yes, I suspect there is some dependency override.

**Comment by mkouba** [comment] 2023-02-06 14:46
> Maybe the Gradle dependency resolves to a "too new" MP Config API?
> 
> > when we call `Indexer#indexWithSummary()` and the indexed class is an annotation, does `ClassSummary.annotations()` return meta-annotations as well?
> 
> I believe so, yes.

Yes, that's my guess too. Sorry for an irrelevant question ;-).

**Comment by aloubyansky** [comment] 2023-02-06 14:46
It comes from MP3 version
```
file:/home/aloubyansky/.gradle/caches/modules-2/files-2.1/org.eclipse.microprofile.config/microprofile-config-api/3.0/6d84c4fbdd01f1f6a1703caa4d40614605fcda60/microprofile-config-api-3.0.jar
```

**Comment by mkouba** [comment] 2023-02-06 14:54
Is this the depencency to blame?
```
+--- io.quarkus:quarkus-smallrye-openapi -> 2.16.0.Final
|    +--- io.smallrye:smallrye-open-api-core:3.1.1
|    |    +--- org.eclipse.microprofile.openapi:microprofile-openapi-api:3.1
|    |    +--- org.eclipse.microprofile.config:microprofile-config-api:3.0
```

**Comment by aloubyansky** [comment] 2023-02-06 14:58
Yes. @GavinRay97 looks like it's a dependency mix up in your project
```
org.eclipse.microprofile.config:microprofile-config-api:2.0.1 -> 3.0 (c)
```

I can imagine these kinds of issues coming up more and more.

**Comment by mkouba** [comment] 2023-02-06 15:02
> Yes. @GavinRay97 looks like it's a dependency mix up in your project
> 
> ```
> org.eclipse.microprofile.config:microprofile-config-api:2.0.1 -> 3.0 (c)
> ```
> 
> I can imagine these kinds of issues coming up more and more.

But it seems like the problem is in `io.quarkus:quarkus-smallrye-openapi` which brings in a `smallrye-open-api` version that depends on MP 3.0.

And it seems that there is a difference between Gradle and Maven in the way they handle transitive dependencies.

CC @radcortez

**Comment by aloubyansky** [comment] 2023-02-06 15:12
Ah, ok. @GavinRay97 you should use `enforcedPlatform` instead of `platform`. `platform` isn't supported for Quarkus BOMs.

**Comment by aloubyansky** [comment] 2023-02-06 15:13
We enforce the proper version of the config API but it's not enforced because the quarkus-bom is applied with `platform`

**Comment by GavinRay97** [comment] 2023-02-06 15:27
Ohhh, mystery solved, thank you @aloubyansky!

What is the difference between these? I have never heard of `enforcedPlatform` before 🤔

**Comment by aloubyansky** [comment] 2023-02-06 15:30
Our code generators have always used `enforcedPlatform`. It looks like `enforcedPlatform` is generally discouraged in Gradle community, however this is a true equivalent of a BOM import in Maven.

**Comment by mkouba** [comment] 2023-02-06 15:51
Ok, thanks all. 

The `enforcedPlatform` seems to be documented here: https://quarkus.io/guides/gradle-tooling#publishing-your-application

I think that we can close this issue now.

**Closed by mkouba** 2023-02-06 15:51 UTC
Labels: kind/bug, area/gradle, area/arc

**Comment by vladimirfx** [comment] 2023-02-06 17:15
So as I said before there is no tracing deps involved. Just another dependency on enforced platform. In our projects we can't just enforced platform because we need update some deps time to time (like Kotlin versions, or JDBC drivers).

Gradle is flexible enough to correctly handle such cases without platform enforcement. https://docs.gradle.org/current/userguide/single_versions.html#simple_version_declaration_semantics

Is this enforcement requirement changes with Quarkus 3.x ?

**Comment by aloubyansky** [comment] 2023-02-06 17:53
Enforcing preferred version constraints using the Gradle capabilities you referenced should still be possible even with `enforcedPlatform`.
`platform` and `enforcedPlatform` are two extremes. One would typically be picked over the other as being a lesser evil. The rest would have to be adjusted manually.
Quarkus BOMs include version constraints that should be applied to transitive dependencies of extensions to make sure they work correctly. This issue is showing why. This is not going to change with Quarkus 3.x.

Our extensions could probably benefit from some better dependency analysis and management. However, for a project like Quarkus it looks pretty complex.

OTOH, enforcing different versions of such dependencies as JDBC drivers could be pretty sensitive, specially in case of native builds.

**Comment by vladimirfx** [comment] 2023-02-09 08:05
Enforcing all dep version on Quarkus BOM prevent users from point-update necessary deps. We should use `platform` on Quarkus BOM and reproduce Quarkus-required (enforced) versions by hand for each minor Quarkus release. Exactly that can be expressed in Quarkus BOM without forcing users to use `enforcedPlatform`. This technique used in other frameworks like Spring, Google Hilt/Dagger.

To run our projects on Quarkus 2.16.x we "just" enforce `microprofile-config-api` to 2.0.1.

Thanx!

**Comment by aloubyansky** [comment] 2023-02-09 08:39
> Enforcing all dep version on Quarkus BOM prevent users from point-update necessary deps.

Could you please clarify this point? Perhaps a simple example?

> We should use platform on Quarkus BOM and reproduce Quarkus-required (enforced) versions by hand for each minor Quarkus release.

You can surely do that if that works for you better. The Quarkus BOM includes version constraints that we tested enforcing them on the whole tree, which is why we recommend enforcing it all the way by default.

Given that you added a comment earlier that you are affected by this issue, could you clarify what would you like us to fix in this regard?
