### ISSUE TITLE
Add support @JsonbTypeAdapter on Enum type

### ISSUE THREAD

**Issue by leotu** [quarkusio/quarkus#2211] opened 2019-04-25 07:55 UTC
javax.json.bind.annotation.JsonbTypeAdapter doesn't work

Quarkus version: 0.13.3

Test code:
```java
@ApplicationScoped
public class Demo1 {
	static final protected org.slf4j.Logger log = LoggerFactory.getLogger(Demo1.class);

	final private Jsonb jsonb = JsonbBuilder.create(new JsonbConfig().withFormatting(true));

	@Scheduled(every = "2s")
	public void fireEvent() {
		Bean data = new Bean();
		data.setId(123);
		data.setName("MyDemo1");
		data.setRelease(new Date());
		data.setStatus(BeanEnum.ENABLE);
		log.debug("json: {}", jsonb.toJson(data));
	}

	static public class Bean {
		private int id;
		private String name;

		@JsonbDateFormat(value = "yyyy-MM-dd'T'HH:mm:ss:SSSxxx", locale = "Locale.ENGLISH")
		private Date release;

		private BeanEnum status;

		public int getId() {
			return id;
		}

		public void setId(int id) {
			this.id = id;
		}

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public Date getRelease() {
			return release;
		}

		public void setRelease(Date release) {
			this.release = release;
		}

		public BeanEnum getStatus() {
			return status;
		}

		public void setStatus(BeanEnum status) {
			this.status = status;
		}

		@Override
		public String toString() {
			return super.toString() + "[id=" + id + ", name=" + name + ", release=" + release + ", status=" + status
					+ "]";
		}

	}

	@JsonbTypeAdapter(BeanEnumAdapter.class)
	static public enum BeanEnum {
		ENABLE("Y"), DISABLE("N");

		public final String value;

		private BeanEnum(String value) {
			this.value = value;
		}

		@Override
		public String toString() {
			return Objects.toString(value);
		}

		public boolean equalsValue(String value) {
			return Objects.equals(this.value, value);
		}

		static public BeanEnum fromValue(String value) {
			return Arrays.stream(BeanEnum.class.getEnumConstants()) //
					.filter(e -> e.equalsValue(value)) //
					.findFirst().orElse(null);
		}

	}

	@Provider
	static public class BeanEnumAdapter implements JsonbAdapter<BeanEnum, String> {

		@Override
		public String adaptToJson(BeanEnum e) throws Exception {
			return e.value;
		}

		@Override
		public BeanEnum adaptFromJson(String value) throws Exception {
			return BeanEnum.fromValue(value);
		}

	}

}
```

Exception:

```java
15:47:22.153 ERROR [DefaultQuartzScheduler_Worker-1] [org.quartz.core.JobRunShell:211,run()] Job io.quarkus.scheduler.Scheduler.1_home.leo.demo.Demo1_ScheduledInvoker_fireEvent_0dc8f9e6bd5d12114268f3c5659297394c3dfec1 threw an unhandled Exception: : java.lang.UnsupportedOperationException
	at io.quarkus.arc.BeanManagerImpl.createAnnotatedType(BeanManagerImpl.java:234)
	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.lambda$getOrCreateComponent$0(BeanManagerInstanceCreator.java:68)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.yasson.internal.components.BeanManagerInstanceCreator.getOrCreateComponent(BeanManagerInstanceCreator.java:67)
	at org.eclipse.yasson.internal.ComponentMatcher.introspectAdapterBinding(ComponentMatcher.java:249)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBindingFromAnnotation(AnnotationIntrospector.java:227)
	at org.eclipse.yasson.internal.AnnotationIntrospector.getAdapterBinding(AnnotationIntrospector.java:206)
	at org.eclipse.yasson.internal.model.PropertyModel.getUserAdapterBinding(PropertyModel.java:151)
	at org.eclipse.yasson.internal.model.PropertyModel.introspectCustomization(PropertyModel.java:205)
	at org.eclipse.yasson.internal.model.PropertyModel.<init>(PropertyModel.java:98)
	at org.eclipse.yasson.internal.ClassParser.lambda$parseProperties$0(ClassParser.java:74)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1625)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.eclipse.yasson.internal.ClassParser.parseProperties(ClassParser.java:75)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:56)
	at org.eclipse.yasson.internal.MappingContext$ParseClassModelFunction.apply(MappingContext.java:37)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at org.eclipse.yasson.internal.MappingContext.getOrCreateClassModel(MappingContext.java:107)
	at org.eclipse.yasson.internal.Marshaller.marshall(Marshaller.java:73)
	at org.eclipse.yasson.internal.JsonBinding.toJson(JsonBinding.java:98)
	at home.leo.demo.Demo1.fireEvent(Demo1.java:39)
	at home.leo.demo.Demo1_ClientProxy.fireEvent(Unknown Source)
	at home.leo.demo.Demo1_ScheduledInvoker_fireEvent_0dc8f9e6bd5d12114268f3c5659297394c3dfec1.invoke(Unknown Source)
	at io.quarkus.scheduler.runtime.QuartzScheduler$InvokerJob.execute(QuartzScheduler.java:264)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
```

**Comment by gsmet** [comment] 2019-04-29 21:35
This is a duplicate of https://github.com/quarkusio/quarkus/issues/1656 .

We are trying to make progress upstream to hopefully support that in the future.

Please follow the other issue if you want some update when it's fixed.

**Closed by gsmet** 2019-04-29 21:35 UTC
Labels: bug, component:resteasy, upstream
