### ISSUE TITLE
JPA orm.xml file handling to support multiple database vendors

### ISSUE THREAD

**Issue by mgwillem** [quarkusio/quarkus#14762] opened 2021-02-02 12:45 UTC
**Description**
I need to implement a solution that supports multiple database vendors like Oracle, MS SQLServer, DB2, etc.

Moreover I need to re-use existing "legacy" JARs containing JPA entities with annotations and orm.xml files.
Such "legacy" JARs are used by existing Java EE 8 applications.

Existing database schemas use sequences for Oracle PK and identities for SQLServer PK.
To handle such differences, we use annotations to define Oracle sequences .. and we use the orm.xml file to define MS SQLServer identities.

Moreover the orm.xml file is used for setting persistence-unit/schema as well. It means it is not only a PK override issue.

The orm.xml file is a standard JPA feature that is very useful (imho) and I believe this file support is mandatory for such use-cases.

Please keep in mind that migration of legacy apps/libraries is an important point here.

Thank you!

**Comment by gastaldi** [comment] 2021-02-02 12:54
@mgwillem can you provide a sample `orm.xml` that you use in your application?

**Comment by mgwillem** [comment] 2021-02-02 12:57
Here is an example of such orm.xml file for the SQLServer support

`<?xml version="1.0" encoding="UTF-8"?>

<entity-mappings
        xmlns="http://java.sun.com/xml/ns/persistence/orm"
        version="2.0">

    <description>Override Annotations...</description>

    <persistence-unit-metadata>
        <persistence-unit-defaults>
            <schema>dbo</schema>
        </persistence-unit-defaults>
    </persistence-unit-metadata>

    <entity class="org.foo.Foo" access="FIELD" metadata-complete="false">
        <attributes>
            <id name="id">
                <generated-value strategy="IDENTITY" />
            </id>
        </attributes>
    </entity>

    <entity class="org.foo.Bar" access="FIELD" metadata-complete="false">
        <attributes>
            <id name="id">
                <generated-value strategy="IDENTITY" />
            </id>
        </attributes>
    </entity>
</entity-mappings>
`

**Comment by Sanne** [comment] 2021-02-02 14:02
I agree we should do this, but let me clarify some restrictions:

- The `orm.xml` resource will be ignored at runtime: I would prefer we pre-parse it during the Quarkus augmentation
- We can allow adding/updating it during "dev mode"
- It should still be possible to build a Quarkus application which does not need to initialize the XML parser libraries at runtime (even if the app is using`orm.xml` backed mappings)

I hope that's agreable?

**Comment by mgwillem** [comment] 2021-02-02 16:12
Yes the `orm.xml` resource could be ignored at runtime. In my use-case I will generate one JAR per database vendor.
It seems we have a deal :)

**Comment by mgwillem** [comment] 2021-02-05 12:27
Hi ! I'm curious to know if this `orm.xml` file support could be added soon in Quakus. What do you think ?

**Comment by Sanne** [comment] 2021-02-05 13:05
I must admit I'm not sure about the timeline.

There's a couple more urgent tasks that my team needs to finish first, and I personally need to take some time off - so it depends if I can delegate this one, but it's not simple to do as far as I remember from the initial POC :) But that's been a couple years ago so I suppose it's possible that this is much simpler noways, as our tools improved and we have a better understanding of GraalVM we have today.

I'll try a better estimate next week; ideally if I can get a getter picture and delegate this to another team members it is more likely to get done quickly.

**Comment by mgwillem** [comment] 2021-02-05 13:37
Thanks @Sanne for your update! I hope it will be easier to implement than expected :)

**Comment by mgwillem** [comment] 2021-02-19 13:55
Hi! Any news regarding this feature support? Thanks

**Comment by sithmein** [comment] 2021-03-01 17:05
So this basically means there is no way to use entities from external libraries with JPA in Quarkus? This is bad.

**Comment by Sanne** [comment] 2021-03-02 17:54
@mgwillem sorry I'm the slow cog here. @yrodiere volunteered to take it over.

@sithmein if by "external libraries" you mean 3rd party classes which can't be annotated, then yes there's this current limitation, but it shouldn't be too hard to fix. At least, conceptually, there's nothing fundamentally hard about it other than someone needing to do the work of wiring up the existing support of Hibernate ORM to our custom bootstrap code.

HTH

**Comment by yrodiere** [comment] 2021-03-18 13:10
@mgwillem Could you please detail what your classpath looks like? What are the JARs involved, where are the `orm.xml` files and there `persistence.xml` files, and which `persistence.xml` file references which `orm.xml` file?

The JPA spec allows many different setups, and it gives the tools to achieve these setups by allowing a `persistence.xml` to specify a list of JARs.

But currently, we don't support that in Quarkus, so we can end up including `orm.xml` files that shouldn't be included. And that's a very real problem: if a `META-INF/orm.xml` file in the classpath defines a default schema, you definitely don't want to apply it to the wrong persistence unit.

Here are the use cases that I can think of:

1. Single-JAR application, configured through either `application.properties` or `persistence.xml`.
2. Multi-JAR application configured through either `application.properties` or `persistence.xml`, where the `orm.xml` files have unique names across all JARs.
3. Multi-JAR application configured through a `persistence.xml`, where the `orm.xml` files may not have unique names, but are always located in the same JAR as the corresponding `persistence.xml`.
4. Multi-JAR application where the `orm.xml` files do **not** have unique names, and are not necessarily located in the same JAR as the `persistence.xml` they need to be used with, or are used in a persistence unit that doesn't have a `persistence.xml`.

Use cases 1 and 2 can be covered easily (barring any problem with the XML parsers, but that's another matter).

Use case 3 requires the configuration of the persistence unit through a `persistence.xml`, but could be covered as well, as long as we have a way to detect where each file (`persistence.xml` or `orm.xml`) comes from (which JAR).

Use case 4 cannot be addressed unless we add support for assigning JARs to a persistence unit, so that we can filter out irrelevant `orm.xml` files. And from what I can see, that doesn't look like something we want to do... @Sanne?

**Comment by Sanne** [comment] 2021-03-18 15:20
by spec 8.2.1 the default name would be `META-INF/orm.xml`, and is able to avoid ambiguity by storing this resource in the root of the persistence unit (e.g. in the same jar as persistence.xml and its entities).

So I'd say you don't have to implement "case 4" as that was never supported in other systems either.

**Comment by yrodiere** [comment] 2021-03-18 15:29
> by spec 8.2.1 the default name would be `META-INF/orm.xml`, and is able to avoid ambiguity by storing this resource in the root of the persistence unit (e.g. in the same jar as persistence.xml and its entities).

I wish :)

> An object/relational mapping XML file named orm.xml may be specified in the META-INF directory in the root of the persistence unit **or in the META-INF directory of any jar file referenced by the persistence.xml**.

Taken from the ORM documentation, quoting the spec: https://docs.jboss.org/hibernate/orm/5.4/userguide/html_single/Hibernate_User_Guide.html#bootstrap-jpa-xml-files

**Comment by Sanne** [comment] 2021-03-22 10:15
@yrodiere I don't understand your point for "I wish" - could you clarify?

It seems to me that it's avoiding ambiguity, what am I missing?

**Comment by yrodiere** [comment] 2021-03-22 10:47
Sorry if that wasn't clear, my point was just below. By spec, `orm.xml` does not even have to be in the same JAR as the `persistence.xml`. Users can avoid ambiguity by specifying the relevant JARs in their `persistence.xml`.

So from my understanding, this JAR content is spec-compliant:

* `my-app.jar`
  * `persistence.xml`
    * PU1
      * `<mapping-file>META-INF/orm.xml</mapping-file>`
      * `<jar-file>pu1.jar</jar-file>`
    * PU2
      * `<mapping-file>META-INF/orm.xml</mapping-file>`
      * `<jar-file>pu2.jar</jar-file>`
* `pu1.jar`
  * `META-INF/orm.xml`
* `pu2.jar`
  * `META-INF/orm.xml`

Same with custom (non-default) file names:

* `my-app.jar`
  * `persistence.xml`
    * PU1
      * `<mapping-file>META-INF/my-orm.xml</mapping-file>`
      * `<jar-file>pu1.jar</jar-file>`
    * PU2
      * `<mapping-file>META-INF/my-orm.xml</mapping-file>`
      * `<jar-file>pu2.jar</jar-file>`
* `pu1.jar`
  * `META-INF/my-orm.xml`
* `pu2.jar`
  * `META-INF/my-orm.xml`

Looking at the (complex) code that handles JARs and entity/resource scanning in ORM, it does seem to handle this kind of setup.

I can tell that we won't be able to provide something that is both simple (flat classpath, simple entity/resource scanner) and adheres to the spec. And that's fine I guess, we don't want to handle every single legacy quirk that JEE allows, but then the whole of this issue was to support legacy setups, so I'm not sure where we should draw the line :)

I'll start with a simple implementation where we just look for mapping files everywhere, and fail if there are multiple resources for a given mapping file name. That should cover use cases 1 and 2.

Then I'll see about use case 3: when looking for a mapping file, I'll consider that a file in the same JAR as the `persistence.xml` gets precedence over all others with the same name.

That should be a decent compromise, I think. And anyway, we cannot support more without supporting `<jar-file>`.

**Comment by mgwillem** [comment] 2021-03-22 11:26
Sorry for the late response.

My use case is the following:
I've 2 legacy libraries, let's call them libA.jar and libB.jar, that are
used by my application.

Compiled for Oracle ... both libA and libB do not contain any
META-INF/orm.xml file.
Compiled for MSSQL ... both libA and libB contain META-INF/orm.xml files
(to override schema and PK generated value [from sequence to identity]).

persistence.xml do not reference the META-INF/orm.xml file as it is
automatically detected by JPA.

Does it answer to your question ? :)

Marc



Le jeu. 18 mars 2021 à 14:10, Yoann Rodière ***@***.***> a
écrit :

**Comment by yrodiere** [comment] 2021-03-22 12:03
> Does it answer to your question ? :)

Almost, thanks. One remaining question: where is the `persistence.xml`? In which file(s)? `libA.jar`, `libB.jar`, or your application jar?

**Comment by sithmein** [comment] 2021-03-22 12:06
In my use case there wouldn't be a `persistence.xml` at all because Quarkus should set up everything.

**Comment by yrodiere** [comment] 2021-03-22 12:14
> In my use case there wouldn't be a `persistence.xml` at all because Quarkus should set up everything.

Sure. I have that in mind too: allow listing mapping files in the Quarkus configuration.

The legacy use cases are much more tricky though, so I'd like to know where the `persistence.xml` file is in @mgwillem 's case...

**Comment by gavinking** [comment] 2021-03-22 12:45
> Sorry if that wasn't clear, my point was just below. By spec, `orm.xml` does not even have to be in the same JAR as the `persistence.xml`. Users can avoid ambiguity by specifying the relevant JARs in their `persistence.xml`.

That seems like a very fine setup in Java EE where you have assemblies (EARs and WARs) that contain `jar`s. And the domain model might be in the `jar` along with its `orm.xml`, and the `persistence.xml` would quite likely be in the assembly.

But do we have that sort of thing here?

**Comment by mgwillem** [comment] 2021-03-22 12:46
libA.jar and libB.jar contain one META-INF/persistence.xml file each.
In my use case the application jar does not contain any persistence file.

Le lun. 22 mars 2021 à 13:14, Yoann Rodière ***@***.***> a
écrit :

**Comment by yrodiere** [comment] 2021-03-22 12:55
> But do we have that sort of thing here?

No, we don't have `<jar-file>` support, even when using `persistence.xml`. There's an exception somewhere being thrown as soon as we detect `<jar-file>` being used.

So that was my point: I don't think we can (fully) support use case 4 without `<jar-file>` support. 

Maybe that's fine, maybe that's not; in any case, supporting the other use cases will be a lot of work already, so I'll stick to that for now.

Fortunately for @mgwillem , it seems he doesn't need that as his `orm.xml` files are in the root file of his persistence units:

> libA.jar and libB.jar contain one META-INF/persistence.xml file each.
> In my use case the application jar does not contain any persistence file.

Alright, thank you! That's use case 3, then.

**Comment by yrodiere** [comment] 2021-04-19 16:15
I submitted a PR to support XML mapping: https://github.com/quarkusio/quarkus/pull/16630

Anyone interested in the feature, please try it out and report about your results! You will need to build the main branch of Hibernate ORM locally first, though. See the PR description.

**Comment by agoncal** [comment] 2021-05-17 10:40
I do have the same problem now. I have a `legacy.jar` that I cannot touch (nor add any configuration file) with a few entities and POJOs that need to be mapped and queried in my app. I've tried adding a `persistence.xml` file with `<mapping-file>` targetting `orm.xm` but didn't work.

Hoping the PR will get in soon ;o) Let me know, I'm ready to test it if you need someone

**Comment by Sanne** [comment] 2021-05-17 10:55
hi @agoncal ! Feel free to test the PR - it looks good, the reason for which it wasn't merged yet should not be a problem for you in practice.

**Comment by agoncal** [comment] 2021-05-17 11:55
@Sanne I just gave it a try and it works! 

I had the following exception:

```
        [error]: Build step io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#defineJpaEntities threw an exception: io.quarkus.deployment.configuration.ConfigurationError: Unable to properly register the hierarchy of the following JPA classes as they are not in the Jandex index:
        - org.agoncal.quarkus.jdbc.Customer
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
 ```

So I had to add the following to the `application.properties`:

```
quarkus.index-dependency."customer".group-id=org.agoncal.course.quarkus
quarkus.index-dependency."customer".artifact-id=jdbc
```

Works like a charm ! And best of the best, I can create a `PanacheRepositoryBase` out of this mapped POJO !

**Comment by yrodiere** [comment] 2021-05-17 11:57
Thanks for testing @agoncal ; happy to see it works for you.

Hopefully we'll get rid of the remaining metaspace problem soon (it may be unrelated, but it's blocking the PR pending investigation). Then we'll merge the PR.

**Comment by Sanne** [comment] 2021-05-17 13:09
that Jandex error makes me think we might want to automatically add them to the index, if we can identify the artifact

**Comment by agoncal** [comment] 2021-05-17 13:18
That would be awesome. As a developer I don't want to know this level of details of Quarkus internals.

**Comment by yrodiere** [comment] 2021-05-17 13:18
@Sanne Maybe. But we cannot add them to the index until we start processing the mapping files and going through the entity hierarchy. I suspect we cannot add them to the index at this point, otherwise this error message wouldn't be here in the first place?

**Comment by yrodiere** [comment] 2021-05-17 13:22
Created #17285

**Comment by agoncal** [comment] 2021-05-18 11:53
I found something weird. `nullable=false` doesn't seem to get mapped. I have the following POJO on a separate JAR file:

```
public class Artist {

  private Long id;
  private String name;
  private String bio;
  private Instant createdDate = Instant.now();
  // Getters and setter
}
```

When I had this `orm.xml` file to my project, `Artist` gets mapped with all the defaults:

```
  <entity class="org.agoncal.quarkus.jdbc.Artist">
    <attributes>
      <id name="id">
        <generated-value strategy="AUTO"/>
      </id>
    </attributes>
  </entity>

create table Artist
(
    id          int8 not null,
    bio         varchar(255),
    createdDate timestamp,
    name        varchar(255),
    primary key (id)
)
```

Now, if I customize the mapping, the name of the table, name of the columns, the length of the columns do get changed, but not the nullability (`name` and `created_date` should not be null:

```
  <entity class="org.agoncal.quarkus.jdbc.Artist">
    <table name="t_artists"/>
    <attributes>
      <id name="id">
        <generated-value strategy="AUTO"/>
      </id>
      <basic name="name">
        <column length="50" nullable="false"/>
      </basic>
      <basic name="bio">
        <column length="3000"/>
      </basic>
      <basic name="createdDate">
        <column name="created_date" nullable="false"/>
      </basic>
    </attributes>
  </entity>

create table t_artists
(
    id           int8 not null,
    bio          varchar(3000),
    created_date timestamp,
    name         varchar(50),
    primary key (id)
)
```

Is my syntax right ? Am I doing something wrong or is the mapping not working correctly ?

**Comment by yrodiere** [comment] 2021-05-18 13:46
@agoncal This looks odd, though I doubt it's caused by Quarkus... Then again, looking at the ORM code, I don't see how `length` could work while `nullable` does not; they are literally handled 5 lines from each other.

Do you have a quick reproducer? If so, please open a ticket either for Quarkus or ORM, I'll try to debug it.

**Comment by agoncal** [comment] 2021-05-18 14:55
@yrodiere  Yes, I managed to reproduce it in a much simpler example https://github.com/agoncal/agoncal-bug-quarkus-orm

**Closed** 2021-05-19 06:24 UTC
Labels: area/hibernate-orm, kind/enhancement
