### ISSUE TITLE
Mounted configMaps not accessible from native-image on OCP

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#10948] opened 2020-07-23 20:34 UTC
**Describe the bug**
Properties in mounted `configMap` are not propagated to native-image application layered on `ubi-quarkus-native-s2i:19.3.1-java11` deployed on OCP.

**Expected behavior**
Properties in mounted `configMap` are properly propagated and usable in native-image application.

**Actual behavior**
Properties in mounted `configMap` are not available in native-image application.

**To Reproduce**
1. Check out the application at https://github.com/mjurc/quarkus-openshift-test-suite/tree/configmap-native-repro/configmap
2. Create native image runner of this app, with e. g. `mvn -B -V -Dquarkus.package.type=native -Dquarkus.native.container-runtime=docker`
3. Deploy a sample `configMap` to OCP with `oc apply -f src/test/resources/configmap.yaml`
4. Deploy the application with `oc apply -f target/kubernetes/openshift.yml`
5. Start a build with `oc start-build configmap --from-dir=target --follow`
6. Check the application endpoint - the message application uses from `configMap` are not available

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  `Linux tigris 5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "11.0.8" 2020-07-14`
 - GraalVM version (if different from Java): default from Quarkus builder image
 - Quarkus version or git rev: `master`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)`

**Comment by geoand** [comment] 2020-07-24 06:23
@mjurc is there an openshift cluster I can use to test this?

**Comment by geoand** [comment] 2020-07-24 06:43
Furthermore, I can't seem to build the test project, I am getting all sorts of errors

**Comment by geoand** [comment] 2020-07-24 06:53
This isn't a bug.

Since you changed `quarkus.s2i.base-jvm-image` to `quay.io/quarkus/ubi-quarkus-native-binary-s2i` (from `registry.access.redhat.com/openjdk/openjdk-11-rhel7`), you also need to update `quarkus.openshift.mounts.app-config.path` to the path where the application jar is copied (and run from) for that specific S2I image (which I think is `/home/quarkus` for the image you are using).

I am going to close this as it's a user-error, but feel free to reopen and / or comment with new information you have.

**Closed by geoand** 2020-07-24 06:53 UTC
Labels: area/kubernetes, kind/bug

**Comment by mjurc** [comment] 2020-08-05 13:43
@geoand I've tried mounting the `configMap` to `/home/quarkus`, however that will delete the native binary deployed there in S2I binary build.

I've also tried mounting the `configMap` volume to `/home/quarkus/config` too since the jar runner seems to have no issues picking the configuration from such location. This does not work for the native image binary though.

I am not quite sure how Quarkus apps pick up the properties from property files right now, nor I can find the documentation for it.

**Comment by geoand** [comment] 2020-08-05 14:01
> I've also tried mounting the `configMap` volume to `/home/quarkus/config` too since the jar runner seems to have no issues picking the configuration from such location. This does not work for the native image binary though.
> 

From: https://quarkus.io/guides/config#overriding-properties-at-runtime

```
The config/application.properties features is available in development mode as well. To make use of it, config/application.properties needs to be placed inside the build tool’s output directory (target for Maven and build/classes/java/main for Gradle). Keep in mind however that any cleaning operation from the build tool like mvn clean or gradle clean will remove the config directory as well. 
```

So all you need to know is the directory where the native binary exists in, and place have the config map mounted in `config` so `config/application.properties` ends up in the filesystem

**Comment by rsvoboda** [comment] 2020-08-06 13:59
I would appreciate simple step by step guide for the scenario of native image being deployed into OpenShift with ConfigMap being used.

**Comment by geoand** [comment] 2020-08-06 14:07
That will have to wait until I get from PTO unfortunately (unless someone else wants to provide it)

**Comment by rsvoboda** [comment] 2020-08-06 14:08
ups, you are off for 2 weeks, right? Who is your "backup" for OpenShift / Kubernetes area?

**Comment by geoand** [comment] 2020-08-06 14:12
Yeah, that it right.

Ioannis would qualify as my backup, but he is on PTO as well.

Maybe @Ladicek can help (if not on PTO)? If not, then I'll try and put aside some time to get to this sooner.

**Comment by Ladicek** [comment] 2020-08-06 15:33
I took a look and can confirm this has nothing to do with accessing a ConfigMap mounted into the container filesystem.

What I did:

1. Updated `application.properties` as described in this discussion. Specifically, I updated these 2 lines:

    ```properties
    quarkus.openshift.mounts.app-config.path=/home/quarkus/config
    quarkus.s2i.base-jvm-image=quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0
    ```

2. Built the application. This is against latest Quarkus `master`:

    ```bash
    mvn -am -pl app-metadata/deployment,configmap clean package -Dquarkus.package.type=native -Dquarkus-core-only
    ```

    I do have GraalVM with `native-image` installed locally, it's the Java 8 variant of GraalVM 20.1.0. Maven is also using Java 8. (Should I feel old, if I'm still using Java 8?) All on Linux, obviously.

3. Deployed it to OpenShift. All commands here are in the `configmap` directory:

    ```bash
    oc apply -f src/test/resources/configmap.yaml
    oc apply -f target/kubernetes/openshift.yml
    # now wait until the ImageStream populates
    # using --from-file instead of --from-dir just to save a bit of time, otherwise there's no difference
    oc start-build configmap --from-file=target/configmap-1.0.0-SNAPSHOT-runner --follow
    ```

4. Waited until the app starts and then hit the endpoint using `curl`. I got an `Internal Server Error`, and the application log contained:

    ```
    2020-08-06 15:18:32,505 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 52bbb078-9ea9-406b-beb7-66ef743d2051-1: org.jboss.resteasy.spi.UnhandledException: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.quarkus.ts.openshift.configmap.Hello and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
    ...
    Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.quarkus.ts.openshift.configmap.Hello and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS)
    ...
    ```

From this itself, it's obvious that there's some other problem (I'll come to it in a bit). But just to be sure, I've put a debug print into the `HelloResource` class:

```java
if (message.isPresent()) {
    System.out.println("!!!!!!!!!!!!!! " + message.get());
    return Response.ok().entity(new Hello(String.format(message.get(), name))).build();
}
```

When I rebuild and redeploy, I see the debug print in the console, saying:

```
!!!!!!!!!!!!!! Hello %s from ConfigMap!
```

So the ConfigMap is mounted into the filesystem on the right place and the application reads it just fine.

Now why did serialization fail? I _guessed_ that I have to add `@RegisterForReflection`, because the JAX-RS resource method has a generic return type of `Response`, so Quarkus isn't smart enough to figure out that the `Hello` class can be used as entity body. And sure enough, when I added the annotation on the `Hello` class, everything works perfectly.

Would be great to understand why it's failing for you. There's a couple of small differences between what you and I do, and while in theory they shouldn't make a difference, it's possible they do :-)

**Comment by geoand** [comment] 2020-08-06 15:54
Thanks a lot @Ladicek !

I can confirm that the Response issue you had is due to Response not having a generic type and thus Quarkus not knowing what type to register for reflection

**Comment by rsvoboda** [comment] 2020-08-07 06:57
> quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0

This S2I image way might work for upstream, but for product the plan was that user builds native image on his own (Jenkins , Tekton pipeline) and deploys to OpenShift just the final native on top of ubi8 image, @tqvarnst is it still the plan?

> Response not having a generic type and thus Quarkus not knowing what type to register for reflection

How can user know this? Can Quarkus detect these common issues and warn users about it.
I know we have guide for native image with some tips, but it's not always easy to connect the dots.
For example https://quarkus.io/guides/writing-native-applications-tips#alternative-with-registerforreflection is just one line and people need to have context.

**Comment by geoand** [comment] 2020-08-07 07:03
> > Response not having a generic type and thus Quarkus not knowing what type to register for reflection
> 
> How can user know this? Can Quarkus detect these common issues and warn users about it.
> I know we have guide for native image with some tips, but it's not always easy to connect the dots.
> For example https://quarkus.io/guides/writing-native-applications-tips#alternative-with-registerforreflection is just one line and people need to have context.

We can't really warn users in code, as that would potentially lead to a lot of false positives.

It might make sense to have mention this limitation in some part of the rest guide.

**Comment by Ladicek** [comment] 2020-08-07 07:10
> > quay.io/quarkus/ubi-quarkus-native-binary-s2i:1.0
> 
> This S2I image way might work for upstream, but for product the plan was that user builds native image on his own (Jenkins , Tekton pipeline) and deploys to OpenShift just the final native on top of ubi8 image, @tqvarnst is it still the plan?

This S2I image is actually `ubi8-minimal` + few more packages installed + S2I scripts for the binary build. (Only for binary build, That is, the image expects the binary to be built elsewhere.)

I have no idea why there are tags for different versions of GraalVM, because there doesn't seem to be anything GraalVM-related in the image.

> > Response not having a generic type and thus Quarkus not knowing what type to register for reflection
> 
> How can user know this? Can Quarkus detect these common issues and warn users about it.
> I know we have guide for native image with some tips, but it's not always easy to connect the dots.
> For example https://quarkus.io/guides/writing-native-applications-tips#alternative-with-registerforreflection is just one line and people need to have context.

Seems to be documented in https://quarkus.io/guides/writing-native-applications-tips The thing is, there's too much guides, and designing a proper information architecture for the Quarkus website is probably pretty hard. I knew about `@RegisterForReflection` because I read everything on the `quarkus-dev` mailing list. Which automatically makes me a tiny minority.

Perhaps in the product documentation, which is currently a lot smaller, this could be highlighted somehow.
