### ISSUE TITLE
Live reload fails with NoSuchMethodError if return type of a method is changed

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#35834] opened 2023-09-10 06:18 UTC
### Describe the bug

Given this example:

```
@Path("/test")
public class TestResource {
    
    @Inject
    TestService testService;
    
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String test() {
        testService.test();
        return "test";
    }
}
```
```
@ApplicationScoped
public class TestService {
    public void test() {
    }
}
```

After changing return type of `TestService::test`:

```
public String test() {
    return null;
}
```

and hit the endpoint `/test`, I got this exception:

```
java.lang.NoSuchMethodError: 'void io.fouad.TestService.test()'
	at io.fouad.TestResource.test(TestResource.java:18)
	at io.fouad.TestResource$quarkusrestinvoker$test_7952b5690bf1ba89c415893cfb1f31837ef019a0.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1623)
```

### Quarkus version or git rev

3.3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.3

**Comment by geoand** [comment] 2023-09-11 06:15
This is actually a very interesting but we can't do much here... 

The problem is that in the case you describe two things are happening at once:
 
There exists `source compatibility` meaning that code that call the previous version `TestService#test` does not need to be recompiled. Furthermore, since in the case the caller (`TestResource`) is not changed, it is not recompiled. 

There exists is a `binary incompatibility` as the bytecode can no longer properly call the bytecode of `TestService#test` due to the changed return type.

As mentioned in the opening of my comment, we can't do much here, so I am going to close this.

**Closed by geoand** 2023-09-11 06:15 UTC
Labels: kind/bug, triage/needs-triage
