### ISSUE TITLE
Async-Await methods

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#13534] opened 2020-11-28 13:37 UTC
**Description**
Quarkus code seems to be highly async. As this has obvious advantages, there is also one major disadvantage:
- Code can quickly become unreadable and convoluted in some non-trivial scenarios

In those scenarios Aync-Await paradigm could be a more readable alternative. https://github.com/electronicarts/ea-async is a library that allows programmers to write asynchronous code in a sequential fashion. Unfortunately, it doesn't seem to be maintained anymore and it only supports JDK 8-10. It is also questionable if it works with Quarkus at all (haven't tried it TBH).

**Proposal**
Expose such/similar utility from Quarkus (either core or an extension) that would allow to write asynchronous code in a sequential fashion.

Let me know if this request does not make sense at all or if it's for some reason not possible.

Edit: seems to have been already mentioned in https://github.com/quarkusio/quarkus/issues/1957

**Comment by geoand** [comment] 2020-11-30 10:03
I know @FroMage has input on this

**Comment by FroMage** [comment] 2020-11-30 10:11
Yeah, that project didn't work in native back when I tried it, but recent graalvm improvements might have changed that. It was however much less versatile/useful than Quasar, which is what the JDK Loom work is based on. Perhaps you can try EA-Async with the latest `native-image` and let us know if it works now?

**Comment by geoand** [comment] 2021-08-03 11:18
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/1957

**Closed by geoand** 2021-08-03 11:18 UTC
Labels: kind/enhancement, triage/needs-triage
