### ISSUE TITLE
QuarkusIntegrationTest and QuarkusTestResource with custom testcontainer failing with "network not found"

### ISSUE THREAD

**Issue by kailashamk** [quarkusio/quarkus#21943] opened 2021-12-06 09:43 UTC
### Describe the bug

A new QuarkusIntegrationTest written for a Quarkus application utilizing quarkus-container-image-docker with a QuarkusTestResource starting the RabbitMQContainer with a NetworkId as shown below.

```java
@QuarkusIntegrationTest
@Tag("integration")
@TestProfile(TINValidatedEventReceiverIntegrationTest.IntegrationTestProfile.class)
@QuarkusTestResource(value = RabbitMQServerTestResource.class,restrictToAnnotatedClass = true)
public class TINValidatedEventReceiverIntegrationTest {

    @Test
    public void test_container_started_successfully() {
        // Check for the "Consumer *** consuming from ** has been registered" entry in quarkus log
        assertTrue(true);
        // Check that there are no errors in the quarkus log
    }

    public static class IntegrationTestProfile implements QuarkusTestProfile {

        @Override
        public Map<String, String> getConfigOverrides() {
            ServiceLoader.load(DockerClientProviderStrategy.class, this.getClass().getClassLoader());
            return Stream.of(new String[][]{
                {"quarkus.http.test-ssl-port", "0"}
            }).collect(Collectors.toMap(data -> data[0], data -> data[1]));
        }
    }
}
```

```java
public class RabbitMQServerTestResource implements QuarkusTestResourceLifecycleManager,
    DevServicesContext.ContextAware {

    private RabbitMQContainer rabbitMQ;

    private Optional<String> containerNetworkId;

    @Override
    public Map<String, String> start() {
        rabbitMQ = new RabbitMQContainer(DockerImageName.parse("rabbitmq:3.8.26-management-alpine"))
            .withQueue("***");
        if (containerNetworkId.isPresent()) {
            rabbitMQ.setNetworkMode(containerNetworkId.get());
        }
        rabbitMQ.start();
        return Map.of(
            "rabbitmq_vhost", "/",
            "rabbitmq_portnumber", "5672",
            "rabbitmq_hostname", rabbitMQ.getContainerId().substring(0,12),
            "rabbitmq_username", rabbitMQ.getAdminUsername(),
            "rabbitmq_password", rabbitMQ.getAdminPassword());
    }

    @Override
    public void stop() {
        rabbitMQ.stop();
    }


    @Override
    public void setIntegrationTestContext(DevServicesContext context) {
        containerNetworkId = context.containerNetworkId();
    }
}
```

### Expected behavior

It is expected that the containers are started

### Actual behavior

Failing with the following error 

Caused by: org.testcontainers.containers.ContainerLaunchException: Could not create/start container
Caused by: com.github.dockerjava.api.exception.NotFoundException:
Status 404: {"message":"network quarkus-integration-test-ytWar not found"}

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15

### Quarkus version or git rev

2.5.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

Reason for this error and possible fix 
-----------------------------------------

Upon investigation, this is because of an issue in IntegrationUtil.handleDevServices 

 if (isDockerAppLaunch) {
            try {
                **Class<?> networkClass = curatedApplication.getAugmentClassLoader().loadClass("org.testcontainers.containers.Network");**
                Object sharedNetwork = networkClass.getField("SHARED").get((Object)null);
                networkId = (String)networkClass.getMethod("getId").invoke(sharedNetwork);
            } catch (Exception var19) {
                networkId = "quarkus-integration-test-" + RandomStringUtils.random(5, true, false);
                manageNetwork = true;
            }
        }

The "org.testcontainers.containers.Network" is loaded by the AugmentClassLoader instead of the ApplicationClassLoader.  However while creating the network in the TestContainer it is  failing to detect the DockerClient because of the classloader issue. 

There are 2 ways to change it. 
1. Make change in Quarkus  to not use the AugmentClassLoader  while loading the "org.testcontainers.containers.Network" but use the applicationclassloader itself ( not sure of the impact  )
2. Make change in TestContainers to use the ClassLoader from the Class rather than using the current thread's contextloader. Already checked with TestContainers ( https://github.com/testcontainers/testcontainers-java/issues/2470 ), but very reluctant to make that  change. ( Made change locally and it worked )

**Comment by geoand** [comment] 2021-12-06 09:47
Thanks for reporting.

This is a duplicate of https://github.com/quarkusio/quarkus/issues/21931 which has already been fixed in main

**Closed by geoand** 2021-12-06 09:47 UTC
Labels: kind/bug, area/testing, env/windows
