### ISSUE TITLE
GraphQL test failure on Java18

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#30064] opened 2022-12-23 17:02 UTC
### Describe the bug

I've noticed the following test failure in one of the Java18 builds:
```
2022-12-23T14:49:53.3617558Z [ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 10.939 s <<< FAILURE! - in io.quarkus.smallrye.graphql.deployment.ConcurrentAuthTest
2022-12-23T14:49:53.3621791Z [ERROR] io.quarkus.smallrye.graphql.deployment.ConcurrentAuthTest.concurrentAllFilmsOnly  Time elapsed: 8.899 s  <<< FAILURE!
2022-12-23T14:49:53.3622404Z org.opentest4j.AssertionFailedError: Unauthorized response codes were found ==> expected: <true> but was: <false>
```

**Comment by jmartisk** [comment] 2023-01-02 06:09
I think this might be the same as https://github.com/quarkusio/quarkus/issues/28145 and it's not Java18-specific

**Comment by jmartisk** [comment] 2023-03-28 12:47
closing as duplicate of https://github.com/quarkusio/quarkus/issues/28145

**Closed by jmartisk** 2023-03-28 12:47 UTC
Labels: kind/bug, area/smallrye, area/graphql
