### ISSUE TITLE
quarkus-smallrye-reactive-messaging-kafka build error since 3.0.0.CR2

### ISSUE THREAD

**Issue by henrikcaesar** [quarkusio/quarkus#32652] opened 2023-04-14 13:28 UTC
### Describe the bug

Building a quarkus application with the quarkus-smallrye-reactive-messaging-kafka extension gives the following warning since 3.0.0.CR2:

`[WARNING] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Cannot find the `native-image` in the GRAALVM_HOME, JAVA_HOME and System PATH. Install it using `gu install native-image` Attempting to fall back to container build.`

On my machine build continues, but in Jenkins running in K8s it fails with:
```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:3.0.0.CR2:build (default) on project eesk: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#resolveNativeImageBuildRunner threw an exception: java.lang.IllegalStateException: No container runtime was found. Make sure you have either Docker or Podman installed in your environment.
[ERROR] 	at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:99)
[ERROR] 	at io.quarkus.runtime.util.ContainerRuntimeUtil.detectContainerRuntime(ContainerRuntimeUtil.java:41)
[ERROR] 	at java.base/java.util.Optional.orElseGet(Optional.java:364)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner.<init>(NativeImageBuildContainerRunner.java:31)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildLocalContainerRunner.<init>(NativeImageBuildLocalContainerRunner.java:21)
[ERROR] 	at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.resolveNativeImageBuildRunner(NativeImageBuildStep.java:332)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

Switching to 3.0.0.CR1 no warning is printed. Changing to 3.0.0.CR2 it is shown.

### Expected behavior

Building a quarkus 3.0.0.CR2 (or newer) application with the quarkus-smallrye-reactive-messaging-kafka should work.

### How to Reproduce?

quarkus create app --stream=3.0 test
cd test
quarkus ext add quarkus-smallrye-reactive-messaging-kafka
edit pom.xml and set quarkus version to 3.0.0.CR1
mvn clean install

edit pom.xml and set quarkus version to 3.0.0.CR2
mvn clean install <---- THIS FAILS

### Output of `uname -a` or `ver`

Linux migvubuntu 5.15.79.1-microsoft-standard-WSL2 #1 SMP Wed Nov 23 01:01:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16.1" 2022-08-12 OpenJDK Runtime Environment Temurin-11.0.16.1+1 (build 11.0.16.1+1) OpenJDK 64-Bit Server VM Temurin-11.0.16.1+1 (build 11.0.16.1+1, mixed mode)

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/xxx/.asdf/installs/maven/3.8.1 Java version: 11.0.16.1, vendor: Eclipse Adoptium, runtime: /home/xxx/.asdf/installs/java/adoptopenjdk-11.0.16+101 Default locale: en, platform encoding: UTF-8 OS name: "linux", version: "5.15.79.1-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by ozangunalp** [comment] 2023-04-14 13:31
I think this is a duplicate of #32461, @geoand wdyt ?

**Closed** 2023-04-14 13:39 UTC
Labels: kind/bug, area/smallrye, area/reactive-messaging, area/kafka

**Comment by gsmet** [comment] 2023-04-14 14:29
In other words, it should be fixed in the Final! Thanks for the report.
