### ISSUE TITLE
Hazelcast fails to locate config from classpath

### ISSUE THREAD

**Issue by Meemaw** [quarkusio/quarkus#11681] opened 2020-08-27 17:35 UTC
**Describe the bug**
When starting new Hazelcast Instance/Client it has extensive logic to locate configuration file (e.g. `hazelcast.xml`) from the environment.

Using quarkusDev (with gradle), Hazelcast fails to locate `hazelcast.xml` location in `resources/hazelcast.xml` and logs the following fallback message: `Loading 'hazelcast-default.xml' from the classpath.` (meaning it didn't find any file and uses a default configuration).

When quarkus is in production mode this works as expected and we can see the following message: `Loading 'hazelcast.xml' from the classpath.`

There seems to be some problem with classpath and how resources are handled in dev mode (in Gradle -- not sure if the behaviour is same in Maven)

**Environment (please complete the following information):**
 - Output of `java -version`: 13
 - Quarkus version or git rev: 1.6.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Gradle 6.6.1

**Comment by jaikiran** [comment] 2020-09-01 07:07
Hello @Meemaw, is there a simple application which you can share to reproduce this issue (perhaps as a github repo)? Also, can you try this against `1.7.1.Final` of Quarkus and see if it's fixed there?

**Comment by gsmet** [comment] 2020-09-01 07:42
I suspect it might be the Hazelcast library not using the TCCL to load the resources.

/cc @pivovarit

**Comment by pivovarit** [comment] 2020-09-01 07:44
I will investigate it. @gsmet can you assign me to the issue?

**Comment by gsmet** [comment] 2020-09-01 08:11
Sure.

@Meemaw as mentioned by @jaikiran , a reproducer would help.

**Comment by Meemaw** [comment] 2020-09-01 08:31
Here is the reproducer: https://github.com/Meemaw/quarkus-hazelcast-config-bug-reproducer

Its pretty straightforward, nothing special. You can run dev mode using `/gradlew quarkusDev` and visit http://localhost:8080/hello (it should work) ✅ 

Then you can build the app using `./gradlew quarkusBuild --uber-jar`, run it with `java -jar build/hazelcast-config-my-version-runner.jar` and visit http://localhost:8080/hello (it will crash) 💣

**Comment by Meemaw** [comment] 2020-09-03 13:54
@pivovarit were you able to reproduce the issue?

**Comment by pivovarit** [comment] 2020-09-03 13:55
Yes, but I have no clue why it's happening for now :)

**Comment by pivovarit** [comment] 2020-09-03 18:35
I have news. Good and bad.

The good one is that I identified the cause of the issue. The bad one is that it requires a subtle change in how Hazelcast deals with resource loading, so the fix will be made available in the next bugfix version.

I will post more details here once I prepare a PR

**Comment by pivovarit** [comment] 2020-09-14 12:25
This got fixed in the Hazelcast core and will be included in 4.1 and 4.0.3 ([link](https://github.com/hazelcast/hazelcast/pull/17491))

@gsmet I believe we can close this one

**Comment by gsmet** [comment] 2020-09-14 12:36
@pivovarit maybe let's close it once the Platform is updated so that we can set the fix version?

**Comment by pivovarit** [comment] 2020-09-14 12:37
Sure!

**Comment by glefloch** [comment] 2021-02-21 13:03
I just tested this with hazelcast 4.0.3 and 4.1. The test project works. I think we can close this one.

**Closed by glefloch** 2021-02-21 13:03 UTC
Labels: area/gradle, kind/bug
