### ISSUE TITLE
KUBERNETES_GROUP=wonka mvn package not taking effect if kubernetes.group set in application.properties

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#6799] opened 2020-01-27 09:45 UTC
while testing #5496  I noticed that `KUBERNETES_GROUP=wonka mvn package` doesn't win over `kubernetes.group=mything` in `application.properties`.

it should according to https://quarkus.io/guides/config#overriding-properties-at-runtime

**Comment by iocanel** [comment] 2020-01-27 09:49
Just verified that myself. I will have a closer look.

**Comment by iocanel** [comment] 2020-01-29 11:01
@maxandersen: I can no longer reproduce it on master. Can you please verify?

**Comment by iocanel** [comment] 2020-01-29 11:02
Also, added an integration test for that. The test overrides the value found in application.properties via system.properties (due to maven invoker plugin limitations). And it seems to work fine.

**Comment by iocanel** [comment] 2020-02-03 15:15
@maxandersen: I think that we can close this now. Any objections?

**Comment by geoand** [comment] 2020-03-19 11:29
I assume we can close this?

**Comment by geoand** [comment] 2020-04-06 11:58
This has since been fixed, so I am closing

**Closed by geoand** 2020-04-06 11:58 UTC
Labels: area/config, area/kubernetes
