### ISSUE TITLE
quarkus  stopped unexpectedly with no error message

### ISSUE THREAD

**Issue by lpn666** [quarkusio/quarkus#33570] opened 2023-05-24 06:49 UTC
### Describe the bug

Quarkus  stopped unexpectedly with no error message。
My project is very simple ,  consume from one kafka topic, and send message to another topic.
But the program would stopped within a few days of starting , with no error message .
This is the log 
![image](https://github.com/quarkusio/quarkus/assets/26716574/7320c0e7-95c9-4ff7-9d4e-69a9c16aa0d1)

### Output of `uname -a` or `ver`

Linux uat142 4.19.90-2107.6.0.0100.oe1.bclinux.x86_64 #1 SMP Wed Dec 1 19:59:44 CST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

Graalvm  17

### GraalVM version (if different from Java)

17

### Quarkus version or git rev

3.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.8

**Comment by geoand** [comment] 2023-05-24 09:19
I am pretty sure we are going to need a lot more information, but I'll leave it up to @ozangunalp

**Comment by ozangunalp** [comment] 2023-05-24 09:29
Yes, we'd need a lot more information than that. 
Without a reproducer, it'd be very hard to understand what is going on. 
Looking at the few lines of logs, it seems like your system has killed the process intentionally.

**Comment by lpn666** [comment] 2023-05-25 01:08
Thank you for your reply.  My program is so  simple   that  that I don’t know what to post.  
this is my pom file
```
<dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-mutiny</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-vertx</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-smallrye-reactive-messaging-kafka</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>org.opensearch.client</groupId>
      <artifactId>opensearch-rest-high-level-client</artifactId>
      <version>2.6.0</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-scheduler</artifactId>
    </dependency>

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.rest-assured</groupId>
      <artifactId>rest-assured</artifactId>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-core-deployment</artifactId>
    </dependency>
  </dependencies>
```

this is some of my code 
```
@ApplicationScoped
public class VertxKafkaServer {

    public VertxKafkaServer(@ConfigProperty(name = "opensearch.index") String index,
                            @ConfigProperty(name = "server.generated.interval") Long interval,
                            Logger log,
                            BulkClient bulkClient) {
        this.interval = interval;
        this.index = index;
        this.log = log;
        this.bulkClient = bulkClient;
    }

    final String index;

    final Long interval;


    final SimpleDateFormat sf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ");

    final Logger log;

    final BulkClient bulkClient;

    @Incoming("abc-in")
    public void consume(JsonObject jsonObject) {
        jsonObject.put("request_time", sf.format(new Date()));
        log.debugv("get record {0}",jsonObject.encodePrettily());
        String msg = jsonObject.getString("msg");
        String replace = msg.replace("/", "");
        JsonObject detail;
        
        ......
    }


    @Outgoing("abc-out")
    public Multi<JsonObject> pp() {
        JsonObject entries = new JsonObject("{\"thread\":\"main\",\"level\":\"INFO \",\"msg\":\"test msg\"}\n");
        if (interval != 0) {
            return Multi.createFrom().ticks().every(Duration.ofMillis(interval))
                    .map(l -> entries);
        }
        return Multi.createFrom().nothing();
    }

}
```
This is the main code ,  and I don't know why the program shutdown for no reason.
By the way ,  there is no error or warn in log .
What I  pasted before , is all...

**Comment by geoand** [comment] 2023-05-25 10:49
Is this running on some kind of orchestrator like Kubernetes?

**Comment by lpn666** [comment] 2023-05-26 05:36
no , I build it native , and run it on  some  linux  system  like centos .

**Comment by lpn666** [comment] 2023-05-30 03:17
@geoand   a......  can you help me please  ?  I can't find any  error ,  at the same time  I run other program  with no error.
Are there any  opinion I can try ?

**Comment by geoand** [comment] 2023-05-30 04:59
It is very unlikely something to do with Quarkus.

Maybe the OS terminated the process due to low overall memory - it's not possible to know given the information we have

**Comment by lpn666** [comment] 2023-05-30 05:53
ok , thanks any way.  I'll reply when I find the exact problem.

**Comment by geoand** [comment] 2023-05-30 05:54
👍🏼 

Closing for the time being. If you do get more information, feel free to comment

**Closed by geoand** 2023-05-30 05:54 UTC
Labels: kind/bug, area/reactive-messaging, triage/needs-reproducer

**Comment by RostyslavKylymchuk** [comment] 2023-12-22 15:16
@lpn666 Have you found the problem?
