### ISSUE TITLE
Quarkus Reactive Cron Job Persistence Issue : io.quarkus.runtime.BlockingOperationNotAllowedException

### ISSUE THREAD

**Issue by OAboutayeb** [quarkusio/quarkus#37524] opened 2023-12-05 11:53 UTC
### Describe the bug

We are reaching out to seek your assistance with a specific challenge we are facing in our Quarkus application.

**Overview:**
We have a cron job triggering two services: one reactive service managing business logic using one of the two datasources, and the other handling persistence in our second datasource.
Our initial aim was to create a reactive application, but we discovered that the library we are using does not fully support reactive operations. As a result, we shifted to "quarkus-hibernate-orm-panache" since Hibernate ORM better aligns with our needs.

**The Challenge:**
The issue arises when a reactive cron job triggers our services, calling a method annotated with "@Transactional." Within this method, we perform a blocking Hibernate "persist" operation.
This leads to the exception: "io.quarkus.runtime.BlockingOperationNotAllowedException: Cannot start a JTA transaction from the IO thread."

**Reproducer:**
To aid in understanding and resolving the matter, we have provided a reproducer with the same configuration, replicating the exception.

**Producer Link:**
https://github.com/OAboutayeb/Quarkus-Producer

**Additional Context:**
Initially, our goal was straightforward: a reactive cron job calling services that use two datasources with Hibernate ORM. We perform persistence only with one datasource. The current issue involves attempting to persist a detached entity. While we have successfully made the cron job work by manually attaching the entity with a "merge," we aim to automatically attach the entity, using a simple ".persist()" approach.

**Request for Assistance:**
We sincerely appreciate your insights and guidance in navigating this challenge. If you require additional information or have specific requests, please do not hesitate to let us know.

### Output of `java -version`

Java 17

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by mkouba** [comment] 2023-12-05 14:54
I've tried to explain why it's not a bug on [zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Reactive.20Cron.20Job.20Persistence.20Issue.20.3A.20io.2Equarkus.2Erun). This is probably more a topic for https://github.com/quarkusio/quarkus/discussions.

**Comment by yrodiere** [comment] 2024-08-13 15:49
> I've tried to explain why it's not a bug on [zulip](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Reactive.20Cron.20Job.20Persistence.20Issue.20.3A.20io.2Equarkus.2Erun). This is probably more a topic for https://github.com/quarkusio/quarkus/discussions.

Hey @mkouba , should we close this as "Not planned" then?

**Closed** 2024-08-26 11:16 UTC
Labels: area/hibernate-orm
