### ISSUE TITLE
Can't run quarkus:dev with maven 3.6.0

### ISSUE THREAD

**Issue by suchwerk** [quarkusio/quarkus#2078] opened 2019-04-15 10:27 UTC
Using maven 3.6.0

```
Apache Maven 3.6.0
Java version: 1.8.0_171, vendor: Oracle Corporation, runtime: /usr/lib/jvm/java-8-oracle/jre
OS name: "linux", version: "4.18.0-18-generic", arch: "amd64", family: "unix"
```

generating using-jwt-rbac example

```
mvn io.quarkus:quarkus-maven-plugin:0.13.1:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=using-jwt-rbac \
    -DclassName="org.acme.jwt.TokenSecuredResource" \
    -Dpath="/secured" \
    -Dextensions="resteasy-jsonb, smallrye-jwt"
```

and try to compile and run (` mvn compile quarkus:dev`) leads to:

```
[INFO] Scanning for projects...
[INFO] 
[INFO] ----------------------< org.acme:using-jwt-rbac >-----------------------
[INFO] Building using-jwt-rbac 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ using-jwt-rbac ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ using-jwt-rbac ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /home/jk/projects/qbill/junk/target/classes
[INFO] 
[INFO] --- quarkus-maven-plugin:0.13.1:dev (default-cli) @ using-jwt-rbac ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.913 s
[INFO] Finished at: 2019-04-15T12:17:42+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.13.1:dev (default-cli) on project using-jwt-rbac: Failed to run: Failed to resolve Quarkus application model: Failed to locate current project among the loaded local projects -> [Help 1]
```

**Comment by suchwerk** [comment] 2019-04-15 10:55
It is a duplicate of #2056.

**Comment by aloubyansky** [comment] 2019-04-15 13:11
This doesn't look like a duplicate of #2056

**Comment by aloubyansky** [comment] 2019-04-15 13:16
That could be a stupid question but which directory are you running `mvn compile quarkus:dev` from @suchwerk ? Thanks.
I couldn't reproduce it following the instructions so far.

**Comment by aloubyansky** [comment] 2019-04-15 13:31
@suchwerk did you start from an empty directory?

**Comment by suchwerk** [comment] 2019-04-15 13:51
I did 
```
git clone https://github.com/quarkusio/quarkus-quickstarts.git
cd quarkus-quickstarts/using-jwt-rbac
mvn compile quarkus:dev
```
from within my current projects working dir (including a pom.xml)

**Comment by aloubyansky** [comment] 2019-04-15 19:54
Ok, I reproduced this issue and yes, #2056 fixes it. Thanks for reporting!

**Closed by aloubyansky** 2019-04-15 19:54 UTC
Labels: duplicate
