### ISSUE TITLE
Hibernate invalidate/update cache

### ISSUE THREAD

**Issue by leonardowestphal** [quarkusio/quarkus#17637] opened 2021-06-02 14:59 UTC
It would be very useful if the hibernate-orm extension added support for invalidating/updating the cache (local or remote) when persistent storage changes occur. Is there such an intention? I didn't find it on the roadmap.

**Comment by Sanne** [comment] 2021-06-02 15:12
hi @leonardowestphal there already is a capability to invalidate the regions, by using the standard Hibernate ORM APIs.
Did you try those?

**Comment by leonardowestphal** [comment] 2021-06-02 17:50
Hi @Sanne 
did you mean, for example, using:

```
em.getEntityManagerFactory().getCache().evict(MyClass.class); 
//or
em.getEntityManagerFactory().getCache().evictAll();
```
If so, it would be a very manual and infeasible process (in my scenario) to control whether a certain entity was changed or not.
Is there another way?

**Comment by Sanne** [comment] 2021-06-02 18:45
I'm not sure I understand - I thought you wanted us to expose an explicit operation to invalidate caches, but now it sounds like you're after an automatic invalidation. Hibernate ORM always invalidates its caches automatically when a matching entity is modified in the DB.

Could you elaborate on your use case? And what are you referring to when mentioning a "remote cache" ?

**Comment by leonardowestphal** [comment] 2021-06-02 19:45
I will try to detail a little more.

Local cache = hibernate-orm extension using the default Caffeine cache (in the same instance of the application). 
Remote cache = Hibernate-orm extension using Infinispan or another cache provider running on a different server or instance. From what I understand it's not supported by hibernate-orm extension yet.

In the documentation https://quarkus.io/guides/hibernate-orm#limitations-of-caching the following is mentioned:
_"These caches are kept locally, so they are not invalidated or updated when changes are made to the persistent store by other applications."_

I have two requirements for my use case and from my understanding the hibernate-orm extension doesn't support it yet:
1 - I need the cache to be automatically invalidated in case of database data changes (made by other applications or not);
2 - Having the possibility to use another cache provider separated from the application (I called it "remote cache"). It would be one or more instances of the application consuming the same "remote cache".

**Comment by Sanne** [comment] 2021-06-03 12:48
I don't disagree that this would be great - but when it comes to implementing such things, it's not really feasible (and I have quite some experience with it, I've worked on Infinispan & Hibernate integration patterns for many years) to keep this simple and bulletproof at the same time.

The most challenging aspect is to make such things work in a fully transparent way w/o the end user needing to configure (and make explicit) several complex aspect of transactional isolation expectations and the specific semantics which are acceptable under the various failure modes that can realistically happen in a production environment.

I actually do have some ideas which I hope could be interesting, but in terms of time investment I would need to dedicate at least six months to it so this has been pushed back by other needs of our projects.

Some middle-ground solutions might be necessary.


## Supporting Infinispan Remote (Hot Rod)

We *could* work on supporting Infinispan Remote Caches out of the box, but I have to warn you that it doesn't support transaction integration in a similar way as Infinispan Embedded Caches do - which implies that if we go for the solution using Hot Rod (Remote Caches), a new integration pattern will be needed in ORM (and it won't be as bullet-proof as the current one which makes use of transactions). So I have to enquire about the use case - would that be useful? And we should understand also if this would be more generally useful beyond yourself.

An alternative would be to use Infinispan Embedded - like WildFly does. This would have the benefit of reusing ancient and fairly battle-tested code with the support for Transactions, but it's really not easy to run an Infinispan Embedded cluster on Kubernetes and other clouds when the applications are joining & leaving the quorum potentially at high speed - this would most likely entail needing a custom operator as well.

## DB integration

Since you mention invalidating the cache because of *any* change on the Database, I should point out that there is no pre-existing technology being able to do so - except some concept prototypes with the Debezium team: Debezium would theoretically be able to notifiy the respective cache regions of *any* transaction which happened on the database, which is great, but this would come at the cost of being an asynchronous invalidation: there will be a gap in time in which your application will still be fed stale data from the caches, even though DB transactions have already committed making some changes. Of course people could work to make this gap in time minimal, but it would still exist.

In terms of implementation, I also think this would be interesting to do but it's another significant investment which I can't "just start" doing.

## Combined patterns

Optimistically speaking, suppose we did have an implementation for both the above solutions. I have this hunch that it could be possible to use both of them combined with version vectors to actually have a 2LC caching solution which is both transactionally safe, and able to guard against stale read windows caused by the asynchronous approach. But haven't proved none of this yet, and it would require implementing above solutions first.

If we had this, I agree it would be amazing - especially as I suspect it could really be bullet-proof, which then in turn implies it could be turned on by default without causing concern.

**Comment by leonardowestphal** [comment] 2021-06-07 12:39
Hi @Sanne 
I agree with you, remote caching support would be great and would suit many scenarios.

Just to confirm that I understand correctly... When you said: "Hibernate ORM always invalidates its caches automatically when a matching entity is modified in the DB."  
I can trust that hibernate already manages this. Is this not an operation performed by the hibernate-orm extension itself, right?

Thank you so much!

**Comment by Sanne** [comment] 2021-06-09 10:26
> Hi @Sanne
> I agree with you, remote caching support would be great and would suit many scenarios.
> 
> Just to confirm that I understand correctly... When you said: "Hibernate ORM always invalidates its caches automatically when a matching entity is modified in the DB."
> I can trust that hibernate already manages this. Is this not an operation performed by the hibernate-orm extension itself, right?

Right. To be clear though, Hibernate ORM can only invalidate the cache when it did flush the changes himself; so this wouldn't work if for example a different application connects to the same DB and makes some changes.

**Comment by crumohr** [comment] 2022-04-04 14:32
> An alternative would be to use Infinispan Embedded - like WildFly does. This would have the benefit of reusing ancient and fairly battle-tested code with the support for Transactions, but it's really not easy to run an Infinispan Embedded cluster on Kubernetes and other clouds when the applications are joining & leaving the quorum potentially at high speed - this would most likely entail needing a custom operator as well.

Hi @Sanne, is there still some discussion going on or are there any plans regarding the implementation of this idea of yours?

**Comment by yrodiere** [comment] 2023-01-12 07:58
Hi @Sanne, IIUC we can close this as "not planned"? Otherwise I don't understand what we're supposed to do here :)

**Closed** 2023-01-12 12:28 UTC
Labels: kind/enhancement, area/persistence, area/hibernate-orm
