### ISSUE TITLE
The optional configuration group is always empty.

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#17088] opened 2021-05-08 11:17 UTC
## Describe the bug
I customized a quarkus extension of the vertx web client and configured WebClient instantiation parameters through the application.properties file. The proxy configuration is always empty, it is an optional configuration group.

RootWebClientConfiguration.java
```java
@ConfigRoot(name = "spinach.web.client", phase = ConfigPhase.RUN_TIME)
public class RootWebClientConfiguration {

    public static final String DEFAULT_CLIENT = "<default>";

    public static boolean isDefault(String name) {
        return DEFAULT_CLIENT.equals(name);
    }

    /**
     * defaultConfiguration
     */
    @ConfigItem(name = ConfigItem.PARENT)
    public WebClientConfiguration defaultConfiguration;

    /**
     * additionalConfiguration
     */
    @ConfigItem(name = ConfigItem.PARENT)
    public Map<String, WebClientConfiguration> additionalConfiguration;

    public WebClientConfiguration getWebClientConfiguration(String name) {
        return isDefault(name) ? defaultConfiguration : additionalConfiguration.get(name);
    }
}
```

WebClientConfiguration.java
```java
@ConfigGroup
public class WebClientConfiguration {

    /**
     * userAgentEnabled
     */
    @ConfigItem(defaultValue = "false")
    boolean userAgentEnabled;

    /**
     * userAgent
     */
    @ConfigItem
    Optional<String> userAgent;

    /**
     * maxPoolSize
     */
    @ConfigItem(defaultValue = "16")
    int maxPoolSize;

    /**
     * tryUseCompression
     */
    @ConfigItem(defaultValue = "true")
    boolean tryUseCompression;

    /**
     * keepAlive
     */
    @ConfigItem(defaultValue = "true")
    boolean keepAlive;

    /**
     * keepAliveTimeout
     */
    @ConfigItem(defaultValue = "60s")
    Duration keepAliveTimeout;

    /**
     * connectTimeout
     */
    @ConfigItem(defaultValue = "60s")
    Duration connectTimeout;

    /**
     * protocolVersion
     */
    @ConfigItem
    @ConvertWith(HttpVersionConverter.class)
    Optional<HttpVersion> protocolVersion;

    /**
     * maxWaitQueueSize
     */
    @ConfigItem(defaultValue = "-1")
    int maxWaitQueueSize;

    /**
     * followRedirects
     */
    @ConfigItem(defaultValue = "true")
    boolean followRedirects;

    /**
     * tcpNoDelay
     */
    @ConfigItem(defaultValue = "true")
    boolean tcpNoDelay;

    /**
     * tcpFastOpen
     */
    @ConfigItem(defaultValue = "false")
    boolean tcpFastOpen;

    /**
     * tcpKeepAlive
     */
    @ConfigItem(defaultValue = "true")
    boolean tcpKeepAlive;

    /**
     * tcpCork
     */
    @ConfigItem(defaultValue = "false")
    boolean tcpCork;

    /**
     * tcpQuickAck
     */
    @ConfigItem(defaultValue = "false")
    boolean tcpQuickAck;

    /**
     * http2MaxPoolSize
     */
    @ConfigItem(defaultValue = "8")
    int http2MaxPoolSize;

    /**
     * http2KeepAliveTimeout
     */
    @ConfigItem(defaultValue = "60s")
    Duration http2KeepAliveTimeout;

    /**
     * trustAll
     */
    @ConfigItem
    boolean trustAll;

    /**
     * verifyHost
     */
    @ConfigItem
    boolean verifyHost;

    /**
     * proxyConfiguration
     */
    @ConfigItem
    Optional<ProxyConfiguration> proxy;

    public static class HttpVersionConverter implements Converter<HttpVersion> {

        @Override
        public HttpVersion convert(String value) {
            value = value.trim().toUpperCase();
            switch (value) {
                case "HTTP_1_1":
                    return HttpVersion.HTTP_1_1;
                case "HTTP_1_0":
                    return HttpVersion.HTTP_1_0;
                case "HTTP_2":
                    return HttpVersion.HTTP_2;
                default:
                    throw new IllegalArgumentException("Unsupported value [" + value + "] given.");
            }
        }
    }
}
```

ProxyConfiguration.java
```java
@ConfigGroup
public class ProxyConfiguration {

    /**
     * type
     */
//    @DefaultConverter
    @ConvertWith(ProxyTypeConverter.class)
    @ConfigItem
    ProxyType type;

    /**
     * host
     */
    @ConfigItem
    String host;

    /**
     * port
     */
    @ConfigItem
    int port;

    /**
     * username
     */
    @ConfigItem
    Optional<String> username;

    /**
     * password
     */
    @ConfigItem
    Optional<String> password;

    public static class ProxyTypeConverter implements Converter<ProxyType> {

        @Override
        public ProxyType convert(String value) {
            if (value == null || value.isEmpty()) {
                throw new IllegalArgumentException("Proxy type is empty.");
            }
            value = value.trim().toUpperCase();
            switch (value) {
                case "HTTP":
                    return ProxyType.HTTP;
                case "SOCKS5":
                    return ProxyType.SOCKS5;
                case "SOCKS4":
                    return ProxyType.SOCKS4;
                default:
                    throw new IllegalArgumentException("Unsupported value [" + value + "] given.");
            }
        }
    }

}
```

application.properties

```properties 
quarkus.spinach.web.client.proxy.type=HTTP
quarkus.spinach.web.client.proxy.host=127.0.0.1
quarkus.spinach.web.client.proxy.port=1080
quarkus.spinach.web.client.max-pool-size=32
```

### Expected behavior

Proxy parameter is not empty.

### Actual behavior

Proxy parameter is empty.

## To Reproduce

[https://github.com/aomsweet/spinach-quarkus-extension](https://github.com/aomsweet/spinach-quarkus-extension)

1.  mvn clean install
2.  cd app-examples
3.  mvn quarkus:dev
4.  open http://localhost:8080/config

Then you can see: `"proxy":{"value":null,"present":false}`

### Configuration
```properties
# Add your application.properties here, if applicable.

quarkus.spinach.web.client.proxy.type=HTTP
quarkus.spinach.web.client.proxy.host=127.0.0.1
quarkus.spinach.web.client.proxy.port=1080
quarkus.spinach.web.client.max-pool-size=32

```

### Screenshots
![image](https://user-images.githubusercontent.com/70388114/117537118-8ec39300-b031-11eb-9158-bb3c2da8862d.png)

### Output of `java -version`

JDK: 1.8

### GraalVM version (if different from Java)

GraalVM: 21.1.0

### Quarkus version or git rev

Quarkus: 1.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven: 3.8.1

## Additional context
(Add any other context about the problem here.)

**Comment by aomsweet** [comment] 2021-05-19 05:56
Hi. @gwenneg   Are there any new developments?

**Comment by gwenneg** [comment] 2021-05-19 07:23
Hi and sorry for the delay. @radcortez Could you please have a look at this?

**Comment by radcortez** [comment] 2021-05-19 14:59
I'll have a look.

I believe this is a duplicate of https://github.com/quarkusio/quarkus/issues/7862

**Comment by aomsweet** [comment] 2021-07-20 07:52
Hi everybody.

The Quarkus version has been upgraded to 2.0.2.Final. Any updates on this? 

Thanks.

**Comment by radcortez** [comment] 2021-07-20 12:13
Not yet. I'm working right now to support `@ConfigMapping` into extensions. I already have a prototype, but still far from complete. When that is done, I'll reference this issue (and others related).

**Comment by aomsweet** [comment] 2021-07-21 02:01
@radcortez Thanks.  I'm looking forward to the features.

**Comment by nicolas-vivot** [comment] 2021-08-02 05:43
Same here, looking forward to be able to use complex objects with @ConfigMapping & having the optional fixed.

**Closed** 2022-02-22 17:38 UTC
Labels: kind/bug, area/config

**Comment by naah69** [comment] 2022-03-22 09:47
> Not yet. I'm working right now to support `@ConfigMapping` into extensions. I already have a prototype, but still far from complete. When that is done, I'll reference this issue (and others related

not support this?
like this [how-to-write-the-configuration-of-a-list-of-objects-for-a-quarkus-extension](https://stackoverflow.com/questions/68615746/how-to-write-the-configuration-of-a-list-of-objects-for-a-quarkus-extension)

```java
@ConfigRoot
public class NacosConfig {
    @ConfigItem(defaultValue = "true")
    public boolean enabled;

    public List<Config>extConfig;

    @ConfigGroup
    public static class Config {
        @ConfigItem(defaultValue = "127.0.0.1:8848")
        public String serverAddr ;

    }

}

```


error：
```
Caused by: java.lang.IllegalArgumentException: SRCFG00013: No Converter registered for class com.mindflow.config.nacos.config.NacosConfig$Config
	at io.smallrye.config.SmallRyeConfig.requireConverter(SmallRyeConfig.java:464)
	at io.smallrye.config.SmallRyeConfig.getConverter(SmallRyeConfig.java:453)
	at io.quarkus.runtime.generated.Config.<clinit>(Unknown Source)
	... 46 more
```
