### ISSUE TITLE
"Can't get the context safety flag: the current context is not a duplicated context". gRPC + Hibernate

### ISSUE THREAD

**Issue by uPagge** [quarkusio/quarkus#36660] opened 2023-10-24 11:06 UTC
### Describe the bug

We get an exception when we call grpc and then call hibernate panache afterwards.

### Expected behavior

There shouldn't be any problems. Grpc is called, then hibernate is executed, the response is sent to the user.

### Actual behavior

We get the exception: Can't get the context safety flag: the current context is not a duplicated context

### How to Reproduce?

1. A GraphQL query is coming in.
2. A method of the authorization library is called. Which under the hood sends a gRPC request to the authorization service.
3. Then we call the service method that is labeled @WithTransaction or @WithSession, where PanacheRepository is called. A simple read operation is called.

### Output of `java -version`

17.0.5

### Quarkus version or git rev

3.4.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

### Additional information

@SafeVertxContext did not help solve the problem.
We have fixed this problem as follows
```
grpc.request()
.emitOn(MutinyHelper.executor(Vertx.currentContext()))
```

**Comment by yrodiere** [comment] 2023-10-24 11:11
Since you mentioned this:

> `@WithTransaction` or `@WithSession`

I'll assume you're using Hibernate Reactive. I'll adjust the labels accordingly.

CC @DavideD

**Comment by uPagge** [comment] 2023-10-25 07:17
Yeah, that's right.

**Comment by cescoffier** [comment] 2023-10-30 07:01
Can you create a minimal / standalone reproducer?

**Comment by DavideD** [comment] 2023-10-30 08:22
The are some known issues related to GraphQL and Hibernate Reactive: https://github.com/quarkusio/quarkus/issues/32870

Not sure if this is related, though.

**Comment by cescoffier** [comment] 2023-11-06 08:19
I would need a reproducer as gRPC should use a duplicated context.

**Comment by uPagge** [comment] 2023-11-08 07:18
@cescoffier Okay, I'll try to do it this weekend

**Comment by cescoffier** [comment] 2023-11-20 07:12
@uPagge, Were you able to produce a reproducer?

**Comment by geoand** [comment] 2023-12-12 08:06
Closing for lack of a reproducer.

If one does become available, we can reopen the issue

**Closed by geoand** 2023-12-12 08:06 UTC
Labels: kind/bug, area/persistence, area/grpc, area/hibernate-reactive, triage/needs-reproducer

**Comment by temaleva** [comment] 2024-05-03 17:32
I think I know how to reproduce. 
Page size and data amount must be big enough.
I will try it. I have it reproducible  in my production code.
