### ISSUE TITLE
Kafka MutinyEmitter.sendAndAwait sometimes ruins blocking DB transaction. #context-propagation #smallrye-kafka #narayana

### ISSUE THREAD

**Issue by MatejPucihar** [quarkusio/quarkus#39100] opened 2024-03-01 08:56 UTC
### Describe the bug

A very simple reproducer example can be found here:
https://github.com/MatejPucihar/kafka-db-tx
![image](https://github.com/quarkusio/quarkus/assets/20385863/b56f6b05-3955-4c9e-81ba-60569d24ee03)

Scenario: 
- send rest http request (from test, every 1ms, to force exception)
- rest request is handler is a `@Transactional` method, which inserts something in DB and sends something to kafka. It must be blocking send, we want to commit out DB TX only if kafka message is ACKed. 

There is ~1:1000 chance that the handler will fail dramatically:
```
2024-03-01 08:32:55,162 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012094: Commit of action id 0:ffff0a010a48:e441:65e18477:d1d0 invoked while multiple threads active within it.
2024-03-01 08:32:55,163 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012107: CheckedAction::check - atomic action 0:ffff0a010a48:e441:65e18477:d1d0 commiting with 2 threads active!
2024-03-01 08:32:55,163 WARN  [com.arj.ats.jta] (executor-thread-2) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a010a48:e441:65e18477:d1d0, node_name=quarkus, branch_uid=0:ffff0a010a48:e441:65e18477:d1d3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@2ea67dc) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
```

I first saw the exception in quarkus 3.5, when we implemented a feature using it. I decided it is time to solve it now, before we go live :)

I investigated a bit further, placing breakpoints here:
- `/Users/matejpucihar/.m2/repository/org/jboss/narayana/jta/narayana-jta/7.0.0.Final/narayana-jta-7.0.0.Final.jar!/com/arjuna/ats/arjuna/logging/arjunaI18NLogger_$logger.class:693` 
- `com.arjuna.ats.arjuna.coordinator.BasicAction.checkChildren`
![image](https://github.com/quarkusio/quarkus/assets/20385863/c975e3e1-cd2c-406e-b0b5-156c9df0e4fc)
It shows that transaction, that was propagated to kafka-producer-thread is still bound to that thread, after message was ACKED(blocking sendAndAwait). That should not happen?

The exception can be solved using a thread without propagated transaction, e.g. `@ManagedExecutorConfig(cleared = ThreadContext.TRANSACTION)`

I know the concept of `write to kafka, wait for message to be ACKed and then commit DB tx` is weird at best. 
But, still this must be a pretty ugly bug. 

### Expected behavior

Exception should never occur

### Actual behavior

Exception 

### How to Reproduce?

clone https://github.com/MatejPucihar/kafka-db-tx
run `./mvnw test`

### Output of `uname -a` or `ver`

happens on multiple OS/ARCHITECTURES. Linux amd64, Mac M1, K8s cluster... My uname -a outputs Darwin Matejs-MBP-2.medius 23.2.0 Darwin Kernel Version 23.2.0: Wed Nov 15 21:53:18 PST 2023; root:xnu-10002.61.3~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

21.0.2" 2024-01-16

### Quarkus version or git rev

3.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae) Maven home: /Users/matejpucihar/.m2/wrapper/dists/apache-maven-3.9.6-bin/3311e1d4/apache-maven-3.9.6 Java version: 21.0.2, vendor: Oracle Corporation, runtime: /Users/matejpucihar/Library/Java/JavaVirtualMachines/openjdk-21.0.2/Contents/Home Default locale: sl_SI, platform encoding: UTF-8 OS name: "mac os x", version: "14.2.1", arch: "aarch64", family: "mac"

### Additional information

Error is present for at least a few major quarkus versions.

Error can be bypassed with disabled tx propagation to kafka-producer-thread (e.g. `@ManagedExecutorConfig(cleared = ThreadContext.TRANSACTION)`)

**Comment by geoand** [comment] 2024-03-01 09:17
I assume this is a duplicate of https://github.com/quarkusio/quarkus/issues/39098

**Closed by geoand** 2024-03-01 09:17 UTC
Labels: kind/bug, area/smallrye, area/kafka, area/mutiny, area/context-propagation, env/m1
