### ISSUE TITLE
Quarkus produces JAR that fails CRC32 checks

### ISSUE THREAD

**Issue by saturnism** [quarkusio/quarkus#4782] opened 2019-10-23 01:43 UTC
**Describe the bug**
```
# Create a new project
$ mvn io.quarkus:quarkus-maven-plugin:0.26.0:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -DclassName="org.acme.quickstart.GreetingResource" \
    -Dpath="/hello"
$ cd getting-started/

# Produce the JAR
$ ./mvnw package

# App runs fine
$ java -jar target/getting-started-1.0-SNAPSHOT-runner.jar

# There are CRC check errors in the produced JAR
$ unzip -tqql target/getting-started-1.0-SNAPSHOT-runner.jar                                                       ↵ META-INF/services/io.quarkus.arc.ComponentsProvider  bad CRC 55fb23e4  (should be 95e5dbd1)
META-INF/MANIFEST.MF    bad CRC 66911b11  (should be 3569519a)

# Alternative checks:
$ zip -T target/getting-started-1.0-SNAPSHOT-runner.jar
META-INF/services/io.quarkus.arc.ComponentsProvider  bad CRC 55fb23e4  (should be 95e5dbd1)
META-INF/MANIFEST.MF    bad CRC 66911b11  (should be 4f04ef90)
test of target/getting-started-1.0-SNAPSHOT-runner.jar FAILED

$ cd target; jar -xf getting-started-1.0-SNAPSHOT-runner.jar
java.io.IOException: Push back buffer is full
	at java.base/java.io.PushbackInputStream.unread(PushbackInputStream.java:229)
	at java.base/java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:359)
	at java.base/java.util.zip.ZipInputStream.read(ZipInputStream.java:197)
	at java.base/java.util.zip.ZipInputStream.closeEntry(ZipInputStream.java:141)
	at jdk.jartool/sun.tools.jar.Main.extractFile(Main.java:1457)
	at jdk.jartool/sun.tools.jar.Main.extract(Main.java:1364)
	at jdk.jartool/sun.tools.jar.Main.run(Main.java:409)
	at jdk.jartool/sun.tools.jar.Main.main(Main.java:1681)
```

**Expected behavior**
No CRC check errors

**Actual behavior**
CRC check errors for unknown reason.

**To Reproduce**
Steps to reproduce the behavior: See above.

**Configuration**
None

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  Darwin ... 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
```
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (AdoptOpenJDK)(build 1.8.0_222-b10)
OpenJDK 64-Bit Server VM (AdoptOpenJDK)(build 25.222-b10, mixed mode)
```
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 0.26.0?

**Additional context**

`gcloud app deploy` now supports deploying thin JARs. However, this deployment fails w/ "ERROR: gcloud crashed (BadZipfile): Bad CRC-32 for file u'META-INF/MANIFEST.MF'" from Python `zipfile` library.

**Comment by ludoch** [comment] 2019-10-23 01:48
On my Mac system, it works, so might be installation specific...?

**Comment by ludoch** [comment] 2019-10-23 02:28
It seems oraclejdk works and adoptopenjdk failed!!
So adoptopenjdk is not a reliable distro?

**Comment by saturnism** [comment] 2019-10-23 02:29
Interestingly enough:

JAR fails CRC check w/ AdoptOpenJDK 11.0.4.

```
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)
```

CRC check fails w/ Zulu 11.0.5
```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Zulu11.35+13-CA (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Zulu11.35+13-CA (build 11.0.5+10-LTS, mixed mode)
```

CRC check passes w/ Oracle OpenJDK 11.0.2
```
openjdk version "11.0.2" 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
```

CRC check passes w/ all OpenJDK 1.8 that I have on the system (Oracle OpenJDK, AdoptOpenJDK, and Zulu)

**Comment by saturnism** [comment] 2019-10-23 02:34
OpenJDK 13 is also broken:
```
openjdk version "13" 2019-09-17
OpenJDK Runtime Environment AdoptOpenJDK (build 13+33)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 13+33, mixed mode, sharing)
```

**Comment by ludoch** [comment] 2019-10-23 02:41
So maybe move this bug to openjdk itself...

**Comment by jaikiran** [comment] 2019-10-23 09:57
This indeed looks like an issue in recent versions of Java itself. I've been able to narrow this down to a very simple usage which reproduces this. I've opened https://bugs.openjdk.java.net/browse/JDK-8232879 to get inputs from the OpenJDK team. Thank you for reporting this and providing sufficient details for narrowing this down.

**Comment by jaikiran** [comment] 2019-10-23 14:04
A PR containing a workaround in Quarkus has been issued https://github.com/quarkusio/quarkus/pull/4801

**Comment by saturnism** [comment] 2019-10-23 14:21
Thanks for the quick workaround!!

**Comment by gsmet** [comment] 2019-10-23 15:54
Let's close this one. I wouldn't hold my breath on the JDK bug being fixed in all supported versions so I'm pretty sure we will keep the workaround for a while.

**Closed by gsmet** 2019-10-23 15:54 UTC
Labels: bug

**Comment by saturnism** [comment] 2019-10-24 01:26
awesome! looking forward to the 0.27 release.
