### ISSUE TITLE
Microprofile @Timeout annotation is not working for methods with rest-client request processing

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#21860] opened 2021-12-01 16:26 UTC
### Describe the bug

If a method with rest-client request processing inside is marked with @Timeout annotation, long requests are not interrupted with Timeout exception.
The reproducer is attached.

### Expected behavior

Fault tolerance interceptors stop the method execution after a specific timeout.

### How to Reproduce?

[fault-tolerance-reproducer.zip](https://github.com/quarkusio/quarkus/files/7635535/fault-tolerance-reproducer.zip)

1) run TimeoutTest
2) It is not interrupted after a certain timeout

### Quarkus version or git rev

2.5.0.Final

**Comment by OleKsimov** [comment] 2021-12-10 12:45
Hi guys.
I'm just wondering if anyone can validate this issue. 
In our production environment, some network problems happen from time to time. Using microprofile readTimeout/connectTimeout for rest-client doesn't help. I don't know why and don't have permission to make an investigation, so the only way I can handle this situation from the service side is to use this type of fault-tolerance processing. But I suppose something is wrong with it :(

**Comment by TomasHofman** [comment] 2021-12-22 15:15
I can reproduce the issue too.

The resource method annotated with `@Timeout` eventually throws fault tolerance `TimeoutException`, rather than completing successfully, but the rest client call itself doesn't get interrupted and blocks until it eventually receives a response.

**Comment by TomasHofman** [comment] 2021-12-22 15:55
I was looking at the MP rest client spec and it actually contains a note about this:

> The @Timeout annotation presents a problem since some parts of the MP Rest Client request are non-blocking and non-interruptible. Implementations should override the default connect and read timeouts and use the timeout value specified in the @Timeout annotation instead. This will ensure that the actual time spent in blocking/non-interruptible operations should be less than or equal to the time specified in the annotation, allowing the MP Fault Tolerance implementation to interrupt the request and the throw the appropriate TimeoutException.

https://download.eclipse.org/microprofile/microprofile-rest-client-2.0/microprofile-rest-client-spec-2.0.html#_microprofile_fault_tolerance

So it looks Quarkus implementation doesn't set the connect & read timeouts, but as a workaround they could be set manually:

```
test-client/mp-rest/connectTimeout: 1000
test-client/mp-rest/readTimeout: 1000
```

**Comment by OleKsimov** [comment] 2021-12-28 17:23
@TomasHofman 
My exact problem is that readTimeout/connectTimeout doesn't interrupt a rest-client connection as well. So the connection just hangs there until it is closed with https (if I remember it right) session timeout in 1 hour. I fix this behavior by running a rest-client connection in a different thread using CompletionStage for response and adding a timeout for this future.

**Comment by TomasHofman** [comment] 2022-01-03 13:10
@OleKsimov I'm not able to reproduce that issue.

I'm testing with two separate apps, the first app serves a resource that takes 10 seconds to respond:

```
    @GET
    @Path("/endpoint")
    @Produces(MediaType.TEXT_PLAIN)
    public Response endpoint() {
        log.info("Going to sleep");
        try {
            Thread.sleep(10000);
        } catch (Exception ex) {}
        log.info("Woke up");
        return Response.ok().entity("Hi!").build();
    }
```

The second app, based on your reproducer, uses rest client to connect to the first one:

```
    @Inject
    @RestClient
    TestClient testClient;

    @GET
    @Consumes(MediaType.TEXT_PLAIN)
    @Produces(MediaType.TEXT_PLAIN)
//    @Timeout(1000)
    @Path("/timeout")
    public Response checkTimeout() {
        log.info("Calling rest client");
        testClient.sendEndlessRequest();
        log.info("Rest client request processing finished");
        return Response.ok().entity("OK!").build();
    }
```

application.yml:

```
test-client/mp-rest/url: http://localhost:8081/

test-client/mp-rest/connectTimeout: 1000
test-client/mp-rest/readTimeout: 1000
```

The rest client connections timeouts after one second with `java.net.SocketTimeoutException: Read timed out`. It doesn't wait for the first resource to respond (10 secs).

I tested both with 2.5.0 and with current main.

**Comment by OleKsimov** [comment] 2022-01-03 18:39
@TomasHofman 
Well, there are no such lines in my reproducer in application.yaml files:
_test-client/mp-rest/connectTimeout: 1000
test-client/mp-rest/readTimeout: 1000_

Please try to run the test itself in the attached reproducer "as is" and check the behaviour. @Timeout annotation doesn't interrupt running test after specified timeout.
And even for your case it's working not quite right, because according to Microprofile documentation:

> Implementations should override the default connect and read timeouts and use the timeout value specified in the @Timeout annotation instead.

so if you specify 1000ms value for @Timeout annotation and 5000ms for readTimeout/connectTimeout in application.yaml, it should be interrupted after 1000ms not 5000ms.

**Comment by TomasHofman** [comment] 2022-01-04 09:09
Yes, I was referring to your sentence:

> My exact problem is that readTimeout/connectTimeout doesn't interrupt a rest-client connection as well.

because in my experiments readTimeout does interrupt an unresponsive rest client connection.

I agree that the readTimeout and callTimeout attributes are not set by Quarkus automatically when `@Timeout` is configured, as the spec says it should, but setting readTimeout/connectTimeout manually can be used as a workaround.

**Comment by Ladicek** [comment] 2022-01-17 13:51
I took a look and observe the same behavior as @TomasHofman: when I explicitly configure `test-client/mp-rest/connectTimeout` and `test-client/mp-rest/readTimeout`, the test works as expected.

Also, the reproducer here uses RESTEasy classic. I tried using RESTEasy Reactive and with that, explicitly configuring the additional timeouts is not required. (RestClient Reactive probably reads the `@Timeout` annotation as specified, but I didn't check.)

I'd also like to note that the MicroProfile Fault Tolerance specification [explicitly mentions](https://download.eclipse.org/microprofile/microprofile-fault-tolerance-3.0/microprofile-fault-tolerance-spec-3.0.html#timeout) that in case of a synchronous execution that doesn't respond to interrupts, `@Timeout` can't possibly work. So that's expected.

**Comment by alessandroAmedei** [comment] 2022-05-06 22:59
Any update? I have the same problem.
I have a class with 
`@RegisterRestClient`
and a method
`    @GET
    @Path("/codes/{code}")
    @Timeout(250)
    Unit find(@PathParam("code") String code);`

Anyway, the timeout is not working.

**Comment by michalszynkiewicz** [comment] 2022-05-07 12:48
@alessandroAmedei can you create a reproducer for your problem?

**Comment by pcaceresf** [comment] 2022-11-17 15:48
i have the same problem, but my solution  its no using more quarkus until really mature System. 
Bye quarkus

**Comment by geoand** [comment] 2023-01-27 10:05
Unless we get a sample application showing the problem, we'll close this soon.

**Comment by bh-tt** [comment] 2023-04-06 11:42
An easy way to make this work is to use the quarkus-rest-client-reactive, as that should not do any blocking IO. A simple test for me caused a call made from a default javax.ws.rs.ClientBuilder.newClient() to a slow webservice to stop after the given timeout.

**Comment by geoand** [comment] 2023-04-10 12:15
Closing as per the comments above

**Closed by geoand** 2023-04-10 12:15 UTC
Labels: kind/bug, area/rest-client, area/fault-tolerance, triage/needs-reproducer
