### ISSUE TITLE
Single project to mutl project gets NPE at UnixPath.normalizeAndCheck ad 404 when hit the endpoints

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6168] opened 2019-12-13 20:27 UTC
**Describe the bug**

**UPDATE:**  it is on 1.0.1 final

Used to have working quarkus web project with rest-easy end-points.

Converted it to multi-module one.

**Expected behavior**
all up and running and - responding by the hitting the url endpoints.

**Actual behavior**

Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:70)
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)

and 404 on hitting the endpoint.

**To Reproduce**
1.
 my-project-service
   - my-project-api
     - data-api-object.java
     - pom.xml // dep on `quarkus-core` as `provided`
   - my-project-backend
     - pom.xml  + depends on my-project-api
   - pom.xml

2.
./mvnw compile quarkus:dev

3.
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:70)
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)

4.
- [io.quarkus] (main) Quarkus 1.0.1.Final started in 1.595s. Listening on: http://0.0.0.0:8080
- [io.quarkus] (main) Installed features: [agroal, cdi, infinispan-client, jaeger, narayana-jta, reactive-pg-client, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-metrics, smallrye-openapi, smallrye-opentracing, swagger-ui, vertx]

**Configuration**
```properties

n my-project-backend / ... / resources/application.properties

quarkus.application.name=my-project-service
quarkus.http.root-path=/my-project-service

```

**Additional context**
Related question: https://stackoverflow.com/questions/59328770/quarkus-project-once-covered-to-mutli-module-form-got-404-when-hit-the-existing

And potentially related previous fixed related issue: https://github.com/quarkusio/quarkus/commit/bc1ffba31f9979b4b60f2bcb6a122a6298649744

**Comment by gsmet** [comment] 2019-12-13 21:01
Could you please provide a reproducer?

Thanks.

**Comment by Sergey80** [comment] 2019-12-13 22:55
Ok. will prep. You do not have any official mult-module project yourself yet?

one more info: 
 If I compile native, application works/reacts on rest requests. Seems it is only about dev (and probably hot reload thing).

**Comment by Sergey80** [comment] 2019-12-13 23:45
https://github.com/Sergey80/quarkus-samples

**Comment by jaikiran** [comment] 2019-12-14 01:38
Hello @Sergey80, Is this 1.1.0.CR1? That NPE line number doesn't match with what's in the code.

**Comment by Sergey80** [comment] 2019-12-14 01:58
No it's 1.0.1 final.  The 1.1.0 rc1 I even  could not start, as I mentioned in stackoverflow. I can try this reproducer with the q.1.0rc.

**Comment by Sergey80** [comment] 2019-12-14 02:07
yes, if you change version to 1.1.0.CR1

on start you would get:

Listening for transport dt_socket at address: 5005
21:06:03,415 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url"
	at io.quarkus.deployment.configuration.matching.PatternMapBuilder.addMember(PatternMapBuilder.java:70)

**Comment by geoand** [comment] 2019-12-14 09:04
The not being able to start issue (#6170) was due to having multiple data sources. Can you please try again with 1.1.0.CR1 after removing the datasource you don't need?

**Comment by Sergey80** [comment] 2019-12-14 13:47
(#6170)  is closed. but this one should not be. this one is about ability to run the app in multi-module mode. when it starts - the endpoints are not available and the exception is:

Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:71)
Caused by: java.lang.NullPointerException
        at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)


on ./mvnw compile quarkus:dev

**Comment by geoand** [comment] 2019-12-14 13:49
I have not able to reproduce this one. Can you give more information about your environment (Java version, OS, etc) please ?

**Comment by jaikiran** [comment] 2019-12-14 13:49
Hello @Sergey80, can you please post the complete exception stacktrace? I have been trying to reproduce the linked github repo application, but haven't been able to.

**Comment by Sergey80** [comment] 2019-12-14 14:01
./mvnw compile quarkus:dev
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO] 
[INFO] my-project-service                                                 [pom]
[INFO] my-project-api2                                                    [jar]
[INFO] my-project-backend                                                 [jar]
[INFO] 
[INFO] ---------------< my.project.subject:my-project-service >----------------
[INFO] Building my-project-service 1.0.0                                  [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:1.1.0.CR1:dev (default-cli) @ my-project-service ---
[INFO] Launching JVM with command line: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/sergii/projects/quarkus/rep/target/my-project-service-dev.jar
Listening for transport dt_socket at address: 5005
Exception in thread "main" java.lang.RuntimeException: java.lang.NullPointerException
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:71)
Caused by: java.lang.NullPointerException
	at sun.nio.fs.UnixPath.normalizeAndCheck(UnixPath.java:77)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:71)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:281)
	at java.nio.file.Paths.get(Paths.java:84)
	at io.quarkus.dev.RuntimeUpdatesProcessor.checkForFileChange(RuntimeUpdatesProcessor.java:306)
	at io.quarkus.dev.DevModeMain.start(DevModeMain.java:91)
	at io.quarkus.dev.DevModeMain.main(DevModeMain.java:67)
[INFO] 
[INFO] -----------------< my.project.subject:my-project-api2 >-----------------
[INFO] Building my-project-api2 1.0.0                                     [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ my-project-api2 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] 
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ my-project-api2 ---
[INFO] Nothing to compile - all classes are up to date
[INFO] 
[INFO] --- quarkus-maven-plugin:1.1.0.CR1:dev (default-cli) @ my-project-api2 ---
[INFO] Launching JVM with command line: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /home/sergii/projects/quarkus/rep/my-project-api2/target/my-project-api2-dev.jar
Listening for transport dt_socket at address: 5005
2019-12-14 08:59:48,434 WARN  [io.qua.jae.run.JaegerDeploymentRecorder] (main) Jaeger service name has not been defined, either as 'quarkus.jaeger.service-name' application property or JAEGER_SERVICE_NAME environment variable/system property
2019-12-14 08:59:48,658 INFO  [io.quarkus] (main) Quarkus 1.1.0.CR1 started in 1.596s. Listening on: http://0.0.0.0:8080
2019-12-14 08:59:48,659 INFO  [io.quarkus] (main) Profile dev activated. Live Coding activated.
2019-12-14 08:59:48,660 INFO  [io.quarkus] (main) Installed features: [cdi, infinispan-client, jaeger, reactive-pg-client, rest-client, resteasy, resteasy-jackson, smallrye-context-propagation, smallrye-fault-tolerance, smallrye-health, smallrye-openapi, smallrye-opentracing, swagger-ui, vertx]

**Comment by geoand** [comment] 2019-12-14 14:17
First of, I can't seem to reproduce the NPE at all.

Secondly the dev mode doesn't seem to be working when executed from the parent directory, but I'm not sure if that's expected or not (@gsmet any idea?). When I launch it from the the `my-project-backend` is works just fine.

**Comment by Sergey80** [comment] 2019-12-14 14:34
@geoand  strange, for me it is:
```
:~/projects/quarkus/rep/my-project-backend$ mvn compile quarkus:dev
[INFO] Scanning for projects...
[INFO] 
[INFO] ---------------< my.project.subject:my-project-backend >----------------
[INFO] Building my-project-backend 1.0.0
[INFO] --------------------------------[ jar ]---------------------------------
Downloading from central: https://repo.maven.apache.org/maven2/my/project/subject/my-project-api2/1.0.0/my-project-api2-1.0.0.pom
[WARNING] The POM for my.project.subject:my-project-api2:jar:1.0.0 is missing, no dependency information available
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.442 s
[INFO] Finished at: 2019-12-14T09:32:56-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project my-project-backend: Could not resolve dependencies for project my.project.subject:my-project-backend:jar:1.0.0: Failure to find my.project.subject:my-project-api2:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```

**Comment by geoand** [comment] 2019-12-14 14:36
@Sergey80 you first need to do `./mvnw clean install -DskipTests` in the parent project.

Now like I said I'm not sure if the dev mode is supposed to work in the parent project. If it is, then there is definitely a bug, because although I can't reproduce your NPE, the application doesn't behave correctly.

**Comment by Sergey80** [comment] 2019-12-14 16:16
also not sure how to build it as native. from the parent of from the the child. in both cases this seems does not work too. 

If I run this single module project:
`./mvnw package -Dnative -Dquarkus.profile=dev -Dmaven.test.skip=true`
I wait for a minute or so and get my binnary -runner

In case of of multi-module one, either I run it from the parent of child, I got something like this msg in 2 seconds:

```
[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building thin jar: /home/sergii/projects/quarkus/rep/my-project-backend/target/my-project-backend-1.0.0-runner.jar
[INFO] [io.quarkus.deployment.QuarkusAugmentor] Quarkus augmentation completed in 2081ms
```

**Comment by Postremus** [comment] 2020-02-06 07:26
@Sergey80 could you please retry with current master? I can't reproduce this one anymore with your reproducer.

**Comment by llowinge** [comment] 2020-05-15 10:49
@Postremus Please check this comment - https://github.com/apache/camel-quarkus/issues/1223#issuecomment-629075660 where i've described why it gave me NPE.

**Comment by cescoffier** [comment] 2021-01-11 07:03
Closing it - See the https://github.com/apache/camel-quarkus/issues/1223 for details.

**Closed by cescoffier** 2021-01-11 07:03 UTC
Labels: kind/bug
