### ISSUE TITLE
Micrometer for http requests: URI templating not working with interfaces

### ISSUE THREAD

**Issue by baiglin** [quarkusio/quarkus#21034] opened 2021-10-27 09:20 UTC
### Describe the bug

Hello, 

While integrating Micrometer into our application, checking the http metrics and more specifically the URI, I could see that in some case it was not templatized.
It seems to come from the fact that we used in some case an API instead of annotating the class directly and in this case it seems the @Path annotation is not used to resolve the template URI.

Best Regards

### Expected behavior

Have a tag with the template URI instead of the whole URI

### Actual behavior

Full URI is set as metric tag. 

### How to Reproduce?

[micrometer_reproducer.zip](https://github.com/quarkusio/quarkus/files/7424843/micrometer_reproducer.zip)

This is a small reproducer that contains the two versions of a dummy resource, one usin an API, the other no to highlight the difference.

**Comment by imjuoy** [comment] 2022-04-24 21:57
What is the current status of resolving this issue? This issue is affecting us for now, since we use micrometer for metrics and are getting WARNING's regarding "number of tags for http.server.requests". 
Should we be moving ahead with setting match-patter properties as mentioned below:
https://github.com/tomekl007/nessie/blob/be4e348f4b1b4e12453912cb594a4781dc73a5d6/servers/quarkus-server/src/main/resources/application.properties#L173

**Comment by ebullient** [comment] 2022-04-25 02:37
You should set the match pattern as that gets you out of trouble right now, there are some things I'm waiting for to fix this issue, but the match pattern will continue to work regardless (at some future point, you may not need it, but it will work, so.. )

**Comment by imjuoy** [comment] 2022-04-25 18:28
@ebullient Thanks for the confirmation.
I have a question regarding having multiple path parameters.
Everywhere I refer for examples of configurations, it's mostly just one path param. For example:

- https://quarkus.io/guides/all-config#quarkus-micrometer_quarkus.micrometer.binder.http-server.match-patterns

- https://github.com/tomekl007/nessie/blob/be4e348f4b1b4e12453912cb594a4781dc73a5d6/servers/quarkus-server/src/main/resources/application.properties#L173

In our case, the application has three path parameters. Let's say:
/v1/api/<param1>/<param2>/<param3>

Param2 has limited set of values and will never lead to high cardinality situations.
Is it possible to just record param2 and keep param1 and param3 templatized?

**Comment by ebullient** [comment] 2022-04-25 18:48
At the moment, no. I was making some tradeoffs re: cost because this comparison is done with every request measurement.

I could add an option to use replaceAll rather than flat assignment...

**Comment by imjuoy** [comment] 2022-04-25 19:17
Can you please elaborate what you meant by : 
"I could add an option to use replaceAll rather than flat assignment..."

**Comment by ebullient** [comment] 2022-04-25 19:23
https://github.com/quarkusio/quarkus/blob/5eb3169668af46140ccd8992ec8a81dc61edb893/extensions/micrometer/runtime/src/main/java/io/quarkus/micrometer/runtime/binder/RequestMetricInfo.java#L59

From there. I just assign the match pattern value at the moment, but the pattern is a proper regex, I could allow use of replaceAll as well

**Comment by imjuoy** [comment] 2022-04-26 05:57
I want to make sure, that I have explained the problem correctly.
So given that I have three path params, param1, param2, param3,
I want to write a regex such that : 
/v1/api/<regex>=/v1/api/{param1}/value/{param3}

**Comment by rkorver** [comment] 2023-12-21 10:03
When will there be a proper solution to the problem that micrometer doesn't properly recognize http request uri's? Thanks in advance!

**Comment by geoand** [comment] 2024-09-20 10:50
Is this still an issue? If it is, can someone attach a reproduce that uses the latest version of Quarkus so I can look into it?

Thanks

**Comment by geoand** [comment] 2024-10-02 07:43
Closing for lack of feedback

**Closed by geoand** 2024-10-02 07:43 UTC
Labels: kind/bug, area/metrics, triage/needs-feedback
