### ISSUE TITLE
(Docs?) datasource max-size not honoured

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#10543] opened 2020-07-08 00:40 UTC
**Describe the bug**
This could be an issue with docs rather than code but might be both.

`quarkus.datasource.jdbc.max-size=50` does not work - starves after hitting the default 20.  Most docs refer to this (https://quarkus.io/guides/datasource, https://quarkus.io/guides/datasource#jdbc-configuration).

`quarkus.datasource.max-size=50` does work.  Few docs refer to this.  The one that does (https://quarkus.io/guides/all-config#quarkus-datasource_quarkus.datasource.max-size) looks broken (no description, no min-size et al).

Historical issues imply `quarkus.datasource.max-size` may be legacy and `quarkus.datasource.jdbc.max-size` is new.  But the new version has no impact.

Given:

`quarkus.datasource.driver=org.postgresql.Driver`
`quarkus.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/redacted?currentSchema= redacted`
`quarkus.datasource.username=${DB_USER}`
`quarkus.datasource.password=${DB_PASSWORD}`
`quarkus.datasource.jdbc.min-size=0`
`quarkus.datasource.jdbc.max-size=50`
`quarkus.datasource.jdbc.idle-removal-interval=1M`

The last 3 have no impact.

**Comment by jimbogithub** [comment] 2020-07-08 01:21
Broken when support for multiple datasources was added?

**Comment by geoand** [comment] 2020-07-08 05:51
cc @gsmet

**Comment by gsmet** [comment] 2020-07-08 08:07
Well, I don't want to be too vocal about the legacy stuff because it might confuse people even more.

I don't know if it's worth complicating the logic to detect this sort of things. I'm worried it will become a big pile of mess.

**Comment by machi1990** [comment] 2020-07-08 08:11
> I don't know if it's worth complicating the logic to detect this sort of things. I'm worried it will become a big pile of mess.

+1. As far as I recall the legacy stuffs are deprecated, we should advocate users to using the new config knobs and probably remove the old way soon enough.

**Comment by gsmet** [comment] 2020-07-08 08:18
Yeah, I think the issue is when they migrate some old config and don't do it fully.

**Comment by jimbogithub** [comment] 2020-07-08 23:33
I was migrating from Thorntail so its `datasource...` settings probably made me fall into the legacy scheme.
So 👍 for removing support for it.  The conversion is easy if you know you need to ;-).  The silent ignoring of `max-size` caused us issues in Prod.  Better to get complaints about the former than the latter.

**Comment by gsmet** [comment] 2024-02-15 10:38
The legacy config is long gone so we can close this one.

**Closed by gsmet** 2024-02-15 10:38 UTC
Labels: kind/bug
