### ISSUE TITLE
@Valid and @RolesAllowed conflict since 1.0.0.CR2

### ISSUE THREAD

**Issue by Xendar** [quarkusio/quarkus#5763] opened 2019-11-26 10:22 UTC
**Describe the bug**
Adding the @Valid annotation to a parameter of a REST endpoint annotated with @RolesAllowed or @DenyAll will make the authentication to be bypassed.

**Expected behavior**
HTTP 401 should be thrown.

**Actual behavior**
The resource is executed.

**To Reproduce**
I have created a minimal reproducer for the issue with unit tests: https://github.com/Xendar/quarkus-validation-security-reproducer
Just clone it and launch a Maven test. You will get 3 tests failing (the ones with the @Valid annotation).
If you change the version to `1.0.0.CR1` then the tests are successful. The tests are failing too with `1.0.0.Final`.

**Additional context**
I would be happy to be able to try to debug it, but I have no idea about where to start... Any code entry point would be great :)

**Comment by ia3andy** [comment] 2019-11-26 10:26
Moving this issue to Quarkus main repo as this issue is related to it.

**Comment by vc-void** [comment] 2019-11-26 10:57
I can confirm this. After updating quarkus version to  ``1.0.0.Final`` I started having a lot of ClassCastExceptions due to unauthorized roles accessing endpoints that they shouldn't.

**Comment by ia3andy** [comment] 2019-11-26 11:06
@gsmet any thought?

**Comment by Xendar** [comment] 2019-11-26 11:40
> I can confirm this. After updating quarkus version to `1.0.0.Final` I started having a lot of ClassCastExceptions due to unauthorized roles accessing endpoints that they shouldn't. After removing the @Valid annotation the issue was fixed.

This is indeed what I saw, without @Valid everything seems fine. But it would be a shame to not be able to benefit from the annotation's goodness :(

**Comment by brunohorta82** [comment] 2019-11-26 12:18
if I use any Annotation from javax.validation.* the filter https://github.com/smallrye/smallrye-jwt/blob/master/implementation/src/main/java/io/smallrye/jwt/auth/jaxrs/RolesAllowedFilter.java#L37
Not Runs 
you can try with @NotNull, @Valid or @NotEmpty

**Closed** 2019-11-27 20:52 UTC

**Comment by gsmet** [comment] 2019-11-27 20:53
We will release 1.0.1.Final tomorrow to address this issue.

Thanks for taking the time to report it with a test case.

**Comment by gsmet** [comment] 2019-11-28 12:46
1.0.1.Final has been released. Thanks again for reaching out and providing the reproducer.

**Comment by Xendar** [comment] 2019-11-28 13:10
> 
> 
> 1.0.1.Final has been released. Thanks again for reaching out and providing the reproducer.

Thanks Guillaume for your reactivity and the provided fix (validated from my end too)!
You're welcome (for the reproducer) :)
