### ISSUE TITLE
AdditionalJpaOperations doest not work properly with multiple PersistenceUnits

### ISSUE THREAD

**Issue by cmuramoto** [quarkusio/quarkus#24128] opened 2022-03-05 21:28 UTC
### Describe the bug

The problem I'm having is kind of similar to #24075, but I'm opening a separate issue because the scenario is a bit different and involves multiple persistent units.

I managed to make SpringRepositories work with multiple PU's by creating a bean to initialize [AbstractJpaOperations::entityToPersistenceUnit](https://github.com/quarkusio/quarkus/blob/2fa974bd2e4d63e0209155f8cb9ced0544e1f4df/extensions/panache/hibernate-orm-panache-common/runtime/src/main/java/io/quarkus/hibernate/orm/panache/common/runtime/AbstractJpaOperations.java#L30), in order to create the necessary mappings:

```java
@Singleton
public class MultiPUBootstrapper {

	public void onEvent(@Observes StartupEvent ev) {
		var descs = PersistenceUnitsHolder.getPersistenceUnitDescriptors();

		var map = new HashMap<String, String>();

		descs.forEach(desc -> {
			var name = desc.getName();
			var types = desc.getManagedClassNames();

			for (var type : types) {
				map.put(type, name);
			}
		});

		AbstractJpaOperations.setEntityToPersistenceUnit(map);
	}
}
```

With this setup, I can configure multiple named persistence units, and spring JPA repositories work (almost) flawlessly. E.g., with this config

```
quarkus.datasource."one".db-kind = h2
quarkus.datasource."one".username = sa
quarkus.datasource."one".password = 
quarkus.datasource."one".jdbc.url = jdbc:h2:mem:one;DB_CLOSE_DELAY=-1

quarkus.datasource."two".db-kind = h2
quarkus.datasource."two".username = sa
quarkus.datasource."two".password = 
quarkus.datasource."two".jdbc.url = jdbc:h2:mem:two;DB_CLOSE_DELAY=-1

quarkus.hibernate-orm."one".dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm."one".datasource=one 
quarkus.hibernate-orm."one".packages=pkg.one
quarkus.hibernate-orm."one".database.generation=drop-and-create

quarkus.hibernate-orm."two".dialect=org.hibernate.dialect.H2Dialect
quarkus.hibernate-orm."two".datasource=two
quarkus.hibernate-orm."two".packages=pkg.two
quarkus.hibernate-orm."two".database.generation=drop-and-create
```

repositories are correctly injected and resolved to their appropriate PU's:

```java
@QuarkusTest
public class TestTwoPUs {

	@Inject
	RepositoryOne ones;

	@Inject
	RepositoryTwo twos;
	
	@Test
	public void will_save_one_and_two() {
		assertEquals(0, ones.count());
		assertEquals(0, twos.count());

		ones.save(new EntityOne());
		
		assertEquals(1, ones.count());
		assertEquals(0, twos.count());
		
		twos.save(new EntityTwo());
		
		assertEquals(1, ones.count());
		assertEquals(1, twos.count());
	}	
}
```

Operations declared [AdditionalJpaOperations](https://github.com/quarkusio/quarkus/blob/2fa974bd2e4d63e0209155f8cb9ced0544e1f4df/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/AdditionalJpaOperations.java), e.g., [deletAllWithCascade](https://github.com/quarkusio/quarkus/blob/2fa974bd2e4d63e0209155f8cb9ced0544e1f4df/extensions/panache/hibernate-orm-panache/runtime/src/main/java/io/quarkus/hibernate/orm/panache/runtime/AdditionalJpaOperations.java#L57) don't use the type info to resolve the associated EntityManger and when running with multiple PU's the code throws

```
java.lang.IllegalStateException: The default datasource has not been properly configured. See https://quarkus.io/guides/datasource#jdbc-datasource for information on how to do that.
```

The lack of multi-PU support breaks standard Repository methods like **deleteAll** and custom user methods with @Query. 

I believe this can easily be fixed simply by replacing 

```
EntityManager em = jpaOperations.getEntityManager();
```

with

```
EntityManager em = jpaOperations.getEntityManager(type);
```

in AdditionalJpaOperations.

### Expected behavior

Methods from AdditionalJpaOperations should work with multiple named PU's, like those declared in AbstractJpaOperations.

### Actual behavior

Methods are not multiple-PU aware and demand a default persistent unit configured, otherwise, an exception is thrown.

The exception thrown is also misleading. Even with a default PU configured, the code would propagate operations to a wrong EntityManager instance for entities not related to the default PU.

### How to Reproduce?

Steps to reproduce:

1. Create two packages (pkg.one and pkg.two)
2. Create one entity in each package, e.g.,

```
package pkg.one;

public class EntityOne { 

        @Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	protected Integer id;

	// other fields, etc
}

package pkg.two;

public class EntityTwo { 

        @Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	protected Integer id;
}
```

3. Create the repository interfaces:

```
package repos.one;

@Repository
public interface RepoOne extends PagingAndSortingRepository<EntityOne, Integer> { 

}

package repos.two;

@Repository
public interface RepoOne extends PagingAndSortingRepository<EntityTwo, Integer> { 

}
```

4. Create a configuration file with two PU's like in the bug description
5. Create a MultiPUBootstraper like in the bug description

### Output of `uname -a` or `ver`

Linux gtr 5.4.0-65-generic #73-Ubuntu SMP Mon Jan 18 17:25:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18

### GraalVM version (if different from Java)

GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05)

### Quarkus version or git rev

2.7.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by geoand** [comment] 2022-03-06 14:30
This class is actually an internal class, so not meant to be used by application code.

I'll close this, because as you mentioned the issue is pretty much the same as #24075

**Closed** 2022-03-06 14:31 UTC
Labels: kind/bug, triage/duplicate, area/panache, area/spring
