### ISSUE TITLE
Error injecting RestClient after upgrade to Quarkus 1.13.2

### ISSUE THREAD

**Issue by wojciechkopciewicz** [quarkusio/quarkus#17287] opened 2021-05-17 13:42 UTC
## Describe the bug
Starting with Quarkus 1.12.2 (not seen in 1.12.1, seen in 1.13.2 and 1.13.3) we see the following error for some time after application startup:

```
SLF4J: Failed toString() invocation on an object of type [com.sample.clients.SampleClient_ClientProxy]
Reported exception:
java.lang.RuntimeException: Error injecting com.sample.clients.sample.ISampleRestClient com.sample.clients.SampleClient.sampleRestClient
        at com.sample.clients.SampleClient_Bean.create(sampleClient_Bean.zig:338)
        at com.sample.clients.SampleClient_Bean.create(sampleClient_Bean.zig:447)
        at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:96)
        at io.quarkus.arc.impl.AbstractSharedContext.access$000(AbstractSharedContext.java:14)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:29)
        at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:26)
        at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
        at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
        at com.sample.clients.SampleClient_ClientProxy.arc$delegate(sampleClient_ClientProxy.zig:67)
        at com.sample.clients.SampleClient_ClientProxy.toString(sampleClient_ClientProxy.zig:153)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
        at ch.qos.logback.classic.spi.LoggingEvent.getFormattedMessage(LoggingEvent.java:293)
        at ch.qos.logback.classic.spi.LoggingEvent.prepareForDeferredProcessing(LoggingEvent.java:206)
        at ch.qos.logback.core.OutputStreamAppender.subAppend(OutputStreamAppender.java:223)
        at ch.qos.logback.core.OutputStreamAppender.append(OutputStreamAppender.java:102)
        at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)
        at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)
        at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)
        at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)
        at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)
        at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)
        at ch.qos.logback.classic.Logger.error(Logger.java:534)
        at com.sample.services.SampleService.sampleMethod(SampleService.java:127)
        at com.sample.services.SampleService.lambda$scheduledActionTask$2(SampleService.java:99)
        at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
        at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
        at java.base/java.util.HashMap$EntrySpliterator.forEachRemaining(HashMap.java:1746)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
        at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
        at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'com.sample.clients.sample.ICallRestClient/mp-rest/url' or 'com.sample.clients.sample.ICallRestClient/mp-rest/uri' to your Quarkus configuration
ing 'com.sample.clients.sample.ICallRestClient/mp-rest/url' or 'com.sample.clients.sample.ICallRestClient/mp-rest/uri' to your Quarkus configuration
```

### Expected behavior
Rest clients should be injected properly.

### Actual behavior
Looks like clients settings from application.properties are not available for some time.

## To Reproduce
Wait until periodic task runs and tries to use previously saved reference to instance of the class using rest client.

### Configuration
```properties
# Add your application.properties here, if applicable.

com.sample.clients.sample.ISampleRestClient/mp-rest/url=${TEST_URL}
com.sample.clients.sample.ISampleRestClient/mp-rest/connectTimeout=15000
com.sample.clients.sample.ISampleRestClient/mp-rest/readTimeout=15000

```

## Environment (please complete the following information):
The attached archive contains a sample application reflecting the logic and structure of the failing part of actual application - the simplest one with which issue could be reproduced (in the actual application).
However, for some reason, with the sample app this issue could not be reproduced.
[getting-started-injection.tar.gz](https://github.com/quarkusio/quarkus/files/6494148/getting-started-injection.tar.gz)

### Output of `uname -a` or `ver`
Distroless java used: gcr.io/distroless/java-debian10:11

### Quarkus version or git rev
1.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
/usr/bin/mvn -version
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/share/apache-maven-3.8.1
Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /usr/lib/jvm/adoptopenjdk-11-hotspot-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-1113-azure", arch: "amd64", family: "unix"

**Comment by geoand** [comment] 2021-05-18 08:54
I was not able to reproduce the problem. Is there anything specific we need to do @wojciechkopciewicz ?

**Comment by wojciechkopciewicz** [comment] 2021-05-20 13:30
@geoand the problem with this issue is that I can easily reproduce it with our application, which is much more complex than the sample I provided but for some reason I cannot reproduce it with the sample code. The latter mimics the failing part of the application. I am currently trying to strip the actual application down to be able to provide a better sample.

**Comment by wojciechkopciewicz** [comment] 2021-06-14 09:29
@geoand I managed to find a missing piece - attached an updated sample application that allows to reproduce the issue. I can reproduce the issue using docker. I could not reproduce it in the tests or running app on my Windows machine.
[getting-started-injection.tar.gz](https://github.com/quarkusio/quarkus/files/6646579/getting-started-injection.tar.gz)

**Comment by wojciechkopciewicz** [comment] 2021-06-14 12:36
One more observation - the issue is not there when **clientsMap.entrySet().stream().parallel().forEach** is changed to **clientsMap.entrySet().stream().forEach**.

**Comment by geoand** [comment] 2021-06-14 15:26
> @geoand I managed to find a missing piece - attached an updated sample application that allows to reproduce the issue. I can reproduce the issue using docker. I could not reproduce it in the tests or running app on my Windows machine.
> [getting-started-injection.tar.gz](https://github.com/quarkusio/quarkus/files/6646579/getting-started-injection.tar.gz)

Thanks!

What are the steps you are following?

A simple `mvn package` followed `java -jar target/quarkus-app/quarkus-run.jar` does not reproduce the issue for me

**Comment by wojciechkopciewicz** [comment] 2021-06-15 10:00
I can only reproduce it in a docker. I use the following commands:
```mvn clean install```
```docker build -f src\main\docker\Dockerfile.jvm -t injectionsample .```
```docker run injectionsample```

**Comment by geoand** [comment] 2021-06-15 10:11
Indeed with the instruction above I can also reproduce it.

@michalszynkiewicz one more for the TODO list :)

**Comment by michalszynkiewicz** [comment] 2021-06-16 15:39
The only thing that comes to my mind after looking at the code is that the TCCL for the call is wrong...

**Comment by michalszynkiewicz** [comment] 2021-06-16 15:47
The `Thread.currentThread().getContextClassloader()` has to contain the Quarkus class loader to have it working, I'm 99% sure ;)

Now, why doesn't `stream().parallel()` use the classloader of the thread that invoked it, I don't know

**Comment by michalszynkiewicz** [comment] 2021-06-16 15:53
After a bit of reading, the issue, at least with the latest reproducer, is that ForkJoinPools don't preserve the context classloader.

A workaround for this is to set this context explicitly in your code, sth like:
```
 ClassLoader cl = Thread.currentThread().getContextClassLoader();
        clientsMap.entrySet().stream().parallel().forEach((c) -> {
            Thread.currentThread().setContextClassLoader(cl);
            ...
          }
```

Or provide a custom fork join worker thread factory that would propagate the classloader.

I don't think there's anything we can do for this on the Quarkus side.

**Comment by michalszynkiewicz** [comment] 2021-06-16 16:21
I will close this issue, but feel free to reopen it if there's something I missed

**Closed by michalszynkiewicz** 2021-06-16 16:21 UTC
Labels: area/rest-client, kind/bug

**Comment by Ladicek** [comment] 2021-06-17 06:42
It seems people stumble upon this relatively often (see also #9397 and #7123).

There is a hack in Quarkus that attempts to set the TCCL of all threads in the common FJ pool to the Quarkus class loader, but that has a problem: threads in a FJ pool can be discarded and recreated. The newly created threads will not have the correct TCCL, leading to this issue.

In my opinion, the hack should have never been added in the first place, because it hides the problem _randomly_.

**Comment by wojciechkopciewicz** [comment] 2021-06-18 06:57
@michalszynkiewicz any idea why we don't see this with Quarkus older than 1.12.2?

**Comment by michalszynkiewicz** [comment] 2021-06-18 08:09
Unfortunately I don't have any idea... Maybe something changed in the way the application scoped beans are initialized...
@mkouba is it possible that pre 1.12.2 beans were initialized  more eagerly?

**Comment by mkouba** [comment] 2021-06-18 09:39
> application scoped beans are initialized

Application scoped beans are initialized lazily, i.e. when needed. So it's probably not the problem. But I'll take a look at the rest of the reproducer...
