### ISSUE TITLE
No vertx context in smallrye messaging when using coroutines.

### ISSUE THREAD

**Issue by jkbbwr** [quarkusio/quarkus#25502] opened 2022-05-11 14:08 UTC
### Describe the bug

When using coroutines for `Incoming` in smallrye messaging an exception is thrown. 

### Expected behavior

The numbers are printed with a timestamp every second.

### Actual behavior

```java
java.lang.IllegalStateException: No Vertx context found
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:16)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:11)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.invoke(AbstractMediator.java:95)
	at io.smallrye.reactive.messaging.providers.AbstractMediator.lambda$invokeOnMessageContext$1(AbstractMediator.java:103)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$0(LocalContextMetadata.java:34)
	at io.smallrye.reactive.messaging.providers.locals.LocalContextMetadata.lambda$invokeOnMessageContext$3(LocalContextMetadata.java:72)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:74)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:601)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:26)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:163)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:193)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.MultiOperatorProcessor.onItem(MultiOperatorProcessor.java:100)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.onItem(ContextDecorator.java:82)
	at io.smallrye.reactive.messaging.providers.locals.ContextDecorator$ContextMulti$ContextProcessor.onItem(ContextDecorator.java:39)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:99)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:85)
	at io.smallrye.mutiny.operators.multi.builders.IntervalMulti$IntervalRunnable.run(IntervalMulti.java:90)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:553)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

### How to Reproduce?

```kotlin
@ApplicationScoped
class Events {
    @Outgoing("test")
    fun test(): Multi<Long> {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
    }

    @Incoming("test")
    suspend fun handle(msg: Long) {
        println("${Instant.now()} = $msg")
    }
}
```

### Output of `uname -a` or `ver`

Linux devbox 5.16.16-arch1-1 #1 SMP PREEMPT Mon, 21 Mar 2022 22:59:40 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### GraalVM version (if different from Java)

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.9.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

### Additional information

Using either kafka or rabbit or in-memory with the vertx context dependency.

**Comment by mschorsch** [comment] 2022-05-11 17:48
Could be a regression in Quarkus 2.9.0. Quarkus 2.8.3 works fine with Apache Artemis (AMQP, without the Vert.x dependency).

**Comment by ozangunalp** [comment] 2022-05-11 21:18
@jkbbwr sorry for the confusion. It wasn't what I thought at first. 
Actually, this happens because you are using the same name for both incoming and outgoing channels. 

At app startup, reactive messaging resolves channels and constructs a graph. 
For channels that are not configured with a connector, pair of in-out channels with matching names get connected in the graph. (When a channel is not resolved, it'll result in a deployment exception)

Because this happens at app startup these "in-memory" channels get called on the main thread.

@geoand shall we just run the coroutine block without Vert.x context. WDYT?

**Comment by geoand** [comment] 2022-05-12 05:14
> @geoand shall we just run the coroutine block without Vert.x context. WDYT?

What would the implications be from the RM side of things?

**Comment by jkbbwr** [comment] 2022-05-12 11:19
I get a weirdly similar issue with trying to do it from scheduler

```kotlin
@ApplicationScoped
class Events(@Channel("test") val testEvents: Emitter<Long>) {
    @Scheduled(every="10s")
    fun every() {
        runBlocking {
            println("Sending")
            testEvents.send(123).await()
            println("sent")
        }
    }

    @Incoming("test")
    suspend fun handle(msg: Long) {
        println("${Thread.currentThread().name} = $msg")
    }
}
```

**Comment by jkbbwr** [comment] 2022-05-12 11:23
And while doing it in a blocking way as well. It seems coroutines and the vertx context just don't seem to play nicely at all

**Comment by geoand** [comment] 2022-05-17 07:35
> > @geoand shall we just run the coroutine block without Vert.x context. WDYT?
> 
> What would the implications be from the RM side of things?

@ozangunalp ^

**Comment by jkbbwr** [comment] 2022-05-17 14:16
This is a blocking issue for myself as I need to be able to do outbox pattern from a poller

**Comment by ozangunalp** [comment] 2022-05-18 10:47
Sorry I kept you waiting. I needed to run some tests to understand the issue. 

I think this issue is independent from the Reactive Messaging. To reiterate on that, on Quarkus when a Reactive Messaging connector (ex. Kafka, AMQP, etc.) is involved, all `@Incoming` methods do run on a Vert.x context and therefore should work with Kotlin coroutines. 
In the example above Reactive Messaging is used without a connector, which will run the reactive stream on the application start, so on the main thread. The constructed reactive stream starts from the `@Outgoing` which creates items using Mutiny ticks and continues by consuming those items on an `@Incoming` method. 

The key thing here is Mutiny ticks (and `@Scheduled` methods) do not run on a Vert.x context but scheduled on an executor service created for executing blocking tasks across all Quarkus extensions. 

@jkbbwr for your use case: 
- For the scheduled method: You can add a `@NonBlocking` annotation and this will make sure that the method is called on an Vert.x context (on an event loop) which plays nicely with Kotlin. I don't know why these methods are not non-blocking by default.
- For the Mutiny ticks: You can emit items on the Vert.x context with the following: 
```kotlin
@ApplicationScoped
class Events(val vertx: io.vertx.mutiny.core.Vertx) {
    @Outgoing("test")
    fun test(): Multi<Long> {
        return Multi.createFrom().ticks().every(Duration.ofSeconds(1))
            .emitOn { r -> vertx.runOnContext(r) }
    }
```

@geoand All in all I don't think we need to run coroutines without a Vert.x context :) Do you think we can give more info on the error message ? The "No vertx context found" error message is correct but doesn't really help. BTW I don't know if there are any coroutine dispatchers other than reactive messaging and scheduler.

**Comment by geoand** [comment] 2022-05-18 12:15
> Do you think we can give more info on the error message

I'll check it out..

@jkbbwr mind adding a reproducer so I can take a look?

**Comment by ozangunalp** [comment] 2022-05-18 12:46
@geoand Here is the test I wrote for the analysis: https://github.com/quarkusio/quarkus/compare/main...ozangunalp:rm_kotlin_coroutine
Check the Events class for TODOs for the fixes.

**Comment by geoand** [comment] 2022-05-18 12:48
Will do, thanks!

**Comment by geoand** [comment] 2022-05-18 13:13
I opened https://github.com/quarkusio/quarkus/pull/25654 for impoving the error message.

I'll close this as @ozangunalp's explanation is spot on.

**Closed by geoand** 2022-05-18 13:13 UTC
Labels: kind/bug, area/smallrye, area/kotlin

**Comment by jkbbwr** [comment] 2022-05-18 15:14
@ozangunalp I owe you a pint at some point in the future, that explanation was spot on and super detailed. 
@geoand Thanks for coordinating on this

I will try this all out locally and report back if I have an issue.
