### ISSUE TITLE
Extend kafka-avro-serializer versions supported in native mode

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#42845] opened 2024-08-28 19:57 UTC
### Describe the bug

Build of native Quarkus applications with kafka-avro-serializer 7.6.* or 7.7.0 fails with the following:
```
Error: Unsupported features in 2 methods
Detailed message:
Error: An object of type 'org.apache.avro.reflect.ReflectData$AllowNull' was found in the image heap. This type, however, is marked for initialization at image run time for the following reason: classes are initialized at run time by default.
This is not allowed for correctness reasons: All objects that are stored in the image heap must be initialized at build time.
You now have two options to resolve this:
1) If it is intended that objects of type 'org.apache.avro.reflect.ReflectData$AllowNull' are persisted in the image heap, add
    '--initialize-at-build-time=org.apache.avro.reflect.ReflectData$AllowNull'
to the native-image arguments. Note that initializing new types can store additional objects to the heap. It is advised to check the static fields of 'org.apache.avro.reflect.ReflectData$AllowNull' to see if they are safe for build-time initialization,  and that they do not contain any sensitive data that should not become part of the image.
2) If these objects should not be stored in the image heap, you can use
    '--trace-object-instantiation=org.apache.avro.reflect.ReflectData$AllowNull'
to find classes that instantiate these objects. Once you found such a class, you can mark it explicitly for run time initialization with
    '--initialize-at-run-time=<culprit>'
to prevent the instantiation of the object.
```

We use the required dependency (`jackson-dataformat-csv`) to make native work with 7.5.* versions of serializer, but it seems this is not enough either.

### Expected behavior

The native build passes

### Actual behavior

The native build fails

### Output of `java -version`

openjdk version "21.0.2" 2024-01-16

### Mandrel or GraalVM version (if different from Java)

23.1.4.0

### Quarkus version or git rev

3.13, 3.14, main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.9 (8e8579a9e76f7d015ee5ec7bfcdc97d260186937)

**Comment by cescoffier** [comment] 2024-08-29 06:12
As explained, it's not a bug, it's an enhancement request.

**Comment by mjurc** [comment] 2024-08-31 12:10
I've opened https://github.com/confluentinc/schema-registry/issues/3257 for now on serializer side.

**Comment by cescoffier** [comment] 2024-11-15 06:46
Closing—there is not much we can do (except add rules for every version, which we can't do); it's more of an upstream problem.

**Closed by cescoffier** 2024-11-15 06:46 UTC
Labels: kind/enhancement, area/kafka, area/native-image
