### ISSUE TITLE
Using Quarkus Gradle extension: error 

### ISSUE THREAD

**Issue by rdehuyss** [quarkusio/quarkus#19504] opened 2021-08-19 12:00 UTC
### Describe the bug

I'm the author of [JobRunr](https://www.jobrunr.io)  and I'm trying to create a Quarkus extension with the Gradle . You can find the branch here: https://github.com/jobrunr/jobrunr/tree/quarkus.

I want to write a test but whenever I run a gradle task, I get the following exception when I use the Quarkus Gradle plugin:
`Execution failed for task ':framework-support:jobrunr-quarkus-extension:deployment:quarkusGenerateCode'.
> argument type mismatch`

### Expected behavior

To be able to run tests.

### Actual behavior

`Execution failed for task ':framework-support:jobrunr-quarkus-extension:deployment:quarkusGenerateCode'.
> argument type mismatch`

### How to Reproduce?

1. clone https://github.com/jobrunr/jobrunr/
2. switch to branch Quarkus
3. Uncomment line 3 in `framework-support/jobrunr-quarkus-extension/deployment/build.gradle` to enable the Quarkus Gradle Plugin
4. Run the test in module framework-support > jobrunr-quarkus-extension > deployment

### Output of `uname -a` or `ver`

Linux rdehuyss-laptop 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "1.8.0_292"

### Quarkus version or git rev

2.1.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1

### Additional information

Gradle version:
```
------------------------------------------------------------
Gradle 7.1
------------------------------------------------------------

Build time:   2021-06-14 14:47:26 UTC
Revision:     989ccc9952b140ee6ab88870e8a12f1b2998369e

Kotlin:       1.4.31
Groovy:       3.0.7
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          15.0.2 (Oracle Corporation 15.0.2+7-27)
OS:           Linux 5.11.0-25-generic amd64
```

**Comment by glefloch** [comment] 2021-08-19 12:16
@rdehuyss the plugin should not be enabled in the extension, it is only necessary for application. In the future their will be a specific gradle plugin for extension that will be in charge of generating `META-INF/quarkus-extension.*` files and running validation.

**Comment by rdehuyss** [comment] 2021-08-19 12:18
Hi @glefloch , thanks for getting back at me. @aloubyansky suggested to enable the gradle plugin and create this bug. How do I then run tests for Quarkus? See also https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/quarkus.20gradle.20extension.

**Comment by aloubyansky** [comment] 2021-08-19 12:22
The issue is that to be able to run Quarkus tests in the deployment module, we need the preparation performed currently by the Quarkus Gradle plugin.

**Comment by glefloch** [comment] 2021-08-19 12:26
oh ok, I will have a deeper look.

**Comment by glefloch** [comment] 2021-08-20 06:54
@aloubyansky should we use the `quarkus-junit5-internal` module and make sure the app model is generated? something like in this: https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L306 but for the `internal` module ? 
FYI @rdehuyss here an example usage of `quarkus-junit5-internal` https://quarkus.io/guides/writing-extensions#testing-extensions

**Comment by rdehuyss** [comment] 2021-08-20 07:06
Hi @glefloch , I also already tried with the `quarkus-junit5-internal` lib following the guide in writing extensions. See https://github.com/jobrunr/jobrunr/blob/fc0d234cf18121a149220a0db4a6e2f7973c4b0e/framework-support/jobrunr-quarkus-extension/deployment/src/test/java/org/jobrunr/quarkus/extension/deployment/DefaultConfigurationTest.java. However, I had another exception back then and I was advised to use the `@Quarkus` test annotation. The exception I had when using the `@RegisterExtension`method was:

```
io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
java.lang.RuntimeException: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
    at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:544)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$8(ClassBasedTestDescriptor.java:368)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:368)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:192)
    at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:78)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:136)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
    at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
    at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
    at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
    at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
    at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
    at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
    at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
    at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.processAllTestClasses(JUnitPlatformTestClassProcessor.java:99)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor$CollectAllTestClassesExecutor.access$000(JUnitPlatformTestClassProcessor.java:79)
    at org.gradle.api.internal.tasks.testing.junitplatform.JUnitPlatformTestClassProcessor.stop(JUnitPlatformTestClassProcessor.java:75)
    at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.stop(SuiteTestClassProcessor.java:61)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
    at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
    at com.sun.proxy.$Proxy5.stop(Unknown Source)
    at org.gradle.api.internal.tasks.testing.worker.TestWorker.stop(TestWorker.java:135)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
    at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
    at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
    at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
    at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
    at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
    at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
    at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to create the application model for null
    at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:325)
    at io.quarkus.bootstrap.app.QuarkusBootstrap.bootstrap(QuarkusBootstrap.java:176)
    at io.quarkus.test.QuarkusUnitTest.beforeAll(QuarkusUnitTest.java:494)
    ... 62 more
Caused by: io.quarkus.bootstrap.BootstrapException: Failed to determine the Maven artifact associated with the application /home/ronald/Projects/Personal/JobRunr/jobrunr/framework-support/jobrunr-quarkus-extension/deployment/build/classes/java/test
    at io.quarkus.bootstrap.BootstrapAppModelFactory.resolveAppModel(BootstrapAppModelFactory.java:265)
    ... 64 more
```

**Comment by aloubyansky** [comment] 2021-08-20 07:45
> @aloubyansky should we use the `quarkus-junit5-internal` module and make sure the app model is generated? something like in this: https://github.com/quarkusio/quarkus/blob/main/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L306 but for the `internal` module ?
> FYI @rdehuyss here an example usage of `quarkus-junit5-internal` https://quarkus.io/guides/writing-extensions#testing-extensions

Yes, this is what this issue is about. It should support the Gradle AppModel.

**Closed** 2021-11-24 21:08 UTC
Labels: kind/bug, area/gradle
