### ISSUE TITLE
Quarkus dev mode is not working with a certain type of folder tree due to dependency injection

### ISSUE THREAD

**Issue by jakwarrior** [quarkusio/quarkus#32690] opened 2023-04-17 14:53 UTC
### Describe the bug

I found a very odd bug. I have a multimodule project and I use maven. I have 2 modules, A and B, with B depending on A. A contains a @ApplicationScoped annotated bean.

If I use this tree, everything is fine:
```
- pom.xml
- A folder
   - pom.xml
- B folder
  - pom.xml
```

But if I use this tree, the quarkus dev mode is not working:
```
- parent folder
   - pom.xml
- A folder
   - pom.xml
- B folder
  - pom.xml
```
There is a UnsatisfiedResolutionException, the bean from A is not found. But the project is still working if I use the command "java -jar quarkus-run.jar, it's only in dev mode.

### Expected behavior

The dev mode should be working for every kind of tree. 

### How to Reproduce?

I created a small project to reproduce the problem:
https://github.com/jakwarrior/quarkus-2-multi-module-project-quickstart

The main branch is working. You can use `mvn quarkus:dev` in the root of the project and everything is fine.
You can see the problem with the branch named "not_working". Go to the "quickstart-parent" folder and do  `mvn quarkus:dev`. You will see this stacktrace:

```
2023-04-17 16:26:24,033 WARN  [io.qua.arc.pro.BeanArchives] (build-39) Failed to index com.github.bgizdov.multimodule.entities.User: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV@53fb3dab
2023-04-17 16:26:24,043 WARN  [io.sma.ope.run.scanner] (build-39) SROAP04005: Could not find schema class in index: com.github.bgizdov.multimodule.entities.User
2023-04-17 16:26:24,076 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-04-17 16:26:24,564 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type com.github.bgizdov.multimodule.service.TestService and qualifiers [@Default]
        - java member: com.github.bgizdov.multimodule.resources.UserResource#injectService
        - declared on CLASS bean [types=[com.github.bgizdov.multimodule.resources.UserResource, java.lang.Object], qualifiers=[@Default, @Any], target=com.github.bgizdov.multimodule.resources.UserResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1223)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:288)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:148)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:526)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
```

The "quickstart-core" module contains a simple bean that cannot be injected.
```
@ApplicationScoped
@Getter
public class TestService {
    private final String test = "Hello inject !";
}
```

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk version "11.0.15"

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.5

**Comment by aloubyansky** [comment] 2023-04-19 08:38
It does look like a bug, I'll look into it.

**Comment by jakwarrior** [comment] 2023-04-19 08:45
> I'm not quite sure if this is a supported use case but in any case if you run `mvn quarkus:dev` in the `quickstart-rest` module (which is the quarkus app itself) then it seems to work fine.

It's working only if I do a `mvn install` before. Otherwise, the dependency to quickstart-core is not found.
In that case, on every change to the quickstart-core module, I need to install again the dependency and relaunch the server. We lose all the interest of the live reload of the dev mode.

**Comment by aloubyansky** [comment] 2023-04-19 12:58
@jakwarrior I opened a PR to fix the issue. A few notes on the reproducer: it looks like a mix of an older Quarkus project config using the universe BOM and the `quarkus-plugin.version` property and the recent one. I'd recommend removing the universe BOM which was deprecated a long time ago.
I tested your project with the upcoming 3.0 and it didn't work even after migrating to the jakarta packages. Not sure why but the compiled UserService still used the `javax` package for the `ApplicationScoped` annotation. I was wondering whether it's related to lombok but not sure.

**Comment by jakwarrior** [comment] 2023-04-19 13:07
I forked an old project, I must have missed something while updating it. What is the correct package for the `ApplicationScoped` annotation ?

**Comment by jakwarrior** [comment] 2023-04-19 13:07
@aloubyansky thanks for the PR. I forked an old project, I must have missed something while updating it. What is the correct package for the ApplicationScoped annotation ?

**Comment by aloubyansky** [comment] 2023-04-19 13:16
The package is correct for Quarkus 2.16 that you are using. However, Quarkus 3.x is moving to Jakarta API. Here is a diff for your reproducer generated by running
```
mvn io.quarkus:quarkus-maven-plugin:3.0.0.Final:update -Dstream=3.0
```
```
diff --git a/quickstart-core/pom.xml b/quickstart-core/pom.xml
index df569db..a781256 100644
--- a/quickstart-core/pom.xml
+++ b/quickstart-core/pom.xml
@@ -47,7 +47,7 @@
     <dependency>
       <groupId>jakarta.enterprise</groupId>
       <artifactId>jakarta.enterprise.cdi-api</artifactId>
-      <version>2.0.2</version>
+      <version>4.0.1</version>
     </dependency>
   </dependencies>
 
diff --git a/quickstart-core/src/main/java/com/github/bgizdov/multimodule/service/TestService.java b/quickstart-core/src/main/java/com/github/bgizdov/multimodule/service/TestService.java
index 3b2e867..a433d41 100644
--- a/quickstart-core/src/main/java/com/github/bgizdov/multimodule/service/TestService.java
+++ b/quickstart-core/src/main/java/com/github/bgizdov/multimodule/service/TestService.java
@@ -1,6 +1,6 @@
 package com.github.bgizdov.multimodule.service;
 
-import javax.enterprise.context.ApplicationScoped;
+import jakarta.enterprise.context.ApplicationScoped;^M
 
 import lombok.Getter;
 
diff --git a/quickstart-parent/pom.xml b/quickstart-parent/pom.xml
index 090c2df..dce4e9a 100644
--- a/quickstart-parent/pom.xml
+++ b/quickstart-parent/pom.xml
@@ -17,7 +17,7 @@
     <quarkus-plugin.version>2.16.6.Final</quarkus-plugin.version>
     <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
     <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
-    <quarkus.platform.version>2.16.6.Final</quarkus.platform.version>
+    <quarkus.platform.version>3.0.0.CR2</quarkus.platform.version>
     <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
   </properties>
   <packaging>pom</packaging>
diff --git a/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/resources/UserResource.java b/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/resources/UserResource.java
index d8e8438..4fc4f7f 100644
--- a/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/resources/UserResource.java
+++ b/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/resources/UserResource.java
@@ -4,12 +4,12 @@ import com.github.bgizdov.multimodule.entities.User;
 import com.github.bgizdov.multimodule.service.TestService;
 import com.github.bgizdov.multimodule.services.UserService;
 import io.smallrye.common.annotation.Blocking;
-import javax.inject.Inject;
-import javax.ws.rs.Consumes;
-import javax.ws.rs.GET;
-import javax.ws.rs.Path;
-import javax.ws.rs.Produces;
-import javax.ws.rs.core.MediaType;
+import jakarta.inject.Inject;
+import jakarta.ws.rs.Consumes;
+import jakarta.ws.rs.GET;
+import jakarta.ws.rs.Path;
+import jakarta.ws.rs.Produces;
+import jakarta.ws.rs.core.MediaType;
 
 @Path("/users")
 @Consumes(MediaType.APPLICATION_JSON)
diff --git a/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/services/UserService.java b/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/services/UserService.java
index 5d7d5a2..cbbebc7 100644
--- a/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/services/UserService.java
+++ b/quickstart-rest/src/main/java/com/github/bgizdov/multimodule/services/UserService.java
@@ -1,7 +1,7 @@
 package com.github.bgizdov.multimodule.services;
 
 import com.github.bgizdov.multimodule.entities.User;
-import javax.enterprise.context.ApplicationScoped;
+import jakarta.enterprise.context.ApplicationScoped;
```

**Comment by aloubyansky** [comment] 2023-04-19 13:20
Ah, it worked with the proper update that I posted above. I didn't do
```
     <dependency>
       <groupId>jakarta.enterprise</groupId>
       <artifactId>jakarta.enterprise.cdi-api</artifactId>
-      <version>2.0.2</version>
+      <version>4.0.1</version>
     </dependency>
```
previously, which you don't have to provide a version for, since it's managed by the `quarkus-bom` already. As well as junit.

**Closed** 2023-04-19 19:52 UTC
Labels: kind/bug, area/devmode, env/windows
