### ISSUE TITLE
Failed to build Quarkus projects with Maven 4

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#39924] opened 2024-04-06 05:28 UTC
### Describe the bug

The quarkus maven plugin `generate-code-tests` task failed.

### Expected behavior

Should work as expected.

### Actual behavior

Failed to build the project.

### How to Reproduce?

1. https://github.com/hantsy/quarkus-cargotracker-regapp
2. Enter the project root folder 
3. Using the latest Maven, run `mvn clean quarkus:run ` 
```bash 

 Failed to execute goal io.quarkus:quarkus-maven-plugin:3.9.1:generate-code-tests (default) 
on project cargotracker-regapp: Quarkus code generation phase has failed: 
No valid constructor found on class org.apache.maven.internal.impl.DefaultTransport -> [Help 1]
```

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

22(but run at 21 Language Level)

### Quarkus version or git rev

3.9.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 4.0.0-alpha-13 (0a6a5617fe5ef65c44f05903491e170d92cf37fc)

**Comment by ramiswailem** [comment] 2024-04-06 11:22
https://github.com/quarkusio/quarkus/issues/37627

**Comment by gastaldi** [comment] 2024-04-06 11:43
Closing as duplicate of #37627

**Closed by gastaldi** 2024-04-06 11:43 UTC
Labels: kind/bug, area/maven, env/windows
