### ISSUE TITLE
Quarkus CLI can not be installed from JBang

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#25201] opened 2022-04-27 13:47 UTC
### Describe the bug

Getting started guide[1] recommends to install Quarkus through JBang, via `jbang  app install --fresh --force quarkus@quarkusio` command. Unfortunately, at the moment the command fails.

[1] https://quarkus.io/get-started/

### Expected behavior

Command should install Quarkus succesfully.

### Actual behavior

```
[jbang] [ERROR] Could not download https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json
[jbang] Run with --verbose for more details
```

If running with `verbose` option, the underlying error would be this: `Caused by: java.io.FileNotFoundException: No file to download at https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json. Server replied HTTP code: 404`

### How to Reproduce?

1. `curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/`
2. `curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio`

### Additional information

It looks like some of Jbang scripts has an error, and it tries to download `https://github.com/quarkusio/jbang-catalog/blob/HEAD/jbang-catalog.json` instead of `https://github.com/quarkusio/jbang-catalog/blob/main/jbang-catalog.json`

**Comment by rsvoboda** [comment] 2022-04-27 13:56
Looks like the URL should be https://raw.githubusercontent.com/quarkusio/jbang-catalog/main/jbang-catalog.json instead of https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json

**Comment by gastaldi** [comment] 2022-04-27 15:04
This looks like a bug in JBang, I managed to reproduce it locally with JBang 0.92.2 by runnning 

```bash
jbang app install --verbose --fresh --force quarkus@quarkusio
```

**Comment by gastaldi** [comment] 2022-04-27 16:55
It seems to be a GitHub glitch, it works for me now, can you try again @fedinskiy ?

**Comment by quintesse** [comment] 2022-04-27 17:05
> Looks like the URL should be https://raw.githubusercontent.com/quarkusio/jbang-catalog/main/jbang-catalog.json instead of https://raw.githubusercontent.com/quarkusio/jbang-catalog/HEAD/jbang-catalog.json

This is actually correct. It's a way to get to a file in the main branch without knowing how that branch is called, "main", "master" or something else. AFAIK that isn't what HEAD does in your local Git repo, but it does seem to work like this for services like GitHub, GItLab etc

**Comment by quintesse** [comment] 2022-04-27 17:06
> It seems to be a GitHub glitch, it works for me now, can you try again @fedinskiy ?

GH has been giving me trouble all day, although mostly when using the website (like refusing to post comments).

**Comment by maxandersen** [comment] 2022-04-27 17:36
It's exactly what HEAD does locally before you change it :)

So yeah; we already have several safeguards in place here with caching etc. But since --fresh is used the ask is to jbang to fetch the latest fresh version thus when that fails to return actual data jbang has no alternative url to try. 

I suggest Closing as GitHub glitch.

**Closed** 2022-04-27 17:56 UTC
Labels: kind/bug, area/cli, area/jbang
