### ISSUE TITLE
Dev-services and related tests for Oracle

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#16172] opened 2021-04-01 09:10 UTC
## Description

Follow-up on #15964 : that PR introduces support for Oracle's JDBC driver, but lacks the corresponding dev-services, as well as the corresponding tests (which, crucially, also test that Agroal's `ExceptionSorter` is correctly set).

## Implementation ideas

See `io.quarkus.jdbc.db2.deployment.DevServicesDB2DatasourceTestCase`: basically, we need the same test in the jdbc-oracle extension.

The implementation should be rather similar to what we did for DB2.

**Comment by meeprophone** [comment] 2021-05-04 17:18
Hi, this is a follow-up to the (very welcome!) release of Oracle support in Quarkus native.

There seems to be a bug wherein a custom `reflect-config.json` is ignored whenever the Oracle JDBC support is included.

When included, all of my declared runtime dependencies throw errors such as:

    Caused by: java.lang.InstantiationException: Type `package.for.my.instantiated.ClassName` can not be instantiated reflectively 
    as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.

I have already declared `package.for.my.instantiated.ClassName` inside `reflect-config.json` and it works fine without the Oracle driver.

## Minimal test case:

The following in `application.properties` works:

      quarkus.native.additional-build-args=\
        -H:ReflectionConfigurationFiles=reflect-config.json

To test, include the following in `src/main/resources/reflect-config.json`, but _without_ the `quarkus-jdbc-oracle`
dependency in the POM:

      [{"name":"foo", "allPublicMethods":true}]

The build fails, as expected, because `foo` is not a known class.

However, when the Oracle dependency is included in the POM (this is the only change):

        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-oracle</artifactId>
        </dependency>

...the build now proceeds. This indicates the reflection config is being ignored. 

I suspect there is a problem merging the native-image Args needed for the Oracle driver with the custom ones 
declared in my project.

I haven't found a workaround yet, so this is stopping us from using Quarkus native with Oracle.

Let me know if this should be a separate bug. 

Thanks very much.

**Comment by gsmet** [comment] 2021-05-04 17:22
@Sanne does it ring a bell?

**Comment by Sanne** [comment] 2021-05-04 17:36
The Oracle JDBC driver includes a resource named `META-INF/native-image/reflect-config.json` . I suppose it might conflict with a user-provided copy of the same resource? 

I expected that native-image would be able to combine them when finding multiple such resources but haven't tested that. @meeprophone what happens if you _don't_ specify the `-H:ReflectionConfigurationFiles=reflect-config.json` build time argument? It should be unnecessary and it might confuse it.

If that doesn't work, please open a new issue to have a better look.

**Comment by meeprophone** [comment] 2021-05-04 18:43
Thanks @Sanne for your super-quick reply. I've done some more testing and I was wrong when I said "This indicates the reflection config is being ignored." On closer analysis the Oracle plugin adds `--allow-incomplete-classpath` to the build. So I'm actually seeing this in the logs, instead of a build failure:

        WARNING: Could not resolve foo for reflection configuration. Reason: java.lang.ClassNotFoundException: foo.  
        WARNING: Method java.sql.SQLXML.<init>() not found.

The reason my build failed at runtime is because `reflect-config.json` was missing 'allPublicConstructors' after migrating from the alternative `@RegisterForReflection`, by accident, at the same time (during a Git merge resolution).

So: I don't think there is a name collision, and I don't think the build args were confusing it. The only thing confused was me, but I've learnt a lot in the process of solving this.

Thanks again for your help, your pointers were really useful.

**Comment by Sanne** [comment] 2021-05-04 19:38
@meeprophone great to hear, thanks for reporting back!

And yes their use of ` --allow-incomplete-classpath` is a problem we've discussed with the Oracle team, they are aware that it might be problematic and are seeing if they can improve on that, but they don't release very often so that migth take a while.

**Comment by Sanne** [comment] 2022-02-10 23:26
This was fixed by #23466

**Closed by Sanne** 2022-02-10 23:26 UTC
Labels: kind/enhancement, area/persistence
