### ISSUE TITLE
Application shutdown hooks

### ISSUE THREAD

**Issue by bpasson** [quarkusio/quarkus#15742] opened 2021-03-15 21:16 UTC
## Description

I would like have the ability to register shutdown hooks to have the Quarkus shutdown tasks wait until all registered hooks have terminated or timed out. This creates the possibility to implement graceful shutdown for end-user tasks to properly shutdown before Quarkus starts shutting down e.g. entity managers, executors and other services that could still be needed while properly shutting down the end-user tasks .

Of course there is @PreDestroy, but that doesn't seem to block the Quarkus shutdown process in my experience. It can be done now listening to the `ShutdownEvent`, but it seems a bit cumbersome and I am not sure it would work in all circumstances.

```java
@ApplicationScoped
public class ServiceLifeCycle {

    @Inject
    SampleService service;

    void onStop(@Observes ShutdownEvent ev) {
        service.shutdown()
                .completeOnTimeout(null, 10, TimeUnit.SECONDS)
                .join();
    }
}

```

Quarkus would need to guarantee all user defined shutdownhooks are called in the order they are registered and finished or timed out before starting the Quarkus shutdown tasks.

## Implementation ideas
One idea could be to do this using an extension and have it register `ShutdownBuildItems`, but I think it deserves a more prominent position. I would rather see something like the following options:

* `Quarkus.addShutdownHook( Runnable r )`
* `Quarkus.addShutdownHook( Runnable r, long timeout, TimeUnit unit )`
* `Quarkus.addShutdownHook( CompletableFuture<Void> cf )`
* `Quarkus.addShutdownHook( CompletableFuture<Void> cf, long timeout, TimeUnit unit )`

**Comment by pedrolopix** [comment] 2021-03-19 12:28
I use this class to do it
```
@Singleton
@Slf4j
public class SignalHook implements SignalHandler {
    private final SignalHandler handler;
    private final List<Runnable> runnableList;

    public SignalHook() {
        this.runnableList = new ArrayList<>();
        handler = Signal.handle(new Signal("TERM"), this);
    }

    @Override
    public void handle(final Signal signal) {
        log.debug("[signalhook] Detected signal {} {}", signal.getName(), signal.getNumber());
        runnableList.forEach(item -> item.run());
        handler.handle(signal);
    }

    public void addShutdownHook(final Runnable runnable) {
        runnableList.add(runnable);
    }
}
```

**Comment by bpasson** [comment] 2021-03-19 12:44
Like my solution it is something which is outside the Quarkus core. In my opinion application shutdown is a fundamental part of the application lifecycle. A lot is done already on that topic. What I suggest to add is a missing piece.

**Comment by geoand** [comment] 2022-03-09 13:27
@bpasson would you be willing to contribute this feature?

**Comment by bpasson** [comment] 2022-03-11 19:23
@geoand I can take a swing at it and see if I can cook up a PR to be reviewed. Is that ok with you?

**Comment by geoand** [comment] 2022-03-12 08:41
👌

**Comment by liuzhaozhao** [comment] 2022-03-20 14:38
I have also encountered this problem. Every time the service is shut down, there are always some exceptions, such as: Database related "(RECIPIENT_FAILURE,8191) Pool closed", Event bus related "(NO_HANDLERS,-1) No handlers for address", This exception is often caused by resources not being shut down in the usual order.

"Quarkus.shutdown. timeout" and "quarkus.thread-pool. Shutdown-timeout" and these configurations cannot solve the problem.

Does The Quarkus team have a temporary solution?

**Comment by bpasson** [comment] 2022-03-22 11:04
@liuzhaozhao the best you can do for time being is do something like below. If that doesn't work for you, you could try the solution suggested by @pedrolopix [here](#issuecomment-802799006).

```java
@ApplicationScoped
public class ServiceLifeCycle {

    @Inject
    SampleService service;

    void onStop(@Observes @Priority(1) ShutdownEvent ev) {
        // do blocking work/cleanup here
    }
}
```

The `@Priority(1)` will make sure it runs as first.

**Comment by bpasson** [comment] 2022-03-28 10:28
@geoand Looking into this and I need some pointers on where I can hook this into the core. Obviously I can add a method `addShutdownHook(Runnable runnable)` on the `Quarkus` class. I need some pointers on where to go from there. I have been digging around in the shutdown process and I'm not sure where to put them and came up with:

1. Add them to the StartupContext in some way, don't see how to access the `StartupContext` class though.
3. Introduce a new `Shutdownhooks` class and trigger them from Application#stop, but that would duplicatie some functionality from the StartupContext.

I'd prefer to add to the `StartupContext`, but I you have a better suggestion I'm all for that.

**Comment by geoand** [comment] 2022-03-29 06:42
Probably best cook something up and open a draft PR so we can discuss

**Comment by yrodiere** [comment] 2022-11-04 09:11
The PR ended with this comment:

> Closing the PR, the functionality is already offered in an other way.

So I'll assume this issue can be closed as well. Feel free to reopen or ping me if I'm wrong.

**Closed by yrodiere** 2022-11-04 09:11 UTC
Labels: kind/enhancement, triage/needs-triage
