### ISSUE TITLE
Redis cache "prefix" option erase the cache name / Prefix option is not a real prefix

### ISSUE THREAD

**Issue by thibaultmeyer** [quarkusio/quarkus#44693] opened 2024-11-25 18:15 UTC
### Describe the bug

Hi, 

The prefix option is not actually a prefix, but an overload of the cache name. This is either very strange or a problem with the name of the option.

Actually, when we define a prefix (for example, the application name, as several applications connect to a Redis cluster), we lose the cache name set in the annotation.

/cc @JackyAnn (#35094)

### Expected behavior

By default, key in redis is `cache:<cache-name>:<cache-key>`. So, when the option `quarkus.cache.redis.prefix` is set to a value, by example `${quarkus.application.name}`, we expect to have a cache key following this format : `<custom-prefix>:<cache-name>:<cache-key>` (or something like that).

### Actual behavior

When the option `quarkus.cache.redis.prefix` is set to a value, by example `${quarkus.application.name}`, we get a cache key following this format : `<app-name>:<cache-key>`.

(cache name set in the annotation by the developer is lost)

### Output of `uname -a` or `ver`

Darwin plerome.local 23.6.0 Darwin Kernel Version 23.6.0: Mon Jul 29 21:16:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T8112 arm64

### Output of `java -version`

penjdk version "22.0.2" 2024-07-16 OpenJDK Runtime Environment GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01) OpenJDK 64-Bit Server VM GraalVM CE 22.0.2+9.1 (build 22.0.2+9-jvmci-b01, mixed mode, sharing)

### Quarkus version or git rev

3.15.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

**Current implementation**
```java
String computeActualKey(String key) {

    if (cacheInfo.prefix != null) {
        return cacheInfo.prefix + ":" + key;
    } else {
        return "cache:" + getName() + ":" + key;
    }
}
```

**Expected implementation (or something like that)**
```java
String computeActualKey(String key) {

    if (cacheInfo.prefix != null) {
        return cacheInfo.prefix + ":" + getName() + ":" + key;
        // or : return cacheInfo.prefix.replace("$cache-name", getName()) + ":" + key;
    } else {
        return "cache:" + getName() + ":" + key;
    }
}
```

**Comment by Ladicek** [comment] 2024-11-26 08:11
Not an expert here, but the current behavior seems intentional. It is even documented:

> If not set, use "cache:$cache-name"

**Comment by thibaultmeyer** [comment] 2024-11-26 18:12
> Not an expert here, but the current behavior seems intentional. It is even documented:
> 
> > If not set, use "cache:$cache-name"

Even if we assume that the prefix is "cache:$cache-name", it should be possible to use "$cache-name" when i provide a custom prefix, but this it not working. "$cache-name" is not replaced by the value set in the annotation.

**Comment by cescoffier** [comment] 2024-11-27 18:49
It works as intended.
The cache is caching value associated with a given _cache-key_.  When stored in Redis, this key is *prefixed* to identify which Redis entries are managed by the cache. So,  the actual Redis key is: `$prefix:$cache-key.` If the prefix is not set, it uses `cache:$cache-name`, which means that the final Redis key is: `cache:$cache-name:$cache-key`.

**Comment by thibaultmeyer** [comment] 2024-11-27 20:23
> It works as intended.

I'm not agree, when "prefix" is set, we lost the cache-name set in the annotation. Is not what is attended when a prefix is set, it's clearly not a "prefix", but a "cache name".

Value defined by a developer in business code cannot be considered part of the prefix. Cache name set in the the annotation should alway be present.

**Comment by cescoffier** [comment] 2024-11-28 06:34
It should be possible to introduce syntax when indicating the cache name placeholder. However, it cannot be $cache-name, as it will be interpreted as a config value placeholder. Maybe `<cache-name>`.

@radcortez do you know if we have something like this anywhere? (a placeholder in a config value that will be managed by the extension runtime code and note by the config system)

**Comment by radcortez** [comment] 2024-11-28 09:08
Maybe `@Scheduled(cron = "{expr}")`?

https://github.com/quarkusio/quarkus/blob/e3495ab2158767da477bbafbb6ba015ee9dd162f/extensions/scheduler/common/src/main/java/io/quarkus/scheduler/common/runtime/util/SchedulerUtils.java#L28

It ends up using `Config`, but manually. It could use anything to populate such expressions.

**Comment by cescoffier** [comment] 2024-11-28 15:04
Ah, yes, just {} without the $. Makes sense!

**Comment by thibaultmeyer** [comment] 2024-12-01 14:55
I've opened a merge request with a modification proposal (#44856).

**Comment by cescoffier** [comment] 2024-12-01 16:38
Thanks @thibaultmeyer! The PR looks good, I just asked for a simple test and a line in the doc in https://quarkus.io/guides/cache-redis-reference.

**Closed** 2024-12-02 06:29 UTC
Labels: area/cache, area/redis
