### ISSUE TITLE
No logs on exception in QuarkusTestResourceLifecycleManager.start 

### ISSUE THREAD

**Issue by maschoene** [quarkusio/quarkus#10885] opened 2020-07-21 14:15 UTC
**Describe the bug**
Imagine having a QuarkusTestResourceLifecycleManager, which might throw an exception, if you have got a bug in your manager or haven't properly prepared your environment. If this manager throws an exception in the start method, no logs except the thrown exception are outputted on console.

**Expected behavior**
All logs, including already logged messages and the stack trace of the uncaught exception, are logged.

**Actual behavior**
Only the stack trace of the uncaught exception are logged.

**To Reproduce**
1. Create a test using a QuarkusTestResourceManager.
2. In the QuarkusTestResourceLifecycleManager, log something and throw a RuntimeException.
3. See the log not containing the logged entry from the manager.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: Linux xxx 4.4.0-17763-Microsoft #1217-Microsoft Mon May 05 16:09:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-3ubuntu1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-3ubuntu1, mixed mode)
 - GraalVM version (if different from Java): -
 - Quarkus version or git rev: 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/No.20logs.20on.20exception.20in.20QTestResourceLifecycleManager.2Estart

**Comment by maschoene** [comment] 2020-07-21 14:15
@famod @geoand

**Comment by famod** [comment] 2020-07-21 14:25
Two more observations:
- I wonder if we could also flatten that `InvocationTargetException` a bit (by catching it in `QuarkusTestExtension` and only using its `cause`)?
- `TestResourceManager` is not closed in this case.

**Comment by geoand** [comment] 2020-07-21 14:39
I can't reproduce this. 

Here is what I got:

```
[INFO] Running org.acme.getting.started.GreetingResourceTest
I just got closed
[ERROR] Tests run: 2, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 2.703 s <<< FAILURE! - in org.acme.getting.started.GreetingResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.045 s  <<< ERROR!
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.lang.RuntimeException: Unable to start Quarkus test resource org.acme.getting.started.DummyTestResource@7fb53256
Caused by: java.lang.RuntimeException: Die!
```

**Comment by geoand** [comment] 2020-07-21 14:40
> * `TestResourceManager` is not closed in this case.

This not true, see: https://github.com/quarkusio/quarkus/blob/728e5859671d512d4afc73a9f3aacd06fe4d365f/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusTestExtension.java#L245

**Comment by famod** [comment] 2020-07-21 14:41
> > * `TestResourceManager` is not closed in this case.
> 
> This not true

Ah, sorry - missed that block somehow.

**Comment by geoand** [comment] 2020-07-21 14:43
Np :)

**Comment by geoand** [comment] 2020-07-21 15:00
Logging doesn't work properly in this context. 

So if you need more information, you need to add it to the exception you throw.

I'll close this, as it does work as expected. If you feel otherwise, feel free to comment and/or reopen.

**Comment by famod** [comment] 2020-07-21 17:06
@geoand 
At the very least, we should document this (e.g. in JavaDoc). Which I can also do myself.
I might even take a stab at the root cause but the fact that you closed this ticket like that has me worrying that a fix is rather complex...?

**Comment by geoand** [comment] 2020-07-21 17:16
If you take a look at the code of the Quarkus JUnit extension, you'll see no place where we log information and for good reason 😉.

As for the javadoc, I agree, it would be nice to have, so if you want to do it, it will be a nice addition

**Comment by famod** [comment] 2020-07-21 17:37
I hope if you don't mind when I reopen this and assign it to me for the JavaDoc adjustment.

**Comment by geoand** [comment] 2020-07-21 17:52
Not at all!

**Closed** 2020-07-23 01:19 UTC
Labels: area/testing, kind/bug

**Comment by Legion2** [comment] 2021-10-13 20:24
I created #20749
