### ISSUE TITLE
quarkus-hibernate-reactive-panache: Won't work with Flyway

### ISSUE THREAD

**Issue by taf-team-aki** [quarkusio/quarkus#15789] opened 2021-03-16 21:58 UTC
## Describe the bug
A project using quarkus-hibernate-reactive-panache and quarkus-flyway won't start.

### Expected behavior
- Database should be created
- Endpoint should deliver results

### Actual behavior
- Service does not start with ".ConfigurationException: Model classes are defined for the default persistence unit but no default datasource found: the default EntityManagerFactory will not be created."

## To Reproduce

Get example from [here](https://bitbucket.org/AlexanderJoeris/hibernate-reactive-panache/src/master/)

1. Open project in idea
2. Run  /src/test/java/org/acme/getting/started/FruitResourceTest to reproduce the exception. 

=> Test fails

3. Comment out dependeny 'quarkus-flyway' in pom.xml (line 67 - 70)
4. Uncomment line 14 in /src/test/java/org/acme/getting/started/MysqlServerResource
5. Rerun /src/test/java/org/acme/getting/started/FruitResourceTest

=> Test ok

### Output of `uname -a` or `ver`
Linux jojo-020 5.4.0-67-generic #75-Ubuntu SMP Fri Feb 19 18:03:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.9" 2020-10-20
OpenJDK Runtime Environment GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06)
OpenJDK 64-Bit Server VM GraalVM CE 20.3.0 (build 11.0.9+10-jvmci-20.3-b06, mixed mode, sharing)

### Quarkus version or git rev
1.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/aki/.local/share/umake/ide/idea-ultimate/plugins/maven/lib/maven3
Java version: 11.0.9, vendor: GraalVM Community, runtime: /usr/lib/jvm/graalvm-ce-java11-20.3.0
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-67-generic", arch: "amd64", family: "unix"

**Comment by geoand** [comment] 2021-03-16 22:13
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/10716

**Closed by geoand** 2021-03-16 22:13 UTC
Labels: area/flyway, area/hibernate-reactive, area/panache, area/persistence, kind/bug
