### ISSUE TITLE
EntityManager find returns entity with all null fields

### ISSUE THREAD

**Issue by ThomasSousa96** [quarkusio/quarkus#12427] opened 2020-09-30 14:33 UTC
**Describe the bug**
I general this works fine, but sometimes the `entityManager.find(Foo.class, id)` returns a `Foo` instance with all null fields except the id. I don't known why this occur.

* I think that the persistence context is inconsistent. Because if I clear the context, using `entityManager.clear()` or `entityManager.detach(foo)`, the `find` method back to work fine;
* I enabled the log and when execute the `find` method the hibernate not show log that it do a query in the database;
* I test if the returned instance is initialized with `Hibernate.isInitialized(foo)` and it returns `false`;
* I did try use `Hibernate.initialize(foo)`. When I execute this method, it show the query log, but field value are not initialized. If execute the `find` method again it yet returns the same instance with the null fields.

**Alternative Solution**

```java
public Foo find(Long id) {
    Foo Foo = entityManager.find(Foo.class, id);
    if (Hibernate.isInitialized(Foo)) {
        return Foo;
    }
    entityManager.detach(Foo);
    return entityManager.find(Foo.class, id);
}
```

**Expected behavior**
Must return the database columns value.

**Actual behavior**
Returns a `Foo` instance with all null fields except the id.

**To Reproduce**
I don't know.

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.hibernate-orm.metrics.enabled=true
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
quarkus.hibernate-orm.batch-fetch-size=100
quarkus.hibernate-orm.jdbc.statement-fetch-size=100
quarkus.hibernate-orm.jdbc.statement-batch-size=100
quarkus.transaction-manager.default-transaction-timeout=PT5M

%dev.quarkus.hibernate-orm.log.sql=true
%dev.quarkus.hibernate-orm.log.bind-param=true
%dev.quarkus.hibernate-orm.log.jdbc-warnings=true

quarkus.datasource.metrics.enabled=true
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.min-size=1
quarkus.datasource.max-size=20
quarkus.datasource.acquisition-timeout=PT10S
quarkus.datasource.leak-detection-interval=PT5M
quarkus.datasource.idle-removal-interval=PT5M
quarkus.datasource.max-lifetime=P1D
quarkus.datasource.new-connection-sql=SELECT 1
quarkus.datasource.validation-query-sql=SELECT 1
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux thomas 5.4.0-48-generic #52-Ubuntu SMP Thu Sep 10 10:58:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 1.8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Additional context**
* I'm using entity manager (directly) and Panache in same project;
* The find is running inside a `@Transactional` block;
* The Bean is a `@ApplicationScoped`;
* I already try with `@RequestScoped` the problem yet occurs;
* Before execute this `find` method are executed other queries and inserts. Some of this entities are related with the `Foo` entity;
* The entity already exists in the database before start the application;

**Comment by Sanne** [comment] 2020-09-30 19:30
It's going to be complicated to fix this without a reproducer.

Do you really have a need to detach entities? It might help me understand your context.

**Comment by ThomasSousa96** [comment] 2020-09-30 19:52
Hello @Sanne! I'm only using the `detach` method because was the single way that I found to retrieve the entity fields. It's a workaround.

I too did try use a named query but the query too returns a entity with null fields.

Inspecting the `Foo` instance I see that the Hibernate is using a Quarkus Caffeine Cache. There a way to disable this cache?

**Comment by Sanne** [comment] 2020-09-30 21:43
The cache will only be used if you mark your entity as `@Cacheable`. What is it that you see in the `Foo` instance exactly? The entity shouldn't have any reference to the cache.

**Comment by ThomasSousa96** [comment] 2020-09-30 22:48
The entity is not annotated with `@Cacheable`. I too did try annotate with `@Cacheable(false)` but the error is the same.

## Simple test

To test I create a simple endpoint that only execute this find method. The find method returns the entity with the values field values. See the below image:

![Screenshot from 2020-09-30 19-05-52](https://user-images.githubusercontent.com/8549602/94746885-189cd680-0354-11eb-8a9e-369dedfed206.png)

## The find method is executed after some other queries and inserts

***Note**: If I execute the same `find` method in the begin of transaction it works fine.*

### Collapsed
![Screenshot from 2020-09-30 19-08-46](https://user-images.githubusercontent.com/8549602/94747138-99f46900-0354-11eb-93d3-5c95f1ac0e18.png)

### Expanded
![Screenshot from 2020-09-30 19-11-27](https://user-images.githubusercontent.com/8549602/94747163-9f51b380-0354-11eb-89a3-33cc935c53e0.png)

**Comment by gavinking** [comment] 2020-10-01 13:46
It sounds like `find()` is just returning a proxy, which is pretty normal behavior.

**Comment by gavinking** [comment] 2020-10-01 13:49
Note also that `Hibernate.initialize()` does not initialize the fields of a proxy instance, it just loads a separate instance that the proxy will delegate to.

**Comment by ThomasSousa96** [comment] 2020-10-01 14:28
Hi @gavinking, can be normal the `find` method return a proxy but it's not initialized when the `get` method is called. Example: 

```java
Foo foo = find(Foo.class, 1L);
foo.getName() //An lazy proxy must be initialize when a get method is called, but when it's executed it yet returns null.
```

I not understand when you did say: "it just loads a separate instance that the proxy will delegate to.". Can you explain with more details?

**Comment by gavinking** [comment] 2020-10-01 14:30
Well sure, it's not normal that `getName()` returns null, but I just wanted to make sure that that is what is happening here, because it's not what you wrote above. You wrote that the _fields_ were null, which might well be perfectly normal.

**Comment by ThomasSousa96** [comment] 2020-10-01 15:31
Got it! I expressed myself badly.

**Comment by geoand** [comment] 2022-07-05 07:16
Is this still an issue? If it is, we will need a reproducer project, otherwise we should close the issue.

**Comment by Sanne** [comment] 2022-07-06 10:44
I'll close it - we can reopen if someone provides a valid reproducer.

**Closed by Sanne** 2022-07-06 10:44 UTC
Labels: kind/bug, area/hibernate-orm, needs-reproducer
