### ISSUE TITLE
Quarkus Kafka Kotlin Coroutines does not work

### ISSUE THREAD

**Issue by akoufa** [quarkusio/quarkus#21423] opened 2021-11-13 09:13 UTC
### Describe the bug

Hello to all. When trying to use Kotlin suspending functions together with Quarkus Kafka I am getting the following exception: 

```
SRMSG00201: Error caught while processing a message: java.lang.IllegalStateException: No Vertx context found
```

I have simply defined the following code:

```
@Incoming("order-in")
    suspend fun consumeOrderEvents(orderRecord: Record<String, Order>) {
```

After analysing the issue I found that the code is not being called on a Vertx Thread as the exception is thrown from the following snippet:

```
val dispatcher: CoroutineDispatcher = Vertx.currentContext()?.let(::VertxDispatcher)
                ?: throw IllegalStateException("No Vertx context found")
```

in the `AbstractSubscribingCoroutineInvoker` class .

Is there anything I have to watch out for when configuring Quarkus Kafka and Kotlin ?

**Comment by cescoffier** [comment] 2021-11-13 11:02
Can you provide a reproducer?

**Comment by akoufa** [comment] 2021-11-13 22:31
@cescoffier I have a created a reproducer. You can check it out here https://github.com/akoufa/quarkus-kafka-kotlin . Just send a value to the orders topic then the following exception is thrown:
```
2021-11-13 23:26:10,815 ERROR [io.sma.rea.mes.provider] (pool-1-thread-1) SRMSG00201: Error caught while processing a message: java.lang.IllegalStateException: No Vertx context found
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:16)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:11)
	at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:94)
	at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningACompletionStage$17(SubscriberMediator.java:214)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:63)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:591)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:24)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:156)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:191)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:597)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:82)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:43)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
	at io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:169)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor.lambda$intercept$0(DevModeSupportConnectorFactoryInterceptor.java:42)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.ReactiveMessagingHotReplacementSetup$OnMessage$1.run(ReactiveMessagingHotReplacementSetup.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by cescoffier** [comment] 2021-11-14 16:06
I got the reason - the ack comes from the Kafka polling thread and not from a Vert.x thread. That Kafka thread is required by the Kafka client execution model. We need to think about a way to fix that issue:

* emitting the callback on the Vert.x context is possible, but won't be free
* doing it only when co-routine are used? 
* should we in this case, just create a Vert.x context is non-available?

**Comment by kdubb** [comment] 2021-11-15 02:57
@cescoffier An identical exception is raised when using RabbitMQ connector.

This method:
```kotlin
@Incoming("my-channel")
suspend fun receiveUpdates(message: Message<String>) {
  // handle message
}
```

Produces this stacktrace:
<details>
java.lang.IllegalStateException: No Vertx context found
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:16)
	at io.quarkus.smallrye.reactivemessaging.runtime.kotlin.AbstractSubscribingCoroutineInvoker.invoke(AbstractSubscribingCoroutineInvoker.kt:11)
	at io.smallrye.reactive.messaging.AbstractMediator.invoke(AbstractMediator.java:88)
	at io.smallrye.reactive.messaging.SubscriberMediator.lambda$processMethodReturningACompletionStage$18(SubscriberMediator.java:216)
	at io.smallrye.context.impl.wrappers.SlowContextualSupplier.get(SlowContextualSupplier.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage.subscribe(UniCreateFromCompletionStage.java:24)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap.subscribe(UniOnItemOrFailureFlatMap.java:27)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.request(UniToMultiPublisher.java:63)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onSubscribe(MultiFlatMapOp.java:591)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher.subscribe(UniToMultiPublisher.java:24)
	at io.smallrye.mutiny.groups.MultiCreate$1.subscribe(MultiCreate.java:156)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem(MultiFlatMapOp.java:191)
	at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem(MultiMapOp.java:50)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.subscription.SafeSubscriber.onNext(SafeSubscriber.java:98)
	at io.smallrye.mutiny.helpers.HalfSerializer.onNext(HalfSerializer.java:31)
	at io.smallrye.mutiny.helpers.StrictMultiSubscriber.onItem(StrictMultiSubscriber.java:83)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.tryEmit(MultiFlatMapOp.java:228)
	at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapInner.onItem(MultiFlatMapOp.java:597)
	at io.smallrye.mutiny.subscription.MultiSubscriber.onNext(MultiSubscriber.java:61)
	at io.smallrye.mutiny.converters.uni.UniToMultiPublisher$UniToMultiSubscription.onItem(UniToMultiPublisher.java:82)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:60)
	at io.smallrye.mutiny.operators.uni.builders.DefaultUniEmitter.complete(DefaultUniEmitter.java:36)
	at io.smallrye.mutiny.groups.UniOnNull.lambda$failWith$1(UniOnNull.java:43)
	at io.smallrye.context.impl.wrappers.SlowContextualBiConsumer.accept(SlowContextualBiConsumer.java:21)
	at io.smallrye.mutiny.groups.UniOnItem.lambda$transformToUni$4(UniOnItem.java:169)
	at io.smallrye.context.impl.wrappers.SlowContextualConsumer.accept(SlowContextualConsumer.java:21)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateWithEmitter.subscribe(UniCreateWithEmitter.java:22)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.performInnerSubscription(UniOnItemTransformToUni.java:81)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni$UniOnItemTransformToUniProcessor.onItem(UniOnItemTransformToUni.java:57)
	at io.smallrye.mutiny.operators.uni.builders.UniCreateFromCompletionStage$CompletionStageUniSubscription.forwardResult(UniCreateFromCompletionStage.java:63)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.DevModeSupportConnectorFactoryInterceptor.lambda$intercept$0(DevModeSupportConnectorFactoryInterceptor.java:42)
	at java.base/java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:863)
	at java.base/java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:841)
	at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base/java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2147)
	at io.quarkus.smallrye.reactivemessaging.runtime.devmode.ReactiveMessagingHotReplacementSetup$OnMessage$1.run(ReactiveMessagingHotReplacementSetup.java:44)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
</details>

**Comment by jogueber** [comment] 2022-01-14 17:43
Any movement on this? 
I have pretty much the same problem what is the reasoning here? Not using suspending functions with reactive messaging?

**Comment by kdubb** [comment] 2022-01-14 17:47
@jogueber I think this has been fixed. The example I posted above works; even in our test beans. I am using RabbitMQ though.

**Comment by jogueber** [comment] 2022-01-14 20:47
@kdubb I still had the problem but I will recheck it :) 
Which version are you using?

**Comment by kdubb** [comment] 2022-01-14 20:48
2.6.2.Final

**Comment by jogueber** [comment] 2022-01-14 20:58
strange I'm using exactly the same and it doesn't work 
which dependencies do you have on your classpath?

**Comment by kdubb** [comment] 2022-01-14 20:59
Well remember I'm using RabbitMQ so maybe there are differences between it and Kafka.

**Comment by jogueber** [comment] 2022-01-14 20:59
nope I'm using RabbitMq as well sorry forgot to say that

**Comment by kdubb** [comment] 2022-01-14 21:01
Are you including `quarkus-smallrye-context-propagation`? That's the only dependency that I have that I can see altering things.

**Comment by jogueber** [comment] 2022-01-14 21:05
Yes I'm including that one

**Comment by lspahija** [comment] 2022-03-23 19:19
We are dealing with this same issue. It appears to not be deterministic. i.e. sometimes the message is handled on a vertx eventloop thread, in which case everything works fine, and sometimes it's handled on a non-eventloop thread such as `pool-1-thread-1` in which case the `No Vertx context found` error mentioned above appears.

This is currently preventing us from using coroutines when consuming from Kafka.

@cescoffier is there a way to ensure that the incoming records always get handled on a vertx eventloop thread?

**Comment by cescoffier** [comment] 2022-03-25 10:37
We are now enforcing it in reactive messaging.

@ozangunalp was that merged in 2.8?

**Comment by ozangunalp** [comment] 2022-03-25 12:26
Yes, Quarkus 2.8 depends on reactive messaging 3.15.0 which runs message handling methods on Vert.x context.

**Comment by lspahija** [comment] 2022-03-25 15:36
Cool, looking forward to the release!

**Comment by gsmet** [comment] 2022-03-25 19:32
Can we close the issue then?

**Comment by lspahija** [comment] 2022-03-25 19:37
As far as I'm aware, this appears to be fixed and the issue can be closed. I didn't open this issue, though.

**Closed** 2022-03-26 18:20 UTC
Labels: kind/bug, area/kotlin, area/kafka
