### ISSUE TITLE
Link.fromMethod does not take class' @Path into account

### ISSUE THREAD

**Issue by gefloh** [quarkusio/quarkus#32369] opened 2023-04-03 14:26 UTC
### Describe the bug (original)

Using `Builder fromMethod(Class<?> resource, String method) ` of the class `javax.ws.rs.core.Link` in a RESTEasy Reactive resource for constructing a link throws a `Request failed: java.lang.IllegalArgumentException: No public method annotated with @Path` **when compiled natively** even when the referenced method exists. Non-natively (and also in earlier Quarkus versions e.g. 2.15.x.Final when compiled natively) this worked without problems.

### Expected behavior

Same behavior for non-natively and natively compiled code: Return the correct link.

### Actual behavior

See bug description.

### How to Reproduce?

[no-annotated-method.zip](https://github.com/quarkusio/quarkus/files/11139170/no-annotated-method.zip)

- Download the zip file and extract
- Run `./mvnw quarkus:dev` inside the extracted directory
- `curl -i -X POST http://localhost:8080/root` returns the expected object with a set `Location:` header (although for some reason the base URL is missing, anyway)
- Compile natively: `./mvnw package -Dnative`
- Run `target/no-annotated-method-1.0.0-SNAPSHOT-runner`
- `curl -i -X POST http://localhost:8080/root` returns a HTTP 500 with `java.lang.IllegalArgumentException: No public method annotated with @Path org.acme.MyResource get`

### Output of `uname -a` or `ver`

Linux victoria 5.10.0-21-amd64 #1 SMP Debian 5.10.162-1 (2023-01-21) x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 OpenJDK Runtime Environment GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.2.0 (build 11.0.16+8-jvmci-22.2-b06, mixed mode, sharing)

### Quarkus version or git rev

2.16.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw 3.8.6

**Comment by geoand** [comment] 2023-04-04 07:23
In RESTEasy Reactive we intentionally do not register JAX-RS Resource Classes for reflection (unless we know it's needed) in order to improve the native-image runtime characteristics.

In this case, Quarkus dow not know that reflection is needed, so you need to manually add `@RegisterForReflection` on the Resource Class.

**Comment by gefloh** [comment] 2023-04-04 11:18
Thanks for explaining @geoand , good to know. Just one more question: Why doesn't it add the `@Path` part from the resource itself, only the part from the referenced method? The resulting link isn't really correct like this.

**Comment by geoand** [comment] 2023-04-04 11:22
You mean the link is not correct in JVM mode either?

**Comment by gefloh** [comment] 2023-04-04 11:24
Yes exactly, in both cases. Is something missing from the code side?

**Comment by geoand** [comment] 2023-04-04 11:29
That sounds like a bug. Let me reopen the issue and adjust the title

**Comment by geoand** [comment] 2023-04-04 11:39
Hm... Actually RESTEasy Classic does this as well so I am not really sure if it's intended or not...

**Comment by geoand** [comment] 2023-04-04 11:40
Looking at the Javadoc of the method, it does seem to be the expected behavior, so I'll close this again :)

**Comment by gefloh** [comment] 2023-04-04 11:41
Not sure where you see this in the Javadocs to be honest.

**Closed by geoand** 2023-04-04 11:40 UTC
Labels: kind/bug, area/resteasy-reactive

**Comment by geoand** [comment] 2023-04-04 11:46
```
    /**
     * Append the path from a Path-annotated method to the existing path. When constructing the final path, a '/' separator
     * will be inserted between the existing path and the supplied path if necessary. This method is a convenience shortcut
     * to {@code path(Method)}, it can only be used in cases where there is a single method with the specified name that is
     * annotated with {@link jakarta.ws.rs.Path}.
     *
     * @param resource the resource containing the method.
     * @param method the name of the method whose {@link jakarta.ws.rs.Path} value will be used to obtain the path to append.
     * @return the updated UriBuilder.
     * @throws IllegalArgumentException if resource or method is {@code null}, or there is more than or less than one
     * variant of the method annotated with {@link jakarta.ws.rs.Path}.
     */
```

**Comment by gefloh** [comment] 2023-04-04 11:49
Strange, for me it looks like this:

    /**
     * Convenience method to build a link from a resource. Equivalent to
     * {@code Link.fromUriBuilder({@link UriBuilder#fromMethod(Class, String) UriBuilder.fromMethod(resource, method)})}.
     * Note that the link URI passed to the {@code Link.Builder} instance returned by this
     * method is relative. Should the link be built as absolute, a {@link Link.Builder#baseUri(URI)
     * base URI} has to be specified in the builder prior to building the new link instance.
     * For example, on a server side a {@link UriInfo#getBaseUri()} may be typically used to define
     * the base URI of a link created using this method.
     */

;-)

**Comment by geoand** [comment] 2023-04-04 11:50
Yeah, I am looking at the Jakarta 10 version :)

**Comment by gefloh** [comment] 2023-04-04 11:51
Not sure what's the point of this method then though. But that's a different question.

**Comment by geoand** [comment] 2023-04-04 11:52
Indeed, it seems pointless to me, but that's just my opinion...

**Comment by gefloh** [comment] 2023-04-04 11:54
I wonder what's the correct way of returning a Location header referencing another method then. :-)

**Comment by geoand** [comment] 2023-04-04 11:56
@FroMage has a cool way of doing this in [Renarde](https://github.com/quarkiverse/quarkus-renarde)
