### ISSUE TITLE
Opentelemetry new trace getting generated during remote call using quarkus rest client

### ISSUE THREAD

**Issue by kunalsumblyavenue** [quarkusio/quarkus#25974] opened 2022-06-06 10:39 UTC
### Scenario

I have a scenario where I need a trace to propagate across 3 different quarkus services : - 

- service 1 is a rest - service which exposes an HTTP GET end point and takes "name" pathParam and dumps the pathParam to an outgoing channel which is linked to a kafka topic
github:- https://github.com/avenuebankau/rest-service/blob/master/src/main/java/org/acme/GreetingResource.java

- service 2 is a smallrye kafka consumer which consumes payload from the kafka topic mentioned in the previous step and sends that same payload to another rest api using quarkus RestClient
github:- https://github.com/avenuebankau/kafka-consumer-rest/blob/master/src/main/java/org/acme/MyReactiveMessagingApplication.java 

- service 3 is another rest api which is called from the service 2 kafka consumer. It takes pathParam "name" and returns a response to the kafka consumer (service 2)
github:- https://github.com/avenuebankau/rest-service-2/blob/master/src/main/java/org/acme/GreetingResource.java

All the 3 projects have the following respective opentelemetry dependencies : - 
`

    <dependency>
      <groupId>io.quarkiverse.loggingjson</groupId>
      <artifactId>quarkus-logging-json</artifactId>
      <version>${quarkiverse.loggingjson.version}</version>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-opentelemetry-exporter-otlp</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry</groupId>
      <artifactId>opentelemetry-extension-trace-propagators</artifactId>
    </dependency>
    <dependency>
      <groupId>io.opentelemetry.instrumentation</groupId>
      <artifactId>opentelemetry-kafka-clients-common</artifactId>
      <version>${kafka.client.opentelemetry.version}</version>
      <scope>runtime</scope>
    </dependency>
    <dependency>
      <groupId>au.com.avenuebank</groupId>
      <artifactId>opentelemetry-dd-logger-extension</artifactId>
      <version>${avenue.opentelemetry.version}</version>
    </dependency>
`

### Issue:- 
Same traceid is propagated from service 1 to service 2 , however when the restClient in service2 calls rest api of service3 , I see a new traceid being set in http outgoing headers. 

The traceid started in service 1 is  **c65c440ef08b2033440f2bc6c808b90c** and we can see that it was propagated to service 2  as well in the kafka message header.  Kafka consumer adds a new span under the same traceid **79c6e55fa61daab5b402d2dde8d9ef5f** as can be seen from the logs of service 2. 

#### service1 logs : -
{"timestamp":"2022-06-06T19:18:49.834+10:00","sequence":2270,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.acme.GreetingResource","level":"INFO","message":"name: kunal","threadName":"executor-thread-0","threadId":115,"mdc":{"transactionId":"5f832cd8ac57cecd","traceId":"c65c440ef08b2033440f2bc6c808b90c","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"rest-service-dev.jar","processId":8880}
{"timestamp":"2022-06-06T19:18:49.843+10:00","sequence":2271,"loggerClassName":"org.jboss.logging.Logger","loggerName":"org.acme.GreetingResource","level":"INFO","message":"messageSent: org.eclipse.microprofile.reactive.messaging.Message$8@2a5dfa1a","threadName":"executor-thread-0","threadId":115,"mdc":{"transactionId":"5f832cd8ac57cecd","traceId":"**c65c440ef08b2033440f2bc6c808b90c**","dd.traceId":"**4904186651989293324**"},"hostName":"c02gk1kymd6m","processName":"rest-service-dev.jar","processId":8880}

#### service 2 logs : - 
{"timestamp":"2022-06-06T19:18:52.586+10:00","sequence":3037,"loggerClassName":"org.apache.commons.logging.impl.JBossLog","loggerName":"org.apache.http.wire","level":"DEBUG","message":"http-outgoing-15 >> \"Accept: text/plain[\\r][\\n]\"","threadName":"vert.x-eventloop-thread-18","threadId":596,"mdc":{"transactionId":"da9fd1ef7025eb15","traceId":"c65c440ef08b2033440f2bc6c808b90c","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"kafka-consumer-rest-dev.jar","processId":9576}
{"timestamp":"2022-06-06T19:18:52.587+10:00","sequence":3038,"loggerClassName":"org.apache.commons.logging.impl.JBossLog","loggerName":"org.apache.http.wire","level":"DEBUG","message":"http-outgoing-15 >> \"kunal: 8fed6d2ad3e2d99e35086a7cfe38c5c2[\\r][\\n]\"","threadName":"vert.x-eventloop-thread-18","threadId":596,"mdc":{"transactionId":"da9fd1ef7025eb15","traceId":"c65c440ef08b2033440f2bc6c808b90c","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"kafka-consumer-rest-dev.jar","processId":9576}
{"timestamp":"2022-06-06T19:18:52.587+10:00","sequence":3039,"loggerClassName":"org.apache.commons.logging.impl.JBossLog","loggerName":"org.apache.http.wire","level":"DEBUG","message":"http-outgoing-15 >> \"sumbly: ffa25f0d6e9437b2[\\r][\\n]\"","threadName":"vert.x-eventloop-thread-18","threadId":596,"mdc":{"transactionId":"da9fd1ef7025eb15","traceId":"c65c440ef08b2033440f2bc6c808b90c","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"kafka-consumer-rest-dev.jar","processId":9576}
**{"timestamp":"2022-06-06T19:18:52.588+10:00","sequence":3040,"loggerClassName":"org.apache.commons.logging.impl.JBossLog","loggerName":"org.apache.http.wire","level":"DEBUG","message":"http-outgoing-15 >> \"traceparent: 00-79c6e55fa61daab5b402d2dde8d9ef5f-b9319414ca11355d-01[\\r][\\n]\"","threadName":"vert.x-eventloop-thread-18","threadId":596,"mdc":{"transactionId":"da9fd1ef7025eb15","traceId":"c65c440ef08b2033440f2bc6c808b90c","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"kafka-consumer-rest-dev.jar","processId":9576}**
{"timestamp":"2022-06-06T19:18:52.588+10:00","sequence":3041,"loggerClassName":"org.apache.commons.logging.impl.JBossLog","loggerName":"org.apache.http.wire","level":"DEBUG","message":"http-outgoing-15 >> \"Host: localhost:8887[\\r][\\n]\"","threadName":"vert.x-eventloop-thread-18","threadId":596,"mdc":{"transactionId":"da9fd1ef7025eb15","traceId":"**c65c440ef08b2033440f2bc6c808b90c**","dd.traceId":"4904186651989293324"},"hostName":"c02gk1kymd6m","processName":"kafka-consumer-rest-dev.jar","processId":9576}

I am not sure if this is a bug or am I missing something here? Any pointers would be really appreciated. 

Thanks,
Kunal

### Expected behavior

Same traceid that was started in service 1 should be propagated to service 3 when service 2 calls service 3 using rest client. 

### Actual behavior

when service 2 (kafka consumer) makes a rest call to service 3, a new traceparentid is set as http outgoing header which means service 3 starts its own trace and the original trace is lost. 

### How to Reproduce?

I have given the github links for all the three services , after git checkout , please run mvn quarkus:dev to start each service and use the following GET url to start the trace 

`http://localhost:8080/rest/hello/kunal`

This will send the `kunal` in the message payload to kafka topic (`words-out`) which will be picked up by service 2 and again sent as a param to service 3 via rest client.

### Output of `uname -a` or `ver`

Darwin

### Output of `java -version`

openjdk 11.0.12 2021-07-20 OpenJDK Runtime Environment Homebrew (build 11.0.12+0) OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.8.3

### Additional information
Need to run the data dog agent 
`
docker run -d --name dd-agent \
        --network kafka-docker_default \
        --rm \
        -v /var/run/docker.sock:/var/run/docker.sock:ro \
        -v /proc/:/host/proc/:ro \
        -v /sys/fs/cgroup/:/host/sys/fs/cgroup:ro \
        -p 8126:8126/tcp \
        -p 8125:8125/udp \
        -p 4318:4318/tcp \
        -p 4317:4317/tcp \
        -e DD_API_KEY=$DATADOG_API_KEY \
        -e DD_SITE="datadoghq.eu"  \
        -e DD_LOGS_ENABLED=true  \
        -e DD_LOGS_CONFIG_CONTAINER_COLLECT_ALL=true  \
        -e DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true \
        -e DD_APM_ENABLED=true \
        -e DD_HOSTNAME=$DATADOG_HOSTNAME \
        -e DD_ENV=Local \
        -e NON_LOCAL_TRAFFIC=false \
        -e DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_HTTP_ENDPOINT=0.0.0.0:4318 \
        -e DD_OTLP_CONFIG_RECEIVER_PROTOCOLS_GRPC_ENDPOINT=0.0.0.0:4317 \
        gcr.io/datadoghq/agent:latest
`
_No response_

**Comment by geoand** [comment] 2022-06-09 09:37
Does the same thing happen with `quarkus-reactive-rest-client`?

**Comment by radcortez** [comment] 2022-06-13 17:22
If I understood the scenario correctly, the issue is that we don't have the automatic propagation of the trace in Reactive Messaging yet. Unfortunately, until we have this working, you need to propagate manually. Here is how to do it: 

- https://github.com/radcortez/quarkus-playground/blob/52aedd666fe764130d46064c7b2c33353c0232fe/services/book-api/src/main/java/com/radcortez/quarkus/playground/services/book/client/IsbnGeneratorFallback.java#L28
- https://github.com/radcortez/quarkus-playground/blob/52aedd666fe764130d46064c7b2c33353c0232fe/services/book-api/src/main/java/com/radcortez/quarkus/playground/services/book/client/IsbnFallback.java#L28-L29

**Comment by kunalsumblyavenue** [comment] 2022-06-13 23:57
Thanks for your comments @radcortez @geoand .

@radcortez  the issue is not with respect to propagating the headers in reactive message, because my kafka consumer is able to extract the trace id from the message. The issue is when kafka consumer calls another rest endpoint using rest client , this is when the trace id is not getting propagated. 

 I will definitely try using quarkus reactive rest client and let you know.

Thanks,
Kunal

**Comment by radcortez** [comment] 2022-06-15 18:00
Since we are not doing it automatically yet, you need to reattach the context manually with `QuarkusContextStorage.INSTANCE.attach(CONTEXT)`

**Comment by kunalsumblyavenue** [comment] 2022-06-20 05:09
@radcortez  I see, thanks for your suggestion. I was able to fix this problem by manually re-attaching the context.

**Comment by radcortez** [comment] 2022-06-20 12:15
I'll leave this open. We are aware of this, we just haven't implemented it yet. We are adding the OTel support piece by piece.

**Comment by radcortez** [comment] 2022-06-20 18:40
Actually will close this one in favor of https://github.com/quarkusio/quarkus/issues/22906.

**Closed by radcortez** 2022-06-20 18:40 UTC
Labels: kind/enhancement, area/smallrye, area/rest-client, area/tracing

**Comment by srigollamudi** [comment] 2023-10-01 23:27
> @radcortez I see, thanks for your suggestion. I was able to fix this problem by manually re-attaching the context.

Hi, where did you manually attach the context? i am having the same issue and tried attaching the context just before the REST call but that didn't work. Thanks
