### ISSUE TITLE
Kotlin dev compiler cannot access Builder subclass after gRPC hot reload

### ISSUE THREAD

**Issue by seanyerg** [quarkusio/quarkus#24258] opened 2022-03-10 22:19 UTC
### Describe the bug

Application builds and starts correctly with 'mvn compile quarkus:dev', but then making changes to any code dependent on generated gRPC classes generates a class access exception for Builder subclass, but only when also using Kotlin.  The following is the stack error message generated by KotlinCompilerProvider on hot reload:

Compilation failed.             .map { res: String? -> HelloReply.newBuilder().setMessage(res).setCount(count).build() }
C:\training\quarkus-quickstarts\grpc-plain-text-quickstart\src\main\kotlin\io\quarkus\grpc\examples\hello\HelloWorldService.kt:17:47
Reason: Cannot access class 'examples.HelloReply.Builder'. Check your module classpath for missing or conflicting dependencies
            .map { res: String? -> HelloReply.newBuilder().setMessage(res).setCount(count).build() }
C:\training\quarkus-quickstarts\grpc-plain-text-quickstart\src\main\kotlin\io\quarkus\grpc\examples\hello\HelloWorldService.kt:17:60
Reason: Unresolved reference: setMessage
2022-03-10 11:13:19,832 ERROR [io.qua.grp.run.dev.GrpcHotReplacementSetup] (vert.x-worker-thread-0) Failed to redeploy application on changes: java.lang.RuntimeException: Compilation failed.             .map { res: String? -> HelloReply.newBuilder().setMessage(res).setCount(count).build() }
C:\training\quarkus-quickstarts\grpc-plain-text-quickstart\src\main\kotlin\io\quarkus\grpc\examples\hello\HelloWorldService.kt:17:47
Reason: Cannot access class 'examples.HelloReply.Builder'. Check your module classpath for missing or conflicting dependencies
            .map { res: String? -> HelloReply.newBuilder().setMessage(res).setCount(count).build() }
C:\training\quarkus-quickstarts\grpc-plain-text-quickstart\src\main\kotlin\io\quarkus\grpc\examples\hello\HelloWorldService.kt:17:60
Reason: Unresolved reference: setMessage
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:87)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:192)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:707)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:454)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:436)
	at io.quarkus.grpc.runtime.devmode.GrpcHotReplacementSetup$RestartHandler.get(GrpcHotReplacementSetup.java:40)
	at io.quarkus.grpc.runtime.devmode.GrpcHotReplacementSetup$RestartHandler.get(GrpcHotReplacementSetup.java:34)
	at io.quarkus.grpc.runtime.devmode.GrpcHotReplacementInterceptor.fire(GrpcHotReplacementInterceptor.java:13)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$9$1.handle(GrpcServerRecorder.java:409)
	at io.quarkus.grpc.runtime.GrpcServerRecorder$9$1.handle(GrpcServerRecorder.java:406)

### Expected behavior

Changes made to Kotlin code dependent on gRPC generated classes should compile during hot reload, as they did at compile/startup.

### Actual behavior

Changes to Kotlin code dependent on gRPC generated classes cannot access Builder subclasses after hot reload

### How to Reproduce?

https://github.com/seanyerg/quarkus-grpc-kotlin-reproducer.git

This reproducer is no more than the "quarkus-quickstarts/grpc-plain-text-quickstart" combined with the "rest-kotlin-quickstart" (https://quarkus.io/guides/kotlin).  After running the application, make a change to HelloworldService.kt and rerun the gRPC request.  You should see the compile error mentioned.  

### Additional information

Every other Kotlin class hot reloads as long as it isn't dependent on gRPC generated classes.  gRPC with Java also works just fine.  I ruled out any classpath related issues as the classes were clearly included in the target folder and modifications to those classes directly were compiled appropriately.  

I also removed any "final" or "private" access-related issues that were possibly created from Kotlin to Java compile-time issues.  I wasn't able to do this with the all-open plugin automatically, but given that it compiled and ran successfully prior to dev mode hot reload, I doubt that this is the issue anyway.

I also tried compiling gRPC with the protobuf-maven-plugin and was still able to recreate the issue.

**Comment by dakr0013** [comment] 2022-10-01 08:43
Any updates or workarounds?

**Comment by dakr0013** [comment] 2022-10-01 12:05
As I use kotlin I added a config to additionally generate kotlin classes. After that hot reloading worked with the kotlin message class. The hello service looks like this:

```
@GrpcService
class HelloService : Greeter {
  override fun sayHello(request: HelloRequest): Uni<HelloReply> {
    return Uni.createFrom().item { helloReply { message = "Hello ${request.name}" } }
  }
}
```

instead of:

```
@GrpcService
class HelloService : Greeter {
  override fun sayHello(request: HelloRequest): Uni<HelloReply> {
   HelloReply.newBuilder().setMessage("Hello ${request.name}").build()
  }
}
```


I added this to my build.gradle.kts:

```
import com.google.protobuf.gradle.*

plugins {
  //...
  id("com.google.protobuf") version "0.8.19"
}

val protobufKotlinVersion = "3.21.7"
val grpcKotlinVersion = "1.3.0"
//...

dependencies {
  //...
  implementation("com.google.protobuf:protobuf-kotlin:$protobufKotlinVersion")
  implementation("io.grpc:grpc-kotlin-stub:$grpcKotlinVersion")
  //...
}

//...

sourceSets { main { java { srcDirs("build/generated/source/proto/main/grpckt") } } }

protobuf {
  protoc { artifact = "com.google.protobuf:protoc:$protobufKotlinVersion" }

  plugins {
    id("grpckt") { artifact = "io.grpc:protoc-gen-grpc-kotlin:$grpcKotlinVersion:jdk8@jar" }
  }

  generateProtoTasks {
    ofSourceSet("main").forEach {
      it.builtins {
        id("kotlin")
        remove("java") // already generated by quarkus-grpc
      }
      it.plugins { id("grpckt") }
    }
  }
}
```

But using the java message class and hot reload still doesn't work. Only with the kotlin message class.

**Comment by miladjafary** [comment] 2023-03-01 10:39
I have also the same issue. Do you have any estimation when it will be fixed?

**Comment by evanchooly** [comment] 2023-03-01 16:09
i just saw this was assigned to me but i'm not actively working on it.  Unassigning in case someone else has the time for it.

**Comment by gregkonush** [comment] 2023-04-06 02:32
Kotlin hot reload is a blocker for me to switch from springboot, has anyone found a workaround? Seems like when the application is running in dev mode it needs to wait until generated classes are ready in classpath.

**Comment by gregkonush** [comment] 2023-06-07 06:41
@dakr0013, your workaround worked for me, thanks!

**Comment by cescoffier** [comment] 2024-10-16 06:37
I've tried using the reproducer that I updated to _main_—no more issue. 
Closing. Please open another issue with an updated reproducer if this is still a problem.

**Closed by cescoffier** 2024-10-16 06:37 UTC
Labels: kind/bug, area/kotlin, area/grpc
