### ISSUE TITLE
CORS is broken with Quarkus and http2

### ISSUE THREAD

**Issue by huw0** [quarkusio/quarkus#18503] opened 2021-07-07 21:02 UTC
## Describe the bug
Duplicate access-control* headers with http 2. Browsers do not allow these and so connections fail.

### Expected behavior
Single access-control* headers for each type matching the Quarkus CORS configuration. Works as expected with http 1.1

### Actual behavior
Duplicate access-control* headers with http 2. There should only be a single header of each type returned.

With http1/1:

```
[user@localhost test]$ curl -v -H "Origin: http://google.com" http://localhost:8080/q/openapi
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
> GET /q/openapi HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
> Origin: http://google.com
> 
< HTTP/1.1 200 OK
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Access-Control-Allow-Methods: GET, HEAD, OPTIONS
< Access-Control-Max-Age: 86400
< Access-Control-Allow-Headers: Content-Type, Authorization
< Content-Type: application/yaml;charset=UTF-8
< content-length: 7494
```

With http2:

```bash
[user@localhost test]$ curl -v -H "Origin: http://google.com" --http2-prior-knowledge http://localhost:8080/q/openapi
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 8080 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Using HTTP2, server supports multi-use
* Connection state changed (HTTP/2 confirmed)
* Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
* Using Stream ID: 1 (easy handle 0x56116f1a64c0)
> GET /q/openapi HTTP/2
> Host: localhost:8080
> User-Agent: curl/7.61.1
> Accept: */*
> Origin: http://google.com
> 
* Connection state changed (MAX_CONCURRENT_STREAMS == 100)!
< HTTP/2 200 
< access-control-allow-origin: http://google.com
< access-control-allow-credentials: true
< access-control-allow-origin: *
< access-control-allow-credentials: true
< access-control-allow-methods: GET, HEAD, OPTIONS
< access-control-max-age: 86400
< access-control-allow-headers: Content-Type, Authorization
< content-type: application/yaml;charset=UTF-8
< content-length: 7494
```
`access-control-allow-origin`, `access-control-allow-credentials` are both duplicated.

In curl I am forcing unencrypted http2 (h2c) since this is how my cloud load balancer connects to the Quarkus service. There should be no need for any extra headers to be added.

Although I'm showing an example here with openapi, the problem shows on all endpoints.

## Environment (please complete the following information):

```
# Enable cross-origin requests.
quarkus.http.cors=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=*
quarkus.http.cors.access-control-max-age=24H
quarkus.http.cors.access-control-allow-credentials=true
```

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20 LTS
OpenJDK Runtime Environment 18.9 (build 11.0.11+9-LTS)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.11+9-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)
N/A occurs in both Java build and native image.

### Quarkus version or git rev
2.0.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Gradle 6.9

**Comment by sberyozkin** [comment] 2021-07-08 08:19
CC @stuartwdouglas

**Comment by stuartwdouglas** [comment] 2021-07-12 02:37
@phillip-kruger this is an open API issue rather than a HTTP/2 one, the OpenApiHandler is always adding its own COR's headers on top of the configured ones.

**Comment by phillip-kruger** [comment] 2021-07-12 04:52
I'll have a look today. Thanks

**Comment by phillip-kruger** [comment] 2021-07-13 06:28
@stuartwdouglas - I looked at this, and I do not think this is a OpenAPI issue. There are however other potential issue with the OpenAPI code, as I would assume that the CORS headers should be used if configured ? (separate issue)

The duplication only happens when adding `--http2-prior-knowledge` to the curl command. The OpenAPI code calls the `resp.headers().setAll` method on `io.vertx.core.http.HttpServerResponse`.

In the HTTP (1.1) version the implementation is `io.vertx.core.http.impl.headers.HeadersMultiMap` and 
In the HTTP (2) version the implementation is `io.vertx.core.http.impl.headers.Http2HeadersAdaptor`

I created https://github.com/eclipse-vertx/vert.x/pull/4015 that might be a potential fix for this.

If I call `reponse.header.clear` myself, or change to not use a map, but rather a MultiMap, the issue is fixed.

For now, I will do a PR with the MultiMap change, please let me know if this is ok. 
Also let me know if the code should be looking at the CORS configuration and if set, get the values from there ?

Thanks.

**Closed** 2021-07-13 08:21 UTC
Labels: kind/bug, triage/needs-triage
