### ISSUE TITLE
Oracle StoredProcedure call with cursor in native mode raises a NullPointerException

### ISSUE THREAD

**Issue by draccagni** [quarkusio/quarkus#17295] opened 2021-05-17 17:32 UTC
Calling an Oracle StoredProcedure with cursor as out parameter raises a NullPointerException in native mode:
```
Caused by: java.lang.NullPointerException
       at org.hibernate.engine.jdbc.cursor.internal.StandardRefCursorSupport.registerRefCursorParameter(StandardRefCursorSupport.java:67)
       at org.hibernate.query.procedure.internal.ProcedureParameterImpl.prepare(ProcedureParameterImpl.java:283)
       at org.hibernate.procedure.internal.ProcedureCallImpl$3.accept(ProcedureCallImpl.java:397)
```
The reproducer (a maven project) is available at https://github.com/draccagni/quarkus-hibernate-orm-oracle.git . All the instructions are explained in the ```README.md``` file

**Comment by Sanne** [comment] 2021-05-17 22:04
Interesting, this looks like a consequence of having disabled metadata loading during boot.  Thanks for reporting @draccagni !

**Comment by draccagni** [comment] 2021-05-18 08:49
Is there any workaround or can i hope the fix will be included in the next release?

**Comment by yrodiere** [comment] 2021-05-18 17:03
I investigated this, and it seems the problem comes from the fact Hibernate ORM sometimes uses reflection to inject services in other services.
In this case, `org.hibernate.engine.jdbc.cursor.internal.StandardRefCursorSupport` contains this:

```
	@InjectService
	@SuppressWarnings("UnusedDeclaration")
	public void injectJdbcServices(JdbcServices jdbcServices) {
		this.jdbcServices = jdbcServices;
	}
```

And this annotation is expected to be detected when we start Hibernate ORM. Obviously, in native mode, it won't be.

I will work on a patch soon, but as a workaround, you can add a file named `src/main/resources/reflection-config.json` in your project:

```
[
  {
    "name" : "org.hibernate.engine.jdbc.cursor.internal.StandardRefCursorSupport",
    "allDeclaredConstructors" : true,
    "allPublicConstructors" : true,
    "allDeclaredMethods" : true,
    "allPublicMethods" : true,
    "allDeclaredFields" : true,
    "allPublicFields" : true
  }
]
```

And ask Quarkus to take it into account by setting this property:

```
quarkus.native.additional-build-args =-H:ReflectionConfigurationFiles=reflection-config.json
```

I used that on your reproducer and it apparently fixed the issue.

**Comment by draccagni** [comment] 2021-05-18 21:33
The workaround fixes the issue. Do you think that the patch will be available in the next release?

**Comment by yrodiere** [comment] 2021-05-19 09:38
The patch is ready: #17348. 

It will be in the next 2.0 release if it gets merged today.

As to including it in 1.13.5, I suppose it will be, but @gsmet will get to decide; I'm not aware of all the constraints.

**Comment by draccagni** [comment] 2021-05-19 11:23
The workaround solve the issue.

**Comment by yrodiere** [comment] 2021-05-19 11:42
@draccagni Thank you for reporting the problem. Please don't close issues though, we will close them when fixes get merged.

**Closed** 2021-05-19 17:10 UTC
Labels: area/hibernate-orm, kind/bug
