### ISSUE TITLE
Regression in 3.3.0.CR1: Synthetic bean instance for io.opentelemetry.api.OpenTelemetry not initialized yet

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#35314] opened 2023-08-10 16:56 UTC
### Describe the bug

Though I'm still waiting for a fix in Hibernate (hopefully 6.2.8), I gave 3.3.0.CR1 a try in my pending Quarkus 3 upgrade branch for my app.
QuarkusTests that have been working in 3.2.3.Final are now failing with:
```
java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
[...]
Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [2deeb341bce4a230183bf3a228841625fe2519ae]: jakarta.enterprise.inject.CreationException: Synthetic bean instance for io.opentelemetry.api.OpenTelemetry not initialized yet: io_opentelemetry_api_OpenTelemetry_4087e2c748253198bc7b05f31387f3f4492f0131
	- a synthetic bean initialized during RUNTIME_INIT must not be accessed during STATIC_INIT
	- RUNTIME_INIT build steps that require access to synthetic beans initialized during RUNTIME_INIT should consume the SyntheticBeansRuntimeInitBuildItem
	at io.opentelemetry.api.OpenTelemetry_2deeb341bce4a230183bf3a228841625fe2519ae_Synthetic_Bean.doCreate(Unknown Source)
	at io.opentelemetry.api.OpenTelemetry_2deeb341bce4a230183bf3a228841625fe2519ae_Synthetic_Bean.create(Unknown Source)
	at io.opentelemetry.api.OpenTelemetry_2deeb341bce4a230183bf3a228841625fe2519ae_Synthetic_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:113)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:37)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:34)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:34)
	at io.opentelemetry.api.OpenTelemetry_2deeb341bce4a230183bf3a228841625fe2519ae_Synthetic_Bean.get(Unknown Source)
	at io.opentelemetry.api.OpenTelemetry_2deeb341bce4a230183bf3a228841625fe2519ae_Synthetic_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:557)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:537)
	at io.quarkus.arc.impl.ArcContainerImpl.beanInstanceHandle(ArcContainerImpl.java:570)
	at io.quarkus.arc.impl.ArcContainerImpl.instanceHandle(ArcContainerImpl.java:532)
	at io.quarkus.arc.impl.ArcContainerImpl.instance(ArcContainerImpl.java:279)
	at io.quarkus.agroal.runtime.OpenTelemetryAgroalDataSource.<init>(OpenTelemetryAgroalDataSource.java:24)
	at io.quarkus.agroal.runtime.AgroalOpenTelemetryWrapper.apply(AgroalOpenTelemetryWrapper.java:11)
	at io.quarkus.agroal.runtime.DataSources.doCreateDataSource(DataSources.java:263)
	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:126)
	at io.quarkus.agroal.runtime.DataSources$1.apply(DataSources.java:123)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.quarkus.agroal.runtime.DataSources.getDataSource(DataSources.java:123)
	at io.quarkus.agroal.runtime.DataSources.fromName(DataSources.java:119)
	at io.quarkus.liquibase.runtime.LiquibaseRecorder.liquibaseFunction(LiquibaseRecorder.java:32)
	at io.quarkus.deployment.steps.LiquibaseProcessor$createBeans1097260187.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.LiquibaseProcessor$createBeans1097260187.deploy(Unknown Source)
	... 53 more
```
PS: OTEL is active for tests, but OTLP export is off.

### Expected behavior

Boot error

### Actual behavior

Test should still be running ok

### How to Reproduce?
[q_otel-jdbc.zip](https://github.com/quarkusio/quarkus/files/12315665/q_otel-jdbc.zip)

### Quarkus version or git rev

3.3.0.CR1

### Additional information

Maybe related to #34545 @geoand?

**Comment by geoand** [comment] 2023-08-10 17:00
We'll need a sample to be able to address this

**Comment by famod** [comment] 2023-08-10 17:04
I've added mock stack data; Liquibase -> JDBC instrumentation

I'll try to provide a reproducer.

**Comment by famod** [comment] 2023-08-10 17:27
Reproducer added!

**Comment by geoand** [comment] 2023-08-10 17:28
Cool, thanks!

Just as an FYI, I won't be around for a couple weeks, so if someone wants to take a stab at it, feel free

**Comment by geoand** [comment] 2023-08-10 17:35
Maybe @michalvavrik is around and can have a look

**Comment by gsmet** [comment] 2023-08-10 17:43
I will have a look tomorrow. There’s something odd because we shouldn’t initialize the datasources at static init.

**Comment by gsmet** [comment] 2023-08-10 17:52
I think I have found the issue, I will test the fix tomorrow.

**Comment by gsmet** [comment] 2023-08-10 17:53
And it looks like Flyway is even worse. I'll have a closer look tomorrow.

**Comment by geoand** [comment] 2023-08-10 18:39
https://github.com/quarkusio/quarkus/pull/35315 is what I came up with. Unfortunately because I don't have any more time on my hands, I did not add tests and the third commit (Flyway )still doesn't pass one of the dev-mode tests.

So I'll leave the PR with you folks and you can do whatever you like with it :)

**Comment by famod** [comment] 2023-08-10 20:25
Ah, no worries! That's what CRs are for, right?
Have a nice PTO!

**Comment by gsmet** [comment] 2023-08-11 10:57
I had a lot of failures for Flyway but they should be all fixed now.

**Comment by gsmet** [comment] 2023-08-11 10:59
And I confirm the PR fixes the reproducer, thanks for the very useful report @famod !

**Closed** 2023-08-11 19:07 UTC
Labels: kind/bug, area/tracing
