### ISSUE TITLE
Cannot invoke "io.opentelemetry.extension.annotations.WithSpan.value()" because "annotation" is null

### ISSUE THREAD

**Issue by romilpunetha** [quarkusio/quarkus#24424] opened 2022-03-19 20:23 UTC
### Describe the bug

I've created a base module with mongodb panache and opentelemetry. I've marked all the base functions with `@WithSpan`. On hitting create, I'm getting the following error:

```
java.lang.NullPointerException: Cannot invoke "io.opentelemetry.extension.annotations.WithSpan.value()" because "annotation" is null
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor$MethodRequestSpanNameExtractor.extract(WithSpanInterceptor.java:87)
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor$MethodRequestSpanNameExtractor.extract(WithSpanInterceptor.java:83)
at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start(Instrumenter.java:159)
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span(WithSpanInterceptor.java:56)
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept(Unknown Source)
at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
```

It's failing on one of my services for all create calls whereas works on the other service which also uses create from the base class in the parent module. 

This is happening in an http call.

### Expected behavior

 A valid span should be created.

### Actual behavior

NPE for `@WithSpan` annotation

### Output of `uname -a` or `ver`

Linux 5.10.96 #1 SMP Tue Mar 1 02:13:02 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 LTS OpenJDK Runtime Environment 21.9 (build 17.0.2+8-LTS) OpenJDK 64-Bit Server VM 21.9 (build 17.0.2+8-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.1

**Comment by gsmet** [comment] 2022-03-19 20:50
It would be helpful if you could provide a small reproducer.

**Comment by romilpunetha** [comment] 2022-03-20 19:41
I'll try to. 
Meanwhile, similar issue faced when annotating my cache repository:

```
java.lang.IllegalArgumentException

at io.opentelemetry.instrumentation.api.annotation.support.ParameterizedClass.of (ParameterizedClass.java:45)
at io.opentelemetry.instrumentation.api.annotation.support.AttributeBindingFactory.resolveListComponentType (AttributeBindingFactory.java:68)
at io.opentelemetry.instrumentation.api.annotation.support.AttributeBindingFactory.createBinding (AttributeBindingFactory.java:55)
at io.opentelemetry.instrumentation.api.annotation.support.MethodSpanAttributesExtractor.bind (MethodSpanAttributesExtractor.java:95)
at java.util.concurrent.ConcurrentHashMap.computeIfAbsent (ConcurrentHashMap.java:1708)
at io.opentelemetry.instrumentation.api.annotation.support.MethodCache.computeIfAbsent (MethodCache.java:21)
at io.opentelemetry.instrumentation.api.annotation.support.MethodCache.computeIfAbsent (MethodCache.java:18)
at io.opentelemetry.instrumentation.api.annotation.support.MethodSpanAttributesExtractor.onStart (MethodSpanAttributesExtractor.java:51)
at io.opentelemetry.instrumentation.api.instrumenter.Instrumenter.start (Instrumenter.java:176)
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor.span (WithSpanInterceptor.java:56)
at io.quarkus.opentelemetry.runtime.tracing.cdi.WithSpanInterceptor_Bean.intercept ([unknown]:-1)
at io.quarkus.arc.impl.InterceptorInvocation.invoke (InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform (AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke (InvocationContexts.java:32)
at com.dstreet.sf.domain.base.BaseCacheRepositoryImpl_Subclass.set ([unknown]:-1)
at com.dstreet.sf.domain.base.BaseDomainCacheRepositoryImpl.set (BaseDomainCacheRepositoryImpl.java:78)
at com.dstreet.userservice.core.module.user.UserCacheRepositoryImpl_Subclass.set$$superforward1 ([unknown]:-1)
at com.dstreet.userservice.core.module.user.UserCacheRepositoryImpl_Subclass$$function$$14.apply ([unknown]:-1)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed (AroundInvokeInvocationContext.java:54)
at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation (AbstractMethodValidationInterceptor.java:68)
at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation (MethodValidationInterceptor.java:17)
at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept ([unknown]:-1)
at io.quarkus.arc.impl.InterceptorInvocation.invoke (InterceptorInvocation.java:41)
at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform (AroundInvokeInvocationContext.java:41)
at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke (InvocationContexts.java:32)
at com.dstreet.userservice.core.module.user.UserCacheRepositoryImpl_Subclass.set ([unknown]:-1)
at com.dstreet.userservice.core.module.user.UserCacheRepositoryImpl_ClientProxy.set ([unknown]:-1)
at com.dstreet.sf.domain.base.BaseServiceImpl.lambda$getByIdsThroughCache$11 (BaseServiceImpl.java:321)
at io.smallrye.mutiny.unchecked.UncheckedFunction.lambda$toFunction$0 (UncheckedFunction.java:45)
at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply (SlowContextualFunction.java:21)
at io.smallrye.mutiny.groups.MultiOnItem.lambda$call$2 (MultiOnItem.java:95)
at io.smallrye.context.impl.wrappers.SlowContextualFunction.apply (SlowContextualFunction.java:21)
at io.smallrye.mutiny.groups.MultiOnItem.lambda$transformToUni$6 (MultiOnItem.java:268)
at io.smallrye.mutiny.operators.multi.MultiFlatMapOp$FlatMapMainSubscriber.onItem (MultiFlatMapOp.java:178)
at io.smallrye.mutiny.operators.multi.MultiMapOp$MapProcessor.onItem (MultiMapOp.java:50)
at io.smallrye.mutiny.operators.multi.MultiEmitOnOp$MultiEmitOnProcessor.run (MultiEmitOnOp.java:199)
at io.quarkus.mongodb.impl.Wrappers.lambda$toMulti$2 (Wrappers.java:30)
at io.vertx.core.impl.AbstractContext.dispatch (AbstractContext.java:100)
at io.vertx.core.impl.AbstractContext.dispatch (AbstractContext.java:63)
at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0 (EventLoopContext.java:38)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute (AbstractEventExecutor.java:164)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks (SingleThreadEventExecutor.java:469)
at io.netty.channel.nio.NioEventLoop.run (NioEventLoop.java:503)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run (SingleThreadEventExecutor.java:986)
at io.netty.util.internal.ThreadExecutorMap$2.run (ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run (FastThreadLocalRunnable.java:30)
at java.lang.Thread.run (Thread.java:833)
```

**Comment by radcortez** [comment] 2022-03-21 10:55
Yes, a reproducer would be helpful. Thanks!

**Comment by geoand** [comment] 2022-07-05 07:12
Closing as we never got a reproducer

**Closed by geoand** 2022-07-05 07:12 UTC
Labels: kind/bug, area/tracing, needs-reproducer

**Comment by v-antech** [comment] 2022-09-20 13:16
I got the same error. Turns out it happened, when I added `@WithSpan` to a static method.

**Comment by gsmet** [comment] 2022-09-20 13:17
@v-antech if you can get us a reproducer, please open a new issue with it attached. Thanks.

**Comment by ThoSap** [comment] 2026-08-26 14:26
@gsmet @geoand @radcortez @v-antech this was fixed with https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/19776

A new release that ships the fix is still pending

**Comment by geoand** [comment] 2026-08-26 16:08
Thanks for the update
