### ISSUE TITLE
`https://code.quarkus.io` should mention which is LTS version

### ISSUE THREAD

**Issue by gian1200** [quarkusio/quarkus#41345] opened 2024-06-20 18:44 UTC
### Description

When using https://code.quarkus.io/, one can select which Quarkus version to use. However, last version is not always recommended, is it? I'd be nice to have a `(LTS)` next to the LTS version (currently 3.8)

![image](https://github.com/quarkusio/quarkus/assets/405347/0bcfa47a-bd83-4d85-840a-fdf69780c53d)

### Implementation ideas

To add `(LTS)` next to current Quarkus LTS version

**Comment by geoand** [comment] 2024-06-21 06:08
@ia3andy should we move this to the code.quarkus.io repo?

**Comment by ia3andy** [comment] 2024-06-21 08:05
Duplicate of https://github.com/quarkusio/code.quarkus.io/issues/1246

**Closed by ia3andy** 2024-06-21 08:05 UTC
Labels: kind/enhancement
