### ISSUE TITLE
Mandrel native executable fails to run on path with Japanese characters

### ISSUE THREAD

**Issue by Rutzzzz** [quarkusio/quarkus#11222] opened 2020-08-05 09:57 UTC
When building native executable with Mandrel image on path with Japanese characters, the produced executable fails to run with the following error being displayed:

```
ERROR: Failed to start application
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/omachala/quarkus-qe/元気かい/app/target/.env
```

1. Create a directory called "元気かい"
2. Inside this directory generate a simple project (e.g. jax-rs app from https://code.quarkus.io/)
3. Run the following command inside the project:
`mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.0.Alpha1-java11 -Dquarkus.version=1.6.0.Final`
4. Run the executable
` ./target/app-1.0.0-SNAPSHOT-runner `

Environment:
Linux localhost.localdomain 5.6.13-100.fc30.x86_64 #1 SMP Fri May 15 00:36:06 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02)
OpenJDK 64-Bit Server VM GraalVM CE 20.1.0 (build 11.0.7+10-jvmci-20.1-b02, mixed mode, sharing)
Quarkus version: 1.6.0.Final
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/omachala/.sdkman/candidates/maven/current
Java version: 11.0.7, vendor: GraalVM Community, runtime: /home/omachala/.sdkman/candidates/java/20.1.0.r11-grl
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.13-100.fc30.x86_64", arch: "amd64", family: "unix"

**Comment by galderz** [comment] 2020-08-07 08:51
@Rutzzzz Thx for trying out Mandrel, have you tried with other Quarkus images to see if the issue is specific to Mandrel or it happens with GraalVM as well?

**Comment by galderz** [comment] 2020-08-07 11:22
This is not specific to Mandrel, Oracle GraalVM CE 20.1.0 shows the same thing. Here's some extra information on the stacktrace:

```
Aug 07, 2020 12:20:52 PM io.quarkus.runtime.ApplicationLifecycleManager run
ERROR: Error running Quarkus application
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:495)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:91)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
Caused by: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/g/tmp/chinese/元気かい/graalvm-20.1/.env
	at sun.nio.fs.UnixPath.encode(UnixPath.java:145)
	at sun.nio.fs.UnixPath.<init>(UnixPath.java:69)
	at sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
	at java.nio.file.Path.of(Path.java:147)
	at java.nio.file.Paths.get(Paths.java:69)
	at io.quarkus.runtime.configuration.ConfigUtils$DotEnvConfigSource.<init>(ConfigUtils.java:171)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:73)
	at io.quarkus.runtime.configuration.ConfigUtils.configBuilder(ConfigUtils.java:58)
	at io.quarkus.runtime.generated.Config.readConfig(Config.zig:855)
	at io.quarkus.deployment.steps.RuntimeConfigSetup.deploy(RuntimeConfigSetup.zig:38)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:282)
	... 6 more
```

**Comment by galderz** [comment] 2020-08-07 14:12
My centos7 docker seg faults when trying to generate docker images (wot?), so I've been trying to build it inside docker on macOS and then running it on linux bare metal and I've been able to reproduce it that way.

However, I fail to replicate it on centos7 when generating native executable bare metal. On macOS, I'd run the more recent:

```
 ./mvnw clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:20.1.0.1.Alpha2-java11 -Dquarkus.version=1.6.1.Final
```

And when I take that binary and run it on centos7 then it fails.

However, if I take those two Mandrel and Quarkus versions and generate the docker image bare metal (setting JAVA_HOME to Mandrel), it all works fine.

This means that there is two possibilities here:

1. Difference in JDK compiling classes vs the JDK generating the images causing issues. I cannot verify this with Mandrel because I cannot run it on macOS. Maybe @zakkak can help verify this. My macOS builds with a Java 11 snapshot version from jdk11u-dev `11.0.9-internal+0-adhoc.g.jdk11u-dev`. I'm going to try to see if I can replicate when using oracle graalvm itself, which I could verify this.

2. The difference is the container itself.

**Comment by galderz** [comment] 2020-08-07 14:23
Re 1. I've tried on macOS to set JAVA_HOME to graalvm 20.1.0 CE, and then build the native executable with ` ./mvnw clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.container-runtime=docker -Dquarkus.version=1.6.1.Final`. Ship the executable to centos7 and run it there with a folder with chinese chars and it fails. So, my gut feeling is that the problem is 2, unless the OS differences in my test play a part but I doubt it. @zakkak should be able to verify this.

**Comment by rsvoboda** [comment] 2020-08-07 19:31
Just for the record - Quarkus product will be using Mandrel via docker image.

**Comment by zakkak** [comment] 2020-08-10 13:29
I was able to reproduce this on Fedora and confirm that building on bare metal produces a working binary, while building with the image results in the reported failure.

**Comment by galderz** [comment] 2020-08-10 16:32
The container image does not seem to be configured with the right encoding, by default it seems to have `file.encoding = ANSI_X3.4-1968`. That would appeear to be `US-ASCII` because when I tried to compile java source code containing japanese characters and it failed with:

```
HelloWorld.java:8: error: unmappable character (0xE5) for encoding US-ASCII
        Path path = Paths.get("/home/g/tmp/japanese/????????????/graalvm-20.1");
```

Changing the locale of the container image would be the sensible thing to do. If that doesn't work or its not possible, changing the locale used when producing native image should work. `UTF-8` should be the target.

**Comment by galderz** [comment] 2020-08-10 16:39
Setting the following in docker might work:

```
ENV LANG='en_US.UTF-8' LANGUAGE='en_US:en' LC_ALL='en_US.UTF-8'
```

I'll check how to do the equivalent with CEKit, but it's quite clear this is an issue for quarkus-images really. I'll create an issue there shortly and close this one.

**Comment by galderz** [comment] 2020-08-11 05:55
Closing this since it's not a Quarkus issue per se. See https://github.com/quarkusio/quarkus-images/issues/86 to follow progress on fix.

**Closed by galderz** 2020-08-11 05:55 UTC
Labels: kind/bug

**Comment by rsvoboda** [comment] 2020-08-11 06:24
The issue is still present until the image is fixed and used by quarkus main code base.
It's like any other component, the issue in Quarkus remains open until the component gets updated.
I'm for keeping this open, @gsmet what's your position on this?
