### ISSUE TITLE
RESTEasy Reactive SSE doesn't provide method annotations, nor actual headers to `MessageBodyWriter`

### ISSUE THREAD

**Issue by cardil** [quarkusio/quarkus#31587] opened 2023-03-03 14:22 UTC
### Describe the bug

The current implementation of RESTEasy Reactive Server Sent Events (SSE) doesn't provide the method annotations, nor actual headers to the implementations of [`MessageBodyWriter#writeTo`](https://jakarta.ee/specifications/platform/8/apidocs/javax/ws/rs/ext/messagebodywriter#writeTo-T-java.lang.Class-java.lang.reflect.Type-java.lang.annotation.Annotation:A-javax.ws.rs.core.MediaType-javax.ws.rs.core.MultivaluedMap-java.io.OutputStream-).

This prevents the implementations of `MessageBodyWriter` knowing they are supposed to serialize the object for SSE, where setting headers make no sense.

Also, it makes sense to warn people that those headers will be dropped. For example, to check if the headers been changed after calling write, we can log a WARN message.

Furthermore, the RESTEasy Classic properly passes the proper annotations. See example here: https://github.com/resteasy/resteasy/blob/0b6e61b27efe52988523821158253a2a28ca8fc9/resteasy-core/src/main/java/org/jboss/resteasy/core/interception/jaxrs/AbstractWriterInterceptorContext.java#L267-L268

See related issue: https://github.com/cloudevents/sdk-java/issues/533

Follow up to https://github.com/quarkusio/quarkus/pull/31560

### Expected behavior

Headers and method annotations are passed to the `MessageBodyWriter` allowing to make proper decisions.

The HTTP response should be:

```http
HTTP/1.1 200 OK
Content-Type: text/event-stream
X-SSE-Content-Type: application/json
transfer-encoding: chunked

data:{
    "data": {
        "play": {
            "game": 33,
            "id": "1ceb74b8-2431-6785-388e-758f8f0c074f"
        },
        "score": 140
    },
    "datacontenttype": "application/json",
    "id": "2",
    "source": "//localhost/dev",
    "specversion": "1.0",
    "type": "com.redhat.openshift.knative.showcase.events.Endpoint"
}

data:{
    "data": {
        "play": {
            "game": 148,
            "id": "e943fdd3-ecc0-353d-a505-16270926258d"
        },
        "score": 296
    },
    "datacontenttype": "application/json",
    "id": "1",
    "source": "//localhost/dev",
    "specversion": "1.0",
    "type": "com.redhat.openshift.knative.showcase.events.Endpoint"
}

data:{
    "data": {
        "play": {
            "game": 61,
            "id": "7b4cd7fc-85b5-828b-2bd1-39de5a8d386a"
        },
        "score": 65
    },
    "datacontenttype": "application/json",
    "id": "0",
    "source": "//localhost/dev",
    "specversion": "1.0",
    "type": "com.redhat.openshift.knative.showcase.events.Endpoint"
}

```

### Actual behavior

The empty headers and annotations are passed to the `MessageBodyWriter`.

The HTTP response is:

```http
HTTP/1.1 200 OK
Content-Type: text/event-stream
X-SSE-Content-Type: application/json
transfer-encoding: chunked

data:{
    "play": {
        "game": 33,
        "id": "1ceb74b8-2431-6785-388e-758f8f0c074f"
    },
    "score": 140
}

data:{
    "play": {
        "game": 148,
        "id": "e943fdd3-ecc0-353d-a505-16270926258d"
    },
    "score": 296
}

data:{
    "play": {
        "game": 61,
        "id": "7b4cd7fc-85b5-828b-2bd1-39de5a8d386a"
    },
    "score": 65
}

```

### How to Reproduce?

1. Use cloudevents-http-restful-ws library, as it has `MessageBodyWriter` implemtation which looks for `StructuredEncoding` annotation in the annotations list. If that annotation isn't found, binary encoding is used. The binary encoding writes the event headers as HTTP headers and event data as body. In the case of SSE, this makes no sense.
2. Define REST endpoint that will produce SSE of return type `Multi<CloudEvent>`.
3. Call such an endpoint. You will see a list of events bodies (the headers are missing)

```java
@GET
@RestStreamElementType(MediaType.APPLICATION_JSON)
Multi<CloudEvent> events() {
  return Multi.createFrom().iterable(events);
}
```

See also: https://github.com/cardil/openshift-knative-showcase/commit/15e00429c459abf655fb483a27f467d598ae173e

### Output of `uname -a` or `ver`

Linux thinkpad-t590 6.1.13-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Feb 22 17:53:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "17.0.5" 2022-10-18
OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8)
OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)
```

### Quarkus version or git rev

2.13.5.Final-redhat-00002

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by cardil** [comment] 2023-03-03 14:56
Even more strange, when trying to return `Set<CloudEvent>` instead of `Multi<CloudEvent>` RESTEasy Reactive throws:

`ERROR [io.qua.res.rea.jac.run.map.NativeInvalidDefinitionExceptionMapper] (executor-thread-0) com.fasterxml.jackson.databind.exc.InvalidDefinitionException: No serializer found for class io.cloudevents.core.data.BytesCloudEventData and no properties discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS) (through reference chain: java.util.ImmutableCollections$SetN[0]->io.cloudevents.core.v1.CloudEventV1["data"])`

```java
@GET
@Produces(MediaType.APPLICATION_JSON)
@StructuredEncoding(JsonFormat.CONTENT_TYPE)
public Set<CloudEvent> all() {
  return Set.copyOf(events);
}
```

**Comment by geoand** [comment] 2023-03-06 09:31
It would be very useful to us if you could put together a super simple sample project based on the reproducing steps you mention. 
This will allow us to focus on addressing the issues at hand (instead of trying and perhaps failing to reproduce them)

**Comment by geoand** [comment] 2023-03-20 09:38
@cardil any luck with the sample?

**Comment by cardil** [comment] 2023-03-20 14:09
> @cardil any luck with the sample?

I haven't got time, but I'll provide it shortly, but I'll provide it shortly.

**Comment by cardil** [comment] 2023-04-20 14:42
@geoand We got this in our showcase app, here: https://github.com/openshift-knative/showcase/blob/2b0a547f558e480f97db79615d9ed383433166d2/quarkus/src/main/java/com/redhat/openshift/knative/showcase/events/Rest.java#L36-L46

You can see the issue, when you remove that method, and restore the [`events` method](https://github.com/openshift-knative/showcase/blob/2b0a547f558e480f97db79615d9ed383433166d2/quarkus/src/main/java/com/redhat/openshift/knative/showcase/events/Rest.java#L19-L23) to `Multi<CloudEvent> events()`

It's just a Quarkus project. You can run it, with `make quarkus` (to build frontend, just once). Later you can run just `quarkus dev` in quarkus dir.

**Comment by geoand** [comment] 2023-04-21 09:54
Thanks

**Comment by geoand** [comment] 2023-04-21 10:39
I have a fix for this that I would like to get in after https://github.com/quarkusio/quarkus/pull/32798 goes in

**Closed** 2023-04-21 15:46 UTC
Labels: kind/bug, area/resteasy-reactive

**Comment by cardil** [comment] 2023-07-25 14:14
@geoand I tried this change in https://github.com/cardil/openshift-knative-showcase/pull/2, but it didn't help, although we are moved further down the stack.

**Comment by geoand** [comment] 2023-07-26 10:08
I had a quick look and it looks like there is a problem in your application (I assume in the test part). You seem to be wriring `Hello world` as the body of the SSE message.

**Comment by cardil** [comment] 2023-07-26 16:10
> I had a quick look and it looks like there is a problem in your application (I assume in the test part). You seem to be wriring `Hello world` as the body of the SSE message.

Nope. It's a CloudEvent that has a `Hello world` as a payload.

See the code at the target branch (Quarkus 3). It works as expected: https://github.com/cardil/openshift-knative-showcase/tree/chore/quarkus3

**Comment by geoand** [comment] 2023-07-26 16:47
I'll need much more cut down sample in order to dig further.

**Comment by geoand** [comment] 2023-07-26 16:53
Saying this because the server was sending data properly and because I have no idea where the sample data is coming from
