### ISSUE TITLE
quarkus create -S 2.43 still createa project

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18772] opened 2021-07-16 22:20 UTC
### Describe the bug

`quarkus21 create --registry-client -S 2.43 test27899rr`

here i'm asking to create a project with non-existent stream and i still get:

```
quarkus21 create --registry-client -S 2.43 test27899rr
Creating an app (default project type, see --help).
Refreshing the local extension catalog cache of playground.io
Downloading from playground.io: http://localhost:8080/registry/maven/io/playground/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml
Downloading from playground.io: http://localhost:8080/registry/maven/io/playground/quarkus-registry-descriptor/1.0-SNAPSHOT/quarkus-registry-descriptor-1.0-SNAPSHOT.json
-----------

applying codestarts...
📚  java
🔨  maven
📦  quarkus
📝  config-properties
🔧  dockerfiles
🔧  maven-wrapper
🚀  resteasy-codestart

-----------
[SUCCESS] ✅  quarkus project has been successfully generated in:
--> /Users/max/code/personal/demo/q21/test27899rr
-----------
Navigate into this directory and get started: quarkus dev
```

### Actual behavior

using dry-run reveals what we got:

```
quarkus21 create --registry-client -S 2.43 --dry-run test27899rr4j
Creating an app (default project type, see --help).
Refreshing the local extension catalog cache of playground.io
Downloading from playground.io: http://localhost:8080/registry/maven/io/playground/quarkus-registry-descriptor/1.0-SNAPSHOT/maven-metadata.xml
Downloading from playground.io: http://localhost:8080/registry/maven/io/playground/quarkus-registry-descriptor/1.0-SNAPSHOT/quarkus-registry-descriptor-1.0-SNAPSHOT.json

A new project would have been created in
	/Users/max/code/personal/demo/q21/test27899rr4j

The project would have been created using the following settings:

  App-config                {}
  Build tool                MAVEN
  Extensions                []
  Java Target               11
  Omit build tool wrapper   false
  Project ArtifactId        test27899rr4j
  Project GroupId           org.acme
  Project Version           1.0.0-SNAPSHOT
  Quarkus Core Version      2.1.0.CR1
  Source Type               JAVA

Navigate into this directory and get started: quarkus dev
````

**Comment by aloubyansky** [comment] 2021-07-16 22:27
Given that the registry doesn't exist, it's basically a duplicate of #18771

**Closed by aloubyansky** 2021-07-16 22:27 UTC
Labels: kind/bug, triage/needs-triage
