### ISSUE TITLE
Incoming HTTP request not being fully read or closed when a constraint validator rejects the request

### ISSUE THREAD

**Issue by davidreis97** [quarkusio/quarkus#28818] opened 2022-10-25 13:16 UTC
### Describe the bug

Machine: Apple M1 Pro
JVM: openjdk 11.0.2
Quarkus: 2.7.4.Final, 2.13.3.Final

There seems to be a race condition between reading a request from a TCP socket and constraint validators.

When a request gets rejected by a constraint validator (such as `@Consume`) before Quarkus had a chance to fully ACK the incoming request, Quarkus answers back with the appropriate status code and stops reading the request from the TCP socket but doesn't close the connection.

This behavior, keeping the connection open but not reading data from the socket, leaves clients in a hanging state after they fully filled the TCP transmission window, waiting for it to be ACK'ed.

The client hang may not be observed if the requests are smaller in size, given that in those cases it's likely that the request has been completely received and ACK'ed by Quarkus before the constraint validator had the chance to fire. In these cases, no hanging is observed.

### Expected behavior

Quarkus should either read the incoming request fully or close the connection, so as to signal to the client that the request transmission should be over.

### Actual behavior

Described in the previous section. Follow the steps below to reproduce.

### How to Reproduce?

1. Create a sample Quarkus application using `quarkus create && cd code-with-quarkus`
2. Add the following endpoint:

```java
@Path("/hello")
public class GreetingResource {

    @POST
    @Consumes({"image/jpeg", "image/png"})
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(byte[] imageFile) {
        throw new NotAuthorizedException("");
    }
}
```
3. Make a request with a large payload (3MB is enough on my machine, Apple M1 Pro) which breaks the `@Consumes` filter by sending a different `Content-Type` header. For your convenience, here's a python snippet that'll do it:

```python
import requests
import os

url = "http://localhost:8080/hello"

payload=b"\x00"+os.urandom(1024 * 1024 * 3)+b"\x00"
headers = {
  'Content-Type': 'image/gif'
}

response = requests.request("POST", url, headers=headers, data=payload)

print(response.text)
```

At this point, the Python code should hang because the request stream is neither being fully read nor closed by Quarkus.

### Output of `uname -a` or `ver`

(macOS M1 Pro) Darwin <REDACTED>.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:19:52 PDT 2022; root:xnu-8020.140.49~2/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.2" 2019-01-15 OpenJDK Runtime Environment 18.9 (build 11.0.2+9) OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)

### Quarkus version or git rev

Reproduced in 2.7.4.Final and 2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 Maven home: /Users/<REDACTED>/.m2/wrapper/dists/apache-maven-3.8.6-bin/67568434/apache-maven-3.8.6 Java version: 11.0.2, vendor: Oracle Corporation, runtime: /Library/Java/JavaVirtualMachines/jdk-11.0.2.jdk/Contents/Home Default locale: en_PT, platform encoding: UTF-8 OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"

**Comment by davidreis97** [comment] 2022-10-25 15:12
Hi, thanks for the help. We're using quarkus-resteasy

**Comment by geoand** [comment] 2022-10-25 15:13
Can you try with `quarkus-resteasy-reactive`

**Comment by davidreis97** [comment] 2022-10-25 15:28
Sorry, I edited right after I commented, we're already using quarkus-resteasy-reactive

**Comment by geoand** [comment] 2022-10-25 15:36
Okay, thanks

**Comment by geoand** [comment] 2022-10-26 05:40
Looking at a Wireshark capture, it seems like the Python client is not sending the `TCP FIN` package after receiving the HTTP 415 response.

It looks something like this:

![Screenshot from 2022-10-26 08-39-33](https://user-images.githubusercontent.com/4374975/197943858-f0a3d308-82dc-4da9-a848-4f7a230cfd88.png)

So I am going to close this issue as `invalid`. Feel free however to comment and provide additional info if you still feel it's an issue

**Comment by davidreis97** [comment] 2022-10-26 07:06
This isn't a problem that just happens with a Python client, this also happens with Postman and with the Java RestEasy client that Quarkus uses as well (the latter is actually where we saw the issue for the first time).

This happens because Quarkus left the TCP connection open and unread. Quarkus should either read the request that is being sent or close the connection so that the TCP transmission is complete.

**Comment by davidreis97** [comment] 2022-10-27 10:11
@geoand Just to add, after sleeping on this - [RFC 2626 (HTTP 1.1)](https://www.ietf.org/rfc/rfc2616.txt) clearly states that a server has the right to respond to a request before receiving it fully, and a client should monitor this response and stop transmitting the request after receiving an error response.

However, given that a lot of modern HTTP client implementations (including the one used by Quarkus for RestEasy auto-generated HTTP clients) do not handle this properly, I believe the right solution here could be either to fully read the request from the TCP socket even after responding to the request. Closing the connection from the server side after sending a response would also fix this issue but would mess with the `KeepAlive` functionality, so I'd steer away from that.

**Comment by geoand** [comment] 2022-10-27 10:21
> However, given that a lot of modern HTTP client implementations (including the one used by Quarkus for RestEasy auto-generated HTTP clients) do not handle this properly

If you have a sample that shows this, I'd love to test it out.

**Comment by geoand** [comment] 2022-10-27 10:22
> However, given that a lot of modern HTTP client implementations (including the one used by Quarkus for RestEasy auto-generated HTTP clients) do not handle this properly, I believe the right solution here could be to either fully read the request from the TCP socket even after responding to the request. Closing the TCP connection from the server side after sending a response would also fix this issue but would mess with the KeepAlive functionality, so I'd steer away from that.

To be honest, this behavior is controlled by Vert.x, so @cescoffier and @jviet probably have a lot more to say about this

**Comment by davidreis97** [comment] 2022-10-27 11:34
@geoand Here's a quick project that'll help you repro it in 5 minutes. The README has a 3 step guide on what you should do to trigger the issue. 

https://github.com/davidreis97/QuarkusRepro28818

**Comment by cescoffier** [comment] 2022-10-28 06:03
I think the problem is really in the client, not in the server. The server respects the specification. It cannot read the request, as it would create an attack vector (send large invalid requests). So, the server is doing the right thing. 

Maybe we should close the connection, in this case; that would be the only thing we could add. However, the clients should be able to react to that.

Does it also happen with the reactive rest client from Quarkus?

**Comment by davidreis97** [comment] 2022-10-28 09:09
@cescoffier As I've reported in [this comment](#issuecomment-1293300932), this happens with multiple (most?) REST clients including the Quarkus Reactive Rest Client. I've provided a test project to reproduce this [here](#issuecomment-1293392935).

**Comment by davidreis97** [comment] 2022-11-02 10:47
@cescoffier @geoand Hi there, have you had the chance to read my previous comment? Should we reopen the ticket and set the proper labels to reflect the fact that this is still an issue that should be solved?

**Comment by Sgitario** [comment] 2022-11-08 09:31
I could reproduce this issue and this is a tentative fix for it: https://github.com/quarkusio/quarkus/pull/29119

**Closed** 2022-11-08 12:36 UTC
Labels: kind/bug, area/resteasy-reactive
