### ISSUE TITLE
NPE when RESTEasy-Reactive and Picocli both in deps

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#24204] opened 2022-03-09 14:58 UTC
### Describe the bug

If you have both RESTEasy-Reactive and Picocli in your dependencies, RESTEasy endpoints throws an NPE exception:
- `NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.getActiveContext(java.lang.Class)" because the return value of "io.quarkus.arc.Arc.container()" is null`

To reproduce, just create a new application at https://code.quarkus.io that has both RESTEasy-Reactive + Picocli, start it, and try to hit the `/hello` endpoint:

![image](https://user-images.githubusercontent.com/26604994/157466227-d86d935d-4236-4604-8854-fa00c4757efd.png)

As an aside to the actual bug report -- I am really curious what is happening here? These two things seem wildly unrelated, how is it that having Picocli in your deps could cause an error with RESTEasy Reactive 🤔 

(It took me 30 minutes of trying different combinations of dependencies to figure out what the minimal reproduction/cause was)

```java
java.lang.NullPointerException: Cannot invoke "io.quarkus.arc.ArcContainer.getActiveContext(java.lang.Class)" because the return value of "io.quarkus.arc.Arc.container()" is null
	at io.quarkus.arc.runtime.devconsole.EventsMonitor_Observer_notify_513ab14b479908baeab956aa73f8a6221325887f.notify(Unknown Source)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:320)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:308)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:238)
	at io.quarkus.arc.impl.RequestContext.fireIfNotEmpty(RequestContext.java:209)
	at io.quarkus.arc.impl.RequestContext.activate(RequestContext.java:123)
	at io.quarkus.arc.ManagedContext.activate(ManagedContext.java:15)
	at io.quarkus.resteasy.reactive.common.runtime.ArcThreadSetupAction.activateInitial(ArcThreadSetupAction.java:18)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.requireCDIRequestScope(AbstractResteasyReactiveContext.java:236)
	at org.jboss.resteasy.reactive.server.handlers.InstanceHandler.handle(InstanceHandler.java:25)
	at org.jboss.resteasy.reactive.server.handlers.InstanceHandler.handle(InstanceHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:163)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:67)
	at io.quarkus.vertx.http.runtime.StaticResourcesRecorder$2.handle(StaticResourcesRecorder.java:55)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1212)
	at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:126)
	at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:141)
	at io.vertx.ext.web.handler.impl.StaticHandlerImpl.lambda$sendStatic$1(StaticHandlerImpl.java:274)
	at io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:141)
	at io.vertx.core.impl.future.FutureBase.lambda$emitSuccess$0(FutureBase.java:54)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

![image](https://user-images.githubusercontent.com/26604994/157467545-83e66527-8ae5-4306-bf3d-7edc196515f4.png)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22000.376]

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.0.0-dev (build 17.0.2+5-jvmci-22.0-b02)

### Quarkus version or git rev

2.7.3-Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

Have a great day 🙂

**Comment by mkouba** [comment] 2022-03-09 16:35
@geoand @GavinRay97 I'll take a look. Is it dev mode only? Also how do you hit the `/hello` endpoint in a CLI app? I mean the command is executed and the app is stopped by default. You can add `Quarkus.waitForExit()` in the `run()` method of the command but what's the point? ;-)

**Comment by geoand** [comment] 2022-03-09 16:45
I only tried dev mode but my guess is that the same would be the case for prod mode.

You basically don't have to do much, just generate the project with the extensions shown, start the application and hit the hello endpoint

**Comment by ebullient** [comment] 2022-03-09 17:35
Picocli commands _tend_ to be one and done. You can use a picocli command-line interface to start a long-running process (too), as an alternate way of processing options. In this case, because resteasy-reactive is present, I would assume a long(er)-running process is the intent, but you would need to indicate that the app is running (using `Quarkus.waitForExit()`, as @mkouba suggests and is documented here: https://quarkus.io/guides/command-mode-reference#the-command-mode-lifecycle). 

Note that dev mode will remain running for CLI apps, but unless you've indicated that the main process should remain active, dev mode will basically just wrap the one-and-done behavior...

**Comment by mkouba** [comment] 2022-03-10 07:47
> I only tried dev mode but my guess is that the same would be the case for prod mode.

Nope. In prod mode the app is shutdown after the picocli command is executed.

> Just clarifying why resteasy-reactive and picocli is not necessarily weird. ;)

Ok, so if I understand it correctly the current behavior is expected and it works as designed and documented ;-).

**Comment by geoand** [comment] 2022-03-10 08:41
Is there any way we can improve the error instead of throwing a NPE?

**Comment by mkouba** [comment] 2022-03-10 09:53
> Is there any way we can improve the error instead of throwing a NPE?

Not easily. The `Arc.container()` method currently returns `null` if the container is not running and some components may rely on this behavior. So we would have to modify all call sites to check nullability instead.

However, we could add a simple check in `io.quarkus.resteasy.reactive.common.runtime.ArcThreadSetupAction.activateInitial()`. WDYT?

**Comment by geoand** [comment] 2022-03-10 09:56
Yeah, that sounds reasonable

**Comment by ebullient** [comment] 2022-03-10 12:31
I guess I would like to know if the long-running usage is what @GavinRay97 intended.. and in that case, if `Quarkus.waitForExit()` is being used... 

(but in case it isn't, a nicer error would still be nice 😊)

**Comment by GavinRay97** [comment] 2022-03-10 14:19
> Nope. In prod mode the app is shutdown after the picocli command is executed.

What do you do if your quarkus app is a web application that also has a CLI? 🤔 
Should there be a different `dev` command for starting the web app versus the CLI app

In this case I have a REST API, plus a "management" CLI tool

@ebullient 

> I guess I would like to know if the long-running usage is what

Yeah, I had assumed it would run the REST API -- I don't have a `QuarkusApplication` overriding anything. I guess my expectations were that it would run the Picocli command, and then leave the REST API running

The code for the reproduction is just this:

```java
// GreetingCommand.java
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

@Command(name = "greeting", mixinStandardHelpOptions = true)
public class GreetingCommand implements Runnable {

    @Parameters(paramLabel = "<name>", defaultValue = "picocli",
        description = "Your name.")
    String name;

    @Override
    public void run() {
        System.out.printf("Hello %s, go go commando!\n", name);
    }

}
```
```java
// ReactiveGreetingResource.java
import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

@Path("/hello")
public class ReactiveGreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello RESTEasy Reactive";
    }
}
```

**Comment by mkouba** [comment] 2022-03-10 15:30
> What do you do if your quarkus app is a web application that also has a CLI?

I think that this is not a common use case ;-). In this case, just use `Quarkus.waitForExit()` as mentioned above.

> What is confusing is that the webserver still works -- IE if you go to `http://localhost:8080` it serves the `index.html` page. It's only the RESTEasy endpoints that throw an NPE.

That's probably because of how the dev mode works. In prod mode the app is just shut down. BTW you can press `space` to run your command again.

> The code for the reproduction is just this:

Just do:

```java
@Command(name = "greeting", mixinStandardHelpOptions = true)
public class GreetingCommand implements Runnable {

    @Parameters(paramLabel = "<name>", defaultValue = "picocli", description = "Your name.")
    String name;

    @Override
    public void run() {
        System.out.printf("Hello %s, go go commando!\n", name);
        Quarkus.waitForExit(); // <== this should solve your problem
    }

```

**Comment by geoand** [comment] 2022-03-11 05:48
I'm gonna close this as it's not a Quarkus issue.

Thanks everyone for your input

**Closed by geoand** 2022-03-11 05:48 UTC
Labels: kind/bug, env/windows, area/resteasy-reactive, area/picocli
