### ISSUE TITLE
Hibernate Reactive's Panache persist methods should return the persisted entity

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#14475] opened 2021-01-21 11:25 UTC
**Description**
In the `PanacheEntityBase` from the `hibernate-reactive-panache`, it would be nice if the `persist()` and `persistAndFlush()` returned the persisted entity in the `Uni` object.

**Implementation ideas**
Change the method signature from `Uni<Void>` to `Uni<T>`

**Comment by gastaldi** [comment] 2021-01-21 11:26
Same for the `PanacheRepositoryBase`

**Comment by DavideD** [comment] 2021-01-21 11:29
Can you show some code examples that will benefit from this change?

**Comment by gastaldi** [comment] 2021-01-21 11:33
@DavideD sure, here is one example:

```java
    private Uni<Extension> createExtension(io.quarkus.dependencies.Extension ext, PlatformRelease platformRelease) {
        Supplier<Uni<? extends Extension>> createNewExtension = () -> {
            Extension newExtension = new Extension();
            newExtension.groupId = ext.getGroupId();
            newExtension.artifactId = ext.getArtifactId();
            newExtension.name = ext.getName();
            newExtension.description = ext.getDescription();
            return newExtension.persistAndFlush()
                    .onItem().transform(x -> newExtension);
        };
        return Extension.findByGroupIdAndArtifactId(ext.getGroupId(), ext.getArtifactId())
                .onItem().ifNull().switchTo(createNewExtension)
                .onItem().transformToUni(extension ->
                        ExtensionRelease.findByExtensionAndVersion(extension, ext.getVersion())
                                .onItem().ifNull()
                                .switchTo(() -> {
                                    ExtensionRelease extensionRelease = new ExtensionRelease();
                                    extensionRelease.extension = extension;
                                    extensionRelease.version = ext.getVersion();
                                    extensionRelease.metadata = toJsonNode(ext.getMetadata());
                                    extensionRelease.platforms.add(platformRelease);
                                    return extensionRelease.persistAndFlush()
                                            .onItem().transform(x -> extensionRelease);
                                })
                                .onItem()
                                .transform(extensionRelease -> {
                                    // Add release to extension
                                    extension.releases.add(extensionRelease);
                                    return extension.persistAndFlush();
                                }).onItem().transform(x -> extension)
                );
    }

```


AFAIU this enhancement would get rid of the `onItem().transform(...)` snippets

**Comment by gavinking** [comment] 2021-01-21 11:59
Even after staring at that code for 5 minutes I've no idea what you're trying to do there.

But I speculate that perhaps this issue can be resolved by trying to clean up your use of the Mutiny APIs, making use of the new operations we added to Mutiny. For example, using `chain()`, `call()`, and `replaceWith()` instead of `.onItem().transformToUni()` for everything.

I might be wrong.

**Comment by gastaldi** [comment] 2021-01-21 12:02
> Even after staring at that code for 5 minutes I've no idea what you're trying to do there.

Welcome to my world :)

This example is a One-to-Many relationship between `Extension` and `ExtensionRelease` (One `Extension` can contain many `ExtensionRelease`s), so I query for `Extension` and if it doesn't exist I perform an INSERT. Same with `ExtensionRelease` and the relationship added in the last `transform` method.

**Comment by DavideD** [comment] 2021-01-21 12:07
I think in Hibernate Reactive one could convert this type of code:
```
Extension extension = new Extension();
       session.  
         .persist( extension)
         .chain( v -> doSomething(extension))
         .chain( v -> session.flush());
```

to something like
```
session
    .persist( new Extension(...) )
    .chain( Type::doSomething )
    .chain( v-> session.flush() )
```

or this:
```
Extension extension = new Extension(...) 
return session
    .withTransaction( tx -> 
        session
            .persist(  extension )
            .chain( v -> doSomethingInTx( extension )
            .invoke( v -> extension )
    );
```

to this:
```
return session
    .withTransaction( tx -> 
        session
           .persist(  new Extension(...)  )
           .chain( Type::doSomethingInTx)
    );
```

**Comment by DavideD** [comment] 2021-01-21 12:15
Actually, the doSomethingInTx doesn't make much difference.

This is a simpler use case for Hibernate Reactive:

```
Extension extension = new Extension(...) 
return session
    .withTransaction( tx -> 
        session
            .persist(  extension )
            .invoke( v -> extension )
    );
```

to this:
```
return session
    .withTransaction( tx -> 
        session
           .persist(  new Extension(...)  )
    );
```

**Comment by gavinking** [comment] 2021-01-21 12:15
@DavideD 

- your third example is a case for `replaceWith()`, not `invoke()` I believe. (It's one of the last things we requested, remember.)
- in your second example you should use `call()` instead of `chain()` to get rid of the nasty `v`.

**Comment by gavinking** [comment] 2021-01-21 12:19
For example:

```java
Extension extension = new Extension(...) 
return session
    .withTransaction( tx -> 
        session
            .persist(  extension )
            .replaceWIth( extension )
    );
```

**Comment by DavideD** [comment] 2021-01-21 12:23
I see, thanks.

You still need the additional `.replaceWith` and an instance of the extension beforehand though.

By the way, I don't have strong opinions either way, but I think it helps to write down some examples as part of the issue.

**Comment by gavinking** [comment] 2021-01-21 12:24
Also @DavideD:

1. We don't use the `v ->` idiom anymore, because it's bad. Use `() ->` instead.
2. For calling `flush()` I think it's better style to use `call()` than `chain().

**Comment by gavinking** [comment] 2021-01-21 12:28
> You still need the additional `.replaceWith` and an instance of the extension beforehand though.


Well I think that's fine personally. I mean, what's actually wrong with:

```java
return session.withTransaction( tx -> {
    Extension extension = new Extension(...);
    return session.persist(extension)
        .replaceWIth(extension);
} );
```

This compares perfectly favorably to the equivalent non-reactive code:

```java
return session.withTransaction( tx -> {
    Extension extension = new Extension(...);
    session.persist(extension);
    return extension;
} );
```

**Comment by DavideD** [comment] 2021-01-21 12:33
Just one last point for completeness.
What about the Hibernate Reactive `Stage.Session` API? A user won't have the nice Mutiny methods in that case.

**Comment by DavideD** [comment] 2021-01-21 12:43
> What about the Hibernate Reactive Stage.Session API? A user won't have the nice Mutiny methods in that case.

I suppose that's the way it is.
Thanks @gavinking

**Comment by FroMage** [comment] 2021-01-21 13:38
This is a RFE for Quarkus's "HR with Panache", so you don't need to change the HR API, this is about the Panache layer.

Originally I made `persist` return `Uni<Void>` because the blocking equivalent returns `void`, but it turns out that it doesn't hurt and leads to more idiomatic reactive pipelines to make it return the item you want to persist, by making it part of the pipeline rather than require a local variable to be declared, which is always a bit tricky with reactive pipelines.

I think it's an acceptable enhancement and doesn't cost anything. It's not like `Uni<Void>` is more useful than `Uni<T>` either.

**Comment by gavinking** [comment] 2021-01-21 13:47
> 2. For calling `flush()` I think it's better style to use `call()` than `chain()`.

Excuse me, I should say the proper style is too use `call()` for _any_ `void`-like method, including `persist()`, `remove()`, etc.

**Comment by gavinking** [comment] 2021-01-21 13:48
> What about the Hibernate Reactive `Stage.Session` API? A user won't have the nice Mutiny methods in that case.

Well, here's where I document the mapping:

<http://hibernate.org/reactive/documentation/1.0/reference/html_single/#_apis_for_chaining_reactive_operations>

For sure it's not quite as nice on the `Stage` API, but it seems like we are currently pushing people toward `Mutiny` anyway.

**Comment by loicmathieu** [comment] 2021-04-30 13:17
@FroMage there is another request for this on #16921 (I closed it as duplicate).

So, do we switch the return type (this is binary compatible but not source compatibe) to `Unit<T>` ?

**Comment by FroMage** [comment] 2021-05-04 08:45
Yes, please.

**Comment by edeandrea** [comment] 2021-05-25 14:58
What about the non-reactive flavor of panache which currently returns `void`? Shouldn't the behavior there be similar?

Also

```java
public Fruit addFruit(@Valid Fruit fruit) {
    return fruitRepository.persist(fruit);
}
```

Is much more elegant and simple than

```java
public Fruit addFruit(@Valid Fruit fruit) {
    fruitRepository.persist(fruit);
    return fruit;
}
```

**Comment by gastaldi** [comment] 2021-05-25 15:23
@edeandrea agreed, that could be changed too

**Comment by edeandrea** [comment] 2021-05-25 15:24
@gastaldi would you like me to open a separate issue for it?

**Comment by loicmathieu** [comment] 2021-05-25 15:36
@gastaldi @edeandrea I'm not against it but I'm pretty sure we already discuss this and dismissed it. 
I would like to hear what's @FroMage think about this one.

**Comment by gastaldi** [comment] 2021-05-25 16:16
> @gastaldi would you like me to open a separate issue for it?

I'm curious to know what @FroMage thinks about it first. I recall seeing some discussions around it as @loicmathieu mentioned

**Comment by edeandrea** [comment] 2021-05-25 16:24
> I'm curious to know what @FroMage thinks about it first. I recall seeing some discussions around it as @loicmathieu mentioned

I don't think he's a fan :)

**Comment by FroMage** [comment] 2021-05-26 15:47
Well, I don't think it's very useful for the non-reactive cases, because we don't usually chain the calls, and this example is really trivial and not common in real code. But it wouldn't hurt I guess.

**Closed** 2021-05-28 09:29 UTC
Labels: area/hibernate-reactive, area/panache, area/persistence, kind/enhancement

**Comment by MartinX3** [comment] 2021-05-28 09:49
Is it possible to backport it to 1.13.x? :)

**Comment by loicmathieu** [comment] 2021-05-28 10:20
> Is it possible to backport it to 1.13.x? :)

I'd rather not, this is already a backport to 2.x as it is already branched, and it can potentially break some code due to method generic return type change so we cannot add it in a micro version.

**Comment by edeandrea** [comment] 2021-06-04 13:21
@FroMage / @loicmathieu after updating to `2.0.0.CR3` I noticed  that the method signature on `PanacheRepositoryBase` within `quarkus-hibernate-reactive-panache` changed to `public default Uni<Entity> persist(Entity entity)` but in `PanacheEntityBase` the `public static Uni<Void> persist(Object firstEntity, Object... entities)` method (and the other `persist` variants still return `Uni<Void>`.

Is this by design? Why do they not return `Uni<T>` like they do in `PanacheRepositoryBase`?

**Comment by loicmathieu** [comment] 2021-06-04 13:49
Entity and repository should offers the same API and they do see https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/PanacheEntityBase.java#L55 and https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/PanacheRepositoryBase.java#L52

Now the persist method that takes a varargs still returns Uni<Void>, we could have return the array of persisted entity but we didn't choose to do so as use cases are less attractive for the various persist variant.

The two exemples you show should works with CR3.

**Comment by edeandrea** [comment] 2021-06-04 13:56
What I'm saying is my examples should look like the following, but it doesn't. I can't use the non-static `persist()` method because I am unable to mock it in my tests using `PanacheMock`. `PanacheMock` can only mock the static methods on `PanacheEntityBase` and `Mockito` can not mock the panache methods.

## Active record
```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Uni<Fruit> addFruit(@Valid Fruit fruit) {
	return Panache.withTransaction(() -> Fruit.persist(fruit));
}
```

## Repository
```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Uni<Fruit> addFruit(@Valid Fruit fruit) {
	return Panache.withTransaction(() -> this.fruitRepository.persist(fruit));
}
```

**Comment by loicmathieu** [comment] 2021-06-04 14:14
@edeandrea what you describe as nothing to do with the changes I made, this is a mocking issue, please open an issue with a reproducer but Mockito should be able to mock your method, or PanacheMock, one of the two.

**Comment by edeandrea** [comment] 2021-06-04 14:19
Mockito can not mock it because the mock is a class, not an instance (i.e. you can't do `Mockito.when(Fruit.class)`).

All I'm trying to say is that the behavior of 

`fruitRepository.persist(fruit)` (returns `Uni<Fruit>`) is now different than `Fruit.persist(fruit)` (returns `Uni<Void>`)

**Comment by loicmathieu** [comment] 2021-06-04 15:09
No `Fruit.persist(fruit)`  returns `Uni<Fruit>` , you can look at https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/PanacheEntityBase.java#L55

**Comment by edeandrea** [comment] 2021-06-04 15:11
That reference you made is not to the correct method. That reference would be for `fruit.persist()`, not `Fruit.persist(fruit)` (https://github.com/quarkusio/quarkus/blob/main/extensions/panache/hibernate-reactive-panache/runtime/src/main/java/io/quarkus/hibernate/reactive/panache/PanacheEntityBase.java#L744)

**Comment by loicmathieu** [comment] 2021-06-04 15:57
OK, you mis-use the API, if you want to persist a single entity you should use the instance method not the static one. As I already said, the static one taken a varags cannot return a `Uni<Fruit>` as it takes a varags, so an array of Fruit.

So the correct usage should be 

```java
@POST
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public Uni<Fruit> addFruit(@Valid Fruit fruit) {
	return Panache.withTransaction(() -> fruit.persist()));
}
```

**Comment by edeandrea** [comment] 2021-06-04 15:58
Ok thanks. Then my ticket (#17697) is blocking me from doing so and forcing me to use `Fruit.persist(fruit)` :)
