### ISSUE TITLE
Not consistent json serialisation between native and not 

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#5420] opened 2019-11-12 20:00 UTC
**Describe the bug**

https://stackoverflow.com/questions/58825073/quarkus-resteasy-jackson-empty-json-result-for-native

**Expected behaviour**
when run not native, hit localhost:8080/init, we got json response filled with data
while nattily, json comes empty {} 

**Actual behaviour**
json response should be the same: native or not

**To Reproduce**
Steps to reproduce the behaviour:
1. based on getting-started-jvm
2. mvn quarkus:add-extension -Dextensions="resteasy-jackson"
3. Add InitData class to serialize as explained here https://stackoverflow.com/questions/58825073/quarkus-resteasy-jackson-empty-json-result-for-native

**Comment by geoand** [comment] 2019-11-13 08:51
Can you please provide the JAX-RS resource you are using to serve `/init`?

My guess is that you returning `Response` and in that case `@RegisterForReflection` is necessary.

**Comment by loicmathieu** [comment] 2019-11-13 09:11
@geoand this issue is so frequent, maybe we can do something inside the resteasy extension? Can't we detect this thanks to Yandex and register for reflection automatically ... or at least log a warning ?

**Comment by geoand** [comment] 2019-11-13 09:17
@loicmathieu you are correct that the issue is very frequent and frustrating.

There is basically only one proper way that I can think of to solve this issue:

In all JAX-RS methods that return `Response` (which remember has no generic type therefore we can't know just by the method signature what type it returns), we would need to have an ASM visitor that visits the method and tries to determine the type that is set to the body. Unfortunately determining the type is not simple and could get complicated very fast since you basically have to do somthing akin to the compiler's work.

The ideal solution would be for JAX-RS's `Response` to have a generic type (which is what Spring's `ResponseEntity` does).

**Comment by loicmathieu** [comment] 2019-11-13 09:41
@geoand the ASM solution seems overkill for Quarkus ...
So this is an issue with JAX-RS that should have defined `Response` as a generic type, nothing that we really fix on our side :(

**Comment by geoand** [comment] 2019-11-13 09:43
@loicmathieu I agree, it would be too much work for too little gain.

**Comment by geoand** [comment] 2021-07-29 06:25
I am going to close this as @FroMage has implemented [@RestResponse](https://github.com/quarkusio/quarkus/pull/18269) in RESTEasy Reactive which is essentially `Response` but with a generic type (and some API improvements)

**Closed by geoand** 2021-07-29 06:25 UTC
Labels: kind/bug
