### ISSUE TITLE
Panache entity is not updated if it exists in different module

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#6832] opened 2020-01-28 15:45 UTC
**Description**
When there is a panache entity in a different module, if it is fetched and changed, Quarkus will not update it in the database and won't throw any Exceptions. It seems like it does not know an attribute changed and a merge is required.

**Expected behaviour**
The entity changes should be persisted.

**Actual behavior**
The entity changes are not persisted.

**To Reproduce**
A very simple small project in https://github.com/AmsterdamFilho/quarkus-poc was created to demonstrate the issue.
Just execute the post to create an entity, and then use the put to update it. The entity will not be updated because the code updating it is in a different module.

**Comment by florent-lb** [comment] 2020-01-28 18:24
Hi  AmsterdamFilho ,

I solved your problem on adding a Setter on name. I think the modification on the property is not inspected but the setter do.

It's precise in the guide : https://quarkus.io/guides/hibernate-orm-panache#defining-your-entity

> And thanks to our field access rewrite, when your users read person.name they will actually call your getName() accessor, and similarly for field writes and the setter. This allows for proper encapsulation at runtime as all fields calls will be replaced by the corresponding getter/setter calls.

**Comment by AmsterdamFilho** [comment] 2020-01-28 18:42
The same code works if the entity is not in an external module. I thought that under the hood the accessors were always being created an invoked. The need to write accessors would only exist for some customisation, like returning the attribute as upper case like the example showed.

**Comment by AmsterdamFilho** [comment] 2020-01-28 18:46
And thanks for the help by the way. I just thought that this was unexpected behaviour that needed to be fixed.

**Comment by gsmet** [comment] 2020-01-29 12:02
We are rewriting the public fields access in the bytecode to point to the getter that has everything to deal with dirty checking.

Looks like something is wrong in your case.

**Comment by gsmet** [comment] 2020-01-29 12:08
/cc @Sanne @stuartwdouglas this is an interesting issue. I'm not sure how we could get the service that is here https://github.com/AmsterdamFilho/quarkus-poc/blob/master/modules/animal-module/src/main/java/br/com/quarkus/poc/AnimalService.java properly instrumented.

One option would be to use the Hibernate ORM Maven plugin to do so. That would be quite ugly but I'm not sure we can get Quarkus to do the instrumentation work, especially without the plugin being declared in the additional module (but IIRC, we should only declare the plugin in the main module).

**Comment by Sanne** [comment] 2020-01-29 13:58
I'm not understanding @gsmet , why would you use the ORM enhancer on the service? Isn't it rather missing the Panache related enhancements?

cc/ @FroMage

**Comment by gsmet** [comment] 2020-01-29 14:03
No, it's missing the fact that we rewrite all public accessor to fields by setters calls.

I think it's called extended enhancement in Hibernate ORM and that's ORM doing that? Or am I mistaken and has it been moved to Panache?

**Comment by FroMage** [comment] 2020-01-29 14:14
ORM can do that, but in Quarkus it doesn't and Panache does it.

If there is an unenhanced service class that uses the entity fields it will break indeed.

So it looks like we're enhancing imported entities, but not imported users of the entities. That's rather inconvenient. Perhaps we should be enhancing the entity and its users in the other module ahead of time?

Or we could add a way to tell Quarkus to enhance the users from a given module?

@stuartwdouglas any idea what we could do here to mitigate?

**Comment by loicmathieu** [comment] 2020-01-31 06:49
Maybe I'm missing something but as the animal-modue https://github.com/AmsterdamFilho/quarkus-poc/blob/master/modules/animal-module/pom.xml didn't use the Quarkus maven plugin it will not be indexed by Jandex. This is why the entity is not enhanced.

It is even documented on the Panache guide: https://quarkus.io/guides/hibernate-orm-panache#defining-entities-in-external-projects-or-jars

**Comment by machi1990** [comment] 2020-01-31 10:01
> Maybe I'm missing something but as the animal-modue https://github.com/AmsterdamFilho/quarkus-poc/blob/master/modules/animal-module/pom.xml didn't use the Quarkus maven plugin it will not be indexed by Jandex. This is why the entity is not enhanced.

I am seeing the presence of a [`beans.xml`](https://github.com/AmsterdamFilho/quarkus-poc/blob/master/modules/animal-module/src/main/resources/META-INF/beans.xml) file, that should be enough for it to be indexed by Jandex.

**Comment by AmsterdamFilho** [comment] 2020-01-31 11:33
I removed the beans.xml and added the Jandex plugin just to be sure. The index was generated, but the problem persisted.

**Comment by gsmet** [comment] 2020-01-31 11:39
Yeah, it won't solve the issue: with the `beans.xml` everything was already fine. The problem is not about the entity, the entity is properly enhanced, but about the service in which all the callers should be rewritten to use the generated setters.

That's expected considering how we do things. Now we need to figure out if/how we can fix it.

**Comment by gsmet** [comment] 2020-01-31 11:40
@stuartwdouglas I affected this one to you so that you can give us your opinion when you're back.

**Comment by Ladicek** [comment] 2020-03-16 16:34
I just found that I'm hitting this bug as well. My use case for using multiple modules is that I want to build the application for multiple databases, and have each database-specific build produced by a separate Maven module that imports a common `app` dependency and adds just the JDBC driver.

**Comment by stuartwdouglas** [comment] 2020-05-19 02:19
This should have been fixed by https://github.com/quarkusio/quarkus/pull/8973

**Closed by stuartwdouglas** 2020-05-19 02:19 UTC
Labels: area/hibernate-orm, area/panache, kind/bug
