### ISSUE TITLE
qute not handling missing getter well

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#16076] opened 2021-03-28 21:35 UTC
## Describe the bug

if I iterate a map defined without getter i.e.

```
 static public class Catalog {
        Map<String, Alias> aliases;
}
```

and then do:

```
{#each catalog.aliases}
| {item.name} | {item.description} |
{/each}
```

I get this non informative error:
```
io.quarkus.qute.TemplateException: Loop section error in template index on line 4: [catalog.aliases] resolved to [io.quarkus.qute.Results$Result] which is not iterable
	at io.quarkus.qute.LoopSectionHelper.extractIterator(LoopSectionHelper.java:92)
	at io.quarkus.qute.LoopSectionHelper.lambda$resolve$1(LoopSectionHelper.java:41)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at io.quarkus.qute.LoopSectionHelper.resolve(LoopSectionHelper.java:34)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.SectionNode$SectionResolutionContextImpl.execute(SectionNode.java:134)
	at io.quarkus.qute.SectionHelper$SectionResolutionContext.execute(SectionHelper.java:37)
	at io.quarkus.qute.Parser$1.resolve(Parser.java:1023)
	at io.quarkus.qute.SectionNode.resolve(SectionNode.java:34)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData(TemplateImpl.java:107)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsync(TemplateImpl.java:90)
	at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.render(TemplateImpl.java:55)
	at io.quarkus.qute.runtime.TemplateProducer$InjectableTemplateInstanceImpl.render(TemplateProducer.java:155)
	at GreetingService.sayHello(catalog2readme.java:87)
	at catalog2readme.run(catalog2readme.java:55)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at io.quarkus.picocli.runtime.PicocliRunner$EventExecutionStrategy.execute(PicocliRunner.java:26)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at io.quarkus.picocli.runtime.PicocliRunner.run(PicocliRunner.java:39)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:122)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
```

### Expected behavior
I would at first expect qute to just access the field since there is no getter - but i'll open that as separate issue.

second I would expect we can tell the user that it is about `{catalog.aliases}` not being resolvable or similar?,,,

**Comment by mkouba** [comment] 2021-03-29 07:22
> I would at first expect qute to just access the field since there is no getter - but i'll open that as separate issue.

Well, the `aliases` field is not `public` and we mention in the docs several times that non-public members are ignored when generating the value resolver classes. The original idea was that non-public members are not part of the public API and thus not intended to be accessed from templates. We could change this behavior but then the obvious question could follow: if you support package-private then why not private members? And for private members we would break encapsulation completely and a reflection fallback (or other workaround) would be needed. 

> second I would expect we can tell the user that it is about {catalog.aliases} not being resolvable or similar?,,,

The [default strategy](https://quarkus.io/guides/qute-reference#quarkus-qute_quarkus.qute.property-not-found-strategy) is to output the `NOT_FOUND` constant which is not iterable and therefore we throw an error. That said you can use `quarkus.qute.property-not-found-strategy=throw-exception`. Alternatively, you can use the `orEmpty` [built-in resolver](https://quarkus.io/guides/qute-reference#built-in-resolvers) to avoid this particular error.

**Comment by maxandersen** [comment] 2021-03-29 08:42
`if you support package-private then why not private members?` package-private are actually accessible between these classes so I would consider them part of the contract. private I could grok would be off-limits. Isn't it at least possible to have the error message detect the presence of package-private to help user guide them?

if NOT_FOUND is the cause of `[io.quarkus.qute.Results$Result]` showing up in error message I would say we should definitely reconsider the default as it is not a good getting started experience IMO.

Can't NOT_FOUND at least implement a kind of interface to let it explain it was actually not found rather than behaving as something was found and return a cryptic inner class name ?

As a user you shouldn't have to know about `property-not-found-strategy` or putting `orEmpty` on properties that is otherwise accessible.

**Comment by mkouba** [comment] 2021-03-29 09:22
> ...package-private are actually accessible between these classes so I would consider them part of the contract. 

Yes, it's part of the "package" contract. It's questionable whether a template is part of the package but I get your point.

> Isn't it at least possible to have the error message detect the presence of package-private to help user guide them?

The problem is that at its core qute does not care about methods at all. There is a "value resolver" abstraction that can be built on top anything (e.g. extension methods). So if a property is not found then we don't know whether it's a private method or what caused the problem.

But I agree that it's definitely not a good getting started experience. We should probably start with a better error message for this particular use case and consider changing the defaults ;-).

**Comment by maxandersen** [comment] 2021-03-29 09:31
I'll say having come back to qute a few times now using it works pretty damn well, except that I see to always get confused about NOT_FOUND and the related error messages around it.

Like, of all the strategies I think NOT_FOUND is the worst to have as default.

As our goal is to catch errors AND still allow developers to work I feel throw-exception or output-original + possibly a warning log would be better.

But yes, no matter what - handling the error on iterating on NOT_FOUND would be helpful!

**Comment by mkouba** [comment] 2021-03-30 07:28
> Like, of all the strategies I think NOT_FOUND is the worst to have as default.

Well, in my opinion the no-op and output the original expression are the worst strategies.

> As our goal is to catch errors...

We do try to catch errors for type-safe expressions and type-safe templates.

> But yes, no matter what - handling the error on iterating on NOT_FOUND would be helpful!

Let's try to produce a better error message first...

**Comment by maxandersen** [comment] 2021-04-01 04:37
Why is it you think NOT FOUND is better than leave the expression so one can actually quickly see what was not found ?

**Comment by Andro999b** [comment] 2021-04-01 07:39
I think its also related to this `java.lang.ClassCastException: class io.quarkus.qute.Results$Result cannot be cast to class java.lang.String` happen when qute try to access not exists string message

**Comment by mkouba** [comment] 2021-04-12 10:18
> Why is it you think NOT FOUND is better than leave the expression so one can actually quickly see what was not found ?

I belive that it's better for production (the less impl details leak to the end user the better), not so for the dev mode. We could use a different default value for the dev mode but I'm not sure whether it fits the quarkus UX, i.e. whether we change the default value based on the profile?

**Comment by mkouba** [comment] 2021-04-12 10:20
> I think it also related to this `java.lang.ClassCastException: class io.quarkus.qute.Results$Result cannot be cast to class java.lang.String` happen when qute try to access not exists string message

Hi @Andro999b, where did you observe this exception? A reproducer would be helpful...

**Comment by mkouba** [comment] 2021-08-12 11:56
I'm going to close this issue.

1. The actual error message for the original snippet is currently:
`Property "aliases" not found on the base object "io.quarkus.qute.Catalog" in expression {catalog.aliases} in template 1 on line 1` (because [strict rendering](https://quarkus.io/guides/qute-reference#strict-rendering) is enabled by default and `Catalog#aliases` is not public)
2. If you make the field public then the error message is: `Iteration error in template [1] on line 1: {catalog.aliases} resolved to null, use {catalog.aliases.orEmpty} to ignore this error`
3. The title of the issue itself is a bit misleading ;-)
4. We can keep the https://github.com/quarkusio/quarkus/issues/16077 open for now

**Closed by mkouba** 2021-08-12 11:56 UTC
Labels: kind/bug, area/qute
