### ISSUE TITLE
RuntimeUpdatesProcessor deletes local .env file in devmode in Quarkus 2.9.1.Final

### ISSUE THREAD

**Issue by serahl** [quarkusio/quarkus#25667] opened 2022-05-18 18:34 UTC
### Describe the bug

When starting Quarkus 2.9.1.Final in devmode in a Maven multi-module setup, the devmode restarts itself on the first request and deletes the local .env file in a module.

I pinpointed the source of the error to the following line of code: https://github.com/quarkusio/quarkus/blob/2205bb989655970f4da72b752ff2c2be7c5103cc/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L983

The code was introduced in https://github.com/quarkusio/quarkus/pull/25376 for Quarkus 2.9.1.Final. I cannot reproduce the bug in Quarkus 2.9.0.Final.

### Expected behavior

All "local" .env files inside subfolders should be kept AND processed.
Also, as a failsafe, only files in the "target"-folder should ever be deleted!

### Actual behavior

Some .env files are deleted without a chance to bring them back since most of the time, they are not under version control.

### How to Reproduce?

I attached a small reproducer project:
[test-quarkus-devmode-env-file.zip](https://github.com/quarkusio/quarkus/files/8719222/test-quarkus-devmode-env-file.zip)

The project has two modules: One "a-runnable-module" which simply aggregates other modules and one "common-util" module. The runnable module has a local .env file.

To reproduce, do the following:

1. Start the devmode for the runnable module: `mvn clean package -am -pl a-runnable-module -P devmode`
2. Call any endpoint, e.g. "http://localhost:8080/q/health"
3. Watch Quarkus delete the .env file in the "a-runnable-module"-folder and then restart itself.
4. You can also debug Quarkus and watch line https://github.com/quarkusio/quarkus/blob/2205bb989655970f4da72b752ff2c2be7c5103cc/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L983

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 LTS

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0)

**Comment by mkowa42** [comment] 2022-05-19 17:05
I can confirm this behavior: The same happens if you set `quarkus.config.locations` system property in order to use additional application.properties. While running quarkus dev mode the file(s) getting deleted.

**Comment by maxandersen** [comment] 2022-05-19 18:51
Interesting - why is that code even trying to delete these files anyway ?

**Comment by gsmet** [comment] 2022-05-19 19:19
This needs a quick fix because it's really bad.

Also, we need to be a lot more careful when deleting path. How come we can delete files that are not in an output dir directory?

**Comment by Postremus** [comment] 2022-05-19 19:26
@gsmet 
`This needs a quick fix because it's really bad.`
Current plan is to finish the fix (#25670) this evening.

`How come we can delete files that are not in an output dir directory?`
.env files are being watched as absolute paths, not as relative ones. i.e. These config files are read directly from the project root and not from a resource root, and are therefore not copied to an outputdir.

https://github.com/quarkusio/quarkus/blob/1ecc64781d2269b8dfeb0048dc15442cc96ec947/core/deployment/src/main/java/io/quarkus/deployment/steps/ConfigGenerationBuildStep.java#L277-L280


These lines prepare the path which should be deleted, by resolving outputdir against the watched path:
https://github.com/quarkusio/quarkus/blob/1ecc64781d2269b8dfeb0048dc15442cc96ec947/core/deployment/src/main/java/io/quarkus/deployment/dev/RuntimeUpdatesProcessor.java#L981-L986

If however the watched path is an absolute file, then Path.resolve returns the absolute path. I.e. the .env file in the project root, and not a file in the outputdir.

https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/Path.html#resolve(java.nio.file.Path)
`If the other parameter is an [absolute](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/nio/file/Path.html#isAbsolute()) path then this method trivially returns other. [..]`

**Closed** 2022-05-21 21:14 UTC
Labels: kind/bug, area/devmode, env/windows
