### ISSUE TITLE
Apache POI giving error 'Could not initialize class' in native image

### ISSUE THREAD

**Issue by cjbi** [quarkusio/quarkus#38291] opened 2024-01-19 06:01 UTC
### Describe the bug

in pom.xml I've:
io.quarkiverse.poi:quarkus-poi:2.0.3
when running on native image, an error will occur
```
2024-01-19 05:44:13,746 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-8) HTTP Request to /api/apps/27/items/164:exportData failed, error id: 97bfd904-7986-4988-ac14-bbefb0ae1a60-1: java.lang.NoClassDefFoundError: Could not initialize class java.awt.Toolkit
        at java.desktop@21.0.1/java.awt.Color.<clinit>(Color.java:277)
        at org.apache.poi.hssf.util.HSSFColor$HSSFColorPredefined.<init>(HSSFColor.java:113)
        at org.apache.poi.hssf.util.HSSFColor$HSSFColorPredefined.<clinit>(HSSFColor.java:55)
        at org.apache.poi.hssf.model.InternalWorkbook.createExtendedFormat(InternalWorkbook.java:1385)
        at org.apache.poi.hssf.model.InternalWorkbook.createCellXF(InternalWorkbook.java:871)
        at org.apache.poi.hssf.usermodel.HSSFWorkbook.createCellStyle(HSSFWorkbook.java:1297)
        at org.apache.poi.hssf.usermodel.HSSFWorkbook.createCellStyle(HSSFWorkbook.java:124)
        at tech.wetech.metacode.infrastructure.poi.ExcelDataExporter.title(ExcelDataExporter.java:245)
        at tech.wetech.metacode.infrastructure.poi.ExcelDataExporter.writeSheet(ExcelDataExporter.java:152)
        at tech.wetech.metacode.infrastructure.poi.ExcelDataExporter.exportAppItemData(ExcelDataExporter.java:86)
        at tech.wetech.metacode.application.AppApplicationService.exportAppItemData(AppApplicationService.java:316)
        at tech.wetech.metacode.application.AppApplicationService_Subclass.exportAppItemData$$superforward(Unknown Source)
        at tech.wetech.metacode.application.AppApplicationService_Subclass$$function$$1.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at tech.wetech.metacode.application.AppApplicationService_Subclass.exportAppItemData(Unknown Source)
        at tech.wetech.metacode.application.AppApplicationService_ClientProxy.exportAppItemData(Unknown Source)
        at tech.wetech.metacode.api.AppResource.exportAppItemData(AppResource.java:118)
        at tech.wetech.metacode.api.AppResource$quarkusrestinvoker$exportAppItemData_d6a1e4c98c92f1217fa6da146bf63aa114036809.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@21.0.1/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.1/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:832)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:211)
```
when I'm running my project without native image it is running fine.

### Output of `java -version`

21

### Quarkus version or git rev

3.6.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.5

**Comment by zakkak** [comment] 2024-01-19 06:52
Hi @cjbi I think this should be reported in https://github.com/quarkiverse/quarkus-poi

It would also help if you could provide a reproducer.

cc @gastaldi @melloware

**Comment by geoand** [comment] 2024-01-19 06:58
Closing this here because as @zakkak says, it should be reported in the poi extension's [repo](https://github.com/quarkiverse/quarkus-poi)

**Closed by geoand** 2024-01-19 06:58 UTC
Labels: kind/bug, area/native-image
