### ISSUE TITLE
NPE in native-image compilation when upgrading to 0.22 with rest-client

### ISSUE THREAD

**Issue by mgagliardo91** [quarkusio/quarkus#4134] opened 2019-09-20 15:26 UTC
**Describe the bug**
We currently have a quarkus app at 0.19.1 that uses the `quarkus-smallrye-rest-client` and builds as a native executable successfully.

Recent feature updates have led to finding a bug within `quarkus-smallrye-rest-client` and the decision to upgrade to 0.22.0 which replaces this client with `quarkus-rest-client`. The implementation works great; however, this simple change has led to a regression in the native compilation with the `native-image` command throwing an NPE without any context of why its being thrown.

**Expected behavior**
native image builds successfully when simply upgrading quarkus from 0.19.1 to 0.22.0 and replacing the import for the rest client.

**Actual behavior**
native image fails and throws an NPE

```
INFO[0049] RUN  native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager      -H:ReflectionConfigurationFiles=reflect-config.json -H:ResourceConfigurationFiles=resource-config.json      -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true      -J-Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true      --initialize-at-build-time= -H:InitialCollectionPolicy='com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime'      -jar quarkus-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1      -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets      -H:EnableURLProtocols=http,https --enable-all-security-services      -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace      && cp  -v quarkus-runner /tmp/quarkus-runner 
INFO[0049] cmd: /bin/sh                                 
INFO[0049] args: [-c native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager      -H:ReflectionConfigurationFiles=reflect-config.json -H:ResourceConfigurationFiles=resource-config.json      -J-Dio.netty.leakDetection.level=DISABLED -J-Dvertx.disableDnsResolver=true -J-Dio.netty.noUnsafe=true      -J-Dcom.sun.xml.internal.bind.v2.bytecode.ClassTailor.noOptimize=true      --initialize-at-build-time= -H:InitialCollectionPolicy='com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime'      -jar quarkus-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1      -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:+PrintAnalysisCallTree -H:-AddAllCharsets      -H:EnableURLProtocols=http,https --enable-all-security-services      -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace      && cp  -v quarkus-runner /tmp/quarkus-runner]
[quarkus-runner:92]    classlist:  15,095.21 ms
15:21:04,918 INFO  [com.sun.xml.int.bin.v2.run.ref.opt.AccessorInjector] The optimized code generation is disabled
[quarkus-runner:92]        (cap):   1,058.03 ms
[quarkus-runner:92]        setup:   2,500.09 ms
Printing call tree to /project/reports/call_tree_quarkus-runner_20190920_152107.txt
Printing list of used classes to /project/reports/used_classes_quarkus-runner_20190920_152107.txt
Printing list of used packages to /project/reports/used_packages_quarkus-runner_20190920_152107.txt
Fatal error: java.lang.NullPointerException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:457)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:308)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:446)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:112)
Caused by: java.lang.NullPointerException
	at sun.reflect.UnsafeFieldAccessorImpl.ensureObj(UnsafeFieldAccessorImpl.java:57)
	at sun.reflect.UnsafeQualifiedObjectFieldAccessorImpl.get(UnsafeQualifiedObjectFieldAccessorImpl.java:38)
	at java.lang.reflect.Field.get(Field.java:393)
	at com.oracle.svm.hosted.SecurityServicesFeature.lambda$getConsParamClassAccessor$0(SecurityServicesFeature.java:232)
	at com.oracle.svm.hosted.SecurityServicesFeature.register(SecurityServicesFeature.java:266)
	at com.oracle.svm.hosted.SecurityServicesFeature.beforeAnalysis(SecurityServicesFeature.java:175)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$7(NativeImageGenerator.java:666)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:63)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:666)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:522)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:440)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1
```

**Comment by geoand** [comment] 2019-09-20 15:49
Hi,

Would you be able to supply a small reproducer project? It would go a long way in helping figuring out the root cause of the issue (and even making sure it's still an issue or if it has been addressed already in `master`)

**Comment by gsmet** [comment] 2019-09-20 15:58
@mgagliardo91 just to be sure, you are using the latest GraalVM (`19.2.0.1`)?

**Comment by mgagliardo91** [comment] 2019-09-20 18:30
@gsmet we are using the graal version as defined in the docker image `ubi-quarkus-native-image:19.1.1`. @geoand it would be hard to provide a small reproducer (honestly, the biggest issue here is that I have _no_ idea where this NPE is coming from). I can try to provide a list of dependencies we use, and the graal resource/reflection config we use. The `native-image` command that is run is in the code snipped in the original post.

**Comment by mgagliardo91** [comment] 2019-09-20 18:32
The only changes that caused this NPE is going from quarkus v0.19.1 to v0.22.0, replacing the `smallrye` client with `quarkus-rest-client`, and using the udpated `ubi-quarkus-native-image:19.1.1` to build the native-image. Nothing else has changed in the repo

**Comment by geoand** [comment] 2019-09-20 19:17
It would be awesome to have some kind of cut down version of your application that exhibits this behavior.
Otherwise we'll just be shooting in the dark I'm afraid

**Comment by stephenc** [comment] 2019-10-16 12:45
Ok I got a bit further. I can reproduce this error with maven tooling or with our custom dockerfile that runs native-image directly.

The issue goes away if I disable `https` protocol. (I'm using Quarkus 0.24.0) 

The strange thing is the same dockerfile works just fine on a different project of essentially the same code... this is leading me to suspect some dependency being pulled in might be the cause of the NPE... I'll dig further

**Comment by stephenc** [comment] 2019-10-18 09:06
Ok. I found the line causing the NPE:

```
    static {
        Security.addProvider(new BouncyCastleProvider());
    }
```

**Comment by stephenc** [comment] 2019-10-18 09:14
More specifically, that `static` block in an `@ApplicationScoped` bean

**Comment by stephenc** [comment] 2019-10-18 09:15
If I move the `static` block to our `@ApplicationPath` annotated class, all is fine... going to try hoisting it to the bean constructor

**Comment by stephenc** [comment] 2019-10-18 09:22
ok. it seems to be just trying to initialize bouncy castle from a static block in an application scoped bean. I can initialize bouncy castle in the constructor of the application scoped bean... at least as far as `native-image` is concerned... just need to test the integrated microservice to see if it's all working as it should

**Comment by stephenc** [comment] 2019-10-18 09:47
ok, so I changed the constructor code to do some logging:

```
        if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
            LOGGER.info("BouncyCastle is not already registered, registering...");
            Security.addProvider(new BouncyCastleProvider());
            LOGGER.info("BouncyCastle registered");
        } else {
            LOGGER.info("BouncyCastle is already registered");
        }
```

And here's what I see in the build logs

<img width="1175" alt="Screenshot 2019-10-18 at 10 29 11" src="https://user-images.githubusercontent.com/209336/67083313-d99d6180-f192-11e9-9cc5-943701deb988.png">

Whereas, if I move that to a static block
<img width="1121" alt="Screenshot 2019-10-18 at 10 35 53" src="https://user-images.githubusercontent.com/209336/67083587-516b8c00-f193-11e9-9a4c-73a5d007a147.png">


This could just be a bug in graal... but if I move the static block out of the `@ApplicationScoped` bean and put it in the `@ApplicationPath` we get this...

<img width="1166" alt="Screenshot 2019-10-18 at 10 42 46" src="https://user-images.githubusercontent.com/209336/67084156-511fc080-f194-11e9-9b68-7a274fcb0165.png">

Which leads me to suspect that that it is something about how Quarkus sets up CDI beans that may have changed since 0.19.1 and *that* is what is causing graalvm to barf!

**Comment by mkouba** [comment] 2019-10-21 11:01
@stephenc Now that you know where the NPE comes from could you try to build a simple reproducer? I'll try figure out what the problem is but it would be really useful to know where to start...

**Comment by mkouba** [comment] 2019-10-21 11:33
So a static initializer itself shouldn't be a problem in general. Note that static initializers of the safe classes are called when the native image is built (see https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md), whereas the constructor is invoked when the bean instance is created - the exact timing depends on the bean scoped and in which phase it's called/needed.

**Comment by mkouba** [comment] 2019-10-21 12:03
Actually, we do initialize the whole class hierarchy at build time: https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L175

**Comment by kenfinnigan** [comment] 2019-10-30 20:50
Can you try reproducing with 0.27 and the most recent Graal

**Comment by mkouba** [comment] 2019-12-12 15:07
I'm closing this one. Feel free to reopen if it's still an issue on Quarkus 1.0.0+/GraalVM 19.2.0+.

**Closed by mkouba** 2019-12-12 15:07 UTC
Labels: bug, component:arc
