### ISSUE TITLE
quarkus:dev cannot pick newly added config property

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#1456] opened 2019-03-13 09:51 UTC
If you add new property in microprofile-config.properties in quarkus:dev mode this property is not picked in hot reload.

Reproducer: https://github.com/xstefank/learning-tests/tree/master/quarkus/config-new-prop

**Comment by emmanuelbernard** [comment] 2019-03-14 14:38
Should work, let's check the reproducer to investigate.

**Comment by mkouba** [comment] 2019-03-18 09:18
@xstefank So I've just tried your demo, i.e. run `mvn clean compile quarkus:dev`, add `key2=pong` to the `microprofile-config.properties`, add `@Inject @ConfigProperty(name = "key2") String key` to PingResource and changed the `me.xstefank.PingResource.hello()` to return the injected value and the output is "pong". What exactly should I try to reproduce?

**Comment by xstefank** [comment] 2019-03-18 09:25
@mkouba I've tried it again, and it fails for me as expected. Let me try it with current master, I am on 0.11.0

**Comment by mkouba** [comment] 2019-03-18 09:27
I used 0.11.0 too. What are your steps to reproduce the issue?

**Comment by geoand** [comment] 2019-03-18 09:31
I ran into this same issue a few days ago while doing a demo. I can reproduce the problem both in `0.11.0` and the current `master`.

**Comment by xstefank** [comment] 2019-03-18 09:32
the same as yours, and same as in the readme of the reproducer

**Comment by geoand** [comment] 2019-03-18 09:34
Here is what I did:

Use:

```
@Path("/greeting")
public class GreetingResource {

    @Inject
    @ConfigProperty(name = "testProp")
    private String testProp;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return testProp;
    }
}
```
and 

```
testProp = asdf
```

Execute:

```
mvn clean compile
mvn quarkus:dev
```

`http://localhost:8080/greeting` correctly returns: `asdf`

Add `testProp2 = hello` to `microprofile-config.properties`.

change `@ConfigProperty(name = "testProp")` to `@ConfigProperty(name = "testProp2")`.
When doing that I get:

```
Caused by: java.lang.IllegalStateException: No config value exists for: testProp2
```

**Comment by mkouba** [comment] 2019-03-18 09:42
Hm, that's weird. Just tried several more times with no problem. Does it occur intermittently or every time you run the app?

**Comment by geoand** [comment] 2019-03-18 09:43
For me it happens everytime

**Comment by xstefank** [comment] 2019-03-18 09:45
yes, same for me

**Comment by mkouba** [comment] 2019-03-18 09:52
Ok gentlemen, pls tell me something about your configuration: jdk, maven, os, ... Also is the hot replacement triggered after you hit the resource? You should see something like `Hot replace total time: 0.462s ` in the console.

**Comment by geoand** [comment] 2019-03-18 09:54
```
Maven home: /home/gandrian/.sdkman/candidates/maven/current
Java version: 1.8.0_202, vendor: Azul Systems, Inc., runtime: /home/gandrian/.sdkman/candidates/java/8.0.202-zulu/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-16-generic", arch: "amd64", family: "unix"

```

**Comment by geoand** [comment] 2019-03-18 09:55
```
2019-03-18 11:55:38,569 INFO  [io.qua.dev] (XNIO-1 task-1) Changes source files detected, recompiling [/home/gandrian/Desktop/newprop/src/main/java/org/acme/config/GreetingResource.java]
2019-03-18 11:55:38,873 INFO  [io.quarkus] (XNIO-1 task-1) Quarkus stopped in 0.001s
2019-03-18 11:55:38,874 INFO  [io.qua.dep.QuarkusAugmentor] (XNIO-1 task-1) Beginning quarkus augmentation
2019-03-18 11:55:38,926 ERROR [io.qua.dev.DevModeMain] (XNIO-1 task-1) Failed to start quarkus: java.lang.RuntimeException: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: No config value exists for: testProp2
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:134)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:121)
        at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:148)
        at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:87)
        at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:54)
        at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:35)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
        at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: No config value exists for: testProp2
        at org.jboss.builder.Execution.run(Execution.java:123)
        at org.jboss.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:136)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:102)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:99)
        ... 12 more
Caused by: javax.enterprise.inject.spi.DeploymentException: java.lang.IllegalStateException: No config value exists for: testProp2
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:624)
        at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:256)
        at io.quarkus.arc.processor.BeanProcessor.process(BeanProcessor.java:160)
        at io.quarkus.arc.deployment.ArcAnnotationProcessor.build(ArcAnnotationProcessor.java:243)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:435)
        at org.jboss.builder.BuildContext.run(BuildContext.java:413)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.IllegalStateException: No config value exists for: testProp2
        at io.quarkus.arc.deployment.ConfigBuildStep$ConfigBeanDeploymentValidator.validate(ConfigBuildStep.java:97)
        at io.quarkus.arc.processor.BeanDeployment.validate(BeanDeployment.java:253)
        ... 14 more

2019-03-18 11:55:38,927 INFO  [io.qua.dev] (XNIO-1 task-1) Hot replace total time: 0.360s 

```

**Comment by geoand** [comment] 2019-03-18 09:58
I should also add than when I simplu change the value of `testProp` (as opposed to adding a new property) hot reload works as expected

**Comment by geoand** [comment] 2019-03-18 10:03
@mkouba If you think a quick call would help in debugging the issue, I'd be happy to do it

**Comment by mkouba** [comment] 2019-03-18 10:50
Hm, I think that it could be related to the fact that we replace the MP Config "data" during various phases of bootstrap... so it might be some sort of timing issue. @dmlloyd David could pls shed some light on this?  

In any case,  the validation in [ConfigBuildStep](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java#L32) **is wrong** because it can only validate static config properties, e.g. it could fail for runtime properties (system properties, environment properties, etc.). On the other hand, we have to valide all the `@ConfigProperty` injection points (MP Config requirement). So we'll have to collect all the injetion points during augmentation but run the validation at RUNTIME_INIT. Which is not very good because A) we will not fail fast and B) we'll prolong the startup time...

**Comment by mkouba** [comment] 2019-03-18 11:48
https://github.com/quarkusio/quarkus/issues/1555

**Comment by dmlloyd** [comment] 2019-03-18 12:58
> Hm, I think that it could be related to the fact that we replace the MP Config "data" during various phases of bootstrap... so it might be some sort of timing issue. @dmlloyd David could pls shed some light on this?

There's not a lot to say (after #1478): the build configuration is set up by consuming config sources, converters, etc. and then producing (and installing) the config object.  At run time, we parse the configuration and install the config object in a very similar way (though we use a couple of fixed config sources containing properties copied from the build `application.properties` and preset defaults from extensions).

> In any case, the validation in [ConfigBuildStep](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/deployment/src/main/java/io/quarkus/arc/deployment/ConfigBuildStep.java#L32) **is wrong** because it can only validate static config properties, e.g. it could fail for runtime properties (system properties, environment properties, etc.). On the other hand, we have to valide all the `@ConfigProperty` injection points (MP Config requirement). So we'll have to collect all the injetion points during augmentation but run the validation at RUNTIME_INIT. Which is not very good because A) we will not fail fast and B) we'll prolong the startup time...

I don't think you'll prolong the startup time in any significant manner, especially if the config part is just: read config value, store in field, read config value, store in field, etc.

**Comment by mkouba** [comment] 2019-03-18 13:25
> I don't think you'll prolong the startup time in any significant manner, especially if the config part is just: read config value, store in field, read config value, store in field, etc.

In this particular case, we'll have to collect all mandatory `@ConfigProperty` injection points (property name + type) and record a template method to validate that a config property for each recorded injection point is present. The performance impact should be negligible. But still, one thousand similar "features" and we're back where we were ;-).

Ok, I didn't know about the next big config PR. @xstefank @geoand So the plan is to merge https://github.com/quarkusio/quarkus/pull/1478 and fix https://github.com/quarkusio/quarkus/issues/1555. Afterwards, we should test the problem again. Does it make sense?

**Comment by geoand** [comment] 2019-03-18 13:29
@mkouba makes perfect sense for me

**Comment by xstefank** [comment] 2019-03-18 13:38
@mkouba yes, same here, just ping us please when to test again

**Comment by mkouba** [comment] 2019-03-20 12:55
@geoand @xstefank PRs merged, could you pls re-test?

**Comment by geoand** [comment] 2019-03-20 12:59
@mkouba on it

**Comment by geoand** [comment] 2019-03-20 13:09
Still the same issue for me @mkouba.

```
java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl3.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:93)
	at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:119)
	at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:105)
	at io.quarkus.dev.DevModeMain.restartApp(DevModeMain.java:132)
	at io.quarkus.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:87)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:56)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:37)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1998)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1525)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1416)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.enterprise.inject.spi.DeploymentException: No config value of type class java.lang.String exists for: greeting.other
	at io.quarkus.arc.runtime.ConfigDeploymentTemplate.validateConfigProperties(ConfigDeploymentTemplate.java:45)
	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigProperties26.deploy(Unknown Source)
	... 15 more
```

**Comment by mkouba** [comment] 2019-03-20 13:14
Hm, very strange. @geoand what's your maven version?

**Comment by geoand** [comment] 2019-03-20 13:17
@mkouba 

```
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T21:33:14+03:00)
Maven home: /home/gandrian/.sdkman/candidates/maven/current
Java version: 1.8.0_202, vendor: Azul Systems, Inc., runtime: /home/gandrian/.sdkman/candidates/java/8.0.202-zulu/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.18.0-16-generic", arch: "amd64", family: "unix"

```

**Comment by mkouba** [comment] 2019-03-20 16:12
So I was able to reproduce the issue when modifying the properties file and the java class in an external editor and not in my IDE - Quarkus did not check for config file changes if a class change was detected and as a result, the config file was not updated (i.e. copied to `target/classes`). AFAIK Eclipse Maven integration copies files from `src/main/resources` to `target/classes` automatically and that's probably the reason why it cannot be easily reproduced in Eclipse.

@geoand @xstefank It would be great if you could verify my fix in https://github.com/quarkusio/quarkus/pull/1598.

**Comment by geoand** [comment] 2019-03-20 16:25
@mkouba I tested it and it works ( and I am using IntelliJ FWIW :) )

**Comment by xstefank** [comment] 2019-03-20 17:52
@mkouba +1 fixed with you PR. Thanks!

**Comment by mkouba** [comment] 2019-03-20 20:34
That's great, thanks for verification!

**Closed** 2019-03-21 10:29 UTC
Labels: bug, config, dev-mode

**Comment by ImShivamSrivastav** [comment] 2024-03-22 06:07
Hi @dmlloyd @mkouba @gsmet I am not getting correct value in my code  @ConfigProperty(
        name = "permission.checking.enabled"
    )
    Boolean permissionCheckerEnabled; in my application.prop file i have mention permission.checking.enabled=false but still I didnt get the correct value which is false in my permissionCheckerEnabled, could you please explain this?Thanks
