### ISSUE TITLE
@Produces(MediaType.SERVER_SENT_EVENTS) is necessary when using server side event

### ISSUE THREAD

**Issue by ryime** [quarkusio/quarkus#32012] opened 2023-03-21 15:18 UTC
### Describe the bug

According to the [documentation](https://quarkus.io/guides/resteasy-reactive#server-sent-event-sse-support) : 

_by using @RestStreamElementType, we don't need to add @Produces(MediaType.SERVER_SENT_EVENTS)_

But it's necessary when using `quarkus-rest-client-reactive-jackson` 

Here is the controller : 
````
 @GET
 @Blocking
 @RestStreamElementType(MediaType.APPLICATION_JSON)
 @Path("/items")
  public Multi<Items> getPaginateItems() {
        return searchService.getAllItems();
    }
````

Here is the rest client :

````
@GET
@Path("/items")
@Produces(MediaType.SERVER_SENT_EVENTS)
Multi<Items> getPaginateItems();
````

As a workaround, we added  `@Produces(MediaType.SERVER_SENT_EVENTS)` in addition of `@RestStreamElementType(MediaType.APPLICATION_JSON)` in the server side.

### Expected behavior

Items are retrieved with status 200

### Actual behavior

When the rest client is used the following exception occures:

```
javax.ws.rs.NotAcceptableException: The accept header value did not match the value in @Produces
	at org.jboss.resteasy.reactive.server.handlers.ClassRoutingHandler.handle(ClassRoutingHandler.java:136)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:96)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:145)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:48)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:23)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:10)
```

### How to Reproduce?

Steps to reproduce the error : 

1. Create an endpoint with `@RestStreamElementType(MediaType.APPLICATION_JSON)` and without `@Produces(MediaType.SERVER_SENT_EVENTS)`
2. Create a external service with a rest client that refers to this endpoint with `@Produces(MediaType.SERVER_SENT_EVENTS)`
3. The external service calls the endpoint

### Output of `java -version`

java version "19.0.1" 2022-10-18

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by geoand** [comment] 2023-03-21 15:30
Yeah, the documentation refers to the server part. @Sgitario do you think we could apply the same simplification for the client?

**Comment by Sgitario** [comment] 2023-03-22 08:38
I think this is doable. Assigning this feature to me.

**Comment by Sgitario** [comment] 2023-03-22 08:54
Sorry, but I can't reproduce what you mention. For me, it's working fine without using `@Produces(MediaType.SERVER_SENT_EVENTS)` using Quarkus 2.16.4.Final and Quarkus 3 main. 

Can you provide a simple reproducer?

**Comment by gsmet** [comment] 2023-03-22 12:08
Ah maybe `@RestStreamElementType` doesn't override a class level `@Produces`? That's probably something we should support, don't you think @Sgitario ?

**Comment by Sgitario** [comment] 2023-03-22 13:56
Yes, according to the documentation, this makes total sense. https://github.com/quarkusio/quarkus/pull/32038 addresses this issue.

**Comment by ryime** [comment] 2023-03-22 16:01
Thank you for your quick reaction !

**Closed** 2023-03-23 08:28 UTC
Labels: kind/enhancement, area/rest-client
