### ISSUE TITLE
Unable to override config properties for Isolates running in native mode

### ISSUE THREAD

**Issue by AndreiYu** [quarkusio/quarkus#14089] opened 2021-01-04 08:44 UTC
**Describe the bug**
The code, that relies on Isolates running in Native image is unable to catch overridden config properties (either passed as command line arguments when launching native executable or overriding properties with `QuarkusTestResourceLifecycleManager` in Native tests).
It seems Isolates use the values of properties that are effective at image build time and do not override them in runtime.

**Expected behavior**
Isolates use the values of properties that are effective at  runtime (as Native-image code without isolates does).

**Actual behavior**
Isolates use the values of properties that are effective at build time and do not override at runtime.

**To Reproduce**

```
	public int readPropertyValue() {
		var params = CreateIsolateParameters.getDefault();
		var isolateThread = Isolates.createIsolate(params);

		try {
			return processInIsolate(isolateThread);
		}
		finally {
			Isolates.tearDownIsolate(isolateThread);
		}

	}

	@CEntryPoint
	private static int processInIsolate(@CEntryPoint.IsolateThreadContext IsolateThread isolateThread) {
		int propertyToOverride = ConfigProvider.getConfig().getValue("property.to.override", Integer.class);
		System.out.println("property.to.override: " + propertyToOverride);

		return propertyToOverride;
	}
```

Demo app, reproducing the bug

https://github.com/AndreiYu/isolates-native-image-testing-bug/blob/master/src/native-test/java/com/example/config/NativeTest.java

1.  run `./gradlew testNative `for demo app
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```
```
quarkus:
  package:
    type: native
  native:
    native-image-xmx: 12g

property:
  to:
    override: 0
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin MacBook-Pro.local 20.2.0 Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  
 - GraalVM version (if different from Java):  20.2.0.r11-grl     
 - Quarkus version or git rev: 1.10.5.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): gradle 6.5.1

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment] 2021-01-04 19:03
I don't think we suppose Isolates for now and I'm not sure we plan to support them.

**Comment by Karm** [comment] 2022-01-10 09:42
@zakkak Do you have any opinion on this one? I don't have any test app for that.

**Comment by AndreiYu** [comment] 2022-01-20 13:20
We made a workaround - CustomRuntimeConfigSource that has higher ordinal than System properties and Environment Variables

https://quarkus.io/guides/config-extending-support#example

Isolates are unable to see changes of system properties (since they have a snapshot of Image Heap at build or start time of native executable), but isolate refreshes env_variable changes with CustomRuntimeConfigSource with ordinal 500 and evaluates them at change. Here is a snippet of code:

@StaticInitSafe
public class RuntimeEnvConfigSource implements ConfigSource {

	@Override
	public Map<String, String> getProperties() {
		return System.getenv();
	}

	@Override
	public Set<String> getPropertyNames() {
		return System.getenv().keySet();
	}

	@Override
	public int getOrdinal() {
		return 500;
	}

	@Override
	public String getValue(String name) {
		if (name == null) {
			return null;
		}

		// exact match
		var data = System.getenv();
		String value = data.get(name);
		if (value != null) {
			return value;
		}

		// replace non-alphanumeric characters by underscores
		String sanitizedName = replaceNonAlphanumericByUnderscores(name);
		value = data.get(sanitizedName);
		if (value != null) {
			return value;
		}

		// replace non-alphanumeric characters by underscores and convert to uppercase
		return data.get(sanitizedName.toUpperCase());
	}

	@Override
	public String getName() {
		return RuntimeEnvConfigSource.class.getSimpleName();
	}
}

**Comment by zakkak** [comment] 2022-01-28 07:58
@AndreiYu as you said:

> Isolates are unable to see changes of system properties (since they have a snapshot of Image Heap at build or start time of native executable)

[According to Christian Wimmer](https://github.com/oracle/graal/issues/4238#issuecomment-1023537496), this is the intended behavior. So I think we can close this issue if you agree.

Could you please point me to the documentation stating that:

> isolate refreshes env_variable changes with CustomRuntimeConfigSource with ordinal 500 and evaluates them at change

if there is no such documentation it would probably be worth adding :)

**Comment by AndreiYu** [comment] 2022-01-28 08:54
@zakkak
What the workaround mentioned above resolves - just places `Environment variables `(500) above `System properties` (400) in Quarkus.
Isolates read Environment variables by calling native code and retrieving them from underlying OS each time they are needed, so env variables can be changed at runtime even for Isolates (as opposed to System properties which are handled by Isolates at build time or start time).
Don't know if it's appropriable: but if Quarkus replaces `System Properties(400) -> Environment Variables from System (300)` with` Environment Variables from System (400)  -> System Properties(300)` it could make Isolates work, but can break  older apps logic when they are updated to newer Quarkus.
If there was an optional config which could override These ordinals, it could be better, what do you think? 
https://quarkus.io/guides/config-extending-support#:~:text=the%20275%20ordinal%3A-,ConfigSource,-Ordinal

**Comment by zakkak** [comment] 2022-11-29 12:34
> Don't know if it's appropriable: but if Quarkus replaces `System Properties(400) -> Environment Variables from System (300)` with` Environment Variables from System (400) -> System Properties(300)` it could make Isolates config retrieval work, but can break older apps logic when they are updated to newer Quarkus.
> If there was an optional config (or configmap) which could override these ordinals and allow deside the developer which configs sources will have which priorities, it could be better, what do you think?

I really don't know. @gsmet @geoand WDYT? (please ping someone more knowledgeable on the matter if you don't know as well)

**Comment by geoand** [comment] 2022-11-29 12:50
cc @radcortez

**Comment by radcortez** [comment] 2022-11-30 10:47
We cannot change the ordinals of System Properties and Environment Variables because the MP Config specification sets them.

But you can override the ordinal of each source if you set `config.ordinal=500` or `CONFIG_ORDINAL=500`. The `config.ordinal` is a unique property that only applies to the source where it was set to override that source ordinal.

**Comment by zakkak** [comment] 2023-11-23 11:41
@AndreiYu I am closing this as won't fix since there doesn't seem to be something we can do on the Quarkus side.

**Closed by zakkak** 2023-11-23 11:41 UTC
Labels: kind/enhancement, area/native-image
