### ISSUE TITLE
Kafka Guide does not work

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2176] opened 2019-04-22 19:56 UTC
I followed the steps in the Kafka Guide in https://quarkus.io/guides/kafka-guide and when I open the page, all I get is 
```
Last price

The last price is N/A €.
```

You can see that the connection closes prematurely if you use HTTPie to connect to `/prices/stream` as in:
 
```http --stream -f localhost:8080/prices/stream -v```
 
By debugging and comparing to the quickstart in https://github.com/quarkusio/quarkus-quickstarts/tree/master/kafka-quickstart (which works btw), the only missing part (and what makes the guide work) is to add the following code to the `PriceResource`:

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
```

See: https://github.com/quarkusio/quarkus-quickstarts/blob/master/kafka-quickstart/src/main/java/org/acme/quarkus/sample/PriceResource.java#L21-L25

**Comment by gsmet** [comment] 2019-04-23 14:24
We merged a work around in the guide but we need to get to the bottom of this as it definitely doesn't look like normal.

**Comment by jaikiran** [comment] 2019-09-23 14:17
There appear to be a couple of issues going on here.

The root cause of this issue seems to be that in the absence of that above workaround (where a `@GET` `@Produces(TEXT_PLAIN)` is added), the `io.quarkus.resteasy.server.common.deployment.ResteasyServerCommonProcessor` isn't registering some of the (MessageWriter) `Provider`(s) (one of them being `org.jboss.resteasy.plugins.providers.DefaultNumberWriter`). Because of that, at runtime, when the streaming URL resource is requested, it runs into this exception:
```
2019-09-23 19:40:03,939 DEBUG [org.jbo.res.res.i18n] (vert.x-eventloop-thread-1) RESTEASY002030: Failed to write event org.jboss.resteasy.plugins.providers.sse.OutboundSseEventImpl@6ab5d8af: javax.ws.rs.ServerErrorException: RESTEASY004082: No suitable message body writer for class : java.lang.Double
	at org.jboss.resteasy.plugins.providers.sse.SseEventProvider.writeTo(SseEventProvider.java:111)
	at org.jboss.resteasy.plugins.providers.sse.SseEventProvider.writeTo(SseEventProvider.java:28)
	at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.writeEvent(SseEventOutputImpl.java:262)
	at org.jboss.resteasy.plugins.providers.sse.SseEventOutputImpl.send(SseEventOutputImpl.java:199)
	at org.jboss.resteasy.core.AsyncResponseConsumer$AsyncGeneralStreamingSseResponseConsumer.sendBuiltResponse(AsyncResponseConsumer.java:553)
	at org.jboss.resteasy.core.AsyncResponseConsumer.internalResume(AsyncResponseConsumer.java:115)
	at org.jboss.resteasy.core.AsyncResponseConsumer$AsyncStreamResponseConsumer.addNextElement(AsyncResponseConsumer.java:299)
	at org.jboss.resteasy.core.AsyncResponseConsumer$AsyncGeneralStreamingSseResponseConsumer.addNextElement(AsyncResponseConsumer.java:492)
	at org.jboss.resteasy.core.AsyncResponseConsumer$AsyncStreamResponseConsumer.onNext(AsyncResponseConsumer.java:308)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.lambda$onNext$2(ContextPropagatorOnFlowableCreateAction.java:50)
	at io.smallrye.context.SmallRyeThreadContext.lambda$withContext$0(SmallRyeThreadContext.java:215)
	at io.smallrye.context.propagators.rxjava2.ContextPropagatorOnFlowableCreateAction$ContextCapturerFlowable.onNext(ContextPropagatorOnFlowableCreateAction.java:50)
```
and thus closes the connection. Interestingly this exception is just logged, that too at DEBUG level (I had to enable these levels in application.properties):
```
quarkus.log.category."io.quarkus".level=TRACE
quarkus.log.category."org.jboss".level=TRACE
```
So the root cause appears to be the `ResteasyServerCommonProcessor` skips registering some providers when only `@Produces({MediaType.SERVER_SENT_EVENTS})` is present on a resource. Someone with more knowledge of JaxRS might have to look at whether this is the right thing to do or if something more needs to be done.

The other related issue that might need tracking is, why that exception just gets logged at DEBUG without providing any hint on what went wrong.

**Comment by gsmet** [comment] 2019-09-23 14:58
@jaikiran nice detective work. Indeed, that's not the first time I see the issue: the root of it is that we only register the producers we use and in this very case we don't use either the JSON one or the `TextStar` one.

Is it still an issue with master? Because I added some default providers in master via this commit: https://github.com/quarkusio/quarkus/commit/7fd45c42dfaab3074cb943a5cdbb08996ce3dcce#diff-7305a4607283d4aafc868f2b2ac3359e .

**Comment by jaikiran** [comment] 2019-09-23 15:42
Hi @gsmet, I haven't yet tried this with master. I will give it a try tomorrow.

**Comment by jaikiran** [comment] 2019-09-23 17:01
Hi @gsmet, I quickly gave the upstream master a try with the quickstart. It still runs into the same issue and still requires that workaround. So I went ahead and borrowed your idea to register some of these commonly needed providers by default and created this PR https://github.com/quarkusio/quarkus/pull/4163. With that change, I was able to get the Kafka guide working fine without the necessity of that workaround.

**Comment by kenfinnigan** [comment] 2019-09-23 17:37
Rather than registering providers that may not be needed, why not fail the deployment if there's no `@Produces` present?

My concern would be we keep adding "edge case" providers and defeat the purpose of DCE.

**Comment by gsmet** [comment] 2019-09-23 17:55
Yeah, the `text/*` and JSON providers were added for the purpose of the error pages. We consider that they should always be there if active. We really don't want to add all the providers around.

I think adding the `text/plain` provider could make sense too... what I'm a bit unsure is if it makes sense to have something like `@Produces({MediaType.SERVER_SENT_EVENTS, MediaType.TEXT_PLAIN}) ` and how RESTEasy behaves in this case.

If it's the blessed solution for RESTEasy, I think I would prefer that, but I could be convinced that having the `text/plain` provider by default could be useful anyway.

**Comment by gsmet** [comment] 2019-09-23 20:04
@asoldano @patriot1burke @cescoffier any chance you could help us about best practices regarding SSE and `@Produces`?

**Comment by jaikiran** [comment] 2019-09-24 05:19
> My concern would be we keep adding "edge case" providers and defeat the purpose of DCE.

I agree. That blind addition of providers kind of defeats the purpose of doing selective additions, even if the provider is a common one. 
This is such a basic use case (IMO) that I felt there should be some other way to deal with it without hacks. So last night, I looked into the internals of RestEasy a bit and I think I found a better way (spec compliant) of dealing with this. Based on that understanding, I have opened a new PR https://github.com/quarkusio/quarkus/pull/4167 which I think deals with this better.

Using this fix, I can now have the quickstart working fine without that previous workaround. The change required in the quickstart will now look like this: (notice the `@Produces` that's now changed on that method):
```
@Path("/prices")
public class PriceResource {

    @Inject
    @Stream("my-data-stream") Publisher<Double> prices;

    @GET
    @Path("/stream")
    @Produces("text/event-stream;element-type=text/plain")
    public Publisher<Double> stream() {
        return prices;
    }
}
```
My knowledge around RestEasy is limited and this change is based on a quick look at the RestEasy internal code, so this may not be perfect. In fact, we might even have to consider similar case for "MessageReader(s)" (a.k.a `@Consumes` etc...) but at least for the issue at hand, this seems to help. @kenfinnigan @gsmet, what are your thoughts about this change? Does this look fine?

**Comment by cescoffier** [comment] 2019-09-26 12:26
Why can we just use the combination of `@Produces` (indicating SSE) and `@SseElementType` indicating Double?

**Comment by jaikiran** [comment] 2019-09-26 14:32
Hi @cescoffier, the PR https://github.com/quarkusio/quarkus/pull/4167, adds that exact support. Once that's merged and released, the quickstart can be updated.

**Closed** 2019-09-30 23:27 UTC

**Comment by jaikiran** [comment] 2019-10-01 03:37
I've openede a PR in the quickstarts repo to remove the previously added workaround https://github.com/quarkusio/quarkus-quickstarts/pull/298

**Comment by serranisimo** [comment] 2020-01-28 12:25
I built an applictaion based on the same tutorial and have a very similar Problem. The application functions correctly when the type being returned by the resource is primitive (e.g. String). As soon as I work with objects the same problem occurs: **"Failed to write event org.jboss.resteasy.plugins.providers.sse.OutboundSseEventImpl@51eb8c1b: javax.ws.rs.ServerErrorException: RESTEASY004082: No suitable message body writer for class : org.acme.quarkus.sample.fruit.Fruit"** :

```
@Path("/fruits")
public class FruitPriceResource {

    Logger LOG = LoggerFactory.getLogger(FruitPriceResource.class);

    @Inject
    @Channel("fruit-out")
    Publisher<Fruit> fruits;

    @GET
    @Path("/stream")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @SseElementType(MediaType.APPLICATION_JSON)
    public Publisher<Fruit> stream() {
        return fruits;
    }
} 
```
The application is in this repository. Here you can find the working example with a Publisher<String> as well as the one with the Fruit object (the one not working).
Repository: [https://github.com/serranisimo/kafka-json](url)
