### ISSUE TITLE
vertx-blocked-thread-checker - Quarkus on Kubernetes

### ISSUE THREAD

**Issue by Bilel-NEJI** [quarkusio/quarkus#25968] opened 2022-06-06 00:37 UTC
### Describe the bug

Hello,
After deploying my app on kubernetes, the Quarkus backend (with graphql) , the Angular frontend, and the Postgresql databese all three of them are running in pods.
First of all, I was exposing the backend and the frontend pods with nodeports, so I type Node IP-address in the url and bang !! --> the frontend can send a request to the backend and I have a feedback.

When I passed to implement an ingress-controller (bellow) and after setting a clusterip for the backend and a DNS.

```
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-ingress
  namespace: namespacename
spec:
  ingressClassName: nginx-internal
  rules:
  - host: bilels.rd.company.tn
    http:
      paths:
      - path: /
        backend:
          service:
            name: my-frontend
            port:
              number: 80
        pathType: Prefix
      - path: /here
        backend:
          service:
            name: my-backend
            port:
              number: 443
        pathType: Prefix
```

Then I open directly the GUI without waiting the finale logs (of the quarkus pod) and I send a GraphQL request from Angular **I get this in the browser's console:**
```
DevTools failed to load source map: Could not load content for chrome-extension://cofdbpoegempjloogbagkncekinflcnj/build/content.js.map: System error: net::ERR_BLOCKED_BY_CLIENT
POST https://bilels.rd.company.tn/here/graphql 503
ERROR Error: Http failure response for https://bilels.rd.company.tn/here/graphql: 503 OK
    at new t (main.f8bdd811da4b7378.js:1:508785)
    at main.f8bdd811da4b7378.js:1:546669
    at _ (main.f8bdd811da4b7378.js:1:502485)
    at main.f8bdd811da4b7378.js:1:502411
    at new t (polyfills.847866961ab00d50.js:1:18350)
    at Object.then (main.f8bdd811da4b7378.js:1:502378)
    at Object.error (main.f8bdd811da4b7378.js:1:502495)
    at kk (main.f8bdd811da4b7378.js:1:464915)
    at zy (main.f8bdd811da4b7378.js:1:465420)
    at t.error (main.f8bdd811da4b7378.js:1:465981)
```

**And the logs for the backend pod with Lens software:**
```
	Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xms87m -Xmx349m -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\__
2022-06-02 18:10:20,705 WARN  [io.qua.net.run.NettyRecorder] (Thread-0) Netty DefaultChannelId initialization (with io.netty.machineId system property set to 06:ce:0c:92:14:a5:83:3f) took more than a second
2022-06-02 18:11:29,707 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 8.4.2 by Redgate
2022-06-02 18:11:29,708 INFO  [org.fly.cor.int.dat.bas.BaseDatabaseType] (main) Database: jdbc:postgresql://postgres:5432/dbmcsthirdparty (PostgreSQL 14.3)
2022-06-02 18:11:33,905 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
2022-06-02 18:11:33,907 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary.
2022-06-02 18:12:00,409 WARN  [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2201 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:125)
	at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:100)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:217)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:149)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:154)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:1067)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:1009)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$429/0x0000000840423840.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$430/0x0000000840423440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:163)
	at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:100)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:217)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:149)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:154)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:1067)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:1009)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$429/0x0000000840423840.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$430/0x0000000840423440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:125)
	at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:100)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:217)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:149)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:154)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:1067)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:1009)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$429/0x0000000840423840.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$430/0x0000000840423440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper$$Lambda$439/0x000000084045fc40.handle(Unknown Source)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:71)
	at io.vertx.core.net.impl.TCPServerBase.listen(TCPServerBase.java:169)
	at io.vertx.core.net.impl.TCPServerBase.bind(TCPServerBase.java:100)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:217)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:149)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:154)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:1067)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:1009)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.DeploymentManager$$Lambda$429/0x0000000840423840.handle(Unknown Source)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$430/0x0000000840423440.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@11.0.14.1/java.lang.Thread.run(Thread.java:829)
2022-06-02 18:12:11,807 INFO  [io.quarkus] (main) back-mcs-thirdparty 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.3.Final) started in 252.302s. Listening on: http://0.0.0.0:8080
2022-06-02 18:12:12,006 INFO  [io.quarkus] (main) Profile prod activated. 
2022-06-02 18:12:12,006 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, kubernetes, kubernetes-client, narayana-jta, resteasy-jackson, resteasy-jsonb, smallrye-context-propagation, smallrye-graphql, vertx]
```

I tried to resolve it by adding the following property ``` quarkus.vertx.max-event-loop-execute-time=5000 ``` to the ``` application-properties ```
This time I waited until having all the logs, knowing that the logs come in parts with a time delay that cannot be ignored between them (50-60 sec)

```
Starting the Java application using /opt/jboss/container/java/run/run-java.sh ...
INFO exec  java -Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Xms87m -Xmx349m -XX:+UseParallelGC -XX:MinHeapFreeRatio=10 -XX:MaxHeapFreeRatio=20 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -XX:ParallelGCThreads=1 -Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -XX:CICompilerCount=2 -XX:+ExitOnOutOfMemoryError -cp "." -jar /deployments/quarkus-run.jar
**delay here**
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-06-06 00:02:57,406 WARN  [io.qua.net.run.NettyRecorder] (Thread-0) Netty DefaultChannelId initialization (with io.netty.machineId system property set to 30:e6:9e:4e:4a:a6:c5:35) took more than a second
2022-06-06 00:04:07,409 INFO  [org.fly.cor.int.lic.VersionPrinter] (main) Flyway Community Edition 8.4.2 by Redgate
2022-06-06 00:04:07,705 INFO  [org.fly.cor.int.dat.bas.BaseDatabaseType] (main) Database: jdbc:postgresql://postgres:5432/dbmcsthirdparty (PostgreSQL 14.3)
2022-06-06 00:04:14,613 INFO  [org.fly.cor.int.com.DbMigrate] (main) Current version of schema "public": 1
2022-06-06 00:04:15,105 INFO  [org.fly.cor.int.com.DbMigrate] (main) Schema "public" is up to date. No migration necessary. 
**delay here**
2022-06-06 00:05:03,307 INFO  [io.quarkus] (main) back-mcs-thirdparty 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.7.3.Final) started in 265.900s. Listening on: http://0.0.0.0:8080
2022-06-06 00:05:03,606 INFO  [io.quarkus] (main) Profile prod activated. 
2022-06-06 00:05:03,607 INFO  [io.quarkus] (main) Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-orm-panache, jdbc-postgresql, kubernetes, kubernetes-client, narayana-jta, resteasy-jackson, resteasy-jsonb, smallrye-context-propagation, smallrye-graphql, smallrye-openapi, swagger-ui, vertx]
```

Also after displaying these logs, I have the error bellow in the browser console:
```
Unchecked runtime.lastError: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was received
```

so I continue and send a request from the GUI and I got the same error message in the browser console. --> 503 again and no new logs for the backend pod

### Expected behavior

I expect a response from the backend pod

### Actual behavior

The error code 503 appears when I send a request

### How to Reproduce?

I can share 

### Output of `uname -a` or `ver`

Kubernetes, win 10 (machine)

### Output of `java -version`

java 11

### Quarkus version or git rev

2.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by geoand** [comment] 2022-06-06 00:39
What does the code look like?

**Comment by Bilel-NEJI** [comment] 2022-06-07 10:04
I already sent the link of the GitHub repo. via Zulip

**Comment by iocanel** [comment] 2022-06-07 10:46
@Bilel-NEJI: Can you please provide that here too?

**Comment by Sgitario** [comment] 2023-03-09 12:02
I guess the zulip channel you mentioned is https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/vertx-blocked-thread-checker.

However, I could see any reproducer and can't reproduce it locally either.

I'm closing this ticket unless you provide one, so we can help!

**Closed by Sgitario** 2023-03-09 12:02 UTC
Labels: kind/bug, area/kubernetes
