### ISSUE TITLE
Hot Reload with Jigsaw modules is not working

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#25836] opened 2022-05-27 18:18 UTC
### Describe the bug

I have a quarkus app with multiple Jigsaw modules running on JDK17, dev mode is starting fine but on each reload I have the following error: invalid flag followed by my class path.

### Expected behavior

Hot reload is performed correctly

### Actual behavior

Hot reload fail with the error invalid flag

### How to Reproduce?

- Run the provided reproducer in dev mode with jdk17
- Trigger a reload

### Output of `java -version`

JDK17

### Quarkus version or git rev

2.9.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by rmanibus** [comment] 2022-05-27 18:42
Reproducer: 
https://github.com/rmanibus/quarkus_25836

It's not the same error than in my app thought. It's failing with 
```
Compilation Failed:
error: module not found: java.xml.bind
error: module not found: java.ws.rs
```

**Comment by rmanibus** [comment] 2022-06-01 00:17
Hello @gsmet ,

Do you know who can help me with that ? 

I can try to draft a PR but I need some insight on how the hot reload mechanism is designed. I'm not sure where I should  start.

**Comment by serahl** [comment] 2022-06-01 07:01
I reported a similar issue with #17747
Would love for this to get fixed/implemented!

**Comment by yrodiere** [comment] 2022-10-12 06:58
Looks like a duplicate of #17747, closing. Feel free to ping me if this problem is different from #17747.

**Closed by yrodiere** 2022-10-12 06:58 UTC
Labels: kind/bug, area/devmode
