### ISSUE TITLE
JBeret blocks Quarkus startup on Java 17

### ISSUE THREAD

**Issue by lostiniceland** [quarkusio/quarkus#28906] opened 2022-10-28 13:37 UTC
### Describe the bug

We are currently upgrading from Quarkus 2.7.2 to 2.13.3 and the services which make use of JBeret fail to boot because of an IllegalAccessException to the JDK-internal java.lang.AbstractStringBuilder.

Already in 2.7.2, when we migrated to Java 17, we had to setup Quarkus to launch with an additional JVM parameter top open up the jdk package `java.security` due to JBeret. With 2.13.3 an additional package from java.base module was needed: `java.util.zip`.

Usually this is enough for the JDK to allow access. But in this case the BatchBeanProducer from JBeret is, for whatever reason, trying to access `java.lang.AbstractStringBuilder`.
Since I could not find any reference to this class in the JBeret repo, I must assume that this behaviour is caused by Quarkus bootstrap magic.

### Expected behavior

Given all required JDK packages are open for reflection, the startup should succeed.

### Actual behavior

```
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 17 more
Caused by: java.lang.IllegalAccessError: failed to access class java.lang.AbstractStringBuilder from class org.jberet.creation.BatchBeanProducer_ProducerMethod_getStringBuffer_63eee896f20ad1cf56dde6a254b221caf7ed9cbc_Bean (java.lang.AbstractStringBuilder is in module java.base of loader 'bootstrap'; org.jberet.creation.BatchBeanProducer_ProducerMethod_getStringBuffer_63eee896f20ad1cf56dde6a254b221caf7ed9cbc_Bean is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @1cbbffcd)
	at org.jberet.creation.BatchBeanProducer_ProducerMethod_getStringBuffer_63eee896f20ad1cf56dde6a254b221caf7ed9cbc_Bean.<init>(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.addBeans13(Unknown Source)
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.impl.ArcContainerImpl.<init>(ArcContainerImpl.java:127)
	at io.quarkus.arc.Arc.initialize(Arc.java:31)
	at io.quarkus.arc.runtime.ArcRecorder.initContainer(ArcRecorder.java:43)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources1337887788.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ArcProcessor$generateResources1337887788.deploy(Unknown Source)
```

### How to Reproduce?

Setup Quarkus Application together with JBeret Batch Framework

Start with add-opens JVM-Parameter
`--add-opens=java.base/java.security=ALL-UNNAMED --add-opens=java.base/java.util.zip=ALL-UNNAMED`

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

I also tried opening up `java.base/java.lang` (which contains the AbstractStringBuilder) to the **unnamed-module**, but this did not work.

**Comment by geoand** [comment] 2022-10-31 08:54
Any chance you can attach a sample? I was not able to reproduce this.

**Comment by gsmet** [comment] 2022-10-31 09:17
This rings a bell and I think it was fixed.

Yeah, this would be the fix: https://github.com/quarkusio/quarkus/pull/28374

I think we probably should backport it to 2.13.

**Comment by gsmet** [comment] 2022-10-31 09:18
@lostiniceland can you check with 2.14.0.CR1 to make sure the issue is fixed for you?

**Comment by mkouba** [comment] 2022-10-31 09:22
@gsmet is right. https://github.com/quarkusio/quarkus/pull/28374 should help because it removes all non-public jdk types from the set of bean types. In this particular case, it removes the `AbstractStringBuilder` from the set of bean types of the [BatchBeanProducer#getStringBuffer()](https://github.com/jberet/jsr352/blob/master/jberet-core/src/main/java/org/jberet/creation/BatchBeanProducer.java#L366-L369) producer method.

> I think we probably should backport it to 2.13.

+1

**Comment by geoand** [comment] 2022-10-31 09:28
👍🏼

**Comment by geoand** [comment] 2022-11-02 06:47
Closing as per Martin's comment.

Feel free to comment and/or reopen if you are not satisfied with the resolution

**Closed by geoand** 2022-11-02 06:47 UTC
Labels: kind/bug, area/arc

**Comment by lostiniceland** [comment] 2022-11-02 09:25
@gsmet  I havent been able to test earliert, but I can confirm that the error is gone in 2.14.0.CR1
