### ISSUE TITLE
REST usage fails with native when e.g. ContainerResponseFilter is used

### ISSUE THREAD

**Issue by alesj** [quarkusio/quarkus#42537] opened 2024-08-14 09:01 UTC
### Describe the bug

ClassLoader cannot find the REST endpoint class

```
Caused by: java.lang.NoSuchMethodException: com.alesj.qcl.app.HelloService.dto()
	at java.base@21.0.1/java.lang.Class.checkMethod(DynamicHub.java:1065)
	at java.base@21.0.1/java.lang.Class.getMethod(DynamicHub.java:1050)
	at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:79)
```

### Expected behavior

Endpoint class should be found.

### Actual behavior

See description.

### How to Reproduce?

Use this repo / branch, see README
* https://github.com/alesj/quarkus_cl130/tree/nativerest1

### Quarkus version or git rev

3.13.2

### Additional information

https://gist.github.com/alesj/7bc3f4737a2f32c4dcaa98bf3c5543cd

If you add @RegisterForReflection to REST endpoint class, it works.

**Comment by alesj** [comment] 2024-08-14 09:02
@FroMage @geoand ^^

**Comment by alesj** [comment] 2024-08-14 09:20
If you add @RegisterForReflection to REST endpoint class, it works.

**Comment by krisgerhard** [comment] 2024-08-16 13:06
I'm seeing the same, only in native, 3.12.3 is working fine, 3.13.0 (and CR) onwards results in NoSuchMethodException

**Comment by geoand** [comment] 2024-08-16 13:34
Please attach a sample that worked with 3.12 and not 3.13.

Thanks

**Comment by krisgerhard** [comment] 2024-08-16 18:45
The sample that @alesj provided indeed does not work with 3.12. 
My usecase was a little different and was fixed with downgrading to 3.12.
In JVM mode it works with latest version as well.

My filter:
```
package com.xyz

import jakarta.annotation.Priority
import jakarta.ws.rs.Priorities.AUTHENTICATION
import jakarta.ws.rs.container.ContainerRequestContext
import jakarta.ws.rs.container.ContainerRequestFilter
import jakarta.ws.rs.container.ResourceInfo
import jakarta.ws.rs.core.Context
import jakarta.ws.rs.core.Response
import jakarta.ws.rs.core.Response.Status.UNAVAILABLE_FOR_LEGAL_REASONS
import jakarta.ws.rs.ext.Provider

@Provider
@Priority(AUTHENTICATION)
@AllowNoProfile
class ProfileFilter : ContainerRequestFilter {

  @Context
  lateinit var resourceInfo: ResourceInfo

  override fun filter(context: ContainerRequestContext) {
    val userUid = context.securityContext.userPrincipal?.name ?: return
    if (resourceInfo.resourceClass.getAnnotation(AllowNoProfile::class.java) != null ||
      resourceInfo.resourceMethod.getAnnotation(AllowNoProfile::class.java) != null
    ) return

    if (userUid === "foobar") {
      context.abortWith(Response.status(UNAVAILABLE_FOR_LEGAL_REASONS).build())
    }
  }
}
```

Stacktrace (removed sensitive parts, ProfileFilter line 33 and 43 are wrong - exception is thrown when accessing resourceMethod):
```
at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:84)
--
at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getResourceMethod(ResteasyReactiveResourceInfo.java:115)
at jakarta.ws.rs.container.ContextProducers_ProducerMethod_resourceInfo_O6EVLN_c9nIaKY9TO6cnD-zx-3c_ClientProxy.getResourceMethod(Unknown Source)
at com.xyz.ProfileFilter.hasAnnotation(ProfileFilter.kt:43)
at com.xyz.ProfileFilter.filter(ProfileFilter.kt:33)
at org.jboss.resteasy.reactive.server.handlers.ResourceRequestFilterHandler.handle(ResourceRequestFilterHandler.java:48)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:131)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:635)
at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base@21.0.4/java.lang.Thread.runWith(Thread.java:1596)
at java.base@21.0.4/java.lang.Thread.run(Thread.java:1583)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:896)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:872)

Caused by: java.lang.NoSuchMethodException: com.xyz.MyResource.getXyz(jakarta.ws.rs.core.SecurityContext, int)
at java.base@21.0.4/java.lang.Class.checkMethod(DynamicHub.java:1078)
at java.base@21.0.4/java.lang.Class.getMethod(DynamicHub.java:1063)
at org.jboss.resteasy.reactive.server.spi.ResteasyReactiveResourceInfo.getMethod(ResteasyReactiveResourceInfo.java:79)
... 18 more
```

**Comment by gsmet** [comment] 2024-08-17 09:26
@geoand shouldn't we register the resource methods for reflection when we have `ResourceInfo` injected somewhere?

**Comment by FroMage** [comment] 2024-08-22 09:51
Probably, but that would mean every resource class/method, since we can't know which one is affected.

Reminds me that we had custom `MessageBodyWriter/Reader` classes to avoid registering reflection just to get annotations, but I don't think we have any support for filters to obtain annotations without reflection.

**Comment by geoand** [comment] 2024-08-22 10:01
We need to see what changed and caused this.

We have tried hard to avoid registering everything for reflection unconditionally, so I would only go down that route if there is no other way

**Comment by geoand** [comment] 2024-08-26 08:12
@krisgerhard your case is indeed different than the one @alesj mentions. Can you please open a new issue and also attach a sample application I can use to quickly reproduce the problem?

Thanks.

**Closed** 2024-08-27 10:05 UTC
Labels: kind/bug, area/native-image
