### ISSUE TITLE
Improve Extension Author Guide

### ISSUE THREAD

**Issue by ebramirez** [quarkusio/quarkus#1964] opened 2019-04-09 18:18 UTC
This is a request to improve the [Extension Author Guide](https://quarkus.io/guides/extension-authors-guide).

The current documentation is pretty impressive but completely inaccessible for the uninitiated like me.

A real life example would be of tremendous help. For example, I would like to create a Quarkus extension for Vaadin, which looks like a rewrite of the project [Vaadin CDI](https://github.com/vaadin/cdi), but I don't know where to start.

The ideal examples would have several blocks like: "Look for THIS (Example of initialization, instrumentation, etc) which translates into THAT (equivalent operation in Quarkus)".

Hope this makes sense.

**Comment by ebramirez** [comment] 2019-04-09 18:20
It looks like @manovotn had similar [thoughts](https://github.com/quarkusio/quarkus/issues/1690#issuecomment-476552043) in #1690.

**Comment by starksm64** [comment] 2019-04-10 01:46
The guide has been significantly expanded in the 0.13 release, so what feedback do you have on that relative to this issue?

https://quarkus.io/guides/extension-authors-guide

**Comment by ebramirez** [comment] 2019-04-10 08:52
> The guide has been significantly expanded in the 0.13 release, so what feedback do you have on that relative to this issue?

You are right that the docs have improved, but still an example of how to write an extension from scratch would be fantastic.

**Comment by danielpetisme** [comment] 2019-04-10 12:32
As discussed on Zulip, I'll work on this one.

**Comment by Dufgui** [comment] 2019-09-04 19:54
it's maybe a duplicate of #2277 now no ? or is there any still some improvement missing ?
@danielpetisme @ebramirez

**Comment by gsmet** [comment] 2019-11-13 21:15
Closing as duplicate of https://github.com/quarkusio/quarkus/issues/2277 .

**Closed by gsmet** 2019-11-13 21:15 UTC
Labels: component:documentation, pinned, user experience
