### ISSUE TITLE
Missing required data: {quarkus.maven-plugin.version} on project bootstrapping

### ISSUE THREAD

**Issue by dastrobu** [quarkusio/quarkus#31569] opened 2023-03-03 06:29 UTC
### Describe the bug

Bootstrap a new project following the guide: https://quarkus.io/guides/getting-started

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions='resteasy-reactive'
```

### Expected behavior

project is generated successfully, as it used to

### Actual behavior

maven fails with: 

```log
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.864 s
[INFO] Finished at: 2023-03-03T07:24:36+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:create (default-cli) on project standalone-pom: Failed to generate Quarkus project: Error while rendering template: /codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml: Missing required data: {quarkus.maven-plugin.version} -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:create (default-cli) on project standalone-pom: Failed to generate Quarkus project
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:375)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: org.apache.maven.plugin.MojoExecutionException: Failed to generate Quarkus project
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:330)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: io.quarkus.devtools.codestarts.CodestartException: Error while rendering template: /codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml
    at io.quarkus.devtools.codestarts.core.reader.QuteCodestartFileReader.readQuteFile (QuteCodestartFileReader.java:85)
    at io.quarkus.devtools.codestarts.core.reader.QuteCodestartFileReader.read (QuteCodestartFileReader.java:55)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.processLanguageDir (CodestartProcessor.java:138)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.lambda$process$0 (CodestartProcessor.java:58)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:992)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.lambda$process$1 (CodestartProcessor.java:58)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.lambda$allocate$0 (CodestartCatalogLoader.java:150)
    at io.quarkus.platform.descriptor.loader.json.ZipResourceLoader.loadResourceAsPath (ZipResourceLoader.java:25)
    at io.quarkus.devtools.codestarts.CodestartResourceLoader.loadResourceAsPath (CodestartResourceLoader.java:37)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.allocate (CodestartCatalogLoader.java:149)
    at io.quarkus.devtools.codestarts.Codestart.use (Codestart.java:27)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.process (CodestartProcessor.java:53)
    at io.quarkus.devtools.codestarts.core.CodestartProjectGeneration.lambda$generateProject$0 (CodestartProjectGeneration.java:49)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.lambda$allocate$0 (CodestartCatalogLoader.java:150)
    at io.quarkus.platform.descriptor.loader.json.ZipResourceLoader.loadResourceAsPath (ZipResourceLoader.java:25)
    at io.quarkus.devtools.codestarts.CodestartResourceLoader.loadResourceAsPath (CodestartResourceLoader.java:37)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.allocate (CodestartCatalogLoader.java:149)
    at io.quarkus.devtools.codestarts.Codestart.use (Codestart.java:27)
    at io.quarkus.devtools.codestarts.core.CodestartProjectGeneration.generateProject (CodestartProjectGeneration.java:47)
    at io.quarkus.devtools.codestarts.core.DefaultCodestartProjectDefinition.generate (DefaultCodestartProjectDefinition.java:56)
    at io.quarkus.devtools.commands.handlers.CreateProjectCommandHandler.execute (CreateProjectCommandHandler.java:168)
    at io.quarkus.devtools.commands.CreateProject.execute (CreateProject.java:234)
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
Caused by: io.quarkus.qute.TemplateException: Missing required data: {quarkus.maven-plugin.version}
    at io.quarkus.devtools.codestarts.core.reader.QuteCodestartFileReader$MissingValueMapper.map (QuteCodestartFileReader.java:143)
    at io.quarkus.qute.EngineImpl.mapResult (EngineImpl.java:108)
    at io.quarkus.qute.ExpressionNode.mapResult (ExpressionNode.java:80)
    at io.quarkus.qute.SingleResultNode.process (SingleResultNode.java:24)
    at io.quarkus.qute.MultiResultNode.process (MultiResultNode.java:20)
    at io.quarkus.qute.MultiResultNode.process (MultiResultNode.java:20)
    at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.lambda$renderData$5 (TemplateImpl.java:233)
    at io.quarkus.qute.CompletedStage.whenComplete (CompletedStage.java:268)
    at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderData (TemplateImpl.java:227)
    at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.renderAsyncNoTimeout (TemplateImpl.java:218)
    at io.quarkus.qute.TemplateImpl$TemplateInstanceImpl.render (TemplateImpl.java:143)
    at io.quarkus.qute.Template.render (Template.java:111)
    at io.quarkus.devtools.codestarts.core.reader.QuteCodestartFileReader.readQuteFile (QuteCodestartFileReader.java:83)
    at io.quarkus.devtools.codestarts.core.reader.QuteCodestartFileReader.read (QuteCodestartFileReader.java:55)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.processLanguageDir (CodestartProcessor.java:138)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.lambda$process$0 (CodestartProcessor.java:58)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.accept (ForEachOps.java:183)
    at java.util.stream.ReferencePipeline$2$1.accept (ReferencePipeline.java:179)
    at java.util.Spliterators$ArraySpliterator.forEachRemaining (Spliterators.java:992)
    at java.util.stream.AbstractPipeline.copyInto (AbstractPipeline.java:509)
    at java.util.stream.AbstractPipeline.wrapAndCopyInto (AbstractPipeline.java:499)
    at java.util.stream.ForEachOps$ForEachOp.evaluateSequential (ForEachOps.java:150)
    at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential (ForEachOps.java:173)
    at java.util.stream.AbstractPipeline.evaluate (AbstractPipeline.java:234)
    at java.util.stream.ReferencePipeline.forEach (ReferencePipeline.java:596)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.lambda$process$1 (CodestartProcessor.java:58)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.lambda$allocate$0 (CodestartCatalogLoader.java:150)
    at io.quarkus.platform.descriptor.loader.json.ZipResourceLoader.loadResourceAsPath (ZipResourceLoader.java:25)
    at io.quarkus.devtools.codestarts.CodestartResourceLoader.loadResourceAsPath (CodestartResourceLoader.java:37)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.allocate (CodestartCatalogLoader.java:149)
    at io.quarkus.devtools.codestarts.Codestart.use (Codestart.java:27)
    at io.quarkus.devtools.codestarts.core.CodestartProcessor.process (CodestartProcessor.java:53)
    at io.quarkus.devtools.codestarts.core.CodestartProjectGeneration.lambda$generateProject$0 (CodestartProjectGeneration.java:49)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.lambda$allocate$0 (CodestartCatalogLoader.java:150)
    at io.quarkus.platform.descriptor.loader.json.ZipResourceLoader.loadResourceAsPath (ZipResourceLoader.java:25)
    at io.quarkus.devtools.codestarts.CodestartResourceLoader.loadResourceAsPath (CodestartResourceLoader.java:37)
    at io.quarkus.devtools.codestarts.CodestartCatalogLoader$PathCodestartResourceAllocator.allocate (CodestartCatalogLoader.java:149)
    at io.quarkus.devtools.codestarts.Codestart.use (Codestart.java:27)
    at io.quarkus.devtools.codestarts.core.CodestartProjectGeneration.generateProject (CodestartProjectGeneration.java:47)
    at io.quarkus.devtools.codestarts.core.DefaultCodestartProjectDefinition.generate (DefaultCodestartProjectDefinition.java:56)
    at io.quarkus.devtools.commands.handlers.CreateProjectCommandHandler.execute (CreateProjectCommandHandler.java:168)
    at io.quarkus.devtools.commands.CreateProject.execute (CreateProject.java:234)
    at io.quarkus.maven.CreateProjectMojo.execute (CreateProjectMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute2 (MojoExecutor.java:370)
    at org.apache.maven.lifecycle.internal.MojoExecutor.doExecute (MojoExecutor.java:351)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:215)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:171)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:163)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:298)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:960)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:293)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:196)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:77)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:568)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
q453358@LMUCM943010:~/tmp/bar$ mvn io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=getting-started \
    -Dextensions='resteasy-reactive'
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------------< org.apache.maven:standalone-pom >-------------------
[INFO] Building Maven Stub Project (No POM) 1
[INFO] --------------------------------[ pom ]---------------------------------
[INFO] 
[INFO] --- quarkus-maven-plugin:2.16.3.Final:create (default-cli) @ standalone-pom ---
[INFO] -----------
[INFO] selected extensions: 
- io.quarkus:quarkus-resteasy-reactive

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.997 s
[INFO] Finished at: 2023-03-03T07:25:54+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.16.3.Final:create (default-cli) on project standalone-pom: Failed to generate Quarkus project: Error while rendering template: /codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml: Missing required data: {quarkus.maven-plugin.version} -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

### How to Reproduce?

see above

### Output of `java -version`

Java version: 17.0.6, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
mvn --version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /usr/local/Cellar/maven/3.8.7/libexec
Java version: 17.0.6, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "13.2.1", arch: "x86_64", family: "mac"
```

**Comment by javiroman** [comment] 2023-03-03 07:48
The same error with quarkus CLI:

```
$ quarkus -version
2.16.3.Final

$ quarkus create app org.acme:vertx-quickstart --extension='vertx,resteasy-reactive' --no-code
-----------
selected extensions: 
- io.quarkus:quarkus-resteasy-reactive
- io.quarkus:quarkus-vertx

[ERROR] ❗  Unable to create project: Error while rendering template: /codestarts/quarkus/buildtool/maven/base/pom.tpl.qute.xml
```

**Comment by aloubyansky** [comment] 2023-03-03 07:49
@gastaldi this is related to the yesterday's registry update. Please disable the option for the registry to provide platform extension catalogs for now. Platform extension catalogs returned by the registry are missing the metadata found in https://repo1.maven.org/maven2/io/quarkus/platform/quarkus-bom-quarkus-platform-descriptor/2.16.3.Final/quarkus-bom-quarkus-platform-descriptor-2.16.3.Final-2.16.3.Final.json

**Comment by aloubyansky** [comment] 2023-03-03 08:39
It's fixed now. The workaround above isn't necessary anymore.

**Closed by aloubyansky** 2023-03-03 08:39 UTC
Labels: kind/bug, area/maven

**Comment by javiroman** [comment] 2023-03-03 09:06
mm, no working yet.

**Comment by maxandersen** [comment] 2023-03-03 09:10
even if you nuke `~/.m2/io/quarkus/platform` ?

**Comment by maxandersen** [comment] 2023-03-03 09:10
i can confirm `quarkus create app org.acme:vertx-quickstart --extension='vertx,resteasy-reactive' --no-code` works for me now.

**Comment by javiroman** [comment] 2023-03-03 09:13
My environment is different:

```
$ ls .m2/
archetype-catalog.xml  repository/  wrapper/
```

The "io" folder is missing.

I'm using:

```
$ mvn -version
Apache Maven 3.8.2 (ea98e05a04480131370aa0c110b8c54cf726c06f)
```

**Comment by javiroman** [comment] 2023-03-03 09:17
Ok, working with:

```
rm -fr .m2/repository/io/quarkus
```

**Comment by aloubyansky** [comment] 2023-03-03 09:26
Oh, sure, sorry, I missed the `repository` in the path. Thanks for pointing it out @javiroman

**Comment by maxandersen** [comment] 2023-03-03 10:00
thanks for confirming! and yeah I copy pasted without noticing the missing repo. my bad:)
