### ISSUE TITLE
Banner full of ??? when running tests against Windows native binary, using cmd

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7672] opened 2020-03-07 22:55 UTC
Banner full of ??? when running tests against Windows native binary, using cmd

But when running the final .exe on my own the banner is ok

![Screenshot 2020-03-07 23 50 07](https://user-images.githubusercontent.com/925259/76153611-99516800-60ce-11ea-89ce-331421076925.png)

![ESil83PXgAAkJO8](https://user-images.githubusercontent.com/925259/76153616-bc7c1780-60ce-11ea-9c51-0b13654e44cb.png)

**Comment by SR-Lut3t1um** [comment] 2020-03-09 11:42
I also get the same issue in intellij when starting quarkusDev

**Comment by rsvoboda** [comment] 2020-03-09 12:10
@maxandersen / @gsmet dev experience in IDE

**Comment by maxandersen** [comment] 2020-03-09 13:23
I don't understand the difference between your two examples ? 

It looks like you are running tests in a docker built binary hence the ?'s are expected unless you are using latest master having #7662 applied ?

**Comment by maxandersen** [comment] 2020-03-09 13:23
> I also get the same issue in intellij when starting quarkusDev (Using 1.3.0.CR1)

can you please give exact steps on what you are doing ?

**Comment by SR-Lut3t1um** [comment] 2020-03-09 14:06
> > I also get the same issue in intellij when starting quarkusDev (Using 1.3.0.CR1)
> 
> can you please give exact steps on what you are doing ?

Using:

```
IntelliJ IDEA 2020.1 EAP (Ultimate Edition)
Build #IU-201.6073.9, built on March 4, 2020
IntelliJ IDEA EAP User
Expiration date: April 3, 2020
Runtime version: 11.0.6+8-b765.1 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 974M
Cores: 4
Registry: ide.balloon.shadow.size=0
Non-Bundled Plugins: Batch Scripts Support, CMD Support, com.github.gtache.lsp, com.dubreuia, com.redhat.devtools.intellij.quarkus, com.mallowigi, google-java-format, org.jetbrains.kotlin, com.chrisrm.idea.MaterialThemeUI
```

And: 

`Powershell 7: Terminal`

**Comment by maxandersen** [comment] 2020-03-09 21:55
@SR-Lut3t1um no, I mean what you acttually do in intellij that makes you end up with garbled banner?

**Comment by geoand** [comment] 2020-03-10 09:34
@SR-Lut3t1um is this happening only on IntelliJ's terminal, or the system terminal as well?

**Comment by SR-Lut3t1um** [comment] 2020-03-10 09:38
@geoand it happens in both terminals. I use gradle and run the quarkusDev task.

**Comment by geoand** [comment] 2020-03-10 09:39
Does the problem occur in `1.3.0.CR2` (which was released today)?

**Comment by SR-Lut3t1um** [comment] 2020-03-10 09:39
Yes

**Comment by geoand** [comment] 2020-03-10 09:43
@SR-Lut3t1um last question: Does this also happens if you produce a jar and run it with `java -jar ...`?

**Comment by SR-Lut3t1um** [comment] 2020-03-10 09:45
> @SR-Lut3t1um last question: Does this also happens if you produce a jar and run it with `java -jar ...`?

No this works, so gradle is the issue?

**Comment by geoand** [comment] 2020-03-10 09:48
Most likely, can you please try adding `--console=plain` to your `./gradlew` invocation?

**Comment by SR-Lut3t1um** [comment] 2020-03-10 09:50
> Most likely, can you please try adding `--console=plain` to your `./gradlew` invocation?

This does'n work still questionmarks.

**Comment by geoand** [comment] 2020-03-10 09:54
@rsvoboda can you check and see if `quarkusDev` is giving you odd behavior?

**Comment by maxandersen** [comment] 2020-03-10 15:40
@SR-Lut3t1um could you try running:

`jbang https://github.com/maxandersen/jbang/blob/master/examples/lang.java`

in the terminal you have issues and show the output ? (you can also just download that file and do `javac lang.java & java lang`

**Comment by SR-Lut3t1um** [comment] 2020-03-10 15:48
```
javac lang.java & java lang

Id     Name            PSJobTypeName   State         HasMoreData     Location             Command
--     ----            -------------   -----         -----------     --------             -------
1      Job1            BackgroundJob   Running       True            localhost            Microsoft.PowerShell.Man…
Fehler: Hauptklasse lang konnte nicht gefunden oder geladen werden -> Error: Main class lang could not be found or loaded
Ursache: java.lang.ClassNotFoundException: lang
|
v
Cause
```

**Comment by maxandersen** [comment] 2020-03-10 16:00
did you download the file  and save as lang.java ? 

```
wget https://raw.githubusercontent.com/maxandersen/jbang/master/examples/lang.java
javac lang.java
java lang
```
works for me.

**Comment by maxandersen** [comment] 2020-03-10 16:06
btw. i've reproduced it on windows gradle. 

mac/linux is fine.

**Comment by maxandersen** [comment] 2020-03-10 16:11
![2020-03-10_17-10-56](https://user-images.githubusercontent.com/54129/76333562-1f99c400-62f2-11ea-9ce8-da734a970c6c.png)

and this is just on plain project created using:

```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=kubernetes-quickstart-gradle -DclassName="org.acme.rest.GreetingResource" -Dpath="/greeting" -Dextensions="kubernetes" -DbuildTool=gradle
```

**Comment by maxandersen** [comment] 2020-03-10 16:12
marked as blocker for now - at least until figure out what is the cause of this.

**Comment by SR-Lut3t1um** [comment] 2020-03-10 16:15
> did you download the file and save as lang.java ?
> 
> ```
> wget https://raw.githubusercontent.com/maxandersen/jbang/master/examples/lang.java
> javac lang.java
> java lang
> ```
> 
> works for me.

Yes I did, it worked the 2.nd time I ran it. 1.st error was prob. beacause of the &

**Comment by SR-Lut3t1um** [comment] 2020-03-10 16:52
Maybe this is a encoding issue the implementation of the Jboss logger has?

**Comment by maxandersen** [comment] 2020-03-10 19:28
> Yes I did, it worked the 2.nd time I ran it. 1.st error was prob. beacause of the &

what was the output you got ? en.windows-1252 ? 

> Maybe this is a encoding issue the implementation of the Jboss logger has?

it works everywhere else so its the encoding of the terminal / what gradle does *not* do in comparison to mvn where it just works.

**Closed** 2020-03-12 13:34 UTC
Labels: env/windows, kind/bug, priority/blocker
