### ISSUE TITLE
Entity not committed when expected

### ISSUE THREAD

**Issue by emersonl91** [quarkusio/quarkus#7163] opened 2020-02-12 15:16 UTC
During the execution of a process I open two transactions:
- One to create an object and inform that the process has started;
- Another to change the object that was created in the first transaction, informing that the process was completed;

However, after executing the second transaction method, if I query the database the value has not yet been updated. What I expected is that after the execution of the method with the @Transactional annotation is finished, the object is already committed to the database.

The reproduction of the situation is in the project:
[https://github.com/emersonl91/quarkus-test](https://github.com/emersonl91/quarkus-tests)

Important lines:
[https://github.com/emersonl91/quarkus-tests/blob/master/code-with-quarkus/src/main/java/org/acme/MyService.java#L32](https://github.com/emersonl91/quarkus-tests/blob/master/code-with-quarkus/src/main/java/org/acme/MyService.java#L32)

[https://github.com/emersonl91/quarkus-tests/blob/master/code-with-quarkus/src/test/java/org/acme/ExampleResourceTest.java#L37](https://github.com/emersonl91/quarkus-tests/blob/master/code-with-quarkus/src/test/java/org/acme/ExampleResourceTest.java#L37)

-----

**Edit 1:**
- I tested the UserTransaction and TransactionManager classes, but the same problem also occurs.
- Added the @Transaction annotation to the method that makes the calls, the whole process starts to be executed in a single transaction, which is different from what I expect.

-----

**Edit 2:**
 - In the **transactionTest** method I added the @Transactional(NOT_SUPPORTED) annotation,  in the **persist** and **update** methods I added the @Transactional(REQUIRES_NEW) annotation. The result did not change.

-----

**Edit 3:**
 - I did a test via POSTMAN and with MSSQL database. I followed the request in the database, the entity is updated as expected, but in the application I use the command `MyEntity.findAll().list().get(0)` and the entity remains not updated.

**Comment by zeljkot** [comment] 2020-02-12 21:32
Is it similar to this: https://github.com/quarkusio/quarkus/issues/7102

**Comment by emersonl91** [comment] 2020-02-13 10:59
@zeljkot  Yes, it looks very similar to me.

**Comment by gastaldi** [comment] 2020-02-13 16:37
Should we close this issue as duplicate and focus on #7102? Looks like #7188 is also related

**Comment by emersonl91** [comment] 2020-02-13 17:04
@gastaldi i agree

**Comment by gastaldi** [comment] 2020-02-13 17:05
@emersonl91 thanks! Closing as duplicate of #7102

**Closed by gastaldi** 2020-02-13 17:05 UTC
Labels: kind/question

**Comment by zeljkot** [comment] 2020-02-13 18:03
> Should we close this issue as duplicate and focus on #7102? Looks like #7188 is also related

@gastaldi if I understood @FroMage correctly, #7188 is a different issue, as discussed in #7102 thread.
