### ISSUE TITLE
Deploying to minikube stopped working starting from 2.7.0.Final

### ISSUE THREAD

**Issue by aloubyansky** [quarkusio/quarkus#23925] opened 2022-02-23 17:19 UTC
Create a project with, e.g.,
````
mvn io.quarkus.platform:quarkus-maven-plugin:2.7.2.Final:create -Dextensions=jib,minikube
````
Executing `mvn clean package -DskipTests -Dquarkus.kubernetes.deploy` from the project dir results in:
````
ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.2.Final:build (default) on project code-with-quarkus: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]     [error]: Build step io.quarkus.kubernetes.deployment.KubernetesDeployer#deploy threw an exception: io.fabric8.kubernetes.client.KubernetesClientException: namespace not specified for an operation requiring one.
[ERROR]     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.checkNamespace(OperationSupport.java:225)
[ERROR]     at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleDelete(OperationSupport.java:260)
[ERROR]     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.deleteThis(BaseOperation.java:527)
[ERROR]     at io.fabric8.kubernetes.client.dsl.base.BaseOperation.delete(BaseOperation.java:445)
[ERROR]     at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.delete(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:116)
[ERROR]     at io.quarkus.kubernetes.deployment.KubernetesDeployer.lambda$deploy$4(KubernetesDeployer.java:211)
[ERROR]     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
[ERROR]     at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:177)
[ERROR]     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
[ERROR]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
[ERROR]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
[ERROR]     at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
[ERROR]     at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
[ERROR]     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]     at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
[ERROR]     at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:199)
[ERROR]     at io.quarkus.kubernetes.deployment.KubernetesDeployer.deploy(KubernetesDeployer.java:110)
````

Changing the platform version to 2.6.3.Final fixes the deployment.

As mentioned by @iocanel in a chat, a workaround is to execute:
````
kubectl config set-context --current --namespace=default
````
before the build.

**Comment by geoand** [comment] 2022-02-24 08:01
@iocanel are you looking into this?

**Comment by iocanel** [comment] 2022-02-24 12:31
I will pick this up.

**Comment by loban** [comment] 2022-03-29 11:59
Just wanted to comment that the same error occurred deploying an app using `Quarkus 2.7.5.Final` to a local knative/kubernetes cluster created using `kind`.

**Comment by iocanel** [comment] 2022-04-07 08:15
The quickest fix for that would be the check if `namespace` has been detected and fallback to `default` if none has been configured.

**Comment by adriannowak** [comment] 2022-05-29 09:19
@iocanel Are you working on this issue? If not, I could take it ;)

**Comment by albers** [comment] 2022-10-04 21:17
When minikube 1.27.0 creates a cluster, the generated kubeconfig context entry has a namespace definition: 

```yaml
- context:
    cluster: minikube
    extensions:
    - extension:
        last-update: Tue, 04 Oct 2022 23:00:57 CEST
        provider: minikube.sigs.k8s.io
        version: v1.27.0
      name: context_info
    namespace: default
    user: minikube
  name: minikube
```

The namespace issue might be less apparent now in the context of minikube.

**Comment by albers** [comment] 2022-10-05 14:34
The behaviour described in this issue is not a bug but a feature, see the [Kubernetes Extension guide](https://quarkus.io/guides/deploying-to-kubernetes#namespace):

>By default, Quarkus omits the namespace in the generated manifests, rather than enforce the default namespace. That means that you can apply the manifest to your chosen namespace when using kubectl

If the namespace is known, the guide recommends:

>To specify the namespace in your manifest customize with the following property in your application.properties:
>```properties
>quarkus.kubernetes.namespace=mynamespace
>```

**Comment by gsmet** [comment] 2022-12-05 09:23
I'm closing this one.

**Closed by gsmet** 2022-12-05 09:23 UTC
Labels: kind/bug, good first issue, area/kubernetes, area/container-image
