### ISSUE TITLE
REST client - better validation of configuration/logging

### ISSUE THREAD

**Issue by ygyg70** [quarkusio/quarkus#31983] opened 2023-03-20 17:18 UTC
### Describe the bug

When the service URL of reactive REST client has a typo, things don't work without any logging/exceptions, making it laborious to troubleshoot.

### Expected behavior

An error on server startup and/or when invoking the service

### Actual behavior

No errors on server startup, no log, calling the client service just does nothing

### How to Reproduce?

1. Have a project that uses REST client reactive
2. in application.properties, modify quarkus.rest-client.some-service.url to have an invalid URL (in my case, I had the protocol repeating)

### Output of `uname -a` or `ver`

WIndows 10 64 bit

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS OpenJDK Runtime Environment Corretto-17.0.6.10.1 (build 17.0.6+10-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.6.10.1 (build 17.0.6+10-LTS, mixed mode, sharing)

### GraalVM version (if different from Java)

Not used

### Quarkus version or git rev

Quarkus 2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: C:\Users\...\.m2\wrapper\dists\apache-maven-3.8.6-bin\67568434\apache-maven-3.8.6 Java version: 17.0.6, vendor: Amazon.com Inc., runtime: C:\Users\yonat\.jdks\corretto-17.0.6 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment] 2023-03-21 07:18
I can't reproduce this.

When trying the [REST Client Reactive quickstart](https://github.com/quarkusio/quarkus-quickstarts/tree/main/rest-client-reactive-quickstart) and using `quarkus.rest-client.extensions-api.url=httpshttps://stage.code.quarkus.io/api` as the invalid URI, I got:

```
2023-03-21 09:16:39,003 ERROR [org.jbo.res.rea.cli.han.ClientSendRequestHandler] (executor-thread-1) Invalid REST Client URL used: 'httpshttps://stage.code.quarkus.io/api/extensions?id=io.quarkus%3Aquarkus-rest-client-reactive'
2023-03-21 09:16:39,004 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /extension/id/io.quarkus:quarkus-rest-client-reactive failed, error id: 3323ade7-1c46-4559-aa36-b11c37a67a17-2: java.lang.IllegalArgumentException: Invalid REST Client URL used: 'httpshttps://stage.code.quarkus.io/api/extensions?id=io.quarkus%3Aquarkus-rest-client-reactive'
```

when using the client

**Comment by ygyg70** [comment] 2023-03-21 07:45
Please try:
quarkus.rest-client.extensions-api.url=https://https://stage.code.quarkus.io/api

I do get the same error trying
quarkus.rest-client.extensions-api.url=httpshttps://stage.code.quarkus.io/api

**Comment by geoand** [comment] 2023-03-21 07:49
I get:

```
2023-03-21 09:49:03,578 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (executor-thread-1) Request failed: jakarta.ws.rs.ProcessingException: java.net.UnknownHostException: https: Temporary failure in name resolution
```

**Comment by ygyg70** [comment] 2023-03-21 07:57
We are probably doing something different, as I don't get the same error as you
However,
Apache commons url validators reports "https://https://stage.code.quarkus.io/api" as invalid.
Imho, it would be nice to get the same "Invalid REST Client URL used" for any URL that doesn't pass common URL validation.

**Comment by ygyg70** [comment] 2023-03-21 08:01
Which version of Quarkus/logging configuration are you using? I would also like to get the unknown host exception.

**Comment by geoand** [comment] 2023-03-21 08:04
I tried both `2.16.4.Final` and Quarkus built from main so I am going to close this unless you can provide a sample that indeed does not log any error.

**Comment by geoand** [comment] 2023-03-21 08:56
There already is logging as I mentioned before so I am not sure what exactly you are asking

**Comment by geoand** [comment] 2023-03-21 09:05
As I mentioned earlier we'll need a sample application to be able investigte any further

**Comment by geoand** [comment] 2023-04-10 08:27
Closing as we did not get a reproducer

**Closed by geoand** 2023-04-10 08:27 UTC
Labels: kind/bug, area/rest-client, env/windows, triage/needs-reproducer
