### ISSUE TITLE
Bean Validation on Vert.x Routes are not validating responses for Java types 

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15168] opened 2021-02-18 15:11 UTC
**Describe the bug**
For example, the next route:

```java
@Route(methods = HttpMethod.GET, path = "/response-uni-invalid-string")
@Valid
@Size(min = 3, max = 3, message = "response must have 3 characters")
Uni<String> validateResponseWithString() {
    return Uni.createFrom().item("ASDASD");
}
```

It raises this exception:

```
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-8) HTTP Request to /validate/response-uni-invalid-string failed, error id: a4e6f67d-ea64-4ee6-a70a-56046338b767-1: javax.validation.UnexpectedTypeException: HV000030: No validator could be found for constraint 'javax.validation.constraints.Size' validating type 'io.smallrye.mutiny.Uni<java.lang.String>'. Check configuration for 'validateResponseWithString.<return value>'
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getExceptionForNullValidator(ConstraintTree.java:116)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.getInitializedConstraintValidator(ConstraintTree.java:162)
	at org.hibernate.validator.internal.engine.constraintvalidation.SimpleConstraintTree.validateConstraints(SimpleConstraintTree.java:54)
	at org.hibernate.validator.internal.engine.constraintvalidation.ConstraintTree.validateConstraints(ConstraintTree.java:75)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.doValidateConstraint(MetaConstraint.java:130)
	at org.hibernate.validator.internal.metadata.core.MetaConstraint.validateConstraint(MetaConstraint.java:123)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraint(ValidatorImpl.java:555)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateMetaConstraints(ValidatorImpl.java:537)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateReturnValueForSingleGroup(ValidatorImpl.java:1141)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateReturnValueForGroup(ValidatorImpl.java:1111)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateReturnValueInContext(ValidatorImpl.java:1033)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateReturnValue(ValidatorImpl.java:309)
	at org.hibernate.validator.internal.engine.ValidatorImpl.validateReturnValue(ValidatorImpl.java:259)
	at io.quarkus.hibernate.validator.runtime.interceptor.AbstractMethodValidationInterceptor.validateMethodInvocation(AbstractMethodValidationInterceptor.java:70)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor.validateMethodInvocation(MethodValidationInterceptor.java:17)
	at io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor_Bean.intercept(MethodValidationInterceptor_Bean.zig:341)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at io.quarkus.qe.validation.ValidationOnResponseRouteHandler_Subclass.validateResponseWithString(ValidationOnResponseRouteHandler_Subclass.zig:171)
```

**Expected behavior**
If there is a technical limitation on supporthing this use case, it must be documented and prevent this exception to be thrown. Otherwise, it should validate Java types.

**Actual behavior**
It throws an exception.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.0.Final

**Comment by gsmet** [comment] 2021-02-19 23:34
What you’re doing is incorrect if you don’t have a validator for Size and Uni. That’s how Bean Validation works. And that’s what the error is saying. So I don’t see anything to change here. 

What could eventually work is having the constraint inside the Uni so on the String type. 

I’m not sure if the latter is currently supported though. I know @cescoffier did some work around that but I don’t remember the specifics.

**Comment by cescoffier** [comment] 2021-02-21 17:33
Reactive Routes validate the emitted objects but do not support using constraints directly on the method.

Here is an example: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx-web/deployment/src/test/java/io/quarkus/vertx/web/validation/UniValidationTest.java#L100-L145

So, if you wrap your response into a class using `@Size` it will work.

**Comment by cescoffier** [comment] 2021-02-22 08:41
The issue is to retrieve the constraints. Currently, we detect `@Valid`, but we don't extract the constraints providing on the method. Maybe @gsmet has an idea.

**Comment by cescoffier** [comment] 2021-06-07 05:48
@gsmet / @mkouba ping?

**Comment by cescoffier** [comment] 2021-09-20 06:16
Closing as `won't fix` as that feature is available in RESTEasy Reactive (which replaces reactive routes for such a use case).

**Closed by cescoffier** 2021-09-20 06:16 UTC
Labels: area/reactive, area/hibernate-validator
