### ISSUE TITLE
Interceptors on abstract methods does not seem to work

### ISSUE THREAD

**Issue by davidfrickert** [quarkusio/quarkus#31745] opened 2023-03-09 18:40 UTC
### Describe the bug

If i define a class as:

```
public abstract class DataMigration {
    // ......
  @LogMigrationExecution
  public abstract void migrate();
}
```

And define the following Logging Interceptor:

```
@InterceptorBinding
@Retention(RetentionPolicy.RUNTIME)
@Target({ ElementType.TYPE, ElementType.METHOD})
@Inherited
public @interface LogMigrationExecution {}

@LogMigrationExecution
@Interceptor
public class LogMigrationExecutionInterceptor {
	private static final Logger LOGGER = LoggerFactory.getLogger(LogMigrationExecutionInterceptor.class);

	@AroundInvoke
	Object logExecution(InvocationContext invocationContext) throws Exception {
		LOGGER.info("[{}] START", invocationContext.getMethod().getDeclaringClass().getSimpleName());

		final Object proceed = invocationContext.proceed();

		LOGGER.info("[{}] - END", invocationContext.getMethod().getDeclaringClass().getSimpleName());

		return proceed;
	}
}
```

And then create an implementation of `DataMigration`:

```
public class ADataMigration {
  @Override 
  public void migrate() {
     // do useful stuff....
  }
}
```

The interceptor is not run. I guess this might be a limitation on annotations but it would be useful to not have to declare them on implementations.
This is a simplified example based on a project using Quarkus that I work on. 

### Expected behavior

The interceptor runs and I see some relevant logs.

### Actual behavior

The interceptor does not run. I am forced to add the annotation on every single implementation for it to run.

### Output of `uname -a` or `ver`

Linux PM-DFrickert 6.1.14-1-MANJARO #1 SMP PREEMPT_DYNAMIC Sat Feb 25 17:11:36 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (build 17.0.6+10)
OpenJDK 64-Bit Server VM (build 17.0.6+10, mixed mode)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

2.16.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /opt/maven
Java version: 17.0.6, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.14-1-manjaro", arch: "amd64", family: "unix"

**Comment by Ladicek** [comment] 2023-03-10 09:28
This seems expected, because CDI generally (with a tiny number of exceptions) follows the Common Annotations recommendations, which are pretty well aligned with the Java semantics of inherited annotations. Which is a fancy way of saying: annotations are only inherited on classes, and only if they are meta-annotated `@Inherited`. Annotations on fields, methods etc. are never inherited.

**Comment by manovotn** [comment] 2023-03-10 09:37
@davidfrickert This is an intended behavior because you override the method.
Ladislav is right but I'd point directly to the CDI spec, namely rules for [member-level inheritance](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#member_level_inheritance), which say:

> Suppose a class X is extended directly or indirectly by the bean class of a managed bean Y.
> If X declares a non-static method x() annotated with an interceptor binding type Z then Y inherits the binding if and only if neither Y nor any intermediate class that is a subclass of X and a superclass of Y overrides the method x(). (This behavior is defined by the Common Annotations for the Java Platform specification.)

**Comment by Ladicek** [comment] 2023-03-10 09:41
Actually I've got a suggestion: it should be pretty straightforward to create a Quarkus extension that "adds" the interceptor binding on all subclasses of `DataMigration`. This is what you need: https://quarkus.io/guides/cdi-integration#annotations_transformer_build_item

**Comment by mkouba** [comment] 2023-03-10 10:31
I'm going to close this issue because it works as expected/designed. By the way, the `ADataMigration` class in the example should probably extend the `DataMigration` class ;-).

**Closed by mkouba** 2023-03-10 10:31 UTC
Labels: kind/bug, area/arc

**Comment by davidfrickert** [comment] 2023-03-10 11:05
Thank you @Ladicek, @manovotn, @mkouba !
Yeah I do sometimes expect that it works similarly to JAX-RS which might be unrealistic.
Thanks for the comments, and I do agree that the issue should be closed. I will check the build step option!
