### ISSUE TITLE
2.0.0.Alpha1 : Unable to connect CloudRun to CloudSql

### ISSUE THREAD

**Issue by anthonydenecheau** [quarkusio/quarkus#24743] opened 2022-04-04 15:59 UTC
### Describe the bug

I come back to an issue that I opened 2 years ago (https://github.com/quarkusio/quarkus/issues/9985) and which was delivered in the 2.0.0.Alpha1 release. I want to connect the CloudRun service to my database instance (CloudSQL)
Unfortunately, the error message has changed but the connection remains impossible.

### Actual behavior

I get this error

`Could not obtain connection to query metadata[39m[38;5;203m: org.postgresql.util.PSQLException: The SocketFactory class provided com.google.cloud.sql.postgres.SocketFactory could not be instantiated.`

### How to Reproduce?

Build image in native mode and deploy on google run (Cloud Build)

### Additional information

pom.xml

```
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <org.mapstruct.version>1.3.1.Final</org.mapstruct.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>2.0.0.Alpha1</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>2.0.0.Alpha1</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>

  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-hibernate-orm-panache</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
    <dependency>
      <groupId>com.google.cloud.sql</groupId>
      <artifactId>postgres-socket-factory</artifactId>
      <version>1.4.4</version>
    </dependency>
  </dependencies>
```

application.properties

```
quarkus.datasource.db-kind=other 
quarkus.datasource.jdbc.url=jdbc:postgresql:///${DATABASE_ACTIVE_SCHEMA}?ipTypes=PRIVATE&cloudSqlInstance=<project:zone:instance-name>&socketFactory=com.google.cloud.sql.postgres.SocketFactory&useSSL=false
quarkus.datasource.jdbc.driver=org.postgresql.Driver
quarkus.datasource.username=${DATABASE_USER}
quarkus.datasource.password=${DATABASE_PASSWORD}
quarkus.datasource.jdbc.additional-jdbc-properties.cloudSqlInstance=<project:zone:instance-name>
quarkus.datasource.jdbc.additional-jdbc-properties.socketFactory=com.google.cloud.sql.postgres.SocketFactory
quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQL10Dialect
quarkus.hibernate-orm.log.sql=false
```

**Comment by geoand** [comment] 2022-04-05 08:26
cc @loicmathieu

**Comment by gsmet** [comment] 2022-04-05 09:24
You are going native with an external library we haven't vetted so you might encounter some issues - not all libraries are working in native out of the box.

The first issue you have is relatively simple to fix: you have to register `com.google.cloud.sql.postgres.SocketFactory` for reflection. See https://quarkus.io/guides/writing-native-applications-tips#registering-for-reflection for guidance about this. The annotation approach with `target` is the way to go in your case.

Now I have no idea if it will be the only problem you will have. Maybe it would make sense to include an extension here https://github.com/quarkiverse/quarkus-google-cloud-services but that will be for @loicmathieu to decide.

**Comment by anthonydenecheau** [comment] 2022-04-07 07:52
It seems to be working now. I think I misinterpreted the logs. By the way, I also added this solution to my deployment https://github.com/quarkusio/quarkus/pull/6634#issuecomment-913658851
I'm sorry I can't say more...

**Comment by loicmathieu** [comment] 2022-04-11 12:31
We document the usage of Cloud SQL but never tested it on native, I need to test it in native. Apparently some people report it to work when adding the google-cloud-graalvm-support library, if it's all that is needed we can add it to the documentation (this library is already used by Quarkus GCP support extension).

We can also add a new extension to the existing GCP extension pack for Cloud SQL for native support as it's a very commonly used cloud service.

**Comment by geoand** [comment] 2022-10-19 09:58
Closing as this is about a very old version of Quarkus.

If this is still an issue, feel free to reopen and/or comment

**Closed by geoand** 2022-10-19 09:58 UTC
Labels: kind/question, triage/needs-triage

**Comment by gunjanthesystem** [comment] 2024-08-16 00:32
Still getting same error. Followed: https://quarkus.io/guides/deploying-to-google-cloud#using-cloud-sql-with-a-jdbc-driver .  Please suggest. Using non reactive jdbc approach.

Error:
> Caused by: org.postgresql.util.PSQLException: The SocketFactory class provided com.google.cloud.sql.postgres.SocketFactory  could not be instantiated.
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:43)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:231)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:273)
	at org.postgresql.Driver.makeConnection(Driver.java:446)
	at org.postgresql.Driver.connect(Driver.java:298)
	at io.agroal.pool.ConnectionFactory.createConnection(ConnectionFactory.java:225)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:580)
	at io.agroal.pool.ConnectionPool$CreateConnectionTask.call(ConnectionPool.java:561)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at io.agroal.pool.util.PriorityScheduledExecutor.beforeExecute(PriorityScheduledExecutor.java:75)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	... 1 more
Caused by: java.lang.ClassNotFoundException: com.google.cloud.sql.postgres.SocketFactory 
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:117)
	at io.quarkus.bootstrap.runner.RunnerClassLoader.loadClass(RunnerClassLoader.java:67)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:421)
	at java.base/java.lang.Class.forName(Class.java:412)
	at org.postgresql.util.ObjectFactory.instantiate(ObjectFactory.java:50)
	at org.postgresql.core.SocketFactoryFactory.getSocketFactory(SocketFactoryFactory.java:39)
	... 13 more

> Exception in thread "Shutdown thread" java.lang.NullPointerException: Cannot invoke "io.quarkus.runtime.Application.isStarted()" because "app" is null
	at io.quarkus.runtime.ApplicationLifecycleManager$ShutdownHookThread.run(ApplicationLifecycleManager.java:455)

application.properties is:
> quarkus.datasource.jdbc.url=jdbc:postgresql:///my_db
quarkus.datasource.jdbc.additional-jdbc-properties.cloudSqlInstance=my-gcp-project:us-west4:my-postgres-instance 
quarkus.datasource.jdbc.additional-jdbc-properties.socketFactory=com.google.cloud.sql.postgres.SocketFactory 
quarkus.datasource.username=quarkus
quarkus.datasource.password=quarkus

build.gradle is:
> dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation enforcedPlatform("${quarkusPlatformGroupId}:quarkus-google-cloud-services-bom:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-rest'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-hibernate-orm'
    implementation 'com.google.cloud.sql:postgres-socket-factory:1.15.2'
}
