### ISSUE TITLE
Image generation failed. Exit code: 1 on Microsoft Windows 10 Enterprise LTSC

### ISSUE THREAD

**Issue by rprodan** [quarkusio/quarkus#25927] opened 2022-06-02 11:00 UTC
### Describe the bug

I would like to build a native executable from [Quarkus guide](https://quarkus.io/guides/building-native-image#configuring-graalvm) on **Microsoft Windows 10** Enterprise LTSC 2019 10.0.17763 Build 17763 with **mandrel-java17-22.1.0.0-Final**.
All prerequisites are set up including initialized Microsoft Native Tools for Visual Studio.

However when I run the following command I get exception.

``` 
mvnw package -Dnative
```

### Expected behavior

Successfully built native image from [Quarkus guide](https://quarkus.io/guides/building-native-image#configuring-graalvm).

### Actual behavior

Running the following command in [getting-started directory](https://quarkus.io/guides/getting-started) on local environment.

``` 
mvnw package -Dnative
```

I get the exception

``` 
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.9.2.Final:build (default) on project getting-started: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: io.quarkus.deployment.pkg.steps.NativeImageBuildStep$ImageGenerationFailureException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:400)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:240)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:925)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

It is worth mentioning that another error appears before that

``` 
[ERROR] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Unable to get GraalVM version from the native-image binary.
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] C:\Program Files\Java\mandrel-java17-22.1.0.0-Final\bin\native-image.cmd -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country=GB -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http -H:+InlineBeforeAnalysis -H:-UseServiceLoaderFeature -H:+StackTrace getting-started-1.0.0-SNAPSHOT-runner -jar getting-started-1.0.0-SNAPSHOT-runner.jar
Error: Could not find or load main class Files\Java\mandrel-java17-22.1.0.0-Final\lib\svm\bin\\..\..\jvmci\graal.jar
Caused by: java.lang.ClassNotFoundException: Files\Java\mandrel-java17-22/1/0/0-Final\lib\svm\bin\\//\//\jvmci\graal/jar
```

### Output of `uname -a` or `ver`

Microsoft Windows 10 Enterprise LTSC Version 10.0.17763 Build 17763

### Output of `java -version`

openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, sharing)

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\Users\rprodan\.m2\wrapper\dists\apache-maven-3.8.4-bin\52ccbt68d252mdldqsfsn03jlf\apache-maven-3.8.4 Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: C:\Program Files\Java\mandrel-java17-22.1.0.0-Final Default locale: en_GB, platform encoding: Cp1250 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by rprodan** [comment] 2022-06-03 13:20
Building native image with **graalvm-ce-java17-22.1.0** works as expected.

**Comment by zakkak** [comment] 2022-06-03 16:50
Hi @rprodan it looks like the issue is caused by the "Program Files" directory (which includes a space). Can you please try moving mandrel under a different path that will not include spaces?

If that works, then you have a work around till we fix the issue, and we know what we need to fix :)
Thanks

**Comment by rprodan** [comment] 2022-06-07 10:48
@zakkak the issue was indeed with space character in my environment variable. Honestly speaking I haven't tought space characters are still troublesome nowadays. Non-ascii characters are different story though.

Thank you for your help.

**Comment by zakkak** [comment] 2022-06-07 13:02
Thanks for the confirmation @rprodan .

I am closing this as it's not a Quarkus issue.
Please follow https://github.com/graalvm/mandrel/issues/386 if interested.

**Closed** 2022-06-07 14:04 UTC
Labels: kind/bug, env/windows, area/mandrel
