### ISSUE TITLE
No easy way to expose Swagger UI static content with Keycloak authorization enabled

### ISSUE THREAD

**Issue by michaeljmcd** [quarkusio/quarkus#8204] opened 2020-03-26 17:31 UTC
**Describe the bug**
No easy way to expose Swagger UI static content with Keycloak authorization enabled

**Expected behavior**
It would be possible to have Keycloak authorization and Swagger UI coexist with a minimal rule excluding

**Actual behavior**
Unable to expose Swagger UI for a Keycloak-authorized service without whitelisting each individual static file.

**To Reproduce**
See https://github.com/michaeljmcd/quarkus-swaggerui-issue

Note that the client is configured as a confidential client in order to use authorization services on the endpoints. See [my-client.txt](https://github.com/quarkusio/quarkus/files/4388741/my-client.txt) for an export of the client.

**Configuration**
```properties

# OIDC Configuration
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/master
quarkus.oidc.client-id=my-client-id
quarkus.oidc.credentials.secret=my-client-secret
quarkus.oidc.authentication.scopes=uma_protection

# Enable Policy Enforcement
quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.enforcement-mode=PERMISSIVE

quarkus.keycloak.policy-enforcer.paths.1.path=/swagger-ui/*
quarkus.keycloak.policy-enforcer.paths.1.enforcement-mode=DISABLED
```

**Screenshots**
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux MYHOST 4.4.0-18362-Microsoft #476-Microsoft Fri Nov 01 16:53:00 PST 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: openjdk version "1.8.0_242"OpenJDK Runtime Environment (Zulu 8.44.0.9-CA-linux64) (build 1.8.0_242-b20)OpenJDK 64-Bit Server VM (Zulu 8.44.0.9-CA-linux64) (build 25.242-b20, mixed mode)
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: 1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**

See Zulip conversation at https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Keycloak.20.2B.20Swagger.20UI

Also, the example attempts the format explained at the end of https://github.com/quarkusio/quarkus/issues/6807

**Comment by sberyozkin** [comment] 2020-03-26 17:53
@pedroigor Hey Pedro, can you please investigate, it is becoming a problem for several users :-). 
Perhaps it can delegate to the code checking the [application properties](https://quarkus.io/guides/security#authorization-of-web-endpoints-using-configuration) first, if a given path is already configured there with whatever policy then do not do anything in `quarkus-keycloak-authorization`.
CC @stuartwdouglas 
Thanks

**Comment by pedroigor** [comment] 2020-05-06 20:39
@sberyozkin @michaeljmcd I run the example and I manage to access the swagger-ui.

However, I found an interesting behavior though. If you run the application in dev mode, the paths you defined to the policy enforcer (e.g.: `quarkus.keycloak.policy-enforcer.paths.1.path=/swagger-ui/*`) is not loaded and that causes the policy enforcer to deny the request.

But if you run the application using the test, the paths are loaded and you can access the swagger-ui at `http://localhost:8081/swagger-ui/`. Btw, I had to also `DISABLE` the `/openapi/*` path.

Another interesting thing is that if you run the application using the generated jar, you get a 404 from JAX-RS.

@michaeljmcd Are you runnin in dev mode? Can you confirm the behavior I mentioned above?

**Comment by skmindbit** [comment] 2020-05-15 07:32
I've just found this issue since I have the same problem in Quarkus 1.4.2. 
In 1.3.2 I can access swagger-ui when starting in dev mode (/openapi/* and /swagger-ui/* policy enforcement disabled in .properties). With just an upgrade to Quarkus 1.4.2 and no other changes it doesn't work anymore. Root context path is not changed.

**Comment by sberyozkin** [comment] 2020-05-25 09:35
Hi @michaeljmcd @pedroigor @skmindbit I'm going to close this issue as a duplicate of #9565 since this issue is an example of a more general `quarkus-keycloak-authorization` dev mode issue

**Closed by sberyozkin** 2020-05-25 09:35 UTC
Labels: area/keycloak-authorization, area/oidc, kind/bug
