### ISSUE TITLE
SmallRyeConfigBuilder.getConverterType NoSuchMethodException

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#3476] opened 2019-08-12 05:02 UTC
version is 0.20.0
error project is https://github.com/qwlabs/quarkus-issues/tree/master/2019-06-21-21-00

```bash
> Task :quarkusDev
Starting process:
/Users/pipinet/.sdkman/candidates/java/8.0.201-oracle/jre/bin/java
-Xdebug
-Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
-XX:TieredStopAtLevel=1
-Xverify:none
-Djava.util.logging.manager=org.jboss.logmanager.LogManager
-jar
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/quarkus-issue-0.1-dev.jar
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/classes/java/main,/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/resources/main
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/wiring-classes
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/transformer-cache
Args:
/Users/pipinet/.sdkman/candidates/java/8.0.201-oracle/jre/bin/java
-Xdebug
-Xrunjdwp:transport=dt_socket,address=5005,server=y,suspend=n
-XX:TieredStopAtLevel=1
-Xverify:none
-Djava.util.logging.manager=org.jboss.logmanager.LogManager
-jar
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/quarkus-issue-0.1-dev.jar
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/classes/java/main,/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/resources/main
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/wiring-classes
/Users/pipinet/qwlabs/quarkus-issues/2019-06-21-21-00/build/transformer-cache

12:58:15,984 INFO  [io.qua.dep.QuarkusAugmentor] Beginning quarkus augmentation
12:58:16,095 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at io.quarkus.runtime.configuration.ConverterSupport.converterToItem(ConverterSupport.java:83)
        at io.quarkus.runtime.configuration.ConverterSupport.getConverters(ConverterSupport.java:95)
        at io.quarkus.runtime.configuration.ConverterSupport.<clinit>(ConverterSupport.java:29)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:207)
        at io.quarkus.deployment.ExtensionLoader.loadStepsFrom(ExtensionLoader.java:137)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:75)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:107)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:171)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:89)
Caused by: java.lang.IllegalStateException: Unexpected reflection failure
        at io.quarkus.runtime.configuration.ConverterFactory.reflectionFailure(ConverterFactory.java:50)
        at io.quarkus.runtime.configuration.ConverterFactory.getConverterTypeMethod(ConverterFactory.java:69)
        at io.quarkus.runtime.configuration.ConverterFactory.<clinit>(ConverterFactory.java:19)
        ... 9 more
Caused by: java.lang.NoSuchMethodException: io.smallrye.config.SmallRyeConfigBuilder.getConverterType(java.lang.Class)
        at java.lang.Class.getDeclaredMethod(Class.java:2130)
        at io.quarkus.runtime.configuration.ConverterFactory.getConverterTypeMethod(ConverterFactory.java:67)
        ... 10 more

12:58:16,097 ERROR [io.qua.dev.DevModeMain] Failed to start Quarkus, attempting to start hot replacement endpoint to recover
12:58:16,155 INFO  [org.jbo.threads] JBoss Threads version 3.0.0.Beta5
12:58:16,172 INFO  [org.xnio] XNIO version 3.7.2.Final
12:58:16,192 INFO  [org.xni.nio] XNIO NIO Implementation Version 3.7.2.Final
```

**Comment by gwenneg** [comment] 2019-08-12 08:38
Hi @pipinet!

I just had a quick look at the dependency tree of your reproducer and found two versions of the `smallrye-config` dependency:

```
+--- io.quarkus:quarkus-arc:0.20.0
|    +--- io.quarkus:quarkus-core:0.20.0
|    |    +--- io.smallrye:smallrye-config:1.3.5 -> 1.3.6
+--- io.quarkus:quarkus-resteasy:0.20.0
|    \--- io.quarkus:quarkus-resteasy-server-common:0.20.0
|         +--- io.quarkus:quarkus-resteasy-common:0.20.0
|         |    +--- org.jboss.resteasy:resteasy-core:4.1.1.Final
|         |    |    \--- io.smallrye:smallrye-config:1.3.6 (*)
```

Could you try again after adding the following line to at the beginning of the `dependencies { }` closure of your `build.gradle` file? `implementation enforcedPlatform('io.quarkus:quarkus-bom:0.20.0')`

After that, the `smallrye-config` version from `quarkus-bom` (which is `1.3.5`) will be used everywhere in your project and the issue should be gone.

**Comment by gwenneg** [comment] 2019-08-12 09:00
@kenfinnigan @dmlloyd Please note that we have two different versions of `smallrye-config` in the Quarkus dependency tree. We're good on the Quarkus side because of the BOM, but downgrading the dependency to `1.3.5` could have consequences on `org.jboss.resteasy:resteasy-core`.

**Comment by kenfinnigan** [comment] 2019-08-12 12:17
Unfortunately, that's going to happen a lot the more MP Config is used within different projects

**Comment by rsvoboda** [comment] 2019-08-19 10:58
I see the same issue when I tried to update to `<smallrye-config.version>1.3.9</smallrye-config.version>` (from version 1.3.5).

I think @dmlloyd planned to update SR Config at some point, but not 100% sure.

What are possible detection and mitigation strategies for these multi-version collisions in dependency tree ?

**Comment by dmlloyd** [comment] 2019-08-21 13:23
Right the solution is going to be to upgrade SmallRye Config.  I was waiting for eclipse/microprofile-config#407 to reach some kind of resolution before I committed Quarkus to what might end up being non-spec behavior.

**Comment by kenfinnigan** [comment] 2019-08-26 13:52
Unfortunately, it looks like that issue is considered a "breaking change", so it wouldn't be included in a release anytime soon.

**Comment by dmlloyd** [comment] 2019-08-29 13:13
This should be fixed now.

**Closed by dmlloyd** 2019-08-29 13:13 UTC
Labels: bug, component:config
