### ISSUE TITLE
NullPointerException in OpenTracingAsyncInterceptor when using @CacheResult

### ISSUE THREAD

**Issue by guldner** [quarkusio/quarkus#8483] opened 2020-04-08 22:17 UTC
**Describe the bug**
NullPointerException after adding @CacheResult.

**Expected behavior**
@CacheResult and jaeger tracing both works.

**Actual behavior**
Adding @CacheResult to a method that calls a reactive RestClient, results in a nullpointerexception if `quarkus.jaeger.enabled=true`.

@CacheResult works fine if `quarkus.jaeger.enabled=false`
just like `quarkus.jaeger.enabled=true` works fine if not using @CacheResult

**To Reproduce**
1. Run the attached sample app
2. Go to http://localhost:8080/api/reactiveposts/123

**Configuration**
```properties
Attached 
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17134.1304]
 - Output of `java -version`: java version "1.8.0_241"
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.3.1.FINAL
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3

**Additional context**
The app has three endpoints. Two works, one fails. See the ReadMe.

[quarkus-npe-cache-jaeger.zip](https://github.com/quarkusio/quarkus/files/4453052/quarkus-npe-cache-jaeger.zip)

**Comment by gwenneg** [comment] 2020-04-09 00:29
Thanks for reporting this issue @guldner. I'll take a look at it.

**Comment by gwenneg** [comment] 2020-04-09 20:07
I tested your reproducer with #8227 and it is still failing, so this issue doesn't seem related to context propagation as I suspected. I am now trying to identify the cause of the NPE.

**Comment by gwenneg** [comment] 2020-04-09 21:14
The issue here is most probably the same one as in #8221.

**Comment by gwenneg** [comment] 2020-07-29 21:39
Hi @guldner! Sorry you had to wait so long for an update on this issue. I just tried to reproduce it using Quarkus `1.6.1.Final` and the NPE seems to be gone with this version of Quarkus. Could you please give it a try?

**Comment by gwenneg** [comment] 2020-11-10 22:59
I checked again with `1.9.2.Final` and still no NPE. The issue must have been fixed at some point between 1.3.1.Final and now.

I'm closing this issue. Do not hesitate to reopen it if the bug is still there.

**Closed by gwenneg** 2020-11-10 22:59 UTC
Labels: area/cache, kind/bug
