### ISSUE TITLE
NPE when server fails to start due to config issue

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#37827] opened 2023-12-19 08:25 UTC
When Quarkus fails to start with a config issue, we can end up with a NPE.

This is not a behavior we want.

```
2023-12-19T05:52:19.5967559Z java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
2023-12-19T05:52:19.5969084Z 	at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:638)
2023-12-19T05:52:19.5970872Z 	at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:706)
2023-12-19T05:52:19.5972290Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-12-19T05:52:19.5974660Z 	Suppressed: java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
2023-12-19T05:52:19.5977377Z 		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:915)
2023-12-19T05:52:19.5979055Z 		at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:907)
2023-12-19T05:52:19.5980766Z 		at io.quarkus.test.junit.QuarkusTestExtension.interceptAfterAllMethod(QuarkusTestExtension.java:901)
2023-12-19T05:52:19.5982145Z 		at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
2023-12-19T05:52:19.5983366Z 		at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1092)
2023-12-19T05:52:19.5984387Z 		... 1 more
2023-12-19T05:52:19.5985036Z Caused by: java.lang.RuntimeException: Failed to start quarkus
2023-12-19T05:52:19.5986074Z 	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
2023-12-19T05:52:19.5987086Z 	at io.quarkus.runtime.Application.start(Application.java:101)
2023-12-19T05:52:19.5988088Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-12-19T05:52:19.5989463Z 	at io.quarkus.runner.bootstrap.StartupActionImpl.run(StartupActionImpl.java:285)
2023-12-19T05:52:19.5990909Z 	at io.quarkus.test.junit.QuarkusTestExtension.doJavaStart(QuarkusTestExtension.java:252)
2023-12-19T05:52:19.5992412Z 	at io.quarkus.test.junit.QuarkusTestExtension.ensureStarted(QuarkusTestExtension.java:605)
2023-12-19T05:52:19.5994074Z 	at io.quarkus.test.junit.QuarkusTestExtension.beforeAll(QuarkusTestExtension.java:655)
2023-12-19T05:52:19.5995090Z 	... 1 more
2023-12-19T05:52:19.5997238Z Caused by: jakarta.enterprise.inject.spi.DeploymentException: io.quarkus.runtime.configuration.ConfigurationException: Failed to load config value of type class java.lang.String for: quarkus.http.insecure-requests
2023-12-19T05:52:19.5999341Z 
2023-12-19T05:52:19.6000028Z 	at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:70)
2023-12-19T05:52:19.6001661Z 	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigValues1665125174.deploy_0(Unknown Source)
2023-12-19T05:52:19.6003572Z 	at io.quarkus.deployment.steps.ConfigBuildStep$validateConfigValues1665125174.deploy(Unknown Source)
2023-12-19T05:52:19.6004885Z 	... 8 more
2023-12-19T05:52:19.6006610Z 	Suppressed: java.util.NoSuchElementException: SRCFG00014: The config property quarkus.http.insecure-requests is required but it could not be found in any config source
2023-12-19T05:52:19.6008613Z 		at io.smallrye.config.SmallRyeConfig.convertValue(SmallRyeConfig.java:296)
2023-12-19T05:52:19.6009975Z 		at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:104)
2023-12-19T05:52:19.6011482Z 		at io.quarkus.arc.runtime.ConfigRecorder.validateConfigProperties(ConfigRecorder.java:60)
2023-12-19T05:52:19.6012587Z 		... 10 more
2023-12-19T05:52:19.6014286Z Caused by: io.quarkus.runtime.configuration.ConfigurationException: Failed to load config value of type class java.lang.String for: quarkus.http.insecure-requests
```

**Comment by gsmet** [comment] 2024-01-09 18:08
I digged into this a bit and the problem is coming from `QuarkusTestExtension`. The issue is that in when `interceptAfterAllMethod` calls `runExtensionMethod`,    `runningQuarkusApplication` might be null if the application didn't start which is the case here.

The first use of `runningQuarkusApplication` is easily fixable by not setting the TCCL if `runningQuarkusApplication` is not started but I'm not entirely sure about how to fix the second one when the arguments are cloned.

@geoand you're probably the best person to have a look at this one.

**Comment by geoand** [comment] 2024-01-09 18:11
Do you have a ready made sample I can use?

**Comment by geoand** [comment] 2024-01-10 07:46
I was not able to reproduce it in a very simple test

**Comment by geoand** [comment] 2024-08-26 12:43
Let's close this for now and reopen if we see the problem again in the future

**Closed by geoand** 2024-08-26 12:43 UTC
Labels: kind/bug, area/config, area/testing, triage/needs-reproducer
