### ISSUE TITLE
Quarkus 2, hibernate query-plan cache increases when binding numeric parameters

### ISSUE THREAD

**Issue by artomasz** [quarkusio/quarkus#34819] opened 2023-07-18 14:38 UTC
### Describe the bug

With Quarkus 2, I observed that SessionFactoryImpl object takes more that 65% of heap memory. It contains many QueryPlanCache items for queries like:

```plpgsql
select distinct generatedAlias0 from Relationship as generatedAlias0 left join generatedAlias0.relatedItem as generatedAlias1 
where ( generatedAlias0.type<>:param0 ) and ( generatedAlias0.item.businessId=1426L )
``` 
QueryPlanCache contains separate query-plan item for each businessId, which is numeric parameter.

This behavior can be changed with property hibernate.criteria.literal_handling_mode set to bind, but this property cannot be used in application.properties.

### Expected behavior

Would be great to have possibility to configure LiteralHandlingMode as a property in application properties. 

### Actual behavior

LiteralHandlingMode has default value auto and cannot be configured in application.properties. Hibernate's query plan is not properly cached, what has the influence on memory consumption and time of query execution (such QueryPlanCache is useless). 

### How to Reproduce?

To reproduce:
- build hibernate query with numeric parameter. 
- execute the query hundred of times 
- observe java heap usage, check QueryPlanCache in heap dump

### Output of `uname -a` or `ver`

Linux ftth-service-inventory-app-7968766d66-hmvcs 5.4.228-132.418.amzn2.x86_64 #1 SMP Wed Jan 25 23:14:15 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.5 2022-10-18 LTS

### Quarkus version or git rev

2.16.7.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.0

**Comment by geoand** [comment] 2023-07-21 08:04
Have you checked the numbers with Quarkus 3.2?

**Comment by gsmet** [comment] 2023-07-21 10:50
And in any case, could you provide a small reproducer for 2.16?

**Comment by Sanne** [comment] 2023-07-24 11:26
@beikov just explained to me that `hibernate.criteria.literal_handling_mode` was removed in ORM 6, so exposing it is not an option. There's now CRITERIA_VALUE_HANDLING_MODE = "hibernate.criteria.value_handling_mode", slightly different semantics.

Let's see how to improve this, I agree that the current semantics is surprising as a default but there might be more to this that I don't know yet - I'll talk with the team.

**Comment by beikov** [comment] 2023-07-24 11:30
Since in ORM 6 the default is to render values as parameters, which will solve the problem the user describes, I don't think it is sensible to allows setting this to a different value. People really shouldn't set this to `INLINE`, unless they really really know what they are doing.
Apart from that, since ORM 6 does not cache query plans for criteria queries anymore, this is even less of a problem.

**Comment by Sanne** [comment] 2023-07-24 11:32
The Hibernate team doesn't believe this would affect Quarkus 3.+ as Hibernate ORM 6 should do the right thing:
 - [CRITERIA_VALUE_HANDLING_MODE = "hibernate.criteria.value_handling_mode"](https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/.E2.9C.94.20Query.20plan.20cache.20to.20include.20parameter.20values.3F)

@artomasz I'd suggest use the unsupported properties facility in Quarkus 2, it's probably not worth it to add an official property at this stage for Quarkus 2 especially as it would need to be removed when upgrading to Quarkus 3.

 - https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key

I'll close this - feel free to reopen if you see this problem on Quarkus 3.2

**Closed by Sanne** 2023-07-24 11:32 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm, area/cache, triage/needs-feedback

**Comment by gavinking** [comment] 2023-07-24 12:01
> `hibernate.criteria.literal_handling_mode` was removed in ORM 6

To clarify: it's not removed, it's still there, it's just that `BIND` is now the default.
