### ISSUE TITLE
gRPC service failed with NoSuchMethodError  com.google.protobuf.Descriptors$FileDescriptor 

### ISSUE THREAD

**Issue by xmlking** [quarkusio/quarkus#9766] opened 2020-06-04 03:36 UTC
**Describe the bug**
starting server throwing following error:
 java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$FileDescriptor com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(java.lang.String[], com.google.protobuf.Descriptors$FileDescriptor[])'

Env: quarkus 1.5.0, kotlin , gradle 

**Expected behavior**
the server should start properly with ` gradle :apps:greeting-service:quarkusDev`
**Actual behavior**

Error
```
> Configure project :
Version: 1.6.5-SNAPSHOT,  Branch: develop, isCI: false
SpotlessChangelog Version Next: 1.7.0-SNAPSHOT  Last: 1.6.4

> Task :apps:greeting-service:quarkusDev
Listening for transport dt_socket at address: 5005
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/schintha/.gradle/caches/modules-2/files-2.1/org.slf4j/slf4j-simple/1.7.25/8dacf9514f0c707cbbcdd6fd699e8940d42fb54e/slf4j-simple-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/schintha/.gradle/caches/modules-2/files-2.1/org.jboss.slf4j/slf4j-jboss-logging/1.2.0.Final/bff294c02b64ad6bf8af6e6994e186dc035e0a47/slf4j-jboss-logging-1.2.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.SimpleLoggerFactory]
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
20:29:37 INFO  [io.qu.gr.ru.GrpcServerRecorder] (Quarkus Main Thread) Registering gRPC reflection service
20:29:37 ERROR [io.qu.application] (Quarkus Main Thread) Failed to start application: java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$FileDescriptor com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(java.lang.String[], com.google.protobuf.Descriptors$FileDescriptor[])'
        at micro.apps.proto.echo.v1.EchoServiceProto.<clinit>(EchoServiceProto.java:60)
        at micro.apps.proto.echo.v1.EchoServiceGrpc$EchoServiceBaseDescriptorSupplier.getFileDescriptor(EchoServiceGrpc.java:308)
        at io.quarkus.grpc.runtime.reflection.GrpcServerIndex.<init>(GrpcServerIndex.java:46)
        at io.quarkus.grpc.runtime.reflection.ReflectionService.<init>(ReflectionService.java:32)
        at io.quarkus.grpc.runtime.GrpcServerRecorder.initializeGrpcServer(GrpcServerRecorder.java:106)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy_0(GrpcServerProcessor$build215158828.zig:90)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy(GrpcServerProcessor$build215158828.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:450)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)

20:29:37 ERROR [io.qu.ru.Application] (Quarkus Main Thread) Error running Quarkus application: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:559)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$FileDescriptor com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(java.lang.String[], com.google.protobuf.Descriptors$FileDescriptor[])'
        at micro.apps.proto.echo.v1.EchoServiceProto.<clinit>(EchoServiceProto.java:60)
        at micro.apps.proto.echo.v1.EchoServiceGrpc$EchoServiceBaseDescriptorSupplier.getFileDescriptor(EchoServiceGrpc.java:308)
        at io.quarkus.grpc.runtime.reflection.GrpcServerIndex.<init>(GrpcServerIndex.java:46)
        at io.quarkus.grpc.runtime.reflection.ReflectionService.<init>(ReflectionService.java:32)
        at io.quarkus.grpc.runtime.GrpcServerRecorder.initializeGrpcServer(GrpcServerRecorder.java:106)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy_0(GrpcServerProcessor$build215158828.zig:90)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy(GrpcServerProcessor$build215158828.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:450)
        ... 12 more

Quarkus application exited with code 1
Press Enter to restart or Ctrl + C to quit
20:29:37 ERROR [io.qu.de.de.DevModeMain] (main) Failed to start Quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
        at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:155)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:93)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:281)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:41)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:131)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:84)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:126)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:56)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:559)
        at io.quarkus.runtime.Application.start(Application.java:90)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:90)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:61)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:144)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.NoSuchMethodError: 'com.google.protobuf.Descriptors$FileDescriptor com.google.protobuf.Descriptors$FileDescriptor.internalBuildGeneratedFileFrom(java.lang.String[], com.google.protobuf.Descriptors$FileDescriptor[])'
        at micro.apps.proto.echo.v1.EchoServiceProto.<clinit>(EchoServiceProto.java:60)
        at micro.apps.proto.echo.v1.EchoServiceGrpc$EchoServiceBaseDescriptorSupplier.getFileDescriptor(EchoServiceGrpc.java:308)
        at io.quarkus.grpc.runtime.reflection.GrpcServerIndex.<init>(GrpcServerIndex.java:46)
        at io.quarkus.grpc.runtime.reflection.ReflectionService.<init>(ReflectionService.java:32)
        at io.quarkus.grpc.runtime.GrpcServerRecorder.initializeGrpcServer(GrpcServerRecorder.java:106)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy_0(GrpcServerProcessor$build215158828.zig:90)
        at io.quarkus.deployment.steps.GrpcServerProcessor$build215158828.deploy(GrpcServerProcessor$build215158828.zig:36)
        at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:450)
        ... 12 more

```

**To Reproduce**
1.  `git clone https://github.com/xmlking/micro-apps.git`
2. `gradle :apps:greeting-service:quarkusDev`
 
 
  the following service is used
```kt
package micro.apps.greeting

import io.grpc.stub.StreamObserver
import javax.inject.Singleton
import micro.apps.proto.echo.v1.EchoRequest
import micro.apps.proto.echo.v1.EchoResponse
import micro.apps.proto.echo.v1.EchoServiceGrpc
import micro.apps.proto.echo.v1.EchoStreamRequest
import micro.apps.proto.echo.v1.EchoStreamResponse

@Singleton
class EchoService0 : EchoServiceGrpc.EchoServiceImplBase() {
    override fun echo(request: EchoRequest, responseObserver: StreamObserver<EchoResponse?>) {
        val name: String = request.message
        val message = "Hello $name"
        responseObserver.onNext(EchoResponse.newBuilder().setMessage(message).build())
        responseObserver.onCompleted()
    }
}
```

**Comment by xmlking** [comment] 2020-06-04 03:41
To reproduce please uncomment `EchoService0` class and  start the server with `gradle :apps:greeting-service:quarkusDev` 

https://github.com/xmlking/micro-apps/blob/develop/apps/greeting-service/src/main/kotlin/micro/apps/greeting/EchoService.kt

**Comment by michalszynkiewicz** [comment] 2020-06-23 12:13
@xmlking thanks for the report!
Could you simplify the reproducer a bit? 
This one uses quarkus-grpc together with kotlin-grpc and the gradle confing is not that simple, it's not that easy for me (being gradle noob) to spot what the problem is with it.

**Comment by michalszynkiewicz** [comment] 2020-06-23 12:14
Also, quarkusDev starts for me locally with the EchoService0 uncommented, on the current `develop` branch

**Comment by xmlking** [comment] 2020-06-24 14:24
i have protos in a sub-project under `libs\protos` which user default grpc java code generated
the test project is under `/apps` which uses generated code under libs. 
I am not using ` quarkus-grpc` to generate code from photos.

**Comment by michalszynkiewicz** [comment] 2020-07-07 19:01
@xmlking I think the reason is mixed versions of grpc dependencies.
But with my knowledge of gradle and with your project being quite complicated I'm having trouble checking it.

**Comment by michalszynkiewicz** [comment] 2020-07-27 14:46
@xmlking could you try with the current master (or 1.7.0.CR1 when it's released)?
I bumped the versions of grpc and protobuf dependencies in Quarkus.

**Comment by xmlking** [comment] 2020-07-27 17:41
thanks @michalszynkiewicz  will try

**Comment by michalszynkiewicz** [comment] 2020-07-27 19:53
Thank you for trying!

What I meant by "when it's released" is that it's not released yet. According to the release plan, it should be released on July 30: https://github.com/quarkusio/quarkus/wiki/Release-Planning

**Comment by leoiii12** [comment] 2020-08-03 15:31
I got the same error when i was using the google cloud api.

```
<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>libraries-bom</artifactId>
    <version>8.1.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

...

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-language</artifactId>
</dependency>
```

I finally resolved it.

```
<protoc.version>3.12.2</protoc.version>

...

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>libraries-bom</artifactId>
    <version>8.1.0</version>
    <type>pom</type>
    <scope>import</scope>
</dependency>

...

<dependency>
    <groupId>com.google.cloud</groupId>
    <artifactId>google-cloud-language</artifactId>
    <exclusions>
        <exclusion>
            <groupId>com.google.protobuf</groupId>
            <artifactId>protobuf-java</artifactId>
        </exclusion>
    </exclusions>
</dependency>
<dependency>
    <groupId>com.google.protobuf</groupId>
    <artifactId>protobuf-java</artifactId>
    <version>${protoc.version}</version>
</dependency>
```

**Comment by michalszynkiewicz** [comment] 2020-09-28 13:00
@xmlking do you still experience this issue with `1.8.1.Final`

**Comment by xmlking** [comment] 2020-09-29 03:25
Will try tomorrow

**Comment by michalszynkiewicz** [comment] 2020-10-03 19:27
@glefloch if you could take a look at this one, it would be great :)
I suspect there are the version of grpc is wrong because of some other (non-quarkus) grpc dependencies

**Comment by glefloch** [comment] 2020-10-04 06:06
@michalszynkiewicz yes I will have a look

**Comment by glefloch** [comment] 2020-10-07 16:07
The first time you run `./gradlew :apps:greeting-service:quarkusDev` it actually works. But the second time, I get the error `java.lang.NoSuchMethodError`. 
Running `./gradlew :apps:greeting-service:quarkusDev` makes everything work again. We are missing something in `quarkusDev` start the second time

**Comment by glefloch** [comment] 2020-10-07 20:08
@xmlking I can reproduce your last error but not the first one. 
Looking at the error, it looks like the error comes from the generated code. Commenting the `EchoService` remove the error. 
Were you able to have coroutine and grpc working together?

**Comment by xmlking** [comment] 2020-10-08 16:03
`Were you able to have coroutine and grpc working together?` <--  I tried grpc + kotlin flow (i guess internally flow use coroutines) which worked. 
https://github.com/xmlking/micro-apps/tree/develop/apps/account-service

**Comment by michalszynkiewicz** [comment] 2021-07-19 16:07
A lot has changed in the area. I will close the issue as it's likely solved in 2.x but please reopen/let us know if it's still there.

**Closed by michalszynkiewicz** 2021-07-19 16:07 UTC
Labels: kind/bug
