### ISSUE TITLE
not a subtype on java 11 with fault-tolerance - when running on custom ForkJoinPool

### ISSUE THREAD

**Issue by danowrw** [quarkusio/quarkus#9397] opened 2020-05-18 07:51 UTC
**Describe the bug**
When executing streams on custom ForkJoinPool with fault-tolerance annotation and java 11 Adopt you get below. This works on java 8 Adopt.

not a subtype
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at org.acme.ExampleResource.notWorkingOnJava11Adopt(ExampleResource.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:123)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2046)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1578)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:588)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1236)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1264)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1299)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1384)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:110)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:86)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:105)
	at io.smallrye.config.inject.ConfigProducer.getConfig(ConfigProducer.java:44)
	at io.smallrye.config.inject.ConfigProducer.produceBooleanConfigProperty(ConfigProducer.java:86)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.create(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:101)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:344)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.get(ConfigProducer_ProducerMethod_produceBooleanConfigProperty_4052c0cbfaba0eb3bbfc4a1d91d5a3d235c1dbf5_Bean.zig:44)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:53)
	at io.smallrye.faulttolerance.metrics.MetricsCollectorFactory_Bean.create(MetricsCollectorFactory_Bean.zig:326)
	at io.smallrye.faulttolerance.metrics.MetricsCollectorFactory_Bean.create(MetricsCollectorFactory_Bean.zig:32)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:79)
	at io.quarkus.arc.impl.ComputingCache$CacheFunction.lambda$apply$0(ComputingCache.java:99)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:26)
	at io.quarkus.arc.impl.ComputingCache.getValue(ComputingCache.java:41)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:25)
	at io.smallrye.faulttolerance.metrics.MetricsCollectorFactory_ClientProxy.arc$delegate(MetricsCollectorFactory_ClientProxy.zig:57)
	at io.smallrye.faulttolerance.metrics.MetricsCollectorFactory_ClientProxy.createCollector(MetricsCollectorFactory_ClientProxy.zig:103)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$getMetricsCollector$10(FaultToleranceInterceptor.java:509)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
	at io.smallrye.faulttolerance.internal.StrategyCache.getMetrics(StrategyCache.java:27)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.getMetricsCollector(FaultToleranceInterceptor.java:509)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.interceptCommand(FaultToleranceInterceptor.java:145)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(FaultToleranceInterceptor_Bean.zig:471)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl$InterceptorInvocation.invoke(InvocationContextImpl.java:154)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.invokeNext(InvocationContextImpl.java:53)
	at org.jboss.resteasy.microprofile.client.InvocationContextImpl.proceed(InvocationContextImpl.java:89)
	at org.jboss.resteasy.microprofile.client.ProxyInvocationHandler.invoke(ProxyInvocationHandler.java:146)
	at com.sun.proxy.$Proxy57.getOrgs(Unknown Source)
	at org.acme.ExampleResource.getGithubOrgs(ExampleResource.java:63)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
	at java.base/java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.ForEachOps$ForEachTask.compute(ForEachOps.java:290)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinTask.doInvoke(ForkJoinTask.java:408)
	at java.base/java.util.concurrent.ForkJoinTask.invoke(ForkJoinTask.java:736)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateParallel(ForEachOps.java:159)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateParallel(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:233)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:497)
	at org.acme.ExampleResource.lambda$notWorkingOnJava11Adopt$0(ExampleResource.java:35)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Expected behavior**
this should work on java 11 too

**To Reproduce**
1. Checkout https://github.com/danowrw/not-a-subtype
2. Run this on java 11 Adpot
3. call http://localhost:8080/not_working - see this do not work
4. call http://localhost:8080/working -see it works
5. switch to java 8 and see http://localhost:8080/not_working - is working now

**Comment by geoand** [comment] 2020-05-18 08:18
cc @michalszynkiewicz @Ladicek

**Comment by Ladicek** [comment] 2020-05-18 08:24
`Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype`

Wonder how that could be caused by FT...

**Comment by Ladicek** [comment] 2020-05-18 08:27
The reproducer has this comment:

```java
    //below annotation cause execution on custom ForkJoinPool fails
    @Retry
    //This also fails for
    //@Timed
    //@Counted
```

So definitely sounds like not caused by FT.

**Comment by Ladicek** [comment] 2020-05-18 08:28
I'll try the reproducer anyway, and perhaps it's fixed by using ConProp -- I'll report back.

**Comment by Ladicek** [comment] 2020-05-18 08:34
Hmm, if I let the task run on an injected `ManagedExecutor`, it works fine, but if I run the task `ThreadContext.contextualRunnable`-ized on the custom FJ pool, then it fails :open_mouth:

**Comment by geoand** [comment] 2020-05-18 08:37
So sounds like an MP - CP problem, no?

**Comment by Ladicek** [comment] 2020-05-18 08:45
Actually, no. Turns out that the FJ pool sets the context classloader for all threads in the pool to the system classloader. This can be worked around by using a custom `ForkJoinWorkerThreadFactory` that returns a subclass of `ForkJoinWorkerThread`, which allows using a constructor that doesn't set the context  classloader. Like this:

```java
customThreadPool = new ForkJoinPool(4, new ForkJoinPool.ForkJoinWorkerThreadFactory() {
    @Override
    public ForkJoinWorkerThread newThread(ForkJoinPool pool) {
        return new ForkJoinWorkerThread(pool) {};
    }
}, null, false);
```

**Comment by jaikiran** [comment] 2020-05-18 08:48
This looks like an issue with classloading. The `ForkJoinPool` uses the system classloader (which won't have access to some the application jars). Quarkus "fixes" this issue by hacking the "common fork join" pool to set the right classloader for it https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/runner/bootstrap/ForkJoinClassLoading.java#L13. However since the application here is creating a custom `ForkJoinPool` it won't get this "fix" by default. The application will have to use a custom `ForkJoinWorkerThreadFactory` to use the proper classloader. Looks like Java 8 and Java 11 APIs have changed in this area for `ForkJoinPool`, so I'm not sure (I haven't looked in detail) which API is applicable to get this working.

**Comment by Ladicek** [comment] 2020-05-18 08:51
But, if you want to use thread pools manually, I'd suggest using MP CP `ManagedExecutor`. You can configure max number of running tasks and queue size by creating your own instance using `ManagedExecutor.builder()`.

In any case, this is not a bug in Quarkus, I'd say.

**Comment by jaikiran** [comment] 2020-05-18 08:51
> Looks like Java 8 and Java 11 APIs have changed in this area for ForkJoinPool, so I'm not sure (I haven't looked in detail) which API is applicable to get this working.

@Ladicek's reply a few minutes before mine has the sample code which I think should fix this issue for the application
https://github.com/quarkusio/quarkus/issues/9397#issuecomment-630037633

**Comment by geoand** [comment] 2020-05-18 08:51
But at the very least, we should have some piece in the documentation telling people about this?

**Comment by Ladicek** [comment] 2020-05-18 09:00
I can't think of any immediately obvious place in the docs where we can put this and expect people to actually read it :-)

What I think we should do is make context classloader a propagatable item in MP CP. Because if people want to propagate the request scope, propagate current transaction, propagate security context, etc., to their thread pool tasks and use custom thread pools (such as arbitrary FJ pools), they have to `ThreadContext.contextualRunnable`-ize their `Runnable`s anyway. If context classloader was also propagated, it would naturally work.

**Comment by Ladicek** [comment] 2020-05-18 09:06
Hmm, but that seems to be there already: https://github.com/eclipse/microprofile-context-propagation/blob/master/api/src/main/java/org/eclipse/microprofile/context/ThreadContext.java#L235-L247

@FroMage @manovotn Do I understand it correctly that the `Application` context in MP ConProp also includes the context classloader? Because it looks like in Quarkus, the context classloader doesn't propagate, and I can't find any `ThreadContextProvider` in the Quarkus codebase that would capture the context classloader and later restore it.

**Comment by jaikiran** [comment] 2020-05-18 09:10
> Because it looks like in Quarkus, the context classloader doesn't propagate,

Hello @Ladicek, it's not that the context classloader doesn't propagate in Quarkus. The issue here is that the application is using an API (the `ForkJoinPool` constructor which takes just the 1 int param) which (as per its API construct) is instructed to use a `defaultForkJoinWorkerThreadFactory` which doesn't honour the current thread's context classloader. That's why switching to the multi-arg constructor (which allows you to specify which classloader to use) does the trick.

**Comment by Ladicek** [comment] 2020-05-18 09:12
@jaikiran I'm specifically talking about MicroProfile Context Propagation at this point. If that included propagating the context classloader (at this point, I believe it should, but in Quarkus, it doesn't), then I could easily run `ThreadContext.contextualRunnable(() -> { ... })` tasks on arbitrary thread pools, including custom FJ pool.

**Comment by FroMage** [comment] 2020-05-18 09:26
It doesn't propagate the TCCL indeed. We've never had a use-case for it. I guess we could, but I would have to ask @stuartwdouglas his opinion about this because it may be harmful.

**Comment by manovotn** [comment] 2020-05-18 09:43
`Application` context is underspecified in MP CP. The API mentions TCCL so in theory it could/should be there, but to my knowledge there are no TCKs testing this. SR doesn't implement this because, as Stephane said, we haven't had a use case yet.

**Comment by Ladicek** [comment] 2020-05-18 09:43
Well, here's one :-)

**Comment by manovotn** [comment] 2020-05-18 09:52
Yeah, definitely not against it.
I am just thinking... SR propagates everything by default, so assuming we add it there, anyone using it might be in for a surprise if they are relying in TCCL in their apps...
Alternatively, we could just add it into Quarkus for now, but I would also love to hear @stuartwdouglas opinion on that.

**Comment by stuartwdouglas** [comment] 2020-05-19 00:46
How are you going to propagate it to the FJ pool? At least on JDK 8 there are no hooks for that, which is why I have the current crappy hack, not sure if the situation has improved in 11.

**Comment by FroMage** [comment] 2020-05-19 07:37
If you're using MP-CP we can make a `ThreadContextProvider` that captures and restores the TCCL.

**Comment by Ladicek** [comment] 2020-05-19 08:02
I was only talking about using MP CP, which users must do explicitly. (I'd personally even consider removing that crappy hack, if it's only for user applications -- when users move execution to a separate thread pool, they should use ConProp.)

**Comment by stuartwdouglas** [comment] 2020-05-20 00:31
Yea, but you can't do it automatically.
The big problem is CompletionStage Async methods, which use the pool by default with no way to capture the context. Hopefully the move to Mutiny means this is no longer a problem.

**Comment by Ladicek** [comment] 2020-05-20 06:37
I think my point is that user should use ConProp explicitly if they are submitting tasks to arbitrary thread pools. (It's not just TCCL, it's also CDI request context, security context, etc.)

At least for now, there's no better way.

(And it would require ConProp to propagate the TCCL, which it currently doesn't :-) )

**Comment by FroMage** [comment] 2020-05-20 07:53
> Yea, but you can't do it automatically.

With MP-CP and `CompletionStage` it's indeed always manual. But if you already have to wrap your `CS` to get the Request Context, you'll get the `TCCL` for free.

> The big problem is CompletionStage Async methods, which use the pool by default with no way to capture the context. Hopefully the move to Mutiny means this is no longer a problem.

Once you've wrapped (contextualised) your `CS`, even `Async` methods are contextualised, so I'm not sure what you mean. And if you're not wrapping the `CS` you don't get any context, `Async` or not, which leads to your request not working if (almost inevitably: when) it ends up on the event loop.

**Comment by brundipub** [comment] 2021-04-13 14:09
Hi guys,
any progress on this issue pls ?  While planning to update Quarkus to version 13, we hoped this exception would dissapear with new Quarkus. 
Unfortunatelly we're still facing it with Quarkus 13 (smallrye-fault-tolerance 4.3.2)
Neither JDK update (15.0.2) has any impact.

**Comment by gsmet** [comment] 2021-04-13 14:22
@brundipub have you seen some of the workarounds proposed in the thread?

**Comment by Ladicek** [comment] 2021-04-13 15:09
I guess my opinion didn't change on this: this is not a Quarkus bug. One, most of the time, you should use the thread pool that Quarkus gives you (`@Inject org.eclipse.microprofile.context.ManagedExecutor`). Two, if you use a custom thread pool (including the default FJ pool, which I'd personally consider a custom thread pool from Quarkus perspective) and require some sort of context propagation (which includes TCCL), you should use MicroProfile Context Propagation manually. If you don't need any kind of context propagation, just want to use a FJ pool, you unfortunately hit the case described here: https://github.com/quarkusio/quarkus/issues/9397#issuecomment-630037633 (which we can't do anything about).

**Comment by brundipub** [comment] 2021-04-14 06:52
@Ladicek  @gsmet  Sorry for not testing the workaround proposed by Ladicek before.  Tested today, it DOES FIX our issue.  Ignore my comment pls.

**Comment by ambition-consulting** [comment] 2021-06-09 05:45
So is everybody still working on JDK8, or why is nobody else complaining about this basic problem? Basically I have to restart my application after every change, because this error is guaranteed to happen after some idle time. Giving up on fault-tolerance isn't an option either.

**Comment by Ladicek** [comment] 2021-06-09 07:17
@ambition-consulting Did you read the comments above? I'd suggest to at least read https://github.com/quarkusio/quarkus/issues/9397#issuecomment-630037633 and https://github.com/quarkusio/quarkus/issues/9397#issuecomment-818812606. I'd be happy to be convinced that this can actually be solved in Quarkus, but "why is nobody else complaining about this basic problem" is not gonna cut it.

**Comment by ambition-consulting** [comment] 2021-06-09 08:20
Yes I did, but am not sure which Quarkus plugin is using the wrong ForkJoinPool, and wouldn't be able to change their code anyway. The great thing about this bug is, that it's not deterministically reproducible and the exception does not help really.

However, even though the stack trace looks exactly the same, and I am using JDK 11 with fault-tolerance also, maybe my application has a different reason, since you seem to be expecting me to constructing a custom ForkJoinPool, which I really am not.

**Comment by Ladicek** [comment] 2021-06-09 09:12
> since you seem to be expecting me to constructing a custom ForkJoinPool, which I really am not

That might be the cause (in which case it's really easy to fix), but a more likely cause is the usage of the _common_ FJ pool. That easily happens e.g. when you're using parallel streams. Can you check that?

(There is a hack in Quarkus that attempts to set the TCCL of all threads in the common FJ pool to the Quarkus class loader, but that has a problem: threads in a FJ pool can be discarded and recreated. The newly created threads will not have the correct TCCL, leading to the present issue.)

**Comment by ambition-consulting** [comment] 2021-06-09 20:43
Thanks, I will look into this. One last question: I only experience the problem in dev mode - prod mode (with fast-jar) has been unaffected. Is this in line with the current understanding of this bug? If not, maybe I should wait for the next occasion and share the complete stack trace. I got so used to restarting during development and not being able to fix this, and only now realize that it won't go away with some future patch as I had hoped.

**Comment by stuartwdouglas** [comment] 2021-06-10 01:46
```

    ForkJoinPool customThreadPool;

    void onStart(@Observes StartupEvent ev) {
        ClassLoader tccl = Thread.currentThread().getContextClassLoader();
        customThreadPool = new ForkJoinPool(4, new ForkJoinPool.ForkJoinWorkerThreadFactory() {
            @Override
            public ForkJoinWorkerThread newThread(ForkJoinPool pool) {
                ForkJoinWorkerThread forkJoinWorkerThread = new ForkJoinWorkerThread(pool) {

                };
                forkJoinWorkerThread.setContextClassLoader(tccl);
                return forkJoinWorkerThread;
            }
        }, null, false);
    }

    @PreDestroy
    void stop() {
        customThreadPool.shutdown();
    }
```

Change you code to the above and you should be ok. Basically it will create a thread with the correct TCCL set.

**Comment by stuartwdouglas** [comment] 2021-06-10 01:47
Also instead of passing in 'null' for the 3rd param in the real world you probably want an exception handler of some kind that would at least log a message.

**Comment by ambition-consulting** [comment] 2021-06-11 15:55
After providing the above mentioned code as a provider, I get

```
17:53:41.533 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.el.se.ru.ElytronRecorder] (Quarkus Main Thread) buildDomain, realm=org.wildfly.security.auth.realm.SimpleMapBackedSecurityRealm@3cea2508
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
17:53:41.551 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.mi.ru.MicrometerRecorder] (Quarkus Main Thread) Discovered global MeterFilters : [io.micrometer.core.instrument.config.MeterFilter$9@46c9fa2d, io.micrometer.core.instrument.config.MeterFilter$9@480e1c84, io.micrometer.core.instrument.config.MeterFilter$9@4c31915d, io.micrometer.core.instrument.config.MeterFilter$9@93316bf]
17:53:41.552 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.mi.ru.MicrometerRecorder] (Quarkus Main Thread) Configuring Micrometer registries : [class io.micrometer.prometheus.PrometheusMeterRegistry]
17:53:41.552 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.mi.ru.MicrometerRecorder] (Quarkus Main Thread) Discovered MeterFilters for class io.micrometer.prometheus.PrometheusMeterRegistry: []
17:53:41.554 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.mi.ru.MicrometerRecorder] (Quarkus Main Thread) Adding configured registry class io.micrometer.prometheus.PrometheusMeterRegistry
17:53:41.603 DEBUG traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.ar.impl] (Quarkus Main Thread) ArC DI container shut down
17:53:41.603 ERROR traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.ru.Application] (Quarkus Main Thread) Failed to start application (with profile dev): java.lang.IllegalAccessError: class com.fiserv.apm.core.app.provider.CoreForkJoinPool_Bean tried to access method 'void com.fiserv.apm.tech.thread.CustomForkJoinPool.stop()' (com.fiserv.apm.core.app.provider.CoreForkJoinPool_Bean and com.fiserv.apm.tech.thread.CustomForkJoinPool are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @181d4b5f)
	at com.fiserv.apm.core.app.provider.CoreForkJoinPool_Bean.destroy(CoreForkJoinPool_Bean.zig:163)
	at com.fiserv.apm.core.app.provider.CoreForkJoinPool_Bean.destroy(CoreForkJoinPool_Bean.zig:184)
	at com.fiserv.apm.tech.thread.CustomForkJoinPool_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.notify(CustomForkJoinPool_Observer_onStart_fd71b5e0b207b7d1ef838b94eaeff75e52b8f463.zig:118)
	at io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:283)
	at io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:268)
	at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
	at io.quarkus.arc.runtime.ArcRecorder.fireLifecycleEvent(ArcRecorder.java:128)
	at io.quarkus.arc.runtime.ArcRecorder.handleLifecycleEvents(ArcRecorder.java:97)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy_0(LifecycleEventsBuildStep$startupEvent1144526294.zig:87)
	at io.quarkus.deployment.steps.LifecycleEventsBuildStep$startupEvent1144526294.deploy(LifecycleEventsBuildStep$startupEvent1144526294.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1016)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
	at java.base/java.lang.Thread.run(Thread.java:834)

17:53:41.603 ERROR traceId=, parentId=, spanId=, sampled=, uuid= [io.qu.de.de.IsolatedDevModeMain] (vert.x-worker-thread-1) Failed to start quarkus: java.lang.RuntimeException: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.dev.appstate.ApplicationStateNotification.waitForApplicationStart(ApplicationStateNotification.java:51)
	at io.quarkus.runner.bootstrap.StartupActionImpl.runMainClass(StartupActionImpl.java:145)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartApp(IsolatedDevModeMain.java:191)
	at io.quarkus.deployment.dev.IsolatedDevModeMain.restartCallback(IsolatedDevModeMain.java:175)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:254)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:64)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$2.handle(VertxHttpHotReplacementSetup.java:54)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:1082)
	at io.quarkus.runtime.Application.start(Application.java:90)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:100)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.runner.bootstrap.StartupActionImpl$3.run(StartupActionImpl.java:134)
```

**Comment by stuartwdouglas** [comment] 2021-06-15 03:46
Can you share your code? This look different to the original issue.

**Comment by geoand** [comment] 2024-09-13 11:03
Is this still an issue?

**Comment by ambition-consulting** [comment] 2024-09-13 11:17
I am not working with Quarkus anymore - new project, back to Spring, unfortunately.

**Comment by geoand** [comment] 2024-09-13 11:19
Gotcha, thanks for the update :)

**Closed** 2024-09-13 11:19 UTC
Labels: kind/bug, triage/needs-feedback
