### ISSUE TITLE
quarkus-config-yaml extension breaks location precedence

### ISSUE THREAD

**Issue by davidmoshal** [quarkusio/quarkus#14172] opened 2021-01-07 21:11 UTC
Quarkus Version: 1.10.5.Final

**Describe the bug**
quarkus-config-yaml extension breaks config location precedence

**Expected behavior**

Given:

Two config files:
- ./src/resources/application.properties
- ./config/application.properties

Then:

a property in the config/applications.properties file should have higher precedence than the same property in src/resources/applications.properties

**Actual behavior**

When quarkus-config-yaml is added to build.gradle then Quarkus config ignores files under config/.
Both config/application.properties and config/application.yml are ignored.

**To Reproduce**
- Create any Quarkus gradle project.  
- add the same property to src/resources/application.properties and config/application.properties.
- confirm that without io.quarkus:quarkus-config-yaml the precedence is correct.
- add extension: io.quarkus:quarkus-config-yaml
- files under config are ignored.
- remove extension: io.quarkus:quarkus-config-yaml
- precedence works

**Configuration**
See above

**Comment by geoand** [comment] 2021-01-08 06:33
I could not reproduce this problem.

I generated an application with `quarkus-config-yaml` from https://code.quarkus.io/ then copied  `application.yaml` to `config/application.yaml` and changed the values.
When I built the application and then ran it with `java -jar ...` then http://localhost:8080/config/supersonic returned the configuration from `config/application.yaml`

**Comment by davidmoshal** [comment] 2021-01-09 23:59
That's odd, easily reproducible for me, not sure what else I can add?

**Comment by gsmet** [comment] 2021-01-10 19:38
@davidmoshal please share a small reproducer.

**Comment by zellerr** [comment] 2021-02-05 14:29
Hi, I just wanted to create an issue for this behaviour and found that it is already reported.

**Reproducer:**

1. Create new project for Maven archetype "config-quickstart"
2. Include extension dependency "quarkus-config-yaml"
2. Add new class `GreetingConfig` as a holder for the configuration properties
3. Inject the `GreetingConfig` in the `GreetingResource` and return the property value in the example endpoint
4. Add "application.yaml" to /src/main/resources and set property to "Hello World"
5. Create new folder "config" folder at the location where you run the application 
6. Add "application.yaml" to the config folder and set property to "Hello Universe"
7. Run (In my case I ran the native image and did not try the JVM mode)
  
```
@ConfigProperties(prefix = "greeting")
public class GreetingConfig {

    private String message;

    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }
}

@Path("/greeting")
public class GreetingResource {

    @Inject
    GreetingConfig greetingConfig;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return greetingConfig.getMessage();
    }
}
```
application.yaml
``` 
greeting:
  message: Hello World
``` 

**Expected behavoir:**
Endpoint returns "Hello Universe" from /config/application.yaml

**Actual behaviour:**
Endpoint still return "Hello World" from /src/main/application.yaml

**Assumption:**
I believe that this has something to do with the `@ConfigProperties` annotation. When you remove that annotation, make the config class `@RequestScoped` and provide the property by ` @ConfigProperty(name = "greeting.message")` it works.

I hope that helps you @gsmet

**Comment by geoand** [comment] 2021-02-05 16:39
I tried again and I still could not reproduce the issue following the steps you mentioned...

**Comment by zellerr** [comment] 2021-02-12 13:34
@geoand Thanks for trying the reproducer. Honestly, I myself cannot reproduce it anymore. This drives me crazy as I was so sure that we had this behaviour in one of our microservices. Either it was fixed by magic or it was the kinda bug that you discover on Friday afternoon after a long exhausting week.... 
Sorry, your time was wasted here so far. I'll post an update when this can (really) be reproduced.

**Comment by geoand** [comment] 2021-02-12 13:35
No problem at all!

Thanks

**Comment by geoand** [comment] 2021-02-17 14:22
I'm going to close this at it doesn't seem reproducible.

If however you are able to reproduce it, feel free to comment and / or reopen

**Closed by geoand** 2021-02-17 14:22 UTC
Labels: kind/bug, triage/needs-triage
