### ISSUE TITLE
IllegalStateException, reactive jaxrs - Don't block when returning void

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#22431] opened 2021-12-21 07:46 UTC
### Describe the bug

Similar case as https://github.com/quarkusio/quarkus/issues/22251 but for cases when void is returned.

Works fine with Quarkus 2.5.4.Final, Fails on Quarkus main

```
2021-12-21 08:36:35,548 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-22) HTTP Request to /value failed, error id: 611ecf39-7ad2-487c-9410-d942dc50f760-1: java.lang.IllegalStateException: The current thread cannot be blocked: vert.x-eventloop-thread-22
	at io.smallrye.mutiny.operators.uni.UniBlockingAwait.await(UniBlockingAwait.java:30)
	at io.smallrye.mutiny.groups.UniAwait.atMost(UniAwait.java:62)
	at io.smallrye.mutiny.groups.UniAwait.indefinitely(UniAwait.java:43)
	at io.quarkus.cache.runtime.CacheInvalidateInterceptor.intercept(CacheInvalidateInterceptor.java:39)
	at io.quarkus.cache.runtime.CacheInvalidateInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.ReactiveResource_Subclass.getValue(Unknown Source)
	at org.acme.ReactiveResource$quarkusrestinvoker$getValue_383be323698d81f3c8faf6d402c8e221fd043820.invoke(Unknown Source)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
	at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:7)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:141)
	at org.jboss.resteasy.reactive.server.handlers.RestInitialHandler.beginProcessing(RestInitialHandler.java:49)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:17)
	at org.jboss.resteasy.reactive.server.vertx.ResteasyReactiveVertxHandler.handle(ResteasyReactiveVertxHandler.java:7)
	at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1193)
...
```

### Expected behavior

Pass the test / return HTTP 204 aka NO_CONTENT

### Actual behavior

Test fails with IllegalStateException, log says `The current thread cannot be blocked: vert.x-eventloop-thread-22`

### How to Reproduce?

use reproducer from https://github.com/quarkusio/quarkus/issues/22251 with these adjustments:

```java
@NonBlocking
@Path("/value")
public class ReactiveResource {
    public static final String CACHE_NAME = "mycache";
    @GET
    @CacheInvalidate(cacheName = CACHE_NAME)
    public void getValue() {
    }
}
```

Change `.statusCode(HttpStatus.SC_OK)` to `.statusCode(HttpStatus.SC_NO_CONTENT)` in ReactiveResourceTest

Alternative way:
 - Use https://github.com/rsvoboda/quarkus-test-suite/tree/revert.50d90aa
 - run `mvn clean verify -pl cache/caffeine`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

main

**Comment by rsvoboda** [comment] 2021-12-21 07:48
@stuartwdouglas can you take a look, similar to the Uni case you fixed.

**Comment by geoand** [comment] 2021-12-21 10:10
Hm... Although superficially this looks similar to https://github.com/quarkusio/quarkus/issues/22251, it can't be fixed in the same way.

@gwenneg can you please reiterate the reasoning why the operations where changed to `Uni` as part of https://github.com/quarkusio/quarkus/pull/8631?

**Comment by gwenneg** [comment] 2021-12-21 10:31
Well, the idea was to offer a reactive programmatic API so returning `Uni` in [Cache](https://github.com/quarkusio/quarkus/blob/main/extensions/cache/runtime/src/main/java/io/quarkus/cache/Cache.java) operations seemed like a good choice.

This issue is caused by the `await().indefinitely()` in [CacheInvalidateInterceptor](https://github.com/quarkusio/quarkus/blob/3cc2737746164565e6c0f0bef7ac3bc8110157d2/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInvalidateInterceptor.java#L39), right?

**Comment by geoand** [comment] 2021-12-21 10:34
> This issue is caused by the `await().indefinitely()` in [CacheInvalidateInterceptor](https://github.com/quarkusio/quarkus/blob/3cc2737746164565e6c0f0bef7ac3bc8110157d2/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheInvalidateInterceptor.java#L39), right?

Yes, as `await` cannot be called on Vertx threads

**Comment by gwenneg** [comment] 2021-12-21 10:36
So the other interceptors have the same issue.

What is the usual way of dealing with `Uni` calls from inside an interceptor executed on a Vertx thread when the interceptor needs the `Uni` to be complete before returning?

**Comment by gwenneg** [comment] 2021-12-21 10:38
The interceptor could skip the transformation from `CompletionStage` to `Uni` that happens in `CaffeineCacheImpl`, but that wouldn't make the interception less blocking since we would still wait for the `CompletionStage` to be done.

**Comment by geoand** [comment] 2021-12-21 10:41
> What is the usual way of dealing with `Uni` calls from inside an interceptor executed on a Vertx thread when the interceptor needs the `Uni` to be complete before returning?

I don't think we had that issue before.

Regarding the cache module specifically, I see that before  #8631, `invalidate` did not return a `Uni`, it just returned `void`

**Comment by gwenneg** [comment] 2021-12-21 10:43
Yes `invalidate` can be fixed. Same goes from `invalidate all`.

But I wonder how [CacheResultInterceptor](https://github.com/quarkusio/quarkus/blob/3cc2737746164565e6c0f0bef7ac3bc8110157d2/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java#L96) can be fixed. It was [already blocking](https://github.com/quarkusio/quarkus/blob/76624276bc44b4f6856a0308d9caa8b9ee8ac644/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/CacheResultInterceptor.java#L66) before #8631.

**Comment by geoand** [comment] 2021-12-21 10:45
`CacheResultInterceptor` was fixed in https://github.com/quarkusio/quarkus/issues/22251

**Comment by gwenneg** [comment] 2021-12-21 10:46
Fixed when `Uni` is returned, but can't the issue happen with other returned types?

**Comment by gwenneg** [comment] 2021-12-21 10:48
The reason why `invalidate` and `invalidate all` were changed from `void` to `Uni<Void>` was to allow these calls to become remote in case we wanted to add another caching provider that wouldn't be local in the future (which may never happen).

**Comment by gwenneg** [comment] 2021-12-21 10:51
> Fixed when `Uni` is returned, but can't the issue happen with other returned types?

Can the following code exist?

```
@NonBlocking
@Path("/value")
public class ReactiveResource {
    public static final String CACHE_NAME = "mycache";
    @GET
    @CacheResult(cacheName = CACHE_NAME)
    public int getValue() {
        return 1;
    }
}
```

**Comment by geoand** [comment] 2021-12-21 10:52
> Fixed when `Uni` is returned, but can't the issue happen with other returned types?

Yes, the same issue as described here can happen

**Comment by gwenneg** [comment] 2021-12-21 13:02
[This approach](https://github.com/gwenneg/quarkus/pull/198) could be a way to fix the `invalidate` and `invalidate all` issues.

The other option would be to change the returned type from `Uni<Void>` to `void` in [Cache](https://github.com/quarkusio/quarkus/blob/main/extensions/cache/runtime/src/main/java/io/quarkus/cache/Cache.java) but that would imply that remote invalidation would no longer be an option (which may be fine), a deprecation period for old methods and new methods with a different name because only changing the returned type would not make the old names available.

**Comment by geoand** [comment] 2021-12-21 13:04
I think we can live with it

**Comment by gwenneg** [comment] 2021-12-21 13:05
Regarding the `@CacheResult` issue, I wonder if it should [make the annotated method blocking](https://quarkus.io/blog/resteasy-reactive-smart-dispatch/#new-world-new-rules) using annotations transformation at build time (add `@Blocking`, remove `@NonBlocking` if present, maybe with a warning) when the returned type is not `Uni`.

**Comment by gwenneg** [comment] 2021-12-21 13:05
> I think we can live with it

or that :)

**Comment by geoand** [comment] 2021-12-21 13:08
I propose sending an email to `quarkus-dev` to get opinions on this

**Comment by gwenneg** [comment] 2021-12-21 13:33
> I propose sending an email to `quarkus-dev` to get opinions on this

Done 😃

**Comment by rsvoboda** [comment] 2022-01-04 14:47
@gwenneg / @geoand is there any conclusion from quarkus-dev mailing list or waiting for more inputs?

**Comment by gwenneg** [comment] 2022-01-04 22:30
Sorry, I forgot to answer in the mailing list 😄

I started working on @stuartwdouglas' suggestion today, I'll have something ready shortly.

**Closed** 2022-01-12 13:15 UTC
Labels: kind/bug, area/cache, area/resteasy-reactive
