### ISSUE TITLE
Trying to test Kafka with smallrye-reactive-messaging in-memory channels and database transaction

### ISSUE THREAD

**Issue by QuentinCazelles** [quarkusio/quarkus#16945] opened 2021-05-03 09:15 UTC
## Describe the bug
QuarkusTest are not working with smallrye-reactive-messaging-in-memory and database transaction (@Blocking) 

```java
@QuarkusTest
@QuarkusTestResource(KafkaResource.class)
public class StreamTest {

    // Inject in-memory connector to use for tests instead of Kafka
    @Inject
    @Any
    InMemoryConnector connector;

    // Use a in-memory source instead of writing in Kafka topic
    private InMemorySource<ObjectIn> streamIn;
    // Use a in in-memory sink instead of reading in Kafka topic
    private InMemorySink<ObjectOut> streamOut;

    @BeforeEach
    public void initEach() {
        // Retrieves the in-memory source to send message
        streamIn = connector.source("channel-in");
        // Retrieves the in-memory sink to check what is received
        streamOut = connector.sink("channel-out");
    }

    @Test
    @TestTransaction
    public void test1() {
        ObjectIn objectIn = new ObjectIn();
        objectIn.setForeignKey("key");

        streamIn.send(objectIn);

        Assertions.assertEquals(1, streamOut.received().size());
        Assertions.assertEquals("key", streamOut.received().get(0).getPayload().getId());
    }
```

```java
@ApplicationScoped
public class StreamHandler {

    @Inject
    ObjectOutDAO objectOutDAO;

    @Inject
    @Channel("channel-out")
    Emitter<ObjectOut> toOtherService;

    @Incoming("channel-in")
    @Blocking
    @ActivateRequestContext
    public void handleStream(ObjectIn objectIn) {
        try {
            ObjectOut out = objectOutDAO.findById(objectIn.getForeignKey());
            toOtherService.send(out);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
```

### Expected behavior
Test should be passing

### Actual behavior
Access to database object through EntityManager in DAO raises an java.lang.IllegalStateException: EntityManagerFactory is closed.
`
java.lang.IllegalStateException: EntityManagerFactory is closed
        at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:530)
        at org.hibernate.internal.SessionFactoryImpl.getCache(SessionFactoryImpl.java:828)
        at org.hibernate.internal.AbstractSharedSessionContract.<init>(AbstractSharedSessionContract.java:159)
        at org.hibernate.internal.AbstractSessionImpl.<init>(AbstractSessionImpl.java:29)
        at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:221)
        at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1282)
        at io.quarkus.hibernate.orm.runtime.session.JTASessionOpener.openSession(JTASessionOpener.java:48)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.acquireSession(TransactionScopedSession.java:87)
        at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.find(TransactionScopedSession.java:168)
        at io.quarkus.hibernate.orm.runtime.session.ForwardingSession.find(ForwardingSession.java:68)
        at test.dao.ObjectOutDAO.findById(ObjectOutDAO.java:21)
        at test.dao.ObjectOutDAO_Subclass.findById$$superaccessor1(ObjectOutDAO_Subclass.zig:211)
        at test.dao.ObjectOutDAO_Subclass$$function$$1.apply(ObjectOutDAO_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:127)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at test.dao.ObjectOutDAO_Subclass.findById(ObjectOutDAO_Subclass.zig:168)
        at test.dao.ObjectOutDAO_ClientProxy.findById(ObjectOutDAO_ClientProxy.zig:151)
        at test.stream.StreamHandler.handleStream(StreamHandler.java:31)
        at test.stream.StreamHandler_Subclass.handleStream$$superaccessor1(StreamHandler_Subclass.zig:199)
        at test.stream.StreamHandler_Subclass$$function$$1.apply(StreamHandler_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:24)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(ActivateRequestContextInterceptor_Bean.zig:275)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at test.stream.StreamHandler_Subclass.handleStream(StreamHandler_Subclass.zig:156)
        at test.stream.StreamHandler_ClientProxy.handleStream(StreamHandler_ClientProxy.zig:176)
        at test.stream.StreamHandler_SmallRyeMessagingInvoker_handleStream_a6c9e6da126eb9169db6ba4e2ef689ec88d5f14a.invoke(StreamHandler_SmallRyeMessagingInvoker_handleStream_a6c9e6da126eb9169db6ba4e2ef689ec88d5f14a.zig:48)
        at io.smallrye.reactive.messaging.AbstractMediator.lambda$invokeBlocking$2(AbstractMediator.java:107)
        at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:572)
        at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:570)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
java.lang.IllegalArgumentException
        at io.quarkus.arc.impl.ArcContainerImpl.unwrap(ArcContainerImpl.java:757)
        at io.quarkus.arc.impl.EventImpl.createNotifier(EventImpl.java:139)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705)
        at io.quarkus.arc.impl.EventImpl.getNotifier(EventImpl.java:113)
        at io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:70)
        at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:93)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:313)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:164)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:100)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:53)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:26)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(TransactionalInterceptorRequired_Bean.zig:340)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at test.dao.ObjectOutDAO_Subclass.findById(ObjectOutDAO_Subclass.zig:168)
        at test.dao.ObjectOutDAO_ClientProxy.findById(ObjectOutDAO_ClientProxy.zig:151)
        at test.stream.StreamHandler.handleStream(StreamHandler.java:31)
        at test.stream.StreamHandler_Subclass.handleStream$$superaccessor1(StreamHandler_Subclass.zig:199)
        at test.stream.StreamHandler_Subclass$$function$$1.apply(StreamHandler_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor.aroundInvoke(ActivateRequestContextInterceptor.java:24)
        at io.quarkus.arc.impl.ActivateRequestContextInterceptor_Bean.intercept(ActivateRequestContextInterceptor_Bean.zig:275)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at test.stream.StreamHandler_Subclass.handleStream(StreamHandler_Subclass.zig:156)
        at test.stream.StreamHandler_ClientProxy.handleStream(StreamHandler_ClientProxy.zig:176)
        at test.stream.StreamHandler_SmallRyeMessagingInvoker_handleStream_a6c9e6da126eb9169db6ba4e2ef689ec88d5f14a.invoke(StreamHandler_SmallRyeMessagingInvoker_handleStream_a6c9e6da126eb9169db6ba4e2ef689ec88d5f14a.zig:48)
        at io.smallrye.reactive.messaging.AbstractMediator.lambda$invokeBlocking$2(AbstractMediator.java:107)
        at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:572)
        at io.vertx.mutiny.core.Vertx$2.handle(Vertx.java:570)
        at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:313)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:829)
2021-05-03 09:12:28,512 INFO  [io.quarkus] (main) Quarkus stopped in 0.045s
`

## To Reproduce

Minimal reproducer project :

[testKafkaDbTx.zip](https://github.com/quarkusio/quarkus/files/6413327/testKafkaDbTx.zip)

1. ./mvnw test

### Configuration
```properties
%test.quarkus.hibernate-orm.sql-load-script=import-test.sql
%test.quarkus.hibernate-orm.database.generation=drop-and-create
%test.quarkus.datasource.db-kind=postgresql
%test.quarkus.hibernate-orm.log.sql=true

%test.mp.messaging.outgoing.channel-out.connector=smallrye-in-memory
%test.mp.messaging.incoming.channel-in.connector=smallrye-in-memory

%test.mp.messaging.incoming.channel-in.topic=topic-in
%test.mp.messaging.outgoing.channel-out.topic=topic-out

```

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev
1.13.3.Final

### Build tool
 ./mvnw -v
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/qcazelles/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-051100-generic", arch: "amd64", family: "unix"

## Additional context
Removing @Blocking makes the test pass but breaks the app when running normally

**Comment by cescoffier** [comment] 2021-05-03 09:22
Instead of `@ActivateRequestScope`, did you try with `@Transactional`?
Things happen asynchronously, so the request-scoped may be closed before you process everything.

By removing the @Blocking, you get the right transaction, but then you execute a blocking call on the I/O thread, I suppose? Am I right?

**Comment by QuentinCazelles** [comment] 2021-05-03 09:36
Removing @ActivateRequestContext and adding @Transactionnal does not seem to change anything, I get the same java.lang.IllegalStateException: EntityManagerFactory is closed

You are exactly right, a blocking call on the I/O thread is executed and raise an exception.

I could make a minimal project with docker run commands for kafka to show a more real-world usage.

**Comment by cescoffier** [comment] 2021-05-03 09:48
Yes, having a reproducer would help!

**Comment by QuentinCazelles** [comment] 2021-05-03 10:57
Hereis  the new project

[testKafkaDbTx-withDockerKafka.zip](https://github.com/quarkusio/quarkus/files/6414403/testKafkaDbTx-withDockerKafka.zip)

I wrote everything in the applications.properties :

```properties
%dev.quarkus.hibernate-orm.sql-load-script=import-test.sql
%dev.quarkus.hibernate-orm.database.generation=drop-and-create
%dev.quarkus.datasource.db-kind=postgresql

%dev.mp.messaging.outgoing.channel-out.connector=smallrye-kafka
%dev.mp.messaging.incoming.channel-in.connector=smallrye-kafka

%dev.mp.messaging.incoming.channel-in.topic=topic-in
%dev.mp.messaging.outgoing.channel-out.topic=topic-out

%dev.mp.messaging.incoming.channel-in.value.deserializer=test.deserializer.ObjectInDeserializer
%dev.mp.messaging.outgoing.channel-out.value.serializer=io.quarkus.kafka.client.serialization.JsonbSerializer
```

The docker run commands :

```shell
docker network create quarkus-test
docker run --rm -d --name zookeeper-local --network quarkus-test -p 2181:2181 wurstmeister/zookeeper
docker run --rm -d --name kafka-local --network quarkus-test -p 9092:9092 -e KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092 -e KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092 -e KAFKA_ZOOKEEPER_CONNECT=zookeeper-local:2181 wurstmeister/kafka:2.13-2.6.0

```

Then you can go inside Kafka container

`docker exec -it kafka-local bash`

Run manual producer :

```shell
cd /opt/kafka/bin
./kafka-console-producer.sh --bootstrap-server localhost:9092 --topic topic-in
```

Produce a simple message :

```json
{"foreignKey":"key"}
```

Works with @Blocking, it does not without and results in :

```
java.lang.IllegalStateException: You have attempted to perform a blocking operation on a IO thread. This is not allowed, as blocking the IO thread will cause major performance issues with your application. If you want to perform blocking EntityManager operations make sure you are doing it from a worker thread.
```

You can inspect the consumer side with :
`./kafka-console-consumer.sh --bootstrap-server localhost:9092 --topic topic-out --from-beginning`

Where you are supposed the receive the message :

```json
{"id":"key"}
```

Thank you

**Comment by cescoffier** [comment] 2021-05-03 12:12
You need `@Blocking` because you want to execute a blocking operation (`ObjectOut out = objectOutDAO.findById(objectIn.getForeignKey());`. So the reported error is expected.

Note that you can use Hibernate Reactive to avoid the blocking API.

So, for me, your reproducer is correct, and you need `@Blocking`.

**Comment by cescoffier** [comment] 2021-06-07 05:51
Closing - the reproducer works as expected. 
Please re-open if there is still an issue.

**Closed by cescoffier** 2021-06-07 05:51 UTC
Labels: area/kafka, area/reactive-messaging, area/smallrye, kind/bug
