### ISSUE TITLE
JAX-RS Resource with multiple MediaTypes fails

### ISSUE THREAD

**Issue by holomekc** [quarkusio/quarkus#15042] opened 2021-02-12 15:47 UTC
**Describe the bug**
When we annotate a JAX-RS Resource with ```@Produces({"application/json", "application/hal+json"})```
It is not possible to access the resource with Header ```Accept: application/hal+json```.

**Expected behavior**
Server answers request with header ```Accept: application/hal+json``` with custom MessageBodyWriter

**Actual behavior**
Server answers request with HTTP 406

**Reason**
I did some debugging and could find the following:
First Quarkus removes hal+ from application/hal+json and stores information in storedMediaTypes:
https://github.com/quarkusio/quarkus/blob/8dc02652c058eeb92b0998293209509f2adb49ca/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/ServerMediaType.java#L91-L94

Then Quarkus checks differently in case multiple media types are annotated and then 
picks data from sortedMediaTypes instead of sortedOriginalMediaTypes which is used when only one media type is annotated. https://github.com/quarkusio/quarkus/blob/8dc02652c058eeb92b0998293209509f2adb49ca/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ClassRoutingHandler.java#L121-L143

**To Reproduce**
https://github.com/holomekc/multiple-mediatype-reproducer

working endpoint:
uses media types: application/json and application/hal
=> HTTP 200

/failing endpoint:
uses media types: application/json and application/hal+json
=> HTTP 406

1. execute HTTP GET: http://localhost:8080/working
2. execute HTTP GET: http://localhost:8080/failing

**Configuration**
No configuration necessary

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin xxxx 19.6.0 Darwin Kernel Version 19.6.0: Tue Nov 10 00:10:30 PST 2020; root:xnu-6153.141.10~1/RELEASE_X86_64 x86_64
 - Output of `java -version`: OpenJDK Runtime Environment Corretto-11.0.10.9.1 (build 11.0.10+9-LTS)
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3

**Comment by markusdlugi** [comment] 2021-02-15 08:10
Might want to add that this only seems to affect RESTEasy Reactive, it is working in classic RESTEasy. So you might want to add the area/resteasy-reactive label.

/cc @FroMage, @geoand, @stuartwdouglas

**Comment by geoand** [comment] 2021-02-16 12:00
Thanks for reporting.

I must be failing to see something here because when I tried your example, both endpoints `application/octet-stream`

**Comment by markusdlugi** [comment] 2021-02-16 13:39
Hi @geoand,

thanks for having a look.

I think @holomekc missed some information about the reproducer - you need to add a specific "Accept" header to your request to observe the behavior. Both /working and /failing have two media types, with /working producing "application/json" and "application/hal" while /failing produces "application/json" and "application/hal+json". The behavior is as follows:

- /working with "Accept: application/json" - 200 OK
- /working with "Accept: application/hal" - 200 OK
- /failing with "Accept: application/json" - 200 OK
- /failing with "Accept: application/hal+json" - 406 Not Acceptable

Here is a Postman collection with those 4 requests:

```
{
	"info": {
		"_postman_id": "7b173443-808f-4142-ba9d-141c08542744",
		"name": "Multiple Mediatype Reproducer",
		"schema": "https://schema.getpostman.com/json/collection/v2.1.0/collection.json"
	},
	"item": [
		{
			"name": "/working - Accept: json - OK",
			"request": {
				"method": "GET",
				"header": [
					{
						"key": "Accept",
						"value": "application/json",
						"type": "text"
					}
				],
				"url": {
					"raw": "http://localhost:8080/working",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"working"
					]
				}
			},
			"response": []
		},
		{
			"name": "/working - Accept: hal  - OK",
			"request": {
				"method": "GET",
				"header": [
					{
						"key": "Accept",
						"value": "application/hal",
						"type": "text"
					}
				],
				"url": {
					"raw": "http://localhost:8080/working",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"working"
					]
				}
			},
			"response": []
		},
		{
			"name": "/failing - Accept: json - OK",
			"request": {
				"method": "GET",
				"header": [
					{
						"key": "Accept",
						"value": "application/json",
						"type": "text"
					}
				],
				"url": {
					"raw": "http://localhost:8080/failing",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"failing"
					]
				}
			},
			"response": []
		},
		{
			"name": "/failing - Accept: hal+json - NOT OK",
			"request": {
				"method": "GET",
				"header": [
					{
						"key": "Accept",
						"value": "application/hal+json",
						"type": "text"
					}
				],
				"url": {
					"raw": "http://localhost:8080/failing",
					"protocol": "http",
					"host": [
						"localhost"
					],
					"port": "8080",
					"path": [
						"failing"
					]
				}
			},
			"response": []
		}
	]
}
```

As detailed above, the last request fails because RESTEasy Reactive removes the "+json" from the "hal+json" media type and then can't find it afterwards when handling the request. But for some reason, this only happens when you have multiple media types produced by your resource.

**Comment by geoand** [comment] 2021-02-17 07:48
Understood thanks.

@FroMage @stuartwdouglas do you guys remember if is there somewhere in the spec that mentions how to handle these sorts of media types?

**Comment by FroMage** [comment] 2021-02-17 10:44
Wow, that's quite a question.

JAX-RS mentions suffixes by accident several times, but not what to do with them. It does however point out that XML serialisers should be registered with `application/xml` and `application/*+xml`, pointing out that there is some partial matching in the subtype, and that it's not automatic: we can't assume that `application/foo+xml` matches `application/xml`.

https://tools.ietf.org/html/rfc6838#section-4.2.8 says they're names, to identify conformance to a format. So `hal+json` is really `hal` and the rest is informative.

HTTP matching doesn't even mention them: https://tools.ietf.org/html/rfc7231#section-5.3.2

If it really is just informative, I guess that an accept of `application/foo` should match both `application/foo+xml` and `application/foo` producers, but not `application/xml` producers. But that's conjecture: I can't find relevant standard information.

**Comment by geoand** [comment] 2021-02-17 10:46
Thanks a lot @FroMage

**Comment by holomekc** [comment] 2021-02-18 11:01
Hi. Thank you for checking it that fast! I agree to what @FroMage mentioned ```application/hal+json``` and ```application/hal``` should both match.

What I still do not get is the different treatment in the linked ```ClassRoutingHandler```. Why is ```sortedOriginalMediaTypes``` used in case of one MediaType and why is it ```sortedMediaTypes``` in case more MediaTypes are used?

**Comment by gsmet** [comment] 2021-03-02 22:52
@geoand anything we can do on this one?

**Comment by geoand** [comment] 2021-03-03 06:18
This needs more thought

**Comment by markusdlugi** [comment] 2021-03-03 12:01
@geoand, I dug a little bit in the commit history and to me it seems like the discrepancy in behavior of single media type vs multiple media types is due to the following commit to fix #14023:

https://github.com/quarkusio/quarkus/commit/7eb7ba7062e95f0403181cdedc6cfbb95d760d4f#diff-2b16b904363609f2eceb08fd7684a0dfce940128f0752e384c52fbb114df729bR123

Here you changed `sortedMediaTypes` to `sortedOriginalMediaTypes`. But this change was only done for the case where a single media type is produced (if block line 121), but not for the case where multiple media types are produced (else block). So in my opinion, the same change should be applied to `ClassRoutingHandler` line 140, which is still using just `sortedMediaTypes`:

https://github.com/quarkusio/quarkus/blob/172446c920decdf3fc32f03613a486fa63b20c35/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ClassRoutingHandler.java#L140-L143

This would be the easiest fix and then the behavior should at least be consistent for both cases. But I'm not sure which other potential side effects such a change could have.

**Comment by geoand** [comment] 2021-03-03 15:52
Hey @markusdlugi 

Thanks for looking into it.
Have you tried making that fix and letting CI run on your fork to see if everything will pass?

**Comment by markusdlugi** [comment] 2021-03-08 15:42
Hi @geoand,

we tested that fix locally and it seems like it does indeed remove the problem that HTTP 406 Not Acceptable is thrown due to multiple media types being present. However, it does not fix the problem that the wrong MessageBodyWriter is selected - the endpoint that initially failed with HTTP 406 now returns `application/json` instead of `application/hal+json`.

We debugged a little and it seems like this is the place where it switched from `application/hal+json` to `application/json` (at least one of the places):

https://github.com/quarkusio/quarkus/blob/0ec090dca944070dbafc03cf48b70113a7055234/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/core/startup/RuntimeResourceDeployment.java#L306-L311

Here the code is looking for the writers for a given media type, but it does so after throwing away everything _in front of_ the +. Therefore it ultimately chooses `application/json` instead of `application/hal+json`. See this code:

https://github.com/quarkusio/quarkus/blob/0ec090dca944070dbafc03cf48b70113a7055234/independent-projects/resteasy-reactive/common/runtime/src/main/java/org/jboss/resteasy/reactive/common/util/MediaTypeHelper.java#L259-L267

So this would seem like it is exactly the wrong approach when taking @FroMage 's investigations into account. I would expect the code to

1. First try `application/hal+json` and look for a suitable writer for that media type.
2. If it can't find any, try `application/hal` and look for a writer for that type.
3. If it can't find either, it should _not_ look for `application/json` but instead throw HTTP 406.

But that's just what I gathered from @FroMage 's comment. And I don't know if that's the only part of the code which would have to be adjusted to achieve this behavior.

I also tried to run CI on a fork of mine, but for some reason it always skipped all the steps, so can't really tell if that initial change in the `ClassRoutingHandler` is valid or not. But seems like that won't be the only change that needs to be done either.

**Comment by geoand** [comment] 2021-03-09 07:23
> I also tried to run CI on a fork of mine, but for some reason it always skipped all the steps, so can't really tell if that initial change in the `ClassRoutingHandler` is valid or not. But seems like that won't be the only change that needs to be done either.

You can open a Pull Request in draft state and that should run on your fork - that way you can get a proper CI run and see if the fixes you have in mind are valid

**Comment by markusdlugi** [comment] 2021-03-09 11:39
Opened the draft PR as suggested. You can see CI passes with that change, so that one should be fine.

But as mentioned above, while that fixes the issue of HTTP 406 being thrown, more work will be needed to ensure that RESTEasy Reactive actually handles compound media types such as hal+json properly.

**Comment by markusdlugi** [comment] 2021-03-23 08:04
Hi @gsmet, how should we proceed with this one? As stated above, the original error (HTTP 406) that was only present with multiple media types is fixed. However the media types are not handled as one would expect (e.g. a header of `Accept: application/hal+json` uses the `MessageBodyWriter` for `json` instead of `hal+json` (or `hal`, as suggested by @FroMage). Should we close this issue and open a new one for the handling of compound media types (with a +) as enhancement? Or change this one to an enhancement? Or keep the bug label? Not sure :)

**Comment by gsmet** [comment] 2021-03-23 08:24
It's probably better to open another issue with a full description of what we want to achieve. I will close this one.

**Closed by gsmet** 2021-03-23 08:24 UTC
Labels: area/resteasy-reactive, kind/bug
