### ISSUE TITLE
java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory when injecting same configuration parameter in multiple test classes

### ISSUE THREAD

**Issue by jargelo** [quarkusio/quarkus#8210] opened 2020-03-27 08:23 UTC
**Describe the bug**
When injecting a config property annotated with `@Configproperty(name = 'myproperty')` and `@Inject` in two separate Test classes, it will run the test fine on the first class, but on the second class it will throw the following exception:

```
<output of testclass1 truncated>
[INFO] Tests run: 10, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.418 s - in dev.testclass1.ObjectsAzureImplTest
[INFO] Running dev.testclass2.RepositoriesAzureImplTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.001 s <<< FAILURE! - in dev.testclass2.RepositoriesAzureImplTest
[ERROR] dev.testclass2.RepositoriesAzureImplTest  Time elapsed: 0.001 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: Failed to create test instance
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype

2020-03-27 09:07:01,704 INFO  [io.quarkus] (main) Quarkus stopped in 0.033s
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Errors: 
[ERROR]   RepositoriesAzureImplTest » TestInstantiation Failed to create test instance
[INFO] 
[ERROR] Tests run: 11, Failures: 0, Errors: 1, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  13.404 s
[INFO] Finished at: 2020-03-27T09:07:02+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.2:test (default-test)
```
Disabling one of the two test classes means both classes run fine, so the tests themselves have no error. After removing the `@Inject` and `@Configproperty(name = 'myproperty')`, and hardcoding the value, both tests are running as expected. So the problem is clearly in the injection mechanism.

Note that this behavior was not with Quarkus 1.2 and started after upgrading to Quarkus 1.3

**Expected behavior**
I can inject the `myproperty` set in `applications.properties` across multiple test classes and have my test classes all succeed.

**Actual behavior**
Currently this injection only works for one class, and will fail once the second test class is starting.

**To Reproduce**
1. Create two separate test classes and a config parameter in application.properties
2. Inject the parameter in both test classes
3. Watch the first test succeed, and the second one fail. Run them individually and the test cases both succeed.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.3.0
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Maven home: /home/jorn/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: /opt/jdk-11.0.6+10
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "4.19.84-microsoft-standard", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment] 2020-03-27 11:54
Thanks for @jargelo.

Could you supply a simple reproducer? I tried to reproduce the problem it in a simple project but couldn't.

**Comment by jargelo** [comment] 2020-03-27 18:57
I've trimmed down my code to the smallest possible set to reproduce the issue, committed it to https://github.com/jargelo/quarkusio. I left my pom.xml intact (but disabled some dependencies) in case that is causing issues.

**Comment by geoand** [comment] 2020-03-29 13:29
This seems to be caused by `@TestInstance(Lifecycle.PER_CLASS)`. 
I will take a deeper look and see what can be done.

**Comment by geoand** [comment] 2020-03-29 14:05
The issue should be fixed by #8210

**Closed** 2020-03-30 05:03 UTC
Labels: kind/bug

**Comment by jargelo** [comment] 2020-03-30 08:30
Thanks for the quick turnaround @geoand

**Comment by geoand** [comment] 2020-03-30 08:33
You are welcome

**Comment by skabashnyuk** [comment] 2020-06-03 18:50
If I sometimes(periodically) get 
`Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
`  with 1.5.0 Final does it sound like a legitimate problem?

**Comment by daniel-alonso-sanchez** [comment] 2020-06-29 14:21
> If I sometimes(periodically) get
> `Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype ` with 1.5.0 Final does it sound like a legitimate problem?

Same here with 1.5.2

**Comment by davidcurrie** [comment] 2020-09-29 08:57
Not sure if there has been a regression here or something else is at play but I'm not seeing this error having moved a project up from 1.4.2 to 1.8.1 Final.

**Comment by independentid** [comment] 2021-04-14 18:38
I am receiving this issue with 1.13.1.Final.  In my case it is triggered trying to load the JwtEncryptionBuilder class which is part of quarkus-smallrye-jwt-build.

**Comment by fstarred** [comment] 2022-03-04 14:43
I had the same error when testing with a Main application that involves parallel().stream().
If I remove parallel(), then test does its work without exceptions.
PS Launching the main from quarkus:dev() return me no error

**Comment by lthasle** [comment] 2022-07-26 10:29
I get the same error when I move from 2.10.2.Final to:  2.10.3.Final

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.quarkus.test.junit.QuarkusTestExtension.popMockContext(QuarkusTestExtension.java:675)
	at io.quarkus.test.junit.QuarkusTestExtension.afterEach(QuarkusTestExtension.java:510)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterEachCallbacks$12(TestMethodTestDescriptor.java:257)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$13(TestMethodTestDescriptor.java:273)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:273)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:272)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterEachCallbacks(TestMethodTestDescriptor.java:256)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:141)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:95)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:91)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:60)
	at org.eclipse.jdt.internal.junit5.runner.JUnit5TestReference.run(JUnit5TestReference.java:98)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:40)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:529)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:756)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.test.junit.QuarkusTestExtension.popMockContext(QuarkusTestExtension.java:673)
	... 56 more
Caused by: java.util.ServiceConfigurationError: io.smallrye.config.SmallRyeConfigFactory: io.quarkus.runtime.configuration.QuarkusConfigFactory not a subtype
	at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:593)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1244)
	at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1273)
	at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1309)
	at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1393)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getFactoryFor(SmallRyeConfigProviderResolver.java:100)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:76)
	at io.smallrye.config.SmallRyeConfigProviderResolver.getConfig(SmallRyeConfigProviderResolver.java:64)
	at org.eclipse.microprofile.config.ConfigProvider.getConfig(ConfigProvider.java:85)
	at io.smallrye.faulttolerance.config.CircuitBreakerConfigImpl.delayUnit(CircuitBreakerConfigImpl.java:180)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.prepareSyncStrategy(FaultToleranceInterceptor.java:365)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.lambda$syncFlow$2(FaultToleranceInterceptor.java:250)
	at io.smallrye.faulttolerance.internal.StrategyCache.lambda$getStrategy$0(StrategyCache.java:20)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at io.smallrye.faulttolerance.internal.StrategyCache.getStrategy(StrategyCache.java:20)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.syncFlow(FaultToleranceInterceptor.java:250)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor.intercept(FaultToleranceInterceptor.java:182)
	at io.smallrye.faulttolerance.FaultToleranceInterceptor_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:40)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at sb1.fip.app.bsf.online.client.SkadeTilbudDocClient$$CDIWrapper_Subclass.clearMock(Unknown Source)
	at sb1.fip.app.bsf.online.client.SkadeTilbudDocClient$$CDIWrapper_ClientProxy.clearMock(Unknown Source)
	at io.quarkus.test.junit.MockSupport.popContext(MockSupport.java:28)
	... 61 more
