### ISSUE TITLE
Support QueryDSL in Panache

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#4016] opened 2019-09-14 06:16 UTC
QueryDSL is very popular in developer communities, as an alternative of JPA APIs, it is better to add it in Quarkus.

**Comment by emmanuelbernard** [comment] 2019-11-18 07:39
Optional predicates #2303 and type safe HQL might be a good replacement for QueryDSL. We looked at QueryDSL but it does not seem to be maintained anymore, that's why we hesitated to invest in it. If you can be a bit patient, let's see if the solution ^ solves your problems. Or you can try and contribute QueryDSL to Quarkus.

**Comment by kivan-mih** [comment] 2019-12-02 10:59
> Optional predicates #2303 and type safe HQL might be a good replacement for QueryDSL. We looked at QueryDSL but it does not seem to be maintained anymore, that's why we hesitated to invest in it. If you can be a bit patient, let's see if the solution ^ solves your problems. Or you can try and contribute QueryDSL to Quarkus.

https://github.com/querydsl/querydsl/issues/2459#issuecomment-555430030
As this post suggests QueryDSL is again maintained by a small team separate from the previous owner, however, the assumption that they would succeed is fragile.

Personally, my benefit from Querydsl was build-time query checking and IDE code completion. I used it as a plugin for Spring Data (example here https://www.logicbig.com/tutorials/spring-framework/spring-data/query-dsl-basic.html), and it was awesome. But Querydsl is not a must have, If some other instrument will give me the same benefits and will be easy to use, I will deffinitely go for it.

Also, type-safe querries in Quarkus could be a good move in competition with Micronaut, since IMHO for now, they have better storage integration options.

**Comment by geoand** [comment] 2024-02-26 16:52
@FroMage I assume that with the latest improvements in Hibernate plus your work to  integrate them in Quarkus, we can close this as `won't do`?

**Comment by FroMage** [comment] 2024-02-26 17:44
Yes.

**Closed by FroMage** 2024-02-26 17:44 UTC
Labels: kind/enhancement, area/panache

**Comment by hantsy** [comment] 2024-02-27 00:56
@geoand QueryDSL provides type safe API, it is good for IDE support and get the QL error at code time, but HQL we have to compile it(and even run it) and know where is wrong.

**Comment by FroMage** [comment] 2024-03-01 10:25
https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#generated-query-methods

These are checked at compile-time and will get you IDE errors, and even completion for some IDEs

**Comment by kivan-mih** [comment] 2024-03-01 11:18
> https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#generated-query-methods
> 
> These are checked at compile-time and will get you IDE errors, and even completion for some IDEs

It does not provide type safe queries checked in compile time as I understand. Another big issue is that they are not composable. QueryDSL solves all these two problems.

**Comment by FroMage** [comment] 2024-03-01 14:15
Well, the problem is that it's not clear if QueryDSL is still maintained. But there's nothing stoping anyone from writing a QueryDSL extension or support in Quarkiverse. That'd be awesome. We're not going in that direction for ORM/Panache, but that doesn't mean QueryDSL has no place in Quarkus, if you all want it, we'll help you build the extension.

**Comment by hantsy** [comment] 2024-03-04 01:20
@FroMage  QueryDSL has just released a new version this year, https://github.com/querydsl/querydsl/releases/tag/QUERYDSL_5_1_0

**Comment by FroMage** [comment] 2024-03-12 10:21
Ah, this was not reflected in their website.

**Comment by dlmiles** [comment] 2024-04-04 17:50
QueryDSL 5.1.0 from Jan 2024 does not support `jakarta.*` namespace, is very Maven centric, so no working Gradle examples or support plugins, official documentation or examples from the source.  There is Kotlin support but I was not able to get it working without error in a 4 hour evaluation of suitability for my project.

I have evaluated the project fork over at `https://github.com/openfeign/querydsl` which might address some on these matters, but I did not find it compelling to continue spending time on evaluating QueryDSL.

Time to evaluate Panache.

Hibernate used to have a useful and manageable Criteria API of its own but design by JPA committee seems to have struck that feature (it is now removed) and transformed it into the abomination it has become.  So looking for a DSL so it never needs to be used directly by the programmer and regular kinds of queries need fewer lines of code.

**Comment by hantsy** [comment] 2024-04-05 01:28
Personally I like QueryDSL/JOOQ like type safe API when assembling complex queries, JPA Criteria API is a little tedious. 

Panache uses literal text instead of type safe Java/Kotlin API, I do not like this approach, without IDE support, we have to determine the correctness of syntax by compiling/running the application.

**Comment by hantsy** [comment] 2024-04-05 01:33
@dlmiles It seems https://github.com/OpenFeign/querydsl is updated to the latest spec/frameworks.
