### ISSUE TITLE
Kubernetes manifests are not generated when using QuarkusProdModeTest

### ISSUE THREAD

**Issue by metacosm** [quarkusio/quarkus#36041] opened 2023-09-20 15:30 UTC
### Describe the bug

I'm seeing the following error message when running my tests from maven:
2023-09-20 14:19:44,884 WARN  [io.qua.kub.dep.KubernetesProcessor] (build-5) No project was detected, skipping generation of kubernetes manifests!

Adding additional information to Quarkus itself, the issue seems to come from dekorate:
```java
java.lang.IllegalStateException: Could not find matching project info read
        at io.dekorate.project.FileProjectFactory.lambda$createInternal$0(FileProjectFactory.java:64)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.dekorate.project.FileProjectFactory.createInternal(FileProjectFactory.java:64)
        at io.dekorate.project.FileProjectFactory.create(FileProjectFactory.java:44)
        at io.quarkus.kubernetes.deployment.KubernetesCommonHelper.createProject(KubernetesCommonHelper.java:129)
        at io.quarkus.kubernetes.deployment.KubernetesProcessor.build(KubernetesProcessor.java:140)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:858)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:1623)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Of note, this only occurs when running the tests from my typical maven build. If I run the tests from my IDE (to debug them, for example), then everything works as expected.

### Expected behavior

Tests should behave the same way wherever they are executed.

### Actual behavior

Kubernetes manifests are not generated when they should really be.

### Quarkus version or git rev

3.2.6.Final

**Comment by iocanel** [comment] 2023-09-21 08:44
@metacosm: The tests we use to test the generation process are mostly QuarkusProdModeTest, so I am wondering if there is something in your setup that triggers it. Do you have a reproducer?

**Comment by iocanel** [comment] 2023-09-22 18:37
I can't reproduce. 
I used the main branch but it worked fine.
I also used the main branch + the code from the commit you provided.

In both cases things worked just fine.

**Comment by metacosm** [comment] 2023-09-22 19:41
What do you mean by "things worked fine"? You didn't get the warning or did the tests pass?

**Comment by gsmet** [comment] 2024-11-21 14:51
AFAICS it has been fixed in the Operator SDK here: https://github.com/quarkiverse/quarkus-operator-sdk/pull/730 so closing.

**Closed by gsmet** 2024-11-21 14:51 UTC
Labels: kind/bug, area/kubernetes
