### ISSUE TITLE
Quarkus OIDC client unable to get access-token

### ISSUE THREAD

**Issue by chiragrp** [quarkusio/quarkus#18221] opened 2021-06-29 06:39 UTC
Hi Quarkus Team,

I am using quarkus-oidc-client extension to obtain token. The idea is to send client-id, client-secret and grant-type to OpenID connect provider to obtain access token. I am referring to specification here @ https://www.oauth.com/oauth2-servers/access-tokens/client-credentials/
In addition, I also need to include additional parameters such as scope
Sample from above link
```
POST /token HTTP/1.1
Host: authorization-server.com
 
grant_type=client_credentials
&client_id=xxxxxxxxxx
&client_secret=xxxxxxxxxx
&scope=xxxx,yyyy,zzzz
```
I have configured the extension with following configuration
```
quarkus.oidc-client.auth-server-url=https://openid-provider.org
quarkus.oidc-client.discovery-enabled=false
quarkus.oidc-client.token-path=/token
quarkus.oidc-client.client-id=rf3ScIceRGbm8IShjMUDUY67INhJEGRb
quarkus.oidc-client.credentials.secret=************
#quarkus.oidc.authentication.scopes=USER_INFO
```
Referring to this https://quarkus.io/guides/security-openid-connect-client to use OidcClient in the code.
However, I get following error:
```
Caused by: io.quarkus.oidc.client.OidcClientException: 
                {  
                        "error":"invalid_client",
                        "error_description":"missing or invalid client_id or client_secret"
                }

```
From debugging, it appears that OidcClientImpl.java does not include "client_id" and "client_secret" in HTTP Form. I could only see "grant_type" added in the HTTP Form. 

How do I make quarkus-oidc-client send all required parameters in HTTP Form?

Software versions:
* OpenJDK 11
* Quarkus 1.13.7

Runtime mode: JAR

**Comment by sberyozkin** [comment] 2021-07-04 17:57
Hi @chiragrp Is it a duplicate of #18374 ? I just commented there

**Comment by sberyozkin** [comment] 2021-07-05 11:58
@chiragrp Let me close this one - it does look like a duplicate, lets continue the discussion at #18374, thanks

**Closed by sberyozkin** 2021-07-05 11:58 UTC
Labels: area/oidc
