### ISSUE TITLE
Remove illegal refletive access warning for xstream for parameterized tests

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#10303] opened 2020-06-26 13:06 UTC
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.thoughtworks.xstream.core.util.Fields (file:/home/peter/.m2/repository/com/thoughtworks/xstream/xstream/1.4.11.1/xstream-1.4.11.1.jar) to field java.util.TreeMap.comparator
WARNING: Please consider reporting this to the maintainers of com.thoughtworks.xstream.core.util.Fields
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by emmanuelbernard** [comment] 2020-06-26 13:07
See #10271

**Comment by geoand** [comment] 2020-06-26 14:07
This should be mostly fixed in `1.6.0.CR1`

**Comment by pschyma** [comment] 2020-06-26 19:53
It does not appear in 1.6.0.CR1 for me. In 1.5.x I could observe it immediately after adding any `@QuarkusTest` to my Gradle projects which use RESTAssured.

**Comment by famod** [comment] 2020-07-28 22:07
Hm, I am able to provoke this in 1.6.1.Final via:
```java
public class FooParamResover implements ParameterResolver {

    @Override
    public boolean supportsParameter(final ParameterContext parameterContext, final ExtensionContext extensionContext) throws ParameterResolutionException {
        return parameterContext.getParameter().getType() == Foo.class;
    }

    @Override
    public Foo resolveParameter(final ParameterContext parameterContext, final ExtensionContext extensionContext) throws ParameterResolutionException {
        return new Foo();
    }
}
```
```java
public class Foo {

    public String get() {
        return CDI.current().select(SomeBean.class).get().toString();
    }
}
```
```java
    @Test
    public void test(final Foo foo) {
        System.err.println(foo.get());
    }
```

PS: The resolver is registered via `META-INF/services/org.junit.jupiter.api.extension.Extension`.

Reopen XOR new ticket?

**Comment by geoand** [comment] 2020-07-28 22:10
Indeed that does provoke the message (it's known).

The problem used to be that the message was shown whether or not the was a parameter resolver.

I'd say reopen the issue but adjust the title.

**Comment by famod** [comment] 2020-07-28 22:17
I am not allowed to change the title so I'd kindly ask you @geoand or @emmanuelbernard to do this. Thanks!

Btw, it has nothing to do with the CDI lookup (just checked), but you certainly knew that already. 😉

**Comment by famod** [comment] 2020-07-28 22:20
Do we need a reproducer or is it obvious?

**Comment by geoand** [comment] 2020-07-29 06:39
Nah, I think it's obvious.

The fix of course needs to be upstream in the xstream project

**Comment by famod** [comment] 2020-07-29 16:56
> The fix of course needs to be upstream in the xstream project

I fear that route doesn't look very promising: https://github.com/x-stream/xstream/issues/101

**Comment by famod** [comment] 2020-07-29 23:22
I took a stab at this upstream: https://github.com/x-stream/xstream/pull/216

This won't help for certain scenarios (e.g. if your parameter class contains a `TreeMap`) but it removed all warnings for my use case.

Now lets hope it gets merged and released soon.

**Comment by geoand** [comment] 2020-07-30 07:07
That's great! Let's see what happens

**Comment by famod** [comment] 2020-07-30 07:29
Until a new release of xstream (which might take a long time), we_could_ work around this Quarkus by registering our own list of converters. Just saying.

**Comment by geoand** [comment] 2020-07-30 07:37
Yeah, if the release don't come soon, I'll let you do a PR for that :)

**Comment by famod** [comment] 2020-07-30 16:07
Until then:
```
--add-opens java.base/java.lang.reflect=ALL-UNNAMED
--add-opens java.base/java.util=ALL-UNNAMED
--add-opens java.base/java.text=ALL-UNNAMED
--add-opens java.desktop/java.awt.font=ALL-UNNAMED
```
(yes, even AWT)

**Comment by famod** [comment] 2020-08-13 17:11
_Update_: My changes were merged into xstream master but since 1.5 seems to take more time, I've created another PR against the 1.4 branch.
The maintainer of xstream said he might have time to release another 1.4 (1.4.12.1?) with my workaround at the beginning of September.

**Comment by famod** [comment] 2020-09-06 21:51
1.4.13 is out (but not yet on central): https://github.com/x-stream/xstream/releases/tag/XSTREAM_1_4_13
I'll have a look in the next few days but it seems I will have some "fun" with the following comment:

```xml
        <dependency>
            <groupId>com.thoughtworks.xstream</groupId>
            <artifactId>xstream</artifactId>
            <!-- Avoid adding this to the BOM / Version has to be kept in sync with what optaplanner uses otherwise the enforcer complains -->
            <version>1.4.11.1</version>
        </dependency>
```

**Comment by geoand** [comment] 2020-09-06 21:56
Good thing is that octaplanner is no longer part of the core, so we shouldn't have any problems

**Closed** 2020-09-08 06:55 UTC
Labels: area/testing, kind/bug

**Comment by deodorel** [comment] 2021-10-13 09:05
Does xstream work with native mode quarkus? Because i had classloading issues with its own custom class loader ....

**Comment by wzChuang** [comment] 2022-06-28 02:03
> Does xstream work with native mode quarkus? Because i had classloading issues with its own custom class loader ....

Is that the problem? I met it, too. How did you solve it?

Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.core.util.TypedNull
Caused by: java.lang.NoClassDefFoundError

**Comment by deodorel** [comment] 2022-06-28 05:23
Hello. I didn't, I just gave up on xstream. Libraries that do serialisation are hard to just use in native mode, usually need some kind of conversion.

Obtenir Outlook pour Android<https://aka.ms/AAb9ysg>
________________________________
