### ISSUE TITLE
LaunchResult.getOutputStream is empty on Windows

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#31765] opened 2023-03-10 13:48 UTC
### Describe the bug

I have an application, which outputs its arguments(via `LOG.info`) and make them available on a http endpoint, and a test, which checks, that the application outputs these arguments(using `QuarkusMainTest` and `LaunchResult`). This test works as expected on Linux, but fails on Windows. The input arguments are in the output on both OSes

### Expected behavior

The test should work (or do not work) consistently on different OSes

### Actual behavior

`LaunchResult.getOutputStream()` returns empty list on widnows

### How to Reproduce?

1. `git clone git@github.com:fedinskiy/reproducer.git -b windows-kubernetes`
2. `mvn clean test` # this fails on windows
3. `mvn clean package -DskipTests`
4. `java -jar target/quarkus-app/quarkus-run.jar  one two`  Output contains "Received arguments: one,two" and http://0.0.0.0:8080/args contains both arguments

### Output of `uname -a` or `ver`

CYGWIN_NT-10.0-17763 fdudinsk-win 3.4.6-1.x86_64 2023-02-14 13:23 UTC x86_64 Cygwin

### Output of `java -version`

11.0.18, vendor: GraalVM Community, runtime: C:\Program Files\GraalVM\graalvm-ce-java11-22.3.1

### Quarkus version or git rev

d6e0af822c47b2f364cffc49dd57861ccb710879

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)

**Comment by geoand** [comment] 2023-03-10 13:53
I wonder if @Karm has any idea what's going on [here](https://github.com/quarkusio/quarkus/blob/56ea635ef1a73811bbd247668a7dc5388af5c2ad/test-framework/junit5/src/main/java/io/quarkus/test/junit/QuarkusMainTestExtension.java#L86)

**Comment by fedinskiy** [comment] 2023-03-10 13:56
And I doubt, that `area/kubernetes` is a proper tag. The branch is named that because I found this one, while investigating another bug :)

**Comment by gastaldi** [comment] 2023-03-10 20:07
I'll have a look at it

**Comment by gastaldi** [comment] 2023-03-11 00:11
@fedinskiy I ran the tests in your project in Windows and couldn't reproduce the issue you're reporting here. I see the following output while running the test: 

```
2023-03-10 21:09:01,885 INFO  [io.qua.ts.lif.Main] (main) Received arguments: cli,Hello,World
```

**Comment by fedinskiy** [comment] 2023-03-13 12:11
@gastaldi that is interesting. RN I can reproduce the bug with `mvn clean test -Dquarkus.platform.version=3.0.0.Alpha5
` as well. Which version of OS do you use?

**Comment by gastaldi** [comment] 2023-03-13 12:19
@fedinskiy it passes with 3.0.0.Alpha5. I am using `Microsoft Windows [Version 10.0.22000.1574]`

**Comment by gsmet** [comment] 2023-03-13 12:29
Are you both using the same shell?

**Comment by gastaldi** [comment] 2023-03-13 12:29
Yes, I tried with Cygwin and with CMD

**Comment by gastaldi** [comment] 2023-03-13 12:32
Actually, sorry. I thought I was using Cygwin, but it was just CMD. I can see the error when running the command in Cygwin

**Comment by geoand** [comment] 2023-04-10 08:36
What was the conclusion of this one?

**Comment by gastaldi** [comment] 2023-04-10 12:08
@geoand I managed to reproduce it using Cygwin and the steps in the issue description but didn't find a solution yet

**Comment by geoand** [comment] 2023-04-10 12:09
Gotcha thanks

**Comment by gsmet** [comment] 2024-08-21 15:58
I will close this one.
We didn't have much people complain about Cygwin and it doesn't look like an easy one to solve.

**Closed by gsmet** 2024-08-21 15:58 UTC
Labels: kind/bug, area/testing, env/windows
