### ISSUE TITLE
ExceptionMapper<WebApplicationException> is not working in DEV mode

### ISSUE THREAD

**Issue by aldettinger** [quarkusio/quarkus#31431] opened 2023-02-27 08:26 UTC
### Describe the bug

For instance, with the route below:

```
@Path("/helloworld")
public class GreetingResource {

    @POST
    @Produces(MediaType.TEXT_PLAIN)
    public void hello(@PathParam(value = "myparam") String param) {
        System.out.println("hello called with param="+param);
    }

    @Provider
    public static class WebAppExceptionMapper implements ExceptionMapper<WebApplicationException> {

        @Override
        public Response toResponse(WebApplicationException exception) {
            return Response.status(400)
            .entity("<h1>Custom Webapplication Exception</h1>")
            .build();
        }
    }
}
```

And invoking with:

```
curl -X POST http://localhost:8080/hellow?myparam=value1
```

In DEV mode, nothing happen while in JVM mode, the output below is produced:

```
curl -X POST http://localhost:8080/hellow?myparam=value1
<h1>Custom Webapplication Exception</h1>
```

Shouldn't DEV mode behave the same as JVM mode with respect to ExceptionMapper ?

### Expected behavior

The ExceptionMapper<WebApplicationException> should maybe work the same in DEV mode.

### Actual behavior

The ExceptionMapper<WebApplicationException> does not work the same in DEV mode.

### How to Reproduce?

See description.

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### GraalVM version (if different from Java)

GraalVM 22.3.0 Java 17 CE (Java Version 17.0.5+8-jvmci-22.3-b08)

### Quarkus version or git rev

2.16.3.Final and 3.0.0.Alpha4

**Comment by gastaldi** [comment] 2023-02-27 13:18
I can observe this behavior in resteasy-reactive and resteasy classic

**Comment by gastaldi** [comment] 2023-02-27 13:18
@geoand any idea here?

**Comment by geoand** [comment] 2023-02-27 13:22
I am pretty sure this is a duplicate, but I'm on a phone now and can't really search

**Comment by geoand** [comment] 2023-03-02 13:48
I would say this is a duplicate of https://github.com/quarkusio/quarkus/issues/7883

**Closed by geoand** 2023-03-02 13:48 UTC
Labels: kind/bug, area/devmode, area/resteasy, area/resteasy-reactive
