### ISSUE TITLE
Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation in unit tests (non @QuarkusTest)

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#29105] opened 2022-11-07 18:56 UTC
### Describe the bug

Hello, we want to test some specific methods of our services which have no dependencies to injected beans.
So we want these tests to be fast without spinning up everything which takes quite some time in our case, so classic unit tests.
Thus, we created unit test class without @QuarkusTest

However, as the service method under test is using `io.quarkus.logging.Log` the test fails.
And I did not find a solution to mock `io.quarkus.logging.Log` as everything from quarkus side seems to assume  `@QuarkusTest`.
Trying to mock with mockito-inline works, but disables the logs.
Is there any way to test service methods that use `io.quarkus.logging.Log` without `@QuarkusTest`?

Example

```
package org.acme;

import io.quarkus.logging.Log;

import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
public class Service {
    public void serviceMethod() {
        Log.info("I am only a logging method and don't have any dependencies to cdi beans etc.");
    }
}
```

```
package org.acme;

import org.junit.jupiter.api.Test;

public class ServiceTest {
    @Test
    public void test(){
        Service service = new Service();
        service.serviceMethod();
    }
}
```

### Expected behavior

console log:
"I am only a logging method and don't have any dependencies to cdi beans etc."

### Actual behavior

java.lang.UnsupportedOperationException: Using io.quarkus.logging.Log is only possible with Quarkus bytecode transformation

	at io.quarkus.logging.Log.fail(Log.java:2716)
	at io.quarkus.logging.Log.info(Log.java:1260)
	at org.acme.Service.serviceMethod(Service.java:10)
	at org.acme.ServiceTest.test(ServiceTest.java:10)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:727)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at io.quarkus.test.junit.QuarkusMainTestExtension.interceptTestMethod(QuarkusMainTestExtension.java:306)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:156)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:147)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:86)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.lambda$invoke$0(InterceptingExecutableInvoker.java:93)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:92)
	at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker.invoke(InterceptingExecutableInvoker.java:86)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:217)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:213)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:138)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:147)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:127)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:90)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:55)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:102)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:57)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)

**Comment by Ladicek** [comment] 2022-11-08 07:36
The exception message is pretty clear, isn't it? `io.quarkus.logging.Log` requires the Quarkus magic to happen. For testing, that indeed means `@QuarkusTest` (and friends). I'm inclined to just close this, but to facilitate discussion, I'll leave this open for a bit -- perhaps we can find a way to make this work. At least I'm removing `kind/bug`, as this certainly works as designed.

**Comment by Ladicek** [comment] 2022-11-08 08:22
Thinking about it some more and I believe `QuarkusUnitTest` would be a perfect fit for this use case. It is not documented or supposed to be used externally, but you may wanna try it and see if that works for you.

**Comment by geoand** [comment] 2022-11-08 09:19
I am pretty sure that most people will not want to use `QuarkusUnitTest` because it requires a shift in what they are used to as application developers.
That being said, it's super useful for such scenarios.

@Ladicek should we close this issue?

**Comment by Ladicek** [comment] 2022-11-08 10:15
Yeah. I can't think of anything better than `QuarkusUnitTest` frankly.

**Closed by Ladicek** 2022-11-08 10:15 UTC
Labels: area/logging

**Comment by syr** [comment] 2022-11-08 16:32
> Thinking about it some more and I believe `QuarkusUnitTest` would be a perfect fit for this use case. It is not documented or supposed to be used externally, but you may wanna try it and see if it works for you.

OK, how can I add this to a mvn project?

**Comment by Ladicek** [comment] 2022-11-09 07:43
Here's the relevant documentation:

- https://quarkus.io/guides/writing-extensions#testing-extensions
- https://quarkus.io/guides/getting-started-testing#mixing-quarkustest-with-other-type-of-tests

**Comment by julianode** [comment] 2023-02-25 20:55
Sorry for the late discussion, but it is a shame this issue is a "won't fix".

I was planing to use the Log.info() method everywhere to leverage more of the Quarkus magic.
However, I would not like to deploy a custom Quarkus application for each test class using @QuarkusUnitTest nor use @QuarkusTest for a simple method test.
Therefore, I will get to my old logging strategy again.

Why would someone ever use Log.info() in any method that will have to go through a simple unit test that does not need the Quarkus application running? It will fail while testing and work in production. We do not need to manage this.
Then, I may just use a Logger object instance which will work in production and when I just want to run my unit tests.

Not fixing this issue kind of breaks the awesomeness of the Quarkus magic.
I think this issue will hold down the use of the Log class or make it useless.
