### ISSUE TITLE
traceId, spanId not set in logs when using quartz and opentelemetry

### ISSUE THREAD

**Issue by syr** [quarkusio/quarkus#28552] opened 2022-10-12 22:36 UTC
### Describe the bug

I use quarkus-quartz and quarkus-opentelemetry

Have definded a custom log format like in https://quarkus.io/guides/opentelemetry#create-the-configuration

```
quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
```

### Expected behavior

Expected that traceId etc. are filled, (this only works for rest resource), see:

```
  00:16:43 INFO  traceId=7d79594584b49a7db88f47c75a0cd185, parentId=, spanId=cb9d17786f3ed0c0, sampled=true [or.ac.qu.TaskResource] (executor-thread-0) log test
```

### Actual behavior

But for log output in quartz scheduled method everything is empty

```
00:16:45 INFO  traceId=, parentId=, spanId=, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-3) log test
```

### How to Reproduce?

https://github.com/syr/quartz-otel-logs is based on latest quartz-quickstart code.

Only needs to be started, scheduler runs every 10 seconds printing log lines without traceId etc.

Calling http://localhost:8080/tasks  shows that it works generally, but only for rest resources

### Output of `java -version`

 java -version openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by mkouba** [comment] 2022-10-13 06:21
I believe that this works as designed. You can't expect a `traceId` to be set during execution of a scheduled method that has no HTTP request associated. In fact, a scheduled method cannot have an HTTP request associated because it represents a kind of entry point in your application - there is no external event that would trigger the execution of a scheduled method.

I'm going to close this issue. Feel free to reopen if the paragraph above does not make any sense.

**Comment by Ladicek** [comment] 2022-10-13 08:36
Technically, a scheduled method can call other external services etc., and so tracing may make sense. As you mention, a scheduled method is an entrypoint, so it deserves a fresh new trace/span, I'd say.

**Comment by mkouba** [comment] 2022-10-13 09:04
> Technically, a scheduled method can call other external services etc., and so tracing may make sense. As you mention, a scheduled method is an entrypoint, so it deserves a fresh new trace/span, I'd say.

I see. My point was that the tracing info should not be propagated but that was probably just a misunderstanding of the problem.

**Comment by brunobat** [comment] 2022-10-13 09:20
Tracing does make sense on Quarkus tasks. This is not just for HTTP. 
It will be great to understand the outcome of each job.
This requires 2 changes, though. One thing is to instrument jobs, another one is curating the MDC context with the right data.

**Comment by syr** [comment] 2022-10-14 10:10
Thanks for adding the issue to the roadmap.
As a workaround I use otel-agent (via JAVA_TOOL_OPTIONS) and set the MDC fields by myself by
```
        SpanContext spanContext = Span.current().getSpanContext();
        MDC.put("traceId", spanContext.getTraceId());
        MDC.put("spanId", spanContext.getSpanId());
        MDC.put("parentId", "unknown");
```

However get two problem:

1. no idea where to get parentId from. As far as I read it is not possible to get it manually
2. manual instrumentation by @WithSpan is not working/ignored. Can a mix of auto-instrumentation (by otel agent) and manual instrumenation work?

**Comment by brunobat** [comment] 2022-10-14 10:25
1. You don't really need the parent. The SpanId and the TraceId are enough to search on Jaeger or an equivalent tool.
2. In Quarkus we don't recommend using the agent because of context propagation problems. The '@WithSpan' on a CDI bean should work with imperative code. If you can provide a reproducer it would help.

**Comment by syr** [comment] 2022-10-14 10:28
https://github.com/syr/quartz-otel-logs/commit/4ccd464e8e216576070acfd63ff6bdf3084d1019

Without agent I don't get valid traceId, only initial values 0000000000000. So atm it's also only meant as a temp. workaround.

**Comment by brunobat** [comment] 2022-10-14 10:33
We need to instrument Quartz with OpenTelemetry. Not done yet.
But if you call a CDI bean from quartz and use '@WithSpan' it should work.

**Comment by syr** [comment] 2022-10-14 10:42
moved the method with @Span to a seperate service class in https://github.com/syr/quartz-otel-logs/commit/57aef0684ec3cd944d3067b4d245203b2b299e67 , but still the same spanId

```
12:39:39 INFO  traceId=1646cfc30a48e24dfaa8a5e3f4cc4a75, parentId=unknown, spanId=5058966601badfb7, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-5) log test
  12:39:39 INFO  traceId=1646cfc30a48e24dfaa8a5e3f4cc4a75, parentId=unknown, spanId=5058966601badfb7, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-5) log test from testMethod
´´´

**Comment by brunobat** [comment] 2022-10-14 13:51
I think we'll need a reproducer project

**Comment by syr** [comment] 2022-10-14 16:06
See link in my previous reply

**Comment by syr** [comment] 2022-10-15 12:10
I added some log output that shows that traceId and spanId from spanContext vs. MDC are not consistent
https://github.com/syr/quartz-otel-logs 

logs from scheduled method (spanId in log entry is correct, but is also directly before set in MDC)
```
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-2) traceId: 59ec1645b4243fdf69e4dc8a61377bf3
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-2) spanId: 46e90f4f12994226
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-2) log test
```

logs from service method, called by scheduled method (spanId in log entries should be different because method is annotated with @WithSpan)
```
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-2) traceId in testMethod: 59ec1645b4243fdf69e4dc8a61377bf3
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-2) spanId in testMethod: b6b70be685472933
14:01:26 INFO  traceId=59ec1645b4243fdf69e4dc8a61377bf3, parentId=unknown, spanId=46e90f4f12994226, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-2) log test in testMethod
```

**Comment by brunobat** [comment] 2022-10-17 09:24
The MDC context needs to be cleared after the job was done, with  MDC.remove(...) after:
https://github.com/syr/quartz-otel-logs/blob/2ad12e7efbbb1557a17c57dc305280a50a92a3d0/src/main/java/org/acme/quartz/TaskBean.java#L34

**Comment by syr** [comment] 2022-10-17 16:20
span id keeps the same like this.

Only thing that worked but is cumbersome is to set als the MDC explicitly in the org.acme.quartz.TaskService#testMethod, so again like:

```
@WithSpan("custom span")
    public void testMethod(){
        SpanContext spanContext = Span.current().getSpanContext();
        MDC.put("traceId", spanContext.getTraceId());
        MDC.put("spanId", spanContext.getSpanId());
...
```
Which leads to correct/expected log field with new spanId but same traceId

```
  18:13:19 INFO  traceId=c99870cee4e1da346d9d73535db2ec5a, parentId=unknown, spanId=58e43c8f29b1f67b, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-2) spanId: 58e43c8f29b1f67b
  18:13:19 INFO  traceId=c99870cee4e1da346d9d73535db2ec5a, parentId=unknown, spanId=58e43c8f29b1f67b, sampled= [or.ac.qu.TaskBean] (QuarkusQuartzScheduler_Worker-2) log test
  18:13:19 INFO  traceId=c99870cee4e1da346d9d73535db2ec5a, parentId=unknown, spanId=8524d787f125a66b, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-2) traceId in testMethod: c99870cee4e1da346d9d73535db2ec5a
  18:13:19 INFO  traceId=c99870cee4e1da346d9d73535db2ec5a, parentId=unknown, spanId=8524d787f125a66b, sampled= [or.ac.qu.TaskService] (QuarkusQuartzScheduler_Worker-2) spanId in testMethod: 8524d787f125a66b
```

Any idea why is opentelemetry not doing this automatically? Or is it not its responsibility? 
Sorry, maybe I should ask this in opentelemetry github or SO

**Comment by brunobat** [comment] 2022-10-18 09:04
There is no connection between the MDC context and OpenTelemetry. 
On Quarkus we curate the MDC context with that data (it's a Quarkus specific feature), however, because we haven't instrumented Quartz yet, that's why the info is not being shown in the logs as well. 
Setting the MDC context manually in the method works even if it's not clean. Please don't forget to call MDC.remove in the end of the method, otherwise you will get wrong log entries afterwards. 
Once we implement the OTel Quartz instrumentation on Quarkus, you will be able to remove that code.

**Comment by syr** [comment] 2022-10-18 13:49
Or is it maybe possible to plug jboss logging to on of the logging framework that supports automatic config of MDC (Log4J, Logback), see https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/logger-mdc-instrumentation.md ?

**Comment by syr** [comment] 2022-11-13 10:19
@Ladicek @brunobat @brunobat @radcortez 
Is there some list of libraries that are instrumented by quarkus-opentelemetry?
I guess it must be a subset of https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md

**Comment by brunobat** [comment] 2022-11-14 10:12
Hi Syr,
There is no such list for the time being and we currently don't follow that [list](https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/docs/supported-libraries.md). 
We prefer to instrument Quarkus ourselves and make sure context propagation and native mode behave correctly. 
I can tell you that inside Quarkus, today we instrument:
* Vertx, including the HTTP server
* REST clients
* GRPC server
But also if you use:
* Reactive messaging from SmallRye
* SQL queries if you use the dedicated driver
* Provide CDI aware beans where you can create your own spans

OpenTelemetry is constantly evolving but also needs the community contributions...

**Comment by syr** [comment] 2022-11-16 10:27
Hi @brunobat, thanks for the info. Could you please add this list to the opentelemetry guide? IMO it's crucial to decide if the extension fits or if otel agent must be used to get more auto-instrumenation, like in our case using quartz and aws sdk libs.

Might be a silly question, but is there a recommended way atm for production applications?
OpenTracing is deprecated and OpenTelemetry experimental, so sitting between chairs atm, using custom stuff.
Would love to contribute, need to fight to get some time slots, which is super hard during a dev project.

**Comment by syr** [comment] 2022-11-17 16:59
> OpenTelemetry tracing is not experimental anymore. We are preparing a few changes, soon, that will wide the instrumentation support.

OK sounds good. I was referring to the status shown at code.quarkus.io.
Is there a rough roadmap weeks/months/2023 when to expect these extended otel support beeing released?
This info would be very helpful to decide how much effort we put in otel agent fixes.


> The OTel agent instrumentation is too generic. It seems to work but, as I mentioned, it has context propagation issues within the service, specially if you mix imperative and reactive code. The built in Quarkus instrumentation fixes that.

Yes I noticed quite some issues (mainly three points in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7120#issuecomment-1316697698), however it was the only way I see to get quartz and aws sdk auto-instrumented atm.

**Comment by brunobat** [comment] 2022-11-18 09:54
@syr This is the current Roadmap: https://quarkus.io/blog/quarkus-observability-roadmap-2023/

**Comment by syr** [comment] 2022-11-18 10:18
Wow this sounds really promissing and gives a very specific picture. Thanks for sharing @brunobat

**Comment by syr** [comment] 2022-11-18 10:37
Wow this sounds really promissing and gives a very specific picture. Thanks for sharing @brunobat

I would wrap it up here now and close the ticket as we have a perspective for 2023.

For everyone looking for a workaround/fix to get traceId, spanId set in logs when using libs which are not instrumented by quarkus-opentelemetry atm (e.g. quartz, aws sdk) I woud advice to use otel agent, by:

1. updating the MDCs in code, for example in an interceptor (required because of: https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7120#issuecomment-1316782316):
```
        SpanContext spanContext = Span.current().getSpanContext();
        MDC.put("traceId", spanContext.getTraceId());
        MDC.put("spanId", spanContext.getSpanId());
```

2. providing a ThreadContextProvider to get MDCs propagated to logger in mutiny async threads, see:
https://stackoverflow.com/questions/65039035/manual-context-propagation-in-quarkus-native-mode/65040601#65040601
3. To add the quarkus-opentelemetry dependency but disabling it in properties `quarkus.opentelemetry.enabled=false` to get the otel interface for example to create custom spans (e.g. @WithSpan)

**Comment by syr** [comment] 2022-11-21 10:21
Reopened for visibility in Observability roadmap  https://github.com/quarkusio/quarkus/projects/20#card-86193431

**Comment by syr** [comment] 2022-11-28 11:46
@brunobat @Ladicek @mkouba 
Can you please have a look at the last comment in https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/7120#issuecomment-1320524053 
Maybe there is not so much to change to get the MDC beeing updated when ussing jboss logger via io.quarkus.logging.Log

**Comment by famod** [comment] 2022-11-28 18:17
I ran into the same problem, but with the simple scheduler (not quartz).
IMO, https://github.com/quarkusio/quarkus/issues/28552#issuecomment-1277245117 also applies to the simple scheduler.

Shall I open a separate issue?

**Comment by brunobat** [comment] 2022-11-30 18:00
@famod yes please.

**Comment by famod** [comment] 2022-11-30 18:05
@brunobat will do.

For the simple scheduler, I've realized that a workaround seems as easy as adding `@WithSpan` to my `@Scheduled` method. Am I missing something?

**Comment by syr** [comment] 2022-11-30 18:38
@famod  do you use otel agent or is this already working with quarkus-opentelemetry + quarkus-scheduler dependencies?

**Comment by famod** [comment] 2022-12-02 17:40
@syr I'm not using the otel agent explicitly, only quarkus-opentelemetry + quarkus-scheduler dependencies and additionally `io.opentelemetry.instrumentation:opentelemetry-jdbc`.

`@WithSpan` just works, I see JDBC sub-spans for my job executions. 

I created a separate enhancement issue: #29647

**Comment by Kasokaso** [comment] 2023-06-13 12:34
Is there any plan to do something similar when consuming events from Kafka? I believe it would be useful to understand the outcome of processed events.

**Comment by brunobat** [comment] 2023-06-13 12:47
Not sure when this is going to be scheduled.

**Comment by Ladicek** [comment] 2023-07-04 09:18
If everything works with `@WithSpan`, which we treat as an interceptor binding, enabling tracing by default for scheduled methods would amount to a simple annotation transformation I'd say.

**Comment by geoand** [comment] 2023-07-04 09:21
Good point

**Comment by syr** [comment] 2023-07-04 16:22
> IIUC, everything just works with `@WithSpan` correct?
> 
> If so, maybe we just need to add a note in the scheduler documentation instead of doing all the work to enable tracing by default for scheduled methods?

AFAIU it does not work when using custom job classes.
Just tested with version 2.16.7.Final: https://github.com/syr/quarkus-resteasy-postgres/tree/otel_quartz_2.16

However, it's interesting that it works (even without `@WithSpan`) when using @Scheduled like
```
    @Scheduled(every = "10s", identity = "task-job")
    void schedule() {
        Log.info("created task");
    }
```
with quarkus-quartz extension.

However, we need the custom job classes, so cannot use `@Scheduled` on methods :/

**Comment by brunobat** [comment] 2023-07-04 16:58
@syr I see that you are implementing org.quartz.Job and annotating with @WithSpan.
I don't think this will be on a CDI context, therefore the interceptor will not kick in. 
If you implement the job in a bean and then, you call it from inside the execute, it should work.

**Comment by syr** [comment] 2023-07-04 17:24
@brunobat  Yes, like this it's working

```
public class TaskCreateJob implements Job {
    @Override
    public void execute(JobExecutionContext jobExecutionContext) {
        Arc.container().select(TaskCreateJobBean.class).get().execute(jobExecutionContext);
    }
}

@ApplicationScoped
@Unremovable
public class TaskCreateJobBean  {
    @WithSpan
    public void execute(JobExecutionContext jobExecutionContext) {
        Log.info("created task");
    }
}
```





..but it's damn ugly. Was hoping there is a more elegant way.

**Comment by radcortez** [comment] 2023-07-04 22:53
It would require adding proper OTel integration in a `JobListener`. This can be used as a basis: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/quartz-2.0/library/src/main/java/io/opentelemetry/instrumentation/quartz/v2_0

Would you like to try submitting a PR with the proper support? :)

**Comment by syr** [comment] 2023-07-10 14:04
> It would require adding proper OTel integration in a `JobListener`. This can be used as a basis: https://github.com/open-telemetry/opentelemetry-java-instrumentation/tree/main/instrumentation/quartz-2.0/library/src/main/java/io/opentelemetry/instrumentation/quartz/v2_0
> 
> Would you like to try submitting a PR with the proper support? :)

In which repo would this have to be added? opentelemetry-java-instrumentation or quarkus-opentelemetry?

**Comment by geoand** [comment] 2023-07-10 14:13
`quarkus-opentelemetry`

**Comment by mskacelik** [comment] 2023-09-07 09:31
Gonna have a look at this

**Closed** 2023-11-29 17:35 UTC
Labels: kind/bug, area/smallrye, area/scheduler, area/tracing
