### ISSUE TITLE
Uni.onFailure() does not work with RestEasy Reactive client and ClientWebApplicationException in prod and dev modes

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#25440] opened 2022-05-08 18:24 UTC
### Describe the bug

The following code works when the tests are run:

https://github.com/quarkusio/quarkus-quickstarts/blob/development/security-openid-connect-client-quickstart/src/main/java/org/acme/security/openid/connect/client/FrontendResource.java#L34

where a `ClientWebExceptionException` is handle by `Uni.onFailure.recoverWith` - the test needs to assert that `403` is returned from a downstream service.

However in both dev and prod mode that `Uni.onFailure.recoverWith` is not reached and `ClientWebExceptionException` escaped leading to 500 returned to the client, so I had to add an `ExceptionMapper`: https://github.com/quarkusio/quarkus-quickstarts/pull/1108/files

### How to Reproduce?

To run the tests, only do `mvn clean install` in `quickstarts/security-openid-connect-client-quickstarts` - all the tests pass.

Then you can try quarkus:dev, then go to `http://localhost:8080/q/dev/`, choose `OIDC/keycloak`, press on `Login to SinglePageApplication`, then login as `alice:alice`, then choose test with `AccessToken`, use `/frontend/admin-name-with-propagated-token`, and before https://github.com/quarkusio/quarkus-quickstarts/pull/1108/files gets applied you will get `500`, or disable the exception mapper if it is already applied.
Perhaps it can be simpler to avoid Keycloak and have the same test structure and have a downstream `ProtectedResource` throw some exception and try to recover in `FrontendResource`

**Comment by sberyozkin** [comment] 2022-05-08 18:38
If this is done by design, let only the tests see the escaped exceptions, then please feel free to close

**Comment by geoand** [comment] 2022-05-09 07:00
Hey @sberyozkin,

so IIUC when running the tests you get the expected behavior but not in dev mode and prod mode?

**Comment by sberyozkin** [comment] 2022-05-09 09:33
Hey @geoand Exactly, when running the tests the `onFailure().recoverWith()` is executed, in dev and prod - not.

**Comment by geoand** [comment] 2022-05-10 08:55
That's really weird... I'll take a look

**Comment by sberyozkin** [comment] 2022-05-10 09:17
@geoand Hi, yes, I had the tests passing and then went to try it in devmode UI and it failed and then it also failed in prod.

**Comment by geoand** [comment] 2022-05-10 10:24
Unfortunately I don't understand what is going on here... In both cases the control flow reaches https://github.com/quarkusio/quarkus/blob/2.9.0.Final/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/RestClientRequestContext.java#L330 with the proper `ClientWebApplicationException`, but then in the test case the Uni's `recoverWith` is called, why in the case of dev mode it's not...

Perhaps @cescoffier has ideas about this

**Comment by sberyozkin** [comment] 2022-05-10 11:23
@geoand Thanks for confirming it is the case

**Comment by geoand** [comment] 2022-05-10 11:39
Sorry I could not help more...

**Comment by sberyozkin** [comment] 2022-05-10 12:11
Np at all, the demo works with the exception mapper added, so it is not a blocker

**Comment by cescoffier** [comment] 2024-02-09 09:53
First, I have the same behavior in test, dev, and prod. If I remove the exception mapper, I get a 500.

But, I'm not totally sure I understand.

The application gets an authenticated request and then uses a REST client to access a restricted resource. The access is not allowed, so the client throws an Exception (a ClientWebApplicationException where the cause is the `WebApplicationException`).

It seems that the question is: why would this ClientWebApplicationException not be used to produce the 403 response? This is what the mapper does. However, I'm not sure it's the right thing to do. This inner exception (the ClientWebApplicationException) should not be pushed to the client. That's an implementation detail that can actually leak details on the infrastructure. So, responding with a 500 is more correct in this case (IMHO).

Now, if we want to handle this, we can just do the following:

```java
    @Override
    protected void handleUnrecoverableError(Throwable throwable) {     
        if (throwable instanceof ClientWebApplicationException && throwable.getCause() != null) {
              result.completeExceptionally(throwable.getCause());
        } else {
            result.completeExceptionally(throwable);
       }
    }
```

Then, we complete with the `WebApplicationException` which will be used to produce the 403. But again, I'm not sure it's the right thing to do.

**Comment by cescoffier** [comment] 2024-02-16 10:30
I think it got changed. I updated the reproducer and for me it always went in the same branch (so same behavior in prod, test and dev). Now we can discuss if it's the right behavior, but at least it's the same.

**Comment by FroMage** [comment] 2024-02-16 13:07
Which same branch? Did `recoverFrom` get called?

**Comment by cescoffier** [comment] 2024-02-16 18:00
I can't remember. I would need to rebuild my reproducer.

**Comment by FroMage** [comment] 2024-02-20 14:17
Well, if it seemed logical to you, it probably worked, so let's close this?

**Closed by FroMage** 2024-02-20 14:17 UTC
Labels: kind/bug, area/devmode, area/rest-client, area/resteasy-reactive
