### ISSUE TITLE
Quarkus Lambda Application abruptly stops after migrating to 3.2.0.Final in local/dev mode during startup 

### ISSUE THREAD

**Issue by parasjain27031994** [quarkusio/quarkus#34822] opened 2023-07-18 14:57 UTC
### Describe the bug

Hi team, I have observed that when I create an AWS lambda application using version 3.2.0.Final, and modify the starter code to use any AWS resource ( tried with S3 ), the application starts but abruptly stops with below logs :

```
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2023-07-18 19:53:46,425 DEBUG [io.qua.boo.cla.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.MemoryClassPathElement@757f675c to QuarkusClassLoader Quarkus Runtime ClassLoader: DEV restart no:0
2023-07-18 19:53:46,425 DEBUG [io.qua.boo.cla.QuarkusClassLoader] (main) Adding elements io.quarkus.bootstrap.classloading.PathTreeClassPathElement[C:\xxxx\xxxx\code-with-quarkus\target\classes runtime=true resources=6] to QuarkusClassLoader Quarkus Runtime ClassLoader: DEV restart no:0
2023-07-18 19:53:46,808 DEBUG [io.qua.arc.impl] (Quarkus Main Thread) ArC DI container initialized [beans=20, observers=0]
2023-07-18 19:53:47,317 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking system property jakarta.json.provider
2023-07-18 19:53:47,317 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking ServiceLoader
2023-07-18 19:53:47,325 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) ServiceLoader loading Facility used; returning object [org.eclipse.parsson.JsonProviderImpl]
2023-07-18 19:53:47,326 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking system property jakarta.json.provider
2023-07-18 19:53:47,326 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking ServiceLoader
2023-07-18 19:53:47,326 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) ServiceLoader loading Facility used; returning object [org.eclipse.parsson.JsonProviderImpl]
2023-07-18 19:53:47,327 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking system property jakarta.json.provider
2023-07-18 19:53:47,327 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking ServiceLoader
2023-07-18 19:53:47,328 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) ServiceLoader loading Facility used; returning object [org.eclipse.parsson.JsonProviderImpl]
2023-07-18 19:53:47,328 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking system property jakarta.json.provider
2023-07-18 19:53:47,328 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) Checking ServiceLoader
2023-07-18 19:53:47,328 FINE  [jak.jso.spi.JsonProvider] (Quarkus Main Thread) ServiceLoader loading Facility used; returning object [org.eclipse.parsson.JsonProviderImpl]
2023-07-18 19:53:47,330 WARN  [io.qua.run.log.LoggingSetupRecorder] (Quarkus Main Thread) Root log level ALL set below minimum logging level DEBUG, promoting it to DEBUG. Set the build time configuration property 'quarkus.log.min-level' to 'ALL' to avoid this warning
2023-07-18 19:53:47,434 INFO  [io.quarkus] (Quarkus Main Thread) code-with-quarkus 1.0.0-SNAPSHOT on JVM (powered by Quarkus 3.2.0.Final) started in 3.454s. 
2023-07-18 19:53:47,435 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-07-18 19:53:47,435 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [amazon-lambda, amazon-s3, cdi, config-yaml]
2023-07-18 19:53:58,782 WARN  [io.qua.ama.lam.run.AbstractLambdaPollLoop] (Lambda Thread (DEVELOPMENT)) Aborting lambda poll loop: ending dev/test mode
2023-07-18 19:53:58,782 DEBUG [io.qua.run.Application] (Lambda Thread (DEVELOPMENT)) Stopping application
2023-07-18 19:53:58,782 DEBUG [io.qua.run.shu.ShutdownRecorder] (Lambda Thread (DEVELOPMENT)) Attempting to gracefully shutdown.
2023-07-18 19:53:58,787 DEBUG [io.qua.arc.impl] (Lambda Thread (DEVELOPMENT)) ArC DI container shut down
2023-07-18 19:53:58,788 INFO  [io.quarkus] (Lambda Thread (DEVELOPMENT)) code-with-quarkus stopped in 0.005s
```

I have enabled LOG Level as "ALL", still I do not see any errors to debug it.

At the same time, if I downgrade the Quarkus Platform version to 3.1.3.Final, the application starts up successfully in local using dev mode.

### Expected behavior

The application should start successfully using the latest Quarkus version in local using dev mode.

### Actual behavior

The application stops w/o any errors in console.

### How to Reproduce?

1. Clone the following sample [https://github.com/parasjain27031994/quarkus-sample.git](url).
2. In the application.yml file please setup relevant AWS credential provider configurations.
3. Create a sample bucket in S3 and put a sample text file into the bucket.
4. Set the relevant bucketname & key in the environment variable of the lambda function having variable name as **_"S3_BUCKET_NAME"_** & **_"S3_OBJECT_PATH"_** respectively.
5. Run the application by setting profile as dev.

### Output of `java -version`

java version "17.0.4" 2022-07-19 LTS

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by vaibhav170** [comment] 2023-07-19 02:00
There are some other issues where workaround is given, you can try that
https://github.com/quarkusio/quarkus/issues/34801

**Comment by gsmet** [comment] 2023-07-20 16:08
I'm closing this one as a duplicate of https://github.com/quarkusio/quarkus/issues/34801 .

**Closed by gsmet** 2023-07-20 16:08 UTC
Labels: kind/bug, area/devmode, area/amazon-lambda
