### ISSUE TITLE
Windows - Japanese characters / `,;~!@#$%^&()` - dev mode doesn't work

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#9707] opened 2020-06-01 13:46 UTC
Windows - Japanese characters or `,;~!@#$%^&()` - dev mode doesn't work, `Error: Unable to access jarfile ...` is reported. `mvn test` works well.

Steps to reproduce
 - create directory `元気かい` or `,;~!@#$%^&()`
 - create bootstrap app https://quarkus.io/guides/getting-started#bootstrapping-the-project
 - run `mvn quarkus:dev`

```
c:\Users\Rostislav\Downloads\元気かい\getting-started>mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.4.2.Final:dev (default-cli) @ getting-started ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to c:\Users\Rostislav\Downloads\????\getting-started\target\classes
Error: Unable to access jarfile c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  8.122 s
[INFO] Finished at: 2020-06-01T13:57:42+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by rsvoboda** [comment] 2020-06-01 13:54
for the record, `mvn clean test` works

**Comment by geoand** [comment] 2020-06-02 06:24
@rsvoboda can you please re-run with the `-X` maven flag and paste the relevant output?

Thanks

**Comment by rsvoboda** [comment] 2020-06-02 07:20
```
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 1 source file to c:\Users\Rostislav\Downloads\????\getting-started\target\classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[DEBUG] Using javaTool: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\java.EXE
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=276277, ConflictMarker.markTime=206566, ConflictMarker.nodeCount=198, ConflictIdSorter.graphTime=212436, ConflictIdSorter.topsortTime=99063, ConflictIdSorter.conflictIdCount=73, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=3720386, ConflictResolver.conflictItemCount=155, DefaultDependencyCollector.collectTime=38660089, DefaultDependencyCollector.transformTime=4661488}
[DEBUG] Executable jar: c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[DEBUG] Launching JVM with command line: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\java.EXE -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
Error: Unable to access jarfile c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
```

Longer version
```
[DEBUG] Using compiler 'javac'.
[DEBUG] Adding c:\Users\Rostislav\Downloads\????\getting-started\target\generated-sources\annotations to compile source roots:
  c:\Users\Rostislav\Downloads\????\getting-started\src\main\java
[DEBUG] New compile source roots:
  c:\Users\Rostislav\Downloads\????\getting-started\src\main\java
  c:\Users\Rostislav\Downloads\????\getting-started\target\generated-sources\annotations
[DEBUG] CompilerReuseStrategy: reuseCreated
[DEBUG] useIncrementalCompilation enabled
[INFO] Changes detected - recompiling the module!
[DEBUG] Classpath:
[DEBUG]  c:\Users\Rostislav\Downloads\????\getting-started\target\classes
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy\1.4.2.Final\quarkus-resteasy-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-vertx-http\1.4.2.Final\quarkus-vertx-http-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-development-mode-spi\1.4.2.Final\quarkus-development-mode-spi-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\security\quarkus-security\1.1.0.Final\quarkus-security-1.1.0.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\smallrye\reactive\mutiny\0.4.4\mutiny-0.4.4.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\enterprise\jakarta.enterprise.cdi-api\2.0.2\jakarta.enterprise.cdi-api-2.0.2.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\el\jakarta.el-api\3.0.3\jakarta.el-api-3.0.3.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\interceptor\jakarta.interceptor-api\1.2.5\jakarta.interceptor-api-1.2.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-vertx-core\1.4.2.Final\quarkus-vertx-core-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-netty\1.4.2.Final\quarkus-netty-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\vertx\vertx-core\3.8.5\vertx-core-3.8.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-handler-proxy\4.1.45.Final\netty-handler-proxy-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-socks\4.1.45.Final\netty-codec-socks-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-http\4.1.45.Final\netty-codec-http-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-http2\4.1.45.Final\netty-codec-http2-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-resolver-dns\4.1.45.Final\netty-resolver-dns-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-dns\4.1.45.Final\netty-codec-dns-4.1.45.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.10.3\jackson-core-2.10.3.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\vertx\vertx-web\3.8.5\vertx-web-3.8.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\vertx\vertx-web-common\3.8.5\vertx-web-common-3.8.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\vertx\vertx-auth-common\3.8.5\vertx-auth-common-3.8.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\vertx\vertx-bridge-common\3.8.5\vertx-bridge-common-3.8.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy-server-common\1.4.2.Final\quarkus-resteasy-server-common-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-arc\1.4.2.Final\quarkus-arc-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\arc\arc\1.4.2.Final\arc-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta.transaction-api-1.3.3.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\eclipse\microprofile\context-propagation\microprofile-context-propagation-api\1.0.1\microprofile-context-propagation-api-1.0.1.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy-common\1.4.2.Final\quarkus-resteasy-common-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\resteasy\resteasy-core\4.5.3.Final\resteasy-core-4.5.3.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\spec\javax\ws\rs\jboss-jaxrs-api_2.1_spec\2.0.1.Final\jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\spec\javax\xml\bind\jboss-jaxb-api_2.3_spec\2.0.0.Final\jboss-jaxb-api_2.3_spec-2.0.0.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\resteasy\resteasy-core-spi\4.5.3.Final\resteasy-core-spi-4.5.3.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\eclipse\microprofile\config\microprofile-config-api\1.4\microprofile-config-api-1.4.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\com\sun\activation\jakarta.activation\1.2.1\jakarta.activation-1.2.1.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-core\1.4.2.Final\quarkus-core-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\jakarta\inject\jakarta.inject-api\1.0\jakarta.inject-api-1.0.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-ide-launcher\1.4.2.Final\quarkus-ide-launcher-1.4.2.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\smallrye\config\smallrye-config\1.7.0\smallrye-config-1.7.0.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\io\smallrye\config\smallrye-config-common\1.7.0\smallrye-config-common-1.7.0.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\logmanager\jboss-logmanager-embedded\1.0.4\jboss-logmanager-embedded-1.0.4.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\logging\jboss-logging-annotations\2.1.0.Final\jboss-logging-annotations-2.1.0.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\threads\jboss-threads\3.1.1.Final\jboss-threads-3.1.1.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\jboss\slf4j\slf4j-jboss-logging\1.2.0.Final\slf4j-jboss-logging-1.2.0.Final.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\graalvm\sdk\graal-sdk\19.3.1\graal-sdk-19.3.1.jar
[DEBUG]  C:\Users\Rostislav\.m2\repository\org\wildfly\common\wildfly-common\1.5.4.Final-format-001\wildfly-common-1.5.4.Final-format-001.jar
[DEBUG] Source roots:
[DEBUG]  c:\Users\Rostislav\Downloads\????\getting-started\src\main\java
[DEBUG]  c:\Users\Rostislav\Downloads\????\getting-started\target\generated-sources\annotations
[DEBUG] Command line options:
[DEBUG] -d c:\Users\Rostislav\Downloads\????\getting-started\target\classes -classpath c:\Users\Rostislav\Downloads\????\getting-started\target\classes;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy\1.4.2.Final\quarkus-resteasy-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-vertx-http\1.4.2.Final\quarkus-vertx-http-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-development-mode-spi\1.4.2.Final\quarkus-development-mode-spi-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\security\quarkus-security\1.1.0.Final\quarkus-security-1.1.0.Final.jar;C:\Users\Rostislav\.m2\repository\io\smallrye\reactive\mutiny\0.4.4\mutiny-0.4.4.jar;C:\Users\Rostislav\.m2\repository\org\reactivestreams\reactive-streams\1.0.3\reactive-streams-1.0.3.jar;C:\Users\Rostislav\.m2\repository\jakarta\enterprise\jakarta.enterprise.cdi-api\2.0.2\jakarta.enterprise.cdi-api-2.0.2.jar;C:\Users\Rostislav\.m2\repository\jakarta\el\jakarta.el-api\3.0.3\jakarta.el-api-3.0.3.jar;C:\Users\Rostislav\.m2\repository\jakarta\interceptor\jakarta.interceptor-api\1.2.5\jakarta.interceptor-api-1.2.5.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-vertx-core\1.4.2.Final\quarkus-vertx-core-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-netty\1.4.2.Final\quarkus-netty-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-codec\4.1.45.Final\netty-codec-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-handler\4.1.45.Final\netty-handler-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\vertx\vertx-core\3.8.5\vertx-core-3.8.5.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-common\4.1.45.Final\netty-common-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-buffer\4.1.45.Final\netty-buffer-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-transport\4.1.45.Final\netty-transport-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-handler-proxy\4.1.45.Final\netty-handler-proxy-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-socks\4.1.45.Final\netty-codec-socks-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-http\4.1.45.Final\netty-codec-http-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-http2\4.1.45.Final\netty-codec-http2-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-resolver\4.1.45.Final\netty-resolver-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-resolver-dns\4.1.45.Final\netty-resolver-dns-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\io\netty\netty-codec-dns\4.1.45.Final\netty-codec-dns-4.1.45.Final.jar;C:\Users\Rostislav\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.10.3\jackson-core-2.10.3.jar;C:\Users\Rostislav\.m2\repository\io\vertx\vertx-web\3.8.5\vertx-web-3.8.5.jar;C:\Users\Rostislav\.m2\repository\io\vertx\vertx-web-common\3.8.5\vertx-web-common-3.8.5.jar;C:\Users\Rostislav\.m2\repository\io\vertx\vertx-auth-common\3.8.5\vertx-auth-common-3.8.5.jar;C:\Users\Rostislav\.m2\repository\io\vertx\vertx-bridge-common\3.8.5\vertx-bridge-common-3.8.5.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy-server-common\1.4.2.Final\quarkus-resteasy-server-common-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-arc\1.4.2.Final\quarkus-arc-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\arc\arc\1.4.2.Final\arc-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\jakarta\transaction\jakarta.transaction-api\1.3.3\jakarta.transaction-api-1.3.3.jar;C:\Users\Rostislav\.m2\repository\org\eclipse\microprofile\context-propagation\microprofile-context-propagation-api\1.0.1\microprofile-context-propagation-api-1.0.1.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-resteasy-common\1.4.2.Final\quarkus-resteasy-common-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\org\jboss\resteasy\resteasy-core\4.5.3.Final\resteasy-core-4.5.3.Final.jar;C:\Users\Rostislav\.m2\repository\org\jboss\spec\javax\ws\rs\jboss-jaxrs-api_2.1_spec\2.0.1.Final\jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar;C:\Users\Rostislav\.m2\repository\org\jboss\spec\javax\xml\bind\jboss-jaxb-api_2.3_spec\2.0.0.Final\jboss-jaxb-api_2.3_spec-2.0.0.Final.jar;C:\Users\Rostislav\.m2\repository\org\jboss\resteasy\resteasy-core-spi\4.5.3.Final\resteasy-core-spi-4.5.3.Final.jar;C:\Users\Rostislav\.m2\repository\org\eclipse\microprofile\config\microprofile-config-api\1.4\microprofile-config-api-1.4.jar;C:\Users\Rostislav\.m2\repository\com\sun\activation\jakarta.activation\1.2.1\jakarta.activation-1.2.1.jar;C:\Users\Rostislav\.m2\repository\jakarta\validation\jakarta.validation-api\2.0.2\jakarta.validation-api-2.0.2.jar;C:\Users\Rostislav\.m2\repository\org\jboss\logging\jboss-logging\3.3.2.Final\jboss-logging-3.3.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-core\1.4.2.Final\quarkus-core-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\jakarta\annotation\jakarta.annotation-api\1.3.5\jakarta.annotation-api-1.3.5.jar;C:\Users\Rostislav\.m2\repository\jakarta\inject\jakarta.inject-api\1.0\jakarta.inject-api-1.0.jar;C:\Users\Rostislav\.m2\repository\io\quarkus\quarkus-ide-launcher\1.4.2.Final\quarkus-ide-launcher-1.4.2.Final.jar;C:\Users\Rostislav\.m2\repository\io\smallrye\config\smallrye-config\1.7.0\smallrye-config-1.7.0.jar;C:\Users\Rostislav\.m2\repository\io\smallrye\config\smallrye-config-common\1.7.0\smallrye-config-common-1.7.0.jar;C:\Users\Rostislav\.m2\repository\org\jboss\logmanager\jboss-logmanager-embedded\1.0.4\jboss-logmanager-embedded-1.0.4.jar;C:\Users\Rostislav\.m2\repository\org\jboss\logging\jboss-logging-annotations\2.1.0.Final\jboss-logging-annotations-2.1.0.Final.jar;C:\Users\Rostislav\.m2\repository\org\jboss\threads\jboss-threads\3.1.1.Final\jboss-threads-3.1.1.Final.jar;C:\Users\Rostislav\.m2\repository\org\slf4j\slf4j-api\1.7.30\slf4j-api-1.7.30.jar;C:\Users\Rostislav\.m2\repository\org\jboss\slf4j\slf4j-jboss-logging\1.2.0.Final\slf4j-jboss-logging-1.2.0.Final.jar;C:\Users\Rostislav\.m2\repository\org\graalvm\sdk\graal-sdk\19.3.1\graal-sdk-19.3.1.jar;C:\Users\Rostislav\.m2\repository\org\wildfly\common\wildfly-common\1.5.4.Final-format-001\wildfly-common-1.5.4.Final-format-001.jar; -sourcepath c:\Users\Rostislav\Downloads\????\getting-started\src\main\java;c:\Users\Rostislav\Downloads\????\getting-started\target\generated-sources\annotations; -s c:\Users\Rostislav\Downloads\????\getting-started\target\generated-sources\annotations -g -parameters -nowarn -target 11 -source 11 -encoding UTF-8
[DEBUG] incrementalBuildHelper#beforeRebuildExecution
[INFO] Compiling 1 source file to c:\Users\Rostislav\Downloads\????\getting-started\target\classes
[DEBUG] incrementalBuildHelper#afterRebuildExecution
[DEBUG] Using javaTool: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\java.EXE
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=276277, ConflictMarker.markTime=206566, ConflictMarker.nodeCount=198, ConflictIdSorter.graphTime=212436, ConflictIdSorter.topsortTime=99063, ConflictIdSorter.conflictIdCount=73, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=3720386, ConflictResolver.conflictItemCount=155, DefaultDependencyCollector.collectTime=38660089, DefaultDependencyCollector.transformTime=4661488}
[DEBUG] Executable jar: c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[DEBUG] Launching JVM with command line: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\java.EXE -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
Error: Unable to access jarfile c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.077 s
[INFO] Finished at: 2020-06-02T08:48:16+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by geoand** [comment] 2020-06-02 07:30
Thanks a lot @rsvoboda.

```
[DEBUG] Launching JVM with command line: C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0\bin\java.EXE -XX:TieredStopAtLevel=1 -Xverify:none -Xdebug -Xrunjdwp:transport=dt_socket,address=0.0.0.0:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
``` 

is the line I wanted to see

**Comment by geoand** [comment] 2020-06-02 09:06
I tried to reproduce this by creating a directory with Greek characters on Linux and wasn't able to - it worked properly :(

**Comment by jaikiran** [comment] 2020-06-03 13:23
> C:\Program Files\GraalVM\graalvm-ce-java11-20.0.0

@rsvoboda, would you be able to try this against a "regular" Java 11 JDK (one like from AdoptOpenJDK)? I gave this a try against 11.0.7 of OpenJDK and both mvn clean install and even mvn quarkus:dev, all went fine (including invoking on the endpoint from a browser during quarkus:dev). I used the exact same instructions (including using the same Japenese characters for the directory).

I haven't tried this with a GraalVM based JDK and I don't think I will be able to on the setup, that I borrowed for this testing. If this turns out to be GraalVM JDK specific issue, we can then raise it in their repo.

**Comment by rsvoboda** [comment] 2020-06-03 14:01
I have 11.0.5 and it fails for me, running from cmd.
```
c:\Users\Rostislav\Downloads\元気かい\getting-started>mvn -V quarkus:dev
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: c:\Users\Rostislav\Downloads\apache-maven-3.6.3\bin\..
Java version: 11.0.5, vendor: Oracle Corporation, runtime: c:\Program Files\Java\jdk-11.0.5
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.4.2.Final:dev (default-cli) @ getting-started ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to c:\Users\Rostislav\Downloads\????\getting-started\target\classes
Error: Unable to access jarfile c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  6.379 s
[INFO] Finished at: 2020-06-03T15:58:39+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by rsvoboda** [comment] 2020-06-03 14:25
And AdoptOpenJDK
```
c:\Users\Rostislav\Downloads\元気かい\getting-started>set JAVA_HOME=c:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot

c:\Users\Rostislav\Downloads\元気かい\getting-started>mvn -V quarkus:dev
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: c:\Users\Rostislav\Downloads\apache-maven-3.6.3\bin\..
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: c:\Program Files\AdoptOpenJDK\jdk-11.0.7.10-hotspot
Default locale: cs_CZ, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
[INFO] Scanning for projects...
[INFO]
[INFO] ----------------------< org.acme:getting-started >----------------------
[INFO] Building getting-started 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.4.2.Final:dev (default-cli) @ getting-started ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to c:\Users\Rostislav\Downloads\????\getting-started\target\classes
Error: Unable to access jarfile c:\Users\Rostislav\Downloads\????\getting-started\target\getting-started-dev.jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.289 s
[INFO] Finished at: 2020-06-03T16:23:45+02:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jaikiran** [comment] 2020-06-04 01:51
Would you be able to attach the build log from a run of `mvn -X clean quarkus:dev`? No matter what I try (including setting the locale to `cs_CZ`, I can't reproduce this). Please also use `1.5.0.Final`, now that it has been released (I don't expect this issue to be a result of `1.4.2.Final` vs `1.5.0.Final` usage, but it helps compare the code in IDE).

**Comment by rsvoboda** [comment] 2020-06-11 09:33
I was able to hit this issues using `,;~!@#$%^&()` as the directory name, so no special national characters are needed.

With Quarkus 1.5.0.Final I see:
```
Error: Could not find or load main class io.quarkus.deployment.dev.DevModeMain
Caused by: java.lang.ClassNotFoundException: io.quarkus.deployment.dev.DevModeMain
```
Running `mvn quarkus:dev` from `c:\Users\Rostislav\Downloads\,;~!@#$%^&()\getting-started>`.
`mvn test` works well and tests are passing.

**Comment by cescoffier** [comment] 2021-01-11 06:51
@rsvoboda should this one be closed?

**Comment by rsvoboda** [comment] 2021-01-11 07:53
I should double check, putting on my TODO list.

**Comment by rsvoboda** [comment] 2021-01-11 10:47
I still see it, tried with Quarkus 1.10.5.Final and 1.11.0.CR1
Used `,;~!@#$%^&()` and `元気かい` as the root directory for getting-started.

`mvn test` works, `mvn quarkus:dev` does not work.

**Comment by jaikiran** [comment] 2021-01-16 12:29
Hello @rsvoboda, is this only on Windows or even Linux? I haven't checked on this in a long time and I don't think I will have access to Windows anytime in near future.

**Comment by rsvoboda** [comment] 2021-01-18 07:33
Windows only

**Comment by Sgitario** [comment] 2021-01-27 06:50
Note that this is also not working for diacritics characters like ěščřžýáíéůú in DEV mode.

**Comment by gastaldi** [comment] 2024-08-27 22:43
That's a file encoding problem and it happens in other tools too (JBang for example):

```bash
C:\temp\元気かい>jbang run run.java
[jbang] Building jar for run.java...
error: file not found: C:\temp\元気�?��?�\run.java
Usage: javac <options> <source files>
use --help for a list of possible options
[jbang] [ERROR] Error during compile
[jbang] Run with --verbose for more details
```

I'm trying to bypass this by running `set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF-8` before but I don't see a proper solution

**Comment by gastaldi** [comment] 2024-08-27 23:55
Installing the latest Eclipse Temurin release solves the problem. This is a JDK bug.

```bash
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode, sharing)
```

Closing as this is not a bug in Quarkus

**Closed by gastaldi** 2024-08-27 23:55 UTC
Labels: kind/bug, area/devmode

**Comment by rsvoboda** [comment] 2024-09-01 15:01
> Installing the latest Eclipse Temurin release solves the problem. This is a JDK bug.

This is true for `元気かい` named directory, but `,;~@#$%^&()` still has issue in dev mode (building and running the app works).

**Comment by rsvoboda** [comment] 2024-09-01 15:03
I would limit this issue to Japanese characters and create new issue for the second case. wdyt @gastaldi ?

**Comment by gastaldi** [comment] 2024-09-01 17:06
@rsvoboda sounds good, if you think it's worth it 😉
