### ISSUE TITLE
Quarkus testing with `@ParameterizedTest` broken with Java 17 + 18 (xstream)

### ISSUE THREAD

**Issue by snazy** [quarkusio/quarkus#24492] opened 2022-03-23 09:32 UTC
### Describe the bug

The following exception happens during tests using `@QuarkusTest` with Java 17 + 18.

The failing test case is a `@ParameterizedTest` with a `@MethodSource` that returns a `Stream` of objects that contain `List` instances created by `Arrays.asList()` - hence the `java.util.Collections$UnmodifiableCollection`.

Looks like it's not a direct fault of Quarkus, but xsteam not able to deal with those objects.

Adding `--add-opens=java.base/java.util=ALL-UNNAMED` does not help.

```
com.thoughtworks.xstream.converters.ConversionException: 
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.Collections$UnmodifiableRandomAccessList
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field private static final long java.util.Collections$UnmodifiableCollection.serialVersionUID accessible: module java.base does not "opens java.util" to unnamed module @7f1dd5e7
-------------------------------
	at com.thoughtworks.xstream.core.DefaultConverterLookup.lookupConverterForType(DefaultConverterLookup.java:88)
	at com.thoughtworks.xstream.XStream$1.lookupConverterForType(XStream.java:478)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:49)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller$1.convertAnother(AbstractReferenceMarshaller.java:83)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshallField(AbstractReflectionConverter.java:270)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$2.writeField(AbstractReflectionConverter.java:174)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.doMarshal(AbstractReflectionConverter.java:262)
	at com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter.marshal(AbstractReflectionConverter.java:90)
	at com.thoughtworks.xstream.core.AbstractReferenceMarshaller.convert(AbstractReferenceMarshaller.java:68)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:59)
	at com.thoughtworks.xstream.core.TreeMarshaller.convertAnother(TreeMarshaller.java:44)
	at com.thoughtworks.xstream.core.TreeMarshaller.start(TreeMarshaller.java:83)
	at com.thoughtworks.xstream.core.AbstractTreeMarshallingStrategy.marshal(AbstractTreeMarshallingStrategy.java:37)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1266)
	at com.thoughtworks.xstream.XStream.marshal(XStream.java:1255)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1228)
	at com.thoughtworks.xstream.XStream.toXML(XStream.java:1215)
	at io.quarkus.test.junit.internal.XStreamDeepClone.doClone(XStreamDeepClone.java:49)
	at io.quarkus.test.junit.internal.XStreamDeepClone.clone(XStreamDeepClone.java:35)
	at io.quarkus.test.junit.internal.SerializationWithXStreamFallbackDeepClone.clone(SerializationWithXStreamFallbackDeepClone.java:33)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:981)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:896)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestTemplateMethod(QuarkusTestExtension.java:856)
```

### Output of `java -version`

17.0.2
18

### Quarkus version or git rev

2.7.5.Final

**Comment by gsmet** [comment] 2022-03-23 19:23
Could you prepare a small reproducer? We run our tests with JDK 17 and 18 so there might be something specific to your project.

**Comment by geoand** [comment] 2022-03-23 19:30
Something tells me there is some extra testing extension coming into play...

Like @gsmet says, we'll need a reproducer

**Comment by snazy** [comment] 2022-03-24 07:35
Will put a reproducer together (or facepalm and close this issue, if one of our extensions is causing this w/ Java 17/18)

**Comment by snazy** [comment] 2022-03-25 14:53
The extension's `org.junit.jupiter.params.ParameterizedTestExtension` from `org.junit.jupiter:junit-jupiter-params`

**Comment by snazy** [comment] 2022-03-25 18:40
Haven't checked Guava's collections though.

**Comment by famod** [comment] 2022-03-25 23:12
This reminds me a lot of https://github.com/x-stream/xstream/issues/253 where I also documented a (not so pretty) alternate workaround.

So this is an upstream issue we cannot really do anything about, so I'm closing this.
Once (if ever) x-stream 1.5 sees the light of day, we'll look into integrating it.

> Adding `--add-opens=java.base/java.util=ALL-UNNAMED` does not help.

I think you've got a typo there as the following makes the test pass (via surefire `argLine`):
```
--add-opens java.base/java.util=ALL-UNNAMED
```

(more specifically `mvn test -f integration-tests/test-extension -Dtest=ParamsTest -Dsurefire.argLine.additional='--add-opens java.base/java.util=ALL-UNNAMED'`, but `surefire.argLine.additional` only exists in Quarkus CI/local buidl)

**Comment by famod** [comment] 2022-03-25 23:13
PS: Anyway, thanks for reporting!

**Closed by famod** 2022-03-25 23:12 UTC
Labels: kind/bug, area/testing, needs-reproducer

**Comment by gsmet** [comment] 2022-03-25 23:49
Does it work with List.of()? Because if so, it’s probably one people will use with Java 17+.

**Comment by famod** [comment] 2022-03-25 23:59
No, unfortunately: https://github.com/x-stream/xstream/issues/253#issuecomment-835877790

**Comment by snazy** [comment] 2022-03-26 07:09
> This reminds me a lot of https://github.com/x-stream/xstream/issues/253

That's a kinda depressing issue to read :(

> I think you've got a typo there (add-opens)

Well, not a typo (as I've added it to .mvn/jvm.config + .mvn/mvnd.properites). It's been a mistake to add it to the Maven JVM - should have added it to the JVM running the tests via surefire (my bad).

I'll probably just add the two `--add-opens` to Quarkus surefire/failsafe configs.

**Comment by xtaixe** [comment] 2022-04-20 08:15
Hi.

I'm still seeing this on `2.8.1.Final` when the `@MethodSource`returns a `Stream<Map.Entry<String, String>>`.  The error is:

```
com.thoughtworks.xstream.converters.ConversionException: 
No converter available
---- Debugging information ----
message             : No converter available
type                : java.util.KeyValueHolder
converter           : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
message[1]          : Unable to make field final java.lang.Object java.util.KeyValueHolder.key accessible: module java.base does not "opens java.util" to unnamed module @7219ec67
-------------------------------
```

Let me know if you want me to create a new issue. cc @geoand

**Comment by geoand** [comment] 2022-04-20 08:19
Please do
