### ISSUE TITLE
Support multiple application.properties files

### ISSUE THREAD

**Issue by jfrantzius** [quarkusio/quarkus#12766] opened 2020-10-16 21:49 UTC
**Description**
Currently Quarkus supports only a single `application.properties` file in the classpath. More exactly, if there are multiple such files in the classpath, an arbitrarily chosen one will be loaded, leading to confusion as the restriction is not obvious.

Having to use a single configuration file has a number of severe drawbacks when used in a Maven multi-module project. It requires having a shared submodule that all other modules have a dependency on. During test execution, however, all submodules then also need to have all dependencies required to instantiate all configured objects for injection, as instantiation seems to happen eagerly (and is not deferred to actual injection). It's not possible to aggregate the required dependencies as test dependencies only in the shared module, as test scope isn't transitive, see https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html#Dependency_Scope.

Eclipse Microprofile already supports having multiple `microprofile-config.properties` files in the classpath, allowing to aggregate configuration from multiple files. So using `microprofile-config.properties` is an effective workaround, but not at all obvious from the documentation. For the sake of developer joy, it would be a nice improvement if this was supported for `application.properties` (or YAML) as well.

(This is not a duplicate of https://github.com/quarkusio/quarkus/issues/6810 , as that instead asks for having one file per profile)

**Implementation ideas**
Currently the `io.quarkus.runtime.configuration.ConfigUtils.configBuilder(boolean, boolean)` looks only for one `application.properties` file (in file system or classpath), effectively doing classpath gambling if there are multiple present in classpath. Maybe it could instead iterate what it finds for that name, in the same way as or even reusing `io.quarkus.runtime.configuration.QuarkusPropertiesConfigSourceProvider.QuarkusPropertiesConfigSourceProvider(String, boolean, ClassLoader)`. This iterates over the result of `classLoader.getResources(propertyFileName)`.

**Comment by radcortez** [comment] 2020-10-20 18:59
I think we may be able to support this.

Remember that if we do this, this should only be applied to the runtime build, since we don't want to pollute the CL at build time. We may find resources that may not be available at runtime.

**Comment by radcortez** [comment] 2020-10-20 19:50
This is actually a duplicate of #9869. Closing this one and following up there.

**Closed by radcortez** 2020-10-20 19:50 UTC
Labels: area/config, kind/enhancement
