### ISSUE TITLE
Error running Panache Reactive Test with IntelliJ JUnit template

### ISSUE THREAD

**Issue by hernael** [quarkusio/quarkus#15131] opened 2021-02-16 22:50 UTC
**Describe the bug**
Since 1.11.x Quarkus version, the Test in IntelliJ fail.
In 1.10.5 work fine.

**Actual behavior**
when run Panache Reactive Test with IntelliJ JUnit template throws the following error:

```
java.lang.AssertionError: This needs to be run on the Vert.x event loop

	at org.hibernate.reactive.session.impl.ReactiveSessionImpl.<init>(ReactiveSessionImpl.java:129)
	at org.hibernate.reactive.mutiny.impl.MutinySessionFactoryImpl.openSession(MutinySessionFactoryImpl.java:67)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer.createMutinySession(ReactiveSessionProducer.java:32)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:259)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.create(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_Bean.zig:297)
	at io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:68)
	at io.quarkus.arc.impl.ClientProxies.getDelegate(ClientProxies.java:33)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.arc$delegate(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:61)
	at io.quarkus.hibernate.reactive.runtime.ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.createQuery(ReactiveSessionProducer_ProducerMethod_createMutinySession_1321d110ee9e92bda147899150401e0a136779c7_ClientProxy.zig:1129)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.createBaseQuery(CommonPanacheQueryImpl.java:299)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.createQuery(CommonPanacheQueryImpl.java:247)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.list(CommonPanacheQueryImpl.java:218)
	at io.quarkus.hibernate.reactive.panache.common.runtime.CommonPanacheQueryImpl.stream(CommonPanacheQueryImpl.java:226)
	at io.quarkus.hibernate.reactive.panache.runtime.PanacheQueryImpl.stream(PanacheQueryImpl.java:154)
	at io.quarkus.hibernate.reactive.panache.runtime.JpaOperations.stream(JpaOperations.java:28)
	at io.quarkus.hibernate.reactive.panache.runtime.JpaOperations.stream(JpaOperations.java:11)
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.streamAll(AbstractJpaOperations.java:240)
	at com.demo.repository.reactive.panache.CurrencyPanacheRepository.streamAll(CurrencyPanacheRepository.java)
	at com.demo.repository.reactive.panache.CurrencyPanacheRepository.getAll(CurrencyPanacheRepository.java:35)
	at com.demo.repository.reactive.panache.CurrencyPanacheRepository_ClientProxy.getAll(CurrencyPanacheRepository_ClientProxy.zig:1208)
	at com.demo.repository.reactive.panache.CurrencyRatePanacheRepositoryTest.insert(CurrencyRatePanacheRepositoryTest.java:85)
	at com.demo.repository.reactive.panache.CurrencyRatePanacheRepositoryTest.basicCRUD(CurrencyRatePanacheRepositoryTest.java:36)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:807)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:714)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:210)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:143)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:129)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:127)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:75)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:114)

2021-02-16 17:49:04,936 INFO  [io.quarkus] (main) currency stopped in 0.023s
```

**To Reproduce**
Just create a test to a Reactive Panache Repository and run it with IntelliJ JUnit template

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux 5.3.18-lp152.60-default x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`:  OpenJDK 64-Bit Server VM Corretto-11.0.10.9.1 (build 11.0.10+9-LTS, mixed mode)
 - Quarkus version or git rev: 1.11.x
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`):  3.6.3

**Comment by FroMage** [comment] 2021-02-17 10:11
This must be related to the changes in HR where we mandate access from the IO thread, but I don't understand why this would have passed CI, there's no reason why running from the CLI should behave differently to running from the IDE.

**Comment by geoand** [comment] 2021-02-17 10:57
I just tried this on our `hibernate-reactive-quickstart` and it worked just fine.

Can you share a sample project that exhibits the problematic behavior please?

**Comment by FroMage** [comment] 2021-02-17 10:58
The quickstart runs from an IO thread, no? This is when running directly from a `@Test` method, no?

**Comment by geoand** [comment] 2021-02-17 11:01
I guess (by just looking at the stacktrace), but that is why I would like to have a project that exhibits the behavior.

**Comment by FroMage** [comment] 2021-02-17 11:02
Oh, I thought this was our CI tests.

OK, then I bet this is becaue our CI tests run this in a transaction and then block waiting for them, which makes them run on the IO thread, because we can do this for transactions.

**Comment by geoand** [comment] 2021-02-17 11:04
Right, that makes sense.

If we have an example of what OP is trying to do, at the very least we need to document what the expected behavior is

**Comment by hernael** [comment] 2021-02-17 14:13
Hi, please note here:

https://github.com/hernael/reactive-demo

I create a test call RepositoryTest with 2 methods.
Both methods fail in IntellIJ 2020.3

**Comment by FroMage** [comment] 2021-02-17 14:15
Yes, that's it. Can you try using `Panache.withTransaction()` around the call in your test?

**Comment by hernael** [comment] 2021-02-17 14:25
I just tried like this:
```
    @Test
    void getFirstBlocking() {
        var response = Panache.withTransaction(() -> repository.getFirst()).await().indefinitely();

        assertNotNull(response);
    }

    @Test
    void getFirst() {
        var response = Panache.withTransaction(() -> repository.getFirst());

        UniAssertSubscriber<Entity> subscriber = response
                .subscribe().withSubscriber(UniAssertSubscriber.create());

        subscriber.assertCompleted().assertTerminated();
    }
```

but they still keep failing

**Comment by FroMage** [comment] 2021-02-17 14:27
`getFirst` will likely fail because it's not waiting. but `getFirstBlocking` should work…

**Comment by hernael** [comment] 2021-02-17 14:31
running them both together in Intellij fails, or running one by one also fail :(

**Comment by geoand** [comment] 2021-02-18 11:40
Can you provide the docker run you are using to start postgresql so we can try your example?

**Comment by geoand** [comment] 2021-02-18 15:32
The issue is that anyone on the team has to run plenty of such examples everyday, so spending time trying to figure out how to run each different one, is not a very productive use of our time.
I spent a couple minutes on this and when second attempt at running  didn't work, that was enough to ask for a docker command.
I don't care about the data, what I care about is having a database up that has the necessary tables

**Comment by hernael** [comment] 2021-02-18 15:38
sorry but i can't provide what you request

**Comment by luce98** [comment] 2021-04-06 14:57
I'm experiencing the same issue: some tests are failing after migrating from 10.5 to 11.
Does someone already have a workaround?

**Comment by hernael** [comment] 2021-04-06 15:23
I have not migrated from version 1.10.5 to any later version (1.11.x, 1.12.x or 1.13.0) because I have problems with the test and reactive panache (#14709) in those versions :(

**Comment by luce98** [comment] 2021-04-12 12:30
Hey everyone, I created a small demo to reproduce the issue; there is also the script to create the DB container, you just need to run that and then run the tests. Hope this can help!
You can find it here: https://github.com/avimedical/quarkus-reactive-demo

**Comment by FroMage** [comment] 2021-04-14 15:05
I'm trying to see if I can reproduce this in our ITs, but I'm running into this issue @DavideD: 

```
Caused by: org.eclipse.aether.resolution.DependencyResolutionException: Could not find artifact org.hibernate.reactive:hibernate-reactive-core:jar:1.0.0.CR1.Vertx4 in central (https://repo.maven.apache.org/maven2)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveDependencies(DefaultRepositorySystem.java:357)
	at io.quarkus.bootstrap.resolver.maven.MavenArtifactResolver.resolveManagedDependencies(MavenArtifactResolver.java:269)
	... 46 more
```

Any idea how I can work around this?

**Comment by FroMage** [comment] 2021-04-14 15:06
It appears that if `Session.withTransaction` allows us to get scheduled on the IO thread, but getting a session requires the caller to be in an IO thread, we have a bootstrapping problem.

**Comment by DavideD** [comment] 2021-04-14 15:49
1..0.0.CR2 should be available on Maven Central now

**Comment by DavideD** [comment] 2021-04-14 15:50
Although, it should already fixed: https://github.com/quarkusio/quarkus/pull/16506

**Comment by FroMage** [comment] 2021-04-15 08:41
Thanks!

**Comment by FroMage** [comment] 2021-04-15 08:50
This is worse. Turns out the HR/Panache IT tests don't appear to even run ATM. I wonder why CI doesn't run them?

**Comment by gwenneg** [comment] 2021-04-21 12:10
I have the same problem but without Panache. Running a query using `Mutiny.Session` from a `@Test` method fails in IntelliJ 2021.1 with Quarkus 1.13.2.Final. Everything's fine if the test is run without IntelliJ.

**Comment by geoand** [comment] 2021-05-11 11:53
That's very interesting, thanks!

**Comment by geoand** [comment] 2021-07-26 10:53
This has likely been fixed in https://github.com/quarkusio/quarkus/pull/17728 which is part of `2.1.0.CR1`. Can you please check so we can close the issue if so, or else see what else needs to be done?

**Comment by DavideD** [comment] 2021-07-29 10:50
I've just tested this with the latest snapshots and it seems to work without errors now.

I had to change a couple of tests from:
```
        subscriber.assertCompleted().assertTerminated();
```
to
```
        subscriber.awaitItem().assertCompleted().assertTerminated();
```

But the Vert.x exception doesn't occur anymore

**Comment by geoand** [comment] 2021-07-29 10:56
Thanks for checking!

I'll close this based on that information. If this comes up again, feel free to reopen

**Closed by geoand** 2021-07-29 10:56 UTC
Labels: area/panache, kind/bug
