### ISSUE TITLE
Warning about failing to index Spring class on reload

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#42237] opened 2024-07-31 10:13 UTC
### Describe the bug

I have an app, which uses several Spring extensions. When I run in a Dev Mode and do a reload (manually or a by adding a new file) there is a warning in a logs.

This warning emerged after update from 3.11.0 to 3.12.3

### Expected behavior

No warnings  during reload

### Actual behavior

```
-07-31 12:07:06,391 INFO  [io.qua.dep.dev.RuntimeUpdatesProcessor] (Aesh InputStream Reader) Restarting as requested by the user.
2024-07-31 12:07:06,400 INFO  [io.quarkus] (Quarkus Main Thread) app stopped in 0.008s
<...>
2024-07-31 12:07:06,530 WARN  [io.qua.arc.pro.BeanArchives] (build-12) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for app-1.0.0-SNAPSHOT@2d2d94bf

```

### How to Reproduce?

1. Create an app:
```
 mvn io.quarkus.platform:quarkus-maven-plugin:3.13.0:create -DprojectGroupId=my-groupId -DprojectArtifactId=app -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.13.0 -Dextensions=quarkus-rest,spring-boot-properties,spring-di,spring-security,spring-web && cd app # spring-data-jpa also seem to be affected
```
2. Run in a dev mode: `mvn clean quarkus:dev`
3. Wait for the app to start and reload it by pressing `s` or by adding a new class

### Output of `uname -a` or `ver`

6.7.3-200.fc39.x86_64

### Output of `java -version`

Java version: 21.0.1, vendor: Eclipse Adoptium

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

**Comment by fedinskiy** [comment] 2024-07-31 10:18
It seems, that 3.12.0 is the first version which is affected, since 3.11.3 is not

**Comment by geoand** [comment] 2024-08-02 10:58
Hm...

When I start the application (before any live reload, I see):

```
2024-08-02 13:57:05,839 WARN  [io.qua.agr.dep.AgroalProcessor] (build-18) The Agroal dependency is present but no JDBC datasources have been defined.
2024-08-02 13:57:05,945 WARN  [io.qua.hib.orm.dep.HibernateOrmProcessor] (build-22) Hibernate ORM is disabled because no JPA entities were found
2024-08-02 13:57:05,967 WARN  [io.qua.dat.dep.dev.DevServicesDatasourceProcessor] (build-36) Unable to determine a database type for default datasour
```

And these warnings make sense as you have not added any JDBC related extensions

**Comment by fedinskiy** [comment] 2024-08-02 11:13
@geoand try to drop "spring-data-jpa" from the creation command (ie make it look like this: ` mvn io.quarkus.platform:quarkus-maven-plugin:3.13.0:create -DprojectGroupId=my-groupId -DprojectArtifactId=app -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.13.0 -Dextensions=quarkus-rest,spring-boot-properties,spring-di,spring-security,spring-web && cd app`)
The warnings you mentioned will be gone, but the reflection warning will stay

**Comment by geoand** [comment] 2024-08-02 11:16
In that case I see the following on reload:

```
WARN  [io.qua.arc.pro.BeanArchives] (build-9) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for app-1.0.0-SNAPSHOT@37a3eb7f
```

**Comment by geoand** [comment] 2024-08-02 11:19
@aureamunoz ^

**Comment by fedinskiy** [comment] 2024-08-02 11:21
@geoand yes, that is the one I meant. I will change the description to make it more clear

**Comment by aureamunoz** [comment] 2024-09-04 06:56
I've just seen this one. The `org.springframework.aot.hint.annotation.Reflective` wasn't included in our quarkus-spring dependency but it has been in https://github.com/quarkusio/quarkus/pull/42895 so it will be released with 3.14.2 and the warning should be gone

**Comment by michalvavrik** [comment] 2024-09-16 17:44
> I've just seen this one. The `org.springframework.aot.hint.annotation.Reflective` wasn't included in our quarkus-spring dependency but it has been in #42895 so it will be released with 3.14.2 and the warning should be gone

@aureamunoz #42895 is merged and present in 3.14.2, I tested this reproducer with 3.14.4 and the issue is still present. Will you have a look?

**Comment by aureamunoz** [comment] 2024-09-17 10:54
Hi, I just looked at it and I can't reproduce it. Everything works fine for me, I don't have any errors. Do you have the project in question?

**Comment by michalvavrik** [comment] 2024-09-17 10:57
> Hi, I just looked at it and I can't reproduce it. Everything works fine for me, I don't have any errors. Do you have the project in question?

I only saw it in CI when I bumped Quarkus to 3.14.4. Let me try it locally and report back.

**Comment by michalvavrik** [comment] 2024-09-17 10:59
Here are steps to reproduce:

```
mvn io.quarkus.platform:quarkus-maven-plugin:3.14.4:create -DprojectGroupId=my-groupId -DprojectArtifactId=app -DprojectVersion=1.0.0-SNAPSHOT -DpackageName=org.my.group -DquarkusRegistryClient=false -DplatformVersion=3.14.4 -Dextensions=quarkus-rest,spring-boot-properties,spring-di,spring-security,spring-web && cd app

mvn clean quarkus:dev
```

Wait for the app to start and reload it by pressing s or by adding a new class.

**Comment by michalvavrik** [comment] 2024-09-17 10:59
`2024-09-17 12:58:32,670 WARN  [io.qua.arc.pro.BeanArchives] (build-25) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for app-1.0.0-SNAPSHOT@61e16160`

**Comment by michalvavrik** [comment] 2024-09-17 12:38
> No way to reproduce

Just read your logs, there is `2024-09-17 14:34:57,211 WARN  [io.qua.arc.pro.BeanArchives] (build-15) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for app-1.0.0-SNAPSHOT@12d99494`.

**Comment by michalvavrik** [comment] 2024-09-17 12:48
btw @aureamunoz I am glad you are looking into this, thank you

**Comment by aureamunoz** [comment] 2024-09-17 14:16
> > No way to reproduce
> 
> Just read your logs, there is `2024-09-17 14:34:57,211 WARN [io.qua.arc.pro.BeanArchives] (build-15) Failed to index org.springframework.aot.hint.annotation.Reflective: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV for app-1.0.0-SNAPSHOT@12d99494`.

Oups!

**Comment by aureamunoz** [comment] 2024-09-25 13:12
It appears that the `@Reflective` annotation is part of a new specific Spring Framework dependency, which comes from the [Spring Experimental AOT](https://mvnrepository.com/artifact/org.springframework.experimental/spring-aot/) package. This dependency is not currently included in any of our Quarkus Spring* dependencies.

Initially, I added this class to be included in the quarkus-spring-aop module because I didn’t notice the **aot** distinction. The package name for the class is very similar to the AOP module's and doesn’t include the word "experimental," which led to the confusion.

To resolve this, a new Quarkus Spring Experimental project/artifact/dependency will need to be created to support this functionality.

**Comment by aureamunoz** [comment] 2024-09-25 14:09
false alarm, can be included in the quarkus-spring-core

**Comment by aureamunoz** [comment] 2024-09-25 15:08
PR for fixing this created: https://github.com/quarkusio/quarkus/pull/43501

**Closed** 2024-09-26 05:43 UTC
Labels: kind/bug, area/spring
