### ISSUE TITLE
Speedup InjectableBean::getTypes lookup for ArcContainerImpl.getMatchingBeans

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#33693] opened 2023-05-30 09:15 UTC
### Description

`ArcContainerImpl.getMatchingBeans` can (and likely will) perform a megamorphic virtual call dispatch on `InjectableBean::getTypes` in order to perform beans matching.

See
![image](https://github.com/quarkusio/quarkus/assets/13125299/36230c1e-4978-4928-af8d-49e650d82278)

The red `itable_stub` cost is due to the different (here 18 bean types) types performing `InjectableBean::getTypes`.

Such cost is dominant (with enough types) if compared to `BeanTypeAssignabilityRules.matches` right after too.

For more information how this has been found, see https://github.com/FgForrest/HttpServerEvaluationTest/issues/1#issuecomment-1566151006)

### Implementation ideas

There are 3 solutions to improve this:
1. trying to pre-compute such matching upfront (but can be a huge number of combinations!)
2. using a LRU cache of matches (usng Caffeine?) 
3. creating a base abstract type which expose `Type` and other immutable fields, without requiring anything more then a single (abstract) type check. Subsequently, the casted type, can perform a much faster lookup without any virtual call, but accessing directly the field.

This last one seems the more reasonable one

**Comment by mkouba** [comment] 2023-05-30 10:42
The `ArcContainerImpl.getMatchingBeans(Resolvable)` should not be used very often. The default path makes use of the computing cache, see `ArcContainerImpl.resolved`. We don't cache the resolution for `BeanManager#getBeans()` which is not recommended in Quarkus and is mainly kept for backward compatibility.

From the flamegraph I can see that you were profiling SmallRye GraphQL. That's IMO the place where to start...

**Comment by franz1981** [comment] 2023-05-30 11:02
Yep @mkouba the test is a graphql query, but it appear to always happen, in the hot path, really. In this issue I have shared the repository with it and I can share a link with the full flamegraphs.

**Comment by manovotn** [comment] 2023-05-30 11:23
> So you suggest that such code path shouldn't perform that lookup and/or reuse what has already found?

I think what Martin suggests is for graphql to not use `BM#getBeans()` - instead, they could use CDI `Instance` where, IIRC, we do use the caching. Looking at `io.smallrye.graphql.cdi.CdiLookupService` (where the invocation comes from according to the graph), this should be doable via plain CDI API.

**Comment by franz1981** [comment] 2023-05-30 11:27
Thanks @manovotn I will take a look! I am not very familiar with both code paths so I had no idea that the matching path I have found wasn't supposed to be called in the hot path although I think there is some value to document such or make it faster (if makes sense, probabiy not).
@Ladicek too, to join the party

**Comment by Ladicek** [comment] 2023-05-30 11:29
I'm unfortunately not familiar with SmallRye GraphQL, but I agree that their `CdiLookupService` looks like a bottleneck by design. We should talk to @phillip-kruger @jmartisk about this I guess.

**Comment by manovotn** [comment] 2023-05-30 11:44
> Thanks @manovotn I will take a look! I am not very familiar with both code paths so I had no idea that the matching path I have found wasn't supposed to be called in the hot path although I think there is some value to document such or make it faster (if makes sense, probabiy not). @Ladicek too, to join the party

TBF I think I understand why they had it like this - before CDI 4.0 there wasn't really such an easy way to access `Bean<T>` metadata for given type and qualifiers and then instantiate it as a bean.
Their code (from a quick glance, I am not familiar with it) uses a combination of `BM#getBeans` to access metadata but then still uses `Instance` (via `CDI.current().select()`) to get an instance and retain the ability to destroy dependent instances.

Since CDI 4.0, you can do both via `Instance` or rather its `Handle` interface which grants both, access to `Bean<T>` metadata and means to instantiate/destroy the bean from it so they could just keep reference to that:

```
Instance.Handle<T> handle = CDI.current().getBeanContainer().createInstance().select(declaringClass).getHandle();
boolean isDependentScope = handle.getBean().getScope().equals(Dependent.class);
...
```

**Comment by mkouba** [comment] 2023-05-30 11:44
> > So you suggest that such code path shouldn't perform that lookup and/or reuse what has already found?
> 
> I think what Martin suggests is for graphql to not use `BM#getBeans()` - instead, they could use CDI `Instance` where, IIRC, we do use the caching. Looking at `io.smallrye.graphql.cdi.CdiLookupService` (where the invocation comes from according to the graph), this should be doable via plain CDI API.

Ideally, the `CdiLookupService` would cache the `ManagedInstance` for normal scoped beans, or at least cache the resolved `Bean` for a given `Class`, or use the `Instance` API. 

In fact, the current code actually resolves the beans twice. First, using the `BeanManager` to find out if the bean is "resolvable" and  `@Dependent`. Second time to get the bean instance - using `CDI.current().select().get()`.

We could leverage the `jakarta.enterprise.inject.Instance.getHandle()` to get the scope of the bean. I can try to send a pull request later today...

**Comment by jmartisk** [comment] 2023-05-30 11:46
Yeah please submit a PR :)

**Comment by manovotn** [comment] 2023-05-30 12:01
Here is my quick take on it - https://github.com/smallrye/smallrye-graphql/pull/1844

**Comment by Ladicek** [comment] 2023-05-30 12:07
That seems like a good idea.

Longer term, it seems to me (though I still don't know anything about it!) that SmallRye GraphQL has a concept of method invoker which is implemented reflectively. If that was generalized, we could pre-generate invokers during build in Quarkus. I actually have an prototype of CDI invokable methods that fits this purpose nicely -- and in my prototype, an invoker can be transformed to lookup the target instance and method arguments from CDI, which is resolved during build and so at runtime, we just lookup a bean by string ID.

**Comment by geoand** [comment] 2023-05-30 12:43
> Longer term, it seems to me (though I still don't know anything about it!) that SmallRye GraphQL has a concept of method invoker which is implemented reflectively.

We certainly don't want these if we can avoid them :)

**Comment by manovotn** [comment] 2023-05-30 14:01
@franz1981 since this should now be improved on graphql side, do you want to close this issue or keep it open for some further tweaks?

**Comment by mkouba** [comment] 2023-05-30 14:23
> The original code path still need some love, but I haven't yet understood if we care about it and/or would like to advertise somehow against using it in the hot path.

If you ask about using `BeanManager#getBeans()` in the hot path then no, it should never be used in a hot path.

> maybe based on @Ladicek experiment)

What is the experiment about?

**Comment by Ladicek** [comment] 2023-05-30 14:39
> > maybe based on @Ladicek experiment)
> 
> What is the experiment about?

You don't wanna know :joy: https://github.com/Ladicek/quarkus/commits/abstract-injectable-bean

**Comment by Sanne** [comment] 2023-05-30 15:02
Funny, wasn't aware of this issue but I also had observed some non-trivial costs associated with `ArcContainerImpl.getMatchingBeans`. Spotted last week in Techempower.

Unfortunately I didn't take note of the details but I'll keep an eye out for it next time I run it.

+1 to polish this code a bit.

Also: since all types are known at build time - could we enumerate them, store them in a constant array, and then each notion of "Set<Types> and operations such as "contains" and "matches" could be implemented via bitset operations?

**Comment by mkouba** [comment] 2023-05-30 15:12
> Funny, wasn't aware of this issue but I also had observed some non-trivial costs associated with `ArcContainerImpl.getMatchingBeans`. Spotted last week in Techempower.
> 
> Unfortunately I didn't take note of the details but I'll keep an eye out for it next time I run it (it wasn't the main problem so I focused on the other ones).

Pls do. Like I said above the `ArcContainerImpl.getMatchingBeans()` method shouldn't normally present a problem in a hot path.

**Comment by manovotn** [comment] 2023-05-30 16:03
> So this is triggering type pollution, and I think Types.isArray is triggered by the method reported by Franz above.

So where is that invocation coming from?
I.e. what code is (over)using `BM#getBeans()` and can we change that?

I am with Martin in that I don't expect this to be the perf critical path; this method certainly has it's uses but mostly in runtime impls (Weld) and their extensions. Thing is, using `getBeans()` doesn't easily allow you to instantiate beans from their metadata afterwards unless you do it fully manually with creational contexts or go via `BM#resolve()` in which case you are unable to handle destruction of dependent beans properly - a likely cause why the original code of graphql was using combination of BM and `Instance` in the first place.

What I mean to say is that just because one benchmark somehow uses this invocation commonly doesn't mean it's hot path in most user apps as the use cases for it are rather limited :)

**Comment by franz1981** [comment] 2023-05-30 16:31
> So where is that invocation coming from? I.e. what code is (over)using BM#getBeans() and can we change that?

I think  @Sanne he means re the techempower benchmark, because mine was the GraphQL common path already addressed.

**Comment by Sanne** [comment] 2023-05-30 17:33
So.. just tried to run the Techempower reproducer with a breakpoint and I got a surprised by the result.

It's indeed not used at runtime (as in after bootstrap), sorry about that I misinterpreted the previous data; I previously only based my assumptions on the type pollution report, which provides global stats spanning the whole app lifecycle

It's still surprising though: for such a simple application, the method `Types:isArray` is invoked more than 10,000 times. Only during bootstrap, and shutdown as well, but I'd consider this a surprising amount - is it possible there's "just" some bootstrap (shutdown) computational complexity at play?

Even if it's just initialization cost, it would seem that `getMatchingBeans` is quite computationally intensive and there could be some low hanging fruits there.

An example stack:

```
isArray:75, Types (io.quarkus.arc.impl)
matchesNoBoxing:45, BeanTypeAssignabilityRules (io.quarkus.arc.impl)
matches:41, BeanTypeAssignabilityRules (io.quarkus.arc.impl)
matches:33, BeanTypeAssignabilityRules (io.quarkus.arc.impl)
matches:874, ArcContainerImpl (io.quarkus.arc.impl)
matches:870, ArcContainerImpl (io.quarkus.arc.impl)
getMatchingBeans:684, ArcContainerImpl (io.quarkus.arc.impl)
resolve:574, ArcContainerImpl (io.quarkus.arc.impl)
apply:-1, ArcContainerImpl$$Lambda$121/0x0000000801202ac8 (io.quarkus.arc.impl)
get:52, ComputingCache$1 (io.quarkus.arc.impl)
get:26, LazyValue (io.quarkus.arc.impl)
computeIfAbsent:69, ComputingCache (io.quarkus.arc.impl)
computeIfAbsent:49, ComputingCache (io.quarkus.arc.impl)
getValue:40, ComputingCache (io.quarkus.arc.impl)
getBean:523, ArcContainerImpl (io.quarkus.arc.impl)
instanceHandle:474, ArcContainerImpl (io.quarkus.arc.impl)
instance:232, ArcContainerImpl (io.quarkus.arc.impl)
<init>:29, QuarkusManagedBeanRegistry (io.quarkus.hibernate.orm.runtime.cdi)
initiateService:19, QuarkusManagedBeanRegistryInitiator (io.quarkus.hibernate.orm.runtime.cdi)
initiateService:9, QuarkusManagedBeanRegistryInitiator (io.quarkus.hibernate.orm.runtime.cdi)
initiateService:119, StandardServiceRegistryImpl (org.hibernate.boot.registry.internal)
createService:264, AbstractServiceRegistryImpl (org.hibernate.service.internal)
initializeService:239, AbstractServiceRegistryImpl (org.hibernate.service.internal)
getService:216, AbstractServiceRegistryImpl (org.hibernate.service.internal)
bindTypeDescriptorRegistrations:447, AnnotationBinder (org.hibernate.boot.model.internal)
bindClass:408, AnnotationBinder (org.hibernate.boot.model.internal)
processEntityHierarchies:255, AnnotationMetadataSourceProcessorImpl (org.hibernate.boot.model.source.internal.annotations)
processEntityHierarchies:275, MetadataBuildingProcess$1 (org.hibernate.boot.model.process.spi)
complete:318, MetadataBuildingProcess (org.hibernate.boot.model.process.spi)
build:406, FastBootMetadataBuilder (io.quarkus.hibernate.orm.runtime.boot)
createMetadata:101, PersistenceUnitsHolder (io.quarkus.hibernate.orm.runtime)
constructMetadataAdvance:73, PersistenceUnitsHolder (io.quarkus.hibernate.orm.runtime)
initializeJpa:40, PersistenceUnitsHolder (io.quarkus.hibernate.orm.runtime)
created:78, HibernateOrmRecorder$1 (io.quarkus.hibernate.orm.runtime)
initBeanContainer:79, ArcRecorder (io.quarkus.arc.runtime)
deploy_0:-1, ArcProcessor$generateResources844392269 (io.quarkus.deployment.steps)
deploy:-1, ArcProcessor$generateResources844392269 (io.quarkus.deployment.steps)
<clinit>:-1, ApplicationImpl (io.quarkus.runner)
newInstance0:-1, NativeConstructorAccessorImpl (jdk.internal.reflect)
newInstance:77, NativeConstructorAccessorImpl (jdk.internal.reflect)
newInstance:45, DelegatingConstructorAccessorImpl (jdk.internal.reflect)
newInstanceWithCaller:499, Constructor (java.lang.reflect)
newInstance:480, Constructor (java.lang.reflect)
run:70, Quarkus (io.quarkus.runtime)
run:44, Quarkus (io.quarkus.runtime)
run:124, Quarkus (io.quarkus.runtime)
main:-1, GeneratedMain (io.quarkus.runner)
invoke0:-1, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:77, NativeMethodAccessorImpl (jdk.internal.reflect)
invoke:43, DelegatingMethodAccessorImpl (jdk.internal.reflect)
invoke:568, Method (java.lang.reflect)
doRun:61, QuarkusEntryPoint (io.quarkus.bootstrap.runner)
main:32, QuarkusEntryPoint (io.quarkus.bootstrap.runner)
```

And an example during shutdown:
```
isArray:75, Types (io.quarkus.arc.impl)
matchesNoBoxing:45, EventTypeAssignabilityRules (io.quarkus.arc.impl)
matches:41, EventTypeAssignabilityRules (io.quarkus.arc.impl)
matches:33, EventTypeAssignabilityRules (io.quarkus.arc.impl)
resolveObservers:784, ArcContainerImpl (io.quarkus.arc.impl)
createNotifier:177, EventImpl (io.quarkus.arc.impl)
createNotifier:169, EventImpl (io.quarkus.arc.impl)
createNotifier:164, EventImpl (io.quarkus.arc.impl)
apply:-1, EventImpl$$Lambda$428/0x00000008015f11d8 (io.quarkus.arc.impl)
computeIfAbsent:1708, ConcurrentHashMap (java.util.concurrent)
getNotifier:127, EventImpl (io.quarkus.arc.impl)
fire:82, EventImpl (io.quarkus.arc.impl)
fireLifecycleEvent:155, ArcRecorder (io.quarkus.arc.runtime)
run:111, ArcRecorder$2 (io.quarkus.arc.runtime)
runAllInReverseOrder:84, StartupContext (io.quarkus.runtime)
close:73, StartupContext (io.quarkus.runtime)
doStop:-1, ApplicationImpl (io.quarkus.runner)
stop:208, Application (io.quarkus.runtime)
stop:155, Application (io.quarkus.runtime)
run:436, ApplicationLifecycleManager$ShutdownHookThread (io.quarkus.runtime)
```

**Comment by geoand** [comment] 2023-05-30 17:38
Seems like an optimization around this would be useful for dev mode 😉

**Closed** 2023-06-05 10:09 UTC
Labels: kind/enhancement, area/arc
