### ISSUE TITLE
unable to deserialize GregorianCalendar

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#20397] opened 2021-09-26 15:54 UTC
### Describe the bug

An attempt to deserialize a `GregorionCalendar` will lead to a `Caused by: java.io.StreamCorruptedException: invalid type code: 00`

### Expected behavior

serialization should be supported for `GregorianCalendar`.

### Actual behavior

```
2021-09-26 15:45:36,799 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello/ser failed, error id: 7f645550-6c23-487a-9e7f-ea7baf2ea212-1: org.jboss.resteasy.spi.UnhandledException: java.io.StreamCorruptedException: invalid type code: 00
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:829)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:567)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
Caused by: java.io.StreamCorruptedException: invalid type code: 00
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1710)
        at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2077)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
        at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:2464)
        at java.io.ObjectInputStream.defaultReadObject(ObjectInputStream.java:629)
        at java.util.Calendar.readObject(Calendar.java:3587)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1175)
        at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2325)
        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2196)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1679)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:493)
        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:451)
        at org.acme.getting.started.GreetingResource.serdeser(GreetingResource.java:48)
        at org.acme.getting.started.GreetingResource.serstring(GreetingResource.java:31)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 17 more
```

### How to Reproduce?

create a sample application.

Add the following endpoint:

```java
    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/ser")
    public String ser() throws IOException, ClassNotFoundException {
        GregorianCalendar calendar = new GregorianCalendar();
        calendar.setTimeInMillis(new Date().toInstant().toEpochMilli());
        return "calendar:" + serdeser(calendar);
    }

    private String serdeser(Object obj) throws IOException, ClassNotFoundException {
        byte[] bytes = null;

        try (
                ByteArrayOutputStream baos = new ByteArrayOutputStream();
                ObjectOutputStream oos = new ObjectOutputStream(baos)) {

            oos.writeObject(obj);
            oos.flush();
            bytes = baos.toByteArray();
        }

        try (ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
                ObjectInputStream ois = new ObjectInputStream(bais)) {
            return "" + ois.readObject();
        }
    }
```

Add the following `serialization-config.json` in `src/main/resources`:

```
[
  {
    "name": "sun.util.calendar.ZoneInfo"
  }
]
```

Add the following directive:

```
<quarkus.native.additional-build-args>-H:SerializationConfigurationResources=serialization-config.json</quarkus.native.additional-build-args>
```

Add the following class:

```
@RegisterForReflection(serialization = true, targets = { ArrayList.class, String.class,
        Calendar.class, GregorianCalendar.class, TimeZone.class, SimpleTimeZone.class
})
public class ReflectionConfig {
}
```

Start a new native build.

Launch the application.

Invoke `curl http://localhost:8082/hello/ser`

The exception is printed in the server console.

Note : the invocation works fine if the application is started in jvm mode:

```
$ curl http://localhost:8082/hello/ser
calendar:java.util.GregorianCalendar[time=1632671566284,areFieldsSet=true,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/Paris",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=184,lastRule=java.util.SimpleTimeZone[id=Europe/Paris,offset=360
0000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=2,minimalDaysInFirstWeek=4,ERA=1,YEAR=2021,MONTH=8,W
EEK_OF_YEAR=38,WEEK_OF_MONTH=4,DAY_OF_MONTH=26,DAY_OF_YEAR=269,DAY_OF_WEEK=1,DAY_OF_WEEK_IN_MONTH=4,AM_PM=1,HOUR=5,HOUR_OF_DAY=17,MINUTE=52,SECOND=46,MILLISECOND=284,ZONE_OFFSET=3600000,DST_OFFSET=3600000]
```

### Quarkus version or git rev

2.3.0.CR1

### Additional information

/cc @zakkak @jaikiran

**Comment by vsevel** [comment] 2021-09-26 16:01
similar behavior with a `BigInteger`:

```
Caused by: java.io.StreamCorruptedException: invalid type code: 2C
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1710)
        at java.io.ObjectInputStream.readArray(ObjectInputStream.java:2077)
        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1667)
        at java.io.ObjectInputStream$GetFieldImpl.readFields(ObjectInputStream.java:2643)
        at java.io.ObjectInputStream.readFields(ObjectInputStream.java:673)
        at java.math.BigInteger.readObject(BigInteger.java:4646)
```

Works well in jvm mode.

**Comment by jaikiran** [comment] 2021-09-27 06:30
Hello @vsevel, I haven't yet looked into this in detail, but looking at the stacktraces and the code in `BigInteger` and `Calendar`, I'm guessing there might be some bug which causes a failure if the object being deserialized contains a filed of type array.

**Comment by jaikiran** [comment] 2021-09-27 07:15
I was able to easily reproduce this even directly with the `native-image` and a trivial (non-Quarkus) Java application. So this looks like a bug in native-image itself. I'll report it in the graal repo with a reproducer for their inputs.

**Comment by jaikiran** [comment] 2021-09-27 13:01
I've raised https://github.com/oracle/graal/issues/3839 with the necessary trivial example.

**Comment by vsevel** [comment] 2021-09-27 14:00
thanks @jaikiran

**Comment by jaikiran** [comment] 2021-10-01 01:59
@vsevel, it looks like for the `BigInteger` case you will have to add `[B` (byte array) as an additional class that should be marked for serialization, as noted in that linked Graal issue. Can you give that a try and see if it works?

For the Calendar thing, I'm not sure if it requires this one or some other class. In any case, this needs to be simplified (at least in Quarkus) instead of developers trying to hunt down which class type gets used within the serialization stream. I haven't had a chance to see how to do that simplification yet. If time permits I'll take a look in the coming days. In the meantime, please let us know if the byte array addition gets you past at least the BigInteger issue.

**Comment by zakkak** [comment] 2021-10-01 07:41
> In any case, this needs to be simplified (at least in Quarkus) instead of developers trying to hunt down which class type gets used within the serialization stream.

It looks like https://github.com/oracle/graal/pull/3760 could help us achieve this once merged.

**Comment by jaikiran** [comment] 2021-10-01 09:20
> > In any case, this needs to be simplified (at least in Quarkus) instead of developers trying to hunt down which class type gets used within the serialization stream.
> 
> It looks like [oracle/graal#3760](https://github.com/oracle/graal/pull/3760) could help us achieve this once merged.

Perhaps it should, but I just built that PR on top of latest graal upstream repo and tried it against the example I had in that BigInteger reproducer. It still fails with same error. I had to add `[B` explicitly in the serialization classes to  get it to work. It's likely that the linked PR doesn't address this specific use case because as noted in the comment here https://github.com/oracle/graal/issues/3839#issuecomment-931453769, `BigInteger` is writing out a `byte[]` for a member field of type `int[]`. So, I think, unless this knowledge of the internal implmentation of BigInteger serialization is fed into the `SerializationFeature` somehow (like we do with substitutions etc...), I don't think this can be inferred.

**Comment by zakkak** [comment] 2021-10-01 11:51
> Perhaps it should, but I just built that PR on top of latest graal upstream repo and tried it against the example I had in that BigInteger reproducer. It still fails with same error. I had to add `[B` explicitly in the serialization classes to get it to work.

That's expected, we will need to make Quarkus use [the new `registerAllAssociatedClasses`](https://github.com/oracle/graal/pull/3760/files#diff-cf39890c8a79b5ac2c7777119d37bd3c59a89878fb6f209f3cb48b3bead76ddeR75) for that to work.

> It's likely that the linked PR doesn't address this specific use case because as noted in the comment here oracle/graal#3839 (comment), BigInteger is writing out a byte[] for a member field of type int[]. So, I think, unless this knowledge of the internal implmentation of BigInteger serialization is fed into the SerializationFeature somehow (like we do with substitutions etc...), I don't think this can be inferred.

You are right about this, using the new API won't fix that for us. It's also mentioned in the [PR's description](https://github.com/oracle/graal/pull/3760#issue-990910849):
> Class with "writeObject" method. We can't automatically find out what
the customized serialization method does.

**Comment by vsevel** [comment] 2021-10-01 15:22
hello. for good measure I have added `"[Z", "[B", "[C", "[S", "[I", "[J", "[F", "[D", "[L"`
Now the `BigInteger` _and_ the `Calendar` issue do work. 
The base `Calendar` class has `protected int           fields[];` and `protected boolean       isSet[];`. so that was definitely missing too.
I agree it is not ideal, since graalvm does not help at all in the error message.
`registerAllAssociatedClasses` would be nice indeed.
not sure if we want to keep this issue around.

**Comment by jaikiran** [comment] 2021-10-02 12:19
@vsevel, I forgot to ask - where and why does the real application use Java (object) serialization? The reason I ask this is to see if improving some parts of this in native image is worth the effort or if the Java serialization usage is going to be very limited and rare case.

**Comment by vsevel** [comment] 2021-10-02 14:17
@jaikiran good question. we have a particular use case, but a very important one.
back in the days when we were running in EAP5, and we started our EAP6 migration we were extremely sad to see that there was not interop on jboss remoting between EAP5 and EAP6. we waited more than a year with no progress. eventually it was putting the migration project in danger. so we designed our own protocol, which was essentially sending a payload of serialized objects on an http connection. on the server side a servlet will locate a local ejb to dispatch the call to. on the client side, a home made generated proxy would implement the remote interface and look like a real remote ejb proxy. it was a crazy idea. but it worked beautifully. it allowed us to migrate gradually and without any issues our apps from EAP5 ro EAP6. developers liked it because it was straightforward (no special jax-rs or soap annotations all over the place): just a few serializable classes, and a java interface with a jndi name, and up you go.
we even had support for graceful shutdown way before it was provided in EAP6. and some resiliency built in (transparent retries when we can, or based on annotations). then later we reimplemented it in our SpringBoot apps. 
of course there is the interop aspect that was never addressed (and that has never been a goal). other technologies had their own protocols.
not suprisingly, these last few years we started writing more and more rest based apis. 
but I would say that 90% of our remote apis are using this serialization based protocol. over time apps will probably move to rest based apis, but this is probably going to take years. again the sad thing about, is that it works well, is reliable, you have productivity, and is very simple. 
this is not a common use case I would agree. but a critical one for us. if we do not have good support for serialization, then basically it kills the graalvm native story in the company, and remove a lot of interest that we have right now in quarkus, as good native support is today a killer argument.
that is the sad thing about doing native. it either works or it does not. there is no middle ground. 
the most important thing for me is that we have a working solution. even if it is not completely practical, then we have to have a way to get it to work. I will do what is necessary in our extensions to make it simple for developers. for instance I created our own annotation `RegisterForReflection` where we can pass a list of packages with wildcards (instead of individual classes).
I hope we can get your support on this use case.

**Comment by vsevel** [comment] 2021-10-02 14:39
I forgot to mention that I reimplemented our serialization based protocol (the client side) in quarkus with build time generated proxies based on annotated based interfaces that we find in the jandex index. 
it is using the vertx main instance to create a web client (no need to rely on bringing in the apache http client like we had to do in EAP). I have support also for security identity propagation. next I am going to implement integration support for our url registry.
the developer experience is great. and the integration in quarkus has been amazingly easy (apart from the serialization issues).
the only minor shortcoming, is that I wish the combined jandex index allowed to search into individual dependencies by name.

**Comment by vsevel** [comment] 2021-10-04 13:41
In my particular use case, it would be ideal (and probably be helpful for anybody doing serialization), to be able indicate a particular type and get all the necessary classes (superclasses, subclasses, and instance variable types) to be registered for serialization.

Since I am working in an extension, in my case I am interested in easily register types of `org.jboss.jandex.MethodInfo` associated with:
- `returnType()`, 
- `parameters()`
- `exceptions()`

**Comment by jaikiran** [comment] 2021-10-04 13:52
Thank you for that detailed context. So essentially, you have a in-house remote invocation framework which uses Java serialization. 

> In my particular use case, it would be ideal (and probably be helpful for anybody doing serialization), to be able indicate a particular type and get all the necessary classes (superclasses, subclasses, and instance variable types) to be registered for serialization.

I haven't followed the Quarkus' `RegisterForSerialization` design/implementation part. I guess what you suggest makes sense and probably should be done by one single "switch" (something like `quarkus.native.enable-serialization`) which would then make the (core) extensions mark these param/return types for serialization. But like I said, I haven't looked at that part of the code yet and not sure how soon I will be able to go through it to see if it's feasible or desirable.

**Comment by vsevel** [comment] 2021-10-05 16:28
Hello. to make sure there is no confusion, my preferred option would to be able to specify a class and get it to register itself, its superclasses, its subclasses, and all of their members, in a recursive way. 
If that is not possible, then I think we should provide an option to register several classes at once, without listing them individually. this could be done by listing packages and supporting wildcards, or registering all serializable classes of a given dependency.
hope this clarifies.

**Comment by gsmet** [comment] 2021-10-05 17:08
I think you should probably adapt `ReflectiveHierarchyBuildItem`. It mostly does what you want but would need to be adapted for serialization. It doesn't handle exceptions though.

**Comment by geoand** [comment] 2022-03-09 12:28
> It looks like [oracle/graal#3760](https://github.com/oracle/graal/pull/3760) could help us achieve this once merged.

With this merged, is there something we can now do?

**Comment by vsevel** [comment] 2022-03-09 14:32
In Oct @zakkak was saying:

> That's expected, we will need to make Quarkus use [the new registerAllAssociatedClasses](https://github.com/oracle/graal/pull/3760/files#diff-cf39890c8a79b5ac2c7777119d37bd3c59a89878fb6f209f3cb48b3bead76ddeR75) for that to work.

I see that there is a new `registerIncludingAssociatedClasses` api in [RuntimeSerialization](https://github.com/ziyilin/ziyi-forked-graal/blob/8e401c9af6643f8671cc0a3aaa464a55ff4b2962/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/hosted/RuntimeSerialization.java#L75)

it sounds like there is something to do in quarkus. e.g. using `registerIncludingAssociatedClasses` instead of the old api, or add a new attribute `associatedClasses=true` in `RegisterForReflection`

**Comment by Karm** [comment] 2022-10-13 11:17
Hello, 

### Quarkus 2.13.2.Final
Using native-image 21.3.3.0-Final Mandrel Distribution (Java Version 17.0.4+8) throws the described exception ```java.io.StreamCorruptedException: invalid type code: 00``` etc.

Using native-image 22.3.0-dev47e81a3a38f5 Mandrel Distribution (Java Version 17.0.4+8) works just fine:
```
$ curl http://localhost:8080/hello/ser
calendar:java.util.GregorianCalendar[time=1665658477167,areFieldsSet=true,areAllFieldsSet=false,lenient=true,zone=sun.util.calendar.ZoneInfo[id="Europe/Prague",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Prague,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]],firstDayOfWeek=1,minimalDaysInFirstWeek=1,ERA=1,YEAR=2022,MONTH=9,WEEK_OF_YEAR=42,WEEK_OF_MONTH=3,DAY_OF_MONTH=13,DAY_OF_YEAR=286,DAY_OF_WEEK=5,DAY_OF_WEEK_IN_MONTH=2,AM_PM=1,HOUR=0,HOUR_OF_DAY=12,MINUTE=54,SECOND=37,MILLISECOND=167,ZONE_OFFSET=3600000,DST_OFFSET=3600000]
```

I'm closing this issue. Reopen if you feel differently about it.

**Closed by Karm** 2022-10-13 11:17 UTC
Labels: kind/bug, area/native-image

**Comment by vsevel** [comment] 2022-10-14 09:07
I confirm this is working as expected. thanks
