### ISSUE TITLE
Add property to disable link-at-build-time at graalvm version 22.1 native-image build (Since Quarkus version 2.8)

### ISSUE THREAD

**Issue by knuspertante** [quarkusio/quarkus#25526] opened 2022-05-12 07:45 UTC
### Description

Hey, 

since Quarkus Version 2.8 - GraalVM 22.1 is used and therefore link-at-build-time is added as default parameter. (See: https://github.com/quarkusio/quarkus/pull/24213) 

But currently I don't know any way to disable or remove this parameter.

**Comment by zakkak** [comment] 2022-05-12 12:13
Hello @knuspertante,

This is something that Quarkus wouldn't want to encourage.
Could you please explain why that option is important to your use case?

One way to disable the `--link-at-build-time` flag is by creating a `NativeImageAllowIncompleteClasspathBuildItem` as in https://github.com/quarkusio/quarkus/blob/3f9bf7ba99c15032ba9c46c83d5f5f2579bca612/extensions/jdbc/jdbc-oracle/deployment/src/main/java/io/quarkus/jdbc/oracle/deployment/OracleMetadataOverrides.java#L114-L117

**Comment by knuspertante** [comment] 2022-05-13 08:51
Hi @zakkak,

thx for the fast reply. 

When I want to build a native-image with --link-at-build-time I got the following error. 

```shell
Error: Unsupported features in 3 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: net.sf.oval.expression.ExpressionLanguageJavaScriptImpl.<init>(). This error is reported at image build time because class net.sf.oval.expression.ExpressionLanguageRegistry is registered for linking at image build time by command line
Trace: 
        at parsing net.sf.oval.expression.ExpressionLanguageRegistry._initializeDefaultEL(ExpressionLanguageRegistry.java:26)
Call path from entry point to net.sf.oval.expression.ExpressionLanguageRegistry._initializeDefaultEL(String): 
        at net.sf.oval.expression.ExpressionLanguageRegistry._initializeDefaultEL(ExpressionLanguageRegistry.java:25)
        at net.sf.oval.expression.ExpressionLanguageRegistry.getExpressionLanguage(ExpressionLanguageRegistry.java:73)
        at net.sf.oval.AbstractCheck.isActive(AbstractCheck.java:154)
        at net.sf.oval.Validator.checkConstraint(Validator.java:791)
        at net.sf.oval.Validator.lambda$1(Validator.java:894)
        at net.sf.oval.Validator$$Lambda$4105/0x0000000104b96bd0.accept(Unknown Source)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at software.amazon.awssdk.protocols.jsoncore.internal.ObjectJsonNode.toString(ObjectJsonNode.java:94)
        at sun.java2d.loops.GraphicsPrimitive.simplename(GraphicsPrimitive.java:610)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_GraphicsPrimitive_simplename_202a3eedb200439fc8661f318bfce7d323ea7603(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: net.sf.oval.ogn.ObjectGraphNavigatorJXPathImpl.<init>(). This error is reported at image build time because class net.sf.oval.ogn.ObjectGraphNavigatorRegistry is registered for linking at image build time by command line
Trace: 
        at parsing net.sf.oval.ogn.ObjectGraphNavigatorRegistry._initializeDefaultOGN(ObjectGraphNavigatorRegistry.java:26)
Call path from entry point to net.sf.oval.ogn.ObjectGraphNavigatorRegistry._initializeDefaultOGN(String): 
        at net.sf.oval.ogn.ObjectGraphNavigatorRegistry._initializeDefaultOGN(ObjectGraphNavigatorRegistry.java:25)
        at net.sf.oval.ogn.ObjectGraphNavigatorRegistry.getObjectGraphNavigator(ObjectGraphNavigatorRegistry.java:39)
        at net.sf.oval.Validator.checkConstraint(Validator.java:816)
        at net.sf.oval.Validator.lambda$1(Validator.java:894)
        at net.sf.oval.Validator$$Lambda$4105/0x0000000104b96bd0.accept(Unknown Source)
        at java.util.LinkedHashMap.forEach(LinkedHashMap.java:721)
        at software.amazon.awssdk.protocols.jsoncore.internal.ObjectJsonNode.toString(ObjectJsonNode.java:94)
        at sun.java2d.loops.GraphicsPrimitive.simplename(GraphicsPrimitive.java:610)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_GraphicsPrimitive_simplename_202a3eedb200439fc8661f318bfce7d323ea7603(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: ucar.nc2.grib.grib2.Grib2JpegDecoder.<init>(int, boolean). This error is reported at image build time because class ucar.nc2.grib.grib2.Grib2DataReader2 is registered for linking at image build time by command line
Trace: 
        at parsing ucar.nc2.grib.grib2.Grib2DataReader2.getData40(Grib2DataReader2.java:727)
Call path from entry point to ucar.nc2.grib.grib2.Grib2DataReader2.getData40(RandomAccessFile, Grib2Drs$Type40): 
        at ucar.nc2.grib.grib2.Grib2DataReader2.getData40(Grib2DataReader2.java:716)
        at ucar.nc2.grib.grib2.Grib2DataReader2.getData(Grib2DataReader2.java:109)
        at ucar.nc2.grib.grib2.Grib2Record.readData(Grib2Record.java:321)
        at ucar.nc2.grib.collection.Grib2Iosp.readData(Grib2Iosp.java:405)
        at ucar.nc2.grib.collection.GribIosp$DataReader.read(GribIosp.java:940)
        at ucar.nc2.grib.collection.GribIosp.readDataFromCollection(GribIosp.java:860)
        at ucar.nc2.grib.collection.GribIosp.readData(GribIosp.java:810)
        at ucar.nc2.NetcdfFile.readData(NetcdfFile.java:1986)
        at ucar.nc2.Variable.reallyRead(Variable.java:860)
        at ucar.nc2.Variable._read(Variable.java:831)
        at ucar.nc2.Variable.read(Variable.java:709)
        at ucar.nc2.NCdumpW.printVariableData(NCdumpW.java:386)
        at ucar.nc2.dt.grid.GridCoordSys.showCoords(GridCoordSys.java:1405)
        at ucar.nc2.dt.grid.GridCoordSys.show(GridCoordSys.java:1355)
        at ucar.nc2.dt.grid.GridCoordSys.toString(GridCoordSys.java:1345)
        at sun.java2d.loops.GraphicsPrimitive.simplename(GraphicsPrimitive.java:610)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY_GraphicsPrimitive_simplename_202a3eedb200439fc8661f318bfce7d323ea7603(generated:0)
```

With the following code, I only can provide a quarkus extension or?
```java
new NativeImageAllowIncompleteClasspathBuildItem("quarkus-jdbc-oracle"); 
```

Do you have another idea how I can solve my problem?

**Comment by zakkak** [comment] 2022-05-13 09:21
This looks like a classpath issue that you should not "work around".

The error essentially says that GraalVM fails to find 2 constructors from `net.sf.oval:oval` (while loading other methods just fine), and 1 constructor from `ucar.nc2:grib` (while loading other methods just fine). This behavior makes me think that either:
1. there is something wrong with the classpath
2. or there is a GraalVM bug you are hitting.

To further help with this issue could you please try compiling your application with a different GraalVM version? e.g. 22.0 but without using `--allow-incomplete-classpath`.

Is there any chance you could share your reproducer? If not, could you least the maven/gradle part where you define the oval and grib dependencies?

**Comment by zakkak** [comment] 2022-05-13 09:36
> This works just fine.

So it looks like a GraalVM regression since in 22.0 `--link-at-build-time` was the default. A reproducer would be great. Thanks @knuspertante !

**Comment by zakkak** [comment] 2022-05-13 10:44
> Ah shit sorry I misread your message. Yep, it just worked with `--allow-incomplete-classpath`

So does it break **with** 22.0 and **without** `--allow-incomplete-classpath`?

**Comment by knuspertante** [comment] 2022-05-17 12:24
Hey @zakkak 

> So does it break **with** 22.0 and **without** `--allow-incomplete-classpath`?

yep, thats it.

**Comment by knuspertante** [comment] 2022-05-17 12:47
@zakkak I updated my comment above. Yeah, but with Quarkus 2.7.X I was able to still allow the build with `--allow-incomplete-classpath`

I updated my comment above

> Hey @zakkak
> 
> > So does it break **with** 22.0 and **without** `--allow-incomplete-classpath`?
> 
> It still works with GraalVM 22.1 and **without** `--allow-incomplete-classpath`? Only if `--link-at-build-time` is added by quarkus version >= 2.8 it does not work any more.
> 
> This works (Quarkus 2.7.5.Final)
> 
> ```shell
> /home/ubuntu/graalvm-ee-java17-22.1.0/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED --initialize-at-run-time=ucar.nc2.grib.grib2,net.sf.oval.ogn.ObjectGraphNavigatorJXPathImpl,de.j21p.janus.filesystem.AwsS3Objects,org.apache.poi.ss.util.SheetUtil,net.sf.oval.expression,org.apache.sis.internal.system.DelayedExecutor,org.apache.sis.internal.system.ReferenceQueueConsumer --no-fallback -H:ResourceConfigurationFiles=resource-config.json -H:ReflectionConfigurationFiles=reflection-config.json -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -J-Xmx8g -H:+AddAllCharsets -H:EnableURLProtocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace janus-funqy-functions-quarkus-1.0.0-SNAPSHOT-runner -jar janus-funqy-functions-quarkus-1.0.0-SNAPSHOT-runner.jar
> ```
> 
> This don't work Quarkus 2.9.0.Final
> 
> ```shell
> /home/ubuntu/graalvm-ee-java17-22.1.0/bin/native-image -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Dfile.encoding=UTF-8 -H:-ParseOnce -J--add-exports=java.security.jgss/sun.security.krb5=ALL-UNNAMED -J--add-opens=java.base/java.text=ALL-UNNAMED --initialize-at-run-time=ucar.nc2.grib.grib2,net.sf.oval.ogn.ObjectGraphNavigatorJXPathImpl,de.j21p.janus.filesystem.AwsS3Objects,org.apache.poi.ss.util.SheetUtil,net.sf.oval.expression,org.apache.sis.internal.system.DelayedExecutor,org.apache.sis.internal.system.ReferenceQueueConsumer --no-fallback -H:ResourceConfigurationFiles=resource-config.json -H:ReflectionConfigurationFiles=reflection-config.json -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -J-Djava.awt.headless=true -H:FallbackThreshold=0 --link-at-build-time -H:+ReportExceptionStackTraces -J-Xmx8g -H:+AddAllCharsets -H:EnableURLProtocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace janus-funqy-functions-quarkus-1.0.0-SNAPSHOT-runner -jar janus-funqy-functions-quarkus-1.0.0-SNAPSHOT-runner.jar
> ```

Sorry, until now I was not able to provide a reproducer, but I hope to get that done in the next few days.

**Comment by zakkak** [comment] 2022-05-17 13:00
> This works (Quarkus 2.7.5.Final)
> This don't work Quarkus 2.9.0.Final

None of these releases officially supports GraalVM 22.1 though. 

Quarkus [2.7.5 supports GraalVM 21.3](https://github.com/quarkusio/quarkus/blob/2733bae7cb7ded76d324b41a3a9f4e81b89ee122/build-parent/pom.xml#L144) and [2.9.0 supports 22.0](https://github.com/quarkusio/quarkus/blob/53d2c9eb73b6113dbd54c3e542fa9ac1211a84c4/core/deployment/src/main/java/io/quarkus/deployment/pkg/NativeConfig.java#L19-L20) 

GraalVM 22.1 is currently officially supported only on the `main` branch of Quarkus and is expected to land in 2.10.x.

> Sorry, until now I was not able to provide a reproducer, but I hope to get that done in the next few days.

No worries.

**Comment by knuspertante** [comment] 2022-05-17 13:32
@zakkak here is a little reproducer https://github.com/knuspertante/quarkus-link-at-build-time-reproducer ;-) 

Thanks for your effort!!!

**Comment by luneo7** [comment] 2022-05-30 18:16
jOOQ is also impacted by this: https://github.com/quarkiverse/quarkus-jooq/issues/73
Maybe we could add a new build item to configure build time linkage... to do not have build time linkage for the extension only and not a global change as described in https://www.graalvm.org/22.1/reference-manual/native-image/BuildConfiguration/

**Comment by zakkak** [comment] 2022-06-20 14:32
@luneo7 is this still an issue for you? If I am not mistaken https://github.com/quarkiverse/quarkus-jooq/issues/73#issuecomment-1141852860 hints that this is now resolved for jOOQ.

**Comment by zakkak** [comment] 2022-06-21 13:46
> I will try to make GraalVM reports make that more clear, including the dependencies that are missing

I created a WIP PR regarding this, see https://github.com/oracle/graal/pull/4661

**Comment by luneo7** [comment] 2022-06-21 16:02
@zakkak it will be fixed in jOOQ 3.17, that is not released yet (dunno when it will be released)... I did a work around though... adding libs to the pom so the class path is complete, even if we are not using the libs...

**Comment by knuspertante** [comment] 2022-07-29 14:29
@zakkak thanks for your work!

However would it be possible, that we only provide ```native-image --link-at-build-time=io.quarkus,io.quarkiverse,...``` or every extension provides its packages/classes instead of a global `--link-at-build-time`?

Then we do not need for every 3rd-Party lib a extension or substitution which uses optional dependencies.

**Comment by Karm** [comment] 2022-08-11 16:35
@knuspertante
> Then we do not need for every 3rd-Party lib a extension or substitution which uses optional dependencies.

Not necessarily, see an example with Apache PDFBox with Quarkus native:

https://github.com/quarkusio/quarkus-quickstarts/pull/1154

**Comment by faskan** [comment] 2023-01-04 16:43
@zakkak can you please help me with the below reproducer using flying-saucer-pdf? I couldn't figure out what the missing dependency here is.

[https://github.com/faskan/tinker-quarkus/tree/main/quarkus-flying-saucer-pdf](https://github.com/faskan/tinker-quarkus/tree/main/quarkus-flying-saucer-pdf)

```
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: com.lowagie.text.pdf.PdfPublicKeySecurityHandler.<init>(). This error is reported at image build time because class com.lowagie.text.pdf.PdfEncryption is registered for linking at image build time by command line
        at parsing com.lowagie.text.pdf.PdfEncryption.<init>(Unknown Source)
```

**Comment by zhfeng** [comment] 2023-02-09 09:54
@zakkak we have a similar issue https://github.com/apache/camel-quarkus/issues/4512

**Comment by scrocquesel** [comment] 2023-11-10 21:17
we have a similar issue with https://github.com/quarkiverse/quarkus-amazon-services/issues/958.
While AWS SDK is supporting native build, it does without `link-at-built-time` so in the extension we used to provide substitutions to remove the reference to the optional dependency. Unfortunately, a major refactoring in the sdk make things a lot more complicated at first glance, meaning a lot more substitutions, cloned code to maintain and sometimes we just can't `@alias` fields of inaccessible type.

**Comment by zakkak** [comment] 2023-11-14 09:28
> Unfortunately, a major refactoring in the sdk make things a lot more complicated at first glance, meaning a lot more substitutions, cloned code to maintain 

I totally understand but that's the cost we (the framework developers) pay so that Quarkus users can take full advantage of the benefit of [build time initialization](https://dl.acm.org/doi/10.1145/3360610). 

> sometimes we just can't @alias fields of inaccessible type

I might be able to help with this.

**Comment by scrocquesel** [comment] 2023-11-16 22:25
> > Unfortunately, a major refactoring in the sdk make things a lot more complicated at first glance, meaning a lot more substitutions, cloned code to maintain
> 
> I totally understand but that's the cost we (the framework developers) pay so that Quarkus users can take full advantage of the benefit of [build time initialization](https://dl.acm.org/doi/10.1145/3360610).
> 
> > sometimes we just can't @alias fields of inaccessible type
> 
> I might be able to help with this.

Thanks for proposing your help, I finally did manage to find proper code to trim.

**Comment by SetoKaiba** [comment] 2023-12-26 11:40
@zakkak I have a requirement to disable --link-at-build-time as well.
I'm trying to create an app in Quarkus with Google Cloud Vertex AI SDK.

I can compile it to native image without --link-at-build-time and any substitutions and it works.
Here's the working app.
https://github.com/SetoKaiba/gcp_test

I can't make it work with `--link-at-build-time`. Altough I have add some substitutions. I know that `--link-at-build-time` is the way to find out the problem before. But it just costs time to fix the app with a lot of substitutions. And for my case, even I can't make it work. I'm not sure whether `--link-at build-time` is a best practise. And also, I can compile it by including the `jdbc-oracle` dependency to disable the `--link-at-build-time` without any substitutions.
Here's the reproduce project.
https://github.com/SetoKaiba/gcp_reproduce

**Closed** 2024-04-10 19:27 UTC
Labels: kind/enhancement, area/native-image
