### ISSUE TITLE
Reactive messaging display false "warning" logs

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#6197] opened 2019-12-16 13:52 UTC
**Describe the bug**
When using reactive messaging with Kafka, it shows some "warning" logs about wrong config properties when it should not.
```
2019-11-20 17:45:38,978 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'channel-name' was supplied but isn't a known config.
2019-11-20 17:45:38,986 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'connector' was supplied but isn't a known config.
2019-11-20 17:45:38,986 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (main) The configuration 'topic' was supplied but isn't a known config.
```

**Comment by anamarija** [comment] 2019-12-16 13:56
Hi,

If nobody is working on this I can fix it.

**Comment by ia3andy** [comment] 2019-12-16 13:57
I guess you can.. just confirm with @cescoffier

**Comment by gsmet** [comment] 2019-12-16 14:04
IIRC, the issue is that all the config is blindly passed to Kafka, even the one specific to Reactive Messaging.

Wait for @cescoffier to weigh in but I'm pretty sure it's something that needs fixing in the Reactive Messaging implementation.

**Comment by gsmet** [comment] 2019-12-16 14:06
BTW, this is the original message which contains important information: https://groups.google.com/d/msg/quarkus-dev/sJ9RcAJSmPE/bAyJxd-vBQAJ .

**Comment by anamarija** [comment] 2019-12-16 14:09
Yes it is surely a fix in the smallrye messaging module.

**Comment by ia3andy** [comment] 2019-12-16 14:13
I'll create an issue there and reference this one.

**Comment by cescoffier** [comment] 2019-12-19 07:01
The upstream issue has been fixed, so this issue will be fixed when we update.

**Comment by cescoffier** [comment] 2020-05-15 08:24
Closing as we integrated a version of reactive messaging containing the fix.

**Closed** 2020-05-15 08:24 UTC
Labels: kind/bug
