### ISSUE TITLE
Validation groups for REST endpoint does not work with Kotlin

### ISSUE THREAD

**Issue by isaul32** [quarkusio/quarkus#20395] opened 2021-09-26 10:22 UTC
### Describe the bug

[Validation groups for REST endpoint](https://quarkus.io/guides/validation#validation-groups-for-rest-endpoint-or-service-method-validation) does not working when REST resource is written in Kotlin.

However, manual validation works fine e.g. `validator.validate(book, ValidationGroups.Post::class.java)`

### Expected behavior

REST endpoint should be validated by converted group.

### Actual behavior

REST endpoint converted group is skipped without validation.

### How to Reproduce?

Define interfaces.
```kotlin
import javax.validation.groups.Default

interface ValidationGroups {
    interface Put : Default
    interface Post : Default
}
```
Add a class to be validated.
```kotlin
class Book {

    @Null(groups = [ValidationGroups.Put::class])
    @NotNull(groups = [ValidationGroups.Post::class])
    var id: Long? = null

    @NotBlank
    var title: String? = null

}
```
Add a REST resource with group validation.
```kotlin
@Path("/")
@POST
@Consumes(MediaType.APPLICATION_JSON)
fun post(@Valid @ConvertGroup(to = Post::class) book: Book) {
    // ...
}
```

### Output of `uname -a` or `ver`

Linux 5.10.63-1-MANJARO SMP PREEMPT Wed Sep 8 14:13:59 UTC 2021 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 6.9

**Comment by geoand** [comment] 2021-09-27 06:32
cc @yrodiere

**Comment by geoand** [comment] 2022-03-09 12:29
Can you please provide a sample project that reproduces this error?

Thanks

**Comment by isaul32** [comment] 2022-03-09 15:39
Sure. There is a [sample project](https://github.com/isaul32/quarkus-kotlin-validation-issue-sample) that reproduces this error. The car and the book should be the same, but the car is written in Java and the book in Kotlin.

**Comment by geoand** [comment] 2022-03-11 07:25
This seems to be a weird interplay between Hibernate Validator and Kotlin...

On one hand, the bytecode that kotlinc generates differs from the bytecode that java generates in the fact that the `RuntimeVisibleTypeAnnotations` element is missing.
On the other hand, Hibernate Validator is not obtaining the method parameter annotations by calling `parameter.getAnnotation(...)` (which does contain the proper annotations), but instead from `parameter.getAnnotatedType().getAnnotation(...)` (which does not contain the annotations, because of the missing `RuntimeVisibleTypeAnnotations` section).

https://youtrack.jetbrains.com/issue/KT-13228 is somewhat related

**Comment by mschorsch** [comment] 2022-03-11 07:36
@isaul32 The kotlin compiler argument `-Xemit-jvm-type-annotations` might help.

**Comment by geoand** [comment] 2022-03-11 07:37
Tried it, it does not

**Comment by gsmet** [comment] 2023-01-23 13:43
Frankly, this does look like a Kotlin issue. We are using standard Java APIs in Hibernate Validator and that should work properly.

I'm going to close as `won't fix`.

**Closed by gsmet** 2023-01-23 13:43 UTC
Labels: kind/bug, area/kotlin, area/hibernate-validator, triage/upstream
