### ISSUE TITLE
Classloader problems with jaxb and stax

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#9300] opened 2020-05-14 14:00 UTC
**Describe the bug**
In my code, I use Jaxb to marshal my objects to xml.

I have an stax:stax:1.2 dependency on my classpath. This causes Classloader problems. `javax.xml.namespace.QName` Is loaded by the `Quarkus Base Runtime ClassLoader`. My Application classes are loaded by `Quarkus Runtime ClassLoader`. In this case, I get an exception when trying to create a new `JAXBContext``.

If I now remove the stax dependency, `javax.xml.namespace.QName` gets loaded by the Quarkus Runtime ClassLoader.
I now get my marshaled XML.

**Expected behavior**
No exceptions, when converting java objects to xml, or at least a better error message.

**Actual behavior**
I get the following exception:

```
Caused by: java.lang.LinkageError: loader constraint violation: when resolving field "DATETIME" of type javax.xml.namespace.QName, the class loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @409986fe of the current class, com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl, and the class loader 'bootstrap' for the field's defining ty
pe, javax.xml.datatype.DatatypeConstants, have different Class objects for type javax.xml.namespace.QName (com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @409986fe, parent loader 'platform'; javax.xml.datatype.DatatypeConstants is in module java.xml of load
er 'bootstrap')
        at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:254)
        at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:33)
        at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:98)
        at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:54)
        at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:132)
        at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:62)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:425)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
        at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
        at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
        at com.sun.xml.bind.v2.JAXBContextFactory.createContext(JAXBContextFactory.java:35)
        at javax.xml.bind.ContextFinder.find(ContextFinder.java:393)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:691)
        at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:632)
        at org.acme.ExampleResource.hello(ExampleResource.java:26)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
        ... 20 more

```

**To Reproduce**
1. Download the reproducer project: 
[jaxb-bug.zip](https://github.com/quarkusio/quarkus/files/4628858/jaxb-bug.zip)

2. Execute mvn quarkus:dev
3. Go to http://localhost:8080/hello
4. Exception happens

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\zulu11.39.15-ca-jdk11.0.7-win_x64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by jmistry65** [comment] 2020-06-04 06:48
facing same issue.

**Comment by daniel-alonso-sanchez** [comment] 2020-06-23 07:50
Same here

**Comment by daniel-alonso-sanchez** [comment] 2020-06-23 11:54
> Same here

Well, I was wrong. The problem in my app was related with the stax api dependency, introduced as a transitive one through min.io java client.

After excluding it, everything went fine.

**Comment by Sridhar-1987** [comment] 2020-07-22 07:00
Same issue here as well. 

@daniel-alonso-sanchez 
Can you elaborate the fix (or pom exclusion), so that others can also benefit

**Comment by TMBD** [comment] 2020-07-23 11:50
I had the same issue.
After further research in my dependencies by using the maven dependency tree tool I saw that the issue was due to the stax-api dependency. This dependency was transitively included in my project. Since then it was difficult to solve the problem because it was not directly included in my poms thus not visible. What I did was just to exclude that stax-api dependency from my pom and that has solved the problem.

Finaly the dependency looks like :

`<dependency>
      <groupId>com.example.lib</groupId>
      <artifactId>my-lib</artifactId>
      <version>${example-lib-version}</version>
      <exclusions>
        <exclusion>
          <groupId>stax</groupId>
          <artifactId>stax-api</artifactId>
        </exclusion>
      </exclusions>
    </dependency>`

With com.example.lib:my-lib the dependency through which stax-api was included.

**Comment by davide-malagoli** [comment] 2020-08-24 14:24
Same issue here with Quarkus 1.7.0.
I tried an example from here

https://2much2learn.com/uploading-files-to-cloud-native-object-store-from-quarkus-restful-api/

and tried to exclude stax api using

<dependency>
        <groupId>stax</groupId>
        <artifactId>stax-api</artifactId>
        <version>[1.0,]</version>
        <scope>provided</scope>
    </dependency>

but this causes an error in the init phase of the nayarana jta plugin.

So I tried "substituting" it with (as the example depicts)

<dependency>
  <groupId>com.fasterxml.woodstox</groupId>
  <artifactId>woodstox-core</artifactId>
  <version>6.2.0</version>
</dependency>

but the linkage error was still there.

Then I tried "downgrading" Quarkus, the only version that works is 1.0.1, how is this possible?
I attach my maven dependency trees, with 1.0.1 and 1.7.0.

[dep_tree_1_0_1.txt](https://github.com/quarkusio/quarkus/files/5118417/dep_tree_1_0_1.txt)
[dep_tree_1_7_0.txt](https://github.com/quarkusio/quarkus/files/5118418/dep_tree_1_7_0.txt)

**Comment by ppalaga** [comment] 2020-12-11 10:50
I can confirm, that excluding `stax:stax-api` helped in my case. I guess also the attached reproducer project can be fixed by replacing

```
        <dependency>
            <groupId>stax</groupId>
            <artifactId>stax</artifactId>
            <version>1.2.0</version>
        </dependency>
```

with 

```
        <dependency>
            <groupId>stax</groupId>
            <artifactId>stax</artifactId>
            <version>1.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>stax</groupId>
                    <artifactId>stax-api</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

I do not think the Quarkus team can help in any way with this, thus closing.

**Closed by ppalaga** 2020-12-11 10:50 UTC
Labels: kind/bug

**Comment by essobedo** [comment] 2021-05-16 06:37
A potential fix for this issue https://github.com/quarkusio/quarkus/pull/17248

**Comment by essobedo** [comment] 2021-05-21 07:04
This problem is actually due to the fact that `javax.xml.namespace.QName` is loaded from the `QuarkusClassLoader`/`RunnerClassLoader` (because Quarkus by default will try to load the classes from the `QuarkusClassLoader`/`RunnerClassLoader` first) while it should rather be loaded from the System `ClassLoader` in that particular case. 

To workaround this problem you can indeed exclude the dependency that causes the `LinkageError` if you can exclude all the classes  of this dependency otherwise you can rely on the property [`quarkus.class-loading.parent-first`](https://quarkus.io/guides/all-config#quarkus-core_quarkus.class-loading.parent-first-artifacts) to indicate Quarkus that its classes need to be loaded from the parent `ClassLoader` first before trying to load it from the `QuarkusClassLoader`/`RunnerClassLoader`.

Example of usage of `quarkus.class-loading.parent-first` in the `application.properties` :
```
quarkus.class-loading.parent-first-artifacts=stax:stax-api
```

**Comment by Google-dfp** [comment] 2025-02-04 19:59
@daniel-alonso-sanchez https://stackdev.space/questions/organizing-xml-data-using-jaxb
