### ISSUE TITLE
GCP Run: Fatal error: Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.open() failed

### ISSUE THREAD

**Issue by rgrebski** [quarkusio/quarkus#4262] opened 2019-09-29 15:51 UTC
**Describe the bug**
I tried to run Quarkus sample app generated by Maven on Google Cloud Run, but unfortunately I get:
Fatal error: Util_sun_misc_Signal.ensureInitialized: CSunMiscSignal.open() failed

**Expected behavior**
App runs correctly on GCP Run

**Actual behavior**
App Fails to run

**To Reproduce**
1. Generate quarkus project using Maven 
2. Build docker image
3. Push to GCP Docker repo
4. Deploy using command:
```
gcloud beta run deploy --allow-unauthenticated --platform managed --image gcr.io/YOUR_PROJECT/YOUR_IMAGE_NAME
```

[logs__2019-09-29T10-56.zip](https://github.com/quarkusio/quarkus/files/3667567/null__logs__2019-09-29T10-56.zip)

**Comment by jaikiran** [comment] 2019-09-30 08:49
Hello @rgrebski, which version of Graal VM and Quarkus are you using?

**Comment by rgrebski** [comment] 2019-09-30 09:03
Thx for quick response. Versions:

Quarkus: 0.23.1
GraalVM: GraalVM CE 19.1.1  (tried also with 19.2.0 and 19.2.1)

**Comment by jaikiran** [comment] 2019-10-02 04:55
As far as I can see, this substitution is coming directly from substratevm here https://github.com/oracle/graal/blob/vm-19.2.0.1/substratevm/src/com.oracle.svm.core.posix/src/com/oracle/svm/core/posix/SunMiscSubstitutions.java#L76. So it looks like something to be reported in that project. Having said that, I'm not an expert in this area. Maybe @dmlloyd might have more inputs?

**Comment by dmlloyd** [comment] 2019-10-02 17:33
The problem is that AWS doesn't allow the syscalls required by the GraalVM signals implementation.  The GraalVM signal handler in turn is a bit convoluted to account for isolates.  I wasn't able to figure out a reasonable solution though: the set of syscalls that can be made from a signal handler is quite limited.

**Comment by Alars-ALIT** [comment] 2019-10-22 07:39
Does this mean that quarkus can't be deployed as a native image to Google Cloud Run? Are there any workarounds?

**Comment by dmlloyd** [comment] 2019-10-22 17:53
You can work around the problem by defining the environment variable `DISABLE_SIGNAL_HANDLERS` to any value.  Obviously this means that you won't have OS signal handling though.

**Comment by dmlloyd** [comment] 2019-10-22 17:54
Ultimately we'll probably end up defining our own signal handler which works more like OpenJDK's.

**Comment by dmlloyd** [comment] 2019-10-25 12:49
It means that `SIGINT`/`SIGTERM` won't call shutdown hooks (the process will end abruptly) and you cannot get stack traces via `SIGQUIT`.

**Comment by loicmathieu** [comment] 2020-10-16 11:34
What is the status on this one ?
I just tested our getting started application on Cloud Run and it works.
Can we close it?

**Comment by dmlloyd** [comment] 2020-10-16 12:43
This I believe was fixed via https://github.com/oracle/graal/pull/2746.

**Closed by dmlloyd** 2020-10-16 12:43 UTC
Labels: kind/bug, pinned
