### ISSUE TITLE
publish gradle plugin to the gradle plugin portal

### ISSUE THREAD

**Issue by cniweb** [quarkusio/quarkus#1793] opened 2019-04-01 10:26 UTC
Publish gradle plugin to the gradle plugin portal.

How it works, see:
https://plugins.gradle.org/docs/submit

**Comment by stalep** [comment] 2019-04-02 08:53
It is also in the todo :)

**Comment by Sanne** [comment] 2019-07-08 11:40
Added it to the list of issues we should have for 1.0

**Comment by Dufgui** [comment] 2019-08-21 21:21
I create a merge request to have better information display in gradle portal.
So now you must create a quarkus release account in gradle portal : 
https://plugins.gradle.org/user/register

Get the API Keys :
```gradle.publish.key=<key>
gradle.publish.secret=<secret>
```

So to do it, during the release process, you must call in `devtools/gradle` (with key and secret replace by the previous API Keys values) :
```
gradle publishPlugins -Pgradle.publish.key=<key> -Pgradle.publish.secret=<secret>
```
No more

**Comment by Sanne** [comment] 2019-08-22 09:37
Reopening as it's not published yet.

**Comment by gsmet** [comment] 2019-08-22 09:46
Raaah, it was closed automatically by the PR. Thanks @Sanne

**Comment by patoessy** [comment] 2019-09-21 18:56
Why is this always been moved to another milestone? Is it always hard to publish?

**Comment by patoessy** [comment] 2019-09-21 18:56
How can I assist?

**Comment by maxandersen** [comment] 2019-10-03 10:25
duplicate of https://github.com/quarkusio/quarkus/issues/4311 which has a bit more context of why its relevant to push.

**Closed by maxandersen** 2019-10-03 10:25 UTC
Labels: component:gradle
