### ISSUE TITLE
Lombok @Builder not producing builder class in submodule of multi-module Gradle project

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#7367] opened 2020-02-23 18:18 UTC
**Describe the bug**

Lombok won´t produce the builder class with the **@Builder** annotation in the library module, but it works as expected in the application module

`Caused by: java.lang.ClassNotFoundException: com.demo.common.model.SharedModel$SharedModelBuilder
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 22 more
`

**To Reproduce**

I´ve made a demo project to reproduce this issue 

https://github.com/mklueh/quarkus-multi-module-lombok-builder-issue

**Comment by Postremus** [comment] 2020-02-23 19:27
I can reproduce this, or at least the root cause, without much trouble in a maven project.

The problem is, I think at least, that the maven-compiler-plugin is only triggered for the module, where the quarkus-maven-plugin is included.
No compilation is done for librarys. The compiler-plugin is not triggered for them.

**Comment by mklueh** [comment] 2020-02-24 19:05
@Postremus This sounds like another issue I´ve posted, where the library module is not compiled into the classpath at all https://github.com/quarkusio/quarkus/issues/7365 . In case of the @Builder issue the class with the annotation is compiled, but not Builder class is generated

**Comment by aloubyansky** [comment] 2020-03-13 16:12
Appears to be fixed in 1.3.0.Final. Thanks for the report!

**Closed by aloubyansky** 2020-03-13 16:12 UTC
Labels: area/gradle, kind/bug
