### ISSUE TITLE
Jandex IndexOutOfBOunds (ImmutableArrayList) when upgrading from keycloak 23 to 24.

### ISSUE THREAD

**Issue by rvanderboom** [quarkusio/quarkus#39701] opened 2024-03-26 14:44 UTC
### Describe the bug

Until keycloak 23 we do not have issues..
But after upgrading to keycloak 24 , the java build goes fine but when building the keycloak (with our custom providers) with docker(-compose) build we get an indexOutOfBounds :

```posh
 ERROR: Build failure: Build failed due to errors
5.668 	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: java.lang.ArrayIndexOutOfBoundsException: Index 2 out of bounds for length 2
5.668 	at org.jboss.jandex.ImmutableArrayList.get(ImmutableArrayList.java:14)
5.668 	at io.quarkus.arc.processor.Types.buildResolvedMap(Types.java:791)
5.668 	at io.quarkus.arc.processor.Types.getTypeClosure(Types.java:660)
5.668 	at io.quarkus.arc.processor.Types.getTypeClosure(Types.java:696)
5.668 	at io.quarkus.arc.processor.Types.getClassUnrestrictedTypeClosure(Types.java:508)
5.668 	at io.quarkus.arc.processor.BeanDeployment.findSkippedClassesMatching(BeanDeployment.java:1733)
5.668 	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:493)
5.668 	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:638)
5.668 	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:308)
5.668 	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:160)
5.668 	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:488)
5.668 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
5.668 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
5.668 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
5.668 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
5.668 	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:849)
5.668 	at io.quarkus.builder.BuildContext.run(BuildContext.java:256)
5.668 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
5.668 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
5.668 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
5.668 	at java.base/java.lang.Thread.run(Thread.java:840)
5.668 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

Tried many things:
* using forced different janex versions.
* excluding it
* quarkus 3.8.1, 3.8.3, 3.9.0

The all have same issue. Block to go futher.

### Expected behavior

expected that our docker build goes fine.
(it adds custom provider to the keycloak /provider folder).

Tried to debug but stuck

### Output of `uname -a` or `ver`

on every os (mac osx, linux).

### Output of `java -version`

openjdk version "17.0.10" 2024-01-16

### Quarkus version or git rev

24.0.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven build goes fine.

**Comment by sberyozkin** [comment] 2024-03-26 14:55
@rvanderboom Can you move this issue to the Keycloak repository please ?

**Comment by sberyozkin** [comment] 2024-03-26 14:57
@rvanderboom The Keycloak team will open a more specific Quarkus issue if it proves related to Quarkus

**Comment by manovotn** [comment] 2024-03-26 15:30
According to the log, it seems that Arc is trying to find the cause of an unsatisfied dependency during build which is this line:

> 5.668 at io.quarkus.arc.processor.BeanDeployment.findSkippedClassesMatching(BeanDeployment.java:1733)

And while extracting type closures, we get array index out of bounds.

Note that even if we nail down this exception (which we should) your build will then fail with unsatisfied dependency.
Plus I suppose you have some very "nice" type structure with generics which is causing this.
@rvanderboom any way we can reproduce this?

**Comment by rvanderboom** [comment] 2024-04-02 06:46
hey, 
Solved it, just last friday..

The issue is that we use quarkusTests (with annotation quarkustest), and with upgrade k24 i needed to add dependency glassfish because we received classnotfound erorrs during running the tests.

So then tests went fine, but somehow it added a wrong jakarta (ws api ?) version into the docker build which made if fail.
it took a long time since i put already the scope to <test>, but the solution was to put the scope to <provided>, which is strange since i thought scope test wouldn't have effect on docker build, but it has..

Thanks.

**Comment by gsmet** [comment] 2024-04-02 08:11
@rvanderboom I still think a reproducer would be of interest as I wouldn't expect such a low level error.

**Comment by geoand** [comment] 2024-06-05 11:09
Closing as we never got a reproducer

**Closed by geoand** 2024-06-05 11:09 UTC
Labels: kind/bug, area/arc, triage/needs-reproducer, area/keycloak

**Comment by robvanderboom** [comment] 2024-06-05 13:23
ok , fixed it somehow by excluding dependencies as we use real @QuarkustTest for our custom code and it seem to interfer with the build.
