### ISSUE TITLE
Quarkus CLI fails to work with encryption keys starting with "-q"

### ISSUE THREAD

**Issue by mocenas** [quarkusio/quarkus#43336] opened 2024-09-17 12:07 UTC
### Describe the bug

Using quarkus CLI to encrypt config fails, when manually specifying encryption key, starting with "-q". Like:
```
$: quarkus config encrypt --key=-qwi5grDHLU05KegUhfNNeA  "Joe Biden"
[ERROR] ❗  Expected parameter for option '--key' but found '-qwi5grDHLU05KegUhfNNeA'
```
This doesn't happen if I change either dash or "q" to anything else. 

Also this "unusable" key was automatically generated using `quarkus config encrypt whatever`. CLI printed out 
`The secret whatever was encrypted to ... with the generated encryption key (base64): -qwi5grDHLU05KegUhfNNeA`.

### Quarkus version or git rev

Quarkus cli 3.14.4

**Comment by mocenas** [comment] 2024-09-19 11:26
> Does that happen if you quote the value?

Yes it does:
```
$: quarkus config encrypt --key="-qwi5grDHLU05KegUhfNNeA"  "Joe Biden"
[ERROR] ❗  Expected parameter for option '--key' but found '-qwi5grDHLU05KegUhfNNeA'

$: quarkus config encrypt "--key=-qwi5grDHLU05KegUhfNNeA"  "Joe Biden"
[ERROR] ❗  Expected parameter for option '--key' but found '-qwi5grDHLU05KegUhfNNeA'
```

**Comment by maxandersen** [comment] 2024-09-19 17:41
Which os/shell are you using ?

**Comment by mocenas** [comment] 2024-09-20 06:16
> Which os/shell are you using ?

linux/bash

**Comment by radcortez** [comment] 2024-09-27 15:18
This seems to be an issue with `picocli` itself:

```java
@CommandLine.Command(name = "dashed")
public class DashedOption implements Callable<Integer> {
    @CommandLine.Option(names = "-x")
    String x;

    @CommandLine.Option(names = "--required", required = true)
    String required;

    @Override
    public Integer call() throws IOException {
        return 0;
    }

    public static void main(String[] args) {
        new CommandLine(new DashedOption()).execute(new String[]{"--required=-1"});
        new CommandLine(new DashedOption()).execute(new String[]{"--required=-"});
        new CommandLine(new DashedOption()).execute(new String[]{"--required=-a"});
        new CommandLine(new DashedOption()).execute(new String[]{"--required=-x"});
    }
}
```

Output:

```
Expected parameter for option '--required' but found '-x'
Usage: dashed --required=<required> [-x=<x>]
      --required=<required>

  -x=<x>
```

When one option value starts with another option it causes the issue. In the `quarkus config` case it is the `-q` option for quiet mode. It works as expected if we try the same command,  with `-dwi5grDHLU05KegUhfNNeA`.

@mocenas Would you mind opening an issue in https://github.com/remkop/picocli? I can do it, but since you found the issue, you may want to report it :)

**Comment by mocenas** [comment] 2024-09-30 13:13
> @mocenas Would you mind opening an issue in https://github.com/remkop/picocli? I can do it, but since you found the issue, you may want to report it :)

@radcortez - Can you handle this picocli issue? IMHO it should be handled by someone who has deeper technical knowledge of this, that I do.

**Comment by radcortez** [comment] 2024-09-30 22:02
Sure.

BTW, this of course happens with other CLI commands from Quarkus:

```bash
🌀 quarkus create app -x=-e
[ERROR] ❗  Expected parameter for option '--extensions' but found '-e'

Usage: quarkus create app [-Beh] [--dry-run] [--refresh] [--[no-]
                          registry-client] [--verbose] [--config=CONFIG]
                          [--description=DESCRIPTION] [--name=NAME]
                          [-o=OUTPUT-DIR] [-D=<String=String>]...
                          [--data=<String=String>]... [-x=EXTENSION[,
                          EXTENSION...]]... [-P=groupId:artifactId:version |
                          -S=platformKey:streamId] [--jbang | --maven |
                          --gradle | --gradle-kotlin-dsl]
                          [[--java=<javaVersion>] [--kotlin] [--scala]] [[--
                          [no-]wrapper] [--[no-]code] [--[no-]dockerfiles]
                          [--package-name=PACKAGE-NAME] [-c=<appConfig>]]
                          [[GROUP-ID:]ARTIFACT-ID[:VERSION]]

See 'quarkus create app --help' for more information.
```

**Comment by radcortez** [comment] 2024-09-30 22:07
https://github.com/remkop/picocli/issues/2340

**Comment by radcortez** [comment] 2024-10-08 13:39
We could prevent that behaviour with https://picocli.info/#_enable_consuming_option_names_or_subcommands

On the other hand, it may be dangerous due to:

_If an option is defined as arity = "*", this option will consume all remaining command line arguments following this option (until the [End-of-options delimiter](https://picocli.info/#_double_dash)) as parameters of this option._

The correct way to do it right now is to use quotes with escapes:

`quarkus config encrypt --key=\"-qwi5grDHLU05KegUhfNNeA\"  "Joe Biden"`

@ebullient what do you think?

**Comment by ebullient** [comment] 2024-10-09 11:44
Messy, but I think correct if clearly documented. I don't know how often a value followed by a dash is.

We could also (specifically for the encryption key) test out picocli's support for passwords, where you are prompted for the option if you don't specify it.

**Comment by radcortez** [comment] 2024-10-15 16:23
> Messy, but I think correct if clearly documented. I don't know how often a value followed by a dash is.

Not very often I guess. Encryption keys are generated. I've just generated a few thousand, and I didn't get any that would reproduce the issue, but it can happen.

> We could also (specifically for the encryption key) test out picocli's support for passwords, where you are prompted for the option if you don't specify it.

I guess we can add it, but it won't eliminate the option to set it in the command directly.

**Comment by ebullient** [comment] 2024-10-15 16:45
Yea.. my thinking is.. either people escape the quotes (because docs mention it), or they use the interactive option so the password isn't in your command history at all (which also avoids the leading dash interpretation problem)

**Comment by maxandersen** [comment] 2024-10-15 18:53
If quotes work we go with that.

**Comment by radcortez** [comment] 2024-10-16 09:46
Ok, so in that case, we can close this issue with the resolution to https://picocli.info/#_option_names_or_subcommands_as_option_values and use `"\` to escape the value.

**Closed by radcortez** 2024-10-16 09:46 UTC
Labels: kind/bug, triage/upstream, area/picocli
