### ISSUE TITLE
NullPointerException with HibernateValidator @Valid

### ISSUE THREAD

**Issue by smil2k** [quarkusio/quarkus#7923] opened 2020-03-17 20:48 UTC
**Describe the bug**

Validator annotations can be placed to various places. Example this is probably not effective:

public class StringBasedIdentity implements Serializable, Comparable<StringBasedIdentity> {

    private static final long serialVersionUID = 1L;

    @NotNull
    @NotEmpty
    private final String name;

...

}

**Expected behavior**
 Quarkus processor should be able to pinpoint the error with at least the location of the annotation should be provided as a hint.

**Actual behavior**
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.2.1.Final:build (default) on project sched-schedule-app: Failed to build a runnable JAR: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.NullPointerException
[ERROR]         at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:191)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]         at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
[ERROR]         at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
[ERROR]         at java.lang.Thread.run(Thread.java:748)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:479)

**To Reproduce**
1. Create file
2. Run build

**Environment (please complete the following information):**
 - Quarkus version 1.2.1

**Comment by gsmet** [comment] 2020-03-17 21:15
Could you provide a reproducer? thanks.

**Comment by geoand** [comment] 2020-03-18 08:10
Hi,

Would you be able to see if `1.3.0.Final` (you'll have to switch to `quarkus-bom` instead of `quarkus-universe-bom` unless you test tomorrow when the latter should also be available) exhibits the same behavior?

**Comment by smil2k** [comment] 2020-03-18 09:49
Hi,

Strange it seems that I'm no longer able to reproduce it.
I'll reopen the ticket if comes back. 

I'm having a multi project setup with jandex on all dependencies. 
I had to remove some @Valid on method parameters.   

Maybe I hit this remark:
```// FIXME this won't work in the case of synthetic parameters```

Cheers,

Tamas

**Comment by gsmet** [comment] 2020-03-18 10:01
> I had to remove some @Valid on method parameters.

You shouldn't have to do that.

So, if you do, please open issues with reproducer and I'll have a look.

Thanks!

**Comment by geoand** [comment] 2020-03-18 10:03
I think we really need a reproducer, because looking at the stacktrace, there should never be NPE at that point.
So perhaps there is some corner case we haven't accounted for and which your reproducer would uncover :)

**Comment by smil2k** [comment] 2020-03-18 10:06
I tried to create one, but I failed. Maybe if I'm hitting it again, I'll reopen this case.

**Comment by luis-martinez-herrera** [comment] 2020-03-18 20:31
Hello @smil2k  , I have the same problem, project Quarkus parent A with Quarkus submodule B. If I run project B with @Valid there are no problems, but when added as a maven dependency the same error occurs.

![image](https://user-images.githubusercontent.com/5863787/77004305-ddddce80-692c-11ea-868b-4407a6c7dcb8.png)

If I remove all @_Valid_ everything works.

`public Response save(@Valid UserDto dto)`

**Comment by geoand** [comment] 2020-03-18 20:33
@luis-martinez-herrera do you perhaps have a reproducer project we could look at?

**Comment by luis-martinez-herrera** [comment] 2020-03-18 22:27
Sorry for the delay: https://github.com/luis-martinez-herrera/quarkusio-7923-reproducer

The error occurs when using an abstract class, in the example it would be **AbstractResource**.

**Comment by geoand** [comment] 2020-03-19 07:12
Thank you @luis-martinez-herrera, I'll look into it

**Comment by geoand** [comment] 2020-03-19 08:45
This looks like some kind of bug in Jandex. I'm in the process of debugging Jandex to try and figure out exactly what the problem is.

**Comment by smil2k** [comment] 2020-03-19 08:54
Let's reopen the ticket then. Adding Jandex caused the issue at my side as well.

**Comment by geoand** [comment] 2020-03-19 09:06
I have opened https://github.com/wildfly/jandex/pull/74 which fixes the issue

**Comment by geoand** [comment] 2020-03-21 08:35
Closed via f9978cfc95e088e037f69e10ff32749808a50cb6

**Comment by geoand** [comment] 2020-03-21 15:02
Reopening as f9978cf was reverted

**Closed** 2020-03-21 16:28 UTC
Labels: kind/bug
