### ISSUE TITLE
Keycloak responds requires Javax Response in Quarkus 3

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#34027] opened 2023-06-14 03:57 UTC
### Describe the bug

It seems like the keycloak admin client relies on the Javax version of Response, even though it outwardly returns the Jakarta version.

### Actual behavior

```
TestUserService.java:171: error: cannot access Response
			try (Response response = usersResource.create(userRep)) {
			                                             ^
  class file for javax.ws.rs.core.Response not found
estUserService.java:173: error: incompatible types: jakarta.ws.rs.core.Response cannot be converted to javax.ws.rs.core.Response
				userId = CreatedResponseUtil.getCreatedId(response);
				 
```

### How to Reproduce?

`Response response = usersResource.create(userRep)`

### Output of `java -version`

17

### Quarkus version or git rev

3.1.1

### Additional information

Referenced error: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/actions/runs/5262713051/jobs/9512158135#step:4:2442

Location: https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/0c9a526fd949131845be1bd2af8f35724e998b0f/software/open-qm-base-station/src/test/java/tech/ebp/oqm/baseStation/testResources/data/TestUserService.java#L171

Gradle dependencies:

https://github.com/Epic-Breakfast-Productions/OpenQuarterMaster/blob/0c9a526fd949131845be1bd2af8f35724e998b0f/software/open-qm-base-station/build.gradle#L82
```
	testImplementation 'com.github.dasniko:testcontainers-keycloak:2.5.0'
	testImplementation 'io.quarkus:quarkus-keycloak-admin-client-reactive'
```

**Comment by gsmet** [comment] 2023-06-14 07:38
Could you please provide a simple Maven reproducer because I suspect something is off? Thanks.

**Comment by sberyozkin** [comment] 2023-06-14 10:49
I've added
```
@GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("user")
    public Response getUser() {
        UserRepresentation user = new UserRepresentation();
        user.setFirstName("alice");
        Response r = keycloak.realm("quarkus").users().create(user);
        return r;
    }
```

to `integration-tests/keycloak-authorization/.../AdminClientResource.java` and updated `AdminClientTestCase` to call on a `/user` path, no problem, works as expected.

**Comment by GregJohnStewart** [comment] 2023-06-14 12:19
Added more info, sorry was rather late when I made the issue. I'll work on a simpler reproducer, try to get it out today

**Comment by GregJohnStewart** [comment] 2023-06-14 23:51
Tried making a reproducer, but stuck on the code.quarkus.io template not playing well https://github.com/quarkusio/quarkus/discussions/34046

**Comment by sberyozkin** [comment] 2023-06-15 17:48
@GregJohnStewart You can use CLI to pull the required extensions, various quickstarts show how to do it

**Comment by GregJohnStewart** [comment] 2023-06-17 19:31
Okay, got a proof going. Interestingly, not the same issue I am seeing on the OQM project, but possibly a similar root; looks like the Keycloak TestContainer is still on javax:

https://github.com/GregJohnStewart/quarkus-proofs/tree/main/34027-keycloak

**Comment by sberyozkin** [comment] 2023-06-20 12:13
Thanks @GregJohnStewart for coming up with this reproducer, that Keycloak TestContainer implementation is not part of the Quarkus project.

You can replace that dependency with the `quarkus-oidc` in the test scope and it will launch a Keycloak container for you, default realm - `quarkus`, client id - `quarkus-app`, client-secret - `secret`, users: `alice` (`admin`, `user` roles), `bob` (`user` role). It can be configured to import custom realms, etc:
https://quarkus.io/guides/security-openid-connect-dev-services

You don't have to use Dev UI, it will do for testing as well.

I think we should close this issue. In meantime, please try to replace the dependency, and I'll help with answering the related questions. If you prefer to continue using the Keycloak test container dependency - then please work with that project, open an issue there

Cheers

**Closed by sberyozkin** 2023-06-20 12:13 UTC
Labels: kind/bug, triage/needs-reproducer, area/keycloak
