### ISSUE TITLE
Separate quarkus-flyway from flyway property config

### ISSUE THREAD

**Issue by encodeering** [quarkusio/quarkus#14573] opened 2021-01-25 10:51 UTC
**Description**
Flyway can be configured using a [plain property file](https://flywaydb.org/documentation/configuration/configfile#reference) and this file may change from release to release. 

For instance `flyway.sqlMigrationPrefix` can be configured through quarkus, whereby `flyway.sqlMigrationSeparator` can actually not. 

I am not aware if those properties, attach to quarkus config, are relevant to the ahead of time compilation, but I would see the following benefits

* strict separation of the configuration for the quarkus integration and flyway migration
* full support of all flyway properties without library changes on release changes
* flyway properties file can be used during the build to generate java code using the very same configuration
* quarkus feature about named datasources can still be supported by pointing the reference to the correct file

**Implementation ideas**

A quarkus flyway property replacing all other flyway properties. A breaking configuration change might be favorable to avoid pitfalls with redundant or repeated configurations

`quarkus.flyway.config.file=one-of ([classpath:]/.../flyway.properties | file:/usr/.../flyway.properties)`

**Comment by gastaldi** [comment] 2022-10-26 01:30
Hello! 

By design choice we don't configure Flyway using `flyway.properties` because (for optimization purposes) some properties are [build-time](https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceBuildTimeConfig.java) while others are [run-time](https://github.com/quarkusio/quarkus/blob/main/extensions/flyway/runtime/src/main/java/io/quarkus/flyway/runtime/FlywayDataSourceRuntimeConfig.java).

You can find the supported properties here: https://quarkus.io/guides/flyway#quarkus-flyway_configuration

I'm closing it since this is not something we plan to do

**Closed by gastaldi** 2022-10-26 01:30 UTC
Labels: kind/enhancement, area/flyway
