### ISSUE TITLE
Add an info-like endpoint to get app version

### ISSUE THREAD

**Issue by laurentperez** [quarkusio/quarkus#17593] opened 2021-06-01 12:33 UTC
## Description

I found no built in solution to get the app version using default endpoints (smallrye, MP)

There have been discussions on zulip chat about a Spring-like actuator endpoint (@agoncal ). Because enabling Dev UI in prod is a no no. Chat : https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Can't.20we.20have.20DevUI.20in.20prod.20.3F

## Implementation ideas

Enable some minimal endpoint to get app version and other useful info found in META-INF/ metadata

See https://docs.spring.io/spring-boot/docs/current/reference/html/actuator.html#actuator.endpoints.info.build-information

**Comment by famod** [comment] 2021-06-04 23:06
With endpoint you mean something that produces JSON?

**Comment by agoncal** [comment] 2021-06-05 10:11
I don't know the internals of DevUI (it might return JSon, I don't know) but this endpoint could also return HTML (with Qute templates). JSON for command line and HTML for Browser

**Comment by laurentperez** [comment] 2021-06-09 15:23
> With endpoint you mean something that produces JSON?

yes, over http.

**Comment by geoand** [comment] 2021-08-03 16:27
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/13598

**Closed by geoand** 2021-08-03 16:27 UTC
Labels: kind/enhancement, triage/needs-triage
