### ISSUE TITLE
mongodb-panache queries cache 

### ISSUE THREAD

**Issue by diogocarleto** [quarkusio/quarkus#9802] opened 2020-06-04 18:01 UTC
Hi guys, how are you?

Guys I like a lot of the ActiveRecord pattern, but I'm facing a issue that made change my mind and use repositories. 

Quarkus cache extension brings a lot of facilities to cache method results, but I couldn't use this inside a query method in my mongo entity (maybe I made some mistake).

Is there a way we support the cache extensions inside Panache?

Best,

**Comment by loicmathieu** [comment] 2020-06-05 06:54
@diogocarleto can you explain why you cannot use cache with Panache Entities ? Maybe with a code snippet of what you want to achieve ?

**Comment by diogocarleto** [comment] 2020-06-05 21:22
Sure, @loicmathieu I'm trying use the quarkus cache extension.
Some like that

```
public class Category extends PanacheMongoEntityBase {
    public String name;

    @CacheResult(cacheName = "test")
    public static List<Category> findAllWithCache() {
        return findAll().list();
    }

}
```

What I'm missing?
Best.

**Comment by loicmathieu** [comment] 2020-06-08 10:45
@FroMage Quarkus cache uses a CDI interceptor, and CDI interceptors didn't work with static methods right ? This is a known limitation of the Active Record pattern I think ?

**Comment by FroMage** [comment] 2020-06-08 12:24
@mkouba merged support for interceptors on static methods recently, so this should now work, but an example would allow us to make sure.

**Comment by mkouba** [comment] 2020-06-08 12:35
@FroMage not yet... there were some troubles with quarkus CI.

**Comment by diogocarleto** [comment] 2020-06-08 13:21
Hi, guys sorry for don't answer before.

class Person {
    public String name;
    public Integer age;

    @CacheResult(cacheName = "test")
    public static List<Person> findPersonByAge(Integer age) {
        return find("{age: ?1}", age).list();
    }
}



Quarkus cache extension u

**Comment by mkouba** [comment] 2020-06-08 14:37
So this should work in master now. Let me know if you run into problems...

**Comment by diogocarleto** [comment] 2020-06-13 12:03
Hi guys, I've just tested using master, and the cache is not working. 
Maybe I'm missing something.

In the example I sent, I'm calling the method is this way:

`Person.findPersonByAge(10);`

Best,

**Comment by diogocarleto** [comment] 2020-06-13 12:17
I did another test using the `PersonRepository` and declaring `findPersonByAge` as static and also non static.

Even in `PersonRepository`, when the `findPersonByAge` is static, the cache doesn't work. 

Best,

**Comment by mkouba** [comment] 2020-06-15 07:24
Hm, you're right. The problem is that `io.quarkus.cache.CacheResult` is not a regular interceptor binding. There is a special annotation transformer that maps `@CacheResult` to `@CacheResultInterceptorBinding` and we don't support bindings added by transformers yet (for static method interception).

**Comment by mkouba** [comment] 2020-06-15 09:56
@diogocarleto this PR should help: https://github.com/quarkusio/quarkus/pull/10005

**Comment by diogocarleto** [comment] 2021-02-16 20:32
Sorry for my delay, now it is working.

Thanks @mkouba, @loicmathieu and @FroMage.

Best,

**Comment by loicmathieu** [comment] 2021-02-16 21:31
Thanks to confirm the fix. 
I'm closing it.

**Closed** 2021-02-16 21:31 UTC
Labels: area/panache, kind/enhancement
