### ISSUE TITLE
Unable to add oidc tenants with runtime configuration

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#29417] opened 2022-11-22 18:03 UTC
### Describe the bug

I try to add new oidc tenants with runtime configuration. As far as I see in the documentation, the properties are not buildtime-only. 
When adding following environment-variables for configuration:
```properties
QUARKUS_OIDC_XXX_AUTH_SERVER_URL=https://xxx.test
QUARKUS_OIDC_XXX_TENANT_ENABLED=true
QUARKUS_OIDC_XXX_TENANT_ID=xxx
```
I assume to have a tenant xxx usable. But in the `OidcConfig`, the tenant is missing in the namedTenanants and can therefore not be used as expected.

### Expected behavior

Tenants can be added with environment variables at runtime. 

### Actual behavior

Tenants added with environment variables only are ignored.

### Output of `java -version`

17

### Quarkus version or git rev

2.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradlew

**Comment by joggeli34** [comment] 2022-11-22 18:45
Probably related to #29325

**Comment by sberyozkin** [comment] 2022-11-23 15:29
Hi @joggeli34 I think the hint suggested at https://github.com/quarkusio/quarkus/issues/29325#issuecomment-1324912729 is the best option we have, can please you try to apply the same idea to the oidc tenants configuration ?

**Comment by joggeli34** [comment] 2022-11-25 11:33
Yes, it works when adding a configuration to the application.properties.
But for our deployment we configure only with environment variables and do not have an additional appliation.properties file to the one included at build time. 

Adding a configuration which don't have a `-` in it's key also helps. So for example adding:
```properties
QUARKUS_OIDC_XXX_PROXY_PORT=80
```
helps so that the oidc tenant is recognized and created. 

But additionally, the property for the tenant-id is ignored. I think this should be used instead of the "name" for the tenant. Then we could even support tenants with a `-` or not lower case. 
So then we could use following configuration to add a tenant with name "xXx-yYy":
```properties
QUARKUS_OIDC_XXXYYY_PROXY_PORT=80
QUARKUS_OIDC_XXXYYY_AUTH_SERVER_URL=https://xXx-yYy.test
QUARKUS_OIDC_XXXYYY_TENANT_ENABLED=true
QUARKUS_OIDC_XXXYYY_TENANT_ID=xXx-yYy
```

As workaround, we currently implemented a custom `TenantConfigResolver` using custom properties supporting a tenant-id value.

**Comment by sberyozkin** [comment] 2023-02-16 22:43
@joggeli34 Sorry for the delay, can you have a look at #30369 and let us know if that helps with your question ? I'm just no sure yet what kind of action may be necessary here

**Comment by geoand** [comment] 2023-07-21 11:05
@sberyozkin is this still relevant?

**Comment by michalvavrik** [comment] 2023-10-26 17:53
This is not a bug, but documented SR config behavior here https://quarkus.io/guides/config-reference#environment-variables, all that you need to do is to add properties in dotted format in config source with lower priority than environment variables (app properties, mp config file, ...). SR config replaces underscore with dots by default and you need to help it to resolve proper name.

+1 for closing this issue

**Closed** 2023-10-26 17:54 UTC
Labels: kind/bug, area/oidc, triage/consider-closing
