### ISSUE TITLE
Occasional io.netty.util.IllegalReferenceCountException: refCnt: 0 when performing REST operations that stream responses

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#22263] opened 2021-12-15 21:35 UTC
### Describe the bug

We have several REST services that stream the Response to the client via javax.ws.rs.core.StreamingOutput and we occasionally get these errors in the logs.  We do not know what is triggering these.

We did upgrade to 2.4.2.Final not too long ago but have no data that suggests that is the cause.

2021-12-15 04:11:23,645 ERROR (executor-thread-776) [com.bs.dl.streaming.AppStreamingOutput_Subclass.writeStream()] Exception streaming query result data : java.io.IOException: java.io.IOException: io.vertx.core.VertxException: Connection was closed
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:81)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:45)
	at org.jboss.resteasy.util.CommitHeaderAsyncOutputStream.write(CommitHeaderAsyncOutputStream.java:57)
	at com.bs.dl.streaming.AppStreamingOutput.writeStream(AppStreamingOutput.java:212)
	at com.bs.dl.streaming.AppStreamingOutput.lambda$processResultStream$0(AppStreamingOutput.java:272)
	at java.base/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:658)
	at org.hibernate.query.spi.StreamDecorator.forEach(StreamDecorator.java:153)
	at com.bs.dl.streaming.AppStreamingOutput.processResultStream(AppStreamingOutput.java:267)
	at com.bs.dl.streaming.AppStreamingOutput.queryStream(AppStreamingOutput.java:257)
	at com.bs.dl.streaming.AppStreamingOutput.write(AppStreamingOutput.java:245)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write$$superforward1(AppStreamingOutput_Subclass.zig:106)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass$$function$$1.apply(AppStreamingOutput_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:41)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew_Bean.intercept(TransactionalInterceptorRequiresNew_Bean.zig:335)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write(AppStreamingOutput_Subclass.zig:171)
	at com.bs.dl.streaming.AppStreamingOutput_ClientProxy.write(AppStreamingOutput_ClientProxy.zig:680)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:20)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: io.vertx.core.VertxException: Connection was closed
	at io.quarkus.resteasy.runtime.standalone.VertxBlockingOutput.write(VertxBlockingOutput.java:79)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpResponse.writeBlocking(VertxHttpResponse.java:172)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:74)
	... 57 more
Caused by: io.vertx.core.VertxException: Connection was closed

2021-12-15 04:11:23,646 ERROR (executor-thread-776) [com.bs.dl.streaming.AppStreamingOutput_Subclass.writeStream()] Exception streaming query result data : java.io.IOException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:81)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:45)
	at org.jboss.resteasy.util.CommitHeaderAsyncOutputStream.write(CommitHeaderAsyncOutputStream.java:57)
	at com.bs.dl.streaming.AppStreamingOutput.writeStream(AppStreamingOutput.java:212)
	at com.bs.dl.streaming.AppStreamingOutput.processResultStream(AppStreamingOutput.java:286)
	at com.bs.dl.streaming.AppStreamingOutput.queryStream(AppStreamingOutput.java:257)
	at com.bs.dl.streaming.AppStreamingOutput.write(AppStreamingOutput.java:245)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write$$superforward1(AppStreamingOutput_Subclass.zig:106)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass$$function$$1.apply(AppStreamingOutput_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:41)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew_Bean.intercept(TransactionalInterceptorRequiresNew_Bean.zig:335)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write(AppStreamingOutput_Subclass.zig:171)
	at com.bs.dl.streaming.AppStreamingOutput_ClientProxy.write(AppStreamingOutput_ClientProxy.zig:680)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:20)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:289)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:68)
	... 52 more

2021-12-15 04:11:23,646 ERROR (executor-thread-776) [com.bs.dl.streaming.AppStreamingOutput_Subclass.write()] Exception streaming data from App: java.lang.RuntimeException: java.io.IOException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at com.bs.dl.streaming.AppStreamingOutput.writeStream(AppStreamingOutput.java:221)
	at com.bs.dl.streaming.AppStreamingOutput.processResultStream(AppStreamingOutput.java:286)
	at com.bs.dl.streaming.AppStreamingOutput.queryStream(AppStreamingOutput.java:257)
	at com.bs.dl.streaming.AppStreamingOutput.write(AppStreamingOutput.java:245)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write$$superforward1(AppStreamingOutput_Subclass.zig:106)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass$$function$$1.apply(AppStreamingOutput_Subclass$$function$$1.zig:33)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:132)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.doIntercept(TransactionalInterceptorRequiresNew.java:41)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew.intercept(TransactionalInterceptorRequiresNew.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequiresNew_Bean.intercept(TransactionalInterceptorRequiresNew_Bean.zig:335)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at com.bs.dl.streaming.AppStreamingOutput_Subclass.write(AppStreamingOutput_Subclass.zig:171)
	at com.bs.dl.streaming.AppStreamingOutput_ClientProxy.write(AppStreamingOutput_ClientProxy.zig:680)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37)
	at org.jboss.resteasy.plugins.providers.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:20)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$writeTo$1(ServerWriterInterceptorContext.java:79)
	at io.quarkus.resteasy.runtime.standalone.VertxHttpRequest$VertxExecutionContext.executeBlockingIo(VertxHttpRequest.java:251)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.writeTo(ServerWriterInterceptorContext.java:79)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.syncProceed(AbstractWriterInterceptorContext.java:245)
	at org.jboss.resteasy.core.interception.jaxrs.AbstractWriterInterceptorContext.getStarted(AbstractWriterInterceptorContext.java:170)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.lambda$getStarted$0(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.aroundWriteTo(ServerWriterInterceptorContext.java:93)
	at org.jboss.resteasy.core.interception.jaxrs.ServerWriterInterceptorContext.getStarted(ServerWriterInterceptorContext.java:73)
	at org.jboss.resteasy.core.ServerResponseWriter.lambda$writeNomapResponse$3(ServerResponseWriter.java:163)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerResponseContextImpl.filter(ContainerResponseContextImpl.java:404)
	at org.jboss.resteasy.core.ServerResponseWriter.executeFilters(ServerResponseWriter.java:252)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:101)
	at org.jboss.resteasy.core.ServerResponseWriter.writeNomapResponse(ServerResponseWriter.java:74)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeResponse(SynchronousDispatcher.java:594)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:524)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:135)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:90)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.io.IOException: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:81)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:45)
	at org.jboss.resteasy.util.CommitHeaderAsyncOutputStream.write(CommitHeaderAsyncOutputStream.java:57)
	at com.bs.dl.streaming.AppStreamingOutput.writeStream(AppStreamingOutput.java:212)
	... 49 more
Caused by: io.netty.util.IllegalReferenceCountException: refCnt: 0
	at io.netty.buffer.AbstractByteBuf.ensureAccessible(AbstractByteBuf.java:1454)
	at io.netty.buffer.AbstractByteBuf.ensureWritable0(AbstractByteBuf.java:289)
	at io.netty.buffer.AbstractByteBuf.ensureWritable(AbstractByteBuf.java:280)
	at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1073)
	at io.quarkus.resteasy.runtime.standalone.VertxOutputStream.write(VertxOutputStream.java:68)
	... 52 more

### Expected behavior

Streaming responses should not have any errors.

### Output of `java -version`

JDK 11 on Linux (not on PROD system to get revision)

### Quarkus version or git rev

2.4.2.Final

**Comment by gsmet** [comment] 2021-12-15 21:46
/cc @stuartwdouglas 
@dhoffer maybe it could help if you put together a small reproducer showing the pattern you are using (not necessarily reproducing the issue as it might be hard but at least showing what you're doing)

**Comment by dhoffer** [comment] 2021-12-15 23:28
Okay I will try to put something together that shows code pattern.  These are very random.  Usually it just works.

**Comment by stuartwdouglas** [comment] 2021-12-15 23:29
It's possible that this commit coming in 2.6 will fix it: https://github.com/quarkusio/quarkus/commit/350965b6f19b322efb38d7babac505b23ad39fab

**Comment by dhoffer** [comment] 2021-12-15 23:39
I am eager to try that once 2.6 is available.  I don't think I can use your CR1 as we use your quarkus-universe-bom and I don't think those are available for CRs let me know if that's not the case.

**Comment by stuartwdouglas** [comment] 2021-12-15 23:56
Actually I think I can see the issue, you could get this if you attempt to write after an exception has been thrown.

**Comment by dhoffer** [comment] 2021-12-16 00:18
I think this maybe the pattern then.

1. We call outputStream.write(bs) to write byte[] of one record
2. That threw java.io.IOException: io.vertx.core.VertxException: Connection was closed
3. We catch that and turn that into a new RuntimeException(e)
4. Our higher level catches that and abandons further reads/writes BUT we have the following code in a finally clause
5. writeStream(outputStream, "]".getBytes()) This is because our streams of records are always Json arrays so we have to manually add the closing bracket to make valid Json array.  So we do make this one final write after an exception.

Does your commit above allow this now?  I think we want to send this to client else they will have a garbage Json response.  Yes it's incomplete if exception but would be worse to have bad Json also.

Also what is causing the io.vertx.core.VertxException that starts this chain of events?

**Comment by stuartwdouglas** [comment] 2021-12-16 00:25
That would do it. The original exception is because the connection has failed (e.g. the user closed the browser), once you have one failed write all subsequent writes will also fail, so writing the closing bracket will have no effect.

**Comment by stuartwdouglas** [comment] 2021-12-16 00:26
With my commit you will just get a more explicit 'stream is closed' exception.

**Comment by dhoffer** [comment] 2021-12-16 01:13
Okay yes I agree if the user initiated the close then all this is on them and not server errors at all but how can I know definitively the user broke the connection?  E.g. how can I know why 'stream is closed'?  Will your change effect the original VertxException or the second IllegalReferenceCountException?  Ideally I'd like to know definitively on the first if the user initiated the close so I could abort further DB reads and writes and not clog up the logs with all these non-server errors.

**Comment by stuartwdouglas** [comment] 2021-12-16 02:55
When you get the first exception you know the connection is broken. There is no real way to know who initiated it (short of looking at the message text and making a guess), but the important point is that from that point on you are not going to be able to send any more data.

**Comment by gsmet** [comment] 2021-12-16 09:23
@dhoffer it won't help you there but for the record we are now publishing the universe bom for CRs too.

**Comment by dhoffer** [comment] 2021-12-16 14:57
@gsmet That's great info that CRs now have the universe bom that will be really helpful.  When will @stuartwdouglas commit above be in some release/CR?  I'm eager to try that so I can catch what we assume are client dropped connections so I can handle that better in our code.

**Comment by gsmet** [comment] 2021-12-16 15:04
When it's merged, it's going to be in our nightly (Europe time) snapshots the next day.

As for releases, the 2.6.0.Final core bits are already built for next week's release so this will be in 2.6.1.Final that will probably happen on December 29th - not really supposed to work but I think I will build a release anyway as I prefer for patch releases to not be enormous.

**Comment by dhoffer** [comment] 2021-12-16 15:14
Thanks for the info/update, I will get 2.6.1.Final as soon as published.

**Closed** 2021-12-17 03:26 UTC
Labels: kind/bug, area/resteasy
