### ISSUE TITLE
Quarkus 3.15 - jdbc leak after running liquibase

### ISSUE THREAD

**Issue by HugoMRAmaro** [quarkusio/quarkus#44042] opened 2024-10-23 11:06 UTC
### Describe the bug

Hello,
I've just download a zip form quarkus starter, and run it with some liquibase xml files.
When the application starts I can see the following in the logs:

WARN  [io.ag.pool] (main) Datasource 'users': JDBC resources leaked: 18 ResultSet(s) and 0 Statement(s)

I believe it's a bug in quarkus 3.15 LTS version?

We are migrating from 3.8 to 3.15 and when we tried to update the pom we got the same issue and it seems that the application is consuming much more memory than before.

### Expected behavior

no JDBC resources leaked after starting the application

**Comment by yrodiere** [comment] 2024-10-23 12:21
> WARN [io.ag.pool] (main) Datasource 'users': JDBC resources leaked: 18 ResultSet(s) and 0 Statement(s)

This means Liquibase opened `ResultSets`, but didn't close them. Agroal warns about this when closing the connection. And, crucially, Agroal also closes the `ResultSets`, so there is no _actual_ leak -- just bad code somewhere.

I don't think Quarkus itself opens `ResultSets` in the Liquibase extension, so the "leaks" are likely in Liquibase itself. Probably introduced by an upgrade of Liquibase? I'll let people familiar with Liquibase comment.

**Comment by yrodiere** [comment] 2024-10-23 12:22
> This means ~Liquibase~ someone opened `ResultSets`, but didn't close them. Agroal warns about this when closing the connection. And, crucially, Agroal also closes the `ResultSets`, so there is no _actual_ leak -- just bad code somewhere.

@gsmet I'd be tempted to just suppress these warnings, by the way. Since Agroal fixes the problems anyway, it seems to me `WARN` is too noisy -- at best this would deserve `DEBUG` level.

**Comment by gsmet** [comment] 2024-10-23 12:35
Yeah, they are manipulating ResultSets a lot in Liquibase so I suspect a bug on their side with their ``ResultSet``s not being properly closed. If I were you, I would reproduce it with plain Liquibase, add a breaking point into the ResultSet constructor and close method and see where they are not properly closed.

If you don't feel like doing it, please provide a reproducer.

@yrodiere yeah maybe we should demote these messages to DEBUG. Now I'm not sure it's something we can do at the Quarkus level as the message has a broad category.

**Comment by yrodiere** [comment] 2024-10-23 12:48
> [@yrodiere](https://github.com/yrodiere) yeah maybe we should demote these messages to DEBUG. Now I'm not sure it's something we can do at the Quarkus level as the message has a broad category.

Created #44047 to track this.

**Comment by HugoMRAmaro** [comment] 2024-10-24 13:29
Just to give some extra info: if I try to use an older version from liquibase the warning just disappear from the logs:
<dependency>
<groupId>io.quarkus</groupId>
<artifactId>quarkus-liquibase</artifactId>
<exclusions>
<exclusion>
<groupId>org.liquibase</groupId>
<artifactId>liquibase-core</artifactId>
</exclusion>
</exclusions>
</dependency>
<dependency>
<groupId>org.liquibase</groupId>
<artifactId>liquibase-core</artifactId>
<version>4.28.0</version>
</dependency>
<dependency>

**Comment by gsmet** [comment] 2024-11-16 15:00
I will close this one as it's a Liquibase issue and @yrodiere created a separate issue to avoid this verbosity in Quarkus.

**Closed by gsmet** 2024-11-16 15:00 UTC
Labels: kind/bug, area/liquibase, area/jdbc
