### ISSUE TITLE
Static producer methods and fields causes containing class being recognized as beans

### ISSUE THREAD

**Issue by slinstaedt** [quarkusio/quarkus#25050] opened 2022-04-20 17:08 UTC
### Describe the bug

When defining a `static` producer method or field, quarkus is interpreting the (method or field) containing class as bean, causing problems
- when the containing class itself is defined as bean via a producer
- when the containing class itself declares "dependencies" (via constructor), that have never been meant to be fulfillfed.

In this example, not only a bean of type `Role` (as producer field) is registered, but also a bean of type `User` (as class).
```
record Role(String value) {
}

@Entity
class User {

	@Produces
	public static final Role ADMINISTRATOR = new Role("admin");
}

```

### Expected behavior

`static` producer method or field should not cause the containing class being registered as bean, if no other non-static member is annotated with CDI annotations.

### Actual behavior

`static` producer method or field should cause the containing class being registered as bean, though no other bean-defining annotation is used.

### How to Reproduce?

See example above

### Output of `uname -a` or `ver`

Darwin sl-macbook.fritz.box 19.6.0 Darwin Kernel Version 19.6.0: Tue Feb 15 21:39:11 PST 2022; root:xnu-6153.141.59~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "18" 2022-03-22 OpenJDK Runtime Environment Homebrew (build 18+0) OpenJDK 64-Bit Server VM Homebrew (build 18+0, mixed mode, sharing)

### Quarkus version or git rev

2.8.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5

**Comment by geoand** [comment] 2022-04-21 05:21
I am not even sure this is valid usage of CDI annotations, but I'll let the experts comment :)

**Comment by mkouba** [comment] 2022-04-21 06:11
A [producer method/field](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#producer_method) _must_ be a method of a managed bean class. So I believe that quarkus follows the rules of the spec. Note that entities are by nature non-contextual objects and I would never recommend to declare a producer in an entity class.

**Comment by manovotn** [comment] 2022-04-21 07:04
From CDI specification:

> A producer method must be a default-access, public, protected or private, non-abstract method of a managed bean class. A producer method may be either static or non-static.
> A producer field must be a default-access, public, protected or private, field of a managed bean class. A producer field may be either static or non-static.

Therefore, Quarkus behaves correctly. 

Quarkus goes beyond specification in that when it detects a producer, it automatically considers its class a bean. This is not required. In fact, I think in other CDI impls, your producer would be simply ignored.

**Comment by geoand** [comment] 2022-04-21 08:03
So should we close this?

**Comment by mkouba** [comment] 2022-04-21 08:30
> Quarkus goes beyond specification in that when it detects a producer, it automatically considers its class a bean. This is not required. In fact, I think in other CDI impls, your producer would be simply ignored.

I'm not so sure about the `bean-discovery-mode=all`. In any case, it's not a good idea and users should not rely on behavior ;-).

**Comment by mkouba** [comment] 2022-04-21 08:38
> So should we close this?

It's definitely not a bug. On the other hand, we could extend the functionality of [`quarkus.arc.detect-wrong-annotations`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.detect-wrong-annotations) and detect this use case and fail the build...

**Comment by manovotn** [comment] 2022-04-21 09:13
> > Quarkus goes beyond specification in that when it detects a producer, it automatically considers its class a bean. This is not required. In fact, I think in other CDI impls, your producer would be simply ignored.
> 
> I'm not so sure about the `bean-discovery-mode=all`. In any case, it's not a good idea and users should not rely on this behavior ;-).

True, but Quaruks doesn't support that so I assumed discovery `annotated` :)

**Comment by slinstaedt** [comment] 2022-04-22 07:23
Wow, that was fast feedback. For non-static members the requirement makes absolute sense. Otherwise getting the produces instance would be impossible. For static-members though, it is not. Just for my curiosity: Is there an actual need for static producer being located in a managed bean class?

**Comment by slinstaedt** [comment] 2022-04-22 07:29
> FTR the following paragraph can be found in the [Weld docs](https://docs.jboss.org/weld/reference/3.1.9.Final/en-US/html_single/#_managed_beans):
> 
> _"According to this definition, JPA entities are technically managed beans. However, entities have their own special lifecycle, state and identity model and are usually instantiated by JPA or using new. Therefore we don’t recommend directly injecting an entity class. We especially recommend against assigning a scope other than `@Dependent` to an entity class, since JPA is not able to persist injected CDI proxies. "_
> 
> > when the containing class itself declares "dependencies" (via constructor)
> 
> AFAIK the entity class must have a no-arg constructor. So what kind of problems do you actually observe? @slinstaedt

For entity classes that have a protected default constructor (meeting JPA requirements), but also a public constructor with some parameters (meeting business requirements), Quarkus will fail to start, because this constructors "dependencies" (normally other entities or domain values, like a LocalDate) are not injected, but handed over when programmatically calling the constructor. 

One need to either 
- move the static member to some other cdi managed class
- have a need to veto the current class for being a cdi managed class

**Comment by mkouba** [comment] 2022-04-22 07:58
> Is there an actual need for static producer being located in a managed bean class?

Well, at least the class must be discovered.

> For entity classes that have a protected default constructor (meeting JPA requirements), but also a public constructor with some parameters (meeting business requirements), Quarkus will fail to start, because this constructors "dependencies" (normally other entities or domain values, like a LocalDate) are not injected, but handed over when programmatically calling the constructor.

@slinstaedt That's odd. Quarkus should not treat such a constructor as a _bean constructor_ (unless it's annotated with `@Inject`). Is your entity part of the app or does it live in a separate jar?

**Comment by manovotn** [comment] 2022-04-22 08:47
> Is there an actual need for static producer being located in a managed bean class?

I believe this is because of bean discovery process which varies between implementations; this can be done for instance with Jandex or with just reflection. But to avoid scanning absolutely every class, you limit components such as producers to beans which have a known set of annotations that define them.

**Comment by slinstaedt** [comment] 2022-04-22 11:03
> > Is there an actual need for static producer being located in a managed bean class?
> 
> Well, at least the class must be discovered.
> 
Sure enough, but "discovered" does not imply "managed" ;)

> > For entity classes that have a protected default constructor (meeting JPA requirements), but also a public constructor with some parameters (meeting business requirements), Quarkus will fail to start, because this constructors "dependencies" (normally other entities or domain values, like a LocalDate) are not injected, but handed over when programmatically calling the constructor.
> 
> @slinstaedt That's odd. Quarkus should not treat such a constructor as a _bean constructor_ (unless it's annotated with `@Inject`). Is your entity part of the app or does it live in a separate jar?

Quarkus is not [enforces](https://quarkus.io/guides/cdi-reference#simplified-constructor-injection) an `@Inject` at any managed bean, so my question would be, which constructor quarkus choses, if multiple are declared? In my case, not the default constructor was choosen, but the one with the parameters, leading to some kind of UnsatisfiedDependencyException (I don't remember the exact class name), because the needed arguments have not been defined as beans, of course.

**Comment by slinstaedt** [comment] 2022-04-22 14:15
Sorry for missing your question: The project is a single module, so the entity is part of the app's jar.

**Comment by slinstaedt** [comment] 2022-04-22 15:05
> Quarkus does require @Inject if multiple constructors are found

During deployment time? Try this code in a vanilla quarkus project, just using only the basic `quarkus-resteasy` extension. Unfortunately this works pretty well:

```
@Singleton
@Path("/test")
public class MultipleConstructor {

	public MultipleConstructor(String x) {
		throw new IllegalStateException();
	}

	public MultipleConstructor(Integer x) {
		throw new IllegalStateException();
	}

	@GET
	public String sayHello() {
		return "hello world";
	}
}
```

**Comment by mkouba** [comment] 2022-04-22 17:18
> During deployment time? Try this code in a vanilla quarkus project, just using only the basic `quarkus-resteasy` extension. Unfortunately this works pretty well, not even throwing an IllegalStateException.

Hm in this case, the `MultipleConstructor` is simply ignored (it's not registered as a CDI bean) because it does not have an [appropriate constructor](https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#what_classes_are_beans). And that's the reason why resteasy reactive throws an `IllegalArgumentException` and the message reads "To fix the problem, make sure this class is a CDI bean.".

**Comment by slinstaedt** [comment] 2022-04-23 21:20
The non-reactive `quarkus-resteasy` seems to use a generated synthetic default constructor, because invoking the resource works without any exception at all. Should not it behave the same as it‘s reactive counterpart?

**Comment by mkouba** [comment] 2022-04-28 11:41
Hm, I've just tried to reproduce the problem with:
```
@Entity
class User {

	@Produces
	public static final Role ADMINISTRATOR = new Role("admin");

	protected User () {}

	public User(String username, LocalDate birthday, Role... initialRoles) { ... }
}
```
and no problem occured. And even the producer worked.

**Comment by mkouba** [comment] 2022-04-28 11:42
> The non-reactive `quarkus-resteasy` seems to use a generated synthetic default constructor, because invoking the resource works without any exception at all. Should not it behave the same as it‘s reactive counterpart?

That's a question for @geoand ;-)

**Comment by geoand** [comment] 2022-04-28 11:54
> The non-reactive `quarkus-resteasy` seems to use a generated synthetic default constructor, because invoking the resource works without any exception at all. Should not it behave the same as it‘s reactive counterpart?

Which case does not work?

**Comment by slinstaedt** [comment] 2022-05-10 23:29
`quarkus-resteasy` and `quarkus-resteasy-reactive` behave differently, when it comes to corner cases like the mentioned MultipleConstructor class. IMHO `quarkus-resteasy-reactive` behavior seem to be more appropriate.

**Comment by mkouba** [comment] 2022-08-30 07:49
I believe that this issue should be closed. @slinstaedt @geoand @manovotn WDYT?

**Comment by geoand** [comment] 2022-08-30 08:08
I agree

**Comment by mkouba** [comment] 2022-08-30 11:03
Closing. @slinstaedt feel free to reopen if you have more questions/additional info.

**Closed by mkouba** 2022-08-30 11:03 UTC
Labels: kind/bug, area/arc
