### ISSUE TITLE
Cannot record objects with both isX and getX

### ISSUE THREAD

**Issue by Christopher-Chianelli** [quarkusio/quarkus#26889] opened 2022-07-22 16:52 UTC
### Describe the bug

If an object with both `getX` and `isX` getter is passed to a recorder, the field `x` remains null, causing subtle bugs that are hard to detect.

### Expected behavior

If an object with both `getX` and `isX` getter is passed to a recorder, the field `x` is set to the value returned by `getX`.

### Actual behavior

The field `x` remains null.

### How to Reproduce?

Reproducer: https://github.com/Christopher-Chianelli/issue-reproducer/tree/quarkus-recorder-is-get-error

1. Clone repo
2. `cd quarkus-issue-reproducer`
3. `mvn clean install`
4. Notice test fails

### Output of `uname -a` or `ver`

Linux 5.18.11-200.fc36.x86_64

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19

### Quarkus version or git rev

2.10.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.4

**Comment by geoand** [comment] 2022-07-26 06:06
Hm... I agree that the current behavior is not correct, but why would we choose `getX` over `isX`?

**Comment by triceo** [comment] 2022-07-26 07:49
Thinking out loud here:

I'm afraid there is no logic that leads to preference of either `getX` or `isX`.
And the situation may get even more complicated if someone refactors the class to a record (with its convention of just `X` for field getters), forgetting to remove the old `getX` getters. (As I did earlier.)

Maybe the only rational choice is to throw an exception?

**Comment by geoand** [comment] 2022-07-26 07:53
> Maybe the only rational choice is to throw an exception?

That would be my preference as wel...

**Comment by triceo** [comment] 2022-07-26 08:41
In the original code that triggered this bug report, the reason that `getX` and `isX` both exist is that they are actually different:

`Boolean getX()`
`boolean isX()`

`isX()` does some additional null checks to convert `Boolean` to a clean `boolean`.
But the type of `X` is `Boolean`.
So maybe Quarkus should prefer `getX`, because it returns the same type as the field?

**Comment by mkouba** [comment] 2022-08-02 13:30
Hm, this is weird because from the code it looks like the `getX()` method should simply take precedence... I'll take a look.

**Comment by mkouba** [comment] 2022-08-02 14:07
Ok, so the problem is something else. You actually register two beans for the `ProblemObject`. One is synthetic (and marked as a [default bean](https://github.com/Christopher-Chianelli/issue-reproducer/blob/quarkus-recorder-is-get-error/quarkus-issue-reproducer/deployment/src/main/java/io/quarkiverse/issue/reproducer/deployment/IssueReproducerProcessor.java#L35)) and the other one is registered as a class bean here: https://github.com/Christopher-Chianelli/issue-reproducer/blob/quarkus-recorder-is-get-error/quarkus-issue-reproducer/deployment/src/main/java/io/quarkiverse/issue/reproducer/deployment/IssueReproducerProcessor.java#L31-L32.

As a result the default bean is ignored and the bean instance is constructed using the no-args constructor (hence the `myBoolean` field is `null`).

Furthermore, the synthetic bean does have the `ProblemObject` in its set of bean types and thus cannot be injected in `IssueReproducerResource.problemObject`. One way to fix this is to replace the `ProblemObjectRecorder.class` with `ProblemObject.class` here: https://github.com/Christopher-Chianelli/issue-reproducer/blob/quarkus-recorder-is-get-error/quarkus-issue-reproducer/deployment/src/main/java/io/quarkiverse/issue/reproducer/deployment/IssueReproducerProcessor.java#L33

**Comment by mkouba** [comment] 2022-08-02 14:08
I'm going to close this issue. Feel free to comment/reopen if you have more questions ;-).

**Closed** 2022-08-02 14:12 UTC
Labels: kind/bug, triage/needs-triage
