### ISSUE TITLE
Can not get buildtime variable at runtime

### ISSUE THREAD

**Issue by alessandroAmedei** [quarkusio/quarkus#36655] opened 2023-10-24 08:38 UTC
### Describe the bug

I am building a Quarkus application with
`mvn package -Dapp.version=2.0.0 -Dquarkus.package.type=uber-jar`

I expose a web service like this..

    @ConfigProperty(name = "app.version")
    Optional<String> version;
   
    @GET
    public string version(){
         return version.orElse(null);
     }

Then i run the application with

      java -jar ..

But the return value is always NULL.
What am I doing wrong? Why is not getting the variable I have set at runtime?

### Expected behavior

The webservice should return a string '2.0.0'

### Actual behavior

The web service is returning null

### How to Reproduce?

Start from a vary basic project.
You do not need a variable app.version in application.properties

### Output of `uname -a` or `ver`

Windows 10

### Output of `java -version`

java version "17.0.2" 2022-01-18 LTS Java(TM) SE Runtime Environment (build 17.0.2+8-LTS-86) Java HotSpot(TM) 64-Bit Server VM (build 17.0.2+8-LTS-86, mixed mode, sharing)

### Quarkus version or git rev

2.14.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.5 (3599d3414f046de2324203b78ddcf9b5e4388aa0) Maven home: C:\Program Files\Java\apache-maven-3.8.5 Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\Program Files\java\jdk-17.0.2 Default locale: it_IT, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by leo-bogastry** [comment] 2023-10-31 12:26
Hi @alessandroAmedei! I'm not an expert, by I think you can only set the value of `app.version` at runtime and not at build time. What you can do when building your package it to set a profile; like explained in [config-reference#profiles](https://quarkus.io/guides/config-reference#profiles)

**Comment by gastaldi** [comment] 2023-11-08 00:15
That's not going to work. [@leo-bogastry's reply](https://github.com/quarkusio/quarkus/issues/36655#issuecomment-1787119997) is correct. 

You can do the following to have a build-time property set in your application:

1. Add an entry to your `application.properties`: `app.version=${projectVersion}`
2. Filter the `application.properties` in the `pom.xml` during the build by adding the following to your `<build>`:
```xml
      <resources>
        <resource>
          <directory>src/main/resources</directory>
          <includes>
            <include>application.properties</include>
          </includes>
          <filtering>true</filtering>
        </resource>
      </resources>
```
 
3. Build your uber-jar with `mvn clean package -DprojectVersion=2.0.0 -Dquarkus.package.type=uber-jar`

Now the snippet you have above should work.

Closing as this is not a bug

**Closed by gastaldi** 2023-11-08 00:15 UTC
Labels: kind/bug, env/windows, triage/needs-triage

**Comment by alessandroAmedei** [comment] 2023-11-08 16:51
> That's not going to work. [@leo-bogastry's reply](https://github.com/quarkusio/quarkus/issues/36655#issuecomment-1787119997) is correct.
> 
> You can do the following to have a build-time property set in your application:
> 
> 1. Add an entry to your `application.properties`: `app.version=${projectVersion}`
> 2. Filter the `application.properties` in the `pom.xml` during the build by adding the following to your `<build>`:
> 
> ```
>       <resources>
>         <resource>
>           <directory>src/main/resources</directory>
>           <includes>
>             <include>application.properties</include>
>           </includes>
>           <filtering>true</filtering>
>         </resource>
>       </resources>
> ```
> 
> 3. Build your uber-jar with `mvn clean package -DprojectVersion=2.0.0 -Dquarkus.package.type=uber-jar`
> 
> Now the snippet you have above should work.
> 
> Closing as this is not a bug

I also have in my application.properties
`app.version=${app.version}`

and what the documentation says here https://quarkus.io/guides/config-reference#property-expressions is:
```
Quarkus provides property expressions expansion on configuration values. An expression string is a mix of plain strings and expression segments, which are wrapped by the sequence ${ …​ }.

These expressions are resolved when the property is read. So if the configuration property is build time the property expression will be resolved at build time. If the configuration property is overridable at runtime it will be resolved at runtime.
```

So the property app.version should be resolved at build time! But this is not working still.
Is it a bug?
