### ISSUE TITLE
JWT quickstart tests fail with 999-SNAPSHOT

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2784] opened 2019-06-11 07:57 UTC
The JWT quickstarts tests are failing:

1. create project for quickstart
```
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=org.acme \
    -DprojectArtifactId=using-jwt-rbac \
    -DclassName="org.acme.jwt.TokenSecuredResource" \
    -Dpath="/secured" \
    -Dextensions="resteasy-jsonb, smallrye-jwt"
```
2. run `mvn package`

You are going to see:
```
[INFO] Running org.acme.jwt.TokenSecuredResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.177 s <<< FAILURE! - in org.acme.jwt.TokenSecuredResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.013 s  <<< ERROR!
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.jwt.TokenSecuredResourceTest]
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.util.NoSuchElementException: No value present
```

**Comment by cescoffier** [comment] 2019-06-11 08:41
(It may be expected, but the error should be much better)

**Comment by sberyozkin** [comment] 2019-06-11 10:26
Looks like a duplicate of #2725

**Comment by sberyozkin** [comment] 2019-06-11 13:30
Please see #2725 for a proposed error message

**Comment by gsmet** [comment] 2019-06-18 19:18
@sberyozkin should this one be closed?

**Comment by gsmet** [comment] 2019-06-19 08:29
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/2725 .

**Comment by sberyozkin** [comment] 2019-07-08 20:01
@gsmet can this issue be actually closed, it is still in the Open state ?

**Closed** 2019-07-16 14:00 UTC
Labels: bug, duplicate

**Comment by gsmet** [comment] 2019-07-16 14:03
@sberyozkin sorry missed your message, thanks for closing it.
