### ISSUE TITLE
Super-types of bean resolved at compile-time but not present at run-time cause start-up failure

### ISSUE THREAD

**Issue by plevart** [quarkusio/quarkus#6527] opened 2020-01-13 13:08 UTC
One example of the problem is described in issue  #5062 which has been fixed with a work-around for that particular bean type (String) and its super-types. This issue is about investigation and proposals to find a more general fix for the problem.

**Comment by dmlloyd** [comment] 2020-01-13 14:26
During the build, we may do any or all of the following:

1. Reflectively examine and/or index classes on the class path for structure
2. Reflectively analyze the method bodies of classes on the class path and their dependencies
3. Execute some code on the class path
4. Store information dependent on any of the above

Because of this, differences in the JDK at build and run time have a much greater impact than what can be solved by usage `--release 8`, which (within the scope of `javac`) uses a stubbed version of JDK 8 instead of the normal run time JDK of the compilation environment.

Here are the possible solutions that I can think of:

1. Never introspect private/package-private members of the JDK in any way for any reason
2. Require that the application run on the same JDK (not just major version, but the exact same JDK) for which it was built or face undefined/unpredictable behavior

**Comment by dmlloyd** [comment] 2020-01-13 15:27
Note that this will (at least in theory) affect building on Mac/Windows and deploying to Linux/etc.

**Comment by dmlloyd** [comment] 2020-01-13 15:31
> Just to clarify - this is not specific to native image this a plain Quarkus JVM built jar that won't necessarily run on different major/minor versions of Java and in worst case not on the same JDK version because the jdk class library can be different between Operating systems ?

Correct, this applies to JVM mode.  Native images don't actually have this problem because in a sense, they carry the JDK inside of them.

**Comment by maxandersen** [comment] 2020-01-13 16:23
So in theory this could even be an issue if you build your app on a linux box based on ubunutu but in production runs on centos/rhel based openjdk ?

**Comment by dmlloyd** [comment] 2020-01-13 16:54
> So in theory this could even be an issue if you build your app on a linux box based on ubunutu but in production runs on centos/rhel based openjdk ?

I think that is unlikely *if* the JDK is identical between them (because the class structure and API implementations of the JDK will not differ in this case).

**Comment by stuartwdouglas** [comment] 2020-01-14 03:04
The linked issue is not about package private members of the JDK, the issue is that additional interfaces have been added to java.lang.String and other constant types. These will be present no matter the minor version.

We should not be introspecting implementation details of the JDK unless the users code is using it directly in their application. 

I don't think this will be a big problem outside of this particular case. There is only a small set of JDK types that are regularly used as CDI beans, and adding additional interfaces will likely not happen very often.

**Comment by stuartwdouglas** [comment] 2020-07-08 01:57
I am closing this, as I don't think there is anything we can do in the general case, and as these issues are relatively rare I think all we can do is fix them on a case by case basis.

**Closed by stuartwdouglas** 2020-07-08 01:57 UTC
Labels: kind/bug
