### ISSUE TITLE
Jakarta EE 9 and Microprofile 5 spec/API alignment

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#22521] opened 2021-12-25 12:40 UTC
### Description
Migrate to the latest Jakarta EE 9 and Microprofile v5 and Java 17 based.

### Analysis

Spring 6 will align with Jakarta EE 9 and introduce built-in native features, and Micornaut 3 already support both Jakarta EE 8 and Jakarta EE 9 API(I have tried `jakarta.inject`, `jakarta.annoations`, etc).

Quarkus has any plan of upgrading to the latest Jakarta EE 9 and Microprofile v5?

**Comment by geoand** [comment] 2022-01-03 06:29
cc @radcortez

**Comment by radcortez** [comment] 2022-01-03 11:43
> Quarkus has any plan of upgrading to the latest Jakarta EE 9 and Microprofile v5?

MP 5.0 only provided Jakarta compatible binaries in December. We now need to move all of the SmallRye implementations to use Jakarta (and this is only covering the MP side).

Unfortunately, this is not an easy thing to do, especially since it requires that dependencies are ready to support Jakarta.

**Comment by gastaldi** [comment] 2022-01-04 14:34
Duplicate of #21574

**Closed by gastaldi** 2022-01-04 14:34 UTC
Labels: kind/epic
