### ISSUE TITLE
2.7.1.final kotlin tests not found task: quarkusTest

### ISSUE THREAD

**Issue by beckend** [quarkusio/quarkus#23814] opened 2022-02-19 14:17 UTC
### Describe the bug

Using version `2.7.1.final`
No tests are found, configured using kotlin and gradle.
Reverting to `2.6.3.final`, the tests are found and are running.

### Expected behavior

```shell
./gradlew quarkusTest
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-02-19 15:08:35,332 INFO  [io.qua.test] (main) Quarkus continuous testing mode started
Starting test run, 1 tests to run.
Running 1/1. Running: #JUnit Jupiter
Running 1/1. Running: net.unikum.app.codegenerator.ApplicationTest#ApplicationTest
2022-02-19 15:08:35,785 INFO  [org.jbo.threads] (Test runner thread) JBoss Threads version 3.4.2.Final
     2022-02-19 15:08:36,395 INFO  [io.quarkus] (Test runner thread) codegenerator unspecified on JVM (powered by Quarkus 2.6.3.Final) started in 0.826s. Listening on: http://localhost:8081
2022-02-19 15:08:36,396 INFO  [io.quarkus] (Test runner thread) Profile test activated. 
2022-02-19 15:08:36,397 INFO  [io.quarkus] (Test runner thread) Installed features: [cdi, kotlin, reactive-routes, smallrye-context-propagation, vertx]
Running 1/1. Running: net.unikum.app.codegenerator.ApplicationTest#testHelloEndpoint()
2022-02-19 15:08:37,174 INFO  [io.quarkus] (Test runner thread) codegenerator(test application) stopped in 0.013s
Press [r] to re-run, [h] for more options>
Press [r] to re-run, [o] Toggle test output, [h] for more options>
All 1 test is passing (0 skipped), 1 test was run in 1864ms. Tests completed at 15:08:37.
```

### Actual behavior

Using version 2.7.1.final
```shell
./gradlew quarkusTest
...
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2022-02-19 15:09:26,678 INFO  [io.qua.test] (main) Quarkus continuous testing mode started
Press [r] to re-run, [h] for more options>
Press [r] to re-run, [o] Toggle test output, [h] for more options>
No tests found

...
```

### How to Reproduce?

https://github.com/beckend/quarkus-test-bug

found and passing tests:
```shell
./gradlew quarkusTest
```

no tests found:
```shell
# use the culprit version
cp gradle.properties.latest gradle.properties
./gradlew quarkusTest
```

### Output of `uname -a` or `ver`

Linux workstation-1.localdomain.internal 5.16.10-xanmod1-1 #1 SMP Wed, 16 Feb 2022 21:27:18 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk 17.0.1 2021-10-19 OpenJDK Runtime Environment (build 17.0.1+12) OpenJDK 64-Bit Server VM (build 17.0.1+12, mixed mode)

### Quarkus version or git rev

2.7.1.final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

**Comment by beckend** [comment] 2022-02-19 14:22
possible duplicate of https://github.com/quarkusio/quarkus/issues/23735

**Comment by glefloch** [comment] 2022-02-20 21:01
Thanks for reporting this @beckend. 
Indeed this is a duplicate of #23735. 
I will close this issue in favor of the other one.

**Closed by glefloch** 2022-02-20 21:01 UTC
Labels: kind/bug, area/kotlin
