### ISSUE TITLE
Make @Fallback repeatable

### ISSUE THREAD

**Issue by artkonr** [quarkusio/quarkus#17362] opened 2021-05-19 14:28 UTC
## Description

It would be really great to have `@Fallback` annotation repeatable to make code like below work:

```java

@RegisterRestClient
public interface SomeClient {

   @CircuitBreaker
   @Fallback(fallbackMethod = "handleBadJson", applyOn = JsonProcessingException.class)
   @Fallback(fallbackMethod = "handleCircuitBreakerOpen", applyOn = CircuitBreakerOpenException.class)
   String callSomeService();

   default handleBadJson() {
      // some processing logic
   }

   default handleCircuitBreakerOpen() {
      // some processing logic
   }

}

```

I know it's possible to pass a custom `FallbackHandler` implementation, which would handle conditional fallbacks, but IMHO making `@Fallback` repeatable would make this a bit more declarative.

**Comment by Ladicek** [comment] 2021-05-20 07:56
Ah, and one question to clarify the use case. How would you handle `JsonProcessingException` differently from `CircuitBreakerOpenException`? Do you actually foresee returning a different value, or would the difference be entirely in side effects (logging etc.)?

**Comment by artkonr** [comment] 2021-05-20 09:03
If I was to implement this, I'd probably go for most-specific-wins. If I got your point correctly, your concern is about cases similar to this:

```java
@Fallback(fallbackMethod = "method1", applyOn = IOException.class)
@Fallback(fallbackMethod = "method2", applyOn = FileNotFoundException.class) 
```

So since `FileNotFoundException` is more specific relatively to `IOException`, method `method2()` takes precedence; all the rest of `IOException`-ish types will be handled by `method1()`. Typically, this is what we get in `try-catch`, so such behavior will not be a surprise. I understand, it is a sort of design which is quite easy to misuse, but that's the nature of exception handling. My thoughts were drifting in the direction of something like `Map<Exception, Function<Exception, T>>`, but there may be a better option, because I reckon resolving unmatched concrete exceptions against their supertypes may get messy. Am I missing something else?

**Comment by Ladicek** [comment] 2021-05-20 09:35
Indeed that is my concern. Your comparison with `try`/`catch` is unfortunately mistaken. If you have

```java
try {
    throw new FileNotFoundException();
} catch (IOException e) {
    ... 1st exception handler ...
} catch (FileNotFoundException e) {
   ... 2nd exception handler ...
}
```

then it's the _1st handler_ who gets to handle the exception. So `try`/`catch` is in fact a "first matching wins" kind of thing. See https://docs.oracle.com/javase/specs/jls/se16/html/jls-14.html#jls-14.20.1

**Comment by Ladicek** [comment] 2021-05-20 09:41
I think I'm leaning towards a conservative approach. If you have

```java
@Fallback(fallbackMethod = "fallback", ...)
public Result hello(Parameters parameters) {
    ...
}

public Result fallback(Parameters parameters) {
    ...
}
```

Then you could possibly add a parameter of type `Throwable` (and of no other type) to the `fallback` method, in the _last_ position:

```java
public Result fallback(Parameters parameters, Throwable exception) {
    ...
}
```

It would be a deployment error for both with-cause and without-cause fallback methods to exist.

WDYT?

**Comment by Ladicek** [comment] 2021-05-20 09:57
Actually that's probably wrong, because it wouldn't work with vararg parameters. Alternative option would be to put the cause parameter to the _first_ position, but that's a little ugly...

**Comment by artkonr** [comment] 2021-05-20 10:18
> Your comparison with try/catch is unfortunately mistaken

Yep, true, won't compile, did not think of that. But anyway, I did not assume to draw a parallel between the exception handling in general and in the fallback methods as a part of suggestion.  

> WDYT?

Is it going to replace `applyOn` in the annotation? I actually like your approach, it will work better in handling cases, when some information is acquired from the exception. I just feel that force-upcasting to `Throwable` might require the client code to downcast in some situations. E.g., I want to handle `WebApplicationException` using the `Response` object it provides via `getResponse()`. I'll have to do the type check, cast down to the type I'm expecting and only then do the processing. In such a case, it is barely different from implementing a custom `FallbackHandler`. However, I can't come up with a way to parametrize it, the only thing that comes to my mind would be to perform a type check at deployment time.

**Comment by Ladicek** [comment] 2021-05-20 10:47
I'm drawing parallels between `@Fallback` and `try`/`catch` because multiple `@Fallback` annotations differing only in `applyOn`/`skipOn` is essentially a new syntax for `try`/`catch`. Which I'd really like to avoid :-)

And no, nothing I'd do with providing access to the causing exception would affect the `applyOn` / `skipOn` annotation attributes.

One more thing:

> E.g., I want to handle `WebApplicationException` using the `Response` object it provides

I believe that `@Fallback` is not what you should use in that case. Fallback is not a generic error handling mechanism. Fallback is, well, fallback -- provides a "surrogate" result in case the true result couldn't be obtained for some reason. If you want to handle errors, use `try`/`catch` in the synchronous case, or the `CompletionStage`/`Uni`/whatever API in the asynchronous case.

**Comment by artkonr** [comment] 2021-05-20 11:47
OK, I get it now. It looks like I've been trying to use it wrong way all along, it seemed to me to be some sort of declarative syntactic sugar over conventional error handling. All objections withdrawn :) I think your proposal is a good way to proceed from here then.

Shall I leave this item here open for reference?

**Comment by Ladicek** [comment] 2021-05-20 11:54
Thanks for your patience and replies! I think I'll close this, as I don't intend to implement repeatable `@Fallback`s at all -- but if you wish, you can continue the discussion either in https://github.com/smallrye/smallrye-fault-tolerance/issues/274 or in https://github.com/eclipse/microprofile-fault-tolerance/issues/507.

**Closed by Ladicek** 2021-05-20 11:54 UTC
Labels: area/fault-tolerance, kind/enhancement, triage/upstream
