### ISSUE TITLE
Handling a multipart request part as a file based on the content-type

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#30502] opened 2023-01-20 09:59 UTC
### Describe the bug

Quarkus `2.13.7.Final`
Related to https://github.com/quarkusio/quarkus/issues/29725

[This issue](https://github.com/quarkusio/quarkus/issues/29725) is still happening on Quarkus `2.13.7.Final` although was backported to Quarkus `2.13.6.Final` . Is working on Quarkus `2.15.2.Final` or main. 

### Expected behavior

All files regardless to the content-type of a multi-part request are uploaded. 

### Actual behavior

I am getting the following error:

```
Request failed: java.lang.NullPointerException: Cannot invoke "java.io.File.toPath()" because "multipartBody.plainTextFile" is null
```

### How to Reproduce?

```
git clone --branch 2.13 git@github.com:quarkus-qe/quarkus-test-suite.git
cd  quarkus-test-suite/http/jaxrs-reactive
```
Fails

```
mvn clean verify -Dit.test=RESTEasyReactiveMultipartIT#testPlainTextFilePartFromMultipart -Dquarkus.platform.version=2.13.7.Final
```

Works
```
mvn clean verify -Dit.test=RESTEasyReactiveMultipartIT#testPlainTextFilePartFromMultipart -Dquarkus.platform.version=2.15.2.Final 
```

Be sure that the test `RESTEasyReactiveMultipartIT#testPlainTextFilePartFromMultipart` is not disabled

### Output of `uname -a` or `ver`

Linux ovpn-193-134.brq.redhat.com 6.0.16-300.fc37.x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

**Comment by gsmet** [comment] 2023-01-20 10:48
@pjgg I'm confused. Does it work with 2.13.6.Final? Because Pedro confirmed things were working for him with 2.13.6.Final.

**Comment by pjgg** [comment] 2023-01-20 11:47
@gsmet the reproducer is still failing on 2.13.6.Final (but works on `2.15.2.Final`) so maybe something else needs to be backported.

**Comment by gsmet** [comment] 2023-01-20 13:00
So what I don't understand is that Pedro was positive his issue was fixed in 2.13.6.Final so I'm not sure your test is actually testing exactly the behavior @pedroigor wanted. I know we had other patches related to this issue that we didn't backport though.

**Comment by Sgitario** [comment] 2023-01-20 13:14
The test is not working because it's sending [a text part](https://github.com/quarkus-qe/quarkus-test-suite/blob/2.13/http/jaxrs-reactive/src/test/java/io/quarkus/ts/http/jaxrs/reactive/RESTEasyReactiveMultipartIT.java#L94). If you change this line to:
```
MultiPartSpecification textSpec = new MultiPartSpecBuilder(text.getBytes(StandardCharsets.UTF_8))
```

The test will work in 2.13.6.Final.

This issue was fixed for 2.15.1.Final by https://github.com/quarkusio/quarkus/pull/29716, which is not backported.

**Comment by geoand** [comment] 2023-01-23 05:56
So should we disable the test in `2.13`?

**Comment by pedroigor** [comment] 2023-01-24 21:22
Looks like it is a different scenario. The behavior we expect is working fine in 2.13.

**Comment by Sgitario** [comment] 2023-03-08 13:17
Closing as not planned.

**Closed by Sgitario** 2023-03-08 13:17 UTC
Labels: kind/bug, area/resteasy-reactive
