### ISSUE TITLE
Kubernetes extension build error

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#30558] opened 2023-01-23 16:49 UTC
### Describe the bug

When using the kubernetes extension, there is an error at build time: `Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.`

We've been running fine even with the error, so it is probably harmless. But it is still concerning to see an error in the build.

### Expected behavior

No error

### Actual behavior

Build error:

```
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
```

### How to Reproduce?

Reproducer:

1. Clone https://github.com/mikethecalamity/quarkus-test
2. `./gradlew -p apps service3:build`

### Output of `java -version`

17

### Quarkus version or git rev

2.15.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by geoand** [comment] 2023-01-23 17:44
Do you perhaps have the entire log line?

**Comment by mikethecalamity** [comment] 2023-01-23 18:19
There's not much else:

```
+ ./gradlew service:quarkusBuild
> Task :service:processResources UP-TO-DATE
> Task :service:quarkusGenerateCode UP-TO-DATE
> Task :service:quarkusGenerateCodeDev UP-TO-DATE
> Task :service:compileJava UP-TO-DATE
> Task :service:classes UP-TO-DATE
> Task :service:jar UP-TO-DATE
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.
[WARN] Could not detect project version. Using 'latest'.
[INFO] Checking for existing resources in: service\src\main\kubernetes.
> Task :service:quarkusBuild

BUILD SUCCESSFUL in 9s
47 actionable tasks: 1 executed, 46 up-to-date
```

**Comment by mikethecalamity** [comment] 2023-01-23 22:22
Added reproducer above.

**Comment by geoand** [comment] 2023-01-24 12:46
Same comment as in https://github.com/quarkusio/quarkus/issues/30559#issuecomment-1401879328

**Comment by mikethecalamity** [comment] 2023-01-24 15:12
@geoand The reproducer is fixed now

**Comment by geoand** [comment] 2023-01-25 07:52
Thanks, https://github.com/dekorateio/dekorate/pull/1135 should fix the issue

**Comment by Sgitario** [comment] 2023-01-25 07:54
> Thanks, [dekorateio/dekorate#1135](https://github.com/dekorateio/dekorate/pull/1135) should fix the issue

As far as I understand, the complaint here is about the log `Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.` which is printed by the Fabric8 Kubernetes Client. 

Having said that, I'm fine with the changes in [dekorateio/dekorate#1135](https://github.com/dekorateio/dekorate/pull/1135) too.

**Comment by geoand** [comment] 2023-01-25 07:56
Ah darn, I was looking at the wrong output :)

**Comment by geoand** [comment] 2023-01-25 08:00
@manusa WDYT about the above? Should we make the change or not?

**Comment by manusa** [comment] 2023-01-25 08:34
> @manusa WDYT about the above? Should we make the change or not?

You mean in the client?

That can be OK. However, the proper solution **might** be to tune the auto configuration methods in order to be able to opt-in/opt-out of which configuration inference methods we should use. It's my understanding that in this case we're aware and sure that this process will never run within a `Pod`, right?

**Comment by Sgitario** [comment] 2023-01-25 08:42
I don't follow what you mean about the proper solution.
However, I think the issue is in this method: https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L536.

When there is no service account token system property, it uses `/var/run/secrets/kubernetes.io/serviceaccount/token` (see [line](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L540)) and then the log message is printed [here](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L568).

From my point of view, the log message is correct as long as the service account token system property is set. But if the default value is used, we should first check the file exists and if not, maybe log a debug/trace message instead of this warning.

**Comment by manusa** [comment] 2023-01-25 08:54
> I don't follow what you mean about the proper solution. However, I think the issue is in this method: https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L536.
> 
> When there is no service account token system property, it uses `/var/run/secrets/kubernetes.io/serviceaccount/token` (see [line](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L540)) and then the log message is printed [here](https://github.com/fabric8io/kubernetes-client/blob/1a3b2b6ce0d167748a73f71baa667b7cbc0e7ff3/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L568).
> 
> From my point of view, the log message is correct as long as the service account token system property is set. But if the default value is used, we should first check the file exists and if not, maybe log a debug/trace message instead of this warning.

As I said, I'm not sure if in this scenario, all possible auto-configurations are applicable. 
The client tries to infer the configuration from `.kube/config`, `/var/run/...` file, and so on. So if in a certain scenario, only some inferences are applicable, being able to opt-in/out **might** be the proper way to operate.

> When there is no service account token system property,

The logic there seems messed-up, it definitely looks like the events that trigger the log messaging should be reviewed.

**Comment by mikethecalamity** [comment] 2023-01-25 21:00
> The logic there seems messed-up, it definitely looks like the events that trigger the log messaging should be reviewed.

I agree, I think it seems odd that the service is looking for kubernetes files at build time. That seems like something it should be finding at runtime.

**Comment by Sgitario** [comment] 2023-01-26 13:18
> being able to opt-in/out might be the proper way to operate.

I don't fully follow what you mean about this. However, you can see the changes I meant in this pull request: https://github.com/fabric8io/kubernetes-client/pull/4795.

**Comment by manusa** [comment] 2023-01-26 13:29
> However, you can see the changes I meant in this pull request: [fabric8io/kubernetes-client#4795](https://github.com/fabric8io/kubernetes-client/pull/4795).

Thx :raised_hands: 

> I don't fully follow what you mean about this. 

I'm talking about something with a different scope than what you're covering.

Basically, if I'm running the client from my local machine, there's no need to check the service account token.
On the other hand, if I'm running the client from a Pod, in many cases it won't be necessary to check the `.kube/config` file

See the following code-block https://github.com/fabric8io/kubernetes-client/blob/f8bf57703603ed8936afaa9567e80afed80c60d4/kubernetes-client-api/src/main/java/io/fabric8/kubernetes/client/Config.java#L290-L298

I'm just saying that it might not make sense to tryXxxx in all scenarios because we already know that the logic there won't be applicable.

**Comment by Sgitario** [comment] 2023-02-01 07:01
This issue should be fixed in the upcoming Fabric8 Kubernetes Client 6.4.2

**Comment by manusa** [comment] 2023-02-01 08:38
> This issue should be fixed in the upcoming Fabric8 Kubernetes Client 6.4.2

The fix provided by @Sgitario is included in the [6.4.1](https://github.com/fabric8io/kubernetes-client/releases/tag/v6.4.1) release which will hopefully make it in with #30480

**Comment by fjlobaton** [comment] 2023-02-07 20:27
This will fix that when building for the image with gradle it doesnt generate the kubernetes manifests?

**Comment by Sgitario** [comment] 2023-02-08 05:58
> This will fix that when building for the image with gradle it doesnt generate the kubernetes manifests?

No, this issue is about to not log this error message: `Error reading service account token from: [/var/run/secrets/kubernetes.io/serviceaccount/token]. Ignoring.`.

**Closed** 2023-03-08 13:15 UTC
Labels: triage/upstream, area/kubernetes
