### ISSUE TITLE
gRPC Server INTERNAL: HTTP status code 400 When Upgrading from 3.12.3 > 3.13.0

### ISSUE THREAD

**Issue by brianwyka** [quarkusio/quarkus#42724] opened 2024-08-23 01:20 UTC
### Describe the bug

When upgrading from version `3.12.3` to `3.13.0`, with no other code changes, the gRPC server is returning an INTERNAL error when being called from a gRPC blocking stub in another application.

### Expected behavior

Should still work as expected and should not return an error.

### Actual behavior

Returns an error response `INTERNAL` with an HTTP status code of `400` and a message indicating invalid content type which is null.

```
INTERNAL: HTTP status code 400
invalid content-type: null
trailers: Metadata(:status=400,date=Fri, 23 Aug 2024 00:10:53 GMT,strict-transport-security=max-age=31536000; includeSubDomains,content-length=0)
io.grpc.StatusRuntimeException: INTERNAL: HTTP status code 400
invalid content-type: null
trailers: Metadata(:status=400,date=Fri, 23 Aug 2024 00:10:53 GMT,strict-transport-security=max-age=31536000; includeSubDomains,content-length=0)
	at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:268)
	at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:249)
	at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:167)
```

### How to Reproduce?

Client Side relevant dependency versions:

```
com.google.protobuf:protobuf-java:3.25.2
com.google.protobuf:protobuf-java-util:3.25.2
io.grpc:grpc-stub:1.61.1
o.grpc:grpc-protobuf:1.61.1
```

Here is the client side code for setting up the `ManagedChannel`:

```java
            final Metadata metadata = new Metadata();
            metadata.put(Key.of("Authorization", Metadata.ASCII_STRING_MARSHALLER), apiAuthorizationToken);
            this.managedChannel = ManagedChannelBuilder.forTarget(apiEndpoint)
                .intercept(MetadataUtils.newAttachHeadersInterceptor(metadata))
                .keepAliveTime(2, TimeUnit.HOURS)
                .keepAliveTimeout(20, TimeUnit.MINUTES)
                .keepAliveWithoutCalls(false)
                .idleTimeout(30, TimeUnit.MINUTES)  // Set idle timeout to 30 minutes
                .enableRetry()
                .build();
```

The `apiEndpoint` is on secure port, i.e. - `service.domain.com:443`

Quarkus Server side configurations:

```
quarkus.grpc.server.compression = gzip
quarkus.grpc.server.use-separate-server  = false
```

Using `proto3`...

Quarkus Server Side service:
```java
@GrpcService
public class SummaryResource extends SummaryServiceGrpc.SummaryServiceImplBase {
 ...
}
```

### Output of `uname -a` or `ver`

linux (debian 12.5) - running in AWS EKS

### Output of `java -version`

17.0.11.9.1

### Quarkus version or git rev

3.13.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.10

**Comment by brianwyka** [comment] 2024-08-23 01:24
I've tried looking for a change in the grpc extension which could be related, but nothing is sticking out:
https://github.com/quarkusio/quarkus/compare/3.12.3...3.13.0

**Comment by cescoffier** [comment] 2024-08-23 08:34
Are you using the same server as HTTP or use a separate server? Are you being a proxy?

**Comment by brianwyka** [comment] 2024-08-23 11:37
I include separate server false config above.  No proxy.  Communication is from an AWS EC2 to a kubernetes grpc ingress.

**Comment by cescoffier** [comment] 2024-08-23 12:32
Does it work locally?

**Comment by cescoffier** [comment] 2024-08-23 12:34
My guess is that it's due to a missing host in the request generating a 400 response. 

CC @tsegismont

**Comment by brianwyka** [comment] 2024-08-23 12:47
It works locally, but with a few differences:
- not running in aws and kubernetes (running everything in docker)
- without SSL (client sends request with plain text)

**Comment by brianwyka** [comment] 2024-08-23 12:48
@cescoffier, do you mean that the client needs to set a host header now?  Any way to disable that validation on the server side to verify if that is the issue?

**Comment by cescoffier** [comment] 2024-08-25 11:29
You cannot disable the validation.

It got reported here: https://github.com/vert-x3/vertx-web/issues/2638

**Comment by brianwyka** [comment] 2024-08-25 12:18
Was this introduced in `3.13.0`?

**Comment by cescoffier** [comment] 2024-08-25 17:06
Yes

**Comment by cescoffier** [comment] 2024-08-25 17:06
You can try to downgrade Vert.x Web

**Comment by brianwyka** [comment] 2024-08-25 19:19
Thanks, I'll try that.  What would I need to do on the client side in the ManagedChannel Metadata or by some other means to be able to successfully upgrade?

**Comment by cescoffier** [comment] 2024-08-26 05:43
It's only on the server side. Downgrading vert.x on the server side should verify that it's the actual issue.

**Comment by tsegismont** [comment] 2024-08-26 08:38
> My guess is that it's due to a missing host in the request generating a 400 response.
> 
> CC @tsegismont

It may be related, indeed. It will be interesting to know if downgrading Vert.x Web to the previous version solves the issue. Also, it would help to get a capture or logs of the network traffic (to confirm the host header is missing).

It is surprising that the host header is missing (I wouldn't expect a gRPC client to use HTTP/1.0 and the HTTP/1.1 mandates the Host header to be present).

**Comment by cescoffier** [comment] 2024-08-27 06:09
I quickly discussed this issue with @tsegismont and we are not sure it's related to the same issue I mentioned yeterday. We striked us was the `invalid content-type: null` in your log. I believe it's client-side, but it's not clear. 

So as @tsegismont said, we would need the network traffic triggering the issue to understand.

Having a way to reproduce the issue locally would be perfect.

**Comment by brianwyka** [comment] 2024-08-27 13:08
@cescoffier , there were no updates on the client side, so how can it be a client-side issue?

**Comment by cescoffier** [comment] 2024-08-27 13:09
I meant the logged message you posted.

**Comment by brianwyka** [comment] 2024-08-27 13:14
Correct, that logged message is on the client-side calling application.

**Comment by brianwyka** [comment] 2024-08-27 13:28
@cescoffier , should I still attempt downgrading `implementation 'io.quarkus:quarkus-reactive-routes:3.12.3'`?  I don't see any code differences in that module other than pom changes.

**Comment by cescoffier** [comment] 2024-08-27 13:32
You need to downgrade vertx-web:
Add the following dependency:

```xml
<dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-web</artifactId>
    <version>4.5.8</version>
</dependency>
```

If still the same, do the same with vertx-core.

**Comment by brianwyka** [comment] 2024-08-27 14:48
@cescoffier , are there and access logs I can enable on the server side to log the traffic?  Would it be through this configuration?
https://quarkus.io/guides/http-reference#configuring-http-access-logs

**Comment by cescoffier** [comment] 2024-08-27 15:01
That would be a great start. Make sure the output contains the headers.

**Comment by brianwyka** [comment] 2024-08-28 14:32
The HTTP access logs did not contain anything for the failed gRPC error.

Reverting `vertx` dependencies to `4.5.7` did the trick.

**Comment by brianwyka** [comment] 2024-08-29 13:08
I downgraded them all to make sure first.  I'll do some follow-up testing to narrow it down, starting with `vertx-web`.

**Comment by cescoffier** [comment] 2024-08-29 15:39
Thanks! That would be super useful!

**Comment by brianwyka** [comment] 2024-08-29 16:13
I've downgraded only `vert-web` to version `4.5.7` and everything is working as expected.  Seems the issue is in there or another transitive `vertx` dependency of web.

**Comment by cescoffier** [comment] 2024-08-30 06:50
Thanks!

@tsegismont So, it's a change in vert.x web. Looking at the commits (https://github.com/vert-x3/vertx-web/commits/4.5.8/), I believe the host/authority header commit broke this one.

**Comment by tsegismont** [comment] 2024-08-30 06:56
OK, thanks for digging into this @brianwyka 

It means either the gRPC Client or a proxy is sending gRPC traffic over HTTP/1.0 or over HTTP/1.1 without a host header. In both cases, this is wrong.

**Comment by brianwyka** [comment] 2024-08-30 09:55
Do you know how to correct this on the client side @tsegismont ?

**Comment by brianwyka** [comment] 2024-09-05 13:24
Looks like this is fixed in https://github.com/vert-x3/vertx-web/issues/2638 (Vertx `4.5.10`).    @cescoffier , which version of Quarkus will this be released in?

**Closed** 2024-09-05 16:18 UTC
Labels: kind/bug, area/grpc, triage/needs-reproducer

**Comment by brianwyka** [comment] 2024-09-26 12:54
@cescoffier, @tsegismont , seeing this again in Quarkus `3.15.0` even with `vertx-web:4.5.10` on classpath.  I was able to mitigate the issue by excluding `vertx-web` from the BOM and downgrading it to `4.5.7` and things work again...

```gradle
    implementation enforcedPlatform('io.quarkus:quarkus-bom:3.15.0') {
        exclude group: 'io.vertx'
    }
    implementation enforcedPlatform('io.vertx:vertx-stack-depchain:4.5.10') {
        exclude group: 'io.vertx', module: 'vertx-web'
    }
    configurations.configureEach {
        resolutionStrategy {
            force('io.vertx:vertx-web:4.5.7')
        }
    }
```

**Comment by cescoffier** [comment] 2024-09-26 18:21
Hum, this is weird. The 400 issue got fixed. 

We would really need a reproducer to better understand the issue.

**Comment by brianwyka** [comment] 2024-09-29 22:22
I'll see what I can do to provide one.
