### ISSUE TITLE
Hibernate Panache: merge() fails for detached entity after delete()

### ISSUE THREAD

**Issue by this-user** [quarkusio/quarkus#43050] opened 2024-09-05 12:52 UTC
### Describe the bug

While using Hibernate with Panache while trying to re-add a detached instance of an entity by calling the `merge()` method on the `EntityManager` throws an `jakarta.persistence.OptimisticLockException` if the same entity was remove by the `TestEntity.delete()` method inside the same transaction.

What is a bit strange is the message: `Row was updated or deleted by another transaction`, because everything should be happening inside the same transaction.

This used to work with recent versions of Quarkus up to 3.13.3 and only occurs starting with the 3.14 version and up to and including 3.14.2. Possibly, this may have something to do with the update of the upstream Hibernate version.

### Expected behavior

The entity is properly persisted again.

### Actual behavior

An exception is thrown upon calling `merge()`:

```
Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [com.test.hibernate.HibernateTest$TestEntity#1]
jakarta.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [com.test.hibernate.HibernateTest$TestEntity#1]
	at org.hibernate.internal.ExceptionConverterImpl.wrapStaleStateException(ExceptionConverterImpl.java:209)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:95)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:167)
	at org.hibernate.internal.ExceptionConverterImpl.convert(ExceptionConverterImpl.java:173)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:865)
	at org.hibernate.internal.SessionImpl.merge(SessionImpl.java:840)
	at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.merge(TransactionScopedSession.java:157)
	at org.hibernate.engine.spi.SessionLazyDelegator.merge(SessionLazyDelegator.java:272)
	at org.hibernate.Session_OpdLahisOZ9nWRPXMsEFQmQU03A_Synthetic_ClientProxy.merge(Unknown Source)
	at com.test.hibernate.HibernateTest.testPersistProfile(HibernateTest.java:39)
	at com.test.hibernate.HibernateTest_Subclass.testPersistProfile$$superforward(Unknown Source)
	at com.test.hibernate.HibernateTest_Subclass$$function$$1.apply(Unknown Source)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
	at io.quarkus.narayana.jta.runtime.interceptor.TestTransactionInterceptor.intercept(TestTransactionInterceptor.java:45)
	at io.quarkus.narayana.jta.runtime.interceptor.TestTransactionInterceptorGenerated_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
	at com.test.hibernate.HibernateTest_Subclass.testPersistProfile(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:973)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:823)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
Caused by: org.hibernate.StaleObjectStateException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect): [com.test.hibernate.HibernateTest$TestEntity#1]
	at org.hibernate.event.internal.DefaultMergeEventListener.entityIsDetached(DefaultMergeEventListener.java:421)
	at org.hibernate.event.internal.DefaultMergeEventListener.merge(DefaultMergeEventListener.java:212)
	at org.hibernate.event.internal.DefaultMergeEventListener.doMerge(DefaultMergeEventListener.java:150)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:130)
	at org.hibernate.event.internal.DefaultMergeEventListener.onMerge(DefaultMergeEventListener.java:87)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
	at org.hibernate.internal.SessionImpl.fireMerge(SessionImpl.java:854)
	... 20 more

```

### How to Reproduce?

```
package com.test.hibernate;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import io.quarkus.hibernate.orm.panache.Panache;
import io.quarkus.hibernate.orm.panache.PanacheEntity;
import io.quarkus.test.TestTransaction;
import io.quarkus.test.junit.QuarkusTest;
import jakarta.inject.Inject;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.fail;

@QuarkusTest
public class HibernateTest {
	
	@Inject
	ObjectMapper mapper;
	
	@Test
	@TestTransaction
	public void testMergeDetachedEntity() {
		
		final TestEntity entity = new TestEntity("MY_TEST_ENTITY");
		
		entity.persist();
		entity.delete();
		
		final TestEntity detachedEntity;
		try {
			detachedEntity = mapper.readValue(mapper.writeValueAsString(entity), TestEntity.class);
			Panache.getEntityManager().merge(detachedEntity);
		} catch (JsonProcessingException e) {
			fail();
		}
		
	}
	@Entity
	public static class TestEntity extends PanacheEntity {
		
		@NotBlank
		private String name;
		
		protected TestEntity() {}
		
		public TestEntity(String name) {
			this.name = name;
		}
		
		public @NotBlank String getName() {
			return name;
		}
		
		public void setName(@NotBlank String name) {
			this.name = name;
		}
	}
	
}
```

### Output of `uname -a` or `ver`

Linux 6.10.8 amd64

### Output of `java -version`

Eclipse Adoptium 21.0.3+9-LTS

### Quarkus version or git rev

3.14.x

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.10

**Comment by yrodiere** [comment] 2024-09-05 12:56
This looks like "Merging detects invalid attempts", already mentioned in the migration guide: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#upgrade-to-hibernate-orm-6-6
Details: https://docs.jboss.org/hibernate/orm/6.6/migration-guide/migration-guide.html#merge-versioned-entity-when-row-is-deleted

Please confirm that's the same problem? If so, this is expected behavior.

**Comment by this-user** [comment] 2024-09-05 13:33
I think you are right, in which case this can be closed. However, this is still an extremely annoying change as it means there is no longer any easy way of re-adding a deleted entity. I can either commit the first transaction, then add the entities back in a second one, which would be a bad way of doing it, if the second tx fails. Or I can walk through my entire entity structure and wipe out the IDs so I can persist the objects as new entities as far as Hibernate is concerned.

The last option is to avoid the deletes in the first place, but my use case is that all of the existing entities are supposed to be replaced by a given list of entities of the same type. I could sort through those two lists to figure out which entities are supposed to be deleted, which are supposed to be added, and which are supposed to be updated, but that's less efficient than deleting everything and then adding the entire new list, which is what is currently causing my problem.

**Comment by yrodiere** [comment] 2024-09-05 15:24
Thanks for the feedback! I will close this issue then.

Regarding the problems this additional check creates, I would recommend taking this to channels of the Hibernate team, because at the end of the day, Quarkus has little influence on this behavior. I doubt the change will be reverted, but Hibernate ORM maintainers may be able to offer alternative solutions (I know for example that the check doesn't apply to all identifier generators, so a custom identifier generator might help).
Here's where to find these people: https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user

**Closed by yrodiere** 2024-09-05 15:24 UTC
Labels: kind/bug, area/panache, area/hibernate-orm, triage/needs-feedback
