### ISSUE TITLE
Postgres reactive configuration doesn't allow for arbitrary parameters on connect string

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#25914] opened 2022-06-01 18:47 UTC
### Describe the bug

I'm trying to use Hibernate Reactive with Panache to connect the [quarkus superheroes `rest-heroes` app](https://github.com/quarkusio/quarkus-super-heroes/tree/main/rest-heroes) to CockroachDB. The app (Quarkus 2.9.2) works fine with Dev Services or a postgres db I stand up on my own.

I've done a similar thing with the [quarkus superheroes `rest-villains` app](https://github.com/quarkusio/quarkus-super-heroes/tree/main/rest-villains) with JDBC & Hibernate ORM with Panache and everything works fine.

When connecting to the Cockroach DB DBaaS, it is [mandatory that you include an `options=--clister=<cluster_name>` parameter](https://www.cockroachlabs.com/docs/v22.1/connection-parameters#connect-using-a-url), so I tried this configuration in the `application.yml`:

```yaml
quarkus:
  datasource:
    username: myusername
    password: mypassword
    reactive:
      url: postgresql://free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Dheroes-db-2463
      postgresql:
        ssl-mode: require
```

### Expected behavior

I would expect the `options` connection param to be passed along to the PG driver.

### Actual behavior

Instead I get this error:

```
15:48:28 INFO  [or.hi.re.pr.im.ReactiveIntegrator] (JPA Startup Thread: default-reactive) HR000001: Hibernate Reactive

15:48:29 WARN  [or.hi.re.pr.se.ReactiveGenerationTarget] (vert.x-eventloop-thread-0) HR000021: DDL command failed [io.vertx.pgclient.PgException: FATAL: codeParamsRoutingFailed: missing cluster identifier (08004)]
15:48:29 WARN  [or.hi.re.pr.se.ReactiveGenerationTarget] (vert.x-eventloop-thread-0) HR000021: DDL command failed [io.vertx.pgclient.PgException: FATAL: codeParamsRoutingFailed: missing cluster identifier (08004)]
```

This indicated that the parameter was not included.

I did this as a test and it works fine:

```java
@ApplicationScoped
public class StartupHelper {
  private final Vertx vertx;

  public StartupHelper(Vertx vertx) {
    this.vertx = vertx;
  }

  public void config(@Observes StartupEvent startupEvent) {
    Log.infof("Inside %s.config", getClass().getName());

    var connectOptions = new PgConnectOptions()
      .setPort(26257)
      .setHost("free-tier14.aws-us-east-1.cockroachlabs.cloud")
      .setDatabase("defaultdb")
      .setUser("myusername")
      .setPassword("mypassword")
      .setSslMode(SslMode.REQUIRE)
      .addProperty("options", "--cluster=heroes-db-2463");

    var poolOptions = new PoolOptions()
      .setMaxSize(5);

    var client = PgPool.client(this.vertx, connectOptions, poolOptions);

    client.query("DROP TABLE IF EXISTS Hero").execute()
      .onItem().invoke(() -> Log.info("Dropped Hero table"))
      .flatMap(r -> client.query("DROP SEQUENCE IF EXISTS hibernate_sequence").execute()
        .onItem().invoke(() -> Log.info("Dropped hibernate_sequence"))
      )
      .flatMap(r -> client.query("CREATE SEQUENCE hibernate_sequence START 1 INCREMENT 1").execute()
        .onItem().invoke(() -> Log.info("Created hibernate_sequence"))
      )
      .flatMap(r -> client.query("CREATE TABLE Hero (id int8 NOT NULL, level int4 NOT NULL, name VARCHAR(50) NOT NULL, otherName VARCHAR(255), picture VARCHAR(255), powers TEXT, PRIMARY KEY (id))").execute()
        .onItem().invoke(() -> Log.info("Created Hero table"))
      )
      .flatMap(r -> client.query("INSERT INTO hero(id, name, otherName, picture, powers, level) VALUES (nextval('hibernate_sequence'), 'Chewbacca', '', 'https://raw.githubusercontent.com/quarkusio/quarkus-super-heroes/characterdata/images/chewbacca--684239239428094811.jpg', 'Super Strength, Agility, Animal Attributes, Jaw Strength, Longevity, Marksmanship, Weapons Master', 30)").execute()
        .onItem().invoke(() -> Log.info("Inserted record into Hero table"))
      )
      .flatMap(r -> client.query("SELECT * FROM hero").execute()
        .onItem().invoke(ar -> Log.infof("Got %d rows", ar.size()))
      )
      .await().atMost(Duration.ofSeconds(20));

    client.close();
  }
}
```

Now the question is - how do I get that `options` parameter to stick in the Quarkus configuration? Is it a problem in the upstream Vert.x pg client? Or is there something we can/should do in Quarkus to solve for this? Maybe adding a config param in `io.quarkus.reactive.pg.client.runtime.DataSourceReactivePostgreSQLConfig` and read that in `io.quarkus.reactive.pg.client.runtime.PgPoolRecorder`?

### How to Reproduce?

Steps to reproduce:

1. You will need a cockroach labs account. I have a DB set up with credentials I can share if you would like. Please ping me privately (I don't want to share publicly).
2. Clone https://github.com/quarkusio/quarkus-super-heroes
3. `cd` into `rest-heroes`
4. Add the following to `src/main/resources/application.yml`:
   ```yaml
   quarkus:  
     datasource:
       username: myusername 
       password: mypassword
       reactive:
        url: postgresql://free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Dheroes-db-2463
        postgresql:
          ssl-mode: require
   ```
5. Run `quarkus dev`

### Output of `uname -a` or `ver`

```
Darwin edeandrea-m1pro 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64
```

### Output of `java -version`

```
openjdk version "17.0.3" 2022-04-19
OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7)
OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode)
```

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)
Maven home: /Users/edeandre/.m2/wrapper/dists/apache-maven-3.8.4-bin/52ccbt68d252mdldqsfsn03jlf/apache-maven-3.8.4
Java version: 17.0.3, vendor: Eclipse Adoptium, runtime: /Users/edeandre/.sdkman/candidates/java/17.0.3-tem
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "12.4", arch: "aarch64", family: "mac"
```

**Comment by Sanne** [comment] 2022-06-01 19:44
@edeandrea remember that the documentation you're linking to is assuming the use of the "regular" jdbc driver - the vert.x drivers don't necessarily provide all the same features, and when they do configuration properties might have different names and/or semantics.

So I don't think we should allow passing any properties from the JDBC driver to the vert.x one - that will most likely be misleading.

**Comment by Sanne** [comment] 2022-06-01 20:08
> Or would it be better to fix it in the vert.x driver so that it doesn't drop the extra params in the [...]

I'm confused - didn't have a chance to look at the code - but why would you want to pass a parameter if the driver doesn't do anything with it? Are these properties passed transparently to the server in some way when using the JDBC driver? I could check but not at my desk now - it would surprise me though.

 > (I can share a reproducer internally - it has DB username/password credentials, so contact me internally @ Red Hat if you'd like access to it).

Would be lovely to have a reproducer which could be openly shared; and I'm not saying it just because of OSS spirit, but practically we'll need regression tests committed upstream so we would need to be able to reproduce in other environments as well.

**Comment by Sanne** [comment] 2022-06-01 20:21
I found the relevant code in the JDBC driver; right so any tuple of parameters passed to the "options" configuration property in the JDBC driver is directly encoded into the startup message when a connection is initiated to the server. So specifically "options" is a special property in sense that its content is indeed passed as-is to the server, without the driver needing to have any awareness about their meaning - other then including the encoded tuples in the packet.

The Vert.x driver would need to implement something similar, and then we can expose it in Quarkus - perhaps they do already, but let's see what @vietj thinks first.

> That would be hard IF you want to specifically test the connection to the CockroachDB service as it requires authentication [...]

We can spin up CockroachDB services via docker, like we do with other databases.

**Comment by Sanne** [comment] 2022-06-01 20:24
> > We can spin up CockroachDB services via docker, like we do with other databases.
> 
> Yes you could, but only their managed serverless offering requires and/or uses that parameter.

Ok, ic. We'll figure out something to test this :)  I suppose we can use a different "option" and query for it to be set in the current connection; we might even be able to test it on a regular PG.

**Comment by edeandrea** [comment] 2022-06-01 20:34
> The Vert.x driver would need to implement something similar, and then we can expose it in Quarkus - perhaps they do already, but let's see what @vietj thinks first.

FWIW - simply exposing it as a property to the `PgConnectOptions` seems to work. If I manually build a `PgConnectOptions` (in "vanilla" Vert.x or Quarkus)

```java
var connectOptions = new PgConnectOptions()
      .setPort(26257)
      .setHost("free-tier14.aws-us-east-1.cockroachlabs.cloud")
      .setDatabase("defaultdb")
      .setUser("myusername")
      .setPassword("mypassword")
      .setSslMode(SslMode.REQUIRE)
      .addProperty("options", "--cluster=heroes-db-2463");

    var poolOptions = new PoolOptions()
      .setMaxSize(5);

    var client = PgPool.client(this.vertx, connectOptions, poolOptions);
```

it works. What seems to be broken in vert.x though (which is what https://github.com/vert-x3/issues/issues/602 refers to) is that given 

```java
PgConnectOptions.fromUri("postgresql://free-tier14.aws-us-east-1.cockroachlabs.cloud:26257/defaultdb?sslmode=require&options=--cluster%3Dheroes-db-2463")
```

drops the `options` property.

**Comment by Sanne** [comment] 2022-06-01 20:41
I just looked into the vertx-sql-client code and it looks like it's already implemented:
 - https://github.com/eclipse-vertx/vertx-sql-client/blob/4e97b37ab6325aa082f47d70910e3e5e3195f809/vertx-db2-client/src/main/java/io/vertx/db2client/impl/DB2ConnectionFactory.java#L54-L61

content of those `properties` can be specified via `io.vertx.sqlclient.SqlConnectOptions#setProperties` - so it looks like someone just needs to patch the extension to pass these on.

**Comment by geoand** [comment] 2022-06-02 08:08
> so it looks like someone just needs to patch the extension to pass these on.

I think @edeandrea already signed up for it 😉

**Comment by edeandrea** [comment] 2022-06-02 13:57
@geoand / @Sanne I took a stab at this in #25931.

**Closed** 2022-06-06 21:45 UTC
Labels: kind/enhancement, area/reactive-sql-clients
