### ISSUE TITLE
ServiceConfigurationError "not a subtype" with Maven Failsafe using config. converter 

### ISSUE THREAD

**Issue by chris-asl** [quarkusio/quarkus#20014] opened 2021-09-09 06:38 UTC
### Describe the bug

When declaring a custom configuration converter, all the unit tests run fine via the Maven Surefire plugin, but when running the exact same test with the Maven Failsafe plugin it fails with an error.

### Expected behavior

Expected application to load the configuration properly.

### Actual behavior

In contrast, all the tests fail when using the Failsafe plugin (for the integration tests).

The error is shown below:
```
[INFO] Running org.acme.CustomConverterIT
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.519 s <<< FAILURE! - in org.acme.CustomConverterIT
[ERROR] org.acme.CustomConverterIT.shouldProvideConfigurationParams  Time elapsed: 0.004 s  <<< ERROR!
java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: org.acme.SubnetInfoCidrConverter not a subtype
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: org.acme.SubnetInfoCidrConverter not a subtype

[ERROR] org.acme.CustomConverterIT  Time elapsed: 0.519 s  <<< ERROR!
java.lang.NullPointerException
```

### How to Reproduce?

Reproducer:  

```shell script
git clone https://github.com/chris-asl/quarkus-custom-config-converter-error
cd quarkus-custom-config-converter-error
./mvnw clean verify
```

### Output of `uname -a` or `ver`

Linux homer 5.11.0-25-generic #27~20.04.1-Ubuntu SMP Tue Jul 13 17:41:23 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)  
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)
```

### Quarkus version or git rev

2.2.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home:  /home/chris/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java  version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.11.0-25-generic", arch: "amd64", family: "unix"
```

### Additional information

It seems like this relates to https://github.com/quarkusio/quarkus/issues/8920 fixed by https://github.com/quarkusio/quarkus/pull/8931

**Comment by stelapo** [comment] 2022-02-23 14:38
I have the same problem with Quarkus 2.6.3.Final.

`[ERROR] it.fcg.amt.agent.filelogs.test.MainLogsAppIT  Time elapsed: 3.596 s  <<< ERROR!
java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: it.fcg.amt.agent.filelogs.config.CustomListStringConverter not a subtype
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: it.fcg.amt.agent.filelogs.config.CustomListStringConverter not a subtype
`
Maybe didn't #8931 fix the issue? 
Do anyone have suggestions to resolve it?

**Comment by geoand** [comment] 2022-05-17 09:22
Is this still an issue with Quarkus `2.9.0.Final`?

If so, please attach a sample project

**Comment by mueihn** [comment] 2022-12-21 14:06
This seems to still be an issue with `2.14.2.Final`.

**Comment by mueihn** [comment] 2022-12-21 14:31
OK, in my case, the problem could be solved by increasing the version of the failsafe plugin from 3.0.0-M5 to 3.0.0-M7.

It seems that the problematic project was set up at a point in time when 3.0.0-M5 was still the current version. The newer Project was directly set up with 3.0.0-M7 and, thus, did not suffer from this issue.

**Comment by geoand** [comment] 2023-04-11 11:25
Closing as per the comments above

**Closed by geoand** 2023-04-11 11:25 UTC
Labels: kind/bug, area/maven
