### ISSUE TITLE
[2.0.0] Cannot create native image because Panache is broken?

### ISSUE THREAD

**Issue by senzu** [quarkusio/quarkus#18402] opened 2021-07-05 09:57 UTC
## Describe the bug
The following error message occurs: 

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved method during parsing: io.quarkus.hibernate.orm.panache.runtime.JpaOperations.getEntityManager(java.lang.Class, java.lang.Class). To diagnose the issue you can use the --allow-incomplete-classpath option. The missing method is then reported at run time when it is accessed the first time.
Trace:
        at parsing security.repository.UserRepository.getEntityManager(UserRepository.java)
Call path from entry point to security.repository.UserRepository.getEntityManager(Class):
        at security.repository.UserRepository.getEntityManager(UserRepository.java)
        at com.oracle.svm.reflect.PanacheRepositoryBase_getEntityManager_4e84aee7ad3e5ad5a355e27fa7314e6f6c1a71de_2899.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Method.java:566)
        at java.util.ServiceLoader$ProviderImpl.invokeFactoryMethod(ServiceLoader.java:737)
        at java.util.ServiceLoader$ProviderImpl.get(ServiceLoader.java:720)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.initializeLazyValue(SystemPropertiesSupport.java:216)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.setProperty(SystemPropertiesSupport.java:201)
        at com.oracle.svm.core.jdk.Target_java_lang_System.setProperty(JavaLangSubstitutions.java:285)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_ARRAY:Ljava_lang_System_2_0002esetProperty_00028Ljava_lang_String_2Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

### Expected behavior
The native image builds fine, like in release 1.13.7

### Actual behavior
The native image build fails

## To Reproduce

Create this two classes:

<pre><code>
@Entity
@Table(name = "users", uniqueConstraints = { @UniqueConstraint(columnNames = { "username" }, name = "users_unique")})
public class User extends PanacheEntityBase implements Serializable {

    @Id
    @NotNull
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "users_seq")
    @SequenceGenerator(
            name = "users_seq",
            sequenceName = "users_seq",
            allocationSize = 1,
            initialValue = 1)
    private Long id;
    @NotNull
    private String username;
    private String password;
    private String salt;
    @NotNull
    private Boolean using_guacamole;

    public User() {
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPassword() {
        return password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public Boolean getUsing_guacamole() {
        return using_guacamole;
    }

    public void setUsing_guacamole(Boolean using_guacamole) {
        this.using_guacamole = using_guacamole;
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", salt='" + salt + '\'' +
                ", using_guacamole=" + using_guacamole +
                '}';
    }
}
</code></pre>

<pre><code>
@ApplicationScoped
public class UserRepository implements PanacheRepository<User> {

    @Transactional
    public void add(User user, String password) {
        String salt = PasswordUtils.getSalt();
        user.setPassword(PasswordUtils.generateSecurePassword(password, salt));
        user.setSalt(salt);
        user.persist();
    }

    public User findUser(String username) {
       return find("username = :username",
               Parameters.with("username", username)).firstResult();
    }
}
</code></pre>

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)

### Quarkus version or git rev
2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: C:\apache-maven-3.8.1\bin\..
Java version: 11.0.11, vendor: GraalVM Community, runtime: C:\GraalVM\graalvm-ce-java11-21.1.0
Default locale: hu_HU, platform encoding: Cp1250
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Build command
mvn clean package -Pnative -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true

**Comment by FroMage** [comment] 2021-07-05 14:24
Thanks for reporting, this looks like a dupe of #18307

**Closed by FroMage** 2021-07-05 14:24 UTC
Labels: area/panache, kind/bug
