### ISSUE TITLE
Enable Gradle add-extension by update gradle project structure to isolate extensions dependencies

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#3102] opened 2019-07-05 08:21 UTC
the `build.gradle` `from` clause to embed the Quarkus extension dependencies
see https://github.com/gradle/kotlin-dsl/tree/master/samples/modularity

That way the add-extension logic could look for that file and edit it.
We can ask users to respect the structure or even make it a no edit file (less preferred).

**Comment by gwenneg** [comment] 2019-07-05 18:38
I'd like to work on this.

**Comment by emmanuelbernard** [comment] 2019-07-09 10:11
Cool, just keep @aloubyansky in the loop as he oversees our general dependency effort.

**Comment by gwenneg** [comment] 2019-07-09 15:32
Ok, I'll do that :) I'm sure there will be a few points to discuss in this upcoming PR.

**Comment by gwenneg** [comment] 2019-07-13 16:15
@aloubyansky @gsmet I found several classes in `quarkus-devtools-common` and `quarkus-devtool-common-core` which contain Maven-dedicated code which should probably be in `quarkus-maven-plugin` instead.

For example, the [AddExtensions](https://github.com/quarkusio/quarkus/blob/master/devtools/common/src/main/java/io/quarkus/cli/commands/AddExtensions.java) class relies on `org.apache.maven.model` classes.

Can I refactor this and move the Maven-dedicated code to `quarkus-maven-plugin` or is there a reason why it is in the `common` modules?

**Comment by gsmet** [comment] 2019-07-13 16:30
@aloubyansky is the right person to answer you but yeah, my inclination would be to have the Maven specific classes in the Maven plugin.

Let's wait for @aloubyansky 's blessing though as he might have things planned in this area.

**Comment by aloubyansky** [comment] 2019-07-13 21:17
Yes, looks like those are assuming that the project is configured in a `pom.xml`, so that could be moved to the Maven-specific module.

**Comment by gwenneg** [comment] 2019-07-13 21:25
Thanks for the answer @aloubyansky! I'll move some of the `common` code to the `quarkus-maven-plugin` then.

**Comment by Dufgui** [comment] 2019-08-09 17:24
@aloubyansky could you assign to me

**Comment by gwenneg** [comment] 2019-08-09 17:36
@Dufgui Did you code this already? I have some code sleeping on a branch for this issue that’s not far from being reviewable.

**Comment by Dufgui** [comment] 2019-08-09 17:46
yes just right there : https://github.com/quarkusio/quarkus/pull/3415/files#diff-18b35164523e4adadddda8b73af26c1aR34

It's reviewed and ready to be merged after CI.
I just need to add it in gradle task now

**Comment by Dufgui** [comment] 2019-08-09 17:47
sorry. I do it  in create project...

**Comment by gwenneg** [comment] 2019-08-09 17:48
Ok then the issue is yours :)

**Comment by Dufgui** [comment] 2019-08-09 17:50
thanks ;o)

**Comment by gwenneg** [comment] 2019-08-09 18:28
> sorry. I do it in create project...

Don't worry about it, it's my fault for putting this on hold for too long, I chose to focus on another enhancement.

**Comment by Dufgui** [comment] 2019-08-09 23:44
In  fact i do it, without changing the structure.

**Closed** 2019-08-12 10:12 UTC
Labels: enhancement
