### ISSUE TITLE
using @ Transaction in @ Observes print warning log: WARN  [io.agr.pool] (trans-consumer-4) Datasource '<default>': Closing open connection prior to commit

### ISSUE THREAD

**Issue by Clever-Wang** [quarkusio/quarkus#36877] opened 2023-11-05 06:54 UTC
### Describe the bug

Quarkus version ： 3.5.0

**Comment by yrodiere** [comment] 2023-11-06 07:29
Thank you but I think I'll need a little bit more information, like the extensions you're using.

Please provide a simple project (as a zip, github repo, ...) that reproduces the problem?

**Comment by mmusgrov** [comment] 2023-11-12 14:13
This problem looks like a duplicate of #18737 

I have a fix for it (#34160  ) but it fails one of the panache tests and I haven't had a chance to fully investigate why the test fails ... but let me take another look at the failing test and I will update this thread when I've figured it out.

The java stacktrace for the successful case is https://pastebin.com/Lk9UpUGv and for the unsuccessful case it is https://pastebin.com/rVUUSFAy

**Comment by mmusgrov** [comment] 2023-11-12 15:38
I found the issue with the PR, I wasn't re-throwing the exception during the before synchronization handler. I've updated my PR on the other issue with the fix so let's see how it does this time ...

**Comment by mmusgrov** [comment] 2023-11-12 22:41
Actually although throwing the exception fixes the failing test it will stop any subsequent beforeCompletion synchronizations from running so we will need a different strategy, or maybe the test is wrong - I will investigate further.

**Comment by yrodiere** [comment] 2023-11-13 08:04
> This problem looks like a duplicate of #18737

Alright, closing as duplicate of #18737 then.

@Clever-Wang feel free to chime in if you think this is a different problem, otherwise let's continue the conversation on #18737.

**Closed by yrodiere** 2023-11-13 08:04 UTC
Labels: kind/bug, triage/needs-reproducer, area/agroal
