### ISSUE TITLE
Kafka MutinyEmitter.sendAndAwait sometimes ruins blocking DB transaction. #context-propagation, smallrye-kafka, narayana

### ISSUE THREAD

**Issue by MatejPucihar** [quarkusio/quarkus#39099] opened 2024-03-01 08:37 UTC
### Describe the bug

Reproducer example can be found here:
https://github.com/MatejPucihar/kafka-db-tx

Scenario: 
- send rest http request (from test, every 1ms, to force exception)
- rest request is handler is a `@Transactional` method, which inserts something in DB and sends something to kafka. It must be blocking send, we want to commit out DB TX only if kafka message is ACKed. 

There is ~1:1000 chance that the handler will fail dramatically:
```
2024-03-01 08:32:55,162 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012094: Commit of action id 0:ffff0a010a48:e441:65e18477:d1d0 invoked while multiple threads active within it.
2024-03-01 08:32:55,163 WARN  [com.arj.ats.arjuna] (executor-thread-2) ARJUNA012107: CheckedAction::check - atomic action 0:ffff0a010a48:e441:65e18477:d1d0 commiting with 2 threads active!
2024-03-01 08:32:55,163 WARN  [com.arj.ats.jta] (executor-thread-2) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffff0a010a48:e441:65e18477:d1d0, node_name=quarkus, branch_uid=0:ffff0a010a48:e441:65e18477:d1d3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@2ea67dc) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
```

### Expected behavior

Exception should never occur

### Actual behavior

Exception 

### How to Reproduce?

https://github.com/MatejPucihar/kafka-db-tx
`./mvnw test`

### Output of `uname -a` or `ver`

happens on multiple OS/ARCHITECTURES. Linux amd64, Mac M1, K8s cluster...

**Comment by geoand** [comment] 2024-03-01 09:17
I assume this is a duplicate of #39098

**Closed by geoand** 2024-03-01 09:17 UTC
Labels: kind/bug, area/smallrye, area/kafka, area/mutiny, area/context-propagation, env/m1

**Comment by MatejPucihar** [comment] 2024-03-01 09:21
> I assume this is a duplicate of #39098

sry, no idea how that happened :( browser refresh I guess

**Comment by geoand** [comment] 2024-03-01 09:21
No worries :)
