### ISSUE TITLE
Documentation about writing extensions

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#810] opened 2019-02-08 08:59 UTC
Opening this based on a discussion on the mailing list:

Regardless of how complex it will be to write an extension, I believe that superb documentation will be necessary if we wish to build an ecosystem ( and it would be a damn shame if this amazing project does not get one :) ).
I would very much like to see both the general concerns that an extension needs to handle and a detailed section including various how-tos. Having links to how existing extensions solve various common problems would be great as well. Although I do expect people will have to look at the code of existing extensions and possibly the core, trying to minimize that as much as possible via great documentation will reduce friction IMHO.

**Comment by michaelpaesold** [comment] 2019-06-06 05:44
There is actually some work in progress regarding improved extension documentation, see #1964.

**Comment by emmanuelbernard** [comment] 2019-07-05 07:47
Dupe of https://github.com/quarkusio/quarkus/issues/2277

**Closed** 2019-07-05 07:47 UTC
Labels: duplicate
