### ISSUE TITLE
JPA bootstrap failing in 1.8.1.Final

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#12312] opened 2020-09-24 04:53 UTC
**Describe the bug**

I have a multi-module project which includes an ORM jar (with small persistence.xml and jandex index) which is used by a number of other projects.  This was all working fine up to and including Quarkus 1.7.3.Final.  However it is broken in 1.8.1.Final (haven't tried 1.8.0.Final).

The persistence.xml is being processed:

`2020-09-23 12:04:14,202 INFO  [main]:[LogHelper] HHH000204: Processing PersistenceUnitInfo [name: MyPU]
`

But it no longer sees the Entities once invoking JPA APIs:

`Caused by: java.lang.IllegalArgumentException: Not an entity: class com.my.Entity`

However they were augmented:

```
2020-09-24 12:23:40,079 DEBUG [pool-2-thread-16]:[Enhancer] Enhancing [com.my.Entity] as Entity
2020-09-24 12:23:40,079 DEBUG [pool-2-thread-16]:[Enhancer] Weaving in PersistentAttributeInterceptable implementation on [com.my.Entity]
2020-09-24 12:23:40,088 DEBUG [pool-2-thread-16]:[PersistentAttributeTransformer] Persistent fields for entity com.my.Entity: [...]
2020-09-24 12:23:40,108 DEBUG [main]:[QuarkusAugmentor] Quarkus augmentation completed in 2033ms
2020-09-24 12:23:40,287 DEBUG [main]:[feature] Hibernate Features Enabled
2020-09-24 12:23:40,287 DEBUG [main]:[orm] List of entities found by Quarkus deployment:
[..., com.my.Entity]
```

**To Reproduce**

Reproducer attached.  This is based off the hibernate-orm-quickstart.  I moved the service and test layers to hibernate-orm-svc-quickstart leaving hibernate-orm-quickstart just containing the Entity, persistence.xml and jandex.

Run the tests in hibernate-orm-svc-quickstart.  Toggle the Quarkus version in the pom.xml to see the difference (1.7.3.Final OK, 1.8.1.Final fails).

[Reproducer.zip](https://github.com/quarkusio/quarkus/files/5273510/Reproducer.zip)

**Comment by geoand** [comment] 2020-09-24 04:57
cc @Sanne

**Comment by Sanne** [comment] 2020-09-24 08:22
Many thanks for the reproducer!  We'll check it out, unfortunately can't jump on it yet.

**Comment by jimbogithub** [comment] 2020-10-30 02:44
@Sanne This is still an issue in 1.9.1.  Any chance of taking a look soon?

**Comment by blxbrgld** [comment] 2020-11-27 13:37
Hi @jimbogithub I faced an issue similar with yours today while trying to upgrade from **1.7.3.Final** to **1.10.1.Final**. My project's structure is similar to yours and the problem seems to be fixed by adding: 

`<property name="hibernate.archive.autodetection" value="class" />`

in **persistence.xml** properties. Give it a try if you haven't already done so.

**Comment by jimbogithub** [comment] 2020-11-27 19:07
@blxbrgld Your suggestion works if I place a **persistence.xml** file in the service project (hibernate-orm-svc-quickstart in my reproducer), however in the real world we have a large number of these services so we are using the https://quarkus.io/guides/hibernate-orm#defining-entities-in-external-projects-or-jars approach.  Adding that setting to the shared **persistence.xml** there (hibernate-orm-quickstart in my reproducer) does not help.

**Comment by jimbogithub** [comment] 2020-11-27 19:56
@blxbrgld Apologies, you may be right, I think I didn't have a clean build above.  Adding that setting to the shared **persistence.xml** does appear to resolve the problem.  I'll confirm once I have things going in the real system.

**Comment by jimbogithub** [comment] 2020-11-27 22:59
@blxbrgld Confirmed, all working using your suggested change with **1.9.2.Final** (I'm not using **1.10.1.Final** due to an unrelated issue).

@Sanne If you think this is a sensible solution, then you can close this issue.  Maybe recommend this `<property name="hibernate.archive.autodetection" value="class" />` setting in the https://quarkus.io/guides/hibernate-orm#defining-entities-in-external-projects-or-jars docs?

**Comment by gsmet** [comment] 2020-11-27 23:04
@jimbogithub 

> (I'm not using 1.10.1.Final due to an unrelated issue).

Which issue?

> Maybe recommend this <property name="hibernate.archive.autodetection" value="class" /> setting

Yeah I had to change this when working on the multiple persistence units implementation.

It should be in the migration guide for 1.8.

That being said, I think we should clearly state that using a `persistence.xml` is not really recommended.

**Comment by gsmet** [comment] 2020-11-27 23:13
I pushed a PR here: https://github.com/quarkusio/quarkus/pull/13530 and added a note to the migration guide.

**Comment by jimbogithub** [comment] 2020-11-27 23:20
> @jimbogithub
> 
> > (I'm not using 1.10.1.Final due to an unrelated issue).
> 
> Which issue?

quarkus-maven-plugin does not recognise source / target / jvmArgs in configuration.  I haven't dug any deeper.

**Comment by geoand** [comment] 2021-07-26 15:16
Is this still an issue?

**Comment by jimbogithub** [comment] 2021-07-26 21:04
It is solved by the solution documented at https://github.com/quarkusio/quarkus/wiki/Migration-Guide-1.8#hibernate-orm

**Closed** 2021-10-08 08:12 UTC
Labels: kind/bug
