### ISSUE TITLE
consuming several kafka messages causes issue

### ISSUE THREAD

**Issue by jigneshmpatel** [quarkusio/quarkus#32835] opened 2023-04-22 03:29 UTC
### Describe the bug

In the following code:

```java
    @Incoming("requests")
    @Outgoing("billingdata")
    @Retry(delay = 20, delayUnit = ChronoUnit.SECONDS, maxRetries = 0)
    public CompletionStage<Void> processEvent(Message<String> incomingjsonreceive){
         return CompletableFuture.runAsync(()-> processmessage(incomingjsonreceive.getPayload())).thenRun(incomingjsonreceive::ack);
    }
```

The system is able to process few messages, but if there are 50+ messages then quarkus consumer rebalances the group. why would that is happening.

### Expected behavior

The consumer should be able to process all the messages.

### Actual behavior

The consumer gets rebalanced and then not able to consume the messages.

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 LTS

### Quarkus version or git rev

2.8.0.Final

**Comment by cescoffier** [comment] 2023-04-22 17:56
It's not Quarkus that rebalance the group, it's the broker managing the consumer group. It's because you didn't poll enough (you must poll at least once per session time).

**Comment by jigneshmpatel** [comment] 2023-04-22 21:44
Thank you very much Clement.
Please elaborate a little bit more about the following, as I am
anticipating the quarkus code must be pulling it.
"It's because you didn't poll enough (you must poll at least once per
session time)."

**Comment by cescoffier** [comment] 2023-04-23 08:17
There are many reasons why your application may not allow the underlying client to poll enough:

- long processing
- blocking processing

These conditions are now handled by Quarkus.

For reference, I recommend https://www.youtube.com/watch?v=paVdXL5vDzg - I talk about the consumer basics at 01:00:00 and rebalance at 02:02:00

**Comment by jigneshmpatel** [comment] 2023-04-27 16:22
It seems if there is a lag then kafka rebalance the group and never reconnects the application.
Why would a lag forces to rebalance the group.

**Comment by jigneshmpatel** [comment] 2023-04-27 21:49
Now I have bumped up the quarkus version to 3.0.0.CR2.
And then getting totally not understandable error:

-consumer   | 21:40:42 INFO  [co.ic.bi.re.CustomerRepository] (ForkJoinPool.commonPool-worker-1) customerId: 12345678910
consumer   | Hibernate: 
consumer   |     select
consumer   |         c1_0.ID,
consumer   |         c1_0.CUSTOMER_ID,
consumer   |         c1_0.NAME,
consumer   |         c1_0.PARENT_ID,
consumer   |         c1_0.STATUS 
consumer   |     from
consumer   |         CUSTOMER c1_0 
consumer   |     where
consumer   |         c1_0.CUSTOMER_ID=? limit ?
consumer   | 21:40:42 ERROR [io.sm.re.me.kafka] (ForkJoinPool.commonPool-worker-1) SRMSG18207: Unable to dispatch message to Kafka: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
consumer   | 	[Exception 0] java.lang.ClassCastException: class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')


Is this because of version.
The code is very simple
    @Transactional(REQUIRED)
    public Customer findByCustomerId(String customerId) {
        logger.info("customerId: "+customerId);
        return find("customerId",customerId).firstResult();
    }
    
    how to solve as the error is not even understandable.

**Comment by cescoffier** [comment] 2023-04-28 06:06
Can you post the full code (entity and the part dealing with Kafka)?

**Comment by jigneshmpatel** [comment] 2023-04-28 11:52
@Builder
@AllArgsConstructor
@Entity
@NoArgsConstructor
@Getter
@Setter
@ToString
@Table(name = "CUSTOMER")
//@EqualsAndHashCode(callSuper=false)
public class Customer extends PanacheEntityBase{

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Basic(optional = false)
	@Column(name = "ID", nullable = false, length = 11)
	private Integer id;

	
	@Column(name="CUSTOMER_ID", length = 50, unique=true, nullable = false)
	private String customerId;	

	@Column(name = "NAME", length = 50,  nullable =false)
	private String name;
	
	@Enumerated(EnumType.STRING)    
    @Column(name = "STATUS",columnDefinition = "enum ('A', 'I') default 'A'", nullable = false, length = 1)
    private StatusEnum status;

    @JoinColumn(name = "PARENT_ID", referencedColumnName = "ID", nullable = true)
    @ManyToOne(fetch = FetchType.LAZY)
    private Customer parentId;
}

import com.xxxr.entity.Customer;
import com.xxx.exception.IcareBillingException;
import io.quarkus.hibernate.orm.panache.PanacheRepositoryBase;
import jakarta.enterprise.context.ApplicationScoped;
import jakarta.inject.Inject;
import jakarta.persistence.EntityManager;
import jakarta.transaction.Transactional;
import org.jboss.logging.Logger;

import static jakarta.transaction.Transactional.TxType.REQUIRED;

@ApplicationScoped
public class CustomerRepository implements PanacheRepositoryBase<Customer,Integer> {

    private static final Logger logger = Logger.getLogger(CustomerRepository.class);
    @Inject
    EntityManager entityManager;
    /**
     * Find Customer data base on customerId
     * @param customerId
     */
    @Transactional(REQUIRED)
    public Customer findByCustomerId(String customerId) throws Exception {
        logger.info("customerId: "+customerId);
        Customer entity=entityManager.find(Customer.class,customerId);
        if(entity == null){
            throw newException("Customer with id of " + customerId + " does not exist.");
        }
        return entity;
    }
}

kafka.auto.offset.reset=earliest
#kafka.bootstrap.servers=td-kafka01-s1:9092,td-kafka02-s1:9092,td-kafka03-s1:9092
heartbeat.interval.ms=3000
session.timeout.ms=60000
max.poll.interval.ms=300000

# Set the Kafka topic, as it's not the channel name
mp.messaging.incoming.requests.connector=smallrye-kafka
mp.messaging.incoming.requests.topic=data-requests
mp.messaging.incoming.requests.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.requests.group.id=consumer



#mp.messaging.incoming.requests.value.deserializer=com.xxxxx.processor.Deserializer
#mp.messaging.incoming.requests.value-deserialization-failure-handler=com.icare.billingconsumer.processor.deserd.DeserializationFailureHandler


# Configure the outgoing  Kafka topic
mp.messaging.outgoing.billingdata.value.serializer=io.quarkus.kafka.client.serialization.ObjectMapperSerializer
mp.messaging.incoming.requests.broadcast=true


# datasource configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=schema
quarkus.datasource.password=passwd
quarkus.datasource.jdbc.url=<URL>
quarkus.datasource.jdbc.max-size=25
quarkus.hibernate-orm.log.sql=true

#quarkus.smallrye-health.root-path=/health
#quarkus.health.extensions.enabled=true
#quarkus.kafka.health.enabled=true


# Send output to a log file under the given directory path
quarkus.log.file.enable=true

**Comment by cescoffier** [comment] 2023-04-28 12:36
Where is the code emitting to Kafka? 
Can you also create a standalone GitHub repository with your code?

**Comment by jigneshmpatel** [comment] 2023-04-28 22:46
The error is changed
 	Suppressed: io.smallrye.reactive.messaging.providers.ProcessingException: SRMSG00103: Exception thrown when calling the method com.acme.consumer.processor.Consumer#processEvent
		at io.smallrye.reactive.messaging.providers.ProcessorMediator.handlePostInvocation(ProcessorMediator.java:369)
		at io.smallrye.reactive.messaging.providers.ProcessorMediator.lambda$processMethodReturningACompletionStageOfPayloadAndConsumingIndividualItem$51(ProcessorMediator.java:423)
		at io.smallrye.context.impl.wrappers.SlowContextualBiFunction.apply(SlowContextualBiFunction.java:21)
		at io.smallrye.mutiny.operators.uni.UniOnItemOrFailureFlatMap$UniOnItemOrFailureFlatMapProcessor.performInnerSubscription(UniOnItemOrFailureFlatMap.java:86)
		... 39 more
	Caused by: org.hibernate.type.descriptor.java.CoercionException: Error coercing value
		at org.hibernate.type.descriptor.java.CoercionHelper.coerceWrappingError(CoercionHelper.java:396)
		at org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:182)
		at org.hibernate.type.descriptor.java.IntegerJavaType.coerce(IntegerJavaType.java:24)
		at org.hibernate.loader.internal.IdentifierLoadAccessImpl.doLoad(IdentifierLoadAccessImpl.java:176)
		at org.hibernate.loader.internal.IdentifierLoadAccessImpl.lambda$load$1(IdentifierLoadAccessImpl.java:160)
		at org.hibernate.loader.internal.IdentifierLoadAccessImpl.perform(IdentifierLoadAccessImpl.java:107)
		at org.hibernate.loader.internal.IdentifierLoadAccessImpl.load(IdentifierLoadAccessImpl.java:160)
		at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2401)
		at org.hibernate.internal.SessionImpl.find(SessionImpl.java:2367)
		at io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession.find(TransactionScopedSession.java:175)
		at org.hibernate.engine.spi.SessionLazyDelegator.find(SessionLazyDelegator.java:784)
		at org.hibernate.Session_3a974b6a18ac399f675913d732c105426414d370_Synthetic_ClientProxy.find(Unknown Source)
		at com.acme.consumer.repository.CustomerRepository.findByCustomerId(CustomerRepository.java:27)
		at com.acme.consumer.repository.CustomerRepository_Subclass.findByCustomerId$$superforward(Unknown Source)
		at com.acme.consumer.repository.CustomerRepository_Subclass$$function$$1.apply(Unknown Source)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:74)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:63)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
		at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
		at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
		at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:38)
		at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:26)
		at com.acme.consumer.repository.CustomerRepository_Subclass.findByCustomerId(Unknown Source)
		at com.acme.consumer.repository.CustomerRepository_ClientProxy.findByCustomerId(Unknown Source)
		at com.acme.consumer.service.CustomerService.findByCustomerId(CustomerService.java:23)
		at com.acme.consumer.service.CustomerService_ClientProxy.findByCustomerId(Unknown Source)
		at com.acme.consumer.service.BService.process(BService.java:41)
		at com.acme.consumer.service.BService_ClientProxy.process(Unknown Source)
		at com.acme.consumer.processor.Consumer.lambda$processEvent$0(Consumer.java:32)
		at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
		... 6 more
	Caused by: java.lang.NumberFormatException: For input string: "2020110000107"
		at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
		at java.base/java.lang.Integer.parseInt(Integer.java:668)
		at java.base/java.lang.Integer.parseInt(Integer.java:786)
		at org.hibernate.type.descriptor.java.IntegerJavaType.lambda$coerce$0(IntegerJavaType.java:183)
		at org.hibernate.type.descriptor.java.CoercionHelper.coerceWrappingError(CoercionHelper.java:393)
		... 39 more
	[CIRCULAR REFERENCE:org.hibernate.type.descriptor.java.CoercionException: Error coercing value]

Created GitHub repo and invited you.

**Comment by cescoffier** [comment] 2023-04-29 10:58
It seems to be because of java.lang.NumberFormatException: For input string: "2020110000107"

It's too big  for an integer.

**Comment by jigneshmpatel** [comment] 2023-04-29 11:20
But it is a string attribute in database too. Integer is a different key.

**Comment by jigneshmpatel** [comment] 2023-04-29 11:23
The code was working with older version of hibernate.

**Comment by jigneshmpatel** [comment] 2023-04-29 17:26
I believe this class is a problem,  PanacheRepositoryBase<Customer,Integer> not able to execute the code properly.

**Comment by jigneshmpatel** [comment] 2023-04-30 11:18
ok found the issue.
The new version doesn't like @Enumerated
If my entity has
	@Enumerated(EnumType.STRING)
	@Column(name = "STATUS",columnDefinition = "enum ('A', 'I') default 'A'", nullable = false, length = 1)
	private StatusEnum status
then it keeps me giving following error:
ClassCast class java.lang.Character cannot be cast to class java.lang.String (java.lang.Character and java.lang.String are in module java.base of loader 'bootstrap')

**Comment by geoand** [comment] 2023-05-08 12:47
As mentioned above, we'll need a sample application in order to investigate

**Comment by cescoffier** [comment] 2023-05-09 04:57
It does not seem to be a kafka issue (anymore), but an hibernate issue.

**Comment by cescoffier** [comment] 2023-05-21 16:06
Closing - please re-open with a reproducer.

**Closed by cescoffier** 2023-05-21 16:06 UTC
Labels: kind/bug, area/kafka, triage/needs-reproducer
