### ISSUE TITLE
Dependency injection problem on quarkus 0.20.0

### ISSUE THREAD

**Issue by matheus-meneses** [quarkusio/quarkus#3425] opened 2019-08-05 13:01 UTC
**Describe the bug**
I'm working in a quarkus maven multi module on quarkus 0.19.1 and every thing works fine!
I just have upgraded to quarkus version 0.20.0 and all my dependency injection is not working 
Is there any breaking change to dependency injection from quarkus 0.19.1 to quarkus 0.20.0.

If i go back to version 0.19.1 everything works fine!

**Expected behavior**
All dependency injection created

**Actual behavior**
Declared beans is not created

**To Reproduce**
1. Using quarkus 0.20.0 with maven multi-module
2. Creating a bean @Default
3. Start the application in dev mode

**Configuration**
My parent pom.xml
```xml
    <groupId>br.com.dummyproject</groupId>
    <artifactId>inter-quarkus-framework-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <surefire-plugin.version>2.22.1</surefire-plugin.version>
        <quarkus.version>0.20.0</quarkus.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <spring.context.version>5.1.9.RELEASE</spring.context.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>br.com.dummyproject</groupId>
                <artifactId>inter-workflow-module</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>br.com.dummyproject</groupId>
                <artifactId>inter-logging-module</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>br.com.dummyproject</groupId>
                <artifactId>inter-security-module</artifactId>
                <version>${project.parent.version}</version>
            </dependency>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-arc</artifactId>
            </dependency>
            <dependency>
                <groupId>io.rest-assured</groupId>
                <artifactId>rest-assured</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-junit5</artifactId>
                <scope>test</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-context</artifactId>
                <version>${spring.context.version}</version>
            </dependency>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-spring-di</artifactId>
            </dependency>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-resteasy</artifactId>
                <version>${quarkus.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
            <version>${quarkus.version}</version>
        </dependency>
    </dependencies>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${surefire-plugin.version}</version>
                    <configuration>
                        <systemProperties>
                            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                        </systemProperties>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>io.quarkus</groupId>
                    <artifactId>quarkus-maven-plugin</artifactId>
                    <version>${quarkus.version}</version>
                </plugin>
            </plugins>
        </pluginManagement>
        <plugins>
            <plugin>
                <groupId>org.jboss.jandex</groupId>
                <artifactId>jandex-maven-plugin</artifactId>
                <version>1.0.6</version>
                <executions>
                    <execution>
                        <id>make-index</id>
                        <goals>
                            <goal>jandex</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                        <version>${quarkus.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <configuration>
                                    <enableHttpUrlHandler>true</enableHttpUrlHandler>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemProperties>
                                        <native.image.path>
                                            ${project.build.directory}/${project.build.finalName}-runner
                                        </native.image.path>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

    <modules>
        <module>inter-workflow-module</module>
        <module>inter-logging-module</module>
        <module>inter-security-module</module>
    </modules>
```

My application.properties

```properties
quarkus.resteasy.path=/api/inter-dummy-quarkus-project-service/v1
quarkus.log.file.enable=true
service.context=inter-dummy-quarkus-project-service

quarkus.log.file.path=/dev/sources/microservices/quarkus-projects/inter-dummy-quarkus-project-service/logs/log-error.log
quarkus.log.file.level=ERROR
quarkus.log.file.format={"timestamp":"%d{YYYY-MM-dd HH:mm:ss}", "service":"${service.context}", "thread":"[%t]", "level":"%p", "meta":%s}%n
```

**Screenshots**
Application boot on quarkus 0.20.0
![image](https://user-images.githubusercontent.com/7905123/62466253-4b0a6e00-b767-11e9-9144-e8d086ce020c.png)

Application boot on quarkus 0.19.1
![image](https://user-images.githubusercontent.com/7905123/62466450-b94f3080-b767-11e9-9a7e-99fa3633a71a.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin 002361 17.7.0 Darwin Kernel Version 17.7.0: Wed Apr 24 21:17:24 PDT 2019; root:xnu-4570.71.45~1/RELEASE_X86_64 x86_64
 - Output of `java -version`:  1.8
 - GraalVM version (if different from Java): 19.1.1
 - Quarkus version or git rev: https://github.com/quarkusio/quarkus/releases/tag/0.20.0

**Additional context**
(Add any other context about the problem here.)

**Comment by gwenneg** [comment] 2019-08-08 07:38
Hi @matheus-meneses and thanks for reporting this.

We may need a reproducer to investigate your issue, but first let's ask @mkouba and @manovotn if they have an idea about what's causing this.

**Comment by matheus-meneses** [comment] 2019-08-09 19:17
Hi, @gwenneg what information do you need?

**Comment by gwenneg** [comment] 2019-08-10 11:55
@matheus-meneses Well, for now we just need to wait for an answer from the dependency injection experts :) It might take a bit longer than usual if they are on vacation.

**Comment by mkouba** [comment] 2019-08-12 05:10
Hi @matheus-meneses, does it only happen in the development mode? It would be great if you could put together a minimal reproducer app.

**Comment by matheus-meneses** [comment] 2019-08-12 11:05
@mkouba what information do you need? I'm in quarkus zullip chat, if you want we can speak there

**Comment by anadollu** [comment] 2019-08-12 11:59
please check it out you have already add resources/META-INF/beans.xml files to any module projects.

**Comment by gsmet** [comment] 2019-08-12 12:06
@matheus-meneses if you could set up a simple project that you can share reproducing the issue, that will help us debugging it.

**Comment by matheus-meneses** [comment] 2019-08-12 12:15
i will do that, just a moment and i will post the link here.

**Comment by matheus-meneses** [comment] 2019-08-12 12:16
> please check it out you have already add resources/META-INF/beans.xml file to any module projects.

Is configured in all maven module

**Comment by matheus-meneses** [comment] 2019-08-12 13:48
@gsmet i posted the code on github and sent an invite to @mkouba. Do you an invite to repository too?

**Comment by mkouba** [comment] 2019-08-12 14:27
It turns out that it's not a regression but an application error that was previously hidden by a Spring DI extension bug fixed in this commit: https://github.com/quarkusio/quarkus/commit/91ed6ee7ffef4f1958c8d48fbbd1998460ed2286.

**Closed by mkouba** 2019-08-12 14:27 UTC
Labels: bug, component:arc, regression
