### ISSUE TITLE
Bean Validation on Vert.x Routes are not working to validate responses using Multi<>

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15166] opened 2021-02-18 13:18 UTC
**Describe the bug**
The guide describes how we can validate responses: https://quarkus.io/guides/reactive-routes#using-bean-validation. For example:

```
@Route(...)
@Valid Uni<Person> createPerson(@Body @Valid Person person, @NonNull @Param("id") String primaryKey) {
  // ...
}
```

This is working fine when using `Uni<...>`, but not using `Multi<...>`. For example:

```
@Route(...)
@Valid Multi<Person> listPerson(....) {
  // ...
}
```

**Expected behavior**
It should work the same as when using Uni reponse.

**Actual behavior**
Validation only works on Uni responses.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.0.Final

**Comment by gsmet** [comment] 2021-02-19 23:37
This is not a bug. The doc says that it’s supported by Uni. 

There’s no support for Multi for now. I know it raises some questions and it was decided to skip it for now.

**Comment by Sgitario** [comment] 2021-02-22 06:24
> This is not a bug. The doc says that it’s supported by Uni.
> 
> There’s no support for Multi for now. I know it raises some questions and it was decided to skip it for now.

Thanks for confirming this! I was expecting a strongest message in the guides: https://quarkus.io/guides/reactive-routes#using-bean-validation. Something alike "Note that this is only supported for objects or Uni, not Multi", but I guess "When returning an object or a Uni, you can also use the @Valid annotation" is suffice. We can revisit this in the future if needed. 

Should we keep this enhancement issue for future tracking then?

**Comment by cescoffier** [comment] 2021-03-01 10:00
The problem with `Multi` is that there is no clear canonical behavior. 
Imagine a Multi with multiple items, and one of them, not the first one, is invalid? You already sent the HTTP headers, so, you cannot change the response status. Maybe closing the response abruptly is enough, but the user has no idea why the response is closed.

**Comment by cescoffier** [comment] 2021-04-12 07:23
Closing as we explicitly don't support this case. See comment.

**Closed by cescoffier** 2021-04-12 07:23 UTC
Labels: area/reactive, kind/enhancement
