### ISSUE TITLE
RegisterForReflection Not Working Where Class Inheritance Hierarchy Spans Subprojects

### ISSUE THREAD

**Issue by mbchangellc** [quarkusio/quarkus#25404] opened 2022-05-05 19:05 UTC
### Describe the bug

Java Reflection API reports no methods for class with an inheritance hierarchy spanning multiple subprojects in a native build.  Attempting to find a method which is declared and public in a class annotated with RegisterForReflection results in a NoSuchMethodException.  When all classes are in a single project the method can be successfully looked up, no exception is thrown.  No issues when run using the VM, only occurs in native builds.

### Expected behavior

Public methods in classes annotated with RegisterForReflection can be looked up using the reflection API in both VM and native builds.

### Actual behavior

A NoSuchMethodException is thrown although the method is declared and public.

### How to Reproduce?

Build a native image using subproject3 in the attached project.  Running the project results in a NoSuchMethodException at startup.
[quarkus-reflection-subprojects.zip](https://github.com/quarkusio/quarkus/files/8634561/quarkus-reflection-subprojects.zip)
 

### Output of `uname -a` or `ver`

Darwin deimos 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "17.0.3" 2022-04-19 LTS Java(TM) SE Runtime Environment (build 17.0.3+8-LTS-111) Java HotSpot(TM) 64-Bit Server VM (build 17.0.3+8-LTS-111, mixed mode, sharing)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-mandrel:22.0.0.2-Final-java17

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

### Additional information

Full command line used to build: /gradlew clean subproject3:build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:22.0.0.2-Final-java17 -Dquarkus.container-image.build=true

**Comment by zakkak** [comment] 2022-05-06 13:17
I had a look in this and it's more confusing than I expected.

In the demo code `DtoContainer extends Container`, `DtoContainer` is defined in `subproject2` and annotated with `@RegisterForReflection` while `Container` is defined in `subproject1` and is also annotated with `@RegisterForReflection`.

* When compiling `subproject1`, `Container` gets registered for reflection as expected.
* When compiling `subproject2`, `DtoContainer` gets registered for reflection but `Container` does not.
* When compiling `subproject3`, I see the same behavior with `subproject2`.

So it appears like `RegisterForReflection` is working with subprojects and hierarchies in some cases, but not in others.

So what's the difference between subpoject1 and subproject2 that is causing this? `subproject2` contains a `beans.xml` file while `subpoject1` does not.

This results in Quarkus not indexing the `subproject1` while indexing `subproject2`. Quarkus detects the classes it needs to register for reflection by looking in the said index and looking for annotated classes:

https://github.com/quarkusio/quarkus/blob/09b13257e22b40757a7cb23fff758419b00ab9a1/core/deployment/src/main/java/io/quarkus/deployment/steps/RegisterForReflectionBuildStep.java#L27-L28

The index is defined as:
https://github.com/quarkusio/quarkus/blob/09b13257e22b40757a7cb23fff758419b00ab9a1/core/deployment/src/main/java/io/quarkus/deployment/builditem/CombinedIndexBuildItem.java#L9-L12

To my understanding only the current application's classes and those containing certain _marker files_ are being indexed and thus candidates to be registered for reflection. 

@stuartwdouglas can you please correct me if I am wrong and clarify whether this is a bug or a feature? (It seems like the latter to me)

FWIW a potential workaround would be to use a `RegisterForReflection` annotation that would register the whole class hierarchy. This functionality is being developed in https://github.com/quarkusio/quarkus/pull/24474/.

**Comment by mbchangellc** [comment] 2022-05-06 14:06
I confirmed adding the META-INF/beans.xml file resolves the issue in both the provided example project and our actual application.  Thanks very much for your help.  Let me know if I should close the ticket.

**Comment by gsmet** [comment] 2022-05-06 14:29
Submodules need to be indexed somehow. See https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module/55513723#55513723 for all the information about how to index things.

**Comment by Karm** [comment] 2022-11-18 14:19
Hello, @mbchangellc, have you tried with https://github.com/quarkusio/quarkus/pull/24474 ?

**Comment by zakkak** [comment] 2022-11-18 18:36
> Hello, @mbchangellc, have you tried with #24474 ?

Note: The actual changes are in https://github.com/quarkusio/quarkus/pull/27551

**Comment by zakkak** [comment] 2022-12-05 11:35
I am closing this as it seems like this is the expected behavior, i.e., non-indexed modules are not examined for annotations.

FTR: Regarding @Karm's question:

> Hello, @mbchangellc, have you tried with https://github.com/quarkusio/quarkus/pull/24474 ?

I confirm that using this feature is a valid workaround for this specific project, but only because `subproject2` is being indexed in the first place. So in order for this approach to work, the leaf classes we want registered for reflection need to be in an indexed module **and** annotated with `RegisterForReflection(registerFullHierarchy=true)`.

**Closed by zakkak** 2022-12-05 11:35 UTC
Labels: kind/bug, area/mandrel
