### ISSUE TITLE
Native build failing when using undertow

### ISSUE THREAD

**Issue by anthony-quiros** [quarkusio/quarkus#16732] opened 2021-04-22 15:11 UTC
## Describe the bug
Getting error when packaging in native:
```
Error: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from the command line). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf

com.oracle.svm.core.util.UserError$UserException: Classes that should be initialized at run time got initialized during image building:
 io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledByteBufAllocator$InstrumentedUnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledUnsafeHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledUnsafeHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledUnsafeHeapByteBuf
io.netty.buffer.UnpooledHeapByteBuf the class was requested to be initialized at run time (subtype of io.netty.buffer.AbstractReferenceCountedByteBuf). To see why io.netty.buffer.UnpooledHeapByteBuf got initialized use --trace-class-initialization=io.netty.buffer.UnpooledHeapByteBuf
io.netty.buffer.AbstractReferenceCountedByteBuf the class was requested to be initialized at run time (from the command line). To see why io.netty.buffer.AbstractReferenceCountedByteBuf got initialized use --trace-class-initialization=io.netty.buffer.AbstractReferenceCountedByteBuf

	at com.oracle.svm.core.util.UserError.abort(UserError.java:68)
	at com.oracle.svm.hosted.classinitialization.ConfigurableClassInitialization.checkDelayedInitialization(ConfigurableClassInitialization.java:539)
	at com.oracle.svm.hosted.classinitialization.ClassInitializationFeature.duringAnalysis(ClassInitializationFeature.java:226)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$runPointsToAnalysis$8(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.FeatureHandler.forEachFeature(FeatureHandler.java:70)
	at com.oracle.svm.hosted.NativeImageGenerator.runPointsToAnalysis(NativeImageGenerator.java:740)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:563)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:476)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Error: Image build request failed with exit status 1

```
### Configuration
```properties
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=test
quarkus.datasource.password=test
quarkus.datasource.reactive.url=postgresql://localhost/test
quarkus.hibernate-orm.database.generation=create
quarkus.hibernate-orm.database.generation.create-schemas=true
quarkus.log.level=TRACE
quarkus.log.category."org.hibernate".min-level=TRACE
quarkus.log.category."org.hibernate".level=TRACE
quarkus.swagger-ui.enable=true
quarkus.swagger-ui.always-include=true
quarkus.servlet.context-path=/static

```

### Output of `uname -a` or `ver`
Darwin MacBook-Pro-xxxxx.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06)
OpenJDK 64-Bit Server VM GraalVM CE 21.0.0.2 (build 11.0.10+8-jvmci-21.0-b06, mixed mode, sharing)
### Quarkus version or git rev
1.13.2.Final

**Comment by geoand** [comment] 2021-09-30 12:39
Can you add a reproducer for this please?

**Comment by Karm** [comment] 2021-12-07 12:52
Hello @anthony-quiros, could you put together a small reproducer for this? You can use something from https://code.quarkus.io/ or https://github.com/quarkusio/quarkus-quickstarts as a scaffolding.
Preferably with the latest Quarkus and Mandrel (or GraalVM), e.g. `-Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-mandrel:21.3-java11`

**Comment by wiebeck** [comment] 2021-12-08 11:29
@Karm I have prepared a minimal example to demonstrate the issue: https://github.com/wiebeck/code-with-quarkus

I went to https://code.quarkus.io/, selected Gradle with Kotlin DSL as build tool, left everything else unchanged and published the project to GitHub. Then I added native build properties to `application.properties` configuring containerized native build using the mandrel image. Finally I added the `azure-storage-blob` dependency from the `quarkus-camel-bom`. That's all.

Steps to reproduce: clone the repo, make sure you have Docker or Podman running and run `./gradlew build`.

Hope this helps.

**Comment by Karm** [comment] 2021-12-20 20:56
Hello, @wiebeck,

I don't think the problem, at least as far as demonstrated in your [reproducer](https://github.com/wiebeck/code-with-quarkus), has anything to do with Undertow per se.

All it takes to build the reproducer correctly is to remove the `azure-storage-blob` dependency in `build.gradle.kts`:
```
   15 dependencies {
   16     implementation(enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}"))
   17     implementation(enforcedPlatform("${quarkusPlatformGroupId}:quarkus-camel-bom:${quarkusPlatformVersion}"))
   18     implementation("io.quarkus:quarkus-arc")
   19     implementation("io.quarkus:quarkus-resteasy")
~  20 //    implementation("com.azure:azure-storage-blob")
   21     testImplementation("io.quarkus:quarkus-junit5")
   22     testImplementation("io.rest-assured:rest-assured")
   23 }
```
The reason is that it pulls a whole Netty distribution with it, see:

```
+--- com.azure:azure-storage-blob -> 12.14.1
|    +--- com.azure:azure-core:1.21.0
|    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.5
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.5 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.5 (*)
|    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.5
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.5 (*)
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.5 (*)
|    |    +--- com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.12.5
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.5 (*)
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.5 (*)
|    |    +--- com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.12.5
|    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.5 (*)
|    |    |    +--- com.fasterxml.jackson.module:jackson-module-jaxb-annotations:2.12.5
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-annotations:2.12.5 (*)
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-core:2.12.5 (*)
|    |    |    |    +--- com.fasterxml.jackson.core:jackson-databind:2.12.5 (*)
|    |    |    |    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.2 -> 2.3.3
|    |    |    |    |    \--- jakarta.activation:jakarta.activation-api:1.2.2 -> 1.2.1
|    |    |    |    +--- jakarta.activation:jakarta.activation-api:1.2.1
|    |    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.5 (*)
|    |    |    +--- org.codehaus.woodstox:stax2-api:4.2.1 -> 4.2
|    |    |    +--- com.fasterxml.woodstox:woodstox-core:6.2.4 -> 6.1.1
|    |    |    |    \--- org.codehaus.woodstox:stax2-api:4.2
|    |    |    \--- com.fasterxml.jackson:jackson-bom:2.12.5 (*)
|    |    +--- org.slf4j:slf4j-api:1.7.32 -> 1.7.30
|    |    +--- io.projectreactor:reactor-core:3.4.10
|    |    |    \--- org.reactivestreams:reactive-streams:1.0.3
|    |    \--- io.netty:netty-tcnative-boringssl-static:2.0.43.Final -> 2.0.44.Final
|    +--- com.azure:azure-core-http-netty:1.11.1
|    |    +--- com.azure:azure-core:1.21.0 (*)
|    |    +--- io.netty:netty-handler:4.1.68.Final -> 4.1.69.Final (*)
|    |    +--- io.netty:netty-handler-proxy:4.1.68.Final -> 4.1.69.Final (*)
|    |    +--- io.netty:netty-buffer:4.1.68.Final -> 4.1.69.Final (*)
|    |    +--- io.netty:netty-codec-http:4.1.68.Final -> 4.1.69.Final (*)
|    |    +--- io.netty:netty-codec-http2:4.1.68.Final -> 4.1.69.Final (*)
|    |    +--- io.netty:netty-transport-native-unix-common:4.1.68.Final -> 4.1.69.Final
|    |    |    +--- io.netty:netty-common:4.1.69.Final
|    |    |    +--- io.netty:netty-buffer:4.1.69.Final (*)
|    |    |    \--- io.netty:netty-transport:4.1.69.Final (*)
|    |    +--- io.netty:netty-transport-native-epoll:4.1.68.Final -> 4.1.69.Final
|    |    |    +--- io.netty:netty-common:4.1.69.Final
|    |    |    +--- io.netty:netty-buffer:4.1.69.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.69.Final (*)
|    |    |    \--- io.netty:netty-transport-native-unix-common:4.1.69.Final (*)
|    |    +--- io.netty:netty-transport-native-kqueue:4.1.68.Final -> 4.1.69.Final
|    |    |    +--- io.netty:netty-common:4.1.69.Final
|    |    |    +--- io.netty:netty-buffer:4.1.69.Final (*)
|    |    |    +--- io.netty:netty-transport:4.1.69.Final (*)
|    |    |    \--- io.netty:netty-transport-native-unix-common:4.1.69.Final (*)
|    |    \--- io.projectreactor.netty:reactor-netty-http:1.0.11
|    |         +--- io.netty:netty-codec-http:4.1.68.Final -> 4.1.69.Final (*)
|    |         +--- io.netty:netty-codec-http2:4.1.68.Final -> 4.1.69.Final (*)
|    |         +--- io.netty:netty-resolver-dns:4.1.68.Final -> 4.1.69.Final (*)
|    |         +--- io.netty:netty-resolver-dns-native-macos:4.1.68.Final -> 4.1.69.Final
|    |         |    +--- io.netty:netty-common:4.1.69.Final
|    |         |    +--- io.netty:netty-resolver-dns:4.1.69.Final (*)
|    |         |    \--- io.netty:netty-transport-native-unix-common:4.1.69.Final (*)
|    |         +--- io.netty:netty-transport-native-epoll:4.1.68.Final -> 4.1.69.Final (*)
|    |         +--- io.projectreactor.netty:reactor-netty-core:1.0.11
|    |         |    +--- io.netty:netty-handler:4.1.68.Final -> 4.1.69.Final (*)
|    |         |    +--- io.netty:netty-handler-proxy:4.1.68.Final -> 4.1.69.Final (*)
|    |         |    +--- io.netty:netty-resolver-dns:4.1.68.Final -> 4.1.69.Final (*)
|    |         |    +--- io.netty:netty-resolver-dns-native-macos:4.1.68.Final -> 4.1.69.Final (*)
|    |         |    +--- io.netty:netty-transport-native-epoll:4.1.68.Final -> 4.1.69.Final (*)
|    |         |    \--- io.projectreactor:reactor-core:3.4.10 (*)
|    |         \--- io.projectreactor:reactor-core:3.4.10 (*)
|    +--- com.azure:azure-storage-common:12.14.0
|    |    +--- com.azure:azure-core:1.21.0 (*)
|    |    \--- com.azure:azure-core-http-netty:1.11.1 (*)
|    \--- com.azure:azure-storage-internal-avro:12.1.1
|         +--- com.azure:azure-core:1.21.0 (*)
|         +--- com.azure:azure-core-http-netty:1.11.1 (*)
|         \--- com.azure:azure-storage-common:12.14.0 (*)
```

Netty is very sensitive to native image compilation and it has its special suite of modifications in Quarkus, see e.g. [NettySubstitutions.java](https://github.com/quarkusio/quarkus/blob/main/extensions/netty/runtime/src/main/java/io/quarkus/netty/runtime/graal/NettySubstitutions.java).  One cannot use arbitrary Netty version with an arbitrary Quarkus version.

There is an extension in the Quarkus Camel universe: [azure-storage-blob](https://github.com/apache/camel-quarkus/tree/main/extensions/azure-storage-blob).
You might want to check it out, e.g. in [integration-test-groups/azure/azure-storage-blob](https://github.com/apache/camel-quarkus/tree/main/integration-test-groups/azure/azure-storage-blob) to see what makes it tick and what are its supported Quarkus versions.

**Comment by geoand** [comment] 2022-11-08 11:53
Closing as per the comment above

**Closed by geoand** 2022-11-08 11:53 UTC
Labels: kind/bug, area/undertow
