### ISSUE TITLE
Quarkus uber/fat jar name not respecting project.build.finalName in version 1.13.(3-7).Final maven plugin, but property quarkus.package.output-name

### ISSUE THREAD

**Issue by WesternGun** [quarkusio/quarkus#18316] opened 2021-07-01 19:03 UTC
## Describe the bug
Quarkus uber/fat jar name does not respect project.build.finalName in version 1.13.3.Final Maven plugin; instead, it respects <quarkus.package.output-name> or property quarkus.package.output-name

### Expected behavior
When I change property project.build.finalName in my maven pom, I expect fat jar name changes respectively.

### Actual behavior
The fat jar name does not  change until I change quarkus.package.output-name in application.yaml, or in maven pom. 

## To Reproduce
Use the "getting-started" example from the doc, and

1. Define `quarkus.package.output-name=package-output-name` in application.properties
2. Define `<build><finalName>finalName</finalName></build>` in pom
3. Set `<quarkus.package.type>uber-jar</quarkus.package.type>` in pom properties part
4. Run `mvn package`
5. You see in console this line: `[INFO] [io.quarkus.deployment.pkg.steps.JarResultBuildStep] Building fat jar: /home/username/Code/getting-started/target/package-output-name-runner.jar`

### Configuration
```properties
# Add your application.properties here, if applicable.
quarkus.package.output-name=package-output-name
```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

## Environment (please complete the following information):
ubuntu 18.04
### Output of `uname -a` or `ver`
Linux elxag5zs8d3 5.4.0-77-generic #86~18.04.1-Ubuntu SMP Fri Jun 18 01:23:22 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
### Quarkus version or git rev
Tested with `1.13.3.Final` and `1.13.7.Final`. The versions in between as well, I guess.

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /opt/maven
Java version: 11.0.11, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.4.0-77-generic", arch: "amd64", family: "unix"

## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment] 2021-07-02 06:28
@gastaldi perhaps something you'd like to take a look at?

**Comment by gsmet** [comment] 2021-07-02 06:53
I'm not entirely sure we want to do that. @stuartwdouglas what's your take on this? Should we honor `finalName`?

**Comment by geoand** [comment] 2021-07-02 06:54
For the uber-jar, I think we should

**Comment by gastaldi** [comment] 2021-07-02 11:55
> @gastaldi perhaps something you'd like to take a look at?

Sure, I'll have a look

**Comment by gastaldi** [comment] 2021-07-02 15:32
Just ran these steps to reproduce that in 2.0 and it's correct that the `quarkus.package.output-name` has precedence over the `finalName`. 

Removing the `quarkus.package.output-name` property from the application.properties will use the `finalName` correctly, which is what I was curious about. 

Therefore, I am closing this issue, as this is not a bug.

**Closed by gastaldi** 2021-07-02 15:32 UTC
Labels: area/maven, kind/bug
