### ISSUE TITLE
native compile error on  io.vertx.redis.client.impl.RedisConnectionManager

### ISSUE THREAD

**Issue by kulame** [quarkusio/quarkus#19266] opened 2021-08-06 05:18 UTC
### Describe the bug

```shell
quarkus build --native
```

### Expected behavior

compile success

### Actual behavior

```shell
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Using docker to run the native image builder
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildContainerRunner] Checking image status quay.io/quarkus/ubi-quarkus-native-image:21.1.0-java16
21.1.0-java16: Pulling from quarkus/ubi-quarkus-native-image
Digest: sha256:3f8c119b36448a147e333fe2348d1b201969b26537d94cd2eae4bbc5118eecea
Status: Image is up to date for quay.io/quarkus/ubi-quarkus-native-image:21.1.0-java16
quay.io/quarkus/ubi-quarkus-native-image:21.1.0-java16
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM 21.1.0 Java 16 CE (Java Version 16.0.1+9-jvmci-21.1-b05)
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildRunner] docker run --env LANG=C --rm --user 1000:1000 -v /srv/project/ebiz/backend/target/backend-1.0.0-SNAPSHOT-native-image-source-jar:/project:z quay.io/quarkus/ubi-quarkus-native-image:21.1.0-java16 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=3 -J-Duser.language=en -J-Duser.country= -J-Dfile.encoding=UTF-8 --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy\$BySpaceAndTime -H:+JNI -H:+AllowFoldMethods -jar backend-1.0.0-SNAPSHOT-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https -H:NativeLinkerOption=-no-pie -H:-UseServiceLoaderFeature -H:+StackTrace backend-1.0.0-SNAPSHOT-runner
[backend-1.0.0-SNAPSHOT-runner:28]    classlist:   1,933.93 ms,  0.94 GB
[backend-1.0.0-SNAPSHOT-runner:28]        (cap):     678.07 ms,  0.94 GB
[backend-1.0.0-SNAPSHOT-runner:28]        setup:   2,396.30 ms,  0.94 GB
05:13:06,333 INFO  [org.jbo.threads] JBoss Threads version 3.4.0.Final
[backend-1.0.0-SNAPSHOT-runner:28]     analysis:  14,387.58 ms,  1.96 GB
Fatal error:com.oracle.graal.pointsto.util.AnalysisError$ParsingError: Error encountered while parsing io.vertx.redis.client.impl.RedisConnectionManager$RedisEndpoint.lambda$requestConnection$1(io.vertx.core.Handler, io.vertx.core.AsyncResult)
Parsing context:
        parsing io.vertx.redis.client.impl.RedisConnectionManager$RedisEndpoint$$Lambda$1664/0x00000007c17dee98.handle(Unknown Source)
        parsing io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:138)
        parsing io.vertx.mutiny.sqlclient.PreparedQuery$2.handle(PreparedQuery.java:135)
        parsing io.vertx.core.impl.future.FutureImpl$3.onSuccess(FutureImpl.java:124)
        parsing io.vertx.core.impl.future.FutureImpl$ListenerArray.onSuccess(FutureImpl.java:230)
        parsing io.vertx.core.impl.future.FutureBase.emitSuccess(FutureBase.java:62)
        parsing io.vertx.core.impl.future.FutureImpl.addListener(FutureImpl.java:164)
        parsing io.vertx.core.impl.future.PromiseImpl.addListener(PromiseImpl.java:23)
        parsing io.vertx.core.impl.future.FutureImpl.onComplete(FutureImpl.java:132)
        parsing io.vertx.core.impl.future.PromiseImpl.onComplete(PromiseImpl.java:23)
        parsing io.vertx.core.impl.CloseFuture.close(CloseFuture.java:111)
        parsing io.vertx.core.impl.CloseFuture.close(CloseFuture.java:138)
        parsing io.vertx.sqlclient.impl.PoolBase.close(PoolBase.java:209)
        parsing io.quarkus.reactive.pg.client.runtime.PgPoolRecorder$$Lambda$1226/0x00000007c173e5e0.run(Unknown Source)
        parsing java.lang.Shutdown.runHooks(Shutdown.java:130)
        parsing java.lang.Shutdown.exit(Shutdown.java:174)
        parsing java.lang.Runtime.exit(Runtime.java:114)
        parsing java.lang.System.exit(System.java:1769)
        parsing com.oracle.svm.core.option.XOptions.parse(XOptions.java:153)
        parsing com.oracle.svm.core.option.RuntimeOptionParser.parseAndConsumeAllOptions(RuntimeOptionParser.java:78)
        parsing com.oracle.svm.core.graal.snippets.CEntryPointSnippets.initializeIsolate(CEntryPointSnippets.java:279)

        at com.oracle.graal.pointsto.util.AnalysisError.parsingError(AnalysisError.java:138)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:327)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.ensureTypeFlowCreated(MethodTypeFlow.java:302)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.addContext(MethodTypeFlow.java:103)
        at com.oracle.graal.pointsto.DefaultAnalysisPolicy$DefaultSpecialInvokeTypeFlow.onObservedUpdate(DefaultAnalysisPolicy.java:368)
        at com.oracle.graal.pointsto.flow.TypeFlow.notifyObservers(TypeFlow.java:470)
        at com.oracle.graal.pointsto.flow.TypeFlow.update(TypeFlow.java:542)
        at com.oracle.graal.pointsto.BigBang$2.run(BigBang.java:547)
        at com.oracle.graal.pointsto.util.CompletionExecutor.lambda$execute$0(CompletionExecutor.java:173)
        at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1434)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:295)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
Caused by: org.graalvm.compiler.java.BytecodeParser$BytecodeParserError: jdk.vm.ci.common.JVMCIError: Unknown JvmConstant tag 17
        at parsing io.vertx.redis.client.impl.RedisConnectionManager$RedisEndpoint$$Lambda$1778/0x00000007c1813000.run(Unknown Source)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.throwParserError(BytecodeParser.java:2601)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3456)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:55)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase.run(GraphBuilderPhase.java:40)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:147)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.LambdaUtils.findStableLambdaName(LambdaUtils.java:91)
        at com.oracle.svm.hosted.lambda.LambdaProxyRenamingSubstitutionProcessor.lambda$getSubstitution$0(LambdaProxyRenamingSubstitutionProcessor.java:90)
        at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1740)
        at com.oracle.svm.hosted.lambda.LambdaProxyRenamingSubstitutionProcessor.getSubstitution(LambdaProxyRenamingSubstitutionProcessor.java:85)
        at com.oracle.svm.hosted.lambda.LambdaProxyRenamingSubstitutionProcessor.lookup(LambdaProxyRenamingSubstitutionProcessor.java:69)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.infrastructure.SubstitutionProcessor$ChainedSubstitutionProcessor.lookup(SubstitutionProcessor.java:125)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookupAllowUnresolved(AnalysisUniverse.java:207)
        at com.oracle.graal.pointsto.meta.AnalysisUniverse.lookup(AnalysisUniverse.java:187)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.lookup(IntrinsifyMethodHandlesInvocationPlugin.java:905)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.access$600(IntrinsifyMethodHandlesInvocationPlugin.java:166)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin$Transplanter.fixedWithNextNode(IntrinsifyMethodHandlesInvocationPlugin.java:696)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin$Transplanter.graph(IntrinsifyMethodHandlesInvocationPlugin.java:621)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.processInvokeWithMethodHandle(IntrinsifyMethodHandlesInvocationPlugin.java:567)
        at com.oracle.svm.hosted.phases.IntrinsifyMethodHandlesInvocationPlugin.handleInvoke(IntrinsifyMethodHandlesInvocationPlugin.java:279)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.tryNodePluginForInvocation(BytecodeParser.java:2232)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.appendInvoke(BytecodeParser.java:1899)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genDynamicInvokeHelper(BytecodeParser.java:1786)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1711)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genInvokeDynamic(BytecodeParser.java:1707)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5450)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBlock(BytecodeParser.java:3258)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.build(BytecodeParser.java:1125)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.buildRootMethod(BytecodeParser.java:1019)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.GraphBuilderPhase$Instance.run(GraphBuilderPhase.java:84)
        at com.oracle.svm.hosted.phases.SharedGraphBuilderPhase.run(SharedGraphBuilderPhase.java:76)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.run(Phase.java:49)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.BasePhase.apply(BasePhase.java:212)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:42)
        at jdk.internal.vm.compiler/org.graalvm.compiler.phases.Phase.apply(Phase.java:38)
        at com.oracle.graal.pointsto.flow.AnalysisParsedGraph.parseBytecode(AnalysisParsedGraph.java:113)
        at com.oracle.svm.hosted.SVMHost.parseBytecode(SVMHost.java:647)
        at com.oracle.graal.pointsto.meta.AnalysisMethod.ensureGraphParsed(AnalysisMethod.java:592)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.parse(MethodTypeFlowBuilder.java:163)
        at com.oracle.graal.pointsto.flow.MethodTypeFlowBuilder.apply(MethodTypeFlowBuilder.java:304)
        at com.oracle.graal.pointsto.flow.MethodTypeFlow.createTypeFlow(MethodTypeFlow.java:313)
        ... 13 more
Caused by: jdk.vm.ci.common.JVMCIError: Unknown JvmConstant tag 17
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotConstantPool$JvmConstants.get(HotSpotConstantPool.java:163)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotConstantPool.getTagAt(HotSpotConstantPool.java:309)
        at jdk.internal.vm.ci/jdk.vm.ci.hotspot.HotSpotConstantPool.lookupConstant(HotSpotConstantPool.java:522)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.lookupConstant(BytecodeParser.java:4407)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genLoadConstant(BytecodeParser.java:4058)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.processBytecode(BytecodeParser.java:5284)
        at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.iterateBytecodesForBlock(BytecodeParser.java:3451)
        ... 63 more
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  38.253 s
[INFO] Finished at: 2021-08-06T13:13:10+08:00
[INFO] ------------------------------------------------------------------------
```

### How to Reproduce?

quarkus build --native

### Output of `uname -a` or `ver`

Linux DESKTOP-I2R0JK3 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20 OpenJDK Runtime Environment (build 16.0.1+9-Ubuntu-120.04) OpenJDK 64-Bit Server VM (build 16.0.1+9-Ubuntu-120.04, mixed mode, sharing)

### GraalVM version (if different from Java)

quay.io/quarkus/ubi-quarkus-native-image:21.1.0-java1

### Quarkus version or git rev

2.0.2

### Additional information

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /home/kula/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1
Java version: 16.0.1, vendor: Private Build, runtime: /usr/lib/jvm/java-16-openjdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.4.72-microsoft-standard-wsl2", arch: "amd64", family: "unix"

**Comment by geoand** [comment] 2021-08-06 05:55
Can you please attach a small project that reproduces this behavior?

**Comment by kulame** [comment] 2021-08-06 07:07
yep
i upload my project 
https://github.com/kulame/ebiz/tree/master/backend

**Comment by geoand** [comment] 2021-08-06 13:30
Does the same thing happen if the project uses Java 11 instead of 16?
Asking because the Java 16 version of GraalVM is experimental and we don't support it

**Comment by cescoffier** [comment] 2022-01-30 16:52
When trying to compile the project with the Java 17 support of GraalVM, I get:
```
com.oracle.svm.core.util.UserError$UserException: Static modifier mismatch: private long io.quarkus.runtime.graal.Target_sun_java2d_cmm_lcms_LCMS.loadProfileNative(byte[],java.lang.Object), private static native long sun.java2d.cmm.lcms.LCMS.loadProfileNative(byte[],java.lang.Object)
```

It is different from the reported issue, which I believe was fixed.

**Comment by cescoffier** [comment] 2022-05-01 15:24
Closing - out of date.

**Closed by cescoffier** 2022-05-01 15:24 UTC
Labels: kind/bug, area/redis, area/native-image
