### ISSUE TITLE
GraphQL NullPointerException when running Quarkus project

### ISSUE THREAD

**Issue by talbiislam96** [quarkusio/quarkus#17733] opened 2021-06-07 15:40 UTC
Trying to build an api using GraphQL and Quarkus . I get NullPointerException whenever I run 
 mvn compile quarkus:dev

This is the my  api :

```
  @Query
    public Map<MissionDto, List<CaseTimesheetDto>> getAllSheetsForUser(@Name("year") int year, @Name("week") int week){
        return timeSheetGraphQlService.getTimesheetUser(year,week,getCurrentUserId().toString());

    }

```
current behavior :
```
 2021-06-07 16:34:58,440 WARN  [io.qua.dep.ide.IdeProcessor] (build-11) Unable to determine running IDE processes
2021-06-07 16:35:02,425 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor#buildExecutionService threw an exception: java.lang.NullPointerException
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:275)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.collectParametrizedTypes(ReferenceCreator.java:356)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:310)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.getReference(ReferenceCreator.java:245)
	at io.smallrye.graphql.schema.creator.ReferenceCreator.createReferenceForOperationField(ReferenceCreator.java:95)
	at io.smallrye.graphql.schema.creator.OperationCreator.createOperation(OperationCreator.java:70)
	at io.smallrye.graphql.schema.SchemaBuilder.addOperations(SchemaBuilder.java:229)
	at io.smallrye.graphql.schema.SchemaBuilder.generateSchema(SchemaBuilder.java:107)
	at io.smallrye.graphql.schema.SchemaBuilder.build(SchemaBuilder.java:80)
	at io.quarkus.smallrye.graphql.deployment.SmallRyeGraphQLProcessor.buildExecutionService(SmallRyeGraphQLProcessor.java:170)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)

```
I don't know what seems to be the problem here , I would appreciate a little help , thanks in advance.

**Comment by phillip-kruger** [comment] 2021-06-07 16:08
Hi @talbiislam96 .

I think the problem is the Map. At the moment map is not supported (in graphQL). We have been discussing how we can support it in SmallRye, basically, we create a object that contain key-value pairs. You can do that yourself for now. see https://github.com/smallrye/smallrye-graphql/issues/754

Also (just f.y.i) You can omit the `@Name` annotation in the method parameter, as the parameter name is the same as the annotation value. Typically name is only used when you want to change the name from the parameter.

Closing here as maps are not supported. If you want you can open a ticket in SmallRye GraphQL (or reopen the one mentioned above) and we can discuss a possible implementation.

**Closed by phillip-kruger** 2021-06-07 16:08 UTC
Labels: area/graphql, area/smallrye, kind/bug

**Comment by gsmet** [comment] 2021-06-07 16:09
I don't think we should close the issue. You can have things unsupported but you shouldn't throw a NPE but a proper error message. Can we make things better for the user?

**Comment by phillip-kruger** [comment] 2021-06-07 16:12
We can open a ticket in SmallRye for the NPE. I'll do that now.

**Comment by phillip-kruger** [comment] 2021-06-07 16:14
https://github.com/smallrye/smallrye-graphql/issues/842

**Comment by talbiislam96** [comment] 2021-06-07 17:03
@phillip-kruger Thank you so much for your answer , I hope the issues gets fixed as soon as possible , as for now I will try and create an object with key-value pairs as you suggested.
