### ISSUE TITLE
User methods requiring a session in Hibernate Reactive does not work for interfaces of Panache REST Data extension

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#34432] opened 2023-06-30 08:48 UTC
### Describe the bug

Two problems:

First, run `curl -H 'Content-Type: application/json' localhost:8080/bot --data-binary '{"id": "bot-a", "config": {}}' `, then these two commands fail:

1. `curl localhost:8080/bot` throws exception,  `rs.getString()` failed on JsonObject.

```
Caused by: java.lang.ClassCastException: Invalid String value type class io.vertx.core.json.JsonObject
                        at io.vertx.sqlclient.Tuple.getString(Tuple.java:410)
                        at org.hibernate.reactive.adaptor.impl.ResultSetAdaptor.getString(ResultSetAdaptor.java:80)
                        at org.hibernate.type.descriptor.jdbc.JsonJdbcType$2.doExtract(JsonJdbcType.java:140)
                        at org.hibernate.type.descriptor.jdbc.BasicExtractor.extract(BasicExtractor.java:44)
                        at org.hibernate.reactive.sql.exec.spi.ReactiveValuesResultSet.lambda$readCurrentRowValues$2(ReactiveValuesResultSet.java:145)
                        ... 35 more
```

2. `curl localhost:8080/bot/all2` throws exception too:
```
java.lang.IllegalStateException: No current Mutiny.Session found
        - no reactive session was found in the context and the context was not marked to open a new session lazily
        - you might need to annotate the business method with @WithSession
        at io.quarkus.hibernate.reactive.panache.common.runtime.SessionOperations.getSession(SessionOperations.java:155)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.getSession(AbstractJpaOperations.java:351)
        at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.findAll(AbstractJpaOperations.java:179)
```

BotResource.java:

```java
public interface BotResource extends PanacheEntityResource<BotEntity, String> {

    @GET
    @Path("/all2")
    @Produces("application/json")
    default Uni<List<BotEntity>> all2() {
        return BotEntity.findAll().list();
    }
}
```

BotEntity.java:

```java
import io.quarkus.hibernate.reactive.panache.PanacheEntityBase;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import java.time.Instant;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@Table(name = "bot")
public class BotEntity extends PanacheEntityBase {

    @Id
    @Column(length = 24, nullable = false)
    public String id;

    @Enumerated(EnumType.STRING)
    @Column(length = 8, nullable = false, columnDefinition = "VARCHAR(8) DEFAULT 'DRAFT'")
    public Status status = Status.DRAFT;

    @Column(name = "created_at", insertable = false, updatable = false,
            nullable = false, columnDefinition = "DATETIME DEFAULT current_timestamp")
    public Instant createdAt;

    @Column(name = "updated_at", insertable = false, updatable = false,
            nullable = false, columnDefinition = "DATETIME DEFAULT current_timestamp ON UPDATE current_timestamp")
    public Instant updatedAt;

    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    public BotConfig config;

    public static enum Status {
        DRAFT, REVIEW, REJECTED, APPROVED, DELETED
    }
}
```

BotConfig.java
```java
public class BotConfig {

    public String name;
}
```

### Expected behavior

Doesn't throw exception.

### Actual behavior

Throws exception.

### Output of `uname -a` or `ver`

Darwin xxx 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 21:00:17 PST 2023; root:xnu-8796.101.5~3/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

3.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by Dieken** [comment] 2023-06-30 09:11
[bot-demo.tar.gz](https://github.com/quarkusio/quarkus/files/11914850/bot-demo.tar.gz)

Upload minimal project,  commands to recur:

```
./mvnw compile quarkus:dev

curl -H 'Content-Type: application/json' localhost:8080/bot --data-binary '{"id": "bot-aaa", "config": {}}'

curl localhost:8080/bot -v
# HTTP 1.1 409 Conflict

curl localhost:8080/bot/all2 -v
# HTTP/1.1 500 Internal Server Error
```

**Comment by geoand** [comment] 2023-06-30 11:06
cc @Sgitario

**Comment by Sgitario** [comment] 2023-06-30 11:06
I don't think the two issues you mentioned are related to the PanacheEntityResource interface, but to the Hibernate Reactive:

- About the endpoint `curl localhost:8080/bot/all2`, the problem is that the `WithSession` annotation is ignored when it's annotated to methods in an interface. If you move this method to a class resource, it will work. Another approach is to directly use the Mutiny session as follows:

```java
public interface BotResource extends PanacheEntityResource<BotEntity, String> {

    @GET
    @Path("/all2")
    @Produces("application/json")
    default Uni<List<BotEntity>> all2() {
        Mutiny.SessionFactory sessionFactory = CDI.current().select(Mutiny.SessionFactory.class).get();
        return sessionFactory.withSession(s -> s.find(BotEntity.class));
    }
}
```

Is there any limitation about why this interface does not work in methods part of an interface? Maybe @mkouba can help here.

- About the another issue, this seems to be related to lack of support of `@JdbcTypeCode(SqlTypes.JSON)`. 

It's definetively odd that you can create a new entity, and it fails when getting the list of entities. 

@DavideD @Sanne can you give some light about the `@JdbcTypeCode(SqlTypes.JSON)` usage here? Does it supported? Is it correctly configured?

**Comment by DavideD** [comment] 2023-06-30 11:43
I'm haivng a look

**Comment by DavideD** [comment] 2023-06-30 13:57
I need to update the documentation, but I've explained how to map a JSon in [this answer on StackOverflow](https://stackoverflow.com/questions/73471277/using-the-postgresql-jsonb-type-with-hibernate-reactive)

**Comment by geoand** [comment] 2023-06-30 13:58
Thanks @DavideD!

Should we close this issue then?

**Comment by DavideD** [comment] 2023-06-30 13:59
> I totally agree that the docs should mention this

There's an issue open: https://github.com/hibernate/hibernate-reactive/issues/1606

I suppose we can close this.

**Comment by Dieken** [comment] 2023-06-30 15:33
@Sgitario Just find Quarkus document doesn't use @WithSession, I guess it's caused by `Uni<List<Person>>`, so I created hibernate-reactive-rest-data-panache-quickstart: https://github.com/quarkusio/quarkus-quickstarts/pull/1294

The quickstart does recur this second problem above.

https://quarkus.io/guides/rest-data-panache#adding-additional-methods-to-the-generated-resource

```java
@ResourceProperties
public interface PeopleResource extends PanacheEntityResource<Person, Long> {
    @GET
    @Path("/name/{name}")
    @Produces("application/json")
    default List<Person> findByName(@PathParam("name") String name) {
        return Person.find("name = :name", Collections.singletonMap("name", name)).list();
    }
}
```

**Comment by Dieken** [comment] 2023-06-30 15:45
@DavideD  

The first problem is resolved, I suggest fourth option shown above, use `JsonObject` and user defined class.

The second problem isn't fully resolved yet,  the hibernate-reactive version should just work without explicit call the `CDI`class, so I suggest reopening this issue.

**Comment by DavideD** [comment] 2023-07-02 08:05
@Dieken, Ok, I will have another look

**Comment by DavideD** [comment] 2023-07-03 09:22
@mkouba, @FroMage, any idea why `@WithSession` doesn't work in this case?

**Comment by mkouba** [comment] 2023-07-03 10:10
> @mkouba, @FroMage, any idea why `@WithSession` doesn't work in this case?

I'll take a look...

**Comment by mkouba** [comment] 2023-07-03 10:52
> Is there any limitation about why this annotation does not work in methods part of an interface? Maybe @mkouba can help here.

Ok, so `@WithSession` does not work with interface because it's an interceptor binding and bindings declared on interfaces are ignored per the CDI/Interceptors spec.

> Another approach is to directly use the Mutiny session as follows: ...
> ```
> public interface BotResource extends PanacheEntityResource<BotEntity, String> {
>
>    @GET
>    @Path("/all2")
>    @Produces("application/json")
>    default Uni<List<BotEntity>> all2() {
>        Mutiny.SessionFactory sessionFactory = CDI.current().select(Mutiny.SessionFactory.class).get();
>        return sessionFactory.withSession(s -> s.find(BotEntity.class));
>    }
> }
> ```

The CDI lookup of `Mutiny.SessionFactory` is not necessary. `Panache#withSession()`/`Panache#withTransaction()` should also work.

I think that it might be reasonable to modify `hibernate-reactive-rest-data-panache` and annotate the gerenated resource class with `@io.quarkus.hibernate.reactive.panache.common.WithSessionOnDemand`. We do the same for existing JAX-RS resources in `PanacheJpaCommonResourceProcessor#transformResourceMethods()`.

However, it should be also possible to make a generated resource method transactional because `@WithTransactional` will not work either.

**Comment by geoand** [comment] 2023-07-03 10:59
cc @Sgitario ^

**Comment by Sgitario** [comment] 2023-07-03 13:56
> > Is there any limitation about why this annotation does not work in methods part of an interface? Maybe @mkouba can help here.
> 
> Ok, so `@WithSession` does not work with interface because it's an interceptor binding and bindings declared on interfaces are ignored per the CDI/Interceptors spec.
> 
> > Another approach is to directly use the Mutiny session as follows: ...
> > ```
> > public interface BotResource extends PanacheEntityResource<BotEntity, String> {
> > 
> >    @GET
> >    @Path("/all2")
> >    @Produces("application/json")
> >    default Uni<List<BotEntity>> all2() {
> >        Mutiny.SessionFactory sessionFactory = CDI.current().select(Mutiny.SessionFactory.class).get();
> >        return sessionFactory.withSession(s -> s.find(BotEntity.class));
> >    }
> > }
> > ```
> 
> The CDI lookup of `Mutiny.SessionFactory` is not necessary. `Panache#withSession()`/`Panache#withTransaction()` should also work.
> 
> I think that it might be reasonable to modify `hibernate-reactive-rest-data-panache` and annotate the gerenated resource class with `@io.quarkus.hibernate.reactive.panache.common.WithSessionOnDemand`. We do the same for existing JAX-RS resources in `PanacheJpaCommonResourceProcessor#transformResourceMethods()`.
> 
> However, it should be also possible to make a generated resource method transactional because `@WithTransactional` will not work either.

Do you mean that by adding the '@WithSessionOnDemand' annotation to the generated class would make the '@WithSession' annotation to work in the methods of the interface? Or to replace the '@WithSession' annotation with '@WithSessionOnDemand'? 

By the way, I didn't check the '@WithTransaction' annotation?  Does it work or do we need to do something similar here?

**Comment by Sgitario** [comment] 2023-07-03 14:23
> > Do you mean that by adding the '@WithSessionOnDemand' annotation to the generated class would make the '@WithSession' annotation to work in the methods of the interface? Or to replace the '@WithSession' annotation with '@WithSessionOnDemand'?
> 
> No, it would not make the `@WithSession` annotation work but it would lazily create a new `Mutiny.Session` if needed for every method that returns `Uni`.
> 

Ok, will take a look on Wednesday. Thanks @mkouba

**Comment by Sgitario** [comment] 2023-07-05 08:02
Title updated to better describe what is the actual problem to address.

**Comment by Sgitario** [comment] 2023-07-05 09:45
https://github.com/quarkusio/quarkus/pull/34542 should fix this issue. The `@WithSessionOnDemand` fixes the issue, tho @mkouba please take a quickly look into this just in case you spot something else to improve/amend/cover.

**Closed** 2023-07-07 10:57 UTC
Labels: kind/question, area/panache
