### ISSUE TITLE
ConcurrentModificationException on ArcContainerImpl.getMatchingBeans

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#10135] opened 2020-06-20 21:48 UTC
**Describe the bug**

I'm unable to reproduce it consistently but with the latest master of camel-quarkus that spawn a thread to start camel-main (to support quarkus command mode)  I see:

```
2020-06-20T21:28:34.4957214Z [INFO] Running org.apache.camel.quarkus.main.deployment.CamelMainInjectTest
2020-06-20T21:28:34.4964703Z 	at java.lang.Thread.run(Thread.java:748)
2020-06-20T21:28:34.4965063Z Caused by: java.util.ConcurrentModificationException
2020-06-20T21:28:34.4965337Z 	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
2020-06-20T21:28:34.4965642Z 	at java.util.ArrayList$Itr.next(ArrayList.java:859)
2020-06-20T21:28:34.4966677Z 	at io.quarkus.arc.impl.ArcContainerImpl.getMatchingBeans(ArcContainerImpl.java:551)
2020-06-20T21:28:34.4968557Z 	at io.quarkus.arc.impl.ArcContainerImpl.getBeans(ArcContainerImpl.java:413)
2020-06-20T21:28:34.4970365Z 	at io.quarkus.arc.impl.BeanManagerImpl.getBeans(BeanManagerImpl.java:99)
2020-06-20T21:28:34.4973882Z 	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferencesByTypeWithName(RuntimeBeanRepository.java:66)
2020-06-20T21:28:34.4975319Z 	at org.apache.camel.quarkus.core.RuntimeBeanRepository.lambda$getReferencesByTypeWithName$0(RuntimeBeanRepository.java:37)
2020-06-20T21:28:34.4996415Z 	at java.util.Optional.map(Optional.java:215)
2020-06-20T21:28:34.4998415Z 	at org.apache.camel.quarkus.core.RuntimeBeanRepository.getReferencesByTypeWithName(RuntimeBeanRepository.java:37)
2020-06-20T21:28:34.5000625Z 	at org.apache.camel.quarkus.core.RuntimeBeanRepository.findByTypeWithName(RuntimeBeanRepository.java:99)
2020-06-20T21:28:34.5002529Z 	at org.apache.camel.support.DefaultRegistry.findByTypeWithName(DefaultRegistry.java:182)
2020-06-20T21:28:34.5004852Z 	at org.apache.camel.main.DefaultConfigurationConfigurer.getSingleBeanOfType(DefaultConfigurationConfigurer.java:398)
2020-06-20T21:28:34.5007111Z 	at org.apache.camel.main.DefaultConfigurationConfigurer.afterConfigure(DefaultConfigurationConfigurer.java:257)
2020-06-20T21:28:34.5009296Z 	at org.apache.camel.main.BaseMainSupport.doConfigureCamelContextFromMainConfiguration(BaseMainSupport.java:669)
2020-06-20T21:28:34.5011080Z 	at org.apache.camel.main.BaseMainSupport.autoconfigure(BaseMainSupport.java:511)
2020-06-20T21:28:34.5013052Z 	at org.apache.camel.main.BaseMainSupport.postProcessCamelContext(BaseMainSupport.java:574)
2020-06-20T21:28:34.5015155Z 	at org.apache.camel.quarkus.main.CamelMain.initCamelContext(CamelMain.java:86)
2020-06-20T21:28:34.5017375Z 	at org.apache.camel.quarkus.main.CamelMain.doInit(CamelMain.java:57)
2020-06-20T21:28:34.5018184Z 	at org.apache.camel.support.service.BaseService.init(BaseService.java:83)
2020-06-20T21:28:34.5080225Z 	at org.apache.camel.support.service.BaseService.start(BaseService.java:111)
2020-06-20T21:28:34.5082479Z 	at org.apache.camel.main.MainSupport.run(MainSupport.java:60)
2020-06-20T21:28:34.5084555Z 	at org.apache.camel.main.MainCommandLineSupport.run(MainCommandLineSupport.java:150)
2020-06-20T21:28:34.5086896Z 	at org.apache.camel.quarkus.main.CamelMainRuntime.lambda$start$0(CamelMainRuntime.java:46)
```

**Environment (please complete the following information):**
 - Output of `java -version`: 
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.7+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.7+10, mixed mode)
```
 - Quarkus version or git rev: 
```
1.5.1
```
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/data/sfw/tools/sdkman/candidates/maven/current
Java version: 11.0.7, vendor: AdoptOpenJDK, runtime: /opt/data/sfw/tools/sdkman/candidates/java/11.0.7.hs-adpt
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.6.18-300.fc32.x86_64", arch: "amd64", family: "unix"
```

**Additional context**

Camel uses the BeanManager behind the scenes to lookup beans.

**Comment by geoand** [comment] 2020-06-22 07:27
cc @mkouba

**Comment by mkouba** [comment] 2020-06-23 07:39
Hm, this should never happen because the list of beans is only modified when the `ArcContainerImpl` is constructed (bootstrap). I can see that you're using the `BeanManager` to obtain the set of beans. @lburgazzoli  How do you obtain the `BeanManager` instance and when?

**Comment by lburgazzoli** [comment] 2020-06-23 08:16
[This](https://github.com/apache/camel-quarkus/blob/master/extensions-core/core/runtime/src/main/java/org/apache/camel/quarkus/core/RuntimeBeanRepository.java#L76-L83) is the current implementation, before it was as simple as 

    Arc.container().beanManager()

That `RuntimeBeanRepository` is used by camel to look up beans from the container in which it runs. Note that I've noticed this problem only when running unit tests, like [those](https://github.com/apache/camel-quarkus/tree/master/extensions-core/main/deployment/src/test/java/org/apache/camel/quarkus/main/deployment) ones.

**Comment by mkouba** [comment] 2020-06-23 08:42
It's very likely that you try obtain the `BeanManager` from a reference to a container that is being currently shut down.

**Comment by lburgazzoli** [comment] 2020-06-23 08:51
yes that's possible however I've no control about that, looking at the stack trace, camel is in its initialization phase so there should be something wrong either in how I did set-up the tests or how the unit tests are executed

**Comment by mkouba** [comment] 2020-07-02 13:26
I wasn't able to reproduce the problem with the current `quarskus-camel` master branch. I'm going to close the issue now but feel free to reopen it if you hit the problem again.

**Closed by mkouba** 2020-07-02 13:26 UTC
Labels: area/arc, kind/bug
