### ISSUE TITLE
MaxIdleTimeout can not be set on the websocket session

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#15671] opened 2021-03-12 13:11 UTC
**Describe the bug**
I like to set the max idle timeout for the websocket connection. Setting this value on the session has no effect as the methods are only stubs on the UndertowSession.

```   
   @Override
    public long getMaxIdleTimeout() {
        //return webSocketChannel.getIdleTimeout();
        return -1;
    }

    @Override
    public void setMaxIdleTimeout(final long milliseconds) {
        //webSocketChannel.setIdleTimeout(milliseconds);
    }
```

**Expected behavior**
Value can be set and the connection gets closed after the idle time when no traffic occures.

As I don't need different idle-timeouts per sessions, it would also be possible to set the default value somehow. Bu I didn't find any documentation on how to do it. 

**Actual behavior**
Nothing happen, the session stays open forever.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.12.1.FINAL

**Comment by elbcoast** [comment] 2021-10-03 18:09
Running into the same problem on Quarkus 2.2.3.Final. Looks like it was removed from quarkus-http 3 years ago. Unfortunately I haven't found a way to set the idle timeout so far.

**Comment by geoand** [comment] 2024-09-13 11:32
@mkouba is this one that has been addressed by Websockets Next?

**Comment by mkouba** [comment] 2024-09-13 11:52
Well, I have no idea what API is actually used here? @joggeli34 could you be more specific? Ideally, pls provide a simple reproducer app.

**Comment by joggeli34** [comment] 2024-09-17 13:36
Well, this is from the old websocket 3 years ago. We are not using this anymore the same way. So I don't know the current state. Feel free to close the issue.

**Comment by mkouba** [comment] 2024-09-17 13:39
> Well, this is from the old websocket 3 years ago. We are not using this anymore the same way. So I don't know the current state. Feel free to close the issue.

:+1: Thanks for your feedback!

**Closed by mkouba** 2024-09-17 13:39 UTC
Labels: kind/bug, area/undertow
