### ISSUE TITLE
Graalvm native Compile Error

### ISSUE THREAD

**Issue by aomsweet** [quarkusio/quarkus#21726] opened 2021-11-26 08:34 UTC
### Describe the bug

Graalvm native compile error after upgrading to `2.5.0.Final`, `2.4.1.Final` is ok.

```log
[qunar-wh-policy-sync-bin:1603]    classlist:   2,945.80 ms,  0.96 GB
[qunar-wh-policy-sync-bin:1603]        (cap):   1,630.65 ms,  0.96 GB
[qunar-wh-policy-sync-bin:1603]        setup:   3,156.07 ms,  0.96 GB
16:09:03,286 INFO  [org.jbo.threads] JBoss Threads version 3.4.2.Final
[qunar-wh-policy-sync-bin:1603]     (clinit):   1,317.19 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]   (typeflow):   8,025.14 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]    (objects):  36,579.45 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]   (features):  15,439.03 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]     analysis:  64,534.34 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]     universe:   3,537.22 ms,  5.88 GB
[qunar-wh-policy-sync-bin:1603]      (parse):  12,050.41 ms,  5.56 GB
[qunar-wh-policy-sync-bin:1603]     (inline):  20,814.87 ms,  6.39 GB
[qunar-wh-policy-sync-bin:1603]    (compile):  44,066.67 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]      compile:  81,027.26 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]        image:   5,066.49 ms,  6.33 GB
[qunar-wh-policy-sync-bin:1603]        write:   1,223.43 ms,  6.33 GB
Fatal error:java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libfreetype.a is missing. Please install it.

Linker command executed:
/usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-16506476398039308040/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /mnt/d/IdeaProjects/zlzl/ota-q
unar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin qunar-wh-policy-sync-bin.o /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/
static/linux-amd64/glibc/libnet.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd6
4/glibc/libextnet.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libnio.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/liblibche
lper.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjava.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/liblcms.a /mnt/d/Java/g
raalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfontmanager.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /mnt/d/Java/graalv
m-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /mnt/d/Java/graalvm-ce-java17-linux-2
1.3.0/lib/static/linux-amd64/glibc/libzip.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-16506476398039308040 -L/mnt/d/Java/graalvm-
ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc -L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64 -lstdc++ -lm -lfreetype -lpthread -ldl -lz -lrt -no-pie

Linker command output:
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.3.0-17ubuntu1~20.04' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortr
an,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --
without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=ne
w --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-objc-gc=auto --enable-multiarch --d
isable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none=/build/gcc-9-HskZEa/gcc-9-9
.3.0/debian/tmp-nvptx/usr,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04)
COMPILER_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/
LIBRARY_PATH=/usr/lib/gcc/x86_64-linux-gnu/9/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../../lib/:/lib/x86_64-linux-gnu/:/lib/..
/lib/:/usr/lib/x86_64-linux-gnu/:/usr/lib/../lib/:/usr/lib/gcc/x86_64-linux-gnu/9/../../../:/lib/:/usr/lib/
COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin
' '-v' '-L/tmp/SVM-16506476398039308040' '-L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc' '-L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/li
nux-amd64' '-no-pie' '-mtune=generic' '-march=x86-64'
 /usr/lib/gcc/x86_64-linux-gnu/9/collect2 -plugin /usr/lib/gcc/x86_64-linux-gnu/9/liblto_plugin.so -plugin-opt=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper -plugin-opt=-fresolution=/tmp
/cc5yzrm1.res -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s -plugin-opt=-pass-through=-lc -plugin-opt=-pass-through=-lgcc -plugin-opt=-pass-through=-lgcc_s --build-
id --eh-frame-hdr -m elf_x86_64 --hash-style=gnu --as-needed -dynamic-linker /lib64/ld-linux-x86-64.so.2 -z relro -o /mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/targ
et/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin -z noexecstack /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crt1.o /usr/lib/gcc/x86_64-linux-gnu/9
/../../../x86_64-linux-gnu/crti.o /usr/lib/gcc/x86_64-linux-gnu/9/crtbegin.o -L/tmp/SVM-16506476398039308040 -L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc -
L/mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-linux-gnu/9 -L/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu -L/usr/lib/gcc/
x86_64-linux-gnu/9/../../../../lib -L/lib/x86_64-linux-gnu -L/lib/../lib -L/usr/lib/x86_64-linux-gnu -L/usr/lib/../lib -L/usr/lib/gcc/x86_64-linux-gnu/9/../../.. --gc-sections --dynami
c-list /tmp/SVM-16506476398039308040/exported_symbols.list --exclude-libs ALL -x qunar-wh-policy-sync-bin.o /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libn
et.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libextnet.a /mnt/d/Ja
va/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libnio.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /mnt/d/Java/graalvm-ce
-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libjava.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/liblcms.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0
/lib/static/linux-amd64/glibc/libfontmanager.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/
static/linux-amd64/glibc/libawt.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/static/linux-amd64/
glibc/libzip.a /mnt/d/Java/graalvm-ce-java17-linux-21.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lm -lfreetype -lpthread -ldl -lz -lrt -lgcc --push-state --as-needed -lgcc_s
 --pop-state -lc -lgcc --push-state --as-needed -lgcc_s --pop-state /usr/lib/gcc/x86_64-linux-gnu/9/crtend.o /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/crtn.o
/usr/bin/ld: cannot find -lfreetype
collect2: error: ld returned 1 exit status
        at com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:502)
        at com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:449)
        at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:657)
        at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:488)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:569)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:122)
        at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:599)
[qunar-wh-policy-sync-bin:1603]      [total]: 162,020.49 ms,  6.33 GB
# Printing build artifacts to: /mnt/d/IdeaProjects/zlzl/ota-qunar-policy/qunar-wh-policy-sync/target/qunar-wh-policy-sync-native-image-source-jar/qunar-wh-policy-sync-bin.build_artifac
ts.txt
Error: Image build request failed with exit status 1
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for ota-qunar-policy 1.1-SNAPSHOT:
[INFO]
[INFO] ota-qunar-policy ................................... SUCCESS [  0.144 s]
[INFO] qunar-international-policy ......................... SUCCESS [  7.276 s]
[INFO] qunar-internal-policy .............................. SUCCESS [  4.234 s]
[INFO] qunar-wh-policy-sync ............................... FAILURE [03:02 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  03:16 min
[INFO] Finished at: 2021-11-26T16:11:24+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.5.0.Final:build (default) on project qunar-wh-policy-sync: Failed to build quarkus application: io.quarkus.builder.Buil
dException: Build failure: Build failed due to errors
[ERROR]         [error]: Build step io.quarkus.deployment.pkg.steps.NativeImageBuildStep#build threw an exception: java.lang.RuntimeException: Failed to build native image
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:233)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[ERROR]         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
[ERROR]         at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR]         at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR]         at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR]         at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR]         at java.base/java.lang.Thread.run(Thread.java:833)
[ERROR]         at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] Caused by: java.lang.RuntimeException: Image generation failed. Exit code: 1
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.imageGenerationFailed(NativeImageBuildStep.java:369)
[ERROR]         at io.quarkus.deployment.pkg.steps.NativeImageBuildStep.build(NativeImageBuildStep.java:213)
[ERROR]         ... 11 more
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
```

### 

### Output of `uname -a` or `ver`

Ubuntu 20.04 64bit

### Output of `java -version`

17

### GraalVM version (if different from Java)

21.3.0

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3

**Comment by geoand** [comment] 2021-11-26 11:34
cc @zakkak @galderz

**Comment by zakkak** [comment] 2021-11-26 12:06
@aomsweet I guess you are using a locally installed GraalVM and not the `ubi-quarkus-native-image`. Is that right?

If so please install `freetype-devel` (on RHEL/CentOS/Fedora) or `libfreetype6-dev` (on Ubuntu/Debian) on your system.

**Comment by aomsweet** [comment] 2021-11-26 12:15
@zakkak Hi, 
I downloaded the Graalvm SDK from https://github.com/graalvm/graalvm-ce-builds. It used to be this way, what should I do now? Thanks!

**Comment by aomsweet** [comment] 2021-11-26 12:15
It is ok after installing `libfreetype6-dev`. But the compiled file size has increased from 68M to 78M.

**Comment by zakkak** [comment] 2021-11-26 12:25
It looks like in 2.5.0.Final the application started pulling in AWT dependencies while it did not in 2.4.1.Final which seems strange to me especially given that https://github.com/quarkusio/quarkus/pull/20867 should have the opposite effect.

@galderz can you please have a look?

**Comment by joggeli34** [comment] 2021-11-26 13:19
Probably related to https://github.com/quarkusio/quarkus/issues/21729, where the awt-dependency got included by liquibase which uses jaxb.

**Comment by galderz** [comment] 2021-11-26 16:21
@aomsweet What quarkus extensions are you using? Are you using liquibase as @joggeli34 suggested? Do you have a reproducer you can share?

IIRC, a PR that @Karm was working on had similar freetype errors (see https://github.com/quarkusio/quarkus/pull/20850#issuecomment-968895175). He's also working to improve things for that PR, which might indirectly fix things here.

**Comment by Karm** [comment] 2021-11-26 17:22
Hello @joggeli34,

I am working on https://github.com/quarkusio/quarkus/pull/20850 (at the moment) that would, among other things, help with this issue. ETA: Soon :-) 

The behaviour when I am done will be this: 
- no AWT dependency and issues with libs you might not need
- if and only if your application hits the graphics libraries at runtime, an error is shown telling you that you have to depend on AWT extension and that you might have to install additional libraries.  

An example to illustrate what I mean:
You might have a POJO with `Image` and `String` attributes. As long as you are POSTing its XML representation containing just the `String` attribute, the `Image` attribute is null and all is well. As soon as you POST also some `Image` data to deserialize, JAXB logs ERROR, asking you to install AWT extension.


To quickly check on what to install in the meantime, take a look at https://github.com/quarkusio/quarkus-quickstarts/tree/development/awt-graphics-rest-quickstart#additional-system-dependencies

**Comment by aomsweet** [comment] 2021-11-29 01:31
Hi, @galderz @Karm 

This is my dependencies, if you need a replicator, I can provide it.

```xml
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-arc</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-redis-client</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jaxb</artifactId>
        </dependency>
        <dependency>
            <groupId>com.github.ben-manes.caffeine</groupId>
            <artifactId>caffeine</artifactId>
        </dependency>
```

**Comment by galderz** [comment] 2021-11-29 11:08
Thx @aomsweet, the dependency that triggers this is the `jaxb` dependency.

**Comment by Karm** [comment] 2021-11-29 16:47
@aomsweet ...and as soon as  #20850 is merged, the AWT dependency won't be pulled in by `jaxb` any longer.

**Comment by aomsweet** [comment] 2021-11-30 01:32
@galderz @Karm Thank you very much.

**Closed** 2021-12-07 10:24 UTC
Labels: kind/bug, area/native-image

**Comment by zipper01** [comment] 2023-01-06 13:07
`Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1

Based on the linker command output, possible reasons for this include:
1. It appears as though libfreetype.a is missing. Please install it.`

yum -y install freetype: "Package freetype-2.8-14.el7_9.1.x86_64 already installed and latest version" 

 Version info: 'GraalVM 22.3.0 Java 17 CE'
 Java version info: '17.0.5+8-jvmci-22.3-b08'
 C compiler: gcc (redhat, x86_64, 4.8.5)

**Comment by Karm** [comment] 2023-01-06 13:38
@zipper01 The linker would like to have a static library version `.a` of `libfreetype.a`. You apparently have just the dynamically linkable shared object `.so` one. 

We compile and test on CentOS 8+ like systems. Not sure about CentOS 7.

You should try installing `freetype-devel`.

**Comment by zipper01** [comment] 2023-01-06 14:04
@Karm Thank you for the quick response, installing `freetype-devel` eliminated the error. But I got another one (final link failed: Bad value):

    Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
    
    Linker command executed:
    /usr/bin/gcc -z noexecstack -Wl,--gc-sections -Wl,--dynamic-list -Wl,/tmp/SVM-4506019668164172958/exported_symbols.list -Wl,--exclude-libs,ALL -Wl,-x -o /root/downloads/myapp myapp.o /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libnet.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libextnet.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libnio.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libmanagement_ext.a /usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libjava.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/liblcms.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libprefs.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libfontmanager.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libawt.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libzip.a /usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -v -L/tmp/SVM-4506019668164172958 -L/usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc -L/usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64 -lstdc++ -lm -lfreetype -lz -lpthread -ldl -lrt
    
    Linker command output:
    Using built-in specs.
    COLLECT_GCC=/usr/bin/gcc
    COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
    Target: x86_64-redhat-linux
    Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
    Thread model: posix
    gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC)
    COMPILER_PATH=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/:/usr/libexec/gcc/x86_64-redhat-linux/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/
    LIBRARY_PATH=/usr/lib/gcc/x86_64-redhat-linux/4.8.5/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/:/lib/../lib64/:/usr/lib/../lib64/:/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../:/lib/:/usr/lib/
    COLLECT_GCC_OPTIONS='-z' 'noexecstack' '-o' '/root/downloads/myapp' '-v' '-L/tmp/SVM-4506019668164172958' '-L/usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc' '-L/usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64' '-mtune=generic' '-march=x86-64'
     /usr/libexec/gcc/x86_64-redhat-linux/4.8.5/collect2 --build-id --no-add-needed --eh-frame-hdr --hash-style=gnu -m elf_x86_64 -dynamic-linker /lib64/ld-linux-x86-64.so.2 -o /root/downloads/myapp -z noexecstack /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crt1.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crti.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtbegin.o -L/tmp/SVM-4506019668164172958 -L/usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc -L/usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64 -L/lib/../lib64 -L/usr/lib/../lib64 -L/usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../.. --gc-sections --dynamic-list /tmp/SVM-4506019668164172958/exported_symbols.list --exclude-libs ALL -x myapp.o /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libnet.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libjavajpeg.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libextnet.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libnio.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libmanagement_ext.a /usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libjava.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/liblcms.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libprefs.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libfontmanager.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libawt_headless.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libawt.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libfdlibm.a /usr/local/graalvm-ce-java17-22.3.0/lib/static/linux-amd64/glibc/libzip.a /usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/libjvm.a -lstdc++ -lm -lfreetype -lz -lpthread -ldl -lrt -lgcc --as-needed -lgcc_s --no-as-needed -lc -lgcc --as-needed -lgcc_s --no-as-needed /usr/lib/gcc/x86_64-redhat-linux/4.8.5/crtend.o /usr/lib/gcc/x86_64-redhat-linux/4.8.5/../../../../lib64/crtn.o
    /usr/bin/ld: /usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a(cpuid.o): unrecognized relocation (0x2a) in section `.text.checkCPUFeaturesOrExit'
    /usr/bin/ld: final link failed: Bad value
    collect2: error: ld returned 1 exit status
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.handleLinkerFailure(NativeImageViaCC.java:204)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.runLinkerCommand(NativeImageViaCC.java:151)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.image.NativeImageViaCC.write(NativeImageViaCC.java:117)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:718)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:535)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:403)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:580)
       at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)

I was actually building this in a 4C/8G CentOS8 instance. But the tool asked for more memory, so I am trying on an old local instance of CentOS7 with 20G mem on top of VirtualBox.

**Comment by Karm** [comment] 2023-01-06 14:36
@zipper01 You are welcome. [Zulip](https://quarkusio.zulipchat.com/#) chat might be a batter place for such an exchange though as this is not a Quarkus bug...

```
/usr/local/graalvm-ce-java17-22.3.0/lib/svm/clibraries/linux-amd64/liblibchelper.a(cpuid.o): 
unrecognized relocation (0x2a) in section `.text.checkCPUFeaturesOrExit'
```

Interesting. I don't recall seeing it. I suspect your GCC might be too old. It says 4.8.5.
We are using GCC 8.5.0. That is a huge gap.

Why are you using CentOS 7? Can you spin up something newer?

**Comment by zipper01** [comment] 2023-01-06 14:53
@Karm I just ordered an on-demand CentOS Linux release 8.2.2004 (Core) and now trying on it.

But I got a new error: 
    Fatal error: java.lang.RuntimeException: There was an error linking the native image: Linker command exited with 1
    
    Based on the linker command output, possible reasons for this include:
    1. It appears as though libstdc++.a is missing. Please install it.

and `/usr/bin/ld: cannot find -lstdc++`. Still trying to solve this.

    [root@ecs-45ee downloads]# dnf install libstdc++
    Last metadata expiration check: 0:13:46 ago on Fri 06 Jan 2023 10:27:48 PM CST.
    Package libstdc++-8.5.0-4.el8_5.x86_64 is already installed.
    Dependencies resolved.
    Nothing to do.

**Comment by Karm** [comment] 2023-01-06 15:15
@zipper01 See https://github.com/graalvm/mandrel#prerequisites

**Comment by zipper01** [comment] 2023-01-06 16:07
@Karm It finally worked after `dnf install gcc-c++ libstdc++-devel`, thank you very much for the help!

**Comment by Karm** [comment] 2023-01-06 18:52
@zipper01 ☺️👍
