### ISSUE TITLE
@RouteFilter stopped working with WebSocket requests Quarkus 3.2.0.Final

### ISSUE THREAD

**Issue by AlekseyMay** [quarkusio/quarkus#34908] opened 2023-07-21 08:27 UTC
### Describe the bug

We were migrating from 2.16.7 to 3.2.0.Final

And we have WebSocket interceptor implemented with @RouteFilter

It looks like this:

```java
@RouteFilter
 void authFilter(RoutingContext rc) {
    /// logic to search for websocket header etc
}
```
We use it to intercept GQL Subscriptions and its initial websocket request.
After migration to 3.2.0.Final it stopped intercepting WebSocket for some reason.

### Expected behavior

Intercept all requests as it was in 2.16.7

### Actual behavior

Not intercepting websocket initial request

### Output of `java -version`

17

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.1.1

**Comment by geoand** [comment] 2023-07-21 09:11
cc @mkouba

**Comment by mkouba** [comment] 2023-08-01 07:51
> We use it to intercept GQL Subscriptions and its initial websocket request.
> After migration to 3.2.0.Final it stopped intercepting WebSocket for some reason.

I'm not aware of any change in the  implementation of `@RouteFilter`.

Maybe it's related to some change in the `smallrye-graphql`?

CC @phillip-kruger @jmartisk

**Comment by uPagge** [comment] 2023-08-03 08:15
Hello everyone. I have the same problem :(

**Comment by mkouba** [comment] 2023-08-03 09:15
Hm, the `SmallRyeGraphQLOverWebSocketHandler` which handles the HTTP UPGRADE header is registered with priority `Integer.MIN_VALUE` and does not call the next route so I would say that the filter route should not be called. But the same priority is used in 2.16 :shrug:.

**Comment by phillip-kruger** [comment] 2023-08-03 09:21
Is it not working in any v3.x ? Or just 3.2.0 ? Because then it might be Dev UI ? Also check Dev Mode vs Prod mode ? That should rule out (or in) Dev UI

**Comment by phillip-kruger** [comment] 2023-08-03 11:30
@AlekseyMay can you test in non dev mode ? So build the jar and run with java -jar ?

**Comment by phillip-kruger** [comment] 2023-08-03 12:14
Thanks ! That kind of rule out Dev UI. @jmartisk @mkouba are you going to look at this ? I can't look at this right away.

**Comment by mkouba** [comment] 2023-08-03 12:33
> I've recorded small video showing the problem using the Reproducer that is attached, maybe it can help to understand the problem.

I do understand the problem and I'm able to reproduce it. But I'm still not convinced it should work. Like I mentioned in https://github.com/quarkusio/quarkus/issues/34908#issuecomment-1663602183.

> Thanks ! That kind of rule out Dev UI. @jmartisk @mkouba are you going to look at this ? I can't look at this right away.

I'm trying to debug the reproducer. With 2.16 the `com.example.Interceptor.filter(RoutingContext)` is executed before `SmallRyeGraphQLOverWebSocketHandler` even though it has `order=-10` and `SmallRyeGraphQLOverWebSocketHandler` has `order=-2147483648`. Maybe the behavior changed between Vert.x 4.2.2 and 4.4.4? IIUIC it was fixed.

**Comment by mkouba** [comment] 2023-08-03 13:17
Ok, I found it. It worked by coincidence because `HttpRootPathBuildItem.Builder.orderedRoute()` was never used before quarkus 3.0, i.e. the value `-1` was always used and therefore the `com.example.Interceptor#filter()` which has the default priority for filters: `-10`, was executed before the `SmallRyeGraphQLOverWebSocketHandler`. We fixed this bug in https://github.com/quarkusio/quarkus/pull/32008. So now the ordering is correct but since the `SmallRyeGraphQLOverWebSocketHandler` is registered with `order=-2147483648` it's always executed before the `Interceptor#filter()`.

@phillip-kruger I believe that `SmallRyeGraphQLOverWebSocketHandler` should use a different value so that it's possible to register a filter that can be executed before this handler. WDYT?

**Comment by phillip-kruger** [comment] 2023-08-03 13:21
Nice ! Thanks @mkouba . Yes for sure. I recall some internal ranges somewhere.... It's probably on Integer.MAX_VALUE at the moment, we should defiantly change that. @mkouba do you want to do the fix ? Else @jmartisk can add it to our todo list :)

**Comment by mkouba** [comment] 2023-08-03 13:25
> Nice ! Thanks @mkouba . Yes for sure. I recall some internal ranges somewhere.... It's probably on Integer.MAX_VALUE at the moment, we should defiantly change that. @mkouba do you want to do the fix ? Else @jmartisk can add it to our todo list :)

I can send a PR shortly. I'm not aware of any "internal ranges" but using a fixed value such as `-1000` should be enough.

**Comment by mkouba** [comment] 2023-08-03 13:49
@AlekseyMay So once the https://github.com/quarkusio/quarkus/pull/35188 is merged you can use `@RouteFilter(10_001)` (or any value > `10000`).

**Closed** 2023-08-04 07:35 UTC
Labels: kind/bug, area/vertx
