### ISSUE TITLE
Quarkus 3/Hibernate 6 - Exception when access ElementCollection from an Entity with an embedded composite Key with associated Object

### ISSUE THREAD

**Issue by bumbel42so** [quarkusio/quarkus#33779] opened 2023-06-01 15:43 UTC
### Describe the bug

I have an Entity with an EmbeddedId and an ElementCollection: 
```
@Entity()
public class MyEntity {
    @EmbeddedId
    EmbeddableId id;

    public String name;

    @ElementCollection
    public Set<EmbeddableElement> elementCollection = new HashSet<>();
}
```
```
@Embeddable
public class EmbeddableElement {
    public String name;
}
```

The embedded id has an composite key
```
@Embeddable
public class EmbeddableId  {
    public String id1;
    @ManyToOne
    public PartOfIdEntity id2;
}
```
```
@Entity()
public class PartOfIdEntity  {
    @Id
    public Long id;
}
```

### Expected behavior

No Exception when accessing the ElementCollection like in Quarkus 2.*

### Actual behavior

I get an Exception

Now if i access the elementCollection of MyEntity i get following exception: 
```
java.lang.NullPointerException: Cannot invoke "org.hibernate.sql.results.graph.entity.EntityInitializer.getNavigablePath()" because "firstEntityInitializer" is null
        at org.hibernate.sql.results.graph.entity.internal.BatchEntityInsideEmbeddableSelectFetchInitializer.getRootEmbeddablePropertyName(BatchEntityInsideEmbeddableSelectFetchInitializer.java:190)
        at org.hibernate.sql.results.graph.entity.internal.BatchEntityInsideEmbeddableSelectFetchInitializer.<init>(BatchEntityInsideEmbeddableSelectFetchInitializer.java:57)
        at org.hibernate.sql.results.graph.entity.internal.EntitySelectFetchInitializerBuilder.createInitializer(EntitySelectFetchInitializerBuilder.java:58)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.buildEntitySelectFetchInitializer(EntityFetchSelectImpl.java:92)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.lambda$createAssembler$0(EntityFetchSelectImpl.java:70)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.entity.internal.EntityFetchSelectImpl.createAssembler(EntityFetchSelectImpl.java:67)
        at org.hibernate.sql.results.graph.embeddable.AbstractEmbeddableInitializer.initializeAssemblers(AbstractEmbeddableInitializer.java:121)
        at org.hibernate.sql.results.graph.embeddable.AbstractEmbeddableInitializer.<init>(AbstractEmbeddableInitializer.java:107)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableResultInitializer.<init>(EmbeddableResultInitializer.java:22)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableForeignKeyResultImpl.lambda$createResultAssembler$0(EmbeddableForeignKeyResultImpl.java:101)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.embeddable.internal.EmbeddableForeignKeyResultImpl.createResultAssembler(EmbeddableForeignKeyResultImpl.java:98)
        at org.hibernate.sql.results.graph.collection.internal.CollectionDomainResult.lambda$createResultAssembler$0(CollectionDomainResult.java:98)
        at org.hibernate.sql.results.internal.ResultsHelper$1.resolveInitializer(ResultsHelper.java:108)
        at org.hibernate.sql.results.graph.collection.internal.CollectionDomainResult.createResultAssembler(CollectionDomainResult.java:94)
        at org.hibernate.sql.results.jdbc.internal.StandardJdbcValuesMapping.resolveAssemblers(StandardJdbcValuesMapping.java:53)
        at org.hibernate.sql.results.internal.ResultsHelper.createRowReader(ResultsHelper.java:78)
        at org.hibernate.sql.results.internal.ResultsHelper.createRowReader(ResultsHelper.java:64)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.doExecuteQuery(JdbcSelectExecutorStandardImpl.java:341)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.executeQuery(JdbcSelectExecutorStandardImpl.java:168)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.list(JdbcSelectExecutorStandardImpl.java:93)
        at org.hibernate.sql.exec.spi.JdbcSelectExecutor.list(JdbcSelectExecutor.java:31)
        at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:144)
        at org.hibernate.loader.ast.internal.SingleIdLoadPlan.load(SingleIdLoadPlan.java:104)
        at org.hibernate.loader.ast.internal.CollectionLoaderBatchKey.load(CollectionLoaderBatchKey.java:116)
        at org.hibernate.persister.collection.AbstractCollectionPersister.initialize(AbstractCollectionPersister.java:668)
        at org.hibernate.event.internal.DefaultInitializeCollectionEventListener.onInitializeCollection(DefaultInitializeCollectionEventListener.java:75)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.initializeCollection(SessionImpl.java:1697)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$initialize$3(AbstractPersistentCollection.java:617)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615)
        at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:136)
        at org.hibernate.collection.spi.AbstractPersistentCollection.lambda$readSize$0(AbstractPersistentCollection.java:163)
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:265)
        at org.hibernate.collection.spi.AbstractPersistentCollection.readSize(AbstractPersistentCollection.java:148)
        at org.hibernate.collection.spi.PersistentSet.size(PersistentSet.java:151)
        at example.MyEntityTest.test(MyEntityTest.java:47)

```

### How to Reproduce?

1. Persist some data 
```
PartOfIdEntity partOfIdEntity = new PartOfIdEntity();
            partOfIdEntity.id = 1L;
            entityManager.persist(partOfIdEntity);

            MyEntity myEntity = new MyEntity();
            myEntity.id = new EmbeddableId();
            myEntity.id.id1 = "123";
            myEntity.id.id2 = partOfIdEntity;

            EmbeddableElement el = new EmbeddableElement();
            el.name = "abc";
            myEntity.elementCollection.add(el);
            entityManager.persist(myEntity);
```
2. Close the transaction
3. Access the data:
```
 MyEntity entityFromSelect = em.createQuery("SELECT e FROM MyEntity e", MyEntity.class).getSingleResult();
        entityFromSelect.elementCollection.size();

        // Cannot invoke "org.hibernate.sql.results.graph.entity.EntityInitializer.getNavigablePath()" because "firstEntityInitializer" is null:
        assertEquals(1, entityFromSelect.elementCollection.size());
```

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7) OpenJDK 64-Bit Server VM Temurin-17.0.7+7 (build 17.0.7+7, mixed mode, sharing)

### Quarkus version or git rev

3.1

### Additional information

First i assumed it was a hibernate issue, but i can´t reproduce it with pure hibernate:
[hibernate-orm-6.zip](https://github.com/quarkusio/quarkus/files/11632131/hibernate-orm-6.zip)

Only with Quarkus 3.*
[quarkus-hibernate-issue.zip](https://github.com/quarkusio/quarkus/files/11632133/quarkus-hibernate-issue.zip)

**Comment by yrodiere** [comment] 2023-06-02 06:43
Thanks for the report.

@marko-bekhta could you please have a look? This one doesn't look specific to Quarkus at all, but who knows...

**Comment by marko-bekhta** [comment] 2023-06-02 10:46
Opened https://hibernate.atlassian.net/browse/HHH-16740
There were similar problems reported in the past but with no reproducers. So thanks one more time for providing an example. The reason it wasn't reproducible in the plain ORM case was a missing `hibernate.default_batch_fetch_size` property. If this is set to some value that is > 1, the error appears.  It is not set by Hibernate ORM by default, while in Quarkus it is set to 16 unless a different value is provided through [quarkus.hibernate-orm.fetch.batch-size](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.fetch.batch-size)

You may try to set it to -1:
```
quarkus.hibernate-orm.fetch.batch-size=-1
```
Which will disable the batch fetching, or maybe @yrodiere can think of another workaround until the issue is addressed.

**Comment by yrodiere** [comment] 2023-06-02 11:07
Thanks @marko-bekhta! No, I don't see another workaround. I mean, I suppose one could annotate every affected association with `@BatchSize(-1)` or `, but that seems very intrusive.

Let's close this when ORM gets a fix and we upgrade to the relevant ORM version in Quarkus.

**Comment by sithmein** [comment] 2023-06-05 19:01
I'm running into the same issue. The only workaround was to globally set `quarkus.hibernate-orm.fetch.batch-size=-1`. I couldn't figure out where to selectively add  `@BatchSize(size = -1)`.

**Comment by yrodiere** [comment] 2023-06-15 15:10
#34058 will upgrade to Hibernate ORM 6.2.5, which fixes this issue (https://hibernate.atlassian.net/browse/HHH-16740)

**Closed** 2023-06-23 11:20 UTC
Labels: kind/bug, triage/upstream, area/hibernate-orm
