### ISSUE TITLE
How to prevent hibernate from generating a create and drop script

### ISSUE THREAD

**Issue by Gaga-for-coding** [quarkusio/quarkus#34769] opened 2023-07-15 11:57 UTC
### Describe the bug

This is the create script defined by hibernate ORM
<img width="960" alt="Screenshot 2023-07-15 114805" src="https://github.com/quarkusio/quarkus/assets/66761900/7e4d4af9-a1a7-4472-a8e3-656491a522b3">
But this is how I want my db schema to be defined : 
<img width="611" alt="Screenshot 2023-07-15 115120" src="https://github.com/quarkusio/quarkus/assets/66761900/f1af5c6f-1148-4796-b70d-6d003db62d60">
I am using flyway for my migrations, so because of the way hibernate predefined my database schema every single operation that I want to perform returns an error.
Example : when trying to create a category this is the error message I get 
"errorMessage": "could not execute statement [ERROR: null value in column \"name\" of relation \"categories\" violates not-null constraint\n  Detail: Failing row contains (251, null, null, 2023-07-15 11:46:05.214181, 2023-07-15 11:46:05.215182).] [insert into categories (created,description,name,updated,id) values (?,?,?,?,?)]",

### Expected behavior

As expected behavior I think it is supposed to insert the values in the following order [insert into categories (id, name, desription, created, updated) values (?,?,?,?,?)]",

### Actual behavior

[insert into categories (created,description,name,updated,id) values (?,?,?,?,?)]", It tries to insert the values in this order which is different from my schema.

### Quarkus version or git rev

 3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.3 (21122926829f1ead511c958d89bd2f672198ae9f)                          
Maven home: C:\Program Files\Java\apache-maven-3.9.3-bin\apache-maven-3.9.3            
Java version: 17.0.7, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-17
Default locale: en_US, platform encoding: Cp1252                                       
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by Sanne** [comment] 2023-07-15 20:25
You can use flyway to define the schema if that's your preference, but it's your responsibility to ensure that the model and the mapping matches the defined schema.
This is usually done by adapting the mapping annotations on the model; you can then use the Hibernate "validate" schema mode to verify that the actual schema matches your expectations.

I'll close this as it's not a bug; please refer to the Hibernate documentation to learn about the mapping options.

**Closed by Sanne** 2023-07-15 20:25 UTC
Labels: triage/invalid, area/persistence, area/hibernate-orm
