### ISSUE TITLE
REST: Custom ExceptionMapper using a custom entity results in 200 when calling non existent resource

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#8675] opened 2020-04-19 16:49 UTC
**Describe the bug**
Given a custom exception mapper like the following one:
```java
@Provider
public class MyExceptionMapper implements ExceptionMapper<Exception> {

    @Override
    public Response toResponse(Exception exception) {
        return Response.serverError().entity(new FailMsg("testMsg")).build();
    }
}
```
results in reponse code 200 instead of 500 if you call a non existent resource/path.

If the mapper is called for an exception that is thrown by an _existing_ endpoint, the problem does _not_ occur!

**Expected behavior**
Respond with 500, as defined by the mapper. Or 404 in case that is how the mapper is implemented.

**Actual behavior**
Responds with 200.

**To Reproduce**
1. Clone https://github.com/famod/quarkus-issue-8675 (based on https://quarkus.io/guides/rest-json#creating-the-maven-project)
2. Run `mvn clean verify`
3. _One_ test should fail with:
    ```
    [ERROR]   FruitResourceTest.testNonExistingEndpoint:35 1 expectation failed.
    Expected status code <500> but was <200>.
    ```
    The other non-positive test `testFailEndpoint()` should not fail (which is interesting because it _also_ triggers the mapper and therefore also the usage of the custom entity).

**Configuration**
n/a

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
    ```
    MINGW64_NT-10.0-18363 BIGBLUE 3.0.7-338.x86_64 2019-11-21 23:07 UTC x86_64 Msys
    ```
 - Output of `java -version`:
    ```
    openjdk version "11.0.6" 2020-01-14
    OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
    OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)
    ```
 - GraalVM version (if different from Java): n/a
 - Quarkus version or git rev: `1.3.2.Final`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
    ```
    Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
    Maven home: C:\_dev\Maven\latest
    Java version: 11.0.6, vendor: AdoptOpenJDK, runtime: C:\_dev\Java\latest
    Default locale: de_DE, platform encoding: Cp1252
    OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
    ```
**Additional context**
I debugged this and ended up in `org.jboss.resteasy.core.ServerResponseWriter` which is [unable to find a `MessageBodyWriter`](https://github.com/resteasy/Resteasy/blob/4.5.3.Final/resteasy-core/src/main/java/org/jboss/resteasy/core/ServerResponseWriter.java#L117-L126) for the custom entity (here: `FailMsg`).
For some strange reason, the error reporting code (```onWriteComplete.accept(new NoMessageBodyWriterFoundFailure(type, mt));```) does not seem to have an effect because nothing like that reaches the client.

So this might be a RestEasy bug after all...

PS: The problem vanishes if I explicitly set the media type via `javax.ws.rs.core.Response.ResponseBuilder.type(MediaType)`.

**Comment by stuartwdouglas** [comment] 2020-04-20 06:08
This appears to be a RESTEasy problem. Because the entity is set but no response type (as it is a non-existent endpoint there is no @Produces) JAX-RS cannot figure out how to map the response.

As you say you need to explicitly set the media type for the entity to be written correctly, however I this the response code should always be 200 for this case anyway.

**Comment by famod** [comment] 2020-04-20 10:43
> however I this the response code should always be 200 for this case anyway.

Not sure I follow. Why should it be 200?

**Comment by stuartwdouglas** [comment] 2020-04-20 10:50
oops, that was supposed to be 500

**Comment by stuartwdouglas** [comment] 2020-04-20 11:29
This PR should fix it in RESTEasy, but the real problem is that you did not set the content type https://github.com/resteasy/Resteasy/pull/2358

**Comment by stuartwdouglas** [comment] 2020-04-20 11:29
By 'fix' I mean you will get a 500, but your object still won't be written out as RESTEasy does not know what representation to use.

**Comment by stuartwdouglas** [comment] 2020-04-20 11:30
I am going to close this now, as the root cause is the missing content type, and the wrong status code is a RESTEasy problem.

**Closed by stuartwdouglas** 2020-04-20 11:30 UTC
Labels: kind/bug

**Comment by famod** [comment] 2020-04-20 11:51
> By 'fix' I mean you will get a 500, but your object still won't be written out as RESTEasy does not know what representation to use.

Ok. That was also my main concern: A failure is simply swallowed.

Thanks for creating the Resteasy issue!
