### ISSUE TITLE
Static Web resources don't work in the Gradle build 

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1622] opened 2019-03-21 15:29 UTC
While version bumping https://github.com/quarkusio/quarkus-quickstarts/pull/90/ for https://github.com/quarkusio/quarkus-quickstarts/issues/75 and re-testing, I noticed that while http://localhost:8080/hello/greeting/M is OK, http://localhost:8080 is NOK and does not show that (new) static `index.html` web resource when built with Gradle (it's OK when built with Maven):

```
$ cd quarkus-quickstarts/getting-started
$ ../gradlew quarkusBuild
$ java -jar build/getting-started-runner.jar

$ http http://localhost:8080/hello/greeting/M
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 7
Content-Type: text/plain;charset=UTF-8
Date: Thu, 21 Mar 2019 15:28:18 GMT

hello M

$ http http://localhost:8080/ 
HTTP/1.1 404 Not Found
Connection: keep-alive
Content-Length: 0
Date: Thu, 21 Mar 2019 15:27:58 GMT
```

@stalep were you already aware of this? Anything obvious which the Quickstart is missing, or more interesting problem?

@jnizet @geoand given your past interest in all things Gradle related, perhaps you would like to chime in here.

**Comment by geoand** [comment] 2019-03-21 15:33
I am afraid I don't know a terrible amount about Gradle but I can definitely look into this if no one knows what the root cause is

**Comment by vorburger** [comment] 2019-03-21 16:25
So... I dug a little, and figured that the Gradle built `build/getting-started-runner.jar` is _"just"_ missing the `/META-INF/resources/index.html` which ends up there in the Maven built `target/quarkus-quickstart-1.0-SNAPSHOT-runner.jar`, from `src/main/resources/META-INF/resources/index.html` ...

.. but this isn't just some dumb `build.gradle` configuration issue, because the "pure Gradle" built `build/libs/getting-started.jar` (NB `not -runner`, and in `/libs/`) still has a `/META-INF/resources/index.html` .... ergo our `quarkus-gradle-plugin` "looses" it when it does the packaging.

@stalep does this ring a bell for what may be missing, or @jnizet perhaps you want to look at what needs to be added [probably here in Gradle plugin to also copy over resources](https://github.com/quarkusio/quarkus/blob/master/devtools/gradle/src/main/java/io/quarkus/gradle/tasks/QuarkusBuild.java), if you happen to have done this sort of thing before?

**Comment by jnizet** [comment] 2019-03-21 18:04
I haven't taken the time to dig deep, but I've noticed that the inputs of the Gradle task, and of the AppCreator class, only contain classes directories. 

This has most probably be designed based on how Maven works: it stored the compiled classes and the copied resources in the same `target/classes` directory.

Gradle doesn't work the same way: 
 - classes, generated by the compileJava task, are stored (by default) in `build/classes/java/main`
 - resources, copied by the `processResources` task, are stored (by default) in `build/resources/main`
 - unrelated to this specific issue, but related to the design of the quarkus gradle plugin: classes, generated by the compileKotlin task, are stored in `build/classes/kotlin/main`

So, just using one classes directory and expect to find everything (Java classes, resources, Kotlin classes), doesn't work with Gradle.

FYI, the reason why Gradle uses a different target directory for each task (and thus for each language) is because Gradle builds are incremental. When building a project, instead of recompiling everythign every time and re-copying the resources every time, Gradle hashes the inputs of the tasks and its outputs, and if the hashes are identical to the hashes of the previous build, the task is skipped. If several tasks used the same output directory, this mechanism wouldn't work anymore.
For example, if resources were copied to the directory where Java classes have been generated, then the next Java compilation would consider that its outputs have been modified, and would thus recompile everything.

**Comment by stalep** [comment] 2019-03-22 12:07
Hi @vorburger et al, sorry for the late reply.
I did not know of this issue and as @jnizet says, the AppCreator only contain classes directories. @Sanne is looking into a rewrite of the Gradle Plugin to work with a rather big change that @aloubyansky have worked on #1519 
We have discussed a bit the current shortcomings in Quarkus regards to Gradle and it is something we'll work to address. To be honest, the Gradle support came in fairly late and we did not anticipate this much usage of it. - but we're very happy with all the help/contributions regarding Gradle! You all have helped a lot making a lot better in these two weeks it's been public :)

**Comment by stalep** [comment] 2019-03-26 12:40
This was fixed with #1688 - thanks for reporting!

**Closed by stalep** 2019-03-26 12:40 UTC
Labels: gradle

**Comment by vorburger** [comment] 2019-04-08 16:12
FTR: I've just tested (using https://github.com/quarkusio/quarkus-quickstarts/pull/137) that this indeed works now.

**Comment by vorburger** [comment] 2019-04-10 16:01
TODO: Add a non-regression test for test after #1985 has been merged...
