### ISSUE TITLE
Adding Groovy plugin to Gradle project fails quarkusDev

### ISSUE THREAD

**Issue by marceloverdijk** [quarkusio/quarkus#6485] opened 2020-01-09 18:16 UTC
When adding the Groovy plugin like:

```
plugins {
    id "java"
    id "groovy"
    id "io.quarkus"
}
```

then `quarkusDev` fails with:

```
❯ ./gradlew clean quarkusDev

> Task :compileJava
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.

> Task :quarkusDev FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':quarkusDev' (type 'QuarkusDev').
> Directory '/Users/marceloverdijk/workspace/demo-backend-quarkus/build/classes/groovy/main' specified for property 'workingDir' does not exist.
> Directory '/Users/marceloverdijk/workspace/demo-backend-quarkus/src/main/groovy' specified for property 'sourceDir' does not exist.
```

It seems the `src/main/groovy` folder is expected.

I'm only adding Groovy to run Spock tests from `/src/test/groovy`.

When creating an empty `src/main/groovy` folder it keeps complaining about `build/classes/groovy/main`.

**Comment by x80486** [comment] 2020-01-09 21:43
Had a [very similar](https://stackoverflow.com/questions/59503068/gradles-kotlin-dsl-script-cannot-start-quarkus-application), if not the same issue with Kotlin; it was fixed with `1.1.1.Final` so this should be really straightforward 😉

**Comment by gastaldi** [comment] 2020-01-09 23:58
That doesn't seem related to the Quarkus plugin. It looks like you need to set the source directories like in https://docs.gradle.org/current/userguide/groovy_plugin.html#sec:changing_groovy_project_layout

**Comment by marceloverdijk** [comment] 2020-01-10 09:15
@gastaldi I never had to configure the Groovy source directories explicitly for any project so far.
And in those projects there were no `src/main/groovy` folders either, only `src/test/groovy`.

Btw even creating an empty `src/main/groovy` folder I still get: 

```
Directory '/Users/marceloverdijk/workspace/demo-backend-quarkus/build/classes/groovy/main' specified for property 'workingDir' does not exist.
```

But I will have another look this evening.

**Comment by gastaldi** [comment] 2020-01-10 09:16
Interesting. I'll have a closer look. Thanks for the feedback

Em Sex, 10 de jan de 2020 06:15, Marcel Overdijk <notifications@github.com>
escreveu:

**Comment by gastaldi** [comment] 2020-01-10 09:18
Can you share a small reproducer project? That would help a lot.

**Comment by marceloverdijk** [comment] 2020-01-10 09:57
Sure, will do it this evening.

**Comment by gastaldi** [comment] 2020-01-10 15:16
The following `build.gradle` works with quarkusDev. There is not much we can do because the error comes from Gradle and happens before the quarkusDev task is executed. 

```gradle
plugins {
    id 'java'
    id 'groovy'
    id 'io.quarkus'
}

repositories {
     mavenLocal()
     mavenCentral()
}

sourceSets {
    main {
        groovy {
            srcDirs = ['src/main/java']
        }
    }
}


dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'org.codehaus.groovy:groovy-all:2.4.15'

    testImplementation 'io.quarkus:quarkus-junit5'
    testImplementation 'io.rest-assured:rest-assured'
    
}

group 'org.acme'
version '1.0-SNAPSHOT'

compileJava {
    options.compilerArgs << '-parameters'
}

java {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}

```

**Comment by marceloverdijk** [comment] 2020-01-10 18:43
@gastaldi here is an small demo project: https://github.com/marceloverdijk/quarkus-spock

`./gradlew clean quarkusDev` fails as stated earlier.

I also added the `application` plugin and executing `./gradlew clean run` does not give the problem. The main class runs successfully.

Also when building the runner jar and executing that one no problems occur, it seems really relates to the `quarkusDev` task. 

PS: check the project's README.me for the output of above mentioned commands.

**Comment by gastaldi** [comment] 2020-01-10 18:55
Try adding the following snippet to your build.gradle file:
```gradle
sourceSets {
    main {
        groovy {
            srcDirs = ['src/main/java']
        }
    }
}
```

**Comment by marceloverdijk** [comment] 2020-01-10 19:28
@gastaldi yes that works, but it is only a workaround I assume?

It also requires `implementation 'org.codehaus.groovy:groovy-all:2.4.15'` and that's not desired. Groovy is only needed in the test scope.

**Comment by gastaldi** [comment] 2020-01-10 22:14
@marceloverdijk Ah I see what's wrong. I created a PR with the fix: https://github.com/quarkusio/quarkus/pull/6504

Can you give it a try and let me know if that works for you?

**Comment by gastaldi** [comment] 2020-01-10 22:16
Thanks for the reproducer project, that helped a lot :wink:

**Comment by marceloverdijk** [comment] 2020-01-11 09:44
@gastaldi I've build the code from the PR locally and now I can indeed run `quarkusDev` without having to define the Groovy sourceSet and adding the Groovy dependency 👍

**Closed** 2020-01-11 10:19 UTC
Labels: area/gradle, kind/bug

**Comment by marceloverdijk** [comment] 2020-01-11 10:26
I've also updated the [spock demo project](https://github.com/marceloverdijk/quarkus-spock).
It uses `999-SNAPSHOT` from your PR.

But adding `QuarkusTest` does not work unfortunately in combination with Spock.
Probably some Spock extension work is needed like Micronaut [has](https://github.com/micronaut-projects/micronaut-test/blob/master/test-spock/src/main/java/io/micronaut/test/extensions/spock/MicronautSpockExtension.java).

I also found https://github.com/quarkusio/quarkus/issues/4797 where @geoand mentioned there is no Spock integration (yet). I spend some evenings this week experimenting with Quarkus using Java, Kotlin, Groovy (using various setups) but I have the same feeling as @mvniekerk that using anything else then Java src and Java (JUnit5) tests could be problematic at this stage. Probably needs some time... ;-)

**Comment by geoand** [comment] 2020-01-11 10:29
Those cases can absolutely be made to work flawlessly, it's just that they need some extra attention :)

**Comment by marceloverdijk** [comment] 2020-01-11 10:32
Yes, that's why I'm posting these issues :-)

**Comment by geoand** [comment] 2020-01-11 10:33
Thank you for all your suggestions and help!
