### ISSUE TITLE
JAX-RS Rest endpoint PathParam value containing * fails

### ISSUE THREAD

**Issue by cpmoore** [quarkusio/quarkus#7352] opened 2020-02-22 02:51 UTC
When attempting to use a value that contains the `*` character for a `PathParam` in a JAX-RS rest endpoint, the following exception is thrown.
```
2020-02-21 20:47:15,137 ERROR [io.und.request] (vert.x-eventloop-thread-6) UT005071: Undertow request failed HttpServerExchange{ GET /api/v1/elastic/filebeat-*-test/search delegate io.undertow.vertx.VertxHttpExchange@e0664762}:
java.nio.file.InvalidPathException: Illegal char <*> at index 43: META-INF/resources/api/v1/elastic/filebeat-*-test/search
        at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:194)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:165)
        at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:89)
        at sun.nio.fs.WindowsPath.parse(WindowsPath.java:106)
        at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:267)
        at sun.nio.fs.AbstractPath.resolve(AbstractPath.java:65)
        at io.quarkus.runner.RuntimeClassLoader.findApplicationResource(RuntimeClassLoader.java:442)
        at io.quarkus.runner.RuntimeClassLoader.getResource(RuntimeClassLoader.java:144)
        at io.undertow.server.handlers.resource.ClassPathResourceManager.getResource(ClassPathResourceManager.java:64)
        at io.quarkus.undertow.runtime.DelegatingResourceManager.getResource(DelegatingResourceManager.java:21)
        at io.undertow.servlet.handlers.ServletPathMatches.getServletHandlerByPath(ServletPathMatches.java:97)
        at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:129)
        at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:43)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$1.handleRequest(UndertowDeploymentRecorder.java:100)
        at io.undertow.server.Connectors.executeRootHandler(Connectors.java:290)
        at io.undertow.server.DefaultExchangeHandler.handle(DefaultExchangeHandler.java:18)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$6.handle(UndertowDeploymentRecorder.java:361)
        at io.quarkus.undertow.runtime.UndertowDeploymentRecorder$6.handle(UndertowDeploymentRecorder.java:353)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup.handleHotReplacementRequest(VertxHotReplacementSetup.java:40)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$$Lambda$6.00000000113B25E0.handle(Unknown Source)
        at io.vertx.ext.web.impl.RouteState.handleContext(RouteState.java:1034)
        at io.vertx.ext.web.impl.RoutingContextImplBase.iterateNext(RoutingContextImplBase.java:131)
        at io.vertx.ext.web.impl.RoutingContextImpl.next(RoutingContextImpl.java:130)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:75)
        at io.quarkus.vertx.http.deployment.devmode.VertxHotReplacementSetup$2.handle(VertxHotReplacementSetup.java:64)
        at io.vertx.core.impl.ContextImpl.lambda$null$0(ContextImpl.java:330)
        at io.vertx.core.impl.ContextImpl$$Lambda$395.0000000011904DA0.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
        at io.vertx.core.impl.EventLoopContext$$Lambda$326.0000000015BC6E80.run(Unknown Source)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:785)
```

It appears that quarkus is attempting to resolve it as a file before checking the JAX-RS endpoints

 - Output of `uname -a` or `ver`:  MINGW64_NT-6.1 P024870 2.10.0(0.325/5/3) 2018-04-23 03:21 x86_64 Msys
 - Output of `java -version`:   openjdk version "1.8.0_222"
 - Quarkus version or git rev: 1.0.1.Final

**Comment by geoand** [comment] 2020-02-22 08:11
Hi,

Can you please try and see if the issue is still around in 1.2.1.Final?

**Comment by sberyozkin** [comment] 2020-02-22 12:35
@cpmoore How do you set the `*` ? Wildcards are not supported in `PathParam` and can only be set as part of the regular expression, example, `@PathParam("id:*")`

**Comment by cpmoore** [comment] 2020-02-22 19:14
@geoand 
I just tested in 1.2.1.Final and the issue still occurs.


@sberyozkin 
The `*` was not in the path param key, but in the url itself. 
For instance given the code 

```
@POST
@Path("/api/v1/elastic/{indexPattern}/search")
@Consumes(MediaType.APPLICATION_JSON)
public Response searchElasticsaerch(@PathParam("indexPattern") String indexPattern,Map<String,Object> body) { 

```
Making request to the endpoint `/api/v1/elastic/filebeat-*/search` causes the issue.
I thought of encoding the `*` but url-encoded `*` is still `*`

**Comment by sberyozkin** [comment] 2020-02-23 16:02
@cpmoore Thanks, yes, I vaguely recall is can be used as is as part of the path components.

**Comment by mmesaric** [comment] 2020-04-17 07:13
I'm having the same issue when using char ':' in PathParam. The issue is still not fixed in quarkus version 1.3.2.Final.

**Comment by cpmoore** [comment] 2020-05-12 23:36
I can add this issue still exists in 1.4.2.Final

**Comment by geoand** [comment] 2023-08-30 12:11
Is this still an issue?

**Comment by cpmoore** [comment] 2023-09-03 00:23
No, I can confirm it's working as expected as of version 2.16. Not sure which version specifically fixed it.

**Closed** 2023-09-03 00:24 UTC
Labels: kind/bug, triage/needs-feedback

**Comment by geoand** [comment] 2023-09-03 04:50
Thanks for checking
