### ISSUE TITLE
Quarkus AWT

### ISSUE THREAD

**Issue by TheBlindM** [quarkusio/quarkus#29396] opened 2022-11-22 01:46 UTC
### Description

Support AWT function:

```
  Desktop.getDesktop().browse(uri);
  Desktop.getDesktop().open(FileUtil.file(path));
```

**Comment by mkouba** [comment] 2022-11-23 12:21
Isnt' this covered by the `quarkus-awt` extension?

CC @zakkak @Karm

**Comment by zakkak** [comment] 2022-11-23 12:49
> Isnt' this covered by the `quarkus-awt` extension?

No, see @Karm's answer in https://github.com/quarkusio/quarkus/issues/29360#issuecomment-1321889149

**Comment by Karm** [comment] 2022-11-23 21:45
I would have some use for desktop GUI with Quarkus capabilities under the hood, yet neither Swing nor JavaFX would be my choice. We can perhaps go the https://fiji.sc/ way and use good old AWT or better, fully leverage GraalVM's C interoperability and use https://github.com/ocornut/imgui in a much more interesting way than via JNA/JNI Java bindings https://github.com/SpaiR/imgui-java.

We can leave the issue hanging in here for a while and see :man_shrugging:

**Comment by TheBlindM** [comment] 2022-11-27 08:37
> I would have some use for desktop GUI with Quarkus capabilities under the hood, yet neither Swing nor JavaFX would be my choice. We can perhaps go the https://fiji.sc/ way and use good old AWT or better, fully leverage GraalVM's C interoperability and use https://github.com/ocornut/imgui in a much more interesting way than via JNA/JNI Java bindings https://github.com/SpaiR/imgui-java.
> 
> We can leave the issue hanging in here for a while and see 🤷‍♂️
It seems that the Desktop operation in java awt is not seen in imgui-java

` Desktop.getDesktop().open(FileUtil.file(savePath));`


I often use cmd instead, but it fails in native

 Runtimeruntime = Runtime.getRuntime();
Processprocess = runtime.exec(""cmd.exe /c start " + savePath"); 

![image](https://user-images.githubusercontent.com/48701152/204126194-0dbf41f2-19d3-4212-a6ed-dff3105c0748.png)

**Comment by TheBlindM** [comment] 2022-11-29 00:39
Can anyone help?😥

**Comment by gsmet** [comment] 2022-11-29 11:46
@Karm if you don't plan on working on this anytime soon, I don't think it's worth keeping the issue open. I don't see anyone else from the team investing time in this and if someone comes with an extension or a blog post, fine, but I don't think keeping this issue open will help.

Now, if you think you will have time to dedicate to this, you can leave it open.

**Comment by Karm** [comment] 2022-11-29 12:34
> Can anyone help?disappointed_relieved

Hello @TheBlindM, I am somewhat rusty on my polyglot skills, but I guess the issue is unrelated to Quarkus. It might be the space in "Program Files" being treated erroneously. It is possible to launch a system process from your Java app.

I will close this issue now and kindly ask you to redirect your questions to either our Zulip https://quarkusio.zulipchat.com/# or to the user discussions https://github.com/quarkusio/quarkus/discussions

**Closed by Karm** 2022-11-29 12:34 UTC
Labels: kind/enhancement, area/native-image
