### ISSUE TITLE
[Hibernate Reactive] Multiple inserts of identical entities during a transaction

### ISSUE THREAD

**Issue by JFeoks** [quarkusio/quarkus#29133] opened 2022-11-08 16:48 UTC
### Description
**Dependencies**
quarkus-hibernate-reactive-panache
quarkus-hibernate-reactive
quarkus-reactive-pg-client
PostgreSQL: 15.0 (also reproduced on 14.5)

**My app does the following:**
1) request to an external system via REST Client to receive items
2) saving items in the database

**Model**
```
@MappedSuperclass
@Data
public class BaseEntity extends PanacheEntityBase implements Serializable {

    @Id
    // FIX: For some reason, the automatically generated id by hibernate leads to id duplication
    // Using sequence identifier types, such as Long, leads to an incorrect amount of inserted data and duplication too
    // Temporary fixed by uuid and session.setBatchSize(entitiesMap.values().size());
    @GeneratedValue(generator = "custom-uuid")
    @GenericGenerator(
            name = "custom-uuid",
            strategy = "ru.jfeoks.shoppingassistant.model.entity.generator.CustomUUIDGenerator"
    )
    private UUID id;
}

@Slf4j
public class CustomUUIDGenerator extends UUIDGenerator {

    @Override
    public Serializable generate(
            SharedSessionContractImplementor session,
            Object object
    ) throws HibernateException {
        Serializable result = super.generate(session, object);
        log.info("Generated ID: {}", result);
        return result;
    }
}

@Entity
@Cacheable
@Data
public class Item extends BaseEntity {

    @NotNull
    @Column(updatable = false, unique = true)
    private Long productId;

    @Column(length = 4000)
    private String name;
}
```

**Insertion code**
```
    @ReactiveTransactional
    @Override
    public Uni<Collection<Item>> createAll(Collection<Item> entities) {
        return Uni.createFrom().item(
                        entities
                                .stream()
                                .collect(
                                        Collectors.toMap(
                                                Item::getProductId,
                                                value -> value,
                                                (left, right) -> right)
                                )
                )
                .chain(
                        entitiesMap ->
                                getRepository()
                                        .findByProductIds(entitiesMap.keySet())
                                        .map(values -> values.stream().map(Item::getProductId).toList())
                                        .onItem().transformToUni(
                                                values -> {
                                                    values.forEach(entitiesMap.keySet()::remove);
                                                    return getRepository().persistAll(entitiesMap.values());
                                                }
                                        )
                                        .invoke(values -> log.info("Loaded: {}", values.size()))

                );
    }
```

**Invocation code**
```
    private Multi<Item> createAll(List<Item> items) {
        return Uni.createFrom().item(items)
                .onItem().transformToMulti(value -> Multi.createFrom().iterable(value))
                .call(
                        item ->
                                wbClient
                                        .queryAdditionalParameters(item.getProductId())
                                        .onItem().ifNotNull()
                                        .invoke(prices -> updateMinPrice(item, prices))
                )
                .group().intoLists().of(500)
                .onItem().transformToUniAndMerge(getService()::createAll)
                .onItem().disjoint();
    }
```
After a little research, I found out that ID generation works correctly, the problem is somewhere after calling org.hibernate.reactive.engine.ReactiveActionQueue
```
private <E extends ReactiveExecutable> CompletionStage<Void> executeActions(
			ExecutableList<E> list) throws HibernateException 
```
In this method, the correct number of entries comes to the list without duplicate ids (perhaps you need to double-check), I couldn't catch it with the debugger. Next in org.hibernate.reactive.pool.BatchingConnection already gets duplicates (with batch size = 1, the problem also reproduces).

**Logs of a single transaction**
```
2022-11-08 14:26:56,032 INFO  [ru.jfe.sho.mod.ent.gen.CustomUUIDGenerator] (vert.x-eventloop-thread-2) Generated ID: 3be253e8-45f6-4cc0-ba6b-b0864d0edcd3
...
2022-11-08 14:26:56,089 TRACE [org.hib.typ.des.sql.BasicBinder] (vert.x-eventloop-thread-2) binding parameter [17] as [OTHER] - [3be253e8-45f6-4cc0-ba6b-b0864d0edcd3]
...
Hibernate: 
    insert 
    into
        Item
        (..., id) 
    values
        (... $17)
...
2022-11-08 14:26:56,483 TRACE [org.hib.typ.des.sql.BasicBinder] (vert.x-eventloop-thread-2) binding parameter [17] as [OTHER] - [3be253e8-45f6-4cc0-ba6b-b0864d0edcd3]
...
Hibernate: 
    insert 
    into
        Item
        (..., id) 
    values
        (... $17)
```

### Expected behavior

Successful insertion

### Actual behavior

```
2022-11-08 18:52:13,363 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-2) HTTP Request to /bundles/enable failed, error id: 89a29588-9305-4819-9560-3fba69db8c60-1: io.vertx.pgclient.PgException: ERROR: duplicate key value violates unique constraint "item_pkey" (23505)
	at io.vertx.pgclient.impl.codec.ErrorResponse.toException(ErrorResponse.java:31)
	at io.vertx.pgclient.impl.codec.QueryCommandBaseCodec.handleErrorResponse(QueryCommandBaseCodec.java:57)
	at io.vertx.pgclient.impl.codec.ExtendedQueryCommandCodec.handleErrorResponse(ExtendedQueryCommandCodec.java:90)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeError(PgDecoder.java:246)
	at io.vertx.pgclient.impl.codec.PgDecoder.decodeMessage(PgDecoder.java:132)
	at io.vertx.pgclient.impl.codec.PgDecoder.channelRead(PgDecoder.java:112)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:1589)
```

### How to Reproduce?

1) The problem is periodically reproduced when trying to save 7000 records, where 500 records are in each transaction.
2) When saving one record at a time, the problem is not reproduced.
3) **WA**: the problem is not reproducible if batch size = collection size
```
    default Uni<Collection<T>> persistAll(Collection<T> entities) {
        return Uni.createFrom().item(entities)
                .call(
                        values -> getSession().call(
                                session -> {
                                    session.setBatchSize(values.size());
                                    return session.persistAll(values.toArray());
                                }
                        )
                );
    }
```

### Output of `uname -a` or `ver`

Windows 10 Pro 22H2

### Output of `java -version`

17

### Quarkus version or git rev

2.13.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by DavideD** [comment] 2022-11-10 10:02
Ah... I guess you are removing the Items that are already in the db

**Comment by DavideD** [comment] 2022-11-10 12:16
Nevermind, I think I've figured out what's going on. I will create a test to make in Quarkus to check

**Comment by DavideD** [comment] 2022-11-10 14:45
I think the problem is that you are using `.onItem().transformToUniAndMerge(getService()::createAll)` instead of `.onItem().transformToUniAndConcatenate(getService()::createAll)`.

The difference is that, when using merge the execution order of the Uni is not deterrministic. This means that the select of the second batch can happen before the insert of the first batch is executed. If there are duplicates between the two batches, the select query won't find them.

If you set `quarkus.hibernate-orm.log.sql=true` in the `application.properties`, you can see the execution order of the sql queries.

Also, even if it's not related, there's no reason to create a map. You could change the method `createAll` to:
```java
	@ReactiveTransactional
	public Uni<List<Item>> createItems(Collection<Item> entities) {
		final Set<Long> pids = entities.stream().map( Item::getProductId ).collect( toSet() );
		return repository
                                // Return the existing product ids in the db
				.findExistingProductIds( pids )
				.map( existingPids -> entities.stream()
						.filter( item -> !existingPids.contains( item.getProductId() ) )
						.collect(toList())
				)
				.call( repository::persist );
	}
```

I've created a POC rewriting one of the quickstarts: https://github.com/DavideD/quarkus-quickstarts/tree/29133-batch/hibernate-reactive-panache-quickstart/src/main/java/org/acme/hibernate/orm/panache

Let me know if I've missed something.

**Comment by JFeoks** [comment] 2022-11-11 09:08
@DavideD, thank you very much for your comment! So it became really clearer, because this thing is not obvious at first glance.

**Comment by DavideD** [comment] 2022-11-11 09:14
I'm closing this issue, but feel free to ask more question or reopen it if something else comes up related to it.

**Closed by DavideD** 2022-11-11 09:14 UTC
Labels: kind/bug, env/windows, area/hibernate-reactive

**Comment by JFeoks** [comment] 2022-11-11 09:21
@DavideD, thanks!
