### ISSUE TITLE
Quarkus Maven Plugin for v2.13.2 fails with Flattened POM

### ISSUE THREAD

**Issue by kjq** [quarkusio/quarkus#28553] opened 2022-10-13 03:21 UTC
### Describe the bug

This just happened when Renovate when to pull the latest version of Quarkus and perform the build - it says it cannot resolve the `.flattened-pom.xml".

We have not had any problems with Maven or the Maven Flatten Plugin or the Quarkus Maven Plugin before.

`[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.13.2.Final:generate-code-tests (default) on project PROJECT: Quarkus code generation phase has failed: Failed to initialize Quarkus bootstrap Maven artifact resolver: Failed to load current project at /home/NAME/work/PROJECT/client/target/.flattened-pom.xml: Cannot invoke "java.io.File.toPath()" because the return value of "org.apache.maven.model.Model.getProjectDirectory()" is null -> [Help 1]`

Ill watch to see if it was just a blip on the CI/CD side but wanted to point it out...

### Expected behavior

Recognizes the POM as before and completes the Maven build.

### Actual behavior

Cannot resolve the `.flattened-pom.xml` generated using the Maven Flatten Plugin

### Output of `java -version`

17

### Quarkus version or git rev

2.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven v3.8.4

### Additional information

Sometimes resolving all the artifacts with a new release gives us a red herring so it may be that.  Will watch/close if it is not.

**Comment by aloubyansky** [comment] 2022-10-13 06:19
This is a duplicate of https://github.com/quarkusio/quarkus/issues/28541, which has already been fixed in https://github.com/quarkusio/quarkus/pull/28542. Sorry about that.

**Closed by aloubyansky** 2022-10-13 06:19 UTC
Labels: kind/bug, area/maven
