### ISSUE TITLE
Items missing in client from a Multi SSE response

### ISSUE THREAD

**Issue by romilpunetha** [quarkusio/quarkus#24851] opened 2022-04-09 12:05 UTC
### Describe the bug

I have a piece of code that gets users from user-service, which returns a multi. However, there are instances where a user object is missing from the list.

Code in user-service:
```
 return this.getByIds(ids).onItem().transformToMulti(users -> Multi.createFrom().items(users.stream()));
```

Code in client:
```
List<String> userIds ; // A list of distinct valid userIds with size <= 25

return userClient.getByIds(userIds).collect().asList()
                .map(users -> { // this list of users has 1 item missing.

                    Map<String, User> userMap = users.stream().collect(Collectors.toMap(User::getId, user -> user));

                   for(String userId: userIds) {
                     User user = userMap.get(userId);
                     Log.debug("userId : " + user.getId()); // this line fails with null error

                     return null;
                   }
                })
                .onFailure().retry().atMost(3)
                ;
    }
```

I have a trace that shows that the ids were being fetched from user-service using cache only (as there is no db call in the trace), and the code fails because the user was null, and then a retry occurs which again fetches the same ids from user-service, and this time, all objects are received. 
I checked that the user that was missing in response exists in cache. Nonetheless, would've been fetched from db if not in cache.

Are there any incidents of items being dropped from the stream? The size of the list also pretty small (<=25).

<img width="1551" alt="Screenshot 2022-04-09 at 5 19 26 PM" src="https://user-images.githubusercontent.com/47735999/162572846-9b111911-bfc3-4db0-a2cf-2164b0158fb4.png">
 

### Expected behavior

The response list contains all items.

### Actual behavior

Sometimes, an item is missing from the list. 

### Output of `uname -a` or `ver`

 Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05) OpenJDK 64-Bit Server VM GraalVM CE 22.0.0.2 (build 17.0.2+8-jvmci-22.0-b05, mixed mode, sharing)

### Quarkus version or git rev

2.8.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Java version: 17.0.2, vendor: Homebrew, runtime: /opt/homebrew/Cellar/openjdk/17.0.2/libexec/openjdk.jdk/Contents/Home Default locale: en_IN, platform encoding: UTF-8 OS name: "mac os x", version: "12.0.1", arch: "aarch64", family: "mac"

**Comment by cescoffier** [comment] 2022-04-09 13:42
I would need a proper reproducer to understand what's going on.

**Comment by romilpunetha** [comment] 2022-04-09 16:43
I'll try reproducing this, but it might be a little difficult because a retry works.
Moreover, I tried making the raw curl call several times and wasn't able to reproduce this.

**Comment by romilpunetha** [comment] 2022-04-10 15:15
Tried the following configurations: 

List size : 25

1. local server, local db : no errors.
2. local server, remote db: no errors.
3. remote server in container with 1 core, remote db: intermittent errors.
4. remote server in container with 2 cores, remote db: intermittent errors.

I'm getting errors only when I run the code in remote containers. Still trying to narrow down the issue.

**Comment by romilpunetha** [comment] 2022-04-10 20:25
@cescoffier 
I was able to narrow it down. There's no issue on the server side. The user-service is sending all elements as expected. One of the items is missing at the client side. This is what the server resource looks like:

user-service:
```
 @POST
    @Produces(MediaType.SERVER_SENT_EVENTS)
    @RestStreamElementType(MediaType.APPLICATION_JSON)
    @Path("/ids")
    public Multi<User> getByIds(List<String> ids) {
        return service.getByIds(ids)
                .emitOn(Infrastructure.getDefaultExecutor());
    }
```

user rest client:
```
 @POST
    @Path("/ids")
    Multi<User> getByIds(List<String> ids);
```

Tried user-client with @Produces and @RestStreamElementType as well but no luck.

The client does the following:
```
return userClient.getByIds(userIds).collect().asList()
```


Is this the intended way of using this or am I missing something?

**Comment by romilpunetha** [comment] 2022-04-10 21:56
A ref on SSE: 
https://dev.to/miketalbot/server-sent-events-are-still-not-production-ready-after-a-decade-a-lesson-for-me-a-warning-for-you-2gie

**Comment by cescoffier** [comment] 2022-04-11 05:37
Are you using the Reactive Rest Client or the _classic+ Rest client (depends on the extension you use).
I'm also wondering why you use an `emitOn` (even if the bug does not come from that, it looks like a bad smell).

\CC @michalszynkiewicz

**Comment by romilpunetha** [comment] 2022-04-11 06:43
I'm using `quarkus-resteasy-reactive-jackson`

The `emitOn` was taken from https://quarkus.io/blog/mutiny-back-pressure/ . I thought for a large stream with large sized objects serialization would be a problem hence offloaded it to the worker thread.

**Comment by cescoffier** [comment] 2022-04-11 07:03
`quarkus-resteasy-reactive-jackson` it the server bit, not the rest client.

**Comment by romilpunetha** [comment] 2022-04-11 07:21
My bad... its `quarkus-rest-client-reactive-jackson`

**Comment by michalszynkiewicz** [comment] 2022-04-11 07:31
@romilpunetha as Clement wrote, a reproducer would help a lot in fixing this/helping you.

If the problem occurs only when you run in containers maybe it's related to latency?
Have you tried reproducing it in a test, e.g. with `@RepeatedTest(100)` ?

**Comment by romilpunetha** [comment] 2022-04-11 07:55
I'll try with the `@RepeatedTest` as suggested. 

As for the latency question, the red indicator in the image attached is the `Multi<>` latency and the blue one is for `Uni<List>`. The request itself is max 25 items, so I don't think latency is an issue. 


<img width="1645" alt="Screenshot 2022-04-11 at 1 23 26 PM" src="https://user-images.githubusercontent.com/47735999/162690451-857f8b39-172d-40a4-9c1a-79256430b46e.png">

**Comment by romilpunetha** [comment] 2022-04-11 20:12
Further narrowed the issue. It's not a problem with the container. It's a problem when the container is deployed in k8s + istio.

I created a container deployment locally and tried the same experiment with 100 user ids. Locally I saw no failures. I did the same test on our stage env which runs on k8s + istio and could see frequent failures.

**Comment by romilpunetha** [comment] 2022-04-11 20:45
Did a couple of more experiments:

| client      | client env | server env  | observation
| ----------- | ----------- | ----------- | ----------- |
| curl      | local       | local  | no errors
| curl   | local        |local container | no errors
| curl   | local  | container in k8s+istio | no errors
| curl   | container in k8s+istio  |container in k8s+istio | no errors
| reactive client   | local  | local | no errors
| reactive client   | local  | local container | no errors
| reactive client   | local  | container in k8s+istio | errors
| reactive client   | container in k8s+istio   | container in k8s+istio | errors

**Comment by romilpunetha** [comment] 2022-04-12 05:02
I did a wireshark capture as suggested.

In the images, you can see that the 5th attempt had one item missing. 
I checked the wireshark analyze http stream for all the 5 responses and all of them had the exact same number of lines in response. So the data is present over the wire. 

<img width="1569" alt="Screenshot 2022-04-12 at 10 19 57 AM" src="https://user-images.githubusercontent.com/47735999/162883295-2367b49a-979e-41bd-9164-4dd5cd3d9b77.png">
<img width="1536" alt="Screenshot 2022-04-12 at 10 20 16 AM" src="https://user-images.githubusercontent.com/47735999/162883325-730fe360-c9fa-4a6a-b6f1-60bde7babeff.png">

**Comment by romilpunetha** [comment] 2022-04-12 05:29
If you try the following, you should get at least one occurrence within 30 sec:

```
while true; do curl --location --request GET 'df-api.stage.dstreet.finance/api/v1/session/test' --header 'x-df-tenant: df' | wc -l | grep 198;done
```
It returns the entire stream of 100 users from user-service using the resteasy reactive client.

**Comment by michalszynkiewicz** [comment] 2022-04-12 06:11
I'll try passing through the items now...

**Comment by romilpunetha** [comment] 2022-04-12 07:32
For the purpose of this test, I'm just passing them through and printing them on the terminal.
Even I wasn't able to reproduce the issue in the last hour using the links I shared.

**Comment by romilpunetha** [comment] 2022-04-12 07:55
Was able to reproduce is just now. 

![Uploading Screenshot 2022-04-12 at 1.25.04 PM.png…]()

**Comment by michalszynkiewicz** [comment] 2022-04-12 09:16
I see your stage server returning not enough results quite often but a simple endpoint like below returns the appropriate amount of results. This makes me think that with high probability the problem is not in the client...

```java
    @Path("pass-through")
    @GET
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public Multi<User> passThrough() throws InterruptedException {
        return client.getUsers("df");
    }
```

**Comment by romilpunetha** [comment] 2022-04-12 09:59
I was able to reproduce it from 2 other machines as well.

<img width="907" alt="Screenshot 2022-04-12 at 3 28 30 PM" src="https://user-images.githubusercontent.com/47735999/162934571-81837612-059e-48e8-91c5-20fcc703b815.png">

<img width="931" alt="Screenshot 2022-04-12 at 3 28 06 PM" src="https://user-images.githubusercontent.com/47735999/162934532-fa426a0b-85d1-4d31-bf49-5a5a9a39a92f.png">

**Comment by michalszynkiewicz** [comment] 2022-04-12 10:06
This command fails, yes.
Accessing your server from an app using rest-client-reactive, with the sources I shared, works.

**Comment by romilpunetha** [comment] 2022-04-12 10:12
Did you connect your client to user-service directly? 

If yes, could you try running that in the while loop like I did and see if there are any errors? Because I've tried this call from clients in 2 different services and both failed.

**Comment by michalszynkiewicz** [comment] 2022-04-12 10:28
This is what I did:
[rrc-sse.zip](https://github.com/quarkusio/quarkus/files/8472062/rrc-sse.zip)

You can start the project with `mvn quarkus:dev` and call `curl localhost:8080/hello/pass-through` to have the app pass through the response from the user-service.

**Comment by michalszynkiewicz** [comment] 2022-04-12 11:21
The linked zip uses Quarkus 2.7 but it works the same way with 2.8 for me

**Comment by romilpunetha** [comment] 2022-04-12 11:28
Yes, I tried your code with 2.8 and couldn't reproduce it as well. Will try again.
If I can't, I'll have to look for what's different in my setup that could be causing the issue as it is happening across all services. I had to move to using Uni<list>.

**Comment by romilpunetha** [comment] 2022-04-12 14:10
I could reproduce the error in your code if I use `kubectl port-forwarding` to the same stage server instead of using the DNS.

<img width="1131" alt="Screenshot 2022-04-12 at 7 39 23 PM" src="https://user-images.githubusercontent.com/47735999/162981408-b33d4db6-300f-4bac-9b54-108c6ce946bb.png">

**Comment by romilpunetha** [comment] 2022-04-12 17:59
@michalszynkiewicz 

I ran the wireshark test again. This is what I found:

When I follow the http stream at the outer level as shown, I can see 1 item missing.

<img width="1718" alt="Screenshot 2022-04-12 at 11 25 29 PM" src="https://user-images.githubusercontent.com/47735999/163024259-6c32c703-06f8-4626-9086-418b0d7254f7.png">
<img width="1585" alt="Screenshot 2022-04-12 at 11 28 10 PM" src="https://user-images.githubusercontent.com/47735999/163024732-c8f53415-e395-45fc-a2b5-88cdf8398cc7.png">

However, when I follow the http stream at the inner level, I can observe all items. 
<img width="1624" alt="Screenshot 2022-04-12 at 11 28 48 PM" src="https://user-images.githubusercontent.com/47735999/163024831-686e9c6e-768f-4a5e-bdfd-83466318a7c7.png">
<img width="1722" alt="Screenshot 2022-04-12 at 11 29 05 PM" src="https://user-images.githubusercontent.com/47735999/163024870-2791f88f-6b26-413d-90bb-0ce3f956d297.png">

Any ideas? This is the same code you shared with the config from previous comment.

**Comment by michalszynkiewicz** [comment] 2022-04-12 20:31
Maybe add some logging on each item in your code to see if the client gets the message?
And this is only if you use port forwarding?

**Comment by romilpunetha** [comment] 2022-04-20 07:43
I have an instance where this is happening even without a client. 

```
return this.mongoCollection().find(filter, findOptions)
```

The above line is consumed as follows:

```
List<Entries> entries = repository.find().collect().asList().await().indefinitely()
```

There's no client call here. The entries are collected directly from the stream that the db returns, by the service directly connected to the db.

**Comment by cescoffier** [comment] 2022-04-24 17:54
I do not understand your last example. Where is the SSE? 

Mongo returns the stream and you collect all items into the list. How do you know that there are missing items?

**Comment by romilpunetha** [comment] 2022-04-24 20:14
I did not quote the complete example as I wanted to emphasize on the fact that simply with the above 2 lines, I'm missing an element in the collected list. There is no client involved, and I've faced this issue only twice when the server was directly communicating with the db. How I confirmed is that the list is converted into a map, and elements are accessed from the map using the input ids. Every id will have an entry in the db without fail. 


It goes something like this:
```
public Multi<Entries> getEntriesById(List<String> ids) {

Document filter = createFilter(ids);

return this.mongoCollection().find(filter, findOptions); // the filter contains the list of ids

}

public Uni<Void> test() {

List<String> ids; // input list of ids

getEntriesById(ids)) // entries are fetched from db using the ids. 
.chain(entries -> {
   Map<String, Entries> mp = createMap(entries);
   for(String id : ids) {
   Log.debug(mp.get(id).getValue()); //  null pointer exception here in getValue()
}
});

}

```

**Comment by cescoffier** [comment] 2022-04-25 12:20
It seems to be an issue in Mongo. 
Anyway to reproduce it?

**Comment by romilpunetha** [comment] 2022-04-25 13:44
Not sure. Because occurrence during direct connection with DB is extremely rare. However, when you add one hop to the service-to-service interaction as in the previous examples, its much easier to reproduce. As shown [here](https://github.com/quarkusio/quarkus/issues/24851#issuecomment-1097027602), the items received by the service connected to the database had all the items, however, the client server's stream dropped one. So mongo may not be the issue here.

**Comment by cescoffier** [comment] 2022-04-25 17:01
I guess you will need to build a reproducer. I don't completely understand the issue. In your previous comment it was mongo only and you said it was missing items, and now it seems to be when there is a hop.

Any chance to produce a reproducer?

**Comment by romilpunetha** [comment] 2022-06-06 06:38
I did multiple tests on getting multi from DB. It always succeeded. I guess my previous observation was incorrect. Its never dropping when getting from db. Only when the multi is passed downstream to the caller service is when I'm observing drops.

**Comment by geoand** [comment] 2022-08-30 14:10
I'm going to close this as we can't reproduce it without a sample project. If you can upload one, please do and we will reopen the issue.

**Closed by geoand** 2022-08-30 14:10 UTC
Labels: kind/bug, area/rest-client, needs-reproducer
