### ISSUE TITLE
Conditionally use @Mock

### ISSUE THREAD

**Issue by edewit** [quarkusio/quarkus#5394] opened 2019-11-12 08:18 UTC
**Description**
Testing my rest endpoint I like the way I can create a mock for my service and only test how my parameter are parsed and passed to the service. But I also have a test that tests the service, in that case I want the real service not the mock. It would be great if there was a way to use the mock conditionally.

**Comment by ia3andy** [comment] 2019-11-12 08:32
Having a way to manage how mocks are used from a test  is a must have IMHO

**Comment by InfoSec812** [comment] 2020-02-25 22:38
+1 The testing story around Quarkus is one of the biggest issues I am having with the tools right now. For example, to test an application which integrates Kafka, I need to have a Kafka instance to connect to. This is similar for many other ancillary service (ActiveMQ, Infinispan, etc...). For a good developer story, being able to test locally without ancillary services is going to be a necessity.

**Comment by InfoSec812** [comment] 2020-02-25 22:40
It has been suggested to me to use [TestContainers](https://www.testcontainers.org/), but that requires that I write additional logic into my tests to detect when I am running tests locally versus running in a Kubernetes cluster.

**Comment by ia3andy** [comment] 2020-02-26 09:14
@geoand any hint on how that could be achievable, I would be interested in implementing it :)

**Comment by geoand** [comment] 2020-02-26 09:22
This is a hard problem to solve currently... I was actually thinking about it a little and didn't come up with any easy solutions...

**Comment by jordanglassman** [comment] 2020-04-08 17:57
My current workaround for this is to comment out `@Mock` on the undesired mock while doing development and then `@Ignore` the tests before checking in.

Sounds like "disabling" annotations involves mucking around in bytecode or various other overcomplicated schemes.

**Comment by geoand** [comment] 2020-04-08 18:04
Quarkus 1.4 will contain major improvements in this area.

Please see the testing documentation in this repository if you wish to know more before 1.4 is released

**Comment by InfoSec812** [comment] 2020-04-08 18:55
@geoand Are you referring to [QuarkusMock](https://github.com/quarkusio/quarkus/blob/ff6f5482096c9682baa5bca15d8f88ac11e6d55e/docs/src/main/asciidoc/getting-started-testing.adoc#72-mocking-using-quarkusmock)? That still will not address issues like Kafka Streams where you are required to use a static method on a class.

**Comment by geoand** [comment] 2020-04-08 18:58
Yes I am.

I am not sure I follow what you mean about Kafka Streams.

**Comment by InfoSec812** [comment] 2020-04-08 19:00
See my updated comment above... The issue is that a lot of these classes require you to call static methods on them which would not be "mock"able.

**Comment by geoand** [comment] 2020-04-08 19:01
We might be able to do something about those in the future.
@FroMage has a PR where he adds support for mocking Panache static methods

**Comment by FroMage** [comment] 2020-04-09 13:13
Well, are we generating those kafka classes? Where are they defined or coming from? Do we own that code?

**Comment by geoand** [comment] 2022-01-11 09:04
Between DevServices and TestProfile I think we have covered this use case, so I will close this

**Closed by geoand** 2022-01-11 09:04 UTC
Labels: kind/enhancement
