### ISSUE TITLE
Resources defaulting to ApplicationScoped

### ISSUE THREAD

**Issue by dansiviter** [quarkusio/quarkus#1371] opened 2019-03-10 09:08 UTC
Quarkus Version: 0.11.0
Maven Version: 3.6.0
Java Version: 1.8.0_191

It appears on build that JAX-RS resources are defaulting to `@ApplicationScope`. e.g.:

```
@Path("v1")
@Produces(APPLICATION_JSON)
public class HelloWorldResource {
```
Is resulting in a message:
```
[INFO] [io.quarkus.arc.processor.BeanProcessor] Found unrecommended usage of private members (use package-private instead) in application beans:
	- @Inject field acme.jaxrs.v1.HelloWorldResource#jwtProvider
```

However, ReSTEasy states:
> If a JAX-RS root resource does not define a scope explicitly, it is bound to the Request scope.

<sup>See [here](http://docs.jboss.org/resteasy/docs/3.6.3.Final/userguide/html_single/index.html#d4e2782).</sup>

Also, there is also a question regarding "unrecommended usage of private members...in application beans": what is the rationale around this?

Moved from quarkusio/quarkus-quickstarts#86.

**Comment by gsmet** [comment] 2019-03-11 11:33
I can confirm we decided to make JAX-RS resources application scoped by default, it's not a bug. We took some liberty from the specs in general to try to choose the best defaults. It should probably be mentioned in our guides if not already, I'll check.

About your second question: if your property is package private, we can inject it directly without requiring any reflection. That's why we recommend package private members for injection as we try to avoid reflection as much as possible. @geoand maybe we should have a SO question about it?

**Comment by geoand** [comment] 2019-03-11 11:35
@gsmet Yeah, that makes perfect sense, I'll go ahead and add one

**Comment by geoand** [comment] 2019-03-11 12:07
SO question and answer added: https://stackoverflow.com/questions/55101095/why-does-quarkus-warn-me-about-injection-in-private-fields/55101248

**Comment by dansiviter** [comment] 2019-03-11 13:20
Thanks for the clarification. 

Regarding performance differences, do you have any rough figures around what that would be? This would help justify trading performance for encapsulation.

**Comment by gsmet** [comment] 2019-03-11 14:59
Not really, it was more a general guidance of the project to try to avoid reflection as much as possible.

**Comment by dansiviter** [comment] 2019-03-11 16:34
Sure. I'm happy to close if the docs are updated as it deviates from documented JAX-RS and CDI behaviour of RestEasy (+Jersey) and Weld.

**Comment by cescoffier** [comment] 2019-03-11 17:20
The getting started guide mentions:

Differences with vanilla Jax-RS:
With Quarkus there is no need to create an Application class. It’s supported but not required. In addition, only one instance of the resource is created and not one per request. You can configure this using the different *Scoped annotations (ApplicationScoped, RequestScoped, etc).

We could improve the wording (open to suggestions)

**Comment by dansiviter** [comment] 2019-03-11 21:12
So I dug out the JAX-RS 2.1 spec and it states:

> **3.1.1 Lifecycle and Environment**
> By default a new resource class instance is created for each request to that resource.
>
> **3.2 Fields and Bean Properties**
> ...supported for the default per-request resource class lifecycle.
>
> **4.1 Lifecycle and Environment**
> By default a single instance of each provider class is instantiated for each JAX-RS application. 

So the spec specifically states each resource should be `@RequestScoped` by default. This includes associated items such as `javax.ws.rs.Providers`. Therefore, I don't this it's a good idea to move away from the specification without good justification.

Also, Thorntail changed the auto-created `javax.ws.rs.Application` instance as it deviated too far away from the JAX-RS spec and caused more pain than it cured (see thorntail/thorntail#847).

**Comment by kenfinnigan** [comment] 2019-03-12 11:55
@dansiviter, as we don't intend to pass Java EE/Jakarta EE TCKs, it means we can choose to do things that improve the defaults for greenfield development, even if they don't comply with the "spec".

**Comment by dansiviter** [comment] 2019-03-12 12:40
@kenfinnigan Regardless, it's fundamental behaviour change under the guise of "sensible defaults". Frankly, I'm yet to use `@ApplicationScoped` resource beans as the default `@RequestScoped` made the most sense in all use-cases. It now risks coupling other injected beans on different scope causing unexpected behaviour as they'll will not get re-injected. Also creating a `Application` instance is hardly a burden to ensure deterministic behaviour.

**Comment by kenfinnigan** [comment] 2019-03-12 13:11
There's nothing that prevents us from changing traditional behavior, if we feel it's the best choice.

If what we've chosen as defaults doesn't fit with a users needs there are two options:

- Modify the behavior such that it behaves as you've experienced in other frameworks. Such as adding `@RequestScoped` to your JAX-RS Resource classes
- Use a different framework. This one is key. In Quarkus we are likely to do things that may not appeal to everyone, and that's ok. It just means that Quarkus is for everyone, and that's ok too.

**Comment by dansiviter** [comment] 2019-03-12 17:28
I think my point is being lost somewhat: If 'Developer Joy' is what Quarkus is aiming for, please don't arbitrarily deviate from specifications. It just wastes time debugging strange behaviour.

We have a lot of stuff running on Thorntail and very interested in Quarkus (especially when Graal gets to J11) especially as Thorntail takes an age to start. Porting to it will be a pain as we'll have to find all the ways in which Quarkus deviates and implement workarounds.

**Comment by kenfinnigan** [comment] 2019-03-12 19:31
Quarkus is certainly aiming for "Developer Joy", but not at the expense of doing what we think is the better approach.

Though a choice might have been made by a specification, that doesn't mean in the world of containers and Kubernetes that such a choice still makes sense. Even more so when such a choice was made before the advent of Cloud.

Quarkus is focused on "Container First" and Kubernetes. To achieve that, if the team believe we need to deviate from current specifications to achieve that goal, then we will.

Quite likely we can do a better job of documenting all these deviations to make it clear what might be required if anyone wants to migrate an existing application. Would that be useful?

**Comment by dansiviter** [comment] 2019-03-12 20:23
Ideally, you'd keep it the same, but if you have to deviate both listing and justifying the changes would be very helpful so develops don't stumble on to them inadvertently. The justification is especially important to why these decisions are "better" than a spec designed by community which hasn't been stated above.

We're a Java house using K8s heavily (currently trialing Knative workloads) so I'm pleased something like Quarkus has landed at just about 
the right time for us. Just please make it easy to migrate to with few gotchas, then maybe I could prise more of our developers away from the abominable Spring Boot.

**Comment by gsmet** [comment] 2019-11-08 00:29
@mkouba could you check if this has been properly documented and close it with the out-of-date label if so. If not, it should be an easy issue to fix and close.

**Comment by mkouba** [comment] 2019-11-08 07:35
Well, there is a tip in the getting-started guide: https://quarkus.io/guides/getting-started#the-jax-rs-resources. But it does not mention the [quarkus.resteasy.singleton-resources](https://quarkus.io/guides/all-config#quarkus-resteasy-server-common_quarkus.resteasy.singleton-resources). Also we don't explain the justification...

@gsmet @kenfinnigan what's the best place to add this info? Writing JSON REST Services? Get Started?

**Comment by kenfinnigan** [comment] 2019-11-08 13:30
Certainly Writing JSON REST Services, but I'm wondering if we need a more general doc with a list of "what's different from current Jakarta EE development" that outlines things like default JAX-RS Resource scope, no need for `Application` class, etc?

**Comment by gsmet** [comment] 2019-11-13 18:58
@mkouba please add it to the JSON REST services doc for now (at the end of it). We will move that out as soon as we have a reference guide.

**Closed** 2019-11-18 13:48 UTC
Labels: component:documentation
