### ISSUE TITLE
NoSuchElementException during Hibernate initialization

### ISSUE THREAD

**Issue by spoenemann** [quarkusio/quarkus#5109] opened 2019-11-01 09:12 UTC
**Describe the bug**
I get a NoSuchElementException when running `./gradlew quarkusDev` in the project https://github.com/theia-ide/extension-registry (branch `quarkus-issue`, subdir `server`).

**Expected behavior**
If anything is wrong in the way I use the JPA annotations, I would expect a meaningful error message.

**Actual behavior**
```
08:42:45,612 ERROR [io.qua.dev.DevModeMain] Failed to start quarkus: java.lang.ExceptionInInitializerError
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:142)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:180)
        at io.quarkus.dev.DevModeMain.start(DevModeMain.java:94)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:66)
Caused by: java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:413)
        ... 9 more
Caused by: java.util.NoSuchElementException
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:999)
        at org.hibernate.cfg.annotations.TableBinder.linkJoinColumnWithValueOverridingNameIfImplicit(TableBinder.java:713)
        at org.hibernate.cfg.PkDrivenByDefaultMapsIdSecondPass.doSecondPass(PkDrivenByDefaultMapsIdSecondPass.java:37)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1684)
        at org.hibernate.boot.internal.InFlightMetadataCollectorImpl.processSecondPasses(InFlightMetadataCollectorImpl.java:1641)
        at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:286)
        at io.quarkus.hibernate.orm.runtime.boot.FastBootMetadataBuilder.build(FastBootMetadataBuilder.java:342)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.createMetadata(PersistenceUnitsHolder.java:111)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.constructMetadataAdvance(PersistenceUnitsHolder.java:84)
        at io.quarkus.hibernate.orm.runtime.PersistenceUnitsHolder.initializeJpa(PersistenceUnitsHolder.java:47)
        at io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder$4.created(HibernateOrmRecorder.java:70)
        at io.quarkus.arc.runtime.ArcRecorder.initBeanContainer(ArcRecorder.java:96)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources22.deploy_0(ArcProcessor$generateResources22.zig:418)
        at io.quarkus.deployment.steps.ArcProcessor$generateResources22.deploy(ArcProcessor$generateResources22.zig:36)
        at io.quarkus.runner.ApplicationImpl1.<clinit>(ApplicationImpl1.zig:375)
        ... 9 more
```

**To Reproduce**
1. Open https://gitpod.io#snapshot/a6511139-67c6-4ab5-a6c1-bbb13af9a6b3
2. See the exception in the terminal after the dev server has started.

The dev server sporadically started without any exception; in that case type `./gradlew quarkusDev` again.

**Configuration**
```properties
quarkus.datasource.url = jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.driver = org.postgresql.Driver
quarkus.datasource.username = gitpod
quarkus.datasource.password = gitpod

quarkus.hibernate-orm.database.generation=drop-and-create
```

**Environment (please complete the following information):**
 - Output of `uname -a`:
```
Linux ws-5d1642e2-0cd8-4d81-aafb-5599769ffec6 4.15.0-1034-gke #36-Ubuntu SMP Thu Jun 6 11:16:45 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
 - Output of `java -version`:
```
openjdk version "11.0.2" 2019-01-15 LTS
OpenJDK Runtime Environment Zulu11.29+3-CA (build 11.0.2+7-LTS)
OpenJDK 64-Bit Server VM Zulu11.29+3-CA (build 11.0.2+7-LTS, mixed mode)
```
 - Quarkus version: 0.26.1

**Additional context**
I'm running the `quarkusDev` task in a docker container in the [Gitpod](https://gitpod.io/) cloud IDE. The JDK is provided by [SDKMAN](https://sdkman.io/) and is set to `11.0.2-zulufx`.

**Comment by geoand** [comment] 2019-11-01 11:00
@Sanne any idea what might be going on here?

I was able to reproduce it both in dev mode and in after building the jar and running it with `java -jar ...`

**Comment by Sanne** [comment] 2019-11-01 13:53
Interesting, looks like a similar problem as https://hibernate.atlassian.net/projects/HHH/issues/HHH-13295

We normally track such issues on Hibernate's JIRA - I'll close this one and link it from there so we can include this as test as well.

Thanks for the reproducer!

**Closed by Sanne** 2019-11-01 13:53 UTC
Labels: bug, component:hibernate-orm

**Comment by Sanne** [comment] 2019-11-01 13:58
@spoenemann I agree - at very least the error should be better. I'll see what we can do.
