### ISSUE TITLE
@FormParam OpenAPI not displayed properly in Resteasy Reactive

### ISSUE THREAD

**Issue by abuelgasimsaadeldin** [quarkusio/quarkus#26461] opened 2022-06-30 06:51 UTC
### Describe the bug

Enquiry regarding the request dto, previously before migrating to resteasy reactive I used to have the ```@FormParam``` annotation providing the ```KEY``` value for the request and ```String variable``` for the variable initialization, however I noticed that now the ```KEY``` value is using the variable name if that makes sense.

For example:
```
    @FormParam("destination_country")
    @PartType(MediaType.TEXT_PLAIN)
    private String destinationCountry;
```

and in Swagger instead of setting the ```KEY``` to ```"destination_country"``` (which is required) it instead uses ```"desinationCountry"``` which gives out errors so I had to initialize my variables with ```String destination_country``` which I believe is not common practice and instead should be using camelCase, hence your input in this is highly appreciated. Thanks.

### Expected behavior

**Expected behavior swagger UI when setting ```@FormParam("destination_country")``` and String destinationCountry:**:**
![image](https://user-images.githubusercontent.com/68045710/176610747-81fea5a2-9e7f-4181-9c4b-0cf62994fca2.png)

### Actual behavior

**Actual behavior swagger UI when setting ```@FormParam("destination_country")``` and String destinationCountry:**
![image](https://user-images.githubusercontent.com/68045710/176610504-8dc27be4-ed76-4a39-9423-990bd6462513.png)

### How to Reproduce?

**CountryRequst.java** (dto):
```
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CountryRequest {
    @NotNull(message = "destination country is required")
    @NotBlank(message = "destination country cannot be blank")
    @FormParam("destination_country")
    @PartType(MediaType.TEXT_PLAIN)
    private String destinationCountry;
```

**CountryResource.java** (resource):
```
@Path("/api/v1/country")
@Tag(name = "Country", description = "Countryendpoints")
public class CountryResource {

@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
@Produces(MediaType.APPLICATION_JSON)
@Transactional
public Response getRate(@Valid @MultipartForm CountryRequest countryRequest) {
CountryResponse countryResponse = new CountryResponse();

double rate = logisticService.getCountryRate(countryRequest);  // Some service to get the rate for a country
countryResponse.rate = rate;

return Response.ok(new Base(countryResponse,true, "successful")).build();
}
```

**Comment by geoand** [comment] 2022-06-30 06:57
@phillip-kruger do we have special RESTEasy Reactive support in our OpenAPI integration?

**Comment by phillip-kruger** [comment] 2022-06-30 07:09
Not really no, the normal JAX-RS module works for both. Is this issue Reactive specific ?

**Comment by phillip-kruger** [comment] 2022-06-30 07:10
Ok I read the issue again, seems like this used to work in the Non-reactive way. So this must be a bug

**Comment by geoand** [comment] 2022-06-30 07:10
Yeah, because it's about our Multipart support. Essentially Multipart objects are just POJOs, very similar actually to `@BeanParam`

**Comment by phillip-kruger** [comment] 2022-06-30 07:11
@abuelgasimsaadeldin - do you have a small reproducer ? @MikeEdgar any comments ?

**Comment by abuelgasimsaadeldin** [comment] 2022-06-30 07:36
@phillip-kruger, yes sure 

**CountryRequst.java** (dto):
```
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
public class CountryRequest {
    @NotNull(message = "destination country is required")
    @NotBlank(message = "destination country cannot be blank")
    @FormParam("destination_country")
    @PartType(MediaType.TEXT_PLAIN)
    private String destinationCountry;
```

**CountryResource.java** (resource):
```
@Path("/api/v1/country")
@Tag(name = "Country", description = "Countryendpoints")
public class CountryResource {

@POST
@Consumes(MediaType.MULTIPART_FORM_DATA)
@Produces(MediaType.APPLICATION_JSON)
@Transactional
public double getRate(@Valid @MultipartForm CountryRequest countryRequest) {

double rate = logisticService.getCountryRate(countryRequest);  // Some service to get the rate for a country

return rate
}
```

**Expected swagger UI**:
![image](https://user-images.githubusercontent.com/68045710/176610747-81fea5a2-9e7f-4181-9c4b-0cf62994fca2.png)

**Comment by MikeEdgar** [comment] 2022-07-10 11:33
I'm looking into this in https://github.com/smallrye/smallrye-open-api/issues/1173, please feel free to assign to me.

**Comment by geoand** [comment] 2022-07-10 11:45
Thanks, done

**Closed** 2022-07-21 07:54 UTC
Labels: kind/bug, area/openapi, area/resteasy-reactive

**Comment by abuelgasimsaadeldin** [comment] 2022-07-21 09:21
@gsmet @MikeEdgar 

Hi there, I see that this issue has already been resolved, may I know what changes are needed in the pom.xml (if any) to be able to get the expected behavior? Thanks!

**Comment by MikeEdgar** [comment] 2022-07-22 01:02
@abuelgasimsaadeldin - prior to the release of Quarkus 2.12, you can add the following to the `<dependencyManagement>` section of you pom.xml. Bure sure to remove it when you do upgrade, or you risk using an outdated version of the OpenAPI library in the future.
```xml
<dependency>
    <groupId>io.smallrye</groupId>
    <artifactId>smallrye-open-api</artifactId>
    <version>2.1.23</version>
</dependency>
```

**Comment by abuelgasimsaadeldin** [comment] 2022-07-22 02:34
Hi @MikeEdgar, I see, thanks for the response, I've just tried adding the following smallrye-open-api dependency to my pom.xml, however my problem still persists (not sure if I'm doing something wrong) as for the Quarkus version, I am currently using version ```2.10.0.Final``` and searching in the maven central repository it seems like ```2.10.2.Final``` (again I could be wrong). 

Your input is highly appreciated. Thanks again!

**Comment by MikeEdgar** [comment] 2022-07-22 11:58
@abuelgasimsaadeldin , sorry I gave you the wrong dependency. If this doesn't work, you may need to tinker with the quarkus-maven-plugin's dependencies. @phillip-kruger - what's the best way to managed the version of the JAX-RS OpenAPI extension being used?
```xml
<dependency>
    <groupId>io.smallrye</groupId>
    <artifactId>smallrye-open-api-core</artifactId>
    <version>2.1.23</version>
</dependency>
```
