### ISSUE TITLE
Frequent Hitting "org.hibernate.exception.GenericJDBCException: Unable to release JDBC Connection" on MariaDB 10.3

### ISSUE THREAD

**Issue by wargun02** [quarkusio/quarkus#3382] opened 2019-07-31 09:08 UTC
Hi there, I keep getting "Unable to release JDBC Connection" exception while running quarkus against MariaDB:
```
org.hibernate.exception.GenericJDBCException: Unable to release JDBC Connection: javax.persistence.PersistenceException: org.hibernate.exception.GenericJDBCException: Unable to release JDBC Connection
```

This happens in a very unpredictable frequency.

The JDBC url is already with autoReconnect Parameter, and here are the application.properties entries which I am using for development (I'm keeping the min and max connection very low):
```
quarkus.hibernate-orm.dialect=org.hibernate.dialect.MariaDB103Dialect
quarkus.hibernate-orm.dialect.storage-engine=InnoDB
quarkus.hibernate-orm.database.charset=utf8

%dev.quarkus.datasource.url=jdbc:mariadb://localhost:3306/whatever?autoReconnect=true
%dev.quarkus.datasource.driver=org.mariadb.jdbc.Driver
%dev.quarkus.datasource.username=username
%dev.quarkus.datasource.password=password
%dev.quarkus.datasource.min-size=5
%dev.quarkus.datasource.max-size=15
%dev.quarkus.datasource.background-validation-interval=PT5S
%dev.quarkus.datasource.leak-detection-interval=PT5S
%dev.quarkus.datasource.idle-removal-interval=PT60S
%dev.quarkus.hibernate-orm.query.query-plan-cache-max-size=20
%dev.quarkus.hibernate-orm.jdbc.statement-batch-size=5
%dev.quarkus.hibernate-orm.jdbc.statement-fetch-size=5
```

I have checked on the MariaDB instance's my.cnf and here are the important extract:
```
max_connections         = 100
connect_timeout         = 5
wait_timeout            = 600
max_allowed_packet      = 16M
thread_cache_size       = 128
sort_buffer_size        = 4M
bulk_insert_buffer_size = 16M
tmp_table_size          = 32M
max_heap_table_size     = 32M
myisam_recover_options = BACKUP
key_buffer_size         = 128M
#open-files-limit       = 2000
table_open_cache        = 400
myisam_sort_buffer_size = 512M
concurrent_insert       = 2
read_buffer_size        = 2M
read_rnd_buffer_size    = 1M
query_cache_limit       = 128K
query_cache_size        = 64M
default_storage_engine  = InnoDB
innodb_buffer_pool_size = 256M
innodb_log_buffer_size  = 8M
innodb_file_per_table   = 1
innodb_open_files       = 400
innodb_io_capacity      = 400
innodb_flush_method     = O_DIRECT
```

I have tried connecting to MariaDb with minimal quarkus.datasource settings (just the url, username and password). But still...

### The environment which I'm running on:
Quarkus Version: 0.19.1
MariaDB: Ver 15.1 Distrib 10.3.14-MariaDB
JAVA: openjdk version "11.0.4" 2019-07-16 LTS
OpenJDK Runtime Environment Zulu11.33+15-CA (build 11.0.4+11-LTS)
OpenJDK 64-Bit Server VM Zulu11.33+15-CA (build 11.0.4+11-LTS, mixed mode)

**Comment by wargun02** [comment] 2019-07-31 15:28
Looking at the exception stack, I found something right at the bottom, which I think might help the diagnostics:

```
Caused by: java.sql.SQLException: Connection.clearWarnings cannot be called on a closed connection
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getSqlException(ExceptionMapper.java:277)
	at org.mariadb.jdbc.MariaDbConnection.clearWarnings(MariaDbConnection.java:1037)
	at io.agroal.pool.ConnectionHandler.resetConnection(ConnectionHandler.java:132)
	at io.agroal.pool.ConnectionPool.returnConnectionHandler(ConnectionPool.java:282)
	at io.agroal.pool.ConnectionHandler.onConnectionWrapperClose(ConnectionHandler.java:97)
	at io.agroal.pool.wrapper.ConnectionWrapper.close(ConnectionWrapper.java:128)
	at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.closeConnection(DatasourceConnectionProviderImpl.java:127)
	at org.hibernate.internal.NonContextualJdbcConnectionAccess.releaseConnection(NonContextualJdbcConnectionAccess.java:46)
	at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.releaseConnection(LogicalConnectionManagedImpl.java:196)
	... 88 more
```

**Comment by Sanne** [comment] 2019-07-31 20:27
Very interesting, thanks for reporting.

We'll need to figure out a way to craft a simple reproducer... any suggestion?

**Comment by wargun02** [comment] 2019-08-01 05:29
My work is usually around:
- Entity classes which extends PanacheEntityBase
- Query classes which implements PanacheRepositoryBase and is annotated with @ApplicationScope (only for querying, no transaction or persists)
- Process classes which will usually @Inject query classes and EntityManager. Annotated with @ApplicationScope
- All end-points are of JAX-RS with @Path, @GET, @POST, etc. It is the REST resource classes where the query classes and the process classes are injected. TransactionManager is injected as well. In some end-point methods, the transaction manager will have .setRollbackOnly() if any exception is captured (only if the process requires transaction).

Usually my webapp will have multiple calls to the quarkus JAX-RS end-point at the load of certain page. The quarkus server will be idle of course when the user fills in the data on the page.

** Perhaps a multiple "GET" with database access and wait/pause for say 5 minutes and do a multiple "GET" again to see if the exception is thrown before or after.

That's all I can suggest, because this issue is quite unpredictable.

Here's a list of the maven dependencies which I have:
```
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-resteasy-jsonb</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-smallrye-rest-client</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-agroal</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-narayana-jta</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-validator</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-hibernate-orm-panache</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-jdbc-mariadb</artifactId>
</dependency>
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-vertx</artifactId>
</dependency>
```

**Comment by emmanuelbernard** [comment] 2019-08-01 12:32
@barreiro said he had an idea, will look at it next week

**Comment by barreiro** [comment] 2019-08-14 14:26
I have push a fix to remove unnecessary calls to ```Connection.clearWarnings()``` in Agroal.

**Comment by kdkanishka** [comment] 2019-10-05 19:55
I am also experiencing the same problem in a random manner.

my datasource config.
quarkus.datasource.initial-size=1
quarkus.datasource.max-size=20

It seems to be the problem is caused by

`: java.sql.SQLException: Connection.clearWarnings cannot be called on a closed connection
`

**Comment by barreiro** [comment] 2019-10-05 22:08
Hi @kdkanishka. Do you mind trying out the latest from master ??? This should have been addressed by #4282

**Comment by kdkanishka** [comment] 2019-10-06 10:57
@barreiro Thanks a lot ! I'll give a try.

**Comment by Sanne** [comment] 2019-10-28 16:34
@kdkanishka  @wargun02 did anyone try the recent fixes?

Please let us know if this was resolved, as we didn't have a way to reproduce this.

**Comment by kdkanishka** [comment] 2019-10-29 03:53
@Sanne 
Tried the fix. It seems that the problem is solved now.

**Comment by wargun02** [comment] 2019-10-29 04:57
@Sanne, thanks for the follow up. I'm on another project. If @kdkanishka has got no issues, then we can close this issue for now. I'll re-open it if I encounter this issue again in future.

**Closed** 2019-10-29 04:57 UTC
Labels: bug, component:persistence

**Comment by Sanne** [comment] 2019-10-29 09:58
great, thanks all!
