### ISSUE TITLE
Using parameterized record as GraphQL query argument makes query always fail validation

### ISSUE THREAD

**Issue by rrrakyah** [quarkusio/quarkus#33223] opened 2023-05-09 12:38 UTC
### Describe the bug

While trying to make a GraphQL API for a project, I've come to encounter what appears to be a regression as of Quarkus 3.0.0.Final.

Using a parameterized record as an argument within a query method makes my query fail, no matter what I try or do. However, this problem is *not* reproducable in Quarkus versions 2.x.x, as far as I could find. 

Versions I have tried so far:

- 2.10.2.Final - Works as intended
- 2.16.7.Final - Works as intended
- 3.0.1.Final - Does not work as intended
- 3.0.2.Final - Does not work as intended

### Expected behavior

Be able to query with a parameterized record within my query and get back expected results

### Actual behavior

Query fails with error `ValidationError` and message `argument 'argument' with value 'StringValue{value='{\n    \"variable\": \"test\"\n}'}' is not a valid 'Unknown Scalar Type [org.rrrakyah.ExampleRecord]'`

### How to Reproduce?

Steps to reproduce:

1. Create new Quarkus project with extension `quarkus-smallrye-graphql`
2. Add parameterized record, with a variable of type parameter, e.g.:
```
package org.rrrakyah;

public record ExampleRecord<T>(T variable) {
}
```
3. Create query with an argument of type parameterized record, e.g.:
```
package org.rrrakyah;

import org.eclipse.microprofile.graphql.Description;
import org.eclipse.microprofile.graphql.GraphQLApi;
import org.eclipse.microprofile.graphql.Query;

@GraphQLApi
public class HelloGraphQLResource {

    @Query
    @Description("Say hello")
    public String sayHello(ExampleRecord<String> argument) {
        return "Hello " + argument.variable();
    }

}
```
4. Try to query, e.g.:
```
query sayHello {
  sayHello(
    argument: {
      variable: "test"
    }
  )
}
```
5. Find that your query failed with a `ValidationError`
```
{
  "errors": [
    {
      "message": "argument 'argument' with value 'StringValue{value='{\n    \"variable\": \"test\"\n}'}' is not a valid 'Unknown Scalar Type [org.rrrakyah.ExampleRecord]'",
      "locations": [
        {
          "line": 4,
          "column": 5
        }
      ],
      "extensions": {
        "classification": "ValidationError"
      }
    }
  ],
  "data": {
    "sayHello": null
  }
}
```

### Output of `java -version`

openjdk version "17.0.4.1" 2022-08-12 LTS

### Quarkus version or git rev

3.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by jmartisk** [comment] 2023-05-09 12:52
This looks very similar to https://github.com/smallrye/smallrye-graphql/issues/1819 where we assume it is caused by a bug in Yasson: https://github.com/eclipse-ee4j/yasson/issues/599, we're waiting for Yasson maintainers to check it. There was an upgrade from Yasson 1 to 3 between Quarkus 2.16 and 3/.0.

**Comment by robp94** [comment] 2023-05-16 12:42
@rrrakyah possible workaround https://github.com/smallrye/smallrye-graphql/issues/1819

**Comment by gsmet** [comment] 2024-08-24 12:40
I will close this one as this is an upstream issue and there's nothing we can do about it.

**Closed by gsmet** 2024-08-24 12:40 UTC
Labels: kind/bug, area/smallrye, area/graphql
