### ISSUE TITLE
Support autodetect-bearer-only with OIDC

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#5899] opened 2019-12-01 14:14 UTC
Credentials support has removed from the JavaScript adapter in Keycloak 8.0.0. 
If we  set client " Access Type" with public ,Only user name and password are needed to get token：

```
curl -X POST http://localhost:8080/auth/realms/quarkus/protocol/openid-connect/token   -H 'content-type: application/x-www-form-urlencoded'   -d 'username=alice&password=alice&grant_type=password&client_id=basedata2'

```
The problem is that quarkus currently does not support  autodetect-bearer-only with Keycloak.

**Comment by sberyozkin** [comment] 2019-12-03 11:44
Hi Stian @stianst, Pedro @pedroigor, right now we have either a `service` or `web-app` application types which are exclusive. I believe @yuhaibohotmail  is asking to have both of these application types supported at the same time, i.e, the adapter checks for some headers and tries to figure out whether to redirect or just respond with 401. Is it correct ?
If yes then I propose to have a `hybrid` application type introduced which will be documented to combine both the `service` and `web-app` types. `autodect-bearer-token` sounds more like an  action. 
Few more options: `service-and-web-app` (may be this one is better, as `hybrid` may also mean an OIDC code flow), `all`.
So I'd go for either `service-and-web-app` (or `web-app-and-service`) or `hybrid`

What do you think ?

**Comment by stianst** [comment] 2019-12-03 13:27
I'm not 100% sure about this one for several reasons:

* Quarkus is a micro-service framework and in general it doesn't make that much sense to have a web-app and a REST service in the same does it?
* Ideally you should have different client for the web-app and the service, not re-use the same client for both use-cases
* The auto-detect based on headers was always a bit hacky - would be better to do it on context-path.

So perhaps the solution is recommend not writing a fat-app on Quarkus? If someone really wants to then the solution could be the multi-tenancy support. I.e. "/web-app/*" uses one config, and "/rest/*" uses another config.

**Comment by sberyozkin** [comment] 2019-12-03 16:28
@stianst thanks, it would be cleaner indeed to have a path segment specific configuration.
@yuhaibohotmail how do you have it set up in your case ?

**Comment by yuhaibohotmail** [comment] 2019-12-04 00:03
@stianst @sberyozkin thanks.

1. My legacy system is deployed in wildfly  using keyclock adapter ，it use the following configuration:
```
{ ...
  "autodetect-bearer-only":true,
  ...
}
```
"Keycloak auto-detects SOAP or REST clients based on typical headers like X-Requested-With, SOAPAction or Accept."
So the easiest way to migrate is for quarkus to support autodetect bear.

2. 
 I agree it's not a good idea that auto-detect based on headers. If the solution is based on a path segment specific configuration，I like the following way:
```
quarkus.oidc.bearer-only-path = /path
```


> I'm not 100% sure about this one for several reasons:
> 
> * Quarkus is a micro-service framework and in general it doesn't make that much sense to have a web-app and a REST service in the same does it?

 I agree with you! 

> * Ideally you should have different client for the web-app and the service, not re-use the same client for both use-cases

But in some simple cases, deploying a single program is a simpler solution. I'm not talking about the microservice scenario.

> * The auto-detect based on headers was always a bit hacky - would be better to do it on context-path.
> 
> So perhaps the solution is recommend not writing a fat-app on Quarkus? If someone really wants to then the solution could be the multi-tenancy support. I.e. "/web-app/_" uses one config, and "/rest/_" uses another config.

I can accept  multi-tenancy solution，it will solve my problem.

**Comment by stianst** [comment] 2019-12-04 08:18
I'd say the ideal here then is to have this as a requirement for the multi-tenancy solution. Ideally the multi-tenancy solution should allow having multiple configs, and allow selecting the right config in an easy way (based on path or headers).

**Comment by sberyozkin** [comment] 2019-12-04 11:09
@stianst @yuhaibohotmail thanks
@yuhaibohotmail would you be OK then if I close this issue as a duplicate of #4448 (multi-tenancy support) ?

**Comment by yuhaibohotmail** [comment] 2019-12-04 11:13
@sberyozkin  OK！ thanks！

**Comment by sberyozkin** [comment] 2019-12-04 14:41
@yuhaibohotmail thanks, please watch #4448 :-)

**Closed** 2019-12-04 14:42 UTC
Labels: component:oidc, enhancement
