### ISSUE TITLE
Java 11/Gradle - NullPointerException on build Reactive Messaging

### ISSUE THREAD

**Issue by collin-sullivan** [quarkusio/quarkus#4767] opened 2019-10-22 15:52 UTC
NullPointerException is thrown at build time when using `@Incoming` or `@Outgoing` method annotations from quarkus-smallrye-reactive-messaging on Java 11.  Build completes successfully on java 1.8 or if I remove the  `@Incoming` or `@Outgoing` method annotations when using Java 11.

Last Quarkus Version it worked:
- 0.23.2

Quarkus Versions this is broken:
- 0.24.0
- 0.25.0
- 0.26.0

Sample Code:
```java
    @Incoming("requests")
    @Outgoing("responses")
    @Broadcast
    public String test() {
        return "test";
    }
```

Properties:
```properties
amqp-username=quarkus
amqp-password=quarkus


mp.messaging.incoming.requests.connector=smallrye-amqp
mp.messaging.incoming.requests.address=request
mp.messaging.incoming.requests.durable=true
mp.messaging.incoming.requests.port=5672

mp.messaging.outgoing.responses.connector=smallrye-amqp
mp.messaging.outgoing.responses.address=result
mp.messaging.outgoing.responses.durable=true
mp.messaging.outgoing.responses.broadcast=true
mp.messaging.outgoing.responses.port=5672
```

Stack Trace:
```java
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':quarkusBuild'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:156)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:108)
        at org.gradle.api.internal.tasks.execution.ResolveBeforeExecutionOutputsTaskExecuter.execute(ResolveBeforeExecutionOutputsTaskExecuter.java:67)
        at org.gradle.api.internal.tasks.execution.ResolveAfterPreviousExecutionStateTaskExecuter.execute(ResolveAfterPreviousExecutionStateTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:94)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:56)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:416)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$CallableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:406)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:102)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.call(DelegatingBuildOperationExecutor.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:355)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:343)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:336)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:322)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:134)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker$1.execute(DefaultPlanExecutor.java:129)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:202)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:193)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:129)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: org.gradle.api.GradleException: Failed to build a runnable JAR
        at io.quarkus.gradle.tasks.QuarkusBuild.buildQuarkus(QuarkusBuild.java:172)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:49)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:42)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:28)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:717)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:684)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$5.run(ExecuteActionsTaskExecuter.java:476)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:402)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:394)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$1.execute(DefaultBuildOperationExecutor.java:165)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:250)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:158)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:92)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:461)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:444)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.access$200(ExecuteActionsTaskExecuter.java:93)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$TaskExecution.execute(ExecuteActionsTaskExecuter.java:237)
        at org.gradle.internal.execution.steps.ExecuteStep.lambda$execute$1(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:33)
        at org.gradle.internal.execution.steps.ExecuteStep.execute(ExecuteStep.java:26)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:58)
        at org.gradle.internal.execution.steps.CleanupOutputsStep.execute(CleanupOutputsStep.java:35)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:48)
        at org.gradle.internal.execution.steps.ResolveInputChangesStep.execute(ResolveInputChangesStep.java:33)
        at org.gradle.internal.execution.steps.CancelExecutionStep.execute(CancelExecutionStep.java:39)
        at org.gradle.internal.execution.steps.TimeoutStep.executeWithoutTimeout(TimeoutStep.java:73)
        at org.gradle.internal.execution.steps.TimeoutStep.execute(TimeoutStep.java:54)
        at org.gradle.internal.execution.steps.CatchExceptionStep.execute(CatchExceptionStep.java:35)
        at org.gradle.internal.execution.steps.CreateOutputsStep.execute(CreateOutputsStep.java:51)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:45)
        at org.gradle.internal.execution.steps.SnapshotOutputsStep.execute(SnapshotOutputsStep.java:31)
        at org.gradle.internal.execution.steps.CacheStep.executeWithoutCache(CacheStep.java:208)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:70)
        at org.gradle.internal.execution.steps.CacheStep.execute(CacheStep.java:45)
        at org.gradle.internal.execution.steps.BroadcastChangingOutputsStep.execute(BroadcastChangingOutputsStep.java:49)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:43)
        at org.gradle.internal.execution.steps.StoreSnapshotsStep.execute(StoreSnapshotsStep.java:32)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:38)
        at org.gradle.internal.execution.steps.RecordOutputsStep.execute(RecordOutputsStep.java:24)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.executeBecause(SkipUpToDateStep.java:96)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.lambda$execute$0(SkipUpToDateStep.java:89)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:54)
        at org.gradle.internal.execution.steps.SkipUpToDateStep.execute(SkipUpToDateStep.java:38)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:76)
        at org.gradle.internal.execution.steps.ResolveChangesStep.execute(ResolveChangesStep.java:37)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:36)
        at org.gradle.internal.execution.steps.legacy.MarkSnapshottingInputsFinishedStep.execute(MarkSnapshottingInputsFinishedStep.java:26)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:90)
        at org.gradle.internal.execution.steps.ResolveCachingStateStep.execute(ResolveCachingStateStep.java:48)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:69)
        at org.gradle.internal.execution.steps.CaptureStateBeforeExecutionStep.execute(CaptureStateBeforeExecutionStep.java:47)
        at org.gradle.internal.execution.impl.DefaultWorkExecutor.execute(DefaultWorkExecutor.java:33)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:140)
        ... 34 more
Caused by: io.quarkus.creator.AppCreatorException: Failed to augment application classes
        at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:191)
        at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:49)
        at io.quarkus.creator.CuratedApplicationCreator.runTask(CuratedApplicationCreator.java:139)
        at io.quarkus.gradle.tasks.QuarkusBuild.buildQuarkus(QuarkusBuild.java:169)
        ... 91 more
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor#build threw an exception: java.lang.NullPointerException
        at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1654)
        at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:760)
        at io.smallrye.reactive.messaging.MediatorConfigurationSupport.isPublisherOrPublisherBuilder(MediatorConfigurationSupport.java:51)
        at io.smallrye.reactive.messaging.MediatorConfigurationSupport.determineShape(MediatorConfigurationSupport.java:37)
        at io.quarkus.smallrye.reactivemessaging.deployment.QuarkusMediatorConfigurationUtil.create(QuarkusMediatorConfigurationUtil.java:64)
        at io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor.build(SmallRyeReactiveMessagingProcessor.java:234)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:940)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

        at io.quarkus.builder.Execution.run(Execution.java:108)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:121)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:130)
        at io.quarkus.creator.phase.augment.AugmentTask.run(AugmentTask.java:182)
        ... 94 more
Caused by: java.lang.NullPointerException
        at org.apache.commons.lang3.SystemUtils.isJavaVersionAtLeast(SystemUtils.java:1654)
        at org.apache.commons.lang3.ClassUtils.isAssignable(ClassUtils.java:760)
        at io.smallrye.reactive.messaging.MediatorConfigurationSupport.isPublisherOrPublisherBuilder(MediatorConfigurationSupport.java:51)
        at io.smallrye.reactive.messaging.MediatorConfigurationSupport.determineShape(MediatorConfigurationSupport.java:37)
        at io.quarkus.smallrye.reactivemessaging.deployment.QuarkusMediatorConfigurationUtil.create(QuarkusMediatorConfigurationUtil.java:64)
        at io.quarkus.smallrye.reactivemessaging.deployment.SmallRyeReactiveMessagingProcessor.build(SmallRyeReactiveMessagingProcessor.java:234)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at io.quarkus.deployment.ExtensionLoader$1.execute(ExtensionLoader.java:940)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:415)
        at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
        at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)

```

**Comment by gsmet** [comment] 2019-10-22 16:04
Oh, yes, the `commons-lang3` version parsing being all broken. Classic.

@jmartisk you were the one working on this, no? Could you see if we can add a proper test and try if `commons-lang3` 3.9 fixes the issue? If not, we should go away from it forever.

**Comment by geoand** [comment] 2019-10-22 16:09
@cescoffier works on this in general but I done some work on it as well

**Comment by geoand** [comment] 2019-10-22 20:27
After talking about this extensively it looks like it might be due the build classpath being set incorrectly (this only happens for Gradle).
@aloubyansky agreed to take a look

**Comment by geoand** [comment] 2019-10-24 19:47
So the plot thickens around this... The boostrap work that reads the user dependencies reads the correct version of commons-lang3!
However it seems like the wrong version is loaded from one of the Gradle classloaders...

**Comment by jaikiran** [comment] 2019-10-25 13:14
> However it seems like the wrong version is loaded from one of the Gradle classloaders...

It's probably is the same or similar to this issue https://github.com/quarkusio/quarkus/issues/3917#issuecomment-533882132. In that example, I can see that (at that time) `org.apache.commons:commons-lang3:3.5` was being pulled in. I guess, if you run that command referenced in that comment against this reproducible app, you will probably see something similar.

**Comment by geoand** [comment] 2019-10-25 13:16
Yeah, I have prototyped a (far from ideal) fix for this and will open a PR over the weekend.

**Closed** 2019-10-30 06:25 UTC
Labels: bug

**Comment by tsfullman** [comment] 2020-01-24 19:11
Getting this same error again after upgrading to 1.2.0.Final. Also occurs on 1.2.0.CR1

Last time it worked was 1.1.1.Final

**Comment by geoand** [comment] 2020-01-24 19:51
Would you be willing to try out master? It's highly likely that it's already fixed there

**Comment by acoburn** [comment] 2020-01-27 19:02
I have encountered this same issue with 1.2.0.Final (using gradle 6). I tried building the current master branch of quarkus and using that, but I the same error manifests itself.

I did, however, find that the gradle extension has a transitive dependency on commons-lang3 version 3.5, via a number of different maven tools. If I add the following line to `./devtools/gradle/build.gradle`:

    implementation "org.apache.commons:commons-lang3:3.9"

and then install that locally, then my own application will build properly with gradle under Java 11.

Alternatively, it seems that it might be cleaner to apply this change to the `quarkus-bootstrap-core` project (`independent-projects/bootstrap/core/pom.xml`) where the commons-lang3 dependency version is already managed, i.e.:

    <dependency>
        <groupId>org.apache.commons</groupId>
        <artifactId>commons-lang3</artifactId>
    </dependency>

If that seems like a reasonable solution (I am thinking here of the second option), I can supply a PR.

**Comment by geoand** [comment] 2020-01-27 19:44
@acoburn can you attach a reproducer using Quarkus master please?

**Comment by acoburn** [comment] 2020-01-28 16:35
In attempting to create a minimal reproducer, I found that the issue seems to have been caused by an interaction with an unrelated gradle plugin. Upgrading that plugin seemed to resolve the issue, so I don't think anything needs to be changed on the quarkus side.

**Comment by geoand** [comment] 2020-01-28 16:38
OK, thanks a lot!

**Comment by zeldanerd24** [comment] 2020-01-30 21:25
I disagree in part with @acoburn's assertion. I was able to create a minimal reproducer for the problem in question using `1.2.0.Final`, with a very similar stacktrace when running `./gradlew quarkusBuild`. I am currently in the process of doing a master build to see if the issue is fixed there.

**Comment by zeldanerd24** [comment] 2020-01-31 12:12
Looks like the issue was fixed in master at some point since the `1.2.0.Final` release. @geoand: Do you know if there plans to introduce more integration testing on the Gradle side at some point to prevent this from resurfacing in the future?

**Comment by geoand** [comment] 2020-01-31 12:14
Thanks for checking @zeldanerd24 

I'll deflect the integration test question to @gastaldi :P

**Comment by gastaldi** [comment] 2020-01-31 12:16
@zeldanerd24 no plans so far, but feel free to submit a PR and I'll be thrilled to review it :wink:

**Comment by MartinX3** [comment] 2020-02-11 11:07
Sadly the issue is not fixed in 1.3.0.Alpha1
Is it possible to create an Alpha2 release? :)

**Comment by geoand** [comment] 2020-02-11 11:13
@MartinX3 do have a reproducer?

**Comment by MartinX3** [comment] 2020-02-11 11:17
Oh I thought since @zeldanerd24 it is fixed in master that Alpha1 just doesn't contain the newest fixes.
@geoand I will try if I am be able to run quarkus master on my local machine with this manual https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md to create a producer :)

**Comment by MartinX3** [comment] 2020-02-11 13:27
Sadly `./mvnw clean install` fails with `INFO] Quarkus - Agroal - Deployment ...................... FAILURE [ 13.326 s]` and I also miss a documentation to create a producer.

**Comment by geoand** [comment] 2020-02-11 13:30
Does `./mvnw -e clean install` give any more information?

**Comment by MartinX3** [comment] 2020-02-11 16:01
Oh yes, sorry
Thought you was already aware
Here is the log :D
[build.log](https://github.com/quarkusio/quarkus/files/4186656/build.log)

**Comment by geoand** [comment] 2020-02-11 16:04
You can always just do `./mvnw clean install -DskipTests` to skip all the tests

**Comment by MartinX3** [comment] 2020-02-11 16:08
Oh yes, thank you :)
I just thought something is broken on master and stopped testing :S

**Comment by geoand** [comment] 2020-02-11 16:10
> Oh yes, thank you :)
> I just thought something is broken on master and stopped testing :S

Nah, our CI would have spotted it by now with all the PRs we have and the CI cron jobs that run :)
