### ISSUE TITLE
JMX and Quarkus logging gelf ext not working together

### ISSUE THREAD

**Issue by KMUS** [quarkusio/quarkus#6943] opened 2020-02-02 08:34 UTC
```
-Djava.rmi.server.hostname=127.0.0.1
-Dcom.sun.management.jmxremote
-Dcom.sun.management.jmxremote.ssl=false
-Dcom.sun.management.jmxremote.port=4711
-Dcom.sun.management.jmxremote.rmi.port=4711
-Dcom.sun.management.jmxremote.local.only=false
-Dcom.sun.management.jmxremote.authenticate=false
```
```

 <dependency>
     <groupId>io.quarkus</groupId>
     <artifactId>quarkus-logging-gelf</artifactId>
 </dependency>
```

The Gelf extension will not log anything in Graylog. Removing the JMX settings and the logs will show up again in Graylog. I have tested it with 

> quarkus:dev

 and the 

> runner.jar

 and I always get the same behaviour. The console logs do not show anything about it.

**Comment by gsmet** [comment] 2020-02-02 14:27
@loicmathieu does it ring any bell?

**Comment by loicmathieu** [comment] 2020-02-03 08:55
@KMUS can you give us the content of you `application.properties` file ?

The issue you describe looks like a port conflict, can  you check that the port you use for JMX (4711) is available ? On Linux you can use this type of command : `sudo lsof -i -P -n | grep LISTEN` or just try by using a different port for JMX and see if it makes a difference ...

**Comment by KMUS** [comment] 2020-02-03 18:21
@loicmathieu 

`INFO: Installed features: [agroal, cdi, flyway, hibernate-orm, hibernate-validator, jdbc-postgresql, logging-gelf, narayana-jta, resteasy, resteasy-jackson, scheduler, servlet, undertow-websockets]`

**application.properties**

```
quarkus.datasource.url=jdbc:postgresql://db:5432/foobar
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=foo
quarkus.datasource.password=bar
quarkus.flyway.migrate-at-start=true
quarkus.flyway.baseline-on-migrate=true
quarkus.hibernate-orm.log.sql=false
quarkus.hibernate-orm.jdbc.statement-batch-size=1000
quarkus.http.cors=true
quarkus.log.level=INFO
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=ssl:logs.domain.xyz?keepAlive=true
quarkus.log.handler.gelf.port=8901
quarkus.log.handler.gelf.include-full-mdc=true
quarkus.log.handler.gelf.additional-field.ApplicationName.value=foobar
quarkus.log.handler.gelf.additional-field.ApplicationName.type=String
quarkus.resteasy.gzip.enabled=true
```
```
nc -vz localhost 4711
nc: connect to localhost port 4711 (tcp) failed: Connection refused
```

`export JAVA_TOOL_OPTIONS="-Djava.rmi.server.hostname=127.0.0.1 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=4711 -Dcom.sun.management.jmxremote.rmi.port=4711 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Djavax.net.ssl.keyStore=/home/user/tools/jdk-11/lib/security/cacerts -Djavax.net.ssl.keyStorePassword=changeit"`

`java -jar foo-runner.jar`

```
nc -vz localhost 4711
Connection to localhost 4711 port [tcp/*] succeeded!
```

JDK Mission Control connects to JMX. Graylog does not log anything.

`export JAVA_TOOL_OPTIONS="-Djavax.net.ssl.keyStore=/home/user/tools/jdk-11/lib/security/cacerts -Djavax.net.ssl.keyStorePassword=changeit"`

`java -jar foo-runner.jar`

```
nc -vz localhost 4711
nc: connect to localhost port 4711 (tcp) failed: Connection refused
```

JDK Mission Control does not connect to JMX. Graylog logs as usual.

Changing JMX port from 4711 to 10000 does not solve the problem.

**Comment by loicmathieu** [comment] 2020-02-04 16:23
In fact, the issue is not only on the loggin-gelf extension, the Quarkus logging system seems to have issues when activating remote JMX.

When running the main integration test with remote JMX enabled, the log format is not the same (it's the default format from JUL) as when running with remote JMX disabled;

Step to reproduce:

- Create a package of the main integration test: `mvn clean package`
- Launch it: `java -jar target/quarkus-integration-test-main-999-SNAPSHOT-runner.jar`
- It produces logs of this form
```
2020-02-04 17:16:31,535 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.RecodingSocket for path /recoder
2020-02-04 17:16:31,541 INFO  [io.und.web.jsr] (main) UT026004: Adding annotated client endpoint class io.quarkus.it.websocket.CodingClient
2020-02-04 17:16:31,542 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.EchoSocket for path /echo
2020-02-04 17:16:31,543 INFO  [io.und.web.jsr] (main) UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.WebSocketOpenEndpoint for path /wsopen
2020-02-04 17:16:31,728 WARN  [io.qua.jae.run.JaegerDeploymentRecorder] (main) Jaeger service name has not been defined, either as 'quarkus.jaeger.service-name' application property or JAEGER_SERVICE_NAME environment variable/system property
[...]
```
- Export JMX settings: `export JAVA_TOOL_OPTIONS="-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.port=4711 -Dcom.sun.management.jmxremote.authenticate=false"`
- Launch again the main integration test: `java -jar target/quarkus-integration-test-main-999-SNAPSHOT-runner.jar`
- It produces logs of this form
```
févr. 04, 2020 5:16:43 PM org.hibernate.validator.internal.util.Version <clinit>
INFO: HV000001: Hibernate Validator 1.0
févr. 04, 2020 5:16:44 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: templatePU]
févr. 04, 2020 5:16:44 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate Core {1.0}
févr. 04, 2020 5:16:44 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
févr. 04, 2020 5:16:44 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: org.hibernate.dialect.PostgreSQL95Dialect
févr. 04, 2020 5:16:44 PM io.undertow.websockets.jsr.ServerWebSocketContainer addEndpointInternal
INFO: UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.RecodingSocket for path /recoder
févr. 04, 2020 5:16:44 PM io.undertow.websockets.jsr.ServerWebSocketContainer addEndpointInternal
INFO: UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.EchoSocket for path /echo
févr. 04, 2020 5:16:44 PM io.undertow.websockets.jsr.ServerWebSocketContainer addEndpointInternal
INFO: UT026004: Adding annotated client endpoint class io.quarkus.it.websocket.CodingClient
févr. 04, 2020 5:16:44 PM io.undertow.websockets.jsr.ServerWebSocketContainer addEndpointInternal
INFO: UT026003: Adding annotated server endpoint class io.quarkus.it.websocket.WebSocketOpenEndpoint for path /wsopen
févr. 04, 2020 5:16:44 PM io.quarkus.jaeger.runtime.JaegerDeploymentRecorder isValidConfig
WARN: Jaeger service name has not been defined, either as 'quarkus.jaeger.service-name' application property or JAEGER_SERVICE_NAME environment variable/system property
```

@dmlloyd apparently, there is some issues with the Quarkus logging system and remote JMX. Do you have any ideas on this ?

**Comment by dmlloyd** [comment] 2020-02-04 16:27
We don't actually support remote JMX at all in Quarkus AFAIK.  What are you trying to do?

**Comment by loicmathieu** [comment] 2020-04-02 09:09
Closing it as JMX is not supported and the user that reports it don't reply since the 4th of feb.
@KMUS you can still reopen it if you need support or really think it is an issue.

**Closed by loicmathieu** 2020-04-02 09:09 UTC
Labels: area/logging, kind/bug
