### ISSUE TITLE
Split package warning from core extensions

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#18732] opened 2021-07-15 23:00 UTC
### Describe the bug

The following warning is displayed in the logs when building my Quarkus app using 2.1.0.CR1

```java
2021-07-15 15:16:36,432 WARN  [io.qua.arc.dep.SplitPackageProcessor] (build-19) Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.quarkus.hibernate.orm.panache" found in [io.quarkus:quarkus-hibernate-orm-panache-common, io.quarkus:quarkus-hibernate-orm-panache]
```

### Expected behavior

No warning should be displayed for our core extensions

### Actual behavior

Warning is displayed

### How to Reproduce?

Build the panache quickstart with 2.1.0.CR1

### Output of `uname -a` or `ver`

Fedora 34

### Output of `java -version`

11

### GraalVM version (if different from Java)

21

### Quarkus version or git rev

2.1.0.CR1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

### Additional information

This was first seen in https://github.com/quarkusio/quarkus/pull/18617#issuecomment-879740342

**Comment by gsmet** [comment] 2021-07-16 09:51
There are more problems than just this one unfortunately.

Here is the list:

> "io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-policy]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-extensions]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-apps, io.fabric8:openshift-model, io.fabric8:openshift-model-operator, io.fabric8:openshift-model-monitoring, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-discovery, io.fabric8:openshift-model-clusterautoscaling, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-extensions, io.fabric8:openshift-model-storageversionmigrator, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-coordination, io.fabric8:openshift-model-tuned, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-certificates, io.fabric8:openshift-model-machine, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-rbac, io.fabric8:openshift-model-console, io.fabric8:openshift-model-machineconfig, io.fabric8:kubernetes-model-core, io.fabric8:openshift-model-operatorhub, io.fabric8:kubernetes-model-scheduling, io.fabric8:openshift-model-whereabouts, io.fabric8:openshift-model-miscellaneous]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-apiextensions]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-flowcontrol]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-networking]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-flowcontrol]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-networking]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-networking]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-scheduling]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-metrics]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-certificates]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-scheduling]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-scheduling, io.fabric8:openshift-model-console, io.fabric8:kubernetes-model-certificates, io.fabric8:openshift-model-operator, io.fabric8:openshift-model-operatorhub, io.fabric8:openshift-model-whereabouts, io.fabric8:openshift-model-machine, io.fabric8:openshift-model-monitoring, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-apiextensions, io.fabric8:openshift-model-tuned, io.fabric8:kubernetes-model-batch, io.fabric8:openshift-model, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-node, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-networking, io.fabric8:openshift-model-miscellaneous, io.fabric8:openshift-model-storageversionmigrator, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-discovery, io.fabric8:openshift-model-clusterautoscaling, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-autoscaling, io.fabric8:openshift-model-machineconfig, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-storageclass]
"io.fabric8.kubernetes.api.model" found in [io.fabric8:kubernetes-model-rbac, io.fabric8:kubernetes-model-batch, io.fabric8:kubernetes-model-networking, io.fabric8:kubernetes-model-events, io.fabric8:kubernetes-model-autoscaling, io.fabric8:kubernetes-model-flowcontrol, io.fabric8:kubernetes-model-discovery, io.fabric8:kubernetes-model-extensions, io.fabric8:kubernetes-model-coordination, io.fabric8:kubernetes-model-storageclass, io.fabric8:kubernetes-model-apiextensions, io.fabric8:kubernetes-model-certificates, io.fabric8:kubernetes-model-metrics, io.fabric8:kubernetes-model-core, io.fabric8:kubernetes-model-admissionregistration, io.fabric8:kubernetes-model-apps, io.fabric8:kubernetes-model-scheduling, io.fabric8:kubernetes-model-policy, io.fabric8:kubernetes-model-node]
"io.fabric8.openshift.api.model" found in [io.fabric8:openshift-model, io.fabric8:openshift-model-operator]
"io.quarkus.arquillian.test" found in [/home/runner/work/quarkus/quarkus/test-framework/arquillian/target/quarkus-arquillian-test14456914113993333186/lib/3c00744b-5421-4757-8795-5f30f04bd855.jar, application classes]

> "io.quarkus.hibernate.orm.panache" found in [io.quarkus:quarkus-hibernate-orm-panache-common, io.quarkus:quarkus-hibernate-orm-panache]

> "io.quarkus.mongodb.panache" found in [io.quarkus:quarkus-mongodb-panache-common, io.quarkus:quarkus-mongodb-panache]

> "io.quarkus.mongodb.panache.reactive" found in [io.quarkus:quarkus-mongodb-panache-common, io.quarkus:quarkus-mongodb-panache]

> "io.quarkus.mongodb.panache.reactive.runtime" found in [io.quarkus:quarkus-mongodb-panache, io.quarkus:quarkus-mongodb-panache-common]

> "io.quarkus.mongodb.panache.runtime" found in [io.quarkus:quarkus-mongodb-panache-common, io.quarkus:quarkus-mongodb-panache]

> "io.quarkus.registry" found in [application classes, io.quarkus:quarkus-devtools-registry-client]

**Comment by FroMage** [comment] 2021-07-27 09:08
So, @loicmathieu you fixed the mongodb issues, but not `io.quarkus.hibernate.orm.panache` right?

**Comment by loicmathieu** [comment] 2021-07-27 09:19
@FroMage Guillaume fixed them in Hibernate with Panache.
I think the issue is fixed now as he also add an ignored rules for the k8s client.

@gastaldi can we close this one now thanks to Guillaume's work ?

**Closed** 2021-07-27 12:27 UTC
Labels: area/panache, kind/bug

**Comment by FroMage** [comment] 2021-08-05 09:27
OK great, thanks.
