### ISSUE TITLE
Response.fromResponse bug in reactive version of resteasy libs

### ISSUE THREAD

**Issue by bkalas** [quarkusio/quarkus#41887] opened 2024-07-15 07:09 UTC
### Describe the bug

We switched from resteasy legacy to recomended reactive alternative quarkus-rest, quarkus-rest-jacskon.
After switch we noticed that Response.fromResponse method does not work anymore.
Code in controllers like 
`Response.fromResponse(rcClient.doCall()).build()`
was working for legacy libs and its not correctly working in new libs.
It returns correct status, but payload somehoiw cannot be accessed.

I created reproducer
https://github.com/bkalas/q3-responsebug-reproducer
there are 2 projects 
'reproducer-reactive-not-working'
'reproducer-resteasy-legacy-working'

See in both MainRestController and test for it, in resteasy-legacy test will pass, same test wont pass for rective

### Expected behavior

Bahviour should be same for both libraries

### Output of `java -version`

17

**Comment by gastaldi** [comment] 2024-08-26 15:53
Thanks for the reproducer. This is a duplicate of #25496

**Comment by gastaldi** [comment] 2024-08-26 15:54
Duplicates #25496

**Closed by gastaldi** 2024-08-26 15:53 UTC
Labels: kind/bug, area/resteasy-reactive
