### ISSUE TITLE
Support Constructor Injection in @QuarkusTest

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34619] opened 2023-07-09 01:47 UTC
### Description

Currently I tried to inject beans via constructor like declaring fields in a general Kotlin class, it does not work as expected.

I have tried the following, both are failed.

```kotlin
@QuarkusTest
class MyTest(val posts: PostRepository) {}
```

```kotlin
@QuarkusTest
class MyTest @Inject constructor(val posts: PostRepository) {}
```

### Implementation ideas

I hope it is working like a simple class with constructor injection automaticially. 

```kotlin
@QuarkusTest
class MyTest(val posts: PostRepository) {}
```

**Comment by geoand** [comment] 2023-07-10 06:28
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/34330

**Closed by geoand** 2023-07-10 06:28 UTC
Labels: kind/enhancement, area/testing
