### ISSUE TITLE
CDI IllegalAccessError when accessing injected bean

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#7735] opened 2020-03-10 14:23 UTC
**Describe the bug**
1. I have the following setup (gradle, Quarkus 1.2.1.Final as well as 1.3.0.CR2): `ExampleResource` injects `BeanA` injects `InnerBeanA`. When I run the following code in the `ExampleResource`, I get the results noted in the comments:

```
System.out.println("InnerBeanA: " + beanA.getInnerBeanA());  // works; prints the object id of an InnerBeanA
System.out.println("InnerBeanA: " + beanA.innerBeanA); // beanA.innerBeanA == null
```

Why are the results different? Both accesses are legal java code and I would expect them to give the exact same results.

2. I extend this example to a multi-project example. In the reproducer I added below, I have two modules. The `library` module is built and published to the local maven repository whenever the `application` project (the quarkus project) is built. So it basically works like it would be with a third party dependency you add to your project (but with more convenience, since it automatically builts the library). 

Now I have `ExampleResource` injects `BeanB` injects `InnerBeanB`. When I run the following code in the `ExampleResource`, I get the results noted in the comments:

```
System.out.println("InnerBeanB: " + beanB.getInnerBeanB());  // works; prints the object id of an InnerBeanB
System.out.println("InnerBeanB: " + beanB.innerBeanB); // crashes
```

The exception is:
```
2020-03-10 15:13:29,034 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: d6c45647-6244-4642-ad08-cfd9a98a9181-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: class org.acme.ExampleResource tried to access field org.acme.BeanB.innerBeanB (org.acme.ExampleResource is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @133e019b; org.acme.BeanB is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2a32de6c)
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:216)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:515)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:259)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:160)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:163)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:245)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:122)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:36)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:87)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2027)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1551)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1442)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.IllegalAccessError: class org.acme.ExampleResource tried to access field org.acme.BeanB.innerBeanB (org.acme.ExampleResource is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @133e019b; org.acme.BeanB is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2a32de6c)
	at org.acme.ExampleResource.hello(ExampleResource.java:25)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:167)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:621)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:487)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:437)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:439)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:400)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:374)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:67)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:488)
	... 20 more
```

Why does this behave differently from the first example? And again, I would expect to get the injected bean in both cases. 

I added a reproducer project below showcasing both cases.

**Expected behavior**
I get the injected bean. 

**Actual behavior**
I either get null or a crash.

**To Reproduce**
1. Download reproducer project [cdi-with-library-not-working.zip](https://github.com/quarkusio/quarkus/files/4312790/cdi-with-library-not-working.zip) and unpack it.
2. In the reproducer project, run `./gradlew :application:quarkusDev`
3. Open a browser and go to `localhost:8080/hello`
4. You should see the following logs and the exception shown above in the console output: 
```
InnerBeanA: org.acme.InnerBeanA@518409bb
InnerBeanA: null
InnerBeanB: org.acme.InnerBeanB@4062e5b6
2020-03-10 15:13:29,034 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: d6c45647-6244-4642-ad08-cfd9a98a9181-1: org.jboss.resteasy.spi.UnhandledException: java.lang.IllegalAccessError: class org.acme.ExampleResource tried to access field org.acme.BeanB.innerBeanB (org.acme.ExampleResource is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @133e019b; org.acme.BeanB is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @2a32de6c)
```

**Environment (please complete the following information):**
 - Windows 10
 - Quarkus 1.2.1.Final as well as Quarkus 1.3.0.CR2
 - gradle 6.2

**Comment by geoand** [comment] 2020-03-10 15:13
I am pretty sure this is a duplicate of #7284.

cc @mkouba @manovotn

**Comment by mkouba** [comment] 2020-03-10 15:22
First of all, `SomeBean` is `@ApplicationScoped` and so a client proxy is always injected. However, the client proxy does not save any state but instead delegates all invocations to the underlying contextual instance. In other words, you should _never access fields of a normal scoped bean through its client proxy_. This is a know limitation of CDI proxies.

WRT `IllegalAccessError` - yes, looks like a duplicate of #7284.

**Comment by andreas-eberle** [comment] 2020-03-10 15:27
@mkouba: I would do that, surely. I just stumbled over this while I was trying to build a reproducer for something else and thought it might be worth reporting. Is this limitation documented somewhere? If not, might it be worth doing this?

And yes, the `IllegalAccessError` looks like #7284.

**Comment by mkouba** [comment] 2020-03-10 15:33
>Is this limitation documented somewhere?

Well, I'd say it's implied ;-). I mean it's a well-known limitation of CDI proxies but it's not even explained/mentioned in the spec. Would you care to to send a PR and modify https://github.com/quarkusio/quarkus/blob/master/docs/src/main/asciidoc/cdi-reference.adoc?

**Comment by manovotn** [comment] 2020-03-10 16:19
It is implied, looking at [5.4 Client proxies section](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#client_proxies):

> A client proxy implements/extends some or all of the bean types of the bean and delegates all method calls to the current instance...

And further down the next paragraphs it all talks about method delegation. From impl PoV it also makes more sense as a stateless proxy can be shared between injection points saving you some resources.

**Comment by manovotn** [comment] 2020-03-10 16:32
And checking on the reproducer, it does look very similar to the already mentioned issue. The issue there was cased by a split package problem (if I understood it correctly). That is a bad practice in general, and a complete no-no with JDK 9+ JPMS taken into account; I'd suggest you avoid that.

**Comment by geoand** [comment] 2020-03-11 08:03
So should we close this?

**Comment by andreas-eberle** [comment] 2020-03-11 09:04
@manovotn: I'm not sure if I'll find the time atm. @geoand: Not sure if you want to keep this open until it is better documented or have it closed since it is not really a bug but expected behavior/known limitation.

**Comment by famod** [comment] 2022-02-22 00:12
The field access problem is described pretty clearly over here: https://quarkus.io/guides/cdi#applicationscoped-and-singleton-look-very-similar-which-one-should-i-choose-for-my-quarkus-application
(doesn't mention other normal scoped beans though)

I'll close this, feel free to reopen.

**Closed by famod** 2022-02-22 00:12 UTC
Labels: kind/bug
