### ISSUE TITLE
UserAgent header is not set after service is running

### ISSUE THREAD

**Issue by miladjafary** [quarkusio/quarkus#41474] opened 2024-06-26 14:38 UTC
### Describe the bug

Consider the following class which is used as an endpoint method parameter
```java
class SampleRequest {
    // Getters and Setters
    @PathParam("name")
    var name: String? = null

    @HeaderParam("Locale")
    var locale: String? = null

    @HeaderParam(HttpHeaders.USER_AGENT)
    val userAgent: String? = null
}
```
Here is the endpoint
```java
@Path("/hello")
class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    fun hello(sampleRequest: SampleRequest): String {
        return "Hello RESTEasy ${sampleRequest.userAgent}"

    }
}
```

when you hit `http://localhost:8080/hello` you will get `400`. If you open the log on DEBUG level you will see the following exception

```java
2024-06-26 16:17:13,446 DEBUG [WebApplicationException] (executor-thread-1) Application failed the request: jakarta.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.acme.SampleRequest.__quarkus_rest_inject(SampleRequest.kt)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:26)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:45)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:137)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: Update to non-static final field org.acme.SampleRequest.userAgent attempted from a different method (__quarkus_rest_inject) than the initializer method <init> 
	... 13 more

```

### Expected behavior

Set `User-Agent` header into `SampleRequest.userAgent` 

### Actual behavior

Return `400` http status with following exception (open DEBUG log) 
```java
2024-06-26 16:17:13,446 DEBUG [WebApplicationException] (executor-thread-1) Application failed the request: jakarta.ws.rs.BadRequestException: HTTP 400 Bad Request
	at org.acme.SampleRequest.__quarkus_rest_inject(SampleRequest.kt)
	at org.jboss.resteasy.reactive.server.core.parameters.InjectParamExtractor.extractParameter(InjectParamExtractor.java:26)
	at org.jboss.resteasy.reactive.server.handlers.ParameterHandler.handle(ParameterHandler.java:45)
	at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:137)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:599)
	at org.jboss.threads.EnhancedQueueExecutor$Task.doRunWith(EnhancedQueueExecutor.java:2516)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2495)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1521)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:11)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:11)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalAccessError: Update to non-static final field org.acme.SampleRequest.userAgent attempted from a different method (__quarkus_rest_inject) than the initializer method <init> 
	... 13 more

```

### How to Reproduce?

1- Run the Quarkus service `mvn clean quarkus:dev`
2- Hit the endpoint `http://localhost:8080/hello`
3- You will get `400` http status code and if you open the log you will see the exception
4- Change the header name on `@HeaderParam(HttpHeaders.USER_AGENT) val userAgent: String? = null` to some other headers like `Content-Type` while the service is still running (`@HeaderParam("Content-Type") val userAgent: String? = null`)
5- hit the `http://localhost:8080/hello`
6- You will get `200` http status 
7- Change the header name again to `@HeaderParam(HttpHeaders.USER_AGENT) val userAgent: String? = null`
8- This time you won't get `400` and exception. 

### Output of `java -version`

17

### Quarkus version or git rev

3.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by Ladicek** [comment] 2024-06-26 14:43
Any reason why the `userAgent` is declared as `val` instead of `var`?

**Comment by geoand** [comment] 2024-06-26 16:09
Thanks for reporting/

It would be make things much more efficient for us if you attached a sample that contained the code in question.

**Comment by miladjafary** [comment] 2024-06-26 20:34
@geoand I have create a project in this repo : https://github.com/miladjafary/quarkus-bug-41474

**Comment by miladjafary** [comment] 2024-06-26 20:35
> Any reason why the `userAgent` is declared as `val` instead of `var`?

I did not want the variable is changed after it is set.

**Comment by geoand** [comment] 2024-06-27 07:20
When I change from `val` to `var`, the service returns `200` and returns the proper response.

**Comment by geoand** [comment] 2024-06-27 07:21
So essentially this is a duplicate of #35382 and therefore I'll close it in favor of the existing issue

**Closed by geoand** 2024-06-27 07:21 UTC
Labels: kind/bug, area/resteasy-reactive
