### ISSUE TITLE
Problems with RestEasy Reactive and Reactive REST Client

### ISSUE THREAD

**Issue by masini** [quarkusio/quarkus#16799] opened 2021-04-26 09:26 UTC
## Describe the bug
I created a test-case problems that shows how using the reactive version we've got problems in the interaction between RESTEasy Reactive, Reactive REST Client and various handler and filters

### Expected behavior
The tests should run all correctly

### Actual behavior
Using the profile reactive tests fails

## To Reproduce

[https://github.com/masini/reactive-rest-test.git](https://github.com/masini/reactive-rest-test.git)

### Output of `uname -a` or `ver`
Darwin WMICTLM1P.local 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64 x86_64

### Output of `java -version`
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev
Problems are with Quarkus 1.13.2, all works fine with 2.0.0.Alpha1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Maven home: /Users/ictlm1/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Applications/sviluppo/java/jdk-11.0.10+9/Contents/Home
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.7", arch: "x86_64", family: "mac"

## Additional context

From here:

https://groups.google.com/g/quarkus-dev/c/xlVoQuJ6hoM

it seems that 1 and 2 are solved by:

https://issues.redhat.com/browse/RESTEASY-2872
https://github.com/quarkusio/quarkus/issues/8543

but I was unable to verify.

**Comment by geoand** [comment] 2021-04-26 10:03
Thanks for reporting!

There were various fixes gone into `main`, could you check and see if they fix some or all of the issues?

**Comment by masini** [comment] 2021-04-26 13:02
Sure, which branch ? I'm a bit confused now that 2.0 is coming !

**Comment by geoand** [comment] 2021-04-26 13:03
`main`

**Comment by geoand** [comment] 2021-04-26 15:04
Understood, thanks.

@michalszynkiewicz can you take a look?

**Comment by michalszynkiewicz** [comment] 2021-05-04 11:16
@geoand @FroMage one of the failures is NPE here: https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/ResponseHandler.java#L33-L34

`entityStream != null`, `entity == null`, `hasEntity` returns true in this case. What should happen here? Should genericReturnType remain unset?

**Comment by geoand** [comment] 2021-05-05 08:54
> `array` is not empty, but no entity is sent. I checked with rest client and `curl`.
> 

I could not reproduce this. The response I saw contained all the headers as expected

**Comment by FroMage** [comment] 2021-05-05 08:59
But did the entity body contain an empty array? `[]` I guess

**Comment by geoand** [comment] 2021-05-05 08:59
> But did the entity body contain an empty array? `[]` I guess

nope, it worked for me as expected

**Comment by FroMage** [comment] 2021-05-05 09:01
Huh. With his PR applied? Could this be the difference?

**Comment by geoand** [comment] 2021-05-05 09:07
I did apply the PR Michal mentioned

**Comment by FroMage** [comment] 2021-05-05 09:10
Then :shrug:

**Comment by geoand** [comment] 2021-05-05 09:11
But I'll contnue looking into it, there is obviously something I'm missing

**Comment by geoand** [comment] 2021-05-05 10:36
https://github.com/quarkusio/quarkus/pull/16999 fixes part of the problem

**Comment by geoand** [comment] 2021-09-30 12:34
Is this still a problem with the latest versions of Quarkus?

**Comment by geoand** [comment] 2021-11-09 10:46
Closing as out of date.

Please comment or reopen if this is still an issue.

**Closed by geoand** 2021-11-09 10:46 UTC
Labels: kind/bug, area/rest-client, area/resteasy-reactive
