### ISSUE TITLE
Unknown SEQUENCE: 'quarkus.hibernate_sequence'

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#31808] opened 2023-03-13 11:16 UTC
### Describe the bug

Using import.sql that references hibernate_sequence results in WARN message at the Dev mode startup:

```
2023-03-13 12:13:05,996 WARN  [org.mar.jdb.mes.ser.ErrorPacket] (JPA Startup Thread) Error: 4091-42S02: Unknown SEQUENCE: 'quarkus.hibernate_sequence'
2023-03-13 12:13:05,997 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (JPA Startup Thread) GenerationTarget encountered exception accepting command : Error executing DDL "drop sequence hibernate_sequence" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "drop sequence hibernate_sequence" via JDBC Statement
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlString(SchemaDropperImpl.java:387)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.applySqlStrings(SchemaDropperImpl.java:371)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.dropFromMetadata(SchemaDropperImpl.java:256)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.performDrop(SchemaDropperImpl.java:156)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:128)
	at org.hibernate.tool.schema.internal.SchemaDropperImpl.doDrop(SchemaDropperImpl.java:114)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.performDatabaseAction(SchemaManagementToolCoordinator.java:157)
	at org.hibernate.tool.schema.spi.SchemaManagementToolCoordinator.process(SchemaManagementToolCoordinator.java:85)
	at org.hibernate.internal.SessionFactoryImpl.<init>(SessionFactoryImpl.java:335)
	at io.quarkus.hibernate.orm.runtime.boot.FastBootEntityManagerFactoryBuilder.build(FastBootEntityManagerFactoryBuilder.java:74)
	at io.quarkus.hibernate.orm.runtime.FastBootHibernatePersistenceProvider.createEntityManagerFactory(FastBootHibernatePersistenceProvider.java:72)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:80)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$LazyPersistenceUnit.get(JPAConfig.java:167)
	at io.quarkus.hibernate.orm.runtime.JPAConfig$1.run(JPAConfig.java:68)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLSyntaxErrorException: (conn=4) Unknown SEQUENCE: 'quarkus.hibernate_sequence'
	at org.mariadb.jdbc.export.ExceptionFactory.createException(ExceptionFactory.java:282)
	at org.mariadb.jdbc.export.ExceptionFactory.create(ExceptionFactory.java:370)
	at org.mariadb.jdbc.message.ClientMessage.readPacket(ClientMessage.java:134)
	at org.mariadb.jdbc.client.impl.StandardClient.readPacket(StandardClient.java:855)
	at org.mariadb.jdbc.client.impl.StandardClient.readResults(StandardClient.java:794)
	at org.mariadb.jdbc.client.impl.StandardClient.readResponse(StandardClient.java:713)
	at org.mariadb.jdbc.client.impl.StandardClient.execute(StandardClient.java:637)
	at org.mariadb.jdbc.Statement.executeInternal(Statement.java:941)
	at org.mariadb.jdbc.Statement.execute(Statement.java:1067)
	at org.mariadb.jdbc.Statement.execute(Statement.java:458)
	at io.agroal.pool.wrapper.StatementWrapper.execute(StatementWrapper.java:235)
	at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:54)
	... 16 more
```

Only a message, the sequence works in the import.sql script.

### Expected behavior

No error if the hibernate_sequence is not found.

### Actual behavior

WARN messages are printed.

### How to Reproduce?

https://github.com/xstefank/quarkus-reproducers/tree/main/mysql-import-sql

$ quarkus dev

### Additional information

Is it possible I have something wrong with import.sql? I think I read somewhere that something changed?

**Comment by yrodiere** [comment] 2023-03-13 11:37
So I thought you were using Quarkus 3 (and thus Hibernate ORM 6), in which case this warning would be expected and caused by [a breaking change in Hibernate ORM 6](https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#identifier-generator-structure)... but your reproducer uses Quarkus 2.16, so that's intriguing. I need to have a closer look.

**Comment by yrodiere** [comment] 2023-03-13 11:42
Ok, judging from your stack trace, the error has nothing to do with your `import.sql`. It's just Hibernate ORM trying to drop the sequence as part of the `drop-and-create` database generation strategy, which is known to create undesirable logs when the sequence doesn't exist.

Closing as duplicate of #16204 . Feel free to comment there, or here if you think your problem is different.

**Closed** 2023-03-13 11:42 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm

**Comment by xstefank** [comment] 2023-03-13 13:12
thanks @yrodiere
