### ISSUE TITLE
hbm2ddl create-schemas doesn't work when setting quarkus.hibernate-orm.database.default-schema

### ISSUE THREAD

**Issue by vu-bui** [quarkusio/quarkus#25244] opened 2022-04-29 08:23 UTC
### Describe the bug

The option [quarkus.hibernate-orm.database.generation.create-schemas](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.database.generation.create-schemas) seems to doesn't work anymore since `2.6.3.Final`. I'm not sure if it's caused by Hibernate upgrade or not.

### Output of `uname -a` or `ver`

Darwin local 21.5.0 Darwin Kernel Version 21.5.0: Thu Apr 21 19:51:22 PDT 2022; root:xnu-8020.120.68.131.2~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.15" 2022-04-19

### Quarkus version or git rev

2.6.3.Final and newer

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by yrodiere** [comment] 2022-12-22 11:08
It seems to work in our integration tests. Can you please provide a simple project that reproduces the problem?

Thank you.

**Comment by yrodiere** [comment] 2023-01-02 08:32
This [other issue](https://github.com/quarkusio/quarkus/issues/30086) suggests the problem is only when `quarkus.hibernate-orm.database.generation` is set to `update`. Was that your case?

**Comment by yrodiere** [comment] 2023-01-24 07:47
Bump. @vu-bui Can you give us a reproducer, or at least confirm your problem is the same as [this one](https://github.com/quarkusio/quarkus/issues/30086) and occurs only when `quarkus.hibernate-orm.database.generation` is set to `update`?

**Comment by vu-bui** [comment] 2023-01-27 10:08
@yrodiere Sorry for the late reply. I've created a repo here https://github.com/vu-bui/quarkus-hibernate-schema-generation. 

What I found out was that `quarkus.hibernate-orm.database.generation.create-schemas` does not work with `quarkus.hibernate-orm.database.default-schema`. It works with Quarkus `2.6.2.Final` and earlier.

It also works if I specifically define `@Table(schema = "")`

**Comment by yrodiere** [comment] 2023-01-30 10:31
Thanks a lot for the information and reproducer @vu-bui , it does seem related to some changes I'm familiar with. I will have a closer look.

**Comment by yrodiere** [comment] 2023-02-13 13:08
After some investigation, the problem seems to be upstream. I reported the problem: https://hibernate.atlassian.net/browse/HHH-16177
I will try to come up with a fix upstream.
Thanks again for the reproducer, that helped a lot.

**Comment by yrodiere** [comment] 2023-02-21 08:27
The bug was fixed upstream. It will be fixed in Quarkus as soon as we upgrade to either Hibernate ORM 5.6.16.Final or Hibernate ORM 6.2.0.Final (neither was released yet).

**Comment by michalvavrik** [comment] 2023-06-01 14:39
I presume this was closed with https://github.com/quarkusio/quarkus/pull/32687, I'll write test in QE test suite, so will verify it later.

**Closed by michalvavrik** 2023-06-01 14:39 UTC
Labels: kind/bug, area/hibernate-orm

**Comment by Sanne** [comment] 2023-06-01 15:35
thanks @michalvavrik !

**Comment by yrodiere** [comment] 2023-06-02 06:29
> I presume this was closed with #32687, I'll write test in QE test suite, so will verify it later.

That's right, I forgot to close this. Thanks!
