### ISSUE TITLE
Dependency cannot read from resource directory

### ISSUE THREAD

**Issue by zeljkot** [quarkusio/quarkus#5401] opened 2019-11-12 13:30 UTC
**Describe the bug**
Main project has dependency on another project. Dependency tries to load resource bundle using `ResourceBundle.getBundle("messages");`, but fails. It seems that dependency uses different classloader, which does not see files from the main project.

**Expected behavior**
Dependency should be able to read configuration from the main project.

**Actual behavior**
Dependency gets NONEXISTENT_BUNDLE.

**To Reproduce**
1. Create two projects, "main" and "provider" where "main" has "provider" as a dependency.
2. "provider" should try to read the resource bundle from the resource directory.
3. "main" should call a method in the "provider" project, which uses a resource bundle.
4. Put the resource bundle in the first project's resource directory.
5. Run.

Example project: [bundle.zip](https://github.com/quarkusio/quarkus/files/3995364/bundle.zip)

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 * Output of uname -a or ver: Microsoft Windows [Version 10.0.18362.418]
 * Output of java -version:
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.221-b11, mixed mode)
 * GraalVM version (if different from Java):
 * Quarkus version or git rev: 1.0.0.CR1, running in dev mode

**Additional context**
(Add any other context about the problem here.)

**Comment by gsmet** [comment] 2019-11-18 23:47
@zeljkot it would definitely help if you could set up a small reproducer. Thanks!

**Comment by jaikiran** [comment] 2019-11-25 13:10
This is actually a genuine issue in the `dev` mode. The `java.util.ResourceBundle#getBundle(bundleName)` states that:

```
Gets a resource bundle using the specified base name, the default locale,
     * and the caller's class loader. Calling this method is equivalent to calling
     * <blockquote>
     * <code>getBundle(baseName, Locale.getDefault(), this.getClass().getClassLoader())</code>,
     * </blockquote>
```

In `dev` mode, we create and use a `RuntimeClassLoader` which only knows about the application classes and doesn't know of the dependency classes or even the `java.util.ResourceBundle`. As a result, the `ResourceBundle` class gets loaded by JRE's application classloader. Now if the `messages.properties` file is placed and packaged as part of the quarkus app's `src/main/resources`, it will end up being available and known (only) to the Quarkus' `RuntimeClassLoader` and as a result, when the `ResourceBundle` tries to load it via the JRE's classloader, it won't find it.

A workaround, if feasible ( depending on the access to the source code in the dependency which does this `ResourceBundle#getBundle`), would be to use something like:

```
ResourceBundle.getBundle("messages", Locale.getDefault(), Thread.currentThread.getContextClassLoader());
```
(important bit in that code is the usage of Thread's context classloader, which in dev mode will correspond to the `RuntimeClassLoader` and should find the `messages.properties`).

I can add a sample testcase to show this issue, in a day or two if needed (I'm away right now).

Adding @stuartwdouglas since he's working on the new classloader implementation and I haven't checked if those proposed changes will address issues like these.

**Comment by jaikiran** [comment] 2019-11-25 13:11
By the way, @zeljkot this issue is only present in `dev` mode, IMO. Can you confirm that? You shouldn't see this issue when you do something like:

```
mvn clean install
java -jar target/...-runner.jar
....
issue requests to the application
```

**Comment by stuartwdouglas** [comment] 2019-11-25 21:22
I don't think there is much we can do here, you will have similar issues in servers like WildFly where modular class loading is in use.

**Comment by zeljkot** [comment] 2019-12-23 15:08
I attached an example project to the original description. As @jaikiran noted, it is specific to `dev` mode; it does not occur if I run tests (also included).

**Comment by zeljkot** [comment] 2019-12-29 19:54
Would making a Quarkus extension out of library help?

**Comment by geoand** [comment] 2024-09-20 06:36
Closing this as the workaround is to use the version of the method that includes the CL as an argument (to which the TCCL would be passed)

**Closed by geoand** 2024-09-20 06:36 UTC
Labels: kind/bug
