### ISSUE TITLE
java.lang.NullPointerException: Cannot invoke "io.vertx.mutiny.mysqlclient.MySQLPool.preparedQuery(String)" because "this.client" is null

### ISSUE THREAD

**Issue by kulame** [quarkusio/quarkus#19271] opened 2021-08-06 13:02 UTC
### Describe the bug

i write a quarkus  cli app. and try to inject the mysql connection.
but i found some bugs on it.

### Expected behavior

execute the query statement success.

### Actual behavior

```shell
➜  cli git:(master) ✗ java -jar target/quarkus-app/quarkus-run.jar hello
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2021-08-06 20:58:52,573 INFO  [io.quarkus] (main) cli 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.0.2.Final) started in 0.436s.
2021-08-06 20:58:52,578 INFO  [io.quarkus] (main) Profile prod activated.
2021-08-06 20:58:52,578 INFO  [io.quarkus] (main) Installed features: [cdi, picocli, reactive-mysql-client, smallrye-context-propagation, vertx]
Hello hello, go go commando!
hello world
java.lang.NullPointerException: Cannot invoke "io.vertx.mutiny.mysqlclient.MySQLPool.preparedQuery(String)" because "this.client" is null
        at net.feelapp.ebiz.Worker.check(Worker.java:19)
        at net.feelapp.ebiz.GreetingCommand.run(GreetingCommand.java:25)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at net.feelapp.ebiz.GreetingCommand.run(GreetingCommand.java:30)
        at net.feelapp.ebiz.GreetingCommand_ClientProxy.run(GreetingCommand_ClientProxy.zig:129)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:123)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
        at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:30)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:567)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
        at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
2021-08-06 20:58:52,661 INFO  [io.quarkus] (main) cli stopped in 0.024s
```

### How to Reproduce?

1 quarkus  create cli net.feelapp.ebiz:cli
2 quarkus ext add quarkus-reactive-mysql-client
3 inject a mysql client

**Comment by tsegismont** [comment] 2021-08-16 12:52
I tried to reproduce without success.

I created a new project with `mvn io.quarkus:quarkus-maven-plugin:2.1.2.Final:create`
Then when asked which extensions to add, I typed `picocli,reactive-mysql-client`.

Here's the generated POM:

```xml
<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <groupId>org.acme</groupId>
  <artifactId>code-with-quarkus</artifactId>
  <version>1.0.0-SNAPSHOT</version>
  <properties>
    <compiler-plugin.version>3.8.1</compiler-plugin.version>
    <maven.compiler.parameters>true</maven.compiler.parameters>
    <maven.compiler.source>11</maven.compiler.source>
    <maven.compiler.target>11</maven.compiler.target>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
    <quarkus.platform.version>2.1.2.Final</quarkus.platform.version>
    <surefire-plugin.version>3.0.0-M5</surefire-plugin.version>
  </properties>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>${quarkus.platform.artifact-id}</artifactId>
        <version>${quarkus.platform.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-picocli</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-reactive-mysql-client</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-arc</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-junit5</artifactId>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>${quarkus.platform.group-id}</groupId>
        <artifactId>quarkus-maven-plugin</artifactId>
        <version>${quarkus.platform.version}</version>
        <extensions>true</extensions>
        <executions>
          <execution>
            <goals>
              <goal>build</goal>
              <goal>generate-code</goal>
              <goal>generate-code-tests</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>${compiler-plugin.version}</version>
        <configuration>
          <parameters>${maven.compiler.parameters}</parameters>
        </configuration>
      </plugin>
      <plugin>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>${surefire-plugin.version}</version>
        <configuration>
          <systemPropertyVariables>
            <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
            <maven.home>${maven.home}</maven.home>
          </systemPropertyVariables>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>native</id>
      <activation>
        <property>
          <name>native</name>
        </property>
      </activation>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-failsafe-plugin</artifactId>
            <version>${surefire-plugin.version}</version>
            <executions>
              <execution>
                <goals>
                  <goal>integration-test</goal>
                  <goal>verify</goal>
                </goals>
                <configuration>
                  <systemPropertyVariables>
                    <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                    <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    <maven.home>${maven.home}</maven.home>
                  </systemPropertyVariables>
                </configuration>
              </execution>
            </executions>
          </plugin>
        </plugins>
      </build>
      <properties>
        <quarkus.package.type>native</quarkus.package.type>
      </properties>
    </profile>
  </profiles>
</project>
```

I modified the generated command like this:

```java
package org.acme;

import io.vertx.mysqlclient.MySQLClient;
import io.vertx.mysqlclient.MySQLPool;
import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Parameters;

import javax.inject.Inject;

@Command(name = "greeting", mixinStandardHelpOptions = true)
public class GreetingCommand implements Runnable {

    @Inject
    MySQLPool pool;

    @Parameters(paramLabel = "<name>", defaultValue = "picocli",
        description = "Your name.")
    String name;

    @Override
    public void run() {
        System.out.printf("Hello %s, go go commando!\n", name);
        System.out.println("pool = " + pool);
    }

}
```

Then ran:

```
 ./mvnw clean package
java -jar target/quarkus-app/quarkus-run.jar greeting
```

The output is:

```
Hello greeting, go go commando!
pool = io.vertx.mysqlclient.impl.MySQLPoolImpl@2a2c13a8
```

Please provider a reproducer.

**Comment by cescoffier** [comment] 2021-08-22 17:15
@kulame Do you have a reproducer? 

See @tsegismont 's comment, it seems to work. 

However, I'm wondering what should happen when no data sources are configured.

**Comment by tsegismont** [comment] 2021-08-23 08:17
@cescoffier I tried with an empty config file, a datasource is created with default values.

**Comment by cescoffier** [comment] 2021-08-23 11:20
@tsegismont makes sense! Thanks!

**Comment by cescoffier** [comment] 2021-09-26 15:24
Closing, please re-open if the issue is still relevant (with a reproducer if possible).

**Closed by cescoffier** 2021-09-26 15:24 UTC
Labels: kind/bug, area/smallrye, area/mutiny, needs-reproducer, area/reactive-sql-clients
