### ISSUE TITLE
RestClient Reactive, MDC lost

### ISSUE THREAD

**Issue by lthasle** [quarkusio/quarkus#24318] opened 2022-03-15 12:26 UTC
### Describe the bug

The MDC set in a ClientRequestFilter can not be retrieved in a ClientResponseFilter.

See also:

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Reactive.2C.20Manual.20Context.20propagation.28MDC.29

### Expected behavior

The MDC set in a ClientRequestFilter should be accessable in a ClientResponseFilter.

### Actual behavior

MDC is lost as the ClientResponseFilter runs in another thread than the one that sets the MDC

### How to Reproduce?

Run the test provided in the attached reproducer.
Verify the logging: REQ_ID: null
Which is expected to contain MDC info

### Output of `uname -a` or `ver`

uname -a Linux hty80028.sb1a.sparebank1.no 4.18.0-348.2.1.el8_5.x86_64 #1 SMP Mon Nov 8 13:30:15 EST 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.10" 2021-01-19 OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)

### Quarkus version or git rev

2.7.4.Final

### Additional information

[rest-client-reactive-quickstart3.zip](https://github.com/quarkusio/quarkus/files/8253227/rest-client-reactive-quickstart3.zip)

**Comment by michalszynkiewicz** [comment] 2022-03-16 20:42
Hi Lars, the Zulip link doesn't work for me...

**Comment by gsmet** [comment] 2022-03-16 20:46
@michalszynkiewicz not sure if you have seen but there is a reproducer attached to the issue. So it should be easy to reproduce.

**Comment by michalszynkiewicz** [comment] 2022-03-16 21:15
I found it and changed the link.

**Comment by bdunni** [comment] 2022-11-09 11:40
Is there any update to this?

Any kind of work-around? We just upgraded to 2.13 which should have a fix for this, but now it happens sporadically in our logs.

**Comment by radcortez** [comment] 2022-11-09 14:27
I'll have a look.

**Comment by luneo7** [comment] 2023-02-06 17:38
Just run the reproducer, and with Quarkus 2.16.1.Final, it doesn't seem to happen anymore, and since we have MDC support built in the Vert.x core Quarkus lib even deleting `ThreadContextProvider` the MDC works, is there another reproducer, or we can assume that it is already fixed in current version @brunobat @radcortez?
We are using 2.13 in our services, and we didn't encounter any missing MDC context in our logs.

**Comment by brunobat** [comment] 2023-02-07 10:08
Hi @luneo7, there has been a lot of improvements of the imperative-reactive context propagation right before 2.13.
I imagine they also fixed this issue.
@lthasle are you ok if we close this issue?

**Comment by radcortez** [comment] 2023-02-07 10:32
I believe this was fixed with https://github.com/quarkusio/quarkus/pull/27443.

I'm closing the issue since you get the expected behavior once you update to Quarkus >= 2.13.x.

**Closed by radcortez** 2023-02-07 10:32 UTC
Labels: kind/bug, area/logging, area/rest-client, area/resteasy-reactive
