### ISSUE TITLE
Quickstart failing with '@ConfigProperty is not supported in @QuarkusIntegrationTest tests'

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#35908] opened 2023-09-13 09:45 UTC
The quickstart build is failing because of that.

I think we probably changed a behavior here and the quickstart needs to be adjusted. Could somebody have a look?

@geoand @mkouba you might have something to do with it?

```
[INFO] Running org.acme.rabbitmq.processor.QuoteProcessorIT
Error:  Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.197 s <<< FAILURE! -- in org.acme.rabbitmq.processor.QuoteProcessorIT
Error:  org.acme.rabbitmq.processor.QuoteProcessorIT -- Time elapsed: 0.197 s <<< ERROR!
org.junit.platform.commons.JUnitException: @ConfigProperty is not supported in @QuarkusIntegrationTest tests. Offending field is org.acme.rabbitmq.processor.QuoteProcessorTest.host
	at io.quarkus.test.junit.IntegrationTestUtil.ensureNoInjectAnnotationIsUsed(IntegrationTestUtil.java:86)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.ensureStarted(QuarkusIntegrationTestExtension.java:143)
	at io.quarkus.test.junit.QuarkusIntegrationTestExtension.beforeAll(QuarkusIntegrationTestExtension.java:130)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.lambda$invokeBeforeAllCallbacks$12(ClassBasedTestDescriptor.java:395)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.invokeBeforeAllCallbacks(ClassBasedTestDescriptor.java:395)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:211)
	at org.junit.jupiter.engine.descriptor.ClassBasedTestDescriptor.before(ClassBasedTestDescriptor.java:84)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:148)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
```

**Comment by geoand** [comment] 2023-09-13 09:46
That was never supported AFAIR

**Comment by geoand** [comment] 2023-09-13 09:46
I'll have a look later on

**Comment by mkouba** [comment] 2023-09-13 10:24
Hm, indeed the injection was never supported in `@QuarkusIntegrationTest`... 

That's weird, if you look at the error message - it mentions `Offending field is org.acme.rabbitmq.processor.QuoteProcessorTest.host` but `org.acme.rabbitmq.processor.QuoteProcessorTest` does not declare the field `host`. The [`org.acme.amqp.processor.QuoteProcessorTest`](https://github.com/quarkusio/quarkus-quickstarts/blob/main/amqp-quickstart/amqp-quickstart-processor/src/test/java/org/acme/amqp/processor/QuoteProcessorTest.java#L24) does. Which indicates that the test class may somehow leak in the `QuarkusIntegrationTestExtension`?

**Comment by geoand** [comment] 2023-09-13 11:56
@mkouba I think you are looking at the wrong `QuoteProcessorTest` :)

**Comment by geoand** [comment] 2023-09-13 11:59
I just removed the IT in https://github.com/quarkusio/quarkus-quickstarts/pull/1329

**Comment by mkouba** [comment] 2023-09-13 12:01
> @mkouba I think you are looking at the wrong `QuoteProcessorTest` :)

Am I? 

* `org.acme.rabbitmq.processor.QuoteProcessorTest` has no `host` field: https://github.com/quarkusio/quarkus-quickstarts/blob/main/rabbitmq-quickstart/rabbitmq-quickstart-processor/src/test/java/org/acme/rabbitmq/processor/QuoteProcessorTest.java
* `org.acme.amqp.processor.QuoteProcessorTest` has the `host` field: https://github.com/quarkusio/quarkus-quickstarts/blob/main/amqp-quickstart/amqp-quickstart-processor/src/test/java/org/acme/amqp/processor/QuoteProcessorTest.java#L24

**Comment by geoand** [comment] 2023-09-13 12:03
Wrong branch :)

**Comment by mkouba** [comment] 2023-09-13 12:05
> Wrong branch :)

I see. So it was a regression caused by https://github.com/quarkusio/quarkus-quickstarts/commit/700ba5083f2f8630cf84790649a571151823eecf.

**Comment by mkouba** [comment] 2023-09-15 07:37
https://github.com/quarkusio/quarkus-quickstarts/pull/1329 got merged so I think that this issue should be closed.

**Closed by mkouba** 2023-09-15 07:37 UTC
Labels: area/testing
