### ISSUE TITLE
Disable JSESSIONID when not needed

### ISSUE THREAD

**Issue by Xnyle** [quarkusio/quarkus#19770] opened 2021-08-30 11:21 UTC
### Description

It would be nice if there is an easy way to 

a) automatically disable the JSESSIONID cookie if there are no session beans
b) manually disable that cookie
c) or at least provide an easy way to rename it

Reason:
Multiple stateless REST services that are reverse proxied should not overwrite each others SESSION ids
(yes you can solve this at the proxy level but IMHO if there is no session scoped bean there should not be a session cookie at all)

**Comment by gastaldi** [comment] 2021-08-30 14:16
Do you have a small project that reproduces this?

**Comment by gastaldi** [comment] 2021-08-30 15:03
I tried to reproduce it and I see that the `JSESSIONID` cookie is already only created when a `@SessionScoped` object is accessed.

**Comment by Xnyle** [comment] 2021-08-31 12:15
Well, no there must be another mechanism that triggers a setcookie. I Just verified that my own code does not have a singe @SessionScoped bean, still I get

server: openresty/1.15.8.2
set-cookie: JSESSIONID=uapGFxiucktFeUpYPrk7OPker8WX83q2TbRRHlsX; path=/

These are the modules I'm using

	implementation "io.quarkus:quarkus-arc"
    implementation "io.quarkus:quarkus-resteasy" 
	implementation "io.quarkus:quarkus-resteasy-jackson"
	implementation "io.quarkus:quarkus-narayana-jta"
	implementation "io.quarkus:quarkus-undertow"

If you say it's only created on access then some hidden @SessionScoped beans in transitive dependencies shouldn't trigger it as I don't access them?

**Comment by gastaldi** [comment] 2021-08-31 14:00
> server: openresty/1.15.8.2

This is strange, it is not provided by a Quarkus app, is it being set manually in your app?

**Comment by gastaldi** [comment] 2021-08-31 14:24
BTW I created a sample project using the same extensions you listed and I still don't see the `set-cookie` header

**Comment by gastaldi** [comment] 2021-09-02 16:25
I'm closing this issue since we couldn't reproduce it. Please attach a reproducer project and reopen if possible

**Closed by gastaldi** 2021-09-02 16:25 UTC
Labels: kind/enhancement, triage/needs-triage
