### ISSUE TITLE
Entities extending PanacheEntityBase are not enhanced in dev mode when located in a dependency

### ISSUE THREAD

**Issue by gwenneg** [quarkusio/quarkus#2936] opened 2019-06-22 13:40 UTC
**Describe the bug**
Getters and setters are not generated for an entity extending `PanacheEntityBase` and located in a dependency of a Quarkus project. This dependency contains an empty `beans.xml`.

**Expected behavior**
The Quarkus documentation says entities getter/setter generation should work for entities from dependencies as long as there's an empty beans.xml in the dependencies:
> Hibernate ORM in Quarkus relies on compile-time bytecode enhancements to your entities. If you define your entities in the same project where you build your Quarkus application, everything will work fine. If the entities come from external projects or jars, you can make sure that your jar is treated like a Quarkus application library by adding an empty META-INF/beans.xml file. This will allow Quarkus to index and enhance your entities as if they were inside the current project.

**Actual behavior**
```
org.jboss.resteasy.spi.UnhandledException: java.lang.NoSuchMethodError: com.gwenneg.EntityWithoutGetterSetter.setName(Ljava/lang/String;)V
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:209)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:496)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:252)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:153)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:156)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:238)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:234)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:61)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:791)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$8$1$1.call(UndertowDeploymentTemplate.java:482)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleRequest(ServletInitialHandler.java:197)
	at io.undertow.server.handlers.HttpContinueReadHandler.handleRequest(HttpContinueReadHandler.java:65)
	at io.quarkus.undertow.runtime.UndertowDeploymentTemplate$1.handleRequest(UndertowDeploymentTemplate.java:90)
	at io.undertow.server.handlers.CanonicalPathHandler.handleRequest(CanonicalPathHandler.java:49)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup.handleHotDeploymentRequest(UndertowHotReplacementSetup.java:77)
	at io.quarkus.undertow.deployment.devmode.UndertowHotReplacementSetup$1$1.handleRequest(UndertowHotReplacementSetup.java:56)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:364)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
	at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:243)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1538)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1429)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:32)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: java.lang.NoSuchMethodError: com.gwenneg.EntityWithoutGetterSetter.setName(Ljava/lang/String;)V
	at com.gwenneg.todo.application.ReproducerResource.test(ReproducerResource.java:16)
	at com.gwenneg.todo.application.ReproducerResource_ClientProxy.test(ReproducerResource_ClientProxy.zig:159)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:151)
	at org.jboss.resteasy.core.MethodInjectorImpl.lambda$invoke$3(MethodInjectorImpl.java:122)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyNow(CompletableFuture.java:680)
	at java.base/java.util.concurrent.CompletableFuture.uniApplyStage(CompletableFuture.java:658)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:2094)
	at java.base/java.util.concurrent.CompletableFuture.thenApply(CompletableFuture.java:143)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:122)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:568)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:442)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:396)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:362)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:398)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:367)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invoke$1(ResourceMethodInvoker.java:341)
	at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
	at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:143)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:341)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:477)
	... 50 more
```

**To Reproduce**
1. Clone https://github.com/gwenneg/quarkus-panache-getter-setter-generation
2. Run `cd entity-dependency`
3. Run `./mvnw clean install`
4. Run `cd ../jaxrs-resource`
5. Run `./mvnw clean compile quarkus:dev`
6. Call http://localhost:8080/reproducer/test from browser

**Environment:**
 - Output of `java -version`: `openjdk version "11" 2018-09-25`
 - Quarkus version or git rev: `0.17.0`

**Comment by gwenneg** [comment] 2019-06-22 21:16
It seems this bug only affects dev mode. It's not happening with `./mvnw clean package` followed by `java -jar target/jaxrs-resource-1.0-SNAPSHOT-runner.jar`.

**Comment by gwenneg** [comment] 2019-06-23 19:30
I added the missing getters/setters as a workaround for this issue and now I'm facing a new `IllegalStateException` with the following message when calling the `PanacheEntityBase.find()` method:
> This method is normally automatically overridden in subclasses: did you forget to annotate your entity with @Entity?

This also happens only in dev mode. Everything's fine if I run a packaged jar like in my previous comment. These two issues have to be related.

This time, I don't see any workaround, I'll have to wait for this to be fixed.

**Comment by machi1990** [comment] 2019-06-23 20:09
Hi @gwenneg, I do no know why you are getting the error but I think that I have a work around.

Taking a closer  look at your project  and was able to reproduce the problem with your current setup. But then looking closer, it looked to me like a `multimodule` project, so I went on and added a `pom.xml`  file at the root of the project: 

```
    <?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.gwenneg</groupId>
    <artifactId>reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <properties>
        <quarkus.version>999-SNAPSHOT</quarkus.version>
        <compiler-plugin.version>3.8.0</compiler-plugin.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    </properties>

    <modules>
	<module>entity-dependency</module>
	<module>jaxrs-resource</module>
    </modules>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <scope>import</scope>
                <type>pom</type>
                <version>${quarkus.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>${compiler-plugin.version}</version>
                <configuration>
                    <!-- the parameters=true option is critical so that RESTEasy works fine -->
                    <parameters>true</parameters>
                </configuration>
            </plugin>
            <plugin>
                <!-- This is what injects the magic Quarkus bytecode -->
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>		
        </plugins>
    </build>
</project>
```

And then I added:

```
<parent>
    <groupId>com.gwenneg</groupId>
    <artifactId>reproducer</artifactId>
    <version>1.0-SNAPSHOT</version>
    <relativePath>../</relativePath>
 </parent>

```
in the `pom.xml` file of the two modules. 
Then running `mvn clean compile` in `entity-dependency` and then `mvn clean compile quarkus:dev` inside `jaxrs-resource` module seems to work when hitting `curl localhost:8080/reproducer/test` endpoint. 
HTH

**Comment by gwenneg** [comment] 2019-06-23 20:33
Hi @machi1990 and thanks for taking the time to help me.

My reproducer may look like a multi-modules Maven project with a missing parent `pom.xml`, but I actually didn't add this `pom.xml` on purpose. At first, I wanted to reproduce this issue with two separate repositories and then I got lazy and put everything in the same repository :)

I am trying to use Panache in several real projects which can't be part of a multi-modules parent project. I need this to work with a simple compile dependency relation between these projects.

**Comment by FroMage** [comment] 2019-06-26 15:01
It appears that we do detect that we need to modify the entity archive, because we create the modified jar, but we don't populate it:

```
 $ unzip -l target/lib/modified-com.gwenneg.entity-dependency-1.0-SNAPSHOT.jar 
Archive:  target/lib/modified-com.gwenneg.entity-dependency-1.0-SNAPSHOT.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2019-06-26 16:58   META-INF/
      131  2019-06-26 16:58   META-INF/MANIFEST.MF
        0  2019-06-26 16:58   com/
        0  2019-06-26 16:58   com/gwenneg/
      183  2019-06-26 16:58   application.properties
        0  2019-06-26 16:58   META-INF/beans.xml
        0  2019-06-26 16:58   META-INF/maven/
        0  2019-06-26 16:58   META-INF/maven/com.gwenneg/
        0  2019-06-26 16:58   META-INF/maven/com.gwenneg/entity-dependency/
     2367  2019-06-26 16:56   META-INF/maven/com.gwenneg/entity-dependency/pom.xml
      121  2019-06-26 16:58   META-INF/maven/com.gwenneg/entity-dependency/pom.properties
---------                     -------
     2802                     11 files

```

**Comment by FroMage** [comment] 2019-06-26 15:04
The augmented entity is properly in `target/jaxrs-resource-1.0-SNAPSHOT-runner.jar` though.

**Comment by FroMage** [comment] 2019-06-26 15:25
Ah, so it's normal that these archives don't have the types we transform, I forgot that was the resolution of #2196.

Note that this is working in the `java -jar target/...-runner.jar` case.

**Comment by FroMage** [comment] 2019-06-26 15:34
In this case, in `quarkus:dev` I can see that the class is loaded from the unmodified archive: `/home/stephane/.m2/repository/com/gwenneg/entity-dependency/1.0-SNAPSHOT/entity-dependency-1.0-SNAPSHOT.jar` rather than the augmented classes.

At this point, surely @stuartwdouglas will know why it's not using the augmented class in dev mode.

**Comment by gwenneg** [comment] 2019-08-28 20:22
I just tested with master (2f519a49cdb6ecfa81874e9e1cb7a4d6423c3a23), this bug is still happening.

**Comment by FroMage** [comment] 2019-08-29 12:39
Thanks, should be fixed now.

**Closed** 2019-08-29 12:38 UTC
Labels: bug, component:panache

**Comment by gwenneg** [comment] 2019-08-29 12:41
Great! Thanks for the fix.

**Comment by gwenneg** [comment] 2019-08-29 16:49
Fix confirmed from `master` with the reproducer.
