### ISSUE TITLE
URL does not match quarkus.http.root-path in dev mode 404

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#40240] opened 2024-04-24 09:06 UTC
### Discussed in https://github.com/quarkusio/quarkus/discussions/40239

<div type='discussions-op-text'>

<sup>Originally posted by **faermanj** April 24, 2024</sup>
So, not sure if this is a bug, what do you think?
URL does not seem to use the root path (quarkus.http.root-path), generating wrong links, as shown in the image below
/pvt/sandbox should be /user/cfp/pvt/sandbox in the URL (generated link)
![image](https://github.com/quarkusio/quarkus/assets/356476/a36a50d9-40e1-437e-88ed-29953769cdf6)
</div>

**Comment by gsmet** [comment] 2024-04-24 09:06
@phillip-kruger could you have a look?

**Comment by phillip-kruger** [comment] 2024-04-24 09:10
Do we have a reproducer?

**Comment by gsmet** [comment] 2024-04-24 09:13
@faermanj any chance you could provide a reproducer?

**Comment by phillip-kruger** [comment] 2024-05-10 05:53
@faermanj ^^^

**Comment by phillip-kruger** [comment] 2024-10-14 00:43
This seems to be fixed (or I can not reproduce). Closing here. Please reopen with a reproducer if this is still the case.

**Closed by phillip-kruger** 2024-10-14 00:43 UTC
Labels: area/devmode, area/dev-ui
