### ISSUE TITLE
Quarkus Flyway applies Java migrations to all data sources regardless of location

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#27957] opened 2022-09-15 08:57 UTC
### Describe the bug

I have a default data source with `quarkus.flyway.locations=db/migration` and another data source with `quarkus.other.flyway.locations=other-db/migration`

I have a Java based migration in a package `another.db.migration`.

The Java migrations are applied to both data sources despite not being in the list of locations for either data source.

I found this out because the migrations were initially in the package `db.migration` but was being applied to both data sources. After moving it to another package not in either data sources locations it is still applied to both data sources.

### Expected behavior

Java based flyway migrations are only applied to a data source if they exist in the correct location for the data source.
In a project with multiple data sources it should be possibly to apply Java based migrations to only one data source.

### Actual behavior

Java migrations are applied to all data sources.

### Quarkus version or git rev

2.12.2.Final

**Comment by geoand** [comment] 2022-09-15 09:33
Thanks for reporting.

It looks like this is a duplicate of https://github.com/quarkusio/quarkus/issues/21275, do you agree?

**Comment by josephearl** [comment] 2022-09-15 09:34
@geoand yes it does look like the same issue, should I close this as dupe?

**Comment by geoand** [comment] 2022-09-15 09:35
I'll do it.

Thanks for confirming

**Closed by geoand** 2022-09-15 09:35 UTC
Labels: kind/bug, area/flyway
