### ISSUE TITLE
Gradle `quarkusIntTest` leaks docker network

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#29868] opened 2022-12-14 19:09 UTC
### Describe the bug

After running `./gradlew -Dquarkus.container-image.build=true quarkusIntTest` the Docker network created for the tests (e.g. `quarkus-integration-test-<random>`) is not cleaned up.

After 20 or so runs Docker runs out of networks and the tests fail because it can no longer create a new network.

### Expected behavior

`quarkusIntTest` cleans up any Docker resources it created, including networks.

### Actual behavior

The Docker network is leaked.

### How to Reproduce?

Run `./gradlew -Dquarkus.container-image.build=true quarkusIntTest` in a project with both `QuarkusTest`s and `QuarkusIntegrationTest`s.

### Output of `uname -a` or `ver`

macOS 13.1

### Output of `java -version`

Java 17.0.2

### Quarkus version or git rev

2.14.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5.1

**Comment by kdubb** [comment] 2022-12-15 06:28
Apparently this only happens if the tests fail.

**Comment by geoand** [comment] 2022-12-15 08:05
I was not able to reproduce this. In all cases, the docker network was removed after the tests completed

**Comment by kdubb** [comment] 2022-12-15 08:14
It might have to do with my disabling of dev services and/or using a special test profile.

In the configuration I have defined a custom profile, `%itest`, and enabled it for integration tests using `quarkus.test.native-image-profile=itest`.

Additionally, in the `build.gradle.kts` I have this task configuration:
```
tasks.quarkusIntTest.configure {
  systemProperty("quarkus.devservices.enabled", "false")
}
```

**Comment by kdubb** [comment] 2022-12-15 08:15
This configuration has the dubious nature of only disabling dev services for integration tests but still keeping them for unit tests.

**Comment by geoand** [comment] 2022-12-15 08:17
Can you share a sample application that behaves in the erroneous way described in the issue?

**Comment by kdubb** [comment] 2022-12-15 08:18
Yeah I'll make a repro. I have one or two other issues related to this configuration.

**Comment by kdubb** [comment] 2022-12-17 06:30
My attempts at creating a reproducer has so far been completely unsuccessful. Although we still see it in our main project from time to time; I believe it's only "sometimes" when errors occur in the tests.

**Comment by geoand** [comment] 2023-02-17 08:52
Closing this for the time being.

**Closed** 2023-02-17 08:52 UTC
Labels: kind/bug, area/gradle, area/testing, triage/needs-reproducer
