### ISSUE TITLE
Permlink in the guides

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#2284] opened 2019-04-29 19:24 UTC
It would be awesome if each H2 entry in the guides had a permlink next to it (similar to what GitHub does with README.md files). Bonus points if a table of contents with links is generated too based on the document structure

**Comment by rquinio** [comment] 2019-06-17 21:23
<sectanchors>true</sectanchors> is already set in this repo asciidoc rendering https://github.com/quarkusio/quarkus/blob/master/docs/pom.xml

This needs actually to be done on quarkusio.github.io repo => https://github.com/quarkusio/quarkusio.github.io/issues/219 (and https://github.com/quarkusio/quarkusio.github.io/issues/196)

**Comment by gsmet** [comment] 2019-06-21 10:28
Closing this one as it's a duplicate of the website issue.

**Closed by gsmet** 2019-06-21 10:28 UTC
