### ISSUE TITLE
OIDC Client registration fails when `post-logout-uri` configuration property is set

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#44269] opened 2024-11-02 10:52 UTC
### Describe the bug

OIDC Client Registration extension has configuration property `quarkus.oidc-client-registration.metadata.post-logout-uri`, if you set it, registration fails.

### Expected behavior

Client registration succeeds.

### Actual behavior

Exception is raised and registration fails:

```
2024-11-02 11:48:37,665 ERROR [io.qua.oid.cli.reg.run.OidcClientRegistrationImpl] (vert.x-eventloop-thread-1) Client registeration has failed:  status: 400, error message: {"error":"Unrecognized field \"post_logout_redirect_uri\" (class org.keycloak.representations.oidc.OIDCClientRepresentation), not marked as ignorable (55 known properties: \"dpop_bound_access_tokens\", \"tos_uri\", \"redirect_uris\", \"client_id\", \"request_object_signing_alg\", \"grant_types\", \"client_id_issued_at\", \"backchannel_client_notification_endpoint\", \"client_secret_expires_at\", \"backchannel_logout_uri\", \"userinfo_signed_response_alg\", \"id_token_encrypted_response_enc\", \"jwks_uri\", \"client_secret\", \"default_max_age\", \"require_auth_time\", \"request_object_encryption_alg\", \"software_id\", \"token_endpoint_auth_method\", \"require_pushed_authorization_requests\", \"request_uris\", \"frontchannel_logout_session_required\", \"backchannel_logout_session_required\", \"registration_client_uri\", \"userinfo_encrypted_response_alg\", \"software_version\", \"tls_client_auth_subject_dn\", \"backchannel_token_delivery_mode\", \"application_type\", \"backchannel_authentication_request_signing_alg\", \"sector_identifier_uri\", \"contacts\", \"scope\", \"logo_uri\", \"frontchannel_logout_uri\", \"policy_uri\", \"id_token_encrypted_response_alg\", \"subject_type\", \"request_object_encryption_enc\" [truncated]])\n at [Source: REDACTED (`StreamReadFeature.INCLUDE_SOURCE_IN_LOCATION` disabled); line: 1, column: 119] (through reference chain: org.keycloak.representations.oidc.OIDCClientRepresentation[\"post_logout_redirect_uri\"])","error_description":"For more on this error consult the server log at the debug level."}
```

### How to Reproduce?

Add `quarkus.oidc-client-registration.tenant-client.metadata.post-logout-uri=http://localhost:8081/protected/tenant` here https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client-registration/src/main/resources/application.properties and run tests.

### Quarkus version or git rev

`999-SNAPSHOT`

**Comment by sberyozkin** [comment] 2024-11-02 11:21
@michalvavrik It's not a bug I think, it just shows Keycloak does not support this optional properly,  will get back with more info later

**Comment by michalvavrik** [comment] 2024-11-02 11:23
> [@michalvavrik](https://github.com/michalvavrik) It's not a bug I think, it just shows Keycloak does not support this optional properly, will get back with more info later

Copy that, but it's really surprising from user position. I think it's worth having an issue at least to improve behavior. Having build failed when I set a configuration property feels wrong.

**Comment by michalvavrik** [comment] 2024-11-02 12:08
I was really surprised, but it was my mistake that I didn't check whether Keycloak supports this property. I suppose behavior cannot be customized for Keycloak because it would require checking up in next KC releases whether they started to support this property. So I'll close it.

**Comment by sberyozkin** [comment] 2024-11-02 12:08
@michalvavrik Actually, it looks like a Keycloak bug, I suggest to report it in the Keycloak project....

What Quarkus reports is a single element [post_logout_redirect_uris](https://openid.net/specs/openid-connect-rpinitiated-1_0.html#ClientMetadata) array [here](https://github.com/quarkusio/quarkus/blob/main/extensions/oidc-client-registration/runtime/src/main/java/io/quarkus/oidc/client/registration/runtime/OidcClientRegistrationImpl.java#L257). 

The exception you are seeing is a Keycloak level exception, which happens `after` Keycloak `correctly` processed a client registration request issued by Quarkus, at the moment Keycloak wants to return a client registration confirmation...

**Comment by michalvavrik** [comment] 2024-11-02 12:09
@sberyozkin I am glad, I'll keep it open then...

**Comment by sberyozkin** [comment] 2024-11-02 12:15
@michalvavrik You can close this one :-), because it it is not a Quarkus level problem, this OIDC client registration extension is about a portable, OIDC client reg spec compliant client registration with any OIDC provider which supports it. Some providers may not support optional properties. 
 
But in this case, it is not even that Keycloak OIDC client reg does not recognize the property on the input, because it does, it only fails to return it correctly on the output...  It is not a Quarkus bug then, right ? 

I'd also like to avoid talking about Keycloak specifically at the Quarkus OIDC client reg doc level, as we continue seeing some users thinking Quarkus OIDC is only about Keycloak

**Comment by sberyozkin** [comment] 2024-11-02 12:17
Np at all, thanks for starting experimenting with this extension, @michalvavrik, cheers

**Closed** 2024-11-02 12:17 UTC
Labels: kind/bug, area/oidc

**Comment by michalvavrik** [comment] 2024-11-02 12:18
> Np at all, thanks for starting experimenting with this extension, [@michalvavrik](https://github.com/michalvavrik), cheers

I actually run into it when creating Dev Mode test using KC Dev Svc I refactored :-). Thanks

**Comment by sberyozkin** [comment] 2024-11-02 12:21
@michalvavrik You may want to keep the existing ones which involve `quarkus-oidc`, but adding a simple devmode test which confirms `quarkus-oidc-client-registration` can be used without `quarkus-oidc` would be nice

**Comment by sberyozkin** [comment] 2024-11-02 12:23
This is because it is likely that a typical pattern would involve the async client registration with reg results saved somewhere and quarkus-oidc picking up those details indirectly via for ex TenantConfigResolver

**Comment by michalvavrik** [comment] 2024-11-02 12:25
> This is because it is likely that a typical pattern would involve the async client registration with reg results saved somewhere and quarkus-oidc picking up those details indirectly via for ex TenantConfigResolver

It makes sense. And I didn't want to overwhelm you with unnecessary information, but in fact I am creating standalone test in OIDC Client Registration module. I suggested this one-line reproducer it required for you less steps. Anyway, thanks!
