### ISSUE TITLE
Random private final static UUID set at native compile time in native-image

### ISSUE THREAD

**Issue by mjurc** [quarkusio/quarkus#10946] opened 2020-07-23 19:30 UTC
**Describe the bug**
In native image, it is currently impossible to use random UUID set as `private final static UUID = UUID.randomUUID();` in a class to identify an instance as the result of `UUID.randomUUID()` in the class's static initialization are set at native compile time. 

**Expected behavior**
Same behaviour as when running Quarkus on JVM - the UUID is different for each launched process of application.

**Actual behavior**
The UUID is same for each and every launched process of application.

**To Reproduce**
1. Build the application at https://github.com/quarkus-qe/quarkus-openshift-test-suite/tree/master/scaling
2. Boot the native image process multiple times, access localhost:8080/scaling - the UUID returned is always the same
3. Boot the app on JVM multiple times, access localhost:8080/scaling - the UUID returned is different for each new launched application

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Linux tigris 5.7.9-200.fc32.x86_64 #1 SMP Fri Jul 17 16:23:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
 - Output of `java -version`: `openjdk version "11.0.8" 2020-07-14`
 - GraalVM version (if different from Java): using builder image
 - Quarkus version or git rev: `master`
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.1 (d66c9c0b3152b2e69ee9bac180bb8fcc8e6af555; 2019-04-04T21:00:29+02:00)`

**Comment by jaikiran** [comment] 2020-07-24 02:02
Hello @mjurc, which Graal VM version are you using? This was fixed a few months back in Graal VM itself https://github.com/oracle/graal/issues/2265

**Comment by jaikiran** [comment] 2020-07-24 02:04
Actually, you mention you are using Linux. So I'm not sure if this is the same issue. I will have to take a look at the reproducer to see if I can reproduce the issue.

**Comment by geoand** [comment] 2020-07-24 07:07
cc @galderz

**Comment by geoand** [comment] 2020-07-24 07:12
I can confirm the problem on Linux

**Comment by jaikiran** [comment] 2020-07-24 07:58
I tried this on both Linux (RHEL 7) and a MacOS:

> 
> Build the application at https://github.com/quarkus-qe/quarkus-openshift-test-suite/tree/master/scaling
> Boot the native image process multiple times, access localhost:8080/scaling - the UUID returned is always the same

and I don't see this behaviour. Every time I build a new native image out of this application it generates a new UUID that is displayed when I access the /scaling endpoint:

First built image:
```
a4bcabe9-21a2-4029-b2aa-c42668852305
```
Second built image:
```
27ccc8f3-65a0-48de-909f-f883422784ad
```
I'm on Linux:
```
Linux localhost 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
and Graal VM version:
```
GraalVM Version 20.1.0 (Java Version 11.0.7)
```
Of course, repeatedly invoking the endpoint /scaling against the same native image binary will display the same UUID, since that's the way this endpoint is coded and from the descriptions of this issue, I don't think it's about multiple invocations on the same native image. 

@geoand, in your tests did you build the native image more than once?

**Comment by geoand** [comment] 2020-07-24 08:05
@jaikiran I am getting a different UUID for each native build, but I am getting the same UUID when running the application.

I didn't really see that the application code used a `static final`, so this does indeed look like a user-code issue - sorry I didn't look at this more closely.

**Comment by geoand** [comment] 2020-07-24 08:07
@mjurc essentially if you remove `static`, then the UUID doesn't get baked into the native image, and then on each run of the native binary you'll get a different UUID.

**Comment by geoand** [comment] 2020-07-24 08:10
I propose we close the issue as this is expected GraalVM behavior, WDYT @jaikiran ?

**Comment by jaikiran** [comment] 2020-07-24 08:16
Agree. This works as advertised (static init runs at build time).

**Closed** 2020-07-24 08:20 UTC
Labels: env/graalvm-java11, kind/bug

**Comment by jaikiran** [comment] 2020-07-24 08:23
@mjurc, for reference here's the class initialization documentation which explains about these semantics https://github.com/oracle/graal/blob/master/substratevm/CLASS-INITIALIZATION.md
