### ISSUE TITLE
[Hibernate Reactive Panache & Mutiny] Concurrent request + Mutiny Retry lead to Sessions error and io.vertx.core.impl.NoStackTraceThrowable: Timeout

### ISSUE THREAD

**Issue by MaximeGil** [quarkusio/quarkus#42267] opened 2024-08-01 11:17 UTC
### Describe the bug

Hello !

I'm opening a new report due to production issues.

For the story, we have a project that retries some functions via Mutiny in case of exception.

Since Quarkus migration to 3.x, when we try to retry and when Hibernate is in the loop, an error is raised: "HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration".

This is my first big problem.

The second is that when one exception follows another, over and over again, the module is no longer able to respond to requests and returns errors like this: 

> 2024-08-01 13:10:30,216 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert. x-eventloop-thread-0) HTTP Request to /patients/094A2A91-6A37-4612-93BA-C36FD133CA9D failed, error id: 89c6c811-5224-420f-a160-9d465a7266bb-100: io.vertx.core.impl.NoStackTraceThrowable: Timeout

This is the second rather blocking problem.

I created a reproducer with my colleague here : 

https://github.com/haddadzineddine/quarkus-reactive-session-with-retry-error

To reproduce the problem, you can simply run the .sh file locally, which will send a number of requests. At first there will be 503 via the Exception Mapper : 

> " Error io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
>         [Exception 0] java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [155]: 'vert.x-eventloop-thread-0' current Thread [167]: 'executor-thread-2'
>         [Exception 1] java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [155]: 'vert.x-eventloop-thread-0' current Thread [167]: 'executor-thread-2' Multiple exceptions caught:
>         [Exception 0] java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [155]: 'vert.x-eventloop-thread-0' current Thread [167]: 'executor-thread-2'
>         [Exception 1] java.lang.IllegalStateException: HR000069: Detected use of the reactive Session from a different Thread than the one which was used to open the reactive Session - this suggests an invalid integration; original thread [155]: 'vert.x-eventloop-thread-0' current Thread [167]: 'executor-thread-2'"
> 

And after, you will notice the 500 error : 

> (vert.x-eventloop-thread-1) HTTP Request to /patients/55254C71-4ED3-4C2D-BB70-6964D1BA5F01 failed, error id: 89c6c811-5224-420f-a160-9d465a7266bb-4: io.vertx.core.impl.NoStackTraceThrowable: Timeout

Can you help me ? Thank in advance to the team, you rock !

### Expected behavior

Retry and keep the session

### Actual behavior

Error from Hibernate first and second the module is completely unable to respond 

### How to Reproduce?

1. Pull : https://github.com/haddadzineddine/quarkus-reactive-session-with-retry-error
2. Launch the module : quarkus:dev
3. Launch the script_simulation_requests.sh in local
4. Wait for the 503 and after the 500

**Comment by jponge** [comment] 2024-08-01 12:02
This happens because the retry operator needs a scheduled executor to perform the exponential backoff logic, hence each retry is made from a worker thread instead of a Vert.x thread, see https://quarkus.io/guides/vertx-reference#use-a-vert-x-context-aware-scheduler for more details.

You can try to fix the `delete` method with:

```java
public Uni<Long> delete(UUID uuid) {
    // This is the default scheduled executor of Mutiny:
    var delegate = Infrastructure.getDefaultWorkerPool();
    // This makes sure we re-use the correct Vert.x duplicated context after the retry:
    var scheduler = ContextAwareScheduler.delegatingTo(delegate).withCurrentContext();
    return this.patientService.get(uuid)
            .onItem().ifNull().failWith(PatientNotFound::new)
            .onFailure().retry()
            .withBackOff(Duration.ofMillis(100), Duration.ofSeconds(1))
            .withExecutor(scheduler)
            .atMost(3)
            .chain((patient) -> this.patientService.delete(patient.uuid()));
}
```

If you run the provided script you will now see error logs such as:

```
024-08-01 13:50:45,216 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-1) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,321 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-1) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,387 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-0) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,509 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-1) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,553 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-0) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,621 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-0) Error org.cgm.core.exceptions.patient.PatientNotFound null
2024-08-01 13:50:45,938 ERROR [org.cgm.res.han.ServerExceptionHandler] (vert.x-eventloop-thread-1) Error org.cgm.core.exceptions.patient.PatientNotFound null
```

I have no idea if this is what you expected, but at least you don't have incorrect thread calls to Hibernate Reactive 😃

**Comment by MaximeGil** [comment] 2024-08-01 13:04
Thank you for the answer @jponge, it works like a charm. I can understand the reason for this issue better now.

On the other hand, I still have a question about Quarkus behavior following a succession of errors of this kind. Why, after so many failed retries, is the module no longer able to serve incoming HTTP requests? 

That's what happened to me in my use case, where a single isolated function managed to ruin my entire microservice.

Thanks again !

**Comment by MaximeGil** [comment] 2024-08-01 13:18
I meant without your fix, sorry if I wasn't clear.
Because with your fix, yes I only have 404 response. That's the expected result.

Without your fix, if I run the script, I have first a lot of 503 (related to the Hibernate Reactive thing) and after minutes, a bunch of 500 error like this one "HTTP Request to /patients/55254C71-4ED3-4C2D-BB70-6964D1BA5F01 failed, error id: 89c6c811-5224-420f-a160-9d465a7266bb-4: io.vertx.core.impl.NoStackTraceThrowable: Timeout"

Wanted to understand the second part of my report also.

**Comment by jponge** [comment] 2024-08-01 13:18
@geoand might know

**Comment by jponge** [comment] 2024-08-01 13:19
BTW I'm closing this as not a bug, but the discussion can continue.

**Closed by jponge** 2024-08-01 13:19 UTC
Labels: kind/bug, area/panache, area/persistence, area/smallrye, area/vertx, area/hibernate-reactive, area/tracing, area/mutiny

**Comment by geoand** [comment] 2024-08-01 13:21
> Wanted to understand the second part of my report also.

Which part exactly?

**Comment by geoand** [comment] 2024-08-01 13:29
I'll actually have to run this on my own and see the problem in action. Hopefully soon.

Also cc @DavideD as this might be a problem with Hibernate Reactive

**Comment by MaximeGil** [comment] 2024-08-01 13:35
> Which part exactly?

My point was to understand why successive call to my API without the scheduler executor fix lead to this error : 

`(vert.x-eventloop-thread-1) HTTP Request to /patients/55254C71-4ED3-4C2D-BB70-6964D1BA5F01 failed, error id: 89c6c811-5224-420f-a160-9d465a7266bb-4: io.vertx.core.impl.NoStackTraceThrowable: Timeout
`

Even i understand the explanation given by @jponge and the Hibernate Reactive errors. It's strange to me that an entire microservice should be impacted by such a localized problem. Isn't that something that could be handled?

**Comment by geoand** [comment] 2024-08-01 13:37
Indeed it sounds strange. I'll try and have a look tomorroq

**Comment by geoand** [comment] 2024-08-01 13:56
There is nothing obviously wrong in the REST layer so this would need to be checked by @DavideD for the HR part

**Comment by DavideD** [comment] 2024-08-01 13:57
I will put it on my TODO list

**Comment by geoand** [comment] 2024-08-01 14:01
🙏🏼
