### ISSUE TITLE
java.nio.file.NoSuchFileException in io.quarkus.amazon.lambda.http.deployment.AmazonLambdaHttpProcessor#generateScripts

### ISSUE THREAD

**Issue by gregertw** [quarkusio/quarkus#32510] opened 2023-04-09 17:34 UTC
### Describe the bug

I have upgraded a project from stable to 3.0.0.RC2 and see that when I add io.quarkus:quarkus-amazon-lambda-http to an otherwise working project, I see the following error when running `quarkus build`:
`% quarkus build
> Task :quarkusBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':quarkusBuild'.
> There was a failure while executing work items
   > A failure occurred while executing io.quarkus.gradle.tasks.worker.BuildWorker
      > io.quarkus.builder.BuildException: Build failure: Build failed due to errors
                [error]: Build step io.quarkus.amazon.lambda.http.deployment.AmazonLambdaHttpProcessor#generateScripts threw an exception: java.lang.IllegalStateException: java.nio.file.NoSuchFileException: /Users/wedel/src/slack-armyknife-kotlin/build/quarkus-build/gen/bootstrap-example.sh
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:918)
                at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
                at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
                at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
                at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
                at java.base/java.lang.Thread.run(Thread.java:833)
                at org.jboss.threads.JBossThread.run(JBossThread.java:501)
        Caused by: java.nio.file.NoSuchFileException: /Users/wedel/src/slack-armyknife-kotlin/build/quarkus-build/gen/bootstrap-example.sh
                at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:106)
                at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
                at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:218)
                at java.base/java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:484)
                at java.base/java.nio.file.Files.newOutputStream(Files.java:228)
                at java.base/java.nio.file.Files.write(Files.java:3512)
                at io.quarkus.amazon.lambda.deployment.LambdaUtil.writeFile(LambdaUtil.java:50)
                at io.quarkus.amazon.lambda.http.deployment.AmazonLambdaHttpProcessor.generateScripts(AmazonLambdaHttpProcessor.java:106)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
                at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
                at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
                at java.base/java.lang.reflect.Method.invoke(Method.java:568)
                at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
                ... 6 more
`

### Expected behavior

generateScripts() should create bootstrap-example.sh and sam templates in build/quarkus-build/gen

### Actual behavior

The thrown error is a NoSuchFileException and on code inspection, I believe the culprit may be that the gen/ directory is not created.

### How to Reproduce?

Relevant build.gradle:
`plugins {
    id 'org.jetbrains.kotlin.jvm' version "1.8.10"
    id "org.jetbrains.kotlin.plugin.allopen" version "1.8.10"
    id 'io.quarkus'
}

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    implementation enforcedPlatform("${quarkusPlatformGroupId}:${quarkusPlatformArtifactId}:${quarkusPlatformVersion}")
    implementation 'io.quarkus:quarkus-kotlin'
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8'
    implementation 'io.quarkus:quarkus-arc'
    testImplementation 'io.quarkus:quarkus-junit5'
    implementation 'io.quarkus:quarkus-undertow:2.16.4.Final'
    implementation 'io.quarkus:quarkus-amazon-lambda-http'
    implementation 'jakarta.ws.rs:jakarta.ws.rs-api:3.1.0'
    implementation 'com.slack.api:bolt:1.28.0'
    implementation 'com.slack.api:bolt-jakarta-servlet:1.28.0'
    implementation 'com.amazonaws:aws-java-sdk-lambda:1.12.435'
    implementation 'com.amazonaws:aws-java-sdk-s3:1.12.435'
    implementation 'javax.xml.bind:jaxb-api:2.3.0'
    implementation 'ch.qos.logback:logback-classic:1.4.6'
    implementation 'org.slf4j:slf4j-api:1.7.28'
}
`

### Output of `uname -a` or `ver`

22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:58 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6020 arm64

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10) OpenJDK 64-Bit Server VM Temurin-17.0.6+10 (build 17.0.6+10, mixed mode)

### Quarkus version or git rev

3.0.0.CR2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.0.2

**Comment by geoand** [comment] 2023-04-10 06:16
I can confirm the problem occurs with Quarkus `3.0.0.CR1` and `3.0.0.CR2` but has since been fixed in the `main` branch

**Closed by geoand** 2023-04-10 06:16 UTC
Labels: kind/bug, area/kotlin, area/amazon-lambda
