### ISSUE TITLE
Quarkus 3.0.0.CR1/CR2 project - quarkus-maven-plugin:update fails, unable to resolve quarkus-update-recipes

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#32288] opened 2023-03-31 07:04 UTC
### Describe the bug

Quarkus 3.0.0.CR1 project - quarkus-maven-plugin:update fails with `Failed to resolve version for io.quarkus:quarkus-update-recipes:jar:LATEST` error.

```
 mvn quarkus:update
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:3.0.0.CR1:update (default-cli) @ code-with-quarkus ---
[WARNING] quarkus:update goal is experimental, its options and output might change in future versions
[INFO] Instructions to update this project from '3.0.0.CR1' to '2.16.5.Final':
[INFO]
[INFO] Recommended Quarkus platform BOM updates:
[INFO] Update: io.quarkus.platform:quarkus-bom:pom:3.0.0.CR1 -> 2.16.5.Final
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.536 s
[INFO] Finished at: 2023-03-31T08:59:13+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR1:update (default-cli) on project code-with-quarkus: Execution default-cli of goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR1:update failed: Failed to resolve artifact: io.quarkus:quarkus-update-recipes:LATEST: Failed to resolve artifact io.quarkus:quarkus-update-recipes:jar:LATEST: Failed to resolve version for io.quarkus:quarkus-update-recipes:jar:LATEST: Could not find metadata io.quarkus:quarkus-update-recipes/maven-metadata.xml in local (/Users/rsvoboda/.m2/repository) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```

### Expected behavior

Command finishes successfully 

### Actual behavior

Command fails

### How to Reproduce?

Download app from https://code.quarkus.io/?S=io.quarkus.platform%3A3.0

run `mvn quarkus:update`

### Output of `java -version`

Java 17

### Quarkus version or git rev

3.0.0.CR1

**Comment by aloubyansky** [comment] 2023-04-03 12:26
@rsvoboda is it still reproducible for you?

**Comment by rsvoboda** [comment] 2023-04-03 12:50
Yes, still able to reproduce

**Comment by rsvoboda** [comment] 2023-04-03 13:40
`rm -rf ~/.m2/repository/io/quarkus/quarkus-update-recipes` didn't help

Also tried custom local maven repo
```
~/Downloads/code-with-quarkus-update $ mvn quarkus:update -Dmaven.repo.local=/Users/rsvoboda/Downloads/qs-repo
... 
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR1:update (default-cli) on project code-with-quarkus: Execution default-cli of goal io.quarkus.platform:quarkus-maven-plugin:3.0.0.CR1:update failed: Failed to resolve artifact: io.quarkus:quarkus-update-recipes:LATEST: Failed to resolve artifact io.quarkus:quarkus-update-recipes:jar:LATEST: Failed to resolve version for io.quarkus:quarkus-update-recipes:jar:LATEST: Could not find metadata io.quarkus:quarkus-update-recipes/maven-metadata.xml in local (/Users/rsvoboda/Downloads/qs-repo) -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
```
```
~/Downloads/code-with-quarkus-update $ mvn -version
Apache Maven 3.8.7 (b89d5959fcde851dcb1c8946a785a163f14e1e29)
Maven home: /Users/rsvoboda/.sdkman/candidates/maven/current
Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /Users/rsvoboda/.sdkman/candidates/java/17.0.5-tem
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.3", arch: "x86_64", family: "mac"
```

**Comment by famod** [comment] 2023-04-05 22:00
Same here, Maven 3,8,8. On my private box, so no special repo manager or proxy involved.

**Comment by rsvoboda** [comment] 2023-04-11 08:29
@ia3andy is this on your radar? @gsmet feels like a problematic one for .Final

**Comment by rsvoboda** [comment] 2023-04-11 08:59
What's the property name for maven plugin? Assuming the above is for CLI

**Comment by ia3andy** [comment] 2023-04-11 09:03
@rsvoboda it doesn't work, I am ont it

**Comment by geoand** [comment] 2023-04-12 08:34
@ia3andy has this since been fixed?

**Comment by gsmet** [comment] 2023-04-12 08:46
Yes, it has been fixed. Let's close it.

**Closed by gsmet** 2023-04-12 08:46 UTC
Labels: kind/bug, area/maven
