### ISSUE TITLE
"no transaction is in progress" in @Transactional service method

### ISSUE THREAD

**Issue by jendib** [quarkusio/quarkus#21948] opened 2021-12-06 11:42 UTC
### Describe the bug

In a Quarkus 2.7.4 application running in non-native mode I have the following service:
```java
@ApplicationScoped
public class TestService {
    @Inject
    @Channel("channel-out")
    Emitter<Long> emitter;

    public void test() {
        MyEntity entity = new MyEntity();
        entity.id = 1L;
        entity.field = "Test";
        entity.persist();

        emitter.send(5L);
    }
}
```
When called from a JAXRS resource annotated with `@Transactional` it produces the following error:

```
2022-03-15 18:04:32,528 WARN  [com.arj.ats.arjuna] (executor-thread-0) ARJUNA012094: Commit of action id 0:ffffc0a8013a:dc52:6230c720:0 invoked while multiple threads active within it.
2022-03-15 18:04:32,529 WARN  [com.arj.ats.arjuna] (executor-thread-0) ARJUNA012107: CheckedAction::check - atomic action 0:ffffc0a8013a:dc52:6230c720:0 commiting with 2 threads active!
2022-03-15 18:04:32,529 WARN  [com.arj.ats.jta] (executor-thread-0) ARJUNA016039: onePhaseCommit on < formatId=131077, gtrid_length=35, bqual_length=36, tx_uid=0:ffffc0a8013a:dc52:6230c720:0, node_name=quarkus, branch_uid=0:ffffc0a8013a:dc52:6230c720:3, subordinatenodename=null, eis_name=0 > (io.agroal.narayana.LocalXAResource@2037e82c) failed with exception XAException.XA_RBROLLBACK: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
	at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
	at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
	at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
	at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
	at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:365)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:165)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	at org.acme.GreetingResource_Subclass.hello(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLException: Enlisted connection used without active transaction
	at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:394)
	at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:353)
	at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
	... 49 more

2022-03-15 18:04:32,539 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello failed, error id: f337656d-b571-4f6a-af7e-31d46d819909-1: org.jboss.resteasy.spi.UnhandledException: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:105)
	at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:359)
	at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
	at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
	at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:151)
	at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:91)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$13.runWith(VertxCoreRecorder.java:543)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
	at org.acme.GreetingResource_Subclass.hello(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
	at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:660)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:524)
	at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:474)
	at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:476)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:434)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:408)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:69)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
	... 15 more
Caused by: javax.transaction.RollbackException: ARJUNA016053: Could not commit transaction.
	at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1307)
	at com.arjuna.ats.internal.jta.transaction.arjunacore.BaseTransaction.commit(BaseTransaction.java:128)
	at io.quarkus.narayana.jta.runtime.CDIDelegatingTransactionManager.commit(CDIDelegatingTransactionManager.java:105)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.endTransaction(TransactionalInterceptorBase.java:365)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:165)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:103)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:57)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
	at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
	at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
	at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
	at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
	... 31 more
	Suppressed: javax.transaction.xa.XAException: Error trying to transactionCommit local transaction: Enlisted connection used without active transaction
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:140)
		at io.agroal.narayana.LocalXAResource.xaException(LocalXAResource.java:134)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:72)
		at com.arjuna.ats.internal.jta.resources.arjunacore.XAResourceRecord.topLevelOnePhaseCommit(XAResourceRecord.java:702)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.onePhaseCommit(BasicAction.java:2400)
		at com.arjuna.ats.arjuna.coordinator.BasicAction.End(BasicAction.java:1502)
		at com.arjuna.ats.arjuna.coordinator.TwoPhaseCoordinator.end(TwoPhaseCoordinator.java:96)
		at com.arjuna.ats.arjuna.AtomicAction.commit(AtomicAction.java:162)
		at com.arjuna.ats.internal.jta.transaction.arjunacore.TransactionImple.commitAndDisassociate(TransactionImple.java:1295)
		... 43 more
	Caused by: java.sql.SQLException: Enlisted connection used without active transaction
		at io.agroal.pool.ConnectionHandler.verifyEnlistment(ConnectionHandler.java:394)
		at io.agroal.pool.ConnectionHandler.transactionCommit(ConnectionHandler.java:353)
		at io.agroal.narayana.LocalXAResource.commit(LocalXAResource.java:69)
		... 49 more
```

### Expected behavior

`@Transactional` methods should never throw "no transaction is in progress".

### How to Reproduce?

Here is a reproducer: [issue-21948.zip](https://github.com/quarkusio/quarkus/files/8255657/issue-21948.zip)
Running the JUnit is enough to trigger the error.

### Output of `java -version`

OpenJDK 17

### Quarkus version or git rev

2.7.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3

**Comment by famod** [comment] 2021-12-06 19:28
Have you verified it's not a transaction timeou

**Comment by jendib** [comment] 2021-12-06 20:26
I should have an error log in that case no? I don't have anything except the error I pasted.

**Comment by famod** [comment] 2021-12-06 22:08
There should be at least a warning, which might not be directly next to the actual error.

**Comment by jendib** [comment] 2021-12-06 23:31
I checked 5min of log before and after and I have nothing else.

**Comment by jendib** [comment] 2022-03-15 17:12
@mkouba I added a reproducer to this issue. It seems to come from sending a Kafka message from inside a `@Transactional` method.

**Comment by mkouba** [comment] 2022-03-16 07:57
My guess is that it's related to integration of context-propagation and mutiny (which is used in reactive messaging). @FroMage @cescoffier @manovotn is there a way to disable the context propagation declaratively?

CC @Ladicek

**Comment by cescoffier** [comment] 2022-03-16 08:10
`send` is async, transactions are not. So, you need to "block" until the sent message is acked:

```java
emitter.send(x).toCompletableFuture().join();
```

Or return the `CompletionStage<Void>`.

**Comment by mkouba** [comment] 2022-03-16 08:26
> `send` is async, transactions are not. So, you need to "block" until the sent message is acked:

What if you don't want to wait for the result at all? Just fire-and-forget behavior and do not propagate the transaction at all...

**Comment by cescoffier** [comment] 2022-03-16 08:54
Because it causes that kind of issue. What surprised me is that in general it happens when you send the persisted object. Here is seems to be a constant value.

**Comment by jendib** [comment] 2022-03-16 09:07
I actually worked around this issue by firing an event which is listened in a `TransactionPhase.AFTER_SUCCESS` method (and this method send the Kafka message).

The only issue I may have here is that the error message is very hard to understand, it took me a while to see that the Kafka message was the problem.

**Comment by mkouba** [comment] 2022-03-16 09:15
> Because it causes that kind of issue. 

??

> What surprised me is that in general it happens when you send the persisted object. Here is seems to be a constant value.

I'm no CP expert but I think that it does not matter, i.e. the tx is propagated no matter what the payload is. And later when the `TestService#test()` method completes JTA attempts to commit the transaction which is associated with multiple threads.

**Comment by cescoffier** [comment] 2022-03-16 09:22
Exactly.However, if you join, the problem goes away as the tx is not accessed concurrently anymore. 

If you want to do an out of band processing you cannot use the emitter but you will need an intermediate event bus 'send' which will not propagate the tx (because it uses the vertx bare API which does not support CP).

**Comment by mkouba** [comment] 2022-03-16 09:42
> Exactly.However, if you join, the problem goes away as the tx is not accessed concurrently anymore.
> 
> If you want to do an out of band processing you cannot use the emitter but you will need an intermediate event bus 'send' which will not propagate the tx (because it uses the vertx bare API which does not support CP).

Ok, my point is that it should be possible to state declaratively/programatically that TX does not need to be propagated. Is this documented somewhere?

**Comment by cescoffier** [comment] 2022-03-16 09:45
Smallrye has custom annotation I believe, but I never used them.

**Comment by manovotn** [comment] 2022-03-16 12:04
@mkouba I remember there was a talk about that annotation, I am not sure it came to fruition.
Maybe this is the one you are looking for - https://github.com/smallrye/smallrye-context-propagation/blob/main/api/src/main/java/io/smallrye/context/api/CurrentThreadContext.java ?

There should also be some global settings but I don't suppose that interests us here.

**Comment by mkouba** [comment] 2022-03-18 13:53
Hm, I don't understand how the `@CurrentThreadContext` annotation should be used. Do we have any docs/examples?

**Comment by manovotn** [comment] 2022-03-18 14:40
So, quickly looking into it, it allows to temporarily override the thread context settings.

I.e. there is some global settings that are applied WRT what contexts are propagated/cleared. This annotation changes it for the scope of the method. That means that any CP action originating from that method can choose to propagate something different to what it would normally do.

It is however an interceptor binding so its applicable only to beans.

[Implementing interceptor](https://github.com/smallrye/smallrye-context-propagation/blob/main/core/src/main/java/io/smallrye)/context/impl/cdi/SmallRyeCurrentThreadContextInterceptor.java
[Test](https://github.com/smallrye/smallrye-context-propagation/blob/main/tests/src/test/java/io/smallrye/context/test/cdi/providedBeans/CurrentThreadContextInterceptorTest.java)

I am not sure it's documented anywhere and I don't even recall when or why we added this in the first place.
But the original PR also mentions Mutiny usage, see https://github.com/smallrye/smallrye-context-propagation/pull/201

**Comment by ahofmeister** [comment] 2022-04-11 04:49
Same problem here, worked around like @jendib did.

**Comment by coiouhkc** [comment] 2024-06-21 12:42
Also duplicate of #18450?

**Comment by geoand** [comment] 2024-09-20 10:47
Is this still an issue?

**Comment by geoand** [comment] 2024-10-02 07:44
Closing for lack of feedback

**Closed by geoand** 2024-10-02 07:44 UTC
Labels: kind/bug, area/narayana, triage/needs-feedback
