### ISSUE TITLE
TimeoutException on application startup after upgrading to v2.12.3 from v2.7.4

### ISSUE THREAD

**Issue by joyitaevolphin** [quarkusio/quarkus#28222] opened 2022-09-27 12:51 UTC
### Describe the bug

We are upgrading quarkus version from 2.7.4 to 2.12.3 for our app. Application startup throws a Timeout exception with the upgraded Quarkus version. It starts up without any issue with v2.7.4

So we need to add any new configuration for flyway to work with 2.12.3

### Expected behavior

Application should startup without any issue.

### Actual behavior

Getting this error on application startup:

```
Powered by Quarkus 2.12.3.Final
2022-09-27 15:42:19,928[WARN][null.null][Quarkus Main Thread] Unrecognized configuration key "quarkus.resteasy.gzip.enabled" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo  
2022-09-27 15:42:57,595[INFO][org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info][Quarkus Main Thread] Flyway Community Edition 9.1.5 by Redgate  
2022-09-27 15:42:57,603[INFO][org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info][Quarkus Main Thread] See what's new here: https://flywaydb.org/documentation/learnmore/releaseNotes#9.1.5  
2022-09-27 15:42:57,659[INFO][org.flywaydb.core.internal.logging.slf4j.Slf4jLog.info][Quarkus Main Thread]   
2022-09-27 15:43:03,725[ERROR][io.quarkus.runtime.ApplicationLifecycleManager.run][Quarkus Main Thread] Failed to start application (with profile dev): java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
	at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
	at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
	at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
	at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
	at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
	at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:146)
	at org.flywaydb.core.Flyway.migrate(Flyway.java:126)
	at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:76)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:69)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runner.GeneratedMain.main(Unknown Source)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
	at java.base/java.lang.Thread.run(Thread.java:833)
  
```

### Output of `java -version`

openjdk version "17.0.1" 2021-10-19 LTS OpenJDK Runtime Environment Corretto-17.0.1.12.1 (build 17.0.1+12-LTS) OpenJDK 64-Bit Server VM Corretto-17.0.1.12.1 (build 17.0.1+12-LTS, mixed mode, sharing)

### Quarkus version or git rev

2.12.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

------------------------------------------------------------ Gradle 7.3.3 ------------------------------------------------------------  Build time:   2021-12-22 12:37:54 UTC Revision:     6f556c80f945dc54b50e0be633da6c62dbe8dc71  Kotlin:       1.5.31 Groovy:       3.0.9 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          17.0.1 (Amazon.com Inc. 17.0.1+12-LTS) OS:           Windows 10 10.0 amd64

**Comment by geoand** [comment] 2022-09-27 12:52
Can you provide a sample application that exhibits this behavior please?

**Comment by tveon** [comment] 2022-10-08 04:52
I've been seeing the same problem, but since I'm not sure what's causing this, I don't know how to create a reproducer. I expect that the problem is related to the environment - probably the database/Flyway state, as it eventually managed to apply the Flyway migrations and start up (and we only saw it in some environments).

FWIW our application is  pure java build with Maven, and the problem manifested on AWS EKS...

Perhaps the best "remedy" would be for this log-line to also include the message of the exception and not just the type:
```
ERROR [io.qua.run.Application] (main) [tenantID=] Failed to start application (with profile prod): java.util.concurrent.TimeoutException
```

**Comment by joyitaevolphin** [comment] 2022-11-14 09:57
> Perhaps the ~best~ first "remedy" would be for this log-line to also include the message of the exception and not just the type of the exception:

Hello @tveon,
Would you mind sharing how did you fix the issue?
I was busy with some other project, so this problem took a backseat. Now I am trying to upgrade to 2.14.0.Final and facing the same issue.

Thanks.

**Comment by joaomfas** [comment] 2022-12-12 14:58
@geoand I am also having this issue with version 2.13.4, the log is exactly the same.

**Comment by geoand** [comment] 2022-12-12 15:07
If you have a sample application for us to look at, that would be great

**Comment by geoand** [comment] 2023-02-06 08:46
Closing as we never got a reproducer

**Closed by geoand** 2023-02-06 08:46 UTC
Labels: kind/bug, triage/needs-reproducer

**Comment by ma-sharifi** [comment] 2023-04-05 14:51
Hi team,
I have the same problem when I debug my code.
What should I do?

Quarkus version: 2.12.1.Final and 2.16.5.Final, both have this problem.
uname -a: Darwin Mahdis-MBP-2.home 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:07:28 PDT 2022; root:xnu 8020.140.41~1/RELEASE_ARM64_T8110 arm64 

Java: openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13, mixed mode, sharing)
Flyway: default
DB: Postgresql

2023-04-05 16:45:43,357 INFO  [io.qu.de.de.IsolatedDevModeMain] Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-04-05 16:45:43,316 ERROR [io.qu.ru.Application] Failed to start application (with profile dev): java.util.concurrent.TimeoutException
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:204)
        at io.agroal.pool.ConnectionPool.handlerFromSharedCache(ConnectionPool.java:296)
        at io.agroal.pool.ConnectionPool.getConnection(ConnectionPool.java:248)
        at io.agroal.pool.DataSource.getConnection(DataSource.java:86)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:48)
        at org.flywaydb.core.internal.jdbc.JdbcConnectionFactory.<init>(JdbcConnectionFactory.java:75)
        at org.flywaydb.core.FlywayExecutor.execute(FlywayExecutor.java:146)
        at org.flywaydb.core.Flyway.migrate(Flyway.java:126)
        at io.quarkus.flyway.runtime.FlywayRecorder.doStartActions(FlywayRecorder.java:76)
        at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy_0(Unknown Source)
        at io.quarkus.deployment.steps.FlywayProcessor$startActions1770701860.deploy(Unknown Source)
        at io.quarkus.runner.ApplicationImpl.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:101)
        at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:110)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:67)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
        at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
        at io.quarkus.runner.GeneratedMain.main(Unknown Source)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:103)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by pehunka** [comment] 2023-09-15 17:05
In case someone else will bump into this issue. .I saw it when my ECS pod didn't had appropriate security group rule to access RDS. 

From what I experienced, network socket is created from QUARKUS >> RDS , but connection is not established.
Use this command from pod to check, if that is your case:
``netstat -nputw``
