### ISSUE TITLE
Lambda native does not work if it has dependency on quarkus-resteasy

### ISSUE THREAD

**Issue by mihapolak** [quarkusio/quarkus#5859] opened 2019-11-29 07:27 UTC
**Describe the bug**
Following [lambda guide](https://quarkus.io/guides/amazon-lambda) works perfectly in native mode. But when adding dependency on io.quarkus:quarkus-resteasy it fails with
`java.lang.IllegalStateException: Failed to create cache dir
 at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332)
 at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87)
 at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:165)`

Found this (already fixed) [bug
](https://github.com/quarkusio/quarkus/issues/4254) that provided workaroud with forcing java.tmpdir to /tmp.
Hovever the official 1.0.0.Final guide (and maven archetype) does not use additional sh bootstrap file, but simply  renames native executable to bootstrap.
On the side note, local invocation of lambda function with AWS SAM framework works without problem.

**Expected behavior**
Guide and archetype should provide valid infrormation.

**To Reproduce**
1. Create aws lambda project found here: https://quarkus.io/guides/amazon-lambda
2. Add extension quarkus-resteasy to the project and create a resteasy service within the code.
3. Build natively and upload to aws lambda.
4. execute lambda function

**Comment by geoand** [comment] 2019-11-29 11:14
cc @evanchooly

**Comment by mehdi-reza** [comment] 2019-12-03 11:01
Hi

I am facing the same problem, no idea how to set -Djava.io.tmpdir=/tmp and 
-Dvertx.cacheDirBase=/tmp/vertx -Djava.io.tmpdir=/tmp system property in aws lambda deployment.

Tried by setting --environment flag in aws lambda create-function by defining JAVA_OPTS property, but did not make any difference.

The cloudwatch events are showing 
--
java.lang.IllegalStateException: Failed to create cache dir
 
Regards

![image](https://user-images.githubusercontent.com/5369680/70045602-32f80d80-15e6-11ea-8647-a5e8b7b07eee.png)

**Comment by mehdi-reza** [comment] 2019-12-03 11:12
> **Describe the bug**
> Following [lambda guide](https://quarkus.io/guides/amazon-lambda) works perfectly in native mode. But when adding dependency on io.quarkus:quarkus-resteasy it fails with
> `java.lang.IllegalStateException: Failed to create cache dir at io.vertx.core.file.impl.FileResolver.setupCacheDir(FileResolver.java:332) at io.vertx.core.file.impl.FileResolver.<init>(FileResolver.java:87) at io.vertx.core.impl.VertxImpl.<init>(VertxImpl.java:165)`
> 
> Found this (already fixed) [bug ](https://github.com/quarkusio/quarkus/issues/4254) that provided workaroud with forcing java.tmpdir to /tmp.
> Hovever the official 1.0.0.Final guide (and maven archetype) does not use additional sh bootstrap file, but simply renames native executable to bootstrap.
> On the side note, local invocation of lambda function with AWS SAM framework works without problem.
> 
> **Expected behavior**
> Guide and archetype should provide valid infrormation.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. Create aws lambda project found here: https://quarkus.io/guides/amazon-lambda
> 2. Add extension quarkus-resteasy to the project and create a resteasy service within the code.
> 3. Build natively and upload to aws lambda.
> 4. execute lambda function

Hi

Have you tried printing java.io.tmpdir system property in rest endpoint and invoke it with sam local ... the set value should be printed!! The problem is it is not clear how to set java.io.tmpdir system property at build/run time in native image.

**Comment by evanchooly** [comment] 2019-12-04 16:25
I'm not convinced you're using the correct module, honestly.  if you're wanting to use resteasy based services, you should be using `amazon-lambda-http` instead which explicitly supports resteasy based services and routing.

**Comment by mehdi-reza** [comment] 2019-12-04 16:30
+1

**Comment by mihapolak** [comment] 2019-12-12 10:19
@evanchooly , I agree with you to use amazon lambda http. But I guess there are other components using vertx?
@mehdi-reza, local sam invoke shows /var/tmp/ (if not changed with custom bootstrap file), which obviously works within local tests but not in case of actual aws deployment.

**Comment by louisbros** [comment] 2020-01-04 22:57
I'm also facing this issue when using the `quarkus-mailer` with `quarkus-amazon-lambda`:
```
ERROR [io.qua.application] (main) Failed to start application: java.lang.IllegalStateException: Failed to create cache dir
```

**Comment by patriot1burke** [comment] 2020-02-11 22:13
@mihapolak Sorry for very late reply.

* We are trying to avoid creating a bootstrap shell script that wraps the native executable as we're trying to reduce coldstart latency.  A wrapper shell script just increases cold start latency
* I've been demoing Native amazon-lambda and amazon-lambda-http a lot and I have yet to have to supply the java.io.tmpdir system property.
* I'll automatically set these system properties in the extension to hopefully avoid this requirement

**Comment by patriot1burke** [comment] 2020-02-13 22:36
@evanchooly Solution for the system property issues is to just set java.io.tmpdir=/tmp and
vertx.cacheDirBase=/tmp/vertx via a SystemPropertyBuildIItem.  Personally though I could never reproduce this issue.  I'll assign this to myself if you like.

@mihapolak Justin is right in that you can't just add quarkus-resteasy, you ahve to add amazon-lambda-http too and follow the quarkus docs for setting up the API gateway with a sam.yaml file.

**Comment by evanchooly** [comment] 2020-02-14 03:15
Sounds great @patriot1burke.

**Comment by oztimpower** [comment] 2020-05-27 13:23
AmazonLambdaCommonProcessor now forces the temp dirs post @patriot1burke updates, suggest this one can be closed?

**Closed** 2020-06-01 12:51 UTC
Labels: area/amazon-lambda, kind/bug
