### ISSUE TITLE
Quarkus 3: `@InjectMock` with Producer

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#32944] opened 2023-04-27 09:35 UTC
### Describe the bug

I just updated to Quarkus 3.0.1.Final. Now I have a problem with a `@QuarkusTest`. I have a CDI-producer which has a `@RequestScoped` producer-method. In the test, I'm trying to mock the bean which would otherwise be produced with `@InjectMock`. This does not work anymore with Quarkus 3, it complains:

`jakarta.enterprise.context.ContextNotActiveException: RequestScoped context was not active when trying to obtain a bean instance for a client proxy of PRODUCER_METHOD bean`

I do not see any reason why the producer needs to be called here? I just want a mock of the bean. I've tried to annotate the test-class with `@ActivateRequestScope` but that had no effect.

It worked with 2.13.3 (and also 2.16 in the reproducer).

### Expected behavior

The original producer should not be called and therefore it should not be needed to have an active request scope.

### Actual behavior

An exception is thrown.

### How to Reproduce?

1. Extract zip: [mock-producer-request.zip](https://github.com/quarkusio/quarkus/files/11341913/mock-producer-request.zip)
2. There are 2 projects in it with the same code: One with version 2.16.6.Final and one with 3.0.1.Final
3. Start the included test in both of them, it will work with 2.x, but not with 3.x

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19045.2728]

### Output of `java -version`

OpenJDK Runtime Environment Corretto-17.0.7.7.1 (build 17.0.7+7-LTS)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by mkouba** [comment] 2023-04-27 11:27
That's very likely a regression caused by https://github.com/quarkusio/quarkus/pull/32409 :-(.

**Comment by wicksim** [comment] 2023-04-27 12:11
Is there a known workaround? I think no, because it is not possible to activate the request context during the phase of the wiring, is it?

**Comment by mkouba** [comment] 2023-04-27 12:40
> Is this related to this issue I just raised?
> 
> #32950

Yes, that one looks like a duplicate of this issue.

**Comment by TonyWeston** [comment] 2023-04-27 12:45
Thanks - I'll close it....

**Closed** 2023-04-28 05:52 UTC
Labels: kind/bug, area/arc, area/testing, env/windows

**Comment by ivansenic** [comment] 2023-04-28 15:22
Is this only coming in the `3.1.x` version? Will this be back-ported to `3.0.x`? We are in the same situation, `3.0.0.CR2` had all unit and integration tests green and with `3.0.1` a lot of tests fail.. We can not move forward with the 3.x without this.. :cry:

**Comment by mkouba** [comment] 2023-04-28 15:25
> Is this only coming in the `3.1.x` version? Will this be back-ported to `3.0.x`? We are in the same situation, `3.0.0.CR2` had all unit and integration tests green and with `3.0.1` a lot of tests fail.. We can not move forward with the 3.x without this.. cry

The fix should be backported in the next 3.0.x version.

**Comment by f0nZ** [comment] 2023-05-03 16:45
This issue is fixed for me with [3.0.2.Final](https://github.com/quarkusio/quarkus/milestone/248)
