### ISSUE TITLE
Quarkus 0.14 problem with sourceDirectory specified in Pom

### ISSUE THREAD

**Issue by uberto** [quarkusio/quarkus#2367] opened 2019-05-08 08:20 UTC

**Comment by uberto** [comment] 2019-05-08 08:26
I have a Kotlin project on Quarkus
https://github.com/uberto/quarkus-quickstarts/tree/master/kotlin-rest-http4k

since I upgrade to 0.14 hot replacement stopped working (still work if I revert to 0.13)

After a bit of digging, I found that it works if I remove the project.base dir property, from this:
        <sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>
        <testSourceDirectory>${project.basedir}/src/test/kotlin</testSourceDirectory>
   
to this
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>


This is a only partial fix anyway because, after doing that the quarkus:dev always reload the project, even when no file has changed.
(this could be a completely indipendent issue anyway, but it is not present in quarkus 0.13)

**Comment by geoand** [comment] 2019-05-09 06:17
Hi,

I tried to run your example, but it seems like compilation is failing. 

```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.3.21:compile (compile) on project kotlin-rest-http4k: Compilation failure: Compilation failure: 
[ERROR] /home/gandrian/Desktop/quarkus-quickstarts-master/kotlin-rest-http4k/src/main/kotlin/com/acme/model/JsonHelper.kt:[5,14] Unresolved reference: json

```

Is there something I am missing (all I did was `mvn compile`)? If not, could you update it so I can check about the second problem you mention?

**Comment by uberto** [comment] 2019-05-09 08:17
Sorry I forget to commit the updated pom, now it should be ok.

I checked and same behaviour is with graalVM rc14 and rc16

Uberto

**Comment by geoand** [comment] 2019-05-09 08:48
OK thanks! I will check it again soon.

**Comment by geoand** [comment] 2019-05-09 09:00
Not sure what the problem is with your project, but if you follow the steps in: https://quarkus.io/guides/kotlin to create a Kotlin project, things work as expected.

**Comment by uberto** [comment] 2019-05-09 09:18
Mmmh... actually not. At least on my machine.
It was the first think I tried and now I retested to be sure.

I did:
1)
mvn io.quarkus:quarkus-maven-plugin:0.14.0:create     -DprojectGroupId=org.acme     -DprojectArtifactId=rest-kotlin     -DclassName="org.acme.rest.GreetingResource"     -Dpath="/greeting"     -Dextensions="kotlin"

2)
mvn compile quarkus:dev

3) 
see the hello in the browser at localhost:8080

4) 
changed "hello" to "hello!!", saved the file

5) browser still show hello no matter if I refresh.


this is on my local linux ubuntu machine
if I change to quarkus 13 or early it works flawless

**Comment by geoand** [comment] 2019-05-09 09:36
Gotcha, I'll need to go over it more extensively over the weekend and see what exactly breaks it and why.

**Comment by geoand** [comment] 2019-05-09 14:48
OK, I have figured out why setting `<sourceDirectory>${project.basedir}/src/main/kotlin</sourceDirectory>` doesn't work.
The culprit is this piece of code: https://github.com/quarkusio/quarkus/blob/158df1697313fc3f7d1e2294747648fe6876fae9/independent-projects/bootstrap/core/src/main/java/io/quarkus/bootstrap/resolver/maven/workspace/LocalProject.java#L189

Basically `getRawModel().getBuild().getSourceDirectory()` will contain the literal `${project.basedir}/src/main/kotlin` instead of the expanded value. @aloubyansky is this to be expected or is it a bug? If it's the expected behavior we should probably find a way around it because the official Kotlin documentation mentions the use of `${project.basedir}` (see [this](https://kotlinlang.org/docs/reference/using-maven.html#compiling-kotlin-only-source-code)).

The solution for the time being is to remove `${project.basedir}` altogether. When I did this, the generated project worked perfectly with Dev mode.
I will open a relevant PR for the Kotlin template used in project creation.

**Comment by aloubyansky** [comment] 2019-05-09 14:53
It's a bug. We should be getting this into from the maven plugin instead. For now though, we could fix the LocalProject to resolve it properly.

**Comment by geoand** [comment] 2019-05-09 14:58
@aloubyansky I'd be glad to fix it on `LocalProject` if you give a pointer on where to look for resolving properties. I very superficial look at the code didn't give me any clues :)

**Comment by aloubyansky** [comment] 2019-05-09 15:02
Just check whether the path begins with `${project.basedir}` and if it does replace it with `this.dir.toString()`.

**Comment by geoand** [comment] 2019-05-09 15:04
Ah ok :), I was thinking about actually resolving the maven property :P. Will follow your suggestion :)

**Comment by geoand** [comment] 2019-05-09 15:14
@aloubyansky PR opened: https://github.com/quarkusio/quarkus/pull/2389

**Closed** 2019-05-09 18:21 UTC
