### ISSUE TITLE
Tests fail after quarkus:dev run

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#7581] opened 2020-03-04 20:22 UTC
When running mvn package (no clean) after quarkus:dev, 1. tests fail 2. with a weird inlined exception in the console.

```
# build Quarkus master
./mvn clean install -DskipTests

# create new project
cd /tmp
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create -DprojectGroupId=org.acme -DprojectArtifactId=test -DclassName="org.acme.GreetingResource" -Dpath="/greeting"   -DplatformArtifactId=quarkus-bom -DplatformVersion=999-SNAPSHOT

# run quarkus:dev
cd test
./mvn clean compile quarkus:dev

# CTRL+C
# start package
./mvnw package
^[[A^[[A ~  Dow  nob  banner-test  mvn package
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< org.acme:banner-test >------------------------
[INFO] Building banner-test 1.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ banner-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ banner-test ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ banner-test ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /Users/emmanuel/Downloads/nobackup/banner-test/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ banner-test ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 2 source files to /Users/emmanuel/Downloads/nobackup/banner-test/target/test-classes
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ banner-test ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.acme.GreetingResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.28 s <<< FAILURE! - in org.acme.GreetingResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.011 s  <<< ERROR!
java.lang.RuntimeException: java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: io.quarkus.test.common.http.TestHTTPConfigSourceProvider not a subtype
Caused by: java.lang.RuntimeException: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: io.quarkus.test.common.http.TestHTTPConfigSourceProvider not a subtype
Caused by: java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.ConfigSourceProvider: io.quarkus.test.common.http.TestHTTPConfigSourceProvider not a subtype

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   GreetingResourceTest.testHelloEndpoint » Runtime java.lang.RuntimeException: j...
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.166 s
[INFO] Finished at: 2020-03-04T21:19:05+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.22.1:test (default-test) on project banner-test: There are test failures.
[ERROR]
[ERROR] Please refer to /Users/emmanuel/Downloads/nobackup/banner-test/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
```

If `./mvnw clean package` is run, then no failure occurs.

**Comment by emmanuelbernard** [comment] 2020-03-04 20:22
@gastaldi do you mind looking at it. 
If you can't @stuartwdouglas can you check it out. Looks like a classloader related issue.

**Comment by maxandersen** [comment] 2020-03-04 20:37
this does look like a blocker to me btw.

**Comment by gastaldi** [comment] 2020-03-04 20:55
@aloubyansky this looks similar to the error wehad in Gradle, no?

**Comment by gastaldi** [comment] 2020-03-04 21:17
@stuartwdouglas assigning it to you, as I got zero cycles today :(

**Comment by aloubyansky** [comment] 2020-03-04 21:45
This is due to the classpath caching. Both `quarkus:dev` and `test` create the deployment classpath cache unless it already exists in the target dir. Except that it appears to be different for the dev and test. So if the dev ran first it will be missing the test deps. I guess it's a regression. I may be wrong but I think the deployment classpath previously shouldn't have contained the test deps.

**Comment by aloubyansky** [comment] 2020-03-04 21:47
Ah, of course, it's because now the hole app model is persisted instead of the deployment only part. The file name `deployment.cp` didn't change though.

**Comment by aloubyansky** [comment] 2020-03-04 21:52
I wouldn't classify this as a blocker for the CR though.

**Comment by emmanuelbernard** [comment] 2020-03-04 21:59
So we could either find a way to unify the work or segregate the cache for the two use cases (or three if we consider packaging as one).

**Comment by aloubyansky** [comment] 2020-03-04 22:16
Actually, changing the file name by appending the launch mode to it would be a one line fix. Let me see if I can do that now.

**Comment by gastaldi** [comment] 2020-03-05 00:03
@aloubyansky hero! Fix merged.

**Closed** 2020-03-05 00:02 UTC
Labels: area/core, kind/bug
