### ISSUE TITLE
unable to delete s3 object with = in the key path using quarkus native executable with graalvm

### ISSUE THREAD

**Issue by vaswanijitesh** [quarkusio/quarkus#9501] opened 2020-05-20 17:37 UTC
**Describe the bug**
Unable to delete s3 object with = in the key path using quarkus native executable with graalvm. if I use java 11 runtime for my quarkus jar deployed as a lambda, then it works successfully!

This code is using a AWS SDK V2 S3Client to delete a key from a bucket where there is a = sign in the name of a directory which is in the path of a key. For example
Bucket name: bucket
Key Name: root-dir/time=14-02/file.ext
This is being deployed as AWS Lambda.
Unable to delete the S3 object using custom runtime in Lambda when deploying Quarkus Native Executable within GraalVM. 
But it works when using Java 11 runtime in Lambda when deploying the .jar

**Expected behavior**
The key gets deleted

**Actual behavior**
{
"errorType": "software.amazon.awssdk.services.s3.model.S3Exception",
"errorMessage": "The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: S3, Status Code: 403, Request ID: 86EB1525A8A8DCCC)"
}

**To Reproduce**
1. Open your S3 bucket.
2. Create a directory with = in the name. eg - key=1 as the directory name.
3. Upload a file in that directory. eg file.jpg

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:  osx 10.5
 - Output of `java -version`:  open-jdk-11 11.0.2
 - GraalVM version (if different from Java): 19.3.1 CE
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): mvn 3.6.2

**Additional context**
(Add any other context about the problem here.)

**Comment by geoand** [comment] 2020-05-21 07:12
Thanks for reporting,

maybe it's because I haven't used the AWS stuff myself, but reading the description I don't see how this can reproduced. 
Can you please enrich the description?

Thanks

**Comment by vaswanijitesh** [comment] 2020-05-21 15:14
I am attaching the code here :) Check out the vaswani.thirdparty.quarkus.TestLambda.java
[vaswani-quarkus.zip](https://github.com/quarkusio/quarkus/files/4663180/vaswani-quarkus.zip)

**Comment by vaswanijitesh** [comment] 2020-05-21 15:25
Updated the description. Please let me know if you need more information on any aspect of it.

**Comment by oztimpower** [comment] 2020-05-22 09:47
@vaswanijitesh Thanks, I have your bundle and I'm testing it. That error message is the AWS Signature4 header, which the AWS SDK signs each request with.

**Comment by oztimpower** [comment] 2020-05-22 09:51
What's the significance of you calling out a key with an equals sign in it? Have you tested other key names?

i.e. 
directory/file
file

I'm testing the simple use case first, just a file at the root of a bucket. All objects are at the root, with the prefix (directory) merely just characters of the key, as I'm sure you're aware.

**Comment by oztimpower** [comment] 2020-05-22 10:50
Ok, so yes I have validated the alternate use cases for the keys, and do get the same error for the "=", however if you check the AWS documentation it explicitly calls this out, and certain characters may require special encoding, "=" being one of them. I appreciate you are seeing this triggered with GraalVM, however I do recommend you avoid such a character, given the AWS documentation. 

The error is from the AWS Java SDK v2, not being able to generate the signature, i.e. it's the encoding of the "=" at issue.

**Comment by oztimpower** [comment] 2020-05-22 10:50
https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html#object-keys

**Comment by oztimpower** [comment] 2020-05-22 11:11
@geoand In simple terms the JVM and GraalVM are encoding the url string different for the HTTPS action. The character "=" is not in the set of characters recommended for use by AWS for S3 object names (as explained above), indeed it's explicitly listed as a character to be avoided, that may cause problems, and may need hex encoding to work. 

It's not something Quarkus can control specifically, so I would suggest closing this issue.

**Comment by geoand** [comment] 2020-05-22 12:19
Thanks a lot for the info @oztimpower

**Closed by geoand** 2020-05-22 12:19 UTC
Labels: kind/bug

**Comment by vaswanijitesh** [comment] 2020-05-22 15:19
Thanks for all your effort. One thing though and I do understand AWS recommends otherwise, but JVM works so I thought there might be something to it where Quarkus is erroring out. So, you believe this issue arises from GraalVM? Thanks :)

**Comment by gboro54** [comment] 2020-05-22 22:36
Im going to chime in and think this is a bug in Graal. While I can understand the special handling argument when dealing with things like Parquet and partitions the = is in the name is a standard and all over the place. S3 is often leveraged as a replacement for HDFS so there should be a way to deal with this in Graal one would think

**Comment by vaswanijitesh** [comment] 2020-06-11 17:45
As soon as I updated to Quarkus 1.5, the delete started working! Just FYI :)
