### ISSUE TITLE
OIDC or JWT Authorization error: Token expiration.

### ISSUE THREAD

**Issue by juandiii** [quarkusio/quarkus#9591] opened 2020-05-25 20:03 UTC
**Describe the bug**
If I have an expired token then every request I make returns a response with no content, with status 403 forbidden, then I have an ExceptionMapper from ForbiddenException and it doesn't return the response I want. It still comes out no content with status 403.

**Expected behavior**
Should response with the ExceptionMapper with ForbiddenException

**Actual behavior**
Response with no content with status 403

**To Reproduce**
1. Start application
2. Put header with `Bearer eyyyXxxx1212`
3. Make GET some endpoint

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: `Darwin Juans-MBP.lan 19.4.0 Darwin Kernel Version 19.4.0: Wed Mar  4 22:28:40 PST 2020; root:xnu-6153.101.6~15/RELEASE_X86_64 x86_64`
 - Output of `java -version`: `openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.6+10)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.6+10, mixed mode)`
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): `Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)`

**Comment by sberyozkin** [comment] 2020-05-25 20:41
@juandiii So this issue is about the custom exception mappers not called when the security exception occurs ? Thanks

**Comment by juandiii** [comment] 2020-05-25 20:57
> @juandiii So this issue is about the custom exception mappers not called when the security exception occurs ? Thanks

Yes, it is. 
Thanks

**Comment by sberyozkin** [comment] 2020-05-25 21:19
@juandiii Thanks, I'll have to close this issue as a duplicate of both #5751 and #8570.
Please watch and vote for #8750

**Comment by sberyozkin** [comment] 2020-05-25 21:23
@juandiii thanks, closing now, please watch #8750

**Closed by sberyozkin** 2020-05-25 21:23 UTC
Labels: area/oidc, kind/bug

**Comment by juandiii** [comment] 2020-05-25 21:32
> @juandiii thanks, closing now, please watch #8750

Correcting #8570.
