### ISSUE TITLE
@Transactional not working for produced beans

### ISSUE THREAD

**Issue by andreas-eberle** [quarkusio/quarkus#17977] opened 2021-06-17 12:33 UTC
## Describe the bug
We have a producer function to create a DAO bean. Into that bean we provide the Hibernate `EntityManager` and run queries on our database. Unfortunately, when these Queries require a transaction (write operations), we get the following exception:

```
Caused by: javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.
```

However, we have these methods annotated with `@Transactional`. 

We were able to shrink this down into a small reproducer. It seems that `@Transactional` doesn't work for beans produced with a producer function but only with beans that have directly been annotated with e.g. `@ApplicationScoped`. 

### Expected behavior
`@Transactional` should work. 

### Actual behavior
It seems no transaction is opend if a bean is produced with a producer function.

## To Reproduce

1. Download reproducer project and unzip it [2021-06-17_transaction-missing.zip](https://github.com/quarkusio/quarkus/files/6670134/2021-06-17_transaction-missing.zip)
2. Start a local postgres database by running the docker-compose file in the project: `docker-compose up -d`.
3. Start the service with `./gradlew quarkusDev`
4. Go to http://localhost:8080/hello-resteasy/1 and you should see the crash.
5. Comment out the `TestDaoProducer` class and add `@ApplicationScoped` to the `TestDao` class. 
6. Run again and it should work as expected and the TestEntity is created.

## Environment (please complete the following information):
* Windows 10
* Quarkus 2.0.0.CR3 and Quarkus 1.13.7.Final
* Java 11

**Comment by famod** [comment] 2021-06-17 22:25
@mkouba @manovotn I tried to find it in the docs (I didn't), but IIRC there is some general limitation (spec induced?) regarding produced beans and interceptors?

**Comment by mkouba** [comment] 2021-06-18 06:15
> @mkouba @manovotn I tried to find it in the docs (I couldn't), but IIRC there is some general limitation (spec induced?) regarding produced beans and interceptors?

Yes, interceptor bindings declared on a producer method are not used to associate interceptors with the return value: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#binding_interceptor_to_bean. CDI 2.0 introduced the `InterceptionFactory` that allows for wrapping the produced instance so that it can be intercepted. However, Quarkus does not support this feature yet: https://github.com/quarkusio/quarkus/issues/3532.

**Comment by manovotn** [comment] 2021-06-18 07:03
Martin is right, this behavior is expected.

As for `InterceptionFactory`, that itself is pretty much a runtime construct and I don't think we can implement it as-is into a build time environment. At least not in a CDI portable manner.

**Comment by andreas-eberle** [comment] 2021-06-18 08:42
Is there an actual technical reason to not add the interceptors for produced beans? It feels this should be possible for Quarkus to do and I don't see a reason why produced beans should behave differently than standard beans. Or is there a reason?

**Comment by mkouba** [comment] 2021-06-18 09:21
The main reason is that a producer method controls the instantiation of the return value, i.e. the container cannot use an internal construct that implements the interception logic.

**Comment by andreas-eberle** [comment] 2021-06-18 12:07
Is there a way to get around this limitation? We need to produce differently parameterized versions of the bean that we then use in different places. We could use inheritance, I guess, but that also has its limitations with injecting stuff into the super type via the constructor which makes that ugly.

**Comment by famod** [comment] 2021-06-18 13:56
You could create a generic TransactionBean (or similar) that takes a Runnable or similar and then call that generic bean from your produced beans.
Or you could switch to bean managed transactions but I have never done this with Quarkus.

**Comment by emmanuel-legros** [comment] 2024-06-07 08:53
Hello,

I'm implementing my first Quarkus service with the Domain Driven Design and hexagonal architecture concept.
So, I have an application layer that manages the dependencies injection, with a class with the @Dependent annotation and all the injection/methods have @Produces.
I wanted to add a @Transactionnal on a method of one repository (that is instantiated in a method that has @Produces)

I have the same exception as this issue, and I'm in the same context in the end, right? = I don't have an @ApplicationScope in the repository class that needs @Transactional.
I'm sorry to update this "old" issue, but does there exist another/new way to make it work in this context?

**Comment by Ladicek** [comment] 2024-06-07 08:59
This is a duplicate of #3532, as mentioned above. I'm closing this issue, and I'm happy to let you all know that I started working on this yesterday, so there should be something shortly.

**Closed by Ladicek** 2024-06-07 08:59 UTC
Labels: kind/bug, env/windows
