### ISSUE TITLE
SmallRyeHealthReporter - Class does not exist in ClassLoader QuarkusClassLoader warning

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18746] opened 2021-07-16 13:20 UTC
### Describe the bug

While using dev mode in the project with the `smallrye-health` dependency, the following warning message is thrown:

=-=-=-=-=-=-=-=-=-=-
WARN  [io.qua.arc.pro.BeanArchives] (build-38) Failed to index [Lio.smallrye.health.SmallRyeHealthReporter$HealthType;: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV
=-=-=-=-=-=-=-=-=-=-

Might be a severe issue. In any way, the warning is unwanted.

### How to Reproduce?

 1. mvn io.quarkus:quarkus-maven-plugin:2.0.2.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"     -Dextensions=smallrye-health

2. cd getting-started
3. mvn clean quarkus:dev

### Quarkus version or git rev

2.0.2.Final

**Comment by xstefank** [comment] 2021-07-19 06:15
@kshpak I can't reproduce this with main branch or 2.1.0.CR1. Can you please check?

**Comment by MartinX3** [comment] 2021-07-20 12:49
I get this warning for every of my @Entity classes in 2.0.2.Final

**Comment by gsmet** [comment] 2021-07-21 11:43
Yeah, this will be fixed by 2.0.3.Final.

**Comment by gsmet** [comment] 2021-07-21 11:44
PR is here: https://github.com/quarkusio/quarkus/pull/18675

**Closed by gsmet** 2021-07-21 11:43 UTC
Labels: area/health, area/smallrye, kind/bug
