### ISSUE TITLE
Inconsistent versions for Slf4J in quarkus-universe-bom

### ISSUE THREAD

**Issue by ljacomet** [quarkusio/quarkus#9715] opened 2020-06-01 21:20 UTC
**Describe the bug**
The `quarkus-universe-bom` version `1.4.2.Final` has inconsistent versions for Slf4J. This issue is present in other versions as well.

**Expected behavior**
All dependencies in group `org.slf4` should be using a single version and build succeeds.

**Actual behavior**
`slf4j-simple` uses `1.7.25` while `slf4j-api` uses `1.7.30`, failing the build.
See [the BOM](https://repo.maven.apache.org/maven2/io/quarkus/quarkus-universe-bom/1.4.2.Final/quarkus-universe-bom-1.4.2.Final.pom)

**To Reproduce**
1. Take any Quarkus project built with Gradle
2. Add the `dev.jacomet.logging-capabilities` plugin, version `0.9.0`
3. Attempt to resolve the `runtimeClasspath`

Because that plugin defines a [virtual platform](https://docs.gradle.org/6.4.1/userguide/dependency_version_alignment.html#sec:align-versions-unpublished) for Slf4J and Quarkus leverages `enforced-platform`, the virtual platform detects the conflicting force and fails resolution.
See issue reported at ljacomet/logging-capabilities#9

**Environment:**
 - Output of `uname -a` or `ver`: Darwin 19.5.0
 - Output of `java -version`: openjdk version "11.0.6" 2020-01-14
 - GraalVM version (if different from Java): N/A
 - Quarkus version or git rev: 1.4.2.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 6.4.1

**Additional context**
I noticed that there is no `quarkus-universe-bom` for version `1.5.0.Final` while there is a `quarkus-bom`, so maybe this issue is no longer applicable.

**Comment by ljacomet** [comment] 2020-06-05 12:44
The [now released](https://repo.maven.apache.org/maven2/io/quarkus/quarkus-universe-bom/1.5.0.Final/quarkus-universe-bom-1.5.0.Final.pom) `quarkus-universe-bom` `1.5.0.Final` suffers from the exact same issue.

**Comment by famod** [comment] 2020-06-05 13:29
Maybe the Quarkus build process should introduce https://maven.apache.org/enforcer/enforcer-rules/dependencyConvergence.html to avoid such issues.

**Comment by famod** [comment] 2020-06-29 13:32
The problem is caused by importing `kogito-bom`: https://github.com/quarkusio/quarkus-platform/blob/master/bom/runtime/pom.xml#L36

This BOM also drags in `slf4j-nop`, btw.

cc @gsmet

**Comment by gsmet** [comment] 2020-06-29 16:40
They shouldn't be in the BOM in the first place.

**Comment by famod** [comment] 2020-06-29 16:48
> They shouldn't be in the BOM in the first place.

Ideally they shouldn't. Looks like another quickfix similar to https://github.com/quarkusio/quarkus-platform/pull/81 is required for now?

**Comment by gsmet** [comment] 2020-06-29 17:01
I would like to know where they are coming from because that's probably something that needs a fix in the external extensions that brings it.

I created https://github.com/quarkusio/quarkus-platform/pull/83 and looks like we have a ton of work ahead of us to clean this.

**Comment by gastaldi** [comment] 2024-08-21 18:36
The latest platform BOM (3.14.0.CR1 as of now) declares a dependency on `org.slf4:sl4j-api:2.0.6` only. Closing this issue

**Closed by gastaldi** 2024-08-21 18:36 UTC
Labels: kind/bug
