### ISSUE TITLE
Using Jackson support for Kotlin fails in native mode.

### ISSUE THREAD

**Issue by rdifrango** [quarkusio/quarkus#3954] opened 2019-09-10 20:29 UTC
**Describe the bug**
When using the Jackson Kotlin module with a Kotlin data class, it fails in native mode with the following:

```
com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `com.capitalone.polyglot.quarkus.model.Address` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)
```

The example code is pretty straight forward:

```
@ApplicationScoped
class CustomObjectMapperConfig {
    @Singleton
    @Produces
    fun objectMapper(): ObjectMapper {
        return ObjectMapper().registerModule(KotlinModule())
    }
}

data class Address(val addressLine1 : String, val addressLine2 : String, val addressLine3 : String, val addressLine4 : String, val city : String, val state : String, val country : String)

@Path("/deposits/tooling/validate-address")
@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
class AddressValidationResource {

    @POST
    fun validateAddress(address : Address) = address.copy(
                addressLine1 = "${address.addressLine1} ${address.addressLine2} ${address.addressLine3} ${address.addressLine4}",
                addressLine2 = "",
                addressLine3 = "",
                addressLine4 = "")
}
```

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
If I run this in JVM mode, aka `mvn compile quarkus:dev`, or as a runnable jar it works just fine.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)

**To Reproduce**
1. 
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
```
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-20190523183630.graal2.jdk8u-src-tar-gz-b03)
OpenJDK 64-Bit GraalVM CE 19.1.0 (build 25.212-b03-jvmci-20-b04, mixed mode)
```
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 
`<quarkus.version>0.21.2</quarkus.version>`

**Additional context**
(Add any other context about the problem here.)
Related #3652

**Comment by rdifrango** [comment] 2019-09-10 20:53
For a short-term work-around the following working:

```
@RegisterForReflection
data class Address(var addressLine1 : String = "", 
                   var addressLine2 : String = "", 
                   var addressLine3 : String = "", 
                   var addressLine4 : String = "", 
                   var city : String = "", 
                   var state : String = "", 
                   var country : String = "")
```

**Comment by gsmet** [comment] 2019-09-11 08:10
I think this is a legit issue. As a parameter of a REST method, the `Address` type should be registered for reflection automatically.

There's something wrong going on.

**Comment by gsmet** [comment] 2019-09-11 08:32
@geoand any chance you could have a look to this one?

**Comment by geoand** [comment] 2019-09-11 08:40
@gsmet sure thing

**Comment by geoand** [comment] 2019-09-11 09:06
This doesn't appear to be a Quarkus issue. 
The `Address`  class does get registered for reflection correctly. 
In order to confirm @rdifrango can you please use your workaround without the `@RegisterForReflection` annotation? If I am correct, it should still work.
In that case you'll need to go read up on what the proper way to use Kotlin data classes and Jackson.

**Comment by rdifrango** [comment] 2019-09-11 13:35
@geoand you're correct, it still works if I remove `@RegisterForReflection`.  

I also tested by swap back to `val` from `var` but with default values and that's when it fails again, so working:

```
data class Address(val addressLine1 : String = "", 
                   val addressLine2 : String = "", 
                   val addressLine3 : String = "", 
                   val addressLine4 : String = "", 
                   val city : String = "", 
                   val state : String = "", 
                   val country : String = "")

**Comment by geoand** [comment] 2019-09-11 13:39
Thanks for confirming and looking into it.
It certainly looks like it's an issue with how Kotlin and Jackson interact.

So I will go ahead and close this since it doesn't appear to be a Quarkus issue. If you feel that is not correct, please reopen and provide an update.

Thanks

**Comment by rdifrango** [comment] 2019-09-11 13:40
@geoand I still think this is an issue as the *NOT WORKING* case, works just fine in JVM mode, it only fails in NATIVE mode.

**Comment by geoand** [comment] 2019-09-11 13:44
@rdifrango a small reproducer then where I can see the exact error you are getting?

**Comment by rdifrango** [comment] 2019-09-11 13:48
The code above is exactly what I used, nothing more nothing less :)

To build it we issue:

```
mvn package -Pnative -Dnative-image.docker-build=true
```

To run it:

```
docker run --rm -p 9090:8080 address-validation-quarkus-kotlin:1.0
```

**Comment by geoand** [comment] 2019-09-11 13:49
If you could upload it to github or something, so I don't make any mistakes while trying to reproduce that would be great :)

**Comment by rdifrango** [comment] 2019-09-11 13:56
@geoand , I'll see what I can do, sadly uploading to GH is non-trivial at the office :)

Here's the maven POM file:

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.example.polyglot</groupId>
    <artifactId>address-validation-quarkus-kotlin</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <kotlin.version>1.3.21</kotlin.version>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <quarkus.version>0.21.2</quarkus.version>
        <sortpom.plugin.version>2.8.0</sortpom.plugin.version>
        <surefire-plugin.version>2.22.0</surefire-plugin.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-bom</artifactId>
                <version>${quarkus.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy</artifactId>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-jdk8</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-jackson</artifactId>
        </dependency>
        <dependency>
            <groupId>com.fasterxml.jackson.module</groupId>
            <artifactId>jackson-module-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-kotlin</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-junit5</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <sourceDirectory>src/main/kotlin</sourceDirectory>
        <testSourceDirectory>src/test/kotlin</testSourceDirectory>
        <plugins>
            <plugin>
                <groupId>com.github.ekryd.sortpom</groupId>
                <artifactId>sortpom-maven-plugin</artifactId>
                <version>${sortpom.plugin.version}</version>
                <executions>
                    <execution>
                        <phase>verify</phase>
                        <goals>
                            <goal>sort</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <predefinedSortOrder>default_1_0_0</predefinedSortOrder>
                    <lineSeparator>\n</lineSeparator>
                    <encoding>${project.build.sourceEncoding}</encoding>
                    <sortProperties>true</sortProperties>
                    <keepBlankLines>true</keepBlankLines>
                    <createBackupFile>false</createBackupFile>
                    <sortDependencies>scope</sortDependencies>
                    <nrOfIndentSpace>4</nrOfIndentSpace>
                </configuration>
            </plugin>
            <plugin>
                <groupId>io.quarkus</groupId>
                <artifactId>quarkus-maven-plugin</artifactId>
                <version>${quarkus.version}</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>build</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>${surefire-plugin.version}</version>
                <configuration>
                    <systemProperties>
                        <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
                    </systemProperties>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.jetbrains.kotlin</groupId>
                <artifactId>kotlin-maven-plugin</artifactId>
                <version>${kotlin.version}</version>
                <executions>
                    <execution>
                        <id>compile</id>
                        <goals>
                            <goal>compile</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>test-compile</id>
                        <goals>
                            <goal>test-compile</goal>
                        </goals>
                    </execution>
                </executions>
                <dependencies>
                    <dependency>
                        <groupId>org.jetbrains.kotlin</groupId>
                        <artifactId>kotlin-maven-allopen</artifactId>
                        <version>${kotlin.version}</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <compilerPlugins>
                        <plugin>all-open</plugin>
                    </compilerPlugins>
                    <pluginOptions>
                        <option>all-open:annotation=javax.ws.rs.Path</option>
                        <option>all-open:annotation=javax.enterprise.context.ApplicationScoped</option>
                    </pluginOptions>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <profiles>
        <profile>
            <id>native</id>
            <activation>
                <property>
                    <name>native</name>
                </property>
            </activation>
            <build>
                <plugins>
                    <plugin>
                        <groupId>io.quarkus</groupId>
                        <artifactId>quarkus-maven-plugin</artifactId>
                        <version>${quarkus.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>native-image</goal>
                                </goals>
                                <configuration>
                                    <enableHttpUrlHandler>true</enableHttpUrlHandler>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemProperties>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                    </systemProperties>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>
</project>
```

**Comment by geoand** [comment] 2019-09-11 14:02
Thanks @rdifrango,  I'll try and reproduce it. One last thing, do you have a curl command for POSTing to the endpoint?

**Comment by rdifrango** [comment] 2019-09-11 14:05
```
curl -X POST -H "content-type:application/json" -H "accept:application/json" http://localhost:9090/deposits/tooling/validate-address -d '{"addressLine1":"asdfasdf line 45", "addressLine2":"line2","addressLine3":"line3","addressLine4":"line4","city":"phl","state":"pa","country":"usa"}'
```

**Comment by geoand** [comment] 2019-09-11 14:06
Thanks, I'll try it and let you know

**Comment by geoand** [comment] 2019-09-11 14:29
I was able to reproduce thje problem. 
It doesn't look like a regular Quarkus problem (since the class is registered for reflection), but more some kind of weird interop issue. 
I am guessing it will take a lot more digging than I can do at the moment, so let's leave it open and I'll take a look when I have som extra time.

**Comment by rdifrango** [comment] 2019-09-11 14:29
thank you @geoand!

**Comment by geoand** [comment] 2019-09-11 14:50
Actually what we are seeing seems consistent with the Kotlin module not being applied in native mode.

**Comment by zerocode** [comment] 2019-11-16 06:21
Would be nice to have this fixed.

**Comment by odilonjk** [comment] 2019-12-04 00:34
I have faced the same problem on Java (JDK 8). The problem just appears running natively.
The `@RegisterForReflection` workaround as @rdifrango mentioned did the trick.

If someone want to check the code, [this is the repository](https://github.com/odilonjk/delayed-rest-product).

**Comment by geoand** [comment] 2019-12-04 06:22
@odilonjk the problem you are seeing is different. In your case it is not a bug but because you are returning `Response`, it is necessary to use `@RegisterForReflection`, see: https://quarkus.io/guides/rest-json#using-response

**Comment by codemwnci** [comment] 2020-01-09 14:42
Is there something specific needed to do to solve this issue, other than upgrading to 1.1.1?
I am still getting the same issue when running in native mode `com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Cannot construct instance of `xxxx` (no Creators, like default construct, exist): cannot deserialize from Object value (no delegate- or property-based Creator)`

This works fine in JVM mode, but not native. I tried with RegisterForReflection, but this did not work, and also, I am not using Response, so this should not be needed.

**Comment by geoand** [comment] 2020-01-09 14:50
@codemwnci is your To-do class is a different module perhaps?

**Comment by codemwnci** [comment] 2020-01-09 14:53
Not that I am aware of. All the Kotlin code is contained within that one KT file.

**Comment by geoand** [comment] 2020-01-09 14:55
Okay, I'll have to give it a look over the few days

**Comment by geoand** [comment] 2020-01-09 14:55
There might be another issue that we haven't taken into account yet

**Comment by MartinX3** [comment] 2020-01-09 15:30
Do we maybe need Jackson 2.10.x ?
(The bom enforces 2.9.x)

**Comment by codemwnci** [comment] 2020-01-09 15:41
Just to confirm, the workaround (var replacing val, and default values) works. 
I will test upgrading Jackson from 2.9.7 to 2.10.10 and feedback shortly.

**Comment by geoand** [comment] 2020-01-09 15:41
The Jackson version shouldn't be an issue, but I need to check

**Comment by geoand** [comment] 2020-01-09 15:46
I see a couple issues in your reproducer:

* You are not using version `1.1.1.Final`
* class `Todo` needs is **not** a Kotlin `data-class`.

**Comment by codemwnci** [comment] 2020-01-09 15:59
I hadn't uploaded the latest version of the POM to Github, but I am using the 1.1.1.Final locally. I'll change `data class`, to just `class` and see if it works.

I can also confirm that using 2.10.1 of Jackson doesn't make a difference.

**Comment by geoand** [comment] 2020-01-09 16:01
OK, let us know how it goes please

**Comment by codemwnci** [comment] 2020-01-09 16:18
Same error with 
`class Todo(val id: Long, val txt: String, val completed: Boolean = false)`
or 
`data class Todo(val id: Long, val txt: String, val completed: Boolean = false)`

I'll try a clean project (just drop in the config and TodoResource.kt) as a final test, but I am not expecting this to make any difference. 

Just for completeness, I am also running the build and run inside of docker, but again, I don't expect that to make any difference.

**Comment by geoand** [comment] 2020-01-09 16:59
I'll reopen this since I was able to reproduce it as well

**Comment by geoand** [comment] 2020-01-25 18:31
Pinging myself (@geoand) just so I can get this to the top of my email list 😎

**Comment by geoand** [comment] 2020-01-25 20:11
The only way I see me being able to debug this is building Jackson locally with a bunch of `println` statements since there is no easy way to debug in native and the stacktrace doesn't provide any useful info...

**Comment by geoand** [comment] 2020-01-26 10:32
The issue seems to occur only when a (data) class has `val` properties some of which have default values and some of which do not.
In that case for native to work, all values need to specified in the json object otherwise it fails

**Comment by geoand** [comment] 2020-01-26 14:49
The issue comes down to the fact that the `kotlin.Metadata` annotation that the Kotlin compiler adds to the class (and which is used [here](https://github.com/FasterXML/jackson-module-kotlin/blob/jackson-module-kotlin-2.10.2/src/main/kotlin/com/fasterxml/jackson/module/kotlin/KotlinModule.kt) to determine whether a class is a Kotlin class) is not present in the native image.
This is of course begs the question of why the annotation is dropped which I'll try and figure out and update the isse.

**Comment by geoand** [comment] 2020-01-28 13:46
So based on a suggestion from @gsmet when registering `kotlin.Metadata` from reflection, the process gets further but still fails. The latest error is:

```
Caused by: java.lang.AssertionError: Built-in class kotlin.Any is not found
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:113)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns$3.invoke(KotlinBuiltIns.java:108)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunction.invoke(LockBasedStorageManager.java:446)
        at kotlin.reflect.jvm.internal.impl.storage.LockBasedStorageManager$MapBasedMemoizedFunctionToNotNull.invoke(LockBasedStorageManager.java:521)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getBuiltInClassByName(KotlinBuiltIns.java:362)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getAny(KotlinBuiltIns.java:367)
        at kotlin.reflect.jvm.internal.impl.builtins.KotlinBuiltIns.getAnyType(KotlinBuiltIns.java:642)
```

**Comment by tellisnz-shift** [comment] 2020-01-28 14:17
I got to this point as well and couldn't figure out a way to register kotlin.Any, when i tried using a reflect-config.json the native image builder says it's not on the classpath, but the stdlib jar is there. I kinda guessed this is because of some magic where kotlin.Any isn't a real class and somehow maps to java.lang.Object?

**Comment by geoand** [comment] 2020-01-28 14:31
@tellisnz-shift I also tried registering `Kotlin.Any` without success. I am knowledgeable of the Kotlin internals so I don't have a path forward for the time being.
I'll try and contact the Kotlin folks and see if I get any info

**Comment by Mason-Harding** [comment] 2020-01-29 16:14
FYI, I have run into this with Kotlin and Native-Image before using Quarkus.  I fixed this by using the Kotlin no-arg compiler plugin.  Then you can use a data class with val, and not needing to set a default value, as it will create a no arg constructor accessible by reflections.

**Comment by geoand** [comment] 2020-01-29 16:23
Ah, the `no-arg` plugin! I completely forgot about that, I'll give it spin soon

**Comment by geoand** [comment] 2020-01-29 16:34
Seems like I can get somewhere with the no-arg plugin but it still doesn't work properly - the default value isn't used (when a default value is set)

**Comment by Mason-Harding** [comment] 2020-01-29 16:40
I'm sure we are getting off topic, and a Quarkus dev will yell at us soon, but defaults won't work as they only work when no value is specified, and via that constructor.  Jackson will set them to null.

**Comment by geoand** [comment] 2020-01-29 16:46
Nobody is going to yell at anyone, we are as super friendly community :)

The problem is that the behavior is different between JVM and native mode. With the no-arg plugin, in JVM the defaults are used which unfortunately is not the case in native mode.

**Comment by Mason-Harding** [comment] 2020-02-05 22:13
I'm working on a related issue, and I was able to get Kotlin.Any registered for reflection by adding java.lang.Object to reflection-config.  Hope that helps.

**Comment by Mason-Harding** [comment] 2020-02-05 22:22
I am running into this same issue, except I get the error 
`@NotNull method kotlin/reflect/jvm/internal/impl/builtins/KotlinBuiltIns.getBuiltInClassByFqName must not return null`
I tried adding kotlin.Metadata to the reflection-config file, and now am also getting 
`java.lang.AssertionError: Built-in class kotlin.Any is not found`

I tried debugging by doing `Class.forName(Any::class.java.name)`, which I was able to do when I added java.lang.Object to the reflection-config file, but I still get `Built-in class kotlin.Any is not found` when jackson tries to read a value.

**Comment by geoand** [comment] 2020-02-06 07:21
Yeah this seems to require a chat with the Kotlin folks to see how to proceed. Unfortunately I haven't had the time to do that :(

**Comment by tellisnz-shift** [comment] 2020-03-15 01:25
hi @geoand - have you been able to get in touch with the kotlin/graalvm folks?

**Comment by geoand** [comment] 2020-03-15 07:52
@tellisnz-shift unfortunately no. With all the stuff that needed to be done for 1.3, I didn't follow up after not being able to reach them the first time.
I'll try again this week I hope.

**Comment by Rupert-RR** [comment] 2020-04-08 08:33
Just as an indicator (I haven't isolated this into a barebones example), in case it helps, I am running into this problem for a data class which does not have any default values (but all properties are `val`, and obviously I have registered the Kotlin Jackson module on the mapper). However I do have several enum parameters for which there are default enum values (`@JsonEnumDefaultValue`) and I have activated the `READ_UNKNOWN_ENUM_VALUES_USING_DEFAULT_VALUE` on the mapper.

**Comment by miron4dev** [comment] 2020-04-12 17:08
Any news?

I was able to get around this problem by explicitly adding Jackson annotations.
So, this code works in JVM mode but doesn't in native mode

```kotlin
@RegisterForReflection
data class CreateTaskRequest(val name: String, val description: String?)
```

but this code works in both JVM and native modes.
```kotlin
@RegisterForReflection
data class CreateTaskRequest @JsonCreator constructor(
        @JsonProperty("name")
        val name: String,

        @JsonProperty("description")
        val description: String?
)
```

Moreover, this workaround keeps the class immutable. 

However, it pollutes my class and I expect to write code without any Jackson annotations as in the first example.

**Comment by geoand** [comment] 2020-04-12 17:18
@miron4dev is that class part of a jax-rs method (I assume it's the payload of a POST request)?

**Comment by miron4dev** [comment] 2020-04-12 17:27
@geoand yes, it's the payload of a POST request.

**Comment by geoand** [comment] 2020-04-20 18:20
I want to give something a try soon. I'll come back when I have something to report.

**Comment by geoand** [comment] 2020-04-20 20:55
I went through various scenaria to try and reproduce the problems with Kotlin Data classes and Jackson deserialization in native but I failed to uncover any...

Here is where I recorded what I did: https://github.com/geoand/kotlin-jackson-demo
If folks have concrete reproducible examples of issues I would love to know about them.

**Comment by codemwnci** [comment] 2020-04-21 14:49
I need to do a little more testing. 
I wondered if it was because you had extracted the data classes out into their own files, rather than inside of the GreetingResource.kt file itself, so I tested with my previous 1.1.1.Final code. This still failed.

I need to upgrade Graal to test with 1.3.2, so this will take me a little longer. Will report back when I can.

**Comment by geoand** [comment] 2020-04-21 14:52
@codemwnci Thanks. Feel free to ping me when you have results :)

**Comment by codemwnci** [comment] 2020-04-22 09:24
I have tried a number of different configurations (slow testing cycle due to the 15minute native compile!). Upgrading to Quarkus 1.3.2, and GraalVM 20.x, did not initially make any difference. I then changed the POM to reflect your POM and it worked.
I then individually started removing the POM configurations back to my original and the key (single) element that has made this work is in the Kotlin maven plugin configuration.

```<javaParameters>true</javaParameters>```

https://github.com/geoand/kotlin-jackson-demo/blob/cabe4f484a20c1b64332a4565060b49a3f1699c0/pom.xml#L120

So, as long as the latest POM creation through the maven archetypes generate the above setting (which appears to be the case), then this bug can be closed.

For anyone who is not creating a new project, they simply need to add the parameter to the "configuration" of the kotlin-maven-plugin, as linked to above.

**Comment by geoand** [comment] 2020-04-22 09:27
Thanks a lot for the thorough check @codemwnci!

Indeed the project generation now includes  `<javaParameters>true</javaParameters>`  : https://github.com/quarkusio/quarkus/blob/1.4.0.CR1/devtools/platform-descriptor-json/src/main/resources/templates/basic-rest/kotlin/pom.xml-template.ftl#L109

I'll close this issue as per both our findings

**Closed by geoand** 2020-04-22 09:27 UTC
Labels: area/kotlin, area/resteasy, kind/bug

**Comment by soufianesakhi** [comment] 2020-07-06 10:37
If anyone is having troubles with Kotlin in native mode, check the configuration resources linked here: https://github.com/oracle/graal/issues/2306

**Comment by oztimpower** [comment] 2021-02-22 04:06
I have some experiences to add on this one. I use an IntelliJ plug-in to convert JSON to Kotlin data classes for me (large structure!)

Everything worked fine in JVM mode, Jackson-Kotlin-module clearly enabled for the `mapper.readValue(jsonBody)`. However, a straight native-image version failed, with similar errors above. I experimented a lot with the issue, looked at the optional fields, default values and so on. The JSON structure was quite complex, with multiple levels and even an array. 

What was interested was when I moved to using `mapper.readTree` for the json and picked out the specific parts I wanted in the hierarchy and then did a `mapper.readValue(myNode)`, it worked fine. The Jackson-Kotlin-module in native-image clearly prefers a simpler denormalised-like structure, than many levels (why?).  I still had a few levels in the JSON, i.e. moving from about 5 nodes down to 2.  When I started using `mapper.readTree` I also started getting different errors, the Jackson parser was giving me more specific object it was struggling to convert, rather than the blanket error (as above) that it can't construct the root data class). Thus the error you get from the Jackson conversion can be a little misleading and in a hierarchy of objects it could be a leaf node that it is struggling to convert, yet reports an issue at the root node (exception probably bubbles up in the code).

So, my recommendation for anyone having these issues, is to use `mapper.readTree` when using native-image, pull out the bits you want from the JSON-nodes and use `mapper.readValue` on that, rather than relying on a large tree to object conversion. More like using a SAX parser for XML than DOM, was the logic. 

I'm looking forward to using Java-records in the future in this scenario, and I believe Kotlin will map the internals of data-classes to records so it will look the same to the JVM(?). No not keen on using Lombok here as a replacement for my Kotlin data classes.

**Comment by oztimpower** [comment] 2021-02-22 10:14
An addendum, I've been able to get it working with the entire object tree for native-image (fiddling with JSON to Kotlin data-class plugin options), generating val with nullable type and default of null, along with the Jackson field name, .i.e.:

```
data class Response(
	@field:JsonProperty("chart")
	val chart: ChartData? = null
)```

**Comment by lbilger** [comment] 2021-03-22 12:57
@geoand, you asked for reproducible examples of issues. I ran into this issue last week and had a hard time figuring out why your example worked and my code didn't. In the end, I found out that the issue seemed to be data classes that have non-primitive members, e.g. a data class containing a `List` or another data class. I'm not sure if I should open a new issue as this one has been closed for a while.
I have extended your example project and will shortly post two pull requests - one for the additional examples that break for me, and one to update to the latest Quarkus version. I hope this helps to track down the issue.

Thanks!

**Comment by geoand** [comment] 2021-03-22 13:01
Thanks @lbilger. I'll try to take a look later on this week,

**Comment by oztimpower** [comment] 2021-03-22 15:23
@geoand This is the same issue I described above (complex structures) and why I added troubleshooting notes to the Kotlin documentation. Using the field annotation does overcome it, but may be considered a workaround.

**Comment by geoand** [comment] 2021-03-22 15:25
Ah, thanks @oztimpower, I had forgot!

**Comment by u6f6o** [comment] 2021-03-27 17:51
I run into the same issue today (I suppose). Initially I used the following data class to de-serialize a  json resource (via rest client): 

```
@JsonIgnoreProperties(ignoreUnknown = true)
data class EnvSnapshot(
    val stations: List<EnvAwareStationConfig>
)
```
It worked without any problem in the non-native mode but as soon as I deployed the application in native mode, the de-serialization failed. After some time, I figured out, that it works if I annotate the stations field with a `@JsonProperty` annotation: 

```
@RegisterForReflection
@JsonIgnoreProperties(ignoreUnknown = true)
data class EnvSnapshot(
    
    @JsonProperty("stations")
    val stations: List<EnvAwareStationConfig>
)
```

There is a bunch of log messages though that remained even after I added the annotation: 

```
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.CollectionProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.JaxrsFormProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.MapProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultBooleanWriter from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.JAXBXmlSeeAlsoProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DocumentProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.JAXBXmlTypeProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.JAXBXmlRootElementProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.JAXBElementProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.SourceProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultNumberWriter from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.FormUrlEncodedProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.sse.SseEventProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.DefaultTextPlain from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.jaxb.XmlJAXBContextFinder from resource:META-INF/services/javax.ws.rs.ext.Providers
RESTEASY002120: ClassNotFoundException: Unable to load builtin provider org.jboss.resteasy.plugins.providers.IIOImageProvider from resource:META-INF/services/javax.ws.rs.ext.Providers
```
