### ISSUE TITLE
Little error in documentation "Configuration all properties"

### ISSUE THREAD

**Issue by sekaijin** [quarkusio/quarkus#18335] opened 2021-07-02 07:34 UTC
## format error in table of configuration properties

if https://quarkus.io/guides/all-config page 
on ligne
quarkus.test.exclude-pattern the default value contents pattern with | but this is a column separator for asciidoctor
And then the next lines are not well formatted

```
quarkus.test.include-patternTests that should be included for continuous testing. This is a regular expression and is matched against the test class name (not the file name).Show less | string |  
-- | -- | --
quarkus.test.exclude-patternTests that should be excluded with continuous testing. This is a regular expression and is matched against the test class name (not the file name). This is ignored if include-pattern has been set.Show less | string | `.*\.IT[^.]+
.*IT | .*ITCase` | quarkus.test.basic-consoleDisable the testing status/prompt message at the bottom of the console and log these messages to STDOUT instead. Use this option if your terminal does not support ANSI escape sequences.Show more
boolean | false | quarkus.test.disable-colorDisable color in the testing status and prompt messages. Use this option if your terminal does not support color.Show more
```

**Comment by machi1990** [comment] 2021-07-02 08:09
Thanks for reporting the issue @sekaijin . Regex are now sanitized and it is the case in `main` branch - as can be seen from the https://quarkus.io/version/main/guides/all-config#quarkus-core_quarkus.test.exclude-pattern. 

@gsmet could this be a deployment issue?

**Comment by gastaldi** [comment] 2021-07-05 16:05
Duplicate of 18411

**Closed by gastaldi** 2021-07-05 16:05 UTC
Labels: area/documentation, kind/bug
