### ISSUE TITLE
Quarkus application ignores SIGINT during the bean initialization phase

### ISSUE THREAD

**Issue by pivovarit** [quarkusio/quarkus#10709] opened 2020-07-14 05:11 UTC
If I try to send SIGINT signal(ctrl-c) to an application that's in the process of injecting beans, the signal gets ignored.

**Expected behavior**
Applications should respond to SIGINT and terminate itself.

**Actual behavior**
The SIGINT signal gets ignored:

**To Reproduce**
1. Start with an empty _code.quarkus.io_ project
2. Create a bean that takes a lot of time to initialize
```
@ApplicationScoped
public class FooConfig {

    @Produces
    String foo() throws InterruptedException {
        Thread.sleep(100000);
        return "foo";
    }
}
```
3. Inject is somewhere
```
@Path("/hello")
public class ExampleResource {

    private final String foo;

    public ExampleResource(String foo) {
        this.foo = foo;
    }

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "hello";
    }
}
```
4. Build the app `mvn package` 
4. Run the app(`java -jar *-runner.jar`) and interrupt it using ctrl-c. Everything should be just fine.
5. Run the app(`java -jar *-runner.jar`) and trigger the injection `curl http://localhost:8080/hello`
6. Interrupt it using ctrl-c

**Screenshots**
_SIGINT_ handling before injection gets triggered:

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/2182533/87385847-6a2c9500-c59f-11ea-9b7b-459a19eea6d5.png">

_SIGINT_ handling after injection was triggered:

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/2182533/87385817-4f5a2080-c59f-11ea-966e-76046e18093a.png">

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 

> Darwin piv-MBP.local 19.5.0 Darwin Kernel Version 19.5.0: Tue May 26 20:41:44 PDT 2020; root:xnu-6153.121.2~2/RELEASE_X86_64 x86_64
 - Output of `java -version`: 
> java -version                                                              х INT 3s RAM 5.51G L 2.12
openjdk version "11.0.4" 2019-07-16
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.4+11)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.4+11, mixed mode)

 - Quarkus version or git rev: 
> 1.6.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
> mvn -version                                                                        RAM 5.48G L 1.99
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

[sigint-reproducer.zip](https://github.com/quarkusio/quarkus/files/4916665/sigint-reproducer.zip)

----

Related: https://github.com/hazelcast/quarkus-hazelcast-client/issues/47

**Comment by geoand** [comment] 2024-09-13 12:31
Is this still an issue?

**Comment by pivovarit** [comment] 2024-09-13 12:39
Just tried it with ```<quarkus.platform.version>3.14.3</quarkus.platform.version>``` and it's still there

reproducer:
[reproducer-2.zip](https://github.com/user-attachments/files/16993932/reproducer-2.zip)

**Comment by geoand** [comment] 2024-09-13 12:42
Thanks for the prompt reply!

cc @mkouba

**Comment by mkouba** [comment] 2024-09-13 13:17
@pivovarit Hm, I cannot reproduce the problem on Linux, openjdk 21.0.3 2024-04-16 LTS, with Tilix terminal...

**Comment by pivovarit** [comment] 2024-09-13 15:29
I gave it another try and I think it works :) sorry for the confusion. I know what happened: the application did not stop immediately, but entered a rather slow graceful shutdown which, at the first sight, seemed to be stuck and I assumed it just did not work:


```
2024-09-13 17:24:53,316 INFO  [io.quarkus] (main) Installed features: [cdi, rest, smallrye-context-propagation, vertx]
^C2024-09-13 17:25:02,386 INFO  [io.qua.thread-pool] (Shutdown thread) Awaiting thread pool shutdown; 1 thread(s) running with 0 task(s) waiting
2024-09-13 17:25:07,408 INFO  [io.qua.thread-pool] (Shutdown thread) Awaiting thread pool shutdown; 1 thread(s) running with 0 task(s) waiting
2024-09-13 17:25:07,419 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello failed, error id: 14bb565a-4b5c-42a3-a5f1-7c895d185fc8-1 [Error Occurred After Shutdown]: jakarta.enterprise.inject.CreationException: java.lang.InterruptedException: sleep interrupted
	at org.acme.FooConfig_ProducerMethod_foo_9exGvS8rf3-QaczRgGHBhcXEUa0_Bean.create(Unknown Source)
	at org.acme.FooConfig_ProducerMethod_foo_9exGvS8rf3-QaczRgGHBhcXEUa0_Bean.get(Unknown Source)
	at org.acme.FooConfig_ProducerMethod_foo_9exGvS8rf3-QaczRgGHBhcXEUa0_Bean.get(Unknown Source)
	at org.acme.GreetingResource_Bean.doCreate(Unknown Source)
	at org.acme.GreetingResource_Bean.create(Unknown Source)
	at org.acme.GreetingResource_Bean.create(Unknown Source)
	at io.quarkus.arc.impl.AbstractSharedContext.createInstanceHandle(AbstractSharedContext.java:119)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:38)
	at io.quarkus.arc.impl.AbstractSharedContext$1.get(AbstractSharedContext.java:35)
	at io.quarkus.arc.impl.LazyValue.get(LazyValue.java:32)
	at io.quarkus.arc.impl.ComputingCache.computeIfAbsent(ComputingCache.java:69)
	at io.quarkus.arc.impl.ComputingCacheContextInstances.computeIfAbsent(ComputingCacheContextInstances.java:19)
	at io.quarkus.arc.impl.AbstractSharedContext.get(AbstractSharedContext.java:35)
	at org.acme.GreetingResource_Bean.get(Unknown Source)
	at org.acme.GreetingResource_Bean.get(Unknown Source)
```

**Comment by geoand** [comment] 2024-09-20 07:05
In light of the above, let's close the issue.

**Closed by geoand** 2024-09-20 07:05 UTC
Labels: kind/bug
