### ISSUE TITLE
Propertie amqp-host does not work for reactive-messaging-amqp

### ISSUE THREAD

**Issue by BiggA94** [quarkusio/quarkus#3806] opened 2019-09-02 13:36 UTC
**Describe the bug**
I am using the reactive-messaging-amqp extension.
The documentation states, that one can change the host to connect to by setting `amqp-host` and `amqp-port` via application.properties.
Sadly, the settings seem to not get propagated to my application.
But ´amqp-user´ and ´amqp-password´  are working though.

Also I am running an ActiveMQ-Artemis Broker on localhost.

**Expected behavior**
I expect the application to fail connecting to the broker.

**Actual behavior**
The AMQP client connects to the broker on localhost and does not try to connect to quarkus.io:42.

**To Reproduce**
1.  Follow the amqp guide
2.  add the line `amqp-port=42` or `amqp-host=quarkus.io` to your application properties.
3.  start your application.

**Configuration**
```properties
# Configures the AMQP broker credentials.
amqp-port=42
amqp-host=quarkus.dev
amqp-username=quarkus
amqp-password=quarkus

# Configure the AMQP connector to write to the `prices` address
mp.messaging.outgoing.generated-price.connector=smallrye-amqp
mp.messaging.outgoing.generated-price.address=prices
mp.messaging.outgoing.generated-price.durable=true
```

**Environment (please complete the following information):**
 - Output of `java -version`:  `openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)`
 - Quarkus version or git rev:  21.1

**Comment by Markus-Schwer** [comment] 2019-11-04 10:24
I have the exact same problem (quarkus version 0.27.0). Does anyone have an update on this?

**Comment by Markus-Schwer** [comment] 2019-11-04 10:45
This is my stacktrace:
```bash
java.util.concurrent.CompletionException: io.netty.channel.ConnectTimeoutException: connection timed out: localhost/127.0.0.1:61616
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:331)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:346)
        at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1063)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2088)
        at io.vertx.axle.AsyncResultCompletionStage.lambda$toCompletionStage$0(AsyncResultCompletionStage.java:20)
        at io.vertx.axle.amqp.AmqpClient$1.handle(AmqpClient.java:114)
        at io.vertx.axle.amqp.AmqpClient$1.handle(AmqpClient.java:109)
        at io.vertx.amqp.impl.AmqpConnectionImpl.lambda$connect$4(AmqpConnectionImpl.java:116)
        at io.vertx.proton.impl.ProtonClientImpl$ConnectCompletionHandler.handle(ProtonClientImpl.java:123)
        at io.vertx.proton.impl.ProtonClientImpl.lambda$connectNetClient$1(ProtonClientImpl.java:98)
        at io.vertx.core.net.impl.NetClientImpl.doFailed(NetClientImpl.java:244)
        at io.vertx.core.net.impl.NetClientImpl.lambda$failed$8(NetClientImpl.java:240)
        at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:369)
        at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:232)
        at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:224)
        at io.vertx.core.net.impl.NetClientImpl.failed(NetClientImpl.java:240)
        at io.vertx.core.net.impl.NetClientImpl.lambda$doConnect$3(NetClientImpl.java:202)
        at io.vertx.core.net.impl.ChannelProvider.lambda$connect$1(ChannelProvider.java:78)
        at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$2(ChannelProvider.java:139)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:263)
        at io.netty.util.concurrent.PromiseTask$RunnableAdapter.call(PromiseTask.java:38)
        at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:139)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
        at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: io.netty.channel.ConnectTimeoutException: connection timed out: localhost/127.0.0.1:61616
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe$1.run(AbstractNioChannel.java:261)
        ... 9 common frames omitted
```

Example for my application.properties:
```
amqp-server=quarkus.io
amqp-port=61616
```

**Comment by HeavyTobi** [comment] 2019-11-04 10:47
have the same issue... any news on that?

**Comment by cescoffier** [comment] 2019-11-04 11:17
I will have a look

**Comment by cescoffier** [comment] 2019-11-04 12:52
The properties seem to work.
I've tried:
```
amqp-host=naboo
amqp-port=5674
```
And the application got the right server and port.

If you give wrong connection details you should see in the application log:
```
 java.util.concurrent.CompletionException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:5674
```
(here I used localhost instead of `naboo`).

@Markus-Schwer  So what you see is the right stack trace when you cannot connect. Can you give me a reproducer if it's still incorrect?

**Comment by Markus-Schwer** [comment] 2019-11-04 13:01
@cescoffier Thank you for your quick response!
The problem isn't that `localhost:61616` isn't reachable, because i don't have a local AMQP server running. The problem is that, as it states in the stacktrace `ConnectTimeoutException: connection timed out: localhost/127.0.0.1:61616` it tries to connect to localhost, instead of the host specified in the properties.

**Comment by Markus-Schwer** [comment] 2019-11-04 13:56
I just noticed that i use the wrong property:
```
# wrong:
amqp-server=naboo
# right:
amqp-host=naboo
```

**Comment by Markus-Schwer** [comment] 2019-11-04 14:06
Turns out, that was the problem...
@cescoffier Sorry for waisting your time.

**Comment by gsmet** [comment] 2019-11-04 15:57
OK, we have at least one person saying it works so let's close it. Please reopen if it still doesn't work for you.

**Closed by gsmet** 2019-11-04 15:57 UTC
Labels: bug
