### ISSUE TITLE
Sample project with rest-client-codestart has test failures

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24553] opened 2022-03-25 09:41 UTC
### Describe the bug

sample project with rest-client-codestart has test failures

```
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.049 s <<< FAILURE! - in io.quarkus.qe.MyRemoteServiceTest
[ERROR] io.quarkus.qe.MyRemoteServiceTest.testExtensionsRestClientEndpoint  Time elapsed: 0.579 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: expected: <REST Client> but was: <>
	at io.quarkus.qe.MyRemoteServiceTest.testExtensionsRestClientEndpoint(MyRemoteServiceTest.java:26)
```

Test fails on `Assertions.assertEquals("REST Client", extension.shortName);` check
https://github.com/quarkusio/quarkus/blob/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/rest-client-codestart/java/src/test/java/org/acme/MyRemoteServiceTest.java#L26

There is no `shortName` defined for quarkus-rest-client extension, see https://stage.code.quarkus.io/api/extensions?id=io.quarkus:quarkus-rest-client

To resolve this either test in the codestart needs to be adjusted or metadata for code.quarkus need to be enhanced to provide `shortName` for quarkus-rest-client extension

cc @ia3andy / @maxandersen 

### Expected behavior

sample project with rest-client-codestart has no failures

### Actual behavior

sample project with rest-client-codestart has test failures

### How to Reproduce?

 - Run `mvn io.quarkus:quarkus-maven-plugin:2.7.5.Final:create -DprojectGroupId=io.quarkus.qe -DprojectArtifactId=rest-client -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=rest-client -DquarkusRegistryClient=false`
   -  `-DquarkusRegistryClient=false` is needed because of https://github.com/quarkusio/quarkus/issues/24552
 - Run `mvn clean verify -f rest-client`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.5.Final

**Comment by ia3andy** [comment] 2022-03-25 09:43
Duplicate of https://github.com/quarkusio/quarkus/pull/24551#issue-1180477926

**Comment by ia3andy** [comment] 2022-03-25 09:45
I'll keep it open until the PR is merged

**Comment by rsvoboda** [comment] 2022-03-25 09:46
+1, I was wondering why are you closing the issue as duplicate with link to the PR

**Comment by ia3andy** [comment] 2022-03-25 09:48
> +1, I was wondering why are you closing the issue as duplicate with link to the PR

me too :)

**Closed** 2022-03-25 14:20 UTC
Labels: kind/bug, area/rest-client, area/devtools, area/codestarts
