### ISSUE TITLE
ORM Generation error when value is update with mysql

### ISSUE THREAD

**Issue by andfs** [quarkusio/quarkus#9896] opened 2020-06-09 23:04 UTC
**Describe the bug**
if use 
```quarkus.hibernate-orm.database.generation=update```
with MySQL database, quarkus tries to create the schema again. Its behavior is like generation was **create**

**Expected behavior**
Quarkus should only update the schema and not recreate it.

**Actual behavior**
Quarkus tries to create the schema again

**To Reproduce**
1. Setup hibernate with panache and a MySQL database
2. configure quarkus.hibernate-orm.database.generation=update
3. starts the app

It happens in dev and production environments.

**Comment by tivrfoa** [comment] 2020-08-02 22:51
@Sanne 
When: quarkus.hibernate-orm.database.generation = update 
If one field is removed, should the schema be changed?
Because I'm testing PanacheEntity and:
1. I removed a field;
2. run: mvn quarkus:dev
3. Schema remained the same.

If this is a issue, is the problem on Quarkus or Hibernate?

**Comment by Bonissauro** [comment] 2020-08-03 13:13
Same behavier here. When trying to add an attriute, quarkus shows an error on console saying table cannot be recreated.

2020-08-03 10:01:01,515 WARN  [org.hib.too.sch.int.ExceptionHandlerLoggedImpl] (Quarkus Main Thread) GenerationTarget encountered exception accepting command : Error executing DDL "create table Usuario (id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB" via JDBC Statement: org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL "create table Usuario (id bigint not null auto_increment, email varchar(255), nome varchar(255), senha varchar(255), primary key (id)) engine=InnoDB" via JDBC Statement

**Comment by Bonissauro** [comment] 2020-08-03 13:20
Does this happen also on PostGres?

**Comment by Jurricane** [comment] 2021-03-17 14:41
I've got the same problem with quarkus 1.9.2 and mysql.

**Comment by yrodiere** [comment] 2021-08-03 08:03
This looks like a duplicate of #5883, which was fixed in Quarkus 2.0.

At the very least, while I'm able to reproduce the problem in Quarkus 1.0, I'm not able to reproduce it in 1.13.

I'll go ahead and assume this was fixed; please reopen this issue or open another one if I'm wrong.

**Closed by yrodiere** 2021-08-03 08:03 UTC
Labels: area/hibernate-orm, kind/bug
