### ISSUE TITLE
Boostrap does not support enabling profiles with `-P`

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2055] opened 2019-04-13 14:59 UTC
The current bootstrap support does not allow enabling profiles from the `settings.xml` using `-P...`

**Comment by geoand** [comment] 2019-04-14 10:56
Is this a duplicate of #2043?

**Comment by cescoffier** [comment] 2019-04-14 14:20
Yes it is.

**Comment by cescoffier** [comment] 2019-04-14 14:20
Closing as duplicate

**Closed** 2019-04-14 14:20 UTC
Labels: component:build, duplicate
