### ISSUE TITLE
No dependency injection in dev mode in extension-provided bean

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#3058] opened 2019-07-01 21:44 UTC
**Describe the bug**
My extension declares an `@Application`-scoped bean (via `AdditionalBeanBuildItem`). When this is run during dev mode, it doesn't have any dependencies injected (only it's no-args constructor gets called, but not its parameterized `@Inject`-annotated constructor.

**Expected behavior**
Dependencies are injected.

**Actual behavior**
Dependencies not injected, leading to NPEs in the bean's `onStart()` handler which access those fields.

**Comment by mkouba** [comment] 2019-07-03 09:33
A minimal reproducer would be helpful.

**Comment by gunnarmorling** [comment] 2019-07-13 15:20
@mkouba, ok, so I think this was a misunderstanding on my end. I have a `Singleton` bean (`KafkaStreams`) which is created via a producer method on an application-scoped bean (`KafkaStreamsTopologyManager`) provided by my Quarkus extension. `KafkaStreamsTopologyManager` expects a `Topology` to be injected created by a producer in the application. Now in that producer I was injecting `KafkaStreams` again, forming some kind of cycle.

It seems it's expected that this doesn't work? I was surprised only not to see a meaningful error about it, but just the reference to `KafkaStreams` being null. Is that intended?

In any case I can work around the issue by splitting up my `Topology` producer and the class in the application which needs to obtain the `KafkaStreams` bean.

**Comment by mkouba** [comment] 2019-07-15 07:17
Hm, circular dependencies are not supported at the moment but you should see some meaningful error message instead. Could you share the code?

**Comment by gunnarmorling** [comment] 2019-07-15 08:45
@mkouba, here's the code:

* Build Quarkus with PR https://github.com/quarkusio/quarkus/pull/2953
* Then take the quickstart example which I've updated based on that PR: https://github.com/gunnarmorling/quarkus-quickstarts/commit/d7b64661526f47e279b5b439ef643c17ec0a52d9

If you change it so that `KafkaStreams` is injected into `TopologyProducer`, the injected bean will be null. The quickstart works as I've changed it so that the `KafkaStreams` is injected only into `InteractiveQueries`, which now is separate from the producer method for the `Topology`.

**Comment by mkouba** [comment] 2019-07-17 09:22
Ok, so I've tried to look at the code and it's a bit more complicated. First of all, we don't detect a cycle because `Instance<Topology>` is used in `KafkaStreamsTopologyManager` (for this injection point a built-in bean is injected). 

Now if you look at the `KafkaStreamsTopologyManager.getStreams()` producer method, it may return null as it simply returns the `KafkaStreamsTopologyManager.streams` field (note that CDI producers are allowed to return `null`). The `KafkaStreamsTopologyManager.streams` field is set in the `onStart(StartupEvent)` method:

```java
streams = new KafkaStreams(topology.get(), streamsProperties);
```
`topology.get()` triggers the `TopologyProducer.buildTopology()` producer method and the container attempts to inject `TopologyProducer.streams` -> this invokes `KafkaStreamsTopologyManager.getStreams()` which returns `null` because the `KafkaStreamsTopologyManager.streams` field is not set yet.

So from my POV there is no bug and we can close the issue. WDYT?

**Comment by mkouba** [comment] 2019-07-25 07:48
@gunnarmorling ^ ?

**Comment by mkouba** [comment] 2019-08-16 13:05
Closing the issue. Feel free to reopen if needed.

**Closed by mkouba** 2019-08-16 13:05 UTC
Labels: bug, component:arc

**Comment by gunnarmorling** [comment] 2019-08-16 13:17
Thanks, it makes sense!

>
