### ISSUE TITLE
Simplified JPA data access (project panache)

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#646] opened 2019-01-28 09:45 UTC
Project Panache goal is to make the simple JPA tasks (CRUD, simple queries etc) very simple and the general needs provided (pagination etc) so people can focus on the complex parts.

We start with the `find` helper method approach as it's mildly more verbose than method name guesses and it scales better in complexity.

Here are the list of tasks for first public releases:

* [x] public fields support (call site enhancement)
* [x] getter support
* [x] base entity
* [x] base DAO
* [ ] `validate` method
* [ ] `rollbackOnly` method
* [x] pagination
* [x] multiple return types (List, Stream etc)

Remember we keep the JPA semantic

Here are the list of tasks optional or after first public releases:

* [ ] type safety via APT
* [ ] query dsl
* [ ] hint features like cacheable

Each bullet point can become a sub issue when you deliver it. That way we can track progress for people consuming the feature. Edit this description and add the sub issue number in the relevant checklist line.

When push comes to shove, we can make this project a nice-first-public-release. But we think that's manageable in first.

**Comment by FroMage** [comment] 2019-05-24 13:30
Let's close this issue since it shipped with the first release.

**Closed by FroMage** 2019-05-24 13:30 UTC
Labels: coding-in-progress, nice-first-public-release

**Comment by 4ntoine** [comment] 2019-11-18 17:59
I've jumped into the same issue. Since the first version is released i wonder if this should be reopened?

**Comment by emmanuelbernard** [comment] 2019-11-18 18:15
Did you hit a bug @4ntoine? This issue was more a list of features we wanted for Panache. That's why it's closed. Or are you referring to a specific feature mentioned here?

**Comment by nimo23** [comment] 2019-12-06 14:04
@emmanuelbernard are there any chance to use `hibernate-panache` also in wildfly or is and will it only be exclusivly available for quarkus? 

I think, `hibernate-orm` will also benefit from panache capabilities. Having something like `hibernate-panache` would simplify hibernate development in general.

**Comment by FroMage** [comment] 2019-12-06 14:07
The problem is that this relies on build-time enhancements inherent in Quarkus. Someone could write an APT processor to do the same, I guess.
