### ISSUE TITLE
quarkus-oidc: NullPointerException if Keycloak groups contains special characters (äöü)

### ISSUE THREAD

**Issue by mbleichner** [quarkusio/quarkus#29559] opened 2022-11-29 15:39 UTC
### Describe the bug

Using special characters in Keycloak group names causes a NullPointerException, leading to authentication errors.

### How to Reproduce?

1. Create Keycloak group with `ä` in name
2. Assign group to user
3. Try to login via quarkus-oidc

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

### Additional information

The critical line seems to be in OidcIdentityProvider.java:278:

```
final String codeAccessToken = (String) vertxContext.get(OidcConstants.ACCESS_TOKEN_VALUE);
```

This evaluates to `null`.

**Comment by sberyozkin** [comment] 2022-11-29 16:05
@mbleichner Can you please create a test token and paste here ?

**Comment by mbleichner** [comment] 2022-11-30 08:28
Upon further investigation, the NPE doesn't seem to be caused by the group name (it doesn't even appear anywhere in the access token), but by a client role that I had associated with the group containing a colon (`:`).

The access token then contains a section like this:
```
{
  "resource_access": {
    "<client-name>": {
      "roles": [
        "test:doppelpunkt"
      ]
    }
}
```
Maybe this leads to a parse error?

**Comment by sberyozkin** [comment] 2022-11-30 10:51
@mbleichner This is a valid JSON, the value is quoted.
If you paste a test token (in JWT format) here then I can have a look. Or create a reproducer please or may be test Keycloak realm can also be enough

**Comment by sberyozkin** [comment] 2022-12-20 11:59
@mbleichner Have you had any progress on identifying the cause of this NPE ? What is happening is that Quarkus OIDC can not get hold of the access token which must be available after the code flow completes. Having a better error message would be better but I'd rather add this message at the point where for ex it is confirmed a flawed code flow response is provided. 
But NPE, as bad as it is, still blocks the invalid request. So I'll close this issue shortly as I can't progress without a reproducer - we can always reopen once you provide more info

Thanks

**Closed** 2022-12-22 12:30 UTC
Labels: kind/bug, area/oidc, area/keycloak
