### ISSUE TITLE
[Regression] Very slow startup in dev mode when the Kubernetes extension is present

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31355] opened 2023-02-22 18:32 UTC
I'm pretty sure this is a regression as my project wasn't as slow to start in dev mode before.

Note that my project uses the `quarkus-openshift` extension to deploy the project to an OpenShift cluster and does not use the quarkus-kubernetes-client extension directly.

There are two problems:
- the first one is that the startup of the Dev Services is slow even if they end up being not started. This is because  https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-client/deployment-internal/src/main/java/io/quarkus/kubernetes/client/deployment/DevServicesKubernetesProcessor.java#L177
is slow (line is `var autoConfigMasterUrl = Config.autoConfigure(null).getMasterUrl();` as I write these lines). Also I'm wondering if the Dev Services for Kubernetes should be part of the internal extension shared between `quarkus-kubernetes` and `quarkus-kubernetes-client`? I would have expected them to be used for testing applications based on the Kubernetes Client?

![Screenshot 2023-02-22 at 19-28-53 Screenshot](https://user-images.githubusercontent.com/1279749/220723006-9720dcda-9995-4665-bcda-12449a4dd17a.png)

- the second one is that the KubernetesProcessor is extremely slow too, even when simply starting my app in dev mode and not actually deploying anything. AFAICS it boils down to the TopologicalSort code being extremely slow but I'm not sure it's even worth executing all this if we are not deploying something? (Note that the TopologicalSort slowness will need to be fixed anyway)

![Screenshot 2023-02-22 at 19-26-10 Screenshot](https://user-images.githubusercontent.com/1279749/220723091-c17a9f56-fac4-48c6-a5c6-87a3c1172d51.png)

Full profile is attached here: 
[startup-cpu-profile.zip](https://github.com/quarkusio/quarkus/files/10807183/startup-cpu-profile.zip)

**Comment by gsmet** [comment] 2023-02-22 18:34
I can provide more information if needed.

The app is https://github.com/quarkusio/quarkus-github-bot .

**Comment by geoand** [comment] 2023-02-22 18:45
This looks like it needs to be addressed in Dekorate @iocanel , @Sgitario

**Comment by gsmet** [comment] 2023-02-22 19:05
I think part of it should be addressed in Quarkus itself and part of it in Dekorate.

**Comment by Sgitario** [comment] 2023-02-22 19:27
I will have a look at the TopologicalSort algorithm tomorrow.

**Comment by Sgitario** [comment] 2023-02-22 19:46
The performance issue was caused by the implementation of the `isVerbose()`. It should be fixed by https://github.com/dekorateio/dekorate/pull/1156.

**Comment by iocanel** [comment] 2023-02-23 05:35
For starters we need to ensure that kubernetes dev services don't run when kubernetes-client is brought in transitively. 

Besides that I don't see how the sorting algorithm and logging could produce noticeable differences, given the number of items to be sorted is small.

Will look closer later today!

**Comment by gsmet** [comment] 2023-02-28 12:31
Part of it has been fixed by @Sgitario here: https://github.com/quarkusio/quarkus/pull/31445

**Closed** 2023-02-28 16:00 UTC
Labels: area/devmode, area/kubernetes

**Comment by scrocquesel** [comment] 2023-03-07 23:18
>  Also I'm wondering if the Dev Services for Kubernetes should be part of the internal extension shared between `quarkus-kubernetes` and `quarkus-kubernetes-client`? I would have expected them to be used for testing applications based on the Kubernetes Client?

@gsmet theoretically, Dev Services for K8S can provide a Kind cluster. I wonder if it would be possible to deploy the app to this cluster with `quarkus-kind`. In this case, we should keep dev services for k8s in `kubernetes-client-internal` (and find a proper way to optimise startup). I'm not using the https://quarkus.io/guides/deploying-to-kubernetes#deploying-to-kind use case so I don't really know how end user are actually using it and if it make sense at all.
