### ISSUE TITLE
Kafka consumer not working inside a Docker container

### ISSUE THREAD

**Issue by GauthierHacout** [quarkusio/quarkus#19586] opened 2021-08-23 16:38 UTC
### Describe the bug

I have a Quarkus app which is basically a Kafka consumer, when I run my app locally (by using `mvn compile quarkus:dev` for example) everything works fine & as expected ! 

But when I run the same app, with the same configuration (same application.properties file) inside a Docker container by using a simple Dockerfile:
```
FROM maven:3.8.1-openjdk-16-slim AS build

COPY src /home/app/src
COPY pom.xml /home/app
RUN mvn -f /home/app/pom.xml clean package -Dmaven.test.skip=true

FROM adoptopenjdk/openjdk16:alpine-slim
COPY --chown=1001 --from=build /home/app/target/*-runner.jar app.jar

EXPOSE 8044
USER 1001

ENTRYPOINT ["java","-jar","app.jar"]
```

The app doesn't work as expected anymore: 

- The Kafka consumer register correctly, with the correct consumer group, member id & even has partitions assigned :heavy_check_mark: 
- But when I produce Kafka record into the topic, nothing happens, it's like the messages are never consumed :negative_squared_cross_mark: 
- I don't have any exceptions or logs that indicates something went wrong

### Expected behavior

The app should work the same way whereas it's launched inside a Docker or directly in a machine. I should be able to consume Kafka records.

### Actual behavior

The app behaves differently if I'm using Docker. I can't consume Kafka record anymore. 

### How to Reproduce?

Creates a new Quarkus app with a simple Kafka consumer:

```
import io.quarkus.runtime.StartupEvent;
import io.smallrye.mutiny.Multi;
import org.eclipse.microprofile.reactive.messaging.Channel;
import org.eclipse.microprofile.reactive.messaging.Message;
import org.jboss.logging.Logger;

import javax.enterprise.context.ApplicationScoped;
import javax.enterprise.event.Observes;
import javax.inject.Inject;
import java.time.Duration;


@ApplicationScoped
public class SubscriptionConsumer {

    private static final Logger LOG = Logger.getLogger(SubscriptionConsumer.class);

    @Inject
    @Channel("loyalty-subscriptions")
    Multi<Message<Subscription>> subscriptionsStream;

    void onApplicationStart(@Observes StartupEvent event) {
        LOG.info("Starting to consumes channel");
        subscriptionsStream.group().intoLists().of(100, Duration.ofMillis(1000))
                .subscribe().with(item -> {
                    LOG.info("HERE I AM CONSUMING MESSAGES :D");
        });
    }
}

```

Configure you're app to be able to use the smallrye Kafka connector, you might need more configuration but basically :
```
kafka.bootstrap.servers=your_kafka_server
# Configure the incoming channel (reading from Kafka)                                                                             
mp.messaging.incoming.loyalty-subscriptions.connector=smallrye-kafka                                                              
mp.messaging.incoming.loyalty-subscriptions.topic=your_topic                                               
mp.messaging.incoming.loyalty-subscriptions.group.id=your_group_id                                        
mp.messaging.incoming.loyalty-subscriptions.value.deserializer=SimpleJSONDeserializerClassForYourRecords   
mp.messaging.incoming.loyalty-subscriptions.health-readiness-enabled=true                                                         
```

Run the app using the two differents methods I described.

FYI The Kafka record I produce are JSON & basically looking like this:
```
import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@NoArgsConstructor
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class Subscription {

    public String customerKey;

    public String cardCode;

    public String idProgram;

    public String joinDate;

    public String expirationDate;

    public String birthday;

    public String idTier;

    public String c0, c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14, c15, c16, c17, c18, c19, c20, c21, c22, c23, c24, c25, c26, c27, c28, c29, c30, c31;
}
```

### Output of `uname -a` or `ver`

5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

java 16.0.2 2021-07-20 Java(TM) SE Runtime Environment (build 16.0.2+7-67) Java HotSpot(TM) 64-Bit Server VM (build 16.0.2+7-67, mixed mode, sharing)

### Quarkus version or git rev

2.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/ghacout/Tools/maven/apache-maven-3.8.1 Java version: 16.0.2, vendor: Oracle Corporation, runtime: /home/ghacout/Tools/Java/jdk-16.0.2 Default locale: fr_FR, platform encoding: UTF-8 OS name: "linux", version: "5.8.0-59-generic", arch: "amd64", family: "unix"

**Comment by cescoffier** [comment] 2021-08-23 16:43
How is served your Kafka broker and ZK instance? How is the advertisement configured? Kafka is metadata and it is possible that it can't consume your topic because it can't access it.

**Comment by cescoffier** [comment] 2021-08-23 16:45
I would recommend running your broker and app in containers on the same container network.

**Comment by GauthierHacout** [comment] 2021-08-23 16:47
My Kafka broker & ZK instance are AWS managed, aka it's an MSK. I'm using the same Kafka broker in the two cases (both local & Docker) it only doesn't work when I'm using Docker.

I believe access to Kafka is not the issue as my app can register normally in both case producing theses logs:
```
021-08-23 16:46:34,621 INFO  [org.apa.kaf.com.sec.aut.AbstractLogin] (main) Successfully logged in.
2021-08-23 16:46:34,843 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka version: 2.8.0
2021-08-23 16:46:34,844 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka commitId: ebb1d6e21cc92130
2021-08-23 16:46:34,845 INFO  [org.apa.kaf.com.uti.AppInfoParser] (main) Kafka startTimeMs: 1629737194842
2021-08-23 16:46:34,850 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18240: 'throttled' commit strategy used for channel 'loyalty-subscriptions'
2021-08-23 16:46:34,853 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18232: Will commit for group 'loyalty_subscription_service_test' every 5000 milliseconds.
2021-08-23 16:46:34,854 INFO  [io.sma.rea.mes.kafka] (main) SRMSG18236: Will mark throttled commit strategy for group 'loyalty_subscription_service_test' as unhealthy if records go more than 60000 milliseconds without being processed.
2021-08-23 16:46:34,938 INFO  [com.spl.loy.con.SubscriptionConsumer] (main) Starting to consumes channel loyalty-subscriptions
2021-08-23 16:46:34,980 INFO  [org.apa.kaf.cli.con.KafkaConsumer] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Subscribed to topic(s): loyalty.cmd.subscriptions
2021-08-23 16:46:35,181 INFO  [io.quarkus] (main) loyalty_subscription_service 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.1.0.Final) started in 4.053s. Listening on: http://0.0.0.0:8080
2021-08-23 16:46:35,183 INFO  [io.quarkus] (main) Profile prod activated. 
2021-08-23 16:46:35,184 INFO  [io.quarkus] (main) Installed features: [agroal, cache, cdi, hibernate-orm, jdbc-mysql, kafka-client, logging-gelf, micrometer, narayana-jta, smallrye-context-propagation, smallrye-health, smallrye-reactive-messaging, smallrye-reactive-messaging-kafka, vertx]
2021-08-23 16:46:35,937 INFO  [org.apa.kaf.cli.Metadata] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Cluster ID: SWhZwmVDTfyTTToFMvzaIQ
2021-08-23 16:46:35,940 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Discovered group coordinator b-1.aws-par-dev-kafka-msk.k9b2kt.c2.kafka.eu-west-3.amazonaws.com:9096 (id: 2147483646 rack: null)
2021-08-23 16:46:35,944 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] (Re-)joining group
2021-08-23 16:46:36,108 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] (Re-)joining group
2021-08-23 16:46:39,202 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Successfully joined group with generation Generation{generationId=9, memberId='kafka-consumer-loyalty-subscriptions-0ca2f96f-85d2-477b-8fd8-48618cba0a93', protocol='range'}
2021-08-23 16:46:39,209 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Finished assignment for group at generation 9: {kafka-consumer-loyalty-subscriptions-0ca2f96f-85d2-477b-8fd8-48618cba0a93=Assignment(partitions=[loyalty.cmd.subscriptions-0])}
2021-08-23 16:46:39,229 INFO  [org.apa.kaf.cli.con.int.AbstractCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Successfully synced group in generation Generation{generationId=9, memberId='kafka-consumer-loyalty-subscriptions-0ca2f96f-85d2-477b-8fd8-48618cba0a93', protocol='range'}
2021-08-23 16:46:39,232 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Notifying assignor about the new Assignment(partitions=[loyalty.cmd.subscriptions-0])
2021-08-23 16:46:39,238 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Adding newly assigned partitions: loyalty.cmd.subscriptions-0
2021-08-23 16:46:39,272 INFO  [org.apa.kaf.cli.con.int.ConsumerCoordinator] (smallrye-kafka-consumer-thread-0) [Consumer clientId=kafka-consumer-loyalty-subscriptions, groupId=loyalty_subscription_service_test] Setting offset for partition loyalty.cmd.subscriptions-0 to the committed offset FetchPosition{offset=17815719, offsetEpoch=Optional.empty, currentLeader=LeaderAndEpoch{leader=Optional[b-3.aws-par-dev-kafka-msk.k9b2kt.c2.kafka.eu-west-3.amazonaws.com:9096 (id: 3 rack: euw3-az1)], epoch=absent}}
```

I can see using tools like AKHQ that my app is indeed registered as a member of the consumer group, with a partition of the topic assigned to it.

**Comment by cescoffier** [comment] 2021-08-23 18:59
That is going to be hard to reproduce for me. I have apps running in containers and connecting to managed instances of Kafka without any issue. 

Are you in JVM or native mode?

**Comment by cescoffier** [comment] 2021-08-24 07:55
Looking at 
![image](https://user-images.githubusercontent.com/402301/130578838-d1942560-6c3b-4a29-80d1-46d7be1ff8bf.png)


There is a very good chance that your container lives is a different network. Yes, some interactions works, but some would not. I would recommend trying to run kafka tools in your container to see if the problem comes from the network configuration or from quarkus.

**Comment by GauthierHacout** [comment] 2021-08-24 08:22
Hello, 

The app is run in JVM, not Native mode. I understand that it can be hard to reproduce, I'll try to create an minimal app that reproduce my issue for you to test. 

Although I have trouble understanding why network would be the issue here because it works perfectly when I run the app directly on my machine. It only doesn't work when I run the app (on the same machine) inside a Docker container.

**Comment by GauthierHacout** [comment] 2021-08-24 10:16
FYI I fixed my issue by using another Docker image for run time. 

I went from `adoptopenjdk/openjdk16:alpine-slim` to `openjdk:16` at my problem got resolved. The app is now working the same way whereas I use Docker or not. I believe it's more of a Java alpine image issue than a Quarkus issue then.

**Comment by cescoffier** [comment] 2021-08-24 11:13
Oh thanks for the feedback! 
Probably related to musl (the libc used in alpine).

If I understand correctly you were able to connect to AMK from your own machine? I failed, I add to use an ec2 instance running on the same VPC. That leads me to the network issue I was mentioning.

**Comment by GauthierHacout** [comment] 2021-08-24 15:54
Yes maybe I should have been a little more precise, I'm using a VPN to connect to AWS managed services (MySQL, Kafka, whatever I need...) from my machine. This is why I'm able to consume Kafka topics even though my app is not inside AWS network directly. 

But since my problem was purely Docker related I didn't elaborate on the MSK part. 

The fix is nice & easy but it was hard to debug this issue, as smallrye Kafka connector didn't care to give me any error log or throw any exception :( 

Hope this issue will help other people if they ever need it !

**Comment by cescoffier** [comment] 2021-08-25 05:45
Actually, it's not the connector, it's even deeper in the Kafka client that something is swallowed. Hard to tell what.

As it looks like a container image issue, I'm going to close this issue for now. If someone can provide a reproducer I can run locally, I would be happy to look to what was swallowed.

**Closed** 2021-08-25 05:45 UTC
Labels: kind/bug, triage/invalid, area/kafka

**Comment by PhilGBr** [comment] 2024-10-04 15:17
FI, I had the same problem with `eclipse-temurin:21-alpine`, and it was solved using `eclipse-temurin:21`

**Comment by cescoffier** [comment] 2024-10-04 17:22
Alpine is not using a complete libc. It can cause issues.
