### ISSUE TITLE
Add extension for hazelcast

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#8160] opened 2020-03-25 16:21 UTC
Need share session use cluster manager like hazelcast etc when use websocket.

**Comment by nimo23** [comment] 2020-03-25 16:31
Already there: https://github.com/quarkusio/quarkus/pull/6758

**Comment by geoand** [comment] 2020-03-25 16:31
See https://github.com/quarkusio/quarkus/pull/6758

**Comment by emmanuelbernard** [comment] 2020-03-25 17:26
Yes let's consider it a dupe of #6758 for now.

**Closed by emmanuelbernard** 2020-03-25 17:26 UTC
Labels: kind/extension-proposal
