### ISSUE TITLE
Quarkus project using hibernate validator on classes from separate jars does not compile with 1.13.5.Final

### ISSUE THREAD

**Issue by bgoggin** [quarkusio/quarkus#17491] opened 2021-05-27 00:14 UTC
## Describe the bug
(Describe the problem clearly and concisely.)
I have a couple of projects that use DTO classes from another jar that are annotated with hibernate validator classes. This includes validations on type declarations for container classes. When I moved from 1.13.4.Final to 1.13.5.final, my project failed to compile.

### Expected behavior
(Describe the expected behavior clearly and concisely.)
I expected everything to compile as with past Quarkus version upgrades.

### Actual behavior
(Describe the actual behavior clearly and concisely.)
The compile for both project failed with stack trace:
F
[demo1.zip](https://github.com/quarkusio/quarkus/files/6550261/demo1.zip)
ailed to execute goal io.quarkus:quarkus-maven-plugin:1.13.5.Final:build (default) on project scoreapi: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] [error]: Build step io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor#build threw an exception: java.lang.ClassCastException: class org.jboss.jandex.ClassInfo cannot be cast to class org.jboss.jandex.MethodInfo (org.jboss.jandex.ClassInfo and org.jboss.jandex.MethodInfo are in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @5411fed2)
[ERROR] at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:56)
[ERROR] at org.jboss.jandex.MethodParameterTypeTarget.enclosingTarget(MethodParameterTypeTarget.java:39)
[ERROR] at io.quarkus.hibernate.validator.deployment.HibernateValidatorProcessor.build(HibernateValidatorProcessor.java:281)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:920)
[ERROR] at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
[ERROR] at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
[ERROR] at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] at org.jboss.threads.JBossThread.run(JBossThread.java:501)

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. reproducer attached.
2. 
3. 

### Configuration
```properties
# Add your application.properties here, if applicable.

```

### Screenshots
(If applicable, add screenshots to help explain your problem.)

### Output of `uname -a` or `ver`
Darwin BillMacBookPro.local 20.5.0 Darwin Kernel Version 20.5.0: Sat May  8 05:10:33 PDT 2021; root:xnu-7195.121.3~9/RELEASE_X86_64 x86_64
### Output of `java -version`
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05)
OpenJDK 64-Bit Server VM GraalVM CE 21.1.0 (build 11.0.11+8-jvmci-21.1-b05, mixed mode, sharing)
### GraalVM version (if different from Java)
CE 21.1.0
### Quarkus version or git rev
1.13.4.Final and 1.13.5.Final(attempted)
### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)
Maven home: /usr/local/Cellar/maven/3.8.1/libexec
Java version: 11.0.11, vendor: GraalVM Community, runtime: /Library/Java/JavaVirtualMachines/graalvm-ce-java11-21.1.0/Contents/Home
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "11.4", arch: "x86_64", family: "mac"
## Additional context
(Add any other context about the problem here.)

**Comment by geoand** [comment] 2021-05-27 05:13
Seems to also be a problem in `2.0.0.CR1`

**Comment by yrodiere** [comment] 2021-05-27 07:31
Having a look right now; we can rule out lombok as the source of the problem, as the problem persists even without lombok.

**Comment by yrodiere** [comment] 2021-05-27 07:31
By the way, thanks a lot for the reproducer, @bgoggin!

**Comment by yrodiere** [comment] 2021-05-27 07:56
Ok; so this looks like a bug in Jandex.

In `org.jboss.jandex.MethodParameterTypeTarget`:

```
    @Override
    public MethodInfo enclosingTarget() {
        return (MethodInfo) super.enclosingTarget();
    }
```

For an annotated parameter in a constructor, `super.enclosingTarget()` returns a `ClassInfo` representing the class declaring the constructor, instead of representing the constructor itself. This seems wrong, and anyway it causes the cast to fail.

I'll look into writing a reproducer for Jandex and reporting this.

**Comment by yrodiere** [comment] 2021-05-27 12:18
Created https://github.com/wildfly/jandex/pull/121 downstream. Not sure they will merge it as-is, but at least we have a reproducer and a fix.

**Comment by gsmet** [comment] 2021-05-27 12:44
I'm pushing a 1.13.6.Final/2.0.0.CR2 with a workaround.

**Comment by famod** [comment] 2021-05-31 11:09
@gsmet isn't this now fixed via #17493?

**Comment by yrodiere** [comment] 2021-05-31 11:14
@famod #17493 is just a workaround. Not a fix. Annotations that trigger an exception are ignored, so there's still the problem of ignoring validation constraints.

The actual fix will be the upgrade of Jandex once https://github.com/wildfly/jandex/pull/121 gets merged and released.

**Comment by famod** [comment] 2021-05-31 11:23
Ok, thanks. I'll add the "upstream" label then...

**Closed** 2021-06-03 17:31 UTC
Labels: area/hibernate-validator, kind/bug, triage/upstream
