### ISSUE TITLE
Quarkus 1.10.2.final issue with SSL config

### ISSUE THREAD

**Issue by AlbozDroid** [quarkusio/quarkus#13703] opened 2020-12-04 13:54 UTC
**Describe the bug**
A Quarkus web app that has configured SSL (keystore, password) would not build in developer mode with the latest Quarkus.
This used to work fine in Quarkus 1.9.2.final.

**Expected behavior**
Application to start normally

**Actual behavior**
The application throws this error:
```
2020-12-04 13:33:39,157 ERROR [io.qua.run.Application] (Quarkus Main Thread) Port 8080 seems to be in use by another process. Quarkus may already be running or the port is used by another application.
```
There is NO other application running in that port.

**To Reproduce**
1. configure the following SSL properties on a project with Quarkus 1.10.2:
```
quarkus.ssl.native=true
quarkus.http.ssl-port=443
quarkus.http.ssl.certificate.key-store-file=server.keystore
quarkus.http.ssl.certificate.key-store-password=ssl_pass
```
2. Run `./mvnw compile quarkus:dev`
[Uploading code-with-quarkus.zip…]()

> Note: If we remove the above SSL properties then everything works fine.

or simply: Download the attached reproducer!
[code-with-quarkus 2.zip](https://github.com/quarkusio/quarkus/files/5643126/code-with-quarkus.2.zip)

**Comment by gsmet** [comment] 2020-12-04 15:16
So first, we need to fine tune the message introduced in https://github.com/quarkusio/quarkus/pull/12683 because the bind exception could also be due to the SSL port not being available.

Now I can't reproduce this on Linux:
- I have a permission denied exception if using 443 and not root, which is expected
- if I change the port back to the default 8443, the app starts OK

I have the exact same behavior with 1.9.2.Final.

@cescoffier could you try to reproduce it on your Mac once you get it back? FTR, I had to manually copy the `server.keystore` to `target/` for it to work on my box (and avoid `clean`).

**Comment by gsmet** [comment] 2020-12-04 17:34
@cescoffier so no need to do anything, we figured it out.

Actions:
* also point to the SSL port in the message is SSL is enabled
* clarify why the keystore is not taken into account

**Comment by gsmet** [comment] 2022-12-12 10:29
We now list all the ports in the error message so we can close this one.

**Closed by gsmet** 2022-12-12 10:29 UTC
Labels: kind/bug, triage/needs-triage
