### ISSUE TITLE
Docker Integrationtests are Broken on MAC since Quarkus 2.1.x

### ISSUE THREAD

**Issue by goafabric** [quarkusio/quarkus#19373] opened 2021-08-12 12:03 UTC
### Describe the bug

Annotating a class with "QuarkusIntegrationTest" 
bootstrapped a Docker Container in Versions < 2.1 by calling

"docker, run, --rm, -p, 8081:8081" ....

this has now changed to

"docker run --rm --net=host"

Unfortunately the type "net=host" is not supported under Macos thus breaking the tests and the build.

### Expected behavior

The Tests should work as with Quarkus < 2.1,
which may require to fall back to the old "-p 8081,8081" version

### Actual behavior

Tests are broken

### How to Reproduce?

Run a QuarkusIntegrationsTests with a Docker Image under Mac
with RestAssured

### Output of `uname -a` or `ver`

arm64v8

### Output of `java -version`

OpenJDK Runtime Environment Zulu11.45+27-CA (build 11.0.10+9-LTS)

### GraalVM version (if different from Java)

21.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by famod** [comment] 2021-08-16 22:31
Most likely related to #18653.

**Comment by geoand** [comment] 2021-08-23 05:09
This is a duplicate of https://github.com/quarkusio/quarkus/issues/18914 and has been fixed from Quarkus `2.2.0.CR1` onward

**Closed** 2021-08-23 05:09 UTC
Labels: kind/bug, area/testing
