### ISSUE TITLE
hibernate-orm-panache-resteasy: updating does not work

### ISSUE THREAD

**Issue by domdorn** [quarkusio/quarkus#1662] opened 2019-03-24 20:59 UTC
I just tried out the `hibernate-orm-panache-resteasy` example and updating a fruit does not work. 

E.g. when updating "Apple" to "Applexxx", I get this response from the rest-endpoint:
```{"persistent":false,"id":2,"name":"Applexxx"}```
adding entity.persist() in the update method of com/acme/hibernate/orm/panache/FruitResource.java:71 did not make any difference. 

There's no exception in the log and nothing obviously wrong in the code. Why is it not working?

**Comment by FroMage** [comment] 2019-03-26 10:10
This must be a dupe of #1376 that I created a PR for just now. Don't hesitate to reopen if the PR does not fix your issue :)

**Closed by FroMage** 2019-03-26 10:10 UTC
Labels: panache
