### ISSUE TITLE
support java record class as @IdClass in hibernate

### ISSUE THREAD

**Issue by lost22git** [quarkusio/quarkus#36641] opened 2023-10-23 15:42 UTC
### Describe the bug

Because id is generally immutable, I simply think that java record class as @IdClass is appropriate. But it dont seem to work in hibernate now?

```java
@RegisterForReflection
@Entity
@Table(name = "test")
@IdClass(Test.PK.class)
public class Test extends PanacheEntityBase {

    @RegisterForReflection
    public record PK(
        long aId,
        long bId
    ) implements Serializable {
    }
   
   @Id
   public long aId;
   @Id
   public long bId;

}
```

* error info
```
.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at io.quarkus.runner.bootstrap.StartupActionImpl$1.run(StartupActionImpl.java:113)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ExceptionInInitializerError
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
	at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
Caused by: java.lang.ExceptionInInitializerError

	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
	at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
	at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
	at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:70)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:44)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:124)
	at lost.test.quarkus.Main.main(Main.java:21)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	... 3 more
Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
Caused by: java.lang.RuntimeException: Failed to start quarkus

	... 16 more
Caused by: java.lang.RuntimeException: Could not access record components
Caused by: java.lang.RuntimeException: Could not access record components
```

**Comment by yrodiere** [comment] 2023-10-23 15:52
Hello,

Records have never worked as an `@IdClass`, so this is not a bug, this is a feature request.

What's more, this is a request for a feature in Hibernate ORM itself, not in Quarkus, so it should be submitted on the Hibernate ORM tracker. As it happens, it's already tracked there: https://hibernate.atlassian.net/browse/HHH-15493

I'm going to close this, please follow progress on https://hibernate.atlassian.net/browse/HHH-15493 .

**Closed by yrodiere** 2023-10-23 15:52 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm
