### ISSUE TITLE
Panache Many-To-Many Association repository not reflected in main entities.

### ISSUE THREAD

**Issue by adjiandov** [quarkusio/quarkus#24810] opened 2022-04-06 22:22 UTC
### Describe the bug

In order to try and keep it short I will use sample code.
I have Entity A with Id(Long) and Entity B with Id(Long), both having PanacheRepository.
They are connected with AxB association table where A.id and B.id is stored.
In order to minimise data traffic and simplify API signature I would like to be able to add/remove from the association table directly, not through one of the main entities. For that purpose I have created AxB Entity with IdClass containing both ids (so composite key of both columns).
I have done an integration test to test this functionality and for addition it works fine.
In order to test the removal I first generate both entity A and B an insert one AxB entity into the association. Using the PanaheRepository<A> I getById(A.id) and assert that the association is present.
Next step is the removal of AxB through PanacheBaseRepository<AxB, IdCalss> using deleteById method.
I stop in the code with breakpoint and check that the removal on the DB level is complete and the entry is gone, however when calling PanaceEntity<A>.getById, the associations Set in A still contains the association.

Note: This is all happening into one transaction.

### Expected behavior

After the removal of the entry in AxB table, when asking PanacheRepository<A>.getById(A.id) I should receive entity having the same state as the Database has.

### Actual behavior

The entity has some stale state.

### How to Reproduce?

1. Create two entities (A and B) associated with each other through association table(AxB).
2. Annotate them with @ManyToMany association.
3. Create entity representing the association table.
4. Create repositories for all entities.
5. Create integration test which persists entity A, entity B and uses their ids to persist AxB, then based on their ids use the PanacheBaseRepository<AxB>.deleteById method to remove the AxB entity, call PanacheRepository<A>.getById(A.id) and it will still contain set of B entity.

### Output of `java -version`

17

### Quarkus version or git rev

latest

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn

**Comment by FroMage** [comment] 2022-04-08 15:20
Thanks, would you be able to give us a reproducer project please?

**Comment by adjiandov** [comment] 2022-04-14 12:28
Hello,
Here is a reproducer project https://github.com/adjiandov/quarkus-reproducer.

Have a look at removeStudentsFromCourseTest.

**Comment by BobanNikolov** [comment] 2022-04-21 09:06
Hello,
I have come to the same issue as mentioned here. Is there any update ?

**Comment by adjiandov** [comment] 2022-04-21 09:08
@FroMage

**Comment by FroMage** [comment] 2022-05-10 09:10
I've tried by removing the Panache layer and just plain ORM and have exactly the same issue, so this is not related to Panache.

Also, I am not familiar with your way of dealing with many-to-many here, because you seem to have a normal many-to-many relation declared on `Student` and `Course` but then you have a manual association declared in `StudentToCourse` but with just IDs. I've never done that, and you mix the two approaches, so I don't know what the effects are supposed to be.

Normally I'd skip `StudentToCourse` entirely, or make it a real entity, with two `@ManyToOne` associations (to `Course` and `Student`).

Perhaps @yrodiere or @Sanne can help?

**Comment by adjiandov** [comment] 2022-05-10 09:24
Hi @FroMage but what is the implementation of ORM, there has to be some implementation to the ORM specification.
I have done the exact same thing with Spring and Hibernate ORM, therefor I expected the same behavior.

**Comment by FroMage** [comment] 2022-05-10 09:27
This is Hibernate ORM. Perhaps your transaction or session boundaries were different in the past?

**Comment by adjiandov** [comment] 2022-05-10 09:54
Transactions and sessions was left out to the default Hibernate settings. There was no explicit Transactional added only the @AutoConfigureDataJpa

**Comment by yrodiere** [comment] 2022-06-01 13:19
I finally had some time to have a look.

First, I agree with @FroMage: having two reprensentations of the same table in your model is unusual. Especially if both are mutable. It could cause problems, in particular when it comes to the session's first-level cache: Hibernate ORM won't automatically synchronize the multiple representations of the same row (association in `Student`/`Course` on one side, and `StudentToCourse` on the other side). But if you're saying you've done that before... you're free to live dangerously :)

But your problem is not there, actually. As was mentioned earlier, it has to do with transactions. Your test doesn't create a transaction, but some of the methods it calls do. This results in a mess, with some methods being executed in the context of their own transaction and the corresponding session, and other methods being (all) executed without a transaction and in the context of a common, longer-lived session.

In particular, `courseService.getCourse` (which you're calling for your assertions) is not run in a transaction, so your two calls to `getCourse` are potentially using the same session, with its own first-level cache, which explains that you're not seing any changes after the second call to `getCourse`: the session you're using for your second assertion is relying on its internal cache, which is out of sync with the database.

At the very least, you should make sure each "operation" runs in its own transaction. That means calls to service methods such as `addStudentsToCourse` (so far, so good: they're annotated with `@Transactional`), but also assertions: the retrieval of an entity, as well as any check that you perform on that entity, should be executed in its own, separate transaction; otherwise you may reuse context (first-level cache) from a previous assertion.

Really, you should just ensure everything runs in its own transaction. Using JPA outside of a transaction is dodgy, and if I had my say, I would have disabled that by default: it's just too dangerous if you don't know what you're doing.

For example take advantage of [`QuarkusTransaction`](https://quarkus.io/guides/transaction#programmatic-approach) to run your assertions in their own transaction:

```
  @Test
  void testRemoveStudentsFromCourse() {
    var course = generateCourse();
    var student1 = generateStudent1();
    var student2 = generateStudent2();

    // Initialization
    QuarkusTransaction.begin();
    course = courseService.save(course);
    student1 = studentService.save(student1);
    student2 = studentService.save(student2);
    QuarkusTransaction.commit();

    // Transactional method call
    studentToCourseService.addStudentsToCourse(course.getId(),
        Set.of(student1.getId(), student2.getId()));

    // Assertion - needs its own transaction.
    QuarkusTransaction.begin();
    final var updatedCourse = courseService.getCourse(course.getId());
    assertTrue(updatedCourse.getStudents().size() > 0);
    QuarkusTransaction.commit();

    // Transactional method call
    studentToCourseService.removeStudentsFromCourse(course.getId(),
        Set.of(student1.getId()));

    // Assertion - needs its own transaction.
    QuarkusTransaction.begin();
    final var result = courseService.getCourse(course.getId());
    assertEquals(1, result.getStudents().size());
    QuarkusTransaction.commit();
  }
```

The test above will pass, without changing your "main" code.

Alternatively, if you want to stick to standards, [`UserTransaction`](https://quarkus.io/guides/transaction#legacy-api-approach) would work too. But it's arguably less convenient.

So, I'm going to close this ticket. If you disagree with my assessment, feel free to answer here; but if you need more advice related to persistence/transactions, please start a [discussion](https://github.com/quarkusio/quarkus/discussions) instead.

In any case, thanks for reaching out!

**Closed by yrodiere** 2022-06-01 13:19 UTC
Labels: kind/bug, area/hibernate-orm
