### ISSUE TITLE
Named oidc-client configuration from .env file is null

### ISSUE THREAD

**Issue by Sirz3chs** [quarkusio/quarkus#29325] opened 2022-11-17 08:25 UTC
### Describe the bug

I'm creating an named oidc-client in my application and the configuration come from a `.env` file. When quakus starts the config properties are loaded correctly but the injected client is `null`, same when injecting `OidcClients`, there's no client inside. The exact same configuration in `application.properties` file is working fine. If the client is not a named one, it seem's to work, but the grant types are not defined, i didn't dig more on it because that's what I saw when creating the reproduction.

### Expected behavior

The injected `OidcClient` from `.env` configurations is not null.

### Actual behavior

The injected `OidcClient` from `.env` configurations is null.

### How to Reproduce?

Steps to reproduce: 
1. Create a named oidc-client configuration in `.env`
2. Inject the `OidcClient`

Reproducer: https://github.com/Sirz3chs/quarkus-oidc-client-env-issue

### Output of `uname -a` or `ver`

Linux 5.4.0-131-generic #147-Ubuntu SMP Fri Oct 14 17:07:22 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)

### Quarkus version or git rev

2.13.4.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

The issue is still reproductible in 2.14.0.Final.
I've foud two closed issues that may be related #14480 #24078

**Comment by sberyozkin** [comment] 2022-11-17 09:08
Hey @radcortez, can you have a quick look please, I recall you were advising to have `application.properties` contain empty declarations anyway due to `oidc-client` containing a `-`, not sure it is related, please clarify again and I'll doc it, thanks

**Comment by Sirz3chs** [comment] 2022-11-23 10:55
Thanks for the answer, that's actually what i did as workaround.

**Comment by radcortez** [comment] 2022-11-23 11:30
If you use something like:

`quarkus.oidc-client.env-client.auth-server-url=${QUARKUS_OIDC_CLIENT__ENV_CLIENT__AUTH_SERVER_URL}`

This will work because the value is looked up with the exact name as expected from the Env Source.

I believe the client must always have the configuration available if the property is present. @sberyozkin can you confirm?

**Comment by sberyozkin** [comment] 2022-11-23 15:18
Hi @radcortez Thanks for the advice, 
`quarkus.oidc-client.env-client.auth-server-url=${QUARKUS_OIDC_CLIENT__ENV_CLIENT__AUTH_SERVER_URL}`

Looks OK to me, and @Sirz3chs has confirmed it works. 
I can work on a doc PR adding a note to the config docs and to OIDC docs to clarify https://github.com/quarkusio/quarkus/issues/29325#issuecomment-1322078347

**Comment by gsmet** [comment] 2023-01-23 10:24
@sberyozkin looks like something we could easily close with some documentation?

**Comment by radcortez** [comment] 2023-01-23 11:25
We recently improved the env rules docs:
https://github.com/quarkusio/quarkus/pull/30369

Not sure what would be the best strategy. I don't think we want to duplicate this on every extension that uses Maps in Config.

**Comment by sberyozkin** [comment] 2023-02-16 22:38
@gsmet Hi Guillaume, do you think Roberto's update is sufficient ? I suppose users who want to use ENV properties will go to the Quarkus Config docs first and find the latest update there ?

**Comment by sberyozkin** [comment] 2023-02-17 17:50
Let me close this one, Guillaume, if you think more specific updates are necessary, please reopen. It feels like this info being available in the main Config docs makes it very visible

**Closed by sberyozkin** 2023-02-17 17:50 UTC
Labels: kind/bug, area/config, area/oidc
