### ISSUE TITLE
Quarkus Websocket sometimes not send the object

### ISSUE THREAD

**Issue by ThomasSousa96** [quarkusio/quarkus#12068] opened 2020-09-14 01:30 UTC
**Describe the bug**

I'm using [Quarkus WebSocket](https://quarkus.io/guides/websockets) in my app. I have a Session list and when occurs some event in my app I sends a message to the opened sessions.

```java
list.forEach(s -> {
    s.getAsyncRemote().sendObject(foo, r -> {
        if (r.isOK()) {
           System.out.println("OK");
        } else {
           System.out.println("FAIL");
        }
    });
}
```

 * This forEach is executed inside a managedExecutor.runAsync method.

The problem is that frequently I send a message, the result handler returns `isOK() == true`, but the message is not sent to the browser. I see the chrome developer tools and the message wasn't received.

 * This problem isn't with a specific message. My messages is a POJO as JSON;
 * Sometimes the app sent the message, but is not guaranteed;

I created a setTimeout in the js to force retrieve the messages. It's working, but the backend need a request to send a message.

**Expected behavior**
That all times the result handler return `isOK() == true` the messaage was really sent.

**Actual behavior**
Sometimes the result handler return `isOK() == true` but the message is not sent to the browser.

**To Reproduce**
1. Create a simple WebSocket client in js
2. Create a WebSocket server following this [example](https://quarkus.io/guides/websockets)
3. In other thread (a thread of a http request by example) send a object to session list, using a [`ManagedExecutor.runAsync`](https://quarkus.io/guides/context-propagation)
4. Check the `isOK`
5. Check the client and the Chrome Developer tool
5. Repeat this steps sometimes until the isOK return true and the browser not receive the message

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Linux thomas 5.4.0-47-generic #51-Ubuntu SMP Fri Sep 4 19:50:52 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 8
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 3.6.3
- Chrome version: Version 84.0.4147.89 (Official Build) (64-bit)

**Additional context**
(Add any other context about the problem here.)

**Comment by stuartwdouglas** [comment] 2020-09-15 03:52
How are you encoding the websocket messages? Are you using javax.websocket.Encoder ?

**Comment by ThomasSousa96** [comment] 2020-09-15 13:11
@stuartwdouglas yes, I did create a `JsonMessageEncoder` class, that is sub class of `Encoder.Text<Foo>`, and did configure it in the annotation `@ServerEndpoint(encoders = JsonMessageEncoder.class)`. Internally it use a instance of `Jsonb` to serialize the objecs. The objects are serialized with success.

**Comment by stuartwdouglas** [comment] 2020-09-16 01:32
Do you have a reproducer? I tried a simple one yesterday and did not observe any problems. 

This code path basically passes the object straight into Netty websockets, if it is not being sent it looks like it would have to be a Netty problem, but Netty is very widely deployed so that seems unlikely.

**Comment by geoand** [comment] 2024-02-27 10:24
Closing for a lack of a reproducer

**Closed by geoand** 2024-02-27 10:24 UTC
Labels: kind/bug

**Comment by kumawatanupriya** [comment] 2024-03-04 11:18
@ThomasSousa96 Hi, was this issue resolved ?? , I am also facing the exact issue with quarkus-websockets, On client side using react with react-use-websocket.
