### ISSUE TITLE
Testcontainers ryuk abandoned during build without testing using Gradle

### ISSUE THREAD

**Issue by kdubb** [quarkusio/quarkus#25852] opened 2022-05-29 20:28 UTC
### Describe the bug

The ryuk container from the Testcontainers project is abandoned when building without running any tests.

We are experiencing this with Gradle, I cannot say wether this the same as for other build tools.

Also, we are using a multi-module Gradle project where we have many Quarkus micro-services under one parent project. If we build all the modules in one go, we get a ryuk container for each sub-module.

### Expected behavior

Preferably ryuk containers are not started but at the very least they should be cleaned up after the build is done.

### Actual behavior

Ryuk container(s) are abandoned and must be removed from docker manually.

### How to Reproduce?

Run a build without testing in a Gradle single or multi-module project.

Example:

     ./gradlew build -Dquarkus.profile=prod -Dquarkus.container-image.build=true -x test -x integrationTest

### Output of `uname -a` or `ver`

macOS 12

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4

**Comment by jskillin-idt** [comment] 2022-08-16 22:29
I am not a developer so take my suggestion here with healthy skepticism, but this is perhaps an issue with your Docker or test setup, as Ryuk is intended to self-destruct on its own once it observes the JVM closing.

**Comment by geoand** [comment] 2022-10-19 09:43
Is this still an issue?

**Comment by kdubb** [comment] 2022-10-19 15:43
I will check. We had put a task in our Gradle project to kill all ryuk containers after completion; not pretty but it worked.

**Comment by kdubb** [comment] 2022-10-19 15:54
<img width="658" alt="Screen Shot 2022-10-19 at 8 54 35 AM" src="https://user-images.githubusercontent.com/787655/196742625-b5a33bb6-1fbc-4911-a611-140c72600f5e.png">

**Comment by geoand** [comment] 2022-10-19 15:59
Darn...

**Comment by kdubb** [comment] 2022-10-19 16:00
I've just realized those orphaned containers are specifically from our `systemTest` task/configuration. It uses a Gradle nested build (a `GradleBuild` task in main `build.gradle.kts`) to build the project with the correct profile and then starts all the services using Docker Compose to runs some e2e tests.

The orphaned ryuk containers are from when it builds some of the services in the nested build. If I run the same type build as the nested build from the command line it doesn't happen.

**Comment by kdubb** [comment] 2022-10-19 21:23
I'm trying to recreate a simple multi-module Gradle project that reproduces this behavior.

**Comment by kdubb** [comment] 2022-10-19 22:26
I've finally created a reproducer. It seems related to multi-module projects and building containers.

The first project, `lib`, is a java library and includes `@QuarkusTest`s to test our common code that requires Quarkus extensions. For example, this includes common code that accesses Vault.

The second project, `app`, is a normal Quarkus application that includes `lib` to use the common code previously mentioned.

To reproduce the issue and get an orphaned ryuk container, run:

    ./gradlew clean build -Dquarkus.container-image.build=true

Running without tests, produces the same result:

    ./gradlew clean build -Dquarkus.container-image.build=true -x test

Notably, running a normal build with/without tests, using the following, will not orphan any containers:

    ./gradlew clean build

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/9824761/code-with-quarkus.zip)

**Comment by geoand** [comment] 2022-10-20 05:39
Thanks for the thorough analysis!

I'll have a look

**Comment by geoand** [comment] 2022-10-20 06:38
The reproducer was most helpful!

https://github.com/quarkusio/quarkus/pull/28702 fixes the issue

**Closed** 2022-10-20 13:14 UTC
Labels: kind/bug, area/gradle
