### ISSUE TITLE
Command line stuck for mvn quarkus:dev on windows 11

### ISSUE THREAD

**Issue by olivierbeltrandocintoo** [quarkusio/quarkus#29726] opened 2022-12-07 10:53 UTC
### Describe the bug

I have a simple project (which runs fine in WSL :)) created from the 'kotlin' template from this page https://quarkus.io/guides/kotlin.
Whenever I run the goal `mvn quarkus:dev` from a windows 11 `cmd` or `powershell` it displays the following stacktrace, and it won't accept any input (pressing `r` to run the tests does not work).

I also tried updating to the latest bom for quarkus platform: 2.14.3.

```shell
[INFO] --- quarkus-maven-plugin:2.14.3.Final:dev (default-cli) @ rest-poc ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ rest-poc
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.14.3.Final:generate-code @ rest-poc
[INFO] Invoking org.jetbrains.kotlin:kotlin-maven-plugin:1.7.21:compile @ rest-poc
[INFO] Applied plugin: 'all-open'
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ rest-poc
[INFO] Changes detected - recompiling the module!
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ rest-poc
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\Users\OlivierBeltrando\dev\rest-poc\src\test\resources
[INFO] Invoking io.quarkus.platform:quarkus-maven-plugin:2.14.3.Final:generate-code-tests @ rest-poc
[INFO] Invoking org.jetbrains.kotlin:kotlin-maven-plugin:1.7.21:test-compile @ rest-poc
[INFO] Applied plugin: 'all-open'
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ rest-poc
[INFO] Changes detected - recompiling the module!
Listening for transport dt_socket at address: 5005
Exception in thread "WindowsStreamPump" java.lang.UnsatisfiedLinkError: 'void org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.init()'
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.init(Native Method)
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.<clinit>(Kernel32.java:583)
        at org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.<init>(Kernel32.java:735)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:823)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:106)
        at org.aesh.readline.terminal.impl.WinSysTerminal.readConsoleInput(WinSysTerminal.java:73)
        at org.aesh.readline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2022-12-07 11:30:51,254 INFO  [io.quarkus] (Quarkus Main Thread) rest-poc 0.0.1-SNAPSHOT on JVM (powered by Quarkus 2.14.3.Final) started in 1.677s. Listening on: http://localhost:8080

2022-12-07 11:30:51,259 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-12-07 11:30:51,260 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kotlin, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
--
Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
```

## from cmd with mvn (3.8.6)
![image](https://user-images.githubusercontent.com/119603054/206156990-51d085c1-633f-4a1d-88fc-b798447b2d50.png)

## from pwershell with mvnw (that invokes mvn 3.8.6 behind the scenes)
![image](https://user-images.githubusercontent.com/119603054/206157484-6d9c8c39-9280-4c5b-88f7-01d40cacf921.png)

This seems to happen *only* on pure windows 11 (I haven't tested on any other windows version), but runs fine within WSL.

Many thanks in advance for your help.
Cheers,
Olivier

### Expected behavior

The terminal should be able to receive user input.
There should not be any stack traces

### Actual behavior

Stack trace shows up. Terminal is frozen and won't accept user input.

### How to Reproduce?

from a powershell with 
* JAVA_HOME and PATH updated with this version of Java
    * https://download.java.net/openjdk/jdk17/ri/openjdk-17+35_windows-x64_bin.zip
* mvn 3.8.6 in the PATH
    * https://dlcdn.apache.org/maven/maven-3/3.8.6/binaries/apache-maven-3.8.6-bin.zip 
```powershell
quarkus create app org.acme:rest-kotlin-quickstart --extension='kotlin,resteasy-reactive-jackson'
```

![image](https://user-images.githubusercontent.com/119603054/206160164-dcdf8706-6632-464d-bc79-c2841a5b3e77.png)

### Output of `uname -a` or `ver`

Microsoft Windows [version 10.0.22000.1219]

### Output of `java -version`

java -version openjdk version "17" 2021-09-14 OpenJDK Runtime Environment (build 17+35-2724) OpenJDK 64-Bit Server VM (build 17+35-2724, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: C:\Users\OlivierBeltrando\bin\apache-maven-3.8.6-bin\apache-maven-3.8.6 Java version: 17, vendor: Oracle Corporation, runtime: C:\Users\OlivierBeltrando\bin\openjdk-17+35_windows-x64_bin\jdk-17 Default locale: fr_FR, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by geoand** [comment] 2022-12-07 11:54
@gnodet @stalep  any idea what might be going on here?

**Comment by gsmet** [comment] 2022-12-07 12:26
My wild guess would be that the Aesh version we are using is not compatible with the JAnsi version we are using.

**Comment by gnodet** [comment] 2022-12-08 13:36
Fwiw `MOUSE_EVENT_RECORD.init()` is a native function, so I suspect more a native library problem than a mismatch.

**Comment by alexkolson** [comment] 2022-12-27 10:33
Also seeing this issue but on Windows 10.

**Comment by stalep** [comment] 2023-01-02 12:19
@geoand I've missed this notification. I need to have a look at which version Quarkus uses, I released a new version not that long ago that uses a newer version of Jansi that works with native binaries.

**Comment by geoand** [comment] 2023-01-02 12:59
I agree that upgrading makes sense

**Comment by olivierbeltrandocintoo** [comment] 2023-01-05 10:39
Hello @stalep,
So without changing anything with `mvn dependency:resolve`
```powershell
mvn dependency:resolve | select-string "aesh|jansi"

[INFO]    org.fusesource.jansi:jansi:jar:1.18:test
[INFO]    org.aesh:readline:jar:2.2:test
[INFO]    org.aesh:aesh:jar:2.6:test
```

With updating the pom to use `aesh 2.6`
```xml
    <dependency>
      <groupId>org.aesh</groupId>
      <artifactId>aesh</artifactId>
      <version>2.6</version>
    </dependency>
```
the new dependencies resolved become
```powershell
mvn dependency:resolve | select-string "aesh|jansi"

[INFO]    org.fusesource.jansi:jansi:jar:1.18:compile
[INFO]    org.aesh:readline:jar:2.2:compile
[INFO]    org.aesh:aesh:jar:2.6:compile
```

**The issue disappears !!** 
It seems it is a good idea to change aesh being a `test` dependency to a `compile` dependency :)

**Comment by olivierbeltrandocintoo** [comment] 2023-01-05 12:08
So after playing around a bit more, it seems that just requiring `org.aesh:readline` **works**.

```xml
    <dependency>
      <groupId>org.aesh</groupId>
      <artifactId>readline</artifactId>
      <version>2.2</version>
    </dependency>
```

which makes the dependency move to compile for `jansi` and `readline` but not for `aesh` itself.
```powershell
PS C:\Users\OlivierBeltrando\dev\rest-poc> mvn dependency:resolve | select-string "aesh|jansi"

[INFO]    org.fusesource.jansi:jansi:jar:1.18:compile
[INFO]    org.aesh:readline:jar:2.2:compile
[INFO]    org.aesh:aesh:jar:2.6:test
```

I have checked and dependency wise this is the only change, that adding this dependency do (kdiff of the full output).

the readline dependency seems to already be on `compile` scope here: https://github.com/quarkusio/quarkus/blob/main/bom/application/pom.xml#L5898-L5902

I am not sure on what needs to be done on the quarkus/your side to make it work for everyone. Not sure I really understand how things are packaged/resolved between what is written in the bom/application/pom.xml and what is actually happening on the user/consumer side.

Again, many thanks for the help :)

**Comment by geoand** [comment] 2023-01-05 16:14
@rsvoboda any chance that you can test if https://github.com/quarkusio/quarkus/pull/30207 fixes the problem?

**Comment by olivierbeltrando** [comment] 2023-01-05 21:17
Hi @geoand, @gsmet  , sorry, I wrote a lot and did not make enough effort to highlight what solves the issue (in a hacky way).

**The workaround**
Add any of the deps `org.aesh:readline:jar:2.2` or `org.aesh:aesh:jar:2.6` to the **applicative pom.xml** (the one generated by the `quarkus create app org.acme:rest-kotlin-quickstart --extension='kotlin,resteasy-reactive-jackson'`).
What I noticed is that adding any of those to pom.xml of the app changes the dependency **scope** of `readline` and `jansi` from `test` to `compile`.
And that does the trick for my work laptop running on windows 11.

Those are **current** versions of the deps that are being bundled with latest quarkus (2.15.2.Final).
What fixes or breaks in my case are just the `scope` of those deps.

What would probably solve the whole thing would be to make sure that any of those are present in the `compile` scope whenever an application pom.xml declares a quarkus version (let's say 2.16.0.Final ;P)

**Comment by geoand** [comment] 2023-01-06 14:42
I have no idea honestly

**Comment by olivierbeltrandocintoo** [comment] 2023-01-06 14:52
Yes, this is what happens with vanilla windows terminal (ie. either powershell and cmd).
You should be able to reproduce with any windows I think seeing that 
1. the stacktrace is UnsatisfiedLinkError (ie, it is missing something)
2. adding the dependency in the applicative pom brings additional packages that seem to resolve the link.

I am betting that upgrading the dependency won't change the outcome (ie. issue persists). 
Please try making sure that `readline` is present for the `compile` scope :)

**Comment by rsvoboda** [comment] 2023-01-07 13:47
> I am betting that upgrading the dependency won't change the outcome (ie. issue persists).

Exactly, the issue is still present

I'm able to reproduce the issue using Quarkus 2.15.2.Final and Quarkus based on the linked PR with upgraded aesh. I'm using https://code.quarkus.io/?e=resteasy-reactive-jackson&e=kotlin based app.

I was able to get get rid of this issue 3 different ways:
 - Explicit aesh dependencies in `pom.xml`
 - Use of Maven 3.6.3 instead of mvnw 3.8.6
 - Drop the `quarkus-arc` dependency definition from `pom.xml` while using mvnw 3.8.6

The last one (`quarkus-arc` drop) is very interesting. It surprised me, have some ideas, but can't exactly explain why it helped.
@olivierbeltrando, would be good if the removal of `quarkus-arc` helps you too (without the need to define aesh dependencies).

**Comment by geoand** [comment] 2023-01-07 13:57
Very interesting info

**Comment by olivierbeltrandocintoo** [comment] 2023-01-07 14:21
Hi @rsvoboda , 

Very nice to hear you could reproduce on your side :)
(same person, but with the work computer (windows)).

I have tried dropping the `quarkus-arc` module, without success
```xml
<!--    <dependency>-->
<!--      <groupId>io.quarkus</groupId>-->
<!--      <artifactId>quarkus-arc</artifactId>-->
<!--    </dependency>-->
```

```powershell
...
[INFO] Changes detected - recompiling the module!
Listening for transport dt_socket at address: 5005
Exception in thread "WindowsStreamPump" java.lang.UnsatisfiedLinkError: 'void org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.init()'
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.init(Native Method)
        at org.fusesource.jansi.internal.Kernel32$MOUSE_EVENT_RECORD.<clinit>(Kernel32.java:583)
        at org.fusesource.jansi.internal.Kernel32$INPUT_RECORD.<init>(Kernel32.java:735)
        at org.fusesource.jansi.internal.Kernel32.readConsoleInputHelper(Kernel32.java:823)
        at org.fusesource.jansi.internal.WindowsSupport.readConsoleInput(WindowsSupport.java:106)
        at org.aesh.readline.terminal.impl.WinSysTerminal.readConsoleInput(WinSysTerminal.java:73)
        at org.aesh.readline.terminal.impl.AbstractWindowsTerminal.pump(AbstractWindowsTerminal.java:310)
        at java.base/java.lang.Thread.run(Thread.java:833)
__  ____  __  _____   ___  __ ____  ______
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/
2023-01-07 15:14:59,394 INFO  [io.quarkus] (Quarkus Main Thread) rest-poc 0.0.1-SNAPSHOT on JVM (powered by Quarkus 2.15.2.Final) started in 1.726s. Listening on: http://localhost:8080

2023-01-07 15:14:59,399 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2023-01-07 15:14:59,400 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, kotlin, reactive-routes, resteasy-reactive, resteasy-reactive-jackson, security, smallrye-context-propagation, smallrye-jwt, vertx]

--
Tests paused
Press [r] to resume testing, [o] Toggle test output, [:] for the terminal, [h] for more options>
...
```

I will also try the previous mvn versions :)

Many thanks for the help.

**Comment by olivierbeltrandocintoo** [comment] 2023-01-09 09:41
Hi @rsvoboda,

Tried also with mvn 3.6.3 and I confirm that it fixes the issue. Also dependency-wise, the same thing is resolved (ie. the `aesh:readline` is with a test scope): 
![image](https://user-images.githubusercontent.com/119603054/211269508-3827f461-d617-4450-a1af-2506668456e8.png)

Funny stuff.

I saved and diffed the output of both `mvn quarkus:dev` commands, and there is no notable difference: both use the same mvn plugins with the same versions. So it seems it comes move from mvn.

So I digged a bit, and **found** something that may be interesting :)


The structure of the jansi-native dir/folder is different (see the screenshot).
**mvn_3.6.3**
![Capture d'écran_20230109_103415](https://user-images.githubusercontent.com/119603054/211278397-1475fc19-dbae-4fec-bd78-364215a4aa2e.png)

**mvn_3.8.6**
![Capture d'écran_20230109_103437](https://user-images.githubusercontent.com/119603054/211278576-6055b07c-8f87-4e17-b33c-967799742c0e.png)

So I tried my luck and copied the mvn-3.6.3 `windows64` dir inside the `jansi`
![Capture d'écran_20230109_103545](https://user-images.githubusercontent.com/119603054/211278616-2ef11b75-985b-4b70-871e-c3c9d6abed14.png)

Guess what... It works... :D:D
So my blind guess, is that mvn (or a lib inside) still expect the dll to be where it used to be in the old structure (ie. `windows64` and not `Windows/x86_64).

Will try to open a bug to mvn with that information.

Thanks for the good lead @rsvoboda !

**Comment by geoand** [comment] 2023-01-09 09:43
This is great information, thanks a ton for investigating folks!

In light of what you have found, I'll close this issue, as it does not seem to be caused by Quarkus.

**Closed by geoand** 2023-01-09 09:43 UTC
Labels: kind/bug, area/kotlin, env/windows

**Comment by gsmet** [comment] 2023-01-10 08:32
I think the problem is an incompatibility between the jansi version shipped with Maven and the one we are using in Quarkus and the problem only shows up on Windows so it's somehow related to what we are doing.

Now as to how to fix it... Apart from aligning our jansi version with Maven's, I don't see many options.

**Comment by geoand** [comment] 2023-01-10 08:33
> Now as to how to fix it... Apart from aligning our jansi version with Maven's, I don't see many options.

I agree

**Comment by olivierbeltrandocintoo** [comment] 2023-01-10 09:39
not 100% sure I understand the implications :D
but changing its scope would make it independent from the mvn version.
Also all `aesh` libs (including readline which is the only one needed apparently) + `jansi` **is less than 2 MB**, and from my understanding it won't be shipped in the generated app code so, I would not mind having those deps managed by the quarkus fwk :)

![Capture d'écran_20230110_101727](https://user-images.githubusercontent.com/119603054/211511215-3050f7ea-3be4-4831-bea9-cd4f369dfcba.png)
![Capture d'écran_20230110_101623](https://user-images.githubusercontent.com/119603054/211511217-190c7351-4257-498f-b27a-2dc276748a72.png)

and even if would be, it is 2MB, compared to the native app top of the `registry.access.redhat.com/ubi8/ubi-minimal:8.7` which amounts in total to about 150MB. So it looks negligible (at least for me) :)

On a side note, I am still waiting for the apache maven team to give me a Jira account so that I can log the ticket (which may be invalid, but maybe not, I am interested into what they would think :))
So far I haven't

**Comment by olivierbeltrandocintoo** [comment] 2023-05-11 06:49
Now with Quarkus 3.0.3 and maven 3.9.X, I don't have that bug anymore :) 
I can remove the readline dependency in my pom.xml.
Thanks !!
