### ISSUE TITLE
QuarkusTest hang in IntelliJ IDEA for master and quarkus 1.3+ but not 1.2

### ISSUE THREAD

**Issue by ge0ffrey** [quarkusio/quarkus#7311] opened 2020-02-20 13:41 UTC
To reproduce:
- On `quarkus-quickstarts`, on branch `development`, run `LegumeResourceTest` in IntelliJ
- Notice that it runs forever consistently, but that's only on my machine for one checkout of the project.

This reproduces with the IntelliJ Ultimate, both in the latest 2019.3.3 and an earlier version 2019.2.2. **This prevents normal debugging of tests in IntelliJ.** Everything works fine in maven (CI's won't detect this problem). This reproduces after system reboot and IntelliJ reboot.

During there run, an `InvocationTargetException` occurs (see debug screenshot below, but when that exception is being written to `System.err`, it deadlocks on `PrintStream`, causing nothing to show up and the test to run to hang.

![Selection_269](https://user-images.githubusercontent.com/176880/75141259-e0178900-56f0-11ea-81f7-1eb3f73f44ea.png)

**Suspected cause**

On 21-Januari this changes happened in the quarkus bom,
from

       <junit.jupiter.version>5.5.2</junit.jupiter.version>

to

        <junit.jupiter.version>5.6.0</junit.jupiter.version>

**Comment by geoand** [comment] 2020-02-20 13:52
I was unable to reproduce this

**Comment by ge0ffrey** [comment] 2020-02-20 13:58
Georgios tried on development branch. I tried on master and switched hibernate-orm-quickstart to use H2 in memory.

**Comment by geoand** [comment] 2020-02-21 07:47
@ge0ffrey were you able to find any more information?

**Comment by ge0ffrey** [comment] 2020-02-21 10:30
I am reproducing it on the `development` branch too, with hibernate-orm-quickstart. **FruitsEndpointTest hangs.**

I did do something extra on the reproduces list (to avoid having to do docker daemon installation):

- Adjust these 4 lines in application.properties:
```
quarkus.datasource.url=jdbc:h2:mem:quarkus_test
quarkus.datasource.driver=org.h2.Driver
quarkus.datasource.username=
quarkus.datasource.password=
```
- Change the postgresql dependency to h2:
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-h2</artifactId>
        </dependency>
```

**Comment by geoand** [comment] 2020-02-21 10:58
How is h2 being started?

**Comment by ge0ffrey** [comment] 2020-02-21 11:34
In the JDBC driver, with "jdbc:h2:mem:quarkus_test". No need to start any DB server.

**Comment by gastaldi** [comment] 2020-02-21 12:12
I can't reproduce that error either. I followed the steps in https://github.com/quarkusio/quarkus/issues/7311#issuecomment-589595484 but no luck :(

**Comment by ge0ffrey** [comment] 2020-02-21 16:17
@gastaldi (no reproduction) and me (reproduction) seem to use the exact same IntelliJ Ultimate version (193.6494.35) now.

**Comment by geoand** [comment] 2020-02-21 16:19
And my IntelliJ version (just for the record, I can't reproduce either):

```
IntelliJ IDEA 2019.3.3 (Ultimate Edition)
Build #IU-193.6494.35, built on February 11, 2020
```

@ge0ffrey do you perhaps have any Quarkus IntelliJ plugins?

**Comment by ge0ffrey** [comment] 2020-02-21 16:32
Nope, only 2 non-bundled IntelliJ plugins (asciidoc and CSV plugin)

**Comment by ge0ffrey** [comment] 2020-02-21 16:35
I can reproduce it on every quickstart, including the rest-json-quickstart `LegumeResourceTest` - so which no special H2 changes etc.

**Comment by gastaldi** [comment] 2020-02-21 16:36
What's shown when you execute `jstack <pid>` with the hanging process?

**Comment by ge0ffrey** [comment] 2020-02-21 16:39
Same as in IntelliJ thread dump that is in the zulip chat.

And it is somehow forever-locked on trying to system.out the InvocationTargetException that occurs (which I discovered by debugging during this stacktrace).
```

"main" #1 prio=5 os_prio=0 tid=0x00007fc3a0054800 nid=0x2d20 runnable [0x00007fc3a90a5000]
   java.lang.Thread.State: RUNNABLE
        at java.io.FileOutputStream.writeBytes(Native Method)
        at java.io.FileOutputStream.write(FileOutputStream.java:326)
        at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
        - locked <0x00000005ce3ebdf8> (a java.io.BufferedOutputStream)
        at java.io.PrintStream.write(PrintStream.java:480)
        - locked <0x00000005ce3ebdd8> (a java.io.PrintStream)
        at sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:221)
        at sun.nio.cs.StreamEncoder.implWrite(StreamEncoder.java:282)
        at sun.nio.cs.StreamEncoder.write(StreamEncoder.java:125)
        - locked <0x00000005ce3ebf18> (a java.io.OutputStreamWriter)
        at java.io.OutputStreamWriter.write(OutputStreamWriter.java:207)
        at java.io.BufferedWriter.flushBuffer(BufferedWriter.java:129)
        - locked <0x00000005ce3ebf18> (a java.io.OutputStreamWriter)
        at java.io.BufferedWriter.write(BufferedWriter.java:230)
        - locked <0x00000005ce3ebf18> (a java.io.OutputStreamWriter)
        at java.io.Writer.write(Writer.java:157)
        at java.io.PrintStream.write(PrintStream.java:525)
        - locked <0x00000005ce3ebdd8> (a java.io.PrintStream)
        at java.io.PrintStream.print(PrintStream.java:669)
        at java.io.PrintStream.println(PrintStream.java:806)
        - locked <0x00000005ce3ebdd8> (a java.io.PrintStream)
        at com.intellij.junit5.JUnit5TestExecutionListener.testFailure(JUnit5TestExecutionListener.java:298)
        at com.intellij.junit5.JUnit5TestExecutionListener.testFailure(JUnit5TestExecutionListener.java:246)
        at com.intellij.junit5.JUnit5TestExecutionListener.executionFinished(JUnit5TestExecutionListener.java:184)
        at com.intellij.junit5.JUnit5TestExecutionListener.executionFinished(JUnit5TestExecutionListener.java:172)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.lambda$executionFinished$10(TestExecutionListenerRegistry.java:109)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener$$Lambda$368/1573751930.accept(Unknown Source)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.lambda$notifyEach$1(TestExecutionListenerRegistry.java:67)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$$Lambda$142/731260860.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.notifyEach(TestExecutionListenerRegistry.java:65)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry.access$200(TestExecutionListenerRegistry.java:32)
        at org.junit.platform.launcher.core.TestExecutionListenerRegistry$CompositeTestExecutionListener.executionFinished(TestExecutionListenerRegistry.java:108)
        at org.junit.platform.launcher.core.ExecutionListenerAdapter.executionFinished(ExecutionListenerAdapter.java:56)
        at org.junit.platform.launcher.core.DelegatingEngineExecutionListener.executionFinished(DelegatingEngineExecutionListener.java:46)
        at org.junit.platform.launcher.core.OutcomeDelayingEngineExecutionListener.executionFinished(OutcomeDelayingEngineExecutionListener.java:63)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.reportCompletion(NodeTestTask.java:179)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:85)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$183/699780352.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$179/601008104.execute(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$178/1752203484.invoke(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$177/1489069835.execute(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService$$Lambda$183/699780352.accept(Unknown Source)
        at java.util.ArrayList.forEach(ArrayList.java:1257)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$179/601008104.execute(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$178/1752203484.invoke(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask$$Lambda$177/1489069835.execute(Unknown Source)
        at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
        at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
        at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
        at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:248)
        at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$5(DefaultLauncher.java:211)
        at org.junit.platform.launcher.core.DefaultLauncher$$Lambda$137/553871028.accept(Unknown Source)
        at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:226)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:199)
        at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:132)
        at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
        at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
        at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
        at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

```

**Comment by ge0ffrey** [comment] 2020-02-21 16:43
This is the exception it's trying to log:

![image](https://user-images.githubusercontent.com/176880/75053440-96048c80-54d1-11ea-82c6-299bbfd8f5ff.png)

That 2th stacktrace points to this code:

```
public static String getUri(RunningQuarkusApplication application) {
        return application.getConfigValue("test.url", String.class).get();
    }
```

which calls

```
return (Optional<T>) getConfig.getReturnType().getMethod("getOptionalValue", String.class, Class.class)
                    .invoke(config, key, type);
```

**Comment by ge0ffrey** [comment] 2020-02-21 17:40
My team member Musa just tried to reproduce without success. It's really just my machine apparently. Restarting IntelliJ didn't work, let me restart my entire machine.

**Comment by geoand** [comment] 2020-02-21 17:44
Thanks for being so thorough about this!

**Comment by ge0ffrey** [comment] 2020-02-21 17:51
My team member Musa just tried to reproduce without success. It's really just my machine apparently. Restarting IntelliJ didn't work. Restarting my entire machine didn't work either.

**Comment by MusaTalluzi** [comment] 2020-02-22 05:21
I can't reproduce it either, here's my IntelliJ version:
```
IntelliJ IDEA 2019.2.2 (Ultimate Edition)
Build #IU-192.6603.28, built on September 6, 2019
```
And the output of running `FruitsEndpointTest` following the instructions:
```
Feb 21, 2020 12:08:00 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.1.Final
Feb 21, 2020 12:08:01 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version 5.4.12.Final
Feb 21, 2020 12:08:01 PM org.hibernate.jpa.internal.util.LogHelper logPersistenceUnitInformation
INFO: HHH000204: Processing PersistenceUnitInfo [name: default]
Feb 21, 2020 12:08:01 PM org.hibernate.Version logVersion
INFO: HHH000412: Hibernate ORM core version 5.4.12.Final
Feb 21, 2020 12:08:01 PM org.hibernate.annotations.common.reflection.java.JavaReflectionManager <clinit>
INFO: HCANN000001: Hibernate Commons Annotations {5.1.0.Final}
Feb 21, 2020 12:08:01 PM org.hibernate.dialect.Dialect <init>
INFO: HHH000400: Using dialect: io.quarkus.hibernate.orm.runtime.dialect.QuarkusH2Dialect
Feb 21, 2020 12:08:02 PM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.1.Final
Feb 21, 2020 12:08:02 PM org.hibernate.resource.beans.spi.ManagedBeanRegistryInitiator resolveBeanContainer
INFO: HHH10005002: No explicit CDI BeanManager reference was passed to Hibernate, but CDI is available on the Hibernate ClassLoader.
Feb 21, 2020 12:08:03 PM io.quarkus.agroal.runtime.AgroalEventLoggingListener onInfo
INFO: Datasource '<default>': Initial size smaller than min. Connections will be created when necessary
Hibernate: 
    
    drop table known_fruits if exists
Hibernate: 
    
    drop sequence if exists known_fruits_id_seq
Hibernate: create sequence known_fruits_id_seq start with 10 increment by 1
Hibernate: 
    
    create table known_fruits (
       id integer not null,
        name varchar(40),
        primary key (id)
    )
Hibernate: 
    
    alter table known_fruits 
       add constraint UK_57g3m8wr3qxoj706a6hsqg6ye unique (name)
Feb 21, 2020 12:08:03 PM org.hibernate.tool.schema.internal.exec.AbstractScriptSourceInput prepare
INFO: HHH000476: Executing import script 'file:/home/internx1/projects/kiegroup/quarkus-quickstarts/hibernate-orm-quickstart/target/classes/import.sql'
Hibernate: 
    INSERT INTO known_fruits(id, name) VALUES (1, 'Cherry')
Hibernate: 
    INSERT INTO known_fruits(id, name) VALUES (2, 'Apple')
Hibernate: 
    INSERT INTO known_fruits(id, name) VALUES (3, 'Banana')
Feb 21, 2020 12:08:03 PM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 999-SNAPSHOT started in 3.578s. Listening on: http://0.0.0.0:8081
Feb 21, 2020 12:08:03 PM io.quarkus.runtime.Timing printStartupTime
INFO: Profile test activated. 
Feb 21, 2020 12:08:03 PM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [agroal, cdi, hibernate-orm, jdbc-h2, narayana-jta, resteasy, resteasy-jsonb]

Hibernate: 
    select
        fruit0_.id as id1_0_,
        fruit0_.name as name2_0_ 
    from
        known_fruits fruit0_ 
    order by
        fruit0_.name
Hibernate: 
    select
        fruit0_.id as id1_0_0_,
        fruit0_.name as name2_0_0_ 
    from
        known_fruits fruit0_ 
    where
        fruit0_.id=?
Hibernate: 
    delete 
    from
        known_fruits 
    where
        id=?
Hibernate: 
    select
        fruit0_.id as id1_0_,
        fruit0_.name as name2_0_ 
    from
        known_fruits fruit0_ 
    order by
        fruit0_.name
Hibernate: 
    call next value for known_fruits_id_seq
Hibernate: 
    insert 
    into
        known_fruits
        (name, id) 
    values
        (?, ?)
Hibernate: 
    select
        fruit0_.id as id1_0_,
        fruit0_.name as name2_0_ 
    from
        known_fruits fruit0_ 
    order by
        fruit0_.name

Feb 21, 2020 12:08:05 PM io.quarkus.runtime.Timing printStopTime
INFO: Quarkus stopped in 0.032s

Process finished with exit code 0

```

**Comment by jaikiran** [comment] 2020-02-23 04:05
Hello @ge0ffrey, which OS are you on and what Java vendor and version does this JVM correspond to:
```
Full thread dump OpenJDK 64-Bit Server VM (25.191-b12 mixed mode)
```

**Comment by jaikiran** [comment] 2020-02-23 04:46
@ge0ffrey - would you be able to pass (via IntelliJ test launch configs) the system property `junit.platform.discovery.listener.default` with its value set to `logging` and see if it makes a difference?

**Comment by ge0ffrey** [comment] 2020-02-24 08:21
I checked out quarkus-quickstarts again (I call my 2nd checkout old-quarkus-quickstarts). There it does NOT reproduce. The IntelliJ run configuration is exactly the same. Rebooting my computer didn't help: the original checkout still reproduces every time.

**Comment by geoand** [comment] 2020-02-24 08:24
@ge0ffrey can you perphaps do a diff of the command command that IntelliJ runs in both cases and see if there is any difference worth noting?

**Comment by ge0ffrey** [comment] 2020-02-24 12:01
Zipping my local checkout and mailing that to Georgios (= same .idea folder etc) did *not* reproduce it there.

**Comment by stuartwdouglas** [comment] 2020-07-08 03:47
It am going to close this, given that it could only be reproduced on one machine with a specific checkout I don't think we will get to the bottom of it unless it pops up again.

**Closed by stuartwdouglas** 2020-07-08 03:47 UTC
Labels: kind/bug

**Comment by ge0ffrey** [comment] 2020-07-08 10:43
I've not seen this issue since, I forget if we found the cause or not, but it doesn't reproduce any more. Thanks for closing it.
