### ISSUE TITLE
ClassCastException on injected class due to a changed hierarchy

### ISSUE THREAD

**Issue by tassadar81** [quarkusio/quarkus#17105] opened 2021-05-10 09:28 UTC
From quarkus 1.13 (i tried 1.13.3) the classloading has changed someway and:

(ParameterizedType) getClass().getGenericSuperclass() executed in a class

MyClass extends AbstractMyClass<MyBean, MyAnother>

blows with a class cast exception.

This doesn't happens with quarkus 12.2

My project is running on:
openjdk version "11.0.1" and  Apache Maven 3.6.3

**Comment by geoand** [comment] 2021-05-10 10:51
Can you please attach a sample project that exhibits the behavior you describe?

**Comment by tassadar81** [comment] 2021-05-10 13:23
@geoand here it is, from getting-started project. Just run as is it'll lead to the error, then change quarkus version to 12.2 and it'll works like a charm
[issueclasshierarchy.zip](https://github.com/quarkusio/quarkus/files/6452319/issueclasshierarchy.zip)

**Comment by geoand** [comment] 2021-05-10 14:50
I tried your attached project and it worked for me

**Comment by tassadar81** [comment] 2021-05-10 14:58
@geoand don't know, just tried again invoking:

http://localhost:8080/hello/greeting/roberto

and it leads to a:

2021-05-10 16:56:42,924 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /hello/greeting/roberto failed, error id: 3faac6ff-84ee-4ed6-b774-042e357b3327-1: org.jboss.resteasy.spi.UnhandledException: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
        at org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:106)
        at org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:372)
        at org.jboss.resteasy.core.SynchronousDispatcher.writeException(SynchronousDispatcher.java:218)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:519)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$invoke$4(SynchronousDispatcher.java:261)
        at org.jboss.resteasy.core.SynchronousDispatcher.lambda$preprocess$0(SynchronousDispatcher.java:161)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.SynchronousDispatcher.preprocess(SynchronousDispatcher.java:164)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:247)
        at io.quarkus.resteasy.runtime.standalone.RequestDispatcher.service(RequestDispatcher.java:73)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.dispatch(VertxRequestHandler.java:138)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler.access$000(VertxRequestHandler.java:41)
        at io.quarkus.resteasy.runtime.standalone.VertxRequestHandler$1.run(VertxRequestHandler.java:93)
        at io.quarkus.runtime.CleanableExecutor$CleaningRunnable.run(CleanableExecutor.java:231)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2415)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1452)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.ClassCastException: class java.lang.Class cannot be cast to class java.lang.reflect.ParameterizedType (java.lang.Class and java.lang.reflect.ParameterizedType are in module java.base of loader 'bootstrap')
        at org.acme.getting.started.AbstractGreetingService.mapEToB(AbstractGreetingService.java:11)
        at org.acme.getting.started.GreetingService_Subclass.mapEToB$$superaccessor1(GreetingService_Subclass.zig:226)
        at org.acme.getting.started.GreetingService_Subclass$$function$$1.apply(GreetingService_Subclass$$function$$1.zig:32)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.getting.started.GreetingService_Subclass.mapEToB(GreetingService_Subclass.zig:184)
        at org.acme.getting.started.GreetingService.greeting(GreetingService.java:9)
        at org.acme.getting.started.GreetingService_Subclass.greeting$$superaccessor2(GreetingService_Subclass.zig:339)
        at org.acme.getting.started.GreetingService_Subclass$$function$$2.apply(GreetingService_Subclass$$function$$2.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.getting.started.GreetingService_Subclass.greeting(GreetingService_Subclass.zig:296)
        at org.acme.getting.started.GreetingService_ClientProxy.greeting(GreetingService_ClientProxy.zig:128)
        at org.acme.getting.started.GreetingResource.greeting(GreetingResource.java:21)
        at org.acme.getting.started.GreetingResource_Subclass.greeting$$superaccessor1(GreetingResource_Subclass.zig:223)
        at org.acme.getting.started.GreetingResource_Subclass$$function$$1.apply(GreetingResource_Subclass$$function$$1.zig:33)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:54)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.proceed(InvocationInterceptor.java:63)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor.monitor(InvocationInterceptor.java:49)
        at io.quarkus.arc.runtime.devconsole.InvocationInterceptor_Bean.intercept(InvocationInterceptor_Bean.zig:521)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:41)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:41)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:32)
        at org.acme.getting.started.GreetingResource_Subclass.greeting(GreetingResource_Subclass.zig:180)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:170)
        at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:130)
        at org.jboss.resteasy.core.ResourceMethodInvoker.internalInvokeOnTarget(ResourceMethodInvoker.java:643)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTargetAfterFilter(ResourceMethodInvoker.java:507)
        at org.jboss.resteasy.core.ResourceMethodInvoker.lambda$invokeOnTarget$2(ResourceMethodInvoker.java:457)
        at org.jboss.resteasy.core.interception.jaxrs.PreMatchContainerRequestContext.filter(PreMatchContainerRequestContext.java:364)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:459)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:419)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:393)
        at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:68)
        at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:492)
        ... 18 more

**Comment by geoand** [comment] 2021-05-10 15:01
Okay, I was able to reproduce this in dev-mode only

**Comment by geoand** [comment] 2021-05-10 15:02
@mkouba want to take a look?

**Comment by geoand** [comment] 2021-05-10 15:19
@mkouba it seems that the problems stems from the fact that in `1.13.x` `this.getClass()` returns `org.acme.getting.started.GreetingService_Subclass` while in `1.12` it returns `org.acme.getting.started.GreetingService`

**Comment by mkouba** [comment] 2021-05-13 16:04
> @mkouba it seems that the problems stems from the fact that in `1.13.x` `this.getClass()` returns `org.acme.getting.started.GreetingService_Subclass` while in `1.12` it returns `org.acme.getting.started.GreetingService`

That's because in 1.13+ the container monitors business method invocations in the development mode by default and thus the bean instance of `GreetingService` is an intercepted subclass. 

@tassadar81 You can disable the monitoring via [`quarkus.arc.dev-mode.monitoring-enabled=false`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.dev-mode.monitoring-enabled) but keep in mind that your code is not entirely valid from the CDI spec POV because "a contextual instance is considered an internal container construct". 

Note that in Quarkus all intercepted subclasses do implement the `io.quarkus.arc.Subclass` marker interface and so your code can test the presence of this interface and obtain the superclass that would correspond to the bean implementation class (`GreetingService` in your example).

**Comment by geoand** [comment] 2021-05-13 16:21
Thanks for the excellent information @mkouba .

So I assume we close this issue?

**Comment by mkouba** [comment] 2021-05-13 16:26
> So I assume we close this issue?

Done ;-).

**Closed by mkouba** 2021-05-13 16:26 UTC
Labels: area/core, kind/bug

**Comment by tassadar81** [comment] 2021-05-14 11:08
thanks @mkouba!

**Comment by mkouba** [comment] 2021-05-14 11:22
yw! :-)
