### ISSUE TITLE
Warning about reflective access of Yasson

### ISSUE THREAD

**Issue by pilhuhn** [quarkusio/quarkus#10803] opened 2020-07-17 09:24 UTC
I get the following warning 

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.eclipse.yasson.internal.ReflectionUtils (jar:file:/Users/hrupp/.m2/repository/org/eclipse/yasson/1.0.7/yasson-1.0.7.jar!/) to constructor java.util.AbstractMap()
WARNING: Please consider reporting this to the maintainers of org.eclipse.yasson.internal.ReflectionUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

```

Yasson is pulled in by quarkus-resteasy-jsonb , so I would expect that this is properly registered inside Quarkus (-resteasy-jsonb) and would not emit the warning

* io.quarkus:quarkus-resteasy-jsonb:1.6.0.Final
** org.jboss.resteasy:resteasy-json-binding-provider:4.5.5.Final
*** org.eclipse:yasson:1.0.7

**Comment by machi1990** [comment] 2020-07-17 09:28
This seems like a duplicate of https://github.com/quarkusio/quarkus/issues/10273

/cc @emmanuelbernard @gsmet

**Comment by geoand** [comment] 2020-07-17 10:26
Yeah, it's a duplicate. Let's keep the other issue open.

**Closed by geoand** 2020-07-17 10:26 UTC
Labels: kind/bug

**Comment by gsmet** [comment] 2020-07-17 10:33
Hint: please add the label when closing :).

**Comment by geoand** [comment] 2020-07-17 10:35
:+1:
