### ISSUE TITLE
WebAuthN `quarkus.webauthn.user-verification `default value is not working as expected

### ISSUE THREAD

**Issue by StephenOTT** [quarkusio/quarkus#38402] opened 2024-01-25 17:43 UTC
### Describe the bug

The web auth n config value: `quarkus.webauthn.user-verification` has a default of `required`

https://quarkus.io/guides/security-webauthn#quarkus-security-webauthn_quarkus.webauthn.user-verification

https://github.com/quarkusio/quarkus/blob/main/extensions/security-webauthn/runtime/src/main/java/io/quarkus/security/webauthn/WebAuthnRunTimeConfig.java#L107

But when you DO NOT set the value / leave it as the default, the login process is returning: `"userVerification": "discouraged",`

If you manually set the property in application.properties: `quarkus.webauthn.user-verification=required` then the userVerification property is properly set to `required`. 

### Expected behavior

Default value is properly set

### Actual behavior

Default value does not get set and value falls back to `discouraged`

**Comment by sberyozkin** [comment] 2024-01-25 18:06
@StephenOTT Is it a duplicate of #38348 ?

**Comment by StephenOTT** [comment] 2024-01-25 18:21
@sberyozkin i don't think so.  `user-verification` is related to the requirements on the authenticator: such as forcing the user to input their PIN.  

<img width="1060" alt="image" src="https://github.com/quarkusio/quarkus/assets/1994838/98309f4b-0a89-4021-b25c-27b36d72eb50">

**Comment by FroMage** [comment] 2024-01-26 14:01
Ah, either a code bug, or a doc bug.

**Comment by FroMage** [comment] 2024-01-26 15:49
Indeed, the default is really `DISCOURAGED` in the code, I'll adjust the docs.

**Closed** 2024-03-26 13:32 UTC
Labels: kind/bug, area/webauthn
