### ISSUE TITLE
jandex index is not generated for multi module project

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#18674] opened 2021-07-14 06:47 UTC
### Describe the bug

Right now we add an META-INF/beans.xml file to each module of quarkus projects. This works and the cdi beans in the modules are detected. The disadvantage is, that we have to remember to add these files.
I therefore wanted to simplifiy this by introducing the jandex-maven-plugin into our company wide quarkus parent.

The documentation says to simply add the jandex-maven-plugin to generate a jandex index. 
https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

The plugin is however not run for multi module projects using "mvn quarkus:dev", only when executing "mvn jandex:jandex quarkus:dev". This is even more trouble for us than adding META-INF/beans.xml files.

### Expected behavior

Quarkus should run the jandex:jandex goal on quarkus:dev, like it does for the maven-compiler-plugin.

### Actual behavior

Beans are not found for "mvn quarkus:dev", the jandex plugin is not executed.
```
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] multi-module-jandex                                                [pom]
[INFO] service                                                            [jar]
[INFO] web                                                                [jar]
[INFO]
[INFO] --------------------< org.acme:multi-module-jandex >--------------------
[INFO] Building multi-module-jandex 1.0.0-SNAPSHOT                        [1/3]
[INFO] --------------------------------[ pom ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ multi-module-jandex ---
[INFO]
[INFO] --- quarkus-maven-plugin:2.0.2.Final:dev (default-cli) @ multi-module-jandex ---
[WARNING] The quarkus-maven-plugin build goal was not configured for this project, skipping quarkus:dev as this is assumed to be a support library. If you want to run quarkus dev on this project make sure the quarkus-maven-plugin is configured with a build goal.
[INFO]
[INFO] --------------------------< org.acme:service >--------------------------
[INFO] Building service 1.0.0-SNAPSHOT                                    [2/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ service ---
[INFO] Deleting C:\workspaces\aviator\multi-module-jandex\service\target
[INFO]
[INFO] --- quarkus-maven-plugin:2.0.2.Final:dev (default-cli) @ service ---
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ service
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ service
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\workspaces\aviator\multi-module-jandex\service\target\classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ service
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\workspaces\aviator\multi-module-jandex\service\src\test\resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ service
[INFO] Changes detected - recompiling the module!
[WARNING] The quarkus-maven-plugin build goal was not configured for this project, skipping quarkus:dev as this is assumed to be a support library. If you want to run quarkus dev on this project make sure the quarkus-maven-plugin is configured with a build goal.
[INFO]
[INFO] ----------------------------< org.acme:web >----------------------------
[INFO] Building web 1.0.0-SNAPSHOT                                        [3/3]
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ web ---
[INFO] Deleting C:\workspaces\aviator\multi-module-jandex\web\target
[INFO]
[INFO] --- quarkus-maven-plugin:2.0.2.Final:dev (default-cli) @ web ---
[INFO] Invoking io.quarkus:quarkus-maven-plugin:2.0.2.Final:generate-code @ web
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:resources @ web
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 0 resource
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile @ web
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\workspaces\aviator\multi-module-jandex\web\target\classes
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ web
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory C:\workspaces\aviator\multi-module-jandex\web\src\test\resources
[INFO] Invoking org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile @ web
[INFO] Changes detected - recompiling the module!
Listening for transport dt_socket at address: 5005
2021-07-14 08:44:26,436 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default
]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1099)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:264)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:492)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:463)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:252)
        ... 13 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:413)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:275)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:66)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:87)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:448)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:61)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:132)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:89)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:145)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:63)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default
]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1099)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:264)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:492)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:463)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:252)
        ... 13 more

        at io.quarkus.builder.Execution.run(Execution.java:116)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:149)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:411)
        ... 9 more
Caused by: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1099)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:264)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:129)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:418)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:820)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2442)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1476)
        at java.base/java.lang.Thread.run(Thread.java:834)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.SomeService and qualifiers [@Default]
        - java member: org.acme.SomeResource#service
        - declared on CLASS bean [types=[org.acme.SomeResource, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.SomeResource]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:492)
        at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:463)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:252)
        ... 13 more
```

### How to Reproduce?

Reproducer; 
[multi-module-jandex.zip](https://github.com/quarkusio/quarkus/files/6814091/multi-module-jandex.zip)

1. mvn quarkus:dev -> app fails with exception from above, the "SomeService" cdi bean could not be found.
2. mvn jandex:jandex quarkus:dev -> app starts

### Output of `uname -a` or `ver`

MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys

### Output of `java -version`

openjdk version "11.0.7" 2020-04-14 LTS OpenJDK Runtime Environment Zulu11.39+15-CA (build 11.0.7+10-LTS) OpenJDK 64-Bit Server VM Zulu11.39+15-CA (build 11.0.7+10-LTS, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: C:\eclipse\tools\apache-maven\bin\.. Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\java\11 Default locale: de_DE, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by famod** [comment] 2021-07-14 09:28
@aloubyansky Maybe it's time to finally implement what I was thinking about not so long ago: execute all plugin goals taht are bound to phase x and before (possibly including a blacklist to avoid enforcer etc.).

**Comment by famod** [comment] 2021-07-14 09:30
@Postremus Just an idea for a workaround: Create a `qdev` (or whatever) Maven profile and set `<defaultGoal>clean jandex:jandex quarkus:dev</deaulfGoal>` so you can simply call `mvn -Pqdev`.

**Comment by aloubyansky** [comment] 2021-07-14 09:33
We are actually not executing any goals on other modules than the main app. However, if the index is present in the other modules, it should be ignored and re-calculated in dev mode.

**Comment by famod** [comment] 2021-07-14 09:39
> We are actually not executing any goals on other modules than the main app.

Ah, yes - I missed that. I think the main problem here is that `clean` is used and (as you said, on purpose) dev is not doing anything in modules that are not building the actual app.

**Comment by aloubyansky** [comment] 2021-07-14 09:41
Right. The project should be built first. @Postremus if you add `<phase>compile</phase>` to the jandex plugin config then `mvn clean compile quarkus:dev` executed from the root will work.

**Comment by aloubyansky** [comment] 2021-07-14 09:45
I am going to close this issue for now. It's not a bug. We are not applying any plugins automatically as part of `quarkus:dev` to the dependencies. It could potentially become a feature request though.

**Closed by aloubyansky** 2021-07-14 09:45 UTC
Labels: area/devmode, area/maven, env/windows, kind/bug

**Comment by Postremus** [comment] 2021-07-15 07:04
@aloubyansky 
> We are not applying any plugins automatically as part of `quarkus:dev` to the dependencies.

The maven compiler plugin is invoked for the service module as part of `quarkus:dev`.
[INFO] Invoking org.apache.maven.plugins:maven-resources-plugin:2.6:testResources @ service

The plugin first compiles, and then checks if it is configured for this module.
https://github.com/quarkusio/quarkus/blob/f6fb0506aca024ead6e40f7dbb402149047a35ef/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L340-L351

I have the quarkus-maven-plugin as part of my parent. This allows me to execute `mvn quarkus:dev` on the root of the project.
This also executes quarkus:dev on the service module.

For now I applied your suggestion of adding the compile phase to the jandex plugin, which works. Thank you!
