### ISSUE TITLE
quarkus-extensions should include its jandex index

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#5871] opened 2019-11-29 12:11 UTC
**Describe the bug**
I start a quarkus-app with quarkus-extensions. It compiles and works, but I get this warning message:
```

[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] 
Unable to properly register the hierarchy of the following classes 
for reflection as they are not in the Jandex index:
	- com.github.benmanes.caffeine.cache.Cache
	- com.github.benmanes.caffeine.cache.Policy$Eviction
	- io.reactivex.Scheduler
	- io.reactivex.functions.Predicate
	- io.reactivex.internal.fuseable.SimplePlainQueue
	- javax.crypto.Cipher
	- javax.crypto.KeyAgreement
	- javax.crypto.SecretKey
	- javax.enterprise.context.spi.Contextual
	- javax.enterprise.context.spi.CreationalContext
	- javax.enterprise.event.Event
	- javax.management.MBeanAttributeInfo
	- javax.management.MBeanInfo
	- javax.management.MBeanOperationInfo
	- javax.management.MBeanServer
	- javax.management.ObjectName
	- javax.naming.directory.DirContext
	- javax.net.ssl.SSLContext
	- javax.net.ssl.SSLServerSocket
	- javax.persistence.EntityManager
	- javax.security.auth.Subject
	- javax.security.auth.callback.CallbackHandler
	- javax.security.sasl.SaslClient
	- javax.security.sasl.SaslClientFactory
	- javax.security.sasl.SaslServer
	- javax.security.sasl.SaslServerFactory
	- javax.sql.DataSource
	- javax.swing.JButton
	- javax.swing.JFrame
	- javax.swing.JLabel
	- javax.swing.JPanel
	- javax.swing.JTabbedPane
	- javax.swing.JTable
	- javax.swing.JTextArea
	- javax.swing.JTextField
	- javax.swing.table.AbstractTableModel
	- javax.transaction.RollbackException
	- javax.transaction.Synchronization
	- javax.transaction.Transaction
	- javax.transaction.TransactionManager
	- javax.transaction.TransactionSynchronizationRegistry
	- javax.transaction.UserTransaction
	- javax.transaction.xa.XAResource
	- javax.transaction.xa.Xid
	- javax.ws.rs.client.Client
	- javax.xml.namespace.QName
	- org.apache.logging.log4j.Logger
	- org.eclipse.microprofile.metrics.ConcurrentGauge
	- org.eclipse.microprofile.metrics.Counter
	- org.eclipse.microprofile.metrics.Gauge
	- org.eclipse.microprofile.metrics.Histogram
	- org.eclipse.microprofile.metrics.Metadata
	- org.eclipse.microprofile.metrics.Meter
	- org.eclipse.microprofile.metrics.Metered
	- org.eclipse.microprofile.metrics.Metric
	- org.eclipse.microprofile.metrics.MetricID
	- org.eclipse.microprofile.metrics.MetricRegistry
	- org.eclipse.microprofile.metrics.MetricType
	- org.eclipse.microprofile.metrics.Snapshot
	- org.eclipse.microprofile.metrics.Timer
	- org.eclipse.microprofile.metrics.Timer$Context
	- org.hibernate.Session
	- org.infinispan.protostream.BaseMarshaller
	- org.infinispan.protostream.FileDescriptorSource
	- org.infinispan.protostream.ImmutableSerializationContext
	- org.infinispan.protostream.SerializationContext
	- org.infinispan.protostream.SerializationContextInitializer
	- org.jboss.logging.DelegatingBasicLogger
	- org.jboss.logging.Logger
	- org.reactivestreams.Publisher
	- org.reactivestreams.Subscriber
	- org.slf4j.Logger
	- org.w3c.dom.Node
```
As you can see, I guess, the listed classes came all from _quarkus-extensions_ or any 3rd party lib defined in `pom.xml`. Actually, 3rd party libs must be registered manually by `application.properties`, e.g.:

```
quarkus.index-dependency.otherlib.group-id = otherlib
quarkus.index-dependency.otherlib.artifact-id = otherlib-impl
```

I must do this for each included library, because currently, quarkus automatically indexes only the main module but not the 3rd party libraries. Even with the definition in `application.properties`, it could be possible that 3rd party libs need a `META-INF/jandex.idx` to be resolvable by quarkus. How should I do that?

For example, even if I include a dependency in my application by `pom.xml `and registering this dependency in `application.properties`:

```
quarkus.index-dependency.{otherlib}.group-id = ..
quarkus.index-dependency.{otherlib}.artifact-id = ..
```

few dependencies are still present in the list of `Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:..`  I dont know why, because I already registered it within `application.properties`. 

Quarkus should also index all the dependencies defined in the lib-folder **automatically** on compile, without declaring it manually in `application.properties`. Why not generating a `master-jandex.idx` within my application on compile by scanning all dependencies and my application. With this, user does not need to include and struggle with `jandex-maven-plugin`, `beans.xml` or `application.properties` only to register these dependencies.

**To Reproduce**
1. compile quarkus app with some extensions or 3rd party lib.

**Environment (please complete the following information):**
 - Output of `java -version`: JDK12
 - Quarkus version or git rev: 1.0 FINAL

**Comment by nimo23** [comment] 2020-01-12 02:32
I think it can be closed if https://github.com/quarkusio/quarkus/issues/6477 is done.

**Comment by nimo23** [comment] 2020-01-12 02:34
Related to https://github.com/quarkusio/quarkus/issues/6477.

**Comment by gsmet** [comment] 2020-02-05 10:35
I would need a reproducer to understand where this is coming from and see if we need to tweak the rules or not.

**Comment by nimo23** [comment] 2020-02-17 17:48
@gsmet I also tried the reproducer with jackson instead of yasson for the rest-endpoint to be sure that this is not a marshalling issue..

**Comment by gsmet** [comment] 2020-03-03 12:33
Your issue is that you try to serialize things that shouldn't be serialized like the EntityManager, loggers, and other fun things that you include in the objects you return from your REST resources.

In fact the warning you have is good because it certainly shows you that you shouldn't do what you're doing.

**Comment by nimo23** [comment] 2020-03-03 12:48
>that you try to serialize things that shouldn't be serialized like the EntityManager,

And how can I exclude those properties from serializing? I tried it with `@Transient`, `@JsonbTransient`, `transient`.

**Comment by nimo23** [comment] 2020-03-03 12:51
Jsonb knows about `@JsonbTransient`, so it will not serialize those funny properties, but jandex seems to ignore that and logs the warnings..

**Comment by nimo23** [comment] 2020-03-03 12:59
For example having this in a class:

```
@JsonbTransient
public EntityManager getEm() {
	return em;
}.
```

indicates that I do not try to serialize the em and indeed it will not be serialized by JsonB. But Jandex wrongly thinks that I want to serialize it and prints the warning..

**Comment by geoand** [comment] 2021-07-28 11:32
Closing as a duplicate of https://github.com/quarkusio/quarkus/issues/5871

**Closed by geoand** 2021-07-28 11:32 UTC
Labels: kind/bug

**Comment by nimo23** [comment] 2021-07-28 14:14
> Closing as a duplicate of #5871

@geoand How can https://github.com/quarkusio/quarkus/issues/5871 be a duplicate of https://github.com/quarkusio/quarkus/issues/5871 ?

**Comment by geoand** [comment] 2021-07-28 14:57
It's magic, because everyone knows that #5871=#6477
