### ISSUE TITLE
Allow mvn create-extension outside of quarkus

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#4108] opened 2019-09-19 08:41 UTC
**Description**
In the guide, https://quarkus.io/guides/extension-authors-guide, the extension dev happen directly in Quarkus. When I try to use the maven `create-extension`, I get "Creating standalone extension projects is not supported yet. Only adding modules under and existing pom.xml file is supported. -> [Help 1]"

I think the plugin (and the guide) should allow (demonstrate) creating an extension from outside of the Quarkus codebase. This feature is going to become really important with the soon coming  Quarkus Platform.

@stuartwdouglas has created such a repository in the mean time: https://github.com/stuartwdouglas/rhte-extension/tree/empty

**Comment by aloubyansky** [comment] 2020-01-23 15:44
This is actually a duplicate of #3321, iiuc.

**Closed by aloubyansky** 2020-01-23 15:44 UTC
Labels: kind/enhancement
