### ISSUE TITLE
Quarkus Redis client not accepting hostnames with underscores in it

### ISSUE THREAD

**Issue by magnusvage** [quarkusio/quarkus#16037] opened 2021-03-26 07:36 UTC
## Describe the bug
This is a borderline bug, since, depending on where on the Internet you check, underscores are either not recommended or not allowed in hostnames.

The issue I am having is that I am running a Quarkus App in one Docker Swarm stack, which needs to connect to a Redis server in another stack. In the Docker Swarm world, with the service redis running in the stack redis, that means that my config would have to be 

`quarkus.redis.hosts=redis://redis_redis:6379`

However, in io.quarkus.redis.client.runtime.RedisConfig.RedisConfiguration, the hosts are defined as a set of URIs
```
        @ConfigItem(
            defaultValueDocumentation = "redis://localhost:6379"
        )
        public Optional<Set<URI>> hosts;
```

and java.net.URI does not accept hostnames with underscores in them.

### Expected behavior
The Redis client uses the Redis host name with underscores in it as defined in application.properties

### Actual behavior
The Redis client defaults to using redis://localhost:6379

## To Reproduce

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

Or attach an archive containing the reproducer to the issue.

1. Start from the Redis quickstart, https://github.com/quarkusio/quarkus-quickstarts/tree/main/redis-quickstart
2. Update application.properties with quarkus.redis.hosts=redis://redis_redis:6379
3. Run application, it will connect to the default Redis hostname redis://localhost:6379

**Comment by machi1990** [comment] 2021-03-26 08:24
The https://github.com/quarkusio/quarkus/blob/23b3435d0cae0fe428d7cf031a57809c0d510fc9/extensions/redis-client/runtime/src/main/java/io/quarkus/redis/client/runtime/RedisConfig.java#L66 config item type can be changed to a `String`. It should be a quick fix and some extensions does this already, but I'd like to get @gsmet @pmlopes opinion on this too.

**Comment by cescoffier** [comment] 2021-03-28 11:26
No problem to switch to String. URI was providing some formatting rules, validating the user input.

I'm actually surprised that underscore is not supported. I need to check the official URI format to check.

**Comment by pmlopes** [comment] 2021-03-28 13:01
Vertx redis uses URI to parse the connection string. Just need to verify if underscores are working as expected. I don't know why it shouldn't tbh.

**Comment by magnusvage** [comment] 2021-03-28 19:26
@pmlopes seems to have been reported for at least a few years.
This bug report talks about java.net.URL accepting underscores, would that be an easier fix than moving to a String perhaps?
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8180809

**Comment by pmlopes** [comment] 2021-03-29 07:31
@cescoffier one of the reasons why URI is being used instead of URL was because in the past URL forced the whole network stack and ssl support to be included on a native image. If this isn't a problem anymore changing it upstream in `vertx-redis-client` isn't a problem

**Comment by pmlopes** [comment] 2021-03-29 08:05
Having a look at `URL` it will not work to parse the connection string because it will not allow the `redis`/`rediss` protocol

**Comment by pmlopes** [comment] 2021-03-29 08:08
The RFC 1123 also dissallows the usage of `_` in domain names, so that is why I think the JDK classes don't allow it. Windows, however, may allow it if used in netbios: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc959336(v=technet.10) but they recommend avoiding it if names are to be resolved outside windows (which is the case).

**Comment by machi1990** [comment] 2021-03-29 08:11
> The RFC 1123 also dissallows the usage of `_` in domain names, so that is why I think the JDK classes don't allow it. Windows, however, may allow it if used in netbios: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-2000-server/cc959336(v=technet.10) but they recommend avoiding it if names are to be resolved outside windows (which is the case).

So our best option is to leave it as it is and ask user to not include underscore in domain names?

**Comment by magnusvage** [comment] 2021-03-29 08:13
I think this is an issue of RFC/specs vs. reality. Agreed, the specs say no to underscores, but in reality it has become somewhat prevalent (but one could argue it is a bad design choice on the Docker Swarm side to generate hostnames like this).

**Comment by pmlopes** [comment] 2021-03-29 16:37
@magnusvage I agree, yet this isn't a trivial issue. Spring and others have open issues regarding the same (support underscore in URIs).

Even though if we relax the rule by creating a parser ourselves, any underlying library that uses `URI` internally will end up blowing with the same exception.

This is more of a JDK structural issue, and sadly `URL` can't be used either... (although it allows underscores) it doesn't allow custom protocols such as `redis://` because the way it was designed it needs to know the protocol to perform equality checks and more...

From the docker docs I see that they recommend users to create a network and there you can specify the hostname you wish.

https://github.com/docker/compose/issues/229

**Comment by gsmet** [comment] 2021-04-01 09:30
I don't think we can reasonably do something about this. Closing.

**Closed by gsmet** 2021-04-01 09:30 UTC
Labels: area/redis, kind/bug

**Comment by sven-geisenhainer** [comment] 2022-09-27 09:46
A proper warning in the logs when defaulting to localhost in case of underscores would be a helpful time saver.
