### ISSUE TITLE
Native image charset encoding UTF-8

### ISSUE THREAD

**Issue by richsanram** [quarkusio/quarkus#1971] opened 2019-04-10 02:31 UTC
When quarkus-maven-plugin is used to build a native image, the resulting binary cannot support UTF-8 characters.

I resolved this setting file.encoding property by hand in the command:

docker run -v /path/example/target:/project:z --rm quay.io/quarkus/centos-quarkus-native-image:graalvm-1.0.0-rc15 **-J-Dfile.encoding=UTF-8** -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -H:InitialCollectionPolicy='com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime' -jar example-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:+PrintAnalysisCallTree -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:-SpawnIsolates -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace

**Comment by limadelrey** [comment] 2019-09-17 16:39
Any update on this @richsanram?

**Comment by gsmet** [comment] 2019-11-13 20:23
I'm closing as we don't have enough information to understand what the issue is.

If you encounter the issue yourself, please open a new issue with the description of what the problem you're trying to solve is.

**Closed by gsmet** 2019-11-13 20:23 UTC

**Comment by nhoughto** [comment] 2020-07-06 23:30
For those coming google, this appears the same as https://github.com/oracle/graal/issues/2492

**Comment by gsmet** [comment] 2020-07-07 11:53
@jaikiran continuing here as I mistakenly posted in the GraalVM issue instead of this one.

I think your proposal is reasonable and we can add an option later if people ask for it. Maybe let's make it ready for our next CR so that people can complain early if it's an issue for them.

**Comment by jaikiran** [comment] 2020-07-07 12:25
@gsmet, done https://github.com/quarkusio/quarkus/pull/10527

**Comment by gsmet** [comment] 2020-07-07 15:15
This will be fixed in the upcoming 1.7 release.
