### ISSUE TITLE
How to get Multipart info in web request filter.

### ISSUE THREAD

**Issue by guoxunbo** [quarkusio/quarkus#24633] opened 2022-03-30 10:57 UTC
### Describe the bug

> I want to log the upload file and request info in my logfilter. But I don't get the multipartinfo in my log filter.
such like this.
```java
@Provider
@Priority(Priorities.USER + 1000)
@Slf4j
public class WebLogFilter implements ContainerRequestFilter, ContainerResponseFilter {

    public static final int MAX_IP_ADDRESS_LENGTH = 15;
    public static final String LOCAL_IP_ADDRESS = "127.0.0.1";
    public static final String LOCALHOST_IP_ADDRESS = "localhost";

    @Context
    HttpRequest httpRequest;

    @Inject
    ObjectMapper objectMapper;

    @Override
    public void filter(ContainerRequestContext containerRequestContext) throws IOException {
        UriInfo uriInfo = containerRequestContext.getUriInfo();
        String userAgent = containerRequestContext.getHeaderString(HttpHeaders.USER_AGENT);
        String ipAddress = getRemoteAddress();
        containerRequestContext.getMediaType();

        // TODO 暂时只处理POST请求。因为系统整体请求都是基于post进行请求，后续需要支持处理上传文件等的日志
        String contentType = containerRequestContext.getHeaderString(HttpHeaders.CONTENT_TYPE);
        String requestString = StringUtils.EMPTY;
        if (contentType.contains(MediaType.MULTIPART_FORM_DATA)) {

            HttpHeaders httpHeaders = httpRequest.getHttpHeaders();
            requestString = getRequestString(containerRequestContext);

            System.out.println(requestString);
        } else {
            requestString = getRequestString(containerRequestContext);
        }

        MDCScope.buildMdcScopeInfo(requestString);

        if (log.isInfoEnabled()) {
            log.info("Ip {} at os and browser info {} sended {} method to {}.", ipAddress, userAgent, containerRequestContext.getMethod(), uriInfo.getPath());
            log.info("The Request str is {}", requestString);
        }

    }

    public String getRequestString(ContainerRequestContext containerRequestContext) throws IOException{
        try (BufferedInputStream stream = new BufferedInputStream(containerRequestContext.getEntityStream());){
            String requestString = IOUtils.toString(stream, Charset.defaultCharset());
            containerRequestContext.setEntityStream(IOUtils.toInputStream(requestString, Charset.defaultCharset()));
            return requestString;
        } catch (IOException e){
            throw e;
        }
    }

    @Override
    public void filter(ContainerRequestContext containerRequestContext, ContainerResponseContext containerResponseContext) throws IOException {
        Object response = containerResponseContext.getEntity();
        if (log.isInfoEnabled() && response != null) {
            log.info("Get Response {}", objectMapper.writeValueAsString(response).toString());
        }
    }


    private String getRemoteAddress() throws IOException{
        String ipAddress = httpRequest.getRemoteAddress();

        if (LOCAL_IP_ADDRESS.equals(ipAddress) || LOCALHOST_IP_ADDRESS.equalsIgnoreCase(ipAddress)) {
            InetAddress host = InetAddress.getLocalHost();
            ipAddress = host.getHostAddress();
        }

        if (StringUtils.isNullOrEmpty(ipAddress) && ipAddress.length() > MAX_IP_ADDRESS_LENGTH) {
            if (ipAddress.indexOf(StringUtils.SPLIT_COMMA) > 0) {
                ipAddress = ipAddress.substring(0, ipAddress.indexOf(","));
            }
        }

        return ipAddress;
    }
}

```
I had try more wat to get Multipart info but not get it.[失望]
such as
1. use the `HttpServerRequest` 
```java

@Context
HttpServerRequest httpServerRequest;
```
but i got error in starting time.
```java
Caused by: java.lang.RuntimeException: RESTEASY003400: Illegal to inject a non-interface type into a singleton
	at org.jboss.resteasy.core.ContextParameterInjector.inject(ContextParameterInjector.java:199)
	at org.jboss.resteasy.core.PropertyInjectorImpl.inject(PropertyInjectorImpl.java:208)
	at io.quarkus.resteasy.common.runtime.QuarkusInjectorFactory$UnwrappingPropertyInjector.inject(QuarkusInjectorFactory.java:68)
	at org.jboss.resteasy.core.providerfactory.ResteasyProviderFactoryImpl.injectedInstance(ResteasyProviderFactoryImpl.java:1413)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.createInterceptor(JaxrsInterceptorRegistryImpl.java:150)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.initialize(JaxrsInterceptorRegistryImpl.java:168)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.checkInitialize(JaxrsInterceptorRegistryImpl.java:183)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$OnDemandInterceptorFactory.getInterceptor(JaxrsInterceptorRegistryImpl.java:193)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl$AbstractInterceptorFactory.postMatch(JaxrsInterceptorRegistryImpl.java:131)
	at org.jboss.resteasy.core.interception.jaxrs.JaxrsInterceptorRegistryImpl.postMatch(JaxrsInterceptorRegistryImpl.java:288)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerRequestFilterRegistryImpl.postMatch(ContainerRequestFilterRegistryImpl.java:30)
	at org.jboss.resteasy.core.interception.jaxrs.ContainerRequestFilterRegistryImpl.postMatch(ContainerRequestFilterRegistryImpl.java:12)
	at org.jboss.resteasy.core.ResourceMethodInvoker.<init>(ResourceMethodInvoker.java:142)
	at org.jboss.resteasy.core.ResourceMethodRegistry.processMethod(ResourceMethodRegistry.java:381)
	at org.jboss.resteasy.core.ResourceMethodRegistry.register(ResourceMethodRegistry.java:308)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:259)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:227)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:208)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:192)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addResourceFactory(ResourceMethodRegistry.java:175)
	at org.jboss.resteasy.core.ResourceMethodRegistry.addPerRequestResource(ResourceMethodRegistry.java:87)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registerResources(ResteasyDeploymentImpl.java:518)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.registration(ResteasyDeploymentImpl.java:475)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.startInternal(ResteasyDeploymentImpl.java:164)
	at org.jboss.resteasy.core.ResteasyDeploymentImpl.start(ResteasyDeploymentImpl.java:121)
	at io.quarkus.resteasy.runtime.standalone.ResteasyStandaloneRecorder.staticInit(ResteasyStandaloneRecorder.java:43)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.ResteasyStandaloneBuildStep$staticInit345281060.deploy(Unknown Source)
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.ReflectAccess.newInstance(ReflectAccess.java:128)
	at java.base/jdk.internal.reflect.ReflectionFactory.newInstance(ReflectionFactory.java:347)
	at java.base/java.lang.Class.newInstance(Class.java:645)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:41)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:120)
```

> Does there has any way to got the mutipartinfo in filter?  

### Output of `java -version`

17

### Quarkus version or git rev

2.7.2.Final

**Comment by yrodiere** [comment] 2022-10-19 06:26
From where I stand (far, far away...) this looks like a CDI problem. I'll assume what you're doing is possible, though I wasn't aware you could use SLF4J in Quarkus (but maybe you're just using the API, with jboss-logging being the implementation?).

As to solutions:

* I don't know if it's possible, but try making your filter application-scoped by adding `@ApplicationScoped`.
* If that doesn't work, try using this to inject the context:
  ```
  @Context
  javax.enterprise.inject.Instance<HttpServerRequest> httpServerRequest;
  ```
* If that doesn't work, someone else will have to chime in :shrug:

**Comment by mkouba** [comment] 2022-10-19 07:00
> this looks like a CDI problem

Why CDI? I can see the `RESTEASY003400: Illegal to inject a non-interface type into a singleton` error message.

> `@Context` javax.enterprise.inject.Instance<HttpServerRequest> httpServerRequest;

I don't think mixing JAX-RS annotations and CDI types could work. You could do `@Inject  javax.enterprise.inject.Instance<HttpServerRequest> httpServerReques` though.

> though I wasn't aware you could use SLF4J in Quarkus (but maybe you're just using the API, with jboss-logging being the implementation?

Yes, it should be possible to use the SLF4j API in Quarkus.

**Comment by yrodiere** [comment] 2022-10-19 07:16
> Why CDI? I can see the RESTEASY003400: Illegal to inject a non-interface type into a singleton error message.

I was guessing that resteasy was using CDI under the hood for injection. But yes, that was probably wrong, sorry.

**Comment by mkouba** [comment] 2022-10-19 08:33
> > Why CDI? I can see the RESTEASY003400: Illegal to inject a non-interface type into a singleton error message.
> 
> I was guessing that resteasy was using CDI under the hood for injection, given it's mentioning concepts that I usually see in CDI (singleton). But yes, that was probably wrong, sorry.

No proble. AFAIK it is using CDI for `@Inject` injection points but not for `@Context`. 

@guoxunbo Is the `HttpServerRequest` mentioned in the description the `io.vertx.core.http.HttpServerRequest`? In any case, we would need a small reproducer app to see what extensions are used etc.

**Comment by guoxunbo** [comment] 2022-10-30 13:38
@mkouba 
Hello. OK. I will give you a small reproducer app tomorrow.
I just want to get `MultipartBody` info in the log filter. such as 👍 
```java
@NoArgsConstructor
public class MultipartBody implements Serializable {

    @FormParam("file")
    @PartType(MediaType.APPLICATION_OCTET_STREAM)
    public InputStream file;

    @FormParam("fileName")
    @PartType(MediaType.TEXT_PLAIN)
    public String fileName;

    @FormParam("request")
    @PartType(MediaType.TEXT_PLAIN)
    public String request;

}
```
> But now i don't know how to get it in log filter. 
```java
@Path("importData")
    @POST
    @Produces(MediaType.APPLICATION_JSON)
    @Consumes(MediaType.MULTIPART_FORM_DATA)
    public TableResponse importData(@MultipartForm MultipartBody multipartBody) throws Exception {
        TableRequest tableRequest = objectMapper.readerFor(TableRequest.class).readValue(multipartBody.request);
    }
```

**Comment by geoand** [comment] 2023-01-05 18:21
Closing as never got a reproducer. 

Feel free to comment and / or reopen if one becomes available

**Closed by geoand** 2023-01-05 18:21 UTC
Labels: kind/question, area/resteasy, needs-reproducer
