### ISSUE TITLE
Multiple QuarkusTestResource annotations in Test are ignored

### ISSUE THREAD

**Issue by lkrzyzanek** [quarkusio/quarkus#5252] opened 2019-11-06 12:31 UTC
**Describe the bug**
Multiple `@QuarkusTestResource` annotations in Test are completely ignored
e.g. 
@QuarkusTest
@QuarkusTestResource(ActiveMQServerTestResource.class)
@QuarkusTestResource(ActiveMQClientTestResource.class)

**Expected behavior**
Given that `QuarkusTestResource` annotation is `Repeatable` both test resources should be processed.

**Actual behavior**
Both QuarkusTestResource are ignored

**To Reproduce**
1. Create a test with two simple "QuarkusTestResource" test resources
2. Run test
3. See that both QuarkusTestResource are ignored. If you comment one of them just 1 is picked and processed correctly.

**Comment by lkrzyzanek** [comment] 2019-11-06 12:38
The trouble seems to be in method `TestResourceManager.getTestResources` here:  https://github.com/quarkusio/quarkus/blob/master/test-framework/common/src/main/java/io/quarkus/test/common/TestResourceManager.java#L88

When I'm debugging the `index` variable it contains list of all annotations but in case of multiple `QuarkusTestResource` annotations the name is  `io.quarkus.test.common.QuarkusTestResource$List` and no `io.quarkus.test.common.QuarkusTestResource`

**Comment by gsmet** [comment] 2019-11-06 13:59
@mkouba could you have a look at that one? There might be something fishy in how Jandex handles repeatable annotations but we really need to figure it out as most of our code is not prepared for having them handled a different way than usual annotations.

**Comment by gastaldi** [comment] 2019-11-06 14:23
Definitely a bug. I managed to reproduce it in this testcase: 

```java
package io.quarkus.test.common;

import java.util.Collections;
import java.util.Map;
import java.util.concurrent.atomic.AtomicInteger;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

public class TestResourceManagerTest {

    @Test
    void testRepeatableAnnotationsAreIndexed() {
        AtomicInteger counter = new AtomicInteger();
        TestResourceManager manager = new TestResourceManager(MyTest.class);
        manager.inject(counter);
        assertThat(counter.intValue()).isEqualTo(2);
    }


    @QuarkusTestResource(FirstLifecycleManager.class)
    @QuarkusTestResource(SecondLifecycleManager.class)
    public static class MyTest {}


    public static class FirstLifecycleManager implements QuarkusTestResourceLifecycleManager {
        @Override
        public Map<String, String> start() {
            return Collections.emptyMap();
        }

        @Override
        public void inject(Object testInstance) {
            ((AtomicInteger)testInstance).incrementAndGet();
        }

        @Override
        public void stop() {

        }
    }

    public static class SecondLifecycleManager implements QuarkusTestResourceLifecycleManager {
        @Override
        public Map<String, String> start() {
            return Collections.emptyMap();
        }

        @Override
        public void inject(Object testInstance) {
            ((AtomicInteger)testInstance).incrementAndGet();
        }

        @Override
        public void stop() {

        }
    }

}
```

**Comment by mkouba** [comment] 2019-11-06 14:35
>  the name is io.quarkus.test.common.QuarkusTestResource$List and no io.quarkus.test.common.QuarkusTestResource...

@lkrzyzanek Yes, that's expected - for repeatable annotations you get the "container" annotation.

@gastaldi Thanks for the reproducer!

**Comment by gsmet** [comment] 2019-11-06 14:46
@mkouba what bothers me a bit with this is that there's a good chance some of our code does not deal with this properly. I would have expected to get the inner annotations when trying to get them.

**Comment by gastaldi** [comment] 2019-11-06 14:47
I have a fix for this, let me send a PR. Feel free to reject or accept it :)

**Comment by gsmet** [comment] 2019-11-06 14:49
Is it a general fix or a localized one? I'm really not comfortable having everyone to think about this every time they want to get annotations.

**Comment by gastaldi** [comment] 2019-11-06 14:50
A localized one, the general fix would involve changing Jandex AFAIK

**Comment by mkouba** [comment] 2019-11-06 14:53
> there's a good chance some of our code does not deal with this properly...

There is. On the other hand, any repeatable annotation processed by a build step should have a test. I know we implemented this for  `io.quarkus.vertx.web.Route` and `io.quarkus.scheduler.Scheduled`.

> I would have expected to get the inner annotations when trying to get them.

Well, repeatable annotations are compiled into the container annotations. 

We can't change the behavior of `IndexView#getAnnotation()` as it could break existing code. Reflection API also has specific methods to handle repeatable annotations.

**Comment by gastaldi** [comment] 2019-11-06 14:58
Since this issue is assigned to @mkouba (just realized after opening the PR) I closed mine in favor of his :wink:

**Comment by mkouba** [comment] 2019-11-06 14:59
> I'm really not comfortable having everyone to think about this every time they want to get annotations.

See my comment above...

**Comment by gsmet** [comment] 2019-11-06 15:13
@mkouba I get your point... but... how do I deal with it on HV for instance? I have a ton of constraint annotations, some of them are repeatable, not all of them and users can also define their own with their own container.

Is there a way to handle that without it becoming overly complicated? For me, it's the work of the index to manage this for me. I shouldn't have to go for the containers and unwrap them.

**Comment by mkouba** [comment] 2019-11-07 08:20
@gsmet I understand. We will need to add something similar to `java.lang.reflect.AnnotatedElement.getAnnotationsByType(Class<T>)` to the `IndexView`. I've created https://github.com/wildfly/jandex/issues/67.

**Comment by gsmet** [comment] 2019-11-15 14:51
The immediate issue is solved.

**Closed by gsmet** 2019-11-15 14:51 UTC
Labels: bug

**Comment by lkrzyzanek** [comment] 2019-11-20 14:03
Nicely works in 1.0.0.CR2.
Thanks guys!
