### ISSUE TITLE
Enabled micrometer.binder.http-server should also capture parameterized sub-resources

### ISSUE THREAD

**Issue by thomasdarimont** [quarkusio/quarkus#31497] opened 2023-03-01 08:49 UTC
### Description

If `quarkus.micrometer.binder.http-server.enabled=true` is enabled, then quarkus generates metrics for resource invocations. That works fine for "primary resources" but not for sub-resources, as shown in the example below.

A gist with an example can be found here: https://gist.github.com/thomasdarimont/cd8c10ed57ba8dc2e1bd888e1bc99e4f

Given resources like:
```java
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;
import javax.ws.rs.container.ResourceContext;
import javax.ws.rs.core.Context;

@Path("/resource")
public class DemoResource {

    @Context
    ResourceContext resourceContext;

    @GET
    @Path("{param1}")
    public String resource(@PathParam("param1") String param1) {
        return "resource1:" + param1;
    }

    @Path("{param1}/subresource")
    public DemoSubResource subResource(@PathParam("param1") String param1) {
        return resourceContext.initResource(new DemoSubResource(param1));
    }

}
```

```java
package org.acme;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.PathParam;

public class DemoSubResource {

    private final String param1;

    public DemoSubResource(String param1) {
        this.param1 = param1;
    }

    @GET
    @Path("{param2}")
    public String subresource(@PathParam("param2") String param2) {
        return "resource:" + param1 + ":subresource:" + param2;
    }
}
```

Requests to the primary-resource `http://localhost:8080/resource/1` produce the following metric in http://localhost:8080/q/metrics:
```
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/resource/{param1}",} 7.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/resource/{param1}",} 4.500558364
```
We can see that the `param1` is correctly templated to avoid capturing individual parameter instances.

However, requests for the sub-resource `http://localhost:8080/resource/1/subresource/3` only produces:
```
http_server_requests_seconds_count{method="GET",outcome="SUCCESS",status="200",uri="/resource/{param1}/subresource",} 14.0
http_server_requests_seconds_sum{method="GET",outcome="SUCCESS",status="200",uri="/resource/{param1}/subresource",} 46.928154483
```
As we see, the ` param2` is missing in the recorded URI template.

It would be great if parameterized sub-resources would also be considered for template URI generation to properly collect metrics.

### Implementation ideas

It seems that `io.quarkus.resteasy.runtime.QuarkusRestPathTemplateInterceptor` populates the `UrlPathTemplate` which is then used by `io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric#applyTemplateMatching (via getUrlTemplatePath())` to replace concrete parameters with the templated path.

The `QuarkusRestPathTemplateInterceptor` is emitted via the `RestPathAnnotationProcessor`.

The logic in `RestPathAnnotationProcessor` or `QuarkusRestPathTemplateInterceptor` could be extended to support generating correctly templated URIs for sub-resources.

**Comment by brunobat** [comment] 2023-03-01 11:43
That subresource class pattern is quite a special case...
Have you tested on the main class with?
`@Path("{param1}/subresource/{param2}")`

**Comment by geoand** [comment] 2023-03-01 13:16
> And the 2nd resource is not even managed by the container.

This may or may not be the case, it depends on how it's used. For example, in RESTEasy Reactive we  support using something like [this](https://github.com/quarkusio/quarkus/blob/2.16.3.Final/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/SubResourceRequestFilterTest.java#L57).

@thomasdarimont out of curiosity, is there any reason you are using RESTEasy Classic instead of RESTEasy Reactive?

**Comment by thomasdarimont** [comment] 2023-03-01 19:14
@brunobat thanks for taking a look, with `@Path("{param1}/subresource/{param2}")` on the `subResource`-method in the main class the endpoint is not callable at all.

I used resteasy classic because it's what is currently being used by Keycloak. I'll try the same with the reactive stuff (which Keycloak is going to migrate eventually too).

**Comment by thomasdarimont** [comment] 2023-03-01 19:21
@geoand if I use 
```
 <dependency>
            <groupId>io.quarkus.resteasy.reactive</groupId>
            <artifactId>resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus.resteasy.reactive</groupId>
            <artifactId>resteasy-reactive-jackson</artifactId>
        </dependency>
``` with the same code as shown above is till get the same result, that the sub-resource {param2} parameter is not considered for the templateUri in the http-server metrics.

The other variant you mentioned, which injects the sub-resource`, cannot be used since I need to pass the current parameter `{param1}` to the constructor of the sub-resource. That's also the pattern that Keycloak uses for it's resources, e.g. the [UsersResource](https://github.com/keycloak/keycloak/blob/main/services/src/main/java/org/keycloak/services/resources/admin/UsersResource.java#L229)

**Comment by ebullient** [comment] 2023-03-01 19:41
This is one of those cases that is really tricky, especially across rest container impls.

https://github.com/quarkusio/quarkus/pull/31059 -- this did go in recently, not sure if that helps. 

A workaround is explained here: https://github.com/quarkusio/quarkus/issues/30843#issuecomment-1416560750

You can use a match pattern to avoid this:

**Comment by thomasdarimont** [comment] 2023-03-01 21:05
> How about providing a custom annotation to let users add the "missing" metadata themselves?

**Comment by geoand** [comment] 2023-03-02 08:34
> I used resteasy classic because it's what is currently being used by Keycloak. I'll try the same with the reactive stuff (which Keycloak is going to migrate eventually too).

This will not be the case - cc @pedroigor :)

**Comment by BenLad17** [comment] 2023-12-20 18:59
Keycloak switched to RESTEasy Reactive in https://github.com/keycloak/keycloak/issues/10713 which was released in version 23. I tested re-enabling the changes in https://github.com/keycloak/keycloak/commit/42f66f2c6f7df19fad910e6d6b7878c3c511ef32

**Comment by wernerdegroot** [comment] 2024-02-09 20:16
I have a similar (but not quite identical) issue. I'm using Quarkus (3.6.9) with `resteasy-reactive` with subresource like in https://github.com/quarkusio/quarkus/blob/2.16.3.Final/extensions/resteasy-reactive/quarkus-resteasy-reactive/deployment/src/test/java/io/quarkus/resteasy/reactive/server/test/resource/basic/SubResourceRequestFilterTest.java#L57 but the parent resource's path is always resolved to `/null` in the tags. This will result in tags like `/null`, `/null/{id}`, etc.

I worked around it with an ugly hack by manually updating/overwriting the vert.x context with key `"UrlPathTemplate"` 😞 

Is there anyone who could take a look? Any help is very much appreciated!

**Comment by geoand** [comment] 2024-03-05 13:45
> Is there anyone who could take a look? Any help is very much appreciated!

Can you provide a small reproducer (preferable with Quarkus 3.8) that exhibits the problem?

**Comment by thomasdarimont** [comment] 2024-03-05 14:37
@geoand I just created a reproducer with resteasy-reactive and quarkus 3.8.1
https://gist.github.com/thomasdarimont/21a64b884d7e7d46e8befe23b6cc0f2c

It still doesn't work but the problem is different. Now the subresource param {param2} is correctly detected, but the sub-resource prefix is `null`  instead of the actual resource.

With a request to `http://localhost:8080/resource/1/subresource/3` 

Expected:
```
/resource/{param1}/subresource/{param2}
```

Actual:
```
/null/{param2}
```

**Comment by geoand** [comment] 2024-03-05 14:38
Got it, thanks!

**Comment by thomasdarimont** [comment] 2024-03-05 15:00
It seems that the template path is indeed correct within `io.quarkus.resteasy.reactive.server.runtime.observability.ObservabilityHandler#handle` but it seems that the URL template get's lost later on:
![image](https://github.com/quarkusio/quarkus/assets/314690/c14e424b-2508-4d3e-84da-2216f61cf987)

**Comment by geoand** [comment] 2024-03-05 15:02
💪🏼 

I'll have to debug and see what's going on. Hopefully soon

**Comment by thomasdarimont** [comment] 2024-03-05 15:08
In `io.quarkus.micrometer.runtime.binder.vertx.HttpRequestMetric#getUrlTemplatePath` the call to `request.context().getLocal("UrlPathTemplate")` returns `null`. That's the problem.

**Comment by geoand** [comment] 2024-03-05 15:12
Super odd as that should have been set by `ObservabilityHandler#handle`...

**Comment by geoand** [comment] 2024-03-05 15:17
I see what's going on here...

The `ObservabilityHandler` is getting called again for the subresource and it's messing up everything. 
I don't have a fix in mind yet because I never really remember how we make subresources work... 

I'll dig in more hopefully in the next few days

**Comment by geoand** [comment] 2024-03-05 15:39
It might have been easier than expected: #39192

I'll into finishing it up tomorrow.

**Comment by geoand** [comment] 2024-03-05 15:54
Go ahead and do a PR if you like as I'm babysitting and won't have time to complete it until tomorrow 😃

**Closed** 2024-03-06 12:29 UTC
Labels: kind/enhancement, area/metrics

**Comment by ahus1** [comment] 2024-03-20 12:02
I'm testing this now for the Keycloak project, and it is working nicely. I create a follow-up issue and PR to optimize the metrics for 404 and 302 responses. See #39581.

**Comment by geoand** [comment] 2024-03-20 12:08
🙏🏼
