### ISSUE TITLE
Quarkus REST extension

### ISSUE THREAD

**Issue by MusaTalluzi** [quarkusio/quarkus#6873] opened 2020-01-29 22:13 UTC
**Describe the extension**
An extension that automatically exposes CRUD endpoints for JPA entities (similar to [Spring Data Rest](https://spring.io/projects/spring-data-rest)) without the need to manually code the `**Resource` classes, which can build on top of [Panache](https://quarkus.io/guides/hibernate-orm-panache). Ideally it provides additional features like pagination, sorting, metadata...

**Comment by geoand** [comment] 2020-01-30 06:26
I am going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/3454. Please follow that issue for the latest information

**Closed by geoand** 2020-01-30 06:26 UTC
Labels: kind/extension-proposal, triage/duplicate
