### ISSUE TITLE
Quarkus cache - persistence layer 

### ISSUE THREAD

**Issue by dicolasi** [quarkusio/quarkus#17058] opened 2021-05-07 09:37 UTC
## Description

Following this guide (https://quarkus.io/guides/cache) we have easily added a local caching layer to our services. However, our pods scale a lot and we are seeing lots of cache miss. Ideally, we would love to add a persistent caching layer using some sass solution such as memchache or redis. 

## Implementation ideas

Use existing quarkus integration for redis and/or infinispan to provide a persistence layer for caching.

**Comment by dicolasi** [comment] 2021-05-10 13:23
Here an example with SpringBoot -> https://www.fatalerrors.org/a/implementation-of-two-level-cache-with-springboot-springcache-redis-caffeine.html

**Comment by gwenneg** [comment] 2021-05-10 14:20
Hi @dicolasi. I would swear I answered here last week, I don't know where my comment went 😄 Sorry about that.

Remote and distributed caching were discussed when the `quarkus-cache` extension was designed almost 2 years ago (#3128, #3306, more recently #8140). At that time, it was decided to start with local caching only and distributed caching was [out of the scope](https://github.com/quarkusio/quarkus/issues/3128#issuecomment-511351463).

I guess this is a good time to start discussing again the possibility of supporting distributed caching in `quarkus-cache`. @Sanne, @emmanuelbernard, @galderz WDYT about this?

**Comment by dicolasi** [comment] 2021-05-10 14:36
Thanks @gwenneg. I can see that something similar is already present for JCache -> https://dzone.com/articles/jcache-api-jsr-107-implementation-for-redis

**Comment by dicolasi** [comment] 2021-05-10 14:40
Basically seems like https://github.com/redisson/redisson does the job.

**Comment by dicolasi** [comment] 2021-05-11 10:58
One potential solution is to have caching layer emit an event when something happens (put/delete) and have the infinispan client reacting to it.

**Comment by Sanne** [comment] 2021-05-11 11:06
> One potential solution is to have caching layer emit an event when something happens (put/delete) and have the infinispan client reacting to it.

That might be fine in some use cases, but the local cache will also need to receive invalidation commands from other nodes. This quickly gets very complicated to implement "automagically" as developers will always need to make some trade-off choices, which in practice leads to most production use cases to require very specific ad-hoc details.

So yes what you suggest might e a good idea for your use case, but we will not implement such a solution "out of the box" in Quarkus at this point in time - but I guess we could discuss solutions for some very specific use cases.

**Comment by Sanne** [comment] 2021-05-11 11:07
cc/ @karesti

**Comment by dicolasi** [comment] 2021-05-11 11:12
@Sanne I am open to any possible solution really. I am just getting lost with this, apparently simple, use case of mine. Any help/guidance is really appreciated.

**Comment by Sanne** [comment] 2021-05-11 14:18
I would suggest using the Infinispan client? You mentioned "we would love to add a persistent caching layer using some sass solution such as memchache or redis" : that's exactly the functionality it offers. Compared to Redis, it has better scaling & clustering capabilities so we see it as the better choice.

 - https://quarkus.io/guides/infinispan-client#additional-features

@karesti @tristantarrant is there also a "quickstart" we could point to? Some 1-2-3 steps to start the server as well for people not familiar with Infinispan?

**Comment by dicolasi** [comment] 2021-05-11 15:45
Thanks for your answer @Sanne. Ok so Infinispan client is the way to go then :) 
Last question (I hope): with quarkus-cache I can very elegantly add @CacheResult for a method and the return values is stored in the local cache. I guess that with infinispan client I got to do a bit of if/then/else, or there is a nicer way to deal with cache miss/cache hit?

**Comment by Sanne** [comment] 2021-05-11 15:52
I'm not aware of anything "nicer".. I suspect it's best you interact with the Infinispan Client directly so that you can implement the most appropriate error handling which is suitable for your application.

**Comment by dicolasi** [comment] 2021-05-12 10:59
@Sanne  can you help with this? https://github.com/infinispan/infinispan-operator/issues/1040

**Comment by dicolasi** [comment] 2021-05-12 12:52
I have created a super simple hello world  client application, but I am getting this error when I try to add something to the cache:

```
Caused by: org.infinispan.client.hotrod.exceptions.TransportException:: ISPN004077: Closing channel [id: 0x097ea28d, L:/192.168.1.13:54371 - R:data-grid.stage.property.xyz/18.130.128.214:80] due to error in unknown operation.
	at org.infinispan.client.hotrod.impl.transport.netty.HeaderDecoder.exceptionCaught(HeaderDecoder.java:208)
	at io.netty.channel.AbstractChannelHandlerContext.invokeExceptionCaught(AbstractChannelHandlerContext.java:302)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:381)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:615)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:578)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: io.netty.handler.codec.DecoderException: org.infinispan.client.hotrod.exceptions.InvalidResponseException:: ISPN004003: Invalid magic number. Expected 0xa1 and received 0x48
```

**Comment by dicolasi** [comment] 2021-05-19 13:29
Are there going to be any updates on this? Otherwise I will close this issue.

**Comment by dicolasi** [comment] 2021-05-19 14:35
I have created my own interceptor for those who wants to use the inifnispan client.
```
@Interceptor
@Priority(1000)
@Cached(cacheName = "")
public class CacheInterceptor {

    @Inject
    RemoteCacheManager remoteCacheManager;

    @Inject
    Logger log;

    @AroundInvoke
    <T> Object checkCache(InvocationContext context) throws Exception {
        Cached cachedAnnotation = context.getMethod().getAnnotation(Cached.class);
        String cacheName = cachedAnnotation.cacheName();
        String key = String.valueOf(context.getParameters()[0]);

        if (cacheExists(cacheName) && isCached(cacheName, key)) {
            return Uni.createFrom().item(getValue(cacheName, key));
        }

        Uni<T> stats = (Uni<T>) context.proceed();

        if (cacheExists(cacheName) && !isCached(cacheName, key)) {
            stats = stats.invoke(data -> putValue(cacheName, key, data));
        }
        return stats;
    }

    private void putValue(String cacheName, String key, Object value) {
        log.infof("Set cached value for key: %s with value: %s", key, value);
        remoteCacheManager.getCache(cacheName).putAsync(key, value);
    }

    private Object getValue(String cacheName, Object key) {
        log.infof("Return cached value for key: %s", key);
        return remoteCacheManager.getCache(cacheName).getAsync(key);
    }

    private boolean isCached(String cacheName, Object key) {
        boolean containsKey = remoteCacheManager.getCache(cacheName).containsKey(key);
        if (containsKey) {
            log.infof("Cache hit for key: %s", key);
        } else {
            log.infof("Cache miss for key: %s", key);
        }
        return containsKey;
    }

    private boolean cacheExists(String cacheName) {
        try {
            if (remoteCacheManager.getCache(cacheName) == null) {
                log.errorf("Cache %s not present. Impossible to leverage the caching layer", cacheName);
                return false;
            }
            return true;
        } catch (TransportException ex) {
            log.errorf("Error while trying to connect to the remote cache: %s", ex.getCause());
            return false;
        }
    }
}
```

```
@InterceptorBinding
@Retention(RetentionPolicy.RUNTIME)
@Target({TYPE, METHOD})
public @interface Cached {
    @Nonbinding String cacheName();
}
```

All you need to do is annotate a method with @Cached and it works (given the fact that inifinispan server is reachable of course :))

**Comment by karesti** [comment] 2021-05-19 17:42
For a quick overview of Infinispan https://infinispan.org/get-started/

For what it's the caching layer using the Infinispan client behind the cache abstraction, we do already do this succesfully with Spring Boot for a long time. For example a latest integration example https://github.com/karesti/protobuf-marshalling-guide/tree/main/marshalling-with-spring-boot-proto

**Comment by fabiojose** [comment] 2021-12-08 17:03
I've wrote some lines of codes to release caching with Redis using JSR-107 annotations.

Check it out: https://github.com/fabiojose/quarkus-redisjcache

May help some of them.

**Comment by qigao** [comment] 2022-06-01 06:01
> I've wrote some lines of codes to release caching with Redis using JSR-107 annotations.
> 
> Check it out: https://github.com/fabiojose/quarkus-redisjcache
> 
> May help some of them.

Hi @fabiojose ,  this is really a good extension except that it was not published to quarkiverse,  and it give more choices for caching.
can anyone from  the  team help to publish this extension?  I think a lot of people including me will appreicate that.

**Comment by tristantarrant** [comment] 2022-06-01 06:12
I wouldn't really invest any effort in the JCache API: it has been stale for years, doesn't have any non-blocking APIs, was never adopted by Java EE/ Jakarta EE/MP. It's better to work on enhancing Quarkus caching.

**Comment by Sanne** [comment] 2022-06-01 15:39
> I wouldn't really invest any effort in the JCache API: it has been stale for years, doesn't have any non-blocking APIs, was never adopted by Java EE/ Jakarta EE/MP. It's better to work on enhancing Quarkus caching.

wise words. We learned a lot since the JCache days; I would agree with Tristan's recommendation to avoid it - using the Quarkus caching layer or the Infinispan client give better control over the outcome, and avoids people getting badly burned.

For these reasons I'll close this issue now - it's a out of date and has too broad of a scope.

If @fabiojose wants to publish his `aurkus-redisjcache` into Quarkiverse that's of course fine? :)
That would make it easier for people to find.

 - https://github.com/quarkiverse/quarkiverse/wiki

**Closed by Sanne** 2022-06-01 15:39 UTC
Labels: kind/enhancement, area/cache
