### ISSUE TITLE
io.quarkus.deployment.dev.RuntimeUpdatesProcessor doScan INFO: Hot replace total time: %ss

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#10746] opened 2020-07-15 11:54 UTC
I got that error with Quarkus 1.6.0.Final

juill. 10, 2020 8:04:42 A.M. io.quarkus.deployment.dev.RuntimeUpdatesProcessor doScan INFO: Hot replace total time: %ss

the bug it's that the value wasn't replace in the output %ss  

I was running the quickstaart with Keycloak

mvn quarkus:dev

and I commented out all that

#quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
#quarkus.oidc.client-id=frontend
#quarkus.oidc.application-type=web-app
#quarkus.http.auth.permission.authenticated.paths=/*
#quarkus.http.auth.permission.authenticated.policy=authenticated
#quarkus.log.category."com.gargoylesoftware.htmlunit.DefaultCssErrorHandler".level=ERROR

and was able to reproduce the error : Hot replace total time: %ss

**Comment by survivant** [comment] 2020-07-15 12:04
https://github.com/quarkusio/quarkus/pull/10748  and https://github.com/quarkusio/quarkus/pull/10749 to fix the issue

**Comment by survivant** [comment] 2020-07-15 12:53
I created a project https://github.com/survivant/quarkus-keycloak-demo  but I found the issue playing with the config in application.properties.

I ran the application using mvn quarkus:dev    and when I put # in all the param in the config, I had that issue.

**Comment by famod** [comment] 2020-07-15 14:11
Apart from getting `io.quarkus.oidc.OIDCException: OIDC server is not available at the 'quarkus.oidc.auth-server-url' URL.` I can confirm that logging format is odd in that reproducer:
```
[INFO] --- quarkus-maven-plugin:1.6.0.Final:dev (default-cli) @ code-with-quarkus ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 3 resources
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to C:\_dev\git\quarkus-keycloak-demo\target\classes
Listening for transport dt_socket at address: 5005
Juli 15, 2020 4:09:23 NACHM. org.jboss.threads
INFO: JBoss Threads version %s
Juli 15, 2020 4:09:24 NACHM. org.jboss.threads
INFO: JBoss Threads version %s
Juli 15, 2020 4:09:26 NACHM. io.quarkus.application
```

**Comment by famod** [comment] 2020-07-15 14:36
Huh?!
- clone
- `mvn clean verify -DskipTests`
- `mvn quarkus:dev` -> odd formatting
- `mvn quarkus:dev` -> odd formatting (even with yet another `mvn clean verify -DskipTests`)
- modify `pom.xml` to move `quarkus-smallrye-openapi` & `quarkus-resteasy-qute` _before_ the test dependencies
- `mvn clean verify -DskipTests`
- `mvn quarkus:dev` -> still odd formatting
- `mvn clean verify -DskipTests`
- `mvn quarkus:dev` -> formatting is fixed!?

IIRC, for one iteration is was fixed directly after adjusting the pom. I even re-cloned etc.

Btw, why the pom change? Reasoning:
- official keycloak quickstart is fine and has:
    ```sh
    $ grep logging deps.log
    [INFO] |  |  \- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
    [INFO] |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:compile
    [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
    [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
    ```
- this reproducer has (initially):
    ```sh
    $ mvn dependency:tree | grep logging
    [INFO] |  |  +- org.jboss.logging:jboss-logging:jar:3.3.2.Final:compile
    [INFO] |  |  +- org.jboss.logging:jboss-logging-annotations:jar:2.1.0.Final:compile
    [INFO] |  |  +- org.jboss.slf4j:slf4j-jboss-logging:jar:1.2.0.Final:compile
    [INFO] |  |  \- org.jboss.logging:commons-logging-jboss-logging:jar:1.0.0.Final:test
    ```

So this might have something to do with `commons-logging-jboss-logging`?

/cc @geoand (even if you wanted to stay out of this 😉 but maybe you have an immediate idea) @aloubyansky @jaikiran 

Would be great if someone else could try the steps I listed.

**Comment by famod** [comment] 2020-07-15 15:05
It is getting even weirder, I am not getting reproducible results.
I'll continue with this later and I hope until then the space-time rift has closed or someone else was able to make sense of it.

**Comment by jaikiran** [comment] 2020-07-16 03:25
My guess is that it's picking up a different logging implementation which doesn't support this construct. The reason why it might be flaky might have to do with some classloading aspects. I'll see if I can find some time on this, to investigate.

**Comment by geoand** [comment] 2021-07-27 12:15
Is this still an issue with the latest Quarkus versions?

**Comment by survivant** [comment] 2021-07-27 12:20
no idea because I opened that issue a year ago and they switch to Spring boot for testing keycloak.

**Comment by geoand** [comment] 2021-07-27 12:28
OK, I'll close it then. Feel free to reopen if it's still an issue

**Closed by geoand** 2021-07-27 12:28 UTC
Labels: area/logging, kind/bug
