### ISSUE TITLE
Quarkus returns 404 on OPTIONS request for the static resources

### ISSUE THREAD

**Issue by zenonwch** [quarkusio/quarkus#32696] opened 2023-04-17 16:21 UTC
### Describe the bug

I have static resources under the `/src/resources/META-INF/resources` folder (ex.: /src/resources/META-INF/resources/img/document.png.

When I make a GET call for the resource - Qurkus responds with 200 OK and returns the resource
But when I make an OPTIONS call for the same resource - Quarkus responds with 404 Not found

### Expected behavior

I expected 200 OK on the OPTIONS request for the static resources.

### Actual behavior

Quarkus responds with 404 Not found on the OPTIONS request for the static resources

### How to Reproduce?

1. Add a static resource to the sample Quarkus project under the `/src/resources/META-INF/resources` folder
2. Try to call this resource with GET and OPTIONS requests.

Sample of RestAssured @QuarkusTest
 - the following example returns image
```
RestAssured.given()
            .contentType(ContentType.JSON)
            .get("/img/document.png")
            .then()
            .statusCode(Matchers.equalTo(200))
```
- the following example failed with the error message [java.lang.AssertionError: 1 expectation failed. Expected status code <200> but was <404>.]
```
RestAssured.given()
            .contentType(ContentType.JSON)
            .options("/img/document.png")
            .then()
            .statusCode(Matchers.equalTo(200))
```

### Output of `uname -a` or `ver`

linux, macOS, Windows

### Output of `java -version`

openjdk 17.0.2 2022-01-18

### Quarkus version or git rev

2.16.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by geoand** [comment] 2023-04-18 06:55
Which extensions are you using?

**Comment by zenonwch** [comment] 2023-04-18 07:05
I don't clearly understand what you mean by extensions. But we use the following Quarkus dependencies:
io.quarkus:quarkus-core:2.16.5.Final
io.quarkus:quarkus-resteasy:2.16.5.Final
io.quarkus:quarkus-resteasy-jackson:2.16.5.Final
io.quarkus:quarkus-jackson:2.16.5.Final
io.quarkus:quarkus-smallrye-openapi:2.16.5.Final
io.quarkus:quarkus-smallrye-opentracing:2.16.5.Final
io.quarkus:quarkus-smallrye-metrics:2.16.5.Final
io.quarkus:quarkus-config-yaml:2.16.5.Final
io.quarkus:quarkus-kotlin:2.16.5.Final
io.quarkus:quarkus-rest-client:2.16.5.Final
io.quarkus:quarkus-oidc:2.16.5.Final
io.quarkus:quarkus-reactive-routes:2.16.5.Final
io.quarkus:quarkus-logging-gelf:2.16.5.Final
io.quarkus:quarkus-hibernate-validator:2.16.5.Final
io.quarkus:quarkus-narayana-jta:2.16.5.Final
io.quarkus:quarkus-smallrye-jwt:2.16.5.Final
io.quarkus:quarkus-smallrye-health:2.16.5.Final
io.quarkiverse.logging.logback:quarkus-logging-logback:0.13.0

and for tests
io.quarkus:quarkus-junit5-mockito:2.16.5.Final
io.quarkus:quarkus-test-security-jwt:2.16.5.Final
io.quarkus:quarkus-jdbc-h2:2.16.5.Final

**Comment by geoand** [comment] 2023-04-18 07:11
Close enough :)

Could you attach the sample application you are using please? It will make things a lot easier for us

**Comment by zenonwch** [comment] 2023-04-18 07:58
https://github.com/zenonwch/test-static-resource-options

**Comment by gsmet** [comment] 2023-04-18 09:51
I think I recall we enabled `GET` and `HEAD` for static resources. We might have to also enable `OPTIONS`.

(but that's a very vague recollection so I might be mistaken)

**Comment by geoand** [comment] 2023-04-18 09:54
Very likely, however I don't remember at all. I'll have a look later on.

**Comment by gsmet** [comment] 2023-04-18 10:02
That would be it I think: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/StaticResourcesRecorder.java#L112-L115

**Comment by gsmet** [comment] 2023-04-18 10:31
Yeah, I'll have a look later today.

**Comment by zenonwch** [comment] 2023-04-18 11:25
@gsmet maybe you can provide me with some workaround for the 2.16.5.Final version?

**Comment by geoand** [comment] 2023-04-18 11:29
There isn't one

**Comment by zenonwch** [comment] 2023-04-18 11:42
But as I see from the code source - there are no restrictions in the StaticResourcesRecorder for 2.16.5.Final version
<img width="752" alt="image" src="https://user-images.githubusercontent.com/17174214/232766392-c67fa82f-5217-4753-a3fd-35bdb6b83f45.png">

**Comment by geoand** [comment] 2023-04-18 11:44
You are right... Let me take a closer look

**Comment by geoand** [comment] 2023-04-18 11:45
By the way, I still cannot access the reproducer link you provided. Please make sure it's not a private repo

**Comment by zenonwch** [comment] 2023-04-18 11:49
Oops, sorry, my fault. Pls, try now.

**Comment by geoand** [comment] 2023-04-18 11:55
It turns out this is a by design in Vert.x see 

https://github.com/vert-x3/vertx-web/blob/4.3.7/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java#L170 

and

https://github.com/vert-x3/vertx-web/blob/4.4.1/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/StaticHandlerImpl.java#L170

So there is not much we can do in Quarkus. 

@cescoffier do we want to handle this in Vert.x or should this be closed as `won't fix`?

**Comment by zenonwch** [comment] 2023-04-18 12:37
Thanks @geoand, I found [this](https://github.com/vert-x3/vertx-web/issues/2193) issue in the vertx-web project and it is still in Open status.

**Comment by geoand** [comment] 2023-04-18 12:38
Cool, let's close this one then

**Closed** 2023-04-18 12:38 UTC
Labels: kind/bug, area/vertx, triage/upstream

**Comment by zenonwch** [comment] 2023-04-19 05:51
> That would be it I think: https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/StaticResourcesRecorder.java#L112-L115

@gsmet I hope you will add OPTIONS to the accept method despite the issue being closed )).
