### ISSUE TITLE
CDI Inheritance: scope annotation of superclass ignored on subclass

### ISSUE THREAD

**Issue by tosix1988** [quarkusio/quarkus#7726] opened 2020-03-10 11:48 UTC
First of all, thanks a lot guys for Quarkus, it's really awesome :). However, I came across a following issue and I need your help:

**Describe the bug**
When extending a class that is annotated with CDI scope anntation, such as `@Dependent` or `@RequestScoped`, the scope is not inherited from the superclass. Note the relevant section of CDI specification: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#inheritance, section 4.1, notably this point:
- If X is annotated with a scope type Z then Y inherits the annotation if and only if Z declares the `@Inherited` meta-annotation and neither Y nor any intermediate class that is a subclass of X and a superclass of Y declares a scope type. (This behavior is different to what is defined in the Java Language Specification.)

Note that both `@Dependent` and `@RequestScoped` are `@Inherited`.

Is this an expected behaviour, or a limitation of CDI implementation that Quarkus uses (or I have misunderstood the CDI spec, which is also very likely :))?

**To Reproduce**
1. Define following types:
```java
@Dependent
public abstract class SuperClass { ... }
```
and a type that extends it (without any scope annotation)
```java
public class SubClass extends SuperClass { ... }
```

2. Inject the SubClass into another type
```java
@RequestScoped
public class Resource {
    @Inject
    SubClass bean;
}
```
3. Application deployment fails with following exception:
```
org.junit.jupiter.api.extension.TestInstantiationException: TestInstanceFactory [io.quarkus.test.junit.QuarkusTestExtension] failed to instantiate test class [org.acme.quickstart.ResourceTest]: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.quickstart.SubClass and qualifiers [@Default]
	- java member: org.acme.quickstart.Resource#bean
	- declared on CLASS bean [types=[java.lang.Object, org.acme.quickstart.Resource], qualifiers=[@Default, @Any], target=org.acme.quickstart.Resource]
	at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:879)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:231)
	at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:117)
	at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:272)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:915)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:279)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:2011)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1535)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1426)
	at java.lang.Thread.run(Thread.java:748)
	at org.jboss.threads.JBossThread.run(JBossThread.java:479)
Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.quickstart.SubClass and qualifiers [@Default]
	- java member: org.acme.quickstart.Resource#bean
	- declared on CLASS bean [types=[java.lang.Object, org.acme.quickstart.Resource], qualifiers=[@Default, @Any], target=org.acme.quickstart.Resource]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:416)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:223)
	... 14 more
```
**Additional context**
I am using Quarkus 1.2.1.Final.

**Comment by geoand** [comment] 2020-03-10 12:00
cc @manovotn @mkouba

**Comment by mkouba** [comment] 2020-03-10 12:19
@tosix1988 Scope annotations are inherited. However, `SubClass` must be annotated with a bean defining annotation in order to be discovered because Quarkus only supports `bean-discovery-mode=annotated` as described in [the docs](https://quarkus.io/guides/cdi-reference#bean_discovery).

The set of bean defining annotations includes all scopes, stereotypes, `@Interceptor` and `@Decorator`. In Quarkus, classes that declare producers and observers are also discovered. In addition, some extensions also define BDAs, such as `@Path`, `@Scheduled` and `@Route`.

**Comment by mkouba** [comment] 2020-03-10 12:33
Closing - works as designed.

**Closed by mkouba** 2020-03-10 12:33 UTC
Labels: kind/bug

**Comment by azurvii** [comment] 2024-08-11 04:24
Both `Dependent` and `ApplicationScoped` are annotated with `@Inherited`. According to the [javadoc](https://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html), "working as signed" should allow the OP's case to work. To me, the documentation is directly contradicting the code.

Not here to argue the CDI spec, but could there be at least an option to allow inheriting the scopes from super classes/interfaces? e.g. by an additional annotation like `@AllowInheritance` (not a real annotation, just a hypothetical suggestion) on the base class/interface? I think this should not introduce unsolvable ambiguities, since Quarkus already supports `@Priority`, `@Default`, etc.

One use case is to support integrating code generators like [AutoFactory](https://github.com/google/auto/tree/main/factory) in the the dependency injection context for assisted injection.

Some background: I jumped a few issues to this one, initially from https://github.com/quarkusio/quarkus/issues/39730. It would be good to have a buit-in / plugin to support assisted inject. But for now, I am looking for a workaround. I used AutoFactory quite a lot, and tried to use that directly with Quarkus. It throws `UnsatisfiedResolutionException`, since the factories generated are not annotated with Quarkus scopes. AutoFactory does not support adding annotations on the generated factory, but allows adding extending / implementing a super class/interface. This is where this feature could help.

**Comment by manovotn** [comment] 2024-08-12 08:21
@azurvii IIUIC, you may be mixing two different cases here. Inheritance and discovery.

The original question was a matter of discovery - Quarkus will not discover a bean without any bean defining annotation (what's called `annotated` discovery mode) or without a producer or an observer.

Then there is annotation inheritance which is defined as working based off of superclasses but not interfaces. However, CDI only performs that for a set of discovered beans. Mind that even the `@Inherited` javadoc mentions that:

> Note that this meta-annotation type has no effect if the annotated type is used to annotate anything other than a class. Note also that this meta-annotation only causes annotations to be inherited from superclasses; annotations on implemented interfaces have no effect.

So even with your suggestion, you'd still have the same problem because the discovery of your classes would not happen.
What you might want to look into instead is explicitly registering your generated classes as beans. You could either use CDI's `BuildCompatibleExtension` or look into Quarkus APIs for something like `AdditionalBeanBuildItem`. Note that you can then process those classes and tweak all of their annotations such as scopes, qualifiers etc.

Here are some potentially useful links for that:
* https://quarkus.io/guides/cdi-integration#additional_bean_build_item
* https://jakarta.ee/specifications/cdi/4.1/jakarta-cdi-spec-4.1#bce_discovery

**Comment by azurvii** [comment] 2024-08-12 14:39
I'm not sure what is the point of separating inheritance and discovery. Yes, I'm "mixing" them. And that is the point.

If you look at the original request, `SuperClass` is annotated with `@Dependent`. `SuperClass` is a class, not an interface. `@Dependent` is annotated with `@Inherited`. `SubClass` extends `SuperClass` but is not injectable since it's not directly annotated with a scope. *This is the issue.* @mkouba linked the reference indicating this is expected behavior. I said the doc is contradicting the `@Inherited` contract. Do help to enlighten me if I missed anything here.

What I suggested is to change the behavior, and to honor `@Inherited`, or at least to offer an option, to make the bean discovery happen for `SubClass`. And I suggested to enhance `@Inherited` to include interfaces as well, if possible. (I have not written many annotation processors, and not sure if that's feasible / easily achievable.)

**Comment by manovotn** [comment] 2024-08-12 15:56
> I'm not sure what is the point of separating inheritance and discovery. Yes, I'm "mixing" them. And that is the point.

Sorry but they are not the same; let me try to elaborate a little.
CDI differentiates between discovery modes based on which it then performs type discovery. Once a given type is discovered, CDI container will process it, including scanning annotations on the type and in its hierarchy. 

What you ask for (or what the original issue here assumes) is very close to an `all` discovery mode - a mode in which you process every single class in the deployment and if it is a viable candidate, you turn it into a bean. This is an option in CDI Full implementations (for instance Weld) but CDI Lite implementation (Quarkus/ArC) doesn't have this mode.
The `all` mode is obviously much more taxing on the amount of processing as you are attempting to process almost everything. It also creates a lot of beans that aren't used or even meant to become beans, they just happen to meet the criteria to become beans.

Here are some spec links for the above (using links for CDI Full):
* https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#bean_archive_full
* https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0#type_discovery_steps_full

> And I suggested to enhance `@Inherited` to include interfaces as well, if possible. (I have not written many annotation processors, and not sure if that's feasible / easily achievable.)

That would go against the `@Inherited` javadoc contract which is, as far as I can tell, why CDI chose not to do that.
Otherwise, it would be technically possible.

**Comment by azurvii** [comment] 2024-08-12 17:37
Lemme just confirm again that what you described is what I am asking for -- to make inherited scopes injectable. I know this is not available in ArC, and it is the ask.

This is obviously more taxing. But with [bean removal](https://quarkus.io/blog/unused-beans/), IIUIC, it should not affect runtime performance much, if at all. I don't know how much degradation it brings for build time. But I would bet it's not dramatically much. Thus I think at least an option would be useful.

**Comment by manovotn** [comment] 2024-08-13 08:47
> Lemme just confirm again that what you described is what I am asking for -- to make inherited scopes injectable. I know this is not available in ArC, and it is the ask.

Yes, I was just trying to explain it is not "just" inheriting scopes and it's against spec forcing us to hide it behind a switch (also due to the TCKs I'd say). Otherwise, I get what you ask for.

BTW is the approach I [mentioned earlier](https://github.com/quarkusio/quarkus/issues/7726#issuecomment-2283367508) with registering those generated classes a viable option for you?

Anyhow, I'll let @mkouba and @Ladicek voice their opinion here but personally I don't think implementing a `[pseudo-]all` discovery mode is what we want.

**Comment by azurvii** [comment] 2024-08-13 12:04
> BTW is the approach I [mentioned earlier](https://github.com/quarkusio/quarkus/issues/7726#issuecomment-2283367508) with registering those generated classes a viable option for you?

Thanks. I am aware of the means but have not tried. I believe it should work. But one main reason for me to use Quarkus, AutoFactory, etc. instead of vertx and separate libs, manual factories is convenience. IMHO, if that's the only option, I may prefer writing factories manually instead of registering them manually. Arguable, but I think that's cleaner and less coupled.

**Comment by Ladicek** [comment] 2024-08-14 06:46
I agree we don't want an "all"-ish discovery mode. It really depends on the application, but it may increase the bean archive size by an order of magnitude or more.

My personal opinion is that you could/should write a simple Quarkus extension that takes `CombinedIndexBuildItem`, finds all subclasses of the superclass, and emits `AdditionalBeanBuildItem` for each of them. If there's just a single superclass, that should be fairly easy and should work everywhere -- but I don't really know how your code looks like.
