### ISSUE TITLE
Dev UI2 show wrong java version

### ISSUE THREAD

**Issue by JackyAnn** [quarkusio/quarkus#32956] opened 2023-04-27 13:00 UTC
### Describe the bug

q/dev-ui/io.quarkus.quarkus-info/information
show wrong information about java version
shows wrong java version, always shows version 11.0.17

![image](https://user-images.githubusercontent.com/3381801/234868925-34f57ea8-1e0b-4543-bfa6-dd34faca6e8f.png)

raw:
![image](https://user-images.githubusercontent.com/3381801/234869071-4df357b0-78a0-4d4c-86e8-50bf51ea192a.png)

### Output of `uname -a` or `ver`

Darwin

### Output of `java -version`

Java(TM) SE Runtime Environment (build 20+36-2344) Java HotSpot(TM) 64-Bit Server VM (build 20+36-2344, mixed mode, sharing) Jacky@jackydeMacBook-Pro ~ % 

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 ------------------------------------------------------------ Gradle 8.1.1 ------------------------------------------------------------  Build time:   2023-04-21 12:31:26 UTC Revision:     1cf537a851c635c364a4214885f8b9798051175b  Kotlin:       1.8.10 Groovy:       3.0.15 Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021 JVM:          20 (Oracle Corporation 20+36-2344) OS:           Mac OS X 13.3.1 x86_64

**Comment by phillip-kruger** [comment] 2023-04-27 13:06
Seems like the is name is also wrong ? I'll have a look

**Comment by geoand** [comment] 2023-04-27 13:08
@phillip-kruger doesn't it get the information from the `quarkus-info` extension?

**Comment by JackyAnn** [comment] 2023-04-27 13:09
@phillip-kruger yes, the system is Mac os x

**Comment by phillip-kruger** [comment] 2023-04-27 13:11
@JackyAnn if you have a small reproducer, that would be great

**Comment by geoand** [comment] 2023-04-27 13:12
> @geoand yes

Then how is it wrong, I don't understand :)

**Comment by phillip-kruger** [comment] 2023-04-27 13:17
No clue, will have to look and see. But that will only be tomorrow...

**Comment by JackyAnn** [comment] 2023-04-27 23:56
I also have this problem on my fedora system, ui always shows the same java version and system info

**Comment by phillip-kruger** [comment] 2023-04-28 12:40
OK. This is the weirdest bug I have seen in a long time :) . I have no idea how this can even happen, maybe @gsmet can help. Here goes:

1) this functionality has been added with this PR: https://github.com/quarkusio/quarkus/pull/32708/files#diff-67cb989558ebc0248001364fc352ef962c7d76fd6658763a7fbb05f935aa37d3 
Note line 96 where we show the Java version

2) this code is the same in current main and in the 3.0.1.Final tag (see https://github.com/quarkusio/quarkus/blob/2c6c42bba6d19a8d65f7a7b3a627b23d3d1e7270/extensions/info/deployment/src/main/resources/dev-ui/qwc-info.js#L97 and https://github.com/quarkusio/quarkus/blob/eef6e01e5d356c31d90af160b91ff08db32d533f/extensions/info/deployment/src/main/resources/dev-ui/qwc-info.js#L97)

3) the above code is correct and works fine. You can also NOT recreate the issue when changing the reproducer provided to 999-SNAPSHOT

So, the main branch is fine, and it seems line 3.0.1 is also fine. However (here is where it gets weird)

4) Go to https://repo1.maven.org/maven2/io/quarkus/quarkus-info-deployment/3.0.1.Final/

These are the artifacts in maven central for 3.0.1

If you download and open the artifact(https://repo1.maven.org/maven2/io/quarkus/quarkus-info/3.0.1.Final/quarkus-info-3.0.1.Final.jar), and look at the qwc-info.js file you will see that is another version !! With hardcoded values ...

Now, I recall that I hardcoded the values initially just to build the page, and then I replaced it with vars... but how that got to maven central I have no idea. The PR is correct, and here another weird one, the source in maven central is correct too... See the source jar (https://repo1.maven.org/maven2/io/quarkus/quarkus-info-deployment/3.0.1.Final/quarkus-info-deployment-3.0.1.Final-sources.jar)

So, it looks like something funky happened with the Ci build maybe ? (@gsmet @geoand ??)

Theoretically, this will be fixed no the next release then ?

**Comment by geoand** [comment] 2023-04-28 13:04
@phillip-kruger and I talked about this one and we have a fix.

**Comment by phillip-kruger** [comment] 2023-04-28 13:04
thanks @geoand . This is on my list of weirdest bugs ever ....

**Comment by geoand** [comment] 2023-04-28 13:06
Thanks for digging in deep!

**Closed** 2023-05-02 11:14 UTC
Labels: kind/bug, area/kotlin, area/dev-ui
