### ISSUE TITLE
Swagger-UI path is serving Swagger's YAML

### ISSUE THREAD

**Issue by aesteve** [quarkusio/quarkus#4690] opened 2019-10-21 08:24 UTC
**Describe the bug**
From 0.24.0 on, when targeting `/swagger-ui`, I'm receiving a YAML file.

**Expected behavior**
This endpoint is configured to serve HTML resources from Swagger's UI, not the Swagger YAML definition.
As in versions 0.21.2 or 0.22.0 (or myabe 0.23.0, couldn't get it running), display Swagger's HTML resources, not the YAML definition

**Actual behavior**
The YAML definition (in the configuration below `/swagger`) is returned instead.

**To Reproduce**
Apply the configuration below, and simply run `quarkusDev`

**Configuration**
```properties
# OpenAPI / Swagger
quarkus.smallrye-openapi.path=/swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui
```

**Environment (please complete the following information):**
 - Quarkus version or git rev: From 0.24.0 (working in 0.22.0, broken in versions>=0.24.0, can't test with quarkus on 0.23.0 because of another issue with `java.util.Collections$UnmodifiableRandomAccessList`")

**Comment by gsmet** [comment] 2019-10-21 08:28
This is a duplicate of https://github.com/quarkusio/quarkus/issues/4613 .

It will be fixed soon but in the meantime, just publish the OpenAPI on something not `/swagger`. The default will work fine.

**Comment by gsmet** [comment] 2019-10-21 08:28
Closing as duplicate.

**Closed by gsmet** 2019-10-21 08:28 UTC
Labels: bug, duplicate

**Comment by aesteve** [comment] 2019-10-21 08:31
Sorry about the duplicate and thanks for the workaround.
