### ISSUE TITLE
Generate the missing no-args constructor for normal scoped CDI beans

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2469] opened 2019-05-16 16:57 UTC
This should work

```
@ApplicationScoped
public class MyBean {
    private EntityManager em;

    @Inject
    public MyBean( EntityManager em) {
        this.em = em;
    }

    public EntityManager em() {
        return em;
    }
}
```

but I have to add the default constructor

```
@ApplicationScoped
public class MyBean {
    private EntityManager em;

    MyBean() {

    }

    @Inject
    public MyBean( EntityManager em) {
        this.em = em;
    }

    public EntityManager em() {
        return em;
    }
}
```

Can we simply add it @mkouba

**Comment by geoand** [comment] 2019-05-18 07:27
:+1: for this! We already do something similar for the RESTEasy classes so further simplifying things would be great from a user perspective!

@mkouba if you have too much on your plate I can take this

**Comment by mkouba** [comment] 2019-05-18 15:15
@geoand I'm working on it and even have a working prototype but I didn't know we have something for RESTEasy. Could you point me to the relevant sources?

**Comment by geoand** [comment] 2019-05-18 15:18
The CDI case is probably more complex, but in the RESTEasy case all we did was this: https://github.com/quarkusio/quarkus/blob/74f18b366aed381dd25588fd454c362e702bde38/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L366

**Comment by mkouba** [comment] 2019-05-20 07:36
@geoand Thanks! The CDI case is also simple but now I wonder how to avoid "bytecode transformer conflicts" - resource classes are also beans and so we should not generate the constructor twice. Jandex index does not help here. Any idea?

**Comment by geoand** [comment] 2019-05-20 07:43
Ah yes... We do have a disconnect here that I guess would arise sooner or later... But in this case Resource classes should be `@Singleton` shoouldn't they? Meaning that no extra constructor would be needed on the CDI side right?
The extra constructor was only added to make RESTEasy happy (or at least that is what I understood from the discussion I had on the RESTEasy JIRA)

**Comment by mkouba** [comment] 2019-05-20 07:58
You could annotate the resource with `@RequestScoped` or `@ApplicationScoped`... But you're right that CDI does not require proxies for `@Singleton`.

**Comment by geoand** [comment] 2019-05-20 08:02
I think we have created the RESTEasy extra constructor creation in a way that wouldn't cause a problem. Specifically, we only create the constructor if the default (Singleton) scope is used (see [here](https://github.com/quarkusio/quarkus/blob/74f18b366aed381dd25588fd454c362e702bde38/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L383)).
Do you think this is enough to not be a problem for the CDI side of things?

**Comment by mkouba** [comment] 2019-05-20 08:07
This should be ok. I'll send an email to quarkus-dev about resolving the possible conflicts though.

**Comment by geoand** [comment] 2019-05-20 08:07
Makes sense :+1:

**Comment by mkouba** [comment] 2019-05-20 11:13
@emmanuelbernard PR sent. The constructor is not generated for more complex use cases (e.g. if your bean extends another bean that does not declare a no-args constructor). It should work in simple cases though.

I'd like to write a short blog post on quarkus.io about all those nice little improvements we did around CDI...

**Comment by emmanuelbernard** [comment] 2019-05-20 15:26
@mkouba +1 for the blog :)
Also if you need a shared non  duplicated change, the pattern we want to promote is a shared extension that exposes BuildItems that can be generated by CDI and RESTEAsy. In this case it would be a default constructor generator. Would that work / be better than what you guys did.

**Comment by mkouba** [comment] 2019-05-20 15:53
Ok, so instead of a custom transformer we could have a specialized transformer. That would probably work.

**Comment by emmanuelbernard** [comment] 2019-05-20 15:56
@mkouba to be clear, I am just asking if that would be a better design. I don't have skin in the game.

**Comment by mkouba** [comment] 2019-05-21 06:54
Ah, I was missing the question mark ;-). Anyway, it is probably a better design but as usual - more generic design is harder to implement. So I would propose to create a new issue to address this problem. @geoand WDYT?

**Closed** 2019-05-21 08:56 UTC
Labels: component:arc, enhancement, user experience

**Comment by hprange** [comment] 2019-09-17 19:25
I'm having an issue while running tests annotated with `@QuarkusTest` using Maven that seems to be related to this issue. The tests fail with the following message:

```
Caused by: java.lang.NoSuchMethodError: com.acme.MyBean: method <init>()V not found
```

The same tests work if I add a no-args constructor to `com.acme.MyBean` class. BTW, `MyBean` doesn't extend other types and it's injected into one of my REST resources.

Curiously, everything works fine if I run the `quarkus:dev` goal or run the tests inside Eclipse.

Should I open another issue?

**Comment by mkouba** [comment] 2019-09-18 07:14
@hprange Yes pls. File a new issue. And if possible add a minimal reproducer app/test.
