### ISSUE TITLE
Kafka consume stopped without any exception log

### ISSUE THREAD

**Issue by liuzhaozhao** [quarkusio/quarkus#27265] opened 2022-08-12 08:42 UTC
### Describe the bug

This problem was reported in the smallrye-reactive-messaging open source project, but the activity is not as good as that of quarkus (slow response), we may have it once every 1-2 days in production, and the node must be restarted to solve it. I hope the quarkus team can help follow up on this question.

https://github.com/smallrye/smallrye-reactive-messaging/issues/1811#issuecomment-1210126919

### Quarkus version or git rev

2.7.6.Final

**Comment by ozangunalp** [comment] 2022-08-12 08:56
@liuzhaozhao I've been looking at your issue to reproduce it and get back to you on the upstream project.

**Comment by liuzhaozhao** [comment] 2022-08-12 09:03
Okay, thanks

**Comment by privetpoka** [comment] 2022-09-08 11:43
Hello. I am experiencing similar issue as @liuzhaozhao described. It happened once I update quarkus version from 2.9.2 to 2.11.2 (also with 2.12.0).
Any idea about how to overcome this issue?

**Comment by ozangunalp** [comment] 2022-09-12 11:48
Hi, I tried to reproduce this without success a couple of weeks ago but was sidetracked. 
I tried to do something similar to this config: https://github.com/smallrye/smallrye-reactive-messaging/issues/1811#issuecomment-1207215229 , but couldn't reproduce hanging consumption with 100k messages.

I know it is hard in these cases but a reproducer would be awesome.

**Comment by ozangunalp** [comment] 2022-09-21 08:41
I believe I found what the problem was, and fixed with https://github.com/smallrye/smallrye-reactive-messaging/pull/1895. It is released on reactive messaging 3.19.1 and will arrive in Quarkus shortly

**Comment by cescoffier** [comment] 2022-09-25 16:16
closed by https://github.com/quarkusio/quarkus/pull/28117

**Closed by cescoffier** 2022-09-25 16:16 UTC
Labels: kind/bug, area/kafka
