### ISSUE TITLE
@RolesAllowed causes Resource method returning CompletionStage to ignore exception mapping 

### ISSUE THREAD

**Issue by LoveFeelings** [quarkusio/quarkus#21814] opened 2021-11-30 12:11 UTC
### Describe the bug

This issue is related to #20979. Looks to have been working in quarkus 2.3.2.Final, but the bug was interduced in quarkus 2.4.0.Final and is still present in quarkus 2.5.0.Final. Note that the code is fork'ed from @antoniomacri :  [antoniomacri/quarkus-completionstage-rolesallowed](https://github.com/antoniomacri/quarkus-completionstage-rolesallowed).

Consider the following method:

```
@RolesAllowed("protected-role")
@Path("/")
public class SampleResource {
    @POST
    @Path("protected")
    @Consumes(MediaType.APPLICATION_JSON)
    public CompletionStage<Response> getProtected(final Content data) throws Exception {
        return CompletableFuture.completedFuture(Response.ok().build());
    }
}
```

And consider that `Content` object's field `name` must not be null:

```
@Getter
@Setter
public class Content {
    @NotNull
    private String name;

}
```

When `getProtected` is called where  `Content` object's field `name` is `null`, an `unhandledAsynchronousException` is thrown.
It is expected that exceptions are thrown in completionStages (in this case the `@Valid` throws the exception) and that these exceptions are correctly mapped. This do not look to be the case with `RolesAllowedInterceptor.java:29` which calls the SecurityHandler.handle method(see below). It looks like the exception mapped is ignored on line 39: https://github.com/quarkusio/quarkus/blob/31cacccf69e3d913ff4244c45b6d0ed5f3043134/extensions/security/runtime/src/main/java/io/quarkus/security/runtime/interceptor/SecurityHandler.java#L25-L49

### Expected behavior

As the request contains incomplete content, it is expected to receive a CompletionStage with a response with 400 Bad Request. And that the exception mapping is not ignored.

### Actual behavior

An unhandledAsynchronousException from resteasy with the return code 500 is returned.

In a QuarkusTest shows this error:
AM org.jboss.resteasy.core.SynchronousDispatcher unhandledAsynchronousException
ERROR: RESTEASY002020: Unhandled asynchronous exception, sending back 500

### How to Reproduce?

Find code to reproduce [here](https://github.com/LoveFeelings/quarkus-completionstage-rolesallowed)

### Output of `java -version`

java 11

### Quarkus version or git rev

2.5.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven 3.8.1

**Comment by geoand** [comment] 2021-11-30 13:11
This is a duplicate of https://github.com/quarkusio/quarkus/issues/21679 and has already been fixed in main (the fix will be available in `2.5.1.Final`)

**Closed by geoand** 2021-11-30 13:11 UTC
Labels: kind/bug, triage/needs-triage
