### ISSUE TITLE
 Native gRPC Client  is failing to send a message to GRPC server 

### ISSUE THREAD

**Issue by u650080** [quarkusio/quarkus#30293] opened 2023-01-10 19:27 UTC
### Describe the bug

Native gRPC client  is failing to send a message  to gRPC server, this is the way to reproduce this problem and also I attached zip file which has both projects: 

1- Copy grpc-plain-text-quickstart to grpc-plain-text-quickstart-client (a new project)
2- Remove HelloWorldEndpoint.java from the project grpc-plain-text-quickstart and build native
3- Remove HelloWorldService.java from the project grpc-plain-text-quickstart-client and build native
4- Run GRPC server grpc-plain-text-quickstart ( use different http port)
5- Run GRPC Client grpc-plain-text-quickstart-client
6- Use curl to trigger grpc client to talk to the grpc server : it is failing and I already posted these exceptions from GRPC server and GRPC client.
7- I used grpcurl to GRPC server is working .

This is an error in server side:
```
2023-01-05 17:51:05,143 SEVERE [io.grp.int.SerializingExecutor] (vert.x-eventloop-thread-0) Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable@2366db6e: io.grpc.StatusRuntimeException: INTERNAL: Invalid protobuf byte sequence
at io.grpc.Status.asRuntimeException(Status.java:526)
at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:218)
at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:118)
at io.grpc.MethodDescriptor.parseRequest(MethodDescriptor.java:307)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailableInternal(ServerCallImpl.java:330)
at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.messagesAvailable(ServerCallImpl.java:313)
at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1MessagesAvailable.runInContext(ServerImpl.java:834)
at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
at io.vertx.grpc.VertxServer$ActualServer.lambda$null$0(VertxServer.java:91)
at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.lang.Thread.run(Thread.java:833)
at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:704)
at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: com.google.protobuf.InvalidProtocolBufferException: Protocol message contained an invalid tag (zero).
at com.google.protobuf.CodedInputStream$ArrayDecoder.readTag(CodedInputStream.java:633)
at examples.HelloRequest.<init>(HelloRequest.java:46)
at examples.HelloRequest$1.parsePartialFrom(HelloRequest.java:499)
at examples.HelloRequest$1.parsePartialFrom(HelloRequest.java:495)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:86)
at com.google.protobuf.AbstractParser.parseFrom(AbstractParser.java:48)
at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parseFrom(ProtoLiteUtils.java:223)
at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.parse(ProtoLiteUtils.java:215)
The client side :
2023-01-05 17:51:05,144 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /hello/blocking/World failed, error id: 6015b74f-8f6a-4953-a581-8251c378f79f-1: io.grpc.StatusRuntimeException: UNKNOWN
at io.grpc.stub.ClientCalls.toStatusRuntimeException(ClientCalls.java:271)
at io.grpc.stub.ClientCalls.getUnchecked(ClientCalls.java:252)
at io.grpc.stub.ClientCalls.blockingUnaryCall(ClientCalls.java:165)
at examples.GreeterGrpc$GreeterBlockingStub.sayHello(GreeterGrpc.java:147)
at io.quarkus.grpc.examples.hello.HelloWorldEndpoint.helloBlocking(HelloWorldEndpoint.java:25)
at io.quarkus.grpc.examples.hello.HelloWorldEndpoint$quarkusrestinvoker$helloBlocking_316ecf2888a019611a7fb9e55314f0a38542f3be.invoke(Unknown Source)
at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:108)
at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:140)
at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:555)
at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
at java.base@11.0.17/java.lang.Thread.run(Thread.java:834)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
```

[grpc-client-problem.zip](https://github.com/quarkusio/quarkus/files/10386149/grpc-client-problem.zip)

### Output of `uname -a` or `ver`

Linux labdev75 3.10.0-1160.76.1.el7.x86_64 #1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

11.0.17+10-LTS-jvmci-22.3-b07

### GraalVM version (if different from Java)

GraalVM 22.3.0 Java 11 EE

### Quarkus version or git rev

2.14.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.6.3

**Comment by musufyian** [comment] 2023-01-11 22:57
How can I assign this issue myself to solve it ?

**Comment by cescoffier** [comment] 2023-01-12 07:01
@musufyian Sure, you can have a look. 
I've assigned it to Ales, who may provide a few hints. 

I didn't look at the reproducer yet, so, that would be the first place to check: is the reproducer correct.

**Comment by cescoffier** [comment] 2023-01-19 14:41
I would need some guidance to reproduce the problem. 

Here is what I did:
- built the 2 apps into native
- launched the first one with `./target/grpc-plain-text-quickstart-1.0.0-SNAPSHOT-runner`
- launched the second one with `./target/grpc-plain-text-quickstart-1.0.0-SNAPSHOT-runner -Dquarkus.http.port=8082`
- called the client service (which called the other service using gRPC): `http :8082/hello/mutiny/foo`

I also called the gRPC service directly using: ` grpcurl -plaintext localhost:9000 helloworld.Greeter.SayHello`

Everything was working as expected.

**Comment by cescoffier** [comment] 2023-01-19 14:42
BTW, I was using GraalVM 22.3 for Java 17.

**Comment by u650080** [comment] 2023-01-19 21:07
I used GraalVM 22.3 java 17 and I can reproduce same problem. 
[1/7] Initializing...   
 Version info: 'GraalVM 22.3.0 Java 17 EE'
 Java version info: '17.0.5+9-LTS-jvmci-22.3-b07'
 C compiler: gcc (redhat, x86_64, 8.3.1)
 Garbage collector: Serial GC
 4 user-specific feature(s)
 - com.oracle.svm.thirdparty.gson.GsonFeature
 - io.quarkus.runner.Feature: Auto-generated class by Quarkus from the existing extensions
 - io.quarkus.runtime.graal.DisableLoggingFeature: Disables INFO logging during the analysis phase for the [org.jboss.threads] categories
 - io.quarkus.runtime.graal.ResourcesFeature: Register each line in META-INF/quarkus-native-resources.txt as a resource on Substrate VM
Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of Unsafe.objectFieldOffset(Field) is not a constant field., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store. 
[2/7] Performing analysis...  [*********]                                                               (41.4s @ 1.94GB)
  12,086 (88.83%) of 13,605 classes reachable
  17,795 (59.97%) of 29,674 fields reachable
  66,764 (57.43%) of 116,246 methods reachable
     476 classes,   133 fields, and 2,604 methods registered for reflection
      63 classes,    68 fields, and    55 methods registered for JNI access
       4 native libraries: dl, pthread, rt, z
[3/7] Building universe...                                                                               (6.1s @ 4.08GB)
[4/7] Parsing methods...      [***]                                                                      (6.4s @ 3.72GB)
[5/7] Inlining methods...     [***]                                                                      (1.9s @ 1.04GB)
[6/7] Compiling methods...    [**********]                                                             (107.5s @ 1.64GB)
[7/7] Creating image...                                                                                  (8.0s @ 3.54GB)
  30.23MB (58.20%) for code area:    36,377 compilation units
  21.40MB (41.20%) for image heap:  322,718 objects and 12 resources
 321.69KB ( 0.60%) for other data
  51.95MB in total

**Comment by cescoffier** [comment] 2023-01-20 06:33
Are you sure you use the command I posted? 
I've retried again, and no problem.

**Comment by u650080** [comment] 2023-01-20 23:48
> Are you sure you use the command I posted? I've retried again, and no problem.

yes I follow same as you, what platform are you using ?

**Comment by cescoffier** [comment] 2023-01-22 09:02
I'm on Mac, but that should not matter.

**Comment by u650080** [comment] 2023-01-23 12:54
please try on redhat  because there are big different between mac and linux redhat .

**Comment by cescoffier** [comment] 2023-01-23 13:25
I ran the same test on my Linux box (Fedora, I do not have RHEL) - no problem.

**Comment by u650080** [comment] 2023-01-23 13:58
what is your suggestion to solve this problem?

**Comment by cescoffier** [comment] 2023-01-23 15:00
I need a way to reproduce it. So, if you can build a reproducer (single app / maven) reproducing it, it would be really great.

**Comment by u650080** [comment] 2023-01-23 15:17
I tried on Mac and it works , I have 2 excusable (grpc server and grpc client) from my build machine(RHEL), how can I send those files to you because there is limitation on attachment size.

**Comment by u650080** [comment] 2023-01-23 15:28
I attached for client
[Uploading grpc-client-exec.zip…]()

**Comment by u650080** [comment] 2023-01-23 15:29
I attached for server:
[grpc-server-exec.zip](https://github.com/quarkusio/quarkus/files/10481153/grpc-server-exec.zip)

**Comment by cescoffier** [comment] 2023-01-23 18:23
Can you create a single app?

**Comment by cescoffier** [comment] 2023-01-23 18:23
I need the sources - not the binaries

**Comment by u650080** [comment] 2023-01-23 20:20
> Can you create a single app?

there is a GRP server app and GRPC client app ..  how can be one app?!

**Comment by u650080** [comment] 2023-01-23 20:21
> I need the sources - not the binaries

the source already attached in first message([grpc-client-problem.zip](https://github.com/quarkusio/quarkus/files/10386149/grpc-client-problem.zip)

**Comment by u650080** [comment] 2023-01-23 20:27
> Can you create a single app?
I uploaded again..

[grpc-client-exec.zip](https://github.com/quarkusio/quarkus/files/10483388/grpc-client-exec.zip)

**Comment by u650080** [comment] 2023-01-23 23:42
I tested with RHEL 8 is working (Linux redh8 4.18.0-372.16.1.el8_6.x86_64 #1 SMP Tue Jun 28 03:02:21 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux
) but not with 7.9(3.10.0-1160.76.1.el7.x86_64 https://github.com/quarkusio/quarkus/pull/1 SMP Tue Jul 26 14:15:37 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux).

**Comment by u650080** [comment] 2023-01-24 14:58
The problem is GraalVM EE , I tried graalVM EE on Mac (M1) and I can reproduce this problem. I used GraalVM CE on RHEL 8/7.9 is working. please use graaVM EE to  reproduce this problem.

**Comment by cescoffier** [comment] 2023-01-25 07:34
I don't have GraalVM EE (I'm mostly using mandrel). Also, if it's a GraalVM EE issue, better to report it to the GraalVM team.

**Comment by wirthi** [comment] 2023-02-09 16:09
What are the correct commands to run client and server _without_ native? I tried with `mvn quarkus:dev` but that seem to conflict with the port setting?

**Comment by cescoffier** [comment] 2023-07-31 07:05
Closing - no feedback.

Please re-open with a reproducer.

**Comment by oubidar-Abderrahim** [comment] 2023-08-31 16:04
We've done some analysis from GraalVM's side, and in short, this is a Quarkus bug. Quarkus initialize protobuf Java runtime at image build time ignoring the following warning for the [com.google.protobuf.UnsafeUtil](https://github.com/protocolbuffers/protobuf/blob/v3.19.3/java/core/src/main/java/com/google/protobuf/UnsafeUtil.java) class:

`Warning: RecomputeFieldValue.FieldOffset automatic substitution failed. The automatic substitution registration was attempted because a call to sun.misc.Unsafe.objectFieldOffset(Field) was detected in the static initializer of com.google.protobuf.UnsafeUtil. Detailed failure reason(s): The argument of sun.misc.Unsafe.objectFieldOffset(java.lang.reflect.Field) is not a constant value or a field load that can be constant-folded., Could not determine the field where the value produced by the call to sun.misc.Unsafe.objectFieldOffset(Field) for the field offset computation is stored. The call is not directly followed by a field store or by a sign extend node followed directly by a field store.`

Apparently, field offsets, array bases, etc. used for unsafe computations happen to have the same value on CE as they do on HotSpot, so it looks like things are working, but that's pure coincidence. Of course, this is no longer the case on EE as we use compressed references by default, so we end up with broken images. Unfortunately for us, this makes it look like this is an EE bug when it isn't, i.e., this is the expected behavior when warnings like the ones above are ignored.

**Comment by cescoffier** [comment] 2023-08-31 17:29
What fix would you propose? We really want to initialize a maximum of gRPC at build time. 

We can try to re-initialize this class at runtime, but we may see a huge difference in term of startup time.

**Comment by cescoffier** [comment] 2023-08-31 17:29
BTW if the warning should be considered as an error, why not failing the build?

**Comment by pejovica** [comment] 2023-09-04 17:51
> What fix would you propose? We really want to initialize a maximum of gRPC at build time.

Our usual recommendation would be to initialize the class at runtime, but if you really want to initialize it at build time, you'll need a substitution to recompute the correct values of the static fields. You can look at the [Target_sun_misc_Unsafe](https://github.com/oracle/graal/blob/master/substratevm/src/com.oracle.svm.core/src/com/oracle/svm/core/jdk/Target_sun_misc_Unsafe.java) substitution as an example of how to do that.

**Closed** 2023-10-25 06:07 UTC
Labels: kind/bug, area/grpc, triage/needs-reproducer
