### ISSUE TITLE
Environment variable mapping is not working propertly using @ConfigMapping or @WithName

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#18845] opened 2021-07-20 08:00 UTC
### Describe the bug

Config is not found following the spec (https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configsources.asciidoc#environment-variables-mapping-rules) when using environment:

```
$ MY_CONFIG_MY_FOO=bug java -jar target/quarkus-app/quarkus-run.jar

...
021-07-20 09:49:49,215 ERROR [io.qua.run.Application] (main) Failed to start application (with profile prod): io.smallrye.config.ConfigValidationException: Configuration validation failed:
	my.config.my.foo does not map to any root
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:818)
	at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:777)
	at io.smallrye.config.ConfigMappings.mapConfiguration(ConfigMappings.java:54)
	at io.smallrye.config.ConfigMappings.registerConfigMappings(ConfigMappings.java:36)
	at io.quarkus.arc.runtime.ConfigRecorder.registerConfigMappings(ConfigRecorder.java:50)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy_0(ConfigBuildStep$registerConfigClasses-2116437784.zig:132)
	at io.quarkus.deployment.steps.ConfigBuildStep$registerConfigClasses-2116437784.deploy(ConfigBuildStep$registerConfigClasses-2116437784.zig:40)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:524)
	at io.quarkus.runtime.Application.start(Application.java:101)
	at io.quarkus.runtime.ApplicationLifecycleManager.run(ApplicationLifecycleManager.java:101)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:66)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:42)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:119)
	at io.quarkus.runner.GeneratedMain.main(GeneratedMain.zig:29)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.doRun(QuarkusEntryPoint.java:48)
	at io.quarkus.bootstrap.runner.QuarkusEntryPoint.main(QuarkusEntryPoint.java:25)
```

### Expected behavior

The app should start and `my.config.my-foo` should be equal to `bug`

### Actual behavior

fail

### How to Reproduce?

Reproducer:

1. git clone https://github.com/ia3andy/reproducer-config-env
2. cd reproducer-config-env
3. mvn clean package
4. MY_CONFIG_MY_FOO=bug java -jar target/quarkus-app/quarkus-run.jar
5. error

It's working using @Deprecated `io.quarkus.arc.config.ConfigProperties`
```java

import io.quarkus.arc.config.ConfigProperties;
import org.eclipse.microprofile.config.inject.ConfigProperty;

@ConfigProperties(prefix = "my.config")
public interface MyConfig {

    @ConfigProperty(name = "my-foo")
    String myFoo();
}

```

### Output of `uname -a` or `ver`

Darwin MacBook-Pro-de-Andy.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /Users/ia3andy/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.11, vendor: AdoptOpenJDK, runtime: /Library/Java/JavaVirtualMachines/adoptopenjdk-11.jdk/Contents/Home Default locale: fr_FR, platform encoding: UTF-8 OS name: "mac os x", version: "11.2", arch: "x86_64", family: "mac"

**Comment by gsmet** [comment] 2021-07-20 08:11
@radcortez could you have a look at this one in priority? Thanks!

**Comment by geoand** [comment] 2021-07-20 09:08
Is this is duplicate of https://github.com/quarkusio/quarkus/issues/18842? If not, it seems pretty close :)

**Comment by radcortez** [comment] 2021-07-20 09:15
Sure, let me have a look.

**Comment by radcortez** [comment] 2021-07-20 09:26
This one was fixed in https://github.com/smallrye/smallrye-config/pull/600.

The SR Config version is already updated in Quarkus `2.1.0.CR1`, so it works correctly with that Quarkus versions. Alternatively, the SR Config version can be also manually updated to fix the issue in the `2.x` range with:

```xml
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config-common</artifactId>
      <version>2.4.2</version>
    </dependency>
    <dependency>
      <groupId>io.smallrye.config</groupId>
      <artifactId>smallrye-config</artifactId>
      <version>2.4.2</version>
    </dependency>
```

@gsmet SR Config `2.4.x` is backwards compatible with `2.3.x`. Do you want me to backport it to Quarkus `2.x`?

**Comment by gsmet** [comment] 2021-07-20 09:34
@radcortez I will do it for 2.0.3.Final, no worries.

**Comment by ia3andy** [comment] 2021-07-20 09:39
Thanks @radcortez the workaround is working:
https://github.com/quarkusio/code.quarkus.io/commit/895dee8950d5ad2687c638262d0c951747e65e70

**Closed** 2021-07-21 11:21 UTC
Labels: area/config, kind/bug
