### ISSUE TITLE
Performance degradation 0.22.0->1.1.0.Final

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#6539] opened 2020-01-13 21:54 UTC
While upgrading a service from version 0.22.0 to 1.1.0.Final I noticed an increase in latency with the same amount of HTTP request/sec.

Things that were changed:
1. Upgrade quarkus 0.22.0 to 1.1.0.Final 
2. `@Context HttpServletRequest` changed to `@Context HttpRequest`
3. Json logging integration was added instead of solution from #1847
4. `@Stream` Changed to `@Channel`

I noticed an increase in latency from <~1ms to <~2ms and increase in memory docker memory consumption from ~250mb to ~750mb

The service is running in alpine docker + OpenJDK 8

**Comment by FreifeldRoyi** [comment] 2020-01-13 22:14
Upgrade to 1.1.1.Final lowered the memory consumption to ~300mb

**Comment by geoand** [comment] 2020-01-20 07:22
cc @johnaohara

**Comment by johnaohara** [comment] 2020-01-21 07:45
@FreifeldRoyi do you have an application that reproduces the issue that we could test? Has the payload being sent/received changed between tests on 0.22.0 and 1.1.1.Final?  Is the application now generating more logging?

**Comment by FreifeldRoyi** [comment] 2020-01-21 11:58
- I had a hunch that it was due to a field change so to pinpoint this issue I reverted back to the good 0.22.0 commit and deployed each commit individually. The very first commit was the 0.22.0 to 1.1.0.Final bump _with no new fields_, only the changes I mentioned in the first message. Later I got to the 1.1.1.Final commit (with new fields) and got better memory footprint but same `<2ms` latency.
- There are no new logs. As a design decision, we don't write logs for each message (due to obvious performance reasons), not even in DEBUG level.
- I can try to write a small service that simulates the issue but locally this issue is really tricky to debug

**Comment by johnaohara** [comment] 2020-01-21 12:05
@FreifeldRoyi when you refer to latency;
1. are you referring to mean latency, max latency, some centile of latency distribution?
2. is the latency you are measuring the response time from the client side requests?
3. Has CPU utilization of the application increased with 1.1.1.Final?
4. Are you running in JVM mode or native mode?  

If you are seeing a difference in response times in JVM mode it could be possible to profile both versions to see where the difference might be coming from

**Comment by FreifeldRoyi** [comment] 2020-01-21 12:33
1. All
2. It's a homebrewed ContainerRequestFilter & ContainerResponseFilter to send time metrics to StatsD
3. at 0.22.0 CPU peaked at ~9%.  Now at ~10-12%
4. JVM with OpenJDK 8 as I mentioned in the first message

**Comment by gsmet** [comment] 2020-01-31 15:17
@FreifeldRoyi I think we will need some profiling information. @johnaohara should be able to help you with this.

A list of the extensions you are using could be useful too.

**Comment by geoand** [comment] 2021-02-26 11:48
I'll close this as we have now have more than 10 releases since the ticket was opened. 

If there is still a problem, please open a new issue

**Closed by geoand** 2021-02-26 11:48 UTC
Labels: kind/bug
