### ISSUE TITLE
Native image creation fails with java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException

### ISSUE THREAD

**Issue by michael-schnell** [quarkusio/quarkus#6327] opened 2019-12-23 14:21 UTC
Using the "quarkus-jdbc-postgresql" extension fails with the below error. Changing the database to "quarkus-jdbc-mariadb" fixes the problem. So it seems clearly to be related only to the postgresql extension.

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/developer/.sdkman/candidates/java/19.2.1-grl/jre/bin/native-image -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --report-unsupported-elements-at-runtime --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar cqrs4j-quarkus-example-query-1.0-SNAPSHOT-runner.jar -J-Djava.util.concurrent.ForkJoinPool.common.parallelism=1 -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace cqrs4j-quarkus-example-query-1.0-SNAPSHOT-runner
[cqrs4j-quarkus-example-query-1.0-SNAPSHOT-runner:5066]    classlist:  20,928.90 ms
[cqrs4j-quarkus-example-query-1.0-SNAPSHOT-runner:5066]        setup:   2,172.90 ms
Fatal error: java.lang.NoClassDefFoundError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:598)
	at java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1005)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:461)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:310)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:448)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:113)
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.getDeclaredMethods(Class.java:1975)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:437)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:270)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:875)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:824)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:524)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:444)
	at java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1386)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Error: Image build request failed with exit status 1

```
**Expected behavior**
Native image creation should work with "quarkus-jdbc-postgresql" as it does with "quarkus-jdbc-mariadb".

**Actual behavior**
Native image creation fails with "--report-unsupported-elements-at-runtime" and also without this parameter for "quarkus-jdbc-postgresql". Same project setup works fine with "quarkus-jdbc-mariadb".

**To Reproduce**
1.  Checkout project [ddd-cqrs-4-java-example](https://github.com/fuinorg/ddd-cqrs-4-java-example/)
2.  Change two files in [quarkus](https://github.com/fuinorg/ddd-cqrs-4-java-example/tree/master/quarkus/query) module to use "postgres" instead of mariadb: "pom.xml" and "src/main/resources/application.properties"  (See lines commented out)
3. Follow the instructions in [README.md](https://github.com/fuinorg/ddd-cqrs-4-java-example/blob/master/quarkus/README.md): "Prerequisites" + "Getting started"
4. Executing "./mvnw verify -Pnative -DskipTests" in module [query](https://github.com/fuinorg/ddd-cqrs-4-java-example/tree/master/quarkus/query) will fail with above error 

**Environment (please complete the following information):**
 - VMware image with Ubuntu Bionic (Kernel 4.15.0-72-generic, x86_64, 8 GB memory)
 - openjdk version "1.8.0_232"
 - OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
 - OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)
 - Quarkus 1.0.1.Final 

**Additional context**
There was a similar issue #[796](https://github.com/quarkusio/quarkus/issues/796), but I do **not** use the "shamrock-maven-plugin" as mentioned in that old issue.

**Comment by wfrank2509** [comment] 2020-01-15 09:50
Not sure if it helps - having the same issue - I could narrow it down to make it work when I don't use the Postgres extended types from 'com.vladmihalcea:hibernate-types-52' library.

For me adding this dependency breaks the native build.

**Comment by gsmet** [comment] 2020-02-02 13:44
@michael-schnell could you try with the latest 1.2.0.Final and GraalVM 19.3.1?

**Comment by michael-schnell** [comment] 2020-02-02 18:17
@gsmet Unfortunately problem stays the same with Quarkus 1.2.0.Final and GraalVM 19.3.1

```
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] Running Quarkus native-image plugin on GraalVM Version 19.3.1 CE
[INFO] [io.quarkus.deployment.pkg.steps.NativeImageBuildStep] /home/developer/.sdkman/candidates/java/19.3.1.r11-grl/bin/native-image -J-Djava.util.logging.manager=org.jboss.logmanager.LogManager -J-Dsun.nio.ch.maxUpdateArraySize=100 -J-DCoordinatorEnvironmentBean.transactionStatusManagerEnable=false -J-Dvertx.logger-delegate-factory-class-name=io.quarkus.vertx.core.runtime.VertxLogDelegateFactory -J-Dvertx.disableDnsResolver=true -J-Dio.netty.leakDetection.level=DISABLED -J-Dio.netty.allocator.maxOrder=1 --report-unsupported-elements-at-runtime --initialize-at-build-time= -H:InitialCollectionPolicy=com.oracle.svm.core.genscavenge.CollectionPolicy$BySpaceAndTime -jar cqrs4j-quarkus-example-query-0.1.0-runner.jar -H:FallbackThreshold=0 -H:+ReportExceptionStackTraces -H:-AddAllCharsets -H:EnableURLProtocols=http,https --enable-all-security-services -H:NativeLinkerOption=-no-pie -H:+JNI --no-server -H:-UseServiceLoaderFeature -H:+StackTrace cqrs4j-quarkus-example-query-0.1.0-runner
[cqrs4j-quarkus-example-query-0.1.0-runner:2293]    classlist:  17,237.36 ms
[cqrs4j-quarkus-example-query-0.1.0-runner:2293]        setup:     664.27 ms
Fatal error: java.lang.NoClassDefFoundError
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:603)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1006)
	at com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:462)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:315)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:454)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:115)
	at com.oracle.svm.hosted.NativeImageGeneratorRunner$JDK9Plus.main(NativeImageGeneratorRunner.java:479)
Caused by: java.lang.NoClassDefFoundError: com/sun/jna/LastErrorException
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3166)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2309)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleDeletedClass(AnnotationSubstitutionProcessor.java:437)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:270)
	at com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:230)
	at com.oracle.svm.hosted.NativeImageGenerator.createDeclarativeSubstitutionProcessor(NativeImageGenerator.java:876)
	at com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:825)
	at com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:528)
	at com.oracle.svm.hosted.NativeImageGenerator.lambda$run$0(NativeImageGenerator.java:445)
	at java.base/java.util.concurrent.ForkJoinTask$AdaptedRunnableAction.exec(ForkJoinTask.java:1407)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Error: Image build request failed with exit status 1

```

**Comment by michael-schnell** [comment] 2020-02-02 18:59
> .vladmihalcea

The library 'com.vladmihalcea:hibernate-types-52' is not in the dependency hierarchy.

**Comment by wfrank2509** [comment] 2020-02-06 09:02
> @wfrank2509 The library 'com.vladmihalcea:hibernate-types-52' is not in the dependency hierarchy.

Hi ... yes sure, but if you want to use Postgres Features like the JSONB type you need a library like that. The one mentioned is very commonly used.

**Comment by gsmet** [comment] 2020-02-06 09:15
My understanding is that something is trying to delete the `com/sun/jna/LastErrorException` from the native image but the class is not there.

You have a lot of dependencies so it's a bit hard to know who. I looked at the Quarkus source code and I don't see anything related to that class.

@dmlloyd any idea how we could debug that one?

**Comment by dmlloyd** [comment] 2020-02-06 17:05
We'd have to start by figuring out what requires JNA.  The `hibernate-types` project doesn't seem to use it so it must come in transitively from something else postgres-related.

**Comment by ricmzn** [comment] 2020-02-26 13:36
As a workaround, I've found that you can create the class in your own project, extending it from `java.lang.Exception`, and then run a clean build. It's not a proper fix, but it's enough to make native-build happy in the meantime.

**Comment by JohT** [comment] 2020-03-14 10:26
As another workaround, native-image configuration `<reportErrorsAtRuntime>true</reportErrorsAtRuntime>`
works for me (MacOs 10.13.6, GraalVM 20.0.0 CE, Quarkus 1.3.0.Final), 
when I add the following dependencies (version managed by quarkus bom):
```xml
<dependency>
	<groupId>jakarta.security.jacc</groupId>
	<artifactId>jakarta.security.jacc-api</artifactId>
</dependency>
<dependency>
	<groupId>net.java.dev.jna</groupId>
	<artifactId>jna</artifactId>
</dependency>
```

**Comment by antonwiens** [comment] 2020-09-17 10:48
Is there a fix in sight?

**Comment by michael-schnell** [comment] 2020-09-17 13:26
@antonwiens Are you facing the same problem with your code? Unfortunately I haven't had the time to check the above mentioned workarounds for my project.

**Comment by antonwiens** [comment] 2020-09-17 13:28
I face the same problem with my code. When using reportErrorsAtRuntime, suddenly the two mentioned dependencies are required.

**Comment by jaikiran** [comment] 2020-09-19 06:43
Hello @antonwiens, is there a simple application you can share (preferably as a github repo) which reproduces this issue?

**Comment by antonwiens** [comment] 2020-09-21 09:42
I will try to create one.

**Comment by antonwiens** [comment] 2020-09-28 13:29
I am getting near to creating a project for reproduction.
For me it seems related to the quarkus-rest-client. It takes in the httpasyncclient dependency which is referenced by below stacktrace. I dont have any other dependencies in the project which refer to httpasyncclient. I will try to create a simple project for sharing next.


The stacktrace related to this:
`Error: com.oracle.svm.hosted.substitute.DeletedElementException: Unsupported method sun.misc.URLClassPath.getLookupCacheURLs(ClassLoader) is reachable
To diagnose the issue, you can add the option --report-unsupported-elements-at-runtime. The unsupported element is then reported at run time when it is accessed the first time.
Detailed message:
Trace: 
        at parsing sun.misc.URLClassPath.initLookupCache(URLClassPath.java:359)
Call path from entry point to sun.misc.URLClassPath.initLookupCache(ClassLoader): 
        at sun.misc.URLClassPath.initLookupCache(URLClassPath.java:359)
        at sun.misc.Launcher$ExtClassLoader.<init>(Launcher.java:177)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:159)
        at sun.misc.Launcher$ExtClassLoader$1.run(Launcher.java:152)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:119)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processSessionRequests(DefaultConnectingIOReactor.java:282)
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:142)
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:221)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
        at java.lang.Thread.run(Thread.java:748)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:517)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)
        at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)`

**Comment by belu** [comment] 2021-02-08 18:49
Still happening with Quarkus 1.11.1.Final and latest GraalVM 21.1.0-dev.

**Comment by Sgitario** [comment] 2021-03-03 06:52
I could reproduce this issue and I had to add this additional dependency to make it work:

```xml
         <dependency>
            <groupId>net.java.dev.jna</groupId>
            <artifactId>jna-platform</artifactId>
            <version>5.3.1</version>
        </dependency>
```

Note that this dependency is not under quarkus bom, so I had to manually set the version.

**Comment by zakkak** [comment] 2021-04-02 12:13
An explanation of why this is happening can be found in https://github.com/oracle/graal/issues/1725

As explained there:
> I think there is some misconception about --report-unsupported-elements-at-runtime and @Delete:
We introduced the option --report-unsupported-elements-at-runtime so that developers can delay thinking about some Native Image compatibility issues and make quick progress getting a first image built. But that option fundamentally hides problems at image build time that you actually want to have checked. So --report-unsupported-elements-at-runtime should not be used for any images that you want to use in production.
So if you mark something as @Delete (which is of course an internal annotation and not part of our API), you are telling the analysis that it is an error if the annotated code is reachable. But then you want this error reported at run time?

So manually adding the dependencies might work around the issue and might be acceptable for development purposes but production code should not use `--report-unsupported-elements-at-runtime`.

**Comment by lost22git** [comment] 2023-10-20 03:03
same problem with latest quarkus version

**Comment by geoand** [comment] 2024-02-27 09:13
Is this still an issue?

**Comment by wfrank2509** [comment] 2024-03-11 14:28
Hi! Not really relevant anymore for me.

**Comment by geoand** [comment] 2024-04-02 11:03
Closing

**Closed by geoand** 2024-04-02 11:03 UTC
Labels: kind/bug, triage/needs-feedback
