### ISSUE TITLE
org.eclipse.microprofile.config.spi.Converter: Provider io.quarkus.amazon.common.runtime.RegionConverter not found

### ISSUE THREAD

**Issue by cthiebault** [quarkusio/quarkus#42545] opened 2024-08-14 11:47 UTC
### Describe the bug

Since Quarkus 3.13.0, I get this error while building with Gradle:

```text
./gradlew build --stacktrace

FAILURE: Build failed with an exception.

* What went wrong:
org.eclipse.microprofile.config.spi.Converter: Provider io.quarkus.amazon.common.runtime.RegionConverter not found

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

* Exception is:
java.util.ServiceConfigurationError: org.eclipse.microprofile.config.spi.Converter: Provider io.quarkus.amazon.common.runtime.RegionConverter not found
        at io.smallrye.config.SmallRyeConfigBuilder.discoverConverters(SmallRyeConfigBuilder.java:149)
        at io.smallrye.config.SmallRyeConfig.buildConverters(SmallRyeConfig.java:99)
        at io.smallrye.config.SmallRyeConfig.<init>(SmallRyeConfig.java:86)
        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:736)
        at io.quarkus.gradle.tasks.EffectiveConfig.<init>(EffectiveConfig.java:79)
        at io.quarkus.gradle.tasks.EffectiveConfig$Builder.build(EffectiveConfig.java:132)
        at io.quarkus.gradle.tasks.AbstractQuarkusExtension.buildBaseConfig(AbstractQuarkusExtension.java:95)
        [...]
```

I also tried with Quarkus 3.13.1 and 3.13.2...

I'm using latest version of `quarkus-amazon-services-bom`.
This version was fine with Quarkus 3.12.3.

```kotlin
implementation(platform("io.quarkiverse.amazonservices:quarkus-amazon-services-bom:2.16.2"))
implementation("io.quarkiverse.amazonservices:quarkus-amazon-s3")
```

The class `io.quarkus.amazon.common.runtime.RegionConverter` exists in the
`io.quarkiverse.amazonservices:quarkus-amazon-common:2.16.2` jar.

I tried to create a reproducer repo, but I can't reproduce the issue with a simple project :-/
I will to work on the reproducer but maybe you have an idea?

Thanks in advance for your help!

### Output of `java -version`

java 21.0.2, Kotlin 2.0.0

### Quarkus version or git rev

3.13.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.8

**Comment by gsmet** [comment] 2024-08-14 17:37
Do you set the value in the .env by any chance?

**Comment by cthiebault** [comment] 2024-08-15 06:54
I'm not sure what you mean by the `.env`. I don't think I use any .env
thing...

**Comment by torgre** [comment] 2024-08-15 07:10
It looks like this is also the same bug as I filed in https://github.com/quarkusio/quarkus/issues/42449

**Comment by radcortez** [comment] 2024-08-20 12:47
Duplicate of https://github.com/quarkusio/quarkus/issues/42449.

**Closed by radcortez** 2024-08-20 12:47 UTC
Labels: kind/bug, area/config, area/kotlin
