### ISSUE TITLE
gRPC service throw warning when using @Blocking and OpenTelemetry gRPC instrumentation

### ISSUE THREAD

**Issue by XSAM** [quarkusio/quarkus#23805] opened 2022-02-18 09:58 UTC
### Describe the bug

Calling a gRPC method with @Blocking annotation produces warnings when enabling [io.opentelemetry.instrumentation:opentelemetry-grpc-1.6:1.10.0-alpha](https://mvnrepository.com/artifact/io.opentelemetry.instrumentation/opentelemetry-grpc-1.6/1.10.0-alpha) and io.quarkus:quarkus-opentelemetry-exporter-otlp.

It does not affect gRPC methods without @Blocking annotation.

### Expected behavior

no warning

### Actual behavior

a warning `Context in storage not the expected context, Scope.close was not called correctly`

### How to Reproduce?

1. Clone https://github.com/XSAM/quarkus-issue-23603-reproducer
2. Local build Quarkus with the master branch (after https://github.com/quarkusio/quarkus/commit/68dff2c1da771fd2131e0ade904854282b4c8503)
3. Run `mvn test` to see the warning

### Output of `uname -a` or `ver`

21.2.0

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

master branch (after https://github.com/quarkusio/quarkus/commit/68dff2c1da771fd2131e0ade904854282b4c8503)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.3.3

### Additional information

Related to https://github.com/quarkusio/quarkus/pull/23702#discussion_r806561686

**Comment by radcortez** [comment] 2022-02-22 00:09
Specific OTel libraries are not officially supported at this point. The plan is to slowly support them in the future.

**Comment by cescoffier** [comment] 2022-02-22 07:07
@radcortez does #23702 fix it?

**Comment by XSAM** [comment] 2022-02-22 07:10
> 

#23702 does not fix this. #23702 only fix #23603.

**Comment by cescoffier** [comment] 2022-02-22 07:10
Ah ok, thanks!

**Comment by radcortez** [comment] 2022-02-22 11:31
The warning message is about the scopes not being closed in the correct order, so it may cause inconsistent trace history.

**Comment by snazy** [comment] 2022-02-23 12:20
I ran into the same issue (blocking + opentelemetry) recently and it seems that the order of gRPC interceptors matters. It seems to work only w/ Quarkus 2.7.2 (with #23607) and `BlockingServerInterceptor` needs to be the first/"outermost" interceptor.

But I also ran into more issue w/ blocking gRPC + opentelemetry. Will open issues / PRs soon-ish.

**Comment by knutwannheden** [comment] 2022-02-28 12:40
I am also seeing this warning quite a lot. So far I wasn't able to find the root cause of it. In my case I am not using any special libraries at all. I will report back if I find something.

**Comment by radcortez** [comment] 2022-03-02 21:12
I don't get the warning message with `2.7.2.Final`. I believe this was fixed by some of the Context work we did.

Please reopen if the issue persists.

**Closed by radcortez** 2022-03-02 21:12 UTC
Labels: kind/enhancement, area/grpc, area/tracing

**Comment by XSAM** [comment] 2022-03-17 10:06
@radcortez I found a case that will throw this warning with `2.7.2.Final`. Here is the [reproducer](https://github.com/XSAM/quarkus-issue-23805-reproducer).

Please reopen this issue.

**Comment by cescoffier** [comment] 2022-03-17 18:51
Can you open a new issue with the reproducer instead of reopening this one? For sure gRPC interceptor we're not handle by the current PR.

**Comment by radcortez** [comment] 2022-03-17 19:39
Yes, the  OTel gRPC library `io.opentelemetry.instrumentation:opentelemetry-grpc`, does not work with Quarkus currently, so we added our own integration. I need to have a better look to see what is not working exactly so I can suggest some changes upstream.

Anyway, gRPC instrumentation is automatic if the gRPC extension is available for your project (plus the OTel Extension).

**Comment by XSAM** [comment] 2022-03-18 08:59
> Can you open a new issue with the reproducer instead of reopening this one?

Sure thing. See https://github.com/quarkusio/quarkus/issues/24395
