### ISSUE TITLE
The openshift and container-image extensions are not listen buy `mvn quarkus:list-extensions`

### ISSUE THREAD

**Issue by tqvarnst** [quarkusio/quarkus#7836] opened 2020-03-13 09:10 UTC
**Describe the bug**
We have included openshift and container-image in Quarkus 1.3.0, but these are not listed when using maven to list possible extensions.

**Expected behavior**
Should be part of the list of extensions.

**Actual behavior**
Does not list these extensions.

**To Reproduce**
1. `mvn io.quarkus:quarkus-maven-plugin:1.3.0.Final:list-extensions`
2. 
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.
N/A
```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)
N/A

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`:
N/A 
 - Output of `java -version`:
N/A
 - GraalVM version (if different from Java): 
N/A
 - Quarkus version or git rev: 
1.3.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /Users/tqvarnst/.sdkman/candidates/maven/current
Java version: 11.0.5, vendor: AdoptOpenJDK, runtime: /Users/tqvarnst/.sdkman/candidates/java/11.0.5.hs-adpt
Default locale: en_SE, platform encoding: UTF-8
OS name: "mac os x", version: "10.15.3", arch: "x86_64", family: "mac"

**Additional context**

**Comment by maxandersen** [comment] 2020-03-13 09:29
@tqvarnst after reading this i think the issue is more likely that you are still using quarkus platform 1.2.1 as 1.3 platform is not released yet.

please check that first.

**Comment by gastaldi** [comment] 2020-03-13 16:21
I can confirm it works in 1.3.0.Final and with `quarkus-bom`

**Comment by gastaldi** [comment] 2020-03-13 16:21
Closing as invalid. Reopen if the problem persists

**Closed by gastaldi** 2020-03-13 16:21 UTC
Labels: triage/invalid
