### ISSUE TITLE
Kotlin dev mode recompile error

### ISSUE THREAD

**Issue by bulldog98** [quarkusio/quarkus#32358] opened 2023-04-03 09:49 UTC
### Describe the bug

If you have a quarkus app using kotlin, that uses library "trove:trove:1.0.2". In dev mode changing a class and reloading the dev ui leads to an error:

<details>

<summary>Error stacktrace</summary>

```
Unable to invoke Kotlin compiler. java.lang.NoSuchFieldError: _deadkeys
	at com.intellij.util.containers.RefHashMap$MyMap.compactIfNecessary(RefHashMap.java:79)
	at com.intellij.util.containers.RefHashMap$MyMap.access$400(RefHashMap.java:55)
	at com.intellij.util.containers.RefHashMap.processQueue(RefHashMap.java:170)
	at com.intellij.util.containers.RefHashMap.put(RefHashMap.java:231)
	at com.intellij.util.containers.WeakHashMap.put(WeakHashMap.java:23)
	at com.intellij.openapi.util.ObjectTree.rememberDisposedTrace(ObjectTree.java:243)
	at com.intellij.openapi.util.ObjectTree.lambda$executeAll$1(ObjectTree.java:175)
	at com.intellij.openapi.util.ObjectTree.runWithTrace(ObjectTree.java:116)
	at com.intellij.openapi.util.ObjectTree.executeAll(ObjectTree.java:168)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:142)
	at com.intellij.openapi.util.Disposer.dispose(Disposer.java:130)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:128)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:47)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at io.quarkus.kotlin.deployment.KotlinCompilationProvider.compile(KotlinCompilationProvider.java:93)
	at io.quarkus.deployment.dev.QuarkusCompiler.compile(QuarkusCompiler.java:226)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.checkForChangedClasses(RuntimeUpdatesProcessor.java:727)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:461)
	at io.quarkus.deployment.dev.RuntimeUpdatesProcessor.doScan(RuntimeUpdatesProcessor.java:441)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:152)
	at io.quarkus.vertx.http.runtime.devmode.VertxHttpHotReplacementSetup$4.handle(VertxHttpHotReplacementSetup.java:139)
	at io.vertx.core.impl.ContextBase.lambda$null$0(ContextBase.java:137)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextBase.lambda$executeBlocking$1(ContextBase.java:135)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1512)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
```
</details>

### Expected behavior

No error should occur

### Actual behavior

The error occurs

### How to Reproduce?

[compile-error.zip](https://github.com/quarkusio/quarkus/files/11136938/compile-error.zip)

1. Start dev mode in the reproducer
2. Change the ClockProvider.kt file, by adding a new line
3. reload/load the dev ui

**Comment by gsmet** [comment] 2024-08-24 09:36
Our Kotlin support in dev mode has been improved quite a lot since then and I can't get the reproducer updated to check it.

I will close this one.

**Closed by gsmet** 2024-08-24 09:36 UTC
Labels: kind/bug, area/devmode, area/kotlin
