### ISSUE TITLE
Quarkus REST. @Path conflict

### ISSUE THREAD

**Issue by andreiyusupau** [quarkusio/quarkus#43065] opened 2024-09-05 21:30 UTC
### Describe the bug

I have two resources (see example code below):
One of them specifies some  path prefix for all it's method on the class level (for example `/admin`).
The other has no class level prefix, but has one method with same prefix (for example `/admin/hello`).
For some reasons `/admin/hello` is not resolved by Quarkus and when I call this url I get error 404.

### Expected behavior

I expect that both types of urls work. (Such cases work pretty fine in Spring for example)
If it's not expected to work this way it would be good to have some compile or startup error.

### Actual behavior

Only endpoint from resource with class level prefix works.

### How to Reproduce?

1. Create Quarkus app with REST module.
```java
@Path("/admin")
public class AdminResource {

    @GET
    @Path("/action")
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        return "Hello from Quarkus REST";
    }
}
```
```java
@Path("")
public class ExampleResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/admin/hello")
    public String hello() {
        return "Hello from Quarkus REST";
    }

}
```
2. Call /admin/action -> works fine
3. Call /admin/example -> 404

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22631.4037]

### Output of `java -version`

Amazon Corretto 21.0.1

### Quarkus version or git rev

3.14.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle 8.10

### Additional information

By the way Quarkus Dev UI shows that both endpoints are available.

**Comment by geoand** [comment] 2024-09-06 05:28
I am going to close this as duplicate of #26496

**Closed by geoand** 2024-09-06 05:28 UTC
Labels: kind/bug, env/windows, triage/needs-triage
