### ISSUE TITLE
Hibernate caching issues with Quarkus 2.2.5.Final

### ISSUE THREAD

**Issue by KyriacosP** [quarkusio/quarkus#23300] opened 2022-01-31 08:26 UTC
### Describe the bug

We have a Kafka consumer method which is annotated with `@Blocking`. Every time this method receives an event it executes a "list" query using entity manager like `select entity from Foo entity` and after that it creates a DTO for each one of the returned entities. The first time we receive an event after startup we can see the hibernate sql logs for the "list" query and every subsequent sql log for loading the `@OneToMany` relationships for every entity when creating the DTO. When a second event arrives we can only see the sql log for the initial "list" query. It seems that hibernate is caching the results between the two events. This happens even if the data where changed in the database between the events leading to loading old data in the DTO. Also the issue happens both in dev and prod modes.

This was working correctly with Quarkus 1.11.2.Final and the issue started when we upgraded to 2.2.5.Final. We are using quarkus-hibernate-orm, quarkus-smallrye-reactive-messaging-kafka, quarkus-jdbc-postgresql and we have no 2LC configured.

### Expected behavior

The data should be loaded from the database every time.

### Actual behavior

The data are cached between events.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19043.1466]

### Output of `java -version`

java version "11.0.12" 2021-07-20 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.12+8-LTS-237) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.12+8-LTS-237, mixed mode)

### Quarkus version or git rev

2.2.5.FINAL

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by Sanne** [comment] 2022-01-31 09:28
Is it possible that each of your events are reusing the same Hibernate Session?

A reproducer would help.

**Comment by KyriacosP** [comment] 2022-01-31 09:44
> Is it possible that each of your events are reusing the same Hibernate Session?

How can we figure that out? And if so how can we avoid it?

> A reproducer would help.

I will try to create one but I'm not very familiar with dev services for kafka and postgresql.

**Comment by Sanne** [comment] 2022-01-31 10:00
> > Is it possible that each of your events are reusing the same Hibernate Session?
> 
> How can we figure that out?

Just checking the reference to the Session to be different would be a good first step.

Better even is to get the internal Session Identifier:

```
        import org.hibernate.engine.spi.SessionImplementor;

    	SessionImplementor s = entityManager.unwrap(SessionImplementor.class);
    	UUID sessionIdentifier = s.getSessionIdentifier();
```

Then log those sessionIdentifier; they need to be different for each event.

> And if so how can we avoid it?

That depends on how you're getting your `Session` or `EntityManager` instances. If you're using CDI injection, bear in mind the default scope is request context.

You could also inject the `EntityManagerFactory` instead, and control lifecycle explicitly if that's easier.

**Comment by KyriacosP** [comment] 2022-01-31 12:24
We have logged the session identifiers and they are the same on both events which means that the same session is used between events. We use CDI injection for the `EntityManager` and also we use the `@ActivateRequestContext` annotation on the class that receives the kafka events which if I understand correctly should manages sessions automatically.

We tested the same code using Quarkus 1.11.2.Final and we get different session ids for each event

**Comment by KyriacosP** [comment] 2022-01-31 16:45
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7972533/code-with-quarkus.zip)

I created a small reproducer just call the /test/event endpoint to fire a kafka event. You will see that the session id is the same between events

**Comment by Sanne** [comment] 2022-01-31 16:52
@mkouba | @manovotn | @Ladicek could one of you ArC experts have a look please?

The problem seems to be that the `EntityManager` isn't being scoped as expected (I couldn't look at the reproducer yet so perhaps it's trivial, sorry for the wide net ping)

**Comment by Sanne** [comment] 2022-02-01 15:40
oh, nice catch. It wasn't trivial then :)

**Comment by Sanne** [comment] 2022-02-01 15:46
I suspect #23324 might relate as well

**Comment by KyriacosP** [comment] 2022-02-03 10:31
Do we have any time frame on this being fixed?

**Comment by Sanne** [comment] 2022-02-03 12:21
I'm sure Martin will figure out something to improve things, but generally speaking I would recommend to not inject an EntityManager (whose scope should be limited to a single transaction) into a long-lived component such as an event stream consumer.

Such components are very long lived, and you will necessarily need to split your Database operations into smaller transactions; inject the `EntityManagerFactory` instead: that will allow you to open/close new EntityManagers as necessary, better handling concurrent operations, transactions, timeouts and memory consumption.

In fact I'm inclined to think we should disallow injecting an `EntityManager` in such cases.

**Comment by mklueh** [comment] 2022-02-03 12:51
> I'm sure Martin will figure out something to improve things, but generally speaking I would recommend to not inject an EntityManager (whose scope should be limited to a single transaction) into a long-lived component such as an event stream consumer.
> 
> Such components are very long lived, and you will necessarily need to split your Database operations into smaller transactions; inject the `EntityManagerFactory` instead: that will allow you to open/close new EntityManagers as necessary, better handling concurrent operations, transactions, timeouts and memory consumption.
> 
> In fact I'm inclined to think we should disallow injecting an `EntityManager` in such cases.

Is the entity manager even supposed to be working with reactive dependencies and hibernate reactive? I was under the impression that the EntityManager is based on JDBC and the reactive dependencies use vertx drivers instead and can't work together with JDBC

**Comment by manovotn** [comment] 2022-02-03 13:05
> Do we have any time frame on this being fixed?

The cause of this issue is being discussed in https://github.com/quarkusio/quarkus/discussions/23363, so take a look there if you're interested.
In shot, the core problem is that within reactive a CDI request context is captured and "endlessly propagated" and the entity manager is `@RequestScoped` so it just keep returning the same instance. So this problems spans beyond just Entity Manager.

We have already discussed a possible solution/workaround and I'll try to create a PR by tomorrow and we'll see if that fixes more than it breaks ;-)
I know there is also a fix planned on Mutiny side but I have no idea how's that going, @cescoffier might know more.

**Comment by cescoffier** [comment] 2022-02-03 13:18
> I know there is also a fix planned on Mutiny side but I have no idea how's that going, @cescoffier might know more.

Not mutiny, but reactive messaging. The idea is to avoid capturing the request context before creating the messaging streams. Before implementing that idea (which is relatively straightforward), I want to check if I can reuse @manovotn's one.

**Comment by Sanne** [comment] 2022-02-03 13:39
> > I'm sure Martin will figure out something to improve things, but generally speaking I would recommend to not inject an EntityManager (whose scope should be limited to a single transaction) into a long-lived component such as an event stream consumer.
> > Such components are very long lived, and you will necessarily need to split your Database operations into smaller transactions; inject the `EntityManagerFactory` instead: that will allow you to open/close new EntityManagers as necessary, better handling concurrent operations, transactions, timeouts and memory consumption.
> > In fact I'm inclined to think we should disallow injecting an `EntityManager` in such cases.
> 
> Is the entity manager even supposed to be working with reactive dependencies and hibernate reactive? I was under the impression that the EntityManager is based on JDBC and the reactive dependencies use vertx drivers instead and can't work together with JDBC

Right, sorry I forgot you were using Hibernate Reactive but it's the same principle.

If you're using Hibernate Reactive inject the `org.hibernate.reactive.mutiny.Mutiny.SessionFactory`  - if you're using JPA / blocking Hibernate then inject the `javax.persistence.EntityManagerFactory`.

Conceptually both are the same: you shouldn't use a single Session (or EntityManager) for such a long span, but use a new one for each transaction.

In addition to this for Hibernate Reactive users, don't use the methods `withSession` or `withTransaction`. These methods as a convenience store the current session and transaction in the current scope, to help with nested code blocks; unfortunately currently this "scope" isn't very well defined in this case, so while we think of how to fix that please use `openSession` and close it explicitly.

**Comment by manovotn** [comment] 2022-02-03 17:20
Apparently, I was wrong - during debugging inside the reproducer I can see that the `EntityManager` bean is actually `@ApplicationScoped`, is that intended @Sanne? Where are CDI beans for EM created?

**Comment by Sanne** [comment] 2022-02-03 17:40
> Apparently, I was wrong - during debugging inside the reproducer I can see that the `EntityManager` bean is actually `@ApplicationScoped`, is that intended @Sanne? Where are CDI beans for EM created?

Hibernate's Sessions are "transactionscoped" so it's most likely delegating to an actual instance which only actually exists within the current JTA scope. See `io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession`.

I wasn't aware the outer component would be flagged as ApplicationScoped though... that's a bit surprising but I suppose it might be ok.

**Comment by Sanne** [comment] 2022-02-03 17:43
The other place to look at is `generateDataSourceBeans` in `io.quarkus.hibernate.orm.deployment.HibernateOrmCdiProcessor`

**Comment by Sanne** [comment] 2022-02-03 17:51
N.B. this implies there's an important diference between the blocking version of Hibernate ORM and Hibernate Reactive: the first one is binding to JTA transactions, while Hibernate Reactive is not binding to JTA. So the scoping mechanism also works differently.

I hope that makes sense :)

**Comment by mkouba** [comment] 2022-02-04 10:10
> Apparently, I was wrong - during debugging inside the reproducer I can see that the `EntityManager` bean is actually `@ApplicationScoped`, is that intended @Sanne? Where are CDI beans for EM created?

@manovotn AFAIK the synthetic bean for `javax.persistence.EntityManager` and `org.hibernate.Session` is `@ApplicationScoped` but it delegates to `io.quarkus.hibernate.orm.runtime.TransactionSessions.getSession(String)` which returns a cached `io.quarkus.hibernate.orm.runtime.session.TransactionScopedSession` which acquires the current session:

1. from the `TransactionSynchronizationRegistry` if a transaction is active
2. from the `RequestScopedSessionHolder` (which is `@RequestScoped`) if no transaction is active; and this is the use case we're observing in this issue..

See also `io.quarkus.hibernate.orm.runtime.HibernateOrmRecorder.sessionSupplier(String)`.

**Comment by mkouba** [comment] 2022-02-04 10:11
^ In other words, it's rather complicated :D

**Comment by manovotn** [comment] 2022-02-04 10:23
> ^ In other words, it's rather complicated :D

Yea, that about sums my understanding of that magic :-D

Either way, I already figured it still depends on req. scope somehow since the PR I just posted(https://github.com/quarkusio/quarkus/pull/23436) actually affects/fixes the behavior.
I didn't go deep enough to uncover all of it though, so thanks for the summary @mkouba!

**Comment by mklueh** [comment] 2022-02-04 15:56
> > > I'm sure Martin will figure out something to improve things, but generally speaking I would recommend to not inject an EntityManager (whose scope should be limited to a single transaction) into a long-lived component such as an event stream consumer.
> > > Such components are very long lived, and you will necessarily need to split your Database operations into smaller transactions; inject the `EntityManagerFactory` instead: that will allow you to open/close new EntityManagers as necessary, better handling concurrent operations, transactions, timeouts and memory consumption.
> > > In fact I'm inclined to think we should disallow injecting an `EntityManager` in such cases.
> > 
> > 
> > Is the entity manager even supposed to be working with reactive dependencies and hibernate reactive? I was under the impression that the EntityManager is based on JDBC and the reactive dependencies use vertx drivers instead and can't work together with JDBC
> 
> Right, sorry I forgot you were using Hibernate Reactive but it's the same principle.
> 
> If you're using Hibernate Reactive inject the `org.hibernate.reactive.mutiny.Mutiny.SessionFactory` - if you're using JPA / blocking Hibernate then inject the `javax.persistence.EntityManagerFactory`.
> 
> Conceptually both are the same: you shouldn't use a single Session (or EntityManager) for such a long span, but use a new one for each transaction.
> 
> In addition to this for Hibernate Reactive users, don't use the methods `withSession` or `withTransaction`. These methods as a convenience store the current session and transaction in the current scope, to help with nested code blocks; unfortunately currently this "scope" isn't very well defined in this case, so while we think of how to fix that please use `openSession` and close it explicitly.

Thanks. How would you close it explicitly after the DB work is done without passing the session object through everything?

**Comment by Sanne** [comment] 2022-02-07 10:12
> > In addition to this for Hibernate Reactive users, don't use the methods `withSession` or `withTransaction`. These methods as a convenience store the current session and transaction in the current scope, to help with nested code blocks; unfortunately currently this "scope" isn't very well defined in this case, so while we think of how to fix that please use `openSession` and close it explicitly.
> 
> Thanks. How would you close it explicitly after the DB work is done without passing the session object through everything?
> 
> Edit: I've found it here http://hibernate.org/reactive/documentation/1.1/reference/html_single/#_obtaining_a_reactive_session

This is conceptually similar to `withSession`, except it doesn't store the Session in the vert.x scope:

```
   public <T> Uni<T> inSession(Function<Mutiny.Session, Uni<T>> work) {
        return sf.openSession().chain( session -> work.apply( session ).eventually( session::close ) );
    }
```

HTH

**Comment by KyriacosP** [comment] 2022-02-07 15:37
Following the merge of #23436 that fixes this issue is there any chance that the fix is going to be backported to release 2.2?

**Comment by Sanne** [comment] 2022-02-07 15:51
hi @KyriacosP , I doubt it as we're no longer doing releases of version 2.2 - please update.

**Comment by KyriacosP** [comment] 2022-02-08 07:33
ok thank you! Do we know when 2.7.1.Final will be released?

**Comment by famod** [comment] 2022-02-08 08:59
@KyriacosP the plan is today: https://groups.google.com/g/quarkus-dev/c/-Xt8cP05Hog

**Comment by manovotn** [comment] 2022-02-08 16:23
Since https://github.com/quarkusio/quarkus/pull/23436 was merged, I can think we can close this issue.

**Closed by manovotn** 2022-02-08 16:23 UTC
Labels: kind/bug, area/persistence, area/reactive-messaging, area/hibernate-orm, env/windows
