### ISSUE TITLE
@RequestScoped doesn't work with fault tolerance @Retry

### ISSUE THREAD

**Issue by blsouthr** [quarkusio/quarkus#4826] opened 2019-10-24 08:43 UTC
I have two request scoped beans. One is holding request data and another is using that data in error case to include it in error response. this however doesn't work if I add Retry annotation.
See attached project with tests. Quarkus 0.26.1

[getting-started.zip](https://github.com/quarkusio/quarkus/files/3766523/getting-started.zip)
1. Start project.
2. do curl http://localhost:8080/hello/error?data=hello
3. expected response should contain hello, but returns nothing
4. Delete Retry annotation from GreetingResource.helloError and all works as expected

**Comment by mkouba** [comment] 2019-10-24 10:07
Hello @blsouthr, the `GreetingResource.helloError(String)` method is executed on a different thread with a new request context. In other words, the original request context is not propagated. I'm not sure whether the MP FT spec defines this behavior though - @Ladicek WDYT?

**Comment by blsouthr** [comment] 2019-10-24 10:21
@mkouba yes, I know. But I think it is a bug. It's working in thorntail btw

**Comment by Ladicek** [comment] 2019-10-24 10:52
@mkouba If the `GreetingResource.helloError(String)` method is executed on a different thread, then there's something terribly wrong. There's no `@Asynchronous` and there's no `@Timeout`, so it must be on the same thread, unless I'm missing something.

**Comment by mkouba** [comment] 2019-10-24 10:58
I'm not sure what the current impl does but I do think that originally (ie. first versions of SmallRye FT) the retry logic was performed within a Hystrix command that was executed on a different thread...

**Comment by Ladicek** [comment] 2019-10-24 11:06
I think I had to rewrite how retry is handled because it didn't work properly in async scenarios. (Basically I think we handle retries manually in SmallRye FT, instead of relying on Hystrix.)

**Comment by mkouba** [comment] 2019-10-24 11:08
Ok, would you care to take this issue @Ladicek?

**Comment by Ladicek** [comment] 2019-10-24 11:30
So, funny thing is: the retried attempts are invoked on the request-handling thread. But the exception mapper is invoked on a different thread!

**Comment by Ladicek** [comment] 2019-10-24 11:33
If I change the retry delay from 500 millis to 5 millis, the exception mapper is invoked on the original request-handling thread, but I'm still getting an empty response. I don't think this is a SmallRye FT problem.

**Comment by Ladicek** [comment] 2019-10-24 11:57
I just tried adding `quarkus-undertow` to switch RESTEasy to Servlet, but no, that doesn't help.

**Comment by mkouba** [comment] 2019-10-24 14:19
So it seems that the contexts are broken by `smallrye-context-propagation-propagators-rxjava1` which automatically registers some [context propagators](https://github.com/smallrye/smallrye-context-propagation/tree/master/propagators-rxjava1/src/main/java/io/smallrye/context/propagators/rxjava1) for rxjava1 and Hystrix is using rxjava1 under the hood. I've also noticed that due to this propagation the `ArcContextProvider` is invoked **continuously**, even if no FT operation is called. This could represent a significant overhead.

@FroMage is it possible to disable the propagation for rxjava1 somehow? If not we should really make it possible because you can't simply exclude the `smallrye-context-propagation-propagators-rxjava1`  dependency.

For the record - I've tried to remove the `smallrye-context-propagation` dependencies from the `quarkus-smallrye-fault-tolerance` extension and it worked.

**Comment by mkouba** [comment] 2019-10-24 14:21
@kenfinnigan @FroMage Why do we have `smallrye-context-propagation` dependencies in the `quarkus-smallrye-fault-tolerance` extension? It does not seem to be necessary.

**Comment by manovotn** [comment] 2019-10-24 14:21
The PR that added it traces back to https://github.com/quarkusio/quarkus/issues/1537

**Comment by kenfinnigan** [comment] 2019-10-24 14:28
Thoughts @michalszynkiewicz?

**Comment by FroMage** [comment] 2019-10-24 14:29
We can disable context propagation, but it will mean nothing works once FT kicks in, because your endpoint code will lose all contexts: CDI, RESTEasy, Transaction, Servlet. This is what #1537 fixed. It was quite a biggie.

**Comment by FroMage** [comment] 2019-10-24 14:31
Frankly I don't know how you can use FT without CP, it's a bit like trying to run EE code on random threads: it won't work.

**Comment by FroMage** [comment] 2019-10-24 14:38
The problem is that once you add context propagation for RxJava1 it will work for all RxJava1 usages, even those that are internal to Hystrix. But we can't really tell from CP whether we should or not do context propagation, we can't tell if this is user code or Hystrix internal code.

Perhaps we could add an API to enable/disable CP that FT would call at some points (we want CP for the endpoint code but not for Hystrix internal stuff) but we'd have to pick a default and none of them look perfect. Only always propagating seems safe.

**Comment by FroMage** [comment] 2019-10-24 14:40
We can also make FT explicitely use the CP API to capture/restore contexts when it invokes the endpoints, instead of depending on RxJava1.

But to get back to the point, all this doesn't really explain why you get an issue: the contexts should be propagated. Even in exception handlers. If your issue is that the context is not propagated in an exception handler of RxJava1, it means you don't get _enough_ propagation. Forget about performance for now ;)

**Comment by FroMage** [comment] 2019-10-24 15:12
Yeah. It _is_ called a lot, and it's annoying, I agree. But I don't know how to make it better.

**Comment by FroMage** [comment] 2019-10-24 15:20
So, let me give some opinion of what might happen. I don't have the first idea of how FT works.

But, IF it works by twisting the REST endpoint return type from things like `Response` into a reactive type such as `CompletionStage<Response>` to accomplish its task, THEN the RESTEasy runtime is going to call `cs.toCompletableFuture().getNow()` which will try to see if the value is already resolved or not, and thus read it right now on the caller thread.

If it's not immediately resolved, then RESTEasy will turn the request async and listen to its value, which can come later.

This _could_ explain why failing fast runs in the same request thread, while failing later will run in an RxJava thread.

Again, no idea how FT is implemented so this may well be completely wrong.

**Comment by michalszynkiewicz** [comment] 2019-10-24 21:05
@kenfinnigan thanks for CCing me.
Unfortunately I don't know enough about the way Hystrix does things to have an answer.

Re directly using CP, is it possible to disable the automatic context propagation for hystrix in such case? If not, wouldn't it be a problem anyway if a user added something else that would bring CP-rxjava1 to his project?

**Comment by FroMage** [comment] 2019-10-25 08:48
We could, but again, it would break any user code requiring contexts in RxJava. If we disable CP for Hystrix, we need to find a way to enable it for non-Hystrix usage, and we also need FT to add explicit support for FT so that user apps actually work.

**Comment by michalszynkiewicz** [comment] 2019-10-25 09:27
So there's no way to selectively disable/enable context propagation, right?
Not sure that would be a good thing, just asking to be sure.

**Comment by michalszynkiewicz** [comment] 2019-10-26 14:26
I'll try to tackle this

**Comment by michalszynkiewicz** [comment] 2019-10-26 18:19
with some println debugging, I'm getting the user code invoked always on the same thread:
```
helloError on thread: vert.x-worker-thread-18[233]
Setting request data on vert.x-worker-thread-18[233]
helloError on thread: vert.x-worker-thread-18[233]
Setting request data on vert.x-worker-thread-18[233]
helloError on thread: vert.x-worker-thread-18[233]
Setting request data on vert.x-worker-thread-18[233]
helloError on thread: vert.x-worker-thread-18[233]
Setting request data on vert.x-worker-thread-18[233]
Exception mapper thread: vert.x-worker-thread-18[233]
getting from bean-bee request data on thread: vert.x-worker-thread-18[233]
Getting request data on vert.x-worker-thread-18[233]

```

**Comment by michalszynkiewicz** [comment] 2019-10-26 21:10
SmallRye FT does some calls that end up RxJava and Context Propagation does some context deactivaton and activation but it all looks fine at first sight (but it's the first time at looking at this code...). Yet, when the mapper is reached, the SomeBean instance it's different...

**Comment by mkouba** [comment] 2019-10-30 07:51
@michalszynkiewicz yes, as I wrote [here](https://github.com/quarkusio/quarkus/issues/4826#issuecomment-545940422) Hystrix is using rxjava under the hood and this triggers [ArcContextProvider](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/context/ArcContextProvider.java) and that could mix up the contexts somehow...

**Comment by michalszynkiewicz** [comment] 2019-10-30 13:16
I started looking into it and intend to continue when I'm finished with my current task so I am assigning it to myself.

**Comment by michalszynkiewicz** [comment] 2019-11-06 22:11
Some further debugging shows that if a bean is created before the retry operation, it is propagated to retry properly. It seems it's the back propagation that fails only.

It's normal that a request-scoped bean is initialized when it's used and not before, isn't it?

**Comment by FroMage** [comment] 2019-11-07 08:27
OK, that's very helpful. We had a long discussion about this with @manovotn and @mkouba and the takeaway point is that ArC should actually propagate a mutable request context, so forward and backward propagation is supported (it's the same underlying storage). For Weld, this is not the case and it's a copied request context with no backward propagation.

So, in theory it should work here, because ArC supports it, so that could be a bug in ArC context propagation?

**Comment by mkouba** [comment] 2019-11-07 08:41
> so that could be a bug in ArC context propagation?

@manovotn ^ WDYT?

**Comment by manovotn** [comment] 2019-11-07 11:05
> It's normal that a request-scoped bean is initialized when it's used and not before, isn't it?

Yes, we have lazy bean creation.

> so that could be a bug in ArC context propagation?

It could be; that or something inside Arc `RequestContext` implementation? From what I know, it should be like Stephane says - we specifically changed Arc to propagate whole map of instances so this won't be an issue.
The propagation looks ok but we did some changes to req. context impl....I'll start there.

**Comment by manovotn** [comment] 2019-11-07 11:15
Problem was likely introduced when we changed req. context state representation to [`InstanceHandlesContextState`](https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/InstanceHandlesContextState.java) because then we use `toConcurrentMap()` which creates new map that we then set.

I think that could be it?
Here is what we do now: https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/RequestContext.java#L103
And here is what we did in Quarkus 0.25: https://github.com/quarkusio/quarkus/blob/0.25.0/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/RequestContext.java#L97

**Comment by mkouba** [comment] 2019-11-07 11:36
Yes, that's very likely the problem. We should 1. fix it, 2. add a test that validates this specific way of context propagation for `RequestContext`.

**Comment by michalszynkiewicz** [comment] 2019-11-07 19:37
fixed

**Closed by michalszynkiewicz** 2019-11-07 19:37 UTC
Labels: bug, component:smallrye
