### ISSUE TITLE
Quarkus 2.2.1 fails with Hibernate-types and enum arrays

### ISSUE THREAD

**Issue by kny78** [quarkusio/quarkus#19856] opened 2021-09-01 21:32 UTC
### Describe the bug

I have isolated a new bug, when using Hibernate-types-55 and Quarkus 2.2.1

The issue is with using PostgreSQL **enum array** and **com.vladmihalcea:hibernate-types-55:2.12.1**.

Hibernate wrongfully reports is as a bug when disintegrating, but when debugging, I found the following error message:
`No Dialect mapping for JDBC type: 2003`

## Conflicting version of hibernate-types-55 and Hibernate 5.6
Hibernate version in 2.2.1 is 5.6.x
And the hibernate-types-55, aka matching Hibernate 5.5.
 @vladmihalcea is this relevant to this bug?
 
 ## Unit tests work correctly
Unit tests work for both Quarkus 2.1 and 2.2
Therefore it is possibly a bug in Quarkus, and not Hibernate-types.

## Test project
I made a very simple test-project based on https://code.quarkus.io and simple tests.
[https://github.com/kny78/quarkus-hibernate-56-array-type-fails](https://github.com/kny78/quarkus-hibernate-56-array-type-fails)

The README.md file explains how to trigger this bug.

### Expected behavior

2.1.1 and 2.2.1 should both work.

### Actual behavior

2.2.1 fails.
2.1.1 runs ok

### Output of `uname -a` or `ver`

Linux fedora 5.13.12-200.fc34.x86_64 #1 SMP Wed Aug 18 13:27:18 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.12" 2021-07-20 OpenJDK Runtime Environment 18.9 (build 11.0.12+7) OpenJDK 64-Bit Server VM 18.9 (build 11.0.12+7, mixed mode, sharing)

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d) Maven home: /home/kny/.m2/wrapper/dists/apache-maven-3.8.1-bin/2l5mhf2pq2clrde7f7qp1rdt5m/apache-maven-3.8.1 Java version: 11.0.12, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.12.0.7-0.fc34.x86_64 Default locale: en_GB, platform encoding: UTF-8 OS name: "linux", version: "5.13.12-200.fc34.x86_64", arch: "amd64", family: "unix"

**Comment by yrodiere** [comment] 2022-11-04 10:27
Hey. Sorry for the (very) long delay, but I just noticed this issue. I had a look at your reproducer.

The thing is, you're using the hibernate-types library directly, and that library is known *not* to work in Quarkus (I don't know the details). As a result, and in agreement with Vlad, a Quarkus extension was created that is essentially a fork of Hibernate-Types (because some of the required changes couldn't be implemented directly in Hibernate-Types, apparently): https://github.com/quarkiverse/quarkus-hibernate-types . You should use that extension in Quarkus instead of the Hibernate-Types library.

Now, that extension unfortunately does not seem to include array types. If you need those, I would suggest to close this issue and continue the conversation on https://github.com/quarkiverse/quarkus-hibernate-types/issues/25 ?

Alternatively, Quarkus 3 will include Hibernate ORM 6, which has [built-in support for array types]()

**Comment by vladmihalcea** [comment] 2022-11-04 10:31
Thanks @yrodiere for the explanation.

**Comment by yrodiere** [comment] 2023-01-04 09:56
Np.

Since the problem is not in Quarkus itself, I'll close the issue. @kny78 Feel free to ping me if you disagree.

**Closed by yrodiere** 2023-01-04 09:56 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm
