### ISSUE TITLE
Support new format for GraalVM reflect-config.json metadata files

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#43387] opened 2024-09-19 09:51 UTC
### Description

A new, more precise format for `reflect-config.json` is being introduced by GraalVM. Support for parsing the new format is being backported to GraalVM JDKs 21 and 17, so we _could_ choose to switch to the new format sometimes soon.

See also https://github.com/oracle/graal/pull/9670

No rush.
cc. @maxandersen @zakkak

**Comment by zakkak** [comment] 2024-09-19 10:07
Closing as duplicate of https://github.com/quarkusio/quarkus/issues/41016

**Closed by zakkak** 2024-09-19 10:07 UTC
Labels: kind/enhancement, area/config, area/native-image
