### ISSUE TITLE
ARC interferes with Smallrye ConfigProducer

### ISSUE THREAD

**Issue by dirkbolte** [quarkusio/quarkus#28309] opened 2022-09-30 05:50 UTC
### Describe the bug

Language: Kotlin

I want to inject a config property of a list of custom types:

```kotlin
@Provider
class TestClass {
    @ConfigProperty(name = "property.list")
    private lateinit var typeList: List<MyType>

    @ConfigProperty(name = "property.single")
    private lateinit var singleType: MyType
}
```

While Smallrye can resolve and fill `singleType`, it fails on the list. The cause in the stack trace is:

```
Caused by: java.lang.IllegalArgumentException: SRCFG02005: Type has no raw type class: io.quarkus.arc.impl.WildcardTypeImpl@2d198533
	at io.smallrye.config.inject.ConfigProducerUtil.rawTypeOf(ConfigProducerUtil.java:224)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:155)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:149)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:160)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:149)
	at io.smallrye.config.inject.ConfigProducerUtil.convertValues(ConfigProducerUtil.java:106)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:76)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:58)
	at io.smallrye.config.inject.ConfigProducer.producesListConfigProperty(ConfigProducer.java:136)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.create(Unknown Source)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.get(Unknown Source)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:60)
	... 89 more
```

From what I see, `WildcardTypeImpl` provides `java.util.List` as `rawType` - should it provide the upper bound of `actualTypeArgument`? 

I tried mitigating it by providing an explizit Converter for `List<MyType>` but the result is the same.

<img width="994" alt="Screenshot 2022-09-30 at 07 42 58" src="https://user-images.githubusercontent.com/1572945/193198675-66a03abc-49b6-499e-b81f-769daf58aada.png">

### Expected behavior

Config Converter for generic type of `List<T>` is used.

### Actual behavior

Exception and quarkus fails to start.

```
java.lang.RuntimeException: java.lang.ExceptionInInitializerError

Caused by: java.lang.ExceptionInInitializerError

Caused by: java.lang.RuntimeException: Failed to start quarkus
	at io.quarkus.runner.ApplicationImpl.<clinit>(Unknown Source)
	... 48 more
Caused by: java.lang.RuntimeException: Error injecting java.util.List<? extends de.test.MyType> de.test.TestClass. typeList
Caused by: java.lang.IllegalArgumentException: SRCFG02005: Type has no raw type class: io.quarkus.arc.impl.WildcardTypeImpl@2d198533
	at io.smallrye.config.inject.ConfigProducerUtil.rawTypeOf(ConfigProducerUtil.java:224)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:155)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:149)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:160)
	at io.smallrye.config.inject.ConfigProducerUtil.resolveConverter(ConfigProducerUtil.java:149)
	at io.smallrye.config.inject.ConfigProducerUtil.convertValues(ConfigProducerUtil.java:106)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:76)
	at io.smallrye.config.inject.ConfigProducerUtil.getValue(ConfigProducerUtil.java:58)
	at io.smallrye.config.inject.ConfigProducer.producesListConfigProperty(ConfigProducer.java:136)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.create(Unknown Source)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.get(Unknown Source)
	at io.smallrye.config.inject.ConfigProducer_ProducerMethod_producesListConfigProperty_1258131a638f518025054697883e1874162124ce_Bean.get(Unknown Source)
	at io.quarkus.arc.impl.CurrentInjectionPointProvider.get(CurrentInjectionPointProvider.java:60)
	... 89 more


```

### How to Reproduce?

1. Create custom type
2. Create Type Converter and add is to `org.eclipse.microprofile.config.spi.Converter`
3. Create Bean using this type as generic parameter of a list
4. Start Quarkus (or a QuarkusTest)

### Output of `uname -a` or `ver`

Darwin mymac.local 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:25:27 PDT 2022; root:xnu-8020.141.5~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "11.0.16" 2022-07-19 OpenJDK Runtime Environment Temurin-11.0.16+8 (build 11.0.16+8) OpenJDK 64-Bit Server VM Temurin-11.0.16+8 (build 11.0.16+8, mixed mode)

### Quarkus version or git rev

2.12.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by dirkbolte** [comment] 2022-09-30 06:16
FYI: When using `@ConfigMapping`, I can get it working with solely the `MyTypeConverter`, so no List Converter:

```kotlin
@ConfigMapping
@StaticInitSafe
interface MyConfig {
    fun single(): MyType
    fun list(): List<MyType>
}

```

**Comment by mkouba** [comment] 2022-09-30 07:23
I think that the problem is caused by the fact that Kotlin translates `List<MyType>` to something like `java.util.List<? extends MyType>`, i.e. Kotlin's `List` is not `java.util.List`. And SmallRye Config does not seem to handle this kind of injection point correctly, i.e. it does not handle `WildcardType` at all.

You can try to replace the `List<MyType>` with `java.util.List<MyType>` or even `MutableList<MyType>` as a workaround.

**Comment by mkouba** [comment] 2022-09-30 07:31
CC @radcortez

**Comment by dirkbolte** [comment] 2022-09-30 07:47
`java.util.List` works. With this, the type smallrye gets is `java.util.List<de.test.MyType>` . Went with `@ConfigMapping` for my implementation nevertheless. 

Is it in the responsibility of smallrye to handle `WildcardType` or in the responsibility of `WildcardType` to act as `ParameterizedTypeImpl` like a List for this kotlin case? I personally would prefer `WildcardType` to mimic the behaviour of ParameterizedTypeImpl` - or at least the "raw type" should return a parameterizedType of List instead of the List itself.

**Comment by mkouba** [comment] 2022-09-30 08:03
> Is it in the responsibility of smallrye to handle `WildcardType` or in the responsibility of `WildcardType` to act as `ParameterizedTypeImpl` like a List for this kotlin case? I personally would prefer `WildcardType` to mimic the behaviour of ParameterizedTypeImpl` - or at least the "raw type" should return a parameterizedType of List instead of the List itself.

I believe that it's the responsibility of SmallRye Config because the bytecode contains a wildcard. Note that `java.lang.reflect.WildcardType` does not even declare the `getRawType()` method.

**Comment by Ladicek** [comment] 2022-09-30 08:03
I think it would make sense for SmallRye Config's `ConfigProducerUtil.rawTypeOf()` to consider an upper bound of a wildcard type as its "raw" type.

**Comment by radcortez** [comment] 2022-09-30 15:46
I'll have a look.

**Comment by geoand** [comment] 2022-12-14 07:34
@radcortez was there any progress on this one?

**Comment by radcortez** [comment] 2022-12-14 11:36
Sorry, not yet. I'll try to have a look this week.

**Comment by radcortez** [comment] 2022-12-14 15:18
I've tried to reproduce the issue, both in SmallRye Config and Quarkus, with no luck. Here are the tests:

- https://github.com/radcortez/quarkus-playground/pull/123
- https://github.com/smallrye/smallrye-config/pull/861

@dirkbolte can you provide me your own reproducer? Thanks!

**Comment by dirkbolte** [comment] 2022-12-14 18:39
sry, I was sloppy: I don't have the test project preserved and now I can't reproduce it either.

**Comment by geoand** [comment] 2022-12-15 05:29
So I'll close this for now. If you do manage to create a reproducer, we can reopen

**Closed** 2022-12-15 05:29 UTC
Labels: kind/bug, area/config, area/smallrye, area/kotlin, needs-reproducer
