### ISSUE TITLE
Docker JVM build not working on new project

### ISSUE THREAD

**Issue by dozd** [quarkusio/quarkus#9107] opened 2020-05-06 07:55 UTC
**Describe the bug**
Building of docker image fails on sample project.

**Expected behavior**
Docker image successfully built

**Actual behavior**
Error during `./mvnw clean package -Dquarkus.container-image.build=true`
```
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] error: Error -1 running transaction
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] The command '/bin/sh -c microdnf install curl ca-certificates ${JAVA_PACKAGE}     && microdnf update     && microdnf clean all     && mkdir /deployments     && chown 1001 /deployments     && chmod "g+rwX" /deployments     && chown 1001:root /deployments     && curl https://repo1.maven.org/maven2/io/fabric8/run-java-sh/${RUN_JAVA_VERSION}/run-java-sh-${RUN_JAVA_VERSION}-sh.sh -o /deployments/run-java.sh     && chown 1001 /deployments/run-java.sh     && chmod 540 /deployments/run-java.sh     && echo "securerandom.source=file:/dev/urandom" >> /etc/alternatives/jre/lib/security/java.security' returned a non-zero code: 1
```
Whole build log: https://gist.github.com/dozd/588b1fb3751b30d204246ec545d74a69

**To Reproduce**
1. ` mvn io.quarkus:quarkus-maven-plugin:1.4.2.Final:create     -DprojectGroupId=org.acme     -DprojectArtifactId=getting-started     -DclassName="org.acme.getting.started.GreetingResource"     -Dpath="/hello"`
2. ` ./mvnw quarkus:add-extension -Dextensions="container-image-docker"`
3.  `./mvnw clean package -Dquarkus.container-image.build=true`

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```
# uname -a
Linux build 4.9.0-12-amd64 #1 SMP Debian 4.9.210-1 (2020-01-20) x86_64 GNU/Linux
```
 - Output of `java -version`: 
```
# java -version
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1bpo91)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1bpo91, mixed mode, sharing)
```
Same problem when using jdk8.

 - Quarkus version or git rev: 

`<quarkus.platform.version>1.4.2.Final</quarkus.platform.version>`

 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
```
# mvn -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/apache-maven
Java version: 11.0.6, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-12-amd64", arch: "amd64", family: "unix"
```
```
./mvnw -version
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /root/.m2/wrapper/dists/apache-maven-3.6.3-bin/1iopthnavndlasol9gbrbg6bf2/apache-maven-3.6.3
Java version: 11.0.6, vendor: Debian, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.9.0-12-amd64", arch: "amd64", family: "unix"
```

 - Docker version

```
# docker -v
Docker version 19.03.8, build afacb8b7f0
```

**Comment by geoand** [comment] 2020-05-06 08:23
I just tried your steps and it worked just fine for me.

**Comment by dozd** [comment] 2020-05-06 08:56
I have tried different machine and yeah - it's working. 
```
# uname -a
Linux *** 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
```
docker
```
# docker -v
Docker version 19.03.5, build 633a0ea838
```

This one error is not present. I think that could be the cause. But don't know why
```
[INFO] [io.quarkus.container.image.docker.deployment.DockerProcessor] /var/tmp/rpm-tmp.t7QVym: line 2: /usr/sbin/groupadd: No such file or directory
```

**Comment by geoand** [comment] 2020-05-06 09:00
I don't really know what the problem is TBH, but it's not a Quarkus issue, so I will go ahead and close this.

**Closed by geoand** 2020-05-06 09:00 UTC
Labels: kind/bug
