### ISSUE TITLE
org.objectweb.asm.ClassTooLargeException when building a project with 2K+ Hibernate entities (hbm.xmls).

### ISSUE THREAD

**Issue by digsb** [quarkusio/quarkus#22833] opened 2022-01-12 12:05 UTC
### Describe the bug

When we are trying to build our project with 2K+ Hibernate Entities (hbm.xmls) we are getting below exception.

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  57.961 s
[INFO] Finished at: 2022-01-12T16:57:23+05:30
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:build (quarkus-final-build-before-package) on project dna-wireless-service: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.deployment.steps.MainClassBuildStep#build threw an exception: org.objectweb.asm.ClassTooLargeException: Class too large: io/quarkus/deployment/steps/HibernateOrmProcessor$build1373687952
[ERROR] 	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:599)
[ERROR] 	at io.quarkus.gizmo.ClassCreator.writeTo(ClassCreator.java:214)
[ERROR] 	at io.quarkus.gizmo.ClassCreator.close(ClassCreator.java:225)
[ERROR] 	at io.quarkus.deployment.recording.BytecodeRecorderImpl.writeBytecode(BytecodeRecorderImpl.java:595)
[ERROR] 	at io.quarkus.deployment.steps.MainClassBuildStep.writeRecordedBytecode(MainClassBuildStep.java:436)
[ERROR] 	at io.quarkus.deployment.steps.MainClassBuildStep.build(MainClassBuildStep.java:168)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:887)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

### Expected behavior

Build to go through successfully.

### Actual behavior

Build failure.

### How to Reproduce?

1. Compile a project with large set of entities (2K+)

### Output of `uname -a` or `ver`

Linux ubuntu 4.15.0-159-generic #167-Ubuntu SMP Tue Sep 21 08:55:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04) OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)

### Quarkus version or git rev

2.6.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by Sanne** [comment] 2022-01-12 12:30
Interesting, thanks for the report!

@stuartwdouglas , @geoand could one of you have a look or suggest someone to assign to?

**Comment by yrodiere** [comment] 2022-01-12 12:41
Note in this particular project, hbm.xml files are being used, which means we record POJOs representing the content of those XML files during the build. This may or may not be the reason for the class file being "too large".

(One of the goals being to avoid XML parsing when the application starts, we cannot simply read the XML files again during static init).

**Comment by geoand** [comment] 2022-01-12 13:12
Stuart had solved a similar issue for generated methods that were too large by breaking them up. 
However the problem here is that the constant pool of the to be generated class is too large (it does not have to do with the fact that the application uses XML), which I don't know how we can solve since each recorder step is associated with a single generated class

**Comment by digsb** [comment] 2022-01-12 15:54
I ran build in Debug mode and collected some stats, not sure if this will be of any help.

`JpaModelBuildItem` generated by `JpaJandexScavenger`

```
domainObjects = {JpaModelBuildItem@9325} 
	allModelPackageNames = {TreeSet@9326}  size = 0
	entityClassNames = {TreeSet@9327}  size = 2396
	potentialCdiBeanClassNames = {TreeSet@9328}  size = 0
	allModelClassNames = {TreeSet@9329}  size = 2428
	xmlMappingsByPU = {HashMap@9330}  size = 1
		"<default>" -> {ArrayList@9335}  size = 2366
```

`ClassOutput` generated by `ByteCodeRecorderImpl`
```
file = {ClassCreator@13717} 
 enclosing = null
 classOutput = {GeneratedClassGizmoAdaptor@13255} 
  generatedClasses = {ExtensionLoader$lambda@13250} 
   arg$1 = {BuildContext@13690} 
    classLoader = {QuarkusClassLoader@13417} "QuarkusClassLoader:Deployment Class Loader: PROD@62bc29a6"
     name = "Deployment Class Loader: PROD"
     elements = {ArrayList@14313}  size = 2
     protectionDomains = {ConcurrentHashMap@14314}  size = 0
     definedPackages = {ConcurrentHashMap@14315}  size = 0
     parent = {QuarkusClassLoader@14316} "QuarkusClassLoader:Augmentation Class Loader: PROD@681bfec1"
     parentFirst = false
     aggregateParentResources = true
     bannedElements = {ArrayList@14317}  size = 0
     parentFirstElements = {ArrayList@14318}  size = 0
     lesserPriorityElements = {ArrayList@14319}  size = 0
     classLoaderEventListeners = {Collections$EmptyList@14320}  size = 0
     resettableElement = {MemoryClassPathElement@14321} 
     transformedClasses = {MemoryClassPathElement@14322} 
     state = {QuarkusClassLoader$ClassLoaderState@14323} 
     closeTasks = {ArrayList@14324}  size = 1
     closed = false
     driverLoaded = false
     ClassLoader.parent = {QuarkusClassLoader@14316} "QuarkusClassLoader:Augmentation Class Loader: PROD@681bfec1"
     ClassLoader.name = null
     unnamedModule = {Module@14325} "unnamed module @77106bd5"
     nameAndId = "io.quarkus.bootstrap.classloading.QuarkusClassLoader @62bc29a6"
     parallelLockMap = {ConcurrentHashMap@14327}  size = 2916
     package2certs = {ConcurrentHashMap@14328}  size = 1
     classes = {Vector@14329}  size = 88
     defaultDomain = {ProtectionDomain@14330} "ProtectionDomain  (null <no signer certificates>)\n QuarkusClassLoader:Deployment Class Loader: PROD@62bc29a6\n <no principals>\n null\n"
     packages = {ConcurrentHashMap@14331}  size = 1
     nativeLibraries = null
     assertionLock = {Object@14332} 
     defaultAssertionStatus = false
     packageAssertionStatus = {HashMap@14333}  size = 0
     classAssertionStatus = {HashMap@14334}  size = 0
     classLoaderValueMap = {ConcurrentHashMap@14335}  size = 0
    stepInfo = {StepInfo@13691} 
    execution = {Execution@13692} 
     chain = {BuildChain@14343} 
     singles = {ConcurrentHashMap@14344}  size = 86
     multis = {ConcurrentHashMap@14345}  size = 78
     finalIds = {HashSet@14346}  size = 2
     contextCache = {ConcurrentHashMap@14347}  size = 3
     executor = {EnhancedQueueExecutor@14348} 
     diagnostics = {Collections$SynchronizedRandomAccessList@14349}  size = 0
     buildTargetName = "main"
     errorReported = {AtomicBoolean@14351} "false"
     lastStepCount = {AtomicInteger@14352} "2"
     runningThread = {Thread@1} "Thread[main,5,main]"
     done = false
    dependencies = {AtomicInteger@13693} "0"
     value = 0
    running = true
  applicationClassPredicate = {GeneratedClassGizmoAdaptor$1@13689} 
   applicationClass = true
  sources = null
 superClass = "java/lang/Object"
 extraAccess = 0
 interfaces = {String[1]@13754} ["io/quarkus/runt..."]
 methods = {LinkedHashMap@13755}  size = 1640
 fields = {LinkedHashMap@13756}  size = 0
 annotations = {ArrayList@13757}  size = 0
 className = "io/quarkus/deployment/steps/HibernateOrmProcessor$build1373687952"
 signature = null
 superclassAccessors = {LinkedHashMap@13758}  size = 0
 accessorCount = {AtomicInteger@13759} "0"
```
Let me know if you want me to collect any more information.

**Comment by digsb** [comment] 2022-01-13 04:26
On Further Analysis found that Constant Pool Size is `253878` which is more than `65535` hence asm ClassWriter is throwing exception.

**Comment by stuartwdouglas** [comment] 2022-01-17 01:10
I could not reproduce this even with 4k entities. What is filling up the const pool in this case?

**Comment by stuartwdouglas** [comment] 2022-01-17 03:14
https://github.com/quarkusio/quarkus/pull/22932 may help here, but I need to make some recorder improvements to fix this properly.

**Closed** 2022-01-31 10:22 UTC
Labels: kind/bug, area/persistence, area/core, area/hibernate-orm
