### ISSUE TITLE
Quarkus is not handling annontation @JsonView properly

### ISSUE THREAD

**Issue by rsearls** [quarkusio/quarkus#7293] opened 2020-02-19 21:04 UTC
For @JsonView I have an app that defines the annotation.

   @JsonView(TestJsonView.class)
   private String annotatedValue;

   @JsonView({TestJsonView.class, TestJsonView2.class})
   private String annotatedValue2;

The endpoint sets the values and returns this object

   public static Something SOMETHING = 
      new Something("annotated value", "annotated value 2", "not annotated value");

   @GET
   @Produces("application/json")
   @JsonView(TestJsonView2.class)
   @Path("/something_w_view2")
   public Something getSomethingWithView2()
   {
      return SOMETHING;

   }

The return value should be
    annotatedValue = null
    annotatedValue = annotated value 2
    notAnnotatedValue = not annotated value
but is
    annotatedValue = annotated value
    annotatedValue = annotated value 2
    notAnnotatedValue = not annotated value

Execution env.
    jdk 11.0.2
    mvn 3.6.0
    quarkus 999-SNAPSHOT

The following project demonstrates the issue
  https://github.com/rsearls/quarkus-JsonView-annotation.git

Follow the directions in the README file to setup and run the test

**Comment by nimo23** [comment] 2020-02-19 23:26
You need to include the extension **quarkus-resteasy-jackson** in your pom.xml.

**Comment by rsearls** [comment] 2020-02-20 13:07
I added quarkus-resteasy-jackson to the provided sample project and got the same error.

**Comment by chrigiansen** [comment] 2020-04-29 17:15
Hello, I would like to know if there is any roadmap regarding a fix to this issue or if there is any viable workaround

**Comment by geoand** [comment] 2020-12-01 06:41
Is this still the case?

**Comment by rsearls** [comment] 2020-12-01 14:39
Yes it still fails.  I have updated the test case to quarkus version 1.9.0.Final

**Comment by geoand** [comment] 2020-12-01 14:41
Thanks for checking

**Comment by cpmoore** [comment] 2021-08-10 16:47
Ran into this today myself, with quarkus 2.0.2.Final

**Comment by gsmet** [comment] 2021-08-11 10:06
@cpmoore I added a test here: https://github.com/quarkusio/quarkus/pull/19340 and it seems to work as expected. What am I missing?

**Comment by gsmet** [comment] 2021-08-17 10:15
I'm closing this given I was unable to reproduce the problem.

Please reopen with a reproducer if you have one.

**Closed by gsmet** 2021-08-17 10:15 UTC
Labels: kind/enhancement

**Comment by joern-spire** [comment] 2022-01-18 16:08
The way this works can be surprising because non-annotated fields are included by default.

`
public class User {
  @JsonView(PublicView.class)
  public String id;
  @JsonView(PublicView.class)
  public String name;
  public String comment;
}
`
Since comment is not annotated with e.g. @JsonView(PrivateView.class) it will be included. There is a feature DEFAULT_VIEW_INCLUSION that can be disabled to prevent this on the ObjectMapper.

See here for docs:
https://fasterxml.github.io/jackson-databind/javadoc/2.12/com/fasterxml/jackson/databind/MapperFeature.html#DEFAULT_VIEW_INCLUSION

**Comment by gquintana** [comment] 2023-08-23 14:02
@joern-spire when you say
>  There is a feature DEFAULT_VIEW_INCLUSION that can be disabled to prevent this on the ObjectMapper.
Is there config somewhere to disable it?
