### ISSUE TITLE
SSE Defects

### ISSUE THREAD

**Issue by jimbogithub** [quarkusio/quarkus#23997] opened 2022-02-27 20:01 UTC
### Describe the bug

Multiple issues related to Server Sent Events demonstrated in https://github.com/jimbogithub/sse.  It contains reactive and non-reactive versions of a simple `TimeBroadcaster` broadcasting a timestamp event once per second to each subscribed `TimeConsumer`.

### SSE Server
See `sse-server` `TimeBroadcaster`.

1. Unable to obtain a centralised (e.g. `@ApplicationScoped` or `@Singleton`) `Sse` instance from which to derive the `SseBroadcaster` and `Builder`.  Hence it appears impossible to properly implement the one-sender-many-receivers pattern.
2. `SseBroadcaster.onError` is called twice for a client that has been cleanly closed.  This is undesirable.

### SSE Client
See `sse-client` `TimeConsumer`.

1. Requires the `Dummy` interface in order for the client to bootstrap.  See comments on that class as to what happens if you don't have this.

### SSE Server Reactive
See `sse-server-reactive` `TimeBroadcaster`.  Unlike the non-reactive server, it is possible to obtain a singular `Sse` instance  from which to derive the `SseBroadcaster` and `Builder`.

1. `SseBroadcaster.broadcast` tries to send messages to clients that have already closed.
2. `SseBroadcaster.onClose` is never called. 

### SSE Client Reactive
See `sse-client-reactive` `TimeConsumer`.

1. `ClientBuilder.newBuilder()...build()` does not work unless you add `.withConfig(new org.jboss.resteasy.reactive.common.jaxrs.ConfigurationImpl(RuntimeType.CLIENT))`.  This wasn't necessary for the non-reactive client or when doing `ClientBuilder.newClient()` and I suspect is not intended.
2. `ClientRequestContext.getHeaders().toString()` is not useful and does not match the non-reactive.  See further discussion in code.
3. `ClientResponseContext.getStatusInfo().toString()` is not useful and does not match the non-reactive.  See further discussion in code.
4. Client does not send the expected `Accept: text/event-stream` header.

### How to Reproduce?

https://github.com/jimbogithub/sse

### Quarkus version or git rev

2.7.2

### Additional information

Initial discussion: https://groups.google.com/g/quarkus-dev/c/qbH9RYnrIPg/m/GUlEiwLABAAJ

**Comment by michalszynkiewicz** [comment] 2022-03-01 08:39
for building the client in the reactive version, is there any reason for not using `ClientBuilder.newClient().register(new ClientRequestLogger()).register(new ClientResponseLogger());` to create the client?

**Comment by michalszynkiewicz** [comment] 2022-03-01 09:35
CC @FroMage @geoand

**Comment by jimbogithub** [comment] 2022-03-01 18:49
> for building the client in the reactive version, is there any reason for not using `ClientBuilder.newClient().register(new ClientRequestLogger()).register(new ClientResponseLogger());` to create the client?

In my case no.  I simply point out the issue that occurs for anyone who does need to access the methods that are only available on the builder.

**Comment by jimbogithub** [comment] 2022-03-02 22:58
> > for building the client in the reactive version, is there any reason for not using `ClientBuilder.newClient().register(new ClientRequestLogger()).register(new ClientResponseLogger());` to create the client?
> 
> In my case no. I simply point out the issue that occurs for anyone who does need to access the methods that are only available on the builder.

Looks like this one has been addressed by #23949 / #23996.

**Comment by jimbogithub** [comment] 2022-03-20 23:41
Another issue with the **SSE Client Reactive** is that it does not propagate the entity in the WebApplicationException.  I think this is a known issue as there are comments in the code to that effect.

This is a more serious issue as I was hoping to switch to the reactive client as it properly implements `connection-ttl` as documented in https://quarkus.io/guides/all-config#quarkus-rest-client-config_quarkus.rest-client.-config-key-.connection-ttl (idle TTL) whereas the non-reactive version does a hard TTL.

**Comment by herasimau** [comment] 2022-08-05 06:08
Hi, any update on this issue ? SSE Server Reactive
 `SseBroadcaster.onClose is never called.`

**Comment by gsmet** [comment] 2022-08-05 12:22
@geoand do you have this one on your radar?

**Comment by geoand** [comment] 2022-08-05 12:46
Nope, it had dropped off, but I guess it's back on

**Comment by jimbogithub** [comment] 2022-08-25 00:02
FYI, I switched to Mutiny SSE as SSE Client Reactive started rapidly leaking memory (from 2.9.x?) - appears Buffers not being closed.

**Comment by geoand** [comment] 2022-08-25 03:33
Do you have a memory dump or a sample project that exhibits this behavior?

**Comment by jimbogithub** [comment] 2022-08-25 21:29
> Do you have a memory dump or a sample project that exhibits this behavior?

See this branch of the reproducer: https://github.com/jimbogithub/sse/tree/mem-leak

Start the sse-server-reactive then the sse-client-reactive.

2.7.x was OK.  Noticed it from 2.9.2.  Still present in 2.11.3.
Appears to be related to the Jackson integration as it doesn't occur if the messages are plain and the consumer does either `event.readData()` or `event.readData(String.class)`.

Not so much leaking byte arrays but they grow in size (increasing `#bytes`):
```
jcmd 87720 GC.class_histogram
87720:
 num     #instances         #bytes  class name (module)
-------------------------------------------------------
   1:        119875       57961616  [B (java.base@17.0.4)
```
Eventually become "humungous" and GC fails.

**Comment by geoand** [comment] 2022-08-26 06:06
Thanks

**Comment by geoand** [comment] 2022-08-30 06:20
@jimbogithub I was not able to reproduce the issue with your project.

**Comment by jimbogithub** [comment] 2022-08-30 07:16
@geoand Did you use the branch I indicated?

**Comment by geoand** [comment] 2022-08-30 08:55
I did yes.

This is what memory looked like:

![mem](https://user-images.githubusercontent.com/4374975/187394021-1bfd3ef8-849d-4f32-9cea-3abe4b095a05.png)

As you see, the `Old Generation` size is constant and all allocations are in `Eden` (which also results in all GCs being `Young Generation` GCs).

**Comment by jimbogithub** [comment] 2022-08-30 09:19
What process are you monitoring?  That loaded class count does not look plausible to me.

![image](https://user-images.githubusercontent.com/5095954/187399670-5c875f1e-fd5f-488a-8170-2459c9e15d0b.png)

![image](https://user-images.githubusercontent.com/5095954/187399759-7911e9ea-36c0-48b8-81d6-eb10f7aad2a4.png)

**Comment by geoand** [comment] 2022-08-30 09:20
Oh, it's the client that has the leak? I was monitoring the server. Let me check the client as well

**Comment by geoand** [comment] 2022-08-30 09:39
I can confirm the client issue.

**Comment by geoand** [comment] 2022-08-30 12:42
https://github.com/quarkusio/quarkus/pull/27594 seems to fix the issue but I am not yet 100% it's the proper fix

**Comment by jimbogithub** [comment] 2022-08-30 19:50
@geoand I've re-tested my assertion that it was related to the Jackson/JSON integration - it isn't.  Reproducer works with server sending PLAIN_TEXT and client doing simple `event.readData()`.  So no need to worry about that aspect.

**Comment by geoand** [comment] 2022-08-31 05:18
Right, I saw that too when testing my fix

**Comment by geoand** [comment] 2023-01-27 09:23
Is this still a problem?

**Comment by geoand** [comment] 2024-03-01 09:56
Closing as we did not receive feedback

**Closed by geoand** 2024-03-01 09:56 UTC
Labels: kind/bug, area/resteasy-reactive
