### ISSUE TITLE
Add Coroutines Support  for CDI Event

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34758] opened 2023-07-14 15:09 UTC
### Description

When calling a `suspend` at the application startup stage, 

```kotlin 
@ApplicationScoped
class DataInitializer(val postRepository: PostRepository) {
    companion object {
        private val LOGGER = Logger.getLogger(DataInitializer::class.java.name)
    }

    suspend fun init(@Observes event: StartupEvent) {
        //@formatter:off
        flowOf(
            Post(title = "Quarkus 3.0", body = "test"),
            Post(title = "Quarkus 3.0 and Koltin", body = "test")
        )
        .map {
            postRepository.persist(it).awaitSuspending()
        }
        .onEach {
            LOGGER.log(Level.INFO, "saved data: $it")
        }
        .onCompletion { LOGGER.log(Level.INFO, "initialization is done at: ${LocalDateTime.now()}") }
        .catch { LOGGER.log(Level.ALL, "error: $it") }
        .collect()
        //@formatter:on
    }
}
```

Currently the codes will throw exception:

```bash 
2023-07-14 23:00:39,402 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-07-14 23:00:40,068 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build f
ailed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.Unsatisfied
ResolutionException: Unsatisfied dependency for type kotlin.coroutines.Continuation<? super kotlin.Unit> and qualifiers [@Default]
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type kotlin.coroutines.Continuation<? super kotlin.Unit> and qualifiers [@Default]      
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:477)
        at io.quarkus.arc.processor.ObserverInfo.init(ObserverInfo.java:303)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:301)
        ... 13 more

        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:336)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:253)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.createInitialRuntimeApplication(AugmentActionImpl.java:60)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.firstStart(IsolatedDevModeMain.java:82)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:423)
        at io.quarkus.deployment.dev.IsolatedDevModeMain.accept(IsolatedDevModeMain.java:55)
        at io.quarkus.bootstrap.app.CuratedApplication.runInCl(CuratedApplication.java:138)
        at io.quarkus.bootstrap.app.CuratedApplication.runInAugmentClassLoader(CuratedApplication.java:93)
        at io.quarkus.deployment.dev.DevModeMain.start(DevModeMain.java:131)
        at io.quarkus.deployment.dev.DevModeMain.main(DevModeMain.java:62)
Caused by: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.Unsatisfied
ResolutionException: Unsatisfied dependency for type kotlin.coroutines.Continuation<? super kotlin.Unit> and qualifiers [@Default]
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type kotlin.coroutines.Continuation<? super kotlin.Unit> and qualifiers [@Default]      
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:477)
        at io.quarkus.arc.processor.ObserverInfo.init(ObserverInfo.java:303)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:301)
        ... 13 more

        at io.quarkus.builder.Execution.run(Execution.java:123)
        at io.quarkus.builder.BuildExecutionBuilder.execute(BuildExecutionBuilder.java:79)
        at io.quarkus.deployment.QuarkusAugmentor.run(QuarkusAugmentor.java:160)
        at io.quarkus.runner.bootstrap.AugmentActionImpl.runAugment(AugmentActionImpl.java:332)
        ... 9 more
Caused by: jakarta.enterprise.inject.spi.DeploymentException: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type kotlin.coroutines.Continuation<?
 super kotlin.Unit> and qualifiers [@Default]
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.BeanDeployment.processErrors(BeanDeployment.java:1435)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:310)
        at io.quarkus.arc.processor.BeanProcessor.initialize(BeanProcessor.java:155)
        at io.quarkus.arc.deployment.ArcProcessor.validate(ArcProcessor.java:469)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.javafor type kotlin.coroutines.Continuation<? super kotlin.Unit> and qualifiers [@Default]      
        - java member: com.example.DataInitializer#init():$completion
        - declared on ObserverInfo [beanClass=com.example.DataInitializer, priority=2500, isAsync=false, reception=ALWAYS, transactionPhase=IN_PROGRESS, observedType=io.quarkus.runtime
.StartupEvent, qualifiers=[]]
        at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:477)
        at io.quarkus.arc.processor.ObserverInfo.init(ObserverInfo.java:303)
        at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:301)
        ... 13 more

```

### Implementation ideas

Currently the Coroutines Repository is not provide https://github.com/quarkusio/quarkus/issues/34624, we could use Reactive API to make it work.

```kotlin 
fun init(@Observes event: StartupEvent) {
    Multi.createFrom()
        .items(
            Post(title = "Quarkus 3.0", body = "test"),
            Post(title = "Quarkus 3.0 and Koltin", body = "test")
        )
        .flatMap{  postRepository.persist(it).convert().toPublisher() }
        .subscribe()
        .with(
            { data -> LOGGER.log(Level.INFO, "saved data: $data") },
            { error -> LOGGER.log(Level.ALL, "error: $error") }
        )
}
```

or using a `runBlocking{}` wrap the original codes to override the barrier. 

Please provides a built-in Coroutines support for CDI Event.

**Comment by Ladicek** [comment] 2023-07-14 15:14
`@Observes` denotes a synchronous observer, so I think you could just use the `runBlocking` coroutine builder.

**Comment by hantsy** [comment] 2023-07-14 15:16
All `suspend` fun from Kotlin Coroutines will append a `Continuation` object as the last method argument at compile time. 

I have tried Bean validation on REST method, it works.

**Comment by hantsy** [comment] 2023-07-14 15:17
> `@Observes` denotes a synchronous observer, so I think you could just use the `runBlocking` coroutine builder.

I see, I have already mentioned in the original post.

**Comment by hantsy** [comment] 2023-07-14 15:24
@Ladicek I am not sure if this exception is occurred in other scenarios, such as Interceptor method binding, `@Produces` method, etc.

**Comment by Ladicek** [comment] 2023-07-14 15:26
Pretty sure the same thing would happen for producer methods too, because all their parameters are injection points. CDI is fundamentally a synchronous framework. There's no point in pretending that synchronous observers may be asynchronous, that just leads to more confusion. A _synchronous_ observer method must be synchronous. If you need to use an asynchronous API in it, you need to block in one way or another. For Kotlin suspending functions, the `runBlocking` coroutine builder seems like the best choice.

**Comment by hantsy** [comment] 2023-07-14 15:38
@Ladicek In fact, when using Spring Reactive stack and Kotlin Coroutines, we also encounter the same issue. Originally, there is a 3rd party project https://github.com/konrad-kaminski/spring-kotlin-coroutine provides great Coroutines experience in Spring. 

But when Spring added official Coroutines support, this project is discontinued. Now more and more Spring built-in feature supports Coroutines, such as reactive WebFilter, Scheduled etc.

Spring Coroutines support is based on its reactive stack, not traditional blocking APIs.

**Comment by geoand** [comment] 2023-07-14 16:04
@hantsy I think you misunderstood what @Ladicek said. 

Arc / CDI is **not** Reactive so supporting suspend methods in the example you mention probably does not make much sense

**Comment by hantsy** [comment] 2023-07-15 01:45
@geoand  At compile time it  will add a `Contination` as last parameter in these `suspend` method, and  at runtime the suspend method(the compiled class) will complain a `Continuation` bean is unsatisfied, so when compiling the Kotlin Coroutines codes by Quarkus Arc/CDI plugin, if possible to generate such a bean?

**Comment by geoand** [comment] 2023-07-15 04:02
The mechanics don't matter because in this case we are talking about something that just isn't meant to be async.

But to answer your question about them, yes, we know and use that in other areas where we support coroutines.

**Comment by mschorsch** [comment] 2023-07-15 07:35
https://github.com/quarkusio/quarkus/issues/26007

**Comment by Ladicek** [comment] 2023-07-17 06:38
A lot of features in Quarkus support Kotlin coroutines too, we even have a documentation for it: https://quarkus.io/guides/kotlin#coroutines-support

My personal opinion is that we should not bolt coroutines on things that are fundamentally synchronous, such as synchronous observers. In any case, this is indeed a duplicate of #26007, so closing.

**Closed by Ladicek** 2023-07-17 06:38 UTC
Labels: kind/enhancement, area/arc, area/kotlin
