### ISSUE TITLE
Is there any way to force validation before Entity.persist() in Panache

### ISSUE THREAD

**Issue by clochardpagan** [quarkusio/quarkus#2834] opened 2019-06-13 14:40 UTC
**Description**
Using Panache and hibernate-validation is hard at the moment, due to no applied rules of validation. We can create a pretty validateable entity like: 

```
@Entity
public class Book extends PanacheEntity {
    
    @NotNull(message="book.title.null.error")
    public String name;
    
}
```
But calling:
```
Book b = new Book();
b.name = null;
b.persist();
```
Will not fire validation routine and user will be able literally "shoot itself in the foot". If solution exists without adding more source to Panache, it'll be good to have it in docs.

**Implementation ideas**
I've been writing last couple years on Grails, and GROM mechanics looks pretty good for me (I may be biased a little on that). We can extend .persist() method attributes with two more:

- boolean doValidate - if set to true, Panache checks entity to be valid (also it may cascade checking). If valid - commit, if failed - return list of violations. Also can raise an Exception (more fail-fast concept)
- boolean doFlush - forces Panache to flush after persist() call. Me be useful in some cases.

**Comment by machi1990** [comment] 2019-06-13 14:43
@gsmet Is this a duplicate of #1889?

**Comment by gsmet** [comment] 2019-06-13 14:43
@clochardpagan we are working on a better integration between Hibernate ORM and Hibernate Validator in Quarkus as we speak. There is a draft PR here: https://github.com/quarkusio/quarkus/pull/2753 .

**Comment by clochardpagan** [comment] 2019-06-13 14:52
> @gsmet Is this a duplicate of #1889?

No, it's not a duplicate.  #1889 is about correct table mapping and constrains on DB. There is an ad-hoc solution for #1889 - add Colunm annotation.

My request is more applied to creating a way to prevent persisting entities breaking validation. For example, DB can have any size table, but if field is ought to confront regexp validation, than all entities must confront. It's not possible to solve this situation with DB-only constrains, it needs a validation on object level.

**Comment by gsmet** [comment] 2019-06-13 14:58
@clochardpagan so #1889 is indeed also about that: right now HV is not integrated at all in ORM. When we integrate it, it will push the constraints to the database and trigger the validation.

There's a good chance, this will be OK for the next release. I'll ping you here once it's in master so that you can test it on your app.

**Comment by FroMage** [comment] 2019-06-13 15:07
Sounds a lot like a dupe of #2755, no?

**Comment by emmanuelbernard** [comment] 2019-07-05 07:30
We also discussed adding a entity.validate() returning `Set<ConstraintViolation>` at some point to explicitly have the result and not even attempt to persist. I tried to find the issue but seems that we never logged our conversation @FroMage

**Comment by FroMage** [comment] 2019-07-08 08:49
We did talk about it, but did not add any issue.

**Comment by FroMage** [comment] 2019-07-08 08:50
This is my last comment about the issue: https://github.com/quarkusio/quarkus/issues/646#issuecomment-465215799

**Comment by loicmathieu** [comment] 2019-10-29 11:43
@clochardpagan #1889 has been merged a long time ago . Does it fixes your issue? Can I close it ?

**Closed** 2019-11-13 22:14 UTC
Labels: enhancement
