### ISSUE TITLE
Custom credentials provider broken in the latest 2.5.1.Final and since from 2.0.0.Final release. It was working till 1.13.7.Final release

### ISSUE THREAD

**Issue by mskulkarni** [quarkusio/quarkus#22084] opened 2021-12-09 18:05 UTC
### Quarkus Custom credential provider not working in case of multiple providers one per datasource.

Quarkus Custom credentials provider is broken since version _2.0.0.Final_ release till latest _2.5.1.Final_ and not referring to the correct credential provider in case of multiple credentials provider for different databases. This was working till 1.13.7.Final Quarkus version. 

The project uses Agrol DataSource to create connection pool with the database. Multiple datasources are used in the project. In this case, we have to databases, one is MSSQL and other is Redshift.

We need to read password from external source before making connection with the database for provided database user. The problem is, at run time, wrong customer credential provider implementation is getting referred or called. Is it injecting default datasource credentials provider everywhere?
 
So for example, if I have below properties in the properties file:

The first section of properties are for MSSQL database. Let's consider MS SQL Server database which has Quarkus support.

**MSSQL:**

```
quarkus.datasource.db-kind=mssql
quarkus.datasource.jdbc.max-size=50
quarkus.datasource.jdbc.min-size=10
quarkus.datasource.username=test
uarkus.datasource.password=test123
quarkus.datasource.credentials-provider = mssqlcredentialsprovider
quarkus.datasource.credentials-provider-name = mssql-credentials-provider
```

The second section of properties refer to other redshift database.

**Redshift:**

```
quarkus.datasource.redshift.db-kind=other
quarkus.datasource.redshift.jdbc.driver=com.amazon.redshift.jdbc42.Driver
quarkus.datasource.redshift.jdbc.url=jdbc:redshift://testinstance:5439/test_db
quarkus.datasource.redshift.username=testuser
quarkus.datasource.redshift.password=testpassword
quarkus.datasource.redshift.credentials-provider = redshiftcredentialsprovider
quarkus.datasource.redshift.credentials-provider-name = redshift-credentials-provider
```

The code has correct implementation of Custom credential providers. I have changed below code just for description. My requirement is that I need to read password for the user from other source such as Amazon SSM parameters which is supported from Quarkus release version 2.0.0.Final.

Here is example of two credentials provider implementations:

**MSSQL:**

```
@ApplicationScoped
@Unremovable
@Named("mssql-credentials-provider")
public class MSSQLCredentialsProvider implements CredentialsProvider {

	@ConfigProperty(name = "quarkus.datasource.username")
	private String databaseUserName;	

	@Override
	public Map<String, String> getCredentials(String credentialsProviderName) {		
		Map<String, String> properties = new HashMap<>();		
		try {
			properties.put(USER_PROPERTY_NAME, databaseUserName);
			properties.put(PASSWORD_PROPERTY_NAME, methoToReadPassWordFromOtherSource());
		} catch (Exception e) {
			e.printStackTrace();			
		}
		return properties;
	}
}
```

**Redshift:**

```
@ApplicationScoped
@Unremovable
@Named("redshift-credentials-provider")
public class RedshiftCredentialsProvider implements CredentialsProvider {	

	@ConfigProperty(name = "quarkus.datasource.redshift.username")
	private String redshiftDatabaseUserName;	

	@Override
	public Map<String, String> getCredentials(String credentialsProviderName) {						
		Map<String, String> properties = new HashMap<>();		
		try {
			properties.put(USER_PROPERTY_NAME, redshiftDatabaseUserName);
			properties.put(PASSWORD_PROPERTY_NAME, methoToReadPassWordFromOtherSource());
		} catch (Exception e) {
			e.printStackTrace();			
		}
		return properties;
	}
}
```

The property **_quarkus.datasource.credentials-provider-name_** for both credential provider refer to the correct bean implementation. however at run time, MSSQL credentials provider implementation is getting called for redshift credentials provider. So It looks like it is injecting or invoking default datasource credentials provider every time?

**Pom file:**

```
<?xml version="1.0"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.testcomp.tstproj</groupId>
	<artifactId>tst-prj-api</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<properties>
		<compiler-plugin.version>3.8.1</compiler-plugin.version>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<maven.compiler.source>11</maven.compiler.source>
		<maven.compiler.target>11</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<quarkus-plugin.version>1.12.0.Final</quarkus-plugin.version>
		<quarkus.platform.artifact-id>quarkus-universe-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
		<quarkus.platform.version>1.12.0.Final</quarkus.platform.version>
		<surefire-plugin.version>2.22.1</surefire-plugin.version>	
	</properties>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy-jackson</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-arc</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-resteasy</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5-mockito</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>1.18.16</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>3.12.0</version>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-mssql</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-agroal</artifactId>
		</dependency>		
		<dependency>
			<groupId>com.amazon.redshift</groupId>
			<artifactId>redshift-jdbc42-no-awssdk</artifactId>
			<version>1.2.45.1069</version>
			<exclusions>
				<exclusion>
					<groupId>com.sun.activation</groupId>
					<artifactId>jakarta.activation</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.java-json-tools</groupId>
					<artifactId>msg-simple</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.java-json-tools</groupId>
					<artifactId>jackson-coreutils</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.github.java-json-tools</groupId>
					<artifactId>json-patch</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.module</groupId>
					<artifactId>jackson-modules-base</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.module</groupId>
					<artifactId>jackson-module-jaxb-annotations</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson</groupId>
					<artifactId>jackson-base</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.jaxrs</groupId>
					<artifactId>jackson-jaxrs-base</artifactId>
				</exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.jaxrs</groupId>
					<artifactId>jackson-jaxrs-json-provider</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>org.antlr</groupId>
			<artifactId>antlr4</artifactId>
			<version>4.5.3</version>
			<scope>runtime</scope>
			<optional>false</optional>
		</dependency>
	</dependencies>
	<build>
		<plugins>
			<plugin>
				<groupId>io.quarkus</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
				<version>${quarkus-plugin.version}</version>
				<extensions>true</extensions>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
							<goal>generate-code</goal>
							<goal>generate-code-tests</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>${compiler-plugin.version}</version>
			</plugin>
			<plugin>
				<artifactId>maven-surefire-plugin</artifactId>
				<version>${surefire-plugin.version}</version>
				<configuration>
					<systemPropertyVariables>
						<java.util.logging.manager>org.jboss.logmanager.LogManager
						</java.util.logging.manager>
						<maven.home>${maven.home}</maven.home>
					</systemPropertyVariables>
				</configuration>
			</plugin>
		</plugins>
	</build>
	<profiles>
		<profile>
			<id>native</id>
			<activation>
				<property>
					<name>native</name>
				</property>
			</activation>
			<build>
				<plugins>
					<plugin>
						<artifactId>maven-failsafe-plugin</artifactId>
						<version>${surefire-plugin.version}</version>
						<executions>
							<execution>
								<goals>
									<goal>integration-test</goal>
									<goal>verify</goal>
								</goals>
								<configuration>
									<systemPropertyVariables>
										<native.image.path>${project.build.directory}/${project.build.finalName}-runner
										</native.image.path>
										<java.util.logging.manager>org.jboss.logmanager.LogManager
										</java.util.logging.manager>
										<maven.home>${maven.home}</maven.home>
									</systemPropertyVariables>
								</configuration>
							</execution>
						</executions>
					</plugin>
				</plugins>
			</build>
			<properties>
				<quarkus.package.type>native</quarkus.package.type>
			</properties>
		</profile>
	</profiles>
</project>


```

### Expected behavior

The correct implementation of Credentials provider should be called as per declaration in properties file while creating connection to database.

### Actual behavior

It is always calling the MSSQL custom credentials provider for redshift as in my case above. In my case, I have to first call the MSSQL database which creates MSSQL connection first and then I will call Redshift database. But I don't think that is issue here. Regardless of sequence of operation, it is loading MSSQL credentials provider class for even for redshift 

### How to Reproduce?

Declare the two section of properties like in my example above for custom credentials provider implementation for different databases using Agrol Datasource.

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.1916]

### Output of `java -version`

11.0.2

### Quarkus version or git rev

2.5.1.Final or all versions from 2.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

### Additional information

Can we please get this fixed with high priority? This is related with Agrol DataSource
_No response_

**Comment by gsmet** [comment] 2021-12-09 18:23
@yrodiere any chance you could have a look at this one?

**Comment by yrodiere** [comment] 2021-12-10 08:15
This is weirdly similar to the behavior you would be getting if the configuration property `quarkus.datasource.redshift.credentials-provider-name` was somehow not set, or not processed by Quarkus: Agroal would just pick the first credentials provider it finds (don't ask me why), and that could end up being the MSSQL one.

Can you please provide a small reproducer?

**Comment by yrodiere** [comment] 2021-12-10 10:39
So I tried to reproduce this on my own, but couldn't; it just works as expected: https://github.com/yrodiere/quarkus-quickstarts/tree/credprovtest

Please provide a reproducer.

**Comment by mskulkarni** [comment] 2021-12-11 03:41
@yrodiere I can still reproduce the issue with Quarkus 2.5.1.Final version. Please find attached zip file of code-with-quarkus project. I have modified the pom for dependencies of Redshift and for MSSQL. Check the logs in log file or console. So when you access /hello/mssql rest service, it should load MSSQLCredentialProvider and for /hello/redshift it should load RedshiftCredentialProvider but with 2.5.1.Final version, for /hello/redshift, it still loads MSSQLCredentialProvider.  Please check this in console or logs. The output 
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7696360/code-with-quarkus.zip)
of Rest service is hardcoded just for example. There is MSSQLReposity class which makes connection with MSSQL Agrol Data source and RedshiftRepository class which tries to connect to Redshift Named datasource.

If you just downgrade the version to 1.13.7.Final or 1.12.0.Final then it works perfectly fine. I was facing problem in my local environment for other dependencies when I downgrade the quarkus version in the attached project so I used my own project pom file which works fine. There is slight difference in my pom where I have to also use quarkus plugin version. But my project pom file works fine with lower version of 1.12.0.Final and when I upgrade quarkus version then Credentials provider not working as described in the issue description. I have mentioned my pom file in description.

**Comment by mskulkarni** [comment] 2021-12-13 14:00
@yrodiere Did my reproducer helped you to reproduce the issue? can we have early resolution for this issue?

**Comment by yrodiere** [comment] 2021-12-13 14:44
No, I did not make any progress over the weekend.

Thanks for the reproducer. It does reproduce the problem on my machine. Howeveer, the problem doesn't seem related to credentials, but to the injected datasource: somehow you're getting the MSSQL injected into this:

```
@Inject
@DataSource("redshift")
private final AgroalDataSource dataSource;
```

Which is very obviously wrong. I'm still investigating.

(Also note that you have a line of code printing "Retrieving MSSQL Database connection" in `RedshiftRepository`, which might add to an already confusing situation :) )

**Comment by mskulkarni** [comment] 2021-12-13 15:22
@yrodiere Thanks for reproducing the issue and pointing mistake. :)   It was typo done in hurry. Please find the modified zip here again. Please keep me posted with your findings.
[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7704842/code-with-quarkus.zip)

**Comment by yrodiere** [comment] 2021-12-13 15:47
... and this turns out to be a CDI usage problem.

## What is going on

If you look closely at your logs, you will see this when Quarkus starts:

```
2021-12-13 16:39:02,884 WARN  [io.qua.arc.pro.Injection] (build-9) An injection field must be non-static and non-final - ignoring: org.repository.RedshiftRepository#dataSource
2021-12-13 16:39:02,886 WARN  [io.qua.arc.pro.Injection] (build-9) An injection field must be non-static and non-final - ignoring: org.repository.MSSQLRepository#dataSource
```

(why this is a warning and not an error is beyond me; I don't have time to fight that right now)

What the message means is, this code:

```java
	@Inject
	@DataSource("redshift")
	private final AgroalDataSource dataSource;

	public RedshiftRepository(AgroalDataSource dataSource) {
		this.dataSource = dataSource;
	}
```

Actually gets interpreted as this:


```java
	private final AgroalDataSource dataSource;

        @Inject 
	public RedshiftRepository(AgroalDataSource dataSource) {
		this.dataSource = dataSource;
	}
```

(because the annotations on a final field are ignored, and `@Inject` on the only constructor is implicit)

In the end, the default, MSSQL datasource gets injected into `RedshiftRepository`.

## How to solve this

If you move `@Inject` and the qualifier to the constructor, everything should be solved.


```java
	private final AgroalDataSource dataSource;

	@Inject
	public RedshiftRepository(@DataSource("redshift") AgroalDataSource dataSource) {
		this.dataSource = dataSource;
	}
```

I verified this on your reproducer.

Alternatively, use field injection rather than constructor injection:

```java
	@Inject
	@DataSource("redshift") 
	private AgroalDataSource dataSource;

	public RedshiftRepository() {
	}
```

## Conclusion

I'll close this as invalid. Someone please open another ticket if you think the warning should rather be an error, like me, and have time to argue before the holidays, unlike me.

**Closed by yrodiere** 2021-12-13 15:47 UTC
Labels: kind/bug, env/windows, needs-reproducer, area/agroal

**Comment by mskulkarni** [comment] 2021-12-14 20:20
@yrodiere  Thanks for pointing that out. I have removed the final from variable declaration and it is working fine now with 
Quarkus 2.5.1.Final version. As mentioned earlier, this used to work till older version of Quarkus 1.13.7.Final. I have another observation with the declaration of private fields and Injecting value in those private fields from Configuration properties. While building the attached application above,  It shows this on the console for tests:
```
2021-12-14 14:44:31,578 INFO  [io.qua.arc.pro.BeanProcessor] (build-36) Found unrecommended usage of private members (use package-private instead) in application beans:
        - @Inject field org.provider.RedshiftCredentialsProvider#redshiftDatabasePassword,
        - @Inject field org.provider.RedshiftCredentialsProvider#redshiftDatabaseUserName,
        - @Inject field org.provider.MSSQLCredentialsProvider#databasePassword
        - and 6 more - please enable debug logging to see the full list
```
It should allow injecting configuration values on private fields? I also use Lombok for setter/getters.

**Comment by yrodiere** [comment] 2021-12-15 07:54
1.13.7 was released a long time ago, and Quarkus is moving fast. These changes in behavior were most likely driven by newly discovered limitations of GraalVM (native compilation).

That's the case for private members, in particular: https://quarkus.io/guides/cdi-reference#native-executables-and-private-members
