### ISSUE TITLE
Exception in the java compiler (17.0.2) during deserialization in quarkus-rest-client

### ISSUE THREAD

**Issue by timhurkmans** [quarkusio/quarkus#24630] opened 2022-03-30 09:58 UTC
### Describe the bug

When I am trying to extract the body of a `javax.ws.rs.core.Response` generated by the quarkus-rest-client, to a `ArrayList<Object>` using quarkus-rest-client-jackson, the java compiler throws an exception.

Scenario:
- Given a restclient with a method getResponse, which returns a Response (content does not matter, this is a compile error):
```
@RegisterRestClient(baseUri = "https://stage.code.quarkus.io/api")
public interface MyRestClient
{
    @GET
    @Path("/extensions")
    Response getResponse();
}
```

- When trying to extract part of the response directly to a `List<Object>`:
```return new ArrayList<>(restClient.getResponse().readEntity(new GenericType<>() {}));```

- When trying to compile using `mvn clean compile`
- Then the java compiler throws an exception.

Coincidentally, workarounds which look similar that do not cause a java compiler error:
```
    List<Object> list = restClient.getResponse().readEntity(new GenericType<>() {});
    return new ArrayList<>(list);
```
```
    return restClient.getResponse().readEntity(new GenericType<List<Extension>>() {});
```

### Expected behavior

I expect the code to compile.

### Actual behavior

```
An exception has occurred in the compiler (17.0.2). Please file a bug against the Java compiler via the Java bug reporting page (http://bugreport.java.com) after checking the Bug Database (http://bugs.java.com) for duplicates. Include your program, the following diagnostic, and the parameters passed to the Java compiler in your report. Thank you.
java.lang.NullPointerException: Cannot invoke "com.sun.tools.javac.code.Type.getThrownTypes()" because "tree.meth.type" is null
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitApply(Flow.java:1439)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodInvocation.accept(JCTree.java:1797)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitNewClass(Flow.java:1445)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCNewClass.accept(JCTree.java:1852)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitReturn(Flow.java:1415)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCReturn.accept(JCTree.java:1709)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:57)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitBlock(Flow.java:1188)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCBlock.accept(JCTree.java:1091)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitMethodDef(Flow.java:1154)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCMethodDecl.accept(JCTree.java:921)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.visitClassDef(Flow.java:1117)
	at jdk.compiler/com.sun.tools.javac.tree.JCTree$JCClassDecl.accept(JCTree.java:819)
	at jdk.compiler/com.sun.tools.javac.tree.TreeScanner.scan(TreeScanner.java:49)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$BaseAnalyzer.scan(Flow.java:444)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1532)
	at jdk.compiler/com.sun.tools.javac.comp.Flow$FlowAnalyzer.analyzeTree(Flow.java:1522)
	at jdk.compiler/com.sun.tools.javac.comp.Flow.analyzeTree(Flow.java:222)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1377)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.flow(JavaCompiler.java:1351)
	at jdk.compiler/com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:946)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.lambda$doCall$0(JavacTaskImpl.java:104)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.invocationHelper(JavacTaskImpl.java:152)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:100)
	at jdk.compiler/com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:94)
	at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
	at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
	at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1134)
	at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:187)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)

```

### How to Reproduce?

[java-compiler-crash.zip](https://github.com/quarkusio/quarkus/files/8379428/java-compiler-crash.zip)

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.19041.1415]

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment Temurin-17.0.2+8 (build 17.0.2+8) OpenJDK 64-Bit Server VM Temurin-17.0.2+8 (build 17.0.2+8, mixed mode, sharing)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Maven home: C:\Users\tim\.m2\wrapper\dists\apache-maven-3.8.4-bin\52ccbt68d252mdldqsfsn03jlf\apache-maven-3.8.4 Java version: 17.0.2, vendor: Oracle Corporation, runtime: C:\dev\tools\jdk\openjdk\jdk-17.0.2 Default locale: en_US, platform encoding: Cp1252 OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

### Additional information

I have been trying to reproduce this with a minimal standalone jackson-databind project. Jackson has a similar deserialization feature with `objectMapper.readEntity(new TypeReference<List<Object>>() {})`, but I could not reproduce the java compiler error there. Somehow quarkus-http-client is doing something that trigger this.

Using a custom entity (e.g. MyObject) does not make a difference.

It is also broken in openjdk-17.0.2. However, **openjdk-18 seems to be working**, but that is not supported by Quarkus.

**Comment by michalszynkiewicz** [comment] 2022-03-30 10:28
@timhurkmans can you check if it works if you switch to rest-client-reactive?

**Comment by timhurkmans** [comment] 2022-03-30 12:50
@michalszynkiewicz it throws the same error.

**Comment by michalszynkiewicz** [comment] 2022-03-30 19:42
interestingly, this looks a lot like https://bugs.openjdk.java.net/browse/JDK-8262095 which should be resolved in 17.0.2

**Comment by michalszynkiewicz** [comment] 2022-03-30 20:08
It looks like it's going to be fixed in 17.0.3: https://github.com/openjdk/jdk17u/commit/ccb20347de5918ca6977cd470afee2398e6ff65f

**Comment by michalszynkiewicz** [comment] 2022-03-30 20:21
I don't think there's anything we can do with it on the Quarkus side, I'll close this issue

**Closed by michalszynkiewicz** 2022-03-30 20:21 UTC
Labels: kind/bug, area/rest-client, env/windows

**Comment by jerboaa** [comment] 2022-03-31 16:22
If it is [JDK-8262095](https://bugs.openjdk.java.net/browse/JDK-8262095), though, it's weird that it reproduces with `17.0.2`. The bug is fixed in `17.0.2` :-/

**Comment by jerboaa** [comment] 2022-03-31 16:35
I cannot reproduce with `17.0.3+5` (early access currently). So it should be fixed once `17.0.3` ships in April 2022. For now you can use a build from here to verify it's fixed (worked for me): https://adoptium.net/temurin/nightly/

**Comment by timhurkmans** [comment] 2022-04-01 08:41
Thank you for looking into this.

The `17.0.3+5` beta works. I guess the JDK-8262095 / JDK-8274904 backport has just been mislabelled, as the commit is done after 17.0.2.GA.

Thank you for pointing me to [](https://bugs.openjdk.java.net/) as the url in the error message [](https://bugs.java.net/) does not find anything when searching for parts of the exception message, even though there are bug reports with the exact text in the title (try searching for tree.meth.type).

**Comment by jerboaa** [comment] 2022-04-01 08:52
> The `17.0.3+5` beta works. I guess the JDK-8262095 / JDK-8274904 backport has just been mislabelled, as the commit is done after 17.0.2.GA.

No, the fix is something else that must have gone into 17.0.3/18. I haven't done the analysis what it was. JDK-8262095 is in `17.0.2+1` and better. It's definitely not the bug that fixed this.
