### ISSUE TITLE
Kubernetes Extension Can't Build on Windows

### ISSUE THREAD

**Issue by aelfric** [quarkusio/quarkus#30525] opened 2023-01-21 16:59 UTC
### Describe the bug

Trying to run `mvn package` on Windows with a project configured with the `quarkus-kubernetes` extension, and it fails seemingly due to a space in the "Program Files" directory name.

```
org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<scalar>'
 in 'reader', line 1, column 14:
    'C:\Program' is not recognized as an internal ...
                 ^

    at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce (ParserImpl.java:274)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent (ParserImpl.java:185)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent (ParserImpl.java:175)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode (Composer.java:163)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData (BaseConstructor.java:184)
    at org.yaml.snakeyaml.Yaml.loadFromReader (Yaml.java:477)
    at org.yaml.snakeyaml.Yaml.load (Yaml.java:418)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:237)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:351)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:287)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:272)
    at io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig (Config.java:746)
    at io.fabric8.kubernetes.client.Config.loadFromKubeconfig (Config.java:702)
    at io.fabric8.kubernetes.client.Config.tryKubeConfig (Config.java:616)
    at io.fabric8.kubernetes.client.Config.autoConfigure (Config.java:286)
    at io.fabric8.kubernetes.client.Config.autoConfigure (Config.java:282)
    at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createConfig (KubernetesClientUtils.java:18)
    at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient (KubernetesClientUtils.java:52)
    at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process (KubernetesClientBuildStep.java:16)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:909)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:281)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)
    at java.lang.Thread.run (Thread.java:1589)
    at org.jboss.threads.JBossThread.run (JBossThread.java:501)
```

### How to Reproduce?

Reproducer: https://github.com/aelfric/github-classroom-lti

On windows, run `./mvnw package`

### Output of `uname -a` or `ver`

Windows 11

### Output of `java -version`

openjdk version "19.0.1" 2022-10-18 OpenJDK Runtime Environment Temurin-19.0.1+10 (build 19.0.1+10) OpenJDK 64-Bit Server VM Temurin-19.0.1+10 (build 19.0.1+10, mixed mode, sharing)

### Quarkus version or git rev

2.15.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

### Additional information

Happy to help debug / fix this if someone could point me in the right direction.

**Comment by aelfric** [comment] 2023-01-21 18:03
Update: This issue seems only to occur in the Windows Terminal.  Running it in the normal windows CMD prompt does not have the same issue.

**Comment by geoand** [comment] 2023-01-23 07:41
@manusa this looks like a client bug. Do you know if it's an issue?

**Comment by manusa** [comment] 2023-01-23 08:33
I think it might be partially related to:
- https://github.com/eclipse/jkube/issues/1540
- https://github.com/fabric8io/kubernetes-client/pull/4198

From the stacktrace I understand that the problem is caused when instantiating the client, and that the autoconfiguration part is failing. i.e. the process fails even before generating resources or anything else.

I'm not sure if the issue is caused by the contents of your [`.kube/config`](https://blog.marcnuri.com/where-is-my-default-kubeconfig-file) file which might have an entry to a `C:\Program files`... which might not be strictly compliant with the YAML spec.

Could you please check the file contents and if there's such an entry enclose it with `"` and see if the error persists?

**Comment by aelfric** [comment] 2023-01-23 14:01
Ah...looks like this might be the answer, though wrapping it in quotes didn't fully fix the problem.  I use Digital Ocean as my k8s provider and their config tool added an entry like this (originally without the quotes).

```yaml
command: "C:\Program Files\doctl\doctl.exe"
```
 After adding the quotes, I got a different error about an invalid escape code so I changed `\doctl\doctl.exe` to `\\doctl\\doctl.exe`.  And then I get some other stack trace:

```
[ERROR] Failed to parse the kubeconfig.
org.yaml.snakeyaml.parser.ParserException: expected '<document start>', but found '<scalar>'
 in 'reader', line 1, column 25:
    'C:\Users\aelfr\.kube\' is not recognized as an internal ...
                            ^

    at org.yaml.snakeyaml.parser.ParserImpl$ParseDocumentStart.produce (ParserImpl.java:274)
    at org.yaml.snakeyaml.parser.ParserImpl.peekEvent (ParserImpl.java:185)
    at org.yaml.snakeyaml.parser.ParserImpl.checkEvent (ParserImpl.java:175)
    at org.yaml.snakeyaml.composer.Composer.getSingleNode (Composer.java:163)
    at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData (BaseConstructor.java:184)
    at org.yaml.snakeyaml.Yaml.loadFromReader (Yaml.java:477)
    at org.yaml.snakeyaml.Yaml.load (Yaml.java:418)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:237)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:351)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:287)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal (Serialization.java:272)
    at io.fabric8.kubernetes.client.Config.getExecCredentialFromExecConfig (Config.java:746)
    at io.fabric8.kubernetes.client.Config.loadFromKubeconfig (Config.java:702)
    at io.fabric8.kubernetes.client.Config.tryKubeConfig (Config.java:616)
    at io.fabric8.kubernetes.client.Config.autoConfigure (Config.java:286)
    at io.fabric8.kubernetes.client.Config.<init> (Config.java:251)
    at io.fabric8.kubernetes.client.Config.<init> (Config.java:245)
    at io.fabric8.kubernetes.client.ConfigBuilder.<init> (ConfigBuilder.java:10)
    at io.fabric8.kubernetes.client.ConfigBuilder.<init> (ConfigBuilder.java:7)
    at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createConfig (KubernetesClientUtils.java:20)
    at io.quarkus.kubernetes.client.runtime.KubernetesClientUtils.createClient (KubernetesClientUtils.java:52)
    at io.quarkus.kubernetes.client.deployment.KubernetesClientBuildStep.process (KubernetesClientBuildStep.java:16)
    at jdk.internal.reflect.DirectMethodHandleAccessor.invoke (DirectMethodHandleAccessor.java:104)
    at java.lang.reflect.Method.invoke (Method.java:578)
    at io.quarkus.deployment.ExtensionLoader$3.execute (ExtensionLoader.java:909)
    at io.quarkus.builder.BuildContext.run (BuildContext.java:281)
    at org.jboss.threads.ContextHandler$1.runWith (ContextHandler.java:18)
    at org.jboss.threads.EnhancedQueueExecutor$Task.run (EnhancedQueueExecutor.java:2449)
    at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run (EnhancedQueueExecutor.java:1478)
    at java.lang.Thread.run (Thread.java:1589)
    at org.jboss.threads.JBossThread.run (JBossThread.java:501)

**Comment by geoand** [comment] 2023-01-26 10:16
@manusa ^

**Comment by manusa** [comment] 2023-01-26 10:29
Hi @aelfric 
Could you please provide a _(redacted)_ version of your .kube/config file so that we can create a reproducer test and fix it upstream?
I¡ll create an issue in the Fabric8 repo once you provide the information.

**Comment by aelfric** [comment] 2023-01-28 01:00
This is the one with the escaped `\d` characters 

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: REDACTED
    server: REDACTED
  name: REDACTED
contexts:
- context:
    cluster: REDACTED
    user: REDACTED
  name: REDACTED
current-context: REDACTED
kind: Config
preferences: {}
users:
- name: REDACTED
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=k8s
      - 95523dba-0a36-46c3-bcab-87de681e0097
      command: "C:\Program Files\\doctl\\doctl.exe"
      env: null
      provideClusterInfo: false
```

**Comment by geoand** [comment] 2023-01-28 05:46
Closing this an upstream issue

**Closed by geoand** 2023-01-28 05:46 UTC
Labels: kind/bug, area/kubernetes, env/windows
