### ISSUE TITLE
Error on native build when using quarkus-opentelemetry-exporter-otlp 2.11.x

### ISSUE THREAD

**Issue by anbonifacio** [quarkusio/quarkus#27253] opened 2022-08-11 15:19 UTC
### Describe the bug

When building a project that uses Quarkus 2.11.x, the native build fails on a gRPC related problem (pulled in by io.quarkus:quarkus-opentelemetry-exporter-otlp:jar:2.11.2.Final)

### Expected behavior

The native build should complete correctly as with Quarkus 2.10.x (with the same project, same Java and GraalVM versions)

### Actual behavior

```
[1/7] Initializing...
                                                                                    (0.0s @ 0.22GB)
Error: Could not find target method: private static java.lang.Object io.quarkus.grpc.common.runtime.graal.Target_io_grpc_ServiceProviders.createForHardCoded(java.lang.Class,java.lang.Class)
com.oracle.svm.core.util.UserError$UserException: Could not find target method: private static java.lang.Object io.quarkus.grpc.common.runtime.graal.Target_io_grpc_ServiceProviders.createForHardCoded(java.lang.Class,java.lang.Class)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.util.UserError.abort(UserError.java:72)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.findOriginalMethod(AnnotationSubstitutionProcessor.java:806)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleMethodInAliasClass(AnnotationSubstitutionProcessor.java:423)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleAliasClass(AnnotationSubstitutionProcessor.java:395)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.handleClass(AnnotationSubstitutionProcessor.java:368)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.substitute.AnnotationSubstitutionProcessor.init(AnnotationSubstitutionProcessor.java:324)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.createAnnotationSubstitutionProcessor(NativeImageGenerator.java:941)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.setupNativeImage(NativeImageGenerator.java:854)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.doRun(NativeImageGenerator.java:561)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGenerator.run(NativeImageGenerator.java:521)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.buildImage(NativeImageGeneratorRunner.java:407)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.build(NativeImageGeneratorRunner.java:585)
        at org.graalvm.nativeimage.builder/com.oracle.svm.hosted.NativeImageGeneratorRunner.main(NativeImageGeneratorRunner.java:128)
```

### Output of `uname -a` or `ver`

Darwin M0-83300006.local 21.6.0 Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101 arm64

### Output of `java -version`

openjdk version "18.0.2" 2022-07-19 OpenJDK Runtime Environment Temurin-18.0.2+9 (build 18.0.2+9) OpenJDK 64-Bit Server VM Temurin-18.0.2+9 (build 18.0.2+9, mixed mode)

### GraalVM version (if different from Java)

GraalVM 22.1.0 Java 17 CE (Java Version 17.0.3+7-jvmci-22.1-b06)

### Quarkus version or git rev

2.11.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by brunobat** [comment] 2022-08-16 09:18
Hi @anbonifacio. Do you have a reproducer project?

**Comment by geoand** [comment] 2022-08-23 11:48
I could not reproduce this, so we'll definitely need a reproducer

**Comment by anbonifacio** [comment] 2022-09-08 13:23
Hi, I'm trying to create a reproducer for the issue, but it's more subtle than I expected initially: it is not enough to import just quarkus-opentelemetry-exporter-otlp, so I have to do some trial and error.
By the way we are using a maven multi-module project and the problem is present also with quarkus 2.12.1

**Comment by geoand** [comment] 2022-10-05 07:45
@anbonifacio did you have any luck coming up with the reproducer?

**Comment by geoand** [comment] 2022-10-19 09:27
Closing as we never got a reproducer

**Closed by geoand** 2022-10-19 09:27 UTC
Labels: kind/bug, area/tracing, needs-reproducer

**Comment by geoand** [comment] 2022-12-01 14:02
Thanks for the update
