### ISSUE TITLE
Invalid gzipped body results in 500 instead of 400 error

### ISSUE THREAD

**Issue by jdentonpfpt** [quarkusio/quarkus#43476] opened 2024-09-24 20:15 UTC
### Describe the bug

When gzipped bodies are enabled, and a REST call is made with data that is declared as gzipped by the headers, but is not actually gzipped, we would expect the resulting error to be a 400 Bad Request. Instead, we get a 500 error. This distinction is important, because the 400 code tells the user they did something wrong, where as the 500 suggests the user re-try the same request later.

### Expected behavior

A badly formatted request should result in a 400 error code.

### Actual behavior

A POST body that is claimed to be in gzip format by the headers, but is not actually in gzip format, results in 

500 Internal Server Error "java.io.EOFException"

### How to Reproduce?

Setup an endpoint to receive gzipped post bodies, by setting `quarkus.resteasy.gzip.enabled=true`in application.properties

curl --location --request POST 'https://someurl.com' \
--header 'content-encoding: gzip' \
--header 'Content-Type: application/json' \
--header 'Authorization: Bearer ...' \
--data '@somethingnotgzipped'

### Output of `uname -a` or `ver`

Linux bulk-0 5.15.0-1058-aws #64~20.04.1-Ubuntu SMP Tue Apr 9 11:12:27 UTC 2024 x86_64 Linux

### Output of `java -version`

openjdk version "21.0.3" 2024-04-16 LTS OpenJDK Runtime Environment Zulu21.34+19-CA (build 21.0.3+9-LTS) OpenJDK 64-Bit Server VM Zulu21.34+19-CA (build 21.0.3+9-LTS, mixed mode)

### Quarkus version or git rev

3.11

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /usr/local/Cellar/maven/3.9.8/libexec Java version: 17.0.12, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.12/libexec/openjdk.jdk/Contents/Home Default locale: en_US, platform encoding: US-ASCII OS name: "mac os x", version: "14.7", arch: "x86_64", family: "mac"

**Comment by geoand** [comment] 2024-09-25 05:55
Thanks for reporting.

Can you please attahc a sample application that behaves as you describe?

**Comment by jdentonpfpt** [comment] 2024-10-08 21:27
I really can’t upload my employers proprietary source code. I believe the bug as filed should be sufficient to identify the problem and recreate it.

Jason Denton


From: Georgios Andrianakis ***@***.***>
Date: Tuesday, September 24, 2024 at 11:57 PM
To: quarkusio/quarkus ***@***.***>
Cc: Jason Denton ***@***.***>, Author ***@***.***>
Subject: Re: [quarkusio/quarkus] Invalid gzipped body results in 500 instead of 400 error (Issue #43476)
Thanks for reporting. Can you please attahc a sample application that behaves as you describe? — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread. Message ID: <quarkusio/quarkus/issues/43476/2373094020@ github. com>


Thanks for reporting.

Can you please attahc a sample application that behaves as you describe?

**Comment by geoand** [comment] 2024-10-13 09:07
It doesn't have to be the actual application.

The reason we usually insist on this is that often enough there are subtleties that make reproducing the problem tough.
Moreover, a to the point reproducer also makes it easy for us to create a test that will ensure we don't run into the same problem in the future.

**Comment by geoand** [comment] 2024-11-04 10:03
Closing for lack of a reproducer

**Closed by geoand** 2024-11-04 10:03 UTC
Labels: kind/bug, triage/needs-reproducer
