### ISSUE TITLE
Vert.x 4 - Re-enable the RESTEasy Reactive TCK

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#15912] opened 2021-03-22 06:57 UTC
## Description

The RESTEasy Reactive TCK is not passing with Vert.x 4 and the build is stuck for 180 seconds (so timeout). 
We need to investigate and re-enable it. 

As this is now in the hot path to create the Quarkus 2.x branch, I have disabled the TCK and we will investigate directly in the 2.x branch.

## Implementation ideas

1. Get a lot of coffee
2. Debug

**Comment by geoand** [comment] 2021-03-22 07:11
@cescoffier should I re-enable in the vertx4-snapshot branch?

I don't think I'll have time to look into the failures today, maybe @FroMage or @stuartwdouglas has time?

**Comment by cescoffier** [comment] 2021-03-22 08:02
I just disabled it in the vertx4-snapshot branch, as it's the base for the 2.x branch (_base_ as it's going to the inspiration as we will re-organize the commits).

There is no emergency, it can wait a few weeks. It's not because we would have a 2.x branch that it's going to be release immediately.

**Comment by geoand** [comment] 2021-03-22 08:04
OK, understood :)

**Comment by FroMage** [comment] 2021-03-22 08:51
How many other branches would I need to compile `vertx4-snapshot`?

**Comment by geoand** [comment] 2021-03-22 08:52
I _think_ you don't need anything else - but @cescoffier would know for sure

**Comment by FroMage** [comment] 2021-03-22 08:53
OK let's try

**Comment by cescoffier** [comment] 2021-03-22 08:54
vertx4-snapshot is THE ONE. If only relies on releases. So, just this one.

**Comment by FroMage** [comment] 2021-03-22 09:08
OK I can reproduce

**Comment by FroMage** [comment] 2021-03-22 09:14
I have a feeling this is due to DNS hanging forever for a call to resolve the `cts.tck` host.

**Comment by FroMage** [comment] 2021-03-22 09:19
Yes: we used to get this exception:

```
java.util.concurrent.CompletionException: javax.ws.rs.ProcessingException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'cts.tck' failed to resolve 'cts.tck.inforealm.org' after 2 queries 
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:607)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:591)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:488)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1990)
	at org.jboss.resteasy.reactive.client.handlers.ClientErrorHandler.handle(ClientErrorHandler.java:13)
	at org.jboss.resteasy.reactive.client.handlers.ClientErrorHandler.handle(ClientErrorHandler.java:9)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:122)
	at org.jboss.resteasy.reactive.client.impl.RestClientRequestContext$1.execute(RestClientRequestContext.java:200)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:71)
	at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.resume(AbstractResteasyReactiveContext.java:51)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$2.handle(ClientSendRequestHandler.java:68)
	at org.jboss.resteasy.reactive.client.handlers.ClientSendRequestHandler$2.handle(ClientSendRequestHandler.java:64)
	at io.vertx.core.http.impl.HttpClientRequestBase.handleException(HttpClientRequestBase.java:133)
	at io.vertx.core.http.impl.HttpClientRequestImpl.handleException(HttpClientRequestImpl.java:370)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$null$6(HttpClientRequestImpl.java:472)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
	at io.vertx.core.http.impl.HttpClientRequestImpl.lambda$connect$7(HttpClientRequestImpl.java:471)
	at io.vertx.core.http.impl.HttpClientImpl.lambda$getConnectionForRequest$4(HttpClientImpl.java:1048)
	at io.vertx.core.http.impl.ConnectionManager.lambda$getConnection$7(ConnectionManager.java:159)
	at io.vertx.core.http.impl.pool.Pool.connectFailed(Pool.java:397)
	at io.vertx.core.http.impl.pool.Pool.access$600(Pool.java:89)
	at io.vertx.core.http.impl.pool.Pool$Holder.lambda$connect$0(Pool.java:129)
	at io.vertx.core.impl.FutureImpl.tryFail(FutureImpl.java:195)
	at io.vertx.core.http.impl.HttpChannelConnector.connectFailed(HttpChannelConnector.java:255)
	at io.vertx.core.http.impl.HttpChannelConnector.lambda$doConnect$0(HttpChannelConnector.java:164)
	at io.vertx.core.net.impl.ChannelProvider.lambda$connect$1(ChannelProvider.java:78)
	at io.vertx.core.net.impl.ChannelProvider.lambda$handleConnect$2(ChannelProvider.java:145)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.channel.DefaultChannelPromise.setFailure(DefaultChannelPromise.java:89)
	at io.netty.bootstrap.Bootstrap$2.operationComplete(Bootstrap.java:228)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.setFailure(DefaultPromise.java:109)
	at io.netty.resolver.InetSocketAddressResolver$1.operationComplete(InetSocketAddressResolver.java:62)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsNameResolver.tryFailure(DnsNameResolver.java:930)
	at io.netty.resolver.dns.DnsNameResolver.access$500(DnsNameResolver.java:89)
	at io.netty.resolver.dns.DnsNameResolver$5.operationComplete(DnsNameResolver.java:950)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsResolveContext$1.operationComplete(DnsResolveContext.java:231)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:551)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:608)
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:935)
	at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:886)
	at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:358)
	at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:545)
	at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:64)
	at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:402)
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
	at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:201)
	at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:193)
	at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1223)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:93)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.ws.rs.ProcessingException: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'cts.tck' failed to resolve 'cts.tck.inforealm.org' after 2 queries 
	... 94 more
Caused by: io.netty.resolver.dns.DnsResolveContext$SearchDomainUnknownHostException: Search domain query failed. Original hostname: 'cts.tck' failed to resolve 'cts.tck.inforealm.org' after 2 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:927)
	... 35 more
```

And now, we don't anymore. I can check if we ignore it somewhere, but does it ring a bell @cescoffier ?

**Comment by FroMage** [comment] 2021-03-22 09:38
Yeah, DNS failures were not caught early enough. I've added a fix commit to your branch and re-enabled the TCK. Let me know if you run into further issues?

**Comment by FroMage** [comment] 2021-03-22 09:41
I'm running the TCK locally ATM, will let you know the results.

**Comment by geoand** [comment] 2021-03-22 09:48
> Yeah, DNS failures were not caught early enough. I've added a fix commit to your branch and re-enabled the TCK. Let me know if you run into further issues?

Great find!

**Comment by cescoffier** [comment] 2021-03-22 10:00
Wow.... I knew it, it's always an issue with the ~~firewall~~ DNS

**Comment by FroMage** [comment] 2021-03-22 10:30
There's more:

```
2021-03-22 11:29:43,081 WARN  [io.net.cha.DefaultChannelPipeline] (vert.x-eventloop-thread-31) An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.: io.netty.channel.ChannelPipelineException: io.vertx.core.net.impl.VertxHandler.handlerAdded() has thrown an exception; removed.
```

**Comment by FroMage** [comment] 2021-03-22 10:38
This one is just naughty.

What happens is:

1. we register a failure handler
2. we register a success handler
3. the success handler throws
4. our failure handler is not called

WTF?
What's the workflow then? Do we need to guard every success handler now?

**Comment by cescoffier** [comment] 2021-03-22 12:40
in netty or in vert.x?

**Comment by FroMage** [comment] 2021-03-22 13:15
Vert.x

**Comment by cescoffier** [comment] 2021-03-22 13:19
Which API? 

CC @vietj

**Comment by FroMage** [comment] 2021-03-22 13:24
I'm talking to him on discord, he confirms it's by design that exception handlers are not called if handlers throw. I find that confusing, especially considering `CompletionStage` does, how about Mutiny?

Also I wonder how to handle that, and why it worked in vert.x 3?

**Comment by FroMage** [comment] 2021-03-22 13:38
@cescoffier we used to have a try/catch in our handler, to handle these cases, and you removed it for the vert.x 4 migration, probably assuming the exception handler would get called, but it doesn't. I'll put it back, but I wonder what other similar assumptions you've made elsewhere? Note that I would have made the same assumption, I find the behaviour counter-intuitive.

**Comment by FroMage** [comment] 2021-03-22 13:50
OK, fixed by putting the handler back. Branch now passes the TCK locally.

**Closed by FroMage** 2021-03-22 13:50 UTC
Labels: area/housekeeping, area/resteasy-reactive

**Comment by cescoffier** [comment] 2021-03-22 14:10
Mutiny calls any subsequent failure handler. 

About the removal, yes, I was thinking it would call the handler. My bad, sorry.

**Comment by stuartwdouglas** [comment] 2021-03-22 23:27
> I'm talking to him on discord, he confirms it's by design that exception handlers are not called if handlers throw. I find that confusing, especially considering `CompletionStage` does, how about Mutiny?
> 
> Also I wonder how to handle that, and why it worked in vert.x 3?

Does this mean that QuarkusErrorHandler will no longer take effect? If so how do you do HTTP error handling now if exception handlers are not called?

**Comment by cescoffier** [comment] 2021-03-23 06:24
@stuartwdouglas No, in this case, it should be called. At least I didn't see any failure related to that (do we have tests?)

**Comment by stuartwdouglas** [comment] 2021-03-23 23:15
ok, I was just wondering about that comment above.
