### ISSUE TITLE
Investigate io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase#testClientStreaming

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#16227] opened 2021-04-03 16:10 UTC
`io.quarkus.resteasy.reactive.server.test.stream.StreamTestCase#testClientStreaming` has been disabled in the Vert.x 4 branches due to some random failure on CI. 

Also:
`io.quarkus.resteasy.reactive.jsonb.deployment.test.sse.SseTestCase#testMultiFromMulti`

**Comment by famod** [comment] 2021-04-06 18:57
FWIW, we have seen this test class failing randomly on `main` as well: #15756

**Comment by geoand** [comment] 2021-04-12 08:33
I was periodically able to reproduce this locally but I still don't know what the cause is.

A packet capture seems to show that the server returns the proper data in all cases so judging from that it looks like a client issue.

**Comment by FroMage** [comment] 2021-04-12 08:51
Huh, that could be very helpful, narrows it down quite a lot !

**Comment by geoand** [comment] 2021-04-12 08:57
I'm looking at `MultiInvoker` and I am wondering whether the `MultiRequest` you added is still needed. Asking because it looks like the bug you mention seems to be fixed in Mutiny.
So perhaps the code can be simplified?

**Comment by geoand** [comment] 2021-04-12 09:27
It seems like in the cases of failure, 

https://github.com/quarkusio/quarkus/blob/c37330647fefd5993f568ec5a48de84707bfbc8e/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java#L161

is getting called **before** 

https://github.com/quarkusio/quarkus/blob/c37330647fefd5993f568ec5a48de84707bfbc8e/independent-projects/resteasy-reactive/client/runtime/src/main/java/org/jboss/resteasy/reactive/client/impl/MultiInvoker.java#L170

The thing is that I don't think we even need to have 

```
        connection.closeHandler(v -> {
            multiRequest.emitter.complete();
        });
```

as 

```
        vertxClientResponse.endHandler(v -> {
            multiRequest.emitter.complete();
        });
```

will always be called anyway (and it does seem to always be called **after** the emitting is done).

WDYT @FroMage ?

**Comment by geoand** [comment] 2021-04-12 09:35
FWIW, I ran thousands of tests with the above fix in place and they all passed

**Comment by geoand** [comment] 2021-04-12 09:48
The same thing exact also applies to `SseEventSourceImpl`. I will open a PR

**Comment by geoand** [comment] 2021-04-12 09:53
Here it is: https://github.com/quarkusio/quarkus/pull/16438

**Closed** 2021-04-13 03:29 UTC
Labels: area/resteasy-reactive, kind/bug
