### ISSUE TITLE
Quarkus + Vertx not performing as well as Vertx alone

### ISSUE THREAD

**Issue by lurumbo** [quarkusio/quarkus#10785] opened 2020-07-16 18:26 UTC
Hi Quarkus team!

I have 2 projects that retrieve data from the same postgres DB, running in a docker container, obtained from [Docker Hub](https://hub.docker.com/_/postgres)

1 - Full Vertx
[https://github.com/lurumbo/vertx-demo](https://github.com/lurumbo/vertx-demo)

2 - Quarkus + Vertx (it is actually the Vertx project, plus some adjustments to make it work with Quarkus)
[https://github.com/lurumbo/quarkus-reactive-pg-vertx-demo](https://github.com/lurumbo/quarkus-reactive-pg-vertx-demo)

I performed some stress tests on them with Jmeter and I can't wrap my head around the results

Vertx Results:
[https://github.com/lurumbo/vertx-demo/blob/master/jmeter/vertx.png](https://github.com/lurumbo/vertx-demo/blob/master/jmeter/vertx.png)

Quarkus Results:
[https://github.com/lurumbo/quarkus-reactive-pg-vertx-demo/blob/master/jmeter/quarkus-reactive-pg-vertx.png](https://github.com/lurumbo/quarkus-reactive-pg-vertx-demo/blob/master/jmeter/quarkus-reactive-pg-vertx.png)

The tests were executed with these params:
- Number of Threads (users): 1000
- Ramp-Up Period (in seconds): 0
- Loop Count: 10

What troubles me the most is the diff in the throughput values.
- Vertx: 1776.5/sec
- Quarkus: 1032.0/sec

Can you please help me understand the results?

Shouldn't the metrics be roughly the same?

Why am I getting such a diff in throughput?

Some notes:

I tested it using the runner.jar

Technical info:

- Processor Intel® Core™ i7-8565U CPU @ 1.80GHz × 8
- Memory 15,5 GiB

Thank you very much!

**Comment by geoand** [comment] 2020-07-17 07:05
cc @johnaohara

**Comment by Serkan80** [comment] 2020-07-17 07:25
And here is a similar test (non reactive way) testing/comparing the same functionality with Quarkus, Micronaut & Spring Boot:

https://youtu.be/rJFgdFIs_k8

I have done a similar test as in the video with Quarkus 1.6 and Spring Boot 2.1.x and what I notice is that the througput of both is almost the same without significant differences. Even the memory consumption is almost similar. 

And one thing I’ve also noticed is that Quarkus throughput fluctuates a lot. Sometimes I got 1200/s and on avg 650/s.

**Comment by johnaohara** [comment] 2020-07-17 08:09
@lurumbo Thanks for the sharing your results and demo apps. This is not a scenario that we have run load tests for, so will take a look at what is causing the differences.
One question, is there a reason why the quarkus version is serializing the getUsers() response to a JsonArray and not in the vert.x version?

**Comment by johnaohara** [comment] 2020-07-17 08:15
@Serkan80 This use case covered in the linked video is a different use case to this reported issue.  That test was influenced by the dispatch cost to a thread pool in the Quarkus case, we explain the flawed assumptions in this post: https://quarkus.io/blog/io-thread-benchmark/

Please could you share examples of tests that you have run wrt throughput in a new issue, so that we can objectively evaluate the results and resolve issues in quarkus, if there are issues that need resolving.  Thanks

**Comment by johnaohara** [comment] 2020-07-17 08:15
@Serkan80 This use case covered in the linked video is a different use case to this reported issue.  That test was influenced by the dispatch cost to a thread pool in the Quarkus case, we explain the flawed assumptions in this post: https://quarkus.io/blog/io-thread-benchmark/

Please could you share examples of tests that you have run wrt throughput in a new issue, so that we can objectively evaluate the results and resolve issues in quarkus, if there are issues that need resolving.  Thanks

**Comment by Serkan80** [comment] 2020-07-17 09:18
@johnaohara if my understanding is correct, other frameworks use the IO thread by default and to achieve the same performance in Quarkus you need to rewrite your whole application with Reactive Routes (RR) ? That’s quite annoying and in most cases inapplicable, because RR has serious functional limitations like no out-of-the-box: Bean Validation, Swagger, Security, etc, support. Imho, not very well suited for real world use cases. Instead you can just write everything in plain Vertx, without using Quarkus.

**Comment by johnaohara** [comment] 2020-07-17 09:37
@Serkan80 This reported issue relates to a very specific use case.  If you have a specific performance issue, please open a new issue. Or, if you would like to discuss different paradigms, and what Quarkus could improve on, please start a discussion on the community mailing list.

**Comment by johnaohara** [comment] 2020-07-18 07:03
Have taken a look at the benchmark you shared and I have a number of observations that means the results are not comparable, and there are issues with the methodology which will skew measurements;


1.  The implementations differ slightly in their implementation, the vert.x implementation is returning an ArrayList.toString() in reply across the event bus, and the Quarkus version is returning a JsonArray that you are building when processing the DB response

2.  Quarkus 1.5.2.Final depends on vert.x 3.9.0, whereas the vert.x impl is using vert.x 3.9.1

3.  From the JMeter config shared in the repo and the DB connection parameters, it appears that you are running the database, application and load generation on the same machine.  The JMeter load is configured to use 1000 threads,  Quarkus will be creating 16 event loop threads, and postgres will also be running around 8 threads.  The processor you are running on is a 4core processor, you mention that you have 8 cores, so am assuming you have hyperthreading enabled.  As it currently configured, the test tries to run over 1000 threads on 8 hardware threads in a very short period of time.  There will be a whole range of system-level issues that will skew results with this configuration (i.e. kernel scheduler, cache line misses, power management etc)

4.  The jMeter model being used is 1000 threads in a loop if 10 requests. This is insufficient to generate meaningful data. The 2 implementations need to be warmed up (i.e. ensure that the hot code paths have been jit'd) and measurements need to be run over a longer period of time to amortize system/jvm costs (e.g. GC, power management etc).  I ran jMeter with the number of loops set to "indefinite" and I saw the throughput steadily rising throughout the test.  I do not use jMeter (due to it being affected by the co-ordinated omission problem) so do not know how the tool calculates throughput, but it did not seem to reach a steady-state in reporting measurements.

    When we run load testing, we do not use tools (or configurations) that are susceptible to the co-ordinated omission problem.  Jmeter, with this configuration, will be affected by the co-ordinated omission issue.


I re-ran the 2 scenarios after resolving the issues above by;

1.  Using the same DbVerticle implementation for the vert.x and Quarkus versions
2.  Building the vert.x implementation with vert.x 3.9.0
3.  split the load generation and System Under Test to 2 machines.  Load generation was run on one machine, and appication+db on a different machine
4.  Used wrk to generate load for 20 seconds (after the JVM had been pre-warmed for 60 seconds), with 1000 connections (users) but running 8 threads.
5.  There were 50 entries in the user table

The results I am seeing;


Vert.x 3.9.0 (port 8080)
```
$ wrk -t 8 -c 1000 -d 20s http://localhost:8080/users
Running 20s test @ http://localhost:8080/users
  8 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    25.11ms    1.34ms  34.13ms   83.94%
    Req/Sec     5.00k   208.47     6.15k    79.50%
  796265 requests in 20.04s, 1.46GB read
Requests/sec:  39733.83
Transfer/sec:     74.54MB
```

Quarkus 1.5.2.Final (port 8081)
```
$ wrk -t 8 -c 1000 -d 20s http://localhost:8081/users
Running 20s test @ http://localhost:8081/users
  8 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    26.01ms    1.55ms  61.82ms   83.05%
    Req/Sec     4.83k   215.62     5.62k    76.69%
  768332 requests in 20.04s, 1.41GB read
Requests/sec:  38340.96
Transfer/sec:     71.92MB
```

I recorded some profiles, there are some slight differences in the calls stack where vertx-web has been integrated into quarkus, but applications were not CPU bound and the biggest bottleneck appears to be the db connection pool.

**Comment by johnaohara** [comment] 2020-07-27 10:29
I have not been able to observe a large delta between a vert.x and quarkus load test. I will close for now, but please re-open if there is a reproducer that demonstrates a performance difference.  Thanks

**Closed by johnaohara** 2020-07-27 10:29 UTC
Labels: kind/question
