### ISSUE TITLE
SeeEventSink.isClosed always false

### ISSUE THREAD

**Issue by stgiaf** [quarkusio/quarkus#8858] opened 2020-04-26 02:35 UTC
Hello,
I am facing exactly the issue described in the following github Issue https://github.com/oracle/helidon/issues/806.

So there are two points:
1. When a client disconnects , the sseEventSink.isClosed remains always false
2. The sseEventSink.send().exceptionally() is never called

Since there is no way to catch the exception , the application breaks whenever a client disconnects . Luckily enough the scenario I am using is exactly the same as in the link using Kafka streams but with quarkus.

**Comment by gsmet** [comment] 2020-04-27 11:49
Could you prepare a simple Maven reproducer so that we can have a look? Thanks!

**Comment by stgiaf** [comment] 2020-04-27 16:25
I have created a demo application, how can I share it with you?
Sorry for the dummy question, but I am new to this process.

**Comment by jaikiran** [comment] 2020-05-01 03:10
Hello @stgiaf, you can create a github repo (under your account) for this reproducer application and point us to that github repo.

**Comment by gsmet** [comment] 2020-05-04 14:46
Or you can just attach a zip to a comment :).

**Comment by stgiaf** [comment] 2020-05-05 09:23
Hello @jaikiran ,
I haveant event noticed that you may attach files in comments. The application is attached.

When an sse clients connects a ping is sent every 3 seconds. 
When you disconnect the client, you will notice that there is an excpetion that is not catched by the exceptionally() of the completionStage and the isCLosed() remains false.

[sse-demo-quarkus.zip](https://github.com/quarkusio/quarkus/files/4579889/sse-demo-quarkus.zip)

**Comment by stgiaf** [comment] 2020-05-14 12:07
Hello Sirs,
Did you had the chance to look at the issue? Is it a bug that needs further actions from your side, or is a misuse of the functionality from my side?

**Comment by stgiaf** [comment] 2020-08-25 21:12
Any update?

**Comment by jaikiran** [comment] 2020-08-26 03:34
Hello @stgiaf, I haven't had a chance to look into this and given some other work, I might not be able to get to this soon.

**Comment by pwatson-ott** [comment] 2022-10-08 02:06
I have the same problem in the latest Quarkus builds eg 2.13.1.Final. In Quarkus 2.11.3.Final everything works fine. I believe it is because RestEasy throws an exception while sending to the client which ends up closing the SseEventSink on the server side. In Quarkus 2.13.1.Final there is no RestEasy exception so the server can't tell that the client is disconnected.

**Comment by SHSolution** [comment] 2023-09-12 11:41
Hi,
any news on that? My SseEventSink also never gets closed on server side...so the list of subscribers is growing and growing and I can't remove subscribers anymore.
Using Quarkus version 2.16.7.Final

**Comment by geoand** [comment] 2024-02-27 09:45
@SHSolution have you tried with Quarkus 3.x?
If it's still a problem, please attach a sample so we can start looking into it.

**Comment by SHSolution** [comment] 2024-02-28 09:29
@geoand Hi, no I did not, since our projects are still based on version 2.16.7.Final

**Comment by SHSolution** [comment] 2024-02-28 11:12
we have very big enterprise solutions....that are running versions for a longer time, because upgrading all projects is quite an effort

**Comment by geoand** [comment] 2024-02-28 11:15
Understood

**Comment by geoand** [comment] 2024-04-02 11:05
I am going to close this, please open a new issue if the problem persists with Quarkus 3

**Closed by geoand** 2024-04-02 11:05 UTC
Labels: triage/needs-reproducer
