### ISSUE TITLE
Quarkus 3.1.1 causes Npe when using configinterceptor

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#33884] opened 2023-06-07 19:12 UTC
### Describe the bug

Works in 3.1.0 but not in 3.1.1. Only happens in dev mode. when running with java -jar and the native app it works as expected.

Within a config interceptor, `context.proceed(name)` returns null when it shouldn't.

### Expected behavior

No npe and value present as expected

### Actual behavior

Npe while starting quarkus in dev mode

### How to Reproduce?

https://github.com/manofthepeace/quarkus-configinterceptor-npe

Steps to reproduce:
1- mvn quarkus:dev (will cause the npe)
2- change to quarkus 3.1.0 in pom.xml
3- mvn quarkus:dev (will work)

### Output of `uname -a` or `ver`

 Darwin Kernel Version 21.6.0

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.7+7 (build 17.0.7+7)

### GraalVM version (if different from Java)

n/a

### Quarkus version or git rev

3.1.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.9.1

**Comment by gsmet** [comment] 2023-06-08 06:32
@radcortez that would be one for you (probably to put at the top of the list given it looks like a regression)

**Comment by gsmet** [comment] 2023-06-08 06:42
@manofthepeace thanks for the report, next time please include the whole stacktrace in your report.

@phillip-kruger apparently, the regression is caused by your changes in the Dev UI:

```
Caused by: java.lang.NullPointerException: Cannot invoke "io.smallrye.config.ConfigValue.withValue(String)" because the return value of "io.smallrye.config.ConfigSourceInterceptorContext.proceed(String)" is null
	at org.acme.DummyInterceptor.getValue(DummyInterceptor.java:15)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.PropertyNamesConfigSourceInterceptor.getValue(PropertyNamesConfigSourceInterceptor.java:17)
	at io.smallrye.config.SmallRyeConfigSourceInterceptorContext.proceed(SmallRyeConfigSourceInterceptorContext.java:20)
	at io.smallrye.config.SmallRyeConfig.getConfigValue(SmallRyeConfig.java:323)
	at io.quarkus.devui.deployment.menu.ConfigurationProcessor.getConfigValue(ConfigurationProcessor.java:297)
	at io.quarkus.devui.deployment.menu.ConfigurationProcessor.calculate(ConfigurationProcessor.java:162)
	at io.quarkus.devui.deployment.menu.ConfigurationProcessor.getAllConfig(ConfigurationProcessor.java:96)
	at io.quarkus.devui.deployment.menu.ConfigurationProcessor.createConfigurationPages(ConfigurationProcessor.java:62)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:833)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
```

**Comment by phillip-kruger** [comment] 2023-06-08 06:57
I'll have a look thanks

**Comment by phillip-kruger** [comment] 2023-06-09 01:41
Yea so this is in Dev UI where we find all the properties to show on the screen. (That is why this only happens in dev mode).

**Comment by radcortez** [comment] 2023-06-09 11:21
Even if this only started to happen now, I don't think it is a Quarkus issue.

The custom interceptor implementation causes the NPE. The API, clearly states that a call to `context.proceed(name)` can return `null`:

https://github.com/smallrye/smallrye-config/blob/3.2.1/implementation/src/main/java/io/smallrye/config/ConfigSourceInterceptorContext.java#L11-L18

So the implementation must handle the NPE on its own.

**Comment by phillip-kruger** [comment] 2023-06-09 11:53
Ok, so do we just close ?

**Comment by gsmet** [comment] 2023-06-09 11:55
Ah yes, good catch @radcortez, I thought it was the context being null. Let's close it then.

**Closed by gsmet** 2023-06-09 11:55 UTC
Labels: kind/bug, area/config, triage/regression

**Comment by manofthepeace** [comment] 2023-06-09 12:42
I am a bit surprised by the outcome here. The javadoc states `or {@code null}  if the value isn't present.`

Why is the value not present in dev mode, but was present before, and is present in jar and native?

I feel a bit uneasy adding a null check on something that should be there, and only for devmode. I don't think that because the api can return null, returning null is necessarily ok is it? Because if I add a null check, then my interceptor is literally skipped, and the code wont work as expected.

I must be missing something, but I dont understand why null in the first place, and only in dev mode. It's the first time that I would have to adapt code for dev mode only. Would it be because dev-ui evaluates it too early that quarkus' config are not yet initialized?


many thanks!

**Comment by gsmet** [comment] 2023-06-09 14:30
You have a point. @radcortez any logical explanation?

**Comment by manofthepeace** [comment] 2023-06-09 15:33
I have just tested with the null check. With it the dev-ui shows the default value of the property (30), so the interceptor is indeed skipped, but I also have a log that show it did get the right value later in startup;`(Quarkus Main Thread) Setting quarkus threadpool keep-alive time to 180 seconds` but dev-ui is showing 30. So something is off between reality vs what dev-ui shows I believe.

**Comment by radcortez** [comment] 2023-06-09 15:55
Because the Dev-UI is evaluating the Config at build time, and the property used in the interceptor is runtime, so no value is available. Interceptors added via ServiceLoader are in all config phases: build, static init, and runtime.

**Comment by radcortez** [comment] 2023-06-09 15:59
> I feel a bit uneasy adding a null check on something that should be there, and only for devmode. I don't think that because the api can return null, returning null is necessarily ok is it? Because if I add a null check, then my interceptor is literally skipped, and the code wont work as expected.

Unfortunately, it is not how it works. Since sources can be mutable, there is absolutely no guarantee that a value should be present, so a guard is always required.

**Comment by manofthepeace** [comment] 2023-06-09 16:37
thanks for the explanation. I will add the guards then. Should I open an issue for the dev-ui config editor not showing the right value though?

**Comment by manofthepeace** [comment] 2023-06-09 17:22
issue opened here: https://github.com/quarkusio/quarkus/issues/33945 thanks.
