### ISSUE TITLE
Allow specifying optional config section with YAML configuration

### ISSUE THREAD

**Issue by hrstoyanov** [quarkusio/quarkus#14847] opened 2021-02-05 10:54 UTC
**Describe the bug**
See [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-sers/topic/Option.20configuration.20not.20working.3F)
**Expected behavior**
Optional configuration sections should be allowed with Quarkus YAML config.

**Actual behavior**
I know of no way of specifying optional section with YAML config.

**To Reproduce**
Unpack this project 
[issue_optional_config.zip](https://github.com/quarkusio/quarkus/files/5931906/issue_optional_config.zip)
and follow the instruction [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Option.20configuration.20not.20working.3F)

**Comment by hrstoyanov** [comment] 2021-02-05 11:00
@geoand

**Comment by hrstoyanov** [comment] 2021-02-05 18:33
@geoand thanks for looking into this issue, any chance this gets fixed in 1.11.x?

**Comment by geoand** [comment] 2021-02-05 18:39
Most likely yes, but I can't make any guarantee on which micro it will be in.

**Comment by geoand** [comment] 2021-02-05 21:54
I took a look at this and actually I am not sure I want to go through with it.

The reason is because the semantics of having the config section be Optional are a little hazy.
Say you make the sectional `Optional`, then under what conditional does rhe method return a value? When at least one property is set, when all properties are set?
If you go with the first option (which on the face of it seems the most reasonable), what happens when you invoke a method of that sub section that does not return an Optional but whose property has not been set? 
It just seems to me to be weird to deal with a consistent and non suprising way... I assume that if we do do this, then whatever way it's done, some folks will be surprised by its behavior.

**Comment by hrstoyanov** [comment] 2021-02-06 19:47
@geoand 
Not sure why it is confusing - if an optional section is partially populated, extracting values from non-existing fields should result in default value for the type?

For example, here is what one could expect for the "server" property:

```
sql_proxy:
  name: proxyname
  server:
    mssql:
      //server: localhost - missing
      //user: john - missing
      //password: changeme - missing
      port: 1143
      ...
```

```
 interface MSSQLConfig {
        @ConfigProperty(name = "server")  String server();
        @ConfigProperty(name = "user", defaultValue="smith")  String user();
        @ConfigProperty(name = "password")  @NotBlank String password();
        @ConfigProperty(name = "port") int port();
}
public interface ServerConfig {
    @ConfigProperty(name = "mssql") Optional<MSSQLConfig> mssql();
}
```

I should see:
```
   Optional<MSSQLConfig> optionalMSSQL = ServerConfig.msssql();

   assert optionalMSSQL.isPresent();        //Because the  section in the YAML is there!
   MSSQLConfig mssql = optional.get();    
   String server = mssql.server();                //This is OK, we get NULL, if missing.
   String user = mssql.user();                      //This is OK, we get default value "smith", if missing.
   String passord = mssql.password();       //This is not OK, since value is required but missing. We get runtime exception.
   int port = mssql.port();                            //This is OK, we get 0, if missing . Or Integer.NAN.
```

**What else is a developer to do without optional sections? How would you deal with the case where you want to make MSSQL section optional ?**

**Comment by geoand** [comment] 2021-02-06 20:17
I explained why I think it's confusing, I don't think there is much point in reiterating it.

You mention the default value for the subsections, but what would happen if there is no default value?

The best I can do is give it some thought and get back to you, but I'll be honest, I don't think I'll implement this.

**Comment by geoand** [comment] 2021-02-06 20:22
Another complication is that in MP Config which is used at the lowest level for configuration, there is no support for multi level configuration - as one uses in YAML - so that means that all configuration options are mapped to a flat property structure.
This really complicates things from a YAML point of view.
Unfortunately we can't do much at the moment, but it's certainly a design choice that needs to be reevaluated in the future

**Comment by geoand** [comment] 2021-02-08 08:54
After taking another look at this, I stand by my initial assement. Once we have a redesign of MP Config based on what I mention above, we can have another look at this

**Comment by hrstoyanov** [comment] 2021-02-08 09:22
i tried several hacks this weekend, but nothing worked.. Dumping  MPConfig, will have to create my own parser.

Feel free to close this issue.

**Comment by geoand** [comment] 2021-02-08 09:25
I won't close it as it's a valid feature request. I will gladly implement it once MP Config has the appropriate architecture in place that will allow me to do so.

**Comment by hrstoyanov** [comment] 2021-02-08 09:31
thanks. i appreciate it.

**Comment by geoand** [comment] 2021-02-08 09:34
You bet!

**Comment by radcortez** [comment] 2021-02-09 00:14
@hrstoyanov please check this: https://github.com/smallrye/smallrye-config/pull/489/commits/b6f6fba17e9b43afcd302030c2d3cb65f96943fe. Is this what you are looking for?

I believe that PR will provide the missing pieces to support YAML mapping properly. Please, provide me most complicated mapping and I'll add it as a test case :)

**Comment by hrstoyanov** [comment] 2021-02-13 00:44
Woudl check it this weekend! And TOML (I have not forgotten!) ... You guys rock!

**Comment by radcortez** [comment] 2021-02-19 22:18
This is now supported with SmallRye Config `@ConfigMapping`, so I will consider there is an option to support the expected behaviour (even if it required to use a different API).

Moving forward, we may replace or use as a backend implementation the SR `@ConfigMapping` in the Quarkus `@ConfigProperties`.

@hrstoyanov if you disagree, please reopen.

**Comment by radcortez** [comment] 2021-02-19 22:22
Here is some documentation as well:
https://smallrye.io/docs/smallrye-config/mapping/mapping.html

**Comment by hrstoyanov** [comment] 2021-04-13 15:42
Please re-open based on this onversation:
https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Need.20some.20help.20with.20Smallrye.20ConfigMapping

**Comment by radcortez** [comment] 2021-04-19 15:37
Reopened due to some additional issues found in the implementation.

**Comment by geoand** [comment] 2021-04-20 07:29
What are the additional implementation issues?

**Comment by radcortez** [comment] 2021-04-20 10:25
This is in SR ConfigMapping. We have an issue where when we have defaults set with the annotation at the same level for collection types, the defaults are not being applied properly.

**Comment by geoand** [comment] 2021-04-20 10:43
Understood, thanks

**Comment by radcortez** [comment] 2021-04-21 11:14
@hrstoyanov this will be fixed with https://github.com/smallrye/smallrye-config/pull/550.

**Comment by hrstoyanov** [comment] 2021-04-21 19:13
Thanks @radcortez , will test as soon as itis available in the maven repo!

**Closed** 2021-05-17 16:55 UTC
Labels: area/config, kind/enhancement
