### ISSUE TITLE
Upgrading quarkus 1.0.1 to 1.1.0/1 fails with "Property quarkus.package.runner-suffix not found"

### ISSUE THREAD

**Issue by guldner** [quarkusio/quarkus#6481] opened 2020-01-09 15:43 UTC
**Describe the bug**
After upgrading from 1.0.1 to 1.1.1, running the application fails with 
`java.util.NoSuchElementException: Property quarkus.package.runner-suffix not found`

**Configuration**
```properties
quarkus.package.runner-suffix=-${foo}
```
Same for 1.1.0

https://quarkus.io/guides/all-config#quarkus-core_quarkus.package.runner-suffix

**Comment by gsmet** [comment] 2020-01-09 16:07
/cc @dmlloyd 

Apart from the issue, I wonder if we should try to improve the error message a bit?

**Comment by dmlloyd** [comment] 2020-01-09 17:57
@guldner am I correct in assuming that the property `foo` is not defined in the configuration?

The correct way to express that a property should expand to the empty string if missing would be like this:

```properties
quarkus.package.runner-suffix=-${foo:}
```

That said, the exception message is incorrect, it should be something like `Property quarkus.package.runner-suffix is invalid: Property foo not found`, so that's a legitimate bug IMO.

**Comment by guldner** [comment] 2020-01-09 20:53
Solved. 
@dmlloyd Well, _foo_ is defined. The problem was that I actually had the same property defined for `%dev` with no value:
```properties
quarkus.package.runner-suffix=-${foo}
%dev.quarkus.package.runner-suffix=
```
This doesn't cause any problems on 1.0.1, but fails on 1.1.0.
I can close the issue, unless you want to keep it for improving the error message.

**Comment by dmlloyd** [comment] 2020-01-09 23:58
Aha.  In that case the error message is "correct", but possibly could be worded better.  The explicitly empty profile-specific value overrides the original value, which is intended behavior.

**Comment by geoand** [comment] 2020-01-11 09:52
So should we close this one?

**Comment by dmlloyd** [comment] 2020-01-11 09:53
Yeah I suppose so.

**Closed by dmlloyd** 2020-01-11 09:53 UTC
Labels: area/config, kind/bug
