### ISSUE TITLE
Dev build profile test run fail when using Maven multi module project and dependency with its own unit tests.

### ISSUE THREAD

**Issue by ivlcic** [quarkusio/quarkus#23284] opened 2022-01-30 18:27 UTC
### Describe the bug

When using Maven multi module project for instance:
**multi_proj**:
+- **A_lib** (has JUnit test scope dep)
+- **B_quarkus** (has dependency on **A_lib**)

And when running in **B_quarkus** project:
`./mvnw quarkus:dev`
if pressing [r] tests fail with:

```
2022-01-30 18:49:59,179 INFO  [io.quarkus] (Quarkus Main Thread) getting-started 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.6.3.Final) started in 1.076s. Listening on: http://localhost:8080

2022-01-30 18:49:59,191 INFO  [io.quarkus] (Quarkus Main Thread) Profile dev activated. Live Coding activated.
2022-01-30 18:49:59,191 INFO  [io.quarkus] (Quarkus Main Thread) Installed features: [cdi, resteasy, smallrye-context-propagation, vertx]
2022-01-30 18:50:02,018 ERROR [io.qua.test] (Test runner thread) Internal error running tests: java.util.ServiceConfigurationError: org.junit.platform.engine.TestEngine: org.junit.jupiter.engine.JupiterTestEngine not a subtype
        at java.base/java.util.ServiceLoader.fail(ServiceLoader.java:589)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNextService(ServiceLoader.java:1237)
        at java.base/java.util.ServiceLoader$LazyClassPathLookupIterator.hasNext(ServiceLoader.java:1265)
        at java.base/java.util.ServiceLoader$2.hasNext(ServiceLoader.java:1300)
        at java.base/java.util.ServiceLoader$3.hasNext(ServiceLoader.java:1385)
        at java.base/java.lang.Iterable.forEach(Iterable.java:74)
        at org.junit.platform.launcher.core.LauncherFactory.collectTestEngines(LauncherFactory.java:145)
        at org.junit.platform.launcher.core.LauncherFactory.createDefaultLauncher(LauncherFactory.java:131)
        at org.junit.platform.launcher.core.LauncherFactory.create(LauncherFactory.java:125)
        at io.quarkus.deployment.dev.testing.JunitTestRunner.prepare(JunitTestRunner.java:146)
        at io.quarkus.deployment.dev.testing.ModuleTestRunner.prepare(ModuleTestRunner.java:83)
        at io.quarkus.deployment.dev.testing.TestSupport.runInternal(TestSupport.java:337)
        at io.quarkus.deployment.dev.testing.TestSupport$2.run(TestSupport.java:296)
        at java.base/java.lang.Thread.run(Thread.java:829)
```

If **B_quarkus** project is isloated from multi module then everything works as it should.
Running tests with maven all work w/o issues.

Assumptions:

It seems that class paths which Quarkus uses from multi module Maven project are infected with JUnit5 dep, which in turn produce class loading incompatibility issues when running tests in dev build mode. 
As if JupiterTestEngine is not correct type, even though all versions are the same.

### Expected behavior

Test runner in dev build profile should not fail.

### Actual behavior

When running:
`./mvnw quarkus:dev`
and pressing [r] tests fail.

### How to Reproduce?

1. Unzip example
2. `mvn clean install`
3. cd `getting-started`
4. `./mvnw quarkus:dev`
5. press [r]

[example.zip](https://github.com/quarkusio/quarkus/files/7966598/example.zip)

### Output of `uname -a` or `ver`

Linux bemtem 5.16.2-arch1-1 #1 SMP PREEMPT Thu, 20 Jan 2022 16:18:29 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 OpenJDK Runtime Environment (build 11.0.13+8) OpenJDK 64-Bit Server VM (build 11.0.13+8, mixed mode)

### GraalVM version (if different from Java)

openjdk 11.0.12 2021-07-20 OpenJDK Runtime Environment GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08) OpenJDK 64-Bit Server VM GraalVM CE 21.2.0 (build 11.0.12+6-jvmci-21.2-b08, mixed mode, sharing)

### Quarkus version or git rev

2.6.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

**Comment by stuartwdouglas** [comment] 2022-01-31 00:42
Duplicate of #21226, should be fixed by the linked PR.

**Closed by stuartwdouglas** 2022-01-31 00:42 UTC
Labels: kind/bug, area/maven
