### ISSUE TITLE
OIDC Regression with 1.13.3.Final

### ISSUE THREAD

**Issue by bertrandp** [quarkusio/quarkus#17182] opened 2021-05-12 16:34 UTC
## Describe the bug
Moving from 1.12.2.Final to 1.13.3.Final broke the OIDC authentication on my application.

When I call some endpoint like this one
```
@Path("/api/users")
public class UserResource {

    @Inject
    private SecurityIdentity identity;

    @GET
    @Path("/me")
    @RolesAllowed({ Role.BACK_OFFICE})
    public User getLocationsForUser() {
        return new User(identity);
    }
```
I get an error.

### Expected behavior
1.12.2.Final was fine.

### Actual behavior
`ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-5) HTTP Request to /api/users/me failed, error id: f1f3370a-becd-49bf-a6b2-781e8323aa7c-2: io.quarkus.oidc.OIDCException: Tenant configuration has not been resolved`

### Configuration
```properties
quarkus:
  http:
    cors: true
  oidc:
    auth-server-url: https://my.keycloak.server.com
    client-id: my-client-id
    credentials:
      secret: xxxxxxxxxxxx
    tls:
      verification: none
```

### Quarkus version or git rev
1.13.3.Final
## Additional context
(Add any other context about the problem here.)

**Comment by sberyozkin** [comment] 2021-05-12 17:03
@bertrandp Can you please create a reproducer ? Looks like a timing issue (KC is not ready) - also `1.13.4.Final` should be due shortly - try it please (or try 2.0.0.alpha2)

**Comment by sberyozkin** [comment] 2021-05-14 21:08
@bertrandp Please try `1.13.4.Final` which has been released.
My guess is that it is not a bug - just happened that for ex KC docker image has not loaded in time.
You can control it with `quarkus.oidc.connection-delay`.
Also, in `1.13.3.Final` Quarkus would start without trying to recover when even after `quarkus.oidc.connection-delay` KC is not available - but in `1.13.4.Final` it will attempt to recover

**Comment by bertrandp** [comment] 2021-05-17 08:50
@sberyozkin thanks for the quick reply.

I tried with `1.13.4.Final`, same error.

But ! Trying with a fresh Quarkus project, without many dependencies, it was working fine. Turns out the issue comes from this dependency : 
```
    <dependency>
      <groupId>nl.martijndwars</groupId>
      <artifactId>web-push</artifactId>
      <version>5.1.1</version>
    </dependency>
```
I can't see why it was the cause.
Here is a reproducer if you want to take a look https://github.com/bertrandp/oidc-bug-reproducer

**Comment by sberyozkin** [comment] 2021-05-17 11:48
Hi @bertrandp Thanks - so this 3rd party library is affecting the ability of `quarkus-oidc` to connect to Keycloak - but this is an external impact - may be it c - all `quarkus-oidc` does it creates an HTTP request to the KC well-known config endpoint - if it fails then it will try to recover. 
I don't have time to look into why that library is affecting it - but I'll keep this issue open for longer - please investigate if you'd like

**Comment by sberyozkin** [comment] 2021-06-03 15:19
@bertrandp let me close it now - if you can find a way to improve quarkus-oidc to avoid such side-effects - please let us know :-)

**Closed by sberyozkin** 2021-06-03 15:19 UTC
Labels: area/oidc, kind/bug
