### ISSUE TITLE
Regression: OAS openapi.json references broken due to redirect to /q

### ISSUE THREAD

**Issue by tarilabs** [quarkusio/quarkus#14307] opened 2021-01-14 21:07 UTC
**Describe the bug**
We use Eclipse Microprofile annotations to supply additional OAS definitions to the generated OpenApi.
Since Quarkus 1.11 redirection to `/q` for OpenApi definition, any OAS `$ref` would break since the relative path do not longer follow the expected convention.

**Expected behavior**
Either OAS `$ref` get reconciled following the relocation of the expected default (`/openapi.json`)
Either if explicitly set property `quarkus.smallrye-openapi.path=/openapi.json` it is respected by Swagger UI ?

**Actual behavior**
The included `$ref` which would have worked without `/q` redirect, is no longer resolved.

**To Reproduce**

A basic Quarkus app with a REST endpoint like:

```java
...
    @POST
    @Path("/")
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @org.eclipse.microprofile.openapi.annotations.parameters.RequestBody(content = @org.eclipse.microprofile.openapi.annotations.media.Content(mediaType = "application/json", schema = @org.eclipse.microprofile.openapi.annotations.media.Schema(ref = "dmnDefinitions.json#/definitions/InputSet")), description = "DMN input")
    @org.eclipse.microprofile.openapi.annotations.responses.APIResponse(content = @org.eclipse.microprofile.openapi.annotations.media.Content(mediaType = "application/json", schema = @org.eclipse.microprofile.openapi.annotations.media.Schema(ref = "dmnDefinitions.json#/definitions/OutputSet")), description = "DMN output")
    public Object dmn(java.util.Map<String, Object> variables) {
      // 
    }
...
```

and a `dmnDefinitions.json` in `META-INF/resources` of said Quarkus app.

Step1 (please notice I type `http://localhost:8080/swagger-ui/`)
![image](https://user-images.githubusercontent.com/1699252/104649161-9216c580-56b4-11eb-97bf-2f56d7c81287.png)

Step2
![image](https://user-images.githubusercontent.com/1699252/104649222-ac50a380-56b4-11eb-8102-0f8c623406b3.png)

**Configuration**
As defaults, or i.e.:
```properties
quarkus.smallrye-openapi.path=/openapi.json
quarkus.swagger-ui.path=/swagger-ui
quarkus.swagger-ui.always-include=true
```

**Screenshots**
(above)

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.11.0.Beta2
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven

**Additional context**

A workaround would be to make `$ref` prefixed with `../` so that instead of:
```java
@org.eclipse.microprofile.openapi.annotations.media.Schema(ref = "dmnDefinitions.json#/definitions/OutputSet"))
```
have instead:
```java
@org.eclipse.microprofile.openapi.annotations.media.Schema(ref = "../dmnDefinitions.json#/definitions/OutputSet"))
```

but it's not clear which default shall be enforced/expected for the ref (for example if explicitly defined in the configuration file)

Reporting regression, and asking for guidance how to properly define MP annotation ref for REST endpoints.
Thanks!

**Comment by famod** [comment] 2021-01-14 23:18
As a workaround, you could try to disable this redirection entirely: https://github.com/quarkusio/quarkus/issues/14066#issuecomment-752224560

**Comment by phillip-kruger** [comment] 2021-01-15 05:07
Hi @tarilabs.
Thanks for this, I'll look at it. I am wondering if ref would work (in 1.10.x - so before the `/q` change) if you set a custom http root (`quarkus.http.root-path=foo`).

I think you might have the same issue then and we just never had that scenario. 

This might require a fix in SmallRye, I'll investigate.

**Comment by phillip-kruger** [comment] 2021-01-15 06:43
Hi @tarilabs - do have a reproducer ? 
What happens if you change the code to 
`@org.eclipse.microprofile.openapi.annotations.parameters.RequestBody(content = @org.eclipse.microprofile.openapi.annotations.media.Content(mediaType = "application/json", schema = @org.eclipse.microprofile.openapi.annotations.media.Schema(ref = "/dmnDefinitions.json#/definitions/InputSet")), description = "DMN input")`

(Add the `/` when ref the json.

**Comment by phillip-kruger** [comment] 2021-01-15 06:51
OK, I think this is not a bug. 

Up until now you have been lucky that both `dmnDefinitions.json` and the generated openapi doc has been served from `/`.
So the URL used in your code is relative to current. 

You have a few options:

1) change the URL in your code to be relative to the domain (add the `/`)
2) change the location in `META-INF/resources` (so add a folder called `q` and add the file in there)
3) disable the `/q` path as @famod suggested.

The nice thing about having `/q` is that you can secure that path and all non-application related stuff is secured. I would thing option 1 is the correct way to do this.

@MikeEdgar - any thought ?

**Comment by tarilabs** [comment] 2021-01-15 08:59
Hi, first thank you all for the prompt feedback, that's awesome :)

I still believe there is a bug, I will try to better frame my point based on this feedback.

---

> As a workaround, you could try to disable this redirection entirely

If I add this to configuration:
```
quarkus.http.redirect-to-non-application-root-path=false
quarkus.http.non-application-root-path=/
```
then everything works as I expected:
![image](https://user-images.githubusercontent.com/1699252/104697416-03379680-5710-11eb-9fd1-d7a0bda40d1b.png)

that is, Swagger UI is fetching `openapi`, which in turn contains the Ref, which is resolved as expected.

---

> Up until now you have been lucky that both dmnDefinitions.json and the generated openapi doc has been served from /.
> So the URL used in your code is relative to current.

I think it depends on the definition of "lucky" :) frankly this was the intended behaviour I wanted to implement: since I know there is the main OAS openapi defintiion served at `/openapi` at least for the default, then the `$ref` is relative being on the same "folder" (root) didn't require any prefix, not even `/`.

---

> 1. change the URL in your code to be relative to the domain (add the /)

I've done a dirty test and also this seems to work, but is it compliant with the OAS/Swagger specification?
My understanding is that Ref must be relative by looking at this paragraph: [$ref Syntax](https://swagger.io/docs/specification/using-ref/)

The test.
I get the browser to `http://localhost:8080/swagger-ui` and I get UI and openapi redirection:
![image](https://user-images.githubusercontent.com/1699252/104698672-0469c300-5712-11eb-90cc-9e943140751f.png)
okay now I open the `test` endpoint:
![image](https://user-images.githubusercontent.com/1699252/104698899-4b57b880-5712-11eb-9411-c6a0fd5ab63d.png)
As expected
![image](https://user-images.githubusercontent.com/1699252/104699006-6a564a80-5712-11eb-8a3a-bf204ac391aa.png)

---

> 2. change the location in META-INF/resources (so add a folder called q and add the file in there)

I don't think this is a valid option, since per my configuration the OAS is still served from `/openapi` and works correctly:
![image](https://user-images.githubusercontent.com/1699252/104702086-cbcbe880-5715-11eb-9c53-cbb0affcca35.png)

so if I change now the referenced resource to please Quarkus' Swagger UI, it would break when external clients access the referenced resource, isn't it ?

## In summary

I have two questions based on this feedback, please.

Q1. Is it allowed in OAS openapi a `$ref` starting with `/` ? My understanding is that Ref must be relative by looking at this paragraph: [$ref Syntax](https://swagger.io/docs/specification/using-ref/) and starting with `/` in my understanding was not really compliant. I would be happy to be told I interpreted that wrong :) and that I could indeed use `$ref` starting with `/` signifying locate the document starting from the root of "this server and same protocol"

Q2. regardless of the question above, isn't the Quarkus' Swagger UI behaviour wrong?
See my feedback above, when the configuration is explicit for `/openapi`.
I open the browser to `http://localhost:8080/swagger-ui`
It get redirected to `http://localhost:8080/q/swagger-ui` okay, somehow the `/q/openapi` in the top bar fetches content from `/openapi` (from configuration) but it fails to update the intenal references?

I believe the behaviour in Q2 is still the bug?

**Comment by phillip-kruger** [comment] 2021-01-15 10:01
Hi @tarilabs .

Q1) I think it's perfectly valid to start with /. It's just a URL, and /foo is a valid URL. So in terms of URLs:
- If you use just filename, it's relative to the source (openapi).
- If you use /filename, it's relative to the domain/host 
- If you use a full URL (http://...) then if will reference it remotely.

From https://swagger.io/docs/specification/using-ref/:


>     Local Reference – $ref: '#/definitions/myElement' # means go to the root of the current document and then find elements definitions and myElement one after one.
>     Remote Reference – $ref: 'document.json' Uses the whole document located on the same server and in the same location.
>         The element of the document located in the same folder – $ref: 'document.json#/myElement'
>         The element of the document located in the parent folder – $ref: '../document.json#/myElement'
>         The element of the document located in another folder – $ref: '../another-folder/document.json#/myElement'
>     URL Reference – $ref: 'http://path/to/your/resource' Uses the whole document located on the different server.
>         The specific element of the document stored on the different server – $ref: 'http://path/to/your/resource.json#myElement'
>         The document on the different server, which uses the same protocol (for example, HTTP or HTTPS) – $ref: '//anotherserver.com/files/example.json'

So again, I think you have been "lucky" that both openapi and your static file has been served from the same place.

Q2: Please double check browser cache. I think it might be that.

**Comment by tarilabs** [comment] 2021-01-15 10:10
Hi @phillip-kruger 
thank you for the feedback, especially for A1 !

Re Q2, all the screenshot from https://github.com/quarkusio/quarkus/issues/14307#issuecomment-760764016 are with Incognito mode, hence no cache at play.
I truly believe the Quarkus' Swagger UI has a bug in its behaviour.

**Comment by tarilabs** [comment] 2021-01-15 10:32
I am now doubtful of my statement for Q2, I believe I have some misunderstanding there.
I will try in the next days to just double check specifically for Q2.

For the main intent and purpose of this issue, the answer from @phillip-kruger about Q1/A1 solves my issue 👍

**Comment by phillip-kruger** [comment] 2021-01-15 10:35
Thanks @tarilabs - closing. Please reopen if there are further concerns.

**Closed by phillip-kruger** 2021-01-15 10:35 UTC
Labels: area/openapi, area/smallrye, kind/bug
