### ISSUE TITLE
IllegalStateException: Can't set the context safety flag

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#24904] opened 2022-04-12 21:35 UTC
### Describe the bug

After a short time of running, our quarkus-service throws following exception:

```console
2022-04-12 20:58:31,843 ERROR [io.qua.ver.cor.run.VertxCoreRecorder] (vert.x-eventloop-thread-0) Uncaught exception received by Vert.x: java.lang.IllegalStateException: Can't set the context safety flag: the current context is not a duplicated context
  |   | at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.setContextSafe(VertxContextSafetyToggle.java:107)
  |   | at io.quarkus.vertx.core.runtime.context.VertxContextSafetyToggle.setCurrentContextSafe(VertxContextSafetyToggle.java:94)
  |   | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:504)
  |   | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$12.handle(VertxHttpRecorder.java:501)
  |   | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:161)
  |   | at io.quarkus.vertx.http.runtime.VertxHttpRecorder$1.handle(VertxHttpRecorder.java:143)
  |   | at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:67)
  |   | at io.vertx.core.http.impl.Http1xServerRequestHandler.handle(Http1xServerRequestHandler.java:30)
  |   | at io.vertx.core.http.impl.Http1xServerConnection.lambda$handleNext$1(Http1xServerConnection.java:225)
  |   | at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:50)
  |   | at io.vertx.core.impl.ContextImpl.emit(ContextImpl.java:274)
  |   | at io.vertx.core.impl.EventLoopContext.emit(EventLoopContext.java:22)
  |   | at io.vertx.core.http.impl.Http1xServerConnection.handleNext(Http1xServerConnection.java:222)
  |   | at io.vertx.core.http.impl.Http1xServerConnection.responseComplete(Http1xServerConnection.java:207)
  |   | at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
  |   | at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
  |   | at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
  |   | at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
  |   | at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
  |   | at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
  |   | at java.lang.Thread.run(Thread.java:833)
  |   | at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:597)
  |   | at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:194)
```

I don't know when and why this exception occurs. It started after the upgrade to Quarkus 2.8.0.Final.
The application is native-build.

We are using following dependecies from quarkus:
```gradle
    implementation 'io.quarkus:quarkus-jdbc-postgresql'
    implementation 'io.quarkus:quarkus-container-image-jib'
    implementation 'io.quarkus:quarkus-smallrye-openapi'
    implementation 'io.quarkus:quarkus-smallrye-health'
    implementation 'io.quarkus:quarkus-hibernate-orm-panache'
    implementation 'io.quarkus:quarkus-resteasy'
    implementation 'io.quarkus:quarkus-resteasy-jackson'
    implementation 'io.quarkus:quarkus-rest-client'
    implementation 'io.quarkus:quarkus-rest-client-jackson'
    implementation 'io.quarkus:quarkus-liquibase'
    implementation 'io.quarkus:quarkus-arc'
    implementation 'io.quarkus:quarkus-micrometer-registry-prometheus'
    implementation 'io.quarkus:quarkus-scheduler'
```

### Actual behavior

After the exception occures, a lot of requests are running into timeout when calling the api.

### How to Reproduce?

I currently don't know how to reproduce it as I don't know why or where this happens.

### Output of `java -version`

17

### GraalVM version (if different from Java)

22.0

### Quarkus version or git rev

2.8.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

gradle

**Comment by cescoffier** [comment] 2022-04-13 05:39
Already fixed. It's a duplicate of https://github.com/quarkusio/quarkus/issues/24626.

**Closed by cescoffier** 2022-04-13 05:39 UTC
Labels: kind/bug, area/container-image
