### ISSUE TITLE
Enable to config quarkus.http.root-path at runtime both jvm/navite mode

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#23992] opened 2022-02-26 16:24 UTC
### Description

Any version quarkus can not support change quarkus.http.root-path at runtime.
but quarkus.http.port can be changed at runtime,  why?

**Comment by gastaldi** [comment] 2022-02-27 01:46
Duplicate of https://github.com/quarkusio/quarkus/issues/13621

**Closed by gastaldi** 2022-02-27 01:46 UTC
Labels: kind/enhancement, triage/needs-triage
