### ISSUE TITLE
Split package usage: `io.smallrye.reactive.messaging`

### ISSUE THREAD

**Issue by jsmrcka** [quarkusio/quarkus#21912] opened 2021-12-03 10:59 UTC
### Describe the bug

Quarkus reports split package `io.smallrye.reactive.messaging` in
`io.smallrye.reactive:smallrye-reactive-messaging-api`,
`io.smallrye.reactive:smallrye-reactive-messaging-provider`

### Expected behavior

No "split package" warning.

### Actual behavior

```
[WARNING] [io.quarkus.arc.deployment.SplitPackageProcessor] Detected a split package usage which is considered a bad practice and should be avoided. Following packages were detected in multiple archives: 
- "io.smallrye.reactive.messaging" found in [io.smallrye.reactive:smallrye-reactive-messaging-api::jar, io.smallrye.reactive:smallrye-reactive-messaging-provider::jar]
```

### How to Reproduce?

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.5.1.Final:create -DprojectGroupId=org.acme -DprojectArtifactId=smallrye-reactive-messaging-reproducer -Dextensions="smallrye-reactive-messaging"
cd ./smallrye-reactive-messaging-reproducer/
mvn clean package
```

### Output of `uname -a` or `ver`

Linux 5.15.5-200.fc35.x86_64

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.5.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.3 (ff8e977a158738155dc465c6a97ffaf31982d739)

**Comment by cescoffier** [comment] 2021-12-03 11:00
Already fixed in the latest reactive messaging release. It should be fixed in 2.5.1.

**Comment by rsvoboda** [comment] 2021-12-03 13:40
The issue is filed against Quarkus 2.5.1.Final. @cescoffier can you find the update PR to see if it got to 2.5.1.Final?

**Comment by cescoffier** [comment] 2021-12-03 17:27
@rsvoboda https://github.com/quarkusio/quarkus/pull/21711

**Comment by cescoffier** [comment] 2021-12-03 17:27
So, 2.6

**Comment by rsvoboda** [comment] 2021-12-06 07:22
Thanks, added comment to the PR about migration guide entry and noteworthy label

**Comment by cescoffier** [comment] 2021-12-06 08:39
Thanks @rsvoboda !

**Closed by cescoffier** 2021-12-06 08:39 UTC
Labels: kind/bug, area/smallrye, area/reactive-messaging
