### ISSUE TITLE
@EntityGraph support in Quarkus Extension for Spring Data JPA?

### ISSUE THREAD

**Issue by va575** [quarkusio/quarkus#31311] opened 2023-02-21 08:51 UTC
### Description

Just tried out Quarkus Extension for Spring Data JPA and found that @EntityGraph is not supported in Quarkus, but it is available in the Spring version of Spring Data JPA. This could be useful to eager fetch entities at repository level (instead of entity level) and hence reduce the number of queries generated.

Just wanted to know why this was removed from the quarkus version of Spring Data JPA? Are there plans to include this in future?

Note: I could also see many other files being removed from the package "org.springframework.data.jpa.repository" i.e. present in Spring data JPA but not in Quarkus .

**Comment by geoand** [comment] 2023-02-21 08:53
Thanks for reporting.

I am going to close this as a duplicate of https://github.com/quarkusio/quarkus/issues/25333

**Closed by geoand** 2023-02-21 08:53 UTC
Labels: kind/enhancement, area/spring
