### ISSUE TITLE
[2.0.0.CR3]Unable to determine the proper baseUrl/baseUri for RestClient.

### ISSUE THREAD

**Issue by dicolasi** [quarkusio/quarkus#17807] opened 2021-06-09 14:51 UTC
## Describe the bug

Unable to determine the proper baseUrl/baseUri for RestClient.

### Expected behavior
Base uri/url fetched from application.properties

### Actual behavior

Quarkus won't start and fails with the following error:

Caused by: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'demand-stats-service/mp-rest/url' or 'demand-stats-service/mp-rest/uri' to your Quarkus configuration

### Configuration

```
  <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
    <quarkus-plugin.version>2.0.0.CR3</quarkus-plugin.version>
    <quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
    <quarkus.platform.group-id>io.quarkus</quarkus.platform.group-id>
    <quarkus.platform.version>2.0.0.CR3</quarkus.platform.version> 

    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
    </dependency>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-rest-client-reactive</artifactId>
    </dependency>
```

```
package xyz.property.service;

import io.micrometer.core.lang.NonNull;
import io.quarkus.oidc.client.reactive.filter.OidcClientRequestReactiveFilter;
import io.smallrye.mutiny.Uni;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import xyz.property.model.DemandStats;

import javax.ws.rs.GET;
import javax.ws.rs.Path;
import javax.ws.rs.Produces;
import javax.ws.rs.QueryParam;
import javax.ws.rs.core.MediaType;

@RegisterRestClient(configKey = "demand-stats-service")
@RegisterProvider(OidcClientRequestReactiveFilter.class)
public interface DemandStatsService {

    @GET
    @Path("/demand")
    @Produces(MediaType.APPLICATION_JSON)
    Uni<DemandStats> getStatsByPostCode(@NonNull @QueryParam("postcode") String postcode);
}
```

```
#Rest client
yield-stats-service/mp-rest/uri=${provider.yield-stats.api.uri}
demand-stats-service/mp-rest/uri=${provider.demand-stats.api.uri}
growth-stats-service/mp-rest/uri=${provider.growth-stats.api.uri}
```

**Comment by dicolasi** [comment] 2021-06-09 14:51
cc @radcortez

**Comment by gsmet** [comment] 2021-06-09 15:00
It would probably be better with a reproducer as we have no idea where `provider.demand-stats.api.uri` comes from.

**Comment by gsmet** [comment] 2021-06-09 15:23
the fact that is internal is not an issue given it fails before that. But given you are using properties, it would be better to have a reproducer (with fake URLs).

**Comment by michalszynkiewicz** [comment] 2021-07-23 10:32
1.5 months later, we have no reproducer. We have tests for similar configurations, I will close this issue. Please reopen if you find time to create a reproducer.

**Comment by michalszynkiewicz** [comment] 2021-07-23 21:41
@radcortez do you know more about this issue?

**Comment by radcortez** [comment] 2021-07-23 21:48
Sorry, I think I've opened this by mistake.

**Comment by dometec** [comment] 2022-04-27 15:21
Hi Guys, I get the same exception using Quarkus 2.7.5.Final. This is a non reproducible bug, at restart sometime happen and sometime no.

**Comment by michalszynkiewicz** [comment] 2022-04-27 19:13
@dometec can you create and attach a reproducer which (even occasionally) reproduces the problem?

**Comment by geoand** [comment] 2022-07-05 07:13
Closing as we never got a reproducer. We can reopen if we can a reproducer (that at least sporadically reproduces the problem)

**Closed by geoand** 2022-07-05 07:13 UTC
Labels: kind/bug, area/rest-client, needs-reproducer

**Comment by uugan** [comment] 2024-02-02 02:24
This error still appears in quarkus 3.3.0, while running tests.

Caused by: jakarta.enterprise.inject.CreationException: Error creating synthetic bean [weKBylYFn3ICKA_y8Y_7hp3qwp0]: java.lang.IllegalArgumentException: Unable to determine the proper baseUrl/baseUri. Consider registering using @RegisterRestClient(baseUri="someuri"), @RegisterRestClient(configKey="orkey"), or by adding 'quarkus.rest-client."service".url' or 'quarkus.rest-client."service".uri' to your Quarkus configuration


```java
@RegisterRestClient(configKey = "service")
@RegisterProvider(SvClientRequestFilter.class)
@RegisterProvider(HttpFilter.class)
public interface SVProxy {
...
}

//----- testing ---

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

@QuarkusTest
class OrderFunctionsTest {
    @Test
    void test() {
        Assertions.assertEquals(1, 1);
    }
```
