### ISSUE TITLE
Maven Devmode in Quarkus 1.10.0 not working when maven-toolchains-plugin is configured

### ISSUE THREAD

**Issue by sebthom** [quarkusio/quarkus#13484] opened 2020-11-25 20:12 UTC
**Describe the bug**
When migrating from Quarkus 1.9.2.Final to 1.10.0.Final launching our maven projects (which have the [maven-toolchains-plugin](https://maven.apache.org/plugins/maven-toolchains-plugin/) configured) in dev mode fails.

**Expected behavior**
Executing `mvn quarkus:dev` should not fail to launch the application with Quarkus 1.10.0.Final

**Actual behavior**
Executing `mvn quarkus:dev` with Quarkus 1.10.0.Final
 results in:
```
C:\>mvn quarkus:dev
[INFO] Scanning for projects...
[INFO]
[INFO] --------------------------< com.example:test >--------------------------
[INFO] Building test 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- quarkus-maven-plugin:1.10.0.Final:dev (default-cli) @ test ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  1.387 s
[INFO] Finished at: 2020-11-25T20:56:53+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:1.10.0.Final:dev (default-cli) on project test: Unable to execute mojo: The parameters 'toolchains' for goal org.apache.maven.plugins:maven-toolchains-plugin:3.0.0:toolchain are missing or invalid -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).](url)

Or attach an archive containing the reproducer to the issue.

1. create a ~/.m2/toolchains.xml file containing
   ```xml
	<?xml version="1.0" encoding="ISO-8859-1"?>
	<toolchains>
		<toolchain>
			<type>jdk</type>
			<provides>
				<version>11</version>
				<vendor>openjdk</vendor>
			</provides>
			<configuration>
				<jdkHome>/path/to/java11</jdkHome>
			</configuration>
		</toolchain>
	</toolchains>
   ```
1. unzip the [test-project.zip](https://github.com/quarkusio/quarkus/files/5599063/test-project.zip)
1. run `mvn quarkus:dev` in the project folder

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.18363.1139]
 - Output of `java -version`: openjdk version "11.0.9.1" 2020-11-04 LTS
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: Quarkus 1.10.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Additional context**
The issue might be introduced via https://github.com/quarkusio/quarkus/pull/12973

**Comment by gsmet** [comment] 2020-11-30 19:03
@aloubyansky could it be due to the same patch causing the issue with the arguments?

**Comment by aloubyansky** [comment] 2020-11-30 20:13
@sebthom you should adjust the toolchain plugin config. I.e. the `configuration` element should be moved out of the `executions`.
The reason it didn't fail in 1.9.2.Final is because the toolchain was completely ignored there. It was fixed in 1.10.0.CR1 with https://github.com/quarkusio/quarkus/pull/12973
However, be aware of https://github.com/quarkusio/quarkus/issues/12943. Toolchain isn't supported for the packaging currently.

**Comment by sebthom** [comment] 2020-12-01 00:39
@aloubyansky I can move the configuration element out of the executions element, as a workaround, however leaving it where it is is perfectly legal and should be handled correctly by quarkus. as background: we are using multiple execution elements with different configurations bound to different life cycle phases in our parent pom. so we can use different jdks for compilation, unit and integration tests.

**Comment by aloubyansky** [comment] 2020-12-01 08:41
@sebthom yes, we are not picking execution configs. This https://github.com/quarkusio/quarkus/pull/13577 should fix it. At least it works for your reproducer.

**Closed** 2020-12-02 12:42 UTC
Labels: area/devmode, area/maven, env/windows, kind/bug
