### ISSUE TITLE
log output not in log file when enabled

### ISSUE THREAD

**Issue by genehi** [quarkusio/quarkus#6622] opened 2020-01-18 14:52 UTC
**Describe the bug**
After setting quarkus.log.file.enable=true in application properties, very minimal entries are logged
The lines that are written into the log file are not shown in console, seems to be very strange filtering
Also, when setting quarkus.log.file.rotation.max-file-size=500M, logs are rotated every 8K

**Configuration**
```properties
quarkus.log.file.enable=true
quarkus.log.file.rotation.max-file-size=500M
```

 - Quarkus version or git rev: 1.1.1.Final

**Comment by rsvoboda** [comment] 2020-01-24 11:54
Everything works for me as expected, I don't see the behavior you are describing here.
I used quarkus generated app and tried various options.

[my-quarkus-project.zip](https://github.com/quarkusio/quarkus/files/4108228/my-quarkus-project.zip)
I tried 1.1.1.Final and also 1.2.0.Final and both are working well

```
mvn package

java -Dquarkus.log.file.enable=true -jar target/my-quarkus-project-1.0-SNAPSHOT-runner.jar

java -Dquarkus.log.file.enable=true -Dquarkus.log.file.rotation.max-file-size=10M -jar target/my-quarkus-project-1.0-SNAPSHOT-runner.jar

java -Dquarkus.log.file.enable=true -Dquarkus.log.file.rotation.max-file-size=10k -jar target/my-quarkus-project-1.0-SNAPSHOT-runner.jar

java -Dquarkus.log.file.enable=true -Dquarkus.log.file.rotation.max-file-size=10k -Dquarkus.log.file.rotation.max-backup-index=20 -jar target/my-quarkus-project-1.0-SNAPSHOT-runner.jar
```

One thing to check is that you log your messages using `org.jboss.logging.Logger`

listing of the directory:
```
my-quarkus-project $ ll
total 336
-rw-r--r--  1 rsvoboda  staff   1180 Jan 22 16:09 README.md
-rwxrwxr-x  1 rsvoboda  staff  10078 Jan 22 16:09 mvnw
-rw-rw-r--  1 rsvoboda  staff   6609 Jan 22 16:09 mvnw.cmd
-rw-r--r--  1 rsvoboda  staff   3847 Jan 24 12:09 pom.xml
-rw-r--r--  1 rsvoboda  staff   6948 Jan 24 12:11 quarkus.log
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.1
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:10 quarkus.log.10
-rw-r--r--  1 rsvoboda  staff  10256 Jan 24 12:10 quarkus.log.11
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.2
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.3
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.4
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.5
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:11 quarkus.log.6
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:10 quarkus.log.7
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:10 quarkus.log.8
-rw-r--r--  1 rsvoboda  staff  10360 Jan 24 12:10 quarkus.log.9
drwxr-xr-x  4 rsvoboda  staff    128 Jan 22 16:09 src
```

**Comment by genehi** [comment] 2020-01-25 15:49
How can that be?  Your application.properties has nothing in it but:
# Configuration file
# key = value

I see you are setting using command line properties that “should not” make a difference.  Also, I am running in K8s, can that make a difference to quarkus.
And I am using jboss.logging.
And showing me a listing of the log files does not mean the content of the log files matches what is seen by doing a stdout using

kubectl logs -f <pod>

**Comment by gsmet** [comment] 2020-01-25 16:44
@genehi could you give us more details about your setup and maybe provide a reproducer with what you would expect and what you have?

We need to get to the bottom of that one.

Thanks!

**Comment by genehi** [comment] 2020-01-27 16:31
It will be very hard to provide a reproducer, as there is a great deal of work in setup up of our apps to run in our minikube environment.
I can say that I might have narrowed down the difference somewhat.
When I enable this property in my application.properties, the SQL logging does not show up in the log file itself, only in the console (stdout).

quarkus.hibernate-orm.log.sql=true

My biggest problem with this logging right now, is the inability for the log file size and rotation to work correctly.
Here are my application.properties settings for such:

quarkus.log.file.enable=true
quarkus.log.file.rotation.max-file-size=500M
quarkus.log.file.rotation.max-backup-index=50
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd-hh-mm
quarkus.log.file.rotation.rotate-on-boot=true

And this is what I get:
[cid:image002.png@01D5D4DB.5AAAD890]

Every file rotates at 3KB, no matter what value I set for max-file-size.
This is very annoying and difficult to deal with.
We now have our docker debug port setup to work thru minikube, so I am able to see the log output directly in my IDEA Services window, so I don’t have to look at the log files directly now, but I need them to work correctly for production.

Please help me resolve this.

**Comment by gsmet** [comment] 2020-01-27 16:52
@gastaldi could you check if you can reproduce the log rotation issue?

**Comment by genehi** [comment] 2020-01-27 16:58
Not much to check, it does it on all 3 of my quarkus apps running in minikube.

**Comment by gsmet** [comment] 2020-01-27 17:09
I'm not saying you don't have this behavior but we need to be able to reproduce it to understand what's going on just why I asked @gastaldi to check. We will start with the information you provided. If we can't reproduce it, we will ask you more info.

As previously said, we need to get to the bottom of it.

**Comment by genehi** [comment] 2020-01-27 17:15
I will provide as much as humanly possible, but creating a reproducer, as I said, is extremely difficult, as I am not running the apps “standalone”, they are running in a minikube environment, that has lots of configuration around them so that they startup under minikube control.

I can “try” to run one standalone and see if the results are consistent.  The amount of errors doing it that way should be huge, and would show if the log file size problem is consistent out of minikube.  I will respond to the email with the results.

Actually, a better idea, I am starting on another new app, that is a “clone” of one of my current apps, that won’t even be in minikube for a few days, I can possibly use that to help resolve some of these issues.  I could even provide that project to you if it shows all of the same problems.

**Comment by gastaldi** [comment] 2020-01-27 17:26
I have created a sample app with the following application.properties and would just call `Logger.info` every 2 seconds:

```properties
# Configuration file
quarkus.log.file.enable=true
quarkus.log.file.rotation.max-file-size=1K
quarkus.log.file.rotation.max-backup-index=50
quarkus.log.file.format=%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n
quarkus.log.file.rotation.file-suffix=.yyyy-MM-dd-hh-mm
quarkus.log.file.rotation.rotate-on-boot=true
```

And this is the output in my target folder: 

```bash
-rw-rw-r--. 1 ggastald ggastald  210 Jan 27 14:22 quarkus.log
-rw-rw-r--. 1 ggastald ggastald  140 Jan 27 14:21 quarkus.log.2020-01-27-02-21
-rw-rw-r--. 1 ggastald ggastald 1.1K Jan 27 14:21 quarkus.log.2020-01-27-02-21.1
-rw-rw-r--. 1 ggastald ggastald 1.1K Jan 27 14:22 quarkus.log.2020-01-27-02-22.1
```

So, besides the 140 bytes file, the rotation is working fine AFAIK. Looking forward to an example reproducing that

**Comment by rsvoboda** [comment] 2020-01-27 21:05
>When I enable this property in my application.properties, the SQL logging does not show up in the log file itself, only in the console (stdout).
>quarkus.hibernate-orm.log.sql=true

There is https://github.com/quarkusio/quarkus/issues/6766 opened for this use-case

**Comment by genehi** [comment] 2020-01-27 21:13
I think that may have been the “primary failure” as that was what I was most interested in when I was debugging.
Glad you were able to reproduce once I provided clearer specifics.
Now I just need to provide a repro on the max-file-size problem.

Which leads me to a question.
I have noticed that we also have these set in our high level minikube configuration:


ENV UTIL_LOG_CONFIG=${CONFIG}/jdk14_log.properties
ENV LOG_CONFIG=${CONFIG}/log4j2.xml

-Dlog4j.configurationFile=${LOG_CONFIG} \
-Djava.util.logging.config.file=${UTIL_LOG_CONFIG} \

I “do not” have such files in my Quarkus apps deployments, but “can” such properties override/affect the quarkus logging?

**Comment by dmlloyd** [comment] 2020-01-27 21:22
None of these properties or files should affect Quarkus logging.

**Comment by genehi** [comment] 2020-01-28 22:44
I have this question posted on StackOverflow.
Do you have any resolution or answer???

https://stackoverflow.com/questions/59833534/how-to-set-maxwebsocketframesize

Sorry for “hijacking” my other subject 😊

**Comment by sushmita-negi** [comment] 2022-03-29 17:18
@genehi It seems you have log rotation happening for every run, irrespective of file size being full.
Try setting property  quarkus.log.file.rotation.rotate-on-boot=false

**Comment by gastaldi** [comment] 2024-08-27 21:01
Closing as it seems to work as expected (https://github.com/quarkusio/quarkus/issues/6622#issuecomment-578859633)

**Closed by gastaldi** 2024-08-27 21:01 UTC
Labels: kind/bug
