### ISSUE TITLE
Infinispan version is null

### ISSUE THREAD

**Issue by karesti** [quarkusio/quarkus#1322] opened 2019-03-07 17:51 UTC
Infinispan version is displayed as null 
2019-03-07 17:14:12,787 INFO  [org.inf.cli.hot.RemoteCacheManager] (main) ISPN004021: Infinispan version: null

**Comment by wburns** [comment] 2019-08-21 12:53
This has to be fixed in Infinisipan directly. The issue is that we are invoking at runtime `RemoteCacheManager.class.getPackage().getImplementationVersion()` and this is always null in native mode. The Infinispan code should be changed to use `Version.printVersion()` method instead as this uses a staticly defined instance that is written at build time.

**Comment by karesti** [comment] 2019-09-02 17:03
@wburns is there a jira related ?

**Comment by wburns** [comment] 2019-09-03 13:33
https://issues.jboss.org/browse/ISPN-10488

**Comment by wburns** [comment] 2019-10-09 13:47
This is fixed in ISPN 10.0.0 Final with https://issues.jboss.org/browse/ISPN-10488

**Closed by wburns** 2019-10-09 13:47 UTC
Labels: component:infinispan
