### ISSUE TITLE
RESTEasy Reactive does not expose correctly a Kogito-generated endpoint

### ISSUE THREAD

**Issue by evacchi** [quarkusio/quarkus#20846] opened 2021-10-18 17:06 UTC
### Describe the bug

While addressing https://github.com/quarkusio/quarkus/issues/19868 
I have created kiegroup/kogito-runtimes#1643 which makes our dependency on RestEasy less forceful. You have now to plug resteasy explicitly.

You can also use RestEasy reactive, and you may opt-out of automated rest generation.

However, when using resteasy reactive, although the endpoints show up in swagger they seem not to work.

### Expected behavior

I should be able to send a request either via Swagger UI or cURL

### Actual behavior

an error is returned instead

### How to Reproduce?

get the PR
```
clone kiegroup/kogito-runtimes#1643
mvn install -Dquickly
```

get the examples; for convenience use this PR

```
cd kogito-examples/process-scripts-quarkus
```

change quarkus-resteasy and quarkus-resteasy-jackson to quarkus-resteasy-reactive and quarkus-resteasy-reactive-jackson

```
mvn quarkus:dev
curl -X POST -H 'Content-Type:application/json' -H 'Accept:application/json' -d '{"name" : "john"}' http://localhost:8080/scripts
<html><head><title>Error</title></head><body>HTTP method POST is not supported by this URL</body></html>%
```

or:

```
cd kogito-examples/rules-quarkus-helloworld 
```
change quarkus-resteasy and quarkus-resteasy-jackson to quarkus-resteasy-reactive and quarkus-resteasy-reactive-jackson

```
mvn quarkus:dev
curl -H "Content-Type: application/json" -X POST -d '{"strings":["hello"]}' http://localhost:8080/hello
<html><head><title>Error</title></head><body>HTTP method POST is not supported by this URL</body></html>%
```

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.3

**Comment by geoand** [comment] 2021-10-18 17:20
Can you add an example endpoint and what the pom.xml looks like?

Thanks

**Comment by evacchi** [comment] 2021-10-19 07:32
here is an example generated endpoint + pom.xml https://gist.github.com/evacchi/b655e013c658f2f1c8291bca4f0184b7
but I feel @stuartwdouglas is on the right track, because we use `GeneratedBeanBuildItem` to notify Quarkus of the generated items https://github.com/kiegroup/kogito-runtimes/blob/f5ae0074963b9c1aa92223ec0c8e2a986bdd2586/quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoAssetsProcessor.java#L131

We may add another another build item if that is useful, and it is simple enough. Although it would be simpler if both Resteasy and Resteasy Reactive consumed the same build item :^)

**Comment by evacchi** [comment] 2021-10-19 07:41
correct

**Comment by geoand** [comment] 2021-10-19 07:50
Yeah, you can depend on it without issue in your Quarkus extension as it's just a SPI module. It doesn't force the use of RESTEasy Reactive - users would still need to include `quarkus-resteasy-reactive` on their own

**Comment by geoand** [comment] 2021-10-19 18:45
Just to keep things in sync, the discussion in https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Kogito.20and.20RESTEasy.20Reactive.20.2320846 led to the conclusion that Kogito is including `quarkus-undertow` which does not allow RESTEasy Reactive to handle the request

**Comment by vsevel** [comment] 2021-11-01 16:47
does this mean that there should be improvement first for kogito to not depend on undertow?

**Comment by evacchi** [comment] 2021-11-01 17:59
WIP ironing out that kink https://github.com/kiegroup/kogito-runtimes/pull/1669
in the meantime, excluding the undertow from kogito dependencies should work

**Comment by geoand** [comment] 2021-11-01 18:29
Great, thanks 👍

**Comment by evacchi** [comment] 2021-11-04 08:37
some generated code is using 

```
    @javax.ws.rs.core.Context
    private org.jboss.resteasy.spi.HttpResponse httpResponse;
```

that seems to cause issues?

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:2.4.0.Final:build (default) on project integration-tests-quarkus-resteasy-reactive: Failed to build quarkus application: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor#generateModel threw an exception: java.lang.IllegalStateException: src/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (45:2140) : org.jboss.resteasy.spi.HttpResponse cannot be resolved to a type
[ERROR] src/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (108:6115) : httpResponse cannot be resolved
[ERROR] src/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (110:6321) : httpResponse cannot be resolved
[ERROR] src/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (45:2140) : org.jboss.resteasy.spi.HttpResponse cannot be resolved to a typesrc/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (108:6115) : httpResponse cannot be resolvedsrc/main/java/http_58_47_47www_46trisotech_46com_47definitions_47__2ceee5b6_450f0d_4541ef_45890e_452cd6fb1adb10/DmnModelResource.java (110:6321) : httpResponse cannot be resolved
[ERROR] 	at org.kie.kogito.quarkus.common.deployment.InMemoryCompiler.compile(InMemoryCompiler.java:104)
[ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoQuarkusResourceUtils.compileGeneratedSources(KogitoQuarkusResourceUtils.java:168)
[ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.compileAndIndexJavaSources(KogitoAssetsProcessor.java:138)
[ERROR] 	at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:106)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR] 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR] 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR] 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[ERROR] 	at io.quarkus.deployment.ExtensionLoader$2.execute(ExtensionLoader.java:821)
[ERROR] 	at io.quarkus.builder.BuildContext.run(BuildContext.java:277)
[ERROR] 	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
[ERROR] 	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
[ERROR] 	at java.base/java.lang.Thread.run(Thread.java:829)
[ERROR] 	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
[ERROR] -> [Help 1]
```

**Comment by evacchi** [comment] 2021-11-04 08:38
@tarilabs FYI ^

**Comment by geoand** [comment] 2021-11-04 08:40
Right, using RESTEasy Classic types will not work with RESTEasy Reactive.

What does that code actually do?

**Comment by evacchi** [comment] 2021-11-04 08:41
enrich response headers https://github.com/kiegroup/kogito-runtimes/blob/fff3b78374da815bbda61e4e7a4fd73592a3a075/kogito-codegen-modules/kogito-codegen-decisions/src/main/resources/class-templates/DecisionRestResourceQuarkusTemplate.java#L36-L35

**Comment by evacchi** [comment] 2021-11-04 08:42
is there a solution that will work for both?

**Comment by evacchi** [comment] 2021-11-04 08:51
maybe use `Response` as detailed here? 🤔  https://stackoverflow.com/questions/4621748/how-to-set-response-header-in-jax-rs-so-that-user-sees-download-popup-for-excel

**Comment by geoand** [comment] 2021-11-04 08:51
Yes, using `Response` is the JAX-RS standard way to go here.

**Comment by evacchi** [comment] 2021-11-04 10:26
allright it looks like generated resources cannot be found by vert.x.
Reproducer at this PR https://github.com/kiegroup/kogito-runtimes/pull/1669
specifically this integration test:

https://github.com/kiegroup/kogito-runtimes/pull/1669/files#diff-8ad52741a58a4e9dfc55668955e8560872e9389a35b0bfb9af6d34cef84925fa

```

2021-11-04 10:27:46,844 WARN  [io.swa.v3.par.OpenAPIV3Parser] (main) Exception while resolving:: java.lang.RuntimeException: Unable to load RELATIVE ref: /dmnDefinitions.json
	at io.swagger.v3.parser.util.RefUtils.readExternalUrlRef(RefUtils.java:115)
	at io.swagger.v3.parser.ResolverCache.loadRef(ResolverCache.java:122)
	at io.swagger.v3.parser.processors.ExternalRefProcessor.processRefToExternalSchema(ExternalRefProcessor.java:75)
	at io.swagger.v3.parser.processors.SchemaProcessor.processReferenceSchema(SchemaProcessor.java:214)
	at io.swagger.v3.parser.processors.SchemaProcessor.processSchema(SchemaProcessor.java:37)
	at io.swagger.v3.parser.processors.RequestBodyProcessor.processRequestBody(RequestBodyProcessor.java:47)
	at io.swagger.v3.parser.processors.OperationProcessor.processOperation(OperationProcessor.java:45)
	at io.swagger.v3.parser.processors.PathsProcessor.processPaths(PathsProcessor.java:84)
	at io.swagger.v3.parser.OpenAPIResolver.resolve(OpenAPIResolver.java:49)
	at io.swagger.v3.parser.OpenAPIV3Parser.resolve(OpenAPIV3Parser.java:175)
	at io.swagger.v3.parser.OpenAPIV3Parser.readContents(OpenAPIV3Parser.java:154)
	at io.swagger.v3.parser.OpenAPIV3Parser.readLocation(OpenAPIV3Parser.java:89)
	at org.kie.kogito.quarkus.EndpointsIT.endpointTest(EndpointsIT.java:45)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:925)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptTestMethod(QuarkusTestExtension.java:755)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:188)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:154)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:128)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:428)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:562)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:548)
Caused by: java.lang.RuntimeException: Unable to load URL ref: http://localhost:8081/dmnDefinitions.json path: null
	at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:239)
	at io.swagger.v3.parser.util.RefUtils.readExternalUrlRef(RefUtils.java:112)
	... 84 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/dmnDefinitions.json
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1974)
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1969)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1968)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at io.swagger.v3.parser.util.RemoteUrl.urlToString(RemoteUrl.java:155)
	at io.swagger.v3.parser.util.RefUtils.readExternalRef(RefUtils.java:204)
	... 85 more
Caused by: java.io.IOException: Server returned HTTP response code: 500 for URL: http://localhost:8081/dmnDefinitions.json
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1924)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1520)
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getHeaderField(HttpURLConnection.java:3099)
	at io.swagger.v3.parser.util.RemoteUrl.urlToString(RemoteUrl.java:152)
	... 86 more
```

**Comment by geoand** [comment] 2021-11-04 10:30
How do I reproduce that?

**Comment by evacchi** [comment] 2021-11-04 10:47
```
git clone https://github.com/evacchi/kogito-runtimes
git checkout KOGITO-6131-resteasy-reactive
mvn install -Dquickly
cd kogito-runtimes/integration-tests/integration-tests-quarkus-resteasy-reactive
mvn verify
```

**Comment by geoand** [comment] 2021-11-04 11:50
There are a couple things going here causing this. They should be easy to fix, but first of all I need to know where `dmnDefinitions.json` is created.

**Comment by evacchi** [comment] 2021-11-04 12:15
https://github.com/evacchi/kogito-runtimes/blob/0f4b959f8985c176483f10dbd8d008d849fbd522/kogito-codegen-modules/kogito-codegen-decisions/src/main/java/org/kie/kogito/codegen/decision/DecisionCodegen.java#L132

then I think they are picked up and registered here https://github.com/evacchi/kogito-runtimes/blob/a98f1ce0482f52c0b7d5963b64354b67f6b702c9/quarkus/extensions/kogito-quarkus-extension-common/kogito-quarkus-common-deployment/src/main/java/org/kie/kogito/quarkus/common/deployment/KogitoQuarkusResourceUtils.java#L137

**Comment by geoand** [comment] 2021-11-04 13:59
Unfortunately https://github.com/quarkusio/quarkus/pull/21190 needs to be reworked because:

1) it causes build cycles
2) it is still susceptible to not picking the resources properly. 

The solution is to introduce an BuildItem as part of the Vertx SPI that you can use in your extension

**Comment by geoand** [comment] 2021-11-04 14:15
> #21190 should take care of the (first) issue

The second issue is that the test should be converted to be a `@QuarkusIntegrationTest` instead of a `@QuarkusTest`.

**Comment by evacchi** [comment] 2021-11-04 16:09
ok it was originally, I guess I'll have to put it back 😅  I must have misunderstood the difference

**Comment by geoand** [comment] 2021-11-08 08:49
In case https://github.com/quarkusio/quarkus/pull/21190 is not clear, to make this work you need to 
include `quarkus-vertx-http-deployment-spi` (it's just a SPI module, so it does not bring any dependencies in other than `quarkus-core-deployment`) and then generate `AdditionalStaticResourceBuildItem` in your `public class KogitoQuarkusResourceUtils#registerResources` for resources that are supposed to be accessible from the web application.

**Comment by vsevel** [comment] 2021-12-10 11:19
hello, any news @evacchi?

**Comment by evacchi** [comment] 2021-12-10 11:28
as soon as kiegroup/kogito-runtimes#1757 is merged most issues should be ruled out @vsevel

**Comment by debu999** [comment] 2021-12-18 02:37
Cool, Its a great support by the team. Really looking forward to the change. We just splitted 2 applications one reactive and one with kogito due the the error. But hopefully will be able to merge them once the change is merged.

**Comment by gsmet** [comment] 2022-01-04 19:41
@evacchi is it on track for Quarkus 2.7? It would be very good to have it. Full platform release is planned for February 2nd (so the Platform PR must be merged at most on Feb 1st)

**Comment by evacchi** [comment] 2022-01-10 07:42
@gsmet it's been merged, so IIRC it'll be even in Kogito 1.15 (i.e. Quarkus 2.6.2)

**Closed** 2022-01-10 10:18 UTC
Labels: kind/bug, triage/upstream, area/kogito, area/resteasy-reactive

**Comment by zakhdar** [comment] 2022-01-15 19:20
Hello, 

i just updated my project to 2.6.2.Final , i try to use RESTEasy Reactive with Kogito but i get this error , did i miss something or is a same bug ? 

```Caused by: org.kie.kogito.quarkus.common.deployment.MissingRestCapabilityException: No REST capability detected!
Add the RestEasy (quarkus-resteasy) and RestEasy Jackson (quarkus-resteasy-jackson) extensions if you want Kogito to generate REST endpoints automatically.
RestEasy Reactive extension is currently not supported: see https://issues.redhat.com/browse/KOGITO-6131
You may also disable automated REST generation by setting `kogito.generate.rest = false`.
You may also override this notice by setting `kogito.generate.rest = true`
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.validateAvailableCapabilities(KogitoAssetsProcessor.java:121)
        at org.kie.kogito.quarkus.common.deployment.KogitoAssetsProcessor.generateModel(KogitoAssetsProcessor.java:80)
```

I have this dependency in my pom 

`<dependency>
            <groupId>org.kie.kogito</groupId>
            <artifactId>kogito-quarkus</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive</artifactId>
        </dependency>
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
        </dependency>`

Step to reproduce 

1. Generate project on (https://code.quarkus.io/) with RESTEasy Reactive , RESTEasy Reactive Jackson , Kogito extensions
2. mvn quarkus:dev (Using kogito dev service)

**Comment by geoand** [comment] 2022-01-15 19:38
This needs a new Kogito release as well

**Comment by evacchi** [comment] 2022-01-17 08:19
I think this is fixed in `main` and should be available on Kogito 1.16 /cc @tkobayas @radtriste

**Comment by radtriste** [comment] 2022-01-17 08:55
confirmed it should be in 1.16: https://github.com/kiegroup/kogito-runtimes/commits/1.16.x (look for KOGITO-6131)

**Comment by debu999** [comment] 2022-04-19 02:00
@radtriste @evacchi is there any specific example to use. quarkus kogito guide breaks with  java.lang.ClassNotFoundException: io.quarkus.resteasy.runtime.QuarkusRestPathTemplate when testing with quarkus 2.8.0.Final and kogito 1.20.0.Final

**Comment by evacchi** [comment] 2022-04-19 07:17
@debu999 can you ensure you are able to reproduce the issue using the quarkus cli or code.quarkus.io to bootstrap your project?

**Comment by debu999** [comment] 2022-04-19 08:01
@evacchi @tiagodolphine 
 It seems the issue is with the following svg generation library. Removing the same makes the generation go fine.
 Guess something in SVG have a need to use rest easy classic instead of reactive.
 `
<dependency> <groupId>org.kie.kogito</groupId> <artifactId>kogito-addons-quarkus-process-svg</artifactId> <exclusions> <exclusion> <groupId>io.quarkus</groupId> <artifactId>quarkus-resteasy</artifactId> </exclusion> </exclusions> <dependency>`

**Comment by debu999** [comment] 2022-04-19 08:02
<img width="419" alt="Screenshot 2022-04-19 at 1 10 41 PM" src="https://user-images.githubusercontent.com/1910577/163955058-3a1e1da8-227c-47ca-b0fe-f9edc0f7da4e.png">
If you do via code.quarkus.io and exclude svg things seems to work fine and rest resources are generated correctly.

**Comment by evacchi** [comment] 2022-04-19 08:05
thanks for reporting, I don't think the SVG addon was tested with resteasy /cc @cristianonicolai @nmirasch

**Comment by tiagodolphine** [comment] 2022-04-19 13:24
> AddON SVG needs some tweak to work with reactive.

yeah, AFAIK the SVG and some other addons were not designed to work with resteasy reactive, at least out-of-the-box.

**Comment by debu999** [comment] 2022-05-02 03:26
@tiagodolphine Do you think we need this can be a enhancement request for svg extension. Or there is a way to integrate it differently. Both resteasy and resteasy-reactive is not supported. So no not sure if we are looking at a directlion to make it work both ways by some means.
