### ISSUE TITLE
yaml config: hierarchical keys

### ISSUE THREAD

**Issue by t1** [quarkusio/quarkus#15751] opened 2021-03-16 04:52 UTC
## Describe the bug
When I configure something like:
```yaml
mp.graphql.showErrorMessage: foo
```

Then the config key is surrounded by quotes. To make it work, I have to configure it like this:

```yaml
mp:
  graphql:
    showErrorMessage: foo
```

The hierarchical syntax (example 1) is nice to have when I have several configurations with a common prefix, but it's annoying when not.

### Expected behavior
Don't add quotes. If I want quotes, I would add them myself.

### Actual behavior
```yaml
mp.graphql:
    showErrorMessage: foo
```

Turns the key into `"mp.graphql".showErrorMessage`.

## To Reproduce
https://github.com/t1/wunderbar/tree/master/demo/product

### Output of `uname -a` or `ver`
`Darwin ruBook.fritz.box 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:07:06 PST 2021; root:xnu-7195.81.3~1/RELEASE_X86_64 x86_64`

### Output of `java -version`
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment AdoptOpenJDK (build 11.0.10+9)
OpenJDK 64-Bit Server VM AdoptOpenJDK (build 11.0.10+9, mixed mode)`
```

### GraalVM version (if different from Java)
none

### Quarkus version or git rev
1.12.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)
```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /usr/local/Cellar/maven/3.6.3_1/libexec
Java version: 11.0.10, vendor: AdoptOpenJDK, runtime: /Users/rdohna/.sdkman/candidates/java/11.0.10.hs-adpt
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"
```

**Comment by famod** [comment] 2021-03-16 10:09
TBH, to me this looks more like an enhancement request than a bug but I'll leave that to @radcortez to decide. 🙂

**Comment by radcortez** [comment] 2021-03-16 10:37
Duplicate of https://github.com/quarkusio/quarkus/issues/11744.

**Comment by radcortez** [comment] 2021-03-16 10:38
Closing this one. Please let's follow in https://github.com/quarkusio/quarkus/issues/11744. Thanks!

**Closed by radcortez** 2021-03-16 10:37 UTC
Labels: area/config, kind/bug
