### ISSUE TITLE
Reactive Programmatic Scheduling

### ISSUE THREAD

**Issue by tiagomistral** [quarkusio/quarkus#32720] opened 2023-04-18 10:40 UTC
### Describe the bug

In a **reactive context**, it is possible to create a scheduled that persists an object:

```java
    package org.acme.quartz;
    
    import io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactional;
    import io.quarkus.logging.Log;
    import io.quarkus.scheduler.Scheduled;
    import io.smallrye.mutiny.Uni;
    
    import javax.enterprise.context.ApplicationScoped;
    
    @ApplicationScoped
    public class TaskBean {
    
        @ReactiveTransactional
        @Scheduled(every = "10s", identity = "task-job")
        Uni<Void> schedule() {
            Log.warn("Scheduled task");
            return new Task().persist()
                    .flatMap(result -> Uni.createFrom().voidItem());
        }
    }
```

But it is not possible programmatically:

```java
    package org.acme.quartz;
    
    import io.quarkus.hibernate.reactive.panache.common.runtime.ReactiveTransactional;
    import io.quarkus.logging.Log;
    import io.quarkus.runtime.StartupEvent;
    import io.smallrye.mutiny.Uni;
    import io.smallrye.mutiny.vertx.MutinyHelper;
    import io.vertx.core.Vertx;
    import org.quartz.Job;
    import org.quartz.JobBuilder;
    import org.quartz.JobDetail;
    import org.quartz.JobExecutionContext;
    import org.quartz.Scheduler;
    import org.quartz.SchedulerException;
    import org.quartz.SimpleScheduleBuilder;
    import org.quartz.Trigger;
    import org.quartz.TriggerBuilder;
    
    import javax.enterprise.context.ApplicationScoped;
    import javax.enterprise.context.control.ActivateRequestContext;
    import javax.enterprise.event.Observes;
    import javax.inject.Inject;
    import java.time.Duration;
    import java.time.temporal.ChronoUnit;
    
    @ApplicationScoped
    public class ProgrammaticallyTaskResource {
    
        private static final String TRIGGER_IDENTIFIER_FORMAT = "%sTrigger";
    
        public static final String groupId = "groupId";
    
        @Inject
        Scheduler quartz;
    
        void onStart(@Observes final StartupEvent event) throws SchedulerException {
            JobDetail job = JobBuilder.newJob(ProgrammaticallyTaskJob.class)
                    .withIdentity(ProgrammaticallyTaskJob.class.getSimpleName(), groupId)
                    .build();
            Trigger trigger = TriggerBuilder.newTrigger()
                    .withIdentity(String.format(
                            TRIGGER_IDENTIFIER_FORMAT,
                            ProgrammaticallyTaskJob.class.getSimpleName()), groupId)
                    .startNow()
                    .withSchedule(
                            SimpleScheduleBuilder.simpleSchedule()
                                    .withIntervalInSeconds(
                                            Long.valueOf(Duration.of(10, ChronoUnit.SECONDS)
                                                            .getSeconds())
                                                    .intValue())
                                    .repeatForever())
                    .build();
            quartz.scheduleJob(job, trigger);
        }
    
        @ReactiveTransactional
        Uni<Void> business() {
            Log.warn("ProgrammaticallyTaskResource!");
            return new Task().persist()
                    .flatMap(result -> Uni.createFrom().voidItem());
        }
    
        // A new instance of ProgrammaticallyTaskJob is created by Quartz for every job execution
        @ActivateRequestContext
        public static class ProgrammaticallyTaskJob implements Job {
    
            @Inject
            Vertx vertx;
    
            @Inject
            ProgrammaticallyTaskResource service;
    
            /**
             * Execute the job 'remove old Async Service Errors'.
             *
             * @param context the context
             */
            public void execute(final JobExecutionContext context) {
                service.business()
                        .runSubscriptionOn(MutinyHelper.executor(vertx.getOrCreateContext()))
                        .subscribe().with(result -> Log.error(result));
            }
    
        }
    }
```

Should exists a class ReactiveJob on quartz module with a different signature of execute? Something like:

    Uni<Void> execute(JobExecutionContext var1) throws JobExecutionException;

I attach the PoC with the PoC :)

Best regards,

[ReactiveProgrammaticScheduling.zip](https://github.com/quarkusio/quarkus/files/11260798/ReactiveProgrammaticScheduling.zip)

### Expected behavior

It should be possible to get the same output programmatically

### Actual behavior

```posh
java.lang.RuntimeException: java.util.concurrent.TimeoutException
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.executeInVertxEventLoop(AbstractJpaOperations.java:52)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.subscribe(UniRunSubscribeOn.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniOnItemTransformToUni.subscribe(UniOnItemTransformToUni.java:25)
	at io.smallrye.mutiny.operators.AbstractUni.subscribe(AbstractUni.java:36)
	at io.smallrye.mutiny.operators.uni.UniRunSubscribeOn.lambda$subscribe$0(UniRunSubscribeOn.java:27)
	at io.smallrye.mutiny.vertx.MutinyHelper.lambda$executor$2(MutinyHelper.java:33)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:264)
	at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:246)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:43)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.concurrent.TimeoutException
	at java.base/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1886)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2021)
	at io.quarkus.hibernate.reactive.panache.common.runtime.AbstractJpaOperations.executeInVertxEventLoop(AbstractJpaOperations.java:50)
	... 17 more
```

### Output of `uname -a` or `ver`

Linux neotolemus 6.2.10-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Apr  6 23:30:41 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.6" 2023-01-17 OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10) OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed mode, sharing)

### Quarkus version or git rev

2.16.6.Final

**Comment by geoand** [comment] 2023-04-19 09:29
@mkouba should we close this as already done in Quarkus 3?

**Comment by mkouba** [comment] 2023-04-19 09:35
> @mkouba should we close this as already done in Quarkus 3?

:+1: 

It's not a bug, we have a new API in Quarkus 3 and the attached PoC could be fixed (as described in https://github.com/quarkusio/quarkus/issues/32720#issuecomment-1514354293).

**Closed** 2023-04-19 09:36 UTC
Labels: area/scheduler

**Comment by tiagomistral** [comment] 2023-04-19 09:40
Thanks for your help @mkouba 

I will change this for 3.0 asap :D

**Comment by yhinge** [comment] 2023-07-31 12:12
Hi @mkouba 
So the approach suggested in the documentation for scheduling the job is 
```
 scheduler.newJob("myJob")
            .setCron("0/5 * * * * ?")
            .setTask(executionContext -> { 
                // do something important every 5 seconds
            })
            .schedule(); 
```
Now here the executionContext has only information like firing time and other stuff. But what if I need some data that is specific to the execution but cannot be statically defined in the method like if my job details are stored in a database about what work is to be done. Is there anyway I can  pass an id while scheduling the job and use it while in execution.

**Comment by mkouba** [comment] 2023-07-31 12:22
> Hi @mkouba So the approach suggested in the documentation for scheduling the job is
> 
> ```
>  scheduler.newJob("myJob")
>             .setCron("0/5 * * * * ?")
>             .setTask(executionContext -> { 
>                 // do something important every 5 seconds
>             })
>             .schedule(); 
> ```
> 
> Now here the executionContext has only information like firing time and other stuff. But what if I need some data that is specific to the execution but cannot be statically defined in the method like if my job details are stored in a database about what work is to be done. Is there anyway I can pass an id while scheduling the job and use it while in execution.

Hi, so first of all this question is not related to this issue. So you should rather start a new [discussion](https://github.com/quarkusio/quarkus/discussions) or start a new zulip topic.

Anyway, the `ScheduledExecution` does not provide an API to store some information because the jobs are not persistent by default. You'll need to use the `quarkus-quartz` extension and Quartz API instead.
