### ISSUE TITLE
Quarkus 3.2 hibernate schema validation extremelly slow

### ISSUE THREAD

**Issue by sinattieng** [quarkusio/quarkus#34674] opened 2023-07-11 11:28 UTC
### Describe the bug

Good morning,

Starting the migration from Quarkus version 2.16.7 to 3.2.0 I'm observing a downgrade (from ms to minute) in terms of hibernate-orm schema validation. My application is based on hibernate+oracle db. I have just migrate my entities from javax.persistence.* to jakarta.persistence.*, none of them is changed. 

Thank you in adavance for the support.

Stefano

**Comment by Sanne** [comment] 2023-07-11 12:21
Very interesting, thanks for opening the issue.
Do you think we'll reproduce it with any simple model or is there something special in you model?

**Comment by sinattieng** [comment] 2023-07-11 14:49
What do you mean with "something special"? 
The entities are very simple, I have noticed that every time the schema validations has blocked (stucked than it goes after **minutes**) on the same point, with org.hibernate log level DEBUG I see this:

`2023-07-11 16:47:10,061 DEBUG [org.hibernate.query.named.NamedObjectRepository] (JPA Startup Thread)  Checking named HQL query: OrgVChkPartitionFascByAa.findAll
2023-07-11 16:47:10,062 DEBUG [org.hibernate.orm.query.hql] (JPA Startup Thread)  HQL : SELECT o FROM OrgVChkPartitionFascByAa o
2023-07-11 16:47:10,062 DEBUG [org.hibernate.query.hql.internal.SemanticQueryBuilder] (JPA Startup Thread)  Handling root path - OrgVChkPartitionFascByAa
2023-07-11 16:47:10,062 DEBUG [org.hibernate.orm.query.sqm.ast] (JPA Startup Thread)  SqmStatement Tree :
    -> [select]
      -> [query-spec]
        -> [select]
          -> [selection]
            -> [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
            <- [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
          <- [selection]
        <- [select]
        -> [from]
          -> [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
          <- [root] - `it.eng.parer.fascicolo.jpa.viewEntity.OrgVChkPartitionFascByAa(o)`
        <- [from]
      <- [query-spec]
    <- [select]


2023-07-11 16:47:10,063 DEBUG [org.hibernate.query.named.NamedObjectRepository] (JPA Startup Thread)  Checking 0 named SQL queries
`

**Comment by sinattieng** [comment] 2023-07-11 14:54
I add another very strange scenario, I have this on my application.yaml:

```
  datasource: 
    db-kind: "oracle"
    jdbc:
      driver: "oracle.jdbc.driver.OracleDriver"
  hibernate-orm:
    dialect: "org.hibernate.dialect.OracleDialect"
    packages: "it.eng.parer.fascicolo.jpa"
...
"%dev":
  quarkus:
   http:
     port: 10001
   shutdown:
    timeout: "PT1S"
   hibernate-orm:
     validate-in-dev-mode: false
     database:
       generation: "validate"
```
with this configuration schema validation (locally) took 5 minutes and it has happen that hibernate **drop and create** some tables mapped as entity ! (not all of them only a portion)

**Comment by Sanne** [comment] 2023-07-11 16:43
Is there any chance you could provide a reproducer? Is the number of entities significant?

It doesn't take that long in our tests, but I'd love to be able to reproduce it locally.

Also: are you connecting to an existing database or having the datasource provided automatically by Quarkus? The Oracle container might take some time to download and run.

**Comment by sinattieng** [comment] 2023-07-11 16:53
> Is there any chance you could provide a reproducer?
Sorry, I didn't cache the point, with "reproducer" do you mean attaching maybe a zip file with all @Entity? 
> Is the number of entities significant?
There are multiple entities (more than 50) **but**  I didn't have any problem with same mapping back on 2.16 version of Quarkus (now on 3.2.0 we have jakarta.* and not javax.*)
> 
> It doesn't take that long in our tests, but I'd love to be able to reproduce it locally.
> 
> Also: are you connecting to an existing database or having the datasource provided automatically by Quarkus? The Oracle container might take some time to download and run.

Existing OracleDB.

Conclusion: same mapping different quarkus version, 2.16: fast schema validation, 3.2: slow schema validation

**Comment by sinattieng** [comment] 2023-07-12 09:31
Good morning,

After a DEBUG session it seems that the problem because the validation took long time is that piece of code:

SessionFactoryObserverChain.java

```java
@Override
	public void sessionFactoryCreated(SessionFactory factory) {
		if ( observers == null ) {
			return;
		}

		for ( SessionFactoryObserver observer : observers ) {
			observer.sessionFactoryCreated( factory );
		}
	}
```

Any idea?

**Comment by sinattieng** [comment] 2024-03-04 13:59
Good evening,

I still have this issue with the latest Quarkus versione **3.8.1**, any idea?

Thank you in advance.

Stefano

**Comment by gsmet** [comment] 2024-03-04 16:18
@sinattieng I don't know a lot about Oracle but do you have the possibility to log the queries with their time? There might be a query that is extremely slow for whatever reason i.e. that the way Hibernate ORM collect metadata in recent versions doesn't work well with either your schema or Oracle in general.
Start with that because that's the most probable culprit.

If you don't find anything weird in the SQL queries, another option would be to use asyncprofiler to get a profile of what's going on during the startup.

There are some pointers here on how to use it: https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md

What we would be looking for here would be a CPU profile.

**Comment by sinattieng** [comment] 2024-03-04 16:34
> @sinattieng I don't know a lot about Oracle but do you have the possibility to log the queries with their time? There might be a query that is extremely slow for whatever reason i.e. that the way Hibernate ORM collect metadata in recent versions doesn't work well with either your schema or Oracle in general. Start with that because that's the most probable culprit.
> 
> If you don't find anything weird in the SQL queries, another option would be to use asyncprofiler to get a profile of what's going on during the startup.
> 
> There are some pointers here on how to use it: https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md
> 
> What we would be looking for here would be a CPU profile.

Thank you for your suggestions but I have already seen (starting from the new version of Quarkus 3.2.x, if I am not wrong) that with the new "validation logic" from Hibernate, some queries that inspect my Oracle schema took long time indeed a possible solution could be use the configuration "hibernate.temp.use_jdbc_metadata_defaults" from true (default) to false (check my comment https://github.com/quarkusio/quarkus/issues/34674#issuecomment-1632170432); so I was asking the newest version of Quarkus has changed policy or added some specific configuration in order to disable metada fetching.

**Comment by gsmet** [comment] 2024-03-04 17:08
I have read your comment earlier but I don't see how just listing tables for a schema would be so slow. Except if you have a gazillion of schemas. But even then, I'm not exactly sure what would be going on.

Thus why I'm asking details.

**Comment by yrodiere** [comment] 2024-03-04 17:09
> indeed a possible solution could be use the configuration "hibernate.temp.use_jdbc_metadata_defaults" from true (default) to false (check my comment https://github.com/quarkusio/quarkus/issues/34674#issuecomment-1632170432);

Quarkus only sets `hibernate.temp.use_jdbc_metadata_defaults` back to `true` because that's the default in Hibernate ORM.

Essentially Quarkus [sets it to `false` during the build](https://github.com/quarkusio/quarkus/blob/47ecd0a245b26e85a2b01536f182f3292e95b2e8/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/FastBootMetadataBuilder.java#L277) because it wouldn't work at that point (the DB generally isn't reachable during the application build), but [sets it back to `true` just before the application starts](https://github.com/quarkusio/quarkus/blob/3b359084b93a8931ae8f66aaf336f20a30b795db/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/FastBootHibernatePersistenceProvider.java#L225-L226), to get the normal Hibernate ORM behavior. Which, in your case, is slow, because the metadata is huge or the queries badly optimized.

Regardless of the solution, `hibernate.temp.use_jdbc_metadata_defaults` isn't a supported property in Hibernate ORM and you shouldn't use it. It's always been meant as a temporary hack for integrators (see the `temp` in the name?).

> so I was asking the newest version of Quarkus has changed policy or added some specific configuration in order to disable metada fetching

If you migrated from Quarkus 2 to 3, my bet would be on the problem coming from the upgrade from Hibernate ORM 5 to 6. Lots of things have changed between these two versions, so a regression would be completely understandable.

Short-term, I would suggest you answer @gsmet 's request and provide a way to reproduce your problem, so that the Hibernate team can investigate what exactly is slow in these queries, and hopefully issue a bugfix.

Long-term, in case of new regressions, a workaround will be available thanks to a new feature, [HHH-17269](https://hibernate.atlassian.net/browse/HHH-17269), which is being worked on (right @beikov ?). It will be available as soon as Quarkus upgrades to a version of Hibernate ORM that provides the feature. But that's not something you can use right now: it's not ready.

**Comment by sinattieng** [comment] 2024-03-04 17:43
Ok, thank you for details, so in order to log queries with their time do you have any suggestions? because I have already activated (on dev profile) the standard query logging from Hibernate but nothing more than the SQL translated, Quarkus offers some embedded solutions? or I have to debug directly the Hibernate 6 validator? (something that I've already done during my first analysis https://github.com/quarkusio/quarkus/issues/34674#issuecomment-1632170432)

**Comment by gsmet** [comment] 2024-03-04 18:20
Oracle doesn't have something similar to PostgreSQL's `log_min_duration_statement`?

If not, I know Hibernate ORM has the ability to log query duration (via a feature called statistics) but I'm not sure how it's implemented in ORM 6.

**Comment by sinattieng** [comment] 2024-03-05 09:07
> `log_min_duration_statement`

Good morning, 
I've tried to activate this configurations :+1: 
> quarkus.hibernate-orm.statistics=true
 quarkus.hibernate-orm.metrics.enabled=true

but they don't work well, I can't see statitics in each query executed.

**Comment by yrodiere** [comment] 2024-03-05 09:12
Statistics and metrics are by definition aggregated across many queries; that's not what you need. 

Ideally you'd look for something in your JDBC driver or in your database. Things like [this](https://stackoverflow.com/a/15813620/6692043) could help.

**Comment by yrodiere** [comment] 2024-03-27 15:50
Hey @sinattieng , did you manage to pinpoint specific queries executed on startup that are slower than expected?

**Comment by sinattieng** [comment] 2024-03-27 16:11
> Hey @sinattieng , did you manage to pinpoint specific queries executed on startup that are slower than expected?

Hi, I tried to debug but it's not about "query slow" but "huge number of tables that hibernate try to scan with metadatas" and it takes long time

**Comment by yrodiere** [comment] 2024-03-27 16:16
Okay, but surely the number of tables didn't change since you were running on Quarkus 2 / Hibernate ORM 5. So there must be more (unnecessary?) queries, or some queries that changed and take longer than expected?

**Comment by sinattieng** [comment] 2024-03-27 16:21
> Okay, but surely the number of tables didn't change since you were running on Quarkus 2 / Hibernate ORM 5. So there must be more (unnecessary?) queries, or some queries that changed and take longer than expected?

At the moment, I didn't find a specif query  or queries, but the logic above (https://github.com/quarkusio/quarkus/issues/34674#issuecomment-1632170432) seems very slow with its internal cycle, the debug is not easy moreover.

**Comment by yrodiere** [comment] 2024-03-28 08:18
Yes I don't expect debugging on the Java side to yield anything useful. Like I said, having the JDBC driver or your database log queries and corresponding execution time is probably going to be easier; Oracle offers an advanced query logs AFAICS: 

Alternatively, you could try creating a flamegraph or JFR recording and sending it to someone on the Quarkus team for analysis -- privately, e.g. by email, since these files could expose information about your code. See https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md . Try doing this on Linux, since Windows is known to exclude some important debugging information from its Java runtimes, making the resulting flamegraphs/JFR recordings pointless sometimes.

cc @Sanne: you might be interested by this case ^

**Comment by sinattieng** [comment] 2024-03-28 09:14
> Yes I don't expect debugging on the Java side to yield anything useful. Like I said, having the JDBC driver or your database log queries and corresponding execution time is probably going to be easier; Oracle offers an advanced query logs AFAICS: https://blogs.oracle.com/analytics/post/oracle-analytics-best-practices---gathering-and-analyzing-query-logs
> 
> Alternatively, you could try creating a flamegraph or JFR recording and sending it to someone on the Quarkus team for analysis -- privately, e.g. by email, since these files could expose information about your code. See https://github.com/quarkusio/quarkus/blob/main/TROUBLESHOOTING.md . Try doing this on Linux, since Windows is known to exclude some important debugging information from its Java runtimes, making the resulting flamegraphs/JFR recordings pointless sometimes.
> 
> cc @Sanne: you might be interested by this case ^

I'll try to do it as soon as I can, busy period :) In case I'll ask some suggestion.

Thank you in advance

**Comment by gsmet** [comment] 2024-03-28 09:28
Yeah, logging the queries is the way to go. Profiling Java won't help you much in my opinion.

**Comment by yrodiere** [comment] 2024-03-28 10:47
> Profiling Java won't help you much in my opinion.

Seems unlikely to me too, for such huge times I'd expect IO to be involved.
But @Sanne is using that information in a similar case (not on Quarkus), so... :shrug:

**Comment by yrodiere** [comment] 2024-04-23 07:06
Hey @sinattieng , any news on your side?

**Comment by sinattieng** [comment] 2024-04-23 15:44
> Hey @sinattieng , any news on your side?

Unfortunately not, I am sorry but during the last period I am facing some issues on a different front so, I hope to resume this task as soon as possible.
Thank you very much for your support, I count to give you some feedback soon.

**Comment by yrodiere** [comment] 2024-04-23 16:02
No problem, we'll be here when you're available :)

**Comment by yrodiere** [comment] 2024-05-30 07:55
Hey, anyone has more information about this (reproducer, relevant bits that trigger the problem, ...)?
Quarkus 3.11 uses a more recent version of Hibernate ORM, so it may be worth trying, to know if the problem is still there.

Relatedly, this new version of Hibernate ORM adds an official way to select offline startup: https://hibernate.atlassian.net/browse/HHH-17269
It's not integrated in Quarkus right now, but we'll try to add it in the future, and it might help *if you do not want to access the database or validate the schema on startup*.

**Comment by geoand** [comment] 2024-07-01 14:15
I am going to close this as we did not receive any new information. 

If new information does become available, please add it and we can reopen the issue

**Closed by geoand** 2024-07-01 14:15 UTC
Labels: kind/bug, area/persistence, area/hibernate-orm, triage/needs-feedback
