### ISSUE TITLE
Exception when stopping native image

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2645] opened 2019-05-30 03:27 UTC
```
2019-05-30 03:25:39,253 INFO  [io.quarkus] (main) Quarkus 0.15.0 started in 0.007s. Listening on: http://0.0.0.0:8080
2019-05-30 03:25:39,254 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy]
^C2019-05-30 03:26:00,906 ERROR [org.jbo.exe.uncaught] (executor-thread-1) Thread Thread[executor-thread-1,5,executor] threw an uncaught exception: java.lang.ClassCastException
        at org.jboss.threads.ThreadLocalResettingRunnable$Resetter.run(Substitutions.java:33)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:34)
        at java.lang.Thread.run(Thread.java:748)
        at org.jboss.threads.JBossThread.run(JBossThread.java:479)
        at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:473)
        at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:193)```

Starting and the Ctril+C (on macOS, Quarkus 0.15.) does this "from time to time".
Not sure why

CC @dmlloyd

**Comment by gsmet** [comment] 2019-05-30 11:06
Looks like a duplicate of: https://github.com/quarkusio/quarkus/issues/2218 . It should be fixed in current master.

**Closed** 2019-05-30 15:43 UTC
Labels: bug, component:core, duplicate
