### ISSUE TITLE
Hibernate Auto update entity without change when using JSON mapping

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#38438] opened 2024-01-27 17:14 UTC
### Describe the bug

i have entity like flow code
```java
@Getter
@Setter
@Entity
@Table(name = "role")
public class RoleEntity  {
    @Id
    @UuidGenerator(style = TIME)
    private String id;
    private String name;
    //!!!!!!this is point!!!!!!!!
    //!!!!!!this is point!!!!!!!!
    //!!!!!!this is point!!!!!!!!
    private List<String> permissions; 
}


@Getter
@Setter
@Entity
@Table(name = "employee_role")
public class EmployeeRoleEntity  {
    @Id
    @UuidGenerator(style = TIME)
    private String id;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private RoleEntity role;
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    private EmployeeEntity employee;
}

@Getter
@Setter
@Entity
@Table(name = "employee")
public class EmployeeEntity {
    @Id
    @UuidGenerator(style = TIME)
    private String id;
    private String name;
}

```

i have readonly query to find employe permissons.
it work well on quarkus 3.6.4, but not work on quarkus 3.6.5
i got error message:
```log
2024-01-28 00:55:14,713 ERROR [io.sma.gra.exe.err.ExceptionHandler] (vert.x-eventloop-thread-2) [,] SRGQL012000: Data Fetching Error: org.hibernate.exception.LockAcquisitionException: could not execute batch [Batch entry 0 update role set attributes='{}',created_at='2024-01-25 05:39:00.673998+00',created_by=NULL,description=NULL,name='所有功能',org_id=NULL,permissions=?,status='ENABLED',type='CUSTOM',updated_at='2024-01-27 16:55:14.481232+00',updated_by='all' where id='1' was aborted: ERROR: could not serialize access due to concurrent update  Call getNextException to see other errors in the batch.] [update role set attributes=?,created_at=?,created_by=?,description=?,name=?,org_id=?,permissions=?,status=?,type=?,updated_at=?,updated_by=? where id=?]
        at org.hibernate.exception.internal.SQLStateConversionDelegate.convert(SQLStateConversionDelegate.java:106)
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:56)
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:108)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:287)
        at org.hibernate.engine.jdbc.mutation.internal.PreparedStatementGroupSingleTable.forEachStatement(PreparedStatementGroupSingleTable.java:59)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.performExecution(BatchImpl.java:260)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.execute(BatchImpl.java:239)
        at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.executeBatch(JdbcCoordinatorImpl.java:188)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:664)
        at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:502)
        at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:364)
        at org.hibernate.event.internal.DefaultAutoFlushEventListener.onAutoFlush(DefaultAutoFlushEventListener.java:55)
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:127)
        at org.hibernate.internal.SessionImpl.autoFlushIfRequired(SessionImpl.java:1375)
        at org.hibernate.sql.exec.internal.JdbcSelectExecutorStandardImpl.scroll(JdbcSelectExecutorStandardImpl.java:115)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.lambda$new$1(ConcreteSqmSelectQueryPlan.java:136)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.withCacheableSqmInterpretation(ConcreteSqmSelectQueryPlan.java:303)
        at org.hibernate.query.sqm.internal.ConcreteSqmSelectQueryPlan.performScroll(ConcreteSqmSelectQueryPlan.java:252)
        at org.hibernate.query.sqm.internal.QuerySqmImpl.doScroll(QuerySqmImpl.java:629)
        at org.hibernate.query.spi.AbstractSelectionQuery.scroll(AbstractSelectionQuery.java:445)
        at org.hibernate.query.spi.AbstractSelectionQuery.stream(AbstractSelectionQuery.java:457)
        at org.hibernate.query.Query.getResultStream(Query.java:168)
        at io.quarkus.hibernate.orm.panache.common.runtime.CommonPanacheQueryImpl.stream(CommonPanacheQueryImpl.java:288)
        at io.quarkus.hibernate.orm.panache.runtime.PanacheQueryImpl.stream(PanacheQueryImpl.java:154)
        at hd.mia.core.security.domain.repositories.EmployeeRoleRepository.findByEmployeeIds(EmployeeRoleRepository.java:43)
        at hd.mia.core.security.domain.repositories.EmployeeRoleRepository_ClientProxy.findByEmployeeIds(Unknown Source)
        at hd.mia.core.security.domain.services.PermissionLoader.loadFixedEmployeeRoles(PermissionLoader.java:146)
        at hd.mia.core.security.domain.services.PermissionLoader.loadEmployeeRoles(PermissionLoader.java:138)
        at hd.mia.core.security.domain.services.PermissionLoader.doLoadByEmployee(PermissionLoader.java:109)
        at hd.mia.core.security.domain.services.PermissionLoader.loadByEmployee(PermissionLoader.java:83)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass.loadByEmployee$$superforward(Unknown Source)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass$$function$$2.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass.loadByEmployee(Unknown Source)
        at hd.mia.core.security.domain.services.PermissionLoader.loadEmployeeByUser(PermissionLoader.java:69)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass.loadEmployeeByUser$$superforward(Unknown Source)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass$$function$$4.apply(Unknown Source)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:73)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInCallerTx(TransactionalInterceptorBase.java:335)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:40)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at hd.mia.core.security.domain.services.PermissionLoader_Subclass.loadEmployeeByUser(Unknown Source)
        at hd.mia.core.security.domain.services.PermissionLoader_ClientProxy.loadEmployeeByUser(Unknown Source)
        at hd.mia.core.security.domain.services.user.UserCallerPermissions.loadOrgRaw(UserCallerPermissions.java:68)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at hd.mia.core.security.domain.services.user.UserCallerPermissions.raw(UserCallerPermissions.java:44)
        at hd.mia.core.security.domain.services.user.UserCallerPermissions.raw(UserCallerPermissions.java:36)
        at hd.mia.core.security.domain.services.caller.CallerIdentityRolesProviderImpl.get(CallerIdentityRolesProviderImpl.java:13)
        at hd.mia.core.security.domain.services.caller.CallerIdentityRolesProviderImpl_ClientProxy.get(Unknown Source)
        at com.qwlabs.security.CallerIdentityAugmentor.lambda$buildSecurityIdentity$1(CallerIdentityAugmentor.java:52)
        at com.qwlabs.security.LazyRolesSecurityIdentity.loadFinalRoles(LazyRolesSecurityIdentity.java:37)
        at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:181)
        at com.qwlabs.security.LazyRolesSecurityIdentity.getRoles(LazyRolesSecurityIdentity.java:66)
        at com.qwlabs.security.LazyRolesSecurityIdentity.hasRole(LazyRolesSecurityIdentity.java:71)
        at io.quarkus.security.runtime.interceptor.check.RolesAllowedCheck.doApply(RolesAllowedCheck.java:65)
        at io.quarkus.security.runtime.interceptor.check.RolesAllowedCheck.apply(RolesAllowedCheck.java:55)
        at io.quarkus.security.runtime.interceptor.SecurityConstrainer.check(SecurityConstrainer.java:34)
        at io.quarkus.security.runtime.interceptor.SecurityHandler.handle(SecurityHandler.java:46)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor.intercept(RolesAllowedInterceptor.java:29)
        at io.quarkus.security.runtime.interceptor.RolesAllowedInterceptor_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:70)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:62)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:136)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.invokeInOurTx(TransactionalInterceptorBase.java:107)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.doIntercept(TransactionalInterceptorRequired.java:38)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorBase.intercept(TransactionalInterceptorBase.java:61)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired.intercept(TransactionalInterceptorRequired.java:32)
        at io.quarkus.narayana.jta.runtime.interceptor.TransactionalInterceptorRequired_Bean.intercept(Unknown Source)
        at io.quarkus.arc.impl.InterceptorInvocation.invoke(InterceptorInvocation.java:42)
        at io.quarkus.arc.impl.AroundInvokeInvocationContext.perform(AroundInvokeInvocationContext.java:30)
        at io.quarkus.arc.impl.InvocationContexts.performAroundInvoke(InvocationContexts.java:27)
        at hd.mia.graphql.FailureGraphQLApi_Subclass.failureTags(Unknown Source)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at io.smallrye.graphql.execution.datafetcher.helper.ReflectionInvoker.invoke(ReflectionInvoker.java:97)
        at io.quarkus.smallrye.graphql.runtime.spi.datafetcher.QuarkusDefaultDataFetcher.lambda$invokeAndTransformBlocking$0(QuarkusDefaultDataFetcher.java:84)
        at io.smallrye.context.impl.wrappers.SlowContextualCallable.call(SlowContextualCallable.java:21)
        at io.vertx.core.impl.ContextBase.lambda$executeBlocking$0(ContextBase.java:167)
        at io.vertx.core.impl.ContextInternal.dispatch(ContextInternal.java:277)
        at io.vertx.core.impl.ContextBase.lambda$internalExecuteBlocking$2(ContextBase.java:199)
        at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update role set attributes='{}',created_at='2024-01-25 05:39:00.673998+00',created_by=NULL,description=NULL,name='所有功能',org_id=NULL,permissions=?,status='ENABLED',type='CUSTOM',updated_at='2024-01-27 16:55:14.481232+00',updated_by='all' where id='1' was aborted: ERROR: could not serialize access due to concurrent update  Call getNextException to see other errors in the batch.
        at org.postgresql.jdbc.BatchResultHandler.handleError(BatchResultHandler.java:165)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2402)
        at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:574)
        at org.postgresql.jdbc.PgStatement.internalExecuteBatch(PgStatement.java:896)
        at org.postgresql.jdbc.PgStatement.executeBatch(PgStatement.java:919)
        at org.postgresql.jdbc.PgPreparedStatement.executeBatch(PgPreparedStatement.java:1685)
        at io.agroal.pool.wrapper.StatementWrapper.executeBatch(StatementWrapper.java:355)
        at org.hibernate.engine.jdbc.batch.internal.BatchImpl.lambda$performExecution$2(BatchImpl.java:273)
        ... 100 more
Caused by: org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
        at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2713)
        at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2401)
        ... 106 more
```

i fond a lot of update role query in logs, like this
```log
Hibernate:
    update
        role
    set
        attributes=?,
        created_at=?,
        created_by=?,
        description=?,
        name=?,
        org_id=?,
        permissions=?,
        status=?,
        type=?,
        updated_at=?,
        updated_by=?
    where
        id=?
2024-01-28 00:55:14,697 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [1] as [JSON] - [hd.mia.core.security.domain.models.RoleAttributes@6478f49a]
2024-01-28 00:55:14,697 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [2] as [TIMESTAMP_UTC] - [2024-01-25T05:39:00.647153Z]
2024-01-28 00:55:14,697 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [3] as [VARCHAR] - [null]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [4] as [VARCHAR] - [null]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [5] as [VARCHAR] - [分析人员]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [6] as [VARCHAR] - [null]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [7] as [ARRAY] - [[FAILURE:ANALYZE:ANALYZER_ADMIN, FAILURE:FAILURE_DATA_SOURCE:VIEW, FAILURE:FAILURE:ANALYZE, FAILURE:FAILURE:VIEW, DASHBOARD:DASHBOARD:EDIT]]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [8] as [VARCHAR] - [ENABLED]
2024-01-28 00:55:14,698 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [9] as [VARCHAR] - [INTERNAL]
2024-01-28 00:55:14,699 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [10] as [TIMESTAMP_UTC] - [2024-01-27T16:55:14.679341Z]
2024-01-28 00:55:14,699 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [11] as [VARCHAR] - [all]
     2024-01-28 00:55:14,699 TRACE [org.hib.typ.des.JdbcBindingLogging] (vert.x-worker-thread-3) [,] binding parameter [12] as [VARCHAR] - [8e46fcfa-9564-4344-9dfb-16c7dea204a3]
```

i found some patterns, i think this is hibernate 6.2.14.Final issue
- use permission field,  quarkus 3.6.4, work well
- use permission field,  quarkus 3.6.5, not work
- remove permission field,  quarkus 3.6.5, work well
- use permission field,  quarkus 3.6.4, hibernate 6.2.13.Final, work well
- use permission field,  quarkus 3.6.4, hibernate 6.2.14.Final, not work
- remove permission field,  quarkus 3.6.4, hibernate 6.2.14.Final, work well

### Output of `uname -a` or `ver`

22.5.0 Darwin Kernel Version 22.5.0

### Output of `java -version`

Oracle GraalVM 21.0.1+12.1

### Quarkus version or git rev

3.6.5~3.6.7

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.5

**Comment by pipinet** [comment] 2024-01-28 03:50
3.6.8 same issue

**Comment by yrodiere** [comment] 2024-01-29 09:07
Can you please provide a minimal reproducer, i.e. a small project using Quarkus and whose tests fail because of this?
Preferably one not using lombok, so that we can more easily debug it.

**Comment by pipinet** [comment] 2024-02-02 17:04
@yrodiere https://github.com/pipinet/hibernate-update

**Comment by yrodiere** [comment] 2024-02-05 08:00
@pipinet Thanks for the reproducer.

Basically, in your example, you do this:

```
    @JdbcTypeCode(SqlTypes.JSON)
    private RoleAttributes attributes;
```

And define `RolesAttributes` like this:

```
public class RoleAttributes {
    private String code;

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }
}

```


The thing is, in order to know whether it needs to send an `update` statement to the database Hibernate ORM needs to determine whether data changed -- that's called dirty-checking.
In your case, there's no bytecode enhancement on `RolesAttribute` (because it's not an `@Embeddable` or anything, so Hibernate ORM will rely on snapshot:

* Upon loading, it performs a deep copy of `RolesAttributes` in a new instance
* Upon dirty-checking, it will compare the entity's `RoleAttributes` with its snapshot using `equals`.

And in your case, `RolesAttributes` doesn't define an `equals` method, so I suspect `current.equals(snapshots)` always returns `false`, marking the entity as dirty and triggering a snapshot.

You can fix this using any of the following tricks (I tried them):

1. Define equals/hashcode in `RolesAttributes`
2. Make `RolesAttributes` a `record`.

Now, there are indeed a couple of questions:

1. Is this related to the Quarkus integration in any way? Some specific setup triggering this behavior?
2. Couldn't dirty-checking comparison apply to the JSON rather than the object, at least when the `RolesAttributes` class doesn't define `equals`? This certainly couldn't address all problems (I'm thinking of ordering in JSON arrays in particular), but it could address the simpler ones.
3. Shouldn't Hibernate ORM produce at least a warning on startup when this situation arises?
4. Shouldn't this be documented somewhere? I couldn't find anything in the Hibernate ORM docs. Worse, a section [here](https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#_struct_aggregate_embeddable_mapping says "It is not necessary to switch to Java records", taking about order of attributes, and shows examples of classes that do not define equals/hashcode, completely glossing over the implications in terms of dirty checking.

Let's ask @beikov for his opinion.

I'll mark this as an upstream bug in the meantime, because I suspect the answer to my first question is "no, this is not specific to Quarkus".

**Comment by beikov** [comment] 2024-02-05 11:57
Hibernate ORM has no way of knowing how to "copy" `RolesAttribute` and also doesn't know if it is mutable or immutable, so it defaults to always assume mutable and hence determines an object is always dirty.

You can tell Hibernate ORM about how to do copying by specifying a `MutabilityPlan` via e.g. `@org.hibernate.annotations.Mutability(MyMutabilityPlan.class)`. For `record` classes Hibernate ORM assumes that the data structure itself is immutable, so only the replacement of the object as a whole would be detected as dirty.

Defining just `equals`/`hashCode` won't help. There is one change [HHH-17294](https://hibernate.atlassian.net/browse/HHH-17294) that affects how this special case is treated, which was fixed in ORM 6.2.14.

You have a few options:

* Use `record` classes
* Mark it as `implements Serializable` and Hibernate ORM will use Serialization/Deserialization for copying
* Implement a custom `MutabilityPlan` to be in charge of the copying yourself

>Couldn't dirty-checking comparison apply to the JSON rather than the object, at least when the RolesAttributes class doesn't define equals? This certainly couldn't address all problems (I'm thinking of ordering in JSON arrays in particular), but it could address the simpler ones.

I have thought about this one in the past, but last time I looked into this, it couldn't figure out a clean way to do it. I created https://hibernate.atlassian.net/browse/HHH-17709 for this.

>Shouldn't Hibernate ORM produce at least a warning, perhaps even an error, on startup when this situation arises?

I don't know. Please start a discussion about this in the #hibernate-dev Zulip channel. For `@Immutable` entities it would be totally reasonable to potentially not have a proper `MutabilityPlan`.

>Shouldn't this be documented somewhere? I couldn't find anything in the Hibernate ORM docs. Worse, a section [here](https://docs.jboss.org/hibernate/orm/6.4/userguide/html_single/Hibernate_User_Guide.html#_struct_aggregate_embeddable_mapping) says "It is not necessary to switch to Java records", taking about order of attributes, and shows examples of classes that do not define equals/hashcode, completely glossing over the implications in terms of dirty checking.

Aggregate embeddables are not the same as JSON/XML basic mappings (this example). An embeddable is something that Hibernate ORM knows about deeply, whereas the detail knowledge for basic mappings stops at the Java type.

I guess that depending on the discussion about WARN/ERROR above, we can create documentation for this as part of an enhancement request.

**Comment by yrodiere** [comment] 2024-02-05 12:08
> Hibernate ORM has no way of knowing how to "copy" RolesAttribute

FWIW in my tests Hibernate ORM did copy RolesAttribute for, creating new snapshots using the default constructor. I do not know if it called setters, but I suspect it did, considering the information below.

> Defining just equals/hashCode won't help. There is one change [HHH-17294](https://hibernate.atlassian.net/browse/HHH-17294) that affects how this special case is treated, which was fixed in ORM 6.2.14.

I'm sorry but it does in the reproducer... https://github.com/pipinet/hibernate-update/pull/1

> I have thought about this one in the past, but last time I looked into this, it couldn't figure out a clean way to do it. I created https://hibernate.atlassian.net/browse/HHH-17709 for this.

Thanks!

> I don't know. Please start a discussion about this in the #hibernate-dev Zulip channel. For @Immutable entities it would be totally reasonable to potentially not have a proper MutabilityPlan.

Done: https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/Always-dirty.20properties

> Aggregate embeddables are not the same as JSON/XML basic mappings (this example). An embeddable is something that Hibernate ORM knows about deeply, whereas the detail knowledge for basic mappings stops at the Java type.

Right, sorry, I missed the `@Embeddable` annotations.

**Comment by pipinet** [comment] 2024-02-14 02:32
@yrodiere Thanks, so i need add equals and hashCode to RoleAttributes, right?

**Comment by yrodiere** [comment] 2024-02-14 08:11
My tests show this solves your problem, yes. But then @beikov disagrees, so I'll let him explain :shrug:

**Comment by beikov** [comment] 2024-02-15 08:26
I can only quote myself:

>You have a few options:
>
> * Use record classes
> * Mark it as `implements Serializable` and Hibernate ORM will use Serialization/Deserialization for copying
> * Implement a custom `MutabilityPlan` to be in charge of the copying yourself

Just implementing `equals`/`hashCode` should not work, because then Hibernate ORM will choose the `MutableMutabilityPlan.INSTANCE` which always assumes a field is dirty, since that mutability plan has no copying mechanism.

**Comment by yrodiere** [comment] 2024-02-19 08:41
> Just implementing equals/hashCode should not work

But it does. I don't know what to say if [a reproducer](https://github.com/quarkusio/quarkus/issues/38438#issuecomment-1926412250) is not a strong enough argument.

Anyway. I think you have your official answer @pipinet : it's not supposed to work currently unless you use records. See https://hibernate.atlassian.net/browse/HHH-17709 to track improvements in this area.

I'll close this since it's not a bug (at most a missing feature) and not related to Quarkus. Let's continue the discussion on https://hibernate.atlassian.net/browse/HHH-17709 if necessary.

**Closed by yrodiere** 2024-02-19 08:41 UTC
Labels: kind/bug, area/persistence, triage/upstream, area/hibernate-orm
