### ISSUE TITLE
Exceptions of @ObservesAsync methods are not logged

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#11525] opened 2020-08-21 13:28 UTC
**Describe the bug**
I have an `@ObservesAsync` observer method.
If it throws an exception, it is not logged anywhere.

I have no special logging configuration in this project.

**Expected behavior**
I see all exceptions in the log if not otherwise specified.

**Actual behavior**
The exception is not logged.

**To Reproduce**
1. Download the reproducer
2. mvn clean compile quarkus:dev
3. Go to localhost:8080/hello
4. The async observer is invoked. "observeAsync" is logged. However, the exception I throw is not logged.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys 
 - Quarkus version or git rev: 1.7.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: C:\eclipse\tools\apache-maven\bin\..
Java version: 11.0.7, vendor: Azul Systems, Inc., runtime: C:\eclipse\tools\zulu11.39.15-ca-jdk11.0.7-win_x64
Default locale: de_DE, platform encoding: Cp1252
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment] 2020-08-24 11:11
This behavior is intentional and defined by the spec: https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#observer_notification and https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#async_exception

If an exception is thrown in any async observer the returned `CompletionStage` is completed exceptionally with `java.util.concurrent.CompletionException` and the exceptions thrown can be obtained via the `getSuppressed()` method.

**Comment by manovotn** [comment] 2020-08-24 12:58
I can confirm this is intentional and per-spec behavior.
Closing issue as it is not a bug.

**Closed by manovotn** 2020-08-24 12:58 UTC
Labels: area/arc, kind/bug

**Comment by knutwannheden** [comment] 2020-09-01 01:46
Coincidentally we stumbled across this same "problem" a few days ago. Only in our case the observer was asynchronous **and** transactional. The spec isn't clear about this corner case.

**Comment by mkouba** [comment] 2020-09-01 06:26
> Coincidentally we stumbled across this same "problem" a few days ago. Only in our case the observer was asynchronous and transactional. The spec isn't clear about this corner case.

Transactional observers are inherently asynchronous (called using a JTA `Synchronization`) and the spec is clear that _"Observer methods may throw exceptions. If the observer method is a transactional observer method, any exception is caught and logged by the container."_. It seems that our code swallows and logs errors. @knutwannheden Could you describe your use case more thoroughly?

**Comment by knutwannheden** [comment] 2020-09-01 06:51
In essence we have an `@Scheduled`-annotated method which reads from a queue table in a database and then fires CDI events corresponding to the queue entries. These CDI events are then "consumed" by an observer method which is annotated with `@Transactional(REQUIRES_NEW)` and `@ObservesAsync` on the parameter corresponding to the CDI event. The observer method will run some "command" and then if all went well delete the queue entry in the database queue table. Any exceptions thrown should of course get reported.

**Comment by knutwannheden** [comment] 2020-09-09 01:34
@mkouba Based on my use case, do you consider anything needs to be done here? Should I report an issue?

**Comment by mkouba** [comment] 2020-09-09 06:36
> Based on my use case, do you consider anything needs to be done here? Should I report an issue?

@knutwannheden Nope, you should check the returned `CompletionStage` and log all exceptions returned from `CompletionException#getSuppressed()`.
