### ISSUE TITLE
NPE in QuarkusTestExtension after exception in `QuarkusTestResourceLifecycleManager.start()`

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#33371] opened 2023-05-15 10:07 UTC
### Describe the bug

By mistake, I had caused an exception in the `start` method of my custom `MariaDBContainerQuarkusLifecycleManager`.

That exception is printed just as expected, but after some skipped QuarkusTests the following exception pops up:

```
java.lang.NullPointerException: Cannot invoke "io.quarkus.bootstrap.app.RunningQuarkusApplication.getClassLoader()" because "io.quarkus.test.junit.QuarkusTestExtension.runningQuarkusApplication" is null
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:901)
	at io.quarkus.test.junit.QuarkusTestExtension.runExtensionMethod(QuarkusTestExtension.java:893)
	at io.quarkus.test.junit.QuarkusTestExtension.interceptAfterAllMethod(QuarkusTestExtension.java:887)
        [...]
	Suppressed: org.opentest4j.TestAbortedException: Boot failed
		at io.quarkus.test.junit.QuarkusTestExtension.throwBootFailureException(QuarkusTestExtension.java:627)
		at io.quarkus.test.junit.QuarkusTestExtension.interceptBeforeAllMethod(QuarkusTestExtension.java:680)
		at org.junit.jupiter.engine.execution.InterceptingExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(InterceptingExecutableInvoker.java:103)
```
That NPE is a bit misleading and shouldn't be there.

### Expected behavior

No NPE

### Actual behavior

NPE as described above

### Quarkus version or git rev

2.16.7.Final

**Comment by famod** [comment] 2023-06-16 16:51
That NPE still pops up in 3.1.2.Final, reopening...

**Comment by gunnarmorling** [comment] 2023-07-29 11:12
Running into the same issue with 3.2.2.Final.

**Comment by geoand** [comment] 2023-07-29 11:14
Same issue? Just throwing an exception in a test resource causes the NPE?

**Comment by gunnarmorling** [comment] 2023-07-29 11:23
Hey @geoand! Wow, what a quick response, on a Saturday nonetheless! So I'm getting the exact same NPE as above, which as I understand is only a follow-up issue to another error. The root cause in my case is this:

```
[ERROR]   ApplyCommandTest » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
	[error]: Build step io.quarkus.arc.deployment.BeanArchiveProcessor#build threw an exception: java.lang.IllegalStateException: Failed to index: KafkaConnectResponseExceptionMapper
	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:157)
	at io.quarkus.arc.deployment.BeanArchiveProcessor.build(BeanArchiveProcessor.java:94)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:578)
	at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:864)
	at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
	at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
	at java.base/java.lang.Thread.run(Thread.java:1623)
	at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalArgumentException: stream cannot be null
	at org.jboss.jandex.Indexer.indexWithSummary(Indexer.java:2476)
	at io.quarkus.deployment.index.IndexingUtil.indexClass(IndexingUtil.java:152)
	... 10 more
```

I've seen other reports for that (https://github.com/quarkusio/quarkus/issues/14348) and you seemed to have it closed in 2021, but somehow it still seems to be a problem. Intermittently, that is. Here's the commit in kcctl which triggers it in some situations.

**Comment by geoand** [comment] 2023-07-29 11:27
Hey @gunnarmorling 👋

I'll try again to reproduce this next week. 
I think I had tried and failed in the past, but it's definitely worth another shot

**Comment by gunnarmorling** [comment] 2023-07-29 11:30
Yeah, it seems to happen really rarely though. It actually only happened once, since then I couldn't reproduce it. I'll let you know when I run into it again.

**Comment by geoand** [comment] 2023-07-29 11:31
👌

**Comment by geoand** [comment] 2023-07-31 06:32
I couldn't reproduce this unfortunately...

**Comment by gunnarmorling** [comment] 2023-07-31 08:26
Me neither. Some rather rare race condition perhaps?

**Comment by geoand** [comment] 2023-07-31 08:27
Very likely... 😭

**Comment by famod** [comment] 2023-08-08 17:15
I can reproduce it all the time, but there is more to it than running just a single test class.
Instead you seem to need at least one other testclass with a `@TestProfile` that is running _after_ the initial QuarkusTest that triggered some exception in the manager.
Also, this is how we activate our MariaDB manager per Maven module:
```java
/**
 * {@link QuarkusTestResource QuarkusTestResources} for this module.
 * <p/>
 * This cannot be shared via test-jar because test resources are not picked up from other modules (by design). Subclassing wouldn't work either, see
 * https://github.com/quarkusio/quarkus/issues/10299.
 *
 * @author fmo
 */
@QuarkusTestResource(value = MariaDBContainerQuarkusLifecycleManager.class, parallel = true)
public class ModuleWideQuarkusTestResources {
}
```

**Comment by geoand** [comment] 2023-08-21 06:30
@famod any chance you can attach a small sample that behaves as you mention?

Thanks

**Comment by famod** [comment] 2023-08-21 09:57
@geoand sure, if the god of time is blessing me 😉

**Comment by geoand** [comment] 2024-04-17 06:04
Let's close this for the time being and we can reopen if more information becomes available

**Closed by geoand** 2024-04-17 06:04 UTC
Labels: kind/bug, area/user-experience, area/testing, triage/needs-reproducer
